### ISSUE TITLE
freeradius using default certificates

### ISSUE THREAD

**Issue by poggenpower** [opnsense/plugins#1004]
Have configured the freeradius plugin to use eap-ttls. 
Have choosen a root and a server certificate from the internal Ca, but when my clients connect they get default certificate with freeradius attributes. See screenshot. 
![screenshot 2018-11-20 at 00 45 40](https://user-images.githubusercontent.com/6035034/48742091-be159800-ec5d-11e8-8d62-3d6826fb9853.png)
found all files in /usr/loacl/etc/raddb/certs were generated at install time from the freeradius plugin.
found the that usr/loacl/etc/raddb/mods-enabled/eap contains pointers to the files in the cert directory and it was also generated at install time. 
If I add/change useres or clients they get updated correct. What could be the issue here?

freeradius plugin version: 1.8.2
opnsense 18.7.7

Thanks for support
  Thomas

**Comment by poggenpower** [comment]
Found that " Validate Certificates" need to be set, that all settings get in place. 
Found also that usr/loacl/etc/raddb/mods-enabled/eap is a symlink and therefor the timestamp didn't changed.

**Comment by poggenpower** [comment]
I think I have found the issue. Not every change triggers a recreation of the config. e.g. adding a user won't.
After tiggering a reconfig via API, the users are there.

**Comment by poggenpower** [comment]
Found the apply button in below the users list.
Sorry for confusion, this generates the users file.

**Comment by mimugmail** [comment]
This is a major difference between legacy code and MVC. 
To be honest, best is to not forget to Save/Apply stuff in the UI. When having 0-5 user the Apply button should be clearly visible .. perhaps you just forgot to apply?
