### ISSUE TITLE
Feature Request: New Features on BGP

### ISSUE THREAD

**Issue by elizandropacheco** [opnsense/plugins#1005]
It would be interesting, to make the bgp module even more functional, to add the commands to the neighbors:

show ip bgp neighbor - To view detailed neighbor statistics.
show ip bgp community - To see details about a specific commnity.

show ip bgp neighbor [IP] advertised-routes - To see in fact which routes we are exporting to the neighbor.

And "if" soft-reconfiguration inbound option is enabled, enable the functions:

show ip bgp neighbor [IP] received-routes - To view received routes

AND

clear ip bgp * soft in - To update the table of received routes without overturning the neighbor.

Fundamental options also, regardless of the above configuration are:

clear ip bgp [IP] - To reset the session with the neighbor.
clear ip bgp * soft out - to update the table of routes sent without overturning the neighbor.

And also important parameters:

neighbor peer ebgp-multihop - To allow configuration of bgp sessions where the neighbor is not directly connected.

neighbor peer update-source - To determine the IP of updates when there is more than one in the interface.

Tkz

**Comment by mimugmail** [comment]
Can you give concrete config snippets for all? Commands are bit tricky as every save would restart the whole daemon. I can try some after 19.1

**Comment by elizandropacheco** [comment]
clear ip bgp [NEIGHBOR-IP] Reload only a session with neighbor, not daemon.

**Comment by elizandropacheco** [comment]
Basically, when you use the clear command along with the neighbor ip, it performs a reload only of the session with the neighbor. This is critical to restarting the connection with only one without the need to knock down all (as would happen if you restart the daemon).


On the other hand, when soft reconfiguration is enabled on the neighbor, it is even possible to make route changes (see input and modify output) without even overturning the session with the specific neighbor.

So there are two levels.

The first is to allow the clearing of one neighbor without affecting the others (giving only reload in the session with the neighbor itself).

The second is when the soft reconfiguration is enabled, it can change mainly route announcements, without even overturning the session with the neighbor.

http://topics-cdn.dell.com/s4820t_9.7.0.0_config_pub-v1-temp/en-us/GUID-F38C3042-7672-42BA-ADC1-4DEDF4830F74.html

**Comment by mimugmail** [comment]
@elizandropacheco I know how soft reconfig works as I'm coming from Quagga CLI (Linux). 
What I tried to explain was, OPNsense generates a config from UI and to read it the service has to be restarted. So when you add a prefix-list the daemon get's restarted. There is no API thing which would communicate to the FRR via vtysh to configure it. 

It shouldn't be hard to add some buttons to Diagnostics so you can do a softly clear, but you have to keep in mind, when adding a new peer, you daemon gets restarted (stop&start). That's how *sense work.

**Comment by elizandropacheco** [comment]
I understand, opnsense only works by managing the configuration file. In high-availability environments this may be a problem, perhaps an alternative such as running a diff of the file generated with the old one and run via console solved the problem. But still, it is very useful for some scenarios that I attend (usually regional internet providers, very common in Brazil).

In this case, the reset options of only one neighbor would be made as? Is it a specific command and does it depend on changing the configuration file?

**Comment by mimugmail** [comment]
Any command not touching the config can be used, mostly `clear XXX` 
Everything else has to be templated and requires a restart.

As always .. you also can install OPNsense and don't use os-frr plugin but plain frr and configure as usual via CLI. Runs perfectly ...

**Comment by elizandropacheco** [comment]
No doubt! I thank you for your attention. About this question of not using the frontend, how would I do exactly?

I ask only out of curiosity, because the frontend is fundamental so that people who do not know the cli can at least perform basic tasks. Already very good, if we can add the clear to the neighbor will be great progress!

Once again, I apologize for anything and appreciate the attention.

**Comment by mimugmail** [comment]
You dont have to apologize for anything :) 

We can't build anything into the UI but some ppl need more so they just install frr:

pkg install frr

Then you add a file:

/etc/rc.conf.d/frr:
frr_enable="YES"
frr_daemons="zebra bgpd"

And start with /usr/local/etc/rc.d/frr

Then you can just use it like within linux, just type vtysh and you are in, save you stuff an so on.

The UI will never touch this unless you install the plugin os-frr or os-quagga.

Only downsice is that the config is not saved within the config.xml for backup/restore, but I you backup text files you can easily restore again.

**Comment by elizandropacheco** [comment]
Thank you very much for the guidance, I am available if you need anything or a test.

**Comment by tfluehmann** [comment]
@mimugmail I tried to install frr manually as you described above since I need to set some settings for bgp which the plugin does not offer or in my case overwrites them when I set them in the config file by hand. Is it still possible to install frr manually or is it an oudated recommendation?
I received the following message when I tried to install it on opnsense 20.7.4:
```
# pkg install frr
Updating OPNsense repository catalogue...
pkg: https://opnsense-mirror.hiho.ch/FreeBSD:12:amd64/20.7/latest/meta.txz: No route to host
repository OPNsense has no meta file, using default settings
OPNsense repository is up to date.
All repositories are up to date.
pkg: No packages available to install matching 'frr' have been found in the repositories
```

**Comment by fichtner** [comment]
it's "frr7"

**Comment by mimugmail** [comment]
Which Features do you miss? Currently there is an open PR about community lists, I can add some more too

**Comment by tfluehmann** [comment]
I am not completely sure so far. I try to connect the opnsense with a ipsec vpn to the google cloud with google cloud vpn ha setup. Therefore I need frr to run bgp on top. For about two days it worked like a charm, but then google probably reset the bgp session on their side, which can happen and bgpd crashed and did not restore probperly. Therefore I want to install frr directly to have more debugging options.
Additionally I found a tutorial how to create the vpn between cloud vpn and a cisco router. In there the keepalive and holdtime is configured, therefore I would like to try that as well. As well as the graceful-restart option.

Here the logs I have (probably you do have another idea what could be wrong): 
os-frr:
```
03.11.2020    14:07:12    ZEBRA    client 20 says hello and bids fair to announce only bgp routes vrf=0
03.11.2020    14:07:12    ZEBRA    client 23 says hello and bids fair to announce only vnc routes vrf=0
03.11.2020    14:07:15    BGP    bgp_update_receive: rcvd End-of-RIB for IPv4 Unicast from 169.254.2.1 in vrf default
03.11.2020    14:46:55    BGP    bgp_update_receive: rcvd End-of-RIB for IPv4 Unicast from 169.254.2.1 in vrf default
04.11.2020    22:36:52    BGP    [EC 33554454] 169.254.2.1 [Error] bgp_read_packet error: Connection reset by peer
04.11.2020    22:36:53    ZEBRA    [EC 100663303] kernel_rtm: 10.22.0.0/20: rtm_write() unexpectedly returned -4 for command RTM_DELETE
04.11.2020    22:36:53    ZEBRA    [EC 100663303] kernel_rtm: 10.22.16.0/20: rtm_write() unexpectedly returned -4 for command RTM_DELETE
04.11.2020    22:36:53    ZEBRA    [EC 100663303] kernel_rtm: 10.22.32.0/20: rtm_write() unexpectedly returned -4 for command RTM_DELETE 
```

Google Cloud VPN Router: 
```
 2020-11-04 22:36:51.380 CET Router Event: Router task activated
 Info  2020-11-04 22:36:51.387 CET Interface Created: if-ha-0 (169.254.2.1)
 Notice  2020-11-04 22:36:51.616 CET BGP Event: Successfully added configuration for peers: 169.254.2.2
 Info  2020-11-04 22:36:51.633 CET BGP Event: BGP Router ID set to: 169.254.2.1
 Info  2020-11-04 22:36:51.638 CET Route Event: Advertising Prefix 10.22.0.0/20, priority 100 to peers.
 Info  2020-11-04 22:36:51.639 CET Route Event: Advertising Prefix 10.22.16.0/20, priority 100 to peers.
 Info  2020-11-04 22:36:51.639 CET Route Event: Advertising Prefix 10.22.32.0/20, priority 100 to peers.
 Info  2020-11-04 22:36:51.720 CET Interface Deleted: if-ha-0 (169.254.2.1)
 Info  2020-11-04 22:36:52.963 CET Route Event: Advertising Prefix 10.22.0.0/20, priority 100 to peers.
 Info  2020-11-04 22:36:52.963 CET Route Event: Advertising Prefix 10.22.16.0/20, priority 100 to peers.
 Info  2020-11-04 22:36:52.963 CET Route Event: Advertising Prefix 10.22.32.0/20, priority 100 to peers.
```

**Comment by mimugmail** [comment]
No idea, did you try to restart VPN first?

**Comment by tfluehmann** [comment]
I did so, but the VPN was always up. Only the BGP session went down and did not came up again on its own.

**Comment by tfluehmann** [comment]
@mimugmail I have some good news regarding the issue I had with connecting the google cloud-vpn to the opnsense/frr.
I installed frr natively and configured it with debugging enabled, graceful_restart and the correct timers. We had one restart yesterday which led to a downtime of less than a minute which is good. Frr restarted the session correctly, which it did not before.
Here my configuration:

```
frr version 7.4
frr defaults traditional
!
hostname opnsense.localdomain
log file /var/log/frr.log
!
debug bgp keepalives
debug bgp neighbor-events
debug bgp update-groups
debug bgp updates in
debug bgp updates out
debug bgp zebra
!
router bgp 64516
 bgp router-id 169.254.2.2
 no bgp ebgp-requires-policy
 bgp graceful-restart
 neighbor 169.254.2.1 remote-as 64515
 neighbor 169.254.2.1 update-source enc0
 neighbor 169.254.2.1 timers 20 60
 !
 address-family ipv4 unicast
  network 10.10.0.0/24
  redistribute connected
  redistribute static
  neighbor 169.254.2.1 next-hop-self
 exit-address-family
 !
 address-family ipv6 unicast
  redistribute connected
 exit-address-family
!
line vty
!
```
It would be nice to configure the graceful_restart option, the timers and trigger the debug options through the UI from my point of view. Would be great if you could add those to your PR.

**Comment by mimugmail** [comment]
Sure, looks easy

**Comment by marcquark** [comment]
this should now be resolved via https://github.com/opnsense/plugins/pull/2112

**Comment by ZaphodB** [comment]
@2112 does not address soft-reconfiguration inbound

**Comment by mimugmail** [comment]
No, this wont work how OPNsense templates configurations. There is a python script to reload changes but its not really stable. Bgp will always hard reset when applying changes
