### ISSUE TITLE
PPPoE Server Problem

### ISSUE THREAD

**Issue by msnzare** [opnsense/plugins#1007]
I have problem with PPPoE Server on opnsense
     OPNSense version: 18.7.7
     os-pppoe Plugin version: 1.7_2
PPPoE server is configured as follows:
![image](https://user-images.githubusercontent.com/10445955/48822315-dd054e80-ed71-11e8-999a-8ef1b9c9d3d5.png)
I have also added “any to any” ipv4 rules in Firewall rules (WAN & PPPoE)
When I want to connect OPNSense using PPPoE client (in windows 7) there is an error (following image) and There is no PPPoE Logins log in opnsense.
![image](https://user-images.githubusercontent.com/10445955/48822326-e42c5c80-ed71-11e8-952e-da0f70776d5a.png)
The PPPoE client security profile is as follow:
![image](https://user-images.githubusercontent.com/10445955/48822330-eabad400-ed71-11e8-8570-f5bd0ed4c566.png)
Thanks for support.

**Comment by msnzare** [comment]
> 
> 
> I have no idea of this plugin, but at first I'd start to check if:
> 
>     * daemon is running
> 
>     * packets arriving at WAN interface
> 
>     * something to see in filter.log
> 
>     * any other logs available?
> 
> 
> Did your setup successfully run on any other version like 18.1?

I've checked:
Daemon is running
Packets arriving at wan interface
and there is not special log available
Is there any idea?
Thanks.

**Comment by mimugmail** [comment]
Do you see packets also replied?
I'd check system.log, ppps.log, or better everything in /var/log :)

**Comment by msnzare** [comment]
> g, pp

I've checked as following:
The firewall has globally been disabled,

**Dump PPPoE Discovery packets:**
root@OPNsense:~ # tcpdump -i igb0 pppoed
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on igb0, link-type EN10MB (Ethernet), capture size 262144 bytes
07:32:49.821187 PPPoE PADI [Service-Name] [Host-Uniq 0x0E000000000000000E000000]
07:32:54.823256 PPPoE PADI [Service-Name] [Host-Uniq 0x0E000000000000000E000000]
07:32:59.825883 PPPoE PADI [Service-Name] [Host-Uniq 0x0E000000000000000E000000]
07:33:04.828672 PPPoE PADI [Service-Name] [Host-Uniq 0x0E000000000000000E000000]
^C
4 packets captured
287 packets received by filter
0 packets dropped by kernel
root@OPNsense:~ # 

**Dump PPPoE Session packets:**
root@OPNsense:~ # tcpdump -i igb0 pppoes
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on igb0, link-type EN10MB (Ethernet), capture size 262144 bytes
^C
0 packets captured
207 packets received by filter
0 packets dropped by kernel
root@OPNsense:~ # 


**poes.log file:**
ov 27 06:54:12 OPNsense poes: caught fatal signal TERM
Nov 27 06:54:14 OPNsense poes: [B] Bundle: Shutdown
Nov 27 06:54:14 OPNsense poes: [L] Link: Shutdown
Nov 27 06:54:14 OPNsense poes: PPPoE: stop waiting for connection on igb0:, service "pppoe1"
Nov 27 06:54:14 OPNsense poes: process 54912 terminated
Nov 27 06:54:23 OPNsense poes: Multi-link PPP daemon for FreeBSD
Nov 27 06:54:23 OPNsense poes:  
Nov 27 06:54:23 OPNsense poes: process 74143 started, version 5.8 (root@opn-build-amd64-1 23:48 27-Jul-2018)
Nov 27 06:54:23 OPNsense poes: PPPoE: waiting for connection on igb0:, service "pppoe1"

Actually PPPoE Discovery packets are sent to OPNsense but there is no reply from it.

Thanks for support.

**Comment by mcellos** [comment]
not resolved? i am have the same problem!

**Comment by polumish** [comment]
I have this problem too. Issue -  set correct service name on client side. From our log - service name is "pppoe1". After I set this name on client side, all worked correctly.
Other question - where we can rename service name on server side?

**Comment by tuyenld** [comment]
I have a work around solution. You need to comment out the line
```bash
vi /usr/local/etc/inc/plugins.inc.d/if_pppoe.inc
//set pppoe service pppoe{$pppoecfg['pppoeid']}
```
According to[ mpd man page](http://mpd.sourceforge.net/doc5/mpd49.html):
```
set pppoe service service-name
Sets the requested PPPoE service name. Setting service name to "*" on link with allowed incoming connections allows to accept incoming connection requests with any service name specified.

Since FreeBSD 6.3-STABLE/7.0-STABLE of 2008-01-30 it is possible to use "AC-Name\Service-Name" syntax to request specified access concentrator for outgoing connection.

The default is "*".
```

**Comment by benddevice** [comment]
No solution ???

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
