### ISSUE TITLE
www/nginx: UX improvements: Location / HTTP Server

### ISSUE THREAD

**Issue by fabianfrz** [opnsense/plugins#1018]
The nginx plugin has many features and it is still growing. Now the location config page already has two screen heights. It may make sense to group some options in a reasonable way to simplify finding the right option and mark some very uncommon settings advanced in addition. The same issue already starts to happen in the HTTP Server menu.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
