### ISSUE TITLE
dns/bind: blacklist empty after cron job

### ISSUE THREAD

**Issue by tiki1980** [opnsense/plugins#1022]
I've set up the bind blocklist according to the instructions on: https://www.routerperformance.net/opnsense/dnsbl-via-bind-plugin/. I've also setup the blocklist to refresh every night with the cron job. 

When the cron job has run the blacklist is completely empty (dnsbl.inc = 0kb), only after saving the dnsbl page in the gui the blacklist is populated. 

only log file entry i could find:
25-Nov-2018 03:33:00.165 general: info: received control channel command 'reload'
25-Nov-2018 03:33:00.165 general: info: loading configuration from '/usr/local/etc/namedb/named.conf'
25-Nov-2018 03:33:00.166 general: info: reading built-in trust anchors from file '/usr/local/etc/namedb/bind.keys'
25-Nov-2018 03:33:00.167 general: info: using default UDP/IPv4 port range: [49152, 65535]
25-Nov-2018 03:33:00.167 general: info: using default UDP/IPv6 port range: [49152, 65535]
25-Nov-2018 03:33:00.168 general: info: sizing zone task pool based on 6 zones
25-Nov-2018 03:33:00.170 config: info: /usr/local/etc/namedb/named.conf:22: 'max-cache-size 75%' - setting to 6048MB (out of 8065MB)

DNSBL config
![image](https://user-images.githubusercontent.com/5437362/48979377-62626900-f0ba-11e8-98fb-8f804bc715dc.png)

Generic config
![image](https://user-images.githubusercontent.com/5437362/48979385-74dca280-f0ba-11e8-9b3f-fc11276d8ca9.png)

Cron gui
![image](https://user-images.githubusercontent.com/5437362/48979392-8d4cbd00-f0ba-11e8-8c56-1499267c6f8f.png)

cron entry in /var/cron/tabs/nobody
![image](https://user-images.githubusercontent.com/5437362/48979529-a5bdd700-f0bc-11e8-922b-cae0c870d325.png)

**Comment by mimugmail** [comment]
@fichtner I mixed something up, I named the API call dnsbl same as the action. 
But while the API call adds the lists as parameters via config.xml, the action does nothing (also action for cron). Is there an easy way to the action with an API call or does this require a new php script?

**Comment by mimugmail** [comment]
@tiki1980 you should disable the cron until this is fixed, sorry ...

**Comment by tiki1980** [comment]
> @tiki1980 you should disable the cron until this is fixed, sorry ...

No probs there, thnx for adding this functionality!

**Comment by mimugmail** [comment]
https://github.com/opnsense/plugins/commit/3ee1ce7fb80b1159ed24ac39f3f77078dce23896 closes this one
