### ISSUE TITLE
[www/nginx] proxy_pass https

### ISSUE THREAD

**Issue by itn3rd77** [opnsense/plugins#1023]
Hi @fabianfrz 

I would like to request the feature to enable HTTPS upstream servers inside a location. As far as I could see there is no such option in the ui and if I understand the location template right there is no way to have an ```proxy_pass https``` currently. 

From service/templates/OPNsense/Nginx/location.conf
```
{% if location.path_prefix is defined and location.path_prefix != '' %}
    proxy_pass http{% if upstream.tls_enable == '1' %}s{% endif %}://upstream{{ location.upstream.replace('-','') }}{{ location.path_prefix }};
{% else %}
    proxy_pass http{% if upstream.tls_enable == '1' %}s{% endif %}://upstream{{ location.upstream.replace('-','') }};
{% endif %}
```

Or is this intentional by design and anything speaks against ```proxy_pass https```?

Thanks for your great work!

Best regards
Ingo

**Comment by fabianfrz** [comment]
Since this is not specific to proxy_pass, this setting is in the upstream config and not the location block.

**Comment by fabianfrz** [comment]
Just FYI: streams (UDP+TCP-Proxy) are using the same setting for TLS-Upstreams so this reduces some duplication.

**Comment by itn3rd77** [comment]
Hi,

thanks for your quick reply. Strange the upstream config had "Enable TLS (HTTPS)" checked but the ```/usr/local/etc/nginx/nginx.conf``` showed no https. After editing the upstream forth and back and restarting Nginx it worked. Nevertheless thanks for the explanation!

Best regards
Ingo

**Comment by fabianfrz** [comment]
I think you may have forgotten to regenerate the config - at least it would explain the issue.
