### ISSUE TITLE
Plugin Request: Accel-ppp with DHCP Option 82 ( IPOE )

### ISSUE THREAD

**Issue by elizandropacheco** [opnsense/plugins#1027]
Sirs, currently in many regional internet providers is using accel-ppp (https://accel-ppp.org/), mature system, with support for IPv6 and mainly ipoe networks (DHCP + Option82).

The ipoe has been used instead of pppoe in many cases, usually in FTTH networks that do not need a tunnel.

On the other hand, the accel itself provides a powerful and stable pppoe daemon.

It would be very interesting to provide this package in future releases of opensense. Is there such a possibility?

**Comment by mimugmail** [comment]
accel-ppp is linux-only ... no chance for us ..

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
