### ISSUE TITLE
Feature Request: Option to clear cache DNS Unbound

### ISSUE THREAD

**Issue by elizandropacheco** [opnsense/plugins#1031]
An interesting option that I missed in the web interface is the possibility of cleaning the Unbound cache. If possible add this option in the interface would be of great help.

This action is possible through the reload command (without restarting the process).

Other options are by zone and by registers:

By zone:
unbound-control flush_zone google.com

By host:
unbound-control flush www.google.com

By type:
unbound-control flush_type name www.google.com aaaa

**Comment by zaggash** [comment]
As of today you need to specify the config location with '-c'

unbound-control -c /var/unbound/unbound.conf stats
unbound-control -c /var/unbound/unbound.conf flush_zone google.com

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.

**Comment by henri9813** [comment]
Hello,

is this subject still exists ?

**Comment by theoisadoor** [comment]
This would be a useful function to expose via the GUI.
