### ISSUE TITLE
use monit to check interface which init's after boot

### ISSUE THREAD

**Issue by mrPsycho** [opnsense/plugins#1032]
Hello,

I'm using opnsense with huawei modem e3276. 
It is needed to be initialised with:
```usb_modeswitch -v 12d1 -p 1f01 -c /usr/local/share/usb_modeswitch/12d1:1f01```

but after reboot, system forgets about it and i have to initialise it again. 

I thought to use `monit` for that case - if everything is fine - so ok.
interface is obsolete - run this command. 

but, i can't chose needed interface, cause it is not shown on web gui:
![screenshot 2018-11-29 at 22 46 40](https://user-images.githubusercontent.com/883964/49247895-7d6e0980-f429-11e8-8dd0-a9eb0b89b529.png)

`pci` is for pci card, `VO` - bridge, `wifi` - wifi card. No modem interface is shown.  

is it possible to add custom value like `ue0`?

yes, i can do for hilink web interface, but it doesn't look correct.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
