### ISSUE TITLE
dns/bind: add new blocklists

### ISSUE THREAD

**Issue by mimugmail** [opnsense/plugins#1033]
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
https://mirror1.malwaredomains.com/files/justdomains
http://sysctl.org/cameleon/hosts
https://zeustracker.abuse.ch/blocklist.php?download=domainblocklist
https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
https://hosts-file.net/ad_servers.txt

https://forum.opnsense.org/index.php?topic=10400.msg47780#msg47780

Have to add some the next days ...

**Comment by docb7** [comment]
This one would be great too:
https://github.com/Akamaru/Pi-Hole-Lists/blob/master/hbbtv.txt
Thank you ;-)

**Comment by mimugmail** [comment]
@docb7 

next release will include:

https://github.com/Akamaru/Pi-Hole-Lists/blob/master/hbbtv.txt
https://zeustracker.abuse.ch/blocklist.php?download=domainblocklist
https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt

**Comment by mimugmail** [comment]
Open for Todo:

https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
https://hosts-file.net/ad_servers.txt

**Comment by docb7** [comment]
Thanks a lot!!!

**Comment by Jank8** [comment]
Hi, please add: https://hole.cert.pl/domains/domains_hosts.txt

**Comment by mimugmail** [comment]
It should be sufficient to add this URL to custom URLs https://hole.cert.pl/domains/domains.txt
