### ISSUE TITLE
Net-SNMP: sysServices should include layer3

### ISSUE THREAD

**Issue by vielhak** [opnsense/plugins#1034]
Hi there,

netdiscovery software does not detect opnsense as "Layer3"-device because default settings of Net-SNMP are
`iso.3.6.1.2.1.1.7.0 = INTEGER: 72 == 1001000 == Layer 7 + Layer 4`
would not it be better adding Layer 3 to it by:
add
`sysServices 76`
to
`/usr/local/share/snmp/snmpd.conf`
?

**Comment by mimugmail** [comment]
@vielhak So you tested manually adding this value and it works?

**Comment by vielhak** [comment]
correct.. with the addition and a restart of the snmpd: our netdisco recognize the opnsense as layer3 device and does an arpnip (which is essential for discovery the devices "behind" the opnsense).
![image](https://user-images.githubusercontent.com/9960355/49289710-ef376900-f4a4-11e8-8cf9-71eb95ea4a13.png)

**Comment by mimugmail** [comment]
There are really ppl Out there using netdisco too? Yay! I'll take care of this :)
