### ISSUE TITLE
[Feature request] vnstat widget

### ISSUE THREAD

**Issue by soder10** [opnsense/plugins#1036]
Dear devs,

I found searching in the forum there is vnstat already available as a plugin, for which I am very thankful (as many of the community members as I could see). Also I found out after testing, that widget is not yet available to show the vnstat counters on the dashboard.
It seems I am the first, so can you please provide sometime a widget for vnstat counters to be seen on the dashboard: 
e.g.
current day tx&rx
current week tx&rx
current month tx&rx

For the rest (more granular hourly stats), one can go to the plugin page itself.

Thanks again!

**Comment by mimugmail** [comment]
@fichtner Do you have a widget example for me and how it plays together with plugins? Never used it :/

**Comment by fabianfrz** [comment]
@mimugmail what kind of widget do you want to create?

You can use the same JS code in a widget as in the new style pages and code against the same API (for example HAProxy does that).

**Comment by mimugmail** [comment]
I have absolutely no idea :) I shall create one, not I want to create one :) I'll dig Info existing widgets over the weekend.

**Comment by arch1mede** [comment]
Hi, was there any progress done on this? I would like this as well.

**Comment by soder10** [comment]
> 
> 
> Hi, was there any progress done on this? I would like this as well.

Wow, I totally forgot this..

**Comment by arch1mede** [comment]
> 
> 
> > Hi, was there any progress done on this? I would like this as well.
> 
> Wow, I totally forgot this..

Yeah I only brought it up was because I noticed that on the dashboard, the interface stats do not reset unless you reboot the device and I didn't want to do that.

**Comment by soder10** [comment]
headsup...
