### ISSUE TITLE
Feature Request: Caddy--HTTP/2 web server with automatic HTTPS

### ISSUE THREAD

**Issue by mervynsword** [opnsense/plugins#1044]
Hi,you geniuses.

I have been using Caddy for a long time.It is a great web server,easy to use and with automatic HTTPS.

So can u guys add it into plugins?

The FreeBSD port is here:
https://www.freshports.org/www/caddy/

**Comment by fabianfrz** [comment]
the nginx plugin can also serve content and supports HTTPS and HTTP/2.

You should give it a try (I has many features so expect big configuration forms).

**Comment by fabianfrz** [comment]
@mimugmail It seems to have a nice feature: TLS tamper (MITM) detection. The rest should be possible in nginx as well. If we really need it, I could write a C extension for it but such a feature would probably lock out enterprise users because it is quite common to intercept HTTPS for AV scanning.

**Comment by fabianfrz** [comment]
@mimugmail I created a ticket in the nginx bug tracker:
https://trac.nginx.org/nginx/ticket/1690#ticket

**Comment by fabianfrz** [comment]
@fichtner @mimugmail @mervynsword Should we close this one, since all features should be in the nginx and the acme.sh plugin now?

**Comment by fichtner** [comment]
I think in haproxy is HTTP/2 now too
