### ISSUE TITLE
dns/dyndns: documentation for plugin

### ISSUE THREAD

**Issue by TheLinuxGuy** [opnsense/plugins#1045]
I haven't found any documentation on setting up cloudflare on the dyndns plugin but using my accounts email/password combination seems to yield an error:

`"Invalid format for X-Auth-Key header"`

Here is the full system log:
`

Dec 2 15:23:22 | opnsense: /services_dyndns_edit.php: Dynamic DNS (fw.xx.com): UNKNOWN ERROR - Invalid request headers
-- | --
Dec 2 15:23:22 | opnsense: /services_dyndns_edit.php: Dynamic DNS (fw.xx.com): PAYLOAD: {"success":false,"errors":[{"code":6003,"message":"Invalid request headers","error_chain":[{"code":6103,"message":"Invalid format for X-Auth-Key header"}]}],"messages":[],"result":null}
Dec 2 15:23:22 | opnsense: /services_dyndns_edit.php: Dynamic DNS (fw.xx.com): Current Service: cloudflare
Dec 2 15:23:22 | opnsense: /services_dyndns_edit.php: Dynamic DNS (fw.xx.com): _checkStatus() starting.
Dec 2 15:23:21 | opnsense: /services_dyndns_edit.php: Dynamic DNS (fw.xx.com via CloudFlare): _update() starting.
Dec 2 15:23:21 | opnsense: /services_dyndns_edit.php: Dynamic DNS (fw.xx.com): running get_failover_interface for wan. found em0
Dec 2 15:23:21 | opnsense: /services_dyndns_edit.php: Dynamic DNS (fw.xx.com): myIP extracted

`

After reading the instructions someone else wrote for pfsense - I figured out the password is the Global API key.

Can we contribute documentation to the wiki or is that off limits because that is not 'core' of opnsense?

**Comment by rootwyrm** [comment]
There's actually a dedicated repository for the documentation: https://github.com/opnsense/docs

I believe you would specifically be looking for https://github.com/opnsense/docs/blob/master/source/manual/dynamic_dns.rst

**Comment by fichtner** [comment]
It looks like the password is empty... We can add a help text in the plugin as well. We just need to know what the "password" is in cloudflare documentation? The "Auth key", "API key" ? And username is the email address?

**Comment by dpieski** [comment]
@fichtner  
Username = email address
Password = "Global API Key" (Under "My Profile" > "API Tokens")

![Screen Shot 2019-10-10 at 12 38 43 AM](https://user-images.githubusercontent.com/3300522/66541865-5dea4780-eaf6-11e9-8b99-f6e418a7943e.png)
