### ISSUE TITLE
phpDynDNS.inc: CURLOPT_INTERFACE gets assigned IP instead of interface name (patch attached)

### ISSUE THREAD

**Issue by ldldr** [opnsense/plugins#1046]
There is a bug in phpDynDNS.inc which causes the update to fail on dual stack interfaces. When updating the DynDNS hostname for the IPv6 of an interface, CURLOPT_INTERFACE gets assigned the IPv4 of that interface. This is a problem because curl attempts to initiate an IPv6 requests with the IPv4 as source address which naturally fails with "bind failed with errno 47: Address family not supported by protocol family".

Although the [CURLOPT_INTERFACE parameter](https://curl.haxx.se/libcurl/c/CURLOPT_INTERFACE.html) may be an IP, it is more robust to use the interface name instead in this case. Here is the fix:
```
--- phpDynDNS.inc.orig  2018-12-03 08:38:13.415421000 +0100
+++ phpDynDNS.inc       2018-12-03 08:57:34.950477000 +0100
@@ -358,7 +358,7 @@
             curl_setopt($ch, CURLOPT_HEADER, 0);
             curl_setopt($ch, CURLOPT_USERAGENT, $this->_UserAgent);
             curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
-            curl_setopt($ch, CURLOPT_INTERFACE, $this->_dnsRequestIfIP);
+            curl_setopt($ch, CURLOPT_INTERFACE, $this->_dnsRequestIf);
             curl_setopt($ch, CURLOPT_TIMEOUT, 15);
         }
```

**Comment by fabianfrz** [comment]
please convert it to a pull request and add a version bump to the readme as well

**Comment by fichtner** [comment]
This was most like fixed via https://github.com/opnsense/plugins/issues/1202.
