### ISSUE TITLE
quagga: Traceback cause of ripd.conf regardless if used or not

### ISSUE THREAD

**Issue by mimugmail** [opnsense/plugins#105]
Hi,

I just did a fresh install of opnsense, installed quagga and package via pkg and got the following:

Mar 29 18:41:44 OPNsense configd.py Starting daemon.
Mar 29 18:41:45 OPNsense configd.py: [6262e1e1-604b-4f06-815b-92db1d1b304e] generate template OPNsense/Quagga
Mar 29 18:41:45 OPNsense configd.py: generate template container OPNsense/Quagga
Mar 29 18:41:45 OPNsense configd.py: [6262e1e1-604b-4f06-815b-92db1d1b304e] Inline action failed with OPNsense/Quagga OPNsense/Quagga/ripd.conf 'collections.OrderedDict object' has no attribute 'quagga' at Traceback (most recent call last):   File "/usr/local/opnsense/service/modules/processhandler.py", line 505, in execute     return ph_inline_actions.execute(self, inline_act_parameters)   File "/usr/local/opnsense/service/modules/ph_inline_actions.py", line 50, in execute     filenames = tmpl.generate(parameters)   File "/usr/local/opnsense/service/modules/template.py", line 309, in generate     raise render_exception Exception: OPNsense/Quagga OPNsense/Quagga/ripd.conf 'collections.OrderedDict object' has no attribute 'quagga'
Mar 29 18:41:45 OPNsense pkg: os-quagga-devel-0.0.3 installed

Also when enabling OSPF I get the same:

Mar 29 18:46:45 OPNsense configd.py: [58ac82fe-fada-4cb6-be17-a304a121f085] request quagga
Mar 29 18:46:49 OPNsense configd.py: [67332e9d-8f6a-4cad-90f0-069187df8daa] request quagga
Mar 29 18:46:49 OPNsense configd.py: [bed730a5-c701-4c1f-a381-bae945fedc5a] generate template OPNsense/Quagga
Mar 29 18:46:49 OPNsense configd.py: generate template container OPNsense/Quagga
Mar 29 18:46:49 OPNsense configd.py: [bed730a5-c701-4c1f-a381-bae945fedc5a] Inline action failed with OPNsense/Quagga OPNsense/Quagga/ripd.conf 'collections.OrderedDict object' has no attribute 'rip' at Traceback (most recent call last):   File "/usr/local/opnsense/service/modules/processhandler.py", line 505, in execute     return ph_inline_actions.execute(self, inline_act_parameters)   File "/usr/local/opnsense/service/modules/ph_inline_actions.py", line 50, in execute     filenames = tmpl.generate(parameters)   File "/usr/local/opnsense/service/modules/template.py", line 309, in generate     raise render_exception Exception: OPNsense/Quagga OPNsense/Quagga/ripd.conf 'collections.OrderedDict object' has no attribute 'rip'
Mar 29 18:46:49 OPNsense configd.py: [fb1affda-158a-41f7-ace0-97f3f84e4634] restarting quagga
Mar 29 18:46:51 OPNsense configd.py: [2c7c1dd2-4ce7-4be5-921d-04ba9119e9b7] request quagga
Mar 29 18:46:52 OPNsense configd.py: [12b61d82-a1a1-4629-8601-03d5e18e3992] request quagga
Mar 29 18:46:55 OPNsense configd.py: [02d16a0d-1ed7-49b7-90ba-c7badc6b2220] request quagga

**Comment by fabianfrz** [comment]
looks like the RIP configuration does not exist. Can you reproduce that, when you hit save on both?

**Comment by fabianfrz** [comment]
@mimugmail for me, this looks like it happens because there is no configuration yet. #106 should disable the generation of probable defect configuration directives if the data does not exist. Maybe @fichtner can post you a command to test the patch.
