### ISSUE TITLE
upnp plugins:not working in a kvm?

### ISSUE THREAD

**Issue by mervynsword** [opnsense/plugins#1050]
Hi there,I am using OpnSense now,and everything works great until I can`t make upnp working.

I installed OpnSense in a proxmox vm machine.I have set vtnet0 as WAN,and vtnet1 as LAN,like this.
![image](https://user-images.githubusercontent.com/6478739/49635746-b3b81400-fa3b-11e8-8a81-be4e30c24db8.png)

And the LAN info.
![image](https://user-images.githubusercontent.com/6478739/49636118-9fc0e200-fa3c-11e8-8517-f1d536292998.png)

I have installed the os-upnp plugin and have make it enabled,like this.
![image](https://user-images.githubusercontent.com/6478739/49635824-e19d5880-fa3b-11e8-9826-e5fd1be70be1.png)

But the game(Warframe) and Deluge keeps telling me that the upnp is not working.

And I have found there are a lot of denies in the firewall log.Like this.
![image](https://user-images.githubusercontent.com/6478739/49636051-7607bb00-fa3c-11e8-8113-1fd296627df1.png)

As it says the interface is vtnet0,I can`t even add a firewall rule.
So,any suggestions?

**Comment by aficustree** [comment]
did you ever figure out how to fix this issue?
