### ISSUE TITLE
Feature Request: upnp - Add more than 4 rules

### ISSUE THREAD

**Issue by unipacket1** [opnsense/plugins#1062]
For the upnp plugin, can the page be modified to allow more than 4 user permissions rules?

**Comment by fichtner** [comment]
@unipacket1 you can try it out by issuing the following command:

    # opnsense-patch -c plugins 0c55fb0

For now there are 8 entries, but it can be changed easily now if further need arises.


Cheers,
Franco

**Comment by unipacket1** [comment]
Thanks  Installed the patch and the 4 additional lines showed up.
