### ISSUE TITLE
net/haproxy: [Feature request] dial pppoe interface on MASTER only

### ISSUE THREAD

**Issue by Droppie391** [opnsense/plugins#1063]
in a HA environment, it would be nice if the master node would dial the pppoe interface while the backup node would NOT.
i would imagine this can be controlled by monitoring the CARP status and then enabling/disabling the pppoe (wan) interface accordingly. 
at present we have to enable/diable the wan interface manually to avoid both nodes to connect, resulting in routing problems with our ipsec links.

**Comment by fraenki** [comment]
@Droppie391 Could you please explain _how_ exactly HAProxy dials the PPPoE interface? Maybe post your configuration and explain in detail.

**Comment by Droppie391** [comment]
Hi Frank,
as far as i know, haproxy does NOT dial the pppoe interface at the moment. 
What we would like is, that in a master-slave setup, with both wan connected to the same isp link, the node which is master will bring-up its wan link link and the slave (or backup) node will not. only when the master node fails and switches to slave, the other node should bring up the wan link.
Our problem at present is, that we have to deactivate the wan interface on the slave node. if we don´t, both nodes will open the pppoe link at the same time wich obviously causes routing issues. We tried setting the slave pppoe to dial-on-demaind but that doesn´t work. As soon as the slave node receives a package it thinks has to go into the internet, it starts its pppoe link.

**Comment by mimugmail** [comment]
But this is related to core and has nothing to do with HAProxy.

**Comment by fraenki** [comment]
> Our problem at present is, that we have to deactivate the wan interface on the slave node. if we don´t, both nodes will open the pppoe link at the same time

Thanks for this clarification. Since this is not directly related to HAProxy, I'll close this issue now.

I'm pretty sure this is a pretty common problem with PPPoE in a HA setup, so I'd suggest to search the [forums](https://forum.opnsense.org/) instead. Some smart people may have solved this issue already.
