### ISSUE TITLE
mail/postfix: Missing parameter for SMTPS support

### ISSUE THREAD

**Issue by NowayIndustries** [opnsense/plugins#1064]
I am missing the option to add `smtp_tls_wrappermode = yes` in the postfix configuration.

In my case this is required because my email host only lists SMTPS connection details on their knowledgebase. After reviewing the logs, I got the following error when attempting to connect:

> postfix/smtp[76434]: SMTPS wrappermode (TCP port 465) requires setting "smtp_tls_wrappermode = yes", and "smtp_tls_security_level = encrypt" (or stronger)

So I changed the dropdown for the TLS Client Security to 'encrypt' but I could not find the option to add the wrappermode. After I manually added the line to `/usr/local/etc/postfix/main.cf` I could succesfully relay via the postfix plugin (to my hoster, so with postfix acting as a smarthost).

For completeness sake:
opnsense version 18.7.8
with the plugin os-postfix 1.7

I plan on upgrading to the latest opnsense release later today, but I didn't see anything in the changelog about this (nor could I find an issue mentioning this wrappermode)

**Comment by NowayIndustries** [comment]
I just found out after updating that the checkmark actually sets 'smpt**d**_tls_wrappermode = yes' instead of the required one (without the d).

See also http://www.postfix.org/postconf.5.html#smtp_tls_wrappermode

As in the documentation, when using this wrappermode = yes the` smtp_tls_security_level = encrypt` _has_ to be set. So perhaps this can be added to the information of the option or if possible enforce this setting (and rename the checkbox to SMTPS support)?

**Comment by fichtner** [comment]
@mimugmail
