### ISSUE TITLE
[www/nginx] 25 open() "/var/db/nginx/auth/b8d291e0-e991-45ae-b333-af6edb3cce63" failed (13: Permission denied),

### ISSUE THREAD

**Issue by itn3rd77** [opnsense/plugins#1066]
I have a Location with "Basic Authentication" and "Basic Credentials List" configured. When I access the URL the basic authentication dialog appears and after I entered my credentials I am faced with the Server Error page. In the error log I see the following message:

```
open() "/var/db/nginx/auth/b8d291e0-e991-45ae-b333-af6edb3cce63" failed (13: Permission denied),
```

All configuration was done through the web ui.

**Comment by fabianfrz** [comment]
@itn3rd77 thanks for your report, the bug probably existed since 1.3 or earlier and you can fix it with the following commit:

https://github.com/opnsense/plugins/pull/1067/files

I am not sure if it works because it also contains the pkg description but you can try to run the following command:

```sh
opnsense-patch -c plugins eb694c9b0cbdf648ae50b0b3b21a2b4623487154
```

**Comment by fabianfrz** [comment]
done in #1067
