### ISSUE TITLE
[www/nginx]: Location with authentication request to the OPNsense not working

### ISSUE THREAD

**Issue by itn3rd77** [opnsense/plugins#1078]
Hi,

I have a location configured with the "Enable Advanced ACLs" option enabled. When I visit the appropriate URL the authentication windows pops up, but I am not able to authenticate with any user from LDAP.

![grafik](https://user-images.githubusercontent.com/2655169/50165315-fc49ba00-02e4-11e9-96d5-dbf08d60e8a9.png)

![grafik](https://user-images.githubusercontent.com/2655169/50164756-d243c800-02e3-11e9-8955-661cb3702551.png)

Is this a known limitation or a bug?

**Comment by fabianfrz** [comment]
@itn3rd77 It is a feature which may be extended in the future but currently it authenticates against the local database (hard coded).

**Comment by fabianfrz** [comment]
FYI: If you plan to work on it, this is the file doing the authentication: 
www/nginx/src/opnsense/scripts/nginx/ngx_auth.php

**Comment by fabianfrz** [comment]
you should be able to test it using the following command: 

`opnsense-patch -c plugins fd48304ea4081aa57551e34062981af4f7b6a83c`
