### ISSUE TITLE
[feature request] www/nginx please add /var/log/nginx/error.log

### ISSUE THREAD

**Issue by Northguy** [opnsense/plugins#1083]
Would it be possible to add the generic error log to the logging pages? When wrongly configuring Nginx, it will not start, but you need ssh to look into the file.

Currently only http errors are shown i.e. hostname.error.log or ip.error.log

**Comment by fabianfrz** [comment]
We should try to avoid generating an invalid configureation. So which error do you have?

**Comment by Northguy** [comment]
Short story: I was listening to a port which was already in use. Due to this error the server refused to start, which did not became evident until I observed the error messages in _/var/log/nginx/error.log_

I think it will require quite some effort to programmatically check this. As you are already displaying _/var/log/nginx/<servername>.error.log_, it should be quite easy to show this generic error.log on the same tabsheets as the other logfiles?
