### ISSUE TITLE
net-mgmt/zabbix-agent: upgrade to 4.0 release series

### ISSUE THREAD

**Issue by fraenki** [opnsense/plugins#1091]
With the release of Zabbix 4.0, the previous version 3.4 is now unsupported.
Our Zabbix Agent plugin should be moved to the current release.

This change is targeted for the upcoming OPNsense 19.1 release.

Refs #859

**Comment by fichtner** [comment]
we can already switch -devel to zabbix4-agent for 18.7.10 if you want?

with version 4 I'd not like to split agent and proxy between different minor versions so we should stay on the same LTS version.

**Comment by fraenki** [comment]
> we can already switch -devel to zabbix4-agent for 18.7.10 if you want?

Ayntime, to ensure it's in working condition for 19.1.

**Comment by fichtner** [comment]
Done. Since stable/19.1 is branched from master it'll be automatically included in 19.1-RC1 and up.

**Comment by fichtner** [comment]
@fraenki looks like the zabbix bump wasn't in 19.1-RC so far. Do you want version 4 for the agent in 19.1 for the stable package?

**Comment by fraenki** [comment]
> Do you want version 4 for the agent in 19.1 for the stable package?

Yes  :+1:
