### ISSUE TITLE
[Feature request] dmidecode plugin

### ISSUE THREAD

**Issue by soder10** [opnsense/plugins#1100]
Please make the dmidecode available as a plugin for opnsense. Would be useful to show BIOS/firmware infirmation on the dashboard, or perform ECC-related check in the CLI.

**Comment by fichtner** [comment]
I am in doubt a plugin is overly useful, but I'd be happy to see a PR.

**Comment by soder10** [comment]
Thanks Franco!
Well if you can keep this feature request open for some more time (not extremely urgent, but rather a low priority nice to have) we can see how many people are interested.
This could be used in case of displaying basic HW inventory on the dashboard: which FW is running on what motherboard vendor, what BIOS version has been applied (easy to figure out if an update is needed) etc.

**Comment by evbevz** [comment]
Something like "System hardware widget"?

**Comment by AdSchellevis** [comment]
or just dmidecode with "system hardware widget" as description, someone else might have better suggestions.

**Comment by evbevz** [comment]
System hardware widget #1117
