### ISSUE TITLE
dns_cf.sh upstream update/merge [Upstream Bug / Remerge]

### ISSUE THREAD

**Issue by KYLE-HILL** [opnsense/plugins#1102]
Hello OPNsense Devs,

When you get a chance could you one of you please update/merge the acme client code base to mirror the current master branch of the Neilpang's upstream project? Specifically could you please apply commit https://github.com/Neilpang/acme.sh/commit/7ba9a5972dd904b1b5834e7ef1a6a3323d1e29aa to fix a bug with dashes being present in the account email / name preventing acme.sh from working correctly.

Thanks, 
Kyle

**Comment by KYLE-HILL** [comment]
Hi Franco, 

Sorry for not understanding what you meant. Yes I can locally modify my install to fix it since it is not complied and wait for the next official release for an OPNsense patch. I don't have the ETA for inclusion in the next official. Thanks for your help!

-Kyle

**Comment by fraenki** [comment]
acme.sh's last release was 5+ months ago. That's a long time, but I'd suggest to keep on waiting for a new release... I don't want to bundle pre-release software.

**Comment by fichtner** [comment]
It looks like this was resolved in the last 2 years…
