### ISSUE TITLE
dns/dnscrypt-proxy: allow dns server port

### ISSUE THREAD

**Issue by thutex** [opnsense/plugins#1104]
We now have the dnscrypt proxy. great.
However, when setting it up i was trying to have this situation:

- clients query the firewalls local dns server (for local domains and filtering etc etc, port 53)
- if the firewall needs to resolve the query, it should use the dnscrypt server (localhost port 5353)

however in system/general/settings under networking - where we enter the general dns servers to use - we cannot specify the port.
this means i cannot have dnscrypt running on port 5353 and have the firewall use this proxy to resolve queries.

**Comment by mimugmail** [comment]
This can be closed as 1.1 supports static Servers?

**Comment by fichtner** [comment]
Perfect, thanks!
