### ISSUE TITLE
Feature: DHCP server able to handle non-interface configured subnets

### ISSUE THREAD

**Issue by willjones** [opnsense/plugins#1105]
It would be very nice to be able to use a pair of OPNsense boxes for HA DHCP for setups where DHCP relay is being used and the OPNsense setup is functioning more like a DHCP server appliance than a full firewall, i.e. there is only one configured interface on the OPN side but we would require multiple networks served via the DHCP server.

I am not awaare of any open source or indeed low cost commercial products that provides a nice, simple GUI for DHCPD and HA configuration like we have in OPNsense, but obviously having to have the DHCP server with a presence in every subnet is not idea, nor often desirable for large networks.

**Comment by mimugmail** [comment]
Ok, it seems to work now with one network. I'll try to add some functionality to allow multiple networks.
I explicitly don't spear from pools as they wont be supported! This is a limitation cause this would need a SQL server and SQLite is highly experimental (unsupported) for pooling. So it's obligatory to add EVERY IP/mac pair manually. 

Hope this is ok for you ...

**Comment by mimugmail** [comment]
3 limitations:
- only works for relay dhcp
- can't be combined with local dhcp
- only works with static leases, but you have api to add via scripting
