### ISSUE TITLE
GoDaddy DynDNS update through Godaddy API

### ISSUE THREAD

**Issue by jd0323** [opnsense/plugins#1108]
Add plugin for Dynamic DNS updates for Godaddy using the API.

**Comment by majorsl** [comment]
Hi, I came looking for this, I'm not sure how much is shared with the DynDNS service and pfSense, but I note they have it available.

**Comment by APoniatowski** [comment]
I was about to log a ticket, but see this here... any update? migrated from pfsense to opnsense. The dashboard broke on pfsense (complete mystery, causing the move). Now I do not have this functionality to update my DNS dynamically, where pfsense had it out-of-the-box... I see the last comment was made on 2 Feb... is this being looked into?

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.

**Comment by YvanDaSilva** [comment]
This issue should be resolved by the basic support of GoDaddy DynDNS provided by the following merge request: 
https://github.com/opnsense/plugins/pull/1654
