### ISSUE TITLE
CARP/Virtual IP over ZeroTier

### ISSUE THREAD

**Issue by dragon2611** [opnsense/plugins#1109]
Raising this in core for now as I don't think the issue is with the ZT plugin but rather the way CARP/VIP works in opnsense.

If you setup a VirtualIP on a Zerotier network it will work initially, the problem however is that the zerotier interface is only present when the zerotier-one service is running.

This leads to the virtual IP being disabled because the interface wasn't present, on first login after boot you'll get a status message informing you the Virtual IP was disabled due to the missing interface

Ideally I'd like it if Opnsense would be able to handle Virtual IP's on interfaces that are not always present (I.e automatically enable the virtual IP when the interface returns) as I'd like to have a Virtual IP on my Zerotier interface as I have some devices on my Zerotier network that cannot run an IGP easily (I use an OSPF to handle fail-over on that network at the moment)

**Comment by guedressel** [comment]
Bump: I'm also interested in running CARP over a ZeroTier network.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.

**Comment by taxilian** [comment]
I haven't adequately tested this, but it initially at least looks like it's working like this:

```
RouterA joins the network, manually assigned in the zerotier UI:
    x.x.x.2

RouterB joins the network, manually assigned in the zerotier UI:
    x.x.x.3

Assign the created interface on both routera and routerb and assign the correct ip address, then add a CARP ip on each:
    x.x.x.1
```

You will not be able to ping it; however, if you add `x.x.x.1` to both systems in the zerotier UI you will then be able to ping it.

I don't know how well failover works, however =]

**Comment by chrisjosuearzu** [comment]
I know this is closed already, but I'm also interested in getting to the zerotier VIP (running CARP) instead of the individual zerotier interfaces. I also posted in the [forum](https://forum.opnsense.org/index.php?topic=15683.0) 
@taxilian you mean adding x.x.x.1 as a secondary IP in the zerotier portal on each of the firewalls?

**Comment by taxilian** [comment]
Yes, I meant adding it as a secondary IP. That said, it seems to be a bit hit and miss as far as that actually doing anything and I doubt failover is working. I haven't really used it much, so I can't say for sure.
