### ISSUE TITLE
Feature request: Allow "Custom configuration" for proxy and such, but require specific GUI access for this

### ISSUE THREAD

**Issue by sebastiannielsen** [opnsense/plugins#1110]
I have a feature request, and that is to add a "Custom configuration" option for all items including Proxy and such.

But, since this allow the GUI user to execute arbitary commands as discussed here:
https://forum.opnsense.org/index.php?topic=6516.0

I would suggest adding a extra option inside:
Effective Privileges

which is called: GUI --> Custom config

That is default off for all except the "System administrator" default account (even if you create a new account with Administrator privileges) and then you have to manually add that privilege to allow custom configs.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
