### ISSUE TITLE
[bug] [proxy] Blacklist is evaluated before custom whitelist, groups acl broken

### ISSUE THREAD

**Issue by inetshell** [opnsense/plugins#1111]
# Issue
Currently, the plugin os-web-proxy-useracl do not work if a local and/or remote blacklist is used. (This is an issue with opnsense core webproxy config).

# How to replicate
I tried the following case:
- Install os-web-proxy-useracl plugin 
- Add a remote access control list and block all video and file transfer sites (I'm using http://www.shallalist.de/Downloads/shallalist.tar.gz)
![imagen](https://user-images.githubusercontent.com/25806983/48309774-616ffa00-e546-11e8-9faf-c3ff975ed8d9.png)
- Enable proxy local authentication
![imagen](https://user-images.githubusercontent.com/25806983/48309778-7056ac80-e546-11e8-8e1f-3977638a7bef.png)
- Create three groups for different access levels: file_sharing, youtube, all_access
- Create three users with "Proxy: Login" privilege and add them to one group
![imagen](https://user-images.githubusercontent.com/25806983/48309782-83697c80-e546-11e8-851b-722a829359a1.png)
- Create the following whitelist in "Services: Web Proxy: Groups and Users"
![imagen](https://user-images.githubusercontent.com/25806983/48309784-8a908a80-e546-11e8-8b46-3d4805ba6d40.png)

# Expected behavior
- user1: should access wetransfer.com 
- user2: should access youtube.com 
- user3: should access any site, even the remote ACL 

# Actual behavior
No user can access the specified sites in their whitelists.

# Cause
In squid.conf, the blacklists (marked in red) are evaluated before the "Auth plugins" include, which has the custom whitelists (marked in blue):
![imagen](https://user-images.githubusercontent.com/25806983/48309799-b57ade80-e546-11e8-992d-802a8ceb1b92.png)

# Solution
Move the blacklists after "Auth plugins" include. (Tested in OPNsense 18.7.7-amd64):
![imagen](https://user-images.githubusercontent.com/25806983/48309815-fd016a80-e546-11e8-814c-3efc41f0df92.png)

**Comment by inetshell** [comment]
Thanks anyway

**Comment by elvysmarchon** [comment]
> In the new version of the plugin you can already do all this. I also added support Remote ACL.

@kekek2 this new version its available?

**Comment by kekek2** [comment]
pull-request not accepted. 06.09.2019, 14:33, "elvysmarchon" <notifications@github.com>:In the new version of the plugin you can already do all this. I also added support Remote ACL.@kekek2 this new version its available?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.  --

**Comment by rafaelolivei** [comment]
Good Morning! I have exactly this problem. I did the procedure to try to resolve as pointed out here in this bug, but also did not have good results. Is there a more updated version of plugins?

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.

**Comment by AndyX90** [comment]
Is this bug still present? I have setup a remote blacklist and want to whitelist urls for some users/groups via os-web-proxy-useracl and the settings have no effect?!
