### ISSUE TITLE
NUT:BlazerUSB driver issue

### ISSUE THREAD

**Issue by kenavn** [opnsense/plugins#1118]
I have tried the following UPS-device attached to several USB-ports;

ugen0.2: <INNO TECH USB to Serial> at usbus0, cfg=0 md=HOST spd=LOW (1.5Mbps) pwr=ON (100mA)

  bLength = 0x0012 
  bDescriptorType = 0x0001 
  bcdUSB = 0x0110 
  bDeviceClass = 0x0000  <Probed by interface class>
  bDeviceSubClass = 0x0000 
  bDeviceProtocol = 0x0000 
  bMaxPacketSize0 = 0x0008 
  idVendor = 0x0665 
  idProduct = 0x5161 
  bcdDevice = 0x0002 
  iManufacturer = 0x0001  <retrieving string failed>
  iProduct = 0x0002  <USB to Serial>
  iSerialNumber = 0x0000  <no string>
  bNumConfigurations = 0x0001

It has its vendorId and productId correctly registered in the /usr/local/etc/devd/nut-usb.conf file. I've checked the access rights on ugen0.2, and it seems correct according to the nut-usb.conf file:

ls -Ll /dev/ugen0.2
crw-rw----  1 root  uucp  0x8d Jan  3 21:11 /dev/ugen0.2
   
I am using the blazer_usb driver set to "auto". I have also tried setting vendorid and productid directly in the /usr/local/etc/nut/ups.conf file directly with no success.

The nut_daemon will not start.

**_root terminal;_**
service nut start
Network UPS Tools - UPS driver controller 2.7.4
Network UPS Tools - Megatec/Q1 protocol USB driver 0.12 (2.7.4)
No supported UPS detected
Driver failed to start (exit status=1)
/usr/local/etc/rc.d/nut: WARNING: failed precmd routine for nut

The UPS is a known brand (PowerWalker VI 1500 LCD) and as described, the vendorid and productid are correct. Where to go, what to do?

**Comment by mimugmail** [comment]
You already reloaded the Firewall and tried to unplug and plug in the cable again?

**Comment by kenavn** [comment]
Yes, the firewall is restarted several times. It does not start the NUT service.

Log-lines from the last startup;
Jan 4 13:08:54 | configd.py: [52217685-306a-4f26-a83b-b9020dd0df17] returned exit status 1
Jan 4 13:08:49 | configd.py: [52217685-306a-4f26-a83b-b9020dd0df17] starting nut

Running opnsense version: 18.7.9
os-nut version: 1.4

**Comment by mimugmail** [comment]
Can you watch system.log and then plug the usb cable and plug in again?

**Comment by kenavn** [comment]
When disconnecting cable and reconnecting cable the following is written to system.log;
_(disconnect)_
Jan  5 12:29:52 fw upsmon[71223]: UPS PowerWalker is unavailable
Jan  5 12:30:44 fw kernel: ugen0.2: <INNO TECH USB to Serial> at usbus0 (disconnected)
_(connect)_
Jan  5 12:30:47 fw kernel: ugen0.2: <INNO TECH USB to Serial> at usbus0

**Comment by kenavn** [comment]
No spaces, no special chars.

_upsdrvctl -t start PowerWalker_

   0.000111	Starting UPS: PowerWalker
   0.000129	1 remaining attempts
   0.000136	exec:  /usr/local/libexec/nut/blazer_usb -a PowerWalker

**Comment by kenavn** [comment]
Then;

_/usr/local/libexec/nut/blazer_usb -a PowerWalker -D_
Network UPS Tools - Megatec/Q1 protocol USB driver 0.12 (2.7.4)
   0.000000	debug level is '1'
   5.664648	No supported UPS detected

**Comment by mimugmail** [comment]
This is strange as it should be supported (only German): https://thomas-leister.de/powerwalker-ups-debian-stretch/

**Comment by kenavn** [comment]
While reading up on this I got the impression that the debian distro uses another approach to USB management than FreeBSD. Could this be a issue related to that? I will try spinning up a container with Debian or whatever, and report on the findings there..

**Comment by kenavn** [comment]
I've now tried with a PowerWalker VFI 1000 CRM LCD also. It's supposed to be supported. Same behaviour.

**Comment by mimugmail** [comment]
Do you think you can install pfsense on a spare machine and test? It's hard for me to debug from remote.

**Comment by djzort** [comment]
Is there any other usb devices connected to the same root-hub? This is a constant problem for my set ups and I dont think is the fault of NUT or the BSD kernel.

My set ups have a Huawei USB 3G dongle and a UPS on a cheap USB hub hanging off the A10 OPNsense appliance's single USB port. If they arent the "right way" around in terms of usb ports, there are all sorts of problems communicating with the devices.

I am using APC UPS's mosty (which use usb-hid) and some random other's that use blazer. They all exhibit the same sorts of problems. I think its because the UPS tend to be usb 1.1 and the other device is usb 2.0.

Its not clear from the above if your device is present when you run `usbconfig` ? 

You can reset the USB port with `usbconfig -d ugen4.2 reset ` where ugenX.X is the device listed with `usbconfig`

**Comment by kenavn** [comment]
Hi, thanks for helping out on this. I tried both with and without hubs, and gave up on it in the end. I ended up retiring my opnsense firewall, and solving the UPS challenge differently. Thanks again.
