### ISSUE TITLE
net/haproxy + acme/letsencrypt: Issue with more than one reverse proxy destinations

### ISSUE THREAD

**Issue by 4lexk** [opnsense/plugins#1124]
I have configured two servers, services, pools and rules and provided Let's Encrypt certs to them. 
Now it looks like the last provisioned service is working and the one before is getting assigned the certificate from the last provisioned one... (the configuration still showing correct cert assignments)

Right now I'm on 18.7.10 but tested the same behavior with 18.7.9

**Comment by fraenki** [comment]
@4lexk Could you possibly paste your /usr/local/etc/haproxy.conf? :)

**Comment by 4lexk** [comment]
@fraenki any news on this?

**Comment by 4lexk** [comment]
I think the issue was to have more than one frontend for the same IP:PORT - I had to use one frontend/service with multiple backends on the same IP:PORT
