### ISSUE TITLE
Dashboard - Wake On Lan Widget Link -> not working!

### ISSUE THREAD

**Issue by opnsenseuser** [opnsense/plugins#1128]
![grafik](https://user-images.githubusercontent.com/34602360/51083126-1aa0ab00-1715-11e9-8af7-204437d47883.png)

![grafik](https://user-images.githubusercontent.com/34602360/51083131-268c6d00-1715-11e9-8989-8178e75ccd75.png)

**Comment by fichtner** [comment]
(closed because PR has been issued and the issue was moved to plugins)
