### ISSUE TITLE
security/acme-client: [Request] Support for All-Inkl.com ACME V2 request

### ISSUE THREAD

**Issue by 4lexk** [opnsense/plugins#1130]
please add acme V2 validation method for all-inkl.com

hook example: https://github.com/o1oo11oo/dehydrated-all-inkl-hook
API: http://kasapi.kasserver.com

**Comment by fraenki** [comment]
@4lexk This must be supported by [acme.sh](https://github.com/Neilpang/acme.sh/tree/master/dnsapi) before we are able to support it in OPNsense. If it's not already integrated in acme.sh, please consider submitting a [PR](https://github.com/Neilpang/acme.sh/pulls).

**Comment by 4lexk** [comment]
will do that, thx.

**Comment by fraenki** [comment]
Upstream PR: https://github.com/Neilpang/acme.sh/pull/1341

**Comment by fraenki** [comment]
I'm closing this issue now, because the features was still not merged upstream. Please let me know when this feature was added in acme.sh, I'll gladly reopen this issue.

**Comment by R000795** [comment]
@fraenki  This feature has been added to acme.sh now. Is there a chance to support this in opnsense? Thx!

**Comment by fraenki** [comment]
@R000795 Sure, I'll add it to my list.

**Comment by fraenki** [comment]
This will be available in the upcoming os-acme-client 2.0.
