### ISSUE TITLE
vpn/openconnect - interface creates everytime after reboot

### ISSUE THREAD

**Issue by mrPsycho** [opnsense/plugins#1135]
Hello,

noticed that not very obvious behavior:
after reboot openconnect starts and every time creates new interface. 

is it possible to fix it? 

why? to assign it and put a name. And then to be possible create routing things with NAT, routes and firewall.

**Comment by mimugmail** [comment]
Did you enable "Disable deletion" in Interface?

**Comment by fichtner** [comment]
Can you provide version numbers for clarity?

**Comment by mimugmail** [comment]
See screenshot, please close if it works 

![image](https://user-images.githubusercontent.com/20438689/51233759-0e159000-196b-11e9-9d2e-753acad9d3e9.png)

**Comment by fichtner** [comment]
It shouldn't happen since https://github.com/opnsense/core/commit/04259b48f8b1

**Comment by fichtner** [comment]
Sorry, I meant https://github.com/opnsense/core/commit/b26ae32f1

**Comment by mrPsycho** [comment]
cool, it works. 

now i will write simple monit check and it will reconnect, if it stucks, 
thanks!
