### ISSUE TITLE
dyndns: cloudflare not working with some tlds

### ISSUE THREAD

**Issue by nwpr** [opnsense/plugins#1136]
CloudFlare dyndns is broken with subdomains or international TLDs with many parts (like .co.uk). The bug exists since commit 55586d3c8ba890d65cc1a2d62839650cfa6aa275. As the current code was taken from pfsense, they already have a fix for that which can be referred to. (https://redmine.pfsense.org/projects/pfsense/repository/revisions/2446fffa5932e8debcaf165bfaf5492cea429c60)

**Comment by broglea** [comment]
Bump bump @Nornode did you find a solution at all?

**Comment by mihaibalaci** [comment]
is there a functional version already? just asking. i can offer testing

**Comment by tbela99** [comment]
I think here is the problem
https://github.com/opnsense/plugins/blob/48888583b0703b7328b7e83c089cedcae3b0183e/dns/dyndns/src/etc/inc/plugins.inc.d/dyndns/phpDynDNS.inc#L764

Using "**X-Auth-Key:** api_token" does not seem to work with the api token

We should use "**Authorization: Bearer** api_token" instead

I have come to that conclusion after trying my api token from the command line.

**Comment by tbela99** [comment]
![image](https://user-images.githubusercontent.com/58517/73143731-b0328280-406b-11ea-8964-88a04cf2fe48.png)

I removed headers X-Auth-Key  and replaced with header "Authorization: Bearer api_token". I used a token with permission to list zones and it worked fine

```php
 curl_setopt($ch, CURLOPT_HTTPHEADER, array(
                    "X-Auth-Email: {$this->_dnsUser}",
                    "Authorization: Bearer {$this->_dnsPass}",
                    'Content-Type: application/json'
                ));
```

**Comment by tbela99** [comment]
Can you please reopen this issue? As I said replacing "X-Auth-Key:" with "Authorization: Bearer" solve the issue. There is no need for "X-Auth-Email:"

**Comment by tbela99** [comment]
it looks like it is being fixed here https://github.com/opnsense/plugins/pull/1726/commits/7592767233be98e89b2d38ad3d5abdbe6376bb12 :)
