### ISSUE TITLE
dyndns long updates

### ISSUE THREAD

**Issue by Franck78** [opnsense/plugins#1140]
Hello,

I worked long time ago for IPCop project. Started with that (dynamic dns)

Maybe this is implemented in your code, maybe not.

Providers don't like to do useless updates on their system. Normal. Why request an update with no IP change ??? Do it to much and you are banned. Ok. Easy to fix and probably done long ago.

But on the long long run, with a stable IP, you will never contact the dyndns provider and maybe he will close your account ! Oups.

So I added a simple option (activated by default), 'Force dyndns update every month'.
=>no abuse with useless updates
=>not a dead account

Franck

(using afraid.org Josh since 10 years)

**Comment by Franck78** [comment]
Oh sorry Fabian, there is no pull request. 
I have not looked a opnSense source code. And don't think I will soon. 
This is more a 'feature request' (I probably got it too, long time ago).

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
