### ISSUE TITLE
Routing on the Dashboard

### ISSUE THREAD

**Issue by Nico82x** [opnsense/plugins#1141]
It'd be great to have a dashboard widget for routing available. Furthermore it'd be very helpful to see the state of BGP or OSPF neighbours directly on the neighbours tab.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
