### ISSUE TITLE
[os-igmp-proxy] Restarts every 30 minutes after c.newwanip and rc.newwanipv6 scripts execution

### ISSUE THREAD

**Issue by jpatriarca** [opnsense/plugins#1152]
I've detected that after upgrading from 18.7.10 to 19.1 (rc1 and rc2) my IPTV service freezes for 10 seconds every 30 minutes. After some further investigation I've detected that after the rc.newwanip and rc.newwanipv6 scripts runs on the WAN interface, 1 second after igmpproxy services goes down and restore itself. Since that it runs in sequence, there are two igmpproxy service stops, as the following logs indicates (full activity in system.log related to the issue:

**Jan 27 20:38:31	igmpproxy[84421]: select() failure; Errno(4): Interrupted system call**
Jan 27 20:38:30	opnsense: /usr/local/etc/rc.newwanipv6: Dynamic DNS: (Success) patriarca.pt updated to <WAN IP>
Jan 27 20:38:30	opnsense: /usr/local/etc/rc.newwanipv6: Dynamic DNS: updating cache file /var/cache/dyndns_wan_public.domain_0.cache: <WAN IP>
Jan 27 20:38:30	opnsense: /usr/local/etc/rc.newwanipv6: Dynamic DNS (public.domain): <WAN IP> extracted
Jan 27 20:38:30	opnsense: /usr/local/etc/rc.newwanipv6: Dynamic DNS (public.domain): Current Service: cloudflare
Jan 27 20:38:30	opnsense: /usr/local/etc/rc.newwanipv6: Dynamic DNS (public.domain): _checkStatus() starting.
Jan 27 20:38:28	opnsense: /usr/local/etc/rc.newwanipv6: Dynamic DNS (public.domain via CloudFlare): _update() starting.
Jan 27 20:38:28	opnsense: /usr/local/etc/rc.newwanipv6: Dynamic DNS (public.domain): running get_failover_interface for wan. found igb0_vlan12
Jan 27 20:38:28	opnsense: /usr/local/etc/rc.newwanipv6: Dynamic DNS (public.domain): <WAN IP> extracted
Jan 27 20:38:28	opnsense: /usr/local/etc/rc.newwanipv6: Dynamic DNS: updatedns() starting
**Jan 27 20:38:25	igmpproxy[36326]: select() failure; Errno(4): Interrupted system call**
Jan 27 20:38:24	opnsense: /usr/local/etc/rc.newwanip: Dynamic DNS: (Success) public.domain updated to <WAN IP>
Jan 27 20:38:24	opnsense: /usr/local/etc/rc.newwanip: Dynamic DNS: updating cache file /var/cache/dyndns_wan_patriarca.pt_0.cache: <WAN IP>
Jan 27 20:38:24	opnsense: /usr/local/etc/rc.newwanip: Dynamic DNS (public.domain): <WAN IP> extracted
Jan 27 20:38:24	opnsense: /usr/local/etc/rc.newwanip: Dynamic DNS (public.domain): Current Service: cloudflare
Jan 27 20:38:24	opnsense: /usr/local/etc/rc.newwanip: Dynamic DNS (public.domain): _checkStatus() starting.
Jan 27 20:38:22	opnsense: /usr/local/etc/rc.newwanip: Dynamic DNS (public.domain via CloudFlare): _update() starting.
Jan 27 20:38:22	opnsense: /usr/local/etc/rc.newwanip: Dynamic DNS (public.domain): running get_failover_interface for wan. found igb0_vlan12
Jan 27 20:38:22	opnsense: /usr/local/etc/rc.newwanip: Dynamic DNS (public.domain): <WAN IP> extracted
Jan 27 20:38:22	opnsense: /usr/local/etc/rc.newwanip: Dynamic DNS: updatedns() starting
Jan 27 20:38:20	opnsense: /usr/local/etc/rc.newwanipv6: ROUTING: skipping IPv6 default route
Jan 27 20:38:20	opnsense: /usr/local/etc/rc.newwanipv6: ROUTING: keeping current default gateway 'WAN router'
Jan 27 20:38:20	opnsense: /usr/local/etc/rc.newwanipv6: ROUTING: setting IPv4 default route to WAN router
Jan 27 20:38:20	opnsense: /usr/local/etc/rc.newwanipv6: ROUTING: no IPv6 default gateway set, assuming wan
Jan 27 20:38:20	opnsense: /usr/local/etc/rc.newwanipv6: ROUTING: IPv4 default gateway set to wan
Jan 27 20:38:20	opnsense: /usr/local/etc/rc.newwanipv6: ROUTING: entering configure using 'wan'
Jan 27 20:38:19	opnsense: /usr/local/etc/rc.newwanipv6: On (IP address: <Local IPV6 IP>) (interface: WAN_Meo[wan]) (real interface: igb0_vlan12).
Jan 27 20:38:19	opnsense: /usr/local/etc/rc.newwanipv6: IP renewal is starting on 'igb0_vlan12'
Jan 27 20:38:16	opnsense: /usr/local/etc/rc.newwanip: ROUTING: skipping IPv6 default route
Jan 27 20:38:16	opnsense: /usr/local/etc/rc.newwanip: ROUTING: keeping current default gateway 'WAN router'
Jan 27 20:38:16	opnsense: /usr/local/etc/rc.newwanip: ROUTING: setting IPv4 default route to <WAN router>
Jan 27 20:38:16	opnsense: /usr/local/etc/rc.newwanip: ROUTING: no IPv6 default gateway set, assuming wan
Jan 27 20:38:16	opnsense: /usr/local/etc/rc.newwanip: ROUTING: IPv4 default gateway set to wan
Jan 27 20:38:16	opnsense: /usr/local/etc/rc.newwanip: ROUTING: entering configure using 'wan'
Jan 27 20:38:16	opnsense: /usr/local/etc/rc.newwanip: Accept router advertisements on interface igb0_vlan12
Jan 27 20:38:15	opnsense: /usr/local/etc/rc.newwanip: On (IP address: <WAN IP>) (interface: WAN_Meo[wan]) (real interface: igb0_vlan12).
Jan 27 20:38:15	opnsense: /usr/local/etc/rc.newwanip: IP renewal is starting on 'igb0_vlan12'

Tried to disable DDNS service since that was my first assumption on the error but with no results.

WAN interfaces are both configured for DHCP/DHCP6.

Require your help and knowledge about this to solve this problem when possible. Let me know if you needfurther debug, logs or commands to be executed.

PS - I remember on a equivalent error in OpenWRT and igmpproxy also related with this automatic script a couple of years ago. If it helps...

**Comment by jpatriarca** [comment]
This behaviour occured in 19.1 RC version, 19.1 release and now on 19.1.1 release. Will someone look on this topic or your solution will be to revert to 18.7 version?

**Comment by fichtner** [comment]
Sounds like https://github.com/opnsense/core/issues/3197 -- if you agree, please close this one.

**Comment by jpatriarca** [comment]
Thanks for the feedback. You're right, the bug seems the same as the one you've refered. Will process to close this one. Thank you
