### ISSUE TITLE
Request: Apt-cacher-ng

### ISSUE THREAD

**Issue by djzort** [opnsense/plugins#1154]
The apt-cacher-ng software is a specialized http/s proxy for caching software distribution sites. 

It's intelligently caches both apt and yum repos. 

The BSD port is here: https://www.freshports.org/www/apt-cacher-ng/

**Comment by fabianfrz** [comment]
Are you sure?

The docs (PDF) in this tar file give me another feeling.See page 16 regarding Fedora Core and Arch Linux): http://ftp.debian.org/debian/pool/main/a/apt-cacher-ng/apt-cacher-ng_3.2.orig.tar.xz

**Comment by djzort** [comment]
It definitely works for centos. I am using it for centos right now.

Check out the fedora and epel mirrors lists in https://packages.debian.org/sid/amd64/apt-cacher-ng/filelist

**Comment by fabianfrz** [comment]
No, since #1198 you can use nginx to host your cache if you plan to work on it.

**Comment by djzort** [comment]
afaik, the nginx cache is generic caching. 

apt-cacher-ng is tailored to suit linux software repos. so you can tell it to import, pre-cache, retain indefinitely, or have expiration policies based on understanding the repo metadata rather than fifo.

**Comment by fabianfrz** [comment]
@djzort no, I just wanted to say that you will probably serve a directory (where your cached files are hosted) and you can use nginx to do that easily.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
