### ISSUE TITLE
Error in Dynamic DNS plugin when updating Namecheap

### ISSUE THREAD

**Issue by stitch10925** [opnsense/plugins#1156]
When I configure Dynamic DNS to update my Namecheap domain I get the following error:

_PHP Warning:  simplexml_load_string(): Entity: line 1: parser error : Space required after the Public Identifier in /usr/local/etc/inc/plugins.inc.d/dyndns/phpDynDNS.inc on line 1072

simplexml_load_string(): Entity: line 6: parser error : Opening and ending tag mismatch: hr line 5 and BODY in /usr/local/etc/inc/plugins.inc.d/dyndns/phpDynDNS.inc on line 1072
[29-Jan-2019 23:01:06 Europe/Brussels] PHP Warning:  simplexml_load_string():  in /usr/local/etc/inc/plugins.inc.d/dyndns/phpDynDNS.inc on line 1072_

As a result I am unable to update my domain.

Plugin version: 1.11

---
https://github.com/opnsense/plugins/blob/34af0c3becddf86bb8556dad2aec306b217e0972/dns/dyndns/src/etc/inc/plugins.inc.d/dyndns/phpDynDNS.inc#L1072

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
