### ISSUE TITLE
net-mgmt/zabbix-agent: not updating to 4.0

### ISSUE THREAD

**Issue by fraenki** [opnsense/plugins#1160]
When upgrading a test VM from 18.7.10 to 19.1 I've noticed that Zabbix Agent was not upgraded to 4.0:

```
root@opnsense-test:~ # pkg info '*zabbix*'
os-zabbix-agent-1.4
os-zabbix-proxy-1.1
zabbix3-proxy-3.0.24
zabbix34-agent-3.4.15
```

I had to to use `pkg` to perform the upgrade:

```
root@opnsense-test:~ # pkg upgrade
Updating OPNsense repository catalogue...
OPNsense repository is up to date.
All repositories are up to date.
Checking for upgrades (1 candidates): 100%
Processing candidates (1 candidates): 100%
The following 2 package(s) will be affected (of 0 checked):

New packages to be INSTALLED:
	zabbix4-agent: 4.0.3

Installed packages to be REINSTALLED:
	os-zabbix-agent-1.4 (direct dependency changed: zabbix4-agent)

Number of packages to be installed: 1
Number of packages to be reinstalled: 1

233 KiB to be downloaded.

Proceed with this action? [y/N]: y
```

This was supposed to be performed during the upgrade to 19.1.

**Comment by fraenki** [comment]
@fichtner Any idea? Maybe a os-zabbix-agent version bump would solve this...

**Comment by fichtner** [comment]
All packages are being reinstalled. I doubt the revision bump for the plugin would help.

We could add a second pkg upgrade after the pkg upgrade -f we do, but it looks silly and might cause further potential for breakage.

**Comment by fraenki** [comment]
I've upgraded another test box and hit the same issue. This break Zabbix Agent, because although the old version is still listed as "installed", the binary is missing:

```
root@opnsense:/usr/local # pkg info zabbix34-agent
zabbix34-agent-3.4.15
Name           : zabbix34-agent
Version        : 3.4.15
Installed on   : Sun Feb  3 13:20:33 2019 CET
```

Notice how "Installed on" is the time of the 19.1 upgrade. But something went wrong during reinstallation (or upgrade to Zabbix Agent 4.0), because the binary is missing:

```
root@opnsense:~ # /usr/local/sbin/zabbix_agentd
/usr/local/sbin/zabbix_agentd: Command not found.
```

The GUI shows that an upgrade for Zabbix Agent is available:

![zabbix4_missing](https://user-images.githubusercontent.com/909706/52176822-8c21c580-27b8-11e9-992d-0ce1a8199aac.png)

**Comment by fraenki** [comment]
@fichtner Maybe setting CONFLICTS in `Makefile` would fix this? I'd assume it would force `pkg` to remove the zabbix34-agent package before reinstalling os-zabbix-agent.

**Comment by fichtner** [comment]
We'll remove the old zabbix32-agent in 19.1.1 and let upgrades run through this directly so it has no choice but to pick up the new one. This is a pkg bug, similar things happened with php in the past so we never have more than one php in the repository which makes testing harder but oh well. :)

**Comment by fichtner** [comment]
PS: CONFLICTS is of no interest to pkg

**Comment by fichtner** [comment]
https://github.com/opnsense/tools/commit/1eab62683f530c79a6fbc12c0be49fc9ca396493

**Comment by fraenki** [comment]
> PS: CONFLICTS is of no interest to pkg

OK, I though it would work the same way as in the ports framework...

Thanks for the fix.

**Comment by fichtner** [comment]
for ports that is also ignored by pkg

**Comment by fraenki** [comment]
Yes, sure we would have to choose CONFLICTS_INSTALL, I just couldn't remember the appropiate name ;)

**Comment by fichtner** [comment]
that is also only used in the ports framework...

**Comment by fraenki** [comment]
Got it. We don't those things to the ports framework.

**Comment by fichtner** [comment]
no, pkg has no relation in CONFLICTS or CONFLICTS_BUILD or CONFLICTS_INSTALL. The value is never stored in the package...

**Comment by fichtner** [comment]
Did a test just now on what is going to be 19.1.1 and the upgrade works fine now. We'll pin the 18.7 upgrades to 19.1.1 and the issue is gone for everyone else as discussed. :)
