### ISSUE TITLE
19.1 php curl error while updating dyndns

### ISSUE THREAD

**Issue by theq86** [opnsense/plugins#1161]
> opnsense: /services_dyndns_edit.php: Curl error occurred: bind failed with errno 47: Address family not supported by protocol family

> opnsense: /usr/local/etc/rc.dyndns: Curl error occurred: bind failed with errno 47: Address family not supported by protocol family

These errors constantly appear in the log and dyndns update ~~fails~~(*) due to curl error.

(*) The IP gets updated correctly but the error makes opnsense think it failed.

OPNsense version 19.1
dyndns provider: HE.net
not working since: new bug in 19.1

**Comment by theq86** [comment]
I'm on Dual Stack. So IPv6 address is present.
WAN IPv6 is DHCPv6 via PPPoE and I'm using prefix delegation instead of asking for a single address.

**Comment by ypid** [comment]
Same here on 19.1.6. I'm also on dual stack but the issue occurs with custom-v6. curl on the command line against dynamic DNS update URL works and I see in the curl verbose output that a connection over v6 is made.

**Comment by fichtner** [comment]
Also fixed, multiple tickets unfortunately... if we can't be able to bundle it into a technically apt ticket where everyone contributes we'll run the risk of not finding the underlying bug. ;)
