### ISSUE TITLE
Tor: Add GUI support for v3 onion service client authorization

### ISSUE THREAD

**Issue by alphazo** [opnsense/plugins#1165]
Some time ago I opened ticket #307 for having a Tor GUI on Opnsense and a very nice one has been made available. Thanks to the developers.
Since Tor 0.3.5.7 is now on Opnsense I think a lot of people would like to get the new v3 onion service client authorization and I believe some changes are required on the GUI to accommodate the new scheme.

You can find a very good summary and links on a Onionshare feature request https://github.com/micahflee/onionshare/issues/697

I also found a nice write-up about actually using this new feature https://gist.github.com/mtigas/9c2386adf65345be34045dace134140b

**Comment by alphazo** [comment]
I did some tests and manually using both V3 addresses and the new client authorization scheme was pretty straightforward.
I used the script mentioned in the gist to generate the proper keys.
```

 ./onion-svc-v3-client-auth.sh
X25519 Private Key:
3DXT2BT7KC7JMPZSSBQUVDTUOCD4TUECCQ23CVFC46ROWUG3Y5FQ

X25519 Public Key: (give this to the onion service)
2T3JCSCQDKGGXYX3GNNLARG5JKXFPUMAHIK6ZCDTLHC5LD47DE5A

=====
Tor client configuration
=====
Make sure you have ClientOnionAuthDir set in your torrc. In the
<ClientOnionAuthDir> directory, create an '.auth_private' file for the
onion service corresponding to this key (i.e. 'bob_onion.auth_private').
The contents of the <ClientOnionAuthDir>/<user>.auth_private file should
look like:

    <56-char-onion-addr-without-.onion-part>:descriptor:x25519:3DXT2BT7KC7JMPZSSBQUVDTUOCD4TUECCQ23CVFC46ROWUG3Y5FQ

i.e.:
    p53lf57qovyuvwsc6xnrppyply3vtqm7l6pcobkmyqsiofyeznfu5uqd:descriptor:x25519:3DXT2BT7KC7JMPZSSBQUVDTUOCD4TUECCQ23CVFC46ROWUG3Y5FQ

=====
Onion service configuration
=====
Inside the HiddenServiceDir for this onion service, create an
/authorized_clients/ subdirectory and a '.auth' file for the user (i.e.
'alice.auth'). The contents of the <HiddenServiceDir>/authorized_clients/<username>.auth
file should look like:

    descriptor:x25519:2T3JCSCQDKGGXYX3GNNLARG5JKXFPUMAHIK6ZCDTLHC5LD47DE5A
```
I then added those keys to both servers and clients:

**Opnsense side**
/usr/local/etc/tor/torrc

```
HiddenServiceDir /var/db/tor/testme/
HiddenServiceVersion 3 
HiddenServicePort 80 192.168.0.10:80

```
And then added the authorized key:
```
cd /var/db/tor/testme
mkdir authorized_clients
chown _tor:_tor authorized_clients
echo "descriptor:x25519:2T3JCSCQDKGGXYX3GNNLARG5JKXFPUMAHIK6ZCDTLHC5LD47DE5A" > test.auth 
chown _tor:_tor test.auth
```
Restarted Tor service and got the new long .onion address from the GUI (or hostname file). For example: 

`p11lf57qovyuxyzc6xnrppyaaa3vtqm7l6pcobkmyqsiofyeznfu5bcd.onion`

It was then very simple to add the right file on the client side:

**Client side (Tor Browser)**
First edited torrc to add path to the client authentication directory:

`echo "ClientOnionAuthDir /home/alphazo/.tor-browser-en/INSTALL/Browser/TorBrowser/Data/Tor/ClientOnionAuthDir" >> ~/.tor-browser-en/INSTALL/Browser/TorBrowser/Data/Tor/torrc`

And then add the private key file and updating .onion address of the hidden service provided by Opnsense (without the .onion extension).

`echo "p11lf57qovyuxyzc6xnrppyaaa3vtqm7l6pcobkmyqsiofyeznfu5bcd:descriptor:x25519:3DXT2BT7KC7JMPZSSBQUVDTUOCD4TUECCQ23CVFC46ROWUG3Y5FQ" >> /home/alphazo/.tor-browser-en/INSTALL/Browser/TorBrowser/Data/Tor/ClientOnionAuthDir/test.auth_private`

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
