### ISSUE TITLE
os-bind - SafeSearch - Google domains

### ISSUE THREAD

**Issue by sgoldtho** [opnsense/plugins#1169]
The Google SafeSearch only redirects two of Googles domains, there are lots more that should be included.

On this page <https://support.google.com/websearch/answer/186669?hl=en>, under the heading 'Lock SafeSearch by making changes to your router' there is an entry (and any other Google ccTLD country subdomains your users may use) which links to this list <https://www.google.com/supported_domain>.

Could you include all the domains in that list?

Thanks,
Steve

**Comment by mimugmail** [comment]
Can you do me a favor and make a list like in this format?

https://github.com/opnsense/plugins/blob/master/dns/bind/src/opnsense/service/templates/OPNsense/Bind/google.db

Then I can include it to the template ...

Thanks!

**Comment by sgoldtho** [comment]
Thanks,
Is this what you meant?

[google.doms.zip](https://github.com/opnsense/plugins/files/2843381/google.doms.zip)

**Comment by mimugmail** [comment]
Look good, thanks! I added it here: https://github.com/opnsense/plugins/pull/1176/files

As you can see it's very easy, so when you want to start contributing on your own I'd be glad to help :)
