### ISSUE TITLE
Quagga: resolve OPNsense names to real interface names

### ISSUE THREAD

**Issue by fabianfrz** [opnsense/plugins#117]
will fix this soon.

looks like I missed that the interface field translates to the OPNsense names like opt1 or lan but quagga needs the real interface names.

There is currently no function for this.
@fichtner @AdSchellevis  the best way would be adding a new helper for interfaces which I can call like `find_interface(interface_name)` where I can access information like the hardware interface name.
So for solving this issue, I will need the framework to be extended.

File in core: https://github.com/opnsense/core/blob/master/src/opnsense/service/modules/addons/template_helpers.py

This seems to be an issue in the proxy configuration as well:
https://github.com/opnsense/core/blob/master/src/opnsense/service/templates/OPNsense/Proxy/squid.conf#L34

**Comment by AdSchellevis** [comment]
@fabianfrz I think macro's are the way to go here, see https://github.com/opnsense/core/blob/master/src/opnsense/service/templates/OPNsense/Macros/interface.macro

and for usage
https://github.com/opnsense/core/blob/master/src/opnsense/service/templates/OPNsense/IDS/rc.conf.d#L2
https://github.com/opnsense/core/blob/master/src/opnsense/service/templates/OPNsense/IDS/rc.conf.d#L18

As soon as I can find some time I will try to add one for you in the same file.

**Comment by fabianfrz** [comment]
This does exactly what I needed but why is that a macro? I looked at the helper file where it was not included.

**Comment by fabianfrz** [comment]
I will close this for now as the issue in the plugin is solved.
