### ISSUE TITLE
os-wol WebIf packet was not send

### ISSUE THREAD

**Issue by Diego-Holzer** [opnsense/plugins#1172]
The packet was not sent due to an error. Please consult the logs.
https://forum.opnsense.org/index.php?topic=10671.0 -> same issue

**Comment by fabianfrz** [comment]
I do get the packet:

![grafik](https://user-images.githubusercontent.com/3713914/52427280-fa8bbe00-2aff-11e9-85c0-6beb129adb98.png)

**Comment by Diego-Holzer** [comment]
Yes, i have 5 firewalls, 2 are virtualized, installed with livecd, there works.
1 firewall is a APU2 Board, installed with livecd, there works.
2 firewalls are ALIX Boards, installed with the i386 nano image, there it doesn't work.

there i get the error.

**Comment by Diego-Holzer** [comment]
now, i was going on the shell.
with wol xx:xx:xx:xx:xx:xx i can wakeup the client.

now i try to understand the webif code to find the error.

**Comment by mixmint** [comment]
The error is in line 149 in the WolController.php file:
instead of
$int_bcast >> 24,
should be
($int_bcast >> 24) & 255,

**Comment by fichtner** [comment]
Thank you @mixmint, this would fix it then: 1116095

Patches directly using the following command on the console:

    # opnsense-patch -c plugins 1116095
