### ISSUE TITLE
WAF: Policy Operator bigger or Equal failed to save

### ISSUE THREAD

**Issue by xarados** [opnsense/plugins#1175]
When i try to edit an existing (or new) Policy it is not possible to save the changes when the Operator field is on Bigger or Equal, Bigger, Lesser, Lesser or Equal. Only with the option Equal it is possible to save.

Restart failed with error message:
```
2019/02/08 09:16:00 [emerg] 83332#100890: Naxsi-Config : Incorrect line CheckRule $policy676b2e8f148c4b4abc6be8ed410be138 = 8 (/usr/obj/usr/ports/www/nginx/work/naxsi-0.56/naxsi_src/naxsi_skeleton.c/646)... in /usr/local/etc/nginx/nginx.conf:1401
```
Line 1401 in nginx.conf:
```
CheckRule "$policy676b2e8f148c4b4abc6be8ed410be138 = 8" ALLOW;
```
As workaround i comment the failed line and start nginx manually.

**Comment by fabianfrz** [comment]
@fichtner this is a core bug as well. My dropdown key contains a "<" as well as a ">", which are escaped here:

https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/controllers/OPNsense/Base/ApiControllerBase.php#L235

And afterwards assigned here:
https://github.com/opnsense/core/blob/master/src/opnsense/www/js/opnsense.js#L140

The opnsense.js has to unescape it or the escaping must be removed entirely.

**Comment by fabianfrz** [comment]
@xarados this will be a breaking change - "=" is not supported by naxsi so I made an error while developing it. Please delete all "=" entries, apply both pull requests and then everything should work as expected.

**Comment by xarados** [comment]
@fabianfrz works like a charm.

**Comment by fabianfrz** [comment]
the plugin side is done, the rest is core.
