### ISSUE TITLE
[Feature Request] DNSCrypt - Blacklist Support

### ISSUE THREAD

**Issue by unipacket1** [opnsense/plugins#1183]
DNSCrypt-Proxy has built-in ability to use domain blacklists:
https://github.com/jedisct1/dnscrypt-proxy/wiki/Public-blacklists

Are there any plans to support this (and possible logging of blocked requests) from the within the existing plug-in?

**Comment by mimugmail** [comment]
I'm thinking about integrating it the same way like with Bind plugin, yes

**Comment by unipacket1** [comment]
That would be awesome, would definitely be interested in it.   Also, thank you for creating the DNSCrypt plug-in!!

**Comment by unipacket1** [comment]
@mimugmail @fichtner Very exciting to see this merged.  Thank you both!

**Comment by fichtner** [comment]
@unipacket1 thank you for the request ❤️
