### ISSUE TITLE
www/nginx misleading help on upstream.tls_enable

### ISSUE THREAD

**Issue by Alphakilo** [opnsense/plugins#1189]
The help element of `upstream.tls_enable` was ^C+^V'ed from `upstream.tls_client_certificate`:
https://github.com/opnsense/plugins/blob/48db37c69969874bb2c90d80f3afea2da1ac5d37/www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/forms/upstream.xml#L21-L23

This is misleading, since all the `upstream.tls_enable` option does is to append an `s` to the `http` upstream protocol if set:
https://github.com/opnsense/plugins/blob/48db37c69969874bb2c90d80f3afea2da1ac5d37/www/nginx/src/opnsense/service/templates/OPNsense/Nginx/location.conf#L143-L147

This was introduced in #762

**Comment by fabianfrz** [comment]
@Alphakilo If you want an entry in the release note, let me know. Since there is no functional change, it does not need one.

**Comment by Alphakilo** [comment]
@fabianfrz yeah, no. I think this can go without being mentioned.

But thanks for asking 😊
