### ISSUE TITLE
ACME (Lets Encrypt) Can't Validate Certs HTTP (Create domain key error)

### ISSUE THREAD

**Issue by Zewwy** [opnsense/plugins#1192]
I seem to be having an issue validating certificates via HTTP validation on OPNsense 19.1

Log on First Cert creation, and issue attempt: https://pastebin.com/7rWWHRXW

Select Cert and Click Issue Certificate again: https://pastebin.com/xx9pRMpB

My IP address is correct, DNS to my OPNsense Public IP is correct.
WAN has rule to allow HTTP port 80.

**Comment by Zewwy** [comment]
WELP!

**Comment by fichtner** [comment]
Question may be faster on the forums, I'm sure @fraenki will have a look but it won't be quick.

**Comment by Zewwy** [comment]
Thanks, I'd like to help more directly myself, maybe I can take a look at the source script, but I'm unsure which one OPNsense is currently using in it's active branch.

Also the logs don't seem to:

1) Report anything in the /var/log/acme.sh.log (i think this was the path, off-memory) when the service is enabled/disabled, when an account is created, pretty much nothing until you actually click a cert and then click Issue/renew.

You'd expect all these events to show in the log, service enabled/disabled, CSR created but not sent, etc.

2) Not script line call backs in the log, I'm basically going to have to search the source script for the line "Create domain key error" and then reverse engineer what logic gets there.

Just food for thought on my first couple attempts using this plugin...

**Comment by Zewwy** [comment]
I found two other issues under the acme.sh repo with similar issues unresolved as of Mar, 2018

https://github.com/Neilpang/acme.sh/issues/1356 

and

https://github.com/Neilpang/acme.sh/issues/1428

**Comment by Neilpang** [comment]
@Zewwy   fixed.  please try again.

**Comment by Zewwy** [comment]
Thanks Neilpang! I'm assuming I simply run check for updates on my OPNsense server?

I'll give a try right now. :D

**Comment by Zewwy** [comment]
Sorry didn't quite follow that. :)

From my testing of a regular OPNsense server with a direct public IP address. The Create Domain Key error was passed. I wasn't sure if this was due to  an actual change in the script, or me trying a different account email address under the accounts area.

I'll be doing a bit more testing with my other OPNsense VM that behind a NAT. I will report my results.

**Comment by Zewwy** [comment]
Alright, so again, I dunno why my initial attempts on the OPNsense that had a direct public IP failed. Which now succeeded.

however the OPNsense that has a HTTP NAT rule to it for Lets encrypt validation, does not seem to work?

 https://pastebin.com/HtEC83EG

**Comment by Zewwy** [comment]
Ugh... so I figured it might have been my firewall that is doing the NATing, and I decided to quickly create a HAproxy backend server pointing to a very basic IIS server. I was able to access it via the WAN IP of the OPNsense server (before the firewalls NAT), but I was unable to access it from the internet.

So I adjusted my firewall access rule (security rule, as the NAT rule was fine), and I was able to access the IIS server behind the OPNserver via the firewall NAT. Which meant the internet access form the outside world to my OPNsense was again perfectly fine at this point.

So I figured I had it covered. Re-confired the OPNsense server just like I did the one that had a Public NAT and is working) but it still fails with the exact same vague error:

Can not create domain Key.... I've tried this now 100 times!

https://pastebin.com/eyHGEsqM

**Comment by Neilpang** [comment]
@Zewwy 

```
[Wed Feb 20 01:08:28 UTC 2019] Domain key exists, do you want to overwrite the key?
[Wed Feb 20 01:08:28 UTC 2019] Add '--force', and try again.

```

The domain certificate already exists.

**Comment by Zewwy** [comment]
well I don't have them or I deleted (cause it kept saying validation failed) them and am trying again. how do I get past this?

**Comment by Zewwy** [comment]
I'm going to create a couple new records on my DNS provider portal right now (all pointing to the Public IP address on my Firewall that has a port 80 NAT rule to send those HTTP requests to the OPNsense's WAN IP), I hope the 3 hours will be enough. This way they should be "all new requests" and there shouldn't be an existing domain certificate?

**Comment by Zewwy** [comment]
https://pastebin.com/E9DAqs8R

I give up on this script...

**Comment by Zewwy** [comment]
This issue can be closed.

**Comment by Zewwy** [comment]
One last thing I noticed about this.... I had my rule created like I usually did (that would cause domain key error and cert validation failure).

Then when I opened the rule to allow the traffic it succeeded in the certificate validation when i was monitoring the logs. Which is awesome.

However the cert in the OPNsense UI still says validation failed? I know the cert actually succeeded per the acme.sh.log file.

Any idea why the UI doesn't correct itself?

**Comment by fraenki** [comment]
FWIW, the initial error reported by acme.sh was "Create domain key error". I've seen this a lot. In my tests it only happens when using acme.sh 2.7.9. The upcoming OPNsense release includes amce.sh 2.8.0, which is not affected by this issue.
