### ISSUE TITLE
Some squid/c-icap/clamd autoconfig issues

### ISSUE THREAD

**Issue by GottemHams** [opnsense/plugins#1194]
On a fresh install of OPN 19.1.1 I enabled squid, clamav and c-icap but:

1. It seems squid doesn't get configured to actually use icap. In `squid.conf` there's only `icap_enable off` and no amount of changing the config (through GUI) seems to change it. The only relevant option I could find to link the two is `Services` > `C-ICAP` > `Configuration` > `Use c-icap with local squid`. For now I simply created `/usr/local/etc/squid/pre-auth/00-icap.conf` containing the necessary variables to get it up and running while still being able to make other changes through GUI.

2. The request and response URLs point to `[::1]:1344` by default but clamd itself is actually listening on __127.0.0.1__ only. There's also no GUI option to change these addresses so I had to change it in the config.xml, otherwise it wouldn't connect at all and squid would throw its ERR_ICAP_FAILURE error page.

Perhaps I'm overlooking something, but I must've gone through all the relevant services' options at least 3 times without any luck.

**Comment by mimugmail** [comment]
Did you follow the guide in official docs?

**Comment by GottemHams** [comment]
Yeah I did, I wanted to make sure I didn't mess up something while building the initial configuration. I followed [this one](https://wiki.opnsense.org/manual/how-tos/proxyicapantivirusinternal.html) with the exception of step 4 due to the mentioned fields not being there in the GUI.

**Comment by mimugmail** [comment]
Squid  talks to cicap via v6 1344 and cicap to clamav via localhost v4, so this is ok.

**Comment by GottemHams** [comment]
Hmm, well for some reason when I ran c-icap-client against v6 1344 it wouldn't connect either. When I told the client to use v4 it worked right away, without any additional config changes. But to get squid to actually talk to c-icap I had to change config.xml to use v4 URLs, as well as manually add stuff to squid's config.

**Comment by mimugmail** [comment]
Eh, you saw the icap subtab in Proxy config where you can also set localhost v4?

**Comment by GottemHams** [comment]
Not until you explicitly said __sub__ tab, as I didn't realise those existed and the wiki isn't too clear on that either. I just figured it meant a __section__ under `Forward Proxy` but I could't find one, so I thought it was simply a bit outdated (which I suppose is normal for projects under active/constant development). The subtab you mentioned has all the options I needed, so thanks. =]
