### ISSUE TITLE
squid non-configurable access

### ISSUE THREAD

**Issue by andreas-p** [opnsense/plugins#1195]
- There's "http_access allow ftp", allowing unconditional FTP access. Since this is defined very early in squid.conf, it can't be overridden. IMHO any http_access rule should be placed late enough in templates/OPNSense/Proxy/squid.conf so there's a chance for manual override.

- When checking "Allow interface subnets", those subnets are added to the ACL "localnet" which has full access. But implicitely fc00::/7 and fe80::/10 are already in that ACL, giving full access for IPV6 machines. This can be overridden in auth.d/*.conf manually, but I still think it's unexpected. I suggest always defining the localnet ACL fully, but creating "http_access allow localnet" depending on the checkbox.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
