### ISSUE TITLE
BGP MIB

### ISSUE THREAD

**Issue by Nico82x** [opnsense/plugins#1200]
It'd be great if BGP was being exported via SNMP through the BGP MIB.

**Comment by mimugmail** [comment]
Do you know the steps how to achieve this?

**Comment by Nico82x** [comment]
Hi,

doesn't seem to be that hard:

https://trick77.com/how-to-compile-quagga-with-snmp-support/
https://community.librenms.org/t/monitoring-quagga-bgp-sessions/5099/2
https://www.nongnu.org/quagga/docs/docs-multi/AgentX-configuration.html#AgentX-configuration
https://lists.gt.net/quagga/users/21823
https://github.com/sbadia/check-bgp

So if quagga is compiled with snmp support, it should be sufficient to add a

agentx

to the zebra/bgp/whatever.conf files of the routing suite. I don't know 
if the net-snmp implementation in FreeBSD is similar to linux but the 
first link states that it is required to add these lines to the snmpd.conf:

master agentx
agentxsocket /var/agentx/master
agentxperms 777 777



HTH!

Best
Nico

Am 18.02.2019 um 13:02 schrieb Michael:

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.

**Comment by joshland** [comment]
I have added a pull request for this.

https://github.com/opnsense/plugins/pull/2321/files
