### ISSUE TITLE
os_tor should expose MyFamily option

### ISSUE THREAD

**Issue by cimnine** [opnsense/plugins#1204]
Affects os_tor plugin up to at least 1.7_1 on OpnSense 19.1.1.

I would like to see the tor plugin adding the possibility to declare the other 'family' members via the [`MyFamily` option][torrc]:

[torrc]: https://www.torproject.org/docs/tor-manual.html.en

> MyFamily fingerprint,fingerprint,…
> Declare that this Tor relay is controlled or administered by a group or organization identical or similar to that of the other relays, defined by their (possibly $-prefixed) identity fingerprints. This option can be repeated many times, for convenience in defining large families: all fingerprints in all MyFamily lines are merged into one list. When two relays both declare that they are in the same 'family', Tor clients will not use them in the same circuit. (Each relay only needs to list the other servers in its family; it doesn’t need to list itself, but it won’t hurt if it does.) Do not list any bridge relay as it would compromise its concealment.
> 
> When listing a node, it’s better to list it by fingerprint than by nickname: fingerprints are more reliable.
> 
> If you run more than one relay, the MyFamily option on each relay must list all other relays, as described above.
> 
> Note: do not use MyFamily when configuring your Tor instance as a brigde.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
