### ISSUE TITLE
Q: Plugin show network interfaces

### ISSUE THREAD

**Issue by teliz** [opnsense/plugins#1206]
I'm creating a plugin and I need to display a box to select a network interface, does anyone have any examples of how to do this? I think it would be something in xml in plugin -> models

thanks :)

**Comment by mimugmail** [comment]
InterfaceField in Model :)

**Comment by fabianfrz** [comment]
* https://github.com/opnsense/plugins/blob/master/net/frr/src/opnsense/mvc/app/models/OPNsense/Quagga/OSPF.xml#L29
* https://github.com/opnsense/plugins/blob/master/net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/ospf.xml#L15

**Comment by teliz** [comment]
Hi, thank you very much, that helped a lot. :+1: 

now I have a question
there is another selection box that I need to list all the devices (em0, em1, lo0 ...), is there any native way of doing this?

I thought of doing .sh (with an ifcondig -l) and using its return as being <options> from the checkbox, any hint how to do this?

thanks :)

**Comment by mimugmail** [comment]
Look at the full templating file of ospfd.conf, the physical import stuff
