### ISSUE TITLE
net/frr: Feature Request - OSPF filtering routes

### ISSUE THREAD

**Issue by fprina** [opnsense/plugins#1213]
I needs to redistribute in my OSPF network only few _kernel_ and _connected_ routes

Reading the FRR manual and after some manual tests the simple way to filter them look like via `distribute-list` and `access-list`

According to my tests we need to define the `access-list` in the **main** block
```
access-list NAME permit IPV4-NETWORK
access-list NAME deny IPV4-NETWORK
```
so something like: 
```
access-list foo1 permit 10.10.1.0/24
access-list foo1 permit 10.30.0.0/24
access-list foo1 deny any
access-list foo2 permit 10.20.2.0/24
access-list foo2 deny any
```
http://docs.frrouting.org/en/latest/filter.html

Then define the `distribute-list` inside the **router ospf** block
```
distribute-list NAME out (kernel|connected|static|rip|ospf)
```
In my conf
```
router ospf
 distribute-list foo1 out kernel
 distribute-list foo2 out connected
!
```

http://docs.frrouting.org/en/latest/ospfd.html?highlight=%22distribute-list%22#ospf-distribute-list

**Comment by mimugmail** [comment]
We already had a similar ticket, solution was to solve this via prefix list. Can you search the closed tickets for this?

**Comment by fprina** [comment]
do you mean the BPG related #985 ?

According to the FRR manual in the **router ospf** blok we can also use a route-map to filter the redistribute routes
```
redistribute (kernel|connected|static|rip|bgp) ROUTE-MAP 
```
> Redistribute routes of the specified protocol or kind into OSPF, with the metric type and metric set if specified, filtering the routes using the given route-map if specified. Redistributed routes may also be filtered with distribute-lists, see ospf distribute-list configuration.

so yes, maybe we ca use a similar solution
In a while I'll try to use a **route-map/prefix-list** as filter

**Comment by fprina** [comment]
It works as expected 

```
router ospf
 redistribute kernel route-map RM1
 redistribute connected route-map RM1
!

ip prefix-list PL1 seq 11 permit 10.10.1.0/24 le 32
ip prefix-list PL1 seq 12 permit 10.30.0.0/24 le 32
!

route-map RM1 permit 10
 match ip address prefix-list PL1 
!
```

**Comment by mimugmail** [comment]
Ok, so the only thing missing is linking route maps to redistributions?

**Comment by fprina** [comment]
yes

and, IMHO, move the _Prefix Lists_ and the _Route Maps_ tabs to the **General** menu

**Comment by mimugmail** [comment]
Err .. no .. but let me have a look :)

**Comment by fprina** [comment]
your code ... your rules :-)

I just need to use the route-map in the OSPF ... then where are located is a detail :-P

**Comment by mimugmail** [comment]
Totally forgot this one, sorry. I'll try to find a way.

**Comment by mimugmail** [comment]
Do you see any reason to have different route-maps for different redistributions? 
I could imagine a dropdown list after redsitribution field listing all route-maps and adding one for ALL redistributions. This would be an easy task ...

**Comment by fprina** [comment]
not really.
At least for my purpose a one-for-all filter should be enough

Anyway in the worst scenario you could add 5 dropdown, one for any "redistribution type" ... maybe ugly but it should works fine

**Comment by fprina** [comment]
just "visualized" your idea ... I agree, just one dropdown after the current list should be more intuitive and simple to manage.

Thanks you your work

**Comment by RoMe82** [comment]
Same "problem"/"issue" here - 

Make a Filter List in OSPF to Deny Redistribution
router ospf
 ospf router-id ***********
 redistribute kernel
 redistribute connected
 redistribute static
network ****** area 0.0.0.0
 area 0.0.0.0 filter-list prefix OSPF in
 area 0.0.0.0 filter-list prefix OSPF out

ip prefix-list OSPF seq 10 deny 192.168.255.0/24
ip prefix-list OSPF seq 11 permit 0.0.0.0/0
-------

But 192.168.255.0/24 will be redistributed

------
In VTYSH i can make a route-map and connect the route-map to redistribute
Works for me on Consol - but not in GUI


And if somebody Save the Config in GUI the Manual Changes are deleted

**Comment by fprina** [comment]
@mimugmail do you have any news for us ?

Thanks for your works ... let me know if I can do anything

**Comment by fprina** [comment]
I've tried to update the code but without results; At the moment I'm not able to do it.

So as temporary workaround I've: 
- Remove the os-ffr plugin 
- Added the package frr6, 
- Manually configure the service via vtysh

To start the service at boot I've added the script _/usr/local/etc/rc.syshook.d/start/50-frr_ as in the _os-frr plugin_
```
#!/bin/sh

# XXX this should not be strictly needed
/usr/local/etc/rc.d/frr start
```

**Comment by fprina** [comment]
Hi @mimugmail sorry to bother you ... I start to need this feature "in production" and I do not like to remove the plug-in to have a "safe" configuration. 
When you have some spare time can you have a look to this 

Thanks again for your time and work

**Comment by mimugmail** [comment]
Oh man ... time flies .. ok, I had a look again. 

Route-maps needs to be integrated from scratch with linking of prefix lists. When this is done a dropdown in ospf add a route-map after redistribution. 

Maybe I can start tomorrow with it.

**Comment by mimugmail** [comment]
Can you test latest master when #1360 is merged?

**Comment by fprina** [comment]
I'll test it as soon it will be merged
Thanks
