### ISSUE TITLE
DNSCrypt-Proxy - Blacklist Option not showing

### ISSUE THREAD

**Issue by unipacket1** [opnsense/plugins#1215]
Hello, I updated to version OPNsense 19.1.2 and the blacklist option is not showing on the Configuration page.  I also tried a fresh install of OPNsense but still not show as an option.  Also tried clearing browser cache in both instances.  I thought maybe when enabling DNSCrypt-Proxy the setting would show but it did not.

**Comment by fichtner** [comment]
Please carefully review version numbers. 1.3 is not in 19.1.2.

**Comment by unipacket1** [comment]
Ohhhh, my bad fichtner!  I''ve have to watch that next time.

**Comment by fichtner** [comment]
You could install the devel package:

    # pkg install os-dnscrypt-proxy-devel
