### ISSUE TITLE
www/nginx: allow setting server_names_hash_bucket_size

### ISSUE THREAD

**Issue by Zauberfisch** [opnsense/plugins#1219]
Long domain names require the `server_names_hash_bucket_size` directive to be set to a higher value inside the `http {}` block.

**Comment by fabianfrz** [comment]
Just run `opnsense-patch -c plugins 18614ad8769c31b7efa469563f6c04742c77b5c2` and it should exist under the first tab menu -> general http options.

How is @fhlug doing?

**Comment by knittl** [comment]
@fabianfrz yes, I'm still kicking :) Although I'm not sure which relation I would have to this issue report?

**Comment by fabianfrz** [comment]
@knittl you may know zauberfisch - he is in /dev/lol and in FHLUG so I had to think about it.
