### ISSUE TITLE
acme/lets encrypt Request for DNS Service for hosting.de

### ISSUE THREAD

**Issue by pipedreams-zz** [opnsense/plugins#1228]
Dear all,
i would like to issue Certificates with the LetsEncrypt Plugin. I am on 19.1.3 and the acme Plugin is in version 1.20.

The DNS Provider is hosting.de, and as we want to issue Wildcard Certs, we plan to use the DNS-01 Validation method.

The acme.sh project by NeilPang provides a script to the hosting.de API, but the plugin does not yet list it.

Would it be possible to add this to the list of available DNS Services: https://github.com/Neilpang/acme.sh/blob/master/dnsapi/dns_hostingde.sh

Thank you and good evening!

**Comment by pipedreams-zz** [comment]
Hi fraenki, i am willing to edit the files myself. First time on Github, but i am confident to manage it - guide myself from the last commit DonMcCoy hast done in June 18. Will fork the 3 files (dialogValidation.xml, AcmeClient.xml and certhelper.php) and add a pull request for you to review.

**Comment by fraenki** [comment]
@pipedreams-zz Good job with your first PR! :+1:
