### ISSUE TITLE
zabbix proxy 4 - PSK, wrong directory

### ISSUE THREAD

**Issue by nantoine555** [opnsense/plugins#1231]
I configured a zabbix 4 proxy on opnsense OPNsense 19.1.3-amd64 (libressl).

I have an issue with psk:
- the zabbix proxy stops and I have the following error in the log
84841:20190308:205848.625 cannot open file "/usr/local/etc/zabbix3/zabbix_proxy.psk": [2] No such file or directory

Note that I only installed the zabbix 4 proxy, not the zabbix prox3.

Thanks,

Antoine

PS: full log

45068:20190308:205848.605 Starting Zabbix Proxy (active) [opnhw.home]. Zabbix 4.0.5 (revision 90164).
 45068:20190308:205848.605 **** Enabled features ****
 45068:20190308:205848.605 SNMP monitoring:       YES
 45068:20190308:205848.605 IPMI monitoring:        NO
 45068:20190308:205848.606 Web monitoring:        YES
 45068:20190308:205848.606 VMware monitoring:      NO
 45068:20190308:205848.606 ODBC:                  YES
 45068:20190308:205848.606 SSH2 support:           NO
 45068:20190308:205848.606 IPv6 support:          YES
 45068:20190308:205848.606 TLS support:           YES
 45068:20190308:205848.606 **************************
 45068:20190308:205848.606 using configuration file: /usr/local/etc/zabbix4/zabbix_proxy.conf
 45068:20190308:205848.616 current database version (mandatory/optional): 04000000/04000003
 45068:20190308:205848.616 required mandatory version: 04000000
 45068:20190308:205848.624 proxy #0 started [main process]
 84841:20190308:205848.624 proxy #1 started [configuration syncer #1]
 84841:20190308:205848.625 cannot open file "/usr/local/etc/zabbix3/zabbix_proxy.psk": [2] No such file or directory
 98388:20190308:205848.625 proxy #2 started [heartbeat sender #1]
 98388:20190308:205848.625 cannot open file "/usr/local/etc/zabbix3/zabbix_proxy.psk": [2] No such file or directory
 13718:20190308:205848.625 proxy #3 started [data sender #1]
 13718:20190308:205848.626 cannot open file "/usr/local/etc/zabbix3/zabbix_proxy.psk": [2] No such file or directory
 45068:20190308:205848.626 One child process died (PID:84841,exitcode/signal:1). Exiting ...

**Comment by nantoine555** [comment]
Note: It works fine when I disable psk encryption on both the server and the proxy side

**Comment by fichtner** [comment]
Hi Antoine,

PSK is not in LibreSSL, we try to use GnuTLS for this to sidestep the requirement. But I am not sure why it isn't working. Yet it'll definitely work for OpenSSL flavour. Can you confirm this?


Cheers,
Franco

**Comment by fichtner** [comment]
Oh no, we build both against GnuTLS for consistency. It might be the same error.

**Comment by nantoine555** [comment]
line 70:
TLSPSKFile=/usr/local/etc/zabbix3/zabbix_proxy.psk 
in
 plugins/net-mgmt/zabbix4-proxy/src/opnsense/service/templates/OPNsense/Zabbixproxy/zabbix_proxy.conf

**Comment by fichtner** [comment]
@nantoine555 thanks for the report, fixed in 19.1.4 next week or directly via 396274da

    # opnsense-patch -c plugins 396274da
