### ISSUE TITLE
net-mgmt/telegraf: Incomplete process statistics

### ISSUE THREAD

**Issue by ppmathis** [opnsense/plugins#1233]
**Plugin:** net-mgmt/telegraf 1.7.4 with patch 73804ba due to #1147 
**System:** OPNsense 19.1.3-amd64 with LibreSSL 2.8.3

**Description:** Telegraf is unable to fetch useful process statistics through `inputs.processes`, as it is running as the `telegraf` user and OPNsense applies these two tunables by default, which only grant the superuser with the ability to see foreign processes:

```
security.bsd.see_other_uids=0
security.bsd.see_other_gids=0
```

**Workaround:** By disabling the built-in system tunables and relying on mod_seeotheruids instead, the primary group of the `telegraf` account can be exempted from this policy. The following system tunables have to be set:

```
security.bsd.see_other_uids=1
security.bsd.see_other_gids=1

mac_seeotheruids_load="YES"
security.mac.seeotheruids.enabled=1
security.mac.seeotheruids.suser_privileged=1
security.mac.seeotheruids.primarygroup_enabled=0
security.mac.seeotheruids.specificgid_enabled=1
security.mac.seeotheruids.specificgid=<ID of primary group for telegraf account>
```

By doing so, the same restrictions as before apply (only superuser is able to view all/foreign processes), however the telegraf group would be exempt for properly monitoring processes.

I suppose this could either be added to the documentation/UI as a hint, be automatically configured during plugin setup -or- Telegraf could run as root again (although that is certainly a security risk), which would also solve #1232.

**How to reproduce:** Install the Telegraf plugin and query your output target (e.g. `SELECT host, last(total) FROM processes` when using InfluxDB). You will notice that before applying the workaround/fix, Telegraf is only able to see its own processes, which makes the whole process monitoring module useless.

**Comment by fichtner** [comment]
This looks like documentation only. I know it seems inconvenient to have a loose set of sysctls that need to be applied for full monitoring, but in general these values are sane defaults and changing them shows more intent to solve an actual issue than pivoting telegraf service to root for monitoring purposes.

@mimugmail What do you think?

**Comment by mimugmail** [comment]
I'd go for doc update, perhaps a CDATA link in the help texst for process input.
@ppmathis ok with this?

**Comment by ppmathis** [comment]
@mimugmail Sure, sounds good to me! Adding it as documentation is probably indeed more reasonable than messing with the system tunables by default or exposing the system by running Telegraf as root.
