### ISSUE TITLE
Quagga: OSPF  for IPv6

### ISSUE THREAD

**Issue by fabianfrz** [opnsense/plugins#124]
A twitter user requested it (https://twitter.com/struband/status/854376817951748096)

If there is some time, it can be added

A sample can be found here:
http://www.nongnu.org/quagga/docs/docs-multi/OSPF6-Configuration-Examples.html

**Comment by mimugmail** [comment]
IMHO the biggest problem here is the v6 reduction, is there some kind of API/macro whatever within OPN available?

**Comment by fabianfrz** [comment]
@mimugmail what is 'reduction'?

OSPFv3 is an own service with its own configuration file and configured entirely different.

**Comment by mimugmail** [comment]
Input validation because you can write the ip like
2001:0DBA:0000:0000:0000:0000:0000:0001
or
2001:0DBA::1
or
2001:DBA::1

**Comment by fichtner** [comment]
IPv6 compression is not a problem, though we need to bounce these inputs through the backend --
-- let's not do this with JS ;)

**Comment by fabianfrz** [comment]
@mimugmail what you explain is called `zero compression`. It is easy to validate as it is allowed to be included only once and for an IPv6 network it is easy as there is only one place where it could be: at the end because the smallest network ist /64 which is the half address ;)

**Comment by mimugmail** [comment]
I extended my test env with ospf6d. 
Added IPv6 via UI, added ospf6d.conf via CLI:

```
!
! Zebra configuration saved from vty
!   2017/03/03 20:21:04
!
!
!
!
!
router ospf6
 interface vtnet0 area 0.0.0.0
 interface vtnet2 area 0.0.0.0
!
line vty
!
```

And have a nice adjacency:

```
OPN2.localdomain# sh ipv6 ospf6 neighbor
Neighbor ID     Pri    DeadTime  State/IfState         Duration I/F[State]
10.99.1.1         1    00:00:32   Init/DR              00:14:41 vtnet0[DR]
10.99.2.4         1    00:00:37   Full/BDR             00:18:03 vtnet2[DR]
```

```
OPN2.localdomain# sh ipv6 ospf6 route
*N IA 2001:db8:0:1::/64              ::                        vtnet0 00:22:55
 N IA 2001:db8:0:1::/64              fe80::1:c1ff:feff:6d56    vtnet2 00:05:48
*N IA 2001:db8:0:2::/64              fe80::1:c1ff:feff:6d56    vtnet2 00:05:53
*N IA 2001:db8:0:3::/64              ::                        vtnet2 00:22:55
*N IA 2001:db8:0:4::/64              fe80::1:c1ff:feff:6d56    vtnet2 00:18:00
```

I think most of the ospf stuff can be copied to ospf6 (or ospfv3).

**Comment by fabianfrz** [comment]
@mimugmail nice, I can add the backend parser into `quagga.rb`

**Comment by mimugmail** [comment]
Is it prohibited to use OSPF and OSPF6? I first copied all files and renamed everything to *6.
Now when I click on OSPF (v2) I get an API exception error: Class \OPNsense\Quagga\OSPF does not exist

**Comment by mimugmail** [comment]
Forget it, was a typo in the old model. Seems fine but data gets not saved. I'll investigate further ..

**Comment by fabianfrz** [comment]
Cannot say anything without knowing the code...

**Comment by mimugmail** [comment]
https://github.com/mimugmail/plugins/tree/ospf6d/net/quagga

Within browser debugging I get a 

`class OSPF6 extends BaseModel { } Fatal error: Uncaught Error: Class 'OPNsense\Quagga\OSPF6' not found in /usr/local/opnsense/mvc/app/controllers/OPNsense/Quagga/Api/Ospf6settingsController.php:45 Stack trace: #0 [internal function]: OPNsense\Quagga\Api\Ospf6settingsController->getAction() #1 [internal function]: Phalcon\Dispatcher->callActionMethod(Object(OPNsense\Quagga\Api\Ospf6settingsController), 'getAction', Array) #2 [internal function]: Phalcon\Dispatcher->_dispatch() #3 [internal function]: Phalcon\Dispatcher->dispatch() #4 /usr/local/opnsense/www/api.php(26): Phalcon\Mvc\Application->handle() #5 {main} thrown in /usr/local/opnsense/mvc/app/controllers/OPNsense/Quagga/Api/Ospf6settingsController.php on line 45`


And searchNetwork and searchInterface return a 500 

```
class OSPF6 extends BaseModel
{
}
{"errorMessage":"Class \\OPNsense\\Quagga\\OSPF6 does not exist"}
```

**Comment by fabianfrz** [comment]
I have looked over your code but I don't think it is a good idea to mix `OSPFv3` and `OSPF6`. It is probably better to rename it to OSPFv3 (as it is the protocol name)

The problem: Have you copied the files to your device?

**Comment by mimugmail** [comment]
I use OSPFv3 only two times where it's displayed. 
Quagga internally always uses ospf6 (in config), only for display there's v3. I'd rather stay to OSPF6 than v3.

No I copied via github UI. 

I forgot to adjust the template folder, but I don't think this is related to the error above.

**Comment by mimugmail** [comment]
Ok, found it, I missed the first line in the ospf6 model .. :(

**Comment by mimugmail** [comment]
@fabianfrz Ok, great. I have a running setup, ospf6d.conf file gets created and the daemon is now started.
I'll adjust the values for ospf6 now and delete the network tab. With ospf6 there's no network statement anymore

**Comment by mimugmail** [comment]
Pulled #143

**Comment by fabianfrz** [comment]
contributed by @mimugmail
