### ISSUE TITLE
www/nginx: CSP always uses report-only

### ISSUE THREAD

**Issue by realflunschi** [opnsense/plugins#1240]
When enabling Content-Security-Policy, a header `Content-Security-Policy-Report-Only` (instead of `Content-Security-Policy`) is added.

`security_rule.csp_report_only` is set to `0` by default in https://github.com/opnsense/plugins/blob/343a8bbeb525cb72860975ac38a1bcd08f552873/www/nginx/src/opnsense/mvc/app/models/OPNsense/Nginx/Nginx.xml#L863
(I suppose that intention is to disable "report-only" by default.) However, the following code checks whether `security_rule.csp_report_only` exists and not wheter it is set to `1`.
https://github.com/opnsense/plugins/blob/343a8bbeb525cb72860975ac38a1bcd08f552873/www/nginx/src/opnsense/service/templates/OPNsense/Nginx/security_rule.conf#L70
This could be fixed by using
```
    add_header Content-Security-Policy{% if security_rule.csp_report_only is defined and security_rule.csp_report_only == '1' %}-Report-Only{% endif %} "{%
```
instead.

**Comment by fabianfrz** [comment]
@realflunschi fix is ready. You can patch your installation in advance if you need to.

**Comment by ruffy91** [comment]
I can't find a field where the report uri could be defined for reporting.
What am I missing?
