### ISSUE TITLE
net/freeradius: add Cisco-AV-Pair

### ISSUE THREAD

**Issue by thutex** [opnsense/plugins#1247]
To be able to set administration privileges for the ubiquiti edgeswitch we need the Cisco-AV-Pair option.
A user could then be assigned the value shell:priv-lvl=15 for administration rights to the edgeswitch.

i am slowly moving towards a centralized way to manage users and clients on my network, and since opnsense has already become the heart of the operation, it would make sense to use the radius plugin for all authentication within my network.

however, to be able to manage the devices we need to be able to set the privilege level of the users.

**Comment by mimugmail** [comment]
So you only need this line for a user and thats it?

**Comment by thutex** [comment]
yeah, that is pretty much it.
this option is used for the edgeswitch to check the privilege level.
as far as i can find, the cisco-av-pair option can do the same (and much more) for cisco switches, but is only used on the edgeswitch for privilege verification.

otther nice options to have (because right now we can assign an IP and password to a user, but no DNS server or other password options) would be : 

Primary-DNS-Server
Secondary-DNS-Server
Change-Password
Password-Expiration

but for the time being, cisco-av-pair is the only one i really do need (since i need to be able to create a user that is actually allowed to manage the equipment)

**Comment by thutex** [comment]
@mimugmail any idea when and if this (cisco-av-pair) will be implemented?

**Comment by thutex** [comment]
a more general "advanced" block would be perfectly fine as well - having to do this manually creates the issue that settings are removed at every update, which is, well... not fun :)
i can go ahead and use the hook after updating to restore this automatically but having it built-in would still be preferable.

**Comment by mimugmail** [comment]
I'll add a new tab in users menu for AVPairs where you can add plenty of them and link in users via multiselect
