### ISSUE TITLE
Let's Encrypt and HAProxy Integration

### ISSUE THREAD

**Issue by WhiteNoseThunderPants** [opnsense/plugins#125]
I posted this on the OPNsense forums, but I figured this would be the best place for it.

I'm running OPNsense 17.1.4 and everything that I have configured has been working great except for the Let's Encrypt and HAProxy integration.

I have the latest plugins installed for both. Let's Encrypt has generated its integration with HAProxy.

You can find the Acme Client log here: https://pastebin.com/j58JwNW1

I've attached some screenshots of my configuration. Basically, I am unable to get certificates because Let's Encrypt is unable to validate my domain.

Not sure what else I can provide at this time. I looked in the HAProxy logs, but there is nothing of relevance in there.

If someone could point me in the right direction, I would appreciate it.
![image](https://cloud.githubusercontent.com/assets/542998/25252457/aeb14bae-25e2-11e7-950e-fcbfd9cd5344.png)
![image](https://cloud.githubusercontent.com/assets/542998/25252474/be69d8fe-25e2-11e7-9e1d-502e69c0eb33.png)
![image](https://cloud.githubusercontent.com/assets/542998/25252483/c66be88a-25e2-11e7-950a-76ddc96a2c8f.png)
![image](https://cloud.githubusercontent.com/assets/542998/25252489/cd075d46-25e2-11e7-8c6d-0c6a11cdf15a.png)
![image](https://cloud.githubusercontent.com/assets/542998/25252498/d42b0cc6-25e2-11e7-837c-75275cbcdf96.png)
![image](https://cloud.githubusercontent.com/assets/542998/25252503/d9f24bec-25e2-11e7-892d-c00923ec0271.png)
![image](https://cloud.githubusercontent.com/assets/542998/25252507/e1f6791c-25e2-11e7-8376-4e2f36c53d18.png)
![image](https://cloud.githubusercontent.com/assets/542998/25252511/e52fce9e-25e2-11e7-9972-1a42c8f79488.png)

**Comment by alanrbryant** [comment]
Any suggestions at all for what to do short of starting from scratch?

**Comment by fichtner** [comment]
CC @fraenki

**Comment by fraenki** [comment]
@alanrbryant Let's Encrypt (the CA, not the plugin!) is unable to reach your servers, according to acme.sh logs:

```
[Wed Apr 19 22:36:22 CDT 2017] original='{
  "type": "http-01",
  "status": "invalid",
  "error": {
    "type": "urn:acme:error:connection",
    "detail": "Could not connect to source.bryantgeeks.com",
    "status": 400
  },
```

And I can't reach your site neither:

```
> telnet source.bryantgeeks.com 80
Trying 75.87.65.9...
Connected to source.bryantgeeks.com.
Escape character is '^]'.
GET / HTTP/1.1
host: source.bryantgeeks.com


HTTP/1.0 503 Service Unavailable
```

At first look it does not seem like the HAProxy configuration does not work yet. Maybe start there and add Let's Encrypt later.

**Comment by alanrbryant** [comment]
@fraenki thanks for the response, I really do appreciate it.

SO, it seams it may be a misunderstanding of how Let's Encrypt works on my part. I do not have anything running on port 80 for source.bryantgeeks.com, only on port 4433. I understood the plugin to be opening port 80 to redirect the request to an internal server. Do I need to first have port 80 open for source.bryantgeeks.com manually?

**Comment by WhiteNoseThunderPants** [comment]
So I went ahead and switched my HAProxy config to point to ports 80 & 443 and once the translation fix comes in, I will try it again and see if that was my problem all along.

**Comment by WhiteNoseThunderPants** [comment]
I've switched to using the Port Forward method.

**Comment by fraenki** [comment]
I know I'm late, but for others that may read this:

> So, it seams it may be a misunderstanding of how Let's Encrypt works on my part. I do not have anything running on port 80 for source.bryantgeeks.com, only on port 4433. I understood the plugin to be opening port 80 to redirect the request to an internal server. Do I need to first have port 80 open for source.bryantgeeks.com manually?

Right, Let's Encrypt requires port 80 for HTTP-01 validation.
If using the HAProxy validation method with our Let's Encrypt plugin you're expected to have a HAProxy frontend listening on port 80 already. Otherwise Let's Encrypt communication may fail.

> I've switched to using the Port Forward method.

This is a good solution if you don't want to open port 80.

For websites that are already configured in HAProxy and have port 80 open, the HAProxy integration method is more reliable.
