### ISSUE TITLE
graphite_tag_support = true in [[outputs.graphite]]

### ISSUE THREAD

**Issue by donixa** [opnsense/plugins#1251]
I need below settings to get telegraf output to Splunk heavy forwarder working,
[[outputs.graphite]]
graphite_tag_support = true

*restarting telegraf service manually will work,
*but adding manually /usr/local/etc/telegraf.cof does not survive on reboot, 
may be I have to put it in different file settings? where is it?

I tried to put in 
[global_tags]
graphite_tag_support = "true"

or
[global_tags]
graphite_tag_support = true

it just does not work, could you help?

**Comment by donixa** [comment]
I found /usr/local/opnsense/service/templates/OPNsense/Telegraf/telegraf.conf

I simply add graphite_tag_support = true below timeout settings:

{% if helpers.exists('OPNsense.telegraf.output.graphite_enable') and OPNsense.telegraf.output.graphite_enable == '1' %}
[[outputs.graphite]]
{%   if helpers.exists('OPNsense.telegraf.output.graphite_server') and OPNsense.telegraf.output.graphite_server != '' %}
  servers = ["{{ OPNsense.telegraf.output.graphite_server }}"]
{%   endif %}
{%   if helpers.exists('OPNsense.telegraf.output.graphite_prefix') and OPNsense.telegraf.output.graphite_prefix != '' %}
  prefix = "{{ OPNsense.telegraf.output.graphite_prefix }}"
{%   endif %}
{%   if helpers.exists('OPNsense.telegraf.output.graphite_template') and OPNsense.telegraf.output.graphite_template != '' %}
  template = "{{ OPNsense.telegraf.output.graphite_template }}"
{%   endif %}
  timeout = 2
  graphite_tag_support = true

{%   if helpers.exists('OPNsense.telegraf.output.graphite_verify') and OPNsense.telegraf.output.graphite_verify == '0' %}
  insecure_skip_verify = true
{%   else %}
  insecure_skip_verify = false
{%   endif %}
{% endif %}

reboot OPNsense, and it works, could you point out docs about this?
May be add this graphical menu settings ?

thank you,

**Comment by mimugmail** [comment]
I'll add it to the next version (a checkbox).
Can you please close the other issues and just leave one open? :)
