### ISSUE TITLE
net-mgmt/zabbix-agent: cannot add custom user parameters

### ISSUE THREAD

**Issue by gec0** [opnsense/plugins#1252]
Hi,

I use  os-zabbix-agent 1.4 on OPNsense 19.1.4-amd64 and would like to add custom user parameters (Services => Zabbix Agent => Advanced  => User Parameters). My problem is that my inputs are checked by the ui before submit and are rejected. Even though my inputs are totally valid for the zabbix agent the ui's form validation won't accept the input.

This is what I want to add:
Key = opnsense.cpuTemperature
===> Error Message: Should be a string between 1 and 255 characters.

Command = sysctl -n dev.cpu.0.temperature | grep -o '[0-9]\?[0-9][0-9]\.[0-9]'
===> Error Message: Should be a string between 1 and 4096 characters.

My suggestion would be to turn off the form validation for special characters like dots, pipes and so on because we need to be able to input any os commands there. The special characters seem to be the problem because when I don't have a dot in the key name it is ok for the ui.

**Comment by fraenki** [comment]
@gec0 Thanks for your report! The following patch should fix this issue:

```
opnsense-patch -c plugins 13332d3a
```

This fix will also be available in the upcoming OPNsense 19.1.5 / os-zabbix-agent 1.5.

**Comment by sjhangiani** [comment]
I'm facing a similar issue to this where I get the key error message.

An example of what I am trying to add:

Key:             unbound.flag[*]
Command:  sudo /usr/sbin/unbound-control stats_noreset | grep num.query.$1= | cut -d= -f2

I think it is tripping up on the 'asterix' which is used as a parameter - I can work around by defining all the keys without an asterix but that would add a whole lot to the config.
