### ISSUE TITLE
net/ftp-proxy 1.0_1 broke vpn tab

### ISSUE THREAD

**Issue by mkaina2** [opnsense/plugins#1256]
Hello,
I'am on opensense 18.7 and had 2 clusters. On the first one I have ftp proxy 1.0 and the other one 1.0_1.
The latest broke the tab vpn ! 
<img width="1357" alt="opensense" src="https://user-images.githubusercontent.com/2117476/54370994-eb58dc80-4678-11e9-8ef0-ca20a7d27039.png">

**Comment by fichtner** [comment]
Wait a second, are you still on exactly "18.7" ? In that case you need to upgrade to 18.7.10 at least. :)

**Comment by fichtner** [comment]
PS: The change made to __items / iterateItems() requires you to run at least 18.7.6

**Comment by mkaina2** [comment]
thanks ! I'll plan to upgrade ! 
It's strange that plugin manager let me install ftp proxy 1.0_1 !
