### ISSUE TITLE
security/acme-client: Gandi LiveDNS API update

### ISSUE THREAD

**Issue by h0lysp4nk** [opnsense/plugins#1259]
Hi,

Recently Gandi's LiveDNS API was updated and the DNS-01 method for registering certificates whether it's normal certs or wildcards doesn't work anymore. Could this please get updates?

Best regards

**Comment by fraenki** [comment]
@h0lysp4nk We're relying on our upstream project https://github.com/Neilpang/acme.sh to update their plugin for Gandi, if required. Looks like the Gandi plugin wasn't updated for 3 months:

https://github.com/Neilpang/acme.sh/commits/master/dnsapi/dns_gandi_livedns.sh

Maybe this upstream bug report matches your issue:
https://github.com/Neilpang/acme.sh/issues/2011

Please report the issue upstream, if it hasn't already been reported. We'll include a fix as soon as it becomes available.

**Comment by fraenki** [comment]
I'm closing this issue now, because there was no upstream bugfix.
