### ISSUE TITLE
net/freeradius: improve EAP section

### ISSUE THREAD

**Issue by alexanderharm** [opnsense/plugins#1261]
@mimugmail I would like to offer my help in improving the Freeradius plugin, e. g. being able to specify the tunnel protocol (TLS, TTLS, PEAP, None) separately from the auth type (MD5, GTR, CHAP, ...) or the ability to authenticate against AD/LDAP via bind. You are interested in this or rather not right now?

**Comment by mimugmail** [comment]
The plugins dont belong to me, I pish them out in the hope some guys start contributing :) As long as your changes dont touch production setups in any case, I'm open for every PR :)

**Comment by mimugmail** [comment]
Are you still working on this?

**Comment by mimugmail** [comment]
Still active here?

**Comment by mimugmail** [comment]
@fichtner timeout?
