### ISSUE TITLE
PPPoE vnstat after reboot stats from wrong interface

### ISSUE THREAD

**Issue by soder10** [opnsense/plugins#1264]
Hello devs,

**Describe the bug**
I have PPPoE as WAN. In vnstat, the listening interface is selected as the "WAN" interface.

If I do an opnsense 19.1.4 reboot, vnstat starts to collect stats for the underlying igb0 interface, instead of pppoe0. Because on the raw igb0 there is not much happening, the stats are missing  even after days of uptime.

**To Reproduce**
1. Reboot opnsense
2. PPPOE session takes some time to establish
3. Goto services\vnstat
4. Under hourly/daily/etc stats, it says not enough data for igb0 (the physical NIC for the pppoe connection)
5. if I click Reset under services\vnstat, it correctly updates the interface to pppoe0, and after a couple of minutes, stats are generated correctly.

**Expected behavior**
vnstat should recognize that the pseudo pppoe0 is the correct device name for collecting WAN stats, not the igb0 physical NIC

**Additional context**
It was working correctly before 19.1.3

**Environment**
OPNsense 19.1.4 (amd64, OpenSSL).
Internet: PPPOE WAN
Network: igb0 for WAN, igb1+igb2 (in L2 bridge) for LAN

**Comment by mimugmail** [comment]
There were no real changes the last time. Perhaps your PPPOE take to long to come up?
@fichtner Would a interface lock help here?

**Comment by fichtner** [comment]
Nope, locking won't ensure the device will be there. When services are started the whole interface configuration is done. It looks like PPPoE went down or never came up, but it is impossible to guard against that from service side.

**Comment by soder10** [comment]
Just wanted to give a headsup that it is still working wrong even on 19.7.x

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.

**Comment by soder10** [comment]
Is there any chance, this gets fixed? Its not a very showstopper feature for me, but have to remember every time I have to reboot the router to go into vnstat and reset the db manually, otherwise I lose the traffic stats counter as long as the reset has not been done.
