### ISSUE TITLE
Plugin Request - Stubby

### ISSUE THREAD

**Issue by FingerlessGlov3s** [opnsense/plugins#1267]
Hi Guys,

I was thinking it would be good if we had a DNS over TLS plugin. Unbound is nearly there but doesn't use connection reuse yet, so it has to make a new TLS connection every time (costing extra time per request).

I'm proposing a plugin like [Stubby](https://dnsprivacy.org/wiki/display/DP/DNS+Privacy+Daemon+-+Stubby) is a dns forwarder which uses DNS over TLS with connection reuse. That way DNS resolution times say low and encrypted.

I personally use this on a Raspberry Pi, but would be neat if it was a Plugin.

DNS over TLS is the open standard so it would make sense to use this over DNS over HTTP etc.

**Comment by mimugmail** [comment]
What about dnscrypt-proxy?

**Comment by jonny3010** [comment]
Does that use DNS over TLS? or is that plugin DNS over HTTP?

**Comment by mimugmail** [comment]
DoH and Dnscrypt

**Comment by jonny3010** [comment]
Yeah I didn't think it used DNS over TLS, just thought it would be better to have a plugin which conforms to [standards ](https://tools.ietf.org/html/rfc7858)

**Comment by mimugmail** [comment]
You can search the forums for user directnupe. He wrote a guide for DNS over TLS with Unbound

**Comment by jonny3010** [comment]
I'll rather stick to using my Pi with Stubby as unbound doesn't do connection reuse (yet, I presume they'll add it at some point), so it keeps having to redo the encryption handshake. Where Stubby reuses the last connection, allowing faster lookup times, close to non tls requests

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
