### ISSUE TITLE
Dynamic DNS: Allow * in hostname for Google Domains

### ISSUE THREAD

**Issue by youngnicks** [opnsense/plugins#1280]
Google Domains allows for wildcard dynamic DNS entries, however opnsense is not allowing me to use wildcards for dynamic DNS.

**Comment by fichtner** [comment]
Can you try 71a8c22 ?

    # opnsense-patch -c plugins 71a8c22

Desperately needed a cleanup, basically what you asked for was adding the "case" statement for google domains in the new format :)
