### ISSUE TITLE
net/haproxy: check-ssl health check

### ISSUE THREAD

**Issue by siginigin** [opnsense/plugins#1282]
Hi,

please add check-ssl option to haproxy config - health monitors.
Meanwhile, how do you recommend to this as workaround? Direct replacement in /usr/local/etc/haproxy.conf is always overwritten after Apply button.

Thank you.

**Comment by cflee** [comment]
[`check-ssl` option](http://cbonte.github.io/haproxy-dconv/1.8/configuration.html#check-ssl) is on the `server` line, I think as a workaround it could be added to the Real Servers' `Option pass-through` box.

**Comment by fraenki** [comment]
I've added a new option "Force SSL" to Health Monitors. When enabled, it adds the `check-ssl` option to the `server` line.

This will be available in the upcoming os-haproxy 2.17.
