### ISSUE TITLE
www/nginx: Syslog Feature Request

### ISSUE THREAD

**Issue by Jacob-Coleman** [opnsense/plugins#1285]
Is it currently possible to collect the nginx logs and send them to a syslog server? I have looked around but have not found it. If it is not I would like to request it as a feature.

**Comment by fabianfrz** [comment]
The nginx server cannot log to the local syslog.

The plugin configureation can log to files.
nginx itself can also log to a remote logging server directly as syslog message. It is also possible to log to both as it would empty the OPNsense log viewer if the logs are not written to disk.

**Comment by Jacob-Coleman** [comment]
I am running a remote log server. I would like to write to local and to the remote log server. Could I enable this now by adding it to the local Nginx config? I attempted that at first but realized the file is generated by the config in the OPNsense GUI. Is there a place outside of the Nginx config I can enable it what would be written to the config when saved in the GUI?
