### ISSUE TITLE
Add Digitalocean to the list of dynamic DNS providers

### ISSUE THREAD

**Issue by BristleBeard** [opnsense/plugins#1286]
Please add Digitalocean to the list of providers for dynamic DNS.

https://developers.digitalocean.com/documentation/v2/#update-a-domain-record

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.

**Comment by HarlemSquirrel** [comment]
Could we please reopen this? I'm happy to help make it happen if someone can point me in the right direction.

**Comment by AdSchellevis** [comment]
@HarlemSquirrel Not going to reopen the ticket, but you can open a pull-request adding additional features. Just make sure to push them to ddclient (https://github.com/opnsense/plugins/tree/master/dns/ddclient), the old dyndns is about to retire.
