### ISSUE TITLE
net/haproxy: does not start on boot

### ISSUE THREAD

**Issue by StrikerTwo** [opnsense/plugins#1289]
Every time my OPNsense box reboots, HAProxy will not start automatically. If I click the play icon in the dashboard it starts and works perfectly.
Can I check anywhere in a log or something? It's bad enough when my server crashes and reboots, but I have pretty much every service behind HAProxy now, so NOTHING works (including monitoring) until I log on to OPNsense and click that stupid arrow :(

**Comment by Taomyn** [comment]
Which IP/port is HA listening on? My setup until v19.1.4 had it listening on the WAN IP:443, but something changed and I had the same issue. Turns out that's not the way to set up HAProxy. It happens because the WAN IP may not be available at the time HAProxy starts up and then fails.

I changed mine to listen on 127.0.0.1 and an unused port, then changed the NAT forwarding to forward from the WAN to that IP and port. It's been fine ever since.

**Comment by StrikerTwo** [comment]
Huh. Yes, I have it listening on the WAN IP.
If this is not the correct way, the documentation should reflect that :)
And if it is, maybe there needs to be a delay or more than one try when starting HAProxy.
Also, some kind of watchdog or something would be nice. 

Or can I start HAProxy with an HTTP API call? Then that's something my monitoring could do.

**Comment by Taomyn** [comment]
Here's where we discussed it on the forums: https://forum.opnsense.org/index.php?topic=11853.msg54316 feel free to add your thoughts there.

**Comment by StrikerTwo** [comment]
Thank you for the link. I use a fixed numeric IP address, so it should not be your specific problem with the hostname.

But I have found a solution: I now use a PRTG sensor to monitor haproxy/service/status, and if it's not running I send a service/start request. This should help in other situations as well where HAProxy just spontaneously fails.

SOME information when a service could not be started (other than the red square on the dashboard) would still be nice.

**Comment by fraenki** [comment]
> Can I check anywhere in a log or something?

Yes, next time please check `System -> Log Files -> General` and `System -> Log Files -> Backend`. It should contain some information if a service could not be started. Furthermore check `Services -> HAProxy -> Log File` as HAProxy might have been started but crashed/terminated immediately, so this log may contain more information.

**Comment by StrikerTwo** [comment]
Thanks.
Log Files -> General: 
root: /usr/local/etc/rc.d/haproxy: WARNING: failed precmd routine for haproxy

/var/log/HAProxy.log did not contain anything useful.
I will check this the next time PRTG notifies me of a failure ;)

**Comment by Taomyn** [comment]
> Thank you for the link. I use a fixed numeric IP address, so it should not be your specific problem with the hostname.

I use a fixed IP also I just used it's FQDN at the time, but regardless if the interface with that IP is not available to HAProxy during the startup, it will fail. That's why using the firewall's local IP is the better method.
