### ISSUE TITLE
Postfix feature request

### ISSUE THREAD

**Issue by indicato** [opnsense/plugins#1293]
Hello 
I like to have to more  functions for the spam protection

smtpd_helo_restrictions = reject_non_fqdn_helo_hostname, reject_invalid_helo_hostname
strict_rfc821_envelopes = yes

Also a postibillity to add DNSBL with a Button or in a txt form.

smtpd_client_restrictions =  reject_rbl_client zen.spamhaus.org, reject_rbl_client ix.dnsbl.m
anitu.net

Thanks for helping to stop spam.

Lars

**Comment by mimugmail** [comment]
Hi Lars, can you post your complete main.cf with hidden IPs? DNSBL is a good idea

**Comment by mimugmail** [comment]
@indicato ? Still interested

**Comment by fabianfrz** [comment]
@mimugmail dnsbl should be in the rspamd plugin.

**Comment by mimugmail** [comment]
It is, but mail would still be processed. For ne rspamd is enough

**Comment by mimugmail** [comment]
@fichtner  Timeout?
