### ISSUE TITLE
security/acme-client: feature request for DNS Service Domain-Offensive (dns_doapi)

### ISSUE THREAD

**Issue by badzox** [opnsense/plugins#1294]
Hi, 

 the acme.sh script already supports the API from Domain-Offensive:
https://github.com/Neilpang/acme.sh/blob/master/dnsapi/dns_doapi.sh

Please provide an update for OPNSense Letsencrypt to reflect this. 
I already did some testing and extended some scripts:

added to : usr/local/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml

 Under OptionValues under <dns_do>:
`  <dns_doapi>Domain-Offensive LetsEncrypt Api</dns_doapi>`

 Under</dns_do_pid>;
 ```
   <dns_doapi type="TextField">
        <Required>N</Required>
      </dns_doapi>

```
added to: /usr/local/opnsense/scripts/OPNsense/AcmeClient/certhelper.php

Under  case 'dns_do':
```
         case 'dns_doapi':
                $proc_env['DO_LETOKEN'] = (string)$valObj->dns_do_letoken;
                break;

```
added to: /usr/local/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml:

```
   <field>
      <label>Domain-Offensive LetsEncrypt API</label>
      <type>header</type>
      <style>table_dns table_dns_doapi</style>
    </field>
    <field>
       <id>validation.dns_do_letoken</id>
       <label>DO LETOKEN</label>
       <type>text</type>
    </field>

```
I added table_dns table_dns_doapi in the field description, but this table doesn't exist and i don't know howto add it. Without it after a reload of the page the value gets lost.

**Comment by fraenki** [comment]
@badzox Thanks. Since you've already posted the required code changes... Why not create a [pull request](https://help.github.com/en/articles/creating-a-pull-request)? Code contributions are very welcome! :)

**Comment by badzox** [comment]
@fraenki : Next time i will create a pull request if i find a solution, but this time i didn't knew where to add the necessary table for" table_dns table_dns_doapi"  in above code..
