### ISSUE TITLE
DynDNS with "Custom v6" request IP from wrong interface

### ISSUE THREAD

**Issue by somova** [opnsense/plugins#1296]
Dialin to my ISP uses PPPoE. The PPPoE Interface "pppoe0" is set up with "ix0" (ethernet interface) as parent interface whereas the latter connects to the DSL modem. Using Dyndns with IPv4 (Custom v4) everything works fine but registering IPv6 addresses with (Custom v6) fails. The configuration of "Custom v6" is almost the same like "Custom v4" with interface "pppoe0" as monitoring interface and interface where to send updates from.

I did the following tests with the following preconditions.

- ix0 has only a IPv6 link local address
- pppoe0 has three IPv6 addresses (a link local address, a public IPv6 generated using SLAAC and a temporary preferred public IPv6 address using SLAAC and privacy extensions)

Registering of the IPv6 address with Dyndns fails with the following error message (also if the third IPv6 with SLAAC and privacy extensions is disabled):

`opnsense: /services_dyndns_edit.php: Dynamic DNS (vpn-gw.spdns.org) There was an error trying to determine the public IP for interface - wan(ix0). Probably interface is not a WAN interface.`

It lookas like Dyndns tries to extract the public IPv6 from the wrong (parent) interface. To verify I removed all public IPv6 addresses from the interface "pppoe0" using ifconfig on the console. Afterwards, I used ifconfig to add one of these public IP addresses to the "ix0" interface and forced a re-registration of Dyndns with "Custom v6". Surprisingly, the registration process was successful.

As a result there is a bug in the Dyndns plugin which gathers the IPv6 address from the wrong interface.

As a further improvement, the user should be able to select which of the multiple IPv6 addresses (e.g. SLAAC, SLAAC with temporary addresses, ...) belonging to a specific interface should be registered.

Regarding this topic there is also thread in the opnsense forum: [https://forum.opnsense.org/index.php?topic=12219.msg55968#msg55968](https://forum.opnsense.org/index.php?topic=12219.msg55968#msg55968)

**Comment by somova** [comment]
This issue currently on hold due to other strange behavior seen in opnsense regarding IPv6. Perhaps, the real issue is somewhere else (see here: [https://forum.opnsense.org/index.php?topic=12219.msg56864#msg56864](url))

**Comment by mr44er** [comment]
How is your DHCPv6 configured?
You don't need to setup an IP or anything on your parent device itself (ix0).
You only need to configure PPPoE for IPv4 and DHCPv6 (this ipv6 is your transfer net/tunnel) on it.
If you request only an IPv6 prefix and use prefix delegation and use over ipv4 (create ipv6 connection on top of ipv4-pppoe) , then pppoe0 speaks over its link-local to the link-local (this is transfer net/tunnel, too, just via link-local) of your ISP-gateway, which is correct that way.

The 'real' wan-side you want to advertise to your dyndns-service is the ipv6 of your lan. Let that sink in, I had some headaches, too.
You must forget and ignore the NAT-thinking. Your real usable ipv6-addresses will always be assigned on the lan-side.
Your ipv6-addresses/traffic on lan are routed over ipv6 transfer net/tunnel on wan.
See it from ISP-side: he cannot know which ipv6-address(es) you will use, so he routes all traffic to the transfer-net, which is only 1 rule. In the transfer net/tunnel there are exactly (only) 2 endpoints (allowed) - your wan-ipv6 and his ipv6-(gateway).

**Comment by fichtner** [comment]
Should be fixed nowadays.
