### ISSUE TITLE
DynDNS: CloudFlare updates fail on multilevel subdomains

### ISSUE THREAD

**Issue by gstuartj** [opnsense/plugins#1299]
When using the DynDNS service with CloudFlare to update a subdomain record with multiple levels, for example "a.b.example.com", the update fails with the error "ERROR - Zone ID was not found" in the logs.

The code in dns/dyndns/src/etc/inc/plugins.inc.d/dyndns/phpDynDNS.inc is not accounting for this usecase, so anything beyond a single-level subdomain does not work.

I was trying to update a record that looked like a.b.c.example.com using OPNsense 19.7.a_442-amd64.

**Comment by fichtner** [comment]
@gstuartj thank you for the patch. I'll try to squeeze this into 19.1.7. But you can always patch up front (to let others know about the fix):

# opnsense-patch -c plugins 31a5b52

(if you run this on your patched version the patch will be removed if it reverts cleanly)


Cheers,
Franc
