### ISSUE TITLE
security/acme-client: During acme.sh execution DNS resolution using internal DNS server times out

### ISSUE THREAD

**Issue by stumbaumr** [opnsense/plugins#1300]
**Describe the bug**
While the acme.sh is executed for a single certificate renewal DNS requests on the OPNsense CLI to the private DNS servers are timing out. The renewal fails.

**To Reproduce**
- Setup OPNsense with a LAN and WAN network
- Configure a DNS server in OPNSense that resides on the LAN network, but goes through the OPNsense to access DNS servers on the WAN side (public DNS like 8.8.8.8)
- Configure a HTTP-01 validation method on the CARP WAN IP of the OPNsense active-passive cluster 
- Configure a certificate for a DNS entry for the CARP IP of the WAN interface
- While executing a forced re-issue of the certificate try resolving internal or external FQDNs 

**Expected behavior**
- DNS resolution should still function while re-issuing a certificate
- Re-issue fails, if there is no public DNS server like 8.8.8.8 configured 

**Relevant log files**
Excerpt from /var/log/acme.sh.log
```
...
[Sun Apr  7 12:20:51 CEST 2019] RSA key
[Sun Apr  7 12:20:54 CEST 2019] GET
[Sun Apr  7 12:20:54 CEST 2019] url='https://acme-v01.api.letsencrypt.org/directory'
[Sun Apr  7 12:20:54 CEST 2019] timeout=
[Sun Apr  7 12:20:54 CEST 2019] _CURL='curl -L --silent --dump-header /var/etc/acme-client/home/http.header  -g '
[Sun Apr  7 12:21:59 CEST 2019] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6
[Sun Apr  7 12:21:59 CEST 2019] ret='6'
[Sun Apr  7 12:21:59 CEST 2019] Can not connect to https://acme-v01.api.letsencrypt.org/directory to get nonce.
[Sun Apr  7 12:21:59 CEST 2019] Can not get domain new authz.
[Sun Apr  7 12:21:59 CEST 2019] pid
...
```

**Environment**
OPNsense 19.1.4 (amd64, OpenSSL).

**Comment by fraenki** [comment]
@stumbaumr To be honest, this looks like a configuration error. I assume your DNS configuration has one or two issues.

acme.sh (and curl) uses the configured resolvers from /etc/resolv.conf. Make sure that these DNS resolvers accept queries from the firewall. I'd suggest to connect to the CLI and test with curl:

`curl -v http://letsencrypt.org`
