### ISSUE TITLE
security/acme-client: feature request for DNS alias mode

### ISSUE THREAD

**Issue by ste-winkler** [opnsense/plugins#1301]
Hi,

in the acme.sh script there is support to use an alternative "service" domain for dns validation. [https://github.com/Neilpang/acme.sh/wiki/DNS-alias-mode](https://github.com/Neilpang/acme.sh/wiki/DNS-alias-mode)

Can you please provide an update to the plugin with an optional text field to use this feature out of the gui? I think it would be best in the validation method form because here you provide the login data and dns provider. 

Thanks a lot!

**Comment by fraenki** [comment]
@ste-winkler Thanks for the suggestions. Will be added soon.

**Comment by fraenki** [comment]
@ste-winkler DNS alias mode will be available in os-acme 1.26. Unfortunately due to my bad timing it won't be in tomorrow's release, but the next release shouldn't be too far away.
