### ISSUE TITLE
net/haproxy: allow for backend without servers

### ISSUE THREAD

**Issue by SebastianS90** [opnsense/plugins#1304]
When no rule matches and there is no default backend, then `haproxy` generates a 503 error. I would like to have a specific 404 error page in that case.

The [easiest solution](https://discourse.haproxy.org/t/how-to-make-haproxy-send-http-404-when-no-acl-get-matched/2900/2) is:
- Add a custom 503 error page with the desired 404 content
- Add a backend without servers and assign it that error page
- Add the backend as default backend to your frontend

But that setup fails, because opnsense treats backends without servers as disabled and they therefore do not end up in the generated configuration file. Can you please rethink the decision made [here](https://github.com/opnsense/plugins/blob/19.1.6/net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf#L1134-L1135)?

**Comment by gstuartj** [comment]
Seconded. It's also sometimes necessary to have a "dummy" backend which forwards users to a different frontend in more complex configs. 

For example: maybe you're doing port-sharing on 443 with multiple protocols, so you need your main listener to be of type TCP. After you determine if a connection is HTTPS you forward to a backend, which then forwards back to an HTTPS frontend.

**Comment by fraenki** [comment]
Sure, this will be added in one of the next releases.

**Comment by fraenki** [comment]
This will be available in the upcoming os-haproxy 2.17.
