### ISSUE TITLE
Plugins do not appear after build

### ISSUE THREAD

**Issue by teliz** [opnsense/plugins#1309]
Hello, 
I made an .iso through the build, copied the sets to an ftp server (I signed my key during the build). everything seemed fine until the moment of updating the firmware, in the plugins tab it appears empty.
*only appears "os-dyndns-devel (installed)"

When I update I receive this message "**There are no updates available on the selected mirror**."

Any clue what to do to make the plugins appear?
thank you guys :)

**I noticed during the build it just displaying plugins with suffix "-devel"
in the path `/usr/obj/usr/tools/config/19.1/OpenSSL:amd64/.pkg/All` all the plugins (prefix "os") appear to have suffix -devel
eg:. `os-acme-client-devel-1.23.txz`, `os-node_exporter-devel-1.0.txz` ,` os-api-backup-devel-1.0.txz` , `os-ntopng-devel-1.2.txz`,` os-arp-scan-devel-1.1.txz`  ... 

when debugging / api / core / firmware / info
Note that json plugins have only one item.
![image](https://user-images.githubusercontent.com/5104527/56532394-0e09cb00-652c-11e9-9eda-45cd48bd88fa.png)

**Comment by mimugmail** [comment]
If you build yourself the default is devel and not stable, thats also the reason you wont find updates on the repo as it is only for stable releases.
