### ISSUE TITLE
DynDNS plugin truncates long passwords without warning user

### ISSUE THREAD

**Issue by jayarmstrong** [opnsense/plugins#1311]
When entering a long, correct password and hitting 'Save' or 'Save and Force Update', the asterisks in the Password field are visibly reduced and the update fails. After changing to a shorter password, the update succeeds.

The long password was probably 50-60 characters.
Using noip.com.
DynDNS 1.14

If the plugin or page JS has a hard limit on password length, it needs to notify the users who exceed it.

**Comment by fichtner** [comment]
I'm unable to confirm what you say it's happening and it would have been strange if there ever was such a bug that is non-local. My best guess is the browser mangles the request.

I added your ticket text as a password. Stores fine:

<img width="1089" alt="Screenshot 2019-04-26 at 5 57 13 AM" src="https://user-images.githubusercontent.com/1915288/56782670-62d96a00-67e8-11e9-89f4-4fbd3f167ef8.png">
