### ISSUE TITLE
Freeradius error

### ISSUE THREAD

**Issue by aatif75** [opnsense/plugins#1316]
Hi. our Daloradius Freeradius just stop working i got the following error message":

Error: Unresponsive child for request 80836, in component <core> module

Any idea what is wrong.. I would appreiciate your help

**Comment by mimugmail** [comment]
Too few informations like did it work before, what happened that it breaks
etc.

aatif75 <notifications@github.com> schrieb am Mo., 29. Apr. 2019, 19:03:

**Comment by aatif75** [comment]
First of all i thanks you for responding this fast. Actually our Radius has been working for past 3 years without any problem. but since last 3 months we have been having this issue frequently and i don't know the solution to it. Let me give you the entire log report here:

Mon Apr 29 11:41:50 2019 : Error: Unresponsive child for request 80836, in component <core> module
Mon Apr 29 11:41:50 2019 : Error: Unresponsive child for request 80837, in component <core> module
Mon Apr 29 11:41:50 2019 : Error: Unresponsive child for request 80838, in component <core> module
Mon Apr 29 11:41:50 2019 : ERROR: (84199)  ERROR: sql : Received conflicting packet from client asr-lns port 1646 - ID: 150 due to unfinished request.  Giving up on old request.
Mon Apr 29 11:41:50 2019 : ERROR: (84200)  ERROR: sql : Received conflicting packet from client asr-lns port 1646 - ID: 151 due to unfinished request.  Giving up on old request.
Mon Apr 29 11:41:50 2019 : Error: Unresponsive child for request 80839, in component <core> module
Mon Apr 29 11:41:50 2019 : Error: Unresponsive child for request 80840, in component <core> module
Mon Apr 29 11:41:50 2019 : ERROR: (84203)  ERROR: sql : Received conflicting packet from client asr-lns port 1646 - ID: 154 due to unfinished request.  Giving up on old request.
Mon Apr 29 11:41:50 2019 : Error: Unresponsive child for request 80850, in component <core> module
Mon Apr 29 11:41:50 2019 : Error: Unresponsive child for request 80851, in component <core> module
Mon Apr 29 11:41:50 2019 : Error: Unresponsive child for request 80852, in component <core> module
Mon Apr 29 11:41:50 2019 : Error: Unresponsive child for request 80853, in component <core> module
Mon Apr 29 11:41:50 2019 : Error: Unresponsive child for request 80855, in component <core> module
Mon Apr 29 11:41:50 2019 : Error: Unresponsive child for request 80856, in component <core> module
Mon Apr 29 11:41:50 2019 : Error: Unresponsive child for request 80857, in component <core> module
Mon Apr 29 11:41:50 2019 : Error: Unresponsive child for request 80858, in component <core> module
Mon Apr 29 11:41:50 2019 : Error: Unresponsive child for request 80861, in component <core> module
Mon Apr 29 11:41:50 2019 : Error: Unresponsive child for request 80865, in component <core> module
Mon Apr 29 11:41:50 2019 : Error: Unresponsive child for request 80866, in component <core> module
Mon Apr 29 11:41:50 2019 : Error: Unresponsive child for request 80867, in component <core> module
Mon Apr 29 11:41:50 2019 : ERROR: (84207)  ERROR: sql : Received conflicting packet from client asr-lns port 1646 - ID: 158 due to unfinished request.  Giving up on old request.

**Comment by mimugmail** [comment]
Is this related to OPNsense? Sql support was newly introduced

**Comment by mimugmail** [comment]
@fichtner can we close please? seems use has chosen wrong repo/project.
