### ISSUE TITLE
FreeRADIUS 3.0.19 not starting after upgrade to 19.1.7

### ISSUE THREAD

**Issue by pmasterc3** [opnsense/plugins#1322]
After the upgrade of Opnsense to 19.1.7 FreeRADIUS doesn't start any more on my firewall:

root@OPNsense-fw:/usr/local/etc/raddb # radiusd -X
...
including configuration file /usr/local/etc/raddb/mods-enabled/unix
including configuration file /usr/local/etc/raddb/mods-enabled/always
including configuration file /usr/local/etc/raddb/mods-enabled/unpack
including configuration file /usr/local/etc/raddb/mods-enabled/utf8
including configuration file /usr/local/etc/raddb/mods-enabled/sql
including configuration file /usr/local/etc/raddb/mods-config/sql/main/sqlite/queries.conf
including configuration file /usr/local/etc/raddb/mods-enabled/counter
including configuration file /usr/local/etc/raddb/mods-enabled/ldap
including configuration file /usr/local/etc/raddb/mods-enabled/sqlippool
including configuration file /usr/local/etc/raddb/mods-config/sql/ippool/sqlite/queries.conf
**/usr/local/etc/raddb/mods-config/sql/ippool/sqlite/queries.conf[102]: Reference "${attribute_name}" not found**
/usr/local/etc/raddb/mods-config/sql/ippool/sqlite/queries.conf[119]: Reference "${attribute_name}" not found
/usr/local/etc/raddb/mods-config/sql/ippool/sqlite/queries.conf[133]: Reference "${attribute_name}" not found
including configuration file /usr/local/etc/raddb/mods-enabled/dhcp_sqlippool
including files in directory /usr/local/etc/raddb/policy.d/
including configuration file /usr/local/etc/raddb/policy.d/accounting
including configuration file /usr/local/etc/raddb/policy.d/canonicalization
including configuration file /usr/local/etc/raddb/policy.d/control
including configuration file /usr/local/etc/raddb/policy.d/cui
including configuration file /usr/local/etc/raddb/policy.d/debug
including configuration file /usr/local/etc/raddb/policy.d/dhcp
including configuration file /usr/local/etc/raddb/policy.d/eap
including configuration file /usr/local/etc/raddb/policy.d/filter
including configuration file /usr/local/etc/raddb/policy.d/moonshot-targeted-ids
including configuration file /usr/local/etc/raddb/policy.d/operator-name
including configuration file /usr/local/etc/raddb/policy.d/abfab-tr
including files in directory /usr/local/etc/raddb/sites-enabled/
including configuration file /usr/local/etc/raddb/sites-enabled/inner-tunnel
including configuration file /usr/local/etc/raddb/sites-enabled/default
including configuration file /usr/local/etc/raddb/sites-enabled/dhcp
/usr/local/etc/raddb/mods-config/sql/ippool/sqlite/queries.conf[102]: Reference "${attribute_name}" not found
**Errors reading or parsing /usr/local/etc/raddb/radiusd.conf**
root@OPNsense-fw:/usr/local/etc/raddb # radiusd -v
radiusd: FreeRADIUS Version 3.0.19, for host amd64-portbld-freebsd11.2, built on May  1 2019 at 00:39:37
FreeRADIUS Version 3.0.19
Copyright (C) 1999-2019 The FreeRADIUS server project and contributors
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE
You may redistribute copies of FreeRADIUS under the terms of the
GNU General Public License
For more information about these matters, see the file named COPYRIGHT
root@OPNsense-fw:/usr/local/etc/raddb # 

From the upgrade log:
May 2 22:39:49 | pkg-static: **freeradius3 upgraded: 3.0.17_4 -> 3.0.19**
May 2 22:39:48 | pkg-static: opnsense upgraded: 19.1.6 -> 19.1.7
May 2 22:39:39 | pkg-static: os-dyndns upgraded: 1.14_1 -> 1.15
...

**Comment by mimugmail** [comment]
Sorry, cannot reproduce here. The file wasn't touched since 2017. Perhaps you did some manual changes to it?

**Comment by pmasterc3** [comment]
Hi,

I am not aware that I did some manual changes to those files. I did now a clean installation of OPNsense in a VirtualBox. And also there it shows the same error as soon as "Enable SQLite" was enabled in the FreeRADIUS general page.  In this installation also FreeRADIUS in version 3.0.19 got installed. BTW: The VirtualBox clean installation is on OPNsense 19.1.4

**Comment by mimugmail** [comment]
Hm, ok, on a fresh install I have similar issues. Seems FR has restructured their syntax. You can downgrade with 

opnsense-revert -r 19.1.6 freeradius3

**Comment by pmasterc3** [comment]
Thanks. Deactivating SQLite also did the job.

**Comment by mimugmail** [comment]
Please reopen / reassign ... I'm still on this, having a stale branch.
3.0.19 did a whole rewrite for SQLite which breaks things , but ATM SQLite has "no use-case" right now.
