### ISSUE TITLE
dnscrypt crashing

### ISSUE THREAD

**Issue by L1ghtn1ng** [opnsense/plugins#1326]
After following https://github.com/opnsense/docs/pull/169 and setting the listen address to :53, have setup to use cloudflares DoH servers only and due to my isp not supporting IPv6 yet I have blocked IPv6 in DNScrypt. Have setup overrides and enabled DNSBL/RPZ and have entries in the whitelist. It seems that DNScrypt keeps crashing or not responding as DNS lookups just stop working, only after restarting DNScrypt that things start working for a short amount of time and then back to square one
CC @mimugmail

**Comment by L1ghtn1ng** [comment]
![image](https://user-images.githubusercontent.com/3628354/57237438-1fb89b80-701f-11e9-8bed-83c8f54d5e29.png)

**Comment by L1ghtn1ng** [comment]
![image](https://user-images.githubusercontent.com/3628354/57237483-365ef280-701f-11e9-9104-2baaa36ff54b.png)

**Comment by L1ghtn1ng** [comment]
This is what happens when dnscrypt stops responding
![image](https://user-images.githubusercontent.com/3628354/57239780-ca7f8880-7024-11e9-9443-b2692ed95073.png)

**Comment by mimugmail** [comment]
What do you see in General Log?

**Comment by L1ghtn1ng** [comment]
@mimugmail only
![image](https://user-images.githubusercontent.com/3628354/57240863-83df5d80-7027-11e9-90fc-c0195012fae8.png)

**Comment by L1ghtn1ng** [comment]
@mimugmail from my mobile as that is the only thing that I have now configured to use DNSCrypt it I get DNS_probe_finished_bad_config when trying to browse to any site

**Comment by L1ghtn1ng** [comment]
@mimugmail From the picture in General log that is from me clearing the log out after doing a complete stop of the service and and starting it back up, on Opnsense 19.1.7 amd64 LibreSSL

**Comment by mimugmail** [comment]
Do you have the chance to switch to OpenSSL for testing?

**Comment by L1ghtn1ng** [comment]
@mimugmail Yeah will give it ago

**Comment by L1ghtn1ng** [comment]
@mimugmail I rebooted after installing openssl and dnscrypt was not working at all, restarted it and it was working longer than it has previously but still ends up not responding
![image](https://user-images.githubusercontent.com/3628354/57243024-f30b8080-702c-11e9-87ee-9550d6f32ca8.png)

**Comment by L1ghtn1ng** [comment]
Also *.googleapis.com is in my whitelist

**Comment by L1ghtn1ng** [comment]
@mimugmail This is what I am using in my DNSBL
![image](https://user-images.githubusercontent.com/3628354/57243275-a5dbde80-702d-11e9-83bc-3fceaad1783b.png)

**Comment by mimugmail** [comment]
Can you send me the dnscrypt part of your config.xml so I can test here?

**Comment by L1ghtn1ng** [comment]
Where is the config.xml located?

**Comment by L1ghtn1ng** [comment]
@mimugmail I have found it, got an email I can send it to?

**Comment by mimugmail** [comment]
/config/config.xml

**Comment by mimugmail** [comment]
https://github.com/opnsense/plugins/blob/master/dns/dnscrypt-proxy/Makefile#L5

**Comment by L1ghtn1ng** [comment]
@mimugmail email sent

**Comment by mimugmail** [comment]
I was able to reproduce, can you try disabling "Use IPv6 Servers"?

Am Mo., 6. Mai 2019 um 20:18 Uhr schrieb J.Townsend <
notifications@github.com>:

**Comment by L1ghtn1ng** [comment]
Will try after work
________________________________

**Comment by L1ghtn1ng** [comment]
@mimugmail After some long testing this seems to have fixed the issue
________________________________

**Comment by mimugmail** [comment]
Great, can you close please.

**Comment by L1ghtn1ng** [comment]
@mimugmail Might be worth putting in a check or warning to say that if you do not have IPv6 from your ISP that having it on will cause it to break?

**Comment by L1ghtn1ng** [comment]
@mimugmail I have the issue again, this time the DNS is working but for some reason it is not blocking anything. I have removed the cloudflare ipv6 server even though I have the option to block ipv6 hosts ticked and am still using openssl instead of libressl
________________________________

**Comment by mimugmail** [comment]
I can not reproduce here, are you still experiencing issues?

**Comment by L1ghtn1ng** [comment]
After updating to the new version of opnsense and having access to the new lists it seems to be due to missing links to block from what I have observed. This can be closed now and thanks for your help

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by fichtner** [comment]
Thanks for the update ❤️
