### ISSUE TITLE
net/wireguard: tunnel shutdown after random time

### ISSUE THREAD

**Issue by toffelwurst** [opnsense/plugins#1331]
**Versions (on both ends):**
```
os-wireguard-devel-0.9
OPNsense 19.1.7-amd64
FreeBSD 11.2-RELEASE-p9-HBSD
OpenSSL 1.0.2r 26 Feb 2019
```
**Problem description:**
I have a simple site-to-site setup, where one side has a static IP (remote) and my LAN side wich is a normal cable internet connection with dynamic IP from the provider. Unfortunately IPv4 is through a DS-Lite-Tunnel.
The Wireguard tunnel is initiated by the local opnsense  and the connection is working a random amount of time. But once in a while (i think mostly when the connection is idle and no traffic is passing through) the tunnel shuts down. The wg0 interface is still present and both sides show "latest handshake: x hour ago" but there are no new handshakes and no connection / traffic is possible to the remote side or backwards.
Restarting the Wireguard services with the webgui or via ssh doens't help. The only way i can bring up the tunnel again is by changing the listening port under "local" and press save or by restarting the whole opnsense appliance.

Can't really figure out how to trouble shoot this. Could the DS-Lite setup of my provider cause these kind of problems?
There is also a tunnel from my iPhone to the remote side wich is stable all the time, so i guess the problem resides somwhere on the local opnsense.
Just let me know if you need any further information

**Comment by mimugmail** [comment]
Yes, could be DS Lite but since I dont have such access it's quite hard to teoubleshoot

**Comment by mimugmail** [comment]
I try to implement PersistentKeepalive option with 0.10, perhaps this fixes it

**Comment by toffelwurst** [comment]
Isn't there a Keepalive option yet?
I have now started a permanent ping trough the tunnel from another VM to see if the breakdown appears only on idle.

**Comment by mimugmail** [comment]
Oh yes, seems I implemented one :) And you tried on both sides with interval 20? Doesn't work?
Then you should rather google for known Wireguard and DS-Lite problems

**Comment by toffelwurst** [comment]
At the moment i have a value of 25 on both ends as Keepalive. Wich doesn't seem to help. I can test to set the value (which i think is seconds?) to 20 or below. Will test with 10 or even 5 too.
There are also some good news. Since i started pinging the remote opnsense through the tunnel continuously, there was no breakdown of the connection. The tunnel has now a uptime of roughly 20h, which i think is the longest i ever got.

After some research on google i couldn't find problems like mine affecting wireguard with DS-Lite. Also the fact that two smartphones are in the same network with the same internet connection which have no problems with the wireguard vpn at all, make me believe the problem isn't the DS-Lite here.
I will set up a small Debian VM to test a wireguard connection to the remote opnsense to see, if the tunnel keeps resetting there too.
Will report the outcomes ;-)

**Comment by toffelwurst** [comment]
After a week of testing it looks like setting the keepalive to 20 seconds fixed the problem.
Also it must have to do something with the local opensense, because the plain debian vm with Wireduard installed only and without any keepalive value set, didn't had any problems.

Never the less, thank you for your tips and sorry, that i didn't figure out the lower keepalive by myself and i had to steal your time. I close this issue now. :)

**Comment by mimugmail** [comment]
Maybe the debian sends some DNS requests or so via tunnel so it keeps up :) 
Glad it's fixed for you.
