### ISSUE TITLE
DnsCrypt add new lists

### ISSUE THREAD

**Issue by L1ghtn1ng** [opnsense/plugins#1333]
Hey @mimugmail can you please add these as new list options please?

There maybe ones that you have already added.

https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
https://mirror1.malwaredomains.com/files/justdomains
http://sysctl.org/cameleon/hosts
https://zeustracker.abuse.ch/blocklist.php?download=domainblocklist
https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
https://hosts-file.net/ad_servers.txt
https://urlhaus.abuse.ch/downloads/text/
https://zeustracker.abuse.ch/blocklist.php?download=baddomains
https://hosts-file.net/psh.txt
https://hosts-file.net/fsa.txt
https://hosts-file.net/emd.txt
https://hosts-file.net/pup.txt
https://blocklist.site/app/dl/fraud
https://blocklist.site/app/dl/phishing
https://blocklist.site/app/dl/ads
https://blocklist.site/app/dl/malware

**Comment by fichtner** [comment]
pasting them in text would be a lot more helpful to the maintainer :>

**Comment by L1ghtn1ng** [comment]
I have updated it with the domains as I have found where they where stored on the pihole

**Comment by L1ghtn1ng** [comment]
Also wondering does this plugin support removing duplicates between the lists that people select?

**Comment by mimugmail** [comment]
Sure https://github.com/opnsense/plugins/blob/master/dns/dnscrypt-proxy/src/opnsense/scripts/OPNsense/Dnscryptproxy/dnsbl.sh#L167

**Comment by mimugmail** [comment]
Lists not in use:

https://hosts-file.net/ad_servers.txt
https://urlhaus.abuse.ch/downloads/text/
https://zeustracker.abuse.ch/blocklist.php?download=baddomains
https://hosts-file.net/psh.txt
https://hosts-file.net/fsa.txt
https://hosts-file.net/pup.txt
https://blocklist.site/app/dl/fraud
https://blocklist.site/app/dl/phishing
https://blocklist.site/app/dl/ads
https://blocklist.site/app/dl/malware


I'll check them now one by one ...

**Comment by mimugmail** [comment]
I'll add 

https://hosts-file.net/ad_servers.txt
https://hosts-file.net/psh.txt
https://hosts-file.net/fsa.txt
https://hosts-file.net/pup.txt
https://blocklist.site/app/dl/fraud
https://blocklist.site/app/dl/phishing
https://blocklist.site/app/dl/ads

to dnscrypt and bind the next days, the others are no fun to integrate. Let's see if the above are enough.

**Comment by mimugmail** [comment]
Can we close this one?
