### ISSUE TITLE
net/upnp:  remove static port & allow port randomization by default

### ISSUE THREAD

**Issue by bsd-source** [opnsense/plugins#1340]
Currently OPNsense uses 2189 as a static HTTP port in the miniupnpd.conf file which is the same static port pfsense started using several years ago. If an HTTP port is not set in the miniupnpd.conf file **miniupnpd will automatically generate a random port when started as a security measure**.

I would like to see a webui option under the universal plug and play settings to set a static port. The default setting for this port should be empty to allow port randomization. An information (I) description would also be helpful.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
