### ISSUE TITLE
net/upnp: webui bug under UPNP settings when selecting information icon

### ISSUE THREAD

**Issue by bsd-source** [opnsense/plugins#1341]
Selecting the information icon next to "Interfaces (generally LAN)" in the universal plug and play settings doesn't expand and show the information. Selecting the information icon next to "External Interface" expands both "External Interface" and "Interfaces (generally LAN)" information. Must be a an issue in the services_upnp.php file.

**Comment by azdps** [comment]
To fix this issue with services_upnp.php file change line number 254 from:

<div class="hidden" data-for="help_for_ext_iface">

to

<div class="hidden" data-for="help_for_iface_array">

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
