### ISSUE TITLE
net/haproxy: Allow hyphens in Server Name

### ISSUE THREAD

**Issue by DiegoQueiroz** [opnsense/plugins#1346]
The HAProxy conf allows us to use hyphens while naming servers (frontend and backend), so the haproxy plugin should support it as well.

This may seem a cosmetic issue, but some directives, like `http-send-name-header` expose this value in the header.

A very common setting is `http-send-name-header Host`, which send the server name as Host header (required for some webservers to work). Without the hability to use valid DNS names (which contains hyphens), I have to workaround this limitation.

**Comment by fraenki** [comment]
@DiegoQueiroz Thanks for your report! I consider this a bug, since there was never a good reason to disallow hyphens.

You can test the fix like this:

`opnsense-patch -c plugins 8ece4c87`
