### ISSUE TITLE
Quagga: startup errors / or only display error

### ISSUE THREAD

**Issue by mimugmail** [opnsense/plugins#135]
In my lab with 4 routers (circled) I have 3 of them with devel 1.0.1 and 1 with stable 1.0.0.
When I shut all systems down und start again the quagga services are startet (ps aufx), but in UI it's marked red. Restarting via UI throws:

```
Apr 27 11:35:10 OPN4 configd.py: [2dfba479-7ba1-46d3-b56b-cea3fb6ffa6b] starting quagga
Apr 27 11:35:11 OPN4 configd.py: [2dfba479-7ba1-46d3-b56b-cea3fb6ffa6b] returned exit status 1
```

Also when enabling OSPF e.g. the UI is still red, but the new process is running. 

This happens with 1.0.0 and 1.0.1. 

In system.log there's no error when booting the system besides 
`Apr 27 11:31:50 OPN4 api[48004]: no active session, user not found`
but I'm not sure if this is quagga related

**Comment by fabianfrz** [comment]
@mimugmail can you restart it or query the status?

It is also red if one of the configured services fails to start - in my case this is often BGP

**Comment by mimugmail** [comment]
@fabianfrz I can restart it via 

```
root@OPN1:~ # configctl quagga restart
OK

```

Via status_services.php I can only try to start it because it thinks it's down. Starting it it fails with the error above.

The protocols are all working fine, only the status is displayed wrong.

**Comment by fabianfrz** [comment]
You can try this patch: #136 if this fixes the problem, please close the issue by yourself.

**Comment by mimugmail** [comment]
Great, works fine! Thanks
