### ISSUE TITLE
c-icap templates not created on start (in tmp dir)

### ISSUE THREAD

**Issue by Kimotu** [opnsense/plugins#1352]
I use option

> /tmp RAM disk | Use memory file system for /tmp

It seems as c-icap copies its templates to `/tmp/c-icap/templates/virus_scan/en` when you save the settings. This means that after firewall reboot, the templates get wiped.
So, either c-icap should use the original location (where are the copied from) or the start-script of c-icap must check templates and copy them if not existing.

Currently I setup a monit script to check templates and remind me that when I reboot, I have to press SAVE in the service settings to create those templates.

**Comment by fichtner** [comment]
In general, all templates will be created before services are started.

**Comment by fichtner** [comment]
Ok, I think we are talking about the same thing and a change (likely in the plugin) fixed this at some point. Thanks for the feedback. 😊
