### ISSUE TITLE
mail/rspamd: Wrong permissions on created spamtrap.map

### ISSUE THREAD

**Issue by Machiavelli6914** [opnsense/plugins#1353]
Hello,

running a up-to-date OPNSense (19.1.8) with os-rspamd 1.5 we discovered that the spamtrap.map throws a permission denied.

```bash
root@OPNsense1:/usr/local/etc/rspamd/maps.d # ls -la
total 12
drwxr-x--x  2 root  wheel   512 May 24 15:55 .
drwxr-xr-x  6 root  wheel  1536 May 24 15:55 ..
-rw-r-----  1 root  wheel    53 May 27 14:24 spamtrap.map
```

Adding following to /usr/local/opnsense/scripts/rspamd/setup.sh solves the issue
```
chmod o+r /usr/local/etc/rspamd/maps.d/* 
```

**Comment by mimugmail** [comment]
Do you want to add the commit and version bump on your own? :)

**Comment by Machiavelli6914** [comment]
@mimugmail Can do, if you want me to

**Comment by mimugmail** [comment]
I added it to my branch, but it'll take some days to commit, I also want to add global sender whitelisting to rspamd. Is this ok for you?
https://github.com/mimugmail/plugins/blob/rspamd/mail/rspamd/src/opnsense/scripts/rspamd/setup.sh#L8
