### ISSUE TITLE
security/acme-client: automation custom script

### ISSUE THREAD

**Issue by AlexanderLJ** [opnsense/plugins#1358]
I don't seem to be able to find it anyway, is it possible to run a custom script as automation?

**Comment by fabianfrz** [comment]
Actions implemented in the plugin can be found here:

https://github.com/opnsense/plugins/blob/master/security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml#L709-L713

In your case the easiest way is creating a custom configd command and call that from the acme plugin.

**Comment by fabianfrz** [comment]
here you can find some documentation for configd:

https://docs.opnsense.org/development/backend/configd.html?highlight=configd

**Comment by fraenki** [comment]
@AlexanderLJ If I understand your request correctly, then you want to be able to add arbitrary scripts to a Let's Encrypt Automation job. For security reasons, this is not supported.

If you have a specific use-case, for example "copy certificate to a remote host using scp", then please open a feature request and explain this use-case in-detail. We may then be able to add it as official feature to our Let's Encrypt plugin.

For a detailed discussion why we don't allow arbitrary code to be added, see this issue:
https://github.com/opnsense/plugins/issues/100

**Comment by ed006949** [comment]
> configd

is not functional enough - how to pass parameters or even cert path via environment or something?
