### ISSUE TITLE
OpenConnect Startup - deletion failed for interface

### ISSUE THREAD

**Issue by imidoriya** [opnsense/plugins#1359]
I'm getting this error on startup, which appears to prevent OpenConnect from starting.  I have to start it manually.

```
kernel: ocvpn0: link state changed to DOWN
kernel: ifa_maintain_loopback_route: deletion failed for interface ocvpn0: 3
kernel: OK
kernel: tun30000: changing name to 'ocvpn0'
kernel: tun30000: link state changed to UP
```

I'm trying to understand how best to NAT.  [In this documentation](https://www.routerperformance.net/using-openconnect-with-newly-released-opnsense-18-1-1/), it states to use the OpenConnect "interface" (which doesn't show up as an Interface, but does show up under Firewall Rules).  However, in other places [1,](https://forum.opnsense.org/index.php?topic=12144.msg55621#msg55621) [2](https://github.com/opnsense/plugins/issues/1135), it is suggested creating an interface and locking it.  But then you end up with two things under Firewall rules.   I just need this thing to be persistent after reboot where it starts up automatically and NAT rules apply.

**Comment by chriscorns** [comment]
I have the same problem and the same messages in error log in my test installation: OpenConnect could not start automaticly after startup. I use the last version 19.7.3. What is the problem? I also tried to setup OPNsense without explicitly assigning the interface **`ocvpn0`**...
```
Sep  9 16:05:58 OPNsense kernel: OK
Sep  9 16:06:00 OPNsense kernel: tun30000: link state changed to UP
Sep  9 16:06:04 OPNsense kernel: tun30000: changing name to 'ocvpn0'
Sep  9 16:06:05 OPNsense monit[77410]: Starting Monit 5.26.0 daemon with http interface at /var/run/monit.sock 
Sep  9 16:06:05 OPNsense monit[46259]: Monit will delay for 120s on first start after reboot ... 
Sep  9 16:06:05 OPNsense kernel: ipfw2 (+ipv6) initialized, divert loadable, nat loadable, default to accept, logging disabled
Sep  9 16:06:05 OPNsense kernel: DUMMYNET 0 with IPv6 initialized (100409)
Sep  9 16:06:05 OPNsense kernel: load_dn_sched dn_sched FIFO loaded
Sep  9 16:06:05 OPNsense kernel: load_dn_sched dn_sched QFQ loaded
Sep  9 16:06:05 OPNsense kernel: load_dn_sched dn_sched RR loaded
Sep  9 16:06:05 OPNsense kernel: load_dn_sched dn_sched WF2Q+ loaded
Sep  9 16:06:05 OPNsense kernel: load_dn_sched dn_sched PRIO loaded
Sep  9 16:06:05 OPNsense kernel: load_dn_sched dn_sched FQ_CODEL loaded
Sep  9 16:06:05 OPNsense kernel: load_dn_sched dn_sched FQ_PIE loaded
Sep  9 16:06:05 OPNsense kernel: load_dn_aqm dn_aqm CODEL loaded
Sep  9 16:06:05 OPNsense kernel: load_dn_aqm dn_aqm PIE loaded
Sep  9 16:06:05 OPNsense kernel: Bump sched buckets to 256 (was 0)
Sep  9 16:06:05 OPNsense kernel: Bump sched buckets to 256 (was 0)
Sep  9 16:06:07 OPNsense kernel: OK
Sep  9 16:06:08 OPNsense kernel: SHA256 93 E3 6E 71 1B 17 F1 39 EE 1A 87 BA 77 7A 8C 55
Sep  9 16:06:08 OPNsense kernel: ifa_maintain_loopback_route: deletion failed for interface ocvpn0: 3
Sep  9 16:06:08 OPNsense kernel: ocvpn0: link state changed to DOWN
```
A manual start is no problem:
```
Sep  9 16:34:46 OPNsense kernel: ocvpn0: link state changed to UP
```
@mimugmail: Can you have a look at the issue next time, please? THX

**Comment by mimugmail** [comment]
It seems your default gateway is not available during startup so openconnect fails.
Sadly it behaves a bit different than openvpn. If it fails cause if timeout, it quits and doesn't try again.
