### ISSUE TITLE
net/wol: broadcast may be calculated incorrectly

### ISSUE THREAD

**Issue by fabianfrz** [opnsense/plugins#1368]
https://forum.opnsense.org/index.php?topic=10671.0;topicseen

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.

**Comment by szotsaki** [comment]
For the curious, this issue got fixed in the meantime. The code now looks like:

```php
private function calculateSubnetBroadcast($ip_addr, $cidr)
{
    // TODO undefined offset
    $parts = explode('.', $ip_addr);
    $int_ip = ((int)$parts[0]) << 24 | ((int)$parts[1]) << 16 | ((int)$parts[2]) << 8 | (int)$parts[3];
    $hostmask = (2 << (31 - $cidr)) - 1;
    $int_bcast = $int_ip | $hostmask;
    return implode('.', array(
        ($int_bcast >> 24) & 255,
        ($int_bcast >> 16) & 255,
        ($int_bcast >> 8) & 255,
        $int_bcast & 255,
    ));
}
```
