### ISSUE TITLE
Wireguard missing in firewall

### ISSUE THREAD

**Issue by patrick7** [opnsense/plugins#1369]
I'm not able to see wireguard in the firewall section (newest opnsense version).

**Comment by mimugmail** [comment]
Interface will appear when daemon is enabled

**Comment by patrick7** [comment]
@mimugmail It is enabled but wireguard does not appear :(

**Comment by mimugmail** [comment]
When you edit a firewall rule and save again. Does it appear?

**Comment by patrick7** [comment]
Yes :-)

**Comment by mimugmail** [comment]
Close please ..

**Comment by patrick7** [comment]
Isn't that a bug which should be fixed?

**Comment by mimugmail** [comment]
No, filter sometimes need a reload which can be triggered via editing a rule. Also affects other VPNs
