### ISSUE TITLE
HW suggestion 2xSFP+ & 4 x 10/100/1000BaseT RJ-45

### ISSUE THREAD

**Issue by MyraBaba** [opnsense/plugins#1373]
Hi,

What is the alternatives for 2 x SFP+ 10Gb/s+  &   4 x 10/100/1000BaseT RJ-45?

Total Throughput min 7.8 Gbps
Min 75000 connection per sec.
AES 256 IPSEC/SSL-VPN min 1 Gbps

Can opnsense achive this with a minimum Hw ? (cheapeast I mean )

**Comment by AdSchellevis** [comment]
please use our forum (https://forum.opnsense.org/) for discussion about hardware. the plugin repository isn't the right place for this.

**Comment by MyraBaba** [comment]
@AdSchellevis sorry thanks..
