### ISSUE TITLE
security/acme-client: Auto renew doesn't seem to create cron job

### ISSUE THREAD

**Issue by Flightkick** [opnsense/plugins#1377]
I might be misinterpreting how auto renewal works but in my case my certificate managed to expire.
According to the UI as well as the acme.sh.log file, acme-client did not run automatically since the certificate was initially created.

![General Let's Encrypt Config](https://user-images.githubusercontent.com/8693699/60076719-8eb19700-9728-11e9-87a2-9af78c9a2ba4.png)

![Certificate Config](https://user-images.githubusercontent.com/8693699/60076739-9c671c80-9728-11e9-85bf-e31c944128a4.png)

In `/ui/cron` I don't see any acme-client / Let's Encrypt jobs.

**Comment by fraenki** [comment]
You have to check "Auto Renewal" in `Services: Let's Encrypt: Settings` and click on "Apply". It immediately creates the required cronjob. I've just verified it on the latest release, it's working for me.

If it does not work for you, please check `System: Log Files: General` and `System: Log Files: Backend`. These logs might contain a hint why it's not working for you.

**Comment by fraenki** [comment]
@Flightkick Let me know if you need further assistance, I'll reopen the issue in this case.
