### ISSUE TITLE
security/acme-client: Last Acme status not correctly updated on force certificate renew

### ISSUE THREAD

**Issue by Flightkick** [opnsense/plugins#1378]
I have force renewed this certificate. The acme.sh.log shows the action was successful. The certificate is actually renewed but the last acme status still shows 'validation failed'.

![Last Acme status shows validation failed](https://user-images.githubusercontent.com/8693699/60077523-73478b80-972a-11e9-8739-00c0b098b18c.png)

If I recall correctly this is how I ended up in this state (very specific but might apply to other cases as well):
1. Create account in the accounts section (leaving e-mail field blank)
2. Create certificate in the certificate section
3. Certificate expired (my autorenew seemed to be broken)
4. Updated my account created at step 1 to include my e-mail (so I would get mail from Let's Encrypt if it is broken in the future)
5. Click the big orange `Issue/Renew Certificates Now` button
Validation will fail:
`Challenge error: {
  "type": "urn:ietf:params:acme:error:unauthorized",
  "detail": "User account ID doesn't match account ID in authorization",
  "status": 403
}
`
6. Click the small `Force renew` button on the record row
Now it seems to renew succesfully but the last status column is not updated.

**Comment by Zewwy** [comment]
Yup I have noticed this bug, when a certificate fails to be validated for "X" reason,, rason is fixed, click renew/issue cert, in acme log file shows cert_success, but UI still shows failed.

**Comment by fraenki** [comment]
Duplicate of #1307.
