### ISSUE TITLE
Tor: security optimizing - set *only* listening IP instead of listening interface(+all IPs)

### ISSUE THREAD

**Issue by mr44er** [opnsense/plugins#1379]
The **only** option for listening interface isn't optimal. There should be added another option, on which IP(s) on the chosen interface it should listen.

If you have multiple IPs assigned on the listening interface, tor will listen on every IP on the interface, which could lead to big security problems. In my case it should **not** listen on ipv6.
The log says it:
`Jun 26 14:22:45.175 [notice] You configured a non-loopback address 'x.x.x.x:PORT' for SocksPort. This allows everybody on your local network to use your machine as a proxy. Make sure this is what you wanted.
Jun 26 14:22:45.175 [warn] You specified a public address '[xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx]:PORT' for SocksPort. Other people on the Internet might find your computer and use it as an open proxy. Please don't allow this unless you have a good reason.`

I know you need the open port in the firewall and ACL to reach, but it should'nt basically be that way.

**Comment by fabianfrz** [comment]
TOR is not meant to be run on a router. So this is why this warning is printed. It is also not enough to get access to the port since you still have to have an allow rule in the ACL.

This warning is intended for home users or people running TOR on a public server, where listening on 127.0.0.0/0 and ::1/128 should be enough. That's not the case for OPNsense in client mode. On OPNsense it is intended to offer the SOCKS-Proxy to the network if desired - also for example as a transparent proxy.

So from my point of view it works as intended.

**Comment by mr44er** [comment]
Sorry for the late answer. Busy life 'n such. :/

> TOR is not meant to be run on a router.

I know, but...

> So this is why this warning is printed.

...this feels wrong for me. Maybe misunderstanding between us?

> It is also not enough to get access to the port since you still have to have an allow rule in the ACL.

That's right. This + open port. It's more of an _autistic do it 100% right_-thingie. ;)

https://docs.opnsense.org/manual/how-tos/tor.html

>Listen Interfaces:
 Add one or multiple interfaces, on which Tor should listen additionally to the loopback interface. This is required if you want to use Tor from other computers than the appliance itself. Tor will bind on the statically configured IP address from your interface configuration. If the interface has no static IP configured, it will be ignored.

I am one of the few lucky persons in Germany to have Global Unicast-Adresses at my home connection, so I have it static. You know, what I mean? I can't separate properly ipv4/ipv6 on the interface, when I really want more than loopback and binding is _automatically_ in dependance on static ip.
Sure, with ACL and fw-port in mind, maybe it is autistic vs. cosmetic.

**Comment by fabianfrz** [comment]
> I can't separate properly ipv4/ipv6 on the interface, when I really want more than loopback and binding is automatically in dependance on static ip.

It will bind to the IP addresses it will find in the interface section. If none is configured (i. e. you are using DHCPv6 or SLAAC), then there is no static IP address to bind. This is the same as it does for IPv4.

It will not look up the current adapter configuration to find out which IP addresses are currently assigned.

**Comment by mr44er** [comment]
I don't use DHCPv6 or SLAAC or 'Track Interface', I configured everything static. ;)
So....that is the problem.
