### ISSUE TITLE
security/acme-client Delete Cert does not Delete certificate

### ISSUE THREAD

**Issue by Zewwy** [opnsense/plugins#1380]
I've noticed the following bug while using the ACME plugin.

After setup, and creating a certificate.

Select the certificate and click the delete icon.

Attempt to recreate the certificate (create new cert w/ same common name and SANs):

Expected: 

 Issue Success and only one of this certificate selectable in the UIs options

Actually happens:

 /var/etc/acme.sh.log states "Certificate has not reached renewal date use --force"
have to manually delete all associated folder (acl GUID) under:
/var/etc/acme-client/certs/GUID
/var/etc/acme-client/keys/GUID
/var/etc/acme-client/configs/GUID
/var/etc/acme-client/home/commonname

Only then can I request the same cert and it succeed, then leaves the final bug of the UI having two certificates listed in drop downs to choose from. there should only be the new one, not both which includes the non-existent certificate.

Please advise.

**Comment by fraenki** [comment]
> Only then can I request the same cert and it succeed

Well, usually you should revoke the certificate before removing it.

> /var/etc/acme.sh.log states "Certificate has not reached renewal date use --force"

However, in our next release we'll call `acme.sh --remove` when a certificate is removed from the GUI. This should fix the issue. You can test the fix as follows:

```
opnsense-patch -c plugins c3b9653d
```

> then leaves the final bug of the UI having two certificates listed in drop downs to choose from. there should only be the new one, not both which includes the non-existent certificate.

I don't consider this to be a bug. We do this on purpose. In OPNsense you have two independent components:

* the OPNsense certificate storage (a core component)
* the Let's Encrypt plugin

Once a certificate was successfully created by the Let's Encrypt plugin it is uploaded to the OPNsense certificate storage. The Let's Encrypt plugin will _never_ attempt to remove something from the certificate storage. This would risk to break services that might require this certificate to work as expected (OPNsense WebGUI, nginx, HAproxy, to name a few). Even worse, you wouldn't notice that something is broken until you restart the affected service, which could be a long time after removing the certificate.

So I have decided that the Let's Encrypt plugin should never remove anything from OPNsense certificate storage. But of course you can always remove obsolete certificates manually from `System -> Trust -> Certificates`.

**Comment by Zewwy** [comment]
fraenki... You get a gold star for a great reply.
