### ISSUE TITLE
Wireguard Peer "Allowed IPs" instead of "Tunnel Address"

### ISSUE THREAD

**Issue by Keltere** [opnsense/plugins#1381]
Hi, i wanted to suggest a change on the nomenclature of the wireguard Peer configuration.
On the peer config page instead of having the usual "Allowed IPs" (present even on openwrt) it was renamed to "Tunnel Address" when the original it's a better explanation of what that config is used for.
Please revert back to the standard wireguard nomenclature.
![Annotation 2019-06-28 143818](https://user-images.githubusercontent.com/8084245/60342700-7654ad00-99b2-11e9-82e2-09b3407a16a5.png)

**Comment by Keltere** [comment]
Even with that in mind i think it's still wrong, in fact that caused me a lot of confusion when i saw people setting up a 0.0.0.0/24 "tunnel address" when in fact they where just allowing all the IPs.
Btw i am migrating from OpenVPN to wireguard too.

**Comment by fichtner** [comment]
I want to quickly point out that "thinking that something is wrong" is not a great way to have an open discussion. To have a more positive note, what does the help text say and how could it be improved?

**Comment by Keltere** [comment]
Sorry i was trying to be polite, didn't want to make any accusation whatsoever, being disrespectful or impose my idea as absolute. Sorry if i've offended in any way.

The description state: `List of addresses to configure on the tunnel adapter. Please use CIDR notation like 10.0.0.1/24.`

I personally will replace "Tunnel address" with the official "Allowed IPs" and the description i would place something like "List of addresses allowed to pass trough the wireguard tunnel. Please use CIDR notation like 10.0.0.1/24"
For me this is the best approach to the matter especially to avoid confusion between systems.

**Comment by mimugmail** [comment]
@Keltere let's make a deal, I'll change it to Allowed IPs and set in helptext the old "Tunnel Address" and you check the documentation pages wireguard* an replace **Tunnel Address** with **Allowed IPs**?
https://github.com/opnsense/docs/tree/master/source/manual/how-tos

**Comment by Keltere** [comment]
@mimugmail without bothering you, ill try to make a PR with all the changes. Luckily the code is good written, way better than asuswrt so it should be kinda easy to do.
Btw to be clear the changes are just related to the endpoint config. Referring to tunnel address on the server config it's correct.

**Comment by Keltere** [comment]
Ok i did create a PR, please could you check that everything it's alright?
https://github.com/opnsense/plugins/pull/1388

**Comment by mimugmail** [comment]
@Keltere I already updated the docs (in review)
