### ISSUE TITLE
arp-scan: migrate to python 3

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/plugins#1383]
With the upcoming 19.7 release, we are dropping support for python2.7.
To be able to still use this plugin, it should be ported to python 3.

@peppelinux can you take care of this?

**Comment by peppelinux** [comment]
Hi @AdSchellevis,
I coded it for python3 but We had a discussion about python3 support at that time.
Now it's the time to migrate, I'll do my best if time permits.

I have seen that code, I think that a migration to python3 would be trivial, probably I tagged these like done here:

https://github.com/opnsense/plugins/blob/master/net/arp-scan/src/opnsense/scripts/OPNsense/ARPscanner/IPtools.py#L77

the code seems very easy to portability to python3, when you'll do your firsts test can you give a try?
removing that encoding, as the previous example, should to the trick.

**Comment by AdSchellevis** [comment]
it's probably not very difficult indeed, at the moment we ship both versions, so testing should be easy :)

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
