### ISSUE TITLE
net/haproxy: ip input validation complains by ipv6 addresses

### ISSUE THREAD

**Issue by Kimotu** [opnsense/plugins#1385]
haproxy plugin does not recognize ipv6 addresses as valid and shows an error due to incorrect format.
It concerns all ip/fqdn input fields (real servers, backend, frontend, statistic server).

I tried 2001:DB8::1:8822 and [2001:DB8::1]:8822 for remote listening ip in statistic server, no version is accepted. I always have to create dummy dns AAAA entries to bind just one ipv6 address.

**Comment by fraenki** [comment]
I don't have IPv6 on my OPNsense test box, but this basic example works for me:

![1385](https://user-images.githubusercontent.com/909706/61189039-b345c280-a687-11e9-8b63-cdd35648b390.png)

```
root@opnsense:~ # clog -f /var/log/haproxy.log|grep 1385
Jul 14 22:33:48 opnsense haproxy[64788]: Proxy 1385_frontend_test started. 

root@opnsense:~ # sockstat -6
USER     COMMAND    PID   FD PROTO  LOCAL ADDRESS         FOREIGN ADDRESS      
www      haproxy    53862 17 tcp6   ::1:8822              *:*
```

@Kimotu Please provide the exact error message and a screenshot of the problematic configuration.

**Comment by Kimotu** [comment]
Hi,

 

first I tried [2001:db8::1]:443 which resulted in this error and although I am pretty sure I already tested the syntax 2001:db8::1:443, when I wanted to provide you a screenshot today, it worked.

 

So you can close this issue.

 

Kind regards,

  Kimotu Bates

 

Exist to resist! – Resistance!
