### ISSUE TITLE
tinc dynamic dns on reconnect

### ISSUE THREAD

**Issue by alexkn** [opnsense/plugins#1390]
I'm using tinc vpn with dynamic dns names.
When tinc is startet everything works fine.
But when tinc should reconnect after the connection was lost temporarily I got errors:
```
Jul 6 10:29:53 	tinc.netname[77225]: Error looking up xyz.xyz.de port 655: hostname nor servname provided, or not known
```
The errors do not disappear until I restart tinc.

I don't know if opnsense uses tinc with chroot, but according to tinc manual you have to copy the resolv.conf to the chroot.
So I try to manually copied it to /usr/local/etc/netname/etc/

It seems to fix the problem.
The opnsense plugin should do that automatically.

**Comment by AdSchellevis** [comment]
we do a chroot indeed, seems like we need to make sure there's a `resolv.conf` then

https://github.com/opnsense/plugins/blob/4604fc89ff3d614baf5cfd66cc6eb4b3bebc48ac/security/tinc/src/opnsense/scripts/OPNsense/Tinc/tincd.py#L106
