### ISSUE TITLE
net/frr: BGP Neighbor weight /Multi IP

### ISSUE THREAD

**Issue by QDaniel** [opnsense/plugins#1397]
When add multiple Neighbors with the same ASN i would like add a custom weight. To set a IP Fallback. 

See:  http://docs.frrouting.org/en/latest/bgp.html#clicmd-[no]neighborPEERweightWEIGHT

**Comment by mimugmail** [comment]
But this is only for outgoing packets? Sure you cant solve via route maps and set xxx?

**Comment by QDaniel** [comment]
I'm new in BGP.  

Now i have set a route map:
``route-map Fallback permit 10
set metric 10``

And configure the fallback neighbors with this for in and out.

I will test it.

**Comment by mimugmail** [comment]
With 2 peers both announcing default gateways you dont even need this. BGP will handle this itself ;)

**Comment by mimugmail** [comment]
@QDaniel Need more help here?

**Comment by mimugmail** [comment]
Timeout?

**Comment by fichtner** [comment]
Timeout!
