### ISSUE TITLE
obfsproxy plugin

### ISSUE THREAD

**Issue by sjorge** [opnsense/plugins#140]
A obfproxy plugin would be handy for use with OpenVPN.
It could also be used for other things.

Maybe we need a lightweight generic proxy interface in core so things like this and ftp-proxy could be configure in a common interface. Instead of each getting 'FTP Proxy, IGMP Proxy, OBF Proxy, ...'

**Comment by fraenki** [comment]
http://www.freshports.org/security/obfsproxy/

**Comment by kevin192291** [comment]
Any Update on the progress of this plugin?

**Comment by fichtner** [comment]
No. The status is “looking for maintainer”.

**Comment by mimugmail** [comment]
Why don't you try it yourself with the help of the community? 👍 

There's an excellent technical explanation:
https://docs.opnsense.org/develop.html

And I wrote some absolute beginner guides with no coding skills required:
http://www.routerperformance.net/opnsense/

**Comment by mimugmail** [comment]
Ok, had a look at the service, it's quite similar to set up like lldpd or openconnect.
If @fichtner build a pkg for obfsproxy in the repo I'll build a plugin.

**Comment by fichtner** [comment]
We have https://github.com/opnsense/tools/blob/master/config/17.7/ports.conf#L142 is that different?

**Comment by mimugmail** [comment]
Yep, we need Obfsproxy. @sjorge correct me if I am wrong

**Comment by mimugmail** [comment]
```
root@OPNsense:/usr/ports/security/obfsproxy # make install
===>  obfsproxy-0.2.13_2,1 is marked as broken: fails to configure.
*** Error code 1

Stop.
make: stopped in /usr/ports/security/obfsproxy

```

**Comment by mimugmail** [comment]
https://github.com/OperatorFoundation/shapeshifter-dispatcher/blob/master/README.md

This seems to be better maintained but no port I believe

**Comment by bryanyork** [comment]
I was able to install the obfsproxy package by enabling the freebsd repo. Works great. I've since disabled it, and gone through some opnsense upgrades, no problem. Would be great to add all the deps into opnsense and create a plugin for it.

**Comment by fichtner** [comment]
Which package name would that be? I can only find pyXX-obfsproxy-tor ?

**Comment by bryanyork** [comment]
https://www.freshports.org/security/obfsproxy/
https://www.freshports.org/security/py-obfsproxy-tor/

> port moved to security/py-obfsproxy-tor on 2018-03-01

I had downloaded obfsproxy-0.2.13.1.txz and py27-pycrypto-2.6.1_1.txz and the freebsd repo installed the rest of the packages needed. I'm not sure if the port move changes anything.

@fichtner

**Comment by bryanyork** [comment]
Any updates on this?

**Comment by fichtner** [comment]
No contributor offered time, I'm closing this after 2 years...
