### ISSUE TITLE
net/frr: last changes break template ospfd and after last update to last version ospfd starting fail

### ISSUE THREAD

**Issue by cedvan** [opnsense/plugins#1400]
Hi,

This PR "https://github.com/opnsense/plugins/pull/1360" create a bug with ospfd template.

This line exactly : https://github.com/opnsense/plugins/pull/1360/files#diff-bf3e64f4cf55ab8a6f6520c485ae21a4R48

-----------------------

Bad config generated sample : 

```
!
! Zebra configuration saved from vty
!   2017/03/03 20:21:04
!
log file /var/log/frr.log warnings
log syslog alerts
!
!
!
interface em2
  ip ospf network broadcast
  ip ospf authentication message-digest
  ip ospf message-digest-key 1 md5 g2Am6}*PujaxDNJCpJg
  ip ospf cost 1000
!
!
router ospf
 ospf router-id 0.0.4.1
 redistribute connected  redistribute static  passive-interface em5
 passive-interface em1
 passive-interface em7
 passive-interface em4
 passive-interface em6
 passive-interface em3
 network 172.25.0.31/24 area 0.0.0.0
!
!
!
line vty
!
```

-----------------------

Error : `redistribute connected  redistribute static  passive-interface em5`  

**should not be on the same line**

-----------------------

manually fix config with replace this line by : 
```
redistribute connected  
redistribute static 
passive-interface em5
```
But on next reboot, config is regenerated

-----------------------

Need fix template to generated a good config

**Comment by mimugmail** [comment]
Close this one as it is merged?
