### ISSUE TITLE
ETPro url not working

### ISSUE THREAD

**Issue by numengit** [opnsense/plugins#1402]
When installing os-intrusion-detection-content-et-pro plugin, it tries to download the rules from a wrong url (wrong suricata version, tries 1.3-enhanced when there's 1.4.1 installed).
Editing 
 /usr/local/opnsense/scripts/suricata/metadata/rules/et-pro.xml
with the correct url solves the issue...

**Comment by AdSchellevis** [comment]
it should actually be `https://rules.emergingthreatspro.com/%%etpro.oinkcode%%/suricata-4.0/etpro.rules.tar.gz` in our case (for suricata 4.0 and up), I'll change it immediately.
