### ISSUE TITLE
Feature Request: Clash,a rule-based tunnel works like Surge

### ISSUE THREAD

**Issue by mervynsword** [opnsense/plugins#1412]
First I wanna thank u all for working so hard to give us OPNSENSE. Thank you all very much.

I am living in China, and I think you guys know China has a GFW which blocks access to some foreign websites including Github. As long as the GFW can detect traffic patterns (such as SSH tunneling, VPN or Tor protocols), we have to use some different way to get over "THE GREAT WALL" such like shadowsocks or v2ray.

Clash is a rule-based tunnel,it works like Surge, it can deal with DNS spoofing by using its own DNS plugin, you can use it as a gateway proxy. I think many people would thank u even more if you can add clash into OPNSENSE as a plugin.

The clash github address:
https://github.com/Dreamacro/clash

The FreeBSD ports:
https://svnweb.freebsd.org/ports/head/net/clash/

Thank you all again.

One more thing, Clash already have some WebUIs: like Clash-dashboard and yacd,so you don`t have to build a fully function UI for Clash,only a simple one that can config the RESTful API port will be enough.

The Clash-dashboard github is here
https://github.com/Dreamacro/clash-dashboard

The yacd github is here
https://github.com/haishanh/yacd

**Comment by fichtner** [comment]
I'll see if we can include the binary package :)

**Comment by mimugmail** [comment]
When you write a detailed real world example I can build a plugin around it

**Comment by fichtner** [comment]
@mimugmail @mervynsword yay, we're doing this then with your help

**Comment by mervynsword** [comment]
> @mimugmail @mervynsword yay, we're doing this then with your help

You mean an example on FreeBSD or a UI?

**Comment by mimugmail** [comment]
@mervynsword I mean a sample config you already use on linux or whatevery so I can build a plugin which would generate exactly this config (with other options).
Only walking trough the docs is too much effort for me

**Comment by mervynsword** [comment]
@mimugmail OK, here is what I am using on linux.

The Clash config file on linux is $HOME/.config/clash/config.yaml
```
# port of HTTP
port: 7890

# port of SOCKS5
socks-port: 7891

# redir port for Linux and macOS
redir-port: 7892

allow-lan: false

# Rule / Global/ Direct (default is Rule)
mode: Rule

# set log level to stdout (default is info)
# info / warning / error / debug / silent
log-level: info

# A RESTful API for clash
external-controller: 0.0.0.0:19090

# Secret for RESTful API (Optional)
# secret: ""

# experimental feature
experimental:
  ignore-resolve-fail: true # ignore dns resolve fail, default value is true

dns:
  enable: true # set true to enable dns (default is false)
  ipv6: false # default is false
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip # or redir-host , after v0.14.0 the developer suggests to use fake-ip reather than redir-host, but fake-ip mode will use 198.18.0.1/16 as a fake-ip pool and 198.19.0.1/16 as a fake-dns pool
  fake-ip-range: 198.18.0.1/16 # only needed when using fake-ip mode
  nameserver:
    - 114.114.114.114
    - tls://dns.rubyfish.cn:853 # dns over tls
    - https://1.1.1.1/dns-query # dns over https
  fallback: # concurrent request with nameserver, fallback used when GEOIP country isn't CN
    - tcp://1.1.1.1

Proxy:
# can be empty because it can be edit on the WebUI.

Proxy Group:
# can be empty too.

Rule:
 # can be empty three...
```

As long as I am using clash as a bypass gateway proxy, and the Clash is running in redir-host mode, I have to use iptables to redirect traffic to the linux machine to the Clash redir port like this.

```
*nat
:PREROUTING ACCEPT [4:355]
:INPUT ACCEPT [4:355]
:OUTPUT ACCEPT [624:44412]
:POSTROUTING ACCEPT [258:16016]
:SS-TCP - [0:0]
-A PREROUTING -s 192.168.0.0/16 -p tcp -j SS-TCP
-A OUTPUT -p tcp -j SS-TCP
-A POSTROUTING -s 192.168.0.0/16 -j MASQUERADE
-A SS-TCP -d 0.0.0.0/8 -j RETURN
-A SS-TCP -d 127.0.0.0/8 -j RETURN
-A SS-TCP -d 10.0.0.0/8 -j RETURN
-A SS-TCP -d 169.254.0.0/16 -j RETURN
-A SS-TCP -d 172.16.0.0/12 -j RETURN
-A SS-TCP -d 192.168.0.0/16 -j RETURN
-A SS-TCP -d 224.0.0.0/4 -j RETURN
-A SS-TCP -d 240.0.0.0/4 -j RETURN
-A SS-TCP -d my_server -j RETURN
-M owner --uid-owner clashuserid -j RETURN
-A SS-TCP -p tcp -j REDIRECT --to-ports 7892
COMMIT

*filter
:INPUT ACCEPT [2370539:820800027]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [2311295:519200391]
COMMIT
```

Maybe you can just make a input field like the Unbound-General-Custom options to allow users enter any config options.

**Comment by mimugmail** [comment]
> Maybe you can just make a input field like the Unbound-General-Custom options to allow users enter any config options.


This wont happen :) When the pkg is ready I'll start playing with it ...

**Comment by RevNelson** [comment]
Adding Clash to OpnSense would allow me to finally ditch OpenWRT. Currently I have to have a VM of OpenWRT running with Clash set as the WAN for OpnSense. It would be amazing to set my PPPoE directly in OpnSense.

**Comment by Cokadhp** [comment]
Please I would like some help on how I can create the links of different proxies for clash, I live in china

**Comment by mimugmail** [comment]
Someone here said China? I try to add a raw plugin to my repo for testing. If it's good to go we can upgrade to an official one.

**Comment by mimugmail** [comment]
Sorry for the delay ... it's here:

https://www.reddit.com/r/OPNsenseFirewall/comments/zy5u4d/new_community_repo_plugin_clash/
