### ISSUE TITLE
SMART lobby widget shows "unknown"

### ISSUE THREAD

**Issue by Taomyn** [opnsense/plugins#1415]
Since the upgrade from 19.1 to 19.7 the Smart status widget on my lobby dashboard just shows yellow "unknown".

Going to the service shows everything is well - logs show no error, the SSD passes the short test, the info all shows fine.

Any ideas how to kick the widget into shape? I've tried a reboot and logged off/on

From forum thread: https://forum.opnsense.org/index.php?topic=13502.0

**Comment by soder10** [comment]
Same issue here...

**Comment by opnsenseuser** [comment]
me too ;-)

**Comment by citbr** [comment]
Same here!

**Comment by atl285** [comment]
#1429

**Comment by atl285** [comment]
#1429

**Comment by atl285** [comment]
#1429 will fix this

**Comment by JRGTH** [comment]
> #1429 will fix this

Thanks, after manually applying the fix to an OPNsense Root-On-ZFS installation, "SMART Status" widget start working correctly with an "OK" on my healthy SATA disk.

**Comment by fichtner** [comment]
Fixed in version 2.1 for 19.7.3. Thanks all!
