### ISSUE TITLE
wireguard doesn't populate allowed ips for endpoints after the first

### ISSUE THREAD

**Issue by lethargy-navigator** [opnsense/plugins#1419]
Wireguard works fine with one endpoint configured for the server. Any endpoint after the first will not populate the "allowed ips" field.

I can disable any two of these endpoints in the server config and the remaining endpoint will populate the allowed ips field and the tunnel will operate.

![Screenshot_20190718_150221](https://user-images.githubusercontent.com/1496294/61484905-dca76c80-a96d-11e9-810c-60674a3a9f96.png)
![Screenshot_20190718_150621](https://user-images.githubusercontent.com/1496294/61484906-dd400300-a96d-11e9-9ed4-ce63b6a9d8ec.png)

**Comment by mimugmail** [comment]
You should set a fixed IP with subnet, not a whole network with ending 0

**Comment by lethargy-navigator** [comment]
I haven't configured that .0/27 anywhere. my three endpoints are .2/27 .3/27 .4/27 and the server is .1/27

**Comment by mimugmail** [comment]
You configure the endpoints on server and link them in local or not? Isnt there a field for Tunnel address in every endpoint dialog?

**Comment by lethargy-navigator** [comment]
Yeah the endpoints are linked in the local server. 

I'm not sure what you're asking in the 2nd question. There's allowed IPs and endpoint address. I'm configuring this tunnel the way I've configured it in Linux, which has always worked.

**Comment by lethargy-navigator** [comment]
To clarify: it seems like a problem in the gui configuration.

the allowed IPs i've configured in each endpoint are not showing in the allowed IPs of the output in 'list configuration'.

the endpoint that shows .0/27 as the allowed ips is actually configured as .2/27

**Comment by mimugmail** [comment]
Hm, this is strange. It also doesn't work when using WG without the GUI/plugin. 
I need to do some more testing and maybe check with the Wireguard devs.

**Comment by mimugmail** [comment]
Solved it, on wireguard server, as tunnel address in enpoints use /32

**Comment by lethargy-navigator** [comment]
apologies for my mistake, I think the help text threw me off

**Comment by mimugmail** [comment]
Nö worries, I already updated the docs as they are not clear enough, will also go througj the helptext again https://github.com/opnsense/docs/blob/master/source/manual/how-tos/wireguard-client.rst

**Comment by Write** [comment]
> 
> 
> Solved it, on wireguard server, as tunnel address in enpoints use /32

omg. Finally solved. Thank you so much.
