### ISSUE TITLE
Add L2tp linkup/linkdown fields do add routes

### ISSUE THREAD

**Issue by ccesario** [opnsense/plugins#1422]
Add L2tp linkup and linkdown custom fields (text area) to add routing option.
Once these files linkup and linkdown files are generated with static content.

Carlos

**Comment by fichtner** [comment]
Hi Carlos,

So we already established that we don't want freeform field input. The biggest question apart from this implementation is what is the actual requirement is. The issue I see here is that you don't provide the actual file contents just a way to inject it.

We need to know what you input here in your scripts so we know what the requirement is. If it is about routes we already have static routes so the issue is why is the current static routes implementation not working for L2TP I guess?


Cheers,
Franco

**Comment by ccesario** [comment]
> Hi Carlos,
> 
> So we already established that we don't want freeform field input. The biggest question apart from this implementation is what is the actual requirement is. The issue I see here is that you don't provide the actual file contents just a way to inject it.
> 
> We need to know what you input here in your scripts so we know what the requirement is. If it is about routes we already have static routes so the issue is why is the current static routes implementation not working for L2TP I guess?
> 
> Cheers,
> Franco

Hello Franco,

I undestood you decision about this, but only to you know, I try do it like Openvpn with advanced textarea field to input values, which IMHO it is identical, once inject code into config files, or no!?
OPenVPN screen

![image](https://user-images.githubusercontent.com/1812609/61734978-5cac4880-ad59-11e9-9ff8-0ad6fd55b12b.png)
![image](https://user-images.githubusercontent.com/1812609/61735037-7d749e00-ad59-11e9-8e7a-9e5dc286e299.png)


About the static routes, I cant create it using Opnsense GUI, because it is needed a Gateway for this, but in case of L2TP connection thse IP are created on link establishment.

![image](https://user-images.githubusercontent.com/1812609/61735095-9bda9980-ad59-11e9-8537-fbcb0fc98d58.png)

![image](https://user-images.githubusercontent.com/1812609/61735160-c2003980-ad59-11e9-86c8-81232526c947.png)

![image](https://user-images.githubusercontent.com/1812609/61735274-02f84e00-ad5a-11e9-9a5a-2c1dac711c3a.png)

These routes (in yellow) I needed create by CLI after L2TP establish 
![image](https://user-images.githubusercontent.com/1812609/61735588-a8abbd00-ad5a-11e9-9855-671f9d1b7878.png)


Then I create a custom fields like OPenVPN to inject theses routes into linup and linkdown scripts

Cheers,
Carlos

**Comment by ccesario** [comment]
Hi @fichtner ,

Any tip about it?

Regards,
Carlos

**Comment by ccesario** [comment]
Hi folks, is there any tip or suggestion for this? Or is ti really a possible BUG!?

cheers,
Carlos

**Comment by ccesario** [comment]
@fichtner any suggestion about it?

**Comment by ccesario** [comment]
Hi folks, is there any update about it ?
Regards

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
