### ISSUE TITLE
Clash for OPNSense

### ISSUE THREAD

**Issue by mervynsword** [opnsense/plugins#1423]
First I wanna thank u all for working so hard to give us OPNSENSE. Thank you all very much.

I am living in China, and I think you guys know China has a GFW which blocks access to some foreign websites including Github. As long as the GFW can detect traffic patterns (such as SSH tunneling, VPN or Tor protocols), we have to use some different way to get over "THE GREAT WALL" such like shadowsocks or v2ray.

Clash is a rule-based tunnel,it works like Surge, it can deal with DNS spoofing by using its own DNS plugin, you can use it as a gateway proxy because it support v2ray and shadowsocks. I think many people would thank u if you can add clash into OPNSENSE as a plugin.

The clash github address:
https://github.com/Dreamacro/clash

The FreeBSD ports:
https://svnweb.freebsd.org/ports/head/net/clash/

Thank you all again.

**Comment by mimugmail** [comment]
Isn't there a feature request already?

**Comment by AdSchellevis** [comment]
duplicate https://github.com/opnsense/plugins/issues/1412

**Comment by AdSchellevis** [comment]
@mervynsword please don't spam our issue tracker. It's considered quite rude to beg for attention like this.

**Comment by mervynsword** [comment]
> @mervynsword please don't spam our issue tracker. It's considered quite rude to beg for attention like this.

Sorry for that,won`t do that again.And thank you for your hard work.

**Comment by fxn2020** [comment]
https://pfschina.org/wp/?p=10626
