### ISSUE TITLE
net/frr: BGP: editing of network causes restart of daemon

### ISSUE THREAD

**Issue by MiStr82** [opnsense/plugins#1436]
Hello,

is it requested behavior for some reason or bug? Because this operation does not need restart of daemon if networks are configured via vtysh.

Thank you

**Comment by mimugmail** [comment]
Every time you hit "Apply" the service get's stopped, new config generated, daemon started. 
There's no change to solve this via vtysh as you would then need to write an API for API.

**Comment by MiStr82** [comment]
Thank you for your quick answer, I understand. I didn't research the source code of plugin, but I thought that it's solved either using generation of config and restart service or using vtysh. At least it will be information for others, thank you

**Comment by mimugmail** [comment]
I'm sorry, also for me it's a but frustrating cause you can't use commands like clear ip bgp etc. But luckily such changes happen very rarely.

Would you mind closing the issue? Thanks

**Comment by MiStr82** [comment]
Yes, I agree that such changes are not made frequently. And yeah, I forgot to close this issue :-)
