### ISSUE TITLE
net-mgmt/telegraf: Round Interval setting not working

### ISSUE THREAD

**Issue by devNan0** [opnsense/plugins#1437]
**Plugin:** os-telegraf 1.7.5
**System:** OPNsense 19.7.1-amd64

**Description:** 
The 'Round Interval' setting does not work.

**How to reproduce:**
Enable 'Round Interval' in Services -> Telegraf -> Genral -> Round Interval.

**Solution:**
There is a typo in the template file that generates the telegraf.conf.
See: https://github.com/opnsense/plugins/blob/master/net-mgmt/telegraf/src/opnsense/service/templates/OPNsense/Telegraf/telegraf.conf#L17 vs. https://github.com/opnsense/plugins/blob/master/net-mgmt/telegraf/src/opnsense/mvc/app/models/OPNsense/Telegraf/General.xml#L14

I am working on a PR to fix this.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
