### ISSUE TITLE
security/maltrail: changes in General UI don't trigger reconfiguration

### ISSUE THREAD

**Issue by MiStr82** [opnsense/plugins#1440]
I noticed that changes in General tab of UI changes global config.xml but not maltrail.conf. Editing Sensors or Server tab works as expected. I found difference in /usr/local/opnsense/mvc/app/views/OPNsense/Maltrail/general.volt where is missing this section after "// link save button to API set action":
ajaxCall(url="/api/maltrail/service/reconfigure", sendData={}, callback=function(data,status) {
                            ajaxCall(url="/api/maltrail/service/status", sendData={}, callback=function(data,status) {
                                    updateServiceStatusUI(data['status']);
...

Maybe this is the cause?

**Comment by mimugmail** [comment]
Hi,

Yes, currently a Save in General only save the value to config.xml but nothing else. You have then restart the sensor or server. It's a bit tricky to implement telling which service to restart because you can run both or only one of the two ...

**Comment by MiStr82** [comment]
Hello,

I understand, thank you for the explanation. And is there a reason to have a General tab? Options "Use Heuristics", "Update Period" and "Monitor Interface" belongs to Server, so they may be placed in Sensor tab and option "SHA256 Admin Password" may be placed in Server tab. If it's necessary to reserve the existing division (with General), it would be good to make a note in General tab, that it's necessary to press the save button in the Server tab or Sensor tab. Because in General tab are the most important options that most users change (password and monitor interface) and the changes won't take effect.
It's just a suggestion for improvement, not a reproach :-)

**Comment by mimugmail** [comment]
@MiStr82 I don't read it like criticism, everythings ok :) 

From the documentation these things belong to server/sensor sections, correct, but when you try to separate them by hand and try to start the daemons you'll see that sensor won't start with some settings normally belonging to server. 
Normally there's no reason for General tab, indeed .. but .. things are complicated sometimes.

I'll add a note to general tab, good idea!
