### ISSUE TITLE
19.7.2: OpenSMTPD no longer available

### ISSUE THREAD

**Issue by thatso** [opnsense/plugins#1441]
I've just updated from OPNsense 19.1.10 to 19.7.2. I didn't see any note that OpenSMTPD would be no longer available. Only during the update via SSH I saw a line telling me that it will be uninstalled.
As my OPNsense serves as smarthost, now I wonder if it will become available again or if I have to move on to Postfix.

**Comment by mimugmail** [comment]
I read somewhere that it's unmaintained? (the port). Maybe better move to postfix

**Comment by thatso** [comment]
I'm asking because OpenSMTPD was specifically promoted by @franco back in 2016 [in the forum](https://forum.opnsense.org/index.php?topic=3561). An official statement would be nice.

**Comment by AdSchellevis** [comment]
It's not promoted, only announced that it was in our build list at the moment. 

Things might change over time. 

Rule of thumb is actually quite simple, if it's in the core system, there's usually a paper trail of changes, if there's a plugin, the (community) owner of the plugin may announce changes. If it's a package which has no relation to any of our plugins and nobody actively supports it, the demand is low and/or has issues it might be removed. 

You can always build the package yourself if it doesn't have issues at the moment (our ports tree is synced regularly).

Our most current package build list can be found in our tools repository, for 19.7, this means https://github.com/opnsense/tools/blob/master/config/19.7/ports.conf

By the way franco's github alias is @fichtner .

**Comment by thatso** [comment]
Thanks ... pity ... seems I'll have to move to Postfix.

**Comment by fichtner** [comment]
You can read more about it here: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=213442

The story is that we initially wanted to use OpenSMTPd in OPNsense but Michael built a Postfix plugin on his own knowledge so we didn’t need OpenSMPTd at all.

Now FreeBSD is not very keen on updating OpenBSD/LibreSSL software for petty reasons and the port is old and marked broken in current FreeBSD ports.

We would maintain and update it instead, but that only works if we had a plugin (see point one).

I don’t believe we can keep quality high if we don’t have a plugin for it in the first place and still fighting the uphill battle just for a few (and previously) happy users at this point.


Sorry,
Franco

**Comment by fichtner** [comment]
PS: if the situation in FreeBSD ports changes we will gladly bring the package back.
