### ISSUE TITLE
FreeRADIUS plugin feature request: user attributes

### ISSUE THREAD

**Issue by shans22** [opnsense/plugins#1444]
Hi! 
I apologize for my poor English.
In the web form "Services: FreeRADIUS: Users -> Edit User" there is a limited number of attributes. The administrator cannot add an arbitrary user attribute (Service-Type, Framed-Protocol, Reply-Message ... etc). 
Is it possible to add to the form "Edit User" a field to specify an arbitrary attribute? 
As on page "Services: FreeRADIUS: Users" - at the bottom of the "add" "delete" button. 
Clicking on "add" opens to fill in the field: attribute, operator, value; аllowing an administrator to assign an arbitrary attribute to a user.

**Comment by mimugmail** [comment]
Hi,

there won't be an arbitrary input field, but when you list the attributes you need here, I will happily add them :)

**Comment by shans22** [comment]
Why not?
I thought that the ability to create any attribute that will make life easier for not only me ) 
Let the administrator assign any attributes to the radius user without distracting the developers once again. 
If You don't mind, please add the attribute "Service-Type" to the form "Edit User".

**Comment by shans22** [comment]
Thanks for help, guys. 
Everything works fine.
