### ISSUE TITLE
mail/postfix: daemon constantly restarted

### ISSUE THREAD

**Issue by thatso** [opnsense/plugins#1445]
As OpenSMTPD is no longer available, I've installed Postfix to use OPNsense as a smarthost to relay various messages from local devices to an internet mail address.
Mails are correctly forwarded and `postfix check` on the console shows no output, which AFAIK  means no configuration error.
However, Services -> Postfix -> Logfile in WebUI shows that the daemon is constantly restarted in varying time intervals:

```
Aug 9 23:52:19 	postfix/master[2628]: daemon started -- version 3.4.6, configuration /usr/local/etc/postfix
Aug 9 23:52:19 	postfix/postfix-script[76871]: starting the Postfix mail system
Aug 9 23:52:18 	postfix/master[46721]: terminating on signal 15
Aug 9 23:52:18 	postfix/postfix-script[14409]: stopping the Postfix mail system
Aug 9 23:48:17 	postfix/master[46721]: daemon started -- version 3.4.6, configuration /usr/local/etc/postfix
Aug 9 23:48:17 	postfix/postfix-script[72709]: starting the Postfix mail system
Aug 9 23:48:15 	postfix/master[15907]: terminating on signal 15
Aug 9 23:48:15 	postfix/postfix-script[90859]: stopping the Postfix mail system
Aug 9 23:44:30 	postfix/master[15907]: daemon started -- version 3.4.6, configuration /usr/local/etc/postfix
Aug 9 23:44:30 	postfix/postfix-script[99848]: starting the Postfix mail system
Aug 9 23:44:29 	postfix/master[6974]: terminating on signal 15
Aug 9 23:44:29 	postfix/postfix-script[87555]: stopping the Postfix mail system
Aug 9 23:37:30 	postfix/master[6974]: daemon started -- version 3.4.6, configuration /usr/local/etc/postfix
Aug 9 23:37:30 	postfix/postfix-script[3561]: starting the Postfix mail system
Aug 9 23:37:28 	postfix/master[21146]: terminating on signal 15
Aug 9 23:37:28 	postfix/postfix-script[80303]: stopping the Postfix mail system
Aug 9 23:37:15 	postfix/master[21146]: daemon started -- version 3.4.6, configuration /usr/local/etc/postfix
Aug 9 23:37:15 	postfix/postfix-script[89228]: starting the Postfix mail system
```

How do I check the reason for this behaviour?

**Comment by mimugmail** [comment]
It restarts every time you save something in the UI ..

**Comment by thatso** [comment]
It seems that simply clicking the reload button in the log view caused a restart. I refreshed the view several times and did not touch anything else meanwhile.

**Comment by thatso** [comment]
Argh ... it just occurred to me that I mistook the button to restart the service with one to refresh the log view:

![UI](https://user-images.githubusercontent.com/40745263/62819106-d2cdef00-bb50-11e9-8846-c00017dea101.png)

Further comparison proofs that almost every service web page has these three buttons for start/restart/stop on the top.
So I guess everything is exactly working as expected. ;-)
