### ISSUE TITLE
netdata - backend configuration - feature request

### ISSUE THREAD

**Issue by animosity22** [opnsense/plugins#1449]
Can you please add the configuration for the backend config:

The following fields should be set for the backend:

```
[backend]
         enabled = yes
         data source = average
         type = opentsdb
         destination = 192.168.1.30:4242
         prefix = netdata
         hostname = router.domain.us
         update every = 10
         buffer on failures = 10
         timeout ms = 20000
```

The forum post here covers it as well:

https://forum.opnsense.org/index.php?topic=13802.0

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
