### ISSUE TITLE
Feature Request: nrpe + plugins

### ISSUE THREAD

**Issue by djzort** [opnsense/plugins#1459]
pfSense includes the nrpe package plus nagios-plugins. We use this extensively to monitor our many pfsense's. It's the last gap between pfsense and opnsense which is blocking us from switching them all over.

See also https://docs.netgate.com/pfsense/en/latest/packages/package-list.html

**Comment by AdSchellevis** [comment]
I think the ports package is already in our build list:
 https://github.com/opnsense/tools/blob/85d1d841230b7e4aa5d9ce45fc667e870b24e001/config/19.7/ports.conf#L94

Let's label this help-wanted to see if someone wants to create a plugin for it.

**Comment by mimugmail** [comment]
If it's only nrpe I can do this later this year

**Comment by djzort** [comment]
NRPE isnt much use without some nagios plugins (either nagios-plugins or monitoring-plugins).

pfsense rather unceremoniously dumps the entire nagios-plugins port in, which includes lots of plugins that are irrelevant on a firewall. but on the plus side, you can still use nrpe+plugins to monitor stuff.

**Comment by mimugmail** [comment]
Close with latest PR?
