### ISSUE TITLE
mail/postfix: Postfix will resolve SMTP server with IPV6 even if IPV6 is explicitly disabled

### ISSUE THREAD

**Issue by thatso** [opnsense/plugins#1461]
I've setup Postfix a few days ago and was wondering ever since why the log files randomly state that DNS resolution for the external SMTP server was done with IPV6 despite having only IPV4 active on all interfaces and configuration pages I know of in OPNsense.
Naturally, the SMTP server could then not be contacted by IPV6 and another (succesfull) attempt with IPV4 was made shortly afterwards.
Turns out that another project spotted the same configuration issue for Postfix recently as explained here: #https://github.com/openmediavault/openmediavault/issues/394 (I took the liberty of copying the headline).
Maybe someone can include the workaround in OPNsense.
As I'm no coder, I don't know how to submit pull requests on my own.

**Comment by mimugmail** [comment]
I'll add a dropdown list next week

**Comment by thatso** [comment]
Thanks, much appreciated.

**Comment by fabianfrz** [comment]
@mimugmail please do not make it mandatory. IPv6 should be preferred (current state) and fallback to v4. I don't want that any connection breaks due to this protocol limitation.

**Comment by thatso** [comment]
@fabianfrz did you read the linked solution proposal? The logical action would be a checkbox in the Postfix GUI to limit DNS to IPV4 if needed. This will not break anything as users can decide on their own if they don't use IPV6 anyways.

**Comment by mimugmail** [comment]
@fabianfrz the templating default is currently `inet_protocols = all` .. I'll add a dropdown with values all, ipv6 and ipv4 with all as default :)

**Comment by fabianfrz** [comment]
@mimugmail perfect - exactly how I would like it to be ;)
