### ISSUE TITLE
dyndns and dyns.cx

### ISSUE THREAD

**Issue by It0w** [opnsense/plugins#1462]
Hi,
currently dyns.cx is not working with dyndns-plugin.

If file /usr/local/etc/inc/plugins.inc.d/dyndns/phpDynDNS.inc is edited in line 479
from
```$server = "https://www.dyns.cx/postscript011.php";```
to
```$server = "http://www.dyns.cx/postscript011.php";```

it will work again.

Thanks

**Comment by fichtner** [comment]
Thanks, will be in the next update 👍
