### ISSUE TITLE
mdns-repeater: allow multicast in firewall

### ISSUE THREAD

**Issue by poggenpower** [opnsense/plugins#1466]
As a result from investigating: https://github.com/opnsense/core/issues/3629, we found that static routes to an interface could hinder multicast traffic to be forwarded as expected. Therefore the plugin should create appropriate rules to allow traffic on 224.0.0.252.5355: UDP in a similar way the frr plugin does:
https://github.com/opnsense/plugins/blob/0ce2c7b268914a5b7df46bc1dde9c482b6498600/net/frr/src/etc/inc/plugins.inc.d/frr.inc#L50-L65

**Comment by 53c70r** [comment]
Since we only want to repeat mDNS I would suggest to allow 224.0.0.251/32, port 5353, UDP.
