### ISSUE TITLE
security/acme-client certificate renewal does not work

### ISSUE THREAD

**Issue by jekare** [opnsense/plugins#1473]
OPNsense v19.7.3  acme-client v1.25 haproxy v2.18

Using the HAproxy HTTP Frontend Integration i simply succeed to get a new certificate when testing the setup against the staging environment of Let's Encrypt.
However, when i switch to the production environment and forcefully (re-)issue the certificate i get errors and thus no certificate. 
Attached is the complete logfile, but the interesting part is: KeyID header contained an invalid account URL: \"https://acme-staging-v02.api.letsencrypt.org/acme/acct/9468460\"

Is this a config problem or is the plugin in some way responsible? And what should i try to resolve this issue?

With kind regards,
Jack Reitsema.

[acme.sh.log](https://github.com/opnsense/plugins/files/3556973/acme.sh.log)

**Comment by blablup** [comment]
It's strange that it worked in staging, but it looks like a problem with the account data. Have you tried to create a new LE Account?

**Comment by jekare** [comment]
Hi blablup,

Yes, i tried with different accounts, even a new one, but with the same result.

What i noticed after some extra digging is that the error states the invalid account URL as "https://acme-staging-v02.api.letsencrypt.org/acme/acct/9468460\" which is clearly pointing at the LE staging environment although i changed my setting to use the production environment.
Is the script trying to get a real certificate from the staging environment??? I can't imagine, otherwise a lot of people would have the same problem.

I also noticed the following lines in the log:
_saved_account_key_hash='+D9eLQaohKgjpS+HZ4kp6KX3tdg15N+i+uCw4TJo3pE='
_saved_account_key_hash is not changed, skip register account.

It is always the same key hash, but i cannot find where it is coming from. I would expect that it changes when i use a new account, but it doesn't.

Steps to reproduce:
Set up the acme plugin with an account, validation method and certificate and use the staging environment to get a test certificate which works fine.
Then change in the settings tab the LE environment to 'Production Environment' and save and apply the new setting.
Then go to the certificates tab and re-issue the same certificate. That is when the error occurs.

Kind regards,
Jack.

**Comment by proofy** [comment]
I would have liked to see a little comment on why this ticket is closed and set to support. Also in the forum there are many users who have the problem and haven't published a solution yet.  
https://forum.opnsense.org/index.php?topic=13206.0

**Comment by fraenki** [comment]
@proofy The original author of this issue closed it. If you have a similar problem and are able to provide the steps to reliable reproduce this issue, please open a new issue.

**Comment by blablup** [comment]
try to login via ssh and start a shell. 
Then try to forcefully register a new account (you have to use your account.conf)
``
/usr/local/sbin/acme.sh --force --register-account  --home /var/etc/acme-client/home --accountconf /var/etc/acme-client/accounts/5d68e74bade178.79849572/account.conf
``

**Comment by fraenki** [comment]
> Then try to forcefully register a new account

Users are not supposed to run acme.sh directly on OPNsense. We should find the root cause for the underlying issue and make it work from the GUI. That's why I've asked him for more details. :)

**Comment by blablup** [comment]
I had almost the same issue if I used the "same" account for staging and prod. The Problem is that in some config files of acme.sh the account data is saved and looks valid but is for staging not for prod. Forcefully re-register the account does solve this. 

The root cause is either acme.sh not recognizing that it is a staging account or that OPNsense plugin isn't creating a new account in ``/var/etc/acme-client/accounts`` if environments are switched. 
Maybe it would help to move the staging/prod flag to the account setting?

**Comment by fraenki** [comment]
>  Maybe it would help to move the staging/prod flag to the account setting?

This would cause the same issue if someone changes the staging/prod flag.

**Comment by blablup** [comment]
But It could be checked that it the flag is changed and if it changed forcefully re-register the account.
