### ISSUE TITLE
OPNsense 19.7.3: Colour of info logo is orange instead of green

### ISSUE THREAD

**Issue by JasMan78** [opnsense/plugins#1474]
**Important notices**
Our forum is located at https://forum.opnsense.org , please consider joining discussions there in stead of using GitHub for these matters.

Before you ask a new question, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

After upgrading from 19.7.2 to 19.7.3. the colour of the info logo e.g. behind the plugins under System:Firmware -> Plugins is orange instead of green (as it was before as far as I remember).

Also the info logo of the new feature to enable/disable the logging of the firewall rules in the overview is always orange, regardless of the logging for the rule is enabled or not.

Did someone accidently overwrite the green logo with the orange one, or is this intended?

EDIT: Typo corrected.

**Comment by JasMan78** [comment]
@fichtner Ahhh, thank you very much. I didn't thougt about this. I'm using this theme from the beginning. For me this is the default theme :)

**Comment by opnsenseuser** [comment]
fixed -> [https://github.com/opnsense/plugins/pull/1475]

**Comment by fichtner** [comment]
Thanks, will hit 19.7.4.

**Comment by opnsenseuser** [comment]
@JasMan78 you can update this by doing:
`opnsense-patch -c plugins 3145be71`
