### ISSUE TITLE
Zabbix-agent doesn't stop properly on shutdown

### ISSUE THREAD

**Issue by pyrodex** [opnsense/plugins#1476]
I've noticed with the latest version of the Zabbix-agent plugin it won't shut down when the firewall is asked to shutdown. I've sat and waited an hour in testing but no luck and the ONLY way to get it to stop is killing the main zabbix-agent process.

**Comment by fichtner** [comment]
See https://forum.opnsense.org/index.php?topic=13886.0

**Comment by fraenki** [comment]
https://support.zabbix.com/browse/ZBX-16460
Will be fixed in Zabbix Agent 4.0.13.

**Comment by fraenki** [comment]
Zabbix Agent 4.0.13 was released on 2019-10-02 and includes the fix:
https://www.zabbix.com/rn/rn4.0.13

The FreeBSD port is about to be updated:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=241142

I'm confident that the fix will be available in the next OPNsense release, so I'm closing this issue.
