### ISSUE TITLE
dyndns Cloudflare API Token support

### ISSUE THREAD

**Issue by hockey6611** [opnsense/plugins#1477]
Cloudflare has announced general availability of their API tokens supporting the principle of least privilege. It would be great if this functionality could be added to OPNsense. This would allow more secure access to the API without exposing the whole Cloudflare account.

https://blog.cloudflare.com/api-tokens-general-availability/

**Comment by AdSchellevis** [comment]
duplicate https://github.com/opnsense/plugins/issues/1614

**Comment by seanho00** [comment]
I'm a bit confused why this issue would be a duplicate of #1614 , which concerns accessing the CloudFlare API for DNS-01 ACME validation, whereas this issue concerns accessing the CloudFlare API for DDNS updating.

On 20.1.7, I'm still unable to update a DDNS entry via a limited-access CloudFlare API token.  Using a general-access CloudFlare API key works.

**Comment by hockey6611** [comment]
@seanho00 Thank you for commenting. It flew under my radar that this issue was marked duplicate and closed.

@AdSchellevis Please re-review closure of this issue as it is not a duplicate of #1614. However, since that issue was resolved, it would seem equally important and relevant to support the Cloudflare token here.

**Comment by AdSchellevis** [comment]
best open a new one using our FR template (https://github.com/opnsense/plugins/issues/new?assignees=&labels=&template=feature_request.md&title=)

**Comment by andreas-rupper** [comment]
Just to let you all know, I have added support for Cloudflare API token.
It works great, I'm using it for half a year now.
check here: #1726 but noone ever merged it.
It is assigned to @fichtner btw...
