### ISSUE TITLE
Support for Gandi LiveDNS API in DYNDNS Service

### ISSUE THREAD

**Issue by tspr** [opnsense/plugins#1478]
Hi,
would you be able to include Gandi LiveDNS Support in the DynDNS Service options?

Our buddies at netgate/pfsense have already done so:

https://github.com/pfsense/pfsense/pull/4061

thanks

Thomas

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
