### ISSUE TITLE
net/frr: Feature request: vtysh integration in WebUI and CLI Login menu

### ISSUE THREAD

**Issue by banym** [opnsense/plugins#1483]
Would be nice to be able to debugg and use the vtysh from the WebUI and have a number assigned to it on CLI loggin if the plugin is installed.

**Comment by fichtner** [comment]
I am in doubt this will ever happen. GUI-based shells have been rejected for security concerns a number of times over the years. And the opnsense-shell menu isn’t meant to be pluggable.

Have you tried a dedicated shell account with csh shell and proper .profile setup?

**Comment by banym** [comment]
For now I login over SSH, change user to root and run vtysh. This is not sexy but works.
I am not sure if the vtysh needs to be run as root or can be accessed as user, too.

**Comment by fichtner** [comment]
worst case setting up sudo without password will solve the root issue :)
