### ISSUE TITLE
net/frr: Feature request: Make it possible to define MD5 authentication for peers

### ISSUE THREAD

**Issue by banym** [opnsense/plugins#1484]
Some providers prefer to use BGP authentication for the sessions. 
Would be nice if it is possible to set the md5 authentication data within the webui for the neighbours. 

This information should all be backed up with the system backup for fast restore.

Whould love to test and debug on this feature.

**Comment by theonemcdonald** [comment]
Second this.

**Comment by HenriWahl** [comment]
Mee too.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
