### ISSUE TITLE
cicada theme - colors in firewall rules

### ISSUE THREAD

**Issue by alfredneumann** [opnsense/plugins#1485]
Hello

Since upadte to 19.7.3 the color for log enabled/disabled on the Firewall/Rules Pages for the cicada theme are quite the same so you cannot see if the Log is enabled or disabled. On the Opensense Theme it is fine.

![example](https://user-images.githubusercontent.com/54841674/64163481-a486bb00-ce41-11e9-9f10-a6de0feacb62.png)

br
Alfred

**Comment by mimugmail** [comment]
https://github.com/opnsense/plugins/pull/1475/files

next version
