### ISSUE TITLE
net/frr: Feature Request: autogenerate BGP related rules for configured neighbors

### ISSUE THREAD

**Issue by banym** [opnsense/plugins#1486]
I am not sure if it's necessary in every situation, but if you enable BGP and configure neigbors. The session workes if it is initiated outgoing? Am I correct with this?

If the neighbor wants to initiate the session, the BGP related ports for on my sided are needed to be open for the neighbors? Please correct me if it is bullshit.

Wouldn't it be usefull to generate the rules for the interfaces automatically, since all information are configured. (Interface, Neighbors IP, and all the BGP defaults Ports) 

Regards,

Dominik

**Comment by mimugmail** [comment]
TBH, I'm not a fan of auto-rules. I like the idea for OSPF since most users are not really experienced with multicast, but normally it should be clear to accept port 179 when using BGP?!

**Comment by banym** [comment]
I learned things are not clear to everybody if you don't have the experience. 
It could be an option under general, to enable auto generated rules for interfaces used with BGP. 
The "good" thing about that is, it makes it possible to hide the BGP rules within autogenerated drop down. 
On my firewalls with BGPthe rule-sets are very often complex. No need to setup rules that are necessary for basic operation if this could be done by an option.
As I tried to explain, the rules can be defined very strict by the information given within the neighbors definition. Only the neigbor would be allowed to contact the port on the given interface. From security side this should be totaly fine?

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
