### ISSUE TITLE
Virtualbox guest additions

### ISSUE THREAD

**Issue by ezraholm50** [opnsense/plugins#1488]
Hey thanks for the awsome project guys. I have OPNsense running on a Vbox virtual machine.
I want to enable usb support to use a dualband wifi dongle to have my wireless devices connecting to OPNsense.

When I run `pkg install virtualbox-ose-additions` it says it cant be found, 

`unable to update OPNsense repository`

Now i heard something about a different install manager? But I can't find anything about it?

Thanks

**Comment by fichtner** [comment]
Hi @andrewhotlab,

That looks promising. I haven't looked after this for a while myself. Let me try to get the port in and then we'll do the plugin as it shouldn't be hard then. :)


Cheers,
Franco

**Comment by fichtner** [comment]
So far no luck, the port build fails in a pristine build chroot, which is rather odd. Needs more time to debug...

**Comment by andrewhotlab** [comment]
Ok, thanks for your effort... I hope to become able to help on this matter in the future.

**Comment by fichtner** [comment]
I found out why our build broke, had the same issue with postfix a while back: https://github.com/opnsense/ports/commit/43cb743615e

So now when 19.7.4 is out you can do "pkg install virtualbox-ose-additions-nox11" and report back if the package works as expected?

Then we can build the plugin :)

**Comment by andrewhotlab** [comment]
For sure! Thank you so much Franco. I’ll report you the result ASAP.

**Comment by andrewhotlab** [comment]
Hi, I just tested the package on 19.7.4_1: it is working as expected.

**Comment by mimugmail** [comment]
Do you want to try building a plugin for it? :)

**Comment by andrewhotlab** [comment]
Eheh, I’d wish to be able to do it... but “never say never”: I will try! :)

Obviously do not let me slow you down, guys: build it if you have the chance meanwhile.

**Comment by andrewhotlab** [comment]
Hi @mimugmail , please give a look at the pull request #1502 . I wrote it blindly copying from the code I found in sysutils/vmware, since coding is not my job! :P

However it seems to work in my test... here is a transcript:
```
[opnsense-plugins/systutils/virtualbox] % make package
>>> Generating metadata for os-virtualbox-devel-1.0... done
>>> Staging files for os-virtualbox-devel-1.0... done
>>> Packaging files for os-virtualbox-devel-1.0:
file sizes/checksums     [3]: 100%
packing files            [3]: 100%
packing directories      [0]: 100%
```

**Comment by mimugmail** [comment]
I think we can close this one?

**Comment by fichtner** [comment]
Yes 😊
