### ISSUE TITLE
Add local bind plugin support for the acme plugin

### ISSUE THREAD

**Issue by blablup** [opnsense/plugins#1489]
Hello,

I wrote a plugin for the acme client to use the local bind via api.
Please let me know waht you think.

**Comment by mimugmail** [comment]
I like the idea since it's a nice approach to use the API. 
Sadly I have no idea of ACME, not sure if I can help here. The responsible part for bind should already be done.

**Comment by blablup** [comment]
if PR #1472 gets merged then everything is there, yes.

**Comment by fraenki** [comment]
I'll take care of reviewing, testing and merging.

**Comment by fraenki** [comment]
Merged. Will be available in the next release (NOT tomorrow's 19.7.4).
