### ISSUE TITLE
security/acme-client: support for DNS-alias-mode

### ISSUE THREAD

**Issue by blablup** [opnsense/plugins#1490]
a patch to detect DNS-alias-mode ( [https://github.com/Neilpang/acme.sh/wiki/DNS-alias-mode](https://github.com/Neilpang/acme.sh/wiki/DNS-alias-mode) ) and use it.

**Comment by mimugmail** [comment]
It's really confusing having 2 PRs and 2 emtpy issues pointing to 2 PRs. Can you sort them out? Usually 1 PR is enough, maybe pointing to the issue related to bind plugin

**Comment by blablup** [comment]
Sorry, 
I thought this are different features. What do you want should i merge the 3 PR to 1 branch?
Tomorrow I don't have time, but I can do it Friday.

**Comment by fraenki** [comment]
more or less a duplicate of https://github.com/opnsense/plugins/issues/1301

**Comment by fraenki** [comment]
@blablup I've added some code to make DNS alias mode configurable in https://github.com/opnsense/plugins/pull/1499/commits/4fd4c77bdf3ac399b6a69c20ee56e63a5e662e37. It would be nice if you could help testing the final code either by applying the patch or by upgrading to 19.7.5 in the not too distant future.:)

**Comment by fraenki** [comment]
@blablup Thanks! I've commited a bugfix in https://github.com/opnsense/plugins/commit/7e8e52ecc23bb3c0e41eaf5bb11a437afd069563.
