### ISSUE TITLE
unbound: Add possibility to enter Access control and views

### ISSUE THREAD

**Issue by BPtLNfxZWo** [opnsense/plugins#1501]
Reffering to https://github.com/opnsense/core/issues/3706#issue-493737939

At the moment Access control conditions and views can be added via „Custom options“. As „custom options“ will be removed please consider an alternative way for defining access controls and views, e.g

server:
#Access control for Internal IPv4/6
access-control-view: 192.168.100.0/24 lanview
access-control-view: xxxx:xxxx:xxxx:xxxx::/64 lanview
view:
name: "lanview"
local-zone: "xxxxxxxx" transparent
local-data: "xxxxxxxx A xxxxxxxxx"

Thanks

**Comment by mimugmail** [comment]
Please close this one, we will work at the initial issue Franco moved

**Comment by mimugmail** [comment]
@fichtner I would make a submenu "Advanced" and put all kind of tabs in there. OK?

**Comment by fichtner** [comment]
I‘m not „Plus“ is all advanced in a way. May be clearer as access control or something.
