### ISSUE TITLE
www/nginx: Erroneously claims only one server per port

### ISSUE THREAD

**Issue by rootwyrm** [opnsense/plugins#1505]
When using Nginx streams to proxy multi-protocol traffic (e.g. DNS which is 53 udp and/or tcp), the UI erroneously reports that you can only have one listener at port 53, which is not correct. You can have one TCP and one UDP listener.

Example:
```
streams { 
    listen 69 udp;
    listen 69;
    proxy_pass tftp_servers;
}
```

The UI needs to consider UDP and TCP separately when configuring data streams. Which aren't even being configured in my test; it's simply doing nothing and pretending it's actually configured a stream. But there is no stream actually configured.

**Comment by blablup** [comment]
is it sufficient to add an option to add UDP as well as tcp (like your snippet)?

**Comment by fabianfrz** [comment]
https://github.com/opnsense/plugins/blob/master/www/nginx/src/opnsense/mvc/app/models/OPNsense/Nginx/Nginx.xml#L797-L800

I think this field could be migrated to a dropdown. TCP/UDP/Both

**Comment by rootwyrm** [comment]
That might be the best option from a validation standpoint. Trying to validate that someone hasn't added 55/udp 55/tcp 55/udp might be a headache.

**Comment by blablup** [comment]
That was my idea, too. Because I didn't find a possibility to do a unique check with 2 fields.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
