### ISSUE TITLE
net/frr: BGP Diagnostics Summary tab not working

### ISSUE THREAD

**Issue by ggoodrich-ipp** [opnsense/plugins#1509]
When you click this tab, you get no information, even though you should. The back-end runs the following vtysh command via quagga.rb, which, when I run this, I get output:

`# vtysh -c show ip bgp`
![image](https://user-images.githubusercontent.com/54906463/65067351-ec323a00-d94b-11e9-87bb-c0a15df44da1.png)

I've done some investigation, and it seems that frr recently added an additional header line for 'Nexthop codes', which is throwing off the parsing in [plugins/net/frr/src/opnsense/scripts/quagga/quagga.rb](https://github.com/opnsense/plugins/blob/871c18c9859e4c6eb154b1f99113d3fe6051b4ae/net/frr/src/opnsense/scripts/quagga/quagga.rb#L390)

I will be submitting a PR shortly to address the defect, as well as hopefully make future defects less likely.

A potentially superior fix for this would be to leverage the json option in vtysh so that parsing isn't really necessary. However, I also noticed that frr has merged changes to the output of the JSON for the next major version, link [here](https://github.com/FRRouting/frr/commit/e008da8e9e8acdede422026bfdbb0ee194123fb4#diff-ec0781ee436de06e46b164b15d406dc6), and is deprecating some of the existing keys. This makes the JSON option problematic, at least for the time being.

**Comment by mimugmail** [comment]
Isnt this already fixed by yourself?

**Comment by ggoodrich-ipp** [comment]
> Isnt this already fixed by yourself?

Yes, it is. I created this issue at the same time that I submitted the PR, so that there would be appropriate tracking of the issue and its solution. I'll close it
