### ISSUE TITLE
Wireguard Plugin API methods not functioning as expected

### ISSUE THREAD

**Issue by garyray-k** [opnsense/plugins#1511]
The current plugin version where the bug first appeared
**os-wireguard (installed) | 1.1 | 44.3KiB | WireGuard VPN service**

The last plugin version where the bug did not exist
**unknown** 
It seems that the controller and methods involved weren't changed since initial commit. also the same code on the wireguard/server API works well enough.
The exact URL of the GUI page involved (if any)

The current OPNsense version used
**OPNsense 19.7-amd64
FreeBSD 11.2-RELEASE-p11-HBSD
OpenSSL 1.0.2s 28 May 2019**

A list of steps to replicate the bug

1. add wireguard plugin
2. setup server (under Local tab) and client (Endpoints tab) for wireguard.
3. use postman or other tool to send GET/POSTs to https://<opnsenseIP>/api/wireguard/client/*

wireguard/client/getclient (lacks information)
![getClient](https://user-images.githubusercontent.com/39040273/65161367-6d99d300-da05-11e9-8727-3f0b2f685d90.png)

wireguard/client/toggleclient (function throws error)
<img width="1192" alt="toggleclient" src="https://user-images.githubusercontent.com/39040273/65161616-e39e3a00-da05-11e9-9f48-a7a580b0471b.png">
![toggleClientParams](https://user-images.githubusercontent.com/39040273/65161618-e39e3a00-da05-11e9-9399-22fa2c5b478f.png)

wireguard/server/toggleserver
![toggleServer](https://user-images.githubusercontent.com/39040273/65161694-04668f80-da06-11e9-89c9-1b033c50fba1.png)

**Comment by fabianfrz** [comment]
Have you tried it as an URL Path parameter: .../toggleClient/<UUID OF Element>

**Comment by garyray-k** [comment]
that works! 
I was going off https://docs.opnsense.org/development/api.html#introduction that states _"The body of the HTTP POST request and response is an ‘application/json’ object."_

Thanks!

**Comment by fabianfrz** [comment]
not all post requests do have a body - it is always specific for the API.
