### ISSUE TITLE
www/web-proxy-useracl - Active Directory filter not work.

### ISSUE THREAD

**Issue by Merlyno979** [opnsense/plugins#1514]
Hi,
I have a problem with the plugin: if i use Active Directory integration on OPNsense, the plugin os-web-proxy-useracl versione 1.11_1 not work.
The authentication metod in OPNsense i set to my personal LDAP organization unit.
LDAP integration is up, the test in the menu "test" is good.

Help me pleace? :-)

**Comment by rafaelolivei** [comment]
I also have the same error. I just depend on it to migrate to opnsense.

**Comment by akrmmar** [comment]
I also have the same problem.
Tested it on 19.7.4 and 19.7.7.
Not sure with what version the problem started, I just noticed the problem last week. It used to work with no issues. I usually update OPNsense every couple of weeks.

**Comment by akrmmar** [comment]
I found the bug cause and how to reproduce it.

**To reproduce:**
1- Setup multiple ldap servers.
2- In Web proxy Authentication method select more than one ldap server.

**Possible fix:** 
 file: plugins/www/web-proxy-useracl/src/opnsense/service/templates/OPNsense/ProxyUserACL/ProxyUserACL.conf (Not sure if this is the only file to be fixed)
Lines: 22, 44, 56, 61
"if ldap|length == 1"
If more than one ldap server is selected these "if" statements will skip and nothing will be added to "ProxyUserACL.conf"

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
