### ISSUE TITLE
dns/dnscrypt-proxy

### ISSUE THREAD

**Issue by Taomyn** [opnsense/plugins#1517]
I've been tracking things in Maltrail and I can see it flagging a suspicious tor exit node at IP: 178.82.102.190

Looking into this IP I found it's called "ibksturm" [Tor Node Check](http://blutmagie.de/router_detail.php?FP=4dacf6702466f31a20674ff7a15e2429bcaa1cd1) and that's the Github handle of [Andreas Ziegler](https://github.com/ibksturm) who has something to do with various dnscrypt-proxy code.

It's all a bit confusing to me so I apologise as I just want to understand why my firewall is making tor connections in the first place, so is this expected behaviour?

**Comment by mimugmail** [comment]
Do you use dnscrypt? Why not run a tcpdump on WAN against the IP and posting the stuff?
Sorry, the whole topic is really confusing.

**Comment by Taomyn** [comment]
Yes, I have dnscrypt-proxy running on my firewall.

Basically I'm trying to figure out why Maltrail is alerting me to this:
![Annotation 2019-09-23 205456](https://user-images.githubusercontent.com/4365929/65453961-7bf05080-de44-11e9-9f36-e3abddec9556.png)

And it led me to the info linked my my first post, a tor site named the same as the owner of the Github site that has dnscrypt code.

**Comment by blablup** [comment]
For me, it looks like DoH.

public dns servers:

dot: ibksturm.synology.me:853
dot: ibksturm.synology.me:443

doh: https//ibksturm.synology.me/dns-query
sdns://AgcAAAAAAAAAACA-GhoPbFPz6XpJLVcIS1uYBwWe4FerFQWHb9g_2j24OBRpYmtzdHVybS5zeW5vbG9neS5tZQovZG5zLXF1ZXJ5

dnscrypt: ibksturm
sdns://AQcAAAAAAAAADjE3OC44Mi4xMDIuMTkwIBuR6jsTpCthR_P_b_jSxBJF9ch_jC7ZTVp7EHV2YgLaGDIuZG5zY3J5cHQtY2VydC5pYmtzdHVybQ

no filters, no logging, no censorship! DNSSEC and OpenNIC

documentation is found on [github / ibksturm](https://github.com/ibksturm/dnscrypt-switzerland)

which is (or was) also a tor exit node.

**Comment by Taomyn** [comment]
Many thanks for clarifying the log
