### ISSUE TITLE
HAProxy: can't specify IPv6 addresses as  Listen Address in frontend

### ISSUE THREAD

**Issue by ghostwheel42** [opnsense/plugins#152]
This can be solved by just adding a colon to frontends.bind &lt;mask&gt; in HAProxy.xml:
`<mask>/^((([0-9a-zA-Z._\-\*:]+:[0-9]+(-[0-9]+)?)([,]){0,1}))*/u</mask>`

I don't know if someone needs a more complete regex including unix domain sockets:
`<mask>/^((((ipv4@)?([0-9.]+|\*)?(ipv6@)?([0-9a-f:]*|\*)?):[0-9]+(-[0-9]+)?|(unix@)?/[^ ]+),?)*/u</mask>`

Alex

**Comment by fraenki** [comment]
@ghostwheel42 thanks for your report and the suggested fix!

**Comment by fraenki** [comment]
The fix can be tested by running the following CLI command:

`opnsense-patch -c plugins ac38144462d35a47b1b2b34ab8fcf1964c5a6746`
