### ISSUE TITLE
os-bind: suggestions and improvements.

### ISSUE THREAD

**Issue by CRYPTONIKAV** [opnsense/plugins#1525]
Good afternoon,

Thank you for this excellent job and some suggestions:

Ability to
- Edit, add, import, delete more block lists or categories.
- Create, edit a list most suspicious TLDs (.xyz .date .country)
- Create categories from an external block list
- Create categories from a local block list
- Create categories from an external allow list
- Create categories from a local allow list
- Use regular expressions (Regex) to create dynamic filters.
- Block by max domain length
- Allow only 'A' record in protocol
- Redirect to page with blocking policy message
- Identify which list has blocked a specific domain
- Add domains to the white list from the blocking report

This resource is not available:
https://raw.githubusercontent.com/Akamaru/Pi-Hole-Lists/master/hbbtv.txt

Thank you

**Comment by mimugmail** [comment]
No idea how to implement caregories, what would be the benefit? Most other stuff is possible with dnscrypt Plugin. Bind is not flexible enough for this.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
