### ISSUE TITLE
smartmontools - bogus drivedb.h

### ISSUE THREAD

**Issue by sporkman** [opnsense/plugins#1527]
On attempting to view drive status, start a test, etc., I get an error in the plugin's output:

```
smartctl 7.0 2018-12-30 r4883 [FreeBSD 11.2-RELEASE-p14-HBSD amd64] (local build)
Copyright (C) 2002-18, Bruce Allen, Christian Franke, www.smartmontools.org

/usr/local/share/smartmontools/drivedb.h(287): Missing terminating '"'
```
Updating it seems to fix the issue (although the stock tool for updating seems to be missing):

```
root@SporkLab:/home/sporkadmin # sudo /usr/sbin/update-smart-drivedb
sudo: /usr/sbin/update-smart-drivedb: command not found
root@SporkLab:/home/sporkadmin # fetch https://www.smartmontools.org/export/4956/branches/RELEASE_7_0_DRIVEDB/smartmontools/drivedb.h
fetch: https://www.smartmontools.org/export/4956/branches/RELEASE_7_0_DRIVEDB/smartmontools/drivedb.h: size of remote file is not known
drivedb.h                                              203 kB  560 kBps 00m00s
root@SporkLab:/home/sporkadmin # mv drivedb.h /usr/local/share/smartmontools/
```

**Comment by fichtner** [comment]
All packages are under /usr/local, so:

    # which update-smart-drivedb
    /usr/local/sbin/update-smart-drivedb

I'm not sure about the file update... the base release should ship a correct file but seemingly doesn't.

The problem goes further:

    # update-smart-drivedb
    /usr/local/sbin/update-smart-drivedb: gpg: not found in '/usr/local/bin:/usr/bin:/bin' ('--no-verify' to ignore)
    # update-smart-drivedb --no-verify
    /usr/local/share/smartmontools/drivedb.h updated from branches/RELEASE_7_0_DRIVEDB (NOT VERIFIED)
    # pkg check -s smartmontools
    Checking smartmontools:   0%
    smartmontools-7.0_1: checksum mismatch for /usr/local/share/smartmontools/drivedb.h
    Checking smartmontools: 100%

The update raises a red flag in the health check because the FreeBSD package doesn't correctly include the drivedb.h file. It expects it never to be updated, which is wrong if that is the right way to unbreak the service.


Cheers,
Franco

**Comment by fichtner** [comment]
PS: we still have #821 open.
