### ISSUE TITLE
security/acme-client: feature request for DNS Service Loopia (dns_loopia)

### ISSUE THREAD

**Issue by moldino** [opnsense/plugins#1529]
Hi!
Would be great if the API for the DNS service provider "loopia.com" (acme/dnsapi/dns_loopia) could be added to the list in opnsense Let's Encrypt GUI. 
/Thanks

**Comment by jpawlowski** [comment]
See pull request https://github.com/opnsense/plugins/pull/1524

**Comment by jpawlowski** [comment]
However, I don't think it was added to the upstream project yet, see their [README](https://github.com/AnalogJ/lexicon/blob/516c9271b36b5f120c8571fb6688410db3e4e0b7/README.md):

> Potential providers are as follows. If you would like to contribute one, follow the CONTRIBUTING.md and then open a pull request.

Loopia is below that list. What you need to do first is to make your contribution to the lexicon project.

**Comment by fraenki** [comment]
> Loopia is below that list. What you need to do first is to make your contribution to the lexicon project.

No, that's not true. It is natively supported by acme.sh, so it's pretty easy to add support for it. I'll try toadd it for one of the next releases.

**Comment by jpawlowski** [comment]
True, I was trapped in my realm it seems.

**Comment by fraenki** [comment]
Support for Loopia will be available in the next release (_not_ today's release, though).

**Comment by moldino** [comment]
Thanks a lot!
