### ISSUE TITLE
www/nginx: Stream Server - Route with: SNI Upstream Mapping doesn't work

### ISSUE THREAD

**Issue by nameless66** [opnsense/plugins#1530]
Hi there,

In "Edit Stream Servers" the Attribute "Route with = SNI Upstream Mapping" doesn't change anything in nginx.conf. So no SNI-based routing is possible.
 
![2019-10-04_22-24-54](https://user-images.githubusercontent.com/4205179/66237739-29414f00-e6f6-11e9-9a27-c54af39d6420.png)

When I select "Route with = Upstream", nginx.conf is updated.

**Comment by fabianfrz** [comment]
I was not able to reproduce exactly this bug but I found #1541which prevented a template regeneration. Please check if `opnsense-patch -c plugins 2aa8d1facbb183a9f9f54b303e423803e171f984` works for you.
