### ISSUE TITLE
security/acme-client: Add automation action "Restart IPsec VPN Service"

### ISSUE THREAD

**Issue by stumbaumr** [opnsense/plugins#1534]
Hi,

I use LE certificates in the IPsec configuration. Could you please add an automation action to restart the strongswan service.

Thanks

**Comment by fraenki** [comment]
@stumbaumr Thanks for your suggestion! I've added a PR to enable this for IPsec and Captive Portal:
https://github.com/opnsense/core/pull/3755
Assuming that this is accepted by the core developers you should be able to do this in the next release.

**Comment by stumbaumr** [comment]
Thanks for taking care of this and following through!
