### ISSUE TITLE
mail/postfix: trusted networks don't stick

### ISSUE THREAD

**Issue by thatso** [opnsense/plugins#1537]
OPNsense 19.7.5 with Postfix 1.11: the GUI field Services > Postfix > General > Trusted Networks always stays empty.
If I enter something (like 192.168.0.0/24), the entry gets boxed in a gray frame to indicate its valid. After saving, changing to the log view to verify the service got restarted and going back to the General tab, the Trusted Networks field is empty again.

**Comment by mimugmail** [comment]
Do you hit save after adding?

**Comment by thatso** [comment]
Yes, as already said.

**Comment by mimugmail** [comment]
Is this a new install? Did this happen after an update?

**Comment by thatso** [comment]
I observed this after today's latest update. However, I don't remember if it worked before. I've installed Postfix as soon as it was clear that OpenSMTPD is no longer supported and only got back to the configuration page today to check the new IPV4/IPV6 selection (which BTW does stick).

**Comment by mimugmail** [comment]
@thatso you can install patch linked in core/#3760 to fix this

**Comment by fabianfrz** [comment]
@mimugmail I fixed your link. GitHub detects it if you enter the full name (namespace '/' project '#' Ticket number)
