### ISSUE TITLE
os-theme-cicada: Orange missing in OPNsense 19.7.5

### ISSUE THREAD

**Issue by JasMan78** [opnsense/plugins#1538]
**System:** OPNsense 19.7.5
**Plugin:** os-theme-ciada

**Issue:** Before 19.7.5 the color of e.g. selected menu, utilization bar and the update link were orange. Now they're all light-grey. New style or issue?

![grafik](https://user-images.githubusercontent.com/20991399/66683947-12ac7200-ec79-11e9-91f7-9051a13ccff7.png)

**Comment by opnsenseuser** [comment]
@JasMan78 soory...its an issue. I will fix this!

**Comment by opnsenseuser** [comment]
fixed -> https://github.com/opnsense/plugins/pull/1542
