### ISSUE TITLE
HAProxy: Table too wide

### ISSUE THREAD

**Issue by fabianfrz** [opnsense/plugins#154]
![bildschirmfoto am 2017-05-11 um 20 50 32](https://cloud.githubusercontent.com/assets/3713914/25966537/9758a66e-368b-11e7-91d4-842c86286bac.png)
The Table needs more space than the screen offers. Maybe folding columns can help.

**Comment by fraenki** [comment]
This looks like a regression. Maybe due to the latest translation additions or a change in the framework. 

FWIW, I can't reproduce this on 17.1.6 with os-haproxy 1.14, see below.

![haproxy_table](https://cloud.githubusercontent.com/assets/909706/25968660/a590b04e-3692-11e7-9e41-12fb1a5807f7.png)

**Comment by fabianfrz** [comment]
I have also 1.14 and master installed on the test VM and both show the same result in Firefox (Linux).

**Comment by fraenki** [comment]
The tables should auto-scale, this is a framework regression in master then.

**Comment by fabianfrz** [comment]
@fraenki should we close this then if it's upstream?

**Comment by fraenki** [comment]
Please test with different browsers.

**Comment by fabianfrz** [comment]
This is vivaldi:

![1a626db1-5085-4ee4-bb5e-dd570bda4819](https://cloud.githubusercontent.com/assets/3713914/25969128/195b5bea-3694-11e7-8b29-6ab14b6fce8c.png)

**Comment by fraenki** [comment]
I was rather thinking of some more common browsers, like Firefox or Chrome.

**Comment by fabianfrz** [comment]
Firefox is the screenshot on the top and vivaldi is chromium based so the results are the same.

**Comment by fraenki** [comment]
Well, we need to check the corresponding files in core to see if a recent change broke this.

**Comment by fabianfrz** [comment]
all JS lib stuff has not been changed since march 4th in core.

**Comment by fabianfrz** [comment]
just if this can be the reason: my screen resolution is 1600x900

**Comment by fraenki** [comment]
Never seen this, even on higher screen resolutions.

**Comment by fabianfrz** [comment]
round the root of the issue: your table is not initialized if haproxy is not running. After enabling it runs in both browsers as expected.

Enabling the server was not required for my translation work where I found it ;)

Handle it like you wish.
