### ISSUE TITLE
os-mail-backup: PHP Warning:  Use of undefined constant PHPMailer

### ISSUE THREAD

**Issue by stalks** [opnsense/plugins#1540]
After each send of an email, opnsense web gui dashboard will tell me there has been an error, saying `A problem was detected. Click here for more information.`

On the report page is
> `[12-Oct-2019 18:50:17 Europe/London] PHP Warning:  Use of undefined constant PHPMailer - assumed 'PHPMailer' (this will throw an Error in a future version of PHP) in /usr/local/opnsense/mvc/app/library/OPNsense/Backup/Mailer.php on line 179`

> `User-Agent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36`
> `FreeBSD 11.2-RELEASE-p14-HBSD  07680caafe9(stable/19.7) amd64`
> `OPNsense 19.7.5 bb0e6e52c`
> `Plugins os-acme-client-1.26 os-dyndns-1.17 os-mail-backup-1.0 os-zerotier-1.3.2_2 `
> `Time Sat, 12 Oct 2019 19:44:10 +0100`
> `OpenSSL 1.0.2t  10 Sep 2019`
> `PHP 7.2.23`

> `os-mail-backup: v1.0`

**Comment by stalks** [comment]
Good morning. I'm not a PHP expert, however I read the short guide on how to use PHPMailer on the class documentation and noticed their example doesn't require the line that is giving the issue in this case, so I commented it out. The plugin still works, and without triggering an error.

```
176        $date     = date('Y-m-d');
177        $hostname = gethostname();
178
179        // PHPMailerAutoload(PHPMailer);  <<<<<<<<<
180        $mail = new \PHPMailer(true);
181        $mail->IsHTML(false);
```

**Comment by fraenki** [comment]
I've submitted a fix for this issue, you may test it like this:

```
opnsense-patch -c plugins 744d7ca8
```

This fix will also be available in the next release of OPNsense.
