### ISSUE TITLE
Lets encrypt, unable to add Alt Name domain

### ISSUE THREAD

**Issue by blackyzero** [opnsense/plugins#1543]
Hello,

This issue happens after upgrading to latest version few days ago. I am running 19.7.5
It's unable to add more sub domain under Alt Name. In addition, there is no Alt Name domains appears when i clicked in edit mode.

Please have a look. Thank you.

**Comment by fichtner** [comment]
Please update to 19.7.5_5.

**Comment by fraenki** [comment]
Likely related to https://github.com/opnsense/core/commit/7a5a2712cdb8dc5cb4e2b7fae46430bd8849799f, should be fixed by updating as stated by @fichtner.
