### ISSUE TITLE
www/nginx: Possibility to configure allowed header size

### ISSUE THREAD

**Issue by tonnosf** [opnsense/plugins#1544]
Hello

Is it possible to add a config for nginx to make buffer size configurable?
In some cases our application uses high header size and NGINX will fail with default config.

Best,
Antonio

**Comment by fabianfrz** [comment]
can you provide an example config you would like to have.

A main starting point for that are the docs:
https://nginx.org/en/docs/http/ngx_http_core_module.html#client_header_buffer_size

**Comment by fabianfrz** [comment]
will be probably in the next release - PR is ready.
