### ISSUE TITLE
net/haproxy: sending traffic to wrong backend

### ISSUE THREAD

**Issue by lilrags16** [opnsense/plugins#1549]
Title says it all. Only way around it is to clear all HAproxy settings from the GUI

**Comment by fraenki** [comment]
> Title says it all

Actually no. Please provide the required information, especially your configuration, errors, logs, etc
See https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md#issue-reports

**Comment by fraenki** [comment]
I'm closing this issue now. Please create a new issue and provide the required information.
