### ISSUE TITLE
dns/bind - add "prefetch" option

### ISSUE THREAD

**Issue by cj0duke** [opnsense/plugins#1551]
Hi,

opnsense is using bind >= 9.10 so the option "prefetch" is available for bind.

Suggested solution:
- configure check box to use the setting and configure prefetch value

Thank you

**Comment by mimugmail** [comment]
Can you give a concrete exmaple please? (config and use-case)

**Comment by cj0duke** [comment]
prefetch renews entries before their TTL expires. Therefore the entry "never expires", depending on the configured values.

According to ISC doc,  prefetch is enabled be default (for bind >=9.10).
Quote:
`BIND 9.10 prefetch values are global options. You cannot ask for different prefetch behavior in different domains. Prefetch is enabled by default.`

Config expample:
```
#prefetch disabled
prefetch 0;

#specific prefetch values set (default values)
prefetch 2 9;
```
The ISC doc:
`The first number is the "eligibility". Only records that arrive with TTL values bigger than the configured elegibility will be considered for prefetch. The second number is the "trigger". If a query arrives asking for data that is cached with fewer than "trigger" seconds left before it expires, then in addition to returning that data as the reply to the query, BIND will also ask the authoritative server for a fresh copy.`

Therefore the following questions for me came up:
- Is the option prefetch in bind with opnsense available?
- Would it be possible to set a checkbox to disable it?
- Would it be possible to configure the values for prefetch?

I thank you for your help.

**Comment by mimugmail** [comment]
Is there really a use case for this? When it expires and there comes a request it would just do a recursicve query

**Comment by cj0duke** [comment]
As mentioned before, ISC states that prefetch is enabled by default.

I am not looking at it for a specific use case, rather to take full control of the behaviour of bind, like disable/enable and/or editing the prefetch option.

**Comment by mimugmail** [comment]
I can't see any reason for tweaking these values, there might be one to disable it completely so I added a checkbox for this.
