### ISSUE TITLE
net/haproxy: First delete the error script. An error will then occur during adaptation.

### ISSUE THREAD

**Issue by penM000** [opnsense/plugins#1553]
**Describe the bug**

I read some notes before upgrading from 19.7.4 to 19.7.5.
I read https://github.com/opnsense/plugins/pull/1498

So I rebooted the system after the upgrade and checked haproxy's behavior.
As expected, an error related to the error message occurred.
So I deleted all the error message and checked the settings.
However, configuration errors continued.

I was removing all error message, including errors, so I was expecting the configuration file to be blank.

However, in reality, configuration errors remained after deleting the error script.
I solved this problem by creating a new error message and explicitly specifying that the error message be used.

**To Reproduce**
1. do upgrade
2. reboot
3. Check haproxy not working
4. all Delete Error Messages
5. do Configuration verification
6. not working (There is no error message, but the previous error remains.)

**Expected behavior**
The error message in question has been deleted, so the error message built into haproxy is used.

**Relevant log files**
```
[ALERT] 291/201316 (39264) : parsing [/usr/local/etc/haproxy.conf:154] : <errorfile> expects <status_code> and <file> as arguments.
[WARNING] 291/201316 (39264) : parsing [/usr/local/etc/haproxy.conf:163] : The 'rspadd' directive is deprecated in favor of 'http-response add-header' and will be removed in next version.
[ALERT] 291/201316 (39264) : parsing [/usr/local/etc/haproxy.conf:295] : <errorfile> expects <status_code> and <file> as arguments.
[ALERT] 291/201316 (39264) : parsing [/usr/local/etc/haproxy.conf:317] : <errorfile> expects <status_code> and <file> as arguments.
[ALERT] 291/201316 (39264) : parsing [/usr/local/etc/haproxy.conf:377] : <errorfile> expects <status_code> and <file> as arguments.
[ALERT] 291/201316 (39264) : Error(s) found in configuration file : /usr/local/etc/haproxy.conf
[ALERT] 291/201316 (39264) : Fatal errors found in configuration.
```
**Environment**
OPNsense  19.7.5_5 (amd64, OpenSSL).
Intel 3865U
Network Intel NIC

**Comment by fraenki** [comment]
> I was removing all error message, including errors, so I was expecting the configuration file to be blank.

I agree, this would be both the expected and desired behaviour.

> However, in reality, configuration errors remained after deleting the error script.

Yes, currently you have to manually remove all references to deleted error files (the same applies to many other configuration items).

It's a known limitation of the MVC framework, but it's currently not being worked on:
https://github.com/opnsense/core/issues/1897

I'm closing this issue, because it should be fixed on core. (That being said, there are ways to workaround this in the template code, but it would have to be implemented in many places.)
