### ISSUE TITLE
No arping plugin ?

### ISSUE THREAD

**Issue by Oxyaxion** [opnsense/plugins#1557]
We actually use Pfsense in production mode. 

We had tested Opnsense which is great but, but, there is NO arping tool and no plugin (like pfsense). This is an indispensable TOOL for troubleshoot network/mac problem connectivy, we use it very often.

In this situation we can remplace pfsense with opnsense without this feature ...

**Comment by mimugmail** [comment]
What exactly should this plugin achieve? Never used it on pf

**Comment by Oxyaxion** [comment]
This is juste the arping command which is available in CLI.

https://en.wikipedia.org/wiki/Arping

This is very usefull tool for detect dual IP on the same network, or the state of the cisco routeur, actually we haven't hand on the hardware routeur GW and we install Pfsense in Virtual Machine. This is very common architecture configuration in Private Cloud provider like OVH.

Sometimes they do some shit with their network, like giving 2 times the same public IP ... arping is the tool for detect this kind of mistake or egally check the status of the arp table of the cisco routeur GW.

**Comment by mimugmail** [comment]
I see. Seems there isn't even an arping pkg available yet. Maybe arpwatch would make more sense as it triggers a warning itself if it seems changing mac address. :)

**Comment by fabianfrz** [comment]
There is a simmilar plug in available:

https://github.com/opnsense/plugins/tree/master/net/arp-scan

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
