### ISSUE TITLE
Ruby 2.6 update

### ISSUE THREAD

**Issue by fichtner** [opnsense/plugins#1558]
A couple of weeks ago FreeBSD went to Ruby 2.6. Do we want to follow-up on this change for 19.7.6? As far as I heard it's compatible.

**Comment by fabianfrz** [comment]
@fichtner I tested my scripts already last year (was the latest test release) - works.

**Comment by fichtner** [comment]
ok, thanks, will update ruby version tomorrow then

**Comment by fabianfrz** [comment]
looks like there is nothing really breaking in 2.7 as well:
https://www.ruby-lang.org/en/news/2019/05/30/ruby-2-7-0-preview1-released/

**Comment by fichtner** [comment]
ok, I'll keep that in mind when FreeBSD is changing default version to 2.7 :)
