### ISSUE TITLE
Discussion Release everything regarding to the  Quagga plugin

### ISSUE THREAD

**Issue by fabianfrz** [opnsense/plugins#156]
Hi @fichtner, @mimugmail,
This is just a question for you:
The latest feature addition was 9 days ago and there are no bug reports since for the development version. There was only one bug mentioned, which affects the current stable (PR #155 fixes it).
What do you think about releasing all additions of the plugin to stable (includes OSPFv3, Diagnostics)?

Before the release is done, #155 must be merged.

**Comment by fabianfrz** [comment]
OK, Diagnostics is also a feature - It is this week but it cannot break anything as it is read only.

**Comment by mimugmail** [comment]
I updated my test env to the lasted version and it looks fine, checked some route additions in ospf6 and the diagnostics updates, all OK.

Sadly the Quagga daemon doesn't support redistributing kernel routes into ospf6. So static v6 routes in OPN are not redistributed to quagga, but this has nothing to do with the current code. 

I'm fine with going to stable ...

**Comment by fabianfrz** [comment]
@mimugmail That's cool - if `system > routes` is refactored, we can copy those routes to the zebra daemon so we have them inside quagga. This stuff also should be merged together with the quagga plugin in the `Routing` menu as dynamic and static routing (but this still needs some time and may be dome for 17.7).

**Comment by fabianfrz** [comment]
this is done in #166
