### ISSUE TITLE
[www/nginx] proxy buffer size

### ISSUE THREAD

**Issue by siga1975** [opnsense/plugins#1561]
I kindly ask to add some parameters in nginx location, related to proxy buffers
Default of 4k is not enough when you have big headers, for example if CSP is enabled with a lot of allowed hash

    proxy_buffer_size          128k;
    proxy_buffers              4 256k;
    proxy_busy_buffers_size    256k;

**Comment by fabianfrz** [comment]
please try this patch:

opnsense-patch -c plugins 8b66adcc2f683436243be5bcfee63c9a3595eb35

I wait for feedback for the final merge. If it is ok, I it will be in 1.16.

**Comment by siga1975** [comment]
Hi Fabian,
looks great! And it works fine :)

Thank you so much

Cheers
Attilio

**Comment by fabianfrz** [comment]
@siga1975 the validation was hard to implement but it seems to be very failsafe now (except if I missed some size checking which is not documented).

**Comment by siga1975** [comment]
for the moment I just checked with the values I had previously inserted
manually, and did a diff of the 2 conf files, then restarted the
application and checked a bit on my site, all is working good

but I didn't do a full test trying for invalid values and so...

**Comment by fabianfrz** [comment]
Will be now in plugin release 1.16.
