### ISSUE TITLE
dnscrypt-proxy: anonymized_dns

### ISSUE THREAD

**Issue by agh1467** [opnsense/plugins#1563]
With version 2.0.29 and above, there has been added support for anonymized queires. This is done via the [anonymized_dns] section of the dnscrypt-proxy.toml file.

It's described in the source repo at: https://github.com/DNSCrypt/dnscrypt-proxy/blob/master/dnscrypt-proxy/example-dnscrypt-proxy.toml

Here is an excerpt from the source.

```
################################
#        Anonymized DNS        #
################################

[anonymized_dns]

## Routes are indirect ways to reach DNSCrypt servers.
##
## A route maps a server name ("server_name") to one or more relays that will be
## used to connect to that server.
##
## A relay can be specified as a DNS Stamp (either a relay stamp, or a
## DNSCrypt stamp), an IP:port, a hostname:port, or a server name.
##
## The following example routes "example-server-1" via `anon-example-1` or `anon-example-2``,
## and "example-server-2" via the relay whose relay DNS stamp
## is "sdns://gRIxMzcuNzQuMjIzLjIzNDo0NDM".
##
## !!! THESE ARE JUST EXAMPLES !!!
##
## Review the list of available relays from the "relays.md` file, and, for each
## server you want to use, define the relays you want connections to go through.
##
## Carefully choose relays and servers so that the are run by different entities.
##
## "server_name" can also be set to "*" to define a default route, but this is not
## recommended. if you do so, keep "server_names" short and distinct from relays.

# routes = [
#    { server_name='example-server-1', via=['anon-example-1', 'anon-example-2'] },
#    { server_name='example-server-2', via=['sdns://gRIxMzcuNzQuMjIzLjIzNDo0NDM'] }
# ]
```

This would require the addition of a new tab since it's a different concept from the other tabs.

Here's a reddit post from the maintainer about the topic: https://www.reddit.com/r/dnscrypt/comments/dhoxah/anonymized_dns_is_here/

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.

**Comment by mimugmail** [comment]
You can reopen and assign me, hopefully I find some time later this year

**Comment by agh1467** [comment]
FYI, I've taken a look at this plugin over the weekend and am currently working on updating it. I've successfully added support for source definitions and the anonymized DNS feature, and I've added all new global settings. I'm also working on expanding functionality in other areas as well.

**Comment by dohlin** [comment]
Any updates on this?  Would be a really nice feature to have!

**Comment by agh1467** [comment]
Coincidentally, I have been working on this recently. I'm going to work to see if I can at least get something usable published to my fork in github, as I have completed the feature which covers these settings along with many others not included in the current plugin. It will take a while longer for it to get accepted and published in the official repos. I've made drastic changes to the structure of the plugin itself, the data model and forms, as well as the UI, and I've added many new features. To that end it is practically a different plugin, so there unfortunately will be more code to review, and likely feedback for changes/improvements. Though the recommended method for plugin updates is incremental changes, there are far too many for that to be reasonable. I intend to provide it fairly polished though.

I should be able to produce a package from the repo which could then be used to install it on a system, though I'm only finding instructions for production of the package itself, and not installation of the package on a system.

**Comment by agh1467** [comment]
I've now finished support for all settings. I'm working on various clean up, code commenting/documentation, and making sure my rants don't make it in or at least re-word them. I have only a few minor things to re-work, and then some testing to make sure it all still works. It'll be ready for consumption after that.

**Comment by agh1467** [comment]
Most of the documentation is done. I also figured out how to build a package, how to install it on OPNsense, and tested this procedure and verified it works as expected. So, I should be able to provide a package, as well as post the instructions on my github.

I noticed that on my 21.1 OPNsense, it's got the latest version of dnscrypt-proxy, 2.0.45. In this version a few more settings have been added, and the names of several others have been changed. I wrote everything so far for 2.0.44, so I'm going to make those updates as it's now reporting in the logs that the config is using deprecated setting names.

I should be able to commit something to my github pretty soon.

**Comment by agh1467** [comment]
Ok @dohlin. If you'll bear with me, this is the first time doing any of this stuff, but I think I got it sorted. I was able to put together a package, which can be installed on an opnsense box through SSH. Instructions and package are located here:

https://github.com/agh1467/plugins/releases/tag/v1-devel

Documentation/Instructions are located here:

https://github.com/agh1467/plugins/tree/dnscrypt-proxy-v2.0.45/dns/dnscrypt-proxy

@mimugmail Pull request to come after I maybe get some feedback, or if I feel more confident in the state of the plugin.

**Comment by dohlin** [comment]
@agh1467 I'm not sure what I'm doing wrong, but after installing this I started setting it up just like I had the official plugin set up and I just could not get it to work.  Could not get any manual server names to pop up, and even if I disabled manual (to use automatic) configuration check would still report no servers configured.  And at one point all of my installed plugins in system showed as orphaned lol not sure what caused that.  

I am using local unbound to forward all requests to dnscrypt-proxy, but I tried installing this package twice.  I made sure to disable the unbound forwarding prior to the 2nd install attempt but both attempts still resulted in the same thing.  I'm back to the official plugin for now, not sure what my issue is.

**Comment by agh1467** [comment]
Thanks for the feedback. I believe I understand that issue. I'll take a look at it tonight and try to come up with a more graceful way to handle that chicken/egg situation.

**Comment by agh1467** [comment]
I created this ticket for your issue: https://github.com/agh1467/plugins/issues/2

I've added a "first-time setup" process to address the issue you encountered. An explanation is provided in the issue ticket as to what's going on. If the fix doesn't resolve the issue, can you update the ticket there rather than here? Feel free to create other issue tickets as well if you encounter problems (or even have recommendations).

I've added a new release which includes the fix: https://github.com/agh1467/plugins/releases/tag/r2

**Comment by mimugmail** [comment]
What is the reason why you dont create PR of your branch so we can talk about the changes

**Comment by agh1467** [comment]
I've created a pull request here: https://github.com/opnsense/plugins/pull/2346

**Comment by vogelfreiheit** [comment]
Any progress on this?

**Comment by agh1467** [comment]
@mimugmail How do I get on the docket for a review? My updates to the plugin have full support for all settings, and it's also functional and tested with the latest version of dnscrypt-proxy v.2.1.0.

**Comment by ilikenwf** [comment]
Hey @mimugmail @agh1467 - can we get this reviewed and merged?

**Comment by mimugmail** [comment]
This is a complete rewrite and I dont have the time to review it.
If the -ng version would use a different namespace and has a PLUGIN_CONFLICTS I can add it to community repo (without support)

**Comment by fichtner** [comment]
There are open reviews for @agh1467 so let’s please work on this in a natural progression. Some functionality was supposed to be moved to core for example.

**Comment by mimugmail** [comment]
This would be best indeed :)

**Comment by mimugmail** [comment]
#2548 closes this
