### ISSUE TITLE
os-bind: New feature

### ISSUE THREAD

**Issue by Claus-Mtsn** [opnsense/plugins#1566]
Can you please add these options to os-bind plugin?

 - Add ability to edit the serial in a masterzone
 - Add ability to set 'any' in lookup and transfer in a masterzone
 - Add more Resource Records for zones. CAA, TLSA, DS, DNSKEY, RRSIG
 - Add ability to DNSSEC a zone through dnssec-keygen & dnssec-signzone command.

Thank you.

**Comment by mimugmail** [comment]
Serial: Why?
Any: Just use ACL 0.0.0.0/0
RR: Sure, I put it on my list
Dnssec: I dont use it for myself, what are the exact steps for this?

**Comment by Claus-Mtsn** [comment]
Serial: Because when you plan on reusing secondairies/slaves, they will only update if the serial is higher than the current one.
Any: BIND won't start on my opnsense, when ACL contains 0.0.0.0/0. I'll investigate if any logs are written.
DNSSEC: I'm not an expert at all, but I found this article describing the process: https://www.digitalocean.com/community/tutorials/how-to-setup-dnssec-on-an-authoritative-bind-dns-server--2

**Comment by mimugmail** [comment]
The serial has an autoincrement, it should notify the slaves with every change

**Comment by Claus-Mtsn** [comment]
As I understand it, the notification tells the slaves to do a new zonetransfer from the master. The will verify that the SOA serial is higher than the on the currently hold. But again I'm not sure.

**Comment by Claus-Mtsn** [comment]
Any: Cancel this. I must have hit a keyword or something, but it works with the suggested solution. Sorry for inconvinience. 

New request for zones: Also-notify. Ips that also needs to be notified on zoneupdates. I have a service, that requires this functionality.

**Comment by mimugmail** [comment]
I added the types, acl is fixed, dnssec is very time-intensive and there's already an issue open. also for notify is #1559 so we can close this one.

**Comment by Claus-Mtsn** [comment]
That is fantastic Michael. Thank you :)
