### ISSUE TITLE
security/acme-client: Support custom ACME directories

### ISSUE THREAD

**Issue by evaryont** [opnsense/plugins#1569]
I am running a custom certificate authority inside my network, powered in part by [Step Certificates](https://github.com/smallstep/certificates). It supports the ACME protocol, just like Let's Encrypt, but with an internal private CA rather than a public one.

I'd like to be able to point the `acme-client` plugin to it, so that the certificate is automatically renewed and reloaded, but signed with my internal CA.

I'm also considering having a hook run after certificate renewal, on a separate machine, that copies the certificate to my OPNsense router and update it's store. That feels like more work, and brittle. However, it likely my only other option outside of manually using the GUI. I'm doing that right now but I'm trying to automate for a reason. 😄 

EDIT: This would mean being able to pass an arbitrary URL as the parameter to `--server` when calling `acme.sh`. Possibly around as a part of [`eval_optional_acme_args` in certhelper.php](https://github.com/opnsense/plugins/blob/master/security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/certhelper.php#L316)?

**Comment by fraenki** [comment]
@evaryont I'm not sure. This is certainly not the main use-case of this plugin. That being said, I'm not totally opposed to this idea. I don't plan to work on this, but if someone wants to contribute this functionality, I'll review it, of course.

**Comment by fraenki** [comment]
I'm closing this issue now, but if anyone wants to contribute this functionality I'll gladly reopen it, of course.
