### ISSUE TITLE
Unbound-plus feature request: redirect denied URLs to local block page

### ISSUE THREAD

**Issue by Northguy** [opnsense/plugins#1571]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

[X] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
When using a DNSBL, the result of a blocked site is a "ERR_NAME_NOT_RESOLVED" page. Although this is a perfectly functioning block, the error message is not very clear to a user

**Describe the solution you'd like**
I would like to see a block page, which indicates that the URL has been blocked by an administrator due to an enforced policy instead of showing the NOT_RESOLVED error.

**Additional context**
Some random internet screenshots that present a rough idea:
![image](https://user-images.githubusercontent.com/1189058/68434518-731bca00-01b9-11ea-853f-7542ae2358ca.png)
![image](https://user-images.githubusercontent.com/1189058/68434727-fb9a6a80-01b9-11ea-8dc5-f27b87a434e6.png)

**Comment by mimugmail** [comment]
And where is this site hosted? There is more behind this vendor feature. No idea how to do this without running a website on OPNsense itself

**Comment by Northguy** [comment]
Maybe I am oversimplifying things, but isn't Lighttpd already serving Captive portal and GUI pages? Is it unsafe if it serves a ' dead end'  webpage also?

**Comment by mimugmail** [comment]
The problem is that the current script sets the IP address, this would need to be changed to a templated value chosen from UI. Also when this would be implemented in any way then there'll be the next wish to make the html page customizable.

This would also mean templated files in /usr/local/www .. I don't think any of core member will accept this.

**Comment by Northguy** [comment]
I understand your concerns and the implications, let's abandon the request as it has more implications than initially thought of.
