### ISSUE TITLE
postfix: check_sender_access is not working

### ISSUE THREAD

**Issue by serial-bug** [opnsense/plugins#1581]
OPNsense 19.7.6
postfix plugin ver. 1.11

**Issue:**
Sender Blocking is not working.

**Cause:**
In main.cf, under smtpd_recipient_restrictions "check_sender_access hash:/usr/local/etc/postfix/sender_access" is on 3rd position. This is wrong.

**Solution:**
To get it working again, it has to be on the first position.

It would be nice, to fix this in the main.cf template file, so it persists updates.

Thank you.

**Comment by mimugmail** [comment]
Why is it wrong? It only wont work when you have an OK in receipient first ...

**Comment by serial-bug** [comment]
Test it out... :)
At the moment, nothing gets blocked.
Set it on the first position and everything is fine.
Addresses are set to REJECT.

**Comment by mimugmail** [comment]
Sorry, works on my end. Only possibility is you have recipient with something like *@domain OK so it get's an OK before REJECT

**Comment by serial-bug** [comment]
No problem.
But i dont use wildcards in recipient list.

I have only my internal user in the recipient list:
usera@mydomain.de OK
userb@mydomain.de OK

On sender list i have:
newsletter@badmail.de REJECT
trash@spam.de REJECT

Example:
When a mail from "trash@spam.de" comes to "usera@mydomain.de", nothing gets blocked.
In my opinion, the problem is the order.:
1. usera@mydomain.de is whitelisted trough recipient list
2. trash@spam.de is blacklisted trough sender list
-> nothing gets blocked, because every mail to usera is whitelisted, in the first place.
If i flip the order, it works as expected.

**Comment by mimugmail** [comment]
And when we flip and you have sender@domain Reject and recipient@domain OK the receipient wont receive mails.

**Comment by serial-bug** [comment]
Right, then it would work as expected.
"the receipient wont receive mails." -> the recipient wont receive mails from sender@domain.

**Comment by mimugmail** [comment]
I flipped the order as we introduced recipient access to only allow existing addresses. Will be fixed in next version.
