### ISSUE TITLE
Rspamd longer history

### ISSUE THREAD

**Issue by lucas12433** [opnsense/plugins#1582]
Hi,

it would be amazing if i could change the duration of the History in the Rspamd WebUI.
At the moment it is set to 1 day, which is definitly to short.

Thank you :)

**Comment by mimugmail** [comment]
On my machine history get's back to 15.11., 4 days, I have no idea where the logic sits :)

**Comment by mimugmail** [comment]
`history_rows = 200;`

I'll make this configurable .. can you set the value via cli to 2000, restart via cli and check?

**Comment by lucas12433** [comment]
in which file is that line? :)

**Comment by mimugmail** [comment]
/usr/local/etc/rspamd/options.inc

/usr/local/etc/rc.d/rspamd restart

**Comment by lucas12433** [comment]
no its not working. 
Still showing the last 200 Mails :/

**Comment by mimugmail** [comment]
But you can verify it's not one day, but 200 lines?

**Comment by lucas12433** [comment]
Yeah, the last one is from today 9:22 when a new mail comes in, the last Mail isn't showing any more.

**Comment by lucas12433** [comment]
Whe i cachange it to "10" it is still showing the last 200 mails

**Comment by lucas12433** [comment]
i've changed the 

`nrows = 200` 
to 
`nrows = 2000`

in /usr/local/etc/rspamd/modules.d/history_redis.conf
now it is showing more than 200 entries.

And i havent seen a difference if i change  just the "history_redis.conf" and not the "options.inc"  of both files

**Comment by mimugmail** [comment]
Problem is when you receive 10 mails per second you can't just set "one week" or so .. but I can add an integer field with default 200 and you can choose the value you like

**Comment by lucas12433** [comment]
That would be perfect.

How can i implement it when its ready? :)

**Comment by mimugmail** [comment]
Maybe with 19.7.8, in General Settings hidden behind Advanced ..

**Comment by lucas12433** [comment]
okay 
thank you very very much :)
