### ISSUE TITLE
Suricata ET Pro plugin doesn't install rules

### ISSUE THREAD

**Issue by deathsdealer** [opnsense/plugins#1585]
I cannot get the ET Pro plugin to install rules.

I have the correct oink code from proofpoint and can manually download the zip from their website.

After enabling the rules, when I click download the wheel spins for a bit but nothing ever installs.

The ET Open rules will download and install fine.

There is no error message in the log files either.

I have tried this on 3 different firewalls. All are official opnsense products.

I have even tried a new install and it will still not downloading the updates.

Versions:	OPNsense 19.7.6-amd64
                FreeBSD 11.2-RELEASE-p14-HBSD
                OpenSSL 1.0.2t 10 Sep 2019

CPU Type	AMD GX-416RA SOC (4 cores)

**Comment by AdSchellevis** [comment]
best check the system log (system -> log file -> general), there's likely something wrong with your subscription preventing it from downloading, in which case you would find an error like this:


```
/rule-updater.py: download failed for https://rules.emergingthreatspro.com/my_illegal_oink_code/suricata-4.0/etpro.rules.tar.gz (http_code: 404)
```

**Comment by deathsdealer** [comment]
There's nothing in the general file about et pro

it completes the download for the abuse.ch that I have enabled.

Looks like it's not even attempting to try to download files for et pro.

**Comment by AdSchellevis** [comment]
if the version is the same, it probably wouldn't try to download again. you can check which rulesets it would try do download in` /usr/local/etc/suricata/rule-updater.config` if you flush the current files (`rm /usr/local/etc/suricata/rules/*.rules`)

Next manually initial the download:
```
/usr/local/opnsense/scripts/suricata/rule-updater.py
```

grep syslog to see what happens:
```
clog /var/log/system.log | grep rule-update
```

**Comment by deathsdealer** [comment]
Getting errors running that rule-updater.py. Nothing in logs after running it either.

Below is output.

root@opnsense.local:~ # /usr/local/opnsense/scripts/suricata/rule-updater.py
Traceback (most recent call last):
  File "/usr/local/opnsense/scripts/suricata/rule-updater.py", line 103, in <module>
    headers=rule['http_headers'], version=remote_hash)
  File "/usr/local/opnsense/scripts/suricata/lib/downloader.py", line 223, in download
    filename=url_filename)
  File "/usr/local/opnsense/scripts/suricata/lib/downloader.py", line 117, in _unpack
    return src.read().decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
root@opnsense.local:~ # clog /var/log/system.log | grep rule-update
root@opnsense.local:~ #

**Comment by AdSchellevis** [comment]
run:
```
opnsense-patch 10a30125
```

and try again, check log afterwards. (change catches UnicodeDecodeError and send it to the log)

**Comment by deathsdealer** [comment]
root@opnsense.local:~ # /usr/local/opnsense/scripts/suricata/rule-updater.py
root@opnsense.local:~ # clog /var/log/system.log | grep rule-update
Nov 20 10:41:47 opnsense.local /rule-updater.py: unable to read /usr/local/etc/suricata/rules//et_pro.malware.rules from "etpro.rules.tar.gz" (decode error)
Nov 20 10:41:47 opnsense.local /rule-updater.py: unable to read /usr/local/etc/suricata/rules//et_pro.p2p.rules from "etpro.rules.tar.gz" (decode error)
Nov 20 11:04:51 opnsense.local /rule-updater.py: unable to read /usr/local/etc/suricata/rules//et_pro.malware.rules from "etpro.rules.tar.gz" (decode error)
Nov 20 11:04:51 opnsense.local /rule-updater.py: unable to read /usr/local/etc/suricata/rules//et_pro.p2p.rules from "etpro.rules.tar.gz" (decode error)
Nov 20 11:06:29 opnsense.local /rule-updater.py: unable to read /usr/local/etc/suricata/rules//et_pro.malware.rules from "etpro.rules.tar.gz" (decode error)
Nov 20 11:06:29 opnsense.local /rule-updater.py: unable to read /usr/local/etc/suricata/rules//et_pro.p2p.rules from "etpro.rules.tar.gz" (decode error)
root@opnsense.local:~ # /usr/local/opnsense/scripts/suricata/rule-updater.py
root@opnsense.local:~ # clog /var/log/system.log | grep rule-update
Nov 20 10:41:47 opnsense.local /rule-updater.py: unable to read /usr/local/etc/suricata/rules//et_pro.malware.rules from "etpro.rules.tar.gz" (decode error)
Nov 20 10:41:47 opnsense.local /rule-updater.py: unable to read /usr/local/etc/suricata/rules//et_pro.p2p.rules from "etpro.rules.tar.gz" (decode error)
Nov 20 11:04:51 opnsense.local /rule-updater.py: unable to read /usr/local/etc/suricata/rules//et_pro.malware.rules from "etpro.rules.tar.gz" (decode error)
Nov 20 11:04:51 opnsense.local /rule-updater.py: unable to read /usr/local/etc/suricata/rules//et_pro.p2p.rules from "etpro.rules.tar.gz" (decode error)
Nov 20 11:06:29 opnsense.local /rule-updater.py: unable to read /usr/local/etc/suricata/rules//et_pro.malware.rules from "etpro.rules.tar.gz" (decode error)
Nov 20 11:06:29 opnsense.local /rule-updater.py: unable to read /usr/local/etc/suricata/rules//et_pro.p2p.rules from "etpro.rules.tar.gz" (decode error)
Nov 20 11:13:47 opnsense.local /rule-updater.py: unable to read /usr/local/etc/suricata/rules//et_pro.malware.rules from "etpro.rules.tar.gz" (decode error)
Nov 20 11:13:47 opnsense.local /rule-updater.py: unable to read /usr/local/etc/suricata/rules//et_pro.p2p.rules from "etpro.rules.tar.gz" (decode error)

**Comment by AdSchellevis** [comment]
Something changed on their end it seems `"etpro.rules.tar.gz"` vs `etpro.rules.tar.gz`. 

`opnsense-patch 16eca2b`  on top of the other one.

**Comment by deathsdealer** [comment]
Success! 

Nov 20 20:46:13 opnsense.local /rule-updater.py: download completed for https://rules.emergingthreatspro.com/2055658823644568/suricata-4.0/etpro.rules.tar.gz
Nov 20 20:49:36 opnsense.local /rule-updater.py: download completed for https://rules.emergingthreatspro.com/2055658823644568/suricata-4.0/etpro.rules.tar.gz

Thank you so much!

**Comment by mimugmail** [comment]
Please, remove those URLs .. it's your billing ID ;)

**Comment by AdSchellevis** [comment]
oops, I've dropped it for you @deathsdealer.

**Comment by tworth04** [comment]
I'm still seeing this issue on current 20.1.1 release.  I tried applying the 2 patches above just in case but no luck on that front.

Feb 20 20:21:53 OPNsense /rule-updater.py: download failed for /suricata-4.0/etpro.rules.tar.gz (http_code: 404)
Feb 20 20:21:54 OPNsense /rule-updater.py: version response for https://rules.emergingthreats.net/open/suricata-4.0/version.txt : 9409
Feb 20 20:21:55 OPNsense /rule-updater.py: download completed for https://rules.emergingthreats.net/open/suricata-4.0/emerging.rules.tar.gz

**Comment by Low351** [comment]
I am still having this problem with opnsense 

> OPNsense 21.1.7_1-amd64
> FreeBSD 12.1-RELEASE-p18-HBSD
> OpenSSL 1.1.1k 25 Mar 2021

Seems silly that it's still a problem, I'm experiencing the exact same issues as the OP
