### ISSUE TITLE
Rspamd redirect Spam Mails and change reject Message

### ISSUE THREAD

**Issue by lucas12433** [opnsense/plugins#1588]
Hello,
at the moment i am doing these Steps to change the reject message for (file rejects in Mails) and not rejecting normal Spam mail, just redirecting them to another Mail adress.

1.0 changing the reject message
1.1 go to /usr/local/opnsense/service/templates/OPNsense/Rspamd/multimap.conf
1.2 change the "SYMBOL" Text
1.3 change the "SUBJECT" to "redirect"

2.0 Milter check for redirecting Spam messages
2.1 go to /usr/local/opnsense/service/templates/OPNsense/Postfix/main.cf
2.2 add the line below over "End System Defaults"
`milter_header_checks = pcre:/usr/local/etc/postfix/milter_header_checks`
2.3 go to /usr/local/etc/postfix/
2.4 create the File "milter_header_checks"
2.5 add the text below to the "milter_header_checks" file
`/^Subject: .*SPAM.*/ REDIRECT spam@domain.com`

Done.
All Spam Mails which Rpamd is "rewriting subject" aren't going to the users Mailbox, they are sent to "spam@domain.com".
Mails with the "reject" action, like "multimap" are still getting rejected, but with the Message you entered under 1.2

Would be amazing if someone could add these function or parts of them to the WebUI.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
