### ISSUE TITLE
os-iperf: no udp

### ISSUE THREAD

**Issue by labor4** [opnsense/plugins#1592]
Hello all

V: OPNsense 19.7.7-amd64

i think os-iperf will not open UDP on the firewall.
It probably should?

(Guessing fw because iperf3 opens both tcp/udp with basic -s commands)

Cheers

**Comment by mimugmail** [comment]
Why should it open a port? You have to do this on your own

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
