### ISSUE TITLE
frr rip/ospf router metric

### ISSUE THREAD

**Issue by darkain** [opnsense/plugins#1595]
I have multiple routers in parallel, but they don't all have the same performance. For example, I have one router that can do 300mbps over VPN, and a second that can do 1000mbps over VPN. I'm using a combination of RIP and OSPF to share routes between multiple locations over these VPN tunnels. The problem is that the backup VPN (the 300mbps) keeps taking over instead of having the faster primary VPN (the 1000mbps) acting as primary.

The only issue is that they're both reporting the exact same route metric, with no way to configure it currently.

And no, these routers are not handling "default router" traffic, only a few select private IP ranges between multiple co-locations, so any metric setting that applies to sharing just the "default router" I dont think would be appropriate for this.

http://docs.frrouting.org/en/latest/ripd.html#rip-metric-manipulation

http://docs.frrouting.org/en/latest/ospfd.html

**Comment by mimugmail** [comment]
Doesnt ospf cost fix this?

**Comment by darkain** [comment]
There is a cost for a default route, but this isn't a default route.
There is a cost for interfaces (separate from routes), but it doesn't appear to actually effect the route metric at all.

**Comment by mimugmail** [comment]
Can you post the config and sh ip stuff please? From your post it's not rellay clear which protocol runs over VPN? As ospd has a higher AD metric over RIP would not help. 

If you can evaluate via CLI that a metric parameter fixes your issue I can add one

**Comment by darkain** [comment]
I'm use OSPF over ZeroTier, and this appears to be working fine, but I'm using RIP to distribute the OSPF information to a local router, and all metrics are showing up exactly the same in RIP regardless or router metric, OSPF metric, latency, number or hops, or anything else.

300mbps router:
`Building configuration...

Current configuration:
!
frr version 6.0.2
frr defaults traditional
hostname router-1.saturn
log syslog warnings
!
interface zte9mjkamp8ogi3
 ip ospf cost 2000
!
interface zte9mjkampfutdp
 ip ospf cost 2000
!
router rip
 version 2
 redistribute ospf
 network 192.168.10.0/24
 network 192.168.200.0/24
 passive-interface sk0
 passive-interface sk2
 passive-interface sk3
 passive-interface zte9mjkamp8ogi3
 passive-interface zte9mjkampfutdp
!
router ospf
 passive-interface sk0
 passive-interface sk2
 passive-interface sk3
 network 172.16.4.0/22 area 0.0.0.0
 network 172.16.12.0/22 area 0.0.0.0
 network 192.168.10.0/24 area 0.0.0.0
 network 192.168.200.0/24 area 0.0.0.0
!
line vty
!
end
`

1000mbps router:
`Building configuration...

Current configuration:
!
frr version 6.0.2
frr defaults traditional
hostname router-3.saturn
log syslog warnings
!
interface zte9mjkamp8ogi3
 ip ospf cost 1
!
interface zte9mjkampfutdp
 ip ospf cost 1
!
router rip
 version 2
 redistribute ospf
 network 192.168.10.0/24
 network 192.168.200.0/24
 passive-interface igb3
 passive-interface igb2
 passive-interface igb0
 passive-interface zte9mjkamp8ogi3
!
router ospf
 passive-interface igb0
 passive-interface igb2
 passive-interface igb3
 network 172.16.4.0/22 area 0.0.0.0
 network 172.16.12.0/22 area 0.0.0.0
 network 192.168.10.0/24 area 0.0.0.0
 network 192.168.200.0/24 area 0.0.0.0
!
line vty
!
end`

I'm using a layer-3 switch which only supports RIP to receive the routes from the pair of OPNsense routers, but as mentioned, both OPNsense routers are showing the exact same metric over RIP to the layer-3 switch. The layer-3 switch is my default gateway for the LAN, and then things get routed out from there as needed.

OSPF does appear to be using the route metrics properly, where the 300mbps router is forwarding packets through the 1000mbps router before going out across the wire. But this still means the clients on the network are running through the slower 300mbps link.

![image](https://user-images.githubusercontent.com/2524251/69890328-ea6ce700-12a9-11ea-8f3b-82dabcc91dc9.png)

This is what the layer-3 switch sees. 192.168.10.0/24 is the local LAN. 192.168.200.0/24 is directly attached to the two OPNsense boxes, this is my ZeroTier network. 192.168.100.0/24 and 192.168.20.0/24 are both far networks beyond ZeroTier (multiple hops away). However, all of these networks are showing up as the same distance over RIP sent from OPNsense/FRR.

192.168.10.1 and 192.168.10.5 are both 300mbps routers (yes, there are actually two of these, not one), and they are the ones the layer-3 switch are preferring, just because they advertised first.

![image](https://user-images.githubusercontent.com/2524251/69890518-0624bd00-12ab-11ea-853b-cbe7c281550d.png)

Trace route:
192.168.10.2 (layer-3 switch)
192.168.10.1 (300mbps OPNsense router)
192.168.10.3 (1000mbps OPNsense router)
192.168.200.20 (1000mbps OPNsense router in other co-location)
192.168.20.202 (destination)

If I can get RIP to accurately report the cost of each of the local OPNsense routing paths, that should solve this, since after further investigation, it looks like OSPF is doing its proper job.

**Comment by darkain** [comment]
Just an FYI: this perfectly solved the issue. Routes are propagating correctly through OSPF>RIP now with proper metrics and router priority. Thanks!

![image](https://user-images.githubusercontent.com/2524251/70095533-d8f14b00-15d9-11ea-8dc9-a25815d8dd77.png)
