### ISSUE TITLE
add custom DPI to ntopng

### ISSUE THREAD

**Issue by robvanhooren** [opnsense/plugins#1597]
hi, since you don't read a conf file at startup, could you add the -p parameter to the startup script and point it to a file?

this allows users to reduce the amount of "Unknown" traffic classification, by including custom information for the nDPI parser.

**howto:**

for **`/usr/local/etc/rc.d/ntopng`**

add

**`dpi_path=/usr/local/etc/custom.protos`** after the **`user_path`** definition line

then tack **`-p {dpi_path}`** somewhere in the **`command_args`** line (maybe right after the -G pidspec?); perhaps touch the custom.protos file too, if it doesn't already exist.

fwiw, if you need a user help blurb for the thing, perhaps mention the custom.protos file takes the format as in **https://github.com/ntop/nDPI/blob/dev/example/protos.txt**

_(consider adding in whatever GUI bits, if you want to make it fancy)_

thanks!!

R.

**Comment by mimugmail** [comment]
Conf is loaded via rc parameter

https://github.com/opnsense/plugins/blob/master/net/ntopng/src/opnsense/service/templates/OPNsense/Ntopng/ntopng

Do you know if there is also a default for this path?

**Comment by mimugmail** [comment]
Any news here?

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.

**Comment by mimugmail** [comment]
@robvanhooren with latest ndpi, is this still relevant?

**Comment by robvanhooren** [comment]
hmmm. haven't looked at latest, so I don't actually know. are the pkgs in 20.7 newer than 20.1.8_1? I haven't got an instance of 20.7 spun up.
