### ISSUE TITLE
NAT64 via Tayga

### ISSUE THREAD

**Issue by lattera** [opnsense/plugins#16]
Since FreeBSD doesn't provide NAT64 natively, maybe [Tayga](http://www.freshports.org/net/tayga/) could fill that role? I have no experience with Tayga, though, and I don't know if it'd work with all IPv6 setups (like TunnelBroker).

**Comment by mimizone** [comment]
It seems like NAT64 is being worked on in pf. https://wiki.freebsd.org/IPv6TODO#NAT64.2FDNS64.

I am not familiar with the development cycle of freebsd/opnsense though to understand when it will be usable and integrated in opnsense.  I discovered opnsense 20 minutes ago, as an alternative to my current pfsense setup... :)

**Comment by AdSchellevis** [comment]
I think that page has been there for quite some time, nat64 is currently only supported with ipfw by my knowledge (https://github.com/freebsd/freebsd/blob/release/11.1.0/sys/conf/NOTES#L984), haven't seen code for pf so far unfortunately.

**Comment by sjorge** [comment]
There also seems to be http://netbsd.gw.com/cgi-bin/man-cgi?faith+4.i386+NetBSD-7.1.1, but it seems to be rather tightly integrated with npf/netBSD. So alas, also not usable for us.

**Comment by fichtner** [comment]
No contributor offered time in almost 3 years, closing issue.

**Comment by mimugmail** [comment]
Please reopen and assign me, I take this
