### ISSUE TITLE
NET-SNMP - Make SysDesc more descriptive

### ISSUE THREAD

**Issue by FingerlessGlov3s** [opnsense/plugins#1602]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

[X] The title contains the plugin to which this issue belongs

**Describe the bug**
When using SNMP monitoring tools such as LibreNMS, the Device OS detection is done via the SysDesc. Which currently reports the output of `uname -a` from the looks of it.

My idea is to use https://github.com/opnsense/plugins/blob/master/net-mgmt/net-snmp/src/opnsense/service/templates/OPNsense/Netsnmp/snmpd.conf to set the SysDesc to format this value like this, or something to this effect.
`OPNsense Firewall - 19.7.7 amd64`

I'm guessing someting like `OPNsense.info.version`, exists to get the 19.7.7 value.

Or maybe user override in the WebUI?

**To Reproduce**
1. Name the firewall without the word OPNsense in it. Firewall1 for example
2. Add to LibreNMS
3. Once its done its full discovery, it believes its a FreeBSD device. (Technically Correct), but should identify as OPNsense.
4. Manually edit /usr/local/share/snmp/snmpd.conf to add "sysDescr OPNsense Firewall"
5. kill and rerun the snmpd process
6. Once LibreNMS does another full discovery, it then reports as OPNense device.

**Expected behaviour**
Device would be described as OPNsense, so SNMP monitoring tools see it as a OPNsense Device.

**Screenshots**
This one has the value set
![image](https://user-images.githubusercontent.com/3495647/69979076-83f3fd00-1525-11ea-92ed-4ab60ccaf362.png)

This one does not.
![image](https://user-images.githubusercontent.com/3495647/69979100-90785580-1525-11ea-91f3-5a86058f311d.png)

OPNsense 19.7.7 (amd64, OpenSSL).
Proxmox Guest
VirtIO

**Comment by mimugmail** [comment]
Sure that you searched the Open issues? ;)

https://github.com/opnsense/plugins/issues/892

@fichtner how to go on with this?

**Comment by FingerlessGlov3s** [comment]
I searched the core repo 😐 woops.

Can close this one if needs be.

**Comment by mimugmail** [comment]
Problem is that a text field doesnt update.

@fichtner maybe we can set the version after update in config.xml so we can template it here like {{ system.version }}

**Comment by fabianfrz** [comment]
Can we close one of them to avoid redundancy.

**Comment by FingerlessGlov3s** [comment]
Any news on the proposed formatting?

**Comment by fabianfrz** [comment]
@mimugmail your idea is stupid. This can be done in the helpers which can contain such helper functions

**Comment by fabianfrz** [comment]
@mimugmail opnsense/core#3845 you my develop a path with my core patch.

**Comment by fichtner** [comment]
> @mimugmail your idea is stupid.

Can we avoid such unfavourable comments in the future? Thanks!
