### ISSUE TITLE
[feature request] SSDP/DLNA multicast discovery support across subnets

### ISSUE THREAD

**Issue by hippi-viking** [opnsense/plugins#1605]
Hello,

It would be great if OPNSense supported SSDP (DLNA discovery) across subnets, which would make Chromecast/Sonos/other DLNA-only devices discover eachother across subnets. As per [link](https://forum.netgate.com/topic/139218/sonos-speakers-and-applications-on-different-subnets-vlan-s) `pimd` could be a drop-in replacement for `mdns-repeater` extending the already-present mDNS support (224.0.0.0/24) with SSDP (239.255.255.250) for those non-Apple devices.
Please consider including `pimd` in the package repository!

Cheers.

**Comment by mimugmail** [comment]
pimd is easy to buils:

```
opnsense-code ports
cd /usr/ports/net/pimd
make install

```

Then you can go on like in the link.
If it really solves your problem I can build a plugin after 20.1 (when @fichtner builds a pkg)

**Comment by hippi-viking** [comment]
Thanks! Installation was straightforward (the binary vanilla FreeBSD package installation also works as proposed at the linked forum), I am currently investigating this solution. So far there is no visible difference to mdns-repeater (it does not work yet), I suspect the wlan router might intercept the multicast traffic (or the devices are not really DLNA compliant contrary what is stated). I will get back if there is any breakthrough.

**Comment by hippi-viking** [comment]
Hello,

Just a quick update: I didn't get anywhere with multicast routing yet, and I feel more and more lost. :( I might be missing something vital. Could you please enlighten me which [config file](https://github.com/opnsense/src/tree/master/sys/amd64/conf) is used for the current x64 OPNSense kernel? If I list the strings in the kernel binary I can see `options MROUTING` but I cannot find it in the conf sources which might be the reason for this not working for me. Do you know a better way to tell if multicast routing is turned on in the kernel?

Anyway I think replacing mdns-repeater with pimd is a good move as mdns-repeater only forwards 224.0.0.251/32 (which mainly works for Apple devices) while pimd does this for the whole 224.0.0.0/4 if I get it correctly. (Alternatively if mdns-repeater could be made to forward the whole /4 range would solve a lot of issues with different devices - I will check this with the respective upstream developers.)

**Comment by mimugmail** [comment]
You can join here

https://forum.opnsense.org/index.php?topic=15385.msg70102#new

**Comment by hippi-viking** [comment]
Thank you, I will check it out.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
