### ISSUE TITLE
[feature request] Whitelisting multicast groups igmpproxy

### ISSUE THREAD

**Issue by Staticznld** [opnsense/plugins#1606]
Is it possible to add "whitelist" in the igmpproxy config page?
Greetz.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
