### ISSUE TITLE
net-mgmt/zabbix-agent: TLS support

### ISSUE THREAD

**Issue by pmuller1990** [opnsense/plugins#1610]
Do you plan to add TLS support for zabbix-agent? My zabbix-server has public IP only and all my other agents send data over TLS. I guess it would welcome more users..

**Comment by fraenki** [comment]
@pmuller1990 I agree, that would be a welcome addition. However, it's not on my current schedule.

**Comment by mimugmail** [comment]
Is this like shared secret encryption in proxy or requires certificate management?

**Comment by pmuller1990** [comment]
I would need just simple PSK method.. Or add a posibility of custom options in the web form (like Haproxy lugin)

**Comment by mimugmail** [comment]
If it's just the same as with zabbix-proxy you can assign me. I'll take a look at it.
