### ISSUE TITLE
dns/dyndns "Custom (v6)": allow specifying custom IPv6 interface identifier

### ISSUE THREAD

**Issue by maurice-w** [opnsense/plugins#1612]
[X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

[X] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
When using dynamic IP addresses and running a dual-stack service on a host in the LAN, you currently have to use two separate dyndns clients: The OPNsense dyndns plugin for updating the IPv4 address and a dyndns client on the host itself for updating the IPv6 address. This is because the OPNsense dyndns plugin currently cannot include the IPv6 address of the host in the update URL.

**Describe the solution you'd like**
I would like an input field in `services_dyndns_edit.php` which would allow specifying an IPv6 interface identifier (lower 64 bits of an IPv6 address). If specified, this would replace the interface identifier in the `%IP%` parameter used in the update URL (and _Result Match_).

Example:
OPNsense LAN interface IPv6 address: `2001:db8:abc:1:200:5eff:fe00:5300`
dyndns plugin _Interface to monitor_: LAN
_Custom interface identifier_ (new input field): `200:5eff:fe00:53ab`
resulting `%IP%` parameter: `2001:db8:abc:1:200:5eff:fe00:53ab`

**Describe alternatives you've considered**
Some dyndns services allow you to do this on their side (specifying a static interface identifier which then gets merged with the IP address sent by the dyndns client). But only very few offer this feature.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
