### ISSUE TITLE
security/acme-client: Support Cloudflares new token concept for DNS-01 challenge

### ISSUE THREAD

**Issue by mkilchhofer** [opnsense/plugins#1614]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues and I'm convinced that mine is new.
- [X] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
In August 2019 Cloudflare finally introduced the granular API tokens:
- https://community.cloudflare.com/t/new-api-tokens/110526
- https://blog.cloudflare.com/api-tokens-general-availability/

Neilpang/acme.sh already implemented it (https://github.com/Neilpang/acme.sh/pull/2404/commits/c25947d5447ac03ac0fae56b338e8821d49d61ac).

**Describe the solution you'd like**
I would to use this new concept to increase security of my setup.

**Describe alternatives you've considered**
Unless implemented I have to use the "Global API Key" for the DNS-01 challenge.

**Additional context**
Current Update level I use:
```
OPNsense 19.7.7-amd64
FreeBSD 11.2-RELEASE-p16-HBSD
OpenSSL 1.0.2t 10 Sep 2019

Plugins:
os-acme-client (installed) | 1.28

Packages:
acme.sh | 2.8.3
```

**Comment by Alphakilo** [comment]
well-written duplicate of #1477

**Comment by AdSchellevis** [comment]
closed the other one.

**Comment by fraenki** [comment]
Thanks to @Alphakilo this will be available in the next release.
