### ISSUE TITLE
Unable to find softether on plugin

### ISSUE THREAD

**Issue by ccmks** [opnsense/plugins#1615]
Where can I find the softether plugin on the OPNSense ver 19.7.7?

I couldn't find it anywhere

Thank you

**Comment by mimugmail** [comment]
It's not released yet as I need more testers :)

Via CLI:

`pkg install os-softether-devel`

Right now it's just an Enable button as the config tool is way more better.

**Comment by mimugmail** [comment]
@ccmks did you find the time to test it?:)

**Comment by mimugmail** [comment]
Did you test the plugin?

**Comment by ccmks** [comment]
Yes, it was working
