### ISSUE TITLE
www/nginx User configurable worker_processes and worker_connections

### ISSUE THREAD

**Issue by ibanezbass** [opnsense/plugins#1620]
It would be nice if there was a way to modify the worker_processes and worker_connections in the GUI. I started hitting 1024 connections resulting in poor performance. I've had to manually modify the nginx template as a temporary fix.

**Comment by ibanezbass** [comment]
#1621

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
