### ISSUE TITLE
Plugin - os-arpscan orphaned?

### ISSUE THREAD

**Issue by AndyX90** [opnsense/plugins#1623]
Before you ask a new question, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

Hi, sorry for posting questions here, but i can not find any announcements about this.
The plugin is marked as orphaned on previous installs and on new machines it is simply not available.

![Screenshot_20191216_105313](https://user-images.githubusercontent.com/10565317/70897213-7d1fbc80-1ff2-11ea-8116-d75986db5c0b.png)

**Comment by fichtner** [comment]
arp-scan is not ready for Python 3 so we disabled it for 19.7. Python 2 is almost EOL. We don't want to announce non-achievements and were hoping for the maintainer to step in which hasn't happened.

Now, the port in FreeBSD is marked "unfetchable" as well which is a clear sign that it will not be back come 20.1.

https://github.com/freebsd/freebsd-ports/commit/aca5844387d#diff-1fd5f30a7298aca28dc1e59e49a3d583R12

The package is still available although the port is not even though it can be built from the ports tree.


Cheers,
Franco
