### ISSUE TITLE
Add sslh as a service

### ISSUE THREAD

**Issue by sjorge** [opnsense/plugins#1630]
It would be nice to have sslh (http://www.rutschle.net/tech/sslh.shtml) as a service, or even as an option for a port forward rule. It's great to forward for example wan:443 to a ssh server, https server, openvpn server and something else (RDP for example)

Ofcourse you can use it on many ports, so having the option to configure multiple instances would be a must. (Hench the suggestion to have it under port forward as an option, it could then just spawn copies for each rule like you would with a proxy program)

**Comment by fichtner** [comment]
Reopened in plugins

**Comment by Stan-Tastic** [comment]
I'll be glad to have it as well, I tried using HAProxy for multiplexing, but it's clearly not made for this. SSLH on my previous Linux router was working flawlessly.

**Comment by coatmaker618** [comment]
Super excited to see this!
