### ISSUE TITLE
DynDNS - PHP Warning:  Invalid argument supplied for foreach() in /usr/local/etc/inc/plugins.inc.d/dyndns/phpDynDNS.inc on line 750

### ISSUE THREAD

**Issue by DanMc85** [opnsense/plugins#1633]
PHP Warning:  Invalid argument supplied for foreach() in /usr/local/etc/inc/plugins.inc.d/dyndns/phpDynDNS.inc on line 750

This error still exists on 19.7.8

**Comment by AdSchellevis** [comment]
duplicate https://github.com/opnsense/plugins/issues/1564
