### ISSUE TITLE
Add IWNX to DDNS list

### ISSUE THREAD

**Issue by phieber** [opnsense/plugins#1636]
It would be cool to have IWNX in the DDNS list as well. The integration effort would be quite low since there are already client libraries available (https://github.com/inwx).

**Comment by ei-ke** [comment]
Should be pretty easy as it is working without problems using the "Custom" option in the Dynamic DNS settings.
What I would really love to see is the integration of the API for setting DNS entries like [this](https://github.com/gehaxelt/Bash-INWX-DynDNS) bash script does as the INWX DDNS user can only update a single domain. E. g. only "example.com" or "*.example.com" or "home.example.com". For me it would be nice to be able to update "example.com" and "*.example.com" by use of the API.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.

**Comment by Starkstromkonsument** [comment]
Take a look at some caveats regarding INWX at #1611 and https://forum.opnsense.org/index.php?topic=16948.msg82344#msg82344
