### ISSUE TITLE
Widget - RSS Feeds - save settings problem

### ISSUE THREAD

**Issue by opnsenseuser** [opnsense/plugins#1637]
The settings cannot be saved. If you click on save, the RSS feeds appear in a new page without formatting. Nothing else happens. I have attached a screenshot. This problem has been around for ages.

![grafik](https://user-images.githubusercontent.com/34602360/71473610-f4660500-27d7-11ea-9da6-2b95033beee2.png)

**Comment by fabianfrz** [comment]
@AdSchellevis would you mind moving this to core since this is not a plugin issue?

**Comment by AdSchellevis** [comment]
better close and ask @opnsenseuser to open a complete ticket in core, it's not very useful to keep moving incomplete tickets.

**Comment by opnsenseuser** [comment]
Did a new ticket in Core.

**Comment by fichtner** [comment]
courtesy link because having everybody figure this out on their own is mean ;) https://github.com/opnsense/core/issues/3867
