### ISSUE TITLE
Security/Maltrail - sensor not working with remote server

### ISSUE THREAD

**Issue by juliocbc** [opnsense/plugins#1640]
Hi @mimugmail !

While testing the plugin with an external server, I can't get it work properly.

Seems that sensor don't properly write down the config, even with the IP of the remote server setted, it doesn't appear in config file `/usr/local/share/maltrail/maltrail.conf`, am I looking in correct file?

Another issue is that sensor don't goes up if server isn't enabled too (in plugin).

Blank Remote Server field even after clicked on Save button:
![Screen Shot 2019-12-27 at 18 11 18 1](https://user-images.githubusercontent.com/917729/71532871-573cc680-28d4-11ea-9ab9-5da07a7c9d8f.png)

Tested on:
OPNsense 19.7.4_1-amd64
FreeBSD 11.2-RELEASE-p14-HBSD
OpenSSL 1.0.2s 28 May 2019

**Comment by mimugmail** [comment]
Thx for the note, I added a fix for it :)
