### ISSUE TITLE
net/wol weird port behaviour

### ISSUE THREAD

**Issue by labor4** [opnsense/plugins#1648]
**Description**
Non exclusively tested reconstruction. WOL doesn't work.

When I use the GUI to wake a single host, I get an OK from the GUI.
But when I listen in via Wireshark it shows:

```
67583	3756.024125	10.24.20.1	10.24.23.255	? KNXnet/IP	144	? Unknown Service Family
```

**It turns out that this happens if** the default port 40000 is used, **but not if** for example 41000 or 40001 is used.

If I change 
https://github.com/opnsense/plugins/blob/master/net/wol/src/opnsense/service/conf/actions.d/actions_wol.conf
to...

```
[wake]
command:/usr/local/bin/wol -p 40001 -i
parameters: %s %s
type:script
```
(just the -p part)

...then Wireshark tells me that this is a sane WOL packet:

```
67950	3785.004252	10.24.20.1	10.24.23.255	WOL	144	MagicPacket for Giga-Byt_ad:7c:35 (e0:d5:5e:ad:7c:35)
```

**Environment**
- 10G "INTEL X520-SR1" Adapter
- sent to a ethernet/broadcast device target of type VLAN
- using Ubiquity Switches to produce untagged LAN using that VLANID
- listened on that untagged LAN

and
- OPNsense 19.7.7-amd64
- FreeBSD 11.2-RELEASE-p16-HBSD
- os-wol 2.2

I don't understand the basics of WOL, but I'm willing to test more if you advise me how to.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
