### ISSUE TITLE
How can I import 70000+ URLs into dnscrypt-proxy forwarding-rules.txt?

### ISSUE THREAD

**Issue by mervynsword** [opnsense/plugins#1652]
I am trying to import a list into dnscrypt-proxy forwarding-rules.txt

I tried to edit the forwarding-rules.txt in /usr/local/etc/dnscrypt-proxy by using WinSCP. But when I restart the DNSCrypt-Proxy, the forwarding-rules.txt will be reset. There are about 70000+ URLs. It`s a IMPOSSIBLE mission for me to enter them using web-GUI.

**Comment by mimugmail** [comment]
You can write a scipt to add them via api or don't use the plugin and just the pkg.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
