### ISSUE TITLE
FreeRADIUS secrets not properly escaped in clients.conf

### ISSUE THREAD

**Issue by sammie-p** [opnsense/plugins#1655]
FreeRADIUS would not start after I added a client with a particular RADIUS secret. I tried to run the daemon from the shell with debugging info turned on and it pointed to an error parsing the clients.conf file because of the secret in that file. 

It should be acknowledged that the FreeRADIUS does not document this limitation, however enclosing the secret in double quotes within the clients.conf file fixed the issue for me.

Note that the shared secret in the code below is no longer used so I have no need to keep it private. 

`root@opnsense:~ # /usr/local/sbin/radiusd -X
FreeRADIUS Version 3.0.20
Copyright (C) 1999-2019 The FreeRADIUS server project and contributors
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE
You may redistribute copies of FreeRADIUS under the terms of the
GNU General Public License
For more information about these matters, see the file named COPYRIGHT
Starting - reading configuration files ...
including dictionary file /usr/local/share/freeradius/dictionary
including dictionary file /usr/local/share/freeradius/dictionary.dhcp
including dictionary file /usr/local/share/freeradius/dictionary.vqp
including dictionary file /usr/local/etc/raddb/dictionary
including configuration file /usr/local/etc/raddb/radiusd.conf
including configuration file /usr/local/etc/raddb/proxy.conf
including configuration file /usr/local/etc/raddb/clients.conf
/usr/local/etc/raddb/clients.conf[3]: Parse error after "~": unexpected token "("
Errors reading or parsing /usr/local/etc/raddb/radiusd.conf`

`root@opnsense:~ # cat /usr/local/etc/raddb/clients.conf

client "localvpn" {
       secret    = zml*)<yZ_UAQCnW.;,~(G?]f
       shortname = "localvpn"
       ipaddr    = 127.0.0.1
}`

**Comment by mimugmail** [comment]
You have to escape them on your own:
https://networkradius.com/doc/3.0.10/raddb/clients.html

I cannot add a validation anymore since it would break current setups already using escaping.

**Comment by mimugmail** [comment]
Close?
