### ISSUE TITLE
net/haproxy: Live log view?

### ISSUE THREAD

**Issue by laralar** [opnsense/plugins#1657]
This is not an issue, but more like a feature request.

Would it be too difficult to implement a Live Log view like the one the firewall has with filter option?

With many websites and HTTP services hosted, and many requests coming (every second, or minute, it is kind of difficult to follow up the log.

For some strange reason, I tried what I normally do in Ubuntu . 

tail -f /var/log/haproxy.log

But it seems stuck in FreeBSD.  Any hint why this could be happening?

Finally,  I am using Map tables.  And where there is a no match, it would be useful to see what is the key that is being trying to match.. This two may not be related to the plugin itself but to HA Proxy, but any help would be appreciated

Thanks,
Luis

**Comment by fraenki** [comment]
> For some strange reason, I tried what I normally do in Ubuntu .
> tail -f /var/log/haproxy.log

That's because OPNsense uses circular log files in several places. You need to use `clog` to view them properly:

```
clog -f /var/log/haproxy.log
```

> Finally, I am using Map tables. And where there is a no match, it would be useful to see what is the key that is being trying to match.

The [OPNsense forum](https://forum.opnsense.org/) is a better place for this kind of question. Or even better the [HAProxy community](https://discourse.haproxy.org/).
