### ISSUE TITLE
[Request] - Chrony on 20.1

### ISSUE THREAD

**Issue by siga1975** [opnsense/plugins#1659]
It would be nice to have chronyd on new 20.1 release, since it is supported by freeBSD 12 and chrony is much better in general, but in particular for machine with a bad hardware clock, or for virtual machines (best practice on NTP servers is to have physical servers).
https://support.ntp.org/bin/view/Support/KnownOsIssues#Section_9.2.2.

Chrony is the default, for example, since RHEL7.

The only missing feature in chrony is:
- broadcast sync (I hope noone is still using this)
- autokeys authentication (unsecure by design)
- md5/sha1 authentication (not rock solid)

From a security perspective I think everyone is waiting for NTS in any case
https://blog.apnic.net/2019/11/08/network-time-security-new-ntp-authentication-mechanism/

A feature is also missing and would be nice to have is
- configure peers and not only servers
- minpoll (some ntp servers are not happy with too frequent requests)
- GPS/PPS conf currently is or prefer or noselect, it should be possible to have nothing specified

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.

**Comment by mimugmail** [comment]
Chrony is already in devel

**Comment by AdSchellevis** [comment]
@mimugmail you want to keep the issue open? this was an automated action (no assignee on the ticket)

**Comment by mimugmail** [comment]
@siga1975 pkg install os-chrony-devel
If it works for you we can move ro stable with 20.7.3 or 4

**Comment by siga1975** [comment]
OK, I will

THX

**Comment by fichtner** [comment]
Let's keep this closed. @mimugmail just let me know when you want to move this to release.

**Comment by siga1975** [comment]
looks like it works well, I would just add a dropdown with checkboxes for
networks selection, and eventually some field for advanced options

[root@myfw ~]# chronyc -n sources
210 Number of sources = 4
MS Name/IP address         Stratum Poll Reach LastRx Last sample
===============================================================================
^+ 192.168.33.41                 1   7   377    58    -36us[  -36us] +/-
1414us
^+ 192.168.33.40                 1   7   377    59   -328ns[ -328ns] +/-
1269us
^* 192.168.33.133                1   7   377    60  +4234ns[+5264ns] +/-
1242us
^+ 192.168.33.43                 1   7   377    59    +17us[  +17us] +/-
1123us

[root@myfw ~]# chronyc -n sourcestats
210 Number of sources = 4
Name/IP Address            NP  NR  Span  Frequency  Freq Skew  Offset  Std
Dev
==============================================================================
192.168.33.41              19  10   978     -0.014      0.057    -33us
 21us
192.168.33.40              19   9   978     +0.001      0.007   -716ns
 2474ns
192.168.33.133             19  12   977     -0.001      0.010   +736ns
 3257ns
192.168.33.43              19   8   978     -0.002      0.040    +22us
 15us

[root@myfw ~]# chronyc tracking
Reference ID    : C0A82185 (www.signorini.in)
Stratum         : 2
Ref time (UTC)  : Mon Sep 21 08:40:47 2020
System time     : 0.000000549 seconds slow of NTP time
Last offset     : +0.000001030 seconds
RMS offset      : 0.000012400 seconds
Frequency       : 29.498 ppm slow
Residual freq   : +0.000 ppm
Skew            : 0.007 ppm
Root delay      : 0.000159759 seconds
Root dispersion : 0.001119647 seconds
Update interval : 64.3 seconds
Leap status     : Normal

[root@myfw ~]# cat /usr/local/etc/chrony.conf

port 123
driftfile /var/db/chrony/drift
pidfile /var/run/chrony/chronyd.pid

server time0.signorini.in iburst
server time1.signorini.in iburst
server time2.signorini.in iburst
server time3.signorini.in iburst

allow 192.168.33.32/27
allow 192.168.33.96/27
allow 172.17.35.32/27
allow 172.17.33.32/27

[root@myfw ~]# netstat -anp udp|egrep "\.123|\.323"
udp4       0      0 127.0.0.1.61628        127.0.0.1.123
udp4       0      0 *.123                  *.*
udp6       0      0 ::1.323                *.*
udp4       0      0 127.0.0.1.323          *.*

**Comment by fichtner** [comment]
Both potential additions lead down a dangerous path for maintainability. 😉
