### ISSUE TITLE
Webproxy with ICAP and ClamAV never working after reboot

### ISSUE THREAD

**Issue by vistalba** [opnsense/plugins#1660]
**Describe the bug**
Webproxy with ICAP and ClamAV never working after reboot until manually restart the services in WebGUI.

**To Reproduce**
1. Configure Webproxy with ICAP and ClamAV in transparent mode
2. create NAT rule and check if traffic from browser is going trought the proxy.
3. reboot opnsense
4. when reboot completes, check internet connectivity in browser. -> ICAP error
5. restart icap, clamav, squid service manually over webgui
6. connectivity restored 

**Expected behavior**
Normal connectivity after reboot of opnsense

**Environment**
Software version used and hardware type if relevant.
e.g.: 
ESXi 6.7u3
OPNsense 19.7.3-amd64
FreeBSD 11.2-RELEASE-p14-HBSD
OpenSSL 1.0.2s 28 May 2019

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
