### ISSUE TITLE
zabbix-proxy and zabbix-agent: TLS certificate-based encryption

### ISSUE THREAD

**Issue by AmazingBeu** [opnsense/plugins#1661]
Today, zabbix-proxy only supports PSK encryption and zabbix-agent will do it soon (#1610) but not certificate-based encryption. 

It's possible to integrate it with the certificate manager (like pfsense)?

**Comment by mimugmail** [comment]
Integrate plugin to certificate store is really unthankful work. If more people chime in I can have a look in maybe Q2

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.

**Comment by brechsteiner** [comment]
I would also be interested in this
