### ISSUE TITLE
net-mgmt/zabbix-proxy: upgrade to zabbix-proxy 4.4

### ISSUE THREAD

**Issue by AmazingBeu** [opnsense/plugins#1662]
zabbix-proxy must be the same version as zabbix-server to work :
https://www.zabbix.com/documentation/current/manual/appendix/compatibility#supported_zabbix_proxies

Today, the latest stable is the 4.4.4 .

Maybe it's possible to have both the latest LTS and the latest stable package?

**Comment by fichtner** [comment]
I would think it's too much work to provide all versions so we agreed on LTS  only  CC @mimugmail

**Comment by mimugmail** [comment]
I'm not against a "lastest LTS" and "latest stable", but there has to be a decision what happens when latest stable is also latest LTS, when will the old plugin be removed. 

Mostly it's not to confuse users like offering zabbix 2.2, 2.4, 3.0, 3.2, 3.4, 4.0, 4.2 and 4.4 (like in other sense?).

**Comment by AmazingBeu** [comment]
Offering all maintained versions is in my opinion the best solution, but it will flood the list of plugins.
Then I think that users will choose the same version that they have on their server.

But maybe it's too hard for you to maintain...

**Comment by fraenki** [comment]
@fichtner I think it would be ideal to have a similar feature what can already be found in FreeBSD ports: you have a master "port" (or plugin) that contains the real code and one or more "slave" ports that just build the master port, but with different dependencies/versions. This way it would be pretty easy to have multiple versions of the same plugin, without duplicating the plugin code.

**Comment by mimugmail** [comment]
Not sure if this works for zabbix as log and config folder labeling changes e.g. /usr/local/etc/zabbix3 vs /usr/local/etc/zabbix4

**Comment by fraenki** [comment]
> Not sure if this works for zabbix as log and config folder labeling changes e.g. /usr/local/etc/zabbix3 vs /usr/local/etc/zabbix4

IMHO the config folders should never contain a version number :)

**Comment by fichtner** [comment]
The truth is the FreeBSD zabbix ports neither allow a sane "flavour" approach nor does it make it easy to implement it. We will not change the way the FreeBSD ports are laid out and we will not add more than 2-3 zabbix ports ever because nobody else will fix build issues, pull in fixes for the insane versioning that they do.

**Comment by fraenki** [comment]
> because nobody else will fix build issues, pull in fixes

Understood. I just wanted to make the proposal to "fix everything", but of course manpower is a limiting factor.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
