### ISSUE TITLE
dnsdist as a plugin

### ISSUE THREAD

**Issue by dkowis** [opnsense/plugins#1663]
[dnsdist](https://dnsdist.org/index.html) is a fantastic dns loadbalancing tool, capable of serving requests as DNScrypt or dns-tls, or dns over https.

It's got some significant anti-abuse configuration, as well as the ability to healthcheck and verify upstream dns. 

Configuration is kinda advanced tho, so it might just be exposed as a simple text editor for the LUA configuration. Not sure if it's best to just opt for a package by itself, instead of integrated with the UI.

## Alternatives

dnscrypt-proxy, ha-proxy for balancing DNS servers, but neither alone, nor combined, offer the same functionality that dnsdist does, as they're more general.

Thanks!

**Comment by craSH** [comment]
I added my vote for this, and would encourage considering it in place of the listed alternatives - dnsdist is fairly unique and powerful compared to dnscrypt-proxy and haproxy.

**Comment by rcmcronny** [comment]
+1 for dnsdist

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.

**Comment by dkowis** [comment]
What does one need to do to make this a plugin?

There's a BSD package already: https://dnsdist.org/install.html

The Contributing document doesn't tell me much about making the plugin. Is there something I could look at?

**Comment by mimugmail** [comment]
First you need to build a pkg for it:

opnsense-code ports
cd /usr/ports/dns/dnsdist/ && make install clean

When you successfully build and installed it you can follow the public guides here:
https://docs.opnsense.org/develop.html

Easiest would be to clone an existing plugin and do search+replace:
https://www.routerperformance.net/opnsense/plugin-development/

**Comment by dkowis** [comment]
Man, one day I'll have time for this, because I still wants it.

**Comment by mimugmail** [comment]
The next version of AdGuardHome plugin will also offer all option you need :)
