### ISSUE TITLE
plugins/dns/rfc2136 - Allow other key algos

### ISSUE THREAD

**Issue by dBitech** [opnsense/plugins#1664]
Currently, the rfc2136 plug has the KMAC-MD5 algorithm hard coded. md5 keys are strongly discouraged by DNS processionals,   the plugin should be updated to allow the admin to specify the algorithm that their key/secret use.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.

**Comment by av-commits** [comment]
I had the same issue and adapted the plugin locally to make the algorithm configurable. Try to do a pull request, but its my first one.

**Comment by fichtner** [comment]
@av-commits your commit looks promising! happy to review if you provide a PR :)
