### ISSUE TITLE
Include support for dns_acmeproxy with acme.sh plugin

### ISSUE THREAD

**Issue by mdbraber** [opnsense/plugins#1665]
In the latest official releases of acme.sh there's a dns_acmeproxy plugin included (see https://github.com/Neilpang/acme.sh/blob/master/dnsapi/dns_acmeproxy.sh) . Currently that plugin isn't included in /usr/local/share/examples/acme.sh/dnsapi and in the interface. It would be great if this plugin could be supported as well. I'm happy to submit a pull request, but would like to know how it's best to (first) include dns_acmeproxy.sh as is in the current upstream. Possibly @fraenki could comment on this?

**Comment by fichtner** [comment]
For the sake of historic accuracy, please do not refer to “latest” or “current” release. It makes interaction much more difficult.

**Comment by mdbraber** [comment]
@fichtner sorry. dns_acmeproxy has been included since release 2.8.2 (https://github.com/Neilpang/acme.sh/releases/tag/2.8.2) and the current package version on OPNsense is 2.8.3, but dns_acmeproxy is not included.

**Comment by fraenki** [comment]
The required file was missing in the FreeBSD port [security/acme.sh](https://www.freshports.org/security/acme.sh/), but this was [fixed a few days ago](https://svnweb.freebsd.org/ports?view=revision&revision=523245).

I'm pretty sure this fix will be available with the next release of OPNsense.

**Comment by mimugmail** [comment]
https://github.com/opnsense/ports/commit/723fe17c3999971ccd35b594cf988b1a8e235bf9
