### ISSUE TITLE
Zabbix Proxy doesn't accept multiple IPs to listen on

### ISSUE THREAD

**Issue by Calypso971** [opnsense/plugins#1667]
In the web interface for Zabbix Proxy it only accepts one interface/IP address to listen on. However, the help text mentions that multiple (comma delimited) addresses can be used. 

Zabbix Proxy itself also facilitates this (adding multiple addresses to the configfile itself in OPNSense has the desired result), so it looks like the check in the web interface is too strict (and contradicts with the help text).

**Comment by mimugmail** [comment]
I will take a look, should be easy
