### ISSUE TITLE
[dynamic-dns] Cloudflare Invalid TTL when updating DNS

### ISSUE THREAD

**Issue by calvinbui** [opnsense/plugins#1668]
**Describe the bug**
Performing a force-update on my Cloudflare DNS domains gives the following errors:

```text
opnsense: /services_dyndns_edit.php: Dynamic DNS (example.com): PAYLOAD: { "result": null, "success": false, "errors": [ { "code": 9021, "message": "Invalid TTL. Must be between 120 and 2,147,483,647 seconds, or 1 for automatic" } ], "messages": [] }
```

**Expected behavior**
Domains to be updated with new IP address

**Environment**
OPNsense 19.7.9

**Comment by vistalba** [comment]
run into the exact same issue as well.
Today there was a public IP change (once again) forced by my provider and DynDNS dosn't update the records at cloudflare. 

I enabled debug log:

```
opnsense: /usr/local/etc/rc.dyndns: Dynamic DNS (example.domain.tld): PAYLOAD: { "result": null, "success": false, "errors": [ { "code": 9021, "message": "Invalid TTL. Must be between 120 and 2,147,483,647 seconds, or 1 for automatic" } ], "messages": [] }


opnsense: /usr/local/etc/rc.dyndns: Dynamic DNS (example.domain.tld): UNKNOWN ERROR - Invalid TTL. Must be between 120 and 2,147,483,647 seconds, or 1 for automatic
```

I checked my monitoring today morning as the issue was occured and I know that the same config was working well at last public IP change (10. December 2019).

**Comment by vistalba** [comment]
cc @fichtner maybe you can help for this issue?

**Comment by fichtner** [comment]
I don't seem to find a reference for where we send TTL in Cloudflare, maybe they changed their policy/code to be explicit.... are there any docs that they published regarding TTL usage?

**Comment by fichtner** [comment]
that would be the case then https://github.com/pfsense/pfsense/commit/9404b54a44a

should be easy enough to fix and confirm... who wants to give this a shot? :)

**Comment by vistalba** [comment]
I didn‘t get any mail or notice about an API change. 

Uf... I would but I don‘t know how... :-(

**Comment by fichtner** [comment]
let me find some time tomorrow :) I'd say for now we should simply go with the automatic TTL setting... easy fix

**Comment by vistalba** [comment]
I‘ve it on auto anyway :-)
No problem... I‘m happy if it would be fixed. 
For now I updated manually. 
If there is an easy way to test just tell me an I will do.

**Comment by vistalba** [comment]
Did you found some time to test it?

**Comment by andreas-rupper** [comment]
I have updated the dyndns plugin to use the (not so) new token based authentification and to set TTL.
#1726

**Comment by fichtner** [comment]
Done.
