### ISSUE TITLE
net/haproxy: feature request for email alerts and mailers

### ISSUE THREAD

**Issue by laralar** [opnsense/plugins#1669]
Hello

I am new to opnsense and Haproxy plugin

Any idea where I can put mailers and email-alerts section.  For example:

3.6. Mailers
------------
It is possible to send email alerts when the state of servers changes.
If configured email alerts are sent to each mailer that is configured
in a mailers section. Email is sent to mailers using SMTP.

mailers <mailersect>
  Creates a new mailer list with the name <mailersect>. It is an
  independent section which is referenced by one or more proxies.

mailer <mailername> <ip>:<port>
  Defines a mailer inside a mailers section.

  Example:
    mailers mymailers
        mailer smtp1 192.168.0.1:587
        mailer smtp2 192.168.0.2:587

    backend mybackend
        mode tcp
        balance roundrobin

        email-alert mailers mymailers
        email-alert from test1@horms.org
        email-alert to test2@horms.org

        server srv1 192.168.0.30:80
        server srv2 192.168.0.31:80

**Comment by fraenki** [comment]
@laralar Currently the plugin does not support this feature. I'll consider adding it in one of the next releases, but it's not a high priority for me.

Out of curiosity, since this is being used for monitoring, have you considered using a monitoring tool for this purpose?

**Comment by laralar** [comment]
Sorry for the late response, I was out of station.

I don't have much experience with any monitoring tool.  since HAProxy has the feature, and I am opting for a simple environment with less variables to consider, the less tools the better.

For example, I could put HAProxy in another server instead of OPNSense, I had it like this, but I would prefer to have the configuration centralized

I could still disable the plugin and put HAProxy on a couple of servers, I am using LXD containers for this, and is quite simple, but I would rather have it there.

Anyway,, if there is an alternative tool for monitoring that is simple to setup, I could really consider it.. if you have any suggestions , they are welcome.

Thanks
Luis

**Comment by laralar** [comment]
Can this be set in the default settings (Advanced) Custom Settings and in the backend respective custom options?

**Comment by fraenki** [comment]
It is highly recommended to not use the options pass-thru (as stated in the help text), because it might break you configuration anytime when we upgrade to a new version of HAProxy or introduce new options.

(The custom options should be an advanced option and hidden by default, this will be fixed in the next release.)

**Comment by fraenki** [comment]
E-mail alerts and mailers will be officially supported in the upcoming os-haproxy version 3.0.
