### ISSUE TITLE
security/acme-client: Add support for the Leaseweb API

### ISSUE THREAD

**Issue by tmaniac** [opnsense/plugins#1670]
Hello,

i've installed the ACME-Client plugin in the Opnnsense fw i'm running.

However, i'm missing the Leaseweb options for DNS validation.

When i look @ the source code where this plugin is based upon, there is a leaseweb file available.

Can this be implemented in this plugin as well?

thanks!

**Comment by fraenki** [comment]
I'll consider adding support for this in one of the next releases.

For my own convenience:
https://github.com/Neilpang/acme.sh/wiki/dnsapi#90-use-leasewebcom-domain-api-to-automatically-issue-cert

**Comment by tmaniac** [comment]
Thank you very much for considering :)

(and sorry for not including the source-url in the first place)

**Comment by fraenki** [comment]
This will be available in the upcoming os-acme-client release 1.31.
