### ISSUE TITLE
NGINX cloudflare support

### ISSUE THREAD

**Issue by Ornias1993** [opnsense/plugins#1679]
**Describe the solution you'd like**
Currently the "Real IP Source" options for NGINX do not include `cf-Connecting-IP`
To support cloudflare, it would be nice if this would be an option.

Note:
Cloudflare doesn't support the other options.

**Comment by fabianfrz** [comment]
Forgot to close that. Will be in the next release.

**Comment by Ornias1993** [comment]
@fabianfrz Awesome, thanks!
