### ISSUE TITLE
"VPN: IPsec: Tunnel Settings" display problem in web gui with cicada theme in 20.1

### ISSUE THREAD

**Issue by goodomens42** [opnsense/plugins#1687]
When opening "VPN: IPsec: Tunnel Settings" in the web GUI with cicada theme phase 1 entries are displayed "white on white" and therefore unreadable, see attached screenshot.
Worked with 19.7. 

**To Reproduce**
1. Open web GUI
2. Navigate to VPN: IPsec: Tunnel Settings
3. See error (provided you have configured IPSEC Tunnels before)

**Expected behavior**

Phase 1 entries should be readable

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/60742141/73942317-1e3e3b80-48ef-11ea-88bf-255bbe26e150.png)

**Relevant log files**

not applicable

**Environment**

OPNsense 20.1-amd64
FreeBSD 11.2-RELEASE-p16-HBSD
OpenSSL 1.1.1d 10 Sep 2019

**Comment by Kimotu** [comment]
Who is responsible for this theme? 2 months and nobody assigned. Current workaround is using mouse to highlight text. Else you cannot read it.

**Comment by fichtner** [comment]
@opnsenseuser but to be fair, maintainers are volunteers and current events are difficult for all of us.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.

**Comment by mimugmail** [comment]
PR for this was added recently

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/plugins/pull/2037 ?

**Comment by mimugmail** [comment]
Yep
