### ISSUE TITLE
WireGuard doesn't start with activated peer without Public Key

### ISSUE THREAD

**Issue by GuybrushX** [opnsense/plugins#1688]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[-] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
Yes

[-] I have searched the existing issues and I'm convinced that mine is new.
Yes

[-] The title contains the plugin to which this issue belongs
Yes

**Describe the bug**
A clear and concise description of what the bug is, including last known working version (if any).
WireGuard crashes and doesn't start anymore when you add a peer without a public key.

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**
- Set up WireGuard
- Create a WireGuard peer -> leave the Public Key empty
- Add the peer to the configured WireGuard instance
- Save -> WireGuard seems to crash and will not start anymore until you remove the "empty" peer

Probably it's a WireGuard issue but since I didn't find any logs I'm not sure.

**Expected behavior**
Do some validation so it's not possible to create a broken configuration.

- Check if it's a WireGuard issue
- Allow adding valid peers only
- If available: check the WireGuard configuration before applying them and cancel if there's an error

**Screenshots**

**Relevant log files**
If applicable, information from log files supporting your claim.

**Additional context**

**Environment**
Software version used and hardware type if relevant.
e.g.:
OPNsense 19.7.10 + 20.1 - just updated running as a Hyper-V VM.

**Comment by mimugmail** [comment]
Maybe we can make the field required to be filled. Need to think of it breaks something but should be ok

**Comment by GuybrushX** [comment]
Or at least add a big warning that it will break WireGuard if it will be activated. I was lucky that I had another way to access the box.

Also it took me quite some time to understand that I need to add all peers individually to the WireGuard instance but that's another issue.
