### ISSUE TITLE
net/haproxy map file from map_dom to map_str?

### ISSUE THREAD

**Issue by ma-karai** [opnsense/plugins#1689]
As far as i can determine the backend selection currently functions with

`use_backend %[req.hdr(host),lower,map_dom(/tmp/haproxy/mapfiles/mapfile.txt,bk_defaultbackend)] `
with a mapfile.txt containing something like this:

`sub.domain.tld bk_subdomain`

when navigating to sub.domain.tld the properbackend will be selected. however i would like to be able to forward directories e.g

`sub.domain.tld/dir bk_otherbackend`

which does not work with map.dom in the usebackend code. How would i go about this ?

**Comment by fraenki** [comment]
> which does not work with map.dom in the usebackend code. How would i go about this?

I don't know. How would you write the config with plain HAProxy?

**Comment by ma-karai** [comment]
good question. I suppose i would replace and see if it works.

`use_backend %[req.hdr(host),lower,map_dom(/tmp/haproxy/mapfiles/mapfile.txt,bk_defaultbackend)]`
with
`use_backend %[req.hdr(host),lower,map_str(/tmp/haproxy/mapfiles/mapfile.txt,bk_defaultbackend)]`
or just
`use_backend %[req.hdr(host),lower,map(/tmp/haproxy/mapfiles/mapfile.txt,bk_defaultbackend)]`

not really sure tbh, i would just try it, i mean i can manually try today and see what works best.  and report back
https://www.haproxy.com/blog/introduction-to-haproxy-maps/

**Comment by ma-karai** [comment]
I just tried editing the file /usr/local/etc/haproxy.conf to map_end, map_str and just map, and neither of them works the way i wanted, haha. 

Not sure if i edit the proper conf file tho. There was a nice button at somepoint where i could see the current loaded haproxy.conf but its not there anymore.

**Comment by fraenki** [comment]
> I just tried editing the file /usr/local/etc/haproxy.conf to map_end, map_str and just map, and neither of them works the way i wanted, haha.

Unfortunately I cannot really help to find the correct solution. The [HAProxy Community](https://discourse.haproxy.org/) is always a good place to ask questions specific to HAProxy :)

If you find a working configuration I'll add support for it to the os-haproxy plugin.

**Comment by ma-karai** [comment]
tried a bunch of things nothing seem to work for me :(

**Comment by ma-karai** [comment]
tbh: the haproxy community is quite slow to response, some map file related questions have stayed unanswerd for over one year. anyway i leave the link to the haproxy discourse here just as a reminder 

https://discourse.haproxy.org/t/haproxy-mapfile-backendselection-with-directory/4852

**Comment by fraenki** [comment]
> If you find a working configuration I'll add support for it to the os-haproxy plugin.

@ma-karai I've seen that there was some discussion in the HAProxy community. Did you figure it out and could provide a working example configuration?

**Comment by ma-karai** [comment]
Hi, the haproxy community recommended to me that i give a 
`use_backend %[base,lower,map_beg(mapfile.txt,bk_defaultbackend)]` which i did, however it did not work as intended on my installation, i cant really tell you why.

**Comment by fraenki** [comment]
Thanks. I'm sorry that you couldn't find a solution. :-/
So I'll close this issue now because giving advice for HAProxy configuration is pretty much out of scope for this project. That being said, I'll gladly reopen this ticket and implement the required features if you or someone else provides a working configuration example.

**Comment by ma-karai** [comment]
of course, thanks frank!
