### ISSUE TITLE
dns/bind Docs » Development Manual » API Reference » bind

### ISSUE THREAD

**Issue by n35k3nd1r** [opnsense/plugins#1698]
**Important notices**
I have read the contributing guide lines at 
I have searched the existing issues and I'm convinced that mine is new.
When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
Docs could be helpful finding a solution for Issue [#1696 ](https://github.com/opnsense/plugins/issues/1696)

**Describe the solution you'd like**
Can you please update the documentation for the bind api?
https://docs.opnsense.org/development/api/plugins/bind.html

Several commands are missing there. For example, the controller "domain" is not documented.

**Describe alternatives you've considered**
Can you tell me the full api reference for bind plugin?

**Additional context**
NONE

Thanks a lot!

**Comment by n35k3nd1r** [comment]
@AdSchellevis 
What do you mean, incomplete? Any information missing from me? Which?

Or are you not responsible for the plugin doku?

**Comment by AdSchellevis** [comment]
no template used, but that doesn't mean someone can't create a PR in docs to add content.

**Comment by n35k3nd1r** [comment]
@AdSchellevis
Better now?

**Comment by mimugmail** [comment]
I think you can edit the file in github, take the table for acl, copy and replace the names with domain and record .. then this should be good to go :)

**Comment by AdSchellevis** [comment]
@mimugmail the original plan was to generate these files  periodically, so I wrote our python script to generate them now. The first batch came in via a powershell script, but we don't use that ourselves.  

https://docs.opnsense.org/development/api/plugins/bind.html should contain the proper endpoints now.
