### ISSUE TITLE
net/haproxy: bug report

### ISSUE THREAD

**Issue by fichtner** [opnsense/plugins#17]
For details see https://forum.opnsense.org/index.php?topic=3153.0

**Comment by manusfreedom** [comment]
See my second post for some fix.
I will try continue to add fix during next week.

**Comment by fraenki** [comment]
@manusfreedom: Thanks for the report. Care to submit a pull request? Sounds like you were able to fix everything on your side already.

**Comment by manusfreedom** [comment]
https://github.com/opnsense/plugins/pull/19

**Comment by manusfreedom** [comment]
All done in the pull request, please check and integrate if ok.

**Comment by fraenki** [comment]
@manusfreedom: Thanks for your pull request! Indeed very useful changes. I've added some comments. I hope you agree to make some small changes.

**Comment by manusfreedom** [comment]
All fixed as requested.
