### ISSUE TITLE
Quagga: Prefix-lists for OSPF

### ISSUE THREAD

**Issue by mimugmail** [opnsense/plugins#170]
@fabianfrz I have a request for prefix-lists in OSPF. Do you mind if I add the BGP code also to OSPF or do you want to have a look on your own?

**Comment by fabianfrz** [comment]
@mimugmail I am currently not having a lot of time. Before you start working at it, I would recommend you to wait until we release the BGP stuff. So you won't duplicate bugs if there are any.

**Comment by fabianfrz** [comment]
@mimugmail we got no bug reports the last time so this is probably bug free.

**Comment by fichtner** [comment]
are we ok on releasing our current master state with 17.1.10?

**Comment by fabianfrz** [comment]
@fichtner the only thing that would prevent it from being added would be the feature @mimugmail used for it which was not on the stable branch in core when the last version was released. If this patch in core has been added to stable there is no problem with adding the current state to stable.

**Comment by mimugmail** [comment]
@fabianfrz Hopefully it was tested by a few a people, but I'm ok with releasing it. :)
@fichtner Yep, master can go to 17.1.10

I spend some time for OSPF and prefix-lists but there are 2 or 3 ways to use them, so it's not just copy+paste from BGP stuff.

**Comment by fichtner** [comment]
will merge now. please close tickets that can already be closed, there are a few open. thanks! :)
