### ISSUE TITLE
[os-nginx] add proxy_ssl_server_name tickbox

### ISSUE THREAD

**Issue by CeeMac-git** [opnsense/plugins#1703]
I'm on 19.7.10 with nginx plugin 1.17 and have an issue with TLS decrypt / recrypt using http server -> location - > backend. The upstream server terminates TLS and performs SNI matching to route traffic into a kubernetes cluster. The Ingress is not matching anything and during debugging it was noticed that the 'Server Name Indicator' header was empty on the request post nginx plugin. Performing a curl directly to the upstream shows a complete SNI header.

Looking at the core nginx documentation I would need to set 'proxy_ssl_server_name = on' however there doesn't appear to be an equivalent setting in the plugin UI. Is this something that could be easily added? Probably in the Advanced settings of the Location alongside the proxy buffer settings etc would be a good place?

**Comment by fabianfrz** [comment]
Fixed for 1.19
