### ISSUE TITLE
Nginx: client_max_body_size

### ISSUE THREAD

**Issue by rrosson** [opnsense/plugins#1708]
**Is your feature request related to a problem? Please describe.**
Allow for tuning Nginx's client_max_body-size. This would allow for applications like nextcloud sitting behind Nginx reverse proxy to function properly. Current hardcoded limit is 200M

**Describe the solution you'd like**
Allow for tuning Nginx's client_max_body-size.

**Describe alternatives you've considered**
Only alternative is to edit the Nginx.conf by hand

**Comment by 2start** [comment]
I have the same problem. I'd like to change the client_max_body_size. 200M seems to be a pretty arbitrary value. The comment above the value in the opnsense nginx.conf says that this should be enough for fileservers but it simply isn't. Alternative would be to just raise the limit to a few gigabytes, however this also is pretty arbitrary.

**Comment by fabianfrz** [comment]
It is already in the current plugin. No change necessary: "Maximum Body Size"

**Comment by rrosson** [comment]
I disagree with this being closed and should be reopened. In looking at the configuration file after adding the value of 600m to Maximum Body Size" (which is found in the plugin under Services -> Nginx -> Configuration -> HTTP(S) -> Location) the client_max_body_size remained the original value and there is no entry of the value I set. So now I have a concern if there  is a bug between the GUI and to what is written to the appropriate file in /usr/local/etc/nginx/

So please re-open and provide more detail of what you have in the GUI and what exact entry should be written to the file to avoid having to search through the code of the plugin. This would help the people who are just trying to stay in the GUI and avoid dropping to the shell to hand edit a file.

Nginx has been my preferred web server over apache for many years and all I am trying to do is depend on the GUI to do what I need. Do not like maintaining one offs.

**Comment by fabianfrz** [comment]
It is an advanced option in HTTP Server **AND** the Location block. So you can configure it wherever you want.

**Comment by rrosson** [comment]
Ok. I see that it is in two places but the issue still stands that the value you enter does not write to any file in /usr/local/etc/nginx/ directory. All files and the directory are owned by root:wheel with the directory permissions being 755 and the files being 644.

Issue still stands.

**Comment by fabianfrz** [comment]
server {
listen  8080;
listen  [::]:8080;

client_header_buffer_size 1k;
large_client_header_buffers 4 8k;
charset utf-8;
access_log  /var/log/nginx/upload.test.access.log main;
access_log  /var/log/nginx/tls_handshake.log handshake;
error_log  /var/log/nginx/upload.test.error.log;
**client_max_body_size 123m;**
#include tls.conf;
    
location  /testupload {
BasicRule wl:19;
DeniedUrl "/waf_denied.html";
root /tmp/testupload;
**client_max_body_size 321m;**
autoindex off;
http2_push_preload off;
}

**Comment by fabianfrz** [comment]
I just generated that location and http server and both are written to the nginx.conf. So all is working as expected.

**Comment by rrosson** [comment]
Well my installation shows the values in the GUI but does not show it in the nginx.conf file.  My OPNsense installation is managed using Safari from my macOS system running fully patched Catalina

**Comment by fabianfrz** [comment]
-> Config Reload is the small button with the two arrows on it which spins if if press it.

**Comment by rrosson** [comment]
Ok, I am good. the reload button you speak of is at the bottom next to the plus sign and is orange on my screen. This is the one that finally wrote the configuration out to nginx.conf. all the others did not do this.  Thank you for the help and patience.
