### ISSUE TITLE
IDS/IPS etpro / snort rules fail to download

### ISSUE THREAD

**Issue by tworth04** [opnsense/plugins#1709]
not sure if i need to open a new ticket so close if we can reopen 1585.  I'm still seeing the IDS/IPS rules are failing to download.

OPNsense Ver:  20.1.1 release. I tried applying the 2 patches noted in the 1585 ticket just in case but no luck on that front.

please see logs:

Feb 20 20:21:53 OPNsense /rule-updater.py: download failed for /suricata-4.0/etpro.rules.tar.gz (http_code: 404)
Feb 20 20:21:54 OPNsense /rule-updater.py: version response for https://rules.emergingthreats.net/open/suricata-4.0/version.txt : 9409
Feb 20 20:21:55 OPNsense /rule-updater.py: download completed for https://rules.emergingthreats.net/open/suricata-4.0/emerging.rules.tar.gz

**Comment by AdSchellevis** [comment]
Applying patches which already are released might result in reverting the code. 

The exact requested url (including your subscription code) should be in the log (https://github.com/opnsense/core/blob/16eca2b9006b1f4a64001dbfb1a6d615caf9e83c/src/opnsense/scripts/suricata/lib/downloader.py#L156).

You can easily check if the url is correct using curl from the box itself.

**Comment by tworth04** [comment]
sorry i removed some of the URL just in case since it it had my license key.  But it's not just etpro...snort is failing as well...i even regenerated my snort code and tried that as well.

Feb 20 20:21:53 OPNsense /rule-updater.py: download failed for https://rules.emergingthreatspro.com/61c863fd5f907247f1e0fd3bbc776eeca31293f7152365544e7df9551778c7b5/suricata-4.0/etpro.rules.tar.gz (http_code: 404)

Feb 20 20:21:31 OPNsense /rule-updater.py: download failed for https://www.snort.org/rules/?oinkcode=2b343fd42b72992efeba7ddb7edf2d4b806a00da (http_code: 404)

**Comment by AdSchellevis** [comment]
Just to be sure, those numbers aren't real I hope. the ETPro looks like telemetry, which should be downloaded using the ETPro-telemetry plugin (as described in the documentation).

**Comment by tworth04** [comment]
yeah...i thought that's what you were asking for...
i can edit

**Comment by AdSchellevis** [comment]
https://docs.opnsense.org/manual/etpro_telemetry.html 

snort needs a filename if I'm not mistaken.

**Comment by tworth04** [comment]
yeah snort worked, so apologies there.  I removed the file when testing

**Comment by AdSchellevis** [comment]
Please read the manual if using ETPro telemetry, when acquiring the commercial version, please test the url separately first.

**Comment by tworth04** [comment]
i've tried the curl command as mentioned...result is the requested URL is not found...I tried adding the widgit from the docs and that is not an option

**Comment by AdSchellevis** [comment]
please, please, please, read the doc, it's all there.... You installed the **wrong** plugin https://docs.opnsense.org/manual/etpro_telemetry.html?highlight=os-etpro-telemetry#plugin 

Pro licenses without subscription can be bought here https://shop.opnsense.com/proofpoint-et-pro-ruleset.html

**Comment by tworth04** [comment]
i apologize.  With the ETPro edition installed, it removed the option for telemtry from plugins...even after removal i didn't see it until i updated rules which at first glance i didn't think it took because it returned a status of no updates available.  

But it is working.  I will close.  Thank you for the assist
