### ISSUE TITLE
[NGINX] Please add auth_request support in GUI

### ISSUE THREAD

**Issue by Ornias1993** [opnsense/plugins#1719]
Pretty simple request actually:
Create a way to add the NGINX auth_request feature to locations from the GUI.

Doesn't have to be anything special.
Even if it's just one field with an url thats checked for being http 200, that would open up a lot of options.

**Comment by fabianfrz** [comment]
I already built that feature into native OPNsense. It is an advanced setting and allows checking any authentication server in OPNsense. So you can use LDAP, RADIUS, internal or add a custom authenticator.

**Comment by Ornias1993** [comment]
@fabianfrz Would "Basic Authentication" in the GUI do this?
I don't understand the help text:
"Enter the realm for this directory and enable authentication."

What the fuck is a "realm" within NGINX? The manual of NGINX als doesn't understand the term "realm".

Is this just the basic auth_request header?

**Comment by Ornias1993** [comment]
Simply put:
I want a basic: 
Auth_request header that checks if an url is http 200 and blocks the request if it isn't.

Where is that setting?

That being said:
Where are all these "authentication" settings documented? I can only find local database auth and thats it... I see no option to use my radius server or something anywhere....

**Comment by Ornias1993** [comment]
Found the other settings, such as LDAP, RADIUS, VOUCHER, etc. :)
Thats still not just an auth_request header though...

I've a site (lets call it x.com), that needs to only be accessable if someone is logged in on another site (lets call it y.com). y.com does this by making sure it sends http 200 if the user is logged in and 401 thats not the case.

With an auth_request this is super duper easy:
auth_request https://y.com
proxy_pass https://x.com

(crude TL:DR version)

**Comment by fabianfrz** [comment]
If you would have an user already, you would not call an authentication request. It forwards the credentials to verify them using the specified auth server. So what you probably need is not a change in the nginx plugin itself but an auth server that does only check basic auth.

This is the authentication callback this feature does and may need slightly adjustments if you want to pass the host to an auth backend but it already has all the values:
https://github.com/opnsense/plugins/blob/master/www/nginx/src/opnsense/scripts/nginx/ngx_auth.php

**Comment by Ornias1993** [comment]
@fabianfrz 
I just need to be able to set "auth_request".
It sounds a bit like you don't know what "Auth_request" under NGINX means?

Example:
```
location /private/ {
    auth_request /auth-0;
    add_header X-Frame-Options "SAMEORIGIN";
    proxy_pass http://192.168.31.22:9091;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }
```

This is a basic NGINX proxy feature!
I don't need to write all sorts of auth servers (I already have that) I need this basic NGINX feature called "auth_request" supported...

**Comment by Ornias1993** [comment]
@fabianfrz 

> If you would have an user already, you would not call an authentication request. It forwards the credentials to verify them using the specified auth server

Could you PLEASE quote which question you are answering? I don't get if you either don't understand my auth_request question or the second question about "X-Forwarded-User"?

Anyhow:
I just need to be able to set "auth_request"!
(thats my main question and unrelated to the one about "X-Forwarded-User"(!)... )

Example:
```
location /private/ {
    **auth_request /auth-0;**
    add_header X-Frame-Options "SAMEORIGIN";
    proxy_pass http://192.168.31.22:9091;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }
```

This is a basic NGINX proxy feature!
I don't need another Auth server, I just need this basic NGINX feature called "auth_request" supported...

**Comment by Ornias1993** [comment]
I think we have a language problem.
So I made a mockup picture

I need this field:
<img width="668" alt="opnsense example" src="https://user-images.githubusercontent.com/7613738/75623507-e1dac400-5baa-11ea-97b8-22ceb1ad4517.PNG">

This should add:
`auth_request https://blabla.com/auth-0;`

To the location.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
