### ISSUE TITLE
Quagga: raw config

### ISSUE THREAD

**Issue by ra1nb0w** [opnsense/plugins#172]
Hello,
What do you think about a raw config section in which I can set the configuration of ospfd for example (ospfd.conf)? Unfortunately, I know it is not a good practice, I need to apply some filters. At the moment I wrote ospfd.conf directly but could be nice to do from gui and save configuration on the global configuration. Maybe, I can try to implement it.

thanks

**Comment by fabianfrz** [comment]
This is a really bad idea (does not play well with the template as well as it may break the configuration. What kind of filters are you using? If you are talking about route maps, @mimugmail wants to implement them (should be easy to copy from the BGP pages) but they should be tested before (you can use the developer preview `os-quagga-devel` where this feature is included.

**Comment by ra1nb0w** [comment]
sorry, you are right; I lost to put a sample config. Here it is
```
interface ovpns1                                                                            
  ip ospf network point-to-point                                             
  ip ospf authentication message-digest
  ip ospf message-digest-key 1 md5 P4ssw0rdV3r1L0n6
!                                   
router ospf                     
  ospf router-id 127.127.127.1                  
  log-adjacency-changes detail                                        
  redistribute connected
  redistribute static
  redistribute kernel
  network 172.16.150.0/24 area 0.0.0.0                         
  area 0.0.0.0 authentication message-digest
  distribute-list rfc-1918 out connected
  distribute-list rfc-1918 out static
  distribute-list rfc-1918 out kernel
!                                                                     
access-list rfc-1918 permit 172.16.200.0/21
access-list rfc-1918 deny any
```
and for what I learn I can't use route-maps directive, wrong?. Anyway, now I noticed that we need message-digest and not md5. About this point, seems that md5 directive is deprecated (I don't find it on documentation), do you know something more?

**Comment by fabianfrz** [comment]
@ra1nb0w route maps are currently not supported as we are having them in BGP for testing. in the current developer preview. If we don't get any bugs there we can add them to OSPF too.

**Comment by ra1nb0w** [comment]
I undestood, but I think is useless in my case. Anyway, I wait :)
thanks

**Comment by mimugmail** [comment]
Would a prefix-list also bei ok instead of a distribution list? This should
be very easy to implement.

Am 06.06.2017 2:20 nachm. schrieb "ra1nb0w" <notifications@github.com>:

**Comment by fabianfrz** [comment]
just FYI: #170 is the same / related

**Comment by ra1nb0w** [comment]
I tryed with prefix-list as below but in my configuration doesn't work, prefixes are not filtered out.
I am not an expert of quagga so I can't explain why.

```
router ospf
   area 0.0.0.0 filter-list prefix OUT out
!
ip prefix-list OUT seq 10 permit 172.24.248.0/24 le 32
ip prefix-list OUT seq 100 deny any
```

**Comment by mimugmail** [comment]
What happens when you dont redistribute anything and use the prefix-list?

Am 07.06.2017 9:32 vorm. schrieb "ra1nb0w" <notifications@github.com>:

**Comment by ra1nb0w** [comment]
if I remove `redistribute <*>` I don't send anything to other routers

**Comment by mimugmail** [comment]
https://serverfault.com/questions/469310/prevent-quagga-from-a-certain-subnet-advertising

Check the last answer, if this doesnt work for you I'll try to implement it
when #171 is fixed

Am 07.06.2017 1:51 nachm. schrieb "ra1nb0w" <notifications@github.com>:

**Comment by ra1nb0w** [comment]
sorry for the delay.
I tryed few times following tha links, the documentation and others tutorial; probably I don't understand something related to LSA and stub zone. I will try next days and I come back.

Thanks to everybody for the patience :)

**Comment by mimugmail** [comment]
Any updates on this @ra1nb0w ?

**Comment by ra1nb0w** [comment]
Unfortunately, not yet. I need to conclude the ceph cluster and then I come back to ospf/opnsense. Anyway, I probably did some bad practice configuration.
Thanks for the help and the interest.

**Comment by fabianfrz** [comment]
@mimugmail @ra1nb0w  should this be closed?

**Comment by mimugmail** [comment]
@fabianfrz I would close it, @ra1nb0w should try the new code from master with the prefix-list and recheck the design. If it still doesn't work just open a new issue with FR to distribution list and I'll look at it.

**Comment by fabianfrz** [comment]
@mimugmail then I'll close it. Thanks for your help.
