### ISSUE TITLE
Add firewall plugin (for API support) [tracking ticket]

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/plugins#1720]
In preparation of one of our long time goals to replace the OPNsense firewall component with an api enabled one using our mvc framework, we're going to start with a minimal viable product to allow the administration of (basic) firewall rules using the API.

The scope of this project is not to replace the current firewall (yet), but to be able to allow machine to machine communication to our firewall software when using this plugin.

At minimum it will be possible to administer (additional) rules with the following properties:

- Action to take (pass, block, reject)
- Interface (one of the registered interfaces, such as wan)
- Direction (in or out)
- TCP/IP Version (ipv4 or ipv6)
- Source (a single host or network [cidr] or a registered alias) +  Invert option
- Destination (same options as source) +  Invert option
- Description (user friendly description)
- Gateway (one of the registered gateways as found in System->Gateways->Single)
- Quick (boolean to mark if rule should apply immediate)
- Protocol (Single registered protocol, such as tcp, udp, icmp)

Existing (manual) rules can't be changed with this plugin, since they live in another section of the configuration (separation of concerns).

Rules created with this plugin will be visible under the "Automatically generated rules" section of the affected interface.  To ease testing and support, a small, very simple, user interface will be added to the package.

**Comment by mimugmail** [comment]
Really nice! :) Happy to help/test
