### ISSUE TITLE
dyndns support dnspod.cn api

### ISSUE THREAD

**Issue by muyuballs** [opnsense/plugins#1724]
may dyndns support dnspod.cn api ?

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
