### ISSUE TITLE
security/acme-client: add support for dnsapi "schlundtech"

### ISSUE THREAD

**Issue by TravisWilder** [opnsense/plugins#1728]
Hello

the acme client supports schlundtec
https://github.com/acmesh-official/acme.sh/wiki/dnsapi#76-use-schlundtech
can we also get this to be a valid validation in the Validation Methods of OpnSense

Thanks

**Comment by fraenki** [comment]
This will be available in the upcoming os-acme-client release 1.31.
You can apply the changes locally to test them:

```
opnsense-patch -c plugins edf3633b
```

**Comment by TravisWilder** [comment]
Thanks. Tested and is working fine!
