### ISSUE TITLE
net/zerotier: Add option from unmanaged routes

### ISSUE THREAD

**Issue by ruworuro** [opnsense/plugins#1729]
To avoid having problems with the paths set by zerotier it would be convenient to have an option to set the allowManaged option to false.

This option is independent for each zerotier network, and allows the client to establish a clean connection without IP and routes.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
