### ISSUE TITLE
net/zerotier: Firewall rule(s) missing

### ISSUE THREAD

**Issue by vnxme** [opnsense/plugins#1730]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the [contributing guide lines](https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md).
[X] I have searched the existing issues and I'm convinced that mine is new.
[X] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
* When using Zerotier in OPNsense, the daemon listens to more than one TCP/UDP port. Below is an example *sockstat* output.
```
root@opnsense:~ # sockstat | grep zerotier
root     zerotier-o 7776  6  tcp4   127.0.0.1:9993          *:*
root     zerotier-o 7776  7  tcp6   ::1:9993                *:*
root     zerotier-o 7776  11 udp4   <PUBLIC_IPV4>:13425     *:*
root     zerotier-o 7776  12 tcp4   <PUBLIC_IPV4>:43453     *:*
root     zerotier-o 7776  13 udp6   <PUBLIC_IPV6>:39326     *:*
root     zerotier-o 7776  14 tcp6   <PUBLIC_IPV6>:20441     *:*
```

* Options `secondaryPort` and `tertiaryPort` seem to have no effect at all - the daemon keeps binding to random ports. Below is an example *local.conf* ([syntax manual](https://github.com/zerotier/ZeroTierOne/blob/master/service/README.md)).

```json
{
    "settings": {
        "allowSecondaryPort": true, 
        "portMappingEnabled": true,
        "bind": ["<PUBLIC_IPV4>", "<PUBLIC_IPV6>"],
        "primaryPort": 9993,
        "secondaryPort": 9994,
        "tertiaryPort": 9995,
        "multipathMode": 2
    }
}
```

* Since port numbers are virtually random (13425, 43453, 39326, 20441), there is currently no way to allow peer-to-peer communication for Zerotier. A firewall rule for UDP/9993 makes no difference.

```
root@opnsense:~ # cat /tmp/rules.debug | grep 9993
pass in quick on WANs inet proto udp from {any} to {(self)} port 9993 keep state label "..."
pass in quick on WANs inet6 proto udp from {any} to {(self)} port 9993 keep state label "..."
```

* As a result, firewall log is populated with *default deny rule* items corresponding to Zerotier packets from other peers blocked by OPNsense.

**Describe the solution you'd like**
There should be a clear way to make OPNsense create dynamic firewall rules for Zerotier ports. A special script could possibly be enough to obtain new port numbers (e.g. from *sockstat*) after launching the daemon and change a special port alias item in firewall.

**Describe alternatives you've considered**
Another option is to make Zerotier daemon bind to non-random ports. It seems to exist but does not work for an unknown reason.

**Additional context**
opnsense 20.1.1
os-zerotier 1.3.2_2
zerotier 1.4.6

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
