### ISSUE TITLE
Acme/Can't get DNS challenge validated: Where is the Renew button?

### ISSUE THREAD

**Issue by xabix** [opnsense/plugins#1740]
**Important notices**
Hello,

I am quite desperate as I can’t seem to be able to validate my CA with DNS-01 (nsupdate). when I create the certificate I don’t see the TXT key to be configured in my DNS therefore anytime I try to issue the CA a new TXT is trying to be verified and never matches the only ongoing.

At what moment should I be aware of the TXT key so I can set it before it gets verified.

> [Sat Mar 14 21:41:44 CET 2020] txtdomain='_acme-challenge.xdealmeida.com'
> [Sat Mar 14 21:41:44 CET 2020] txt='BPvSHaT2NKDerBylv7DI1Rz8qY48uuuO_FQfZuYOpyM'
> [Sat Mar 14 21:41:44 CET 2020] d_api='/usr/local/share/examples/acme.sh/dnsapi/dns_nsupdate.sh'
> [Sat Mar 14 21:41:44 CET 2020] Found domain api file: /usr/local/share/examples/acme.sh/dnsapi/dns_nsupdate.sh
> [Sat Mar 14 21:41:44 CET 2020] Adding txt value: BPvSHaT2NKDerBylv7DI1Rz8qY48uuuO_FQfZuYOpyM for domain:  _acme-challenge.xdealmeida.com
> [Sat Mar 14 21:41:44 CET 2020] adding _acme-challenge.xdealmeida.com. 60 in txt "BPvSHaT2NKDerBylv7DI1Rz8qY48uuuO_FQfZuYOpyM"
> [Sat Mar 14 21:41:44 CET 2020] error updating domain

when I am creating the certificate I would have assume that I should get the TXT value to be configured before pressing the "Issue/Renew" button.
![image](https://user-images.githubusercontent.com/394407/76690423-08cfd600-6640-11ea-9ac8-650fdb9dfa4a.png)

I don’t seem to find the Renew option like well described in https://www.reddit.com/r/PFSENSE/comments/5v6b0a/how_to_acme_lets_encrypt_dns_manual/

Plugin: os-acme-client (installed) 1.29 (acme.sh v2.8.5)

 dig -t TXT _acme-challenge.xdealmeida.com
```
; <<>> DiG 9.11.3-1ubuntu1.11-Ubuntu <<>> -t TXT _acme-challenge.xdealmeida.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 58533
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;_acme-challenge.xdealmeida.com.        IN      TXT

;; ANSWER SECTION:
_acme-challenge.xdealmeida.com. 3600 IN TXT     "BPvSHaT2NKDerBylv7DI1Rz8qY48uuuO_FQfZuYOpyM
```

MERCI
XabiX

![image](https://user-images.githubusercontent.com/394407/76690440-2a30c200-6640-11ea-92aa-52103374835c.png)

**Comment by fraenki** [comment]
> I can’t seem to be able to validate my CA with DNS-01 (nsupdate)

The screenshot shows that you haven't configured the required nsupdate options. Do you know how nsupdate works?

If you want to validate the domain that is visible on the screenshots, you should probably choose CloudFlare for DNS-01 validation and enter the required credentials. (CloudFlare provides DNS for this domain.)

> I don’t seem to find the Renew option like well described in https://www.reddit.com/r/PFSENSE/comments/5v6b0a/how_to_acme_lets_encrypt_dns_manual/

The linked guide is for pfSense, so it does not apply at all.

**Comment by xabix** [comment]
Unfortunately the documentation on the web is not that available at least when I was looking within an Opnsense case.
Got it working with CloudFlare API approach. thanks

**Comment by fraenki** [comment]
Glad you got it working.
