### ISSUE TITLE
Dynamic DNS -- Add support for Gandi LiveDNS API

### ISSUE THREAD

**Issue by jkhii** [opnsense/plugins#1743]
I would like the Dynamic DNS feature to support Gandi's LiveDNS.
The documentation can be found here: https://api.gandi.net/docs/reference/
The Let's Encrypt Plugin already supports this so may have some code that could be reused.

I can provide an API Key for testing if needed.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.

**Comment by vizion8-dan** [comment]
It is actually merged. :-)

**Comment by winny-** [comment]
confirmed ddclient works as intended with gandi now - See this comment for a brief how-to https://github.com/opnsense/plugins/issues/3143#issuecomment-1411282802
