### ISSUE TITLE
security/acme-client: renewal causes haproxy failure

### ISSUE THREAD

**Issue by andrewheberle** [opnsense/plugins#1745]
We have had an ongoing problem whereby renewals, or adding a new certificate causes haproxy to no longer respond to requests.

The renewal or issue process via the acme-client works fine and the haproxy service is still running, however I need to actually stop then start the haproxy service to resolve the outage.

Opnsense Version: 19.7.9 (although this problem existed for us prior to this release)

Lets Encrypt Config:

* Auto Renewal = Enabled
* Lets Encrypt Environment = Production
* HAProxy Integration = Enabled

Validation Methods:

* Challenge Type = HTTP-01
* HTTP Service = HAProxy HTTP Frontend Integration
* HAProxy:
  * Enable Auto-Configuration = Enabled
  * HAProxy Frontends: Our HAProxy frontend that listens on HTTP (80/tcp)

Automations:

A single automation is defined to restart HAProxy

Certificates:

We have four different certificates, two are multi-domain (SAN) certs while then others are single-domain certificates.

All are set to use HTTP-01 validation and with the defined HAProxy restart automation selected.

HAProxy Configuration:

We have two HAProxy frontends (public services) configured.

One listens on port 80 for plain HTTP which is the front-end selected for the Lets Encrypt HTTP-01 validation method.  In addition to the automatically added acme redirect rule, this frontend has some select rules in place to redirect some internal services from HTTP -> HTTPS.

The other frontend is our HTTPS listener which has the four certificates included and various rules to direct connections to internal systems.

**Comment by TravisWilder** [comment]
Hello

I have the same issue. When Let's Encrypt renews in the night the cert the automation i have is "restart Ha proxy"

I can see in the log that the automation is triggered and then the HA proxy goes down.

config[13504]: /usr/local/opnsense/scripts/OPNsense/AcmeClient/certhelper.php: AcmeClient: running automation: Reload HA

In the HAProxy Log File I can see, that the Pool / Service / Backend where stopped.

When I just go to the HA Settings and click "Apply" it will start the services again and all is working normal

Version : 
OPNsense 20.1.3-amd64
os-acme-client (installed) | 1.29_1
os-haproxy (installed) | 2.20

**Comment by fraenki** [comment]
I was able to reproduce this issue.

First, some details about this behaviour: HAProxy provides a feature called "graceful" stop/restart. In this mode HAProxy does not abort connections upon stop/restart, but instead will wait for all open connections to either end or to expire. This is useful to avoid dropping client connections mid-transfer, but it also can take a really long time for the shutdown to succeed, depending on the configured timeout values. This feature can be enabled or disabled in HAProxy's "service settings" in OPNsense.

However, there is a limitation in the (upstream) RC script that is used to control the HAProxy service: it **always** uses the "graceful" feature when using the "restart" command. Even if the "graceful" feature was disabled in the OPNsense GUI, it would still be used for the "restart" command.

A workaround was added, you can apply it by using the following command:

```
opnsense-patch -c plugins c013a659
```

Please let me know if this fixes the issue for you.
This workaround will also be available in the upcoming version 2.21 of os-haproxy.
