### ISSUE TITLE
Extend firewall plugin (for API support) with snat support [tracking ticket]

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/plugins#1749]
In https://github.com/opnsense/plugins/issues/1720 we worked on API support for the basic firewall features, this ticket describes the extension with source (outbound) nat rules. 

**Scope:**

_This feature addition is not about: port forwards and 1:1 rules, these are destination type nat rules, which therefor lie outside the scope of this ticket._

At minimum this plugin should provide the possibility to use standard API endpoints, similar to the ones for all other new style features.

The rules settings provided should be the following:

- Disabled (ignore rule)
- Interface (one of the registered interfaces, such as wan)
- TCP/IP Version (ipv4 or ipv6)
- Protocol (Single registered protocol, such as tcp, udp, icmp)
- Source (a single host or network [cidr] or a registered alias)  + Invert option
- Destination (same options as source) + Invert option
- Translation target (Either an address or registered alias)
- Description (user friendly description)
- Log (enable logging)

Existing (manual) rules can't be changed with this plugin, since they live in another section of the configuration (separation of concerns). 

The rules created by the api don't depend on mode settings of the outbound nat rules, such as  "**Manual outbound NAT rule generation**" or "**Hybrid outbound NAT rule generation**". 
Since automatic rules are not visible elsewhere in the gui, it's imperative that this plugin has a simple user interface to retain visibility.

**Comment by AdSchellevis** [comment]
(internal reference) this point should be in 20.1.4-devel

**Comment by wrobelda** [comment]
Thanks for a quick response. I need a programmatic access to a DNAT rule, but luckily the "Alias" workaround laid out in the thread I linked should be sufficient.

**Comment by AdSchellevis** [comment]
you could also consider the relayd plugin (https://docs.opnsense.org/manual/relayd.html) when it comes to forwarding
