### ISSUE TITLE
haproxy check interval not from UI setting

### ISSUE THREAD

**Issue by mariusrugan** [opnsense/plugins#175]
Hi,
using haproxy UI configurator in OPNsense 17.1.8-amd64, health check interval is wrongly set at 2s instead of the value.
	
![#1](https://user-images.githubusercontent.com/143987/26877811-6b3124fc-4b8b-11e7-9199-864146e551a0.png)

results no matter the value in:

![#2](https://user-images.githubusercontent.com/143987/26877820-7828a018-4b8b-11e7-84b4-b586acedc34f.png)

edit,
seems there is a mismatch in between 
![#3](https://user-images.githubusercontent.com/143987/26877942-f1019f9e-4b8b-11e7-9980-b8dcac96fc27.png)

and

![#3](https://user-images.githubusercontent.com/143987/26877960-fc2be276-4b8b-11e7-841c-944e513c1f27.png)

**Comment by mariusrugan** [comment]
thanks @fraenki
a little bit of a side-step, until fixed, i'm trying to understand if a /conf/haproxy.conf file would be picked up instead of the autogenerated one ?

**Comment by fraenki** [comment]
@mariusrugan I can't reproduce this issue. Using "10s" or "10000" for "Check interval" works like a charm on 17.1.8 with os-haproxy 1.15.

**Comment by fraenki** [comment]
Looks like you're running an old version of the os-haproxy plugin? The validation method in the current release differs from your screenshot:

![screenshot at 2017-06-07 15-55-39](https://user-images.githubusercontent.com/909706/26882162-dc63dcd8-4b99-11e7-9f73-dccf53cc468e.png)

Are you by chance running an old development build of os-haproxy?

**Comment by mariusrugan** [comment]
you're right about the mismatch, it seems i have a broken installation :/

i have, in the interface

![#1](https://user-images.githubusercontent.com/143987/26882785-a83d2a70-4b9b-11e7-89b0-395f607c2712.png)

![#2](https://user-images.githubusercontent.com/143987/26882809-b9e9758a-4b9b-11e7-99f9-77ecfa63666d.png)

I've just rebooted the machine, didn't do it on the spot on upgrade.

**Comment by mariusrugan** [comment]
i've tried, no luck,

it seems the dir has been changed (mtime changed) but  sha256-ing haproxy.conf template is different from 

`https://github.com/opnsense/plugins/blob/17.1.8/net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf`

![#1](https://user-images.githubusercontent.com/143987/26885088-de51d9ca-4ba1-11e7-8839-af1881eeadaf.png)


![#2](https://user-images.githubusercontent.com/143987/26885079-d6085ffa-4ba1-11e7-9185-53349126efbf.png)

i'll try to manually clean-up everything and come back

**Comment by mariusrugan** [comment]
@fraenki i've cleaned up as much as i could, and i did a CLI install:

![#1](https://user-images.githubusercontent.com/143987/26887800-5129607e-4ba9-11e7-9b98-832d87ceca0d.png)

looking at the validation xml everything looks fine, the message you are seeing is there;

![#2](https://user-images.githubusercontent.com/143987/26887830-6ab91098-4ba9-11e7-854a-bf3c446f7037.png)

however not in the interface:

![#3](https://user-images.githubusercontent.com/143987/26887986-fea19500-4ba9-11e7-9ee8-d79e2449d834.png)

i've cleaned up even the Volt cache, /usr/local/opnsense/mvc/app/cache

i know it's a bit of a side-step from the original issue, but do you have any suggestion what could be wrong?

**Comment by fraenki** [comment]
@fichtner PING! Any idea? This is really odd.

**Comment by fichtner** [comment]
https://github.com/opnsense/plugins/blob/master/net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.xml#L661-L667

I don't see anything odd in this other than it's not what you guys expect even though it's there. Maybe the form field is not mapped correctly?

**Comment by mariusrugan** [comment]
@fichtner, long story short,@fraenki is seeing it and i don't, with both of us having haproxy and os-haproxy reported as up-2-date. i have repeatedly restarted the machine;  
my validation file is the same as what you've pasted above (i've compared with the tag https://github.com/opnsense/plugins/tree/17.1.8) but i still don't get the validation message.
am wondering, in this case, what am i missing from other UI "parts" that might have been updated and i'm not seeing the latest version.

as i have dug into, this message is coming in from an XHR API request.
 
- is there any php cache to be cleaned at API level ? 
- now that i'm down the rabbit hole, can i reinstall just the UI only package ? i'm a noob into opnsense but feel pretty comfortable hacking into a webapp, so i'd appreciate some guidance for start.

**Comment by fichtner** [comment]
# opnense-revert os-haproxy
    # opnsense-revert opnsense

The latter will also remove all cached files.

Try a different browser on your end, a different machine. Make sure you don't have a caching proxy active somewhere that could interfere.

**Comment by mariusrugan** [comment]
thanks, 
i did it, reverted, no luck.
already did try different browsers, different machines. no caching proxy in my network.
same results.

![#1](https://user-images.githubusercontent.com/143987/26929947-eaeccd2e-4c5b-11e7-9e20-5c5bdbc6f2b9.png)

**Comment by fichtner** [comment]
Everything looks ok... you want to set the health check, it wants a number because it's an integer field... let's start from the top: what are you trying to do? why do you not input a number?

**Comment by fichtner** [comment]
note there is a similar setting in the server tab, which @fraenki showed you... it is a different value, it accepts text ;)

**Comment by mariusrugan** [comment]
Nop, the healthcheck.interval validation message in https://github.com/opnsense/plugins/blob/master/net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.xml#L612-L617 is

`Should be a number between 1 and 8 characters, optionally followed by either "d", "h", "m", "s", "ms" or "us".`

i'm getting another message:
 
i've quickly browsed this: 
https://github.com/opnsense/plugins/commit/7da6fb7fe0ed10f97473d8da52cf56e68d936292#diff-f15f50e2971b09d30c1d8feb857301f2

**Comment by fichtner** [comment]
Nope, it's this one, see the parent XML tags... https://github.com/opnsense/plugins/blob/master/net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.xml#L661-L667

You are looking in the servers section.

**Comment by mariusrugan** [comment]
problem is, the validation somehow spits out in the config "2s" as in my screenshot, because i think doesn't match regex.

**Comment by mariusrugan** [comment]
ok,
you're right @fichtner. the server tab takes precedence over the healthcheck tab. 

healthcheck config that is not included anywhere ?
![#1](https://user-images.githubusercontent.com/143987/26930989-55115e6a-4c5f-11e7-8d14-660611a3f8dc.png)

server config that is included:
![#2](https://user-images.githubusercontent.com/143987/26931062-92d4ba12-4c5f-11e7-8c4e-da63daf1f7e3.png)

result:
![#3](https://user-images.githubusercontent.com/143987/26931098-ad18d41c-4c5f-11e7-93c1-7953e73df11a.png)

so, @fraenki it's still a bug :)

**Comment by fichtner** [comment]
true, the interval for the health check is never written / used

**Comment by fraenki** [comment]
Thanks guys for the clarification. I'll prepare a fix.

**Comment by fraenki** [comment]
My patch in #177 changes the default behaviour, so I thought some explanation would be nice.

First of all: I always wanted the server tab to take precedence over the healthcheck tab. To get this working I had to apply the following code changes:
- server settings:
  - make "check interval" optional
  - remove default value for "check interval"
  - it's now possible to have an empty value for "check interval"
- healthcheck settings:
  - make "check interval" mandatory
  - add default value for "check interval"
  - it's no longer possible to have an empty value for "check interval"

For existing configurations this means that nothing changes. ;-) One has to remove "check interval" in server settings, otherwise the healthcheck setting is not used.

All _new_ configurations will not have a default value for "check interval" in server settings and will use the value from the healthcheck setting instead.

**Comment by fraenki** [comment]
@mariusrugan Thanks again for reporting, this finally fixes a long-standing bug. :+1:

**Comment by mariusrugan** [comment]
@fraenki no problem, thanks for taking the time to herd these things around :)
i have some feedback after i've put up with the UI, what would you prefer ? issues with [improvement] prefix ?

**Comment by fraenki** [comment]
@mariusrugan I'm fine with [improvement], more common (in other projects) is [rfe] (request for enhancement).

**Comment by fraenki** [comment]
@mariusrugan btw. you can test the bugfix by running the following command:

`opnsense-patch -c plugins 42128fb`

**Comment by mariusrugan** [comment]
👍  
it renders the config fine @fraenki, thanks.
