### ISSUE TITLE
net/freeradius: add mikrotik group support

### ISSUE THREAD

**Issue by mimugmail** [opnsense/plugins#1751]
https://forum.opnsense.org/index.php?topic=16226.0

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
