### ISSUE TITLE
os-openconnect - no place to enter second password

### ISSUE THREAD

**Issue by darkain** [opnsense/plugins#1752]
The Cisco AnyConnect client has a "second password" field used for 2FA codes and commands. For example, you can enter in "push" into this second field to have DUO Authenticator activate a prompt on your mobile phone to validate that it was actually you trying to login with your account.

I would like to have this second password field available in the OpenConnect web UI. From what I've read elsewhere online, OpenConnect itself supports this feature, so in theory it should be easy to add to the web UI.

![image](https://user-images.githubusercontent.com/2524251/77803564-ab258b80-703a-11ea-9c67-7726263e5217.png)

![image](https://user-images.githubusercontent.com/2524251/77803248-e83d4e00-7039-11ea-9daa-e878e663fac0.png)

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
