### ISSUE TITLE
DynamicDNS: Warning: Invalid argument supplied for foreach() on line 775

### ISSUE THREAD

**Issue by dlcasto** [opnsense/plugins#1754]
**Description:** 
The PHP error "Warning: Invalid argument supplied for foreach()" is thrown on line 775 of phpDynDNS.inc file. I eventually discovered that the issue was caused by using invalid credentials for Cloudflare (my password manager filled in the username/password with the OPNsense credentials instead of using what I had typed into the username/password boxes). Once I entered the proper credentials, I never received the error again. Perhaps there should be some sort of validation checking to prevent the error from occurring. More useful would be to display to the user on the web GUI that invalid credentials were used (if it is easy to determine) or that the DNS update failed.

**To Reproduce:**
1. Create a valid DynamicDNS entry for Cloudflare
2. Enter a valid Cloudflare hosted domain (I don't know if this error occurs if the domain is not hosted on Cloudflare since I have not tested that scenario)
3. Enter an invalid username/password
4. Once the an update has occurred, you should see an error report on the Dashboard page

**Expected behavior:**
Expected to be notified of invalid credentials or at least an "Unable to update DNS entry" type of message, which would alert the user that there is some sort of problem

**Environment:**
OPNsense 20.1.3 (amd64, OpenSSL)
DynamicDNS 1.20

**Comment by Finwood** [comment]
> Once I entered the proper credentials, I never received the error again.

I get the same error message, even though my credentials are correct.

I have two Cloudflare DDNS entries, one for IPv4 and one for IPv6, both for the same domain name using the same credentials. Using the _Save and Force Update_ button, both IPv4 and IPv6 are working properly. During automatic update, though, only the first entry in the list (IPv4) succeeds, while the IPv6 address remains unchanged on Cloudflare's DNS servers.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
