### ISSUE TITLE
telegraf plugin, add support for inputs.http_listener_v2 and aggregator

### ISSUE THREAD

**Issue by frankenbubble** [opnsense/plugins#1757]
I'd like to be able to add this to telegraf.conf via the UI (works by manually editing)

```
 [[inputs.http_listener_v2]]
    service_address = ":8089"
    methods = ["GET"]
    data_source = "query"
```

This allows me to send metrics to graphite (remote) via telegraf in opnsense, by making http gets to opnsense on port 8089.  I use this to collect metrics for my solar panel and electricity meter

and 

```
[[aggregators.basicstats]]
   period = "1s"
   stats = ["count", "min", "max", "mean", "stdev", "s2", "sum"]
```

for the same use cases, for me , it counts and sums how many kwh pulse are sent for my electricity meter.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
