### ISSUE TITLE
collectd plugin, add support for chains, regex and aggregation

### ISSUE THREAD

**Issue by frankenbubble** [opnsense/plugins#1758]
Please add support to generate this configuration.

```
LoadPlugin match_regex
LoadPlugin aggregation

<Plugin "aggregation">
  <Aggregation>
    Plugin "cpu"
    Type "cpu"
    GroupBy "Host"
    GroupBy "TypeInstance"
    CalculateAverage true
  </Aggregation>
</Plugin>

PostCacheChain "PostCache"
<Chain "PostCache">
  <Rule "rule1">
    <Match "regex">
      Plugin "^cpu$"
      PluginInstance "^[0-9]+$"
    </Match>
    <Target "write">
      Plugin "aggregation"
    </Target>
    Target stop
  </Rule>
  Target "write"
</Chain>
```

and to add this to the write graphite output 

`SeparateInstances true`

The first aggregates cpu stats, this is how we monitor our cpus in our fleet already, so fits our dashboard.
second  (SeparateInstances true) is to use namespaces better, interfaces would be interface-re0 without it, but interface.re0 with it, which allows for better dashboarding in grafana

**Comment by pmhausen** [comment]
I would also love to see these improvements. FreeNAS already does the aggregation for the CPU plugin and the "SeparateInstances true" and it is really useful for graphing ... Currently I cannot add my OPNsense to my Grafana dashboard because of the missing "SeparateInstances true". Please add this option.

**Comment by mimugmail** [comment]
Ok, I dont want to make it too complex. So just one checkbox calles "Aggregate CPU" which does this all?

**Comment by pmhausen** [comment]
These are two entirely different features but ...

- I think you can include the config snippet unconditionally. It simply shovels more and differently aggregated data to the graphite target. It does not change anything about the way all the other metrics are sent.
- The "SeparateInstances true" should be made a simple checkbox. I'll attach the FreeNAS config panel as an example. And here's the FreeNAS help text in the plain to reduce your work a bit:

> Enabling sends the plugin instance and type instance to Graphite as separate path components: host.cpu.0.cpu.idle.
> Disabling sends the plugin and plugin instance as one path component and type and type instance as another component: host.cpu-0.cpu-idle.

<img width="975" alt="Bildschirmfoto 2020-07-12 um 12 25 18" src="https://user-images.githubusercontent.com/27051716/87244000-08531a80-c43b-11ea-911a-fa5e89321528.png">

Thanks!
Patrick

**Comment by pmhausen** [comment]
Hey, @mimugmail 

are you ok with my feedback? Can I help? This does not look very complicated and I should be able to implement it with the proven "programming by copy&paste" method. I already had a close look at the XML for the UI - trivial.

So how do I go about this pull request thing? Do I have to clone the repo to my account, then make modifications? I come from a strong FreeBSD background so I am used to sending diffs ;-)

Kind regards,
Patrick

**Comment by mimugmail** [comment]
@pmhausen Sorry, forgot about this one. Yes, for me everything is clear. 
Also if you want to try it on your own I'm glad to help. 
Some time ago I wrote couple of guides how to build or extend plugins, most of it should still be valid:

https://www.routerperformance.net/opnsense/plugin-development/

This commit should also be self explanatory (hopefully):
https://github.com/opnsense/plugins/commit/3e203bd5c2f98533d1451d285f6e6da86898d55c#diff-b57ba26bfc426fd13b7dfc249098ec24

**Comment by pmhausen** [comment]
No problem, I see you have a release to prepare.
Nonetheless it would be great if we got the updated plugin with the 20.7 release.

Thanks for all your work!
Patrick

**Comment by pmhausen** [comment]
Hey, it's just XML and jinja - easy peasy.
Separate instances done, aggregate values in progress, pull request pending ...

**Comment by pmhausen** [comment]
@frankenbubble Could you explain what the PostCacheChain *does*?

i implemented the aggregate values and the separate instances because I am familiar with them and use them extensively.
I wasn't sure about that regex and chain thing, though.

Kind regards,
Patrick

**Comment by frankenbubble** [comment]
Hi !. The chains and regex stop the recording of individual per cpu stats, so you ONLY record the aggregates.  see https://collectd.org/wiki/index.php/Plugin:Aggregation/Config example if you need more detail.

**Comment by pmhausen** [comment]
Ah ... but I for one would want aggregates and individual stats. Can you live with that? The aggregates and the separate instances are finished.

**Comment by frankenbubble** [comment]
I can live with that :)

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
