### ISSUE TITLE
os-vnstat package does not pick up vnstat_enable="YES" in /etc/rc.conf

### ISSUE THREAD

**Issue by pjardetzky** [opnsense/plugins#1763]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[yes] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[yes] I have searched the existing issues and I'm convinced that mine is new.

[yes] The title contains the plugin to which this issue belongs

**Describe the bug**
/usr/local/etc/rc.d/vnstat rcvar does not see the variable 

**To Reproduce**
1. Install os-vnstat
2. add vnstat_enable="YES" to /etc/rc.conf
3. run /usr/local/etc/rc.d/vnstat rcvar 

**Expected behavior**
You should see vnstat_enable="YES"

THE FIX:
change line 17 to read:
     load_rc_config $rcvar
instead of:
     load_rc_config $name

**Environment**
OPNsense 20.1.3-amd64
FreeBSD 11.2-RELEASE-p17-HBSD
LibreSSL 3.0.2

Platform
Manufacturer | PC Engines
Product Name | APU
Version | 1.0
Vendor | coreboot
Version | SageBios_PCEngines_APU-45
Release Date | 04/05/2014

**Comment by fichtner** [comment]
Not sure what the bug is, os-vnstat doesn’t read rcvar, it sets it so you don’t have to when you enable it from the GUI. And it does not use rc.conf to do it.

**Comment by fichtner** [comment]
rc.d/vnstat is part of FreeBSD package so it can’t be changed from the plugin anyway.

**Comment by pjardetzky** [comment]
Thanks. I was using the command line and will switch to the GUI. I will close the bug since I was probably not using the package correctly.
