### ISSUE TITLE
net/haproxy: Log File doesn't work (missing diag_logs_template.inc)

### ISSUE THREAD

**Issue by githubcek** [opnsense/plugins#1764]
**Describe the bug**
HAProxy plugin:
when I click on "Log File" I got:

Warning: require_once(diag_logs_template.inc): failed to open stream: No such file or directory in /usr/local/www/diag_logs_haproxy.php on line 6 Fatal error: require_once(): Failed opening required 'diag_logs_template.inc' (include_path='/usr/local/etc/inc:/usr/local/www:/usr/local/opnsense/mvc:/usr/local/opnsense/contrib:/usr/local/share/pear:/usr/local/share') in /usr/local/www/diag_logs_haproxy.php on line 6

**Additional context**
https://forum.opnsense.org/index.php?topic=16611.0

**Environment**
Opnsense 2.1.3

In 20.1.2 release is line: system: drop unused services.inc and diag_logs_template.inc

**Comment by fichtner** [comment]
This was fixed in os-haproxy 2.20 for 20.1 as far as I know, current is 2.21. The info was not included in your report? Also things like os-cache can interfere.

**Comment by fraenki** [comment]
Works for me on 20.1.3 with os-haproxy 2.20.

**Comment by githubcek** [comment]
Strange. I have same version 20.1.3 and haproxy 2.20.
Maybe one of upgrades didn't go as planed. I will wait for next upgrade.

I have fixed my problem with old diag_logs_template.inc and I had to comment line: 
_require_once("services.inc"); otherwise if I added also this file I got error function (don't remember name) already declared or something like this._

**Comment by githubcek** [comment]
I have just upgraded to 20.1.4 (available today) and now HAporoxy Logs are working :)
HAproxy is now 2.21.

**Comment by fraenki** [comment]
@githubcek Thanks for reporting back.
