### ISSUE TITLE
net/freeradius: Add Radius-Proxy

### ISSUE THREAD

**Issue by AndyX90** [opnsense/plugins#1767]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

[x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
I try to set up WiFi networks for Windows- and Mobileclients on a remote site (s2s-vpn) with Freeradius as local RADIUS-Server.
The users are stored in Microsoft ActiveDirectory on main site.
I have tried to use ldap as authentication-backend in freeradius and it works if the password is a cleartext password. But practically the clients will not send cleartext passwords (PEAP/MSCHAPv2).
In this scenario you will get something like this:
    mschap: ERROR: FAILED: No NT/LM-Password.  Cannot perform authentication
Afaik it is only possible to do MSCHAPv2 against AD if the radius-server(firewall) is a domainmember and does ntlm_auth. 
    
**Describe the solution you'd like**
For me it would be enough to have the possibility to configure freeradius as radius-proxy for proxying radius-requests to Microsoft-NPS.

**Describe alternatives you've considered**
Alternative would be to not proxy and use SMB. (https://wiki.freeradius.org/guide/FreeRADIUS-Active-Directory-Integration-HOWTO).
I know about the pros and cons of using SAMBA on a firewall, but that would give other plugins the possibility to use it as well..

**Additional context**
-

**Comment by mimugmail** [comment]
Why don't you just use the IP of your AD Radius within your APs? 
Do you already have experience with radius proxy?

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
