### ISSUE TITLE
net/frr:  switch development version to ffr7?

### ISSUE THREAD

**Issue by fichtner** [opnsense/plugins#1768]
frr7 has been in packages for a while and FRR 7 has had a number of releases so it may be time to move forward :)

**Comment by TekunoKage** [comment]
First, Thanks for the attention and a great improvement on OpnSense with this plugins. Even so respectfully I take my chance to mention that this request is not just a feature request. There are a lot of bug fix from 6.0.2 to 7.x (7.3.1) is the current latest stable. Please Review if is possible to upgrade and how fast that could be.

**Comment by fichtner** [comment]
@mimugmail even if you can't test can we switch dev version to ffr7 in the meantime so others can test?

**Comment by mimugmail** [comment]
Sure :)

**Comment by TekunoKage** [comment]
Hi @mimugmail today I install a OpnSense 20.7 Beta and install the FRR-dev plugin (os-frr-devel 1.14), but that remains on FRR 6.0.2, Did I need something else to get on FRR 7?

Regards,

**Comment by mimugmail** [comment]
@TekunoKage correct, in @fichtner commit only the version was changed but no revision/version bump. This means the plugin version 1.14 will only ship new frr7 when it was build against new code and synced to repo. 

For testing, run these commands on your local firewall:

```
pkg install git
opnsense-code plugins
cd /usr/plugins/net/frr
make upgrade
```

This will fetch the latest code and build the pkg on your own

**Comment by mimugmail** [comment]
This one is also in stable for long time :)
