### ISSUE TITLE
os-openconnect plugin place to additional otions

### ISSUE THREAD

**Issue by artemnext** [opnsense/plugins#1771]
Hello. I try to use last version of openconnect plugin in OPNsense. I have not to config cisco devices in my organisaton.
 
I haven’t  stable connect with standart options and I try to change config from CLI.
 
When I add strings the connection is stable.
reconnect-timeout=300
no-http-keepalive
 
But it not work fine becouse after reboot the config is reset and this strings deleted from config.
 
If it possible please add this options in next versions of plugins, or add additional string to add non standart options to openconnect config.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
