### ISSUE TITLE
os-bind: TXT records not working

### ISSUE THREAD

**Issue by NightDragon1** [opnsense/plugins#1772]
**To Reproduce**
1. Create a (master) zone using the experimental GUI
2. Add an "A record" (IP address) and an "TXT record" (description) for the same hostname
3. Save data and restart bind
5. Login via SSH / or local console.
4. execute "dig @127.0.0.1 hostname.domain A"
5. OK: The A record is listed.
6. execute "dig @127.0.0.1 hostname.domain TXT"
7. ERROR: The TXT record will not be listed

**Expected behavior**
The entered TXT record is shown for the requested host.

**Additional context**
I may have created the wrong TXT data. But according to my configured BIND under Gentoo Linux (fully manual configuration of bind) I have the format:
```
hostname       A        10.x.x.x
               TXT      "Some text"
```

and that works fine.
In OPNSense the format is (and it should be valid too but doesn't work):
```
hostname       A        10.x.x.x
hostname       TXT      "Some text"
```
I'm not a bind expert, so maybe that makes the difference...

**Environment**
Intel(R) Core(TM) i3-9100 / 128GB M.2 SSD / 16GB RAM (customized system)
OPNsense 20.1.4-amd64
FreeBSD 11.2-RELEASE-p18-HBSD
OpenSSL 1.1.1f 31 Mar 2020
OS-Bind 1.13

**Comment by NightDragon1** [comment]
*faceplam* Didn't use bind as primary DNS - unbound was still active and listening on 53

**Comment by fichtner** [comment]
No worries, thanks for posting the solution ❤️
