### ISSUE TITLE
freeradius: EAP-TLS based VLAN assignment

### ISSUE THREAD

**Issue by iamhermes** [opnsense/plugins#1774]
current situation:
On a opnsense box vlan assignment only possible through freeradius integrated users database for WPA2-Enterprise
WPA2-Enterprise clients using EAP-TLS authentication should assigned to a VLAN (based on the used client-certificate), for now only with additional MAC-VLAN enabled WiFi Network.

I think following features would give much affort to all EAP-TLS users to enhance overall security
-in freeradius plugin list all available client certs (opnsense user db) based on freeradius defined ca
-add new entries for a client cert (vlan assignment, ...) to add values like default freeradius user database
-add default vlan for not assigned certs

in post_auth section from sites-enabled/default after 

update {
    &reply: += &session-state:
}

for every certificate add

if (TLS-Client-Cert-Serial== "...."){   // or other values like Expiration...Issuer...Subject
update reply {
    &Tunnel-Type = ...,
    &Tunnel-Medium-Type = ...,
    &Tunnel-Private-Group-Id = "...new VLAN..."
}
}

should do the thing (did not check this, only found it on web)

**Comment by mimugmail** [comment]
Can you post the link where you found it? Maybe we add a new grid tab to EAP section with certificates from OPNsense store and custom attributes

**Comment by iamhermes** [comment]
now i run a test on sites-enabled/default config with radiusd restart


VLAN assignment works:
> session {
> }
> 
> post-auth {
>         update {
>                 &reply: += &session-state:
>         }
>         **if(TLS-Client-Cert-Subject== "/C=DE/ST=Germany/L=City in Germany/O=MyNetwork/emailAddress=nobody@not.me/CN=SomeComputerOrClientName") {
>         update reply {
>          &Tunnel-Type = 13,
>          &Tunnel-Medium-Type = 6,
>          &Tunnel-Private-Group-Id = 203
>         }
>         }**
>         -sql
>         exec
>         remove_reply_message_if_eap
>         Post-Auth-Type REJECT {


works:
> post-auth {
>         update {
>                 &reply: += &session-state:
>         }
>         if(TLS-Client-Cert-Serial== **"07"**){

`

VLAN Assignment works not with 1 char serial (not a 2 char block):
> post-auth {
>         update {
>                 &reply: += &session-state:
>         }
>         if(TLS-Client-Cert-Serial== **"7"**){
>

**Comment by iamhermes** [comment]
> Can you post the link where you found it? Maybe we add a new grid tab to EAP section with certificates from OPNsense store and custom attributes

Do you need the link for this? It's the code which I posted above

**Comment by mimugmail** [comment]
I think the latest PR already added this feature .. can you have a look at it?
https://github.com/opnsense/plugins/pull/1900/files

**Comment by iamhermes** [comment]
It doesn't add the described feature, custom Tunnel-Private-Group-Id for client certificates

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
