### ISSUE TITLE
Monitor Gateway/CARP/OpenVPN with Zabbix

### ISSUE THREAD

**Issue by Leboubou111** [opnsense/plugins#1775]
Hi all,

I use Zabbix for monitoring my network elements.
In fact, with Zabbix default pligin and FreeBSD Zabbix template, and I've essentials information. 
But I'd like monitor additional parameters : 
- CARP status
- Gateway status
- OpenVPN Status
- Version and Update Available

I've find a verry good script for pfSense but, it doen't work with OPNsense.
This script call to many inc php files... I think it's for pfsense public functions.
Link to script : https://github.com/rbicelli/pfsense-zabbix-template/blob/master/pfsense_zbx.php

I've checked some functions to call : 

Interfaces functions :
```
    get_interface_info()
    get_interface_arr()
    get_configured_interface_list()
    get_configured_interface_with_descr()
```

CARP functions :
```
    get_carp_status()
    get_carp_interface_status()
```

OpenVPN functions :
```
    openvpn_get_active_clients()
    openvpn_get_active_servers()
```

Services functions :
```
    get_services()
    get_service_status()
    is_service_enabled()
```

Other functions :
```
    get_single_sysctl()
    get_system_pkg_version()
    return_gateways_status()
```

Developer want some help to adapt this one : https://github.com/rbicelli/pfsense-zabbix-template/issues/14

**Do you think it's possible to adapt this script for OPNsense ?**

Many thanks for your help ;-)

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.

**Comment by chrisjosuearzu** [comment]
I'm also interested on this, if someone was able to figure it out please share more info with the rest of us.
@Leboubou111 did you have any luck by any chance?

**Comment by cweiland** [comment]
+1
