### ISSUE TITLE
net/HAproxy: 2x text: "Source IP: cumulative number of connections"

### ISSUE THREAD

**Issue by githubcek** [opnsense/plugins#1780]
**Describe the bug**
In conditions there are two lines with identical string:
Source IP: cumulative number of connections
and lower again
Source IP: cumulative number of connections

I think last should be
Source IP: cumulative number of sessions.

**To Reproduce**
1. Go to HAproxy settings
2. Edit one of conditions (acl)
3. Drop down menu: Condition type 

**Screenshots**
![image](https://user-images.githubusercontent.com/46692483/79162740-14005800-7dde-11ea-89be-4501ddb151e9.png)

Additional:
also if I select "Source IP: session rate", it is not possibible to select: Comparison and Session rate.

OPNsense 20.1.4-amd64
HAproxy 2.21

**Comment by githubcek** [comment]
Additional:
also if I select "Source IP: session rate" there is **not** possibility to select:  Comparison and Session rate.

**Comment by fraenki** [comment]
@githubcek Good catch! This will be fixed in the upcoming os-haproxy 2.22.
