### ISSUE TITLE
os-clamav plugin only listens to 127.0.0.1

### ISSUE THREAD

**Issue by Justheretoreportanissue** [opnsense/plugins#1786]
As reported, and described, in the OPNsense forum:
[https://forum.opnsense.org/index.php?topic=15319.0](url)

OP from forum post:
`
Hi!

Code: [Select]
OPNSense: v19.7.8
os-clamav: v1.7

I have recently started to play with the plugin os-clamav to be used by my mailserver (other machine on local network) for scanning mails.
As far as I can understand the configuration 'Enable TCP port' (This will enable TCP port 3310 in addition to the local socket) should make it listen to port 3310 and be available to other machines on the network.

It turns out that I only get it to listen to 127.0.0.1 port 3310 regardless if it's enabled or disabled in the configuration.

After having a look in /usr/local/etc/clamd.conf I can see the entry for this
TCPAddr 127.0.0.1

How do I get it to listen on either ALL interfaces (*) or the local LAN address of the OPNSense server?

Am I doing something wrong here?

Regards,

   /Jonas...
`

Reported here as proposed by @mimugmail 

Thank you!

**Comment by jkellerer** [comment]
Just came across the same issue and solved it with port forwarding to "127.0.0.1:3310".

_Just my opinion_: Would vote for keeping it as-is but improve the UI help to mention that port forwarding is required. An unprotected/unencrypted service like ClamAV should be protected by a firewall rule. Binding it to localhost enforces this.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
