### ISSUE TITLE
Add mesh VPN Plugin: Yggdrasil or CJDNS Networks

### ISSUE THREAD

**Issue by petrov-adg** [opnsense/plugins#1788]
I use cjdns network on OPNsense gateways without white ip addresses. Yes, it possible to compile and install it manually and it's works, but it a little bit difficult to configure or add nodes etc. 

It's possible to create cjdns or yggdrasil vpn plugin ? it can be useful for routers behind NAT (port forwardings, VPN networks etc.)

[CJDNS An encrypted IPv6 network](https://github.com/cjdelisle/cjdns)
[Yggdrasil End-to-end encrypted IPv6 networking to connect worlds](https://yggdrasil-network.github.io/)

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
