### ISSUE TITLE
quagga: syntax error in generated ospfd.conf file

### ISSUE THREAD

**Issue by cultcom** [opnsense/plugins#179]
Hi,

when I enable MD5 authentication on an interface the resulting quagga ospfd.conf file has syntax errors.
The file is beeing generated like this:

> interface vmx1_vlanXY
  ip ospf authentication md5
  ip ospf authentication-key XXXXXX
  ip ospf cost 10
!
!
router ospf
 redistribute connected
 passive-interface vmx1_vlanZZ
 network 10.10.42.0/24 area 0.0.0.44
!

But this leads to an error starting up the service:
> Checking ospfd.conf
*** Error reading config: There is no such command.
*** Error occured processing line 9, below:
  ip ospf authentication md5
 FAILED

Actually the syntax is as follows:
> interface vmx1_vlanXY
  ip ospf message-digest-key 1 md5 XXXXXX
  ip ospf cost 10
!
!
router ospf
 redistribute connected
 passive-interface vmx1_vlanZZ
 network 10.10.42.0/24 area 0.0.0.44
 area 0.0.0.44 authentication message-digest
!

**Comment by fabianfrz** [comment]
Does #183 fix the issue?

**Comment by cultcom** [comment]
well from the changes I assume that if fixes the interface configuration part but there is still the "router ospf" section which lacks the entry "area xxx authentication message-digest".

**Comment by cultcom** [comment]
We applied the patch to a running test machine and it is working. The generated config is valid and running now. Please put this fix to the next release soon.

**Comment by fichtner** [comment]
added to stable/17.1 for 17.1.10.
