### ISSUE TITLE
net/haproxy: http_auth_group and userlists

### ISSUE THREAD

**Issue by githubcek** [opnsense/plugins#1796]
**Is your feature request related to a problem? Please describe.**
I have basic authentication turned on and HAproxy have method **[http_auth_group](https://cbonte.github.io/haproxy-dconv/2.1/configuration.html#7.3.6-http_auth_group)** which need name of **userlist** and returns string corresponding to the current logged-in user name.
Problem is that userlist's name generated are dynamic and not static and can't be used in custom conditions/rules.

**Describe the solution you'd like**
Solution1(best):
Add additional userslists defined in "User Management->Groups". Name of userlist should be created with same name as group name defined in group settings. (Field: Name)
If group userlist's would have names, it could be used in all custom conditions/rules :)

Solution2:
add support for method **http_auth_group**

**Describe alternatives you've considered**
I have found solution to create  userlist with static name in "Settings->Global Parameters" in  "Custom options" like this:
```
    userlist userlist_name
        user user1 password $6$...
        user user2 password $6$...

```
and later in Rules (actions) I can use this custom rule like this:
`   http-request set-var(txn.user) http_auth_group(userlist_name)
`
and then I put this variable to cookie: %[var(txn.user)]. I read this cookie inside html and show logged in username :)

Problem with this solution is: If I add user (and add it to group) I have to go to Settings->Global Parameters->Custom options and also add user there :(

Regards.

**Comment by fraenki** [comment]
>  Add additional userslists defined in "User Management->Groups". Name of userlist should be created with same name as group name defined in group settings. (Field: Name)

A new option will be available in the upcoming os-haproxy 2.24:

![hap_group](https://user-images.githubusercontent.com/909706/88489861-777e5200-cf97-11ea-84ed-017c7fead854.png)

If the new option `add userlist` is enabled, the group will be added as userlist to the HAProxy configuration:

```
userlist grouptest2a
    user foo3 insecure-password sdfsdfsdf
    user fooo insecure-password plain-text-pass
```

However, HAProxy only allows alphanumeric characters in userlist names. Note that all whitespace and other special characters are automatically stripped from the group name, as demonstrated in this example.

Besides that I've added support for `http-request set-var` and `http-response set-var` functions, which will be available for use in rules.
