### ISSUE TITLE
BIND: enhancement requests

### ISSUE THREAD

**Issue by dpiven** [opnsense/plugins#1797]
Hi -- having installed BIND on my new opnSense machine (bind-devel on top of opnSense development), I've run into a couple of issues I think might be popular enough to warrant some work:

1) Currently, copying a zone does NOT copy any records within the zone.  I was trying to build a BIND server to serve seven domains I host, and found that copying the zone didn't copy the contents of the zone -- I had to reenter all the glue records, etc.  The request is to have copying a zone copy the records within the zone.

2) I would like to be able to set the zone serial number to an arbitrary value.  Right now I have a DNS server on another machine which I am trying to retire :-) with BIND on my new opnSense system.  The problem is that my new zones on the opnSense system have a serial number like 2004171447, while the zones on my live server have a serial number like 2020041105 (YYMMDD##)... which will cause problems replicating the zones on the opnSense box with my secondary DNS provider.  I would like to able to set the serial # on each zone I host to, say, a YYYYMMDD## value like I do on BIND on the old server.

Thanks!

**Comment by dpiven** [comment]
This is with os-bind-devel 1.13 on opnSense OPNsense 20.7.b_40-amd64.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
