### ISSUE TITLE
dns/unbound-plus: Issue with /var RAM disk option

### ISSUE THREAD

**Issue by definitio** [opnsense/plugins#1798]
**Describe the bug**
Ad blocking doesn't work after reboot when /var RAM disk enabled because /var/unbound/etc/dnsbl.conf is missing.

**To Reproduce**
1. Go to 'System -> Settings -> Miscellaneous'
2. Enable '/var RAM disk'
3. Go to 'Services -> Unbound DNS ->Blacklist'
4. Choose list(s) and enable
5. Reboot
6. Ad blocking doesn't work

**Environment**
OPNsense 20.1.4 (amd64, OpenSSL)

**Comment by pkejval** [comment]
Thanks for reporting issue. I'll take a look at it.

**Comment by mimugmail** [comment]
@fichtner do you have an example somewhere around where this is not handled via rc.conf since Unbound is called via onestart like OpenVPN

**Comment by fichtner** [comment]
Unbound chroot + /var MFS + dynamic list generated from Internet requiring Unbound to resolve in the first place is a terrible mix. Basically we need to fix up the startup with rc.syshook start facility, but also need to put a mockup of "dnsbl.conf" in place for the boot to continue correctly.

**Comment by pkejval** [comment]
What do you think about adding script into "/usr/local/etc/rc.syshook.d/start/"?
50-dnsbl will be generated from template:

```
#!/bin/sh

if [ ! -f "/var/unbound/etc/dnsbl.conf" ]; then
    echo "/var/unbound/etc/dnsbl.conf file is missing. Restarting script."
    configctl unboundplus dnsbl
fi
```

**Comment by fichtner** [comment]
please no rc.syshook files from templates. that what plugins are for... dnsbl.py is responsible for knowing if it should run and how the dnsbl.conf contents is generated.

it's still messy, unfortunately. worst case unbound doesn't start because dnsbl.conf is not found but a required include file, but I'm not sure if unbound cares about it. just a worst case guess...

**Comment by mimugmail** [comment]
Unbound just includes files ending with .conf in etc/ but maybe it's more
worth imvestigating to start the usual way.

Franco Fichtner <notifications@github.com> schrieb am Di., 21. Apr. 2020,
10:53:

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
