### ISSUE TITLE
Add logging for unbound-plus blacklisting

### ISSUE THREAD

**Issue by rsheasby** [opnsense/plugins#1801]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

[x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
When a domain is blocked using the DNSBL functionality, there is no indication that this has happened nor a simple way to identify and unblock a false positive.

**Describe the solution you'd like**
A table that logs and displays recent blocked requests, including the IP address that performed the request. A button to easily add the blocked site to the whitelist would also be great. Furthermore, responding with a much shorter TTL for blacklist results (60 seconds or so) would allow unblocking of a site relatively quickly, without having to wait an hour for the client cache to expire. This could alternatively be configurable in the DNSBL settings.

**Comment by pkejval** [comment]
I had the same idea. It should look like https://pi-hole.net/ for RasperryPi. But we are blocking at Unbound level in unbound-plus plugin. I think it could be possibly done with Unbound verbose logging but at cost of performance.

Sorry but I am not interested in implementing feature like this. Maybe someone else do or feel free to submit your PR.

TTL could be set in Unbound config. We can't set another TTL for "blocked" queries alone.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
