### ISSUE TITLE
#Unbound-Plus - Only one DoT server possible

### ISSUE THREAD

**Issue by computeralex92** [opnsense/plugins#1802]
**Describe the bug**
If I try to add more than one DoT server, it is not possible to save the config.

`list validation error`

**To Reproduce**
1. Go to Services / Unbound DNS / Miscellaneous
2. Add more then one servers to DNS over TLS Servers
3. Try to save this setting

**Expected behavior**
The config will be accepted and saved.

**Screenshots**
<img width="1484" alt="Bildschirmfoto 2020-04-23 um 21 01 10" src="https://user-images.githubusercontent.com/6564612/80138763-9a1e5a80-85a5-11ea-82ee-e5789a514d8e.png">

**Relevant log files**

```
{
  "result": "failed",
  "validations": {
    "miscellaneous.dotservers": "list validation error"
  }
}
```

**Environment**
Software version used and hardware type if relevant.
e.g.:
 
OPNsense 20.1.5-amd64
FreeBSD 11.2-RELEASE-p18-HBSD
LibreSSL 3.0.2
AMD GX-412TC SOC (4 cores)

**Comment by Madj42** [comment]
Having the same issue here.  I'd be happy to help test when a fix is available.
