### ISSUE TITLE
Option for restrictmoderate.youtube.com in BIND plugin

### ISSUE THREAD

**Issue by paulstaylor** [opnsense/plugins#1805]
Posted on the forum and reply was to open a FR here:

The restrict.youtube.com domain seems to be VERY locked down.  

To limit YouTubes results to safe items, Google recommends:

Add a CNAME for the following hostnames:
www.youtube.com
m.youtube.com
youtubei.googleapis.com
youtube.googleapis.com
www.youtube-nocookie.com
To set strict restricted access, set the CNAME value to restrict.youtube.com.

BUT, just below that line there's another option in the recommendation:
To set moderate restricted access, set the CNAME value to restrictmoderate.youtube.com.

I think it would be good to have this available in the Web interface.

Thank you

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
