### ISSUE TITLE
[NGINX] Wrong mime-type for csp-reports

### ISSUE THREAD

**Issue by Kimotu** [opnsense/plugins#1808]
[X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

[X] The title contains the plugin to which this issue belongs

**Describe the bug**
csp-reports create HTTP 400 BAD REQUEST

**To Reproduce**
Set CSP headers and load sources that are not allowed. Tested firefox and chrome.

**Expected behavior**
CSP report created and saved to /var/log/nginx/csp_violations.log

**Solution**
Change expected mime-type from json to csp-report in file /usr/local/opnsense/scripts/nginx/csp_report.php. Firefox and chrome send the csp-report with mime-type application/csp-report.

I already forked and fixed it and created a pull-request.

*Environment**
OPNsense 20.1.5-amd64
FreeBSD 11.2-RELEASE-p18-HBSD
OpenSSL 1.1.1f 31 Mar 2020

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
