### ISSUE TITLE
Multiple issues with monit plugin

### ISSUE THREAD

**Issue by thomasnilsen** [opnsense/plugins#181]
- Unable to add multiple smtp servers using comma separated list. Tried space in between also etc.
- Unable to add ping to a host (in my example google public dns)
- Unable to add ping or network link on opnsense

![screen shot 2017-06-13 at 11 05 01](https://user-images.githubusercontent.com/7230202/27075094-46e23256-5029-11e7-88fe-ac29c34877de.png)
![screen shot 2017-06-13 at 11 09 01](https://user-images.githubusercontent.com/7230202/27075091-46dc6aba-5029-11e7-8455-ddf19bec6f62.png)
![screen shot 2017-06-13 at 11 09 15](https://user-images.githubusercontent.com/7230202/27075095-46e31234-5029-11e7-95a6-d47fec027c9a.png)
![screen shot 2017-06-13 at 11 10 44](https://user-images.githubusercontent.com/7230202/27075093-46dfff22-5029-11e7-9720-626c2f368f6b.png)
![screen shot 2017-06-13 at 11 10 56](https://user-images.githubusercontent.com/7230202/27075096-46eafada-5029-11e7-804e-ddd4440e6344.png)
![screen shot 2017-06-13 at 11 11 40](https://user-images.githubusercontent.com/7230202/27075092-46ddbf82-5029-11e7-991a-9c0851754b5c.png)

**Comment by fbrendel** [comment]
> Unable to add multiple smtp servers using comma separated list. Tried space in between also etc.

This is a bug. :unamused:  I'll fix that.
> Unable to add ping to a host (in my example google public dns)

The service type must be 'Remote Host' not 'Network'. [NETWORK PING TEST](https://mmonit.com/monit/documentation/monit.html#NETWORK-PING-TEST)
> Unable to add ping or network link on opnsense

For the NetworkLink test you need the service type 'Network'. [NETWORK LINK STATUS TEST](https://mmonit.com/monit/documentation/monit.html#NETWORK-LINK-STATUS-TEST)
![image](https://user-images.githubusercontent.com/20316831/27125125-90fcf19e-50f3-11e7-985a-5da3cb04c592.png)

**Comment by thomasnilsen** [comment]
Thanks! I got the ping test working the way you suggested.

I still think there is something wrong with the filesystem test;

![screen shot 2017-06-15 at 20 39 19](https://user-images.githubusercontent.com/7230202/27196454-cccbe1fe-520a-11e7-9289-4bb22f14dc61.png)
![screen shot 2017-06-15 at 20 39 34](https://user-images.githubusercontent.com/7230202/27196453-ccc9e8a4-520a-11e7-803d-84d5482921e4.png)

**Comment by fichtner** [comment]
The file system test is broken in monit 5.22, next update will bring in 5.23.
