### ISSUE TITLE
[DNSCrypt-Proxy] Does not support multiple forwarders per domain

### ISSUE THREAD

**Issue by deasmi** [opnsense/plugins#1810]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

[X] The title contains the plugin to which this issue belongs

**Describe the bug**
Providing multiple forwarders for a single domain does not have the intended result of listing them in forwarding-rules.txt as comma separated value. Instead it adds separate lines for each, only the first of which appears to be used.

**To Reproduce**
1. Go to 'DNSCrypt-proxy forwarders
2. Add a forwarder to example.com to ip address 1.1.1.1
3. Add a forwarder to example.com to ip address 2.2.2.2
4. Click save
5. Examine /usr/local/etc/dnscrypt-proxy/forwarding-rules.txt

**Expected behavior**
File should contain
example.com 1.1.1.1,2.2.2.2

File instead contains
example.com 1.1.1.1
example.com 2.2.2.2

**Additional context**
I forward internal domains to AD controllers, of which I have two. If the first one in file is down DNS resolution fill fail.

**Environment**

OPNsense 20.1.3 (amd64, LibreSSL).
APC 2

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.

**Comment by deasmi** [comment]
Hi. Wondering why this has been closed. 

Is this fixed or intended behaviour?
