### ISSUE TITLE
Unbound Plus - DoT - TLS Authentication

### ISSUE THREAD

**Issue by mrancier** [opnsense/plugins#1811]
Is it possible to add TLS authentication/configuration ID values for DoT servers.ie. host names for the likes of nextdns or blockerdns  ?

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
