### ISSUE TITLE
os-bind: add zone transfer ACL configuration to slave zones

### ISSUE THREAD

**Issue by iongchun** [opnsense/plugins#1813]
**Information**
- Plugin version: 1.13
- Package version: bind916-9.16.2
- Configuration URI: /ui/bind/general/index#domains

**Problem**
A master zone has "Allow Transfer" option to choose which ACL the server allow for transfer requests,
but a slave zone has no such option to choose.
Therefore slave zones inherit default value, i.e. any host can request for a copy of zone records.

**Possible solutions**

- Add "Allow Transfer" option for slave zones

Or/and:

- Add "Allow Transfer" option to General page for a global / fallback configuration

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.

**Comment by fraenki** [comment]
Sorry for hitting the inactivity timeout, it was my fault. I'll review the PR soon.
