### ISSUE TITLE
security/acme-client: Update for CloudFlare DNS-01

### ISSUE THREAD

**Issue by woolfyx** [opnsense/plugins#1817]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

- [X] I have searched the existing issues and I'm convinced that mine is new.

- [X] The title contains the plugin to which this issue belongs

**Describe the bug**
When you try to issue a certificate based on a DNS-01 CloudFlare challenge, it's failed due to a change in a CloudFlare API.

An issue is open for acme.sh project : acmesh-official/acme.sh/issues/2888

An update is required to update the file 'dns_cf.sh'. Tested manually on my opnsense and this fix solve the issue.

**Comment by fraenki** [comment]
The fix is available in acme.sh 2.8.6, which will be included in the next release of OPNsense.
