### ISSUE TITLE
[NGINX] Allow multiple ids in whitelists (comma separated)

### ISSUE THREAD

**Issue by Kimotu** [opnsense/plugins#1819]
[X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

[X] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
You have to create separate rules e.g. for 1010 '(' and 1011 ')' for same url, matchzone, etc. 

**Describe the solution you'd like**
Allow comma to list rules in id field: 1010,1011

**Additional context**
In naxsi whitelist examples no match value 'str:', 'rx:' is shown. So I think you could omit this value if match type is whitelist.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
