### ISSUE TITLE
netdata: apps.plugin missing permissions to monintor all processes

### ISSUE THREAD

**Issue by cryptoluks** [opnsense/plugins#1823]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

- [x] I have searched the existing issues and I'm convinced that mine is new.

- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
I am not entirely sure if this is a OPNsense port issue or BSD upstream issue, but as I discovered it with the OPNsense plugin, I will report here first.

With the default config, only processes the netdata user has permissions to are visible under Applications. No system processes are monitored:
![image](https://user-images.githubusercontent.com/9020527/81340328-f6a66d00-90af-11ea-876b-36232280ede2.png)

**To Reproduce**
1. Install netdata plugin and start it
2. Visit netdata web interface
3. Observe applications

**Expected behavior**
Even root owned and other system processes should be displayed.

This is happening, because netdata has no permissions to monitor other processes - more precisely, `apps.plugin` has no permissions.

There are three ways this issue is solved:
- run netdata as root
- use capabilities: `setcap`/`getcap` not available on BSD? On my Arch Linux system `apps.plugin` has the following capabilities:
```
❯ getcap apps.plugin
apps.plugin = cap_dac_read_search,cap_sys_ptrace+ep
```
- set `setuid` bit with`chmod 4755`

So it seems that the only way to monitor all processes is the setuid way. Of course, with `setuid` some security implications must be considered, especially on a security critical system like OPNsense.

**Relevant log files**
```
[root@opnsense ~]# sudo -u netdata /usr/local/libexec/netdata/plugins.d/apps.plugin
2020-05-07 21:24:42: apps.plugin ERROR : MAIN : apps.plugin should either run as root (now running with uid 302, euid 302) or have special capabilities. Without these, apps.plugin cannot report disk I/O utilization of other processes. Your system does not support capabilities. To enable setuid to root run: sudo chown root:netdata /usr/local/libexec/netdata/plugins.d/apps.plugin; sudo chmod 4750 /usr/local/libexec/netdata/plugins.d/apps.plugin;
```

As you can see, every netdata process is running with user netdata by default:
```
[root@opnsense /usr/local/libexec/netdata/plugins.d]# ps aux | grep netdata
netdata 28080  90.6  0.3   46876 12412  -  SN   22:34      0:04.20 /usr/local/sbin/netdata -u netdata -P /var/db/netdata/netdata.pid
netdata 70685  36.3  0.6   27784 24064  -  RN   22:34      0:03.03 /usr/local/bin/python3.7 /usr/local/libexec/netdata/plugins.d/python.d.plugin 1
netdata 35738  12.1  0.1 1059248  4652  -  SN   22:34      0:00.20 /usr/local/bin/bash /usr/local/libexec/netdata/plugins.d/charts.d.plugin 1
netdata 19608  10.7  0.2   12396  6876  -  SN   22:34      0:00.05 /usr/local/libexec/netdata/plugins.d/apps.plugin 1
```
When giving netdata the capability to start `apps.plugin` as root user:
![image](https://user-images.githubusercontent.com/9020527/81342419-800b6e80-90b3-11ea-8ead-d612f941e355.png)

**Environment**
OPNsense 20.1.6-amd64
FreeBSD 11.2-RELEASE-p19-HBSD
LibreSSL 3.0.2

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
