### ISSUE TITLE
Freeradius stores user passwords in plain in config

### ISSUE THREAD

**Issue by tomatotoast** [opnsense/plugins#1824]
System:
OPNsense 20.1.6-amd64
FreeBSD 11.2-RELEASE-p19-HBSD
OpenSSL 1.1.1g 21 Apr 2020

The Freeradius plugin stores user/pass in opnsense config in plaintext. An attacker could extract those to gain access to the network.

**Comment by tomatotoast** [comment]
extract from config file:

<users>
          <user uuid="3cd951d6-9d96-472f-86db-4eda17f4c71d">
            <enabled>1</enabled>
            <username>testuser</username>
            <password>testpassword</password>
            <description/>
            <ip/>
            <subnet/>
            <route/>
            <ip6/>
            <vlan/>
            <logintime/>
            <simuse/>
            <wispr_bw_min_up/>
            <wispr_bw_max_up/>
            <wispr_bw_min_down/>
            <wispr_bw_max_down/>
            <chillispot_bw_max_up/>
            <chillispot_bw_max_down/>
            <mikrotik_vlan_id_number/>
            <mikrotik_vlan_id_type/>
            <sessionlimit_max_session_limit/>
            <servicetype/>
            <linkedAVPair/>
          </user>

**Comment by tomatotoast** [comment]
extract from config file

`<users>
          <user uuid="3cd951d6-9d96-472f-86db-4eda17f4c71d">
            <enabled>1</enabled>
            <username>testuser</username>
            <password>testpassword</password>
            <description/>
            <ip/>
            <subnet/>
            <route/>
            <ip6/>
            <vlan/>
            <logintime/>
            <simuse/>
            <wispr_bw_min_up/>
            <wispr_bw_max_up/>
            <wispr_bw_min_down/>
            <wispr_bw_max_down/>
            <chillispot_bw_max_up/>
            <chillispot_bw_max_down/>
            <mikrotik_vlan_id_number/>
            <mikrotik_vlan_id_type/>
            <sessionlimit_max_session_limit/>
            <servicetype/>
            <linkedAVPair/>
          </user>
`

**Comment by tomatotoast** [comment]
Are further information required or why is the status incomplete?

**Comment by mimugmail** [comment]
Because you didn't use the template.

The main problem is that FreeRADIUS write the password in plaintext itself. There is a hack via ntlm hashing available but I don't see a security gain compared to the work it takes.

If you feel brave I'm happy to help/review/test

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
