### ISSUE TITLE
Freeradius use local user Database for authentication

### ISSUE THREAD

**Issue by tomatotoast** [opnsense/plugins#1825]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
YES
[X] I have searched the existing issues and I'm convinced that mine is new.
YES
[-] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
NO

**Describe the solution you'd like**
(e.g. I would like an input field in the `/ui/firewall/alias` which would add .... to ....)

Is it possible to use the local user database on the device for authentication purpose?
Like: One user is able to connect to OpenVPN with a given username and Password.
The user should be able to use the same credentials to authenticate with freeradius in the network.
So no LDAP authentication needed.

**Describe alternatives you've considered**

Using a seperate LDAP Server would be a solution.

**Additional context**

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
