### ISSUE TITLE
missing documentation of workflow for new plugins

### ISSUE THREAD

**Issue by botboe** [opnsense/plugins#1827]
[+] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
[+] I have searched the existing issues and I'm convinced that mine is new.

Hi everyone, I'm currently developing a plugin for radsecproxy, a secury Radius proxy used for example in the eduroam-project. The GUI-part is quite complete after looking at the tutorials and other plugins in this repository. 

But now I'm not sure about the next steps of the workflow. I'd like to publish the plugin in this repository, so what do I have to do next? The tutorials told me to create the files directly in the corresponding places in the filesystem, whereas [here](https://github.com/opnsense/plugins/issues/231#issuecomment-322993962) the files need to lie under `/usr/plugins`.

The mentioned `make` command isn't working either:
```
root@radsecproxy-dev:/usr/plugins/net/radsecproxy # make package
make: don't know how to make package. Stop

make: stopped in /usr/plugins/net/radsecproxy
```

Is there an instruction for publishing plugins I didn't find?

Best regards
Tobias

**Comment by AdSchellevis** [comment]
Hi Tobias, the tutorial should contain all files needed to build a plugin https://docs.opnsense.org/development/examples/helloworld.html

**Comment by Mad-Onion** [comment]
I was switching between the "hello world" and "using grids" examples so much, that I obviously never reached the last chapter of "hello world" - thanks @AdSchellevis 

What would be the next steps to publish the plugin here?

**Comment by AdSchellevis** [comment]
a pull request containing your code, so people can review and test .

**Comment by Mad-Onion** [comment]
Hi Ad, I'm sorry for asking but this is the first time for me to contribute something in form of a pull request. I know git and use it for private projects (sync between multiple PCs), but that's it.

What is the way to go now? Create a fork of the plugins-repository on github, check it out to my virtual opnsense, create my plugin there, push the changes back into it and create a pull request from there? Or can I checkout the plugins-repository directly into my virtual opnsense and create a pull request from there?
Like I said, it's my first time and I want to make everything right ;-)

**Comment by AdSchellevis** [comment]
@Mad-Onion no problem, you normally fork indeed and create a PR then. I think GitHub as a nice document about the standard workflow somewhere, but I couldn't find it very fast.

**Comment by Mad-Onion** [comment]
Ok, I'll give it a try and also try to find the github-docs :-)

**Comment by fraenki** [comment]
I was about to add the link :)
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
