### ISSUE TITLE
Support for Zabbix 5.0 LTS

### ISSUE THREAD

**Issue by x-jokay** [opnsense/plugins#1830]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
`os-zabbix5-proxy` and `os-zabbix-agent` plugins supporting Zabbix 5.0 LTS.

**Describe alternatives you've considered**
None.

**Additional context**
* [What's New in Zabbix 5.0 LTS](https://www.zabbix.com/whats_new_5_0)

**Comment by mimugmail** [comment]
Hi,

it's not yet in FreeBSD ports, but it will come :)

**Comment by fraenki** [comment]
@mimugmail, I suggest that you handle the upgrade of os-zabbix-proxy and I care for os-zabbix-agent, if you agree. :) (But I'm not in a hurry. Zabbix 5.0 hast just been released and I'd favour to give it some minor releases to stabilize.)

**Comment by mimugmail** [comment]
Yep, maybe we can also wait for 20.7

**Comment by x-jokay** [comment]
May be it already works using the current plugin(s), I didn't tested it yet.

**Comment by fraenki** [comment]
Yes, 20.7 might be the perfect time to switch Zabbix to a new major release.

**Comment by fraenki** [comment]
> May be it already works using the current plugin(s), I didn't tested it yet.

Zabbix Agent is almost certainly compatible with newer releases. Zabbix Proxy however should usually match the Zabbix Server version, so it's likely that it does not work with newer/older versions.

**Comment by fichtner** [comment]
We should at least add it to packages now if they are available?

**Comment by mimugmail** [comment]
Yes. Not sure if the agent will be in Go then ... :)

**Comment by x-jokay** [comment]
[svn commit: r537856 - in head/net-mgmt: . zabbix5-agent zabbix5-frontend zabbix5-java zabbix5-proxy zabbix5-server zabbix5-server/files](https://docs.freebsd.org/cgi/getmsg.cgi?fetch=4851808+0+/usr/local/www/mailindex/archive/2020/svn-ports-all/20200607.svn-ports-all)
