### ISSUE TITLE
net/frr: Add a RAW config option.

### ISSUE THREAD

**Issue by Napsterbater** [opnsense/plugins#1831]
**Is your feature request related to a problem? Please describe.**
FRR Configuration is very limited via current web interface, good for somewhat basic ish configurations, but still limited.

**Describe the solution you'd like**
Allow for more advanced FRR configurations via a "raw" configuration.

When a Routing Protocol is enabled and a raw config is provided via a free form text box, or if a checkbox is selected to use said free form text box, ignore anything configured in the web interface for that Routing Protocol and just use the raw config as provided.

**Additional context**
While the web interface is nice for basic configurations, allowing free form raw configs can allow someone to unleash the full power of FRR.

Also, it would make it easy to copy and paste large identical sections of the configs from one system to another during initial setup or future changes.

This is pretty much the only show stopper in me being able to use Opnsense to replace another solution in place.

**Comment by mimugmail** [comment]
Raw configs will never find it's way into OPNsense as the projects tries to more and more get rid of them. Which feature are you missing? Maybe it's not that hard to implement it.

You are also free to just use the pkg without the plugin, so you can just copy your existing configs.
Only downsice is you can't control the daemon via UI, rest is the same, and with the benefit that you don't need to restart the process for adding stuff like BGP neighbors

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.

**Comment by Napsterbater** [comment]
Seem that while Custom options are being removed from the UI, there is now support in some built in backend services to read a config from the file system directly.

Maybe this can be looked into for FRR, either said file add to the generated config, or said file is the whole config, ignoring the UI.

**Comment by mimugmail** [comment]
Which features so you need not available via gui?

**Comment by Napsterbater** [comment]
BGP Confederation, (being worked on)
In GUI BGP Route map "names" is limited to numbers even though FRR accepts alphanumeric names. And when applying route map GUI refers to it by only number.
Route Maps will not apply set value unless 1 of the 3 filter options is used to match, again not required, no match = everything matches.
Also ability to set "no bgp default ipv4-unicast"
Ability set a peer for IPv4 or IPv6 or both AFI ties into the prev option.

These a just a few things I can think of off the top of my head. But also, the sheer convenience of making mass changes across multiple units would be easier, even if I had to SFTP a modified file to the units. I would say even a partial add on/include type like Unbound/dnsmasq but looks like FRR does not support that yet and it would to be a full config.

**Comment by Napsterbater** [comment]
Here is a link to my post in the other Feature request "issue" https://github.com/opnsense/plugins/issues/2202#issuecomment-767175708

FRR is an insanely flexible and configurable, as it needs to be. A Lot of options are only needed in certain niche situations. While it would be nice to have every single knob FRR provides in the GUI it's not practical, some times and for a variety of reasons, it's just easier to have a free form RAW/Custom config/options. And I know the team is already limited so Being able to focus on just the knobs needed for the vast majority, and leaving the knobs that if one is turning should know how to deal with the whole config anyways.

I know OPNsense it trying to get away from this. But this just put an artificial limit on the system IMO. Also without the RAW/Custom options being able to be specified in the GUI this removes the ability for the Config Backup to copy/save this portions as well, I have no problem keeping my RAW config saved elsewhere, but it is another nice integration perk.

**Comment by AdSchellevis** [comment]
You can build any type of setup you like by just installing `frr` without the plugin, raw config options won't be accepted for reasons quite often explained (https://docs.opnsense.org/development/guidelines/basics.html#safeguard-user-input).  A file based option might be possible, someone just needs to open a PR for discussion in that case.

**Comment by Napsterbater** [comment]
> FRR still needs this. A lot of thing can't be configured like BGP neighbor/peer groups so you can do dynamic neighbors

I agree but unfortunately the team has decided that's not going to happen.

Which still doesn't make any sense to me.

They claimed it was for security at one point, but if someone has access to modify the configuration then security is out the window already..

Unfortunately I've just had to do without FRR completely on OPNsense and use other workarounds outside of OPNsense.

**Comment by AdSchellevis** [comment]
> They claimed it was for security at one point

It is. It also makes it theoretically impossible to validate if a (combination of) choice(s) is vallid, which makes it quite user unfriendly in the long run. When options are needed, open a ticket and explain others why such a feature is a good idea and/or contribute it yourself...... 

> but if someone has access to modify the configuration then security is out the window already..

Unfortunately in the real world it doesn't work like that (yes, security researchers report issues like these, cve's are opened for less....).
If you can't validate input you are asking for code injections which at some point will bite you in the tail.

**Comment by Napsterbater** [comment]
I did request multiple options, they were ignored so I gave up.

As I explained in this thread, you guys don't have the development bandwidth to add the hundreds of available options that FRR provides, and without those options, FRR is extremely limited and just about useless for anything other than extremely basic usage.

FRR worked amazingly well when I had the ability to use a raw configuration But without that ability it's practically useless.

**Comment by fichtner** [comment]
Is this satire? Happy new year!

**Comment by AdSchellevis** [comment]
it looks like it, happy new year indeed!

**Comment by ulyssedu45** [comment]
PFSENSE handles this very well, it seems like the OPNSENSE team is being disingenuous. Essential options are missing, for example, the source IP for BGP announcements are arbitrarily limited to interfaces, and it is not possible to use CARP IP addresses, for example.

**Comment by fichtner** [comment]
These are the projects preferred policies, certainly not the policies of other projects. We live and die with our policies and that’s ok.


Cheers,
Franco

**Comment by ulyssedu45** [comment]
Making essential features unusable is not a political decision but a lack of sound judgment. Providing options that conflict with how FRR is designed to operate leads to inconsistent behavior and discourages the adoption of OPNsense.

We had planned to deploy six firewalls using OPNsense with a Business Support license. However, the fact that a critical component such as routing is poorly implemented seriously calls this decision into question.

FRR is currently unusable in complex environments due to unsuitable design choices in OPNsense. Additionally, discussions on certain topics suggest there is resistance to changes that would address these limitations.

**Comment by Napsterbater** [comment]
Save your breath, they even try to say just open a ticket with whatever feature you want, and when I explained that I did and then they were ignored, well their response and attitude is clearly evident. It's quite funny that the other project implements this better, and usually that type of attitude comes from that other project.

**Comment by fichtner** [comment]
I‘m closing this useless discussion. You can check how many FRR features were added since this ticket was opened and see that reasonable requests will be easily and plentifully fulfilled. 😊
