### ISSUE TITLE
net/wireguard: Usage for prod env

### ISSUE THREAD

**Issue by x-jokay** [opnsense/plugins#1837]
Hello

When do you think will Wireguard no longer be considered as "not advised to be used in prod env" (message on UI) by OPNsense?

* [WireGuard VPN: What You Need to Know](https://restoreprivacy.com/wireguard/)

**Comment by mimugmail** [comment]
20.7 brings a Kernel which prevents some rare crashes, maybe we can remove it with 20.7

**Comment by x-jokay** [comment]
Cool, nice to know 👍

**Comment by fichtner** [comment]
Said fix might be in 20.1.7. We haven’t decided, but it’s nice to have rather sooner than later.

Cheers,
Franco

**Comment by fichtner** [comment]
@mimugmail if you want to take care of it we can already remove it from -devel (no version bump required)

**Comment by mimugmail** [comment]
It isnt in devel, there is only a warning in the volt. :)

**Comment by fichtner** [comment]
os-wireguard-devel and os-wireguard are the same AFAICS, so both have a warning
