### ISSUE TITLE
dns/dyndns support tracking CARP/alias addresses

### ISSUE THREAD

**Issue by darkain** [opnsense/plugins#1843]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to easily track my CARP address and update DNS automatically, rather than having to update it manually when setting/changing CARP settings.

**Describe the solution you'd like**
Add CARP (and really, any aliases) to the drop down list on the dyndns plugin.

**Describe alternatives you've considered**
manual dns, rather than dynamic dns

![image](https://user-images.githubusercontent.com/2524251/82606089-5cdcc680-9b6b-11ea-830c-48b3406ad585.png)

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.

**Comment by Paraplexo** [comment]
> This issue has been automatically timed-out (after 180 days of inactivity).
> 
> For more information about the policies for this repository,
> please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.
> 
> If someone wants to step up and work on this issue,
> just let us know, so we can reopen the issue and assign an owner to it.

I think this is the same issue i have descibed here: https://github.com/opnsense/plugins/issues/2114 
It probably can be solved when all interfaces could be selected (similar as it is implemented in OpenVPN server settings). This way you could also select the virtual CARP IPs sitting on the particular WAN interface.
