### ISSUE TITLE
os-acme-client reports a php 7.3 warning

### ISSUE THREAD

**Issue by weust1979** [opnsense/plugins#1844]
**Describe the bug**
Since 20.1.7 and the PHP 7.3 update, the os-acme-client plugin reports a warning at midnight (when the cron job is run.

> [21-May-2020 00:00:00 Europe/Amsterdam] PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /usr/local/opnsense/scripts/OPNsense/AcmeClient/certhelper.php on line 1421

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**
1. Enable the plugin
2. Wait till the cron job is run at midnight
3. Login in OPNsense and on the Dashboard it will shows the OPNsense error report

**Expected behavior**
To not show the warning every night/

**Relevant log files**

> [21-May-2020 00:00:00 Europe/Amsterdam] PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /usr/local/opnsense/scripts/OPNsense/AcmeClient/certhelper.php on line 1421

**Environment**
OPNsense 20.1.7 (amd64, LibreSSL, PHP 7.3)

**Comment by ssbarnea** [comment]
I see bug closed 7 days ago but still happening today with a system configured to check for updates daily.

**Comment by fichtner** [comment]
Will be fixed in 20.1.8. The impact is nonexistent so we will not rush to hotfix. It was said a number of times already...
