### ISSUE TITLE
net-mgmt/telegraf: Support InfluxDB v2 Output

### ISSUE THREAD

**Issue by jojoxd** [opnsense/plugins#1847]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

[x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
I've recently upgraded to Influx v2.0.0-beta on my servers, but can't find an option to setup an influx 2 connection in the os-telegraf package.

**Describe the solution you'd like**
I'd like a checkbox, like the other ones for influx/prometheus/etc outputs, where we can fill in the following data:

* Url - The URL where Influx v2 is hosted.
* Token - The token with which to connect.
* Organization - Influx v2 is multi-tenant, so we _must_ specify an organization.
* Bucket - Database name.

**Describe alternatives you've considered**

**Additional context**

Here's how the configuration should look like
```
[[outputs.influxdb_v2]]
    ## The URLs of the InfluxDB cluster nodes.
    ##
    ## Multiple URLs can be specified for a single cluster, only ONE of the
    ## urls will be written to each interval.
    ## urls exp: http://127.0.0.1:9999
    urls = ["http://my.host:9999"]

    ## Token for authentication.
    token = "<base64-encoded-string>"

    ## Organization is the name of the organization you wish to write to; must exist.
    organization = "<string>"

    ## Destination bucket to write into.
    bucket = "<string>"
```

**Environment**
OPNsense 20.1.7-amd64 on a virtual machine
os-telegraf 1.7.7

**Comment by jojoxd** [comment]
I'll try to spin up a development environment and add it myself, doesn't seem that hard.

Ill be taking notes from https://github.com/opnsense/plugins/pull/834

**Comment by mimugmail** [comment]
Yes, should be easy :)

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
