### ISSUE TITLE
net/wireguard: crashes without a public key

### ISSUE THREAD

**Issue by alfrisch** [opnsense/plugins#1850]
**Describe the bug**
WireGuard crashes and doesn't start anymore when you add a peer without a public key.
Running `wireguard-go wg0` on the command line eventually revealed the problem in the wg0.config.

**To Reproduce**
1. Set up WireGuard
2. Create a WireGuard peer -> leave the Public Key empty
3. Add the peer to the configured WireGuard instance
4. Save -> WireGuard seems to crash and will not start anymore until you remove the "empty" peer

**Expected behavior**
If an empty key causes wireguard-go to crash then the UI should not allow empty keys.

**Comment by x-jokay** [comment]
Seems to be a dub of https://github.com/opnsense/plugins/issues/1688.

**Comment by chadek** [comment]
We may open a new issue but it is almost the same issue as this one: wireguard will still crash if you put a wrong formatted public key. Here is the fix https://github.com/opnsense/plugins/pull/2056 It may be include to https://github.com/opnsense/plugins/pull/1852

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.

**Comment by jeffg2k** [comment]
PR request was added for this issue https://github.com/opnsense/plugins/pull/2174
