### ISSUE TITLE
net/frr: Prefix List Description

### ISSUE THREAD

**Issue by TekunoKage** [opnsense/plugins#1858]
Could be add a field for prefix description? This field didn't need to be parsed on the config of FRR, just to have a reference why that prefix has been add, and descriptive name should later on could be referenced. This is very useful when prefix are add during migration periods and latter should be removed.  

I would like a input field to type a description, and the description typed will be display on the Prefix List Table.

On the case that the description want to be add to the FRR configuration, the command will be something like:
`ip prefix-list <Prefix_List_Name> description <Description_Text>`

I really enjoy your plugging for OpnSense! **Thanks for your effort.**

Regards,

**Comment by mimugmail** [comment]
Do you want the description field displayed in the overview? I can imagine that this would be nice if you handle lots of prefixes, route-maps, neigbors.

**Comment by TekunoKage** [comment]
An overview sound great!

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
