### ISSUE TITLE
net/frr/bgp: Neighbor Description

### ISSUE THREAD

**Issue by TekunoKage** [opnsense/plugins#1860]
Could be add a field for BGP Neighbor description? This field didn't need to be parsed on the config of FRR, just to have a reference how is the peering device and descriptive comment, that should later on could be referenced. This is very useful to remember the peering device.

I would like a input field to type a description, and the description typed will be display on the Route Map List Table.

On the case that the description want to be add to the FRR configuration, the command will be something like:

```
router bgp
neighbor <neighbor_IP> description <Description_Text>
```

Example:

```
router bgp
neighbor 192.0.2.1 description VIQZ1-OpnSense-02
```
I really enjoy your plugging for OpnSense! **Thanks for your effort.**

Regards,

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/plugins/pull/2054

**Comment by TekunoKage** [comment]
Thanks a Lot!!!
