### ISSUE TITLE
net/frr/bgp: Aggregate Routes

### ISSUE THREAD

**Issue by TekunoKage** [opnsense/plugins#1861]
Could be add a field for aggregate routes? In its simples form could be just similar to network on the BGP General Tab. On a better improved approach could have it's own tab to define the different aggregate segment and their attributes. 

Simplest implementation: 
BGP/General/Aggregate Routes field (similar to Network); that should generate the command line:
`aggregate-address A.B.C.D/M`

Example:
```
router bgp 64496
 address-family ipv4 unicast
  aggregate-address 198.51.100.0/24
```

A more detailed implementation could be:

BGP/Aggregate Routes/ and from there each aggregate address should have the attribute options of: route-map, origin<egp|igp|incomplete>, as-set, summary-only.

GUI Example idea:
```
<form>
  <label for="AggRT">Aggregate Route:</label>
  <input type="text" id="AggRT" name="AggRT"><br><br>
  <label for="RT_SummOnly"> Aggregate Route Summary Only: </label>
  <input type="checkbox" name="RT_SummOnly" value="summary-only"><br><br>
  <label for="RT_MAP">Route Map:</label>
  <input type="text" id="RT_MAP" name="RT_MAP"><br><br>
  <label for="RT_Origin">Route Origin:</label>
	  <select id="RT_Origin" name="RT_Origin" size="1">
	    <option value="">None</option>
	    <option value="origin incomplete">incomplete</option>
	    <option value="origin igp">igp</option>
	    <option value="origin egp">egp</option>
	  </select><br><br>
	<label for="RT_as-set">Route as-set:</label>
	  <select id="RT_as-set" name="RT_as-set" size="1">
	    <option value="">None</option>
	    <option value="as-set">as-set</option>
	  </select><br>
</form>
```
Example:

```
router bgp 64496
 address-family ipv4 unicast
  aggregate-address 192.0.2.0/24 as-set
  aggregate-address 198.51.100.0/24 summary-only
  aggregate-address 203.0.113.0/25 origin incomplete
  aggregate-address 203.0.113.128/25 route-map aggr-rmap
```

**Thanks!**

Regards,

**Comment by mimugmail** [comment]
The problem here is, if you add it the easy way, no fun to enhance it. I don't use this feature for myself so I can't say if it's worth the work of add the complex way

**Comment by TekunoKage** [comment]
> The problem here is, if you add it the easy way, no fun to enhance it. I don't use this feature for myself so I can't say if it's worth the work of add the complex way

LOL; I like your way of think... I suggest the different option to may be allow the option to do it on phases...

Regarding the use. Let me do an example use case.

An University System with multiple Campus where different location are connected throw an internal network (most universities use public IP address), but all them share a Internet Gateway location with a OpenSense Cluster with multiple Internet providers. The only command necessary will be use the aggregate route and that will generate the summary route as soon it receive any route on that segment. That will simplify the operation because each campus could announce their segments on their internal network and that would be expose to the Internet through the aggregate announcement.

Regards

**Comment by mimugmail** [comment]
Ok, so do you need it implemented like in example 1 or 2?

**Comment by TekunoKage** [comment]
Example #2 is the most preferable.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
