### ISSUE TITLE
 net/wireguard: Dashboard widget

### ISSUE THREAD

**Issue by x-jokay** [opnsense/plugins#1862]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
It would be great to have a Dashboard widget for WireGuard connections (similar to the existing widget for OpenVPN) :wink:

**Describe alternatives you've considered**
None.

**Comment by mimugmail** [comment]
I have no plans but if anyone wants to jump in I'm happy to help

**Comment by x-jokay** [comment]
@AdSchellevis isn't this supposed to go in the [opnsense/core](https://github.com/opnsense/core/tree/master/src/www/widgets/widgets) repo?

**Comment by AdSchellevis** [comment]
no, wireguard is a plugin.

**Comment by x-jokay** [comment]
Basic dashboard widget implemented.
