### ISSUE TITLE
net/wireguard: No longer working os-zabbix4-proxy connection from remote site

### ISSUE THREAD

**Issue by x-jokay** [opnsense/plugins#1863]
**Describe the bug**
* On a site-to-site **OpenVPN** the **os-zabbix4-proxy** can connect to the zabbix server.
* On a site-to-site **WireGuard** the **os-zabbix4-proxy** can no longer connect to the zabbix server.
* No config changes on the **os-zabbix4-proxy** (tried with **hostname** and **ip**).
* Rebooted, Firewall rules set to **allow all**, ping works fine.
* Direct connections without proxy work fine.

**To Reproduce**

1. Setup WireGuard Site-To-Site VPN
2. Setup zabbix server behind **firewall 1**
3. Setup **os-zabbix4-proxy** on **firewall 2**
4. Ping should work but **os-zabbix4-proxy** can't connect to zabbix server.  

**Expected behavior**

Connection to zabbix server using **os-zabbix4-proxy** should work, when using WireGuard Site-To-Site VPN.

**Relevant log files**

`/var/log/zabbix_proxy.log` on `firewall 2`.

```sh
43545:20200527:212942.563 Unable to connect to the server [192.168.1.10]:10051 [cannot connect to [[192.168.1.10]:10051]: [4] Interrupted system call]
 72862:20200527:213023.026 Still unable to connect...
 68269:20200527:213027.190 Still unable to connect...
 43545:20200527:213042.566 Unable to connect to the server [192.168.1.10]:10051 [cannot connect to [[192.168.1.10]:10051]: [4] Interrupted system call]
```

**Environment**

* OPNsense 20.1.7-amd64, LibreSSL 3.0.2
* os-zabbix4-proxy 1.2
* Zabbix server 4.0.20 (192.168.1.10)

**Configuration**

`firewall 1` (192.168.**1**.0/24)

```sh
interface: wg1
  public key: (hidden)
  private key: (hidden)
  listening port: 1234

peer: (hidden)
  preshared key: (hidden)
  endpoint: (hidden)
  allowed ips: 10.10.0.1/32, 192.168.2.0/24
  latest handshake: 1 minute, 45 seconds ago
  transfer: 269.00 MiB received, 733.72 MiB sent
```

`firewall 2` (192.168.**2**.0/24)

```sh
interface: wg1
  public key: (hidden)
  private key: (hidden)
  listening port: 1234

peer: (hidden)
  preshared key: (hidden)
  endpoint: (hidden)
  allowed ips: 10.10.0.1/32, 192.168.1.0/24
  latest handshake: 1 minute, 45 seconds ago
  transfer: 269.00 MiB received, 733.72 MiB sent
```

**Comment by mimugmail** [comment]
Have you checked If packets arrive at Firewall1 and if they leave WG interface on firewall2? Better to ask in the forums where a broader community is available

**Comment by x-jokay** [comment]
Ok, thx for the advice, will do :+1:
