### ISSUE TITLE
theme-rebellion: System / Access / Users improvement

### ISSUE THREAD

**Issue by x-jokay** [opnsense/plugins#1864]
**Is your feature request related to a problem? Please describe.**
When using the theme `rebellion` and going to the users overview (System / Access / Users) you can't barely distinguish between `disabled` and `normal` users.

![users-overview](https://user-images.githubusercontent.com/18613935/83068331-7cdb2100-a068-11ea-9d36-abc04e32e115.png)

**Describe the solution you'd like**
The icon color of the `disabled` users should be darker. 

**Describe alternatives you've considered**
Live with it :wink:

**Comment by marjohn56** [comment]
If I'm not much mistaken, this has already been fixed.

**Comment by x-jokay** [comment]
Thank you, I can confirm it :+1:
