### ISSUE TITLE
dns/bind - Enable zone forwarding in BIND plugin

### ISSUE THREAD

**Issue by zesu2154** [opnsense/plugins#1867]
I would like to suggest to enable zone forwarding in the BIND plugin

Looking at the Bind documentation and the plugin, I think the addition should be relatively simple. (This observation obviously is from someone who stand on the side, so please forgive me if that is not the case.  :) )

That should be doable by adding the option for "Forward" zone and also a field for list of Forwarders, and obviously the appropirate logic to generate the forward zone in the Bind config file.

This allows me to be able to easily do local zone or overrides without Unbound, and one less software to worry about.

**Describe alternatives you've considered**
If it is not enabled, then the obvious choice is to continue using Unbound to do conditional forwarding/overrides

Regards

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.

**Comment by 0dragosh** [comment]
Any news on this?
