### ISSUE TITLE
net/wireguard: Generate QR-Code with qrencode?

### ISSUE THREAD

**Issue by white-rabbit07** [opnsense/plugins#1868]
Hi. I used this tutorial to play with wireguard (installation on OPNSense):
https://emanuelduss.ch/2018/09/wireguard-vpn-road-warrior-setup/
Under "Mobile Client Usage" there's a command "qrencode -t ansiutf8 < client-mobile_splittunnel.conf" that generates a QR-Code; ready to import on a mobile device. Very easy and very cool! Are there plans to show this qr-code directly in the OPNSense-Webinterface? It would be a nice feature ...

The second question is: In the section "endpoints" it's possible to "edit, copy, delete" but not to download the configuration-files for a user. Is there a plan to integrate a download-Button as well?
Thanks.

**Comment by fabianfrz** [comment]
Just a short response for @mimugmail:

rendering QR-Codes in OPNsense is already possible. There is a jQuery plugin in the frontend which is used for 2FA: 

https://github.com/opnsense/core/blob/master/src/www/system_usermanager.php#L930-L950

if @mimugmail wants to, he can create the config file (maybe via backend API) and use the existing QR code rendering lib to render it.

**Comment by mimugmail** [comment]
Due to Corona my time is very limited and currently I'm working on different projects. I don't plan any new features this year, but if anyone else wants to jump in I'm happy to help/test.

**Comment by EneOli** [comment]
I looked into the plugin code and it shouldn't be that hard to implement it. I also tried to implement this feature, but the opnsense_bootgrid_plugin.js that is responsible for rendering the table seems to be very limited. Is there an option to add a custom command or a custom cell with own html to it?

**Comment by EneOli** [comment]
I did a mistake. Generating the client config in opnsense is impossible because of the missing client private key. 
Generating the server config is useless, because it is already applied in opnsense.
The only option is to also generate client keys in the server and store them temporarily while creating the client config. But I don't think that's a good solution. Maybe asking for the key in the ui before generating the config is an option?

**Comment by mimugmail** [comment]
I think the only way it makes sense is when OPN also handles client keys, but this would break most of the open-ness of the system.

**Comment by white-rabbit07** [comment]
... and if it's optional: Let the admin of the firewall **decide** if the client private keys are stored on the firewall -- or not?

**Comment by pkejval** [comment]
But WG client can generate its private key from given public key in config, isn't it? There's no need to store clients private keys on the firewall. I am pretty sure that I saw this implemented in OpenWRT and DD-WRT.

**Comment by mimugmail** [comment]
It doesnt make sense to store private keys from client locally. Azire or Mullvad only does this to ease the rollout process. This wont happen ...

**Comment by ChristianUlbrich** [comment]
The twist is, the keys would not needed to be stored; but the frontend could generate them _locally_. Basically it would involve integrating something like https://www.wireguardconfig.com/ into the plugin.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.

**Comment by gbakeman** [comment]
Just want to throw my support behind this. Client setup would be much less painful if the opnsense frontend could generate codes/config for us to distribute to our clients.

**Comment by cwmoriarty** [comment]
+1 for this

**Comment by HNGamingUK** [comment]
Fully aware that this thread is closed but the ability to export config and have a QR code provides that extra level of ease of use. Sure it isn't as secure since the client private key isn't on the client, but it could be an optional thing so the owner can decide.

**Comment by kquinsland** [comment]
> Sure it isn't as secure since the client private key isn't on the client, but it could be an optional thing so the owner can decide.

Or even just a simple "template" QR code which facilitates entering some of the data.  Encode the "fixed" and "template" data into the QR code just to save some time on mobile setup.

E.G.: A qr code with the server/peer information: `vpn.my-domain.net:1234` as this information is fixed/static and in place of "real" keys, a simple string could be used "REPLACE_ME_ON_CLIENT" or similar.

**Comment by Shurov** [comment]
Also vouching for this! (and bumping the thread)

**Comment by hwcltjn** [comment]
+1, would be great!

**Comment by Goeste** [comment]
Personally I take security and privacy very serious. However, I want to also have easy access to my configs. it's a pain to setup my wife's phone with several whatsapp messages, or the like a QR-code would make it a lot easier for such setups.

Unfortunately, I am not a dev nor programmer at al (just hack and paste code snippets) so I cannot support and even if i found a solutions that works for me, it would be to risky to make it public because i cannot give support.

@mimugmail your decision is still solid as a rock on not integrating qr-enc or similar?!

**Comment by Crimsonize** [comment]
+1, this would be really nice

**Comment by Tragen** [comment]
@AdSchellevis could you reopen this issue or should we create a new one?

**Comment by AdSchellevis** [comment]
@Tragen just open a pull request if you're planning to work on a feature.re-opening tickets only makes sense if it's on someones radar to do the actual work....

**Comment by Tragen** [comment]
@tamaskan 
Wow nice.
It took me a while to reformat everything so I could see the differences.
I haven't tested it with a real client, but I can click on the button to create the QR code.
There is one problem so far. When I create the qr code, and I click the button again, the previous qr isn't removed.
I get more and more qr codes.

**Comment by Goeste** [comment]
That is awesome!

May I add an idea:

> Once the QR code is generated, and later deleted, when pressing the qrcode button again, a new pair of keays is also generated and updated in the peer details

Or is it rather nonsense?!

Best, goeste

**Comment by bernardgut** [comment]
Yeah QR code generation in the interface is a must

**Comment by fichtner** [comment]
For an open source project where nobody commits to it? Reality says it’s not a must. ;)

**Comment by Goeste** [comment]
now available as "Peer Generator" in v24.1.5

**Comment by bernardgut** [comment]
@Goeste  nice. Any chance for this to be available in the business version ? *v23.10.XXX

**Comment by AdSchellevis** [comment]
@bernardgut 24.4 was released yesterday including the QR codes for wireguard

**Comment by bernardgut** [comment]
all right got it thanks
