### ISSUE TITLE
Quagga: Error when redistributing more than one source

### ISSUE THREAD

**Issue by mimugmail** [opnsense/plugins#187]
@fabianfrz I tried to redistribute multiple sources but I always get a:

![image](https://user-images.githubusercontent.com/20438689/27378181-5f62fb22-5677-11e7-8ba4-122d71a27a49.png)

No matter which values I choose, it's only when theres mor than one.

Do you have any clue? 

Thanks

**Comment by fabianfrz** [comment]
this looks like there has been a character sent, which is not a valid option of the list. Is a wrong character in the list? Maybe a special char?

**Comment by mimugmail** [comment]
It's picked from here:

https://github.com/opnsense/plugins/blob/master/net/quagga/src/opnsense/mvc/app/models/OPNsense/Quagga/OSPF.xml#L25-L37

The problem is, I can select every entry if I only select one. But when a second one is added I get the error

**Comment by mimugmail** [comment]
@fabianfrz When I change the FieldType to CSV and type in e.g. kernel and static manually it works. 
I'm not sure if OptionField really allows/accpets <Multiple>Y</Multiple>?

**Comment by fabianfrz** [comment]
@mimugmail If it fixes the issue, you can create a pull request and I will merge it.

**Comment by mimugmail** [comment]
Ok, can I add it to #186 ? But what happens to existing installations when the field type in the model changes?

**Comment by fabianfrz** [comment]
@mimugmail If they are compatible, nothing happens but if they are not, the validation will fail so the user has to change it. In such a case a migration needs to be created.

**Comment by mimugmail** [comment]
@fabianfrz Since the values wont change this should be fine. 
Can I rename #186 and add the change for BGP and OSPF to it (perhaps also RIP)?

**Comment by fabianfrz** [comment]
Yes, you should be able to rename it (click edit right of the title)

**Comment by mimugmail** [comment]
@fabianfrz This one fixes the issue, so no change is needed:

https://github.com/opnsense/core/commit/ac75ef6f10665b495f4d7503dc05dc804d63a061
