### ISSUE TITLE
acme-client: Security concerns regarding DNS-01 challenge

### ISSUE THREAD

**Issue by Alphaprot** [opnsense/plugins#1873]
**Important notices**
Our forum is located at https://forum.opnsense.org , please consider joining discussions there in stead of using GitHub for these matters.

Before you ask a new question, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

---
Hey  there - first of all thank you for creating the acme-client plugin.
However, this might encourage people to simply "secure" their network by using the DNS-01-challenge without further security meassurements.

See Joona's blog entry on the EFF [here](https://www.eff.org/deeplinks/2018/02/technical-deep-dive-securing-automation-acme-dns-challenge-validation), where he shows some ways to counteract the possibility of third parties gaining access to your zone file.

His main argument is: most DNS-provider's API-keys are global keys (and even if they only allow one to alter DNS-settings, they often still allow that person to alter ALL DNS-settings) - and storing them on an internet facing device might result in that device being more lucrative to hack (in order to get the API-key). 

This is a HardenedBSD device, I know - but at least awareness of that possible security risk should be raised, shouldn't it?

**Comment by fraenki** [comment]
I agree that it is always important to be aware of possible security issues.

Howver, in this particular case the security issue is unrelated to the ACME plugin and OPNsense/HardenedBSD. People need to protect their DNS servers and APIs. But the ACME plugin does just _utilize_ a possibly insecure DNS service, so I don't see the point of raising awareness here. In my opinion this is simply the wrong place. The affected DNS provider/software should raise awareness of this issue, IMHO.

That's just my opinion as the current maintainer of the ACME plugin, it's **not** an official statement for OPNsense or even HardenedBSD.
