### ISSUE TITLE
Postfix restart when certificate is updated by Lets Encrypt

### ISSUE THREAD

**Issue by OleSta** [opnsense/plugins#1874]
Using Postfix/Rspamd/redis/clamav as mail gateway with a Lets Encrypt certificate for Postfix.

Need a hook to restart Postfix when acme client renew the Lets Encrypt certificate.

**Comment by fraenki** [comment]
@mimugmail, could you add a description to the restart command? This would expose it to Let's Encrypt Automations (see https://github.com/opnsense/core/pull/3755).
