### ISSUE TITLE
Zerotier LInk dies after some hours 

### ISSUE THREAD

**Issue by jstrebel** [opnsense/plugins#1876]
Hi, I installed ZT successfully on OPNsense. In Myzerotier I see OPNsense has joined the Network. After some hours OPNsense / Zerotier disconnects from Myzerotier. I can't bring up the ZT link via the GUI of OPNsense. (tried under VPN and under the dashbord) with a chance less than 50% I can successfull reconnect by CLI doing a join network. If this fails then I need to restart OPNsense. Then I can rejoin via CLI. Please let me know how I can provide you with better info to track the problem. Jakob

**Comment by jstrebel** [comment]
@AdSchellevis, My apology to disturb you. Anything else I can do to help finding what causes the problem?
Jakob

**Comment by AdSchellevis** [comment]
@jstrebel I'm not working on this, it's a community support case, maybe someone else wants to step in.

**Comment by mimugmail** [comment]
@darkain sorry to mention you, maybe you have an idea as you use ZT too?

**Comment by darkain** [comment]
I've not seen this particular issue.

OPNsense uses ZeroTier pretty much unmodified, with just issuing a few basic commands to the local api/cli to connect to networks and retrieve status.

I'd personally try going to the OPNsense cli and checking the output of the following commands. 

- **zerotier-cli status**
- **zerotier-cli listnetworks**
- **zerotier-cli listpeers**

Additionally for OPNsense specifically, try opening TCP and UDP port 9993 on both IPv4 and IPv6 on the WAN firewall. ZT is a peer-to-peer networking system, sometimes it will initiate the connection to other peers, sometimes those other peers will initiate the connection to OPNsense. 

Also from the OPNsense UI, you can try adding the following to the **local.conf settings** section
`{"settings": {"primaryPort":9993, "allowSecondaryPort":false}}`

**Comment by jstrebel** [comment]
@darkain @mimugmail Thank you for your responses. I have tried all the Zerotier-cli command successfully. I see the OPNsense Zerotier client in the myzerotier Status for a while. As I mention in my first posting. BTW: If I put a Raspberry as a ZT client in my Network this client stays on for ever.

**Comment by darkain** [comment]
_"I have tried all the Zerotier-cli command successfully."_

What does this success look like? Specifically the **listpeers** command, ran multiple times, will show how the physical links are being made between ZT nodes.

And again, things such as the firewall and TCP/UDP port settings are important here. The Raspberry Pi OS doesn't have a port restricting firewall by default, whereas OPNsense does. This is certainly worth looking into.

**Comment by Tennyleaz** [comment]
I have this issue too. Zerotier dies after a few hours.
Using zerotier-cli shows offline:

```
root@OPNsense:~ # zerotier-cli info
200 info 1f807cxxxx 1.4.6 OFFLINE
root@OPNsense:~ # zerotier-cli listnetworks
200 listnetworks <nwid> <name> <mac> <status> <type> <dev> <ZT assigned ips>
200 listnetworks 9bee8941xxxxxxxx My_Network 8a:e0:58:c9:29:2c OK PRIVATE zt9nrk986qthvs8 <ipv6-address>/88,<ipv4-address>/16

```

Have to restart opnsense. Any methods to restart zerotier only?

Similar issue on opnsense forum: [Zerotier stops intermittend (unstable) (20.1.7)](https://forum.opnsense.org/index.php?topic=17502.0)

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.

**Comment by xvisionbelgium** [comment]
Got the same issue.... connectivity gone after 2h... 
But it comes back after 30 minutes or by cycling the Zerotier service in the GUI
