### ISSUE TITLE
Increase BGP functionality

### ISSUE THREAD

**Issue by alexharvard** [opnsense/plugins#1877]
I've switched from pfsense to opnsense and got opnsense be my favourite Router/Firewall before pfsense and also vyos.
Pfsense has a ton of BGP options in the GUI while opnsense lacks of many options without which i've to edit my FRR config manually.
Are there plans to increase bgp functions in the GUI?

**Comment by TekunoKage** [comment]
@alexharvard I agree with you that opnsense could improve on the FRR plugin. Don't get me wrong, I guest they are doing well, but their is opportunity to improve.
The way I'm training to assist, like you did is opening issues, but I try to be more concise, requesting the exact feature that I'm not seen available and I'm interested. That way will be easier to additional people comment to increment the importance and also will be easier to keep track when is available or any progress. 

If your review the cases related to frr, most of them you will notice on the subject that start with net/frr.

Regards,

**Comment by mimugmail** [comment]
@alexharvard can you sum them up so I can work in it? I don't use pfsense, but I know OPN has more options than Sophos :)

**Comment by marcquark** [comment]
@mimugmail being able to adjust BGP timers (connect, keepalive, hold) would be a big one for sure, and i guess it's fairly simple to implement. the defaults are pretty conservative

**Comment by marcquark** [comment]
also a neighbor view ("show ip bgp neighbor") at least as an API endpoint i.e. /quagga/diagnostics/showipbgpneighbors would be awesome

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
