### ISSUE TITLE
FRR/Quagga Module Bug

### ISSUE THREAD

**Issue by alexharvard** [opnsense/plugins#1878]
It seems that inside the Routing -> BGPv4 Module there is a potential bug.
When checking the checkboxes Next Hop Self, Multi Hop or Default Originate inside the Neighbors tab it consistently only changes the Neighbor Enabled state but not the state of the clicked checkbox.
Inside "Edit Neighbor" the boxes work as intended.

**Comment by alexharvard** [comment]
In the mean time i've been able to reproduce this issue with the latest opnsense from the iso and also with the latest updates on version v.20.1.7 on two different machines and different browsers (Chrome and Firefox)
os-frr version is 1.14
![grafik](https://user-images.githubusercontent.com/66095010/83981171-d589a400-a91b-11ea-8550-994bf1512a89.png)

**Comment by mimugmail** [comment]
Indeed, this only works in grid edit view. Maybe it's better to remove the columns from the overview in favor of a description text asked in another issue.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
