### ISSUE TITLE
Upgrade frr version

### ISSUE THREAD

**Issue by alexharvard** [opnsense/plugins#1879]
Since the used frr version 6.0.2 was released on 9 Jan 2019 it would be great to upgrade this to some kind of newer version.
FRR 7.x has especially lots of BGPd and other bugs fixed which would make BGP on Opnsense more interesting i guess.

**Comment by fichtner** [comment]
Please look for similar topics before posting and/or provide more relevant info. Dev version is already on FRR 7 for the upcoming release.

**Comment by 0906349604dreem** [comment]
2563-06-08 4:11 GMT+07:00, Franco Fichtner <notifications@github.com>:
