### ISSUE TITLE
dyndns Cloudflare API Token support (re-submission)

### ISSUE THREAD

**Issue by hockey6611** [opnsense/plugins#1885]
[-] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
Yes

[-] I have searched the existing issues and I'm convinced that mine is new.
Yes. Previously closed issue: #1477. Informed it was best to create new issue

[-] When the request is meant for an existing plugin, I've added its name to the title.
N/A

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Cloudflare has announced general availability of their API tokens supporting the principle of least privilege. It would be great if this functionality could be added to OPNsense. This would allow more secure access to the API without exposing the whole Cloudflare account.

https://blog.cloudflare.com/api-tokens-general-availability/

**Describe alternatives you've considered**
N/A

**Additional context**
API token support was added to ACME plugin, it should be added for dynDNS as well.

**Comment by andreas-rupper** [comment]
Already done, awaiting merge
#1726

**Comment by hockey6611** [comment]
Thank you for noting that, and commenting on the original issue. Hopefully it will be re-reviewed and merged soon.

@AdSchellevis and @fichtner please take note of this associated pull request by @andreas-rupper: #1726 

Thank you all for the consideration of this feature!

**Comment by AdSchellevis** [comment]
@hockey6611 just did, it needs some style changes before merge, but shouldn’t be too much work for @andreas-rupper to fix (together with the feedback earlier provided by @fichtner). Although we allow changes/additions on the dyndns plugin, it's rather old and would need a rewrite eventually, which isn't on the todo list for our core team.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
