### ISSUE TITLE
Nginx-plus support in plugins

### ISSUE THREAD

**Issue by scomoletti** [opnsense/plugins#1889]
Would love to see support for Nginx-plus in the plugins. Based on https://cs.nginx.com/repo_setup the only significant difference during install is the addition of the package config for the official nginx-plus repo and the customer cert/key to go with it. Guessing the keys could be imported via the web ui and just alter the path to them in the conf file. The other package requirements are already a part of the base opnsense install. The existing forms should all work as is without change as a starting point.

To go along with that, and the real reason I want this, would be the additional menu options for using openid connect for sso support - https://docs.nginx.com/nginx/deployment-guides/single-sign-on/. 
This part is a bit more complicated depending on the specific idp used since they each have some specific code aside from the base openid connect support. It also would require expanding the server and location forms to include setting vars for things like headers, access/error logs, proxy settings and more. 

While I haven't touched php in 20? years I can help out with testing and more specific requirements. I have access to a paid nginx-plus, onelogin through Sept 2020, and Okta in about a month. I could probably swing Amazon Cognito with a little time as well.

**Comment by mimugmail** [comment]
Doesnt N+ only offers precompiled binarys for linux?

**Comment by scomoletti** [comment]
Check https://cs.nginx.com/repo_setup. FreeBSD 11.3+ and 12.1+ are available as the only non-linux packages.

**Comment by fichtner** [comment]
This won’t fly very well, we still use 11.2 and do not intend to provide binary blobs.

**Comment by scomoletti** [comment]
something to track for when the base is upgraded to 11.3+ or 12?

**Comment by AdSchellevis** [comment]
@scomoletti as mentioned by @fichtner we're not planning to include binary blobs, so highly likely this won't happen.

**Comment by scomoletti** [comment]
Maybe I'm missing something but you wouldnt have to include any binary blobs.. just the config for their repo, a few js files, and the associated config templates.

**Comment by mimugmail** [comment]
But they will only maintain for latest stable, when 20.7 with 12.1 will be released, FreeBSD will push to 12.2 couple of weeks later and you may run into trouble with external repo's.
You probably can fetch the binary manually and install via pkg, this won't break your system if you lock nginx

**Comment by scomoletti** [comment]
Thanks for that answer. With respect to release cycles and supported versions I agree this is more difficult that I thought at first glance. Less a technical more a support problem. 

I do have some contacts at Nginx/F5.. I may chase them down and then look at opnsense professional services for this if we can get some clarification on supported versions from Nginx. I'm betting it works on a larger range of FreeBSD versions than they list but 'officially supported' vs 'it works' are different things I know. 

Thanks all for the input.

**Comment by fichtner** [comment]
Not revoking the previously existing binaries and/or providing builds longer would indeed be a start. A lot of vendors use older FreeBSD releases longer than what FreeBSD itself offers so these would get a chance to integrate.... might even be a business opportunity for Nguni and such vendors down the road.

**Comment by fabianfrz** [comment]
I will just add a comment here for maintainance: they have a private repository for the commercial version so we cannot easily include it. Even then it would only make real sense if we fork the open source nginx plugin and add the commercial features.
