### ISSUE TITLE
unbound-plus: uninstallation leaves active configuration data that conflicts with other plugins  

### ISSUE THREAD

**Issue by sja1440** [opnsense/plugins#1890]
[-] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[-] I have searched the existing issues and I'm convinced that mine is new.

[-] The title contains the plugin to which this issue belongs

**Describe the bug**
After uninstalling an unbound-plus that was configured for DNS-over-TLS (DOT), a populated configuration file is left active (dot.conf). The contents of dot.conf cannot be viewed or removed through the OPNsense GUI. The contents of dot.conf are incompatible with other OPNsense plugs (e.g. DNSCrypt-Proxy) and prevent unbound from being started.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install os-unbound-plus
2. Configure os-unbound-plus and Unbound for DNS over TLS (DOT). Verify that it works 
3. Uninstall os-unbound-plus using the OPNsense GUI
4. Install DNSCrypt-Proxy using the OPNsense GUI
5. Configure DNSCrypt-Proxy and Unbound for DNS-over-HTTPS.
6. Unbound fails to start
7. Verify that using the OPNsense GUI there is no way to view or remove the contents of the previous DOT configuration 
8. ssh to OPNsense machine
9. Delete the file /var/unbound/etc/dot.conf
10. Restart successfully Unbound and verify that DOH works.

**Expected behavior**
During uninstallation, unbound-plus must ensure that none of its old configuration data can impact any active component of OPNsense.

**Environment**
os-unbound-plus 1.1_1
OPNsense 20.1.7-amd64
FreeBSD 11.2-RELEASE-p20-HBSD
OpenSSL 1.1.1g 21 Apr 2020

**Comment by mimugmail** [comment]
You can install unbound-plus again and disable all settings, after this you can uninstall again.
I don't think it's worth the work since this plugin may move to core with 20.7

**Comment by sja1440** [comment]
Thanks for the response. I agree that it is not worth it since according to the [roadmap](https://opnsense.org/about/road-map/), the integration into 20.7 seems already completed.
