### ISSUE TITLE
telegraf allow inputs.exec or custom entries

### ISSUE THREAD

**Issue by pyrodex** [opnsense/plugins#1896]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It would be nice to find a way to either support guided entry into the telegraf configuration file for inputs.exec options and 3rd party scripts or a custom Advanced configuration box to input additional configuration items into the configuration file.

**Describe alternatives you've considered**
Today I can edit the file by hand and insert what is required then restart the daemon. However these custom settings are wiped out when I add something through the UI for telegraf in the proper setting.

**Additional context**
I am trying to capture additional data above the standard inputs supported today such as CPU temperature and other things in the future so I use the following additional lines to achieve this function.

`
[[inputs.exec]]
   commands = [
     "/root/telegraf_temperature.sh"
   ]
   data_format = "influx"
`

**Comment by fichtner** [comment]
In general, we don’t aim to provide execution hooks from configuration. We do however offer file system based plugin capabilities so we could add an include statement for further configuration if Telegraf supports it.
