### ISSUE TITLE
Netdata plugin cannot listen on IPv6 address

### ISSUE THREAD

**Issue by imp1sh** [opnsense/plugins#1906]
Netdata plugin cannot listen on IPv6. This is the error message in /var/log/messages:

```
Jul  2 19:37:25 uprouter1 kernel: -> pid: 65028 ppid: 1 p_pax: 0xa50<SEGVGUARD,ASLR,NOSHLIBRANDOM,NODISALLOWMAP32BIT> 
Jul  2 19:37:25 uprouter1 netdata: LISTENER: getaddrinfo('2001', 'a0a0:f2f2f2:5000::1ae0'): servname not supported for ai_socktype 
Jul  2 19:37:25 uprouter1 netdata: LISTENER: Cannot listen on any API socket. Exiting... 

```

1. Install netdata plugin
2. Goto Services - Netdata - General
3. Input IPv6 address in 'Listen Address'
4. Service won't start, see log error above.

OPNsense 20.1.7-amd64
PC-Engines APU4C4

**Comment by mimugmail** [comment]
Did you use the correct syntax? Error looks strange

**Comment by imp1sh** [comment]
The Synatx of the IP I entered was like this:
`2001:a0a0:f2f2f2:5000::1ae0`

**Comment by mimugmail** [comment]
Please reopen and assign me
