### ISSUE TITLE
net/haproxy: Add support for header field names

### ISSUE THREAD

**Issue by patan32** [opnsense/plugins#1907]
Hello,

I need bit of help with haproxy config through GUI. I am using Opnsense and i can't edit the config file manually. 
I need to setup a socket for my website. I found this config but i am not able to get it going from the GUI. 

The socket config for haproxy:
How can i accomplish this from the GUI? 

```
  acl unms_ws hdr_beg(Host) -i ws.
  ## UNMS Websocket routing based on websocket protocol header
  acl unms_connection_upgrade hdr(Connection) -i upgrade
  acl unms_upgrade_websocket hdr(Upgrade) -i websocket
```

Thanks for all the help. :)

```
#################
### FRONTEND ###
#################
frontend public
  bind *:80
  bind *:443 ssl crt /etc/haproxy/certs/

  # Optional : Allowed sources IP for additional security
  acl allowed_ip src 10.0.0.0/24
  ## https://www.haproxy.com/fr/blog/websockets-load-balancing-with-haproxy/
  ## UNMS Websocketrouting based on Host header
  acl unms_ws hdr_beg(Host) -i ws.
  ## UNMS Websocket routing based on websocket protocol header
  acl unms_connection_upgrade hdr(Connection) -i upgrade
  acl unms_upgrade_websocket hdr(Upgrade) -i websocket

  # Let's Encrypt
  acl acl_letsencrypt path_beg /.well-known/acme-challenge/

  ## Secure headers https://blog.devcloud.hosting/securing-haproxy-and-nginx-via-http-headers-54020d460283
  http-response set-header Strict-Transport-Security max-age=15768000;includeSubDomains;preload
  http-response set-header X-XSS-Protection: 1;mode=block
  http-response set-header X-Content-Type-Options: nosniff
  http-response set-header Referrer-Policy no-referrer-when-downgrade
  http-response set-header X-Frame-Options SAMEORIGIN
  http-response del-header X-Powered-By
  http-response del-header Server
  http-response del-header X-Apache-Server-ID

  ## Force HTTPS
  http-request set-header X-Forwarded-Port %[dst_port]
  http-request add-header X-Forwarded-Proto https if { ssl_fc } !acl_letsencrypt
  http-request redirect scheme https code 301 if !{ ssl_fc } !acl_letsencrypt

  # UNMS
  use_backend unms if unms_ws allowed_ip
  use_backend unms if unms_connection_upgrade unms_upgrade_websocket allowed_ip

###############
### BACKEND ###
###############
backend letsencrypt
     server vm-haproxy localhost:8088
# UNMS # "ssl verify none" is mandatory as UNMS itself have use a ssl certificate backend unms      server vm-unms 192.168.10.13 ssl verify non
```

**Comment by patan32** [comment]
Any help from the team? Appreciate all you guys do.

**Comment by fraenki** [comment]
>  How can i accomplish this from the GUI?

Both directives `hdr` and `hdr_beg` currently only support checking for the host header. I'll add support for other checks in a future release (no ETA!).

**Comment by patan32** [comment]
Thanks for the response @fraenki. 

This is exactly what I am looking for. If you can add this feature I would be the happiest person. A lot of applications are using WebSockets nowadays and it causes issues with reverse proxy. 

https://www.haproxy.com/blog/websockets-load-balancing-with-haproxy/

I appreciate all the hard work you put in. 

Regards Ronald.

**Comment by fraenki** [comment]
This will be available in the upcoming os-haproxy version 3.0.

I was able to replicate the requested config using the new HTTP Header checks:

```
    # ACL: check websocket part I
    acl acl_602ef3f20faa20.88847816 hdr(Connection) -i upgrade
    # ACL: check websocket part II
    acl acl_602ef409043d60.43254543 hdr(Upgrade) -i websocket

    # ACTION: use backend for websocket
    use_backend websocket_backend if acl_602ef3f20faa20.88847816 acl_602ef409043d60.43254543
```

**Comment by patan32** [comment]
Hello,

I just tested the Haproxy with Websocket and it doesn't work. i have created the config as per your instruction. 

From HAproxy page:
"## routing based on websocket protocol header
  acl hdr_connection_upgrade hdr(Connection)  -i upgrade
  acl hdr_upgrade_websocket  hdr(Upgrade)     -i websocket"

Here is my exported config:
#
# Automatically generated configuration.
# Do not edit this file manually.
#

global
    uid                         80
    gid                         80
    chroot                      /var/haproxy
    daemon
    stats                       socket /var/run/haproxy.socket group proxy mode 775 level admin expose-fd listeners
    nbproc                      1
    nbthread                    1
    hard-stop-after             60s
    tune.ssl.default-dh-param   1024
    spread-checks               0
    tune.chksize                16384
    tune.bufsize                16384
    tune.lua.maxmem             0
    log                         /var/run/log local0 info
    lua-prepend-path            /tmp/haproxy/lua/?.lua
cache opnsense-haproxy-cache
    total-max-size 4
    max-age 60

defaults
    log     global
    option redispatch -1
    timeout client 30s
    timeout connect 30s
    timeout server 30s
    retries 3
    default-server init-addr last,libc

# autogenerated entries for ACLs


# autogenerated entries for config in backends/frontends

# autogenerated entries for stats




# Frontend: HTTP (Front End HTTP)
frontend HTTP
    bind 0.0.0.0:80 name 0.0.0.0:80 
    mode http
    option http-keep-alive
    option forwardfor
    # tuning options
    timeout client 30s

    # logging options
    # WARNING: pass through options below this line


# Frontend: HTTPS (Front End HTTPS)
frontend HTTPS
    http-response set-header Strict-Transport-Security "max-age=15768000; includeSubDomains; preload"
    bind 0.0.0.0:443 name 0.0.0.0:443 ssl no-sslv3 no-tlsv10 no-tls-tickets ciphers ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256 ciphersuites TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256 alpn h2,http/1.1 crt-list /tmp/haproxy/ssl/5e7eb6cd3ccad8.52678052.certlist 
    mode http
    option http-keep-alive
    option forwardfor
    # tuning options
    timeout client 30s

    # logging options
    # ACL: Emby_Webserver
    acl acl_5e811fc593d624.87923872 hdr(host) -i emby.noobstogeeks.com
    # ACL: Unifi_Protect_Websocket_1
    acl acl_61bfe65d4066b0.98106842 hdr(Connection) -i upgrade
    # ACL: Unifi_Protect_Websocket_2
    acl acl_61bfe67f211b51.96043088 hdr(Upgrade) -i websocket



    # ACTION: Emby_Webserver
    use_backend Emby_Webserver if acl_5e811fc593d624.87923872 !acl_61bfe65d4066b0.98106842 



# Backend: Emby_Webserver (Emby Web Server)
backend Emby_Webserver
    # health check: Health Check 443
    option ssl-hello-chk
    mode http
    balance source
    # stickiness
    stick-table type ip size 50k expire 30m  
    stick on src
    # tuning options
    timeout connect 30s
    timeout server 30s
    http-reuse safe
    server Emby_Webserver 10.10.40.18:8096 check inter 2s port 443 

I still get websocket error on my emby server. 
https://ibb.co/hy6WctM

Something is missing in Haproxy to support websocket connections. Please help.

**Comment by fraenki** [comment]
@patan32 Please don't crosspost.
