### ISSUE TITLE
Custom DynDNS: The TTL value needs to be a valid integer number

### ISSUE THREAD

**Issue by abplfab** [opnsense/plugins#1910]
**To Reproduce**
1. Go to 'Services: Dynamic DNS'
2. Click on 'Add'
3. Choose Service type 'Custom', Interface to monitor: WAN, Interface to send update from: WAN, Hostname: some.domain.ch, CURL Options: both checked, Update URL: https://dyn.xxx.ch/cgi/dyndns.cgi?hostname=[HOSTNAME].somedomain.ch&myip=%IP%
4. Click Save
5. See error "The TTL value needs to be a valid integer number"

**Environment**
OPNsense 20.1.8

**Comment by fichtner** [comment]
See https://github.com/opnsense/plugins/pull/1903 hotfix soon...
