### ISSUE TITLE
Firewall API returning PHP MVC error

### ISSUE THREAD

**Issue by camelusferus** [opnsense/plugins#1912]
**Description**
The usage of the firewall (plugin) api triggers an "Array to string conversion (errno=8)"

**To Reproduce**
1. Go to "System" - > "Access" > "Users" and get an API token a one user
2. Make a POST request to http(s)://[OPNSENSE-IP]/api/firewall/filter/addRule with the following content

```
{"rule":{"enabled":"1","sequence":"1","action":{"block":{"value":"Block","selected":1}},"quick":"1","interface":{"opt1":{"value":"/// InterfaceName ///","selected":1}},"direction":{"in":{"value":"In","selected":1}},"ipprotocol":{"inet":{"value":"IPv4","selected":1}},"protocol":{"any":{"value":"any","selected":1}},"source_net":"any","source_not":"0","source_port":"","destination_net":"1.2.3.0/24","destination_not":"0","destination_port":"","gateway":{"":{"value":"keiner","selected":1}},"log":"0","description":"Test rule from API"}}
```

**Shown behavior**
```
{"errorMessage":"Error at /usr/local/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/BaseField.php:334 - Array to string conversion (errno=8)","errorTitle":"An API exception occured"}% 
```

**Expected behavior**
Accepting the Request

**Environment**
OPNsense 20.1.7 (amd64, OpenSSL) with the firewall plugin.
virtualized with KVM a on Intel(R) Xeon(R) Silver 4114

**Comment by akong77** [comment]
I got same error when I use api to add naxsi rules
`curl -XPOST -d '{"naxsi_rule":{"description":"doc file upload","ruletype":{"main":{"value":"Main Rule","selected":1},"basic":{"value":"Basic Rule","selected":0}},"message":"doc file upload","identifier":"2500","url":"0","dollar_url":"","match_value":"\\.doc","match_type":{"id":{"value":"Blacklist","selected":1},"wl":{"value":"Whitelist","selected":0}},"negate":"0","score":"8","regex":"1","args":"0","headers":"0","dollar_args_var":"","dollar_body_var":"","dollar_headers_var":"","file_extension":"1","raw_body":"0","name":"0"}}' -H "Content-Type: application/json" -k -u "wbM3ElB7KFwEYN2W+1YvL/1TB8owp/Zy4xp0tcFd9hnJ9/Ixkb6Zy4DrXcjFVLjGgkuN6qlu0N0hLJFU":"Wq+9bq5D49oz3ol5aUdetwEwEtu2dsDoA5Y9ov9t0Xxlg+3oXDBkrC7DI9oDO1dhmkSTZv2wzJN5U9Bo"`

**Comment by AdSchellevis** [comment]
best try sing the supplied user interface first, if you can replicate the issue there it's easier to investigate, if you can't you can compare both requests for differences (just check the network traffic from our browser).

**Comment by akong77** [comment]
I use follow command to get already rules.

`curl -k -u "key":"secret" https://IP:8082/api/nginx/settings/getnaxsirule/7b7bacfe-ee9a-46e6-b5cd-00176a33f1e3`

I got follow content.

`{"naxsi_rule":{"description":"asp\/php\/jsp file upload","ruletype":{"main":{"value":"Main Rule","selected":1},"basic":{"value":"Basic Rule","selected":0}},"message":"asp\/php\/jsp file upload","identifier":"1500","url":"0","dollar_url":"","match_value":"\\.ph|\\.asp|\\.ht|\\.jsp","match_type":{"id":{"value":"Blacklist","selected":1},"wl":{"value":"Whitelist","selected":0}},"negate":"0","score":"8","regex":"1","args":"0","headers":"0","dollar_args_var":"","dollar_body_var":"","dollar_headers_var":"","file_extension":"1","raw_body":"0","name":"0"}}`

I copy this rules and edit some settings like description and identifier and message and match_value.Then I use follow command to add rules.

`curl -XPOST -d '{"naxsi_rule":{"description":"doc file upload","ruletype":{"main":{"value":"Main Rule","selected":1},"basic":{"value":"Basic Rule","selected":0}},"message":"doc file upload","identifier":"2500","url":"0","dollar_url":"","match_value":"\\.doc","match_type":{"id":{"value":"Blacklist","selected":1},"wl":{"value":"Whitelist","selected":0}},"negate":"0","score":"8","regex":"1","args":"0","headers":"0","dollar_args_var":"","dollar_body_var":"","dollar_headers_var":"","file_extension":"1","raw_body":"0","name":"0"}}' -H "Content-Type: application/json" -k -u "key":"secret" https://IP:8082/api/nginx/settings/addnaxsirule`

It's will get error message.Could I make a mistake something?

**Comment by mimugmail** [comment]
Hit F12 in browser, network tab, add a naxsi rule via browser and look at the correct syntax of your browser

**Comment by akong77** [comment]
OK,Thanks a lot

**Comment by LeXavLima** [comment]
I have the same problem. It seems that submitting an array is not possible. Can someone show an example on how to create this rule? The error appears as soon as I add the "interface" item.

```json
{
    "rule": {
        "enabled": "1",
        "sequence": "1",
        "description": "rule_description8",
        "source_net": "192.168.0.0/24",
        "protocol": "TCP",
        "destination_net": "10.0.0.0/24",
        
        "pass": {
            "value": "Pass",
            "selected": 1
        },
        "interface": {
            "opt2": {
                "value": "castintern",
                "selected": 0
            },
            "opt3": {
                "value": "castpublic",
                "selected": 1
            },
            "lan": {
                "value": "LAN",
                "selected": 0
            },
            "lo0": {
                "value": "Loopback",
                "selected": 0
            },
            "opt1": {
                "value": "OPT1",
                "selected": 0
            },
            "wan": {
                "value": "WAN",
                "selected": 0
            }
        }
    }
}
```json

**Comment by LeXavLima** [comment]
Found the correct and easy way:

```
{
    "rule": {
        "enabled": "1",
        "sequence": "1",
        "description": "rule_description8",
        "source_net": "192.168.161.23",
        "protocol": "any",
        "destination_net": "192.168.160.100",
        "interface": "opt1"
    }
}
```
