### ISSUE TITLE
DMIdecode - missing information

### ISSUE THREAD

**Issue by Taomyn** [opnsense/plugins#1920]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

[x] The title contains the plugin to which this issue belongs

**Describe the bug**
Brand new installation of OPNsense v20.1 on a new hardware build, restored config from old firewall. After installing the os-dmidecode plugin, the widget is missing a great deal of information.

**To Reproduce**
1. Install os-dmidecode
2. Visit lobby dashboard

**Expected behavior**
More than what is being shown

**Screenshots**
![image](https://user-images.githubusercontent.com/4365929/86958095-eec08300-c15b-11ea-8cfb-83218236b08c.png)

**Relevant log files**
Tell me where they are or how to generate logging from the plug-in and I will add it to the report.

**Additional context**
My previous hardware was an older Jetway SoC build, and it had only a little bit more showing, which is why after this new build I thought I would be report it. I appreciate that the information may not actually be there to obtain, but I'd like to know for sure, otherwise I'll just remove the plug-in.

**Environment**
Jetway JNF795T2-Q170 with i3-7100, 8GB RAM, 60GB SSD
OPNsense 20.1.8_1-amd64
FreeBSD 11.2-RELEASE-p20-HBSD
LibreSSL 3.0.2

**Comment by fichtner** [comment]
@Taomyn can you provide the output of these two:

    /usr/local/sbin/dmidecode -q -t system
    /usr/local/sbin/dmidecode -q -t bios


Cheers,
Franco

**Comment by Taomyn** [comment]
Here you go, I did obfuscate the UUID but the rest is from the commands:
```
root@bart:~ # /usr/local/sbin/dmidecode -q -t system
System Information
		Manufacturer: _
		Product Name: _
		Version: _
		Serial Number: _
		UUID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
		Wake-up Type: Power Switch
		SKU Number: _
		Family: _

System Configuration Options
		Option 1: _

System Boot Information
		Status: No errors detected


root@bart:~ # /usr/local/sbin/dmidecode -q -t bios
BIOS Information
		Vendor: American Megatrends Inc.
		Version: 5.12
		Release Date: 12/06/2019
		Address: 0xF0000
		Runtime Size: 64 kB
		ROM Size: 16 MB
		Characteristics:
				PCI is supported
				BIOS is upgradeable
				BIOS shadowing is allowed
				Boot from CD is supported
				Selectable boot is supported
				BIOS ROM is socketed
				EDD is supported
				5.25"/1.2 MB floppy services are supported (int 13h)
				Print screen service is supported (int 5h)
				8042 keyboard services are supported (int 9h)
				Serial services are supported (int 14h)
				Printer services are supported (int 17h)
				ACPI is supported
				USB legacy is supported
				BIOS boot specification is supported
				Targeted content distribution is supported
				UEFI is supported
		BIOS Revision: 5.12

BIOS Language Information
		Language Description Format: Long
		Installable Languages: 1
				en|US|iso8859-1
		Currently Installed Language: en|US|iso8859-1
		
```

**Comment by fichtner** [comment]
Looks like dmidecode can't gather any data on the platform. Can't do anything about this from a plugin level unless dmidecode needs to be started with a different command sequence or something?

**Comment by Taomyn** [comment]
I've sent an email to Jetway support to see if they can explain if it's on the BIOS side, will update here if I get a response
