### ISSUE TITLE
Blacklist also to include subdomains

### ISSUE THREAD

**Issue by msvendsen** [opnsense/plugins#1923]
Hi!

Migrating from old BIND configuration where my DNSBL worked like a charm, I found out that with Unbound Plus, it only worked half way.
Found out that the difference is that BIND was blacklisting also any subdomains (*.domain.tld) for each blacklist entry. Unbound Plus only blacklists explicitly domains listed in the blacklist.

You can argue which method is most correct - but blocking all subdomains worked very well for me as many advertisement servers are having random subdomains to prevent adblocking to work.

Is it somehow possible to also include *.domain.tld in the dnsbl.inc file? I tried to change the dnsbl.py script to write both a line with "domain.tld" and a line with "*.domaintld" - but for some reason it seems not to work properly.

THANKS! :)

**Comment by mimugmail** [comment]
@pkejval do you have an opinion on this?

**Comment by pkejval** [comment]
As **local-data** [documentation](https://nlnetlabs.nl/documentation/unbound/unbound.conf/) says:

> Configure  local data, which is served in reply to queries for it. The query has to match exactly unless you configure the local-zone  as  redirect.  If not matched exactly, the local-zone type determines further processing.

You need to create **local-zone** record for blocking subdomains. You can find that line commented in dnsbl.py as this PR https://github.com/opnsense/plugins/pull/1901

But I'm aware that this will cause false-positive of "good" domains too. Blocklists are meant to block listed domains only.

@mimugmail Do you think it will be good to make this configurable from UI? Switch between "block exact" and "block with subdomains"?

**Comment by msvendsen** [comment]
> You need to create **local-zone** record for blocking subdomains. You can find that line commented in dnsbl.py which also solves problem with this PR #1901

Great! Switching to the other line, just worked! To me it doesn't matter if Unbound replies 0.0.0.0 or NXDOMAIN :-)

> But I'm aware that this will cause false-positive of "good" domains too. Blocklists are meant to block listed domains only.
> 
> @mimugmail Do you think it will be good idea to make this configurable from UI? Switch between "block exact" and "block with subdomains"?

Correct, as I wrote - you can argue which one is most correct. Actually I think as it works now with local-data IS most correct, as the blacklists - as you also say - includes FQDN... but maybe would be nice with a check box "Include subdomains", or something like that.

THANKS!!
