### ISSUE TITLE
os-dnscrypt-proxy Feature Request: Allow selection of alternative DNS List Sources

### ISSUE THREAD

**Issue by KD7TKJ** [opnsense/plugins#1928]
By default, dnscrypt-proxy uses public resolvers; However, it does support others, ala https://github.com/DNSCrypt/dnscrypt-proxy/wiki/DNS-server-sources

Specifically, I am interested in OpenNIC, but one can imagine a use for the Parental Control servers or the Onion servers as well. 

The URL to the list and it's minisign signature belong under "Sources" in the .tocl file; I tried writing it manually and it works, but it gets overwritten frequently.

**Comment by mimugmail** [comment]
We have the Servers tab for this to put them in manually. :)

**Comment by KD7TKJ** [comment]
Fair, it can be done that way: Recurse by hand into the list, add each of the interesting servers twice, first on the Servers page to make OPNSense aware of it, and second on the General page to allow it to be used. These lists change infrequently, and each server is very reliable; I'm likely to have no problems.

The upstream software's documentation seems to suggest using the Lists though, and they certainly invest some effort maintaining the Lists so that they may be used; Further, only by using the curated and metadatad list can the automatic filtering work... which one might consider central to the point of the software.

**Comment by mimugmail** [comment]
Ans how do you import them in regular usage?

**Comment by KD7TKJ** [comment]
To use a list, add it to the `[sources]` section of your
`dnscrypt-proxy.toml` configuration file as follows, for the example of OpenNIC:

"""
    [sources.'opennic']
    urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/opennic.md', 'https://download.dnscrypt.info/resolvers-list/v3/opennic.md']
    minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
    cache_file = 'opennic.md'
"""

For the other examples, the minisign keys are in the aforementioned DNSCrypt GitHub.

I wonder if one might impliment this as a drop down menu on the Servers page; The 4 maintained list, and then a "Manual Servers" option that exposes the current functionality?
