### ISSUE TITLE
Request: smokeping plugin

### ISSUE THREAD

**Issue by djzort** [opnsense/plugins#1935]
The port is already present, it just needs a plugin and i a bit of a gui

https://github.com/opnsense/ports/tree/master/net-mgmt/smokeping

Simply having the whole config as a text box in the UI would be fine, although providing a UI driven config would be better for everyone.

**Comment by mimugmail** [comment]
I wrote an article ages ago when I was active on pfsense. I really love smokeping and it's part of my daily business at work, but it has many dependencies and I'm not sure if it's a good idea to put them all on a Firewall

**Comment by fichtner** [comment]
Most of the deps are perl-based. Probably not a show stopper as some of those are already in packages for other reasons.

**Comment by djzort** [comment]
Many / Most of the probes arent of much value. EchoPing, Fping, DNS and HTTP/S are where 99% of the value is.
