### ISSUE TITLE
Support Linode Cloud API in Let's Encrypt Plugin

### ISSUE THREAD

**Issue by jsgf** [opnsense/plugins#1939]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

[x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
The Let's Encrypt plugin supports "Linode API" as a way of doing DNS-01 validation. However, this is the old API
which Linode is migrating away from in favour of its "Cloud API" aka Linode API v4.

acme.sh supports this API with `--dns dns_linode_v4` option, so it's just a matter of setting up a suitable UI to
configure it.

**Describe the solution you'd like**

Extend Let's Encrypt plugin's UI to support Linode API v4.

**Describe alternatives you've considered**

Using the old Linode API. I'd prefer not to because it doesn't give enough access control.

**Additional context**

**Comment by fraenki** [comment]
@jsgf I've seen that you've already made the required changes in your private fork. Could you please submit a pull-request with your changes?

**Comment by jsgf** [comment]
@fraenki Yep, just working out how to test them first.

**Comment by fraenki** [comment]
@jsgf Thanks for your contribution!
