### ISSUE TITLE
Zabbix Agent not starting

### ISSUE THREAD

**Issue by timherrm** [opnsense/plugins#194]
Hi, 
I'm running

OPNsense 17.1.8-i386
FreeBSD 11.0-RELEASE-p10
OpenSSL 1.0.2l  25 May 2017

in a VM and want to use the zabbix agent (Zabbix 3.2.3 (revision 64610)).
Plugin Version is: os-zabbix-agent | 1.1

After setting "Hostname" and "Listen Port" and "Zabbix Servers" i have to enter "Listen IPs".
In this field the only aaccpted format is: 10.44.2.100:10050
but the  if i try to start the agent i get this error message:

48648:20170707:081114.098 listener | failed: cannot resolve address [[10.44.2.100:10050]:10050]: [8] hostname nor servname provided, or not known

Could you please help me with this problem?

**Comment by fraenki** [comment]
> OPNsense 17.1.8-i386 

This version shipped with os-zabbix-agent 1.0 that contained a bug (#178). The current release OPNsense 17.1.9 updated os-zabbix-agent 1.1 to fix this issue.

Nevertheless I spotted another bug that is related to the validation of "Listen IPs" and fixed it in #196.
