### ISSUE TITLE
acme-client Bug Report: Missing several DNS plugin scripts

### ISSUE THREAD

**Issue by phedoreanu** [opnsense/plugins#1946]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

[x] The title contains the plugin to which this issue belongs

**Describe the bug**
The `acme.sh` client installed on OPNsense doesn't contain all the DNS plugin scripts.

**To Reproduce**
Steps to reproduce the behaviour:
1. Download https://github.com/acmesh-official/acme.sh/archive/2.8.6.tar.gz
2. Check its SHA2 sum with the value from [opnsense/ports/distinfo](https://github.com/opnsense/ports/blob/master/security/acme.sh/distinfo)
3. Extract the tar.gz and see all dnsapi plugins contained in the `2.8.6.` release. 
```
$ ls Downloads/acme.sh-2.8.6/dnsapi | wc -l                                                          
105
```
4. ssh into opnsense and run
```
$ sudo ls /var/db/acme/.acme.sh/dnsapi | wc -l
95
```
5. Comparing `/var/db/acme/.acme.sh/dnsapi` with the release tar reveals the 10 missing plugin scripts:
```
$ diff Downloads/acme.sh-2.8.6/dnsapi opn_dnsapi
Only in Downloads/acme.sh-2.8.6/dnsapi: dns_1984hosting.sh
Only in Downloads/acme.sh-2.8.6/dnsapi: dns_arvan.sh
Only in Downloads/acme.sh-2.8.6/dnsapi: dns_clouddns.sh
Only in Downloads/acme.sh-2.8.6/dnsapi: dns_constellix.sh
Only in Downloads/acme.sh-2.8.6/dnsapi: dns_df.sh
Only in Downloads/acme.sh-2.8.6/dnsapi: dns_dynv6.sh
Only in Downloads/acme.sh-2.8.6/dnsapi: dns_joker.sh
Only in Downloads/acme.sh-2.8.6/dnsapi: dns_kas.sh
Only in Downloads/acme.sh-2.8.6/dnsapi: dns_nm.sh
Only in Downloads/acme.sh-2.8.6/dnsapi: dns_opnsense.sh
```

**Expected behavior**
The folder `/var/db/acme/.acme.sh/dnsapi` should have the same contents as the `dnsapi` folder from the release tar,
as its SHA2 sum and file size match.
```
$ shasum -a 256 Downloads/acme.sh-2.8.6.tar.gz                                                      
fd36cb749466296ded521ceacda3fc841ec76be620900d1116e0492d171c1d9f  Downloads/acme.sh-2.8.6.tar.gz
------------------------------------------------------------
$ ls -al Downloads/acme.sh-2.8.6.tar.gz                                                             
-rw-r--r--@ 1 test  nobody  193182 Aug  1 15:37 Downloads/acme.sh-2.8.6.tar.gz
````

**Environment**
OPNsense 20.7-amd64
FreeBSD 12.1-RELEASE-p7-HBSD
OpenSSL 1.1.1g 21 Apr 2020

**Comment by phedoreanu** [comment]
I've also created this PR to add support for the `dns_1984hosting.sh` plugin script #1945.

**Comment by fraenki** [comment]
It's a bug in the upstream FreeBSD [port](https://www.freshports.org/security/acme.sh/) and needs to be [reported](https://bugs.freebsd.org/bugzilla/)/fixed there.

**Comment by phedoreanu** [comment]
Thanks. Bug reported - https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=248425.

**Comment by fraenki** [comment]
A fix was committed upstream and will soon find it's way into our upstream HardenedBSD ports repo, so I'll close this issue now.

@phedoreanu Thanks for bringing this issue to our attention, much appreciated.
