### ISSUE TITLE
NRPE Plugin Usage Documentation

### ISSUE THREAD

**Issue by baqwas** [opnsense/plugins#1949]
**Important notices**
Our forum is located at https://forum.opnsense.org , please consider joining discussions there in stead of using GitHub for these matters.

Before you ask a new question, we ask you kindly to acknowledge the following:

**YES** [-] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

**YES** [-] I have searched the existing issues and I'm convinced that mine is new.

Is there any documentation on:

- list of NRPE plugins, if any, deployed as part of the standard install/upgrade for OPNsense
- dummies guide on using any one (_e.g._ **check_load**) of the plugins

The **Services** -> **NRPE** -> **Configuration** -> **Commands** (tab) makes sense to me having used NRPE plugins extensively in Debian/Ubuntu farms but I could not find any example for entries for the following fields (_w.r.t._ to the example **check_load** above as an example):

- **Command**
- **Arguments**

Presumably the **Name** would have to be linked in an nrpe.cfg file which begs the questions where and how?

I've read some comment in another thread at this repository about another platform dumping all the NRPE plugins and my simplistic interpretation is that no such thing is taking place with OPNsense. Is this correct? The guidance needed, please:

- Where are the NRPE plugins (standard ones only)?
- What is the process of installing these plugins?
- How to determine the parameters for entry into **Commands** page?

Thanks.

**Comment by maniac-0s** [comment]
Did you ever get anything to this?

**Comment by baqwas** [comment]
Hello @maniac-0s,

My knowledge of OPNsense is very minuscule. There must be a simple solution except that the NRPE daemon would have to be built for OPNsense (may have been built already but _not started_) and that is beyond my job grade.

I can send documentation to anyone on how I do it routinely under Raspberry Pi OS & Ubuntu. Two step process - build & install NRPE daemon and install Plugins (either from Nagios archive or community - different teams using different folders:(). Having never done any command line work on OPNsense, I don't know where to begin. Sorry.

Kind regards.
