### ISSUE TITLE
HAProxy shutdown not working

### ISSUE THREAD

**Issue by tskarman** [opnsense/plugins#195]
As mentioned in https://github.com/opnsense/core/issues/1447 by someone else.

This still happens to me on OPNsense 17.1.9 and os-haproxy 1.16.

Both these don't work:
- Shutting down the haproxy service manually
- Rebooting OPNsense via the web UI

Notes that might be of interest:
- My configured frontends bind to 0.0.0.0:443 and 0.0.0.0:80
- I've configured the firewall itself as a backend/server (on some port, in this case HTTP/4444)

**Comment by fraenki** [comment]
OPNsense 17.7 is scheduled for release this month and will finally update HAProxy to version 1.7.x.

**Comment by tskarman** [comment]
This is still happening on OPNsense 17.7, os-haproxy 1.16, haproxy 1.7.8.

The only message showing up in the log (when attempting to shutdown haproxy manually) is:

    Aug 1 19:30:44 | configd.py: [e36569b4-e4df-4c2f-ab56-a40038749656] stopping haproxy

What can I do to help diagnosing this?

**Comment by fraenki** [comment]
> This is still happening on OPNsense 17.7, os-haproxy 1.16, haproxy 1.7.8.

Very unfortunate. :( But I'm pretty sure we'll find a workaround soon.

> What can I do to help diagnosing this?

The problem is that I was never able to reliably reproduce this issue. Does it happen *every* time you restart HAProxy? If so, I'd be interested in a config dump – a full config.xml dump would be ideal, but I could live with only the HAProxy parts too (anonymized, if required) :)

**Comment by tskarman** [comment]
I've just sent you a config dump to the mail address mentioned on your GitHub profile.

I haven't rebooted in a long time without killing haproxy manually via the shell before, because I don't want to wait for any timeouts to expire.
But I can tell you that this happens consistently every time when attempting the manual shutdown via the "Services" widget on the start page.

**Comment by fraenki** [comment]
Thanks, @tskarman! I've received your config dump and will use it to debug this issue.

**Comment by fraenki** [comment]
@tskarman According to my tests the "hanging" HAProxy processes on shutdown/stop are related to (a) high timeout values in haproxy.conf and (b) HAProxy's default "graceful" stop mode (see #221 for more details). You can check if HAProxy is still serving connections by running `sockstat -4 | grep haproxy` on the CLI.

For OPNsense 17.7.1 we've changed the default stop mode of HAProxy from "graceful" to "hard". It's scheduled for release in a few days – please let me know if it solves the issue for you.

**Comment by tskarman** [comment]
@fraenki working great - thank you!
