### ISSUE TITLE
plugins/net/wireguard configuration reload support

### ISSUE THREAD

**Issue by astuckey123** [opnsense/plugins#1951]
Currently when hitting the "Save" button under either Servers or Clients tabs, or calling the equivalent "reconfigure" API call, a traffic outage is caused to all VPN connections, even if there were no changes to the configuration.  It appears that a full restart of the service is taking place, causing interfaces to be removed and recreated etc, then all of the VPN peers need to re-connect after this, which can take from seconds to a couple of minutes depending on if you have Endpoint addresses defined on both sides of the connection.

The /usr/local/etc/rc.d/wireguard already supports a "reload" option, which uses the wg syncconf option, which allows you to update a particular interfaces configuration without any noticeable hit to traffic.

By adding the following section to /usr/local/opnsense/service/conf/actions.d/actions_wireguard.conf:

> [reload]
command:
    /usr/local/opnsense/scripts/OPNsense/Wireguard/setup.sh;
    /usr/local/etc/rc.d/wireguard reload;
parameters:
type:script
message:reloading Wireguard

and an additional function to /usr/local/opnsense/mvc/app/controllers/OPNsense/Wireguard/Api/ServiceController.php:
> /**
     * update config without restarting
     * @return array
     */
    public function reloadAction()
    {
           $backend = new Backend();
           $response = $backend->configdRun("wireguard reload");
           return array("response" => $response);
    }

I can now successfully perform a GET (not the best choice) to /api/wireguard/service/reload which updates the configuration without causing an outage.

I understand there there may be issues when a new "Server" is created, as I don't believe the corresponding interface will be created with just the reload, as the wg-quick components would not be being called, but as far as adding / removing peers to existing endpoints this seems to work well - could this be considered going ahead?

OPNsense 20.1.9-amd64
os-wireguard 1.2

Cheers,
Adam

**Comment by seandmccarthy** [comment]
I've refined this with @astuckey123 by implementing the `reconfigureAction` method for the ServiceController class. Before it was falling back to the default reconfigureAction in `ApiMutableServiceControllerBase` which was then invoking a full wireguard service restart. Our version uses the less disruptive wireguard reload instead.

**Comment by mimugmail** [comment]
Please reopen and assign to me, there's an open PR for this but I didn't find the time to play with it. 

Thx

**Comment by mimugmail** [comment]
@astuckey123 @seandmccarthy does the reload still work for you? I tried to relaod via CLI only and hit 5 second timeout like when restarting the service.

**Comment by scottdharvey** [comment]
Any updates on this?

**Comment by mimugmail** [comment]
Info to all, this one can be reopened if some guys can test it, for me the reload executed manually didn't work on FreeBSD

**Comment by fichtner** [comment]
A new PR will have to be submitted.

**Comment by hapm** [comment]
It worked for me as described by @astuckey123, but I had to reload the template as well. So after changing `actions_wireguard.conf` I can apply new peers from ssh shell with

```
configctl template reload OPNsense/Wireguard
configctl wireguard reload
```

That is good enough for me atm. To get this into the UI for peers and changes in the peer association to servers there shouldn't be much to do, but I don't know how to do it correctly and I don't have the time to figure it out. I can provide a pull request for the changes to `actions_wireguard.conf` as soon as I have tested them on the newest version of the plugin. Tested them only on the version before #3206 but that shouldn't make much of a difference. Still better safe then sorry.

**Comment by hapm** [comment]
Had two up and running, but didn't look at them while I reloaded the config. Will test on monday.

**Comment by parnic** [comment]
@hapm do you have that pr still? We are very interested in adding this and could test it in any way needed.

**Comment by fichtner** [comment]
If it works I don’t mind a PR, but we don’t need a reload action. We can actually switch the controller default from restart to reload, just needs another function override (not T a computer at the moment to point to it).

but we should also check if this was attempted before and failed for some reason.


Cheers,
Franco

**Comment by hapm** [comment]
> If it works I don’t mind a PR, but we don’t need a reload action. We can actually switch the controller default from restart to reload, just needs another function override (not T a computer at the moment to point to it).
> 
> but we should also check if this was attempted before and failed for some reason.
> 
> Cheers, Franco

If I'm not mistaken restart is still needed to add and remove new wg instances, so removing restart wouldn't be an option.

**Comment by astuckey123** [comment]
From memory when we first did a PR (it was quite a while ago), you need to do a restart when altering / adding anything in "Local", except when updating the "Peers" list in the Local config.  Adding new Endpoints / modifying the Peers list only needs a reload (hitless).

**Comment by astuckey123** [comment]
We are still plagued by this issue causing outages each time we add an endpoint...

**Comment by mimugmail** [comment]
> We are still plagued by this issue causing outages each time we add an endpoint... as we went back to mainline after our PR didn't go through due to being deemed too complicated.

So, when you dont change anything and type via CLI:

service wireguard reload

Nobody geht's kicked or has interruptions? Can you do this a couple of time on high value traffic? In my last testing I had disconnects too even with reload but I cant find anyone to test this.

**Comment by mimugmail** [comment]
> > > We are still plagued by this issue causing outages each time we add an endpoint... as we went back to mainline after our PR didn't go through due to being deemed too complicated.
> > 
> > 
> > So, when you dont change anything and type via CLI:
> > service wireguard reload
> > Nobody geht's kicked or has interruptions? Can you do this a couple of time on high value traffic? In my last testing I had disconnects too even with reload but I cant find anyone to test this.
> 
> I am ramping up testing of our solution described in [#1951 (comment)](https://github.com/opnsense/plugins/issues/1951#issuecomment-1479887345) and will know for sure if it's a problem or not today. In my tests yesterday, reload added a new peer and existing sessions and traffic were _not_ disrupted.

And you usually have disruptions without the solution of above?

**Comment by parnic** [comment]
> > > > We are still plagued by this issue causing outages each time we add an endpoint... as we went back to mainline after our PR didn't go through due to being deemed too complicated.
> > > 
> > > 
> > > So, when you dont change anything and type via CLI:
> > > service wireguard reload
> > > Nobody geht's kicked or has interruptions? Can you do this a couple of time on high value traffic? In my last testing I had disconnects too even with reload but I cant find anyone to test this.
> > 
> > 
> > I am ramping up testing of our solution described in [#1951 (comment)](https://github.com/opnsense/plugins/issues/1951#issuecomment-1479887345) and will know for sure if it's a problem or not today. In my tests yesterday, reload added a new peer and existing sessions and traffic were _not_ disrupted.
> 
> And you usually have disruptions without the solution of above?

Correct. Using the existing "reconfigure" endpoint, all clients have their connections interrupted as Wireguard re-establishes its connection. That drop/hitch is not present with the "reload" endpoint, and all other functionality is preserved.

**Comment by parnic** [comment]
I've got several users connecting and disconnecting today, which runs a "reload" each time, and no traffic has been disrupted. I can verify that `service wireguard reload` specifically can be run on the CLI and nobody gets dropped (in fact, I can run it while connected to the machine through the same Wireguard connection that I'm reloading and there's not even a blip).

I can get this endpoint added to the documentation (with the explanation that it's only useful for peer addition and removal) and submit a PR if that would be helpful. It would be _handy_, but not critical, to have access to this in the UI, but I'm not sure how to message the caveats appropriately in that context.

**Comment by hapm** [comment]
When it comes to GUI, my dream would be, that it detects if there are changes made to local, that are other than only changing associated enpoints and than automatically change the action used to apply from reload to restart. If the apply would requier a restart, it should warn the user before applying, that it will result in a connection reset. Bonus points if it uses [`wg syncconf`](https://manpages.debian.org/wireguard-tools/wg.8#syncconf), what I didn't even know existed when I started to write this reply.

**Comment by DerAlSem** [comment]
@hapm wg_syncconf is the preferred way, i agree.

**Comment by parnic** [comment]
As of the changes detailed in the comments of #3358, a configuration reload will be performed when peers are added or removed from a Wireguard instance so long as "Disable routes" is enabled on the instance.
