### ISSUE TITLE
NETDATA: Please don't overwrite custom netdata.conf configuration, or at least back up old one

### ISSUE THREAD

**Issue by cpw** [opnsense/plugins#1956]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[/] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[/] I have searched the existing issues and I'm convinced that mine is new.

[/] The title contains the plugin to which this issue belongs

**Describe the bug**
A clear and concise description of what the bug is, including last known working version (if any).
Upgrading to 20.7, I lost all my custom netdata configuration with no backup preserved. I activate a bunch of extra netdata plugins (e.g. fping to monitor upstream links), stream to a remote host, and disable all the local webUI and history collection. Most of it was lost on upgrade.

**To Reproduce**
1. Customize 20.1 netdata configuration (netdata.conf file)
2. Upgrade to 20.7
3. Lose all customizations of netdata configuration

**Expected behavior**
It'd be nice to at least have the old configuration file backed up somewhere.

**Environment**
OPNsense 20.7-amd64
FreeBSD 12.1-RELEASE-p7-HBSD
LibreSSL 3.0.2

**Comment by mimugmail** [comment]
But this is the way how OPNsense works?
You have a UI and place your settings. This will be saved in a huge XML files called /conf/config.xml. 
Then you have configd daemon which generates from all stuff in this XML file the templates configs, also netdata.conf.

This means, with every change in Netdata section or with every reboot, this file gets overwritten.

If you miss some features you can always add a feature request (and ping me from time to time) of you just use the pkg without the gui.

Just delete the plugin and via CLI:

```
pkg install netdata
sysrc netdata_enable="YES"

```
Place your custom config and give it a `service netdata restart`

**Comment by cpw** [comment]
OK, understood. Do you want me to suggest some plugin enhancements here? Things I can think of are supporting a "no storage/ui streaming mode" where you configure netdata to not store anything locally, or even serve a webui, but rather, forward everything onto another node elsewhere. The fping module is really helpful too - getting stats on how good the quality of upstream connections in netdata is really useful.
I'm also looking at building an opnsense python module for netdata, to pull some stuff like gateway information and maybe pf info (if it's accessible from cmdline).

**Comment by mimugmail** [comment]
Do you have a netdata.conf where I can check what to set where?

**Comment by cpw** [comment]
I do, but most of it is not relevant.

To disable the storage of data locally, you need
```
[global]
   memory mode = none
```

To disable the web interface, you need
```
[web]
   mode = none
```

To stream to another machine, you need to write a separate file: `stream.conf`

Here's mine:
```
[stream]
        enabled = yes
        api key = <special UUID from the target machine>
        destination = <target machine:port>
```

On the remote machine (probably _not_ an opnsense box) you put:
```
[<special UUID from above>]
        enabled = yes
```

This is documented here: https://learn.netdata.cloud/docs/agent/streaming/

To be honest, it'd be great if this was managed for me :D

On fping, you need to enable the fping module:
```
[plugins]
        freebsd = yes
	fping = yes
```
then you write an "fping.conf" file out with your fping parameters. Obviously you need fping installed. 

```
# no need for shebang - this file is sourced from fping.plugin

# fping.plugin requires a recent version of fping.
#
# You can get it on your system, by running:
#
# /usr/libexec/netdata/plugins.d/fping.plugin install

# -----------------------------------------------------------------------------
# configuration options

# The fping binary to use. We need one that can output netdata friendly info
# (supporting: -N). If you have multiple versions, put here the full filename
# of the right one

#fping="/usr/local/bin/fping"


# a space separated list of hosts to fping
# we suggest to put names here and the IPs of these names in /etc/hosts

hosts="8.8.4.4"


# The update frequency of the chart - the default is inherited from netdata

#update_every=2


# The time in milliseconds (1 sec = 1000 ms) to ping the hosts
# by default 5 pings per host per iteration
# fping will not allow this to be below 20ms

#ping_every="200"


# other fping options - defaults:
# -R      = send packets with random data
# -b 56   = the number of bytes per packet
# -i 1    = 1 ms when sending packets to others hosts (switching hosts)
# -r 0    = never retry packets
# -t 5000 = per packet timeout at 5000 ms

fping_opts="-R -b 56 -i 1 -r 0 -t 5000"
```

I'm actually running a pretty custom fping setup, so I can ping from each of my upstream interfaces separately (the fping plugin can only do a single source interface per "plugin") - that's a pretty advanced setup tho.

Hope this helps.

**Comment by mimugmail** [comment]
Ok, great, can you ping me in three weeks? I'll take care after vacation.

**Comment by Trufax** [comment]
Are there any plan

> Ok, great, can you ping me in three weeks? I'll take care after vacation.

Hey do you have any plans to enable this features in the UI ? I Would also like to setup Netdata as a stream only client on the box and these settings would make it much easier.

**Comment by singularity098** [comment]
Yeah, I would love to see this issue addressed.

Seems like there is no way, not even a workaround to config Netdata in any meaningful way?  I want to stream my netdata info to a server, and to slow the polling time from 1 second to 10 seconds, among some other things.

**Comment by Trufax** [comment]
Any updates on this? Can we get it repoend ?

**Comment by fichtner** [comment]
Same as https://github.com/opnsense/plugins/issues/3964#issuecomment-2094207977

Please don’t ask for things that are against the development policy… and then keep asking without bothering to check the relevant ways forward.
