### ISSUE TITLE
Let the wireguard widget show the endpoint name instead of its pubKey

### ISSUE THREAD

**Issue by sh4d0v1** [opnsense/plugins#1958]
The new wireguard widget is great, but it shows the pubKey of the endpoint, instead of its name, which is not optimal. Who remembers pubKeys of wireguard clients, especially if there are many?

Displaying the user given endpoint names instead of their pubKeys would make the widget more helpful. With the knowledge of how to access the endpoint names it is a trivial modification.

**Comment by mimugmail** [comment]
This is currently not possible as the widget only prints the output of wg command which can't work with users or descriptions (it's the design of WG itself). To display the description we'd need a different approach.

I remember there's still an open PR for the diagnostics page, maybe you want to have a look?

**Comment by sh4d0v1** [comment]
If it was possible to access the endpoint configuration data we could map the privKey from the wg command to that, couldn't we?

**Comment by petervynck** [comment]
Is there any progress on this please? Started using Wireguard and very happy but the widget and the TABS 'List configuration' and 'Handshakes' could be much more helpful if they could include the IP and/or Name of the endpoints.

**Comment by sh4d0v1** [comment]
The code in QDaniel's commit is working, but not yet merged.
You can just take that one php file's code and replace it on your installation though.

I wished it would be merged, or at least some more details about why it "feels too hacky".

**Comment by petervynck** [comment]
Works perfectly! Thanks.

**Comment by pagong** [comment]
You might also consider using
https://github.com/warner/wireguard-vanity-address
for generating public keys that start with a string that has some meaning to you.
