### ISSUE TITLE
net/igmp-proxy OPNsense 20.7 not leaving group upstream

### ISSUE THREAD

**Issue by Staticznld** [opnsense/plugins#1959]
It looks like the upstream interface defined in the IGMPproxy settings is not leaving multicast groups.
After some channel zapping the bandwith goes up to 75Mbps!

When i was using 20.1.9 i had no problems!

See https://forum.opnsense.org/index.php?topic=18347.0 for some screenshots.

**Comment by Staticznld** [comment]
https://github.com/opnsense/src/issues/69 
Discribes the same problem

# opnsense-update -kr 20.7-re-mcast2
# opnsense-shell reboot

Fixes the problem.

**Comment by fichtner** [comment]
@Staticznld thanks a lot for confirming. We'll add the 3 multicast patches to 20.7.1 :)
