### ISSUE TITLE
security/acme-client: rerun automation [FR]

### ISSUE THREAD

**Issue by QDaniel** [opnsense/plugins#1962]
I would like a new button for rerun the linked automation.

![Zwischenablage01](https://user-images.githubusercontent.com/905384/89644104-83331800-d8b7-11ea-9eae-90831f32b015.png)

**Comment by fraenki** [comment]
Thanks for the suggestion. This feature will be available in the upcoming os-acme-client version 1.36. (Likely to arrive with OPNsense 20.7.2.)
