### ISSUE TITLE
wire guard problem

### ISSUE THREAD

**Issue by yhq34** [opnsense/plugins#1964]
I setup wireguard according to below official manual; but I cannot see interface Wireguard in rules, until I create a interfaces at assignment on interfaces, but when I create opnvpn. this tab will show auto, no need add new interface. what's the problem?
'Step 3 - Setup Firewall

On Firewall ‣ Rules add a new rule on your WAN interface allowing the port you set in your instance (Protocol UDP). You also have a new interface Wireguard in rules, where you can set granular rules on connections inside your tunnel.'

**Comment by mimugmail** [comment]
Just edit a Firewall rule without changes and save, then it should be there

**Comment by yhq34** [comment]
Thanks,after upgrade to 20.7. This works
