### ISSUE TITLE
Wireguard: routes aren't set up

### ISSUE THREAD

**Issue by mbunkus** [opnsense/plugins#1966]
I'm using the Wireguard plugin with two tunnels. Both have various IPv4 and IPv6 routes (no explicit routing, just via the "allowed IPs" setting). After rebooting the machine or after restarting the Wireguard plugin via the Dashboard, the second tunnel is missing almost all of its routes. Only after restarting the plugin via ssh are all routes set.

Here's how routing looks after booting or after restarting via the UI  (I'm going to anonymize the IPv6 addresses somwhat):

```shell
[root@layla ~]# netstat -n -r | grep wg
10.54.0.0/16       wg0                US          wg0
10.55.5.0/30       wg0                US          wg0
10.55.5.2          link#8             UH          wg0
10.55.5.6          link#9             UH          wg1
2a01:4f8:…:…::2              wg0                           UHS         wg0
2a01:4f8:…:…::100:0/104      wg0                           US          wg0
2a01:4f8:…:…::/64            wg0                           US          wg0
fd01:4f8:…:…:55::/112        link#8                        U           wg0

```

For the first tunnel, `wg0`, all relevant routes seem to be present, both for IPv4 and IPv6.

For the second tunnel however,, `wg1`, there's only a single IPv4 route, the one for the interface address itself. There isn't even an IPv6 route for the interface address.

Now I can restart the plugin via ssh, and afterwards all the routes I'm expecting to be there are there:

```shell
[root@layla ~]# /usr/local/etc/rc.d/wireguard restart
[#] rm -f /var/run/wireguard/wg0.sock
[#] rm -f /var/run/wireguard/wg1.sock
[#] wireguard-go wg0
INFO: (wg0) 2020/08/09 13:31:31 Starting wireguard-go version 0.0.20200320
[#] wg setconf wg0 /tmp/tmp.7RYytZCh/sh-np.2XiIGW
[#] ifconfig wg0 inet 10.55.5.2/30 10.55.5.2 alias
[#] ifconfig wg0 inet6 fd01:4f8:…:…:55::2/112 alias
[#] ifconfig wg0 mtu 1412
[#] ifconfig wg0 up
[#] route -q -n add -inet6 2a01:4f8:…:…::2/128 -interface wg0
[#] route -q -n add -inet6 2a01:4f8:…:…::100:0/104 -interface wg0
[#] route -q -n add -inet6 2a01:4f8:…:…::/64 -interface wg0
[#] route -q -n add -inet 10.55.5.0/30 -interface wg0
[#] route -q -n add -inet 10.54.0.0/16 -interface wg0
[+] Backgrounding route monitor
[#] wireguard-go wg1
INFO: (wg1) 2020/08/09 13:31:31 Starting wireguard-go version 0.0.20200320
[#] wg setconf wg1 /tmp/tmp.qhFkQmYa/sh-np.8Leeqt
[#] ifconfig wg1 inet 10.55.5.6/30 10.55.5.6 alias
[#] ifconfig wg1 inet6 fd01:1640:…::feed:2:2/126 alias
[#] ifconfig wg1 mtu 1412
[#] ifconfig wg1 up
[#] route -q -n add -inet6 2001:1640:…:…::/64 -interface wg1
[#] route -q -n add -inet6 2001:1640:…:…::/64 -interface wg1
[#] route -q -n add -inet6 2001:1640:…:…::/64 -interface wg1
[#] route -q -n add -inet6 2001:1640:…:…::/64 -interface wg1
[#] route -q -n add -inet 192.168.0.0/16 -interface wg1
[#] route -q -n add -inet 172.16.0.0/12 -interface wg1
[#] route -q -n add -inet 10.0.0.0/8 -interface wg1
[+] Backgrounding route monitor
[root@layla ~]# netstat -n -r | grep wg
10.0.0.0/8         wg1                US          wg1
10.54.0.0/16       wg0                US          wg0
10.55.5.0/30       wg0                US          wg0
10.55.5.2          link#8             UH          wg0
10.55.5.6          link#9             UH          wg1
172.16.0.0/12      wg1                US          wg1
192.168.0.0/16     wg1                US          wg1
2001:1640:…:…::/64              wg1                           US          wg1
2001:1640:…:…::/64              wg1                           US          wg1
2001:1640:…:…::/64              wg1                           US          wg1
2001:1640:…:…::/64           wg1                           US          wg1
2a01:4f8:…:…::2              wg0                           UHS         wg0
2a01:4f8:…:…::100:0/104      wg0                           US          wg0
2a01:4f8:…:…::/64            wg0                           US          wg0
fd01:4f8:…:…:55::/112        link#8                        U           wg0
fd01:1640:…::feed:2:0/126       link#9                        U           wg1
```

Both tunnels work just fine after said manual restart.

I'll gladly provide more debugging output or logs as needed.

**To Reproduce**

I haven't actually tried to reproduce this behavior manually, but I do see it consistently with my current configuration through two reboots and four or five restarts via the dashboard. To the best of my knowledge, here's how to reproduce it:

1. Install the Wiregard pluygin
2. Go to VPN → Wireguard → Endpoints
3. Create two endpoints. For each add several networks, both IPv4 & IPv6, as the "Allowed IPs". I'm not using a "shared secret". I am providing an endpoint address, a port & a keepalive of 25.
4. In the list of endpoints hit the "Save" button (not sure what that button actually does, but maybe it is required for making the endpoints… active or stuff).
5. Go to VPN → Wireguard → Local.
6. Create two local configurations, each using one of the endpoints created in step 3. For each local configuration provide one IPv4 and one IPv6 tunnel address. Do _not_ check "disable routes". Do _not_ select a "gateway" in "advanced" mode. I'm not providing neither a "public key" nor a "DNS server". I am providing a "listen port" as well as an "MTU" of 1412.
7. Back in the list of local configurations hit the "Save" button (not sure what that button actually does either).
8. Go to the dashboard. Stop the Wireguard service, then start it again.
9. Observe the routing table., either via the UI or via ssh. The routes for the tunnels will likely not be present.
10. Log in via ssh and restart the plugin via `/usr/local/etc/rc.d/wireguard restart`.
11. Observe the routing table again. The routes should now all be present.

**Relevant log files**

I do not know where Wireguard logs to. `/var/log/vpn.log` is empty, and there's no `/var/log/wireguard.log` or similar.

**Environment**

OPNsense 20.7-amd64 (OpenSSL)
os-wireguard v1.2

**Comment by mbunkus** [comment]
Sorry, I accidentally removed the confirmations at the top:

Yes, …

[✓] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
[✓] I have searched the existing issues and I'm convinced that mine is new.
[✓] The title contains the plugin to which this issue belongs

**Comment by mimugmail** [comment]
Is this a Site 2 Site setup or remote access?

**Comment by mbunkus** [comment]
Both tunnels are site 2 site setups.
