### ISSUE TITLE
os-frr: area setup for non default area types in OSPF

### ISSUE THREAD

**Issue by Be-El** [opnsense/plugins#1971]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

[x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
In a new setup a uplink router, we need to connect to an existing OSPF area. This area is defined as 'not-so-stubby-area' (nssa). All routers in one area need to use the same area configuration, so all routers including the opnsense boxes need to define the area as nssa in this case. The same might be true for other area types, too.

**Describe the solution you'd like**
In the current configuration pages, there is no way to define the area itself, just networks and interfaces (which might be linked to certain areas). IMHO the best but also most work intensive option is adding areas as first class objects next to interfaces and networks; the configuration pages for both can refer to the configured areas instead of entering the area as IP address or area number. This might also reduce typing errors.
The area configuration itself need to include e.g. a checkbox or radio box for the various configurable area types. It can also be used to define the redistribution option for announce other networks.

**Describe alternatives you've considered**
I'm currently using a manually edited ospfd.conf, but this solution is suboptimal and overwritten each time a configuration change is saved in the web interface. 
I could also switch to static routes, but I consider area types an important feature of OSPF, and they should be added to the plugin.

**Comment by mimugmail** [comment]
Can you post the manually edited ospfd.conf and the one which get's generated (overrides it). I'm not sure if I can follow but the diff would certainly explain it :)

**Comment by epers** [comment]
Hopefully I can help with this as we are in need of this feature as well.

PFSense has this feature (in 2.5.1), here's some screenshots of the relevant menus:
![image](https://user-images.githubusercontent.com/34660529/117655451-18c04880-b165-11eb-920b-6d4c9731861f.png)
![image](https://user-images.githubusercontent.com/34660529/117655484-237add80-b165-11eb-8cd4-b9b74a179bb9.png)
![image](https://user-images.githubusercontent.com/34660529/117655869-a308ac80-b165-11eb-8a70-fdbe6005b8f4.png)



It generates snippets like this in frr.conf:
```
router ospf
 ospf router-id 10.15.10.31
 default-information originate metric 10
 auto-cost reference-bandwidth 10000
 max-metric router-lsa on-startup 60
 max-metric router-lsa on-shutdown 60
 passive-interface lo0
 area 0.0.0.0 shortcut default
 area 10.15.192.0 stub no-summary
 area 10.15.192.0 default-cost 10
 area 10.15.192.0 shortcut default
 area 10.15.32.0 stub no-summary
 area 10.15.32.0 default-cost 10
 area 10.15.32.0 shortcut default
 area 10.15.64.0 stub no-summary
 area 10.15.64.0 default-cost 10
 area 10.15.64.0 shortcut default
!
```
Note the `stub no-summary` lines, that's what we really need here. It would be different for the different area types.

Any other info I can provide just let me know.

**Comment by LennertVA** [comment]
Two years later and it doesn't seem like anything has changed. Any way to force it to work - even if it it's manually in cli?

**Comment by KodyKodersan** [comment]
Any updates here?  This is pretty much required with any OSPF implementation on a firewall nowadays.
