### ISSUE TITLE
os-frr: No support for authentication in BGP

### ISSUE THREAD

**Issue by Be-El** [opnsense/plugins#1972]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

[x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
For a sane production setup, BGP routing should be protected at least by a password.

**Describe the solution you'd like**
A field should be added to the neighbor table taht contains the MD5 password used to authenticate to the given neighbor. The fields content needs to be added as 'neighbor <perr ip> password <password>' to the configuration if set to a concrete value.
See also http://docs.frrouting.org/en/latest/bgp.html#clicmd-[no]neighborPEERpasswordPASSWORD

**Describe alternatives you've considered**
Running BGP without passwords, but I would consider this insecure and unsuited for production use.

**Comment by mimugmail** [comment]
I failed in my tests with just passwords, doesn't this require some kernel tweaks?

**Comment by mimugmail** [comment]
I played with this a but, 2 problems

@fichtner for this I need TCP_SIGNATURE in kernel ( https://github.com/FRRouting/frr/issues/1479 )
@AdSchellevis This feature needs to add keys via setkey ( https://github.com/FRRouting/frr/issues/1479#issuecomment-626209323 ) and I'm not sure where this would fit best as already ipsec touches it.

**Comment by AdSchellevis** [comment]
@mimugmail I don't think we currently can distinct the different sa entries, in which case I expect the manual ones might be dropped by the ipsec module (haven't tested it).

https://github.com/opnsense/core/blob/87efd07831bc136416a5bd435e6bb67716c16ce7/src/etc/inc/plugins.inc.d/ipsec.inc#L674-L770

The current construction isn't great, but it's quite time consuming to workout better alternatives, which I'm currently not planning to invest  (if I'm not mistaken, ideally the policies should be assigned after the tunnel comes up, for which we miss events. Last time I spend time on setkey, I also remember the documentation and examples weren't really helpful).

**Comment by mimugmail** [comment]
@AdSchellevis Users of BGP with IPsec in combination should be near zero as the encrypted traffic is already safe.
Would it be ok if I add a script and add a warning in the plugin? MD5 passwords in BGP are not common on my side and this about the 3rd or 4th request (incl. forum) so I'd like to work on it (if we also add the kernel option)

**Comment by AdSchellevis** [comment]
@mimugmail sure, I can live with that if it doesn't lead to weird race conditions (at a first glance this looks quite static). If we can exclude these entries easily, I don't even mind changing some of the ipsec code, but someone needs to test it and collect the different scenarios that do exist.

**Comment by theonemcdonald** [comment]
I've got a provider that insists on password authentication for BGP. This would be nice to have.

**Comment by mimugmail** [comment]
@fichtner what so you think about adding signature support to kernel?

**Comment by fichtner** [comment]
Well, does it work nowadays?

**Comment by mimugmail** [comment]
In the first step we need no add kernel support in general as this is no real authentication inside BGP protocal, rather on the TCP layer. In a second step we have to add/manipulate for each neighbor the SPD database like with ipsec, but I can't test second when kernel features are missing.

**Comment by mimugmail** [comment]
@fichtner any news about MD5 Kernel support?

**Comment by theonemcdonald** [comment]
Well with the WireGuard fiasco over at pfSense, I’m really eager to move over here. This is the most significant barrier to that means. Any update?

**Comment by mimugmail** [comment]
Please reopen and assign me .. some day I can motivate @fichtner to add this option :)
Steter Tropfen hölt den Stein ...

**Comment by fichtner** [comment]
@mimugmail I went back in tools git but I never found a kernel that didn't have TCP_SIGNATURE unset...

https://github.com/opnsense/tools/blob/ae1fabd98527460cddac3c74335259a3500fc13a/config/21.1/SMP#L18

What am I missing?

**Comment by mimugmail** [comment]
Hm, I was under the impression it's not in yet, maybe I looked at the wrong files or we crosstalked in IRC.
Ok, I'll have a go the next week working with the spd :)

**Comment by mfld-pub** [comment]
> 
> 
> Well with the WireGuard fiasco over at pfSense, I’m really eager to move over here. This is the most significant barrier to that means. Any update?

+1. Showstopper for us right now.  

Upstream demands that we set a _neighbor password_ and our environment demands that we set  

`ebgp-multihop **2** `

as well as 

`no bgp network import-check` 

once FRR 7.5 is introduced. Right now OpnSense is on 7.4 so this isn't an issue yet but soon will be. 

No doubt it is impossible to expose all possible scenarios in the GUI without making it look ridiculous - FRR is vast. 

But Perhaps as a compromise for now expose a RAW CONFIG in the GUI where one can override the settings. That way we can use the GUI to get most of the way there and then add the 1 or 2 extra lines of needed tweaks to the resulting config file.

**Comment by fichtner** [comment]
> But Perhaps as a compromise for now expose a RAW CONFIG in the GUI where one can override the settings.

No chance. You can use FRR manually as a FreeBSD port/package if the plugin cannot cover your use cases.

**Comment by thexa4** [comment]
I'd also like to migrate away from pfSense and have the same requirement from my upstream provider to use MD5 authentication and multihop 2.

Is there any way I can help to fix this issue?

**Comment by mfld-pub** [comment]
The required module seems to be present and loaded in vanilla OPNsense 21.1.5:

```
root@opnsense-github-issue-1972:~ # kldload tcpmd5
kldload: can't load tcpmd5: module already loaded or in kernel
```

I will try install the FRR FreeBSD package, make it work and then work my way from there. I am guessing the MD5 TCP secret has to go into **ipsec.conf** 

`add [neighbor ip] [router ip] tcp 0x1000 -A tcp-md5 "[bgp session secret]";`

I gather the challenge here lies in not making os-frr overwrite or break actual IPSEC secrets?

**Comment by mimugmail** [comment]
https://bird.network.cz/pipermail/bird-users/2018-March/012094.html

In a file somewhere:
```
# /etc/setkey.conf
flush;		# useful when running mutations manually
spdflush;	# useful when running mutations manually
add -4 12.34.56.6 12.34.56.7 tcp 0x1000 -A tcp-md5 "teNp8XUrZtNteNjbep68jXgUGroZtUN";
add -4 12.34.56.7 12.34.56.6 tcp 0x1000 -A tcp-md5 "teNp8XUrZtNteNjbep68jXgUGroZtUN";
```

Then:
`setkey -v -f /etc/setkey.conf`

Seems to work, but I didn't check in live system.
@AdSchellevis If I add this to FRR plugin it might break NAT inside IPsec since all SPD are flushed. 
But I think it's highly unsual to use BGP inside IPsec and also natting stuff. What do you think?

**Comment by AdSchellevis** [comment]
@mimugmail I'm not a huge fan to be honest, my experience so far is that some day someone opens ticket why this can't be combined and starts rambling everything is stupid. If it's the only way, so be it, but if we can engineer something smarter that would be my preference.

**Comment by mimugmail** [comment]
I'm not sure about the glue between spd in legacy code and frr mvc .. but I'll have a look :)

**Comment by mmack** [comment]
If you guys need someone for testing ping me... I have the same problem on vultr.com

**Comment by mimugmail** [comment]
Ok, I successfully tested the approach above by hand, I try to get a draft next week. :)

**Comment by mmack** [comment]
@mimugmail any progress so far? Can we test it?

**Comment by mimugmail** [comment]
I try to start this evening, thx for the reminder :)

**Comment by mmack** [comment]
@mimugmail Can i buy you a coffee? :smile:

**Comment by mimugmail** [comment]
Sure :)

https://github.com/opnsense/plugins/pull/2645

**Comment by Chikito7** [comment]
Hi Guys,
So, now authentication is working well ? 
we are using  and it doesn't work 

FRRouting 7.5.1 (OPNsense.localdomain).
OPNsense 22.7.10_2-amd64
FreeBSD 13.1-RELEASE-p5

**Comment by mfld-pub** [comment]
It never worked for us. Session with IPv6 and bidirectional setkey MD5 secret just stays "Active".

Logs show an error that may or may not be relevant `2023-01-19T02:46:06 | Error | bgpd | [EC 100663299] buffer_flush_available: write error on fd 2: Bad file descriptor`

Just tried again from scratch as the last time I tried was ~12 months ago. Now on 

OPNsense 22.7.11-amd64
FreeBSD 13.1-RELEASE-p5
os-frr-1.31

**Comment by mimugmail** [comment]
Can you add a screenshot of neighbor config?

**Comment by mfld-pub** [comment]
> Can you add a screenshot of neighbor config?

Sure thing!

![Screenshot 2023-01-19 055332](https://user-images.githubusercontent.com/66289900/213366531-52961818-ddab-4397-b9f0-3ae356ebbb14.png)

The MD5 secret has no special characters and is of this sort of format: `uzyV8qHiVmXlT2B2`

The prefix lists allow one prefix to be announced and default route to be received. 

Sanitized running config:
```

Building configuration...

Current configuration:
!
frr version 7.5.1
frr defaults traditional
hostname testbox.opnsense.rocks
log syslog
!
router bgp 64500
 bgp router-id 22.120.12.93
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 bgp graceful-restart
 no bgp network import-check
 neighbor 2001:19f0:ffff::1 remote-as 64515
 neighbor 2001:19f0:ffff::1 password uzyV8qHiVmXlT2B2
 neighbor 2001:19f0:ffff::1 ebgp-multihop 255
 neighbor 2001:19f0:ffff::1 disable-connected-check
 !
 address-family ipv6 unicast
  network 2001:db8:1014::/48
  neighbor 2001:19f0:ffff::1 activate
  neighbor 2001:19f0:ffff::1 prefix-list default-in-v6 in
  neighbor 2001:19f0:ffff::1 prefix-list default-out-v6 out
 exit-address-family
!
ipv6 prefix-list default-in-v6 seq 100 permit ::/0
ipv6 prefix-list default-out-v6 seq 100 permit 2001:db8:1014::/48
!
line vty
!
end
```

**Comment by mimugmail** [comment]
You need to fill local Initiator IP to get this working. Maybe something for the docs

**Comment by mfld-pub** [comment]
> You need to fill local Initiator IP to get this working. Maybe something for the docs

Oh, it is not resolving from `Update-Source Interface` ? I will test again.

**Comment by mimugmail** [comment]
It is used for setkey parameters

https://github.com/opnsense/plugins/pull/2800/files

**Comment by Chikito7** [comment]
Cool - will test it tomorrow.

Thanks

**Comment by Chikito7** [comment]
Tested and confirmed - it is working

**Comment by joachimtingvold** [comment]
Seems like this implementation only works for IPv4 BGP peers?

**Comment by mfld-pub** [comment]
This has been my experience too. Cannot turn up a session with an IPv6 neighbor.

**Comment by mimugmail** [comment]
Can you post the contents of the files in the PR above? Dont see a reason why it shouldnt work with v6

**Comment by joachimtingvold** [comment]
> Can you post the contents of the files in the PR above? Dont see a reason why it shouldnt work with v6

Line [63](https://github.com/opnsense/plugins/pull/2800/files#diff-bf3265a40e757ef34244f6c69e9fbfc03e40edc6f487216ff2eb17dd67ad5522R63) + [65](https://github.com/opnsense/plugins/pull/2800/files#diff-bf3265a40e757ef34244f6c69e9fbfc03e40edc6f487216ff2eb17dd67ad5522R65) in `net/frr/src/opnsense/scripts/frr/register_sas` only adds `setkey` stuff with the `-4` parameter (which I assume means IPv4, and thus IPv6 neighbors needs the `-6` parameter).

**Comment by joachimtingvold** [comment]
I see now that the contents of the PR above since has been updated via PR #3345 to allow for IPv6 peers. I can confirm that my OPNsense version is 23.1.11, which has #3345 incorporated. However, I cannot get IPv6 neighbors to work with MD5 passwords.
