### ISSUE TITLE
net/haproxy plugin: Support server-template stanza

### ISSUE THREAD

**Issue by hny-gd** [opnsense/plugins#1975]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

[X] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
Right now, when defining a "backend" section via the GUI, one can describe a "server" entry for the config file via "Real Servers".
When using HAProxy with a service discovery tool, it is necessary to use the "server-template" stanza instead of the now always generated "server" stanza together with a "resolvers" stanza. 
That way, HAProxy does not connect to a static IP address but instead looks up the IP address and port via the resolver.

**Describe the solution you'd like**

According to the current GUI logic, probably the "Backend Pool" dialog could remain unchanged.

The "Real Servers" GUI would need to be extended:
- With a drop down field "static" or "resolver" (or similar) 
- When "static" is chosen, the dialog remains like today
- When "resolver" is chosen, the entry fields need to change and one needs to define the service name and the resolver (i.e. name server) that is used to resolve the service name

**Describe alternatives you've considered**
No alternative came to my mind.

**Additional context**
A very simple example for using HAProxy to resolve services via Consul (one of many available service discovery tools) can be found at https://learn.hashicorp.com/tutorials/consul/load-balancing-haproxy

**Comment by fraenki** [comment]
Basic support for server-template will be available in the upcoming os-haproxy version 3.0.
Please open a new bug report / feature request if something does not work as expected.
