### ISSUE TITLE
Add rescure_domain_blacklist.txt to DnsCrypt-proxy

### ISSUE THREAD

**Issue by L1ghtn1ng** [opnsense/plugins#1979]
@mimugmail I can create a PR for this blocklist if you like? https://rescure.fruxlabs.com/rescure_domain_blacklist.txt

Just want to run it by you first just to make sure it would work before I did the work of adding it, thanks

**Comment by mimugmail** [comment]
Sure, just add a PR. It's a bit small, but if it helps, why not 👍
