### ISSUE TITLE
security/tinc: doesn't show a list of Ciphers in 17.1.9

### ISSUE THREAD

**Issue by mrdmiller2** [opnsense/plugins#198]
It looks like the Tinc Plugin is broken since it doesn't generate a list of cipher's that can be used.  I've tried many different ways to (re)install. Using LibreSSL and OpenSSL.  Even a complete rebuild.. but Tinc never shows a list of Cipher options.  Which means you can't actually configure things.

**Comment by mrdmiller2** [comment]
For some additional information, the os-tinc package version is: 1.2_2 and the tinc package version: 1.0.31

**Comment by AdSchellevis** [comment]
can you test the following on a console? (on my end it does list ciphers using the latest version)

`configctl tinc list ciphers
`

and
`/usr/local/opnsense/scripts/OPNsense/Tinc/list_ciphers.py
`

**Comment by mrdmiller2** [comment]
Both report a Ciphers list:

 

{"camellia-256-cfb":"camellia-256-cfb","desx-cbc":"desx-cbc","id-aes192-GCM":"id-aes192-GCM","camellia-192-ofb":"camellia-192-ofb","des-ede-ofb":"des-ede-ofb","aes-128-cfb":"aes-128-cfb","des3":"des3","camellia-256-cfb1":"camellia-256-cfb1","seed-ofb":"seed-ofb","rc4-hmac-md5":"rc4-hmac-md5","camellia-256-cfb8":"camellia-256-cfb8","rc2-ofb":"rc2-ofb","id-aes256-GCM":"id-aes256-GCM","des-ecb":"des-ecb","aes-256-ecb":"aes-256-ecb","rc4-40":"rc4-40","idea-ofb":"idea-ofb","des-ede3":"des-ede3","aes-192-ecb":"aes-192-ecb","aes-192-gcm":"aes-192-gcm","camellia-128-cfb":"camellia-128-cfb","seed-ecb":"seed-ecb","id-aes128-wrap":"id-aes128-wrap","des-ede-cfb":"des-ede-cfb","aes-192-ccm":"aes-192-ccm","desx":"desx","des-cbc":"des-cbc","cast5-ofb":"cast5-ofb","camellia-128-cfb8":"camellia-128-cfb8","des-ede3-ofb":"des-ede3-ofb","none":"None","id-aes192-wrap":"id-aes192-wrap","cast5-cfb":"cast5-cfb","des-ede3-cfb":"des-ede3-cfb","id-aes192-CCM":"id-aes192-CCM","aes-256-cbc":"aes-256-cbc","idea-ecb":"idea-ecb","camellia192":"camellia192","camellia-256-ofb":"camellia-256-ofb","id-aes256-CCM":"id-aes256-CCM","rc2-cbc":"rc2-cbc","bf-ofb":"bf-ofb","aes-128-ofb":"aes-128-ofb","bf-ecb":"bf-ecb","rc2-40-cbc":"rc2-40-cbc","idea":"idea","bf-cbc":"bf-cbc","aes-192-cfb1":"aes-192-cfb1","aes192":"aes192","aes-192-cfb8":"aes-192-cfb8","camellia-128-ofb":"camellia-128-ofb","aes-192-ofb":"aes-192-ofb","camellia-192-cfb":"camellia-192-cfb","aes-192-cfb":"aes-192-cfb","aes-256-ofb":"aes-256-ofb","des-ede3-cfb8":"des-ede3-cfb8","des-ede3-cfb1":"des-ede3-cfb1","bf":"bf","idea-cfb":"idea-cfb","cast5-ecb":"cast5-ecb","seed-cfb":"seed-cfb","id-aes256-wrap":"id-aes256-wrap","seed-cbc":"seed-cbc","aes-256-cfb":"aes-256-cfb","rc5-ecb":"rc5-ecb","des-ede3-cbc":"des-ede3-cbc","aes-256-ctr":"aes-256-ctr","camellia-256-cbc":"camellia-256-cbc","rc2-64-cbc":"rc2-64-cbc","des-ede":"des-ede","camellia128":"camellia128","cast5-cbc":"cast5-cbc","aes-128-cbc":"aes-128-cbc","camellia-128-cbc":"camellia-128-cbc","aes-128-gcm":"aes-128-gcm","des-ede-cbc":"des-ede-cbc","rc5-cbc":"rc5-cbc","blowfish":"blowfish","aes-128-ctr":"aes-128-ctr","des-cfb1":"des-cfb1","rc4":"rc4","rc5":"rc5","des":"des","des-cfb8":"des-cfb8","rc2":"rc2","camellia256":"camellia256","cast":"cast","aes-128-cfb1":"aes-128-cfb1","des-cfb":"des-cfb","id-smime-alg-CMS3DESwrap":"id-smime-alg-CMS3DESwrap","rc2-cfb":"rc2-cfb","aes-128-cfb8":"aes-128-cfb8","aes-128-ccm":"aes-128-ccm","camellia-128-cfb1":"camellia-128-cfb1","rc5-ofb":"rc5-ofb","aes-192-cbc":"aes-192-cbc","camellia-128-ecb":"camellia-128-ecb","seed":"seed","rc5-cfb":"rc5-cfb","aes-256-xts":"aes-256-xts","camellia-256-ecb":"camellia-256-ecb","aes-256-cfb1":"aes-256-cfb1","aes-256-cfb8":"aes-256-cfb8","aes-256-ccm":"aes-256-ccm","rc2-ecb":"rc2-ecb","aes-128-ecb":"aes-128-ecb","bf-cfb":"bf-cfb","aes-256-gcm":"aes-256-gcm","idea-cbc":"idea-cbc","id-aes128-CCM":"id-aes128-CCM","camellia-192-cbc":"camellia-192-cbc","aes-128-xts":"aes-128-xts","aes256":"aes256","camellia-192-cfb8":"camellia-192-cfb8","cast-cbc":"cast-cbc","camellia-192-cfb1":"camellia-192-cfb1","camellia-192-ecb":"camellia-192-ecb","des-ofb":"des-ofb","id-aes128-GCM":"id-aes128-GCM","aes128":"aes128","aes-192-ctr":"aes-192-ctr"}

 

Interestingly after running both commands, the GUI now shows the list of Ciphers.. so I’m guessing the GUI isn’t running that python command?

**Comment by AdSchellevis** [comment]
It should be using that command, using the configd socket, although it might be cached to avoid . 
Can you open the following page to request an empty network entry?
https://10.211.55.100/api/tinc/settings/getNetwork/

Then remove the configd model cache file, and try again:

`rm /tmp/configdmodelfield.data`

**Comment by mimugmail** [comment]
I did a upgrade from 17.1.8 to 17.1.9 but I can't reproduce this, so this should be specific to your system/setup.

**Comment by tuxec** [comment]
I have seen the same problem - as described above - on 17.1.9., occuring both, under "Networks" and under "Hosts", in the "Cipher" entry field, on a fresh installation. This made it impossible to do any changes in the entries. After some time, however, the problem "disappeared" - looks like a kind of internal refresh to me - and the cipher could be choosen as usual.

**Comment by mrdmiller2** [comment]
It seems to happen both after a fresh install but also after any significant change that requires a reboot.  Just upgraded to 17.7 and the same problem exists.. however running the above commands does give a cipher list. So I think the problem still exists.

**Comment by AdSchellevis** [comment]
@mrdmiller2 this will be quite difficult to track, I haven't seen it on my end, which certainly doesn't mean it's not there.

For reference the model uses a fieldtype which fetches configd when either there is no cache or the cache is too old https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/JsonKeyValueStoreField.php#L166. The plugin model requests the following file to be used as cache /tmp/tinc_current_cipher_options.index (https://github.com/opnsense/plugins/blob/master/security/tinc/src/opnsense/mvc/app/models/OPNsense/Tinc/Tinc.xml#L62).


So if it fails, we should logically inspect the following:

1. The time of the machine `date`
2. The existence and change date of the file `ls -als  /tmp/tinc_current_cipher_options.index`
3. And finally the contents of the file `cat  /tmp/tinc_current_cipher_options.index`

If it happens again, can you try the above steps? This should help narrowing it down.

**Comment by mrdmiller2** [comment]
I have the time mapped to NTP.

After a reboot, the problem seems to re-occur.. (But once its populated via running those scripts manually it works until the next reboot)

So for example, I rebooted today at 01:19:00 AM PST.

 ls -als /tmp/tinc_current_cipher_options.index produces this output:

0 -rw-r--r--  1 root  wheel  0 Aug 19 01:09 /tmp/tinc_current_cipher_options.index

But the file is empty.

**Comment by AdSchellevis** [comment]
@mrdmiller2 thanks for testing, https://github.com/opnsense/core/commit/c72c1874b83a3b9437a4c5c872c4d226ab26bfa9 + https://github.com/opnsense/core/commit/2349bc39d2fdd879d10700e58eb67cc72b9cc0ba should fix the issue. 

If for some reason there already is an empty file on disk, it will be ignored, the first fix prevents illegal data to be written to disk (configd result should contain valid json data for the field type to understand).

**Comment by fichtner** [comment]
This was fixed.
