### ISSUE TITLE
Postfix not logging anymore

### ISSUE THREAD

**Issue by AndyX90** [opnsense/plugins#1980]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

[x] The title contains the plugin to which this issue belongs

**Describe the bug**
After upgrading to 20.7 (and 20.7.1) the postfix log stays empty.

**To Reproduce**
1. Upgrade from 20.1.9 to 20.7
2. Go to 'Services'
3. Click on 'Postfix'
4. Click on 'Logfile'
5. Verify that the log is empty.

Also the logfile /var/log/postfix.log is present but empty.
In /var/log/mail.log are the logs until the upgrade-process.

**Expected behavior**
The logs should be there.

**Screenshots**
No.

**Relevant log files**
/var/log/postfix.log
(/var/log/mail.log)

**Additional context**
No Remote-Logging is used.
Syslog-ng struggled to start sometimes.
I tried also resetting all log files, but without effect.
Other logfiles are present.

**Environment**
OPNsense 20.7.1 (amd64, OpenSSL).
Intel® Xeon™ E3-1225V5 3.3Ghz Quad Core
Network Intel® I210-AT
(2 x DEC4630 HA)

**Comment by mimugmail** [comment]
This was fixed with 20.7.1 and reported to work. Can you disable circular and restart one or two times?

**Comment by AndyX90** [comment]
That was it! 
I did disable the circular-logs without effect, but reboot fixed it.
Thanks again!
