### ISSUE TITLE
os-bind: zone transfer "none" allows zone transfer by default

### ISSUE THREAD

**Issue by laoclos** [opnsense/plugins#1981]
### Information

- Plugin version: 1.13
- Package version: bind 9.16.5_1
- Configuration URI: /ui/bind/general/index#domains

### Problem
A master zone has "Allow Transfer" option to choose which ACL the server allows for transfer requests,
but if you select the option "_none_" there is no `allow-transfer {none;};` option set in `named.conf`. 

**This allows a zone transfer per default, which states a security risk** 

### Possible solutions

   Add `allow-transfer {none;}` if "_none_" is selected.

### Workarounds

A) Create an ACL for e.g. _127.0.0.1_ and chose this in the "Allow Transfer" option. 

B) Block TCP Queries in Firewall for DNS/BIND Port (e.g. 53), since zone transfer is done via TCP.

**Comment by mimugmail** [comment]
Not sure how to proceed here.
None should be default, if one requires security an acl can be added to it.

**Comment by laoclos** [comment]
> None should be default, if one requires security an acl can be added to it.
Maybe it should be made clear that "none" does not mean no zone transfer allowed. 
I assumed, if I select "none" there is no possibility to transfer a zone, which is not the case.

**Comment by laoclos** [comment]
Maybe it would be possible to add an Option "NoACL" to the drop down list to have the choice between, "NoACL", "None" and the defined ACLs. "None" is in my Opinion a bad label in the bind context for saying there is no ACL configured.

**Comment by mimugmail** [comment]
Give me a week when I am back at a Computer to think about it

**Comment by mimugmail** [comment]
Ok, I had a look. The problem is that OPNsense calls nothing selected as `none` but BIND uses none as noone. So this is a bit misleading when coming from BIND. As I don't want to break current setups where things work cause of not using an ACL, I'd suggest to enhance the help-text that transfer is allowed from everywhere when nothing is set.
