### ISSUE TITLE
www/nginx: The GUI parameter "Verify Certificate" does not do anything

### ISSUE THREAD

**Issue by 8191** [opnsense/plugins#1986]
**Describe the bug**
The GUI parameter "TLS: Verify Certificate" of an Upstream does not do anything; Nginx always successfully connects to the upstream, regardless of the checkbox.

**To Reproduce**
Preconditions:
A working Nginx config which acts as a proxy for a page which is upstreamed via HTTPs and an _invalid certificate_.

1. Go to Upstream > Upstream > Edit
2. Check 'TLS: Verify Certificate'
3. Connect via HTTP to the configured Nginx instance
4. The proxied page is successfully displayed even the certificate could not be verified. 

**Expected behavior**
Nginx shall not connect to the upstream and display an error to the end-user.

**Comment by kulikov-a** [comment]
agree. location.conf template does not contain proxy_ssl_verify directive at all.
IMHO location.conf template not updated very long time
SNI directives also not works as expected

**Comment by 8191** [comment]
@AdSchellevis Any chance to pull #1987 for the next release?

**Comment by AdSchellevis** [comment]
@8191 since @fabianfrz is the maintainer, we should ask him if we can pull it in. to me it looks like a good addition, although the model change needs a version upgrade and might be backwards incompatible (removing the url attribute).

**Comment by fabianfrz** [comment]
@AdSchellevis I did the review and yes, I think the model change is needed all the other things are ok beside the whitespace (@8191 probably used some windows editor which is not set up for spaces)

**Comment by 8191** [comment]
Fixed by merging #1987
