### ISSUE TITLE
UPnP stops responding when connection cleared

### ISSUE THREAD

**Issue by Taomyn** [opnsense/plugins#1988]
**Describe the bug**
When connections are cleared in the UPnP service, it then no longer responds to any new requests either for new connections or even a status. To clear the condition I am forced each time to disable UPnP and then re-enable it - even a restart of the service fails.

**To Reproduce**
1. Disable UPnP
2. Enable UPnP
3. Make UPnP connection from client machine
4. Clear the connection
5. Attempt to make new connection or get status

**Expected behavior**
New connections/status should work

**Environment**
OPNsense 20.7.2-amd64
FreeBSD 12.1-RELEASE-p8-HBSD
LibreSSL 3.1.4
os-upnp v1.4

**Comment by bsd-source** [comment]
I can confirm once OPNsense Universal Plug and Play --> Status clear button is selected the status entries are cleared and will not show additional information until the miniupnpd service is stopped and started again.

**Comment by Taomyn** [comment]
Just to be clear, my experience is that no UPnP sessions can be made until the service is restarted, it's not a visual problem.

**Comment by Taomyn** [comment]
I'm up to 20.7.3 now, and this still happens. For whatever reason once a session drops the service is stuck not responding to further connections until I disable then re-enable uPnP.

**Comment by Taomyn** [comment]
Can anyone help me to possible get this fixed?

I tried uninstalling and reinstalling the plugin and deleting the one file I could find that had my config so I could start again, but on the next install they were still there.

If someone could point me at where I can really delete my old config I would like to try again.

**Comment by mimugmail** [comment]
You can edit /conf/config.xml with your favourite editor and remove the xml section.

**Comment by Taomyn** [comment]
@mimugmail thanks, that cleared them but when I reinstalled and tried to set things up I get on a blank web page:

`Warning: Illegal string offset 'miniupnpd' in /usr/local/www/services_upnp.php on line 158 Fatal error: Uncaught Error: Cannot use string offset as an array in /usr/local/www/services_upnp.php:158 Stack trace: #0 {main} thrown in /usr/local/www/services_upnp.php on line 158`

**Comment by Taomyn** [comment]
I fixed it, when I cleared out the old setting from config.xml I left it as:

```
  <installedpackages>
  </installedpackages>
```

So I deleted those as well and now I can save settings.

Now to test........

**Comment by Taomyn** [comment]
Have tested all this weekend and so far the UPnP service has held up and worked all the time. The only thing I have not been able to do is perform a restart of the firewall to be sure it still works afterwards. I hope to do that tonight and then test tomorrow.

Unfortunately the copy of the generated config file I made has gone missing so I can't use it to compare it with the new one to see if I can spot any differences.
