### ISSUE TITLE
os-postfix in 20.7.1 breaks smtpd_sasl_auth

### ISSUE THREAD

**Issue by fhloston** [opnsense/plugins#1990]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

[x] The title contains the plugin to which this issue belongs

**Describe the bug**

os-postfix in 20.7.1 does not know smtpd_sasl_auth_enable anymore:

`postconf: warning: /usr/local/etc/postfix/main.cf: unused parameter: smtpd_sasl_auth_enabled=yes`

`opnsense-revert -r 20.7 os-postfix` reverts to working smtpd sasl auth

working: os-postfix-1.14_1
broken: os-postfix-1.15

**Comment by fichtner** [comment]
You mean this change? oO

https://github.com/opnsense/plugins/commit/629e73451e335d

**Comment by fhloston** [comment]
So weird. I cannot reproduce this error. I have been upgrading/reverting os-postfix several times.

It happened initially on both nodes on the upgrade from 20.7 to 20.7.1.

**Comment by fhloston** [comment]
I guess it was something that only happened during the initial update in regard to the used libraries.
