### ISSUE TITLE
security/acme-client: Health check shows missing files

### ISSUE THREAD

**Issue by chris42** [opnsense/plugins#2001]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

[X] The title contains the plugin to which this issue belongs

**Describe the bug**
When running health check in the firmware section, I get the following errors:
```
>>> Check for missing or altered package files
Checking all packages: 
acme.sh-2.8.6_2: missing file /var/db/acme/.acme.sh/account.conf.sample
acme.sh-2.8.6_2: missing file /var/db/acme/.acme.sh/deploy
acme.sh-2.8.6_2: missing file /var/db/acme/.acme.sh/dnsapi
acme.sh-2.8.6_2: missing file /var/db/acme/.acme.sh/notify
Checking all packages............. done
```

**To Reproduce**
Steps to reproduce the behavior (freely translated from German):
1. Go to System - Firmware - Updates
2. Use Audit - Health to trigger health audit

**Expected behavior**
Not error messages

**Relevant log files**
Full health check
```
***GOT REQUEST TO AUDIT HEALTH***
>>> Check installed kernel version
Version 20.7.1 is correct.
>>> Check for missing or altered kernel files
No problems detected.
>>> Check installed base version
Version 20.7.1 is correct.
>>> Check for missing or altered base files
No problems detected.
>>> Check for and install missing package dependencies
Checking all packages: .......... done
>>> Check for missing or altered package files
Checking all packages: 
acme.sh-2.8.6_2: missing file /var/db/acme/.acme.sh/account.conf.sample
acme.sh-2.8.6_2: missing file /var/db/acme/.acme.sh/deploy
acme.sh-2.8.6_2: missing file /var/db/acme/.acme.sh/dnsapi
acme.sh-2.8.6_2: missing file /var/db/acme/.acme.sh/notify
Checking all packages............. done
>>> Check for core packages consistency
Checking core packages: .................................................................... done
***DONE***
```

**Comment by fichtner** [comment]
Just reinstall package. This is a local error, not something that can be solved from here.

**Comment by chris42** [comment]
Ok, that solved it. Thanks!
