### ISSUE TITLE
netdata: opt-out from sending anonymous statistics

### ISSUE THREAD

**Issue by kulikov-a** [opnsense/plugins#2003]
Hi!
According to 
https://github.com/netdata/netdata/blob/master/docs/anonymous-statistics.md
"Starting with v1.12, Netdata collects anonymous usage information by default and sends it to Google Analytics"
GUI does not contain option to opt-out from sending anonymous statistics.
So is netdata installing with "--disable-telemetry" option or i should disable it by hand?
Thanks!

**Comment by mimugmail** [comment]
You can close this one, already implemented vi ports:
https://github.com/opnsense/ports/blob/master/net-mgmt/netdata/Makefile#L133

**Comment by kulikov-a** [comment]
wow, already forgot about it. thanks!

**Comment by mimugmail** [comment]
Checking the issues I'm assigned to :)
