### ISSUE TITLE
Let's Encrypt daily auto-renew failing with "is not a issued domain, skip"

### ISSUE THREAD

**Issue by Taomyn** [opnsense/plugins#2007]
**Describe the bug**
Since upgrading from 20.1 to 20.7 the auto-renew has been failing with "is not a issued domain, skip" for all my previously issued domains. If I renew any of them manually it works. Firewall has been rebooted many times and there are no networking issues as running the cron task manually also fails.

**To Reproduce**
1. Wait for daily auto-renew or manually run "/usr/local/sbin/configctl acmeclient cron-auto-renew"
2. Check log

**Expected behavior**
Certificates should be renewed

![image](https://user-images.githubusercontent.com/4365929/91632119-f0315d80-e9de-11ea-8d28-7c374ea7130a.png)

**Relevant log files**
Names changed for protection:
```
[Sat Aug 29 00:00:03 CEST 2020]	'mysubdomain1.mydomain.com' is not a issued domain, skip.
[Sat Aug 29 00:00:03 CEST 2020]	Renew: 'mysubdomain1.mydomain.com'
[Sat Aug 29 00:00:03 CEST 2020]	DOMAIN_PATH='/var/etc/acme-client/home/mysubdomain1.mydomain.com'
[Sat Aug 29 00:00:03 CEST 2020]	ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Sat Aug 29 00:00:02 CEST 2020]	'mysubdomain2.mydomain.com' is not a issued domain, skip.
[Sat Aug 29 00:00:02 CEST 2020]	Renew: 'mysubdomain2.mydomain.com'
[Sat Aug 29 00:00:02 CEST 2020]	DOMAIN_PATH='/var/etc/acme-client/home/mysubdomain2.mydomain.com'
[Sat Aug 29 00:00:02 CEST 2020]	ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Sat Aug 29 00:00:01 CEST 2020]	'mysubdomain3.mydomain.com' is not a issued domain, skip.
[Sat Aug 29 00:00:01 CEST 2020]	Renew: 'mysubdomain3.mydomain.com'
[Sat Aug 29 00:00:01 CEST 2020]	DOMAIN_PATH='/var/etc/acme-client/home/mysubdomain3.mydomain.com'
[Sat Aug 29 00:00:01 CEST 2020]	ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
```

**Environment**
OPNsense 20.7.1-amd64
FreeBSD 12.1-RELEASE-p8-HBSD
LibreSSL 3.0.2
os-acme-client (installed) | 1.35 | 389KiB | Let's Encrypt client

**Comment by fraenki** [comment]
You could try to forcefully re-issue the certificate, there's a button to do so.

**Comment by Taomyn** [comment]
> You could try to forcefully re-issue the certificate, there's a button to do so.

I know that works as stated -  `If I renew any of them manually it works` - this happened a few weeks ago as well but there was only one or two needing to be renewed, and forcing them worked, so I thought this tim I would leave these as is for troubleshooting. I have 16 days before the first one expires.

**Comment by Taomyn** [comment]
I just updated to OPNsense v20.7.2 and waited for the daily job to run - same problem. I tried the new option to re-run the automated job for one of the failed certificates and it too fails:

`
2020-09-03T07:12:19 | opnsense[40904] | /usr/local/opnsense/scripts/OPNsense/AcmeClient/certhelper.php: AcmeClient: failed to run automation, certificate status not OK: mysubdomain.mydomain.com
`

So I forcefully re-issued the same certificate, the oldest of the ones failing, and it worked just fine.

`
[Thu Sep 3 07:17:37 CEST 2020] | _on_issue_success
`

**Comment by fraenki** [comment]
> So I forcefully re-issued the same certificate, the oldest of the ones failing, and it worked just fine.

This sounds to me like running the "issue" command twice results in a successful validation.

Which acme.sh challenge type (validation method) are you using?

**Comment by Taomyn** [comment]
> > So I forcefully re-issued the same certificate, the oldest of the ones failing, and it worked just fine.
> 
> This sounds to me like running the "issue" command twice results in a successful validation.

No, re-running the daily issue repeats the problem, and no certificate is generated. Only doing a single "forcefully re-issue" will succeed in getting a renewed certificate.

> 
> Which acme.sh challenge type (validation method) are you using?

HTTP-01

**Comment by fraenki** [comment]
In my experience HTTP-01 can be pretty unreliable. I'd suggest to switch to DNS-01 if your DNS provider is supported.

That being said the upcoming os-acme-client version 2.0 is a major rewrite and logs addition debug messages. Maybe this helps to identify the root cause of this issue, if you can't switch to DNS-01.

**Comment by Taomyn** [comment]
> In my experience HTTP-01 can be pretty unreliable. I'd suggest to switch to DNS-01 if your DNS provider is supported.
> 
Hasn't been for me until this release, so I checked and my DNS provider, Azure DNS, is listed but I can't find anywhere documentation on how to set it up on the Azure side so I can fill in all the fields:

![image](https://user-images.githubusercontent.com/4365929/93046437-12bbab80-f65a-11ea-8464-e12c4bfd8fd9.png)

> That being said the upcoming os-acme-client version 2.0 is a major rewrite and logs addition debug messages. Maybe this helps to identify the root cause of this issue, if you can't switch to DNS-01.

It would be nice to log some extra info as it's not showing anything for me at the moment.

**Comment by Taomyn** [comment]
Scratch the idea that it's HTTP, I continued to dig around with Google trying to find instructions on setting up Azure DNS and eventually got that sorted in OPNsense. I switched LE to the staging environment then created a new test certificate and force issued it - worked perfectly. I could see the validation record appear in Azure and then the certification was validated, created a certificate and the record got removed. So I switched LE back to production and switched one of the failing ones to use DNS. I ran the daily script from the shell - it failed the same way.

BTW, the option to "delete" a certificate within the LE plugin, it repeatedly asks for confirmation and requires a browser refresh to clear - the certificate is still deleted though.

**Comment by Taomyn** [comment]
Quick update, after upgrading to 20.7.3 this week along with switching from the LibreSSL to OpenSSL build of OPNsense, I just checked and I think the problem has resolved itself. I see some new renewals since the upgrade.

So either the update/switch fixed it, or by force renewing each of the failing certificates it somehow fixed them - unfortunately I cannot prove the latter for some months when the failing ones are due again for auto renewal.

**Comment by fraenki** [comment]
> It would be nice to log some extra info as it's not showing anything for me at the moment.

os-acme-client 2.0 will contain additional debug output, hopefully this will make it easier to analyze and fix such issues in the future.

**Comment by Taomyn** [comment]
Thanks @fraenki automated renewals still working fine for now, but as you say this will help

**Comment by JairoMarques** [comment]
@Taomyn did you find all Azure DNS information to fill in?
Azure has for each secret an "id" and a "secret value" but unfortunately I can't do this plugin to generate my certificate.
Any help will be very appreciated

**Comment by fraenki** [comment]
@JairoMarques Please don't post on old issues, instead open a new issue for your problem or post on the [forums](https://forum.opnsense.org/).
