### ISSUE TITLE
FRR add BGP community-list support

### ISSUE THREAD

**Issue by nzkiwi68** [opnsense/plugins#2011]
I need to accept the newer **bgp-community** list format from my upstream provider.
Can we please add bgp community-list support?

This is all well supported in FRR, just missing from the OPNsense GUI configuration.
[http://docs.frrouting.org/en/latest/bgp.html#community-lists](url)

OPNsense GUI would need the following items;

- The ability to **add or change** a community-list
- **Use in route maps** the community-list

Example Configuration (lifted from FRR documents)
`router bgp 7675`
` neighbor 192.168.0.1 remote-as 100`
 `address-family ipv4 unicast`
`  neighbor 192.168.0.1 route-map RMAP in`
` exit-address-family`
`!`
`bgp community-list 70 permit 7675:70`
`bgp community-list 70 deny`
`bgp community-list 80 permit 7675:80`
`bgp community-list 80 deny`
`bgp community-list 90 permit 7675:90`
`bgp community-list 90 deny`
`!`
`route-map RMAP permit 10`
` match community 70`
` set local-preference 70`
`!`
`route-map RMAP permit 20`
` match community 80`
` set local-preference 80`
`!`
`route-map RMAP permit 30`
` match community 90`
` set local-preference 90`

**Comment by mimugmail** [comment]
Ok, quick summarize:

- adding route-maps to neighbors already in place
- add a new tab for bgp community-lists like with prefix-lists
- add a match against community in route-maps 

Correct?

**Comment by nzkiwi68** [comment]
Yes, thanks.

**Comment by mimugmail** [comment]
Ok, seems I'm finished, will add a PR:


```
Building configuration...

Current configuration:
!
frr version 7.4
frr defaults traditional
hostname OPNsense.localdomain
log file /var/log/frr.log informational
!
router bgp 65003
 no bgp ebgp-requires-policy
 neighbor 31.24.36.163 remote-as 333
 neighbor 31.24.36.163 ebgp-multihop 255
 neighbor 172.16.32.2 remote-as 444
 neighbor 172.16.32.2 ebgp-multihop 255
 neighbor 2001:db8:1::1 remote-as 65112
 neighbor 2001:db8:1::1 update-source wan
 neighbor 2005:dba::1 remote-as 333
 neighbor 2005:dba::1 ebgp-multihop 255
 !
 address-family ipv4 unicast
  network 10.10.10.0/24
  no neighbor 2001:db8:1::1 activate
  no neighbor 2005:dba::1 activate
 exit-address-family
 !
 address-family ipv6 unicast
  neighbor 2001:db8:1::1 activate
  neighbor 2001:db8:1::1 next-hop-self
  neighbor 2005:dba::1 activate
 exit-address-family
!
ip prefix-list test-test seq 16 permit 10.3.3.0/24
ip prefix-list test_test33Q seq 16 permit 10.3.3.0/24
ip prefix-list v4 seq 12 permit 10.10.10.0/24
!
ipv6 prefix-list v6 seq 32 permit 2001:dba:99::/56
!
bgp as-path access-list 44 permit .$
!
bgp community-list 20 seq 10 permit 40:30
bgp community-list 20 seq 15 permit 50:50
bgp community-list 25 seq 10 permit 1:1
!
route-map test12 permit 77
 match ipv6 address prefix-list v6
 set local-preference 200
!
route-map test14 permit 25
 match community 25
!
line vty
!
end
```
