### ISSUE TITLE
net/frr/diagnostics/log: present the log from most recent to the oldest or Allow to sort by DateTime

### ISSUE THREAD

**Issue by TekunoKage** [opnsense/plugins#2012]
Would be good to have the log presented in reverse order (The most recent at the top).

If an optimal implementation is desirable, a filter would be great. A Date range, Time range, Service, and a keyword on the message. Wishful Thinking...

I really enjoy your plugging for OpnSense! Thanks for your effort.

Regards,

**Comment by QDaniel** [comment]
A tail for last 5000 lines are nice ...
And truncate for the log on frr restart to the latest 5MB would nice.

When i log in verbose mode after time the log are very big and the interface hangs for minutes when the log will be shown.

**Comment by marcquark** [comment]
this should be fine now in 1.19
