### ISSUE TITLE
PC Engines APU2 firmware updater plugin

### ISSUE THREAD

**Issue by jokay** [opnsense/plugins#2014]
Do you think it would be possible to have a plugin which allows to update the firmware of a [PC Engines APU2](https://pcengines.ch/apu2.htm) device directly from the web-UI?

Currently I use this [firmware updater script](https://github.com/pcengines/apu2-documentation/blob/1034963eaf085eb54fb76b84223b05564f409d00/scripts/apu_fw_updater_opnsense.sh).

Is it even possible to have this executed with `root` permissions within the "plugin context"?

What do you think?

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Plugin to be able to update the PC Engines APU2 firmware directly from the web-UI.

**Describe alternatives you've considered**
Continue the "manual" update procedure using the script.

**Comment by soder10** [comment]
You need to poweroff the APU completely after the update finished, otherwise the firmware update may stay in an unpredictable state (its documented on pcengines.github.io). Soft-Reboot is insufficient, you have to power cycle the board.

**Comment by x-jokay** [comment]
@soder10 the [script](https://github.com/pcengines/apu2-documentation/blob/master/docs/firmware_flashing.md#apu-firmware-updater-for-opnsense) was merged to the official documentation. Used it several times doing remote upgrades followed by a remote reboot only and hadn't any problems until now. Not sure if the power cycle is still needed 🧐 or may be only for the legacy firmware.

**Comment by MattElekHarris** [comment]
Are there any plans of implementing this? Full power cycles appear to be possible using a command like `pciconf -w pci0:24:0 0x6c 0x580ffe10` as documented [here](https://github.com/pcengines/apu2-documentation/blob/master/docs/firmware_flashing.md#corebootrom-flashing), and as previously stated, there's already a script for it.
