### ISSUE TITLE
security/acme-client: Add automation action "Reconfigure IPsec service"

### ISSUE THREAD

**Issue by stumbaumr** [opnsense/plugins#2019]
**Is your feature request related to a problem? Please describe.**
I configured the automation action to restart the IPsec VPN service after aquiring a new LE certificate. If I re-issue a certificate now all IPsec clients get obviously disconnected. I would like the service to be available the whole time.

**Describe the solution you'd like**
Instead of using "Restart IPsec VPN Service" as added in https://github.com/opnsense/core/pull/3755 triggered by https://github.com/opnsense/plugins/issues/1534 it would be better to change it to use the `[reconfigure]` action in src/opnsense/service/conf/actions.d/actions_ipsec.conf .
There might be users who really want to restart their IPsec VPN service by a cron task. So I would still keep that option.

**Describe alternatives you've considered**
Triggering the LE cert update during the night - but then it is hard to debug the process if there is something wrong...

**Comment by fraenki** [comment]
Waiting for the core PR to be merged, nothing left to do for me :)
