### ISSUE TITLE
net/haproxy: advanced timeout / connection Options

### ISSUE THREAD

**Issue by bluesource** [opnsense/plugins#202]
Hi,

I would love to see some advanced timeout / connection Options in the GUI :)

* timeout http-request (slowloris attacks)

* Limiting TCP Connection Rate, abuse Unfair users, etc. (as described in https://www.haproxy.com/blog/use-a-load-balancer-as-a-first-row-of-defense-against-ddos/)

Thanks and regards,
Michael

**Comment by fraenki** [comment]
Thanks for your feature request! :) I'll try to add these features in one of the next feature releases.

**Comment by fraenki** [comment]
I've added all the bits and pieces. Now our GUI supports more powerful rules than ever. Thanks again for your feature request!

**Example: Limiting the number of connections per user to 3**


- **(1.) create the following condition:**

![01](https://user-images.githubusercontent.com/909706/34920522-7f94de4c-f974-11e7-81d9-a205a70b0899.png)

- **(2.) create the following rule:**

![02](https://user-images.githubusercontent.com/909706/34920524-819feb5a-f974-11e7-829e-f89b75f2eed4.png)

- **(3.) enable stickiness in the "Public service" (frontend):**

![03](https://user-images.githubusercontent.com/909706/34920527-8418f3d6-f974-11e7-8d66-5d28810043f8.png)

- **(4.) add the rule to the "Public service" (frontend):**

![04](https://user-images.githubusercontent.com/909706/34920529-85ac1764-f974-11e7-994b-20f86b6d6f7a.png)

While it may not be perfect, most rules should just work. I'm interested in hearing feedback and seing real-world rules and use-cases.
