### ISSUE TITLE
Set Web-Proxy user-acl before global blacklist

### ISSUE THREAD

**Issue by tomatotoast** [opnsense/plugins#2024]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

[x] When the request is meant for an existing plugin, I've added its name to the title.

This request is related to:
"[bug] [proxy] Blacklist is evaluated before custom whitelist, groups acl broken"
https://github.com/opnsense/plugins/issues/1111

**Describe the solution you'd like**
i would like to have the option to select between different behaviours.

Currently the Squid configuration looks like this:

![grafik](https://user-images.githubusercontent.com/60579201/92638007-ee6a7280-f2d9-11ea-80cf-806b2e1f28b8.png)

It would be great if it looks more like this:
![grafik](https://user-images.githubusercontent.com/60579201/92638149-270a4c00-f2da-11ea-9083-1cf6a3985e41.png)

A button on the webinterface that would allow setting the user-acl lists in front of the global blacklists would be nice.

So that the user could decide over the behaviour.

For me this little change would my life much easier.

**Comment by tomatotoast** [comment]
Why did you mark this as "support"? From my perspective this is a feature request. I guess customers would also like the feature of being able to give certain user groups white list rights for specific websites while the global blacklists still is active.

**Comment by AdSchellevis** [comment]
We have had discussions in the past on where we should include custom overrides, which resulted in the current default. Adding more toggles which are hard to explain likely won’t help the general population. 

You can always override our default template with one of your own, hence the support tag.
