### ISSUE TITLE
net/haproxy: Action and ACL rules generated to incorrect block

### ISSUE THREAD

**Issue by admlko** [opnsense/plugins#2027]
**Describe the bug**
One frontend for HTTPS, multiple backends which all have their own ACL and Action rules. ACL is used to check the path (subfolder) and Action is used to match ACL to the correct Backend.

This configuration results ACL and Action rules to be generated inside each Backend block, which is incorrect. They should be generated under Frontend block.

**To Reproduce**
1. Go to 'Services/HAProxy/Settings'
2. Click on 'Real Servers' and add at least two servers
3. Click on 'Virtual Servers' and add the same amount of entries as the number of 'Real Servers'
4. Click on 'Public Servers' and add one for HTTPS
5. Click on 'Rules & Checks/Conditions'
6. Add one 'Path starts with' condition for each 'Virtual Server' defined in the step number 3.
7. Click on 'Rules & Checks/Rules'
8. Add one rule for each 'Virtual Server' defined in the step number 3.
9. Rule definition matches the Condition to the Backend pool. For example, if path starts with /checkmk/, use Backend pool named 'Checkmk'.
10. Click on 'Virtual Servers' and go through all instances created in step number 3, and add the rule created in the step 9 for each of them in the 'Rules/Selected Rules' section. So, one rule per one Virtual Server.
11. Try to check config syntax and apply it. It fails.

**Expected behavior**
Syntax should be okay and the config should get applied.

**Relevant config files**
/usr/local/etc/haproxy.conf

**Incorrectly generated config**
```
# Frontend: HTTPS ()
frontend HTTPS
    http-response set-header Strict-Transport-Security "max-age=15768000; includeSubDomains; preload"
    bind 0.0.0.0:4433 name 0.0.0.0:4433 ssl no-sslv3 no-tlsv10 no-tlsv11 no-tls-tickets ciphers ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256 alpn h2,http/1.1 crt-list /tmp/haproxy/ssl/5f43e861ecd554.84319585.certlist
    mode http
    option http-keep-alive
    option forwardfor
    # tuning options
    timeout client 30s

    # logging options

# Backend: Checkmk ()
backend Checkmk
    # health checking is DISABLED
    mode http
    balance source
    # stickiness
    stick-table type ip size 50k expire 30m
    stick on src
    # tuning options
    timeout connect 30s
    timeout server 30s
    # ACL: Checkmk
    acl acl_5f5c6f566752f6.38264457 path_beg -i /checkmk/

    # ACTION: Checkmk
    use_backend Checkmk if acl_5f5c6f566752f6.38264457
    http-reuse safe
    server Checkmk 192.168.123.123:8080
```

**Working configuration fixed by hand**
```
# Frontend: HTTPS ()
frontend HTTPS
    http-response set-header Strict-Transport-Security "max-age=15768000; includeSubDomains; preload"
    bind 0.0.0.0:4433 name 0.0.0.0:4433 ssl no-sslv3 no-tlsv10 no-tlsv11 no-tls-tickets ciphers ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256 alpn h2,http/1.1 crt-list /tmp/haproxy/ssl/5f43e861ecd554.84319585.certlist
    mode http
    option http-keep-alive
    option forwardfor
    # tuning options
    timeout client 30s

    # logging options

    # ACL: Checkmk
    acl acl_5f5c6f566752f6.38264457 path_beg -i /checkmk/

    # ACTION: Checkmk
    use_backend Checkmk if acl_5f5c6f566752f6.38264457

# Backend: Checkmk ()
backend Checkmk
    # health checking is DISABLED
    mode http
    balance source
    # stickiness
    stick-table type ip size 50k expire 30m
    stick on src
    # tuning options
    timeout connect 30s
    timeout server 30s
    http-reuse safe
    server Checkmk 192.168.123.123:8080
```

**Environment**
OPNsense 20.7.2-amd64
FreeBSD 12.1-RELEASE-p8-HBSD
OpenSSL 1.1.1g 21 Apr 2020
os-haproxy 2.24

I thought this got fixed by #1925 but it doesn't seem to be the case.

**Comment by fraenki** [comment]
> This configuration results ACL and Action rules to be generated inside each Backend block, which is incorrect. They should be generated under Frontend block.

I quickly checked the code and there is no way this could happen. Please double-check your configuration.

**Comment by admlko** [comment]
What can I say, it happened. And still does :)
I created the config with previous version of os-haproxy, after the latest update I deleted all virtual servers, rules and conditions and re-added them. Same result.

So, what do you suggest I double-check?
Do you want screenshots or...?

**Comment by fraenki** [comment]
Glad you got it working!
