### ISSUE TITLE
Quagga: static route redistribution

### ISSUE THREAD

**Issue by cultcom** [opnsense/plugins#203]
Quagga currently ignores static routes set by "system/routes". To redistribute static routes you have to manually inject those to the zebra process with vtysh or the zebra.conf file...

**Comment by mimugmail** [comment]
@cultcom Yes that's a known issue and ATM unresolvable. Can you try with kernel routes?

**Comment by cultcom** [comment]
Well, I can add routes manually with vtysh, but you asked me in IRC to open a ticket for the issue to discuss it...

**Comment by mimugmail** [comment]
Yes, but when you set a route via System/Routes it should be in kernel, so redistribute kernel instead of static should do the trick

**Comment by cultcom** [comment]
Ah, good point, I will try that the next time. Currently the topology changed so that I don't need it anymore.

**Comment by mimugmail** [comment]
Great, would you mind closing the issue and reopen if it still occurs next time?

Thanks!

**Comment by cultcom** [comment]
sure
