### ISSUE TITLE
net/haproxy: Add possibility to view generated haproxy config in the webui

### ISSUE THREAD

**Issue by sorano** [opnsense/plugins#2035]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

[X] When the request is meant for an existing plugin, I've added its name to the title.

**Describe the solution you'd like**
When troubleshooting issues in haproxy it sometimes helps to look at the generated config file rather than browsing between different settings in the webui. Adding a view of the generated config file ( /usr/local/etc/haproxy.conf ) in the webui would make it easier instead of having to view the file via ssh.

**Comment by fraenki** [comment]
This will be available in the upcoming os-haproxy version 3.0.
