### ISSUE TITLE
net/haproxy: add support for proxy names for frontend and backend

### ISSUE THREAD

**Issue by sepahewe** [opnsense/plugins#2040]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

[x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
Today the plugin requires, and validates, that a correct ip or FQDN is entered for frontend and backend host. This prevents entering proxynames which is required to configure HAProxy for a looped setup. In those cases you configure a backend with a proxyname "MyProxy_12" and a frontend with the same proxyname "MyProxy_12". Any data sent to that backend is then directly sent to the frontend. This is needed for instance when you have to have different SSL configurations on the same port, like client certificate authentication for one application but not the rest.

The following config line is valid:
bind www.mydomain.com:443 ...
but this one is unfortunately invalid:
bind MyProxy_12 ...

**Describe the solution you'd like**
The data validation on the input form should allow proxy names. The allowed syntax is found in chapter 4 "Proxies" in HA documentation (http://cbonte.github.io/haproxy-dconv/2.2/configuration.html#4). 

The following config line should  be valid:
bind MyProxy_12 ...

**Describe alternatives you've considered**
I cannot find an alternative but editing haproxy.conf manually and preventing any future GUI changes.

**Additional context**
No changes needed in HAproxy, just a less strict data validation.

**Comment by fraenki** [comment]
@sepahewe Could you please provide a full haproxy.conf demonstrating the desired configuration?

**Comment by sepahewe** [comment]
Here is an example that has a first frontend "combined" that distinguishes between TLS and non-TLS, based on that it sends it to different backends "plain_loopback" and "tls_loopback". These backends loops it back using proxy names ("abns@haproxy-plain" and "abns@haproxy-tls") to new frontends "fix_tls" and "fix_plain".

`# MAIN FRONTEND LISTENING FOR CLIENT CONNECTIONS
frontend combined
  mode tcp
  log global
  option tcplog
  bind *:9018

  tcp-request inspect-delay 2s
  tcp-request content accept if { req.ssl_hello_type 1 }

  # use the tls loopback backend if SSL handshake
  use_backend tls_loopback if { req.ssl_hello_type 1 }

  # use default backend for everything else
  default_backend plain_loopback

# backend proxying to plain/unencrypted front-end
backend plain_loopback
  mode tcp
  server loopback-for-plain abns@haproxy-plain send-proxy-v2

# backend proxying connection to TLS front-end
backend tls_loopback
  mode tcp
  server loopback-for-tls abns@haproxy-tls send-proxy-v2

# proxy accept loopback - used as TLS termination proxy unencrypting traffic before sending to the main backend
frontend fix_tls
  mode tcp
  log global
  option tcplog
  bind abns@haproxy-tls accept-proxy ssl crt /etc/ssl/tlsproxy/tlsproxy.pem
  default_backend fix-backend

# proxy accept loopback - used as plain proxy to forward unencrypted traffic to the main backend as it is
frontend fix_plain
  mode tcp
  log global
  option tcplog
  bind abns@haproxy-plain accept-proxy
  default_backend fix-backend

# main backend server to route to - only working with unencrypted connections
backend fix-backend
  mode tcp
  log global
  option tcplog
  server quickfix 127.0.0.1:9008 check`

**Comment by fraenki** [comment]
According to the [HAProxy documentation](http://cbonte.github.io/haproxy-dconv/2.2/configuration.html#4.2-bind), abstract namespace `abns@` are not supported on FreeBSD. However, using a UNIX socket `unix@` should work. I need to figure out the best way to make this configurable from the GUI. Contributions and mockups are welcome.

**Comment by fraenki** [comment]
@sepahewe Are you still interested in this feature? I'd need some help to verify if the following additions would satisfy your needs.

The code can be applied on a recent OPNsense installation like this:

```
opnsense-patch -c plugins 1aac7bde4b45482d706e54a6ba7a1614a1b57ac6 4d94864c93893cd043769019bdb568ff4d8e374b
```

As stated previously, `unix@` must be used because `abns@` is not supported, so I've added the following features:

1. Allow to configure UNIX sockets as a frontend's listen address by using the `unix@socket-name` pattern.
2. Allow to specify a UNIX socket as a server's address.

Steps to test this:
* Create a new frontend, add `unix@socket-test` as listen address.
* Create a new server, set type to "unix socket", choose the frontend with the unix@ listen address.
* Create a new backend, choose the previously created server. (Optionally enable the PROXY protocol.)

This results in the following test config:

```
frontend unix_socket_test
    bind unix@/tmp/haproxy/sockets/socket-test name unix@/tmp/haproxy/sockets/socket-test 
    mode tcp

backend plain_loopback
    mode tcp
    balance source
    server loopback_for_socket unix@/tmp/haproxy/sockets/socket-test send-proxy-v2 check-send-proxy
```

This config passes HAProxy syntax check and HAProxy creates the UNIX sockets on startup, but that's all I can test right now.

@sepahewe Could you verify that this allows you to build a working loopback config?

**Comment by fraenki** [comment]
I'll release the proposed state in os-haproxy 3.8. If something is missing or not working as expected, we can fix it in another release.
