### ISSUE TITLE
net/freeradius: toggle user password visibility

### ISSUE THREAD

**Issue by knxuf** [opnsense/plugins#2047]
Add button to show/hide user passwords.

**Comment by mimugmail** [comment]
There is no such option, but you can see the password in cleartext in /conf/config.xml or in the users file via CLI

**Comment by knxuf** [comment]
i know where to find them but it would be nice to make it visible from GUI in mobilephone, when the users forget their wlan password. Like in Unifi Controller.
But I understand what you mean, there is no option in templates to make it visible, just type password.
