### ISSUE TITLE
net/haproxy: 20.7 invented ordering problems

### ISSUE THREAD

**Issue by andreas-p** [opnsense/plugins#2048]
After upgrading from 20.1.9 to 20.7.2 (and still in 20.7.3), a haproxy ruleset will throw a warning:

```
[WARNING] 273/202100 (47599) : parsing [/usr/local/etc/haproxy.conf:86] : a 'redirect' rule placed after a 'use_backend' rule will still be processed before.
Configuration file is valid
```

Comparing what 20.1 generated vs. 20.7, the only difference is that two redirect and use_backend lines are swapped, triggering that warning.

While (according to the message) this isn't a functional problem, it seems better to avoid this warning. Since ordering of commands in the generated file is out of user's influence, this should be handled by the plugin correctly.

**Comment by fraenki** [comment]
> Since ordering of commands in the generated file is out of user's influence, this should be handled by the plugin correctly.

This statement might be true for previous version of os-haproxy, but the behaviour was changed in os-haproxy 2.24. This version removes all automatic ordering of rules and now you have full control over the sort order (see https://github.com/opnsense/plugins/issues/1925). The old behaviour was odd, unexpected and caused confusion.

The only drawback of this change is the warning message you're seeing. But this can be avoided by changing the ordering of your rules.
