### ISSUE TITLE
HAProxy - SNI TLS extension (TCP request content inspection) does not work as expected

### ISSUE THREAD

**Issue by tacticz** [opnsense/plugins#2062]
I searched the GitHub issue and didn't find a similar report.
Although a similar problem seems to be reported in the OPNsense forum: [HaProxy SSL passthrough trouble with SNI_contains rule](https://forum.opnsense.org/index.php?topic=17066.0)

Since I'm new to using OPNsense, I sincerely wish I'm not missing something obvious.

**Describe the bug**
In the HAProxy pluign, creating conditions that use the SNI TLS extension (TCP request content inspection) condition types does not seem to work as expected.

Rules that are using such conditions do not seem to apply correctly.

**To Reproduce**

- Have OPNsense with the HAProxy plugin installed
- Have a firewall rule allowing traffic hitting the firewall to local servers on port 80 and 443
- Have two "real servers" configured in HAProxy, each being setup to answer for different subdomains using TLS (i.e server 1 answers for https://test.domain.tld, server 2 answers for https://test2.domain.tld)
- Configure 2 backend pools, one for each server
- Create a condition checking if the SNI TLS extension of client requests matches test2.domain.tld
- Create a rule directing to backend 2 when the previosu SNI TLS condition is matched
- Create a Public service (frontend) using backend 1 (server 1) as default and applying the previous rule, then forcing usage of backend 2 (server 2)

**Expected behavior**
A client request made to the firewall using https://test2.domain.tld should be directed to server 2

**Effective behavior**
Traffic is directed to server 1, although the hostname matches the defined condition

**Additional context**
- The exact same configuration works using HTTP and the "Host starts with" (or other Host ...) conditions
- It has been verified that the SNI TLS extension is present in the client request
- Tests were made using the SNI TLS extension matches, contains and start with (TCP request content inspection)
- The "matches" condition occasionally worked but stopped working after being switched to "starts with" and then switched back
- The "regex" condition was tested (not working) but I'm unsure of the exact syntax to enter the regex since I couldn't find any example (start and end slashes required ?)  

**Environment**
OPNsense 20.7.3 (amd64, OpenSSL).
HAProxy 2.24

One last question: could you tell me where, on the OPNsense system, is the "raw" HAProxy configuration stored?
It would be useful to be able to inspect it in order to figure out where the problem might be.

Unfortunately my coding skills are not sufficient to allow me to delve into the plugin code and figure out whether I could help resolve the situation, thank you to anyone having a look at this!

Sincerely.

**Comment by tacticz** [comment]
Sorry, sorry and sorry!
My bad :-(

As I stated in my previous post:
**Since I'm new to using OPNsense, I sincerely wish I'm not missing something obvious.**

And obviously I DID MISS SOMETHING!

My mistake was that I didn't fully understand the way HAProxy Rules are to be established, thus I created two separate rules for the backend redirection, one for HTTP and the other for HTTPS. Then I applied BOTH rules in the "Select Rules" option of the Public Service (frontend) that I created, which is NOT the way it should be done.

I finally understood that what needs to be done is to create 2 conditions, one for HTTP checking the hostname, another for HTTPS checking the SNI (as I already did). But then those two conditions have to be applied INSIDE THE RULE redirecting to backend 2, in the "Select conditions" option, along with the OR logical operator for conditions.
Then, using this single rule in the Public service (frontend) definition works as expected...

Once again, sorry for the misunderstanding, but I guess I'm not the only one getting a bit confused when trying to understand how all the pieces of the complicated puzzle of a great software like OPNsense do fit together ;-)

Thank you;

**Comment by fraenki** [comment]
@tacticz Thanks for sharing your experience and the solution! I'm always open for ideas and recommentations, maybe the "Introduction" pages or the inline help could be improvded. Furthermore feel free to [contribue](https://github.com/opnsense/docs) to the [OPNsene HAProxy documentation](https://docs.opnsense.org/manual/how-tos/haproxy_howtos.html), for example you could add your example and describe the logic behind it. Just a thought... :)

> One last question: could you tell me where, on the OPNsense system, is the "raw" HAProxy configuration stored?

You'll find it at `/usr/local/etc/haproxy.conf` on your OPNsense system. There's also a feature request, so in a future release you should be able to download `haproxy.conf` from the GUI.
