### ISSUE TITLE
All plug-ins should have uninstall option that clears _all_ previous settings

### ISSUE THREAD

**Issue by Taomyn** [opnsense/plugins#2064]
**Is your feature request related to a problem? Please describe.**
Nearly every time I have tried to reinstall a plug-in that is misbehaving I find my old settings are still there. This might be fine for many occasions and even handy, but when you really want to eliminate the current config as the source of the problem and have a really clean start, you can't. At least not easily.

It's not always obvious by searching the entire file system which files they would be - take the uPnP plugin, I uninstalled then searched for *upnp* and found just one file, a config file that did have my settings. So I deleted it and reinstalled and found my settings come back.

**Describe the solution you'd like**
Option to clear all previous settings on uninstall of all plug-ins, or alternative it displays instructions on what files must be deleted or altered.

**Comment by curve1417** [comment]
Thats quite a decent idea
