### ISSUE TITLE
Startup issue Collectd and Freeradius

### ISSUE THREAD

**Issue by mimugmail** [opnsense/plugins#207]
@fichtner You did some follow-up changes to the rc.conf.d files, but I'm not sure how they behave.
I tried a fresh install of 17.7RC and collectd, but the service doesn't start when enabling it. It only starts after a reboot of the machine. When enabling the service and pressing start there's no error in browser debug mode and CLI, status returning ist "unknown". Also the rc.conf.d file is colloectd_enable="no".

I checked the setup script and it seems fine, but not executeable. Then I checked with Freeradius because you did the same changes there. The service starts fine after installtion, no reboot required. I also wanted to check how the setup script looks like, but it's not there?! 

Now I'm confused :)

**Comment by mimugmail** [comment]
Ah, the bootup log show a permission denied for collectd setup.sh and a file not found for freeradius setup.sh

**Comment by fichtner** [comment]
should be fixed on master now, sorry.

**Comment by mimugmail** [comment]
Great! What about the permissions for collectd file?

**Comment by fichtner** [comment]
<img width="638" alt="screen shot 2017-07-24 at 10 05 01 am" src="https://user-images.githubusercontent.com/1915288/28513751-a0f741d4-7057-11e7-8868-87cdc76cd6c6.png">

;)

I don't have time to confirm, so please close if really solved and sorry about the trouble.

**Comment by mimugmail** [comment]
Hm, when I look at the freeradius commit I wont see collectd :)

Ok, so for collectd it's fixed but for freeradius I get a:

![image](https://user-images.githubusercontent.com/20438689/28514174-6f8b5944-7059-11e7-9c52-85279f37ec21.png)

**Comment by fichtner** [comment]
<img width="584" alt="screen shot 2017-07-24 at 10 19 24 am" src="https://user-images.githubusercontent.com/1915288/28514454-4d98f0f2-705a-11e7-8e3d-ba1f276cf491.png">

:D

**Comment by fichtner** [comment]
ok, found the issue

**Comment by mimugmail** [comment]
All errors gone, thanks :)

**Comment by fichtner** [comment]
collectd doesn't reload the template on save

**Comment by mimugmail** [comment]
Really?


```
Jul 24 12:38:39 OPNsense configd.py: [28d76e73-5c2c-4929-b55c-9e438638f569] generate template OPNsense/collectd
Jul 24 12:38:39 OPNsense configd.py: [8b67e5c1-f284-47bf-8831-b14a72433a34] starting Collectd
Jul 24 12:38:39 OPNsense configd.py: [af61973f-cf32-4e53-9cad-d4f5b608424f] request Collectd status

```

**Comment by fichtner** [comment]
Have you tested with a clean config.xml? I hit enable, save, it saves but does not rewrite the template so the service won't start as well.

**Comment by mimugmail** [comment]
.. cloning a fresh clone ...

**Comment by mimugmail** [comment]
https://github.com/opnsense/plugins/blob/master/net-mgmt/collectd/src/opnsense/mvc/app/controllers/OPNsense/Collectd/Api/ServiceController.php#L136

Capital C I think ...

**Comment by fichtner** [comment]
my bad then, once again. will fix in a sec :)

**Comment by mimugmail** [comment]
No, my bad using Github Desktop for Windows :)

**Comment by fichtner** [comment]
no, no, my bad for being such a sloppy reviewer :)

**Comment by fichtner** [comment]
In all seriousness: thanks for finding it, confirmed fixed now.
