### ISSUE TITLE
[os-bind] BIND plugin does not apply configuration for slave zones

### ISSUE THREAD

**Issue by wizzycom** [opnsense/plugins#2070]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[-] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
Yes

[-] I have searched the existing issues and I'm convinced that mine is new.
Yes

[-] The title contains the plugin to which this issue belongs
Yes

**Describe the bug**
A clear and concise description of what the bug is, including last known working version (if any).
When you add a slave zone via os-bind plugin, the slave zone configuration is not parsed on /usr/local/etc/namedb/named.conf. Any other configuration after that, is not parsed to named.conf. The same happens when I tried to enter those changes manually to /usr/local/etc/namedb/named.conf, then, every change on the os-bind plugin is not parsed until I erase those lines that I added manually and delete all slave zones from os-bind plugin.

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)
Same behavior as os-bind 1.12

**To Reproduce**
1. Go to Services
2. Click on BIND, then click on 'Zones' tab
3. Add a new zone and select 'Type: slave'. Set the zone name and master IP (By the way you cannot add more than one masters)
4. Click 'save'
5. Check the contents of the file /usr/local/etc/namedb/named.conf. Conguration for the slave zone is not parsed.

**Expected behavior**
Configuration for slave zone should be applied on  /usr/local/etc/namedb/named.conf

**Environment**
OPNsense 20.7.3-amd64
FreeBSD 12.1-RELEASE-p10-HBSD
OpenSSL 1.1.1g 21 Apr 2020
os-bind 1.13_1
BIND 9.16.6_1

**Comment by mbalmer** [comment]
I noticed that adding a slave zone eventually yields an empty /usr/local/etc/named/named.conf file (after disabling and re-enabling bind).  After this, named won't start at all.

Removing the slave zone and disabling / re-enabling bind again creates a valid named.conf file.

**Comment by mimugmail** [comment]
What exactly means eventually? I can't reproduce it.

**Comment by mbalmer** [comment]
> Am 02.12.2020 um 11:31 schrieb Michael <notifications@github.com>:
> 
> 
> What exactly means eventually? I can't reproduce it.
> 
> 

Eventually means almost momantenous.  I wil try to come up with a clear recipe to reproduce the issue.

**Comment by mbalmer** [comment]
1) Create a bind configuration with only master zones
2) Very named.conf is correct
3) Add a slave zone
4) Note how named.conf is still valid, but does not contain the slave zone
5) Disable bind
6) Note that named.conf is empty
7) Re-enable bind
8) Note that named.conf is still empty
9) Remove the slave zone
10) named.conf is now correct again

**Comment by pmhausen** [comment]
Seconded. Slave zones never make it into the named.conf file. But an empty .db file in the "master" directory gets created. os-bind-1.15

**Comment by mimugmail** [comment]
Sorry guys, I still can't reproduce. I took a fresh machine, latest version, installed os-bind, just hit enable, added a slave zone and a master IP (in this case routerperformance.net):

![image](https://user-images.githubusercontent.com/20438689/104798887-c54b7880-57ca-11eb-982b-f82277da7db7.png)

And the details:

![image](https://user-images.githubusercontent.com/20438689/104798898-d8f6df00-57ca-11eb-8748-30e7d2a70386.png)

This is the named.conf:

```
root@OPNsense:/usr/local/etc/rc.d # cat /usr/local/etc/namedb/named.conf


options {

        directory       "/usr/local/etc/namedb/working";
        pid-file        "/var/run/named/pid";
        dump-file       "/var/dump/named_dump.db";
        statistics-file "/var/stats/named.stats";

         listen-on port 53530 { 127.0.0.1; };
         listen-on-v6 port 53530 { ::1; };




        max-cache-size    80%;
        dnssec-validation    no;
};

key "rndc-key" {
        algorithm hmac-sha256;
        secret "VxtIzJevSQXqnr7h2qerrcwjnZlMWSGGFBndKeNIDfw=";
};
controls {
        inet 127.0.0.1 port 9530
                allow { 127.0.0.1; } keys { "rndc-key"; };
};

zone "." { type hint; file "/usr/local/etc/namedb/named.root"; };

zone "localhost"        { type master; file "/usr/local/etc/namedb/master/localhost-forward.db"; };
zone "127.in-addr.arpa" { type master; file "/usr/local/etc/namedb/master/localhost-reverse.db"; };
zone "0.ip6.arpa"       { type master; file "/usr/local/etc/namedb/master/localhost-reverse.db"; };


zone "routerperformance.net" { type slave; masters { 81.24.64.2; };  allow-notify { 81.24.64.2; }; file "/usr/local/etc/namedb/slave/routerperformance.net.db";  };


logging {
        channel default_log {
                file "/var/log/named/named.log" versions 3 size 5m;
                print-time yes;
                print-severity yes;
                print-category yes;
        };

        channel query_log {
                file "/var/log/named/query.log" versions 3 size 5m;
                print-time yes;
        };

        channel rpz_log {
                file "/var/log/named/rpz.log" versions 3 size 5m;
                print-time yes;
        };

        category default { default_log; };
        category general { default_log; };
        category queries { query_log; };
        category rpz { rpz_log; };
        category lame-servers { null; };
};



```

The log of named.conf:

```
16-Jan-2021 07:13:35.755 general: info: received control channel command 'stop'
16-Jan-2021 07:13:35.755 network: info: no longer listening on ::1#53530
16-Jan-2021 07:13:35.756 network: info: no longer listening on 127.0.0.1#53530
16-Jan-2021 07:13:35.757 general: info: shutting down: flushing changes
16-Jan-2021 07:13:35.757 general: notice: stopping command channel on 127.0.0.1#9530
16-Jan-2021 07:13:35.782 general: notice: exiting
16-Jan-2021 07:13:37.055 zoneload: info: managed-keys-zone: loaded serial 0
16-Jan-2021 07:13:37.059 zoneload: info: zone 127.in-addr.arpa/IN: loaded serial 42
16-Jan-2021 07:13:37.061 zoneload: info: zone 0.ip6.arpa/IN: loaded serial 42
16-Jan-2021 07:13:37.063 zoneload: info: zone localhost/IN: loaded serial 42
16-Jan-2021 07:13:37.063 general: notice: all zones loaded
16-Jan-2021 07:13:37.065 general: notice: running
16-Jan-2021 07:13:37.068 xfer-in: info: zone routerperformance.net/IN: Transfer started.
16-Jan-2021 07:13:37.070 xfer-in: info: transfer of 'routerperformance.net/IN' from 81.24.64.2#53: connected using 10.24.80.221#26967
16-Jan-2021 07:13:37.072 xfer-in: info: zone routerperformance.net/IN: transferred serial 2021010701
16-Jan-2021 07:13:37.072 xfer-in: info: transfer of 'routerperformance.net/IN' from 81.24.64.2#53: Transfer status: success
16-Jan-2021 07:13:37.072 xfer-in: info: transfer of 'routerperformance.net/IN' from 81.24.64.2#53: Transfer completed: 1 messages, 11 records, 340 bytes, 0.002 secs (170000 bytes/sec)
16-Jan-2021 07:13:37.073 notify: info: zone routerperformance.net/IN: sending notifies (serial 2021010701)
16-Jan-2021 07:13:37.142 resolver: info: resolver priming query complete

```

There's the file with usual yadda yadda

```

root@OPNsense:/usr/local/etc/rc.d # cat /usr/local/etc/namedb/slave/routerperformance.net.db
`▒lrouterperformancenet?pns     maxonlinede
homeschoolingrouterperformancenet.J▒:opn-reporouterperformancenet.N▒6testrouterperformancenetQB▒Ewwrouterperformanceneweb03-01max-itde
```

I can see that also an empty file gets created in master directory, but it should work. Can you send me some screenshots of you config?

**Comment by pmhausen** [comment]
Working here, too, now. *If* you enter an IP address into "Allow Notify". If you leave that empty, it doesn't work ...

**Comment by mimugmail** [comment]
@pmhausen this should do it https://github.com/opnsense/plugins/pull/2193/commits/237add3bf2dfeaa98516a3ca59de8b4d385e910a

**Comment by pmhausen** [comment]
Looks good. Thanks.
