### ISSUE TITLE
os-iperf: Add option to set port

### ISSUE THREAD

**Issue by definitio** [opnsense/plugins#2082]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:
[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
[x] I have searched the existing issues and I'm convinced that mine is new.
[x] When the request is meant for an existing plugin, I've added its name to the title.

It would be nice to have an option to set port for Iperf because setting port on clients on every run is very annoying.

**Describe the solution you'd like**
I would like an input field in the `/ui/iperf`.

**Comment by bramevo** [comment]
+1 on this request. Because without this option, you always need to configure a FW rule manually for each session.
