### ISSUE TITLE
security/acme-client: support deSEC.io as DNS service for DNS-01 challenge

### ISSUE THREAD

**Issue by scat70** [opnsense/plugins#2086]
Hi!

I haven't seen any corresponding request so far. So I like to raise it. It would be greate if deSEC.io could be supported as additional DNS service for the DNS-01 challenge. seSEC.io supports letsencrypt and offers a corresponding REST API

Thanks & BR, Marc

**Comment by fraenki** [comment]
Will be added in one of the next releases.
For my own convenience:
https://github.com/acmesh-official/acme.sh/wiki/dnsapi#71-use-desecio
https://github.com/acmesh-official/acme.sh/blob/master/dnsapi/dns_desec.sh

**Comment by fraenki** [comment]
#2120
