### ISSUE TITLE
parameters submitted via "set"  in route maps are not propagated to config

### ISSUE THREAD

**Issue by NielsPiersma** [opnsense/plugins#2088]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[-] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
[-] I have searched the existing issues and I'm convinced that mine is new.
[-] The title contains the plugin to which this issue belongs
**Describe the bug**
Adding parameters like
"weight 3000" 
"local-preference 300"
"community 1:1"
Are not propagated to the running config.

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)
Not applicable, started using functionality recently

**To Reproduce**
1. Go to  " routing, bgpv4 route maps" 
2. Add a new map
3. enter a name
4. select any permit/deny
5. give any ID
5. Scroll down to 'set'
6. add set weight 433 or "set weight 433" (or any other supported command)
7. hit save.
8. start vtysh and type sh run.
9. added commands don't appear below the route map.

**Expected behavior**
Entered set commands to appear in config.
 
**Screenshots**

<img width="776" alt="gui" src="https://user-images.githubusercontent.com/70269175/97813403-45604880-1c88-11eb-800e-5e74cfa8cb77.PNG">

**Relevant log files**
If applicable, information from log files supporting your claim.

Building configuration...

Current configuration:
!
Warning: connecting to zebra...success!
Warning: connecting to bgpd...success!
frr version 7.4
frr defaults traditional
hostname pibe31fw2.phb.4sr.org
log file /var/log/frr.log informational
!
router bgp 65404
 no bgp ebgp-requires-policy
 neighbor 10.2.0.1 remote-as 65000
 neighbor 10.2.0.1 update-source ipsec1000
 neighbor 10.2.0.65 remote-as 65405
 neighbor 10.2.0.65 update-source ipsec2000
 !
 address-family ipv4 unicast
  network 10.4.0.0/16
  neighbor 10.2.0.1 route-map VTI_VCLOUD out
  neighbor 10.2.0.65 route-map VTI_PDR in
  neighbor 10.2.0.65 route-map VTI_PDR out
 exit-address-family
!
route-map VTI_PDR permit 11
!
route-map VTI_VCLOUD permit 10
!
line vty
!

**Additional context**

**Environment**
vmware esx 6.7 guest

OPNsense 20.7.4 (amd64, OpenSSL).
Intel® 
Network esxi vmx

**Comment by mimugmail** [comment]
Via CLI

cat /usr/local/etc/frr/bgpd.conf

It should be there but is declined by service cause of syntax error (check logs)

**Comment by NielsPiersma** [comment]
Michael

Which logs, tried to enable debug.logging.but couldn't find any syntax errors in the logging.
________________________________

**Comment by mimugmail** [comment]
/var/log/frr.log

**Comment by NielsPiersma** [comment]
Michael,

Many thanks, will collect the logs and report back.
Niels
________________________________

**Comment by NielsPiersma** [comment]
Hi Michael,

I've enabled debug for logging and for syslogging.

![settings](https://user-images.githubusercontent.com/70269175/97817209-2b7c3100-1c9b-11eb-83ef-1c1e563fcead.PNG)

added "local-preference 300" to one of the route maps

![routemap](https://user-images.githubusercontent.com/70269175/97817223-4c448680-1c9b-11eb-9372-ca6abdde6fc4.PNG)

and reloaded zebra, output in /var/log/frr.log
root@pibe31fw2:/var/log # tail -f /var/log/frr.log
2020/11/01 23:35:18 ZEBRA: release_daemon_table_chunks: Released 0 table chunks
2020/11/01 23:35:18 ZEBRA: zebra/zebra_ptm.c:1351 failed to find process pid registration
2020/11/01 23:35:18 ZEBRA: client 20 disconnected 38 bgp routes removed from the rib
2020/11/01 23:35:18 ZEBRA: Terminating on signal
2020/11/01 23:35:18 ZEBRA: Zebra final shutdown
2020/11/01 23:35:19 BGP: [EC 33554499] sendmsg_nexthop: zclient_send_message() failed
2020/11/01 23:35:19 ZEBRA: client 23 says hello and bids fair to announce only vnc routes vrf=0
2020/11/01 23:35:19 ZEBRA: client 20 says hello and bids fair to announce only bgp routes vrf=0
2020/11/01 23:35:21 BGP: bgp_update_receive: rcvd End-of-RIB for IPv4 Unicast from 10.2.0.65 in vrf default
2020/11/01 23:35:21 BGP: bgp_update_receive: rcvd End-of-RIB for IPv4 Unicast from 10.2.0.1 in vrf default

I can't find any "syntax" errors in the logging.

Where should I look or where can I up the logging level ?

Kind regards
Niels

**Comment by NielsPiersma** [comment]
Extra information;

Adding the "local-preference 300" did not impact the config file at /usr/local/etc/frr/bgpd.conf.

! Zebra configuration saved from vty
**!   2017/03/03 20:21:04**
!
log file /var/log/frr.log debugging
log syslog debugging
!
!
!
router bgp 65404
 no bgp ebgp-requires-policy
 neighbor 10.2.0.65 remote-as 65405
 neighbor 10.2.0.65 update-source ipsec2000
 neighbor 10.2.0.1 remote-as 65000
 neighbor 10.2.0.1 update-source ipsec1000
 address-family ipv4 unicast
  network 10.4.0.0/16
  neighbor 10.2.0.65 route-map VTI_PDR in
  neighbor 10.2.0.65 route-map VTI_PDR out
  neighbor 10.2.0.1 route-map VTI_VCLOUD out
 exit-address-family
!
 address-family ipv6 unicast
 exit-address-family
!
!
!
route-map VTI_PDR permit 11
route-map VTI_VCLOUD permit 10
!
!
line vty

**Comment by NielsPiersma** [comment]
Posted deleted as it seems to refer to vtysh changes :)

**Comment by mimugmail** [comment]
Every Set needs a Match in route-map.

**Comment by NielsPiersma** [comment]
Michael,
Can you please elaborate, I don't fully grasp your reply? 

Thanks in advance.
NIels

**Comment by mimugmail** [comment]
Create a prefix list with your local network, then create route-map, match against prefix-list and add the set

**Comment by NielsPiersma** [comment]
Michael,

That did the trick! Excellent guidance. I would however recommend making the GUI behave in such a way that incorrect or useless configuration directives are denied or at least reported back to the user.

Still love the product though! Keep up the good work.

Niels

**Comment by saumyakswain** [comment]
> Create a prefix list with your local network, then create route-map, match against prefix-list and add the set

It works this way. I had got it to work by setting an "AS-Path List". Basically "Set" works only when another parameter is set. But I think this is an workaround rather than solution. Because the same thing can be accomplished with vtysh without specifying other parameters. For example when I add a route map like the following through vtysh, it works but does not work when given through opnsense interface.

router bgp 3
 bgp router-id 10.0.11.2
 neighbor 10.0.11.1 remote-as 4
 neighbor 10.0.11.1 route-map test out
!
route-map test permit 10
 set as-path prepend 3 3

I may be missing something here.

**Comment by NielsPiersma** [comment]
Saumya,
It is a while back, but we eventually got it working. In older versions the route map was not needed. Now it is mandatory. So we created them and it worked.

The weight was not an issue, as we choose our (redundant) op addresses in such a way out primary path was always selected.

Niels
________________________________

**Comment by saumyakswain** [comment]
> Create a prefix list with your local network, then create route-map, match against prefix-list and add the set

I'm unable to figure out how I can add multiple "set" statements to a route map for example
```
route-map test permit 10
 set as-path prepend 3 3
 set local-preference 300
```
Really sorry, I should have posted this in the forum, but posted here in issues just because it is related and if the feature does not exist, it may be considered for addition.
Thanks in advance.
