### ISSUE TITLE
[FreeRadius] @ in password not working

### ISSUE THREAD

**Issue by Ornias1993** [opnsense/plugins#2090]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

[X] The title contains the plugin to which this issue belongs

**Describe the bug**
When entering passwords into FreeRadius (username and password list), they don't work if they contain @ , this has been the case for quite a while now.

I verified with FreeRadius and it should be able to do it, even though the implementation in OPNSense is not able to.
I also verified it by moving (a slightly modified version of) the OPNSense FreeRadius config to another plain-freeradius system and this also leads to special characters not working when entered into the `users `file

So the config for this bug seems to be in the FreeRadius config OPNSense is using

**To Reproduce**
1. Add a user with @ in password  (either via manual editing the `users` file or ldap.
2. Try to login/authentication
3. Notice login fails due to invalid password
4. Notice invalid password message in log
5. Notice the right password was recieved in the log

**Expected behavior**
According to the guys at FreeRadius, special characters should just work out of the box. Here they don't.

**Environment**
Latest, hardware really not relevant (as it's clearly related to FreeRadius config, not hardware in any way, shape or form)

**Maintainers:**
@mimugmail and @fichtner

**Comment by fichtner** [comment]
> Add a user with special character in password

There is too much ambiguity regarding "special" to be being able to reproduce the issue.

**Comment by Ornias1993** [comment]
@fichtner 
Please reread:
>  tested with ! and @

**Comment by Ornias1993** [comment]
Update:
Testing of special characters, which are working and which are not working:

Working:
#
!
$

Not-Working:
@

It seems to be limited to @

**Comment by fichtner** [comment]
Sorry, my bad. Thanks for updating the ticket. I'll let @mimugmail handle this for now. 👍

**Comment by Ornias1993** [comment]
@fichtner Also my bad, I made a testing mistake by which I assumed more characters where involved than just @

I noticed the UI doesn't accept @ btw.... had to directly use it in the password file or using ldap. So the reproduction criteria are not right currently. Still users using ldap could for example still hit this bug, because ldap does allow @ in passwords.

**Comment by Ornias1993** [comment]
Okey, freaking weird... testing again it just... started working again...
And can't reproduce anymore >.<

**Comment by fichtner** [comment]
Ok, let us know if that changes again and just reopen. Thanks! :)
