### ISSUE TITLE
net/haproxy: plan upgrade to 2.2 release series

### ISSUE THREAD

**Issue by fraenki** [opnsense/plugins#2092]
HAProxy 2.2 introduces several [exiting new features](https://www.haproxy.com/blog/announcing-haproxy-2-2/) and is [stabilizing nicely](https://www.mail-archive.com/haproxy@formilux.org/msg38809.html). We should target to include HAProxy 2.2 in OPNsense 21.1.x.

Open tasks:
- [x] Check for removed features / incompatible changes
- [x] Replace deprecated functionality
- [x] Document known issues

**Comment by fraenki** [comment]
This change will not affect a lot people, but it may cause serious trouble:

> A bug in the PROXY protocol v2 implementation was present in HAProxy up to
> version 2.1, causing it to emit a PROXY command instead of a LOCAL command
> for health checks. This is particularly minor but confuses some servers'
> logs. Sadly, the bug was discovered very late and revealed that some servers
> which possibly only tested their PROXY protocol implementation against
> HAProxy fail to properly handle the LOCAL command, and permanently remain in
> the "down" state when HAProxy checks them. When this happens, it is possible
> to enable this global option to revert to the older (bogus) behavior for the
> time it takes to contact the affected components' vendors and get them fixed.

A new option was added to `HAProxy -> Settings -> Global Parameters` to restore the old buggy behaviour.

**Comment by fichtner** [comment]
Thank you ❤️

Is this 21.1.1 material for next week or should this stay on development and land this in 21.1.2?

**Comment by fraenki** [comment]
> Is this 21.1.1 material for next week or should this stay on development and land this in 21.1.2?

We need a few more days, so it will likely land in 21.1.2. Andeman is already working on the last missing feature (#1882) :)

**Comment by fichtner** [comment]
Ok if the timeline changes let me know. We will probably do the 21.1.1 update on Tuesday or Wednesday.
