### ISSUE TITLE
Wireguard doesn't reconnect, resilience issues

### ISSUE THREAD

**Issue by netadvanced** [opnsense/plugins#2095]
**Context**
My infrastructure is installed with OPNSense exclusively.  
To connect between firewalls, I've installed Wireguard as LAN-to-LAN and everything works beautifully.

My issue is that when a router disconnects (unintended) or reboots (I have a key firewall reboot every night since it sometimes get stuck and access is complicated) not all Wireguard reconnect and I lose connection to a network.

Now I will mention one important aspect, one of my Wireguard VPNs is on a CARP interface, could that be an issue ?!

**Setup**
OPNSense A ======= OPNSense B ====== OPNSense C1
                                                                       +== OPNSense C2 (Currently switched off during tests)
A is on a dynamic DNS setup and works great. WG on A has no endpoint IP, see further.
B has two (2) WG interfaces (different Eth, IP & ports), one to A and an other to C1/2. WG configs on C1 & C2 are identical.
B initiates connection to A as B is inside a private LAN, unreachable directly. Works mostly great.
B to C are both on separate private LANs (no WAN in between). Timeout on both B & C set to 15 seconds
C1 & C2 are using CARP interface as it's in HA mode, C2 is switched off as it seems to makes no difference and easier during debugging.
B endpoint points to Carp interface of C

**Problem**
When B is rebooted or goes offline, it will **never** recover B to C, and less often but sometimes B to A fails without recovering as well.  As soon as I press Save on B (reload WG) it connects fine.

**Expected**
When either side goes down and recovers, I assume it should re-initiate the connection or at least retry.
In the connection details, I see i.e 15 hours since last handshake.

OPNsense 20.7.4-amd64
Various hardware setups, old HP G7 & G8 servers.

**Comment by mimugmail** [comment]
Carp is unsupported as you cant control the outgoing IP and therefore no match. I already asked the author of WireGuard twice without a reply. It's only supported in Linux

**Comment by netadvanced** [comment]
@mimugmail Thanks for your feedback.  What a shame.

Any recommendation on best practice ?
Such as having dual WG connections to both OPNSense IP C1 & C2 bypassing the VIP, guess I would need to configure both as separate interfaces and add routing priorities to avoid gateway competition ?!
