### ISSUE TITLE
ntopng allow to select multiple interfaces in WebGui

### ISSUE THREAD

**Issue by D3R-ST3FAN** [opnsense/plugins#2096]
I am using OPNsense with a couple VLANs(20+) on a lagged trunk as well as Multi-WAN.
Selecting/deselecting interfaces is quite painful and I don't need all of them.

However the current setup in OPNsense with ntopng only allows one the use a specific interface OR none (manage withing ntopng).

I propose to:

Make the interface selection on /ui/ntopng/general/index multi a selectable field.
This then should update ntopng.conf with addl. "-i interface name" lines.

I have tested this by manually addl. lines to the config files (e.g. the wan interfaces + the trunk containing the vlans).
This works perfectly fine. (on the console: kill ntopng, update config, restart ntopng).

So I am getting the interfaces I need in ntopng.
The downside of my manual hack is that the conf file is re-generated after each restart of ntopng.

**Comment by mimugmail** [comment]
Sounds trivial, I will add it

**Comment by D3R-ST3FAN** [comment]
Hi, is this still on the radar-screen?

**Comment by mihakralj** [comment]
Pull request submitted: https://github.com/opnsense/plugins/pull/2292
