### ISSUE TITLE
net-mgmt/zabbix5-proxy - Request for VMware Collector addition to GUI config

### ISSUE THREAD

**Issue by lemtargatwing** [opnsense/plugins#2097]
Problem:

Unable to add VMware Collector options to the zabbix5-proxy through the web gui.  I can always add them into the config file, but upon reboot that gets reset back to the config per the GUI.

Solution:

Add input fields for the following per https://www.zabbix.com/documentation/5.0/manual/vm_monitoring#configuration:

    StartVMwareCollectors
    VMwareCacheSize
    VMwareFrequency
    VMwarePerfFrequency
    VMwareTimeout

**Comment by mimugmail** [comment]
Sure, I can add it. Nice to see someone is using this in production :)

**Comment by barzog** [comment]
Any news on that?

**Comment by barzog** [comment]
Here's diff to add StartVMwareCollectors to GUI.
[Zabbixproxy.diff.txt](https://github.com/opnsense/plugins/files/6128840/Zabbixproxy.diff.txt)

**Comment by fraenki** [comment]
@barzog It's usually better to [create a pull request](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request), it has more chances to get added/merged.
