### ISSUE TITLE
FRR: dropdown boxes multiple vs single

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/plugins#2098]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

[x] The title contains the plugin to which this issue belongs

**Describe the bug**

While working on the ospf interface section, it looks like some dropdown boxes are intended for single use but do accept multiple values (including none).

`OSPF -> Interfaces -> new `

- Interface
- Authentication Type
- Network Type

**Expected behavior**
Either accepting multiple options and accepting them or accepting single options.

**Screenshots**
![image](https://user-images.githubusercontent.com/9783985/98561707-7ef90b00-22a9-11eb-9aec-909c616cb7ca.png)

**Relevant log files**
none

**Additional context**

https://github.com/opnsense/plugins/blob/20.7.4/net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/dialogEditOSPFInterface.xml#L10

**Environment**
Software version used and hardware type if relevant.
e.g.:

OPNsense 20.7.4 (amd64, OpenSSL).

**Comment by mimugmail** [comment]
I didn't check the code yet, but there's a for-loop in templating, so it might look sane?

https://github.com/opnsense/plugins/blob/20.7.4/net/frr/src/opnsense/service/templates/OPNsense/Quagga/ospfd.conf#L22-L40

**Comment by AdSchellevis** [comment]
if it would accept additional entries, yes :)

https://github.com/opnsense/plugins/blob/a878826c05ff470ab2a5001cf9f26b153a1f7bcf/net/frr/src/opnsense/mvc/app/models/OPNsense/Quagga/OSPF.xml#L127-L129

**Comment by mimugmail** [comment]
Oh, indeed. :) 
You will take care of it?

**Comment by AdSchellevis** [comment]
if there's no rush, I can probably add it in the rest of my PR

**Comment by AdSchellevis** [comment]
@mimugmail `interfacename` isn't split into different entries, I suspect dhis should have been single items. (you pointed to iterating the interface section, not the name)

**Comment by AdSchellevis** [comment]
@mimugmail https://github.com/opnsense/plugins/commit/4671d450e52d1f025c301e7682010cb2d76da89c ?

**Comment by mimugmail** [comment]
Yep, thx :)
