### ISSUE TITLE
approval of acme.sh version 2.7.2

### ISSUE THREAD

**Issue by fichtner** [opnsense/plugins#210]
https://github.com/HardenedBSD/hardenedbsd-ports/commit/d6341952611

**Comment by fraenki** [comment]
The [list of changes](https://github.com/Neilpang/acme.sh/compare/v2.6.9...master) is rather lengthy, but I couldn't spot a breaking change. I'll do a brief test on 17.7 though.

**Comment by fraenki** [comment]
Tested alongside https://github.com/opnsense/plugins/pull/219, ready for merge!

**Comment by fichtner** [comment]
via https://github.com/opnsense/ports/commit/b3edafd122e9faeec92c8086340a917864f16bd5
