### ISSUE TITLE
FRR: replace ruby dependancy

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/plugins#2101]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

[x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
Since most of our core components are written in either `python` or `php` and FRR is being used more ofter, it would be practical to increase the maintainability of the plugin since output formats of `vtysh`  change over time.

looking briefly at quagga.rb, a list of diagnostics can be retrieved, for which a part can already be extracted natively in json format, some will still need a (simple) conversion from plain text to json. To ease the user interface parsing, we might hook into a similar tree view as is being used in the netstat view (`/ui/diagnostics/interface/netstat`).

**Describe the solution you'd like**
The solution depends on the diagnostic to fetch, when a native json output is available, we should probably use that, if not, we need a (simple) parser. Below the list of diagnostics being extracted split in both groups.

**vtysh -u -c "[command] json"**
- show ip[6] route
- show ip ospf neighbor
- show ip ospf interface
- show ip ospf route
- show ip ospf json
- show ip bgp

**need parser**
- show ip ospf database
- show ipv6 ospf6
- show ipv6 ospf6
- show ipv6 ospf6 linkstate
- show ipv6 ospf6 route
- show ipv6 ospf6 neighbor
- show ipv6 ospf6 database
- show ipv6 ospf6 interface

**Describe alternatives you've considered**
not applicable.

**Additional context**
In the long term we likely will start classifying plugins in relation to official support levels, to increase chances of a plugin to gain a higher level it should match certain criteria in terms of documentation and manageability.

**Comment by marcquark** [comment]
Would you want the API output format to remain stable, or would you replace it with whatever FRR produces? The API is called internally in the GUI in some places, but that should be easy to fix (or just replace everything with a tree view as you've suggested). However changing the format would of course break custom scripts.

I personally would favor a change, since it could open up new avenues (reuse tooling that is already compatible with FRR JSON output). It's also probably easier to keep up with than having to maintain an internal translation layer

**Comment by marcquark** [comment]
oh, it seems like `show ip ospf database json` is now available in upstream master: https://github.com/FRRouting/frr/pull/6795 that's nice!

**Comment by AdSchellevis** [comment]
@marcquark we should indeed stick to the format FRR produces, if it's not forward compatible, we can't really fix that I guess.  I just don't expect we're currently able to produce a better more future stable output than they do, we can however if needed extend the format a bit with extra fields if that's easier for the frontend to manage (the treeview in netstat does something similar if I'm not mistaken), maybe not perfect but easier to use with other tooling indeed and less prone to errors on our end.

Thanks for working on this by the way.

**Comment by marcquark** [comment]
i was more thinking about remaining backwards compatible with the existing API. but that would certainly become ugly and tough to maintain, especially properly converting every edge case to the old format... more code more bugs

kind of along the same line of thought, i'd try to stick with leaving FRR's json output untouched, avoiding additional backend complexity. the frontend overhead wasn't that bad so far.

**Comment by AdSchellevis** [comment]
Eventually we may want to refactor some of the frontend code as well, this is one of the few components depending on lodash, which we don't use anywhere else either, although I realise we don't offer a lot of glue in our core system at the moment with similar functionality (have been thinking about something like react, but that would require quite some work and might not be very easy to fit in). 

Good to hear the frontend work isn't to bad.

**Comment by fichtner** [comment]
yay, many thanks to @marcquark for working on this ❤️
