### ISSUE TITLE
net-mgmt/zabbix-agent:  Cannot add custom user parameters - Similar to issue #1252

### ISSUE THREAD

**Issue by scs-tech** [opnsense/plugins#2102]
This is very similar to issue #1252.
In that issue, the User parameter Command field was being filtered so that special characters could not be added.
In this issue, the same problem exists for the User parameter Key field

Problem description:
I am using os-zabbix-agent v1.7 on OPNsense 20.1.9-amd64 and would like to add a custom User Parameter Key (Services => Zabbix Agent => Advanced => User Parameter Key)
I want to add coretemp.cpu[*]  as a Key
This is a valid key sequence in Zabbix agent
According to the Zabbix documentation:
"Unique item key. The [*] defines that this key accepts parameters within the brackets. Parameters are given when configuring the item."

Steps to reproduce problem:
Services => Zabbix Agent => Advanced => User Parameter => Add => Key)
Key = coretemp.cpu[*]
===> Error Message: Should be a string between 1 and 255 characters.

I suspect that whatever fix you made for issue #1252 should be applied to the Key field as well.

Thank you.

**Comment by fraenki** [comment]
> The [] defines that this key accepts parameters within the brackets

When creating a "User Parameter" there is an option for this in the GUI:
```[X] Accept Parameters```

When this option is enabled, it will add the following to the Zabbix Agent configuration:

```
UserParameter=my.customKey[*],echo test2
```

Without this option, it would look like this:

```
UserParameter=my.customKey,echo test2
```

So please use this option to indicate that your "User Parameter" accepts parameters.

**Comment by scs-tech** [comment]
I have noticed and checked that box.  Are you saying that I do NOT enter the [*] in the userparameter key field and it will add it in the background?
Thank you.

**Comment by fraenki** [comment]
>  Are you saying that I do NOT enter the [*] in the userparameter key field

Exactly. The `[* ]` just indicates that parameters are supported, so it's exactly what the GUI option `[X] Accept Parameters` will do for you.
