### ISSUE TITLE
FRR: logging and standard facilities

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/plugins#2104]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

[x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
Currently you can setup both file and syslog facilities, the question is if it wouldn't be better to only use syslog and generate logfiles like other core facilities do. While there, also set the default to enable logging to some sane level (warnings?).

https://github.com/opnsense/plugins/blob/983daacb33698c3f06f139609e1a7e8f41aa0bd1/net/frr/src/opnsense/mvc/app/models/OPNsense/Quagga/General.xml#L33-L36

**Describe the solution you'd like**
To align the logview more to the standard core templates and have better defaults, the first place to look for issues should be the log when issues arise, which is disabled by default now.

**Describe alternatives you've considered**
The question is if there's a good reason to be able to specify file and syslog separately, in most cases when the device shouldn't store the log, it likely should store it for any of the facilities (disable local logging).

**Additional context**
none

**Comment by AdSchellevis** [comment]
@mimugmail thoughts?

**Comment by mimugmail** [comment]
Nice! File-based logging doesn't use rotation and logs are also displayed in wrong order. Maybe treat it like postfix etc. would be very nice :)

**Comment by AdSchellevis** [comment]
@mimugmail there you go https://github.com/opnsense/plugins/commit/64f29b2fc6b63b52a88bbf39efb9948b79e72de0

**Comment by mimugmail** [comment]
Before:

![image](https://user-images.githubusercontent.com/20438689/99059723-3f7b3900-259f-11eb-9d3c-dd5491b7e336.png)

After:

![image](https://user-images.githubusercontent.com/20438689/99060745-c7ae0e00-25a0-11eb-8a4f-3e7fca67ecb1.png)


Really nice :)
