### ISSUE TITLE
add --listenon option do frr

### ISSUE THREAD

**Issue by GaardenZwerch** [opnsense/plugins#2106]
Hi,

as per mimugmail's suggestion (https://forum.opnsense.org/index.php?topic=20028.0) 
I would like to request to have the -l (--listenon) option added to frr
this would be useful when your external interface has several IPs, eg in a HA/CARP scenario.
Thanks

**Comment by mimugmail** [comment]
@GaardenZwerch can you do me a favor please?
Via CLI, edit /etc/rc.conf.d/frr and add: 
`bgpd_flags="-l 172.24.68.133"`

Where the IP would be your CARP. In my test it successfully binds to this IP, but I cant test if also originating packets are sent via this IP.

After the change please dont restart via UI as this would overwrite it. Just do a `service frr restart`

**Comment by GaardenZwerch** [comment]
Hi Michael,
I'm sorry
a) this took so long. I'm in home office mode this week, so, not easy to get access to the LAB.
b) I can't, for the life of me, reproduce the behavior, so I can't really say if this flag makes any difference. 
I have three IPs:

- master: .108
- slave: .109
- CARP: .110
remote gw is .97

I tcpdump -i... port bgp on both OPNsenses, and I only ever see traffic between .97 and .110
When I do failovers, I see about a dozen bgp packets dropped on the active host, probably because they belong to a non-existent session. But it looks like the OPNsense boxes never originate the bgp negotiations. 

Friday afternoon, I was _under the impression_ that the -l flag had no effect, but since I couldn't get bgp to work event with a single host and no virtual IP, I rebooted the entire LAB and since then it magically does what I need.

I will test further with a second remote gateway from my ISP, since that is the point of using BGP here. For now, my setup does what I need.

I'll be happy to do any supplementary testing you would need.

Thanks
Frank
