### ISSUE TITLE
Feature request: unbound: option for marking override domain as insecure

### ISSUE THREAD

**Issue by mbunkus** [opnsense/plugins#2108]
We use a lot of internal domains for development and testing purposes, e.g. `domain1.intranet`, `test42.intranet` etc. All of those domains run their own nameservers. We would like to make those domains resolvable via our OPNsense.

We can do that via the "Overrides" mechanism. This works fine as long as DNSSEC support is turned off.

As soon as we turn DNSSEC support on, resolving names for those domains fails with `NXDOMAIN` (tested via `host myhost.test42.intranet` directly on the OPNsense machine).

unbound itself does offer an option called `domain-insecure` for turning DNSSEC off for certain domains. At home on my Linux router running unbound this works nicely together with globally enabled DNSSEC support.

For the time being I can work around this problem by including the option in the "custom options", but those are deprecated:

```
server:
  domain-insecure: "domain1.intranet"
  domain-insecure: "test42.intranet"
```

So here's my feature request:

In the unbound "Override" configuration, add a checkbox for marking overridden domains as insecure. If marked, include that domain in the configuration with the `domain-insecure` option.

Thanks for considering.

**Comment by mimugmail** [comment]
I take it, we can add this to misc section (where also DoT and private-domain sits) ..
