### ISSUE TITLE
security/acme-client: Namesilo Validation prevents overriding the DNS Sleep time

### ISSUE THREAD

**Issue by ken-wolfe** [opnsense/plugins#2121]
The current plugin version where the bug first appeared - Probably version 2, based on code inspection.
The last plugin version where the bug did not exist - I don't know if it ever did not exist.
The exact URL of the GUI page involved (if any) - ui/acmeclient/validations (but on the 'Edit' screen for a particular validation)
A list of steps to replicate the bug - See below
The current OPNsense version used - 
**OPNsense 20.7.5-amd64
FreeBSD 12.1-RELEASE-p10-HBSD
OpenSSL 1.1.1h 22 Sep 2020**

**Describe the bug**
I cannot change the sleep time for the Namesilo validation in the UI. It always defaults to 900 seconds. This is a problem because Namesilo only does updates after 15 minutes and there is DNS propagation time which means that the records are infrequently available by the time the acme script checks. The suggestion from Namesilo is to wait at least 1 hour, however it would be great if this could be tuned. See below for bug analysis based on source code inspection.

**To Reproduce**
1. Create a Let's Encrypt account
2. Use Namesilo.com API for the DNS Service with a challenge type set to DNS-01
3. Try to change the "Sleep Time" parameter in the UI that is anything other than 15 minutes (900 seconds)

**Expected behavior**
The sleep time between setting the TXT record and having the acme.sh script check the TXT record should honor the "Sleep Time" parameter in the UI. So if I set this to 1020 seconds, I should see in the logs that the script slept for 1020 seconds.

Actual behavior
Code sleeps for just 900 seconds regardless of the value put into this parameter.

**Relevant log files**
If applicable, information from log files supporting your claim.

**Additional context**
I've looked at the code files that are involved and I think I see the bug. So in `AcmeClient/LeValidation/Base.php` the `init` function sets an entry in the `acme_args` array for the `dnssleep` parameter. This method (`init`) is called first in `AcmeClient/LeCertificate.php/LeCertificate.setValidation()`. The `prepare` is called on `AcmeClient/LeValidation/DnsNamesilo.php` which basically sets the same parameter on `acme_args`. Based on reading `acme.sh` it looks like it takes the last one it finds and just overwrites it's internal variable. 

I haven't looked at this code that much, but I would suggest two different fixes (that appear to not be disruptive).
1) Don't set a default in `DnsNamesilo.php`
or 
2) Only set a value if whatever was specified was below 15 minutes.

**Comment by fraenki** [comment]
@ken-wolfe Thanks for the detailed bug report. I think the hardcoded value of 900 seconds was added with good intentions in mind. But as you've just discovered it does not work for everyone.

So starting with os-acme-client version 2.2 the hardcoded value is removed and the user is expected to provide a working value. A hint indicating that something >900 seconds should work was added to the GUI. This is a breaking change for existing users, but it was never a good idea to use a hardcoded value in the first place.

You may test this change by applying the patch to your system:

```
opnsense-patch -c plugins 416487e3
```

**Comment by ken-wolfe** [comment]
Thanks for fixing this @fraenki, I figured providing the details will get it fixed faster. I'll give this a try when it comes out (I would have tested the patch, but I think I need two patches because of the Let's Encrypt changes.)
