### ISSUE TITLE
Can Wireguard display the peer configuration name in handshakes?

### ISSUE THREAD

**Issue by gitpower2017** [opnsense/plugins#2123]
Can Wireguard display the peer configuration name in handshakes?

For troubleshooting purposes, it would be nice if the endpoint name is displayed in the handshakes.

Example:
current: 
wg0 TkEFIXtRstIrT4r2oPqhr1SfyF0AWXSF9v3M7PgDJRI= 1606374792

better:
wg0 (NAME OF THE PEER) TkEFIXtRstIrT4r2oPqhr1SfyF0AWXSF9v3M7PgDJRI= 1606374792

**Comment by mimugmail** [comment]
I think this is already the Case when using the Dashboard widget?

**Comment by gitpower2017** [comment]
which Dashboard widget?

**Comment by mimugmail** [comment]
Go to your Dashboard, Add widget, select WireGuard Widget and save.

**Comment by gitpower2017** [comment]
thanks a lot, I found it.

Unfortunately it is exactly the same.
Only the private keys are shown without the peer names from the config

**Comment by jeffg2k** [comment]
Looks like this is already in a PR, just waiting for approval / merging. https://github.com/opnsense/plugins/pull/1970
