### ISSUE TITLE
Support for Zabbix Minor Releases (5.2.x)

### ISSUE THREAD

**Issue by stevefxp1** [opnsense/plugins#2129]
**Is your feature request related to a problem? Please describe.**
I would like to see OPNsense plugins not only support Zabbix LTS but also the minor releases, in this case 5.2.x. 

**Describe the solution you'd like**
Please provide a package that deploys the latest Zabbix agent.

**Describe alternatives you've considered**
No other alternatives,

**Additional context**

**Comment by fichtner** [comment]
https://github.com/opnsense/plugins/pull/2116 Here we discuss solutions, but none really make sense for the release engineering that zabbix does. In the end we may introduce more complexity than we can actually solve due to said upstream process.

**Comment by olewales** [comment]
+1 on that. Unfortunately zabbix proxy version must be in sync with the server version so single OPNsense instance may be holding back updating of a much bigger network. PfSense manages to provide packages for each supported major release (5.2 and 5.0LTS at the time of writing) and I believe that OPNsense should too, regardless of the implementation.

**Comment by Baeth** [comment]
> 
> 
> +1 on that. Unfortunately zabbix proxy version must be in sync with the server version so single OPNsense instance may be holding back updating of a much bigger network. PfSense manages to provide packages for each supported major release (5.2, 5.0LTS, 4.0LTS, 3.0LTS at the time of writing) and I believe that OPNsense should too, regardless of the implementation.

Just made a mistake of going for zabbix 5.2 and can't use the proxy package. I'd love to have it. Seeing that this issue is floating for three months I'll be forced to switch to pfsense for now.

**Comment by fichtner** [comment]
We are certainly not in a rush to make mistakes here. The Zabbix release schedule is not low maintenance for downstream projects so we still have to figure out a viable  way without pushing work our way at the same time. Good luck.

**Comment by meyju** [comment]
+1 for zabbix-proxy-5.2

Using zabbix in version 5.2 and would like to use the proxy on my opnsense firewalls to monitore some smaller offices.

**Comment by MAGICCC** [comment]
I wll abuse this issue, since latest LTS of Zabbix is now 5.4 and an upgrade for the plugin would be really nice

**Comment by fichtner** [comment]
Plugin variants are supported now without having to duplicate plugin code. Zabbix proxy is the first to use it, but certainly other zabbix tools can now follow depending on maintainer time.

**Comment by fraenki** [comment]
I plan to add all supported releases of Zabbix Agent in the near future (just need to finish priority tasks first).

**Comment by bastolino** [comment]
Hi @fraenki 
as currently already Zabbix 5.4 LTS is released, do you have any expected timeframe?
Appreciate your update!

**Comment by fraenki** [comment]
>  as currently already Zabbix 5.4 LTS is released

Zabbix 5.4 is not a LTS release:
https://www.zabbix.com/life_cycle_and_release_policy

**Comment by fraenki** [comment]
The plugin was updated with support for plugin variants. It will support both Zabbix 5.0 (LTS) and Zabbix 5.4.

https://github.com/opnsense/plugins/pull/2656
https://github.com/opnsense/tools/pull/251
