### ISSUE TITLE
security/acme-client: Add support for Hexonet DNS-API

### ISSUE THREAD

**Issue by HB9DUT** [opnsense/plugins#2134]
Please add support for the Hexonet-API.
The official acme client has support for Hexonet but not Opensense. Is there a reason for that?
(https://github.com/acmesh-official/acme.sh/blob/master/dnsapi/dns_hexonet.sh)

**Comment by fraenki** [comment]
> Is there a reason for that?

That's simple: because [nobody has worked](https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md) on this yet. ;)
I'll plan to add support for it in one of the next releases.

**Comment by fraenki** [comment]
This will be available in the upcoming os-acme-client version 2.2
You may test it by applying the patch manually:

```
opnsense-patch -c plugins 7bae0539
```

**Comment by HB9DUT** [comment]
Thank you - I'll test the patch right away.

**Comment by HB9DUT** [comment]
Works perfectly in DNS alias mode. Many Thanks!
