### ISSUE TITLE
FRR v1.19 Routing: Diagnostics: General:IPv4 Routes

### ISSUE THREAD

**Issue by thecyberdevl** [opnsense/plugins#2137]
https://github.com/opnsense/plugins/blob/8a72865e007cd157f0cbf6eace34a67971525c46/net/frr/src/opnsense/scripts/quagga/quagga.rb#L121

"ruby -d /usr/local/opnsense/scripts/quagga/quagga.rb --general-routes"

"Exception NoMethodError at /usr/local/opnsense/scripts/quagga/quagga.rb:121 - undefined method split for nil:NilClass"

Results in blank output in the Web-UI

**Comment by mimugmail** [comment]
I can't reproduce here, for me it works fine. 
What happens when you revert back to 1.17?

**Comment by LensHunnel** [comment]
I got the same error. frr v1.17 opnsense 20.7.5

```bash
ruby -d /usr/local/opnsense/scripts/quagga/quagga.rb --general-routes
Exception `LoadError' at /usr/local/lib/ruby/2.6/rubygems.rb:1375 - cannot load such file -- rubygems/defaults/operating_system
Exception `LoadError' at /usr/local/lib/ruby/2.6/rubygems.rb:1384 - cannot load such file -- rubygems/defaults/ruby
Exception `Gem::MissingSpecError' at /usr/local/lib/ruby/2.6/rubygems/dependency.rb:311 - Gem::MissingSpecError
/usr/local/opnsense/scripts/quagga/quagga.rb:565: warning: assigned but unused variable - mode
Using Ext extension for JSON.
Exception `NoMethodError' at /usr/local/opnsense/scripts/quagga/quagga.rb:121 - undefined method `split' for nil:NilClass
{"general_routes":"error"}```

**Comment by marcquark** [comment]
i'm also seeing this in two independent test environments.
#2143 should fix a lot of these issues by using FRR's JSON output directly. it also generally overhauls/improves the diagnostics UI. i expect to add the missing pieces of the new python based parser pretty soon
