### ISSUE TITLE
acme-client: web server doesn't serve intermediate certificate

### ISSUE THREAD

**Issue by mbunkus** [opnsense/plugins#2138]
[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

[x] The title contains the plugin to which this issue belongs

**Describe the bug**

I'm using the `acme-client` plugin to create certificates. Those are used by OPNsense's web admin server. Since the latest certificate renewal some clients cannot connect anymore because they don't know about the new intermediate certificate used by Let's Encrypt, and the web admin server only serves the leaf certificate without the intermediate certificate.

Explanation of what's going on:

Let's Encrypt has recently switched to a [different intermediate certificate](https://letsencrypt.org/2020/09/17/new-root-and-intermediates.html) (note that I'm talking about the new intermediate, not the new root certificate). See also [here](https://letsencrypt.org/certificates/). The earlier intermediate used until recently was `C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3`, the one in use since is `O = Digital Signature Trust Co., CN = DST Root CA X3`.

Most if not all browsers & operating systems have the old intermediate in their trust stores. However, some do not have the intermediate in their trust stores. In my case I'm using `curl` to download the configuration as a method of backup. This fails currently.

Such a problem isn't new, nor is it limited to Let's Encrypt as a CA. Most CAs use intermediates, and they do get renewed/swapped out regularly. In order to accommodate these changes, web servers are usually configured to serve both the leaf certificate and the intermediate certificate. That way clients can verify the whole chain regardless of whether the intermediate certificate was known to the client in advance.

The `acme-client` plugin does _retrieve_ the intermediate certificate (called `chain.pem`)l they're present in `/var/etc/acme-client/certs/<account-id>/chain.pem`. Unfortunately, though, the certificate file it generates for the web admin server, `/var/etc/cert.pem`, does not contain the intermediate certificate, only the leaf certificate and its private key.

**To Reproduce**

1. Configure the `acme-client` plugin & let it request a certificate.
2. Configure the web admin server to use the certificate retrieved in step 1 (System → Settings → Administration → SSL Certificate).
3. Log in via ssh and look at the content of `/var/etc/cert.pem`; it'll only contain the leaf certificate.
4. Use `openssl s_client -connect <ip address>:443 -showcerts` ; it'll confirm that only the leaf certificate is served.

**Expected behavior**

I expect the web admin server to serve both the leaf & the intermediate certificate.

**Environment**

OPNsense 20.7.5-amd64
FreeBSD 12.1-RELEASE-p10-HBSD
OpenSSL 1.1.1h 22 Sep 2020
os-acme-client v2.0

**Comment by fraenki** [comment]
Duplicates #2126

**Comment by mbunkus** [comment]
Oh, sorry for that. I did see that issue, had read through it, but it sounded too different from my actual problem for me to give the patch a try.

I've applied the patch now, re-newed the certificate and can confirm that `curl` is fine now and `openssl s_client -connect … -showcerts` shows the intermediate as well. Thanks!
