### ISSUE TITLE
net-mgmt/zabbix5-proxy: add support for receiving SNMP traps

### ISSUE THREAD

**Issue by Starkstromkonsument** [opnsense/plugins#2141]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

[x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
I'm using the Zabbix Proxies on my OPNSense machines for monitoring the local devices on my remote sites. I would like to be able to receive SNMP Traps by the proxies too.

**Describe the solution you'd like**
Add
```
    StartSNMPTrapper=1
    SNMPTrapperFile=[TRAP FILE]
```
to the configuration file and an option to enable receiving SNMP traps to GUI.

Set up zabbix_proxy with Perl trap receiver as described at the [manual](https://www.zabbix.com/documentation/5.0/manual/config/items/itemtypes/snmptrap?s[]=snmp#setting_up_snmp_trap_monitoring) (scroll down to "Configuring Perl trap receiver").

Nice to have: Add management of additional MIB files to GUI. 

**Additional context**
- https://git.zabbix.com/projects/ZBX/repos/zabbix/browse/misc/snmptrap/zabbix_trap_receiver.pl
- https://blog.zabbix.com/snmp-traps-in-zabbix/

**Comment by mimugmail** [comment]
Did you test on a OPN instance if it works when editing config manually and starting the perl script?
I'm currently unsure how to handle the extra process

**Comment by Starkstromkonsument** [comment]
I gave it a try:

- Add the script zabbix_trap_receiver.pl to /usr/local/bin/ (with the same owner and permissions as the zabbix binaries themselfes).

- Add additional lines to /usr/local/etc/zabbix5/zabbix_proxy.conf:

```
# SNMP Traps TEST
StartSNMPTrapper=1
SNMPTrapperFile=/tmp/zabbix_traps.tmp
```
- `root@opnsense:~ # mkdir -pv /usr/local/etc/snmp`
- `root@opnsense:~ # touch /usr/local/etc/snmp/snmptrapd.conf`

- Add to /usr/local/etc/snmp/snmptrapd.conf

```
authCommunity execute public
perl do "/usr/local/bin/zabbix_trap_receiver.pl";
```

- `root@opnsense:~ # touch /etc/rc.conf.d/snmptrapd`

- Add to /etc/rc.conf.d/snmptrapd
```
snmptrapd_enable="YES"
```

- `root@opnsense:~ # /usr/local/etc/rc.d/snmptrapd start`

It looked quite promising at first. Unfortunately the perl script does not work due to a missing perl module [NetSNMP::TrapReceiver](https://metacpan.org/pod/NetSNMP::TrapReceiver)

```
root@opnsense:~ # /usr/local/bin/zabbix_trap_receiver.pl
Undefined subroutine &NetSNMP::TrapReceiver::register called at /usr/local/bin/zabbix_trap_receiver.pl line 112.
```

How can this be installed? `pkg search` did not bring up anything useful and I'm not sure whether using cpan is such a good idea on a firewall.

**Comment by Starkstromkonsument** [comment]
Update: I tried it again and it actually works. Kind of ... it takes several minutes for the snmptrapd to start. It is able to receive and correctly process some traps and then the whole process gets stuck. Sometimes it does not work at all. There must be a performance issue, that I was not able to track down yet. Running `snmptrapd -f -Le -D` outputs a lot of debugging messages, these are the last lines:

```
9:read_config:line: /usr/local/share/snmp/snmptrapd.conf:10 examining: perl do "/usr/local/bin/zabbix_trap_receiver.pl";
trace: read_config(): read_config.c, 972:
read_config:line: /usr/local/share/snmp/snmptrapd.conf:10 examining: perl do "/usr/local/bin/zabbix_trap_receiver.pl";
trace: run_config_handler(): read_config.c, 538:
read_config:parser: Found a parser.  Calling it: perl / do "/usr/local/bin/zabbix_trap_receiver.pl";
trace: maybe_source_perl_startup(): snmp_perl.c, 51:
perl: initializing perl (/usr/local/share/snmp/snmp_perl_trapd.pl)
Loaded Zabbix SNMP trap receiver
NET-SNMP version 5.9
```

I was not able to enable any debugging output for the embedded perl part. I'm stuck here right now. It works fine on my zabbix server (running on ubuntu). My OPNsense-Instance is running on a [PC Engines APU 3C4](https://pcengines.ch/apu3c4.htm). I'll try it on one of my other machines next.

And I made a mistake: the perl module NetSNMP::TrapReceiver is not missing. One simply can't use it from outside snmptrapd:

> This module can NOT be used in a normal perl script to receive traps. It is intended solely for embedded use within the snmptrapd demon.

Another correction: use `/usr/local/share/snmp/snmptrapd.conf` as path for the config file.

**Comment by barzog** [comment]
Any news on that?

**Comment by barzog** [comment]
Here's patch to add StartSNMPTrapper to zabbix_proxy.
[zabbix_proxy.patch.txt](https://github.com/opnsense/plugins/files/6390061/zabbix_proxy.patch.txt)

In addition to that to start snmptrapd following changes should be made:
(this part should really go to net-snmp plugin)
create /etc/rc.conf.d/snmptrapd in order to start snmptrapd with following content:
snmptrapd_enable="YES"
snmptrapd_flags="-On -p /var/run/snmptrapd.pid"

/etc/rc.conf.d/snmpd
snmpd_enable="YES"
snmpd_flags="-x tcp:localhost:705 127.0.0.1:161"

mkdir /usr/local/etc/snmp and create config /usr/local/etc/snmp/snmptrapd.conf:
authCommunity   log,execute,net public
disableAuthorization yes
perl do "/usr/bin/zabbix_trap_receiver.pl";

put wget https://git.zabbix.com/projects/ZBX/repos/zabbix/raw/misc/snmptrap/zabbix_trap_receiver.pl -O /usr/bin/zabbix_trap_receiver.pl 

start snmpd and snmptrapd 
/usr/local/etc/rc.d/snmpd start
/usr/local/etc/rc.d/snmptrapd start
