### ISSUE TITLE
net/frr: Use "all" in "show bgp ... [json]" commands once it's available

### ISSUE THREAD

**Issue by marcquark** [opnsense/plugins#2146]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

[x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
While working on #2143 i realized that the `show bgp` command outputs only the ipv6 routing table. This behaviour is a little unintuitive because other commands such as `show bgp summary` or `show bgp neighbors` will display everything (i.e. IPv4 _and_ IPv6 information if both is present).
In a future release, FRR will introduce an `all` keyword to explicitly request all information at once. Reference http://docs.frrouting.org/en/latest/bgp.html#clicmd-showbgp[all][wide|json]

**Describe the solution you'd like**
I've already added the necessary boilerplates (actions and API endpoints) to #2143 so the `all` keyword can be easily added and used once it's available in a release and pulled into the opnsense ports repo.
ToDo would be to modify the existing bgp actions. For the sake of being explicit, also modify the ones which currently technically seem to work as intended (output everything). Furthermore, implement the `bgp_route` and `bgp_route_json` actions.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by marcquark** [comment]
@AdSchellevis could u assign this to me? I'll keep an eye on it and implement it as soon as an FRR release that has these commands is available in OPNsense :-)

**Comment by AdSchellevis** [comment]
@marcquark done, thanks!

**Comment by marcquark** [comment]
Note to self:

The change was merged into master in September, but has not yet made it into an FRR release yet https://github.com/FRRouting/frr/commit/a68b613b094bb6ea825f723688c36c3f16b3c5d9
```
$ git branch --contains a68b613b094bb6ea825f723688c36c3f16b3c5d9
* master
```

**Comment by marcquark** [comment]
Another note to self: It's now included in frr8 but there seems to be no port for it yet. Waiting for that to become available then test it
