### ISSUE TITLE
net/udpbroadcastrelay: Allow same port on different relay interfaces

### ISSUE THREAD

**Issue by 2nv2u** [opnsense/plugins#2154]
Currently you can only create 1 rule for a specific relay port, this makes it impossible to create the same rule for different interface combinations.
I would like to suggest to amend this validation to check if any of the selected interfaces are having the same port included or not.

**Comment by marjohn56** [comment]
Give me an example of what you are trying to do.

**Comment by 2nv2u** [comment]
I have a setup which consists of 2 separated buildings which have multiple interfaces in which I want them to share the broadcasts.
All managed within the same opnsense instance.

**Comment by 2nv2u** [comment]
Technically this should just work fine, binding the same port to different interfaces within different broadcast daemons should be straightforward and most likely already working, it's just the validation in the UI that keeps it from being created.

**Comment by marjohn56** [comment]
If you only have a single Opnsense instance then where's your problem?

**Comment by 2nv2u** [comment]
Like I said, you cannot specify 2 rules (daemons) with the same port, even though they operate on different interfaces

**Comment by marjohn56** [comment]
can you give me rough schematic of your network, showing where the server is and where the clients are.

**Comment by 2nv2u** [comment]
Both sites have specific LAN and WLAN interface which both are managed by 1 opnsense instance (LAN1 & WLAN1 / LAN2 & WLAN2). For both sites I want to broadcast the common discovery packages within their combination of interfaces (LAN & WLAN)

**Comment by 2nv2u** [comment]
Side note, I don't want them to broadcast to each other, it's not desirable for them to see devices in the other building.

**Comment by marjohn56** [comment]
I'm even more confused now, you previously said 'which have multiple interfaces in which I want them to share the broadcasts'

**Comment by 2nv2u** [comment]
Yes, that's correct in this example:
- WAN
- LAN1
- WLAN1
- LAN2
- WLAN2

I want 2 rules on the same ports for the combinations:

- LAN1&WLAN1
- LAN2&WLAN2

What is so confusing about this?

**Comment by 2nv2u** [comment]
All is managed in the same opnsense server, it has all these interfaces configured

**Comment by marjohn56** [comment]
Not Opnsense, what type of server are your clients trying to connect to, Sonos or what?

**Comment by 2nv2u** [comment]
In essence all of them, but for now I configured mDNS (Googlecast) and SSDP (DLNA and also Sonos I believe).
Both sites (buildings) have several devices on both the LAN and WLAN interfaces needing to find each other in there own building.

**Comment by marjohn56** [comment]
right, I think I understand now. You have effectively two separate networks with a LAN/WLAN on each, each network has its own servers and clients and you don't want the clients in one building/network to be able to see the others server. Yeh, I can probably do that... I'll release something once I've made sure it doesn't cause any other validation issues.

**Comment by 2nv2u** [comment]
Yes, that's exactly what I mean and as far I can tell by looking at the code and the way it just creates multiple instances of the same udpbroadcastrelay daemon it should be fairly easy. Thanks in advance!

**Comment by marjohn56** [comment]
yes, but removing the validation check for port means I have to add a validation check for each interface/port, it makes it more complex in fact.

**Comment by 2nv2u** [comment]
Yes true, it does involve adding to the check if any of the selected interfaces already have the specified port allocated instead of doing this on a global level

**Comment by marjohn56** [comment]
OK, well I'll take a look when I can, real work is keeping me busy at present,
