### ISSUE TITLE
Wireguard 'Table = off' should be an option in the GUI

### ISSUE THREAD

**Issue by theonemcdonald** [opnsense/plugins#2155]
There is a very useful Wireguard Interface option called 'Table' that allows you to control what routes get inserted into the kernel routing table when a wireguard interface is brought up. Table = off allows a tunnel to accept AllowedIPs = 0.0.0.0/0 without also making itself the default gateway. This is critical for situations where you have routing over a wireguard tunnel (say with FRR), but don't want the wireguard tunnel to be a default gateway...you just want it to behave like a point-to-point link.

**Comment by mimugmail** [comment]
There is already Disable Routes checkbox acailable

**Comment by theonemcdonald** [comment]
That box does not do what Table = off does.

**Comment by theonemcdonald** [comment]
Looks like the conf template is supposed to set Table = off, but it doesn't appear to be working for me.

**Comment by mimugmail** [comment]
So when you tick the checkbox the Table = off is present in your wgX.conf?

**Comment by theonemcdonald** [comment]
Okay so yes, it does appear that Table = off is present in my wgX.conf. It seems that when disable routes is checked, it is mandatory to also create a gateway and define it under the advanced wireguard>local configuration. Which begs the question, why is the disable route option not also hidden behind the advanced configuration switch if it is useless without also defining a gateway?
