### ISSUE TITLE
Please add regfish.de to DynDNS Hoster

### ISSUE THREAD

**Issue by gertfriend** [opnsense/plugins#216]
Could you please add the DynDNS-Hoster regfish.de?

I tried with the following and it worked:

        case 'regfish':
            if ($this->_dnsVerboseLog)
                log_error("Regfish: ({$this->_dnsHost}): DNS update() starting.");
            $server = "http://dyndns.regfish.de/?fqdn={$this->_dnsHost}&ipv4={$this->_dnsIP}&forcehost=1&token={$this->_dnsPass}";
            curl_setopt($ch, CURLOPT_URL, $server);
            curl_setopt($ch, CURLOPT_IPRESOLVE, CURL_IPRESOLVE_V4);
            break;

The fields neccessary are:
Hostname witch is fqdn
Forcehost a flag witch returns 0 or 1, 0 is off and 1 is on
And if possible name a field token witch is the individual token for the domain. A 32 character long ID with numbers and letters
Username and Password field are not used

See (german):
https://www.regfish.de/domains/dyndns/dokumentation

Answer on success:
Dynamic DNS: PAYLOAD: success|100|update succeeded!

**Comment by fichtner** [comment]
looks like we can add ipv4 and ipv6 variants here 👍

**Comment by fichtner** [comment]
@gertfriend added IPv4 and IPv6 support, can you test?

Small change: Username is the token, password is not needed (like Duck DNS works)

    # opnsense-code plugins
    # cd /usr/plugins/dns/dyndns
    # make install


Cheers,
Franco

**Comment by gertfriend** [comment]
Hi,

i tested the IPv4 version on 2 opnsense and it works great. I'm sorry but i haven't yet a provider that supports IPv6 for testing it.

Thank you for your work
Cheers

**Comment by fichtner** [comment]
Hi @gertfriend,

Thanks, I'll add it to 17.7.1 then. I tested IPv6 as far as I could with the account, the parameters and embedded IP look alright. The code is mostly shared so I think we are good here. :)


Cheers,
Franco
