### ISSUE TITLE
Add netserver mode to NUT plugin

### ISSUE THREAD

**Issue by RainerMinixhofer** [opnsense/plugins#2164]
Hi all,

It would be great if the NUT plugin which currently just supports the "netclient" and "standalone" modes in the most recent version of OPNsense (20.7.7) would be extended to support the "netserver" mode (set in nut.conf). Furthermore a GUI form to set ACLs (defined in upsd.conf) would be needed as well. With this feature one would be able to readout the data of an USV attached to the hardware OPNsense is running and to show it at a separate location with an NUT monitor running (e.g. if multiple USVs are in the same network).

Best regards,
Rainer

**Comment by mimugmail** [comment]
Just add a portforward to localhost in standalone mode :)

**Comment by just-simon** [comment]
> 
> 
> Just add a portforward to localhost in standalone mode :)

Any tips for doing this?
I'm new and can't work out how to configure the port forward.

**Comment by mimugmail** [comment]
For the archives:

Firewall - NAT - Portforward - Add
Interface LAN, protocol TCP, source LAN net, destination LAN address, Port other/3493, redirect target 127.0.0.1

**Comment by just-simon** [comment]
> 
> 
> For the archives:
> 
> Firewall - NAT - Portforward - Add
> Interface LAN, protocol TCP, source LAN net, destination LAN address, Port other/3493, redirect target 127.0.0.1

Thanks!
I had it so wrong originally, then managed to find some other instructions that weren't quite as complete as this.

Now I just need to figure out how to set the client side, but that's not relevant to this project.

**Comment by djkazaz** [comment]
An additional problem with using the plugin as server, is that the ui does not expose or allow configuring the password, so getting other clients to monitor it, is not at all straightforward.
