### ISSUE TITLE
[Wireguard] Easier peer configuration

### ISSUE THREAD

**Issue by pkejval** [opnsense/plugins#2167]
Hello, this is just suggestion for new feature. As network admin in these Covid days I need to setup many new peers for Wireguard. But this task is quite time demanding because you need manually

- generate client private and public keys
- set server public key (copy-paste from OPNsense) in client config
- create new Endpoint in OPNsense with cliet public key (copy-paste from client)
- add new peer in OPNsense Local settings of Wireguard

Can OPNsense provide "Quick add" of peer like this script? https://github.com/burghardt/easy-wg-quick
Quick add dialog should include only these fields

- Endpoint Name
- Endpoint Shared Secret
- Endpoint AllowedIPs

After clicking Save, OPNsense should generate client config for this new peer. Config file should be downloadable and QR code should be shown for easier setting of mobile device. For security reasons, this config file should be deleted after download.

**Comment by mihakralj** [comment]
To simplify the feature request:

Change **VPN - WireGuard - Endpoints - Edit Local Configuration** form:
- Add Endpoint public address (allow URL or IPv4 or IPv6)

Change **VPN - WireGuard - Endpoints - Edit Endpoint** form:
- Add a drop-down box with all peering local endpoint (can stay blank)
- Add DNS field
- Add IP Address field
- Add (and pre-select) a checkbox "Generate a new Key Pair"
- Add (and keep blank) a checkbox "Generate a new Shared Secret"

When clicking **Save** button:
- a new key pair for a remote endpoint is generated
- the new public key is inserted is stored in the remote endpoint record
- shared secret is generated  (or nothing if was blank) and stored in the remote endpoint record
- chosen local endpoint gets a new Peer added to its Peers (or nothing if peering field was blank)
- .config file with the name of remote Endpoint is generated:
    - new generated (remote) **private key** is stored in the .config
    - DNS field is stored in the .config
    - selected local endpoint **public key** is stored in the .config (or left with a placeholder if blank)
    - **shared secret** is stored in the .config (if selected and generated)
    - **Public address** of selected local endpoint is stored in the .config

The .config file is downloaded to the browser and deleted on OPNSense
Structure of downloaded .config file:

```
[Interface]
PrivateKey = <newly generated private key of Remote endpoint>
Address = <taken from the IP Address field>
DNS = <taken from DNS field>

[Peer]
PublicKey = <chosen local endpoint' public key - or dummy placeholder if blank>
PresharedKey = <newly generated shared secret - or ommit if blank>
AllowedIPs = 0.0.0.0/0
Endpoint = <taken from Local Endpoint public address - or dymmy placeholder if blank>
```

**Comment by jeffg2k** [comment]
I find this bit the most confusing - it's bit me several times and did so again, hours of troubleshooting.
`add new peer in OPNsense Local settings of Wireguard`

If the endpoint is enabled, shouldn't that mean that it's a peer?  Nope.  It should though.. Or at least in the Peer section of the local, give an option for `ALL` enabled endpoints.

**Comment by mihakralj** [comment]
What about configurations that have multiple WG endpoints on different ports? I have two local endpoints and 7 peers - and not all peers are enabled for both endpoints...

**Comment by jeffg2k** [comment]
Good point.. Then yea, an ALL option would be nice for those of us that have one.

**Comment by jeffg2k** [comment]
Or maybe something in the endpoint itself, that allows you to add and remove it from different local peer configs.  It's just confusing that you have this in two places and there is that extra step of adding a client.
