### ISSUE TITLE
collectd: add ipstats and tcpconns plugin

### ISSUE THREAD

**Issue by djzort** [opnsense/plugins#2168]
The new "ipstats" plugin for collectd is just for freebsd and reports various network stats. Its already installing on opnsense and just needs to be exposed via the collectd configuration gui. From the README "IPv4 and IPv6; incoming, outgoing, forwarded counters. FreeBSD only."

https://github.com/collectd/collectd/pull/3187

Theres a seriously large number of options and lots of them would likely be of interest to firewall administrators, perhaps a simple default for on/off checkbox would be:

  <Plugin ipstats>
    ip4fragment true
    ip6fragment true
  </Plugin>

The tcpconns plugins is already installed and also just needs to be exposed via gui. I would recommend it's configuration be:

LoadPlugin tcpconns
<Plugin "tcpconns">
    AllPortsSummary true
</Plugin>

See https://collectd.org/wiki/index.php/Plugin:TCPConns

**Comment by mimugmail** [comment]
Please reopen and assign me
