### ISSUE TITLE
security/acme-client: feature request for DNS Service Infomaniak (dns_infomaniak)

### ISSUE THREAD

**Issue by MoiMemePerso** [opnsense/plugins#2169]
Hi,
It would be great to add Infomaniak API into the DNS service providers list in OPNsense Let's Encrypt GUI.
This provider is already supported by the acme client (dnsapi/dns_infomaniak.sh)
Many thanks in advance!

**Comment by fraenki** [comment]
This will be added in the upcoming os-acme-client version 2.3 (#2199).
