### ISSUE TITLE
net-mgmt/collectd: improvements

### ISSUE THREAD

**Issue by yves-vogl** [opnsense/plugins#217]
Hi,

I'm new to OPNsense and wondering why the collectd plugin is missing.
Is this plugin not supported in 17.1.11 of am I getting something wrong?

```

os-acme-client | 1.8 | 213KiB | Let's Encrypt client |  
os-boot-delay | 1.0 | 32.0B | Apply a persistent 10 second boot delay |  
os-debug | 1.2 | 4.00B | Debugging Tools |  
os-ftp-proxy | 1.0 | 38.8KiB | Control ftp-proxy processes |  
os-haproxy | 1.16 | 265KiB | Reliable, high performance TCP/HTTP load balancer |  
os-helloworld | 1.1 | 17.2KiB | A sample framework application |  
os-igmp-proxy | 1.1 | 22.8KiB | IGMP-Proxy Service |  
os-intrusion-detection-content-pt-open | 1.0 | 425B | IDS PT Research ruleset (only for non-commercial use) |  
os-l2tp | 1.7 | 43.7KiB | L2TP server based on MPD5 |  
os-monit | 1.3 | 79.3KiB | Proactive system monitoring |  
os-pppoe | 1.7 | 50.2KiB | PPPoE server based on MPD5 |  
os-pptp | 1.7 | 49.8KiB | PPTP server based on MPD5 |  
os-quagga | 1.3.2 | 763KiB | Quagga Routing Suite |  
os-relayd | 1.1 | 120KiB | Relayd Load Balancer |  
os-smart | 1.1 | 15.6KiB | SMART tools |  
os-snmp | 1.1 | 22.3KiB | SNMP Server via bsnmpd |  
os-tinc | 1.2_2 | 52.7KiB | Tinc VPN |  
os-upnp | 1.2 | 31.2KiB | Universal Plug and Play Service |  
os-vmware | 1.4 | 303B | VMware tools |  
os-wol | 1.0 | 24.1KiB | Wake on LAN Service |  
os-xen | 1.1 | 80.0B | Xen guest utilities |  
os-zabbix-agent

```

**Comment by fichtner** [comment]
Hi Yves,

Collectd wasn't formally released yet, it's considered under development.

It hasn't been added to 17.1 at all, but there is a development version on 17.7:

    # pkg install os-collectd-devel

You could also install collectd from the plugins.git for 17.1, I can walk you through it.


Cheers,
Franco

**Comment by yves-vogl** [comment]
Hi @fichtner, 
thanks for your feedback.  I'd like to help you getting this into production.
Can you give me some information what's missing or where some work is needed?

**Comment by fichtner** [comment]
it should work as is now, literally in a "grace period" before its first release.

@mimugmail as author / maintainer will be able to help with what may be missing.

If you have ideas on what you think is missing will also help.

Do you have the plugin installed or do you still need assistance with that?


Thanks,
Franco

**Comment by mimugmail** [comment]
@yves-vogl I'd be glad if you could test the plugin. It should work as is right now, but some beta testers would be fine. 

If you could switch to 17.7 and install the plugin and check if everything works as expected would be a great step forward to stable.

**Comment by yves-vogl** [comment]
Alright, I'll do this.

**Comment by yves-vogl** [comment]
I've switched to 17.7 yesterday.
Installation of the package was successful (see Screenshots)
![screen shot 2017-08-03 at 11 44 46](https://user-images.githubusercontent.com/21128/28916081-4f4d9b34-7841-11e7-8623-609f4c48498f.png)
![screen shot 2017-08-03 at 11 44 56](https://user-images.githubusercontent.com/21128/28916086-54194758-7841-11e7-8317-4b145b465af0.png)

After installation the collectd services shows up successfully.

Here are my comments:

- *Hostname* could be taken from the hostname of the firewall
- *Network collector host* does not allow to use a FQDN (validation fails)
- An InfluxDB writer would be nice. This is something I could work on for a later version
- After saving a working configuration an UI feedback would be great
- Functionality of *FQDN lookup* is not clear


I've setup the collectd with the network collector and username/password authentication - but without encryption. This works!
Data looks OK - Grafana can plot those values.
![screen shot 2017-08-03 at 12 03 56](https://user-images.githubusercontent.com/21128/28916876-ed6aac1a-7843-11e7-98ff-9de5a9dd3026.png)

**Comment by mimugmail** [comment]
@yves-vogl Thanks for testing, I put a PR for your requested changes in #218 

@fichtner Regarding Influx perhaps you could check the parameters when compiling collectd. http and influx is not supported by binary.

**Comment by fichtner** [comment]
done
