### ISSUE TITLE
net/frr: Migration needed for 1.21?

### ISSUE THREAD

**Issue by marcquark** [opnsense/plugins#2170]
**Important notices**
Our forum is located at https://forum.opnsense.org , please consider joining discussions there in stead of using GitHub for these matters.

Before you ask a new question, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

I'm wondering whether we will need a migration after merging https://github.com/opnsense/plugins/pull/2143 to remove the old ruby script from existing installations?
Similarly, will a migration also need to take care of uninstalling ruby, or are packages without dependencies automatically removed during updates?

I currently can't test it, but i'm sure one of the more knowledgeable Devs will be able to tell :-) If a migration is needed, feel free to assign the ticket to me. I'll probably find time over the weekend to write a small script.

**Comment by AdSchellevis** [comment]
pkg should take care of removal, since there are no model changes we should be safe there as well.

**Comment by marcquark** [comment]
tested an upgrade today. pkg cleans up everything. looks good, closing.
