### ISSUE TITLE
select which disks are displayed in smart widget

### ISSUE THREAD

**Issue by thatso** [opnsense/plugins#2171]
I've recently installed OPNsense on a Zotac Zbox CI329 nano. It runs fine, however this PC has a built-in SD card reader which cannot be disabled in BIOS. Unfortunately, the SMART plugin recognizes this unused and otherwise empty reader (there is no card in it) as drive da0 with status _unknown_ in the dashboard widget while the real SDD shows as ada0 with status _ok_.
Hence, I would like an option to select which drives are shown in the widget or the possibility to have smartd ignore this drive in the first place.

**Comment by dli417** [comment]
Hey, I am also experiencing a similar situation. I’m running OPNsense on a Dell Wyse 5070 extended with 16gb eMMC that cannot be disabled via BIOS. It would be great to have the option to hide these non-SMART drives in the SMART widget.

**Comment by dli417** [comment]
As a workaround (and if not using the MMC device in OPNsense), I have found that adding the following to system tunables or to /boot/loader.conf.local will remove the MMC drive from the SMART widget:

hint.mmc.0.disabled="1"
hint.mmcsd.0.disabled="1"
hint.sdhci.0.disabled="1"
hint.sdhci_acpi.0.disabled="1"
hint.sdhci_pci.0.disabled="1"
