### ISSUE TITLE
Private server URL for os-acme-client

### ISSUE THREAD

**Issue by hboetes** [opnsense/plugins#2173]
Of course the primary use for the os-acme-client is to work with letsencrypt. But the protocol is open and can also be used to communicate with other servers.

Since we have our own company CA and refreshing certificates is quite a bit of work and forgetting to upgrade could lead to disaster I'd like to use acme to update the certificates.

The only thing that — as far as I can tell — is missing is the possibility to configure a custom acme server URL.

If anyone can implement that, that would be magnificent.

**Comment by fraenki** [comment]
If someone provides a PR, then I'll gladly review it. But I'm not going to work on this feature.
