### ISSUE TITLE
net/relayd: Add UDP/TCP protocol selector for redirects

### ISSUE THREAD

**Issue by hoalex** [opnsense/plugins#2176]
When editing a virtual server entry in redirect mode, it would be nice to include a dropdown whether to use UDP or TCP for the listening port. Currently, the resulting `relayd.conf` file does not include any "ip-proto" value, thereby defaulting to TCP. This makes it impossible to configure a UDP redirect (e.g. for DNS balancing).

The FreeBSD doc says:

> _listen on address **[ip-proto]** port port [interface name]_
> 
> Specify an address and a port to listen on.  pf(4) will redirect
> incoming connections for the specified target to the hosts in the
> main or backup table.  The port argument can optionally specify a
> port range instead of a single port; the format is
> min-port:max-port. **The optional argument ip-proto can be used to**
> **specify an IP protocol like tcp or udp; it defaults to tcp**.  The
> rule can be optionally restricted to a given interface name.

**Comment by sde1aney** [comment]
+1 for this, would mean we can remove our existing F5BIGIP from the network path for a lot more stuff.

**Comment by mimugmail** [comment]
Shouldnt this already work with nginx plugin?

**Comment by sde1aney** [comment]
@mimugmail
I've not yet located an option for specifying interfaces to bind to for the NGINX plugin. HAproxy and relayd have this very visible.
In my specific case I need to have multiple TCP and UDP load balancers, bound on different addresses and routing to different backend servers.
If NGINX is able to do this, then great. I just need to find the right configuration options to allow it.

**Comment by fbrendel** [comment]
@hoalex yes the `ip-proto` is missing.
I'll put that on my list.
