### ISSUE TITLE
security/acme-client: Disabling Auto Renewal doesn't stop auto renewal

### ISSUE THREAD

**Issue by maurice-w** [opnsense/plugins#2178]
[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
[x] I have searched the existing issues and I'm convinced that mine is new.
[x] The title contains the plugin to which this issue belongs

**Describe the bug**
Disabling Auto Renewal for individual certificates has no effect. All certificates auto renew if Auto Renewal is enabled in the global settings.

**To Reproduce**
1. Go to 'Services: Let's Encrypt: Settings' and make sure that Auto Renewal is enabled globally
2. Go to 'Services: Let's Encrypt: Certificates'
2. Add a new certificate (or edit an existing one) and disable Auto Renewal
3. Wait for the Renewal Interval to expire
4. The certificate will auto renew

**Expected behavior**
Certificates which have Auto Renewal disabled should not auto renew.

**Environment**
OPNsense 20.7.7_1 (amd64, OpenSSL).
os-acme-client 2.2
DNS-01 challenge

**Comment by fraenki** [comment]
@maurice-w Please provide the logs for os-acme-client (navigate to `System: Log Files: General`, enter "AcmeClient" as search string).

**Comment by maurice-w** [comment]
For further testing, I disabled Auto Renewal globally ('Services: Let's Encrypt: Settings'). This created one log entry:
`2021-01-11T19:13:06 | api[33557] | AcmeClient: HAProxy plugin is NOT installed, skipping integration`

I also made sure there's nothing left in 'System: Settings: Cron'. But still, a renewal was triggered at midnight (log sanitized):
```
2021-01-12T00:00:00 | config[86941] | AcmeClient: issue/renewal not required for certificate: test2.example.com
2021-01-12T00:00:00 | opnsense[86941] | AcmeClient: validation for certificate failed: test.example.com
2021-01-12T00:00:00 | opnsense[86941] | AcmeClient: domain validation failed (dns01)
2021-01-12T00:00:00 | opnsense[86941] | AcmeClient: using challenge type: DNS-01
2021-01-12T00:00:00 | opnsense[86941] | AcmeClient: account is registered: Test
2021-01-12T00:00:00 | opnsense[86941] | AcmeClient: renew certificate: test.example.com
2021-01-12T00:00:00 | opnsense[86941] | AcmeClient: certificate must be issued/renewed: test.example.com
```
Then I rebooted OPNsense. No renewal was triggered the following midnight (nothing in the log at 2021-01-13T00:00:00).

Now I re-enabled the global Auto Renewal setting (while leaving it disabled in the certificate settings). This created two log entries:
```
2021-01-13T00:03:30 | api[57889] | AcmeClient: HAProxy plugin is NOT installed, skipping integration
2021-01-13T00:03:30 | config[93298] | [OPNsense\AcmeClient\AcmeClient:settings.UpdateCron] Related cron not found.
```

The cron job is now back in 'System: Settings: Cron'. We'll see what happens in 24 hours.

**Comment by maurice-w** [comment]
After further investigation, I've now identified two separate issues related to Auto Renewal:

1. Changing the global Auto Renewal setting ('Services: Let's Encrypt: Settings') requires a reboot to become effective. The cron job is added / removed immediately (see 'System: Settings: Cron'), but a reboot is required for the system to behave accordingly.
2. The original issue remains: As long as Auto Renewal is enabled globally, all certificates auto renew. Disabling Auto Renewal for individual certificates has no effect. "AcmeClient: certificate must be issued/renewed" is written to the log if a certificate is older than 60 days, "AcmeClient: issue/renewal not required for certificate" otherwise. (I didn't change the default 60 day Renewal Interval, just disabled Auto Renewal for some certificates.)

**Comment by fraenki** [comment]
I can confirm this bug. The code to handle this feature is missin. Looks like I forgot to implement it (it's also missing from os-acme-client version 1.x). I'll try to fix this in the next release.

**Comment by fraenki** [comment]
@maurice-w You may try this patch:

```
opnsense-patch -c plugins 6751020b8d08ef64d06fdce4b51e76e3837dd013
```

You may speedup testing by manually running the cron job task:

```
configctl acmeclient cron-auto-renew
```

When auto renewal is disabled in plugin settings, the following message will be logged:

```
AcmeClient: auto renewal is globally disabled, skipping certificate: test.example.com
```

If auto renewal is enabled in plugin settings, but disabled in certificate settings:

```
AcmeClient: auto renewal is disabled for certificate: test.example.com
```

**One question:** It is currently implemented to only skip auto renewal for cron jobs. When using the GUI button "Issue/Renew Certificates Now", then certificates would still be renewed. Is this the expected behaviour? Or should renew also be skipped when using the GUI button?

**Comment by fraenki** [comment]
The fix will be available in the upcoming os-acme-client version 2.3 (#2199).

**Comment by maurice-w** [comment]
Indeed, disabling auto renewal for individual certificates now works. Thanks!
And I agree that this setting having no effect on the renew certificates now button is expected behaviour.
Changing the global auto renewal setting still requires a reboot to become effective. Not a big deal, but maybe a little hint in the UI would be helpful.

**Comment by fraenki** [comment]
> Changing the global auto renewal setting still requires a reboot to become effective

Maybe you need to elaborate more on this, because I cannot reproduce this issue.

When "Auto Renewal" is enabled, the following cron job is added:

```
root@opnsense:~ # crontab -l -u nobody
...
# Origin/Description: AcmeClient/AcmeClient Cronjob for Certificate AutoRenewal
0	0	*	*	*	/usr/local/sbin/configctl acmeclient cron-auto-renew 
```

When I disable "Auto Renewal" in `Services: Let's Encrypt: Settings` and click on "Apply", then the cron tab is empty:


```
root@opnsense:~ # crontab -l -u nobody
# or /usr/local/etc/cron.d and follow the same format as
# /etc/crontab, see the crontab(5) manual page.
SHELL=/bin/sh
PATH=/etc:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
#minute	hour	mday	month	wday	command
```

Without this cron job, there is no way the auto renewal process could be started.

Please double-check if you have a second cron job in `System: Settings: Cron`, this might explain your issue.

**Comment by maurice-w** [comment]
The cron job gets added / removed, but a reboot is required for cron to honour the change. This can't be reproduced by looking at the crontab (which indeed looks fine). You have to check the system log whether the cron job actually runs.

I now figured out that going to 'System / Settings / Cron' and simply clicking 'Apply' (without changing anything) has the same effect as a reboot. So it seems that the ACME plugin is missing some essential step when reconfiguring cron. Maybe you have to "tell cron that the crontab changed" (for lack of better words)?

**Comment by fraenki** [comment]
@maurice-w I think I finally found the root cause for the cron job issue while working on another issue. os-acme-client 2.5 will contain a fix.
