### ISSUE TITLE
Bootgrid table with customized action buttons in row

### ISSUE THREAD

**Issue by 8191** [opnsense/plugins#2181]
**Important notices**
Our forum is located at https://forum.opnsense.org , please consider joining discussions there in stead of using GitHub for these matters.

Before you ask a new question, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

- [x] I have searched the existing issues and I'm convinced that mine is new.

I'm trying to create a MVC view which consists out of a bootgrid table, but with an additional action button. Is there a way to use `UIBootgrid` from [opnsense_bootgrid_plugin.js](https://github.com/opnsense/core/blob/master/src/opnsense/www/js/opnsense_bootgrid_plugin.js) for that table?

I searched through most plugins and core components, and each page which requires custom action buttons just copied and pasted most content of opnsense_bootgrid_plugin.js to the volt template. Not sure if that's the right way to go? Or did I oversee something...?

**Comment by AdSchellevis** [comment]
@8191 you only want to add additional actions? you can overwrite the command section or add a new one, I still have some documentation stashed for the docs which I need to publish (https://github.com/opnsense/docs/commit/aca5f2412cb670b78061e6baf6a20d887c5454bb), the closest example I could find in our code was this one (assuming your are looking for the customisable buttons)

https://github.com/opnsense/core/blob/de291e62660996b04d589381cad3396db5e9eb80/src/opnsense/mvc/app/views/OPNsense/Firewall/alias_util.volt#L13-L24

**Comment by 8191** [comment]
@AdSchellevis Thanks for the link to the documentation and the example!
Overriding the command section is one thing (even this already requires copy-and-paste of the "rowtoggle" and "boolean" sections in most cases), I didn't find an efficient way how to hook the commands to the buttons, but that's clear now thanks to your example:
https://github.com/opnsense/core/blob/de291e62660996b04d589381cad3396db5e9eb80/src/opnsense/mvc/app/views/OPNsense/Firewall/alias_util.volt#L25-L26
