### ISSUE TITLE
Feature request: ntopng plugin - allow additional settings for ntopng.conf

### ISSUE THREAD

**Issue by mihakralj** [opnsense/plugins#2185]
The configuration form for ntopng plugin doesn't allow any custom/additional configuration settings as described at https://www.ntop.org/guides/ntopng/how_to_start/configuration_file.html

**ntopng.conf** gets rewritten each time the form is saved, leaving no place to add custom configuration settings to ntopng.

Suggestion: an additional field 'Custom options' that would be appended at the bottom of generated **ntopng.conf** - similar to Custom options field on Unbound configuration form.

**Comment by mimugmail** [comment]
Which options do you miss?

**Comment by mihakralj** [comment]
# force community edition license
--community 
# identify local networks
-m ="192.168.0.0/16"
# file with custom app categories
-p custom_categories.conf

**Comment by fichtner** [comment]
Just because it's relevant to the original request: https://docs.opnsense.org/development/guidelines/basics.html?highlight=custom#safeguard-user-input

We do not offer custom configuration fields that defy validation methods.

**Comment by mihakralj** [comment]
OK, how about we add the first two fields then - should be relatively low effort:
1. the checkbox (turned on by default) for "ntopng community edition"
2. the field (with CIDR validation) for "local networks"

The third one (custom categories) might wait - it would require a new form that would generate a new .conf file.

**Comment by mihakralj** [comment]
@fichtner Can we just add the `--community` option into the ntopng plugin form?
I have to manually add `--community` flag directly into ntopng.conf each and every time that OPNSense decides to rewrite it...

**Comment by fichtner** [comment]
@mimugmail is already on it 😊
