### ISSUE TITLE
security/acme-client provide Tooltips for small Command-Icons

### ISSUE THREAD

**Issue by oli-h** [opnsense/plugins#2188]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues and I am convinced that mine is new.

**Is your feature request related to a problem? Please describe.**

In the GUI of the Plugin "Let's Encrypt" under tab "Certificates" (i.e: https://MYOPNSENSE/ui/acmeclient/certificates) we have _seven_ command-buttons. Some of them can be identified quite easily to understand what will probably happen when you click it. E.g. "edit" or "delete" 
But most buttons are hard to understand. E.g. the "paper plane" (4th icon) will do what? Start an aircraft? (just kidding).
I am missing tooltips when I hover the mouse-pointer on the icons

**Describe the solution you like**

Propose to add tooltips which pop-up when you mouse-hover: "edit" "copy" "sign" etc..
Ideally a short description would also be helpful

**Describe alternatives you considered**

none. Sorry

**Additional context**

![ACME commands](https://user-images.githubusercontent.com/20283081/104654201-03a64200-56bc-11eb-8c34-4d0c2fd0a4b0.jpg)

**Comment by fraenki** [comment]
Tooltips are not part of the overall OPNsense UI design. I will not add this just for this plugin, it needs to exist in OPNsense core first.

**Comment by oli-h** [comment]
Ah ok - thanks for this information. Good arguments.

**Comment by fichtner** [comment]
The issue very quickly circles back to plugins where the icon has no obvious meaning like was the case here. In the end, to explain the behaviour (which is what this ticket is about) it is a case by case fix.

We can probably add a core mechanism to place tooltips on "well-known" icons, but again it doesn't solve the issue of what buttons really do in complex scenarios.


Cheers,
Franco

**Comment by fraenki** [comment]
@fichtner Thanks for taking immediate action. Tooltips haven't been around for 6 years, so I was assuming that it wasn't part of the overall UI design.

> The issue very quickly circles back to plugins where the icon has no obvious meaning like was the case here

Everyone is free to propose different icons and I will replace them.

**Comment by fraenki** [comment]
I've added (preliminary) tooltips in the upcoming os-acme-client version 2.4. I'll probably have to adjust them once https://github.com/opnsense/core/issues/4608 is implemented, but it gets the job done for now.

**Comment by oli-h** [comment]
Guysm you're so cool. Thx for all your work

**Comment by fichtner** [comment]
Hi @fraenki,

You can keep your elaborate tooltips in place, but in order to active the consistent tooltip style in 21.7 add the class "bootgrid-tooltip" to the buttons.


Cheers,
Franco

**Comment by fraenki** [comment]
Tooltip styles will be updated in os-acme-client 3.0.
