### ISSUE TITLE
Feature request: plugins/security/stunnel Client mode

### ISSUE THREAD

**Issue by tuxnet** [opnsense/plugins#2194]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

[x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
Currently STunnel can only be run in server mode.

**Describe the solution you'd like**
Adding a "client mode" checkbox in the configuration menu.
This is to operate the connection in client mode (i.e. the connection to an SSL server and not act as a server).
In the stunnel.conf file "client = yes" must be added.

**Describe alternatives you've considered**
A custom options text field could be added.

**Additional context**
Example of client configuration (stunnel.conf):

```cert = /usr/local/etc/stunnel/stunnel.pem
chroot = /var/tmp/stunnel
chroot = /var/tmp/stunnel
setuid = stunnel
setgid = stunnel

[TEST]
client = yes
cert = /usr/local/etc/stunnel/60066d1dd714a.pem
accept = 127.0.0.1:1234
connect = test.example.com:123
debug = 5
TIMEOUTclose = 0```

**Comment by tuxnet** [comment]
Example of client configuration (stunnel.conf):
```cert = /usr/local/etc/stunnel/stunnel.pem
chroot = /var/tmp/stunnel
setuid = stunnel
setgid = stunnel

[TEST]
client = yes
cert = /usr/local/etc/stunnel/60066d1dd714a.pem
accept = 127.0.0.1:1234
connect = test.example.com:123
debug = 5
TIMEOUTclose = 0```

**Comment by AdSchellevis** [comment]
looks like https://github.com/opnsense/plugins/pull/2166
