### ISSUE TITLE
[os-bind] Bind always use hard-coded and provided rndc-key

### ISSUE THREAD

**Issue by expeditioneer** [opnsense/plugins#2196]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[+] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[+] I have searched the existing issues and I'm convinced that mine is new.

[+] The title contains the plugin to which this issue belongs

**Describe the bug**
Currently the _rndc-key_ is hard coded. After a  manual change via console it is always replaced during a reboot with:

```bash
key "rndc-key" {
        algorithm hmac-sha256;
        secret "VxtIzJevSQXqnr7h2qerrcwjnZlMWSGGFBndKeNIDfw=";
};
```

**Expected behavior**
It would be great if the _rndc-key_ also the used algorithm could be defined in the GUI.

It would be also possible move the _rndc-key_ into a separate file which could be included into the _named.conf_

**Environment**
OPNsense 20.7.8-amd64
FreeBSD 12.1-RELEASE-p12-HBSD
LibreSSL 3.2.3
os-bind 1.14

**Comment by elforesto** [comment]
Important note on this, the built-in DHCPv4 service requires that the key be either hmac-md5 or hmac-sha512. (See #4136.) Resolving this is a good opportunity to also address this shortcoming. I can't configure dynamic DNS updates in the BIND plugin and have them persist without this change.

**Comment by mimugmail** [comment]
So, would a dropdown list with supported algo's and a text field for entering the key be sufficient? Or are there more options which might make sense?

**Comment by elforesto** [comment]
I think the more logical expectation is that you can click New Key, pick an algorithm, and then either fill a text box with the key OR check a box to generate a new key. In the background, this would require running tsig-keygen and capturing the output to write to the config file. As op suggested, it may be a better design to store each key in its own file and use the include directive in the main conf file.

This is one part of the puzzle, though. Once you can generate keys you need the ability to specify where and when they should be used. My use case (I can't speak to op) is to enable dynamic DNS updates from DHCP. This requires an update in the GUI so you can enable updates (enable-update directive) and pick from the list of valid keys to specify which key is required to update each zone. But that may be better broken out to a separate issue.

**Comment by expeditioneer** [comment]
@elforesto I have the same need, there is already a second ticket for that, see https://github.com/opnsense/plugins/issues/2197

**Comment by Sverto** [comment]
I was also looking into this.
Temporary workaround:

Generate key:
`tsig-keygen -a hmac-sha512 rndc-key`

Modify the template instead of the generated file with the new key:
`vi /usr/local/opnsense/service/templates/OPNsense/Bind/named.conf`

Change the following line:
`zone "{{ domain.domainname }}" { type {{ domain.type }}; {%` ...
to
`zone "{{ domain.domainname }}" { type {{ domain.type }}; allow-update { 127.0.0.1; }; {%` ...

Add 127.0.0.1 to your allow-query ACLs.

Fix file permission denied error with:
`chown bind:wheel /usr/local/etc/namedb/master`

...

**Comment by elforesto** [comment]
> I was also looking into this.
> Temporary workaround:
> 
> Generate key:
> `tsig-keygen -a hmac-sha512 rndc-key`
> 
> Modify the template instead of the generated file with the new key:
> `vi /usr/local/opnsense/service/templates/OPNsense/Bind/named.conf`
> 
> Change the following line:
> `zone "{{ domain.domainname }}" { type {{ domain.type }}; {%` ...
> to
> `zone "{{ domain.domainname }}" { type {{ domain.type }}; allow-update { 127.0.0.1; }; {%` ...
> 
> Add 127.0.0.1 to your allow-query ACLs.
> 
> Fix file permission denied error with:
> `chown bind:wheel /usr/local/etc/namedb/master`
> 
> ...

Those instructions worked great for me. Thanks!

Side node, you can use key rndc-key in place of 127.0.0.1 if you want to lock it down to allowing by key rather than just IP.

**Comment by mimugmail** [comment]
Please reopen and assign to me

**Comment by AdSchellevis** [comment]
@mimugmail done
