### ISSUE TITLE
FRR: Add confederation GUI options.

### ISSUE THREAD

**Issue by Napsterbater** [opnsense/plugins#2202]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

[x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
Unable to use OPNsense with FRR in a BGP Confederation.

**Describe the solution you'd like**
Would like BGP Confederations options added to the UI since there is no custom/raw config options.

**Describe alternatives you've considered**
RAW/Custom config, but will not be added per https://github.com/opnsense/plugins/issues/1831

**Additional context**
Need 2 new fields in the GUI, hidden under advanced in the General Tab that control these 2 lines in the FRR config.

 bgp confederation identifier <"External" ASN, used when connecting with non confed. peer.>
 bgp confederation peers <Space separated list of confed. peers>

I.e.:
 bgp confederation identifier 4242421050
 bgp confederation peers 4200000001 4200000003 4200000010

**Comment by Napsterbater** [comment]
Also, need an option to apply a route-map to a network statement. 

Network: 10.0.1.0/24  (add a 2nd dropdown to the right) Route-map: rm-no-export
Of Course the routemap will be the dropdown of Route-maps that are already specified.

Which would cause the config network statement to look like this:
network 10.0.1.0/24 route-map rm-no-export

**Comment by mimugmail** [comment]
The first one is easy, the second one will break as multiple networks are allowed to add, or so you need this for all?

**Comment by Napsterbater** [comment]
By 2nd one are you talking about the route map for network statements. Because the reason I hit hide for that is because apparently it actually works already, I didn't expect it to. I simply added the subnet with the statement route map and the name of the route map and it adds into the config just as it should. But no validation which works exactly how I need it.

But right now route maps must be numbers when added in the GUI. Even though FRR can take a "name", which makes it MUCH easier to know what route map is what, since at least only refers to the route map number. 

I'm mobile right now Ill try and add more helpful details tonight.

Also I found an issue in routes maps where they will not apply the set option unless you add a filter or something to it aswell, which again FRR does not require. Again I'll add more detail tonight.

**Comment by Napsterbater** [comment]
### Specify Route-map for network statement.
![Capture](https://user-images.githubusercontent.com/18711451/105774830-cb142d00-5f33-11eb-8109-584071e5fd92.PNG)
```
address-family ipv4 unicast
  network 10.0.0.1/32 route-map rm-no-export
  network 10.0.0.40/29 route-map rm-no-export
  network 10.0.1.0/24 route-map rm-no-export
  network 10.0.14.0/24 route-map rm-no-export
  network 10.0.30.0/24 route-map rm-no-export
  no neighbor fda9:26a9:1c47::2 activate
 exit-address-family
 !
 address-family ipv6 unicast
  network ::/0 route-map rm-no-export
  network 2000::/3 route-map rm-no-export
  network 2001:470:****:1::/64 route-map rm-no-export
  network 2001:470:****:6::/64 route-map rm-no-export
  network 2001:470:****:1030::/64 route-map rm-no-export
  network fda9:26a9:1c47::40/124 route-map rm-no-export
  network fda9:26a9:1c47:1::/64 route-map rm-no-export
  network fda9:26a9:1c47:1030::/64 route-map rm-no-export
  neighbor fda9:26a9:1c47::2 activate
  neighbor fda9:26a9:1c47::2 next-hop-self
  neighbor fda9:26a9:1c47::2 default-originate
  neighbor fda9:26a9:1c47::2 prefix-list BlockDefaultIPv4 in
  neighbor fda9:26a9:1c47::2 prefix-list BlockDefaultIPv4 out
  neighbor fda9:26a9:1c47::2 route-map rm-no-export in
  neighbor fda9:26a9:1c47::2 route-map rm-no-export out
 exit-address-family
```
As you can see the the adding route map to a network statement worked perfectly.

### Route-map requiring specifying a AS-Path List, Prefix List or a Community List before defining the set statement in the config.
As for the route-map issue of not adding a "set" statement if there if no list if defined is also a problem, there is no requirement in frr for any list/match statements, no match statement means match all.

Also note Route-map "ID" should be called Sequence, Order or Order ID or such, seems . ID to me implies the "Name".
Seems the different areas of the Plugin switch names calling basically the same thing either "ID", "Number" or "Sequence Number" depending on what page you are on.

![Capture2](https://user-images.githubusercontent.com/18711451/105775314-a1a7d100-5f34-11eb-9ea1-df19fa9468c3.PNG)

```
!
route-map rm-no-export permit 10
!
route-map rm-no-export permit 20
!
```

### Other General finds.
Multiple Lists:
Action is multi select, though input validation properly catches this, it should not be multi select.

AS path:
"Number" Should be "Name", especially since Route Maps seems to refer to it by the number/name and not the description.

Prefix List:
IP Version is multi select, though input validation properly catches this, it should not be multi select.
"Sequence" limited to 10-99, FRR supports 1 to 4294967295

Route Maps:
ID limited to 10-99, FRR supports 1-65535, and name should change to Sequence or something common.

**Comment by mimugmail** [comment]
Please reopen and assign to me

**Comment by AdSchellevis** [comment]
@mimugmail there you go
