### ISSUE TITLE
Pihole

### ISSUE THREAD

**Issue by pablocarreraest** [opnsense/plugins#2212]
I'm new at here but is posible to add integration with pihole or is there a way to add "adlist group management" for use existing and well made list to block ads like: https://dbl.oisd.nl

**Comment by jakub-svoboda-ch** [comment]
https://docs.opnsense.org/manual/unbound.html#predefined-sources

**Comment by pablocarreraest** [comment]
amazing so there is a way to predefined sources on opnsense as pihole.

I think this will answer my question and thank you for point me out.

have a great day
