### ISSUE TITLE
[Wireguard] Dashboard shows part of public key in table of Endpoint

### ISSUE THREAD

**Issue by anefkens** [opnsense/plugins#2217]
**Describe the bug**
When using the dashboard for Wireguard, it shows the public keys of the endpoint to identify the endpoints. I would have expected to see the name of the endpoint instead.

**To Reproduce**
1. Setup WireGuard VPN Service
2. Add Wireguard to the Dashboard
3. Save the dashboard
4. See part of the public key in the list under endpoints

**Expected behavior**
The actual name for each VPN client in the column of Endpoint

**Screenshots**
<img width="517" alt="Screenshot 2021-02-05 at 14 31 41" src="https://user-images.githubusercontent.com/1443738/107040350-67a1bf00-67bf-11eb-8169-2b555510bec4.png">

**Environment**
OPNsense 21.1-amd64
FreeBSD 12.1-RELEASE-p12-HBSD
OpenSSL 1.1.1i 8 Dec 2020
AMD GX-412TC SOC (4 cores)
PC Engines apu4

**Comment by sorano** [comment]
There is actually already an old issue for this: #1958

And a PR that's been cooking for a while: #1970

So if you want to you can manually edit the php files with the changes from that PR.

(Offtopic, fellow AFOL eh? 😃 )

**Comment by anefkens** [comment]
Thanks,  I’ll take a look.

(Offtopic: yep and proud of it… ;-) Was planning to visit Billund this year, but considering the restrictions do not think it will happen this year… )

**Comment by pagong** [comment]
You might also consider using 
https://github.com/warner/wireguard-vanity-address 
for generating public keys that start with a string that has some meaning to you.
