### ISSUE TITLE
Enable user entry of exit/entry nodes on the TOR gui

### ISSUE THREAD

**Issue by aimdev** [opnsense/plugins#2221]
Currently adding entry/exit nodes on the TOR gui does not exist
The torrc file can be edited, however any changes are lost if the gui page for TOR is updated.
Request that the entry/exit nodes settings be added to improve the security of TOR

**Comment by mihakralj** [comment]
temporary workaround:

edit `/usr/local/opnsense/service/templates/OPNsense/Tor/torrc` and add desired line items in there. 

For example, I added `DisableDebuggerAttachment 0` so I can run nyx and show open connections.
I also commented-out the section related to FascistFirewall and FirewallPorts - these commands are obsolete and replaced with `ReachableAddress` instead.
