### ISSUE TITLE
security/acme-client: No log files on Let’s Encrypt by production environment

### ISSUE THREAD

**Issue by arnaud056** [opnsense/plugins#2227]
Hi,

**The issue:**
on OPNSense 20.7 and 21.1 the plugin Let’s Encrypt doesn't generate logs into /var/log/acme.sh.log when  "Let's Encrypt Environment" is "Production environment".

**How to reproduce the issue:**  
- clear the file  /var/log/acme.sh.log (Services: Let's Encrypt: Log File)
- Services: Let's Encrypt: Settings:  "Let's Encrypt Environment" => "Production environment" and "Log Level" => "normal" or "debug"
- Services: Let's Encrypt: Accounts is registered
- Services: Let's Encrypt: Challenge Types: "http-01"
- Services: Let's Encrypt: Certificates: renew one of the certs on clicking on the arrow
- reload Services: Let's Encrypt: Certificates: "Issue/Renewal Date" and "Last Acme Run" show the current date and time
- Services: Let's Encrypt: Log File: "File /var/log/acme.sh.log yielded no results."

**Information:**
- "acme.sh" has been launched:  "System: Log Files: General" shows `AcmeClient: running acme.sh command: /usr/local/sbin/acme.sh --issue --debug --webroot /var/etc/acme-client/challenges etc.....`
- selecting Services: Let's Encrypt: Settings:  "Let's Encrypt Environment" => "staging environment" and renew the cert as described: in this case the logs are present into  /var/log/acme.sh.log

Please let me know if further info is needed.
Bye
Arnaud

**Comment by fraenki** [comment]
@arnaud056

* Do you have `/var RAM disk`enabled in `System: Settings: Miscellaneous`? (logs get lost on reboot)
* Is this a new installation of os-acme-client?

It might be an issue for _new_ installations, maybe some default options in acme.sh have changed recently. I'll have to verify this.

**Comment by mimugmail** [comment]
I had this too recently. I worked on stage and stopped at some point (but worked in the end)

**Comment by arnaud056** [comment]
Hi,
>     * Do you have `/var RAM disk`enabled in `System: Settings: Miscellaneous`? (logs get lost on reboot)
no I haven't  `/var RAM disk`enabled  and the issue happen immediately after a cert renew. No reboot in between.

>     * Is this a new installation of os-acme-client?
I would say I installed it about 2 months ago.

**Comment by Xboarder56** [comment]
> @arnaud056
> 
> * Do you have `/var RAM disk`enabled in `System: Settings: Miscellaneous`? (logs get lost on reboot)
> * Is this a new installation of os-acme-client?
> 
> It might be an issue for _new_ installations, maybe some default options in acme.sh have changed recently. I'll have to verify this.

I have tried a brand new installation of 21.1 and installing only acme with the same log issue.

**Comment by fraenki** [comment]
I think I've found the root cause. Feel free to test the patch and report back:

```
opnsense-patch -c plugins 3a029db4
```

**Comment by Xboarder56** [comment]
> I think I've found the root cause. Feel free to test the patch and report back:
> 
> ```
> opnsense-patch -c plugins 3a029db4
> ```

This patch worked perfect. I restarted acme client did a force issue and it started logging.

**Comment by arnaud056** [comment]
Hi,
the patch works by me too.
Many thanks for the job.
