### ISSUE TITLE
net/haproxy: Download of files larger than 100K fail with os-haproxy 2.26

### ISSUE THREAD

**Issue by passuf** [opnsense/plugins#2230]
**Describe the bug**
After updating to the latest OPNSense and HAProxy plugin version, larger files behind the HAProxy cannot be served. After downloading about 60K the connection times out, and when retrying the next 60K are downloaded. This breaks my website as JavaScript files larger than 100K cannot be served.

**To Reproduce**
1. Go to Services > HAProxy and create a Public Service (including a Real Server, Backend Pool, etc.)
2. Serve some files, e.g. a 600K JavaScript file
3. Try to download these files, e.g. using `wget`

**Example Download** 
This is an example output when trying to download a 600K JavaScript file using wget:

```bash
# wget example.org/assets/webpack/main.67c0a6c0.chunk.js
main.67c0a6c0.chunk.js.7     9%[==>                                   ]  63.64K  --.-KB/s    in 30s 
2021-02-10 17:08:39 (2.16 KB/s) - Connection closed at byte 65169. Retrying.

main.67c0a6c0.chunk.js.7    18%[+++===>                               ] 127.29K  --.-KB/s    in 30s     
2021-02-10 17:09:10 (2.15 KB/s) - Connection closed at byte 130344. Retrying.

main.67c0a6c0.chunk.js.7    27%[+++++++==>                            ] 187.64K  --.-KB/s    in 0.05s   
2021-02-10 17:09:42 (1.28 MB/s) - Connection closed at byte 192145. Retrying.

...
```

When downloading the same file using a browser, the site keeps loading until the timeout is reached.

**Expected behavior**
The download should not time out or fail.

**Relevant log files**
No relevant logs are created in HAProxy plugin or OPNSense logs.

**Environment**
This is the current environment, where the problem occurs:
- OPNsense 21.1.1-amd64
- os-haproxy 2.26
- Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (2 cores)
- 4GB or RAM

This is the previous environment, where the problem did not occur:
- OPNsense 20.7.4-amd64
- os-haproxy 2.25
- Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (2 cores)
- 4GB or RAM

**Comment by fraenki** [comment]
Nothing in the HAProxy _plugin_ version 2.26 would explain this issue. In fact, this version only contains [minor changes](https://github.com/opnsense/plugins/blob/master/net/haproxy/pkg-descr). It is more likely that you've hit a HAProxy bug. I'd suggest to search the HAProxy [issue tracker](https://github.com/haproxy/haproxy/issues), [mailing list](https://www.mail-archive.com/haproxy@formilux.org/) or [changelog](https://www.haproxy.org/download/2.0/src/CHANGELOG) if you can spot your issue.

**Comment by passuf** [comment]
Thanks for checking the changes and pointing me to the right direction!

I played with different configurations and I suspect that the problem is related to LibreSSL version 3.2.3, probably in combination with HAProxy. Switching to OpenSSL solved the problem so far, will do further experiments.

Will close the issue for now, thanks again for your help!

**Comment by fichtner** [comment]
There is an update for LibreSSL coming to 21.1.2 that seems to fix multiple compatibility issues: https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-3.2.4-relnotes.txt

Not sure this will resolve it, but with all the oddities around LibreSSL in various third party tools that may be a step into the right direction.


Cheers,
Franco
