### ISSUE TITLE
relayd: Usability improvements

### ISSUE THREAD

**Issue by ltning** [opnsense/plugins#2232]
**Is your feature request related to a problem? Please describe.**
The current status UI for `relayd` is somewhat unwieldy with a significant number of virtual servers/tables. It also has some other usability issues that makes it difficult and error-prone.

**Describe the solution you'd like**

Specific issues I'd like to see addressed, order of priority:
- being able to disable a backend while it's down, preventing it from joining the pool even if it comes back up
- make sure stopping/starting a backend from the status display is reflected there without having to refresh
- allow filtering the displayed entries, to make sure we only see/operate on a given (set of) virtual servers, for instance
- being able to sort the status view (and preferably persist the sort order)

More difficult:
We need a way to determine the reason for a given host being marked as down. E.g. when using HTTP(S) checks, we would like to be able to quickly determine what was returned by the test. If there would be a way to link directly to log entries corresponding to the state of the host in question, that would go a long way towards helping us.

Subject to taste/discussion:
I would like to reduce the "busyness" of the display when there are lots of entries. Specifically, we are going to have 2-3 dozen virtual servers, each with 1 or 2 tables, each of which with 2 or 3 hosts. This quickly becomes hard to "digest" when looking at the status page. For example, in our case, we'd usually only need to see the virtual server and the hosts assigned to the primary pool. Some suggestions for how this could be helped:
- Make fallback pool display optional
- Make table column optional (it's redundant if only primary pool is shown)
- Have a dashboard widget listing virtual servers and their state, with direct links to filtered status page

**Describe alternatives you've considered**
We were considering HAProxy but need the transparent load balancing offered by relayd.

**Comment by AdSchellevis** [comment]
closed with https://github.com/opnsense/plugins/pull/2373 and https://github.com/opnsense/plugins/pull/2398

---
sponsored by : Modirum (https://www.modirum.com/)
