### ISSUE TITLE
security/acme-client: OCSP Must Staple checkbox state is not honored

### ISSUE THREAD

**Issue by definitio** [opnsense/plugins#2234]
**Describe the bug**
`acme.sh` is always running without `--ocsp` even when `OCSP Must Staple` ckecked in the certificate settings. I have tried to reset acme client and to revoke a certificate.

**To Reproduce**
1. Enable 'OCSP Must Staple'
2. Issue the certificate

**Expected behavior**
The new certificate must have a `TLS Feature: status_request`.

**Relevant log files**
```
AcmeClient: running acme.sh command: /usr/local/sbin/acme.sh --issue --debug  --dns 'dns_duckdns' --dnssleep '120' --home '/var/etc/acme-client/home' --certpath '/var/etc/acme-client/certs/foo/cert.pem' --keypath '/var/etc/acme-client/keys/foo/private.key' --capath '/var/etc/acme-client/certs/foo/chain.pem' --fullchainpath '/var/etc/acme-client/certs/foo/fullchain.pem' --domain 'foobar.duckdns.org' --domain-alias 'foobar.duckdns.org' --days '1' --force --keylength 'ec-256' --accountconf '/var/etc/acme-client/accounts/67890_prod/account.conf'
```

**Environment**
OPNsense 21.1.1 (amd64, OpenSSL).

**Comment by fraenki** [comment]
I found the bug, feel free to test the following patch and report back:

```
opnsense-patch -c plugins b6bbd6a3
```

**Comment by definitio** [comment]
It works. Thanks!
