### ISSUE TITLE
security/acme-client: deploy certificates to Synology DSM

### ISSUE THREAD

**Issue by nanosonde** [opnsense/plugins#2236]
[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

[x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
Synology does not offer DNS-01 challenges. Only HTTP-01. So the ACME client plugin could come to the rescue.

**Describe the solution you'd like**
Create a new automation which offers the deployment of certificates to Synology DSM using the already existing Synology DSM deployment hook script from acme.sh.
https://github.com/acmesh-official/acme.sh/blob/dev/deploy/synology_dsm.sh
This script also works if Synology DSM has OTP enabled. The device ID has to be provided in this case so that no OTP is required foe the webbook script.

**Additional context**
A tutorial describing the setup using a CLI based setup using acme.sh and deployment to Synology DSM:
https://lippertmarkus.com/2020/03/14/synology-le-dns-auto-renew/

The deployment script uses the Synology Web API to upload the certificate. So you do not have to deal with paths and restarting of a service as this is already handled internally by the API call.

**Comment by fraenki** [comment]
The "synology_dsm" deploy hook will be supported in os-acme-client 3.5.

I couldn't test the actual upload because I don't have access to a Synology DSM, so if someone wants to test it, please apply the following patch and report back:

```
opnsense-patch -c plugins 037ef927
```

**Comment by cbrueffer** [comment]
Fantastic, thanks @fraenki!
