### ISSUE TITLE
net/haproxy: seamless reloads with HAProxy 1.8

### ISSUE THREAD

**Issue by fraenki** [opnsense/plugins#224]
Starting with HAProxy 1.8, which is scheduled to arrive late in 2017, it's possible to reload HAProxy [without dropping packets](https://www.haproxy.com/blog/truly-seamless-reloads-with-haproxy-no-more-hacks/) in the process.

This might also be of interest in the scope of #195, because I assume that open/stalled connections may be blocking the restart.

In addition to seamless reloads we should implement this new feature:

>   - hard-stop-after: this new global setting forces old
>     processes to quit after a delay consecutive to a soft reload operation.
>     This is mostly used to avoid an accumulation of old processes in some
>     environments where idle connections are kept with large timeouts.

**Comment by fraenki** [comment]
I expect HAProxy 1.8 to be [released in November](https://www.mail-archive.com/haproxy@formilux.org/msg27653.html). So this and a HAProxy 1.8 (FreeBSD) port should be ready for OPNsense 18.1 :)

**Comment by fraenki** [comment]
HAProxy 1.8.0 is [here](https://www.mail-archive.com/haproxy@formilux.org/msg28004.html) \o/

**Comment by fraenki** [comment]
HAProxy 1.8.0 is already available in FreeBSD as [net/haproxy-devel](https://www.freshports.org/net/haproxy-devel/).

**Comment by fichtner** [comment]
Impressive list! I can grab haproxy-devel and push it to our packages for 17.7.9 so this can be tried / master branch switched over.

**Comment by fraenki** [comment]
@fichtner :+1:

**Comment by fraenki** [comment]
@fichtner Can you confirm that the SSL issues are resolved in the recent version of net/haproxy-devel? I want to ship HAProxy 1.8 ASAP.

**Comment by fichtner** [comment]
Ok, I will check.

**Comment by fichtner** [comment]
1.8.3 does not work with LibreSSL. It's going to be very hard to do split releases here and keep supporting both 1.7 and 1.8... :(

**Comment by fichtner** [comment]
Maybe @Sp1l could help with haproxy-devel on LibreSSL? Pretty please? :)

**Comment by fraenki** [comment]
@fichtner How about this? :)
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=223196
https://www.mail-archive.com/haproxy@formilux.org/msg27570.html

**Comment by fichtner** [comment]
Let's have some fun, shall we....

**Comment by fichtner** [comment]
https://github.com/opnsense/ports/commit/dd764f462

LibreSSL is ok now, now let's see if i386 agrees....

**Comment by fichtner** [comment]
Ok, another tweak https://github.com/opnsense/ports/commit/b5e63c79 :D

**Comment by fichtner** [comment]
Okay, so fixing i386 was the weirdest issue, I had to go to the haproxy 1.9 development branch and pull in some arcane stuff that doesn't work on FreeBSD 11.1's clang because it's too old...

https://github.com/opnsense/ports/commit/5fd9ecfcf

I want you to try haproxy-devel manually when 18.1.2 is out, we could switch for 18.1.3 if all is ok...

In parallel I try to get that into FreeBSD and make haproxy-devel the real "haproxy" package since 1.8 is officially out... I am guessing the issue here is the reason why FreeBSD didn't do this....

**Comment by fraenki** [comment]
> I want you to try haproxy-devel manually when 18.1.2 is out, we could switch for 18.1.3 if all is ok...

Will do! Thanks again.

**Comment by fichtner** [comment]
1.8.4 hit the tree and it has the patch that I pulled from upstream applied so I simply added the fix for i386 and LibreSSL again. Looks good. If you want to make the switch, I'd say go for it.

**Comment by fraenki** [comment]
> I want you to try haproxy-devel manually when 18.1.2 is out

The amd64 version works as expected with my existing config, starting/stopping, etc.

**Comment by fraenki** [comment]
Seamless reloads are not yet implemented :)

**Comment by fraenki** [comment]
HAProxy 1.8.13 will contain [a fix for seamless reloads](https://www.mail-archive.com/haproxy@formilux.org/msg30744.html) on FreeBSD.

**Comment by fraenki** [comment]
Seamless reloads will finally be available in version 2.8 of our HAProxy plugin.
