### ISSUE TITLE
UI: Add config parameters for Zabbix Proxy service

### ISSUE THREAD

**Issue by sch-lu** [opnsense/plugins#2246]
Hi all,

We are using Zabbix Proxy to monitor systems at our branch offices.
Two more parameters in the config of zabbix proxy service could be helpfull.

- ConfigFrequency (Default value according to ZABBIX: 3600s)
- DataSenderFrequency (Default value according to ZABBIX: 1s)

With these parameters a more flexible data sending and acquisition would be possible.
Until now we added them into the configuration template of Zabbix Proxy Service, but once the package is updated changes are lost.

Thanks

Luc

**Comment by Starkstromkonsument** [comment]
Is this closed by #2275?

**Comment by fichtner** [comment]
Yes, typo in PR. Thanks!
