### ISSUE TITLE
LE certificates sync to HA backup fails after upgrade to v21

### ISSUE THREAD

**Issue by heindries** [opnsense/plugins#2248]
Opnsense instances in HA used to sync LE certificates in v20. After the upgrade to v21 all cetificates are misssing from the backup node. Firewall rules and other settings are syncing properly. 

OPNsense Version: 21.1.2
ACME plugin 2.4

**Comment by fraenki** [comment]
I think there is a misunderstanding here. The Let's Encrypt _plugin_ never had a HA sync feature (for good reasons) for LE settings (everything in `Services: Let's Encrypt:*`).

However, the actual certificates (in `System: Trust: Certificates`) are covered by HA sync, provided that this is enabled in `System: High Availability: Settings`.

**Comment by heindries** [comment]
Sorry.. No misunderstanding. Since the upgrade the certs dir on the backup is empty. All the rest syncs? It was flawless before? 

________________________________

**Comment by fraenki** [comment]
Please provide more information. What is the "certs dir" you're referring to?

**Comment by heindries** [comment]
> Please provide more information. What is the "certs dir" you're referring to?

Thank you for asking. I was not fully aware of the System/Trust/Certificates setting. Had a good look at what I can see is happening. The certs dir is /var/etc/acme-client/home on the secondary HA machine. 

The issue I see is like this: The primary node opnsense1  shows all certificates in System/Trust/Certificates page and physically certs on the filesystem in /var/etc/home/acme-client/ On the second node, opnsense2, the backup machine in the HA setup, the certificates appear in System/Trust/Certficates but no synchronisation of cert files on the filesystem is taking place. For the moment I copied the certs over by scp. To test I deleted a cert from opnsense2 both from the Settings page and the filesystem on opnsense2, leaving opnsesne1 untouched. After syncing again, the cert re-appears on the settings page but not on the filesystem in /var/etc/acme-client/home/ on opnsense 2.

**Comment by fraenki** [comment]
> The certs dir is /var/etc/acme-client/home on the secondary HA machine.
> On the second node, opnsense2, the backup machine in the HA setup, the certificates appear in System/Trust/Certficates but no synchronisation of cert files on the filesystem is taking place.

That's expected. There is no sync feature for the folder `/var/etc/acme-client/home`. This feature is just not implemented (and it is very unlikely that it will ever be implemented).

**Comment by heindries** [comment]
Ok perhaps it was Haproxy plugin that was syncing them before? But I never had to copy them over. Thanks - so far. I will have a look at this again in a few days.

**Comment by fraenki** [comment]
> Ok perhaps it was Haproxy plugin that was syncing them before?

No, I'm the author of both plugins, they never had this specific sync feature. :)

That being said, it is strongly advised to not rely on the contents of `/var/etc/acme-client/home`, but instead only use certificates from `System: Trust: Certificates`.

The Let's Encrypt plugin also has a SFTP feature, which allows you to transfer certificates to other (non-opnsense) hosts (check `Services: Let's Encrypt: Automations`).

**Comment by heindries** [comment]
> No, I'm the author of both plugins, they never had this specific sync feature. :)

Alright - a double thanks then! 

> That being said, it is strongly advised to not rely on the contents of `/var/etc/acme-client/home`, but instead only use certificates from `System: Trust: Certificates`.

Not sure why my opnsense1 has certs there then - I never touched this - never had to!  I had a look at where the hapoxy config gets its certs. It is fetching them from  /tmp/haproxy/ssl. This is syncing fine again after a restart of both nodes.  

> The Let's Encrypt plugin also has a SFTP feature, which allows you to transfer certificates to other (non-opnsense) hosts (check `Services: Let's Encrypt: Automations`).

I know the sftp feature - it's great - but never used it between my opnsenses before. In any event, may have been a temporary glitch in sync connectivity or so. Thank you for your time. By the looks all is well now.
