### ISSUE TITLE
[os-telegraf] Add GUI option for Datadog Output

### ISSUE THREAD

**Issue by LucasBillbee** [opnsense/plugins#2260]
**Is your feature request related to a problem? Please describe.**
I can install the os-telegraf plugin fine, but one of the outputs that can be configured (Datadog) cannot be set from the GUI. I read that I could install telegraf manually instead of as a plugin, but that is not what I was originally after

**Describe the solution you'd like**
The os-telegraf plugin should have an additional configuration section where I could enable Datadog output and enter the API key 

**Describe alternatives you've considered**
Not installing os-telegraf as a plugin, but from the shell - but then I would not see it in the GUI.

**Comment by mimugmail** [comment]
How would the syntax look like in conf?

**Comment by LucasBillbee** [comment]
Like this, see the telegraf output definition at https://github.com/influxdata/telegraf/blob/master/plugins/outputs/datadog/datadog.go

`var sampleConfig =`
  ## Datadog API key
  apikey = "my-secret-key"`

  ## Connection timeout.
  # timeout = "5s"

  ## Write URL override; useful for debugging.
  # url = "https://app.datadoghq.com/api/v1/series"
`

**Comment by LucasBillbee** [comment]
I just saw a better link: https://github.com/influxdata/telegraf/tree/master/plugins/outputs/datadog
