### ISSUE TITLE
RFC2136 plugin reports key name has invalid characters when key name has trailing dot

### ISSUE THREAD

**Issue by TangoAlpha** [opnsense/plugins#2264]
The RFC2136 plugin incorrectly reports that a key name has invalid characters when the key name has a trailing dot.

To reproduce
1. install RFC2136 plug-in
2. go to Services, RFC 2136
3. enter a valid dns key name, one that has a trailing dot
4. click save
5. see error: "The following input errors were detected: The DNS update key name contains invalid characters."

Expected:
A dns key name with a trailing dot is valid and should be accepted.

OPNsense 21.1.2-amd64
FreeBSD 12.1-RELEASE-p13-HBSD
OpenSSL 1.1.1j 16 Feb 2021
os-rfc2136 version 1.6_1

**Comment by fichtner** [comment]
According to the code the trailing dot is added always:

https://github.com/opnsense/plugins/blob/f0ec64d1304558295f1bfbea2cf97d619684a228/dns/rfc2136/src/etc/inc/plugins.inc.d/rfc2136.inc#L120-L122

I don't see a good reason to change the validation as it will complicate the input more than necessary.


Cheers,
Franco

**Comment by TangoAlpha** [comment]
So if I don't have a trailing dot the code adds one for me, that would work :-)

However, the help underneath the key name box reads "This must match the setting on the DNS server." The setting on the DNS server has a trailing dot.

Not using the trailing dot on the key name entered in the box would mean that it doesn't actually match the setting on the DNS server (although the key name sent to the would be correct). Maybe the help line should tell the user to use the DNS server key name without the trailing dot.

**Comment by fichtner** [comment]
Sure, good idea, happy to update the help text. 😊
