### ISSUE TITLE
Unable to delete backend pool from haproxy

### ISSUE THREAD

**Issue by drinn** [opnsense/plugins#2266]
When trying to delete some of my backend pools from haproxy -> settings -> virtual services -> backend pools, some of them give me an error saying the item "is in use by" a few items in the "Rules" section.

The backend pools that I'm trying to delete, however, does not currently have any of those rules in its configuration.

If I clone a rule that I'm unable to delete, I can freely delete that clone with the same settings but not the original.

Please let me know if you would like me to gather any other information and I'll be happy to provide it to you.

EDIT: I'm currently running the latest release version of opnsense - OPNsense 21.1.3-amd64

**Comment by fraenki** [comment]
> some of them give me an error saying the item "is in use by" a few items in the "Rules" section

Please provide the exact error message, ideally a screenshot.

> Please let me know if you would like me to gather any other information and I'll be happy to provide it to you.

The config export of your haproxy.conf would be of interest to me. And the name of the rule that cannot be deleted would help me to identify the root cause of this issue.

**Comment by drinn** [comment]
![haproxy1](https://user-images.githubusercontent.com/12588455/110718106-f8f5be00-81cf-11eb-9bef-c0bee54472d0.png)

Is the screenshot of the error. That is what I get when trying to delete that "airsonic_backend" pool which is not enabled in my current configuration. Along those lines, in my haproxy.conf the only reference to airsonic_backend is:

`# Backend (DISABLED): airsonic_backend ()

# Backend: navidrome_backend ()
backend navidrome_backend
    # health checking is DISABLED
    mode http
    balance source
    # stickiness
    stick-table type ip size 50k expire 30m
    stick on src
.
.
.
`

And since it's disabled, there is nothing underneath it to define.

Hope that helps? Let me know what else I can provide for you.

**Comment by fraenki** [comment]
> And there are no references to x-forwarded-host, x-forwarded-proto, http_to_https, or scheme_https in that airsonic_backend pool.

It's probably the other way around: the backend does not contain references **to** these rules, but instead is referenced **by** these rules. For example, if I create a rule with the content "Use specified Backend Pool test_backend", then I cannot delete "test_backend" unless I change or remove this rule.

**Comment by drinn** [comment]
I understand what you're saying, but with all due respect, I think I had it right the first time. :) A screenshot of one of the rules that was referenced above when trying to remove the backend pool:

![xforwardedhost](https://user-images.githubusercontent.com/12588455/110787112-9550ac80-8232-11eb-8e3a-721f1bfa912e.png)

I don't see anything specific to the backend pool in there that would be preventing me from deleting the pool?

I am also able to clone that backend pool which should create a copy of that rule (with all the same dependencies in it) and I'm able to delete that newly cloned backend pool, but unable to delete the original still?

Any other ideas or things that I can provide to help in troubleshooting?

**Comment by fraenki** [comment]
> I don't see anything specific to the backend pool in there that would be preventing me from deleting the pool?

I cannot reproduce it, so a wild guess: could it be that this rule was cloned at some point in the past? It could be that the backend reference is still there. Please switch the rule to "Use specified Backend Pool". Now check if a Backend Pool is selected, if that is the case, remove the selected backend pool and save.

**Comment by drinn** [comment]
> It could be that the backend reference is still there, but hidden from you. Please switch the rule to "Use specified Backend Pool". Now check if a Backend Pool is selected in this rule, if that is the case, remove the selected backend pool and save.

That is progress. Switching the rule to "Use specified Backend Pool", I am presented with a dropdown of the two backend pools available. If I select the enabled pool and go back and try and delete the unenabled one, that rule drops off the list of reasons why I can't delete the pool.

I also just tried to create a brand new rule from scratch and the default action is to "Execute function" and "Use specified Backend Pool". The "Use backend pool" in that case is already populated by the first of my two backend pools (I'm guessing in alphabetical order), but I'm not able to delete that item or select none? Perhaps that is the issue? In any case, when I change the Execute function to something else, Save, and then go and try and delete that backend pool, that rule is now added to the list of reasons why I cannot delete the pool.

So I think you're onto something with that backend reference being there but hidden from me. Maybe being able to delete fields from the "Use backend pool" on the rules page or having a blank entry as an option there would work? Or defaulting to something other than "Use specified Backend Pool" when you create a new rule so it doesn't get referenced upon creation?

**Comment by fraenki** [comment]
OK, I was finally able to reproduce this issue. Currently the fields "Use backend pool" and "Use server" are always pre-filled for every rule. This is the case even if these fields are not used.

The following patch changes this behaviour for new rules and also allows to set both fields to "none" for existing rules:
`opnsense-patch -c plugins 8756e7c807bf3abb600de41269c58a875adc5bab`

I'll also prepare another patch which will automatically fix this issue for all existing rules in os-haproxy 3.1.

**Comment by drinn** [comment]
Awesome. Thanks for your work with this plugin! I can verify that I am now able to set "Use specified backend pool" (necessary to delete entry in "backend pools") and "Override server in backend pool" (necessary to delete entry in "real servers") to "none" in all my rules and that has fixed my initial issue. Thanks again!

**Comment by fraenki** [comment]
As promised, a data migration will fix all existing rules when upgrading to the upcoming os-haproxy 3.1.
