### ISSUE TITLE
[os-telegraf] Support Unbound input plugin

### ISSUE THREAD

**Issue by Sebclem** [opnsense/plugins#2271]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I'm convinced that mine is new.
- [x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
It will be interesting to add option for the `inputs.unbound` plugin.
I don't think this one need any additional field.
I think we just need to specify the config file location in the config.
More info here : https://github.com/influxdata/telegraf/blob/release-1.17/plugins/inputs/unbound/README.md

**Describe the solution you'd like**
Add this plugin in the telegraf config GUI

**Describe alternatives you've considered**

**Additional context**

**Comment by mimugmail** [comment]
Did you test it if it works when adding manually? Mostly there are missing permissions like with pf input

**Comment by Sebclem** [comment]
I have tested with this config:
```tolm
[[inputs.unbound]]                                                                 
                                    
  ## The default location of the unbound-control binary can be overridden with: 
  binary = "/usr/local/sbin/unbound-control"                                       
  ## The default location of the unbound config file can be overridden with:       
  config_file = "/var/unbound/unbound.conf"                                        
                                                                     
  ## When set to true, thread metrics are tagged with the thread id.               
  ##                                                                               
  ## The default is false for backwards compatibility, and will be changed to   
  ## true in a future version.  It is recommended to set to true on new            
  ## deployments.                                                                  
  thread_as_tag = true
```

I have just added the `unbound` group to the `telegraf` user: `/usr/sbin/pw groupmod unbound -m telegraf`, and everything work great.

**Comment by psychogun** [comment]
* OPNsense 21.7.1-amd64
* os-telegraf 1.12.0


I do not know if _this_ particular code made it to the 21.7.1 release, as stated here in the release notes; https://forum.opnsense.org/index.php?topic=24233.0
> o plugins: os-telegraf 1.12.0[4]

https://github.com/opnsense/plugins/blob/stable/21.7/net-mgmt/telegraf/pkg-descr
> Plugin Changelog
================

> 1.12.0

> * Allow to start telegraf with wheel group permissions
> * Add Unbound input

But enabling this feature, which adds this config in `telegraf.conf`; 
```
[[inputs.unbound]]
   binary = "/usr/local/sbin/unbound-control"
   config_file = "/var/unbound/unbound.conf"
   thread_as_tag = true
```

gives me no metrics in InfluxDBv2. 


Checking the log files for Telegraf, I have every 10s this error:
```
2021-08-04T21:20:50 |   | E! [inputs.unbound] Error in plugin: error gathering metrics: error running unbound-control: exit status 1 (/usr/local/sbin/unbound-control [-c /var/unbound/unbound.conf stats_noreset]) |  
2021-08-04T21:20:40 |   | E! [inputs.unbound] Error in plugin: error gathering metrics: error running unbound-control: exit status 1 (/usr/local/sbin/unbound-control [-c /var/unbound/unbound.conf stats_noreset]) |  
2021-08-04T21:20:30 |   | E! [inputs.unbound] Error in plugin: error gathering metrics: error running unbound-control: exit status 1 (/usr/local/sbin/unbound-control [-c /var/unbound/unbound.conf stats_noreset]) |
```

`telegraf` is a part of the `unbound` group:
```
id telegraf
uid=884(telegraf) gid=884(telegraf) groups=884(telegraf),59(unbound),62(proxy)
```

**Comment by mimugmail** [comment]
You also need to enable wheel group

**Comment by fichtner** [comment]
We could add a constraint for this where strictly required?

**Comment by psychogun** [comment]
Ah, I looked for it - did not find it / understood what it meant in the release notes - but now I saw it on the very top under "Input". 

@mimugmail ; check the permissions for directory and file `/var/log/suricata/eve.json` - it is rwx------; so adding `telegraf` to `wheel` group does not enable Suricata / "Intrusion Detection Alerts" (if this checkbox doesn't do more behind the scenes??).

**Comment by psychogun** [comment]
I have two firewalls. Same hardware and same software as mentioned above. 

One where I have added `telegraf` manually to the group `wheel`:
```
id telegraf
uid=884(telegraf) gid=884(telegraf) groups=884(telegraf),0(wheel),59(unbound),62(proxy)
```

 I still get the same error; 
```
2021-08-05T19:57:50 |   | E! [inputs.unbound] Error in plugin: error gathering metrics: error running unbound-control: exit status 1 (/usr/local/sbin/unbound-control [-c /var/unbound/unbound.conf stats_noreset])
```


On the other firewall, checking "Wheel Group" does not seem to do anything:
```
id telegraf
uid=884(telegraf) gid=884(telegraf) groups=884(telegraf),59(unbound),62(proxy)
```

I have disabled and enabled the service with "Wheel Group" checked. 
```
2021-08-05T19:59:40 |   | E! [inputs.unbound] Error in plugin: error gathering metrics: error running unbound-control: exit status 1 (/usr/local/sbin/unbound-control [-c /var/unbound/unbound.conf stats_noreset])
```

**Comment by mimugmail** [comment]
Checking it only tells the process to start with wheel group permissions
and with it I hot metrics in my influx

Mr. Johnson ***@***.***> schrieb am Do., 5. Aug. 2021, 22:01:

**Comment by psychogun** [comment]
Can you please show me
```
ps aux | grep telegr
telegraf 21482   4.1  0.7  5039828   53396  -  S    00:42      0:00.26 /usr/local/bin/telegraf --quiet --config=/usr/local/etc/telegraf.conf --config-directory=/usr/local/etc/telegraf.d
```
(I have not checked "Quiet Log" under General, however it is started with parameter `--quiet`?)

This firewall might need a reboot, or something.

**Comment by mimugmail** [comment]
Strange, it worked for period of time and now also not for me. 
Need to have a look after vacation time

![image](https://user-images.githubusercontent.com/20438689/128460707-067361d5-22f2-48d5-8708-b91651f7ce3b.png)

**Comment by andrema2** [comment]
Hi, 

I think I was able to create a workaround. Not the safest one...

in the  /usr/local/etc/rc.d/telegraf instead of running the daemon as telegraf user I changed to run with the root user.

I don't have any errors now and the data is being saved on Influx as I wanted.

Still not clear why the telegraf user can't run telegraf on daemon mode, but it's certainly related to it.
