### ISSUE TITLE
Wireguard User Mgmt based on LDAP group membership

### ISSUE THREAD

**Issue by DerDanilo** [opnsense/plugins#2280]
[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
[x] I have searched the existing issues and I'm convinced that mine is new.
[x] When the request is meant for an existing plugin, I've added its name to the title.

## Is your feature request related to a problem? Please describe.

Kind of. Configuration overhead in a sense and human error.

## Describe the solution you'd like
Wireguard does not support login based on LDAP credentials which is totally fine and in a sense adds even 2-factor auth to access a network and it's services.

But what would be really nice to add to the OS Wirguard plugin would be a way to enable or disable users based on an LDAP group membership. This is something I haven't seen with any of the many existing Wireguard "mgmt solutions" so far.

Since OS has aleady configuration for access server/ldap and supports sync to local groups the "only thing" that needs to be added is a way to use this information by the wireguard plugin and check for changes every 5 minutes (should be configurable).

### Checking for group membership

Since WG config works different we need a way to regularly check for the ldap group membership of a user. Hence sync the ldap group from time to time. There could be a cron job checking every 5,15,60 Minutes for changes and then do something with user peer configuration.

### Adding users

OPNsense does not yet support proper WG peer mgmt with QR code support or even a way to export/download the user configuration. It could also be a solution to automatically download the configuration files to a webdav server that admins can then grep the config and provide it to the user. 

So what does this have to do with the LDAP groups?  
Well, when a user is present in the LDAP vpn group, the OS WG plugin should create a new peer and "download/export" the configuration to the external storage.
I have seen solution that litteraly will send you the WG config via E-Mail. But since the configuration contains all information on how to connect this is a really (really) bad idea since most e-mails servers still send unencrypted traffic and this behaviour is not gonna change over night.

### Removing users

Based on that it then could remove(if ldap user is deleted)/disable(if ldap user is only disabled) a peer from the WG server.

## Also support HA-config-sync

We need to keep in mind that we need a way that config changes do not get messed up between OS nodes when HA-config-sync is enabled. Hence only the currently active (master) node should be able to make WG config changes while the other one only receives changes. But since the HA-config sync does not behave like this I have no idea how to solve this part currently. Maybe a OS dev has an idea.

## Describe alternatives you've considered
Not using OS for WG and either waiting for a project to implement the above idea or start to implement my own (not having time and enough development experience is actually the problem to get this going in a sensable timeframe).

**Comment by sorano** [comment]
Am I misunderstanding something or how would this even be considered 2-factor **auth**?

If the user is present in the LDAP VPN group, and someone gets hold of that users keys. Would they still not be able to authenticate as long as that user is still in that group?

**Comment by mimugmail** [comment]
In WireGuard all is about Public and private Keys, nothing more. No 2FA, no LDAP, nothing. You are free to use the API for adding and removing users, disable them or group them. But inside the plugin it doesnt really makes sense

**Comment by DerDanilo** [comment]
> Am I misunderstanding something or how would this even be considered 2-factor **auth**?
I mean "in a sense". Of course this is not 2-factor auth. But a working wireguard config/peer would require ldap group membership. If the user is disabled or not a member of the vpn group anymore the connection simply won't work (once the peer was removed from WG of course). 

> You are free to use the API for adding and removing users, disable them or group them.
This is just about that. It's harder for admins to integrate this into existing infrastructures since ldap login and group membership is used to manage access. Now with WG it's more complicated to do that since there is another access part admins need to think of.

If OS would support a simple feature that would generate user config and disable/remove users based on ldap group membership many more users would actually use it. Most admins I talk to don't want to use it or fail to get it approved simply for the fact regarding ldap i mentioned above. This is an idea to get it going somewhere.

If people have to write their own toolset to manage WG peers they mostly will skip using it at all.

So is this something that the OS team would be willing to integrate at a point or not?

Thanks!

**Comment by fichtner** [comment]
I think you are barking up the wrong tree. WireGuard maintainers do not have much intent to make WireGuard enterprise ready. That leaves downstream to either fork or work around things. Both situations are not great and require lots of work that could break at any moment.

In the end enterprise will stick to what is already there (a.k.a anything but WireGuard) to avoid reinventing the wheel.

I'm kind of wondering if a captive portal or proxy on top could be used for user authentication after tunnel establishment. But I really don't know if it would be possible or that it finds its way into OPNsense quickly if possible.


Cheers,
Franco

**Comment by DerDanilo** [comment]
Thanks for your feedback. Then we'll see how WG management will improve in OS. Currently it's working but takes many manual configuration steps.

**Comment by KwadwoObeng** [comment]
@fichtner  You are right. You can use captive portal on top for authentication.This option opens up posibilities of using LDAP and even 2FA on top of WireGuard. I have been using this extensively for months and it works perfectly.No issues so far. @DerDanilo  If you are interested in exploring this. Check out this article on medium.   https://obengafrane-oa.medium.com/wireguard-peer-authentication-a-captive-portal-approach-c464e4be8675

**Comment by fichtner** [comment]
@KwadwoObeng very nice, thanks for sharing!
