### ISSUE TITLE
FRR zebra installed routes

### ISSUE THREAD

**Issue by smalchow** [opnsense/plugins#2284]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

**Is your feature request related to a problem? Please describe.**

There is no way to configure zebra installed routes in the FRR plugin. We are in the situation the we need to install zebra routes in some boxes to not have to redistribute kernel routes or connected networks due to the network layout.

**Describe the solution you like**

I would like to be able to configure zebra routes in the frontend.

**Describe alternatives you considered**

I do not really have an alternative, in those situations we are still using pfsense

**Additional context**

Add any other context or screenshots about the feature request here or links to relevant forum thread or similar

![image](https://user-images.githubusercontent.com/8308427/111621303-1f2ae780-87e8-11eb-8f7d-1bc31df6fef5.png)

a section underneath the "General" configuration could do the trick.

As an example here a screenshot form pfsense

![pfsense_routing](https://user-images.githubusercontent.com/8308427/111624827-7763e880-87ec-11eb-9313-5432bae33571.png)

**Comment by mimugmail** [comment]
I can add a grid for this ... BUT ... I have no idea how FRR handles interface resets and how it interferes with opnsense scripts.
For me it would be ok to add it plus a banner warning about experimental state for this (like in bind).

@AdSchellevis @fichtner opinions?

**Comment by AdSchellevis** [comment]
@mimugmail if it will need additional triggers likely depends on how FRR handles this, if you add the feature and setup a test environment, I don't mind taking a look at your end if it needs anything specific.

**Comment by smalchow** [comment]
If i can help in any way, let me know, we can test patches for example, no problem

**Comment by smalchow** [comment]
Hi,

i checked the configuration and what would need to be done, 

- we would need to be able to put routes into the configuration like this
`ip route xxx.xx.xxx.0/24 vmx0`

according to the frr documentation the needs to go into staticd.conf, but it will also look in frr.conf as fallback as it looks
And then the staticd must also be started, otherwise it does not work.

The start/Stop script in /usr/local/etc/rc.d checks for "frr_daemons" to be started, i could not really find where this is configured, but when that vrariable contains "staticd" it should start it.

**Comment by ampfinger** [comment]
Hello,

is this bus already fixed somehow?
We are currently in the same position and wanted to ask if it would be fixed by now.

Thanks!

**Comment by fmeppo** [comment]
I just added PR #3880 which might help with this.  Happy to take over this issue as well, and clean up that PR to resolve more completely.
