### ISSUE TITLE
net-mgmt/zabbix5-proxy: Proxy Mode UI is ambiguous.

### ISSUE THREAD

**Issue by SamForma** [opnsense/plugins#2297]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[-] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
yup

[-] I have searched the existing issues and I'm convinced that mine is new.
yup

[-] When the request is meant for an existing plugin, I've added its name to the title.
yup

**Is your feature request related to a problem? Please describe.**
in the configuration form for the Zabbix Proxy (/ui/zabbixproxy/general/index) there is a checkbox for "Proxy Mode". As this isn't really a bool option, what this check box does could be made clearer to the admin.

**Describe the solution you'd like**
Instead of a checkbox, make it a pull down, or radial button. Or change field description to something like "Disable Active Mode".

**Describe alternatives you've considered**
manually checking Zabbix Proxy config via SSH to determine what's actually happening.

**Additional context**
opnsense: 21.1.3_3
os-zabbix5-proxy: 1.3_1

**Comment by mimugmail** [comment]
Maybe adjusting the help text would also be fine?

**Comment by Starkstromkonsument** [comment]
This is a screenshot of the Proxy Config page from the Zabbix Server WebUI:

![image](https://user-images.githubusercontent.com/53019449/115777356-7444b500-a3b5-11eb-950c-071522247bfe.png)

I would adopt this to make it more intuitive.
