### ISSUE TITLE
net/haproxy: Configuration check is valid even if a frontend listens on non-existent IPs

### ISSUE THREAD

**Issue by fpoussin** [opnsense/plugins#2307]
**Describe the bug**
Adding a frontend with a non-existent ip is validated via the syntax-test feature, but HaProxy will fail to (re)start as it can't bind.

**To Reproduce**
1. Go to Haproxy -> settings
2. Add a frontend with a non-existent IP
3. Test the configuration, which should pass
4. Apply the configuration

**Expected behavior**
Test should fail.

**Relevant log files**
```
root@OPNsense:~ # haproxy -f /usr/local/etc/haproxy.conf -c
Configuration file is valid

root@OPNsense:~ # haproxy -f /usr/local/etc/haproxy.conf
[NOTICE] 088/164342 (50674) : haproxy version is 2.2.11-c58c4e4
[ALERT] 088/164342 (50674) : Starting frontend test: cannot bind socket [192.168.88.50:8080]
```

**Context**
Haproxy's syntax check can only do so much, but there could be some more tests to prevent this from happening.

**Environment**
OPNsense 21.1.4-amd64
FreeBSD 12.1-RELEASE-p15-HBSD
OpenSSL 1.1.1k 25 Mar 2021

**Comment by fraenki** [comment]
>  Haproxy's syntax check can only do so much, but there could be some more tests to prevent this from happening.

That's an upstream (=HAProxy developer) decision to not test this during syntax check. I'm not sure what additional checks you're expecting from the OPNsense plugin. Can you please elaborate further on this and provide the additional commands you'd want to be evaluated?

**Comment by fpoussin** [comment]
It would be nice if the plugin could check if frontend IPs are bound to any interface,
something as simple as `ifconfig | grep "inet <FRONTEND_IP>"` for each frontend would work.

**Comment by fraenki** [comment]
@fpoussin First let me assure you that I understand why you are asking for this extra check. But there is a reason why I've never seen this check in any other service: it's not as easy as it sounds. Parsing "ifconfig" output is not the only task, one would also have to check all listening sockets ("sockstat") to find possible conflicts (and exclude the ones from the running HAProxy service). This is cumbersome and error-prone.

For this reason basically every application relies on the underlying operating system to reply to "bind" attempts, without first checking if a "bind" is possible. And I hate to say it, but it's our – the sysadmin's – responsibility to ensure that the HAProxy service is properly configured. No offense, it's just the reality I've been facing over the course of the past 20 years. :) The existing syntax check already helps us to find most errors, the remaining (limited) number of errors is ours to avoid.

> That's an upstream (=HAProxy developer) decision to not test this during syntax check.

I'd like to rectify my previous statement. It was not meant to blame anyone (especially not the developers!). I just wanted to state that upstream decided not to implement it (for good reasons), which is a good indication not to try and implement it in our plugin.
