### ISSUE TITLE
net/wireguard: The api 'server/addServer' does not return the created UUID

### ISSUE THREAD

**Issue by Sebclem** [opnsense/plugins#2315]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

[x] The title contains the plugin to which this issue belongs

**Describe the bug**

When using the API to create a new server (`wireguard/server/addServer`), the response only contain : 
```json
{"result":"saved"}
```
This endpoint must (I think) respond the same way as the `wireguard/client/addClient` endpoint do:
```json
{"result":"saved","uuid":"28d016f2-xxxx-xxxx-xxxxxx-xxxxxxx"}
```

Note: I will try to take a look, if it's not too complicated, I will try to open a PR.

**To Reproduce**
1. Create a new WG server with the API (`wireguard/server/addServe)

**Expected behavior**
The api should return something like the `wireguard/client/addClient` endpoint :
```json
{"result":"saved","uuid":"28d016f2-xxxx-xxxx-xxxxxx-xxxxxxx"}
```

**Environment**
OPNsense 21.1.4-amd64

**Comment by Sebclem** [comment]
After a fast check, it caused by the [Save method of ApiMutableModelControllerBase](https://github.com/opnsense/core/blob/0b9a77806902ca28f4c4080fb62d4e7f2c5643b2/src/opnsense/mvc/app/controllers/OPNsense/Base/ApiMutableModelControllerBase.php#L247) that not return the UUID but only `{"result":"saved"}`
So, i don't know if this can be fixed or if change this in Core will break something.
Did i need to open an issue in Core for this ?

**Comment by AdSchellevis** [comment]
@Sebclem best open an issue in core for this indeed, I don't expect it would be problematic to include the uuid in the response by default.

**Comment by Sebclem** [comment]
Issue moved to https://github.com/opnsense/core/issues/4904
