### ISSUE TITLE
security/acme-client: nsupdate not found after update to 17.7

### ISSUE THREAD

**Issue by QuentinC** [opnsense/plugins#232]
Hello,

My Let's encrypt certificates are not renewing since the upgrade of the router to 17.7.

I'm using DNS-01 as validation method (talking to the DNS server, allowed to update with some key).
It seems that the commands tries to run nsupdate, and this command is not available anymore on my system...

How can I fix that ?

Thanks !

Quentin Canel

**Comment by fichtner** [comment]
Not really a bug. Fixed in 17.7.1. 

For a workaround:

    # pkg install bind911
