### ISSUE TITLE
net/haproxy: Update OCSP data fails (WARNING: no nonce in response)

### ISSUE THREAD

**Issue by browne-net** [opnsense/plugins#2323]
[+] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
[+] I have searched the existing issues and I'm convinced that mine is new.
[+] The title contains the plugin to which this issue belongs

**Describe the bug**
Since the latest version of [HAProxy now supports OCSP stapling](https://github.com/opnsense/plugins/issues/1430#issuecomment-779482060) I thought it would be a good idea to switch from the [workaround-script](https://gist.github.com/Da-Juan/0f765160e69a99882c5188b6ab4e13e1) to the official option.
But it turned out that at least for me it is not working quite right.

**To Reproduce**
1. Enable "Store OCSP responses" in HAProxy. (HAProxy --> Settings --> Service)
2. Configure the cron job to run every day.
3. Cron Job fails, see log below.

**Expected behavior**
Automatic update of the OCSP data in HAProxy.

**Workaround**
I created another cron job that runs 10 minutes later and simply restarts the haproxy service, which works just fine.

**Screenshots**
https://imgur.com/a/XM9tpZt

**Relevant log files**
````
2021-04-06T03:42:01	configd.py[18127]	[b2eb554c-4009-4e75-9e58-3f8a1a64e656] Script action stderr returned "b'WARNING: no nonce in response\nResponse verify OK\nWARNING: no nonce in response\nResponse verify OK'"
2021-04-06T03:42:00	configd.py[18127]	[b2eb554c-4009-4e75-9e58-3f8a1a64e656] update haproxy ocsp data
````

**Environment**
OPNsense 21.1.3_3-amd64 --- FreeBSD 12.1-RELEASE-p14-HBSD --- OpenSSL 1.1.1j 16 Feb 2021
os-haproxy 3.0 --- haproxy 2.2.10

**Comment by fraenki** [comment]
@browne-net So, you're maintaining a workaround for the OCSP update... so I was wondering: do you have any idea why this occurs or what this error refers to? What kind of certificate are you using, which CA is being used?

**Comment by browne-net** [comment]
I have no idea why this occurs (occured).

The certificate doesn't have anything special.
- automatically aquired using the ACME plugin
- Common Name: subdomain.domain.com
- Alt Names: service1.domain.com service2.domain.com .... (total of 6)
- Challenge Type: HTTP-01
- Auto Renewal: yes
- Renewal Interval: 60
- Key Length: ec-384
- OCSP Must Staple: yes
- Automation: Restart HAProxy
- DNS Alias Mode: no

Special things in my config:
- 2x WAN IPs
- 2x HTTP-01 validation methods, one for each IP
- 2x ec-384 certificates, one of them with some alt names
- 2x frontends in HAProxy, one for each IP with the corresponding certificate

That's about it.
A pretty normal setup I think.


Also I just checked the logs!
I had the default "Update OCSP Data" cron job (added by HAPRoxy) still activated all the time in combination with my workaround.
The default job is running 15 min ahead of my workaround.
--> It seems the error is no longer present.
--> There are no errors anymore at the time these cron jobs are running.

I now disabled my workaround and will leave it like this to check the logs in a bit.
How long does it take until the OCSP data is marked / recognized as outdated?

**Comment by fraenki** [comment]
>  How long does it take until the OCSP data is marked / recognized as outdated?

AFAIK it depends on the implementation, but 1-2 weeks seems to be common.

However, the OCSP update script in the HAProxy plugin does not check the validity. To keep things simple it just updates everything on every run.

**Comment by fraenki** [comment]
> It seems the error is no longer present.
> There are no errors anymore at the time these cron jobs are running.

Since the error is gone, I'll close this issue for now. Please report back if it occurs again and provide as much (debug) log data as possible. (I have no idea where to look at, so everything is useful, I guess.)
