### ISSUE TITLE
Add a plugin to support Nebula VPN

### ISSUE THREAD

**Issue by pagong** [opnsense/plugins#2324]
Nebula VPN has been developed at Slack and is freely available since 2019.

**Describe the solution you'd like**
Nebula should be available as an optional plugin in the list of supported VPNs.

**Additional context**
https://github.com/slackhq/nebula
https://www.defined.net/

**Comment by CGenie** [comment]
Still, would be nice to have this plugin. Nebula is working quite well for me for some time now. There is a FreeBSD package as well which works.
