### ISSUE TITLE
IDS/IPS - Allow combination of ET telemetry and ET open rulesets to be selected

### ISSUE THREAD

**Issue by TurtleRecall** [opnsense/plugins#2329]
**Issue**

Currently, OPNsense's Suricata IDS/IPS allows use of either ET Open rulesets or ET Telemetry rulesets, but not both together/a combination of the two.

As per this thread (https://forum.opnsense.org/index.php?topic=15693.0) a number of quite useful emerging threat rulesets are populated (and regularly updated) in ET open but empty in ET telemetry, examples of empty rulesets from this thread (https://forum.opnsense.org/index.php?topic=14921.0) are:

dshield.rules
drop.rules
compromised.rules
botcc.rules
botcc.portgrouped.rules
ciarmy.rules

Prior to moving to telemetry I was seeing the ET open rules dropping quite a lot of incoming traffic from known compromised IPs etc, so this feels like useful functionality/protection that is being lost by using telemetry rulesets.

**Feature Request**

There was a suggestion from AdSchellevis in the above thread that a core issue could/should be raised to investigate the possibility of running ET telemetry and ET open side by side (or perhaps only allow use/selection of the relevant open ruleset where the telemetry ruleset is empty?).   

I've searched for closed issues but can't see any related to this, apologies if this has already been discussed.*

##EDIT##

Found a previous issue logged and closed as a support issue: https://github.com/opnsense/core/issues/4479.  I feel the above is still a valid feature request, maybe for those specific 'empty' telemetry rules mentioned above, to ensure defence in depth by allowing wholesale blocking of known compromised IPs, tor exit points, botnets etc, as well as the advantage of the more up-to-date specific rules present in the telemetry rulesets.

**Comment by TurtleRecall** [comment]
Thank you, Ad - the xml works perfectly, looking forward to seeing it in the release too!

**Comment by AdSchellevis** [comment]
@TurtleRecall thanks for letting us know!
