### ISSUE TITLE
net/haproxy: Add support for "hold valid" and other timeouts for dns resolvers

### ISSUE THREAD

**Issue by taxilian** [opnsense/plugins#2330]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

[X] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**

I am using haproxy as a front-end for kubernetes services and using dns service discovery; thus I'm using a custom resolver pointed at the kubernetes DNS server but when a deployment is restarted the ip address of all pods will be different and the default "hold valid" for haproxy is, according to docs, 10 seconds which may be too long in some cases.

**Describe the solution you'd like**

2 possibilities:

1. I would like to see fields for the "hold" values (see http://cbonte.github.io/haproxy-dconv/2.2/configuration.html#5.3.2-hold)
2. I think it would make sense to add an "additional configuration" section for resolvers just in case additional / less common options are needed. It would be "at your own risk" like other such sections, of course.

**Describe alternatives you've considered**

I don't really see any other options on the haproxy side; these can't be configured, so they can't be configured. I can try to slow down the update process to ensure that the 10s timeout catches at least some of the new pods before the last of the old go away.

**Additional context**

N/A

-- 

I would like to say thank you for all the hard work and improvements on this lately! Not long ago resolvers weren't available at all and the server templates are *exactly* what I need.

**Comment by taxilian** [comment]
I'd be willing to help work on this, but I know nothing about opnsense plugins; please let me know if there is any way I can help. (I do have a strong web dev background)

**Comment by fraenki** [comment]
@taxilian Thanks for offering help, greatly appreciated! If you like to dive deep into it, take a look at the plugin framework documentation:
https://docs.opnsense.org/development/examples/helloworld.html

Otherwise I'd suggest to browse through the HAProxy plugin commits and look for a smallish, self-contained commit that addresses a similar feature and may help you to figure this out:
https://github.com/opnsense/plugins/commits/master/net/haproxy

Please let me know if you have any questions. I'm also on freenode IRC in #opnsense.

**Comment by taxilian** [comment]
I'll try to drop in on IRC when I have a bit of time =] This is becoming more important to me.

I just hit another related issue -- without the ability to set the ["accepted payload size"](https://cbonte.github.io/haproxy-dconv/2.2/configuration.html#5.3.2-accepted_payload_size) the default for dns lookups in haproxy is 512, which only fits (in my instance) 27 servers, so if I have more than that the entire lookup fails.... =] Definitely need an override. I'm sure this isn't hard, just need to find time to learn the basics.

**Comment by fichtner** [comment]
libera #opnsense
