### ISSUE TITLE
net-mgmt/zabbix-agent: allow logging to syslog

### ISSUE THREAD

**Issue by bradleeedmondson** [opnsense/plugins#2332]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

[x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
I'm able to get a lot of the logging info from my OpnSense box into a syslog collector (running elasticsearch-oss and kibana-oss, at least until AWS OpenSearch takes off). But it doesn't include zabbix-agent logs, even though that's a built-in feature of the zabbix agent and can be enabled in the conf file. This makes finding issues with the zabbix agent much more difficult, since (1) they aren't in the syslog server with everything else, and (2) the zabbix agent log rotates every so often, erasing old entries.

**Describe the solution you'd like**
In the zabbix-agent configuration page, I would like to be able to select whether to send its logging to syslog or to local log file. For example, a checkbox or drop-down on the /ui/zabbixagent page, which could toggle LogType=file / LogType=system in [zabbix_agentd.conf](https://github.com/opnsense/plugins/blob/master/net-mgmt/zabbix-agent/src/opnsense/service/templates/OPNsense/ZabbixAgent/zabbix_agentd.conf#L10)

**Describe alternatives you've considered**
Alternatives include:
* manually logging in to the OpnSense UI to check the zabbix agent logfile exposed at ui/diagnostics/log/zabbix/zabbix_agentd
  * This is an extra, unnecessary step
  * This prevents the log messages from being correlated with events that do make it to the central syslog server (e.g. restarting the zabbix-agent)
  * This file rotates at a fixed size, unrelated to syslog data retention schedules
* SSHing into OpnSense and manually editing zabbix_agentd.conf to change to LogType=system
  * Presumably this would disappear upon every update to the package, and in the worst case could break the zabbix-agent package

**Comment by bradleeedmondson** [comment]
I started pull request in #2348 , but I do not have the resources to do my own builds to test. My commits are all "blind" writes assuming that build testing and syntax verification are all taking place project-side.

**Comment by fraenki** [comment]
This will be available in the upcoming release 1.9 of os-zabbix-agent.
