### ISSUE TITLE
net-mgmt/zabbix-agent: key net.tcp.listen[port] always returns 0 (not listening), even if service is running on that port

### ISSUE THREAD

**Issue by bradleeedmondson** [opnsense/plugins#2333]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

[x] The title contains the plugin to which this issue belongs

**Describe the bug**
Zabbix agent includes the `net.tcp.listen[port]` [key](https://www.zabbix.com/documentation/current/manual/config/items/itemtypes/zabbix_agent), to see if the OS is listening on a particular TCP port. I use this to check that SSH is running, without generating lots of login-aborted type log messages, which is what sshd does if you do a full TCP connect to that port without authenticating. This zabbix agent key works on Linux (ubuntu server 20.04.2 LTS) and reports the state of the SSH socket on TCP port 22. Per the [Zabbix agent feature-by-platform documentation](https://www.zabbix.com/documentation/current/manual/appendix/items/supported_by_platform), it is supported on FreeBSD, so I would think it should work on OpnSense (via HardenedBSD). But the key always returns 0 (i.e. "not running"), whether I query for port 22 (while SSH is running), 443, 80, or any other valid port number. 

If I pass a parameter that is not a valid port number, such as a string, or a negative number, I properly get `ZBX_NOTSUPPORTED: Invalid first parameter.` Likewise, if I garble the key name itself instead of changing the port number, I properly get the `ZBX_NOTSUPPORTED: Unsupported item key.` error. This indicates that the OpnSense zabbix agent believes the requested key, net.tcp.listen[port], is in fact supported.

I don't know if this key was ever working in past versions of OpnSense -- though it does work as expected on my Linux hosts.

**To Reproduce bug**
1. Install zabbix-agent package
1. Configure zabbix-agent listen IP to either 0.0.0.0 or 127.0.0.1, and add server IP 127.0.0.1
1. SSH to OpnSense, option (8) for shell
1. Run `zabbix_get -s 127.0.0.1 -k "net.tcp.listen[22]"` --> `0` for "not running", even though you have just logged in and in fact have an active session over port 22

**To show zabbix is partially processing the key**
1. ...
1. Run `zabbix_get -s 127.0.0.1 -k "net.tcp.listen[-1]"` --> `ZBX_NOTSUPPORTED: Invalid first parameter.` Zabbix agent properly evaluating parameter `-1` and concluding it is not a valid port number.
1. Run `zabbix_get -s 127.0.0.1 -k "net.tcp.listeeeeeeen[22]"` --> `ZBX_NOTSUPPORTED: Unsupported item key.` Zabbix agent properly concluding that this misspelled key is not a valid zabbix-agent key.

**Expected behavior**
1. Run `zabbix_get -s 127.0.0.1 -k "net.tcp.listen[22]"` --> `1` for "running", if the SSH daemon is listening on port 22
    * Query what the behavior should be if SSH is bound to certain local IPs but not 0.0.0.0. Probably should be `1` running if bound to any local IPs on that port.

**Screenshots**
![image](https://user-images.githubusercontent.com/7350638/114967184-f8d98580-9e41-11eb-9ba8-689cb29cd84c.png)

**Relevant log files**
n/a

**Additional context**
n/a

**Environment**
environment | value
-- | --
Version | 21.1.4 |  
Architecture | amd64 |  
Flavour | OpenSSL |  
Commit | 0a42a1966 |  
Mirror | http://mirror.wdc1.us.leaseweb.net/opnsense/FreeBSD:12:amd64/21.1 |  
Repositories | OPNsense |  
Updated on | Tue Apr 6 19:06:33 EDT 2021

**Comment by fraenki** [comment]
I think this is not working as expected due to a FreeBSD security feature, which is enabled by default on OPNsense. It hides processes (and related data) from other users, i.e. the user "zabbix" cannot get information for processes from user "root".

You may disable this feature in `System -> Settings -> Tunables` by setting the following values:

```
security.bsd.see_other_uids 	1
security.bsd.see_other_gids 	1 
```

**Comment by bradleeedmondson** [comment]
Thanks @fraenki  --  you are correct. Setting these tunables (both of them) to 1 allows Zabbix agent to report the socket state appropriately. Much appreciated!
