### ISSUE TITLE
chrony does not sync huge time differences fast

### ISSUE THREAD

**Issue by hboetes** [opnsense/plugins#2338]
`*** cougarfw.example.com: OPNsense 21.1.4 (amd64/OpenSSL) ***`

I just ran into an issue where the VPN wasn't connecting, after logging in I noticed the time was off by 4 years. chrony was running but didn't set the time properly.

After manually setting the time the VPN started and I fixed the last 22 second with `chronyc -a makestep`

According to the official documentation adding a line with `makestep` with allow chrony to immediately set the correct time.

https://chrony.tuxfamily.org/faq.html#_what_is_the_minimum_recommended_configuration_for_an_ntp_client

Could you guys add something sensible to the default configuration, so that chrony will immediately fix the time on boot/restart?

Thanks!

**Comment by kosli** [comment]
@hboetes  I assume you could either adapt the chrony.conf template, add the option, test it and submit a patch.
 (https://github.com/opnsense/plugins/blob/16f3522d08d30919b17e66bdec38352ef4c75208/net/chrony/src/opnsense/service/templates/OPNsense/Chrony/chrony.conf).
Or if it neesd to be more sophisticated and the option should not be enabled for everybody, you would need to add an option to activate it in the UI. 
You may ask the package maintainer about his preference. (https://github.com/opnsense/plugins/blob/16f3522d08d30919b17e66bdec38352ef4c75208/net/chrony/Makefile)

**Comment by hboetes** [comment]
I strongly suspect this is an option which everyone would like to have enabled, maybe under some circumstances it's not a good idea to set the proper time at the start of chrony. But then again, who am I?

**Comment by mimugmail** [comment]
I will add it, thx
