### ISSUE TITLE
Let's Encrypt: Log file view broken

### ISSUE THREAD

**Issue by StrikerTwo** [opnsense/plugins#234]
Something is not right here :)

![image](https://user-images.githubusercontent.com/6770084/29744798-8e941912-8aac-11e7-99ae-77dbf96586ca.png)

**Comment by fraenki** [comment]
@StrikerTwo Thanks for reporting this issue! We're already aware of it and tracking it in https://github.com/opnsense/plugins/issues/69.

**Comment by fichtner** [comment]
There may be two things here, it logs a full header which looks off...

**Comment by fraenki** [comment]
> There may be two things here, it logs a full header which looks off...

Not exactly. It's part of the acme log (level 2). Though, we may change the log level once we support other log formats.

**Comment by StrikerTwo** [comment]
Thanks, didn't see the other issue.
If you ask me, you could just drop the date column and display everything in a single line as it is in the original log file.

**Comment by fichtner** [comment]
I promise to fix that this week. We just need to pass a word count for the split...
