### ISSUE TITLE
security/acme-client: IONOS DNS-01 challenge support

### ISSUE THREAD

**Issue by browne-net** [opnsense/plugins#2345]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:
[+] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
[+] I have searched the existing issues and I'm convinced that mine is new.
[+] When the request is meant for an existing plugin, I've added its name to the title.

**Describe the solution you'd like**
Would it be possible to add ACME DNS-01 support for IONOS in order to get wildcard certificates?
https://www.ionos.de/hilfe/server-cloud-infrastructure/cloud-panel-verwaltung/api/

https://developer.hosting.ionos.com/docs/getstarted

**Comment by browne-net** [comment]
Is there any ETA yet for this feature?

**Comment by HeinzKrischeu** [comment]
Hi,
When do I find the entry for IONOS in the default program of opnsense?
Best Regards,
Heinz

**Comment by fraenki** [comment]
As always, no ETA, it's not a priority for me (I'm just volunteering here). However, adding new DNS APIs is [not too difficult](https://github.com/opnsense/plugins/commit/13f55969431c1e2020bde4f9f709609d9c805bd7), so PRs are always welcome.

**Comment by fraenki** [comment]
This will be available in the upcoming release 2.6 of os-acme-client.
