### ISSUE TITLE
[security/acme-client]: challenge type DNS01 fails on cloudflare.com api because dns txt entry created doesn't match txt entry verification looks for

### ISSUE THREAD

**Issue by zombiehoffa** [opnsense/plugins#2359]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[-] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[-] I have searched the existing issues and I'm convinced that mine is new.

[-] The title contains the plugin to which this issue belongs

**Describe the bug**
using DNS-01 challenge type with cloudflare.com api (for router.mydomain.com). I see the renewal script creating a txt entry named router with a bunch of characters as the content. It then waits 120 seconds and the verification script errors out on code 200 incorrect TXT record and the TXT record is deleted.

if I login to cloudflare interface manually and copy the contents from the router entry created by the verification script to a new txt entry named _acme-challenge.router the certificate verification succeeds and the cert renews. that script also deletes the router txt entry but does not delete the manually create _acme-challenge.router txt entry.
 

I am using dns because the ip address this dns entry points at is internal (although that shouldn't really affect any of the above in theory, I am reporting it in case I am wrong and the internal ip is somehow messing up the script).

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Relevant log files**
If applicable, information from log files supporting your claim.

**Additional context**

**Environment**
Software version used and hardware type if relevant.
e.g.:

OPNsense 19.1.1 (amd64, OpenSSL).
Intel® Xeon™ E3-1225V5 3.3Ghz Quad Core
Network Intel® I210-AT

**Comment by fraenki** [comment]
> OPNsense 19.1.1 (amd64, OpenSSL).

Please upgrade to the latest OPNsense version. Afterwards provide logs.

**Comment by zombiehoffa** [comment]
I am actually on the latest, sorry I didn't realize I should delete the rest of the template. I will resubmit again or comment on this when the cert gets closer to expiry because, after using the above procedure to force it to work it is giving acme status ok now (probably because it's not trying to renew)

some example errors on checking the older logs (above this there is a bit that says TXT record was added ok and to wait):
[Sat Apr 17 00:08:31 MDT 2021] _post_url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/somenumberIamnotsureifIneedtohideornot/HQvLEw'
[Sat Apr 17 00:08:31 MDT 2021] _CURL='curl --silent --dump-header /var/etc/acme-client/home/http.header  -L '
[Sat Apr 17 00:08:31 MDT 2021] _ret='0'
[Sat Apr 17 00:08:31 MDT 2021] code='200'
[Sat Apr 17 00:08:31 MDT 2021] router.mydomain.com:Verify error:Incorrect TXT record

**Comment by fraenki** [comment]
Unfortunately, the required log information is missing.
Please go to `Services: Let's Encrypt: Settings` and set `Log Level` to `debug`, then click the `Apply` button.

Afterwards, please wait for the next (auto) renewal. If it fails, go to `Services: Let's Encrypt: Log Files` and provide the _full_ logs for both `System log` and `Acme log` (feel free to cloak sensitive information).

**Comment by zombiehoffa** [comment]
I will have to try it again whenever it needs to be renewed again as I noticed your request for logs after I renewed it manually. I can explain exactly what is happening though.  in cloudflare dns the router domain I am trying to get letsencrypt to work for is router.mydomain.com. When I go look at cloudflare dns I  see the renewal process creates a text entry for router with a key and an expiry time of two minutes. If I do nothing it fails. If I copy the key to an entry I created _acme-challenge.router it succeeds. So there is either a bug in the creation script (probably for sub domains) that is creating the txt entry for the subdomain itself without adding _acme-challenge. in front of the subdomain (making a sub  sub domain???) Or there is a bug in the script checking the text entry and it isn't supposed to look for _acme-challenge, it's supposed to look for just the subdomain. Given how this should be setup I would guess it is the first one and this works fine when it's on a primary domain and fails like this when it is a  subdomain on cloudflare dns (or maybe it's something as stupid like router being the subdomain breaks something).

**Comment by fraenki** [comment]
> So there is either a bug in the creation script (probably for sub domains) that is creating the txt entry

If that's the case then this bug must be reported for acme.sh, the ACME client that is used by OPNsense:
https://github.com/acmesh-official/acme.sh

**Comment by fraenki** [comment]
I'll close this issue now, because I think there is nothing that we can do to fix this, if it's an upstream bug in acme.sh.
However, I'd recommend to try again with the upcoming release 3.0 of os-acme-client, because it also includes a new release of acme.sh.
