### ISSUE TITLE
[Plugin - haproxy] stick table counter regression

### ISSUE THREAD

**Issue by bluesource** [opnsense/plugins#2363]
**Describe the bug**
stick table counter regression does not work as described in https://github.com/haproxy/haproxy/issues/1196

**Expected behavior**
Counters decrement over time as per configuration.

**Additional context**
this is a haproxy issue solved with 2.2.12 as described in https://github.com/haproxy/haproxy/issues/1224

**Environment**

OPNsense 21.1.4-amd64FreeBSD 12.1-RELEASE-p15-HBSDOpenSSL 1.1.1k 25 Mar 2021
--

**Comment by fraenki** [comment]
An update to HAProxy 2.2.13 is already scheduled for the next release of OPNsense:
https://github.com/opnsense/ports/blob/master/net/haproxy/distinfo
