### ISSUE TITLE
HAProxy Listener mixed mode

### ISSUE THREAD

**Issue by Zewwy** [opnsense/plugins#2365]
I was attempting to pull of this feat:

https://discourse.haproxy.org/t/mixing-mode-tcp-and-http-ssl-termination-and-passthrough/2698

or this:

https://discourse.haproxy.org/t/ssl-offloading-ssl-passthrough-on-same-port-with-sni/4619

With backend config examples as these:

https://discourse.haproxy.org/t/how-to-set-ssl-verify-client-for-specific-domain-name/1489/11
https://pastebin.com/bZb155DU

I would prefer a way to do this via the HAProxy plugin UI on OPNsense, as I'd be worried editing the haproxy config files would be overwritten if I did it via the backend itself. If this is possible some user guidance documentation would be greatly appreciated. As I was unable to located any documentation on how to accomplish this more complex design implementation.

If it's not, can I request a feature request to make such a configuration possible using the front end UI?

**Comment by fraenki** [comment]
Please use the issue templates and provide the desired config inline. Thanks.

**Comment by Zewwy** [comment]
Sorry I do not follow?

If there's existing Documentation on how to achieve this configuration, please direct me to the appropriate places.

I do not know what the "desired config inline" is as I don't fully understand what's required to make it work, I have only the example config as already linked in the initial request. If there is more information required from me, I'm more than willing to provide.

**Comment by sorano** [comment]
@Zewwy Mixing passthrough and termination on the same port is already possible to do purely in the webui. I use it for terminating some sites in HAProxy, passthrough to some other sites and OpenVPN.
You can close this issue.

**Comment by Zewwy** [comment]
@sorano I'm super excited to know it is possible. However, could you by chance provide me some guidance on how you achieved it? I can't seem to find any blog or Hot to's on how to achieve it.

I haven't had enough time lately to reverse engineer what each part of the UI is doing in the haproxy.conf file to figure it all out yet.

Any help on that is greatly apricated. I would gladly take this information and write a How to Guide on my log that can be used to extend OPNses's HAProxy How to guides.,

**Comment by sorano** [comment]
@Zewwy
Take a look at this and please close this issue:
https://forum.opnsense.org/index.php?topic=23339.0
