### ISSUE TITLE
security/acme-client: Acme Log in WUI is empty

### ISSUE THREAD

**Issue by Starkstromkonsument** [opnsense/plugins#2366]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

[x] The title contains the plugin to which this issue belongs

**Describe the bug**
The WUI offers to log files for the plugin:
- System Log
- Acme Log

The Acme Log is empty in the WUI although `/var/log/acme.sh.log` has content. 

**To Reproduce**
1. Go to 'Services --> Let's Encrypt --> Settings'
2. Set Log Level to 'debug 3'
3. Click on 'Apply'
4. Go to 'Services --> Let's Encrypt --> Certificates'
5. Click on 'Issue/Renew Certificates Now'
6. Go to 'Services --> Let's Encrypt --> Log Files'
7. Click on 'Acme Log'
8. See empty Log File (error)

**Expected behavior**
View the content of `/var/log/acme.sh.log`.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/53019449/116463221-bc0e8500-a86a-11eb-961d-8d2e7cff62a3.png)

**Relevant log files**
`/var/log/acme.sh.log`

**Additional context**
Log file path:
https://github.com/opnsense/plugins/blob/16f3522d08d30919b17e66bdec38352ef4c75208/security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeCommon.php#L45

WUI-View path of the logfile:
https://github.com/opnsense/plugins/blob/9a132c18050da5dc54f7c84a451ca2937ab46254/security/acme-client/src/opnsense/mvc/app/views/OPNsense/AcmeClient/logs.volt#L55

Search path of the logformat:
https://github.com/opnsense/plugins/blob/16f3522d08d30919b17e66bdec38352ef4c75208/security/acme-client/src/opnsense/scripts/systemhealth/logformats/acmeclient.py#L39

**Environment**
OPNsense 21.1.5-amd64
FreeBSD 12.1-RELEASE-p16-HBSD
OpenSSL 1.1.1k 25 Mar 2021

**Comment by Starkstromkonsument** [comment]
Running 

`root@opnsensehost:/var/log # mv acme.sh.log acmeclient.log`

via ssh for testing purposes fixes the issue (for the existing log content), but the logformat seems to be broken too:

![grafik](https://user-images.githubusercontent.com/53019449/116467233-bff0d600-a86f-11eb-8570-a2ce84ee058b.png)

**Comment by fraenki** [comment]
> The Acme Log is empty in the WUI although /var/log/acme.sh.log has content.

The acme.sh log was recently switched to using syslog, so the GUI now uses /var/log/acmeclient.log.

> root@opnsensehost:/var/log # mv acme.sh.log acmeclient.log
> via ssh for testing purposes fixes the issue (for the existing log content), but the logformat seems to be broken too:

That's the expected results, the format is incompatible.

**Comment by fraenki** [comment]
I cannot reproduce it on 20.7. However, I will change the acme.sh configuration in the upcoming release to only log to syslog, the old logfile `/var/log/acme.sh.log` will then be obsolete and removed, which should avoid any further confusion.

Removing the duplicate log option _may_ fix this issue, but since I cannot reproduce it, I can't tell for sure.

**Comment by fraenki** [comment]
I'll close this issue for now, please re-test with the upcoming release 3.0 of os-acme-client.
