### ISSUE TITLE
security/acme-client: OCSP Must Staple is broken on Firefox (all Gecko powered platforms)

### ISSUE THREAD

**Issue by wget** [opnsense/plugins#2367]
**Describe the bug**

May be related to #1430, but I'm **NOT** using HA-Proxy.

On Firefox, enabling `OCSP Must Staple` is returning a `MOZILLA_PKIX_ERROR_REQUIRED_TLS_FEATURE_MISSING` on Firefox.

I even tried on a fresh profile and with another internet connection (in the unlikely event the ISP was dropping OCSP verification) without success.

The web ui is listening on port 44378.

In `System` > `Settings` > `Administration` > `HTTP Redirect` , `Disable web GUI redirect rule` is **checked**.

Tested browsers:
* Firefox on GNU/Linux: NOK
* Firefox on Windows 10: NOK
* Firefox on Android: NOK
* Firefox on iOS: OK (logical as it is using WebKit)
* AOSP (LineageOS) browser on Android: OK
* Safari on iOS: OK
* Chromium based on all platforms: OK

**To Reproduce**
* Reissue a production LetsEncrypt certificate checking the `OCSP Must Staple`.

  
  ![Screenshot_20210429_163822](https://user-images.githubusercontent.com/2997662/116569166-6937da80-a909-11eb-9e7c-e0cd8ddb1d11.png)

* Refresh the page on Firefox and get this beautiful error message:
  
  ![Screenshot_20210429_161917](https://user-images.githubusercontent.com/2997662/116567563-07c33c00-a908-11eb-841a-176585328f68.png)

**Mitigation**

Disable the OCSP Must Staple feature from Firefox:
* Go to `about:config`
* Set `security.ssl.enable_ocsp_must_staple` to `false`

**Expected behavior**
A working connection.

**Screenshots**
cf. above

**Relevant log files**
N/A

**Additional context**
* I'm currently rate limited by the LetsEncrypt server and cannot generate the certificate until Tuesday evening.
* So if you need further tests, this will need to wait or need to switch to staging.

**Environment**
OPNsense 21.1.5-amd64
FreeBSD 12.1-RELEASE-p16-HBSD
OpenSSL 1.1.1k 25 Mar 2021

AMD GX-412TC SOC (4 cores)
PC Engines
apu2

Using the default lighttpd server, **not** using the os-nginx plugin.

**Comment by maurice-w** [comment]
This is not an acme-client issue. The OPNsense Web UI simply doesn't support OCSP stapling yet: opnsense/core#4205
Many browsers don't enforce OCSP Must Staple, that's why it works with Safari, Chrome etc.

**Comment by wget** [comment]
Closing and will follow up in 4205 if I succeed to provide a patch. :)

**Comment by willhoh** [comment]
Am I wrong or is this still not fixed? I just installed an OPNsense and still have this "error".

**Comment by wget** [comment]
@willhoh Still unfixed yes :disappointed:

**Comment by 3ighty2O** [comment]
Ran into the same issue today. Has to disable OCSP.
