### ISSUE TITLE
[nginx] opnsense-report-csp-violation refuse application/csp-report mime type.

### ISSUE THREAD

**Issue by Aarklendoia** [opnsense/plugins#2368]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

[x] The title contains the plugin to which this issue belongs

**Describe the bug**
When a CSP violation is triggered, csp_report.php returns a 400 error because it only accepts data in the application/json  mime type and not the one sent by browsers, application/csp-report.

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**
1. Configure a strict CSP.
2. Triggerd a violation.
3. Analyze the response in the debugger of the browser.
4. See error 400 for the report request.

**Expected behavior**
The report must accept the application/csp-report mime type.

**Patch**
Replace `{if (stristr($_SERVER['CONTENT_TYPE'], 'json') === false)` by `if (stristr($_SERVER['CONTENT_TYPE'], 'json') === false && stristr($_SERVER['CONTENT_TYPE'], 'csp-report') === false)` in the file csp_report.php.

**Environment**
OPNsense 21.1.5 (amd64, OpenSSL).
AMD GX-412TC SOC (4 cores)

**Comment by fabianfrz** [comment]
probably forgot to close that.
