### ISSUE TITLE
security/acme-client: add support for Njalla DNS API

### ISSUE THREAD

**Issue by rderensy** [opnsense/plugins#2376]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x]  I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x]  I have searched the existing issues and I'm convinced that mine is new.
- [x]  When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
It's annoying that you can't generate SSL certificate with DNS-01 challenge from the WebUI if your DNS provider doesn't appear in the list.

**Describe the solution you'd like**
It would be nice if there was a "manual" way to add a DNS-01 challenge, either by entering the TXT domain directly or by allowing custom API config as described [here](https://github.com/acmesh-official/acme.sh/wiki/dnsapi) (with an open field) so you can still generate certificates even with an unsupported DNS provider (I use Njalla which is supported by acme but it doesn't appear in OPNsense's WebUI) from the WebUI.

**Describe alternatives you've considered**
Doing it in CLI but it's annoying because it's not directly integrated. Also I haven't found a way to automatically add generated certificates as default in the UI.

**Additional context**
/

**Comment by fraenki** [comment]
> I use Njalla which is supported by acme but it doesn't appear in OPNsense's WebUI

So, adding support for Njalla to os-acme-client sounds like best solution to your problem, would you agree?

I'm somewhat opposed to the "manual" method. Sure, it's a last resort if the DNS provider is not (yet) supported, but it's definitely not how the plugin is supposed to work. And it makes it easy to just keep such an imperfect state instead of requesting a new feature (such as adding support for new DNS APIs).

Would you agree to convert this issue to a feature request for Njalla? Otherwise feel free to open a new issue instead.

**Comment by rderensy** [comment]
For my specific problem, adding Njalla is definitely the best solution.

However I was thinking more about a general solution for unsupported DNS providers, but if you're opposed to it then yes, let's go with Njalla only!

**Comment by pcmediapear** [comment]
hello, please add also Active24...

**Comment by fraenki** [comment]
@pcmediapear Please don't hijack issues. You should open a new feature request instead.

**Comment by theredspoon** [comment]
I've submitted PR #2446 to resolve this issue.

**Comment by fraenki** [comment]
PR was merged, this will be available in the upcoming release 2.6 of os-acme-client.
