### ISSUE TITLE
net-mgmt/zabbix-agent: upgrade to Zabbix Agent 3.4.1

### ISSUE THREAD

**Issue by fraenki** [opnsense/plugins#238]
New major release 3.4 available, needs testing.

**Comment by fichtner** [comment]
https://github.com/opnsense/tools/commit/a0042e34fb

We could switch os-zabbix-agent-devel to 3.4 ? the build is capable of this split scenario now :)

**Comment by obrienmd** [comment]
I'm a heavy Zabbix user, and that sounds great to me!

**Comment by fraenki** [comment]
> We could switch os-zabbix-agent-devel to 3.4 ? the build is capable of this split scenario now :)

Yes, please switch the -devel version when you have a minute to spare :)

**Comment by fichtner** [comment]
package is currently here btw... https://pkg.opnsense.org/FreeBSD:11:amd64/17.7/experimental/All/zabbix34-agent-3.4.1.txz

**Comment by fichtner** [comment]
and this.. https://github.com/opnsense/plugins/commit/a2f34139731a8223174c7efa4535b12ee4cd0e14

**Comment by fichtner** [comment]
did anybody try os-zabbix-agent-devel yet?

**Comment by fraenki** [comment]
I've tested os-zabbix-agent-devel (Zabbix Agent 3.4.1) and have not noticed any issue :)

**Comment by fichtner** [comment]
It's not too late. Happy to ditch zabbix32.

**Comment by fichtner** [comment]
https://github.com/opnsense/plugins/commit/daf80a98b7fc9b21012712bff67b1e2888745bc8

**Comment by fichtner** [comment]
thanks :)
