### ISSUE TITLE
net/haproxy: Header "interest-cohort" for blocking floc not correctly recognised

### ISSUE THREAD

**Issue by Taomyn** [opnsense/plugins#2380]
**Describe the bug**
The recommended header option to block floc "Permissions-Policy interest-cohort=()" does not get set correctly when sent to browsers

**To Reproduce**
1. On the public service add to "Option pass-through" add "http-response set-header Permissions-Policy interest-cohort=()"
2. Save and restart HAProxy
3. Visit a proxied site
4. See error in browser console - Error with Permissions-Policy header: Unrecognized feature: 'interest-cohort'.

**Expected behavior**
No error in browser console

**Screenshots**
![image](https://user-images.githubusercontent.com/4365929/117448641-475cda00-af3f-11eb-8d5d-13f459845f68.png)

**Additional context**
I'm using both Brave and Microsoft Edge for testing, both based on Chromium v90

My actual "Option pass-through" contains one other header that gets set and it doesn't cause any issues that I can see
```
http-response set-header X-SSL-Proxy haproxy
http-response set-header Permissions-Policy interest-cohort=()
```
I believe the issue could be caused by case-sensitivity, because when I use an online HTTP header viewer, my site shows:
```
(Status Line)	HTTP/1.1 200 OK		
strict-transport-security	max-age=31536000; includeSubDomains; preload
x-ssl-proxy	haproxy
permissions-policy	interest-cohort=()
Accept-Ranges	bytes
Content-Length	203
Content-Type	text/html; charset=UTF-8
Date	Fri, 07 May 2021 12:37:00 GMT
ETag	"cb-594dafa240800"
Last-Modified	Mon, 14 Oct 2019 08:51:44 GMT
Server	Apache/2.4.46 (Fedora) OpenSSL/1.1.1k
```

Whereas another site also sending the header shows:
```
(Status Line)	HTTP/1.1 200 OK		
Upgrade	h2,h2c
Connection	Upgrade, Keep-Alive
Vary	Accept-Encoding,User-Agent
Permissions-Policy	interest-cohort=()
Keep-Alive	timeout=5, max=100
Accept-Ranges	bytes
Content-Length	108862
Cache-Control	max-age=0, public
Content-Type	text/html; charset=UTF-8
Date	Fri, 07 May 2021 12:34:46 GMT
Expires	Fri, 07 May 2021 12:34:46 GMT
Server	Apache
X-Powered-By	WP Rocket/3.8.1
```

I can see that both my sets of options are forced to lower-case by the plug-in, so I request a fix is created to stop is changing the case of any options added to the "Option pass-through" entry

**Environment**
OPNsense 21.1.4-amd64
FreeBSD 12.1-RELEASE-p15-HBSD
OpenSSL 1.1.1k 25 Mar 2021
os-haproxy 3.1

**Comment by fraenki** [comment]
@Taomyn This doesn't sound like it's actually related to the plugin, but probably a HAProxy upstream issue. Have you already checked the HAProxy [bug tracker](https://github.com/haproxy/haproxy/issues) or [mailing list](https://www.mail-archive.com/haproxy@formilux.org/) for a similar report? You may also want to check the [list of known and solved bugs](http://www.haproxy.org/bugs/bugs-2.2.html).

**Comment by Taomyn** [comment]
> @Taomyn This doesn't sound like it's actually related to the plugin, but probably a HAProxy upstream issue. Have you already checked the HAProxy [bug tracker](https://github.com/haproxy/haproxy/issues) or [mailing list](https://www.mail-archive.com/haproxy@formilux.org/) for a similar report? You may also want to check the [list of known and solved bugs](http://www.haproxy.org/bugs/bugs-2.2.html).

I just spent about an hour scouring through all those and did not find anything remotely close, and doesn't help it's the kind of thing that is difficult to search for as some of the keywords appear almost everywhere. I did then do some more searches via Google and came across articles that state that all headers are sent in lower-case for HTTP/2 and that HAProxy sticks to that for HTTP/1 as well, so I am now thinking this is more likely a browser issue or something else. Either way you are probably correct and that there's nothing wrong from the perspective of this plug-in.

**Comment by fraenki** [comment]
If you open a bug in the HAProxy issue tracker or post on their mailing list, please add the link here. It might be of interest for others too.
