### ISSUE TITLE
net/haproxy: No logging beyond start/stop of services

### ISSUE THREAD

**Issue by BrianPuccio** [opnsense/plugins#2386]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**

HAproxy logs only contain start/stop information

**To reproduce**

1. Set logging to `debug`:  
<img width="878" alt="Screen Shot 2021-05-10 at 1 17 02 AM" src="https://user-images.githubusercontent.com/4541384/117609141-72a51c00-b12d-11eb-9007-bd8b32feba9c.png">
2. Set public service's advanced settings to allow the log level to be raised:  
<img width="683" alt="Screen Shot 2021-05-10 at 1 19 14 AM" src="https://user-images.githubusercontent.com/4541384/117609291-bf88f280-b12d-11eb-8cba-0d6051190e93.png">
3. Navigate to HAproxy logs:  
<img src="https://user-images.githubusercontent.com/4541384/117609737-84d38a00-b12e-11eb-8a1d-650b926a0369.png">

**Expected behavior**

Detailed log information

**Screenshots**

See above

**Relevant log files**

N/A

**Additional context**

I tried the things suggested in #280 and #34 with no luck.

There are forum users who seem to have similar issues as well:

- https://forum.opnsense.org/index.php?topic=21835.msg10305
- https://forum.opnsense.org/index.php?topic=18837.0
- https://forum.opnsense.org/index.php?topic=22373.0

**Environment**

OPNsense v21.1.5 on amd64 with os-haproxy v3.2

Thanks!

**Comment by fraenki** [comment]
> Detailed log information

What _exactly_ are you missing from the logs? As described in #280 HAProxy's logging is not exactly self-explanatory... however, in layer 7 mode you'll get some more details: `GET /path/to/foo.html HTTP/1.1`.

Is the backend using layer 4 oder layer 7 mode? Is SSL offloading enabled in the frontend?

**Comment by BrianPuccio** [comment]
Thanks for replying so quickly!

> > Detailed log information
> > 
> What exactly are you missing from the logs?

I'm trying to debug HAProxy with very limited success. I was hopeful that logging with the `debug` level would give me some insights as to why things aren't working.

> As described in #280 HAProxy's logging is not exactly self-explanatory... 

I'm OK with that. I was just looking for something beyond "x started", "y started", "z started". A few websites seemed to indicate that reviewing logs was a good starting point for figuring things out.

Should I be looking somewhere else for troubleshooting? Someplace that isn't a log?

The config file generated by the web interface includes for the frontends `option httplog` and `option tcplog` as appropriate.

> In layer 7 mode you should get some additional details: `GET /path/to/foo.html HTTP/1.1`.
> 
> Is the backend using layer 4 oder layer 7 mode? Is SSL offloading enabled in the frontend?

I have two set to `HTTP (Layer 7)` and one set to `TCP (Layer 4)`.

I don't have SSL offloading enabled. My goal, for the SSL'd connections, is to implement SSL passthrough.

**Comment by fraenki** [comment]
> I have two set to HTTP (Layer 7) and one set to TCP (Layer 4).

In Layer 7 mode you should get additional request logging. Note that HAProxy only logs connections, nothing else, so if your frontend does not receive connections, then nothing will be logged.

I'd suggest that you share your haproxy.conf (use `Services: HAProxy: Config Export`).

**Comment by BrianPuccio** [comment]
> In Layer 7 mode you should get additional request logging. Note that HAProxy only logs connections, nothing else, so if your frontend does not receive connections, then nothing will be logged.
> 
> I'd suggest that you share your haproxy.conf (use `Services`: `HAProxy`: `Config Export`).

I was still unable to get logging that I was looking for,  but I figured out the option that I needed to get things working which I added manually:

```
    # WARNING: pass through options below this line
    tcp-request inspect-delay 5s
    tcp-request content accept if { req_ssl_hello_type 1 }
```

Thank you for your help and suggestions. 🙌

**Comment by puzzle-it-nu** [comment]
I'm sorry to say but the problem of only start/stop entries of haproxy persists even after the help from #280 and I'm on :
OPNsense 21.7.1-amd64
FreeBSD 12.1-RELEASE-p19-HBSD
OpenSSL 1.1.1k 25 Mar 2021
os-haproxy (installed)	3.4

Joop

**Comment by fraenki** [comment]
@puzzle-it-nu This issue is closed. Please open a new issue and provide your full HAProxy configuration and the Log/Syslog settings of OPNsense.
