### ISSUE TITLE
net/haproxy: Support proxying backend servers which require SNI

### ISSUE THREAD

**Issue by johnlaur** [opnsense/plugins#2388]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

[X] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
Some servers require SNI and cannot be proxied or have health checks performed by HAProxy without particular configuration directives informing HAProxy to use SNI when connecting to them. Please consider supporting the `sni` directive on Real Server objects and the `check-sni` directive on Health Checks. Without the ability to force SNI, both health checks and proxied connections fail with L6RSP status.

**Describe the solution you'd like**
On both the Real Server and Health Check configuration screens, I would suggest changing the `SSL` checkbox to a dropdown offering the selection of None, SSL, and SSL with SNI. A string containing the hostname to send via SNI would also need to be added in both locations.

The 'Real Server' portion would add `sni str(host.example.com)` to the server directive.
The 'Health Check' portion would add `check-sni host.example.com` to the server directive.

An example output configuration for a SNI server which requires health checks is:
`server pickyhost 10.0.0.10:443 check inter 10s ssl verify none sni str(host.example.com) check-sni host.example.com`

**Describe alternatives you've considered**
Backend requests can be successfully proxied by setting the Option pass-through on a Real Server to `sni str(example.domain.com) check-sni example.domain.com` which will cause HAProxy to use SNI on the backend connection for both regular connections and health checks. A regular health check should also be configured and enabled with 'SSL' checkbox disabled on the health check to effect this workaround. Specifying configuration related only to the health check in the option pass-through of the Real Server is not an ideal solution, though.

**Additional context**
[Documentation for `check-sni`](https://cbonte.github.io/haproxy-dconv/1.8/configuration.html#5.2-check-sni)
[Documentation for `sni`](https://cbonte.github.io/haproxy-dconv/1.8/configuration.html#5.2-sni)

**Comment by fraenki** [comment]
I've added a new `SSL preferences` option to health checks and a new `SSL SNI` field to servers in https://github.com/opnsense/plugins/pull/2719/commits/8b856ddc1d126269a9e041ac5559fc0c4166fc6c. This should add all requested functionality, according to my (limited) testing. Please let me know if anything is missing or not working as expected.

This change requires a data model migration, so it cannot be tested using a patch. (It's still possible to test it by cloning my fork https://github.com/fraenki/plugins/tree/haproxy_390/net/haproxy and running the `make upgrade` command.)
