### ISSUE TITLE
security/acme-client: add support for Domeneshop DNS API

### ISSUE THREAD

**Issue by wazabees** [opnsense/plugins#2390]
Please add support for Domeneshop. Link below to acmesh-official.

https://github.com/acmesh-official/acme.sh/wiki/dnsapi#85-use-domeneshop-dns-api-to-automatically-issue-a-cert
https://github.com/acmesh-official/acme.sh/blob/master/dnsapi/dns_domeneshop.sh

Thank you!

**Comment by sttr-source** [comment]
Hi. Any progress on this?
I use domeneshop  as my registrar and I am using this on pfsense at the moment.
I cannot contribute codewise but I can test this implementation of needed as I am transitioning to opnsense.

**Comment by fraenki** [comment]
This will be available in the upcoming release 2.6 of os-acme-client.
