### ISSUE TITLE
dns/bind - adding slave zone needs master port defined for master ip

### ISSUE THREAD

**Issue by ziptx** [opnsense/plugins#2396]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:
[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
[x] I have searched the existing issues and I'm convinced that mine is new.
[x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
I need to subscribe a slave zone to a master zone that is operating on a non-standard port because unbound is occupying port 53.

**Describe the solution you'd like**
In the Zone creation, Type:Slave … "Slave Zone" section to be able to define in a new entry box the "Master Port" after the "Master IP" field.   This would define "port" in the zone part of the config [referenced below]

**Describe alternatives you've considered**
- Tried a VIP on the interface with BIND using that VIP, but unbound binds to all interface IPs [not viable]
- run separate OPNsense BIND server [metal requirement and extra hardware not available]
- create additional interface/networks to allow BIND to talk on different network [viable, but overly complicated] 

**Additional context**
/ui/bind/general/index  > Zones Tab > Add (+) Zone >  popup > Type: slave

Bind config needed [see **port** definition after IP address]:
zone "mycoolzone" {
        type slave;
        masters { 192.168.211.11 port 53530; };
        masterfile-format text;
        file "mycoolzone.db";
};

**Comment by mimugmail** [comment]
You could use a port forward to reroute port 53 to 5354

**Comment by ziptx** [comment]
Port is already actively occupied by Unbound, therefore making it unavailable for forwarding.  
OPNHost 1:   Port 53 - Unbound  [binds to all IPs on interface automatically]
OPNHost 1:   Port 53530 - Bind MASTER
OPNHost 2:   Port 53 - Unbound
OPNHost 2:   Port 53530 - Bind SLAVE [needs to subscribe to Host1 Port 53530 where Master is listening ... current slave behavior uses default of port 53 only which is occupied on Host 1]
