### ISSUE TITLE
net/nginx Execute a program from a php script

### ISSUE THREAD

**Issue by sbeu** [opnsense/plugins#2397]
Hello,
I am trying to execute a program with the shell php command, using the nginx plugin on OPNsense. The command is not launched and I can't see any error messages.
Here is the php line:
`
shell_exec("sudo timeout 120 /srv-n1/gorepeat.executable -w 10.199.9.104/32 -w 10.10.1.21/32 vtnet0_vlan1999 vtnet0_vlan1010 &");
`
When I execute this command in the shell as a root or as www, it works. When I execute this line from a php script executed with the nginx plugin, it does not work. 

Any idea on why this command is not executed?

**Comment by fichtner** [comment]
The output will probably tell you why. I'm guessing sudo is prohibited likely since nginx runs a different user (and dangerous to begin with).
