### ISSUE TITLE
hairpinning through vpns

### ISSUE THREAD

**Issue by boistordu** [opnsense/plugins#2403]
**Important notices**
Our forum is located at https://forum.opnsense.org , please consider joining discussions there in stead of using GitHub for these matters.

Before you ask a new question, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

Since nobody is responding on the forum about this.
Is NAT reflection or so called hairpinning feature, supposed to work through vpn gateways too or not? 
I have a bunch of vpn that gets me a publicly routable ips to expose services and apparently nat reflection is not working.

**Comment by mimugmail** [comment]
When the VPN interface is assigned it should work. It only works for directly connected networks. The rest needs to be added manually

**Comment by boistordu** [comment]
okey and do we agree that the only option needed is the 3 checked boxes in advanced settings in the interface? 
if yes then I don't think it is actually working. 
The system is clearly letting it go I don't think the correct source address is correctly transcribed by the system and so it is not being accepted by the client. 
What do you need for me to demonstrate that ?
