### ISSUE TITLE
os-telegraf allow configs from within /usr/local/etc/telegraf.d

### ISSUE THREAD

**Issue by mircsicz** [opnsense/plugins#2410]
[-] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[-] I have searched the existing issues and I'm convinced that mine is new.

[-] When the request is meant for an existing plugin, I've added its name to the title.

I'm adding telegraf and other pkg's to OPNsense using ansible, afterwards I'ld like to copy config snippet to the host. My Problem is that the process is started like this:
`
/usr/local/bin/telegraf --quiet --config=/usr/local/etc/telegraf.conf

`

What would solve my problem is if it would be startetd like that:
`
/usr/local/bin/telegraf --quiet --config=/usr/local/etc/telegraf.conf --config=/usr/local/etc/telegraf.d

`

This way I could use ansible's copy modul to transfer snippets and simple restart the service...

I've already tried to append to the file but I can't get a consistent result from my approach. I've so far tried the blockinfile and lineinfile module and on first run they both work but on the second run it's giving me double line's. I've already tried to cleanup the file before the append, but can't get it to work...

Using telegraf.d approach what make extending quite simple no matter what tool would be used, ansible, puppet, plain ssh/scp or vim they all would be possible. ;-)

**Comment by mimugmail** [comment]
Isn't there an option in telegraf.conf to add an optional include folder?

**Comment by mircsicz** [comment]
@mimugmail not as far as I know...

But I've solved it like this:
`
- name: Creates telegraf.d directory
    file:
      path: /usr/local/etc/telegraf.d
      state: directory

  - name: copy telegraf addon config
    copy:
      src: ~/ansible/telegraf-isp-monitor.conf
      dest: /usr/local/etc/telegraf.d/
      mode: '0644'
      backup: yes

  - name: check if vendor.conf file exists
    stat:
      path: /etc/defaults/vendor.conf
    register: stat_result

  - name: Create vendor.conf if it doesnt exist already
    file:
      path: /etc/defaults/vendor.conf
      state: touch
    when: not stat_result.stat.exists

  - name: Insert telegraf_configdir /etc/defaults/vendor.conf
    blockinfile:
      path: /etc/defaults/vendor.conf
      block: |
        telegraf_confdir=/usr/local/etc/telegraf.d

  - name: Restart service telegraf
    service:
      name: telegraf
      state: restarted
`

**Comment by mircsicz** [comment]
Reopened as suggest by @fichtner ;-)
