### ISSUE TITLE
security/acme-client: Change IP checking URL for Namecheap DNS API

### ISSUE THREAD

**Issue by ysguy** [opnsense/plugins#2419]
Problem
- During certificate renewal, for Namecheap domains, the default IP validation URL is https://ifconfig.co/ip 
The IP checking service is rate limited to 1 request per minute. The script runs faster than that and does multiple calls, causing the renewal to fail when it does not get returned an IP address.

Workaround
Changing the script to use: https://ipinfo.io/ip solves the issue

I edited the file: /usr/local/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsNamecheap.php to make the change to the following line

$this->acme_env['NAMECHEAP_SOURCEIP'] = 'https://ipinfo.io/ip';

I was able to renew my cert without any issues after making this change.

**Comment by fraenki** [comment]
The URL will be changed in the upcoming release 2.6 of os-acme-client.
