### ISSUE TITLE
[Freeradius] Support for EAP-TTLS-GTC is broken

### ISSUE THREAD

**Issue by fchavant** [opnsense/plugins#2421]
**Describe the bug**
Support for EAP-TTLS-GTC in FreeRADIUS does not work.

**To Reproduce**
1. Install the os-freeradius plugin
2. Navigate to Services > FreeRADIUS > EAP
3. Set "Default EAP Type" to "TTLS-GTC"
4. Enable the service and look at its log file

**Expected behavior**
EAP-TTLS with GTC is enabled and working.

**Relevant log files**
The following error being logged:
> Error: /usr/local/etc/raddb/mods-enabled/eap[15]: No dictionary definition for default EAP method 'ttls-gtc'

**Additional context**
I believe https://github.com/opnsense/plugins/issues/2085 which introduced the feature has a small issue:
 - `OPNsense.freeradius.eap.default_eap_type` is used on [line 631](https://github.com/opnsense/plugins/blob/21.1.6/net/freeradius/src/opnsense/service/templates/OPNsense/Freeradius/mods-enabled-eap#L631) to set `eap { ttls { default_eap_type = gtc } }` which is fine, however
- it is also used on [line 30](https://github.com/opnsense/plugins/blob/21.1.6/net/freeradius/src/opnsense/service/templates/OPNsense/Freeradius/mods-enabled-eap#L30) to set `eap { default_eap_type = ttls-gtc }` which, as far as I can tell, is invalid.

I think `default_eap_type` within the `eap` section should be set to `ttls`, not `ttls-gtc`.
After making this change manually radiusd starts without any error message and I can use it for WPA2-Enterprise.
 
**Environment**
OPNsense 21.1.6-amd64
FreeBSD 12.1-RELEASE-p16-HBSD
OpenSSL 1.1.1k 25 Mar 2021

**Comment by fchavant** [comment]
I believe I have provided all applicable pieces of information as per https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md. Should any more information be required I'll be happy to provide it.

**Comment by Citizen-Brainium** [comment]
This is still an issue, and I have also encountered this.  I own a DEC2680 that this is replicating on

**Comment by mimugmail** [comment]
Thx from bumping this up ... sorry @fchavant for my late respone, my fault :/
