### ISSUE TITLE
net/haproxy: Support OCSP stapling for multiple certs in a PEM blob

### ISSUE THREAD

**Issue by Arnavion** [opnsense/plugins#2429]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

- [x] I have searched the existing issues and I'm convinced that mine is new.

- [x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
https://github.com/opnsense/plugins/commit/d5b7a679b86f9af1e46bf6920c37a38aa15d0ec9 added support to the plugin for automatically fetching the OCSP responses for all certs used by haproxy public services, but it only did this for certs that were [created using the internal CA method,](https://github.com/opnsense/plugins/blame/76ec2c13ae93361b34416678fcdf8fde99e53205/net/haproxy/src/opnsense/scripts/OPNsense/HAProxy/exportCerts.php#L80-L90) since only those certs have `caref` set. For imported certs there is no `caref`, so that code does not generate a `.issuer` file, so `updateOcsp.sh` [ignores such certs.](https://github.com/opnsense/plugins/blame/76ec2c13ae93361b34416678fcdf8fde99e53205/net/haproxy/src/opnsense/scripts/OPNsense/HAProxy/updateOcsp.sh#L25-L30)

**Describe the solution you'd like**

`exportCerts.php` should support certs which don't have a `caref` but do have more than one `CERTIFICATE` in the PEM blob. All `CERTIFICATE`s except the first constitute the issuer chain and should be written to a `.issuer` file.

**Describe alternatives you've considered**
N/A

**Additional context**
Originally reported at https://github.com/opnsense/plugins/issues/1430#issuecomment-860172357

**Comment by fraenki** [comment]
> it only did this for certs that were created using the internal CA method, since only those certs have caref

That's not accurate. Certificates generated by the Let's Encrypt plugin also work as expected.

Wild guess: importing the CA/chain certificate for a certificate would probably add the required `caref` to the certificate.

**Comment by Arnavion** [comment]
Sure, I was only looking at the Cert Manager endpoint code in tthe core repo when I made that observation, not the plugins repo.

**Comment by fraenki** [comment]
> Wild guess: importing the CA/chain certificate for a certificate would probably add the required caref to the certificate.

@Arnavion Can you confirm that importing the CA/chain certificate fixes this issue?

**Comment by Arnavion** [comment]
If you mean I should use the "Import an existing certificate" option in the Certificates UI, that does not allow me to import a cert without its private key.

**Comment by fraenki** [comment]
No, you should import the CA/chain certificate under `System: Trust: Authorities`. Most certificates ship with a CA/chain certificate and you should import this too.

**Comment by Arnavion** [comment]
Yes, doing that retroactively adds the `caref` to the original server cert I had imported.

It would be good to implement the solution I noted in the OP as well, because all the information needed to identify the issuer is already in the original certificate's PEM blob.

**Comment by fraenki** [comment]
Thanks for the confirmation. So there already exists a working solution to this problem.

I may be wrong, but I think this is exactly how it is supposed to work in OPNsense:
* import the CA certificate under `System: Trust: Authorities`
* import the certificate under `System: Trust: Certificates`

A certificate that was imported this way should work both with OPNsense core components and all plugins.

> exportCerts.php should support certs which don't have a caref but do have more than one CERTIFICATE in the PEM blob

What's the reason not to use the previously described workflow?

I don't like the idea of modifying exportCerts.php to support this. It would need to be able to parse (unexpected) additional data, making it more complex without a real benefit, just to support an undocumented feature. And it would only work for HAProxy, but other OPNsense components use similar scripts to export certificates, they would not support this feature.

If there is a real use-case for this, please let me know.

**Comment by Arnavion** [comment]
The reason is that a single PEM containing the full chain is a standard way of dealing with certs. You get one file containing the chain from your issuer and can trivially copy-paste the whole chain into the "Import Certificate" form. Having to manually split the PEM and input two forms is busywork.

**Comment by fraenki** [comment]
I get that. However, since I'm a volunteer and there is a working solution, I'm not going to work on this. But everyone is free to step in and submit a PR, then I'll gladly review it.

(FWIW, I'd recommend to use something like Let's Encrypt, since there's no need to manually import certs.)

(I'll unassign myself and flag this issue so that it's clear that PRs are welcome. However, according to the contribution policy this issue may automatically be closed.)

**Comment by Arnavion** [comment]
>(FWIW, I'd recommend to use something like Let's Encrypt, so there's no need to manually import certs anymore.)

I do use Let's Encrypt. But I don't use Let's Encrypt from my OPNsense install, since I have multiple things that use the same (wildcard) cert apart from my router.

**Comment by fraenki** [comment]
> I don't use Let's Encrypt from my OPNsense install, since I have multiple things that use the same (wildcard) cert apart from my router

FYI, the Let's Encrypt plugin provides an automation to copy certificates via SFTP (SSH) to other hosts, but you're probably already aware of this. :)

**Comment by ThePowerOfDreams** [comment]
>fUCK0FF1

Where did this come from?
