### ISSUE TITLE
security/acme-client: certificate renewal fails after backup and restore of configuration

### ISSUE THREAD

**Issue by Woi** [opnsense/plugins#243]
Hey,

Since 21.6.2017 I get the following error in my acme log (It should be obvious, but the host/domain names are sanitised):

```
[Sat Sep 2 00:00:01 CEST 2017] | 'subdomain.example.net'' is not a issued domain, skip.
[Sat Sep 2 00:00:01 CEST 2017] | Renew: 'subdomain.example.net''
[Sat Sep 2 00:00:01 CEST 2017] | DOMAIN_PATH='/var/etc/acme-client/home/subdomain.example.net''
[...]
[Fri Jul 21 00:00:01 CEST 2017] | 'subdomain.example.net' is not a issued domain, skip.
[Fri Jul 21 00:00:01 CEST 2017] | Renew: 'subdomain.example.net'
[Fri Jul 21 00:00:01 CEST 2017] | DOMAIN_PATH='/var/etc/acme-client/home/subdomain.example.net'
```

These are the corresponding lines from system log:
```
Sep 2 00:00:05 | opnsense:  /usr/local/opnsense/scripts/OPNsense/AcmeClient/certhelper.php:  AcmeClient: unable to import certificate: subdomain.example.net
Sep 2 00:00:05 | opnsense:  /usr/local/opnsense/scripts/OPNsense/AcmeClient/certhelper.php:  AcmeClient: unable to import certificate, file not found:  /var/etc/acme-client/certs/58d16bf8caff73.73035884/cert.pem
Sep 2 00:00:05 | opnsense:  /usr/local/opnsense/scripts/OPNsense/AcmeClient/certhelper.php:  AcmeClient: issued/renewed certificate: subdomain.example.net
Sep 2 00:00:01 | configd.py: [5d07fe8e-f899-468f-a450-cfea2c575859] Reloading filter
Sep 2 00:00:00 | configd.py: [60e1d13e-e6ff-4643-a99a-f451b13e9ba3] cronjob running to sign or renew certificates
```
And this is from the crash report:
```
[01-Sep-2017 18:04:16 Europe/Berlin] PHP Warning:  cert_action_validator(): Node no longer exists in /usr/local/opnsense/scripts/OPNsense/AcmeClient/certhelper.php on line 122
[02-Sep-2017 00:00:05 Europe/Berlin] PHP Warning:  cert_action_validator(): Node no longer exists in /usr/local/opnsense/scripts/OPNsense/AcmeClient/certhelper.php on line 122
```

The cron job was working before. Last successful run was on 20.5.2017, which is the issue date of my now expired certificate. I'll have a cron job for nightly updates which makes me sure it was working ok on OPNsense 17.1.5.
I assume some change between 20.5 and 20.6 must have broken my cron job. It could have been an update (OPNsense 17.1.6-17.1.8) or some changed configuration. Unfortunately my configuration history (`diag_confbak.php`) ends mid August. But I'm quite sure to not have altered the Let's encrypt configuration. 

Common name: `subdomain.example.net`
Multi-Domain (SAN): `host.subdomain.example.net`
Last Acme Status: `internal error`
Validation method is `http_portfwd_on_wan`

So what comes to my mind, that might be special:
* I use a SAN entry, which has one more level than the domain name
* I have dynamic IPv4 and IPv6 addresses 
* I use a DynDNS hostname, but my domain provider only supports IPv4

**Comment by fraenki** [comment]
@Woi Thanks for your report! I'm not aware of any such issue and can't reproduce it.

Can you update to the current release of OPNsense, 17.7.1? 
Can you try to manually renew the certificate from the WebUI?

**Comment by Woi** [comment]
Thanks for the plugin and your support :)

I'm running OPNsense 17.7.1_2-amd64. It also fails when triggered from the WebUI.
Just for clarification: The problem exists since 21.6 and reoccurs every night. Last successful renewal was on  20/21.5. Between 20/21.5 and 21.6 no renewal was triggered.

**Comment by fraenki** [comment]
According to [the acme.sh source](https://github.com/Neilpang/acme.sh/blob/afdd02a80dcfee3c43cffc84e7e6dfd6b4cf9a8c/acme.sh#L3965-L3969), the error "is not a issued domain" is displayed if acme.sh can't find the (previously created) configuration file for this domain.

@Woi Have you changed the domain name? Or did you reinstall OPNsense? In any case the file seems to be lost.

Can you try to remove the Certificate from the LE GUI and re-create it? This way it should not be handled as "renewal" but instead acme.sh would try to recreate everything. (Note that the "old" certificate will remain in OPNsense's Certificate Managed and not be deleted.)

**Comment by Woi** [comment]
I followed your directions and deleted and recreated the certificate. It was a bit rough, but now I have a working certificate again :)

Regarding the root cause of my problem: You made a very good guess :) I replaced my Alix-Board with an APU2 at the time in question. I used `/diag_backup.php` to backup and restore the configuration from a file. So backup and/or restore missed a some bits of ACME configuration.

**Comment by fraenki** [comment]
>  I used /diag_backup.php to backup and restore the configuration from a file. So it looks like backup and/or restore missed some bits of ACME configuration.

I'll try to fix this in the next release.

**Comment by Woi** [comment]
Nice. Give me a shout if you like me to test your patch.

**Comment by fraenki** [comment]
Sorry, this got lost somehow. os-acme-client version 1.20 includes a new button in settings that allows to reset all states, which in turn should trigger acme.sh to recreate everything. Let me know if it works for you.

**Comment by EugenMayer** [comment]
Since 18.7.10 has 1.18, i guess 1.20 is 19.1 only then.

Does this button just remove all certificates and one has to add them, or just wipes them on the drive and lets acme.sh re-fetch them from scratch?

**Comment by EugenMayer** [comment]
ran `/usr/bin/find /var/etc/acme-client/home /var/etc/acme-client/configs /var/etc/acme-client/certs /var/etc/acme-client/keys /var/etc/acme-client/accounts -type f -delete` manually

then ran issue/renew certificates now and it failed, since it still tried to renew - i guess you have a state for each cert in the `config.xml`, so you are specifically triggering renew on acme, and not `--issue` and this will fail again.

This is not an issue of acme.sh in this regard, it's just a mixed state. So you need a new button "reset" and "force issues all certificates" in addition too - i would guess this issue is not closed this way ( IMHO )

For me after all it's good to be forced to move traefik at home too now for that regard, as i did with all the other boxes in the office - maybe its just me :)
