### ISSUE TITLE
net/freeradius: Login incorrect (eap_peap: (TLS) Alert write:fatal:protocol version) [after update]

### ISSUE THREAD

**Issue by primemaster** [opnsense/plugins#2434]
**Describe the bug**
After updating to 21.1.7_1 one of my Radius user (Android 7 phone) isn't able to get authenticated. On the previous version of OPNsense (21.1.5 or .6) it was working.
Was the minimal TLS version changed to TLS 1.2 by that update?

**To Reproduce**
1. Have OPNsense 21.1.7_1 running with os-radius 1.9.13 / Freeradius 3.0.22
2. Try to connect Android 7.0 phone to Unifi Wifi using 802.1x 
3. device doesn't connect

**Expected behavior**
Device authenticates against user & password stored in Freeradius / OPNsense.
(The Radius server shall select a TLS Cipher Suite from the list that Android offers)

**Screenshots**

**Relevant log files**
2021-06-19T01:38:00	 	Auth: (254) Login incorrect (eap_peap: (TLS) Alert write:fatal:protocol version): [$CLIENT/<via Auth-Type = eap>] (from client unifi port 0 cli $MACADDRESS)	 
2021-06-19T01:38:00	 	ERROR: (254) eap_peap: ERROR: (TLS) Server : Error in error	 
2021-06-19T01:38:00	 	ERROR: (254) eap_peap: ERROR: (TLS) Alert write:fatal:protocol version
...
Update OPNsense to 21.
...
2021-06-18T20:05:44	 	Auth: (6943) Login OK: [$CLIENT/<via Auth-Type = eap>] (from client unifi port 0 cli $MACADDRESS)	
2021-06-18T20:05:44	 	Auth: (6942) Login OK: [$CLIENT/<via Auth-Type = eap>] (from client unifi port 0 via TLS tunnel)

Wireshark decoded package that is send from Android to Freeradius (which fails then):

        AVP: t=EAP-Message(79) l=115 Last Segment[1]
            Type: 79
            Length: 115
            EAP fragment: 0219007119800000006716030100620100005e0301f7ae09...
            Extensible Authentication Protocol
                Code: Response (2)
                Id: 25
                Length: 113
                Type: Protected EAP (EAP-PEAP) (25)
                EAP-TLS Flags: 0x80
                    1... .... = Length Included: True
                    .0.. .... = More Fragments: False
                    ..0. .... = Start: False
                    .... .000 = Version: 0
                EAP-TLS Length: 103
                Secure Sockets Layer
                    TLSv1 Record Layer: Handshake Protocol: Client Hello
                        Content Type: Handshake (22)
                        Version: TLS 1.0 (0x0301)
                        Length: 98
                        Handshake Protocol: Client Hello
                            Handshake Type: Client Hello (1)
                            Length: 94
                            Version: TLS 1.0 (0x0301)
                            Random: f7ae093d44d73e696e0dfa19c2347bb3d9d5272f32b583ec...
                            Session ID Length: 0
                            Cipher Suites Length: 26
                            Cipher Suites (13 suites)
                                Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA (0xc00a)
                                Cipher Suite: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (0xc014)
                                Cipher Suite: TLS_DHE_RSA_WITH_AES_256_CBC_SHA (0x0039)
                                Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA (0xc009)
                                Cipher Suite: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (0xc013)
                                Cipher Suite: TLS_DHE_RSA_WITH_AES_128_CBC_SHA (0x0033)
                                Cipher Suite: TLS_ECDHE_ECDSA_WITH_RC4_128_SHA (0xc007)
                                Cipher Suite: TLS_ECDHE_RSA_WITH_RC4_128_SHA (0xc011)
                                Cipher Suite: TLS_RSA_WITH_AES_256_CBC_SHA (0x0035)
                                Cipher Suite: TLS_RSA_WITH_AES_128_CBC_SHA (0x002f)
                                Cipher Suite: TLS_RSA_WITH_RC4_128_SHA (0x0005)
                                Cipher Suite: TLS_RSA_WITH_RC4_128_MD5 (0x0004)
                                Cipher Suite: TLS_RSA_WITH_3DES_EDE_CBC_SHA (0x000a)
                            Compression Methods Length: 1
                            Compression Methods (1 method)
                                Compression Method: null (0)
                            Extensions Length: 27
                            Extension: renegotiation_info (len=1)
                                Type: renegotiation_info (65281)
                                Length: 1
                                Renegotiation Info extension
                                    Renegotiation info extension length: 0
                            Extension: extended_master_secret (len=0)
                                Type: extended_master_secret (23)
                                Length: 0
                            Extension: ec_point_formats (len=2)
                                Type: ec_point_formats (11)
                                Length: 2
                                EC point formats Length: 1
                                Elliptic curves point formats (1)
                                    EC point format: uncompressed (0)
                            Extension: supported_groups (len=8)
                                Type: supported_groups (10)
                                Length: 8
                                Supported Groups List Length: 6
                                Supported Groups (3 groups)
                                    Supported Group: secp256r1 (0x0017)
                                    Supported Group: secp384r1 (0x0018)
                                    Supported Group: secp521r1 (0x0019)

iOS however sends:

        AVP: t=EAP-Message(79) l=163 Last Segment[1]
            Type: 79
            Length: 163
            EAP fragment: 02b600a119800000009716030100920100008e030360cdb4...
            Extensible Authentication Protocol
                Code: Response (2)
                Id: 182
                Length: 161
                Type: Protected EAP (EAP-PEAP) (25)
                EAP-TLS Flags: 0x80
                    1... .... = Length Included: True
                    .0.. .... = More Fragments: False
                    ..0. .... = Start: False
                    .... .000 = Version: 0
                EAP-TLS Length: 151
                Secure Sockets Layer
                    TLSv1.2 Record Layer: Handshake Protocol: Client Hello
                        Content Type: Handshake (22)
                        Version: TLS 1.0 (0x0301)
                        Length: 146
                        Handshake Protocol: Client Hello
                            Handshake Type: Client Hello (1)
                            Length: 142
                            Version: TLS 1.2 (0x0303)
                            Random: 60cdb43d4b2fa98524e9140d00d2d9a8740c1a556ddc1e61...
                            Session ID Length: 0
                            Cipher Suites Length: 44
                            Cipher Suites (22 suites)
                                Cipher Suite: TLS_EMPTY_RENEGOTIATION_INFO_SCSV (0x00ff)
                                Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 (0xc02c)
                                Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 (0xc02b)
                                Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384 (0xc024)
                                Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256 (0xc023)
                                Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA (0xc00a)
                                Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA (0xc009)
                                Cipher Suite: TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA (0xc008)
                                Cipher Suite: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (0xc030)
                                Cipher Suite: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (0xc02f)
                                Cipher Suite: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 (0xc028)
                                Cipher Suite: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 (0xc027)
                                Cipher Suite: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (0xc014)
                                Cipher Suite: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (0xc013)
                                Cipher Suite: TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA (0xc012)
                                Cipher Suite: TLS_RSA_WITH_AES_256_GCM_SHA384 (0x009d)
                                Cipher Suite: TLS_RSA_WITH_AES_128_GCM_SHA256 (0x009c)
                                Cipher Suite: TLS_RSA_WITH_AES_256_CBC_SHA256 (0x003d)
                                Cipher Suite: TLS_RSA_WITH_AES_128_CBC_SHA256 (0x003c)
                                Cipher Suite: TLS_RSA_WITH_AES_256_CBC_SHA (0x0035)
                                Cipher Suite: TLS_RSA_WITH_AES_128_CBC_SHA (0x002f)
                                Cipher Suite: TLS_RSA_WITH_3DES_EDE_CBC_SHA (0x000a)
                            Compression Methods Length: 1
                            Compression Methods (1 method)
                                Compression Method: null (0)
                            Extensions Length: 57
                            Extension: supported_groups (len=8)
                                Type: supported_groups (10)
                                Length: 8
                                Supported Groups List Length: 6
                                Supported Groups (3 groups)
                                    Supported Group: secp256r1 (0x0017)
                                    Supported Group: secp384r1 (0x0018)
                                    Supported Group: secp521r1 (0x0019)
                            Extension: ec_point_formats (len=2)
                                Type: ec_point_formats (11)
                                Length: 2
                                EC point formats Length: 1
                                Elliptic curves point formats (1)
                                    EC point format: uncompressed (0)
                            Extension: signature_algorithms (len=18)
                                Type: signature_algorithms (13)
                                Length: 18
                                Signature Hash Algorithms Length: 16
                                Signature Hash Algorithms (8 algorithms)
                            Extension: status_request (len=5)
                                Type: status_request (5)
                                Length: 5
                                Certificate Status Type: OCSP (1)
                                Responder ID list Length: 0
                                Request Extensions Length: 0
                            Extension: signed_certificate_timestamp (len=0)
                                Type: signed_certificate_timestamp (18)
                                Length: 0
                            Extension: extended_master_secret (len=0)
                                Type: extended_master_secret (23)
                                Length: 0

And the Radius Server answers:

        AVP: t=EAP-Message(79) l=247 Last Segment[4]
            Type: 79
            Length: 247
            EAP fragment: 00304406096086480186f842010d043716354f504e73656e...
            Extensible Authentication Protocol
                Code: Request (1)
                Id: 183
                Length: 1004
                Type: Protected EAP (EAP-PEAP) (25)
                EAP-TLS Flags: 0xc0
                    1... .... = Length Included: True
                    .1.. .... = More Fragments: True
                    ..0. .... = Start: False
                    .... .000 = Version: 0
                EAP-TLS Length: 3048
                [4 EAP-TLS Fragments (3048 bytes): #14(994), #16(994), #18(994), #20(66)]
                Secure Sockets Layer
                    TLSv1.2 Record Layer: Handshake Protocol: Server Hello
                        Content Type: Handshake (22)
                        Version: TLS 1.2 (0x0303)
                        Length: 93
                        Handshake Protocol: Server Hello
                            Handshake Type: Server Hello (2)
                            Length: 89
                            Version: TLS 1.2 (0x0303)
                            Random: 00bfb42604d079c8bd4a3c9ed214ffb7d707c80fc6c586df...
                            Session ID Length: 32
                            Session ID: 171d6a5e672f36537edd4ff51fa07ec714707f915ce7f3d0...
                            Cipher Suite: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (0xc030)
                            Compression Method: null (0)
                            Extensions Length: 17
                            Extension: renegotiation_info (len=1)
                                Type: renegotiation_info (65281)
                                Length: 1
                                Renegotiation Info extension
                                    Renegotiation info extension length: 0
                            Extension: ec_point_formats (len=4)
                                Type: ec_point_formats (11)
                                Length: 4
                                EC point formats Length: 3
                                Elliptic curves point formats (3)
                                    EC point format: uncompressed (0)
                                    EC point format: ansiX962_compressed_prime (1)
                                    EC point format: ansiX962_compressed_char2 (2)
                            Extension: extended_master_secret (len=0)
                                Type: extended_master_secret (23)
                                Length: 0
                    TLSv1.2 Record Layer: Handshake Protocol: Certificate
                        Content Type: Handshake (22)
                        Version: TLS 1.2 (0x0303)
                        Length: 2598
                        Handshake Protocol: Certificate
                            Handshake Type: Certificate (11)
                            Length: 2594
                            Certificates Length: 2591
                            Certificates (2591 bytes)
                    TLSv1.2 Record Layer: Handshake Protocol: Server Key Exchange
                        Content Type: Handshake (22)
                        Version: TLS 1.2 (0x0303)
                        Length: 333
                        Handshake Protocol: Server Key Exchange
                            Handshake Type: Server Key Exchange (12)
                            Length: 329
                            EC Diffie-Hellman Server Params
                                Curve Type: named_curve (0x03)
                                Named Curve: secp256r1 (0x0017)
                                Pubkey Length: 65
                                Pubkey: 04b69cdf4fdbdedb1beeb2d514bada7c55ac2326b1471135...
                                Signature Algorithm: rsa_pkcs1_sha256 (0x0401)
                                Signature Length: 256
                                Signature: a3428df5bdc600b574506352effd30a221d64397f26a6f2f...
                    TLSv1.2 Record Layer: Handshake Protocol: Server Hello Done
                        Content Type: Handshake (22)
                        Version: TLS 1.2 (0x0303)
                        Length: 4
                        Handshake Protocol: Server Hello Done
                            Handshake Type: Server Hello Done (14)
                            Length: 0
        AVP: t=Message-Authenticator(80) l=18 val=2e249d48494772b5868b4d5b0243bab7
            Type: 80
            Length: 18
            Message-Authenticator: 2e249d48494772b5868b4d5b0243bab7
        AVP: t=State(24) l=18 val=7d1657957ca14e627055729e0da8aca5
            Type: 24
            Length: 18
            State: 7d1657957ca14e627055729e0da8aca5

**Additional context**
An older iPhone (iOS 12.3) does connect without an issue.

**Environment**
Phone is on Android 7.0 . It is also happening for an Android 5.1.1 device

| Type | opnsense |
| -- | -- |
 | Version | 21.1.7_1 |
 | Architecture | amd64 |
 | Flavour | OpenSSL |
 | Commit | 86a95e21b |
 | Mirror | https://pkg.opnsense.org/FreeBSD:12:amd64/21.1 |
 | Repositories | OPNsense |
 | Updated on | Fri Jun 18 20:18:35 CEST 2021 | 
 | Checked on | Sat Jun 19 10:24:51 CEST 2021 |

**Comment by primemaster** [comment]
I now tried to set 

    disable_tlsv1_2 = yes

in /usr/local/etc/raddb/mods-available/eap . But then the following error message appears in the log:
 Timestamp | Message
 -- | --
  2021-06-19T12:06:39 | Error: /usr/local/etc/raddb/mods-enabled/eap[15]: Instantiation failed for module "eap" 
  2021-06-19T12:06:39 | Error: rlm_eap (EAP): Failed to initialise rlm_eap_tls 
  2021-06-19T12:06:39 | Error: rlm_eap_tls: Failed initializing SSL context 
  2021-06-19T12:06:39 | Error: tls: 'disable_tlsv1_2' is set, but 'min_version &lt;= 1.2'.  These cannot both be true. 
  2021-06-19T12:06:39 | Info: Debugger not attached

**Comment by primemaster** [comment]
Found the following release note:

https://github.com/FreeRADIUS/freeradius-server/releases/tag/release_3_0_22 

- The default minimum TLS version is now TLS 1.2, as per RFC 8996. Older versions can be allowed by setting tls_min_version, and updating cipher_list.

**Comment by primemaster** [comment]
adding 

                tls_min_version = "1.0"
                tls_max_version = "1.2"

to /usr/local/etc/raddb/mods-available/eap lead to a connected Android device. So maybe the FreeRADIUS plugin should write that to the eap config file.

**Comment by mimugmail** [comment]
Thx for your report, I will add it

**Comment by primemaster** [comment]
@mimugmail: I am preparing a PR which also updates the comments to the upstream v3.0.22.

**Comment by markusdd** [comment]
just one comment guys:

I would sincerly recommend making this a GUI option and a concious decision on the side of the user.

There are very good reasons NOT to allow older TLS versions, especially below 1.1 .

So if older versions get allowed, the end user should know.
