### ISSUE TITLE
net/freeradius: client web config page does not accept CIDR notation

### ISSUE THREAD

**Issue by markusdd** [opnsense/plugins#2456]
The web interface has currently a glitch where the freeradius cannot be configured to accept a CIDR-Range.

So one has to hack the underlying config file on the commandline.

so e.g. 10.10.0.40 is accepted as a client, but 10.10.0.0/22 is not.

This is cumbersome because this way each access point needs to be given seperately.

Version:
OPNsense 21.4.1-amd64
FreeBSD 12.1-RELEASE-p16-HBSD
OpenSSL 1.1.1k 25 Mar 2021

**Comment by markusdd** [comment]
also as a workaround question: how can we make our client.conf edit permanent until this is fixed?

**Comment by fourthwall** [comment]
Hi,

I published a fix for this issue when I encountered it today:
https://github.com/opnsense/plugins/pull/2459

To fix on your installation:
Edit /usr/local/opnsense/mvc/app/models/OPNsense/Freeradius/Client.xml

Change:
<ip type="HostnameField">
to

<ip type="NetworkField">

Then reload FreeRADIUS server on OPNsense. Seems to work for me

**Comment by markusdd** [comment]
excellent! thanks so much!

**Comment by mimugmail** [comment]
This can be closed, update will get released with next version
