### ISSUE TITLE
net/freeradius: EAP-TTLS with inner auth from LDAP is impossible to configure from GUI

### ISSUE THREAD

**Issue by markusdd** [opnsense/plugins#2458]
We have been tinkering to get our desired setup working, but we had to manually patch config files to make it work.

If you wish to use EAP-TTLS with inner-tunnel auth set to PAP, which actually uses LDAP on Radius side, in inner-tunnel config,

the authorize ldap section needs to look like the one in the default file.

The way it is now, for any type of EAP auth that uses an inner tunnel, LDAP will never work.

If the inner-tunnel site config is changed as shown, and the client is configured for EAP-TTLS and PAP as inner auth, then the TLS tunnel is built properly using the annonymous uid and then as the inner auth the credentials are being sent and an LDAP bind is attempted to verify the user can authenticate. This has been tested against an IPA LDAP server. 

```
authorize {
...

        #
        #  The ldap module reads passwords from the LDAP database.
        ldap
          if ((ok || updated) && User-Password) {
              update control {
                  Auth-Type := ldap
              }
          }
...
}

authenticate {
...
        Auth-Type LDAP {
                ldap
        }
...
}

```

**Comment by markusdd** [comment]
as a workaround now: what is the way to make this permanent for us?
Currently each time the gui is touched, our edits will be overridden.

**Comment by mimugmail** [comment]
I will take care of all your Tickets, sounds reasonable. Thx for investigation

**Comment by markusdd** [comment]
Sure, thanks so much for taking care of this plugin. It has saved us the huge PITA to setup a radius ourselves, which is always everyones least favorite thing to do... 😆

**Comment by mimugmail** [comment]
Sorry for the delay, I added a checkbox in LDAP section to explicitly enable this, so this wont break existing setups (if any) cause I cant test every combination.

**Comment by markusdd** [comment]
it seems that this has been adressed in some other ticket. is that the case?

**Comment by mimugmail** [comment]
Yep, #2626 .. maybe @fichtner is motivated to have a look next week :)
