### ISSUE TITLE
Feature Request: siproxd integration

### ISSUE THREAD

**Issue by NicholasRush** [opnsense/plugins#246]
Bezogen auf Forenthread: https://forum.opnsense.org/index.php?topic=5799

[Dokumentation zur Integration von Siproxd in OPNsense.pdf](https://github.com/opnsense/plugins/files/1273186/Dokumentation.zur.Integration.von.Siproxd.in.OPNsense.pdf)

Ich hoffe ich habe das gut genug erklärt.

**Comment by mimugmail** [comment]
Tomorrow I'll start with the basic layout.
Thanks for the excellent explanation! 👍

**Comment by fichtner** [comment]
@NicholasRush Very good spec, thank you!

**Comment by mimugmail** [comment]
@NicholasRush I'm quite busy with a multi wan issue here, only little time for creating the model. 
Is it ok to start testing mid of next week?

**Comment by NicholasRush** [comment]
@mimugmail No problem, because i am currently ill. And i think i need about two weeks to be healthy again.

**Comment by mimugmail** [comment]
```
pkg install git
opnsense-code -a mimugmail plugins
cd /usr/plugins
git checkout siproxd
cd net/siproxd
make package
pkg install work/pkg/o*
```

It's missing some stuff. 
Is siproxd able to handle multiple outbound_domain_name at once? So can multiple be enabled? 
If no I'd add jsut a single form field, if yes then a new tab with dialog fields.

**Comment by NicholasRush** [comment]
@mimugmail Oh that´s very fast. Yes siproxd definitivly can handle multiple options of these entrys:

outbound_domain_name = freenet.de
outbound_domain_host = proxy.for.domain.freende.de
outbound_domain_port = 5060

**Comment by mimugmail** [comment]
Ok, then we need two new tabs for users and outbound_domains, use_rport dropdown, ACLs and the plugins.

How about registered devices? Is it just looking at the content of `registration_file` ?

**Comment by NicholasRush** [comment]
For the registered-devices file, there just have to be a protected text area Box or a scrollable <div> with the content of the `registration_file`.

**Comment by mimugmail** [comment]
Regarding plugins, we only need the stuff "Essential for OPNsense"? 

It's getting quite complex to make all of the useable/configureable like in you doc, esp. regexp and shortcall.

**Comment by fichtner** [comment]
a minimum viable plugin is a great start to wait and reassess later on

**Comment by mimugmail** [comment]
I'm only asking because I don't know which ones are essential to run the plugin at all since I have never used siproxd :)

**Comment by mimugmail** [comment]
@NicholasRush Can you show me an example output of registrations?

ATM my output looks like this:

![image](https://user-images.githubusercontent.com/20438689/30546216-491c4e62-9c8c-11e7-95a3-5b164d19f526.png)

**Comment by NicholasRush** [comment]
@mimugmail 
Yes the output is right, because my looks the same. If clients have to authenticate at siproxd, then there should be more detailed output in the file. But i don´t use the authentication feature and than there will be nothing more like this.
![reg](https://user-images.githubusercontent.com/15971491/30557446-902356c6-9cae-11e7-978b-df3f54fecb8d.PNG)

The siproxd webgui plugin does not need to be "as fast as possible" ready to use. It is better to have more configuration features from the beginning, than a plugin which you have, but you cannot use it how you need it. I already know that my requirements, how the form should work, are not easy to develop. 
When it´s possible it would be better to put all configuration options in an XML file, and in that file you change things like, enable users, add outbound proxies etc. And if you save your configuration, than it first writes everything to the XML file, and from that it generates a minimal siproxd configuration with all currently enabled options. Like an helper file.

**Comment by mimugmail** [comment]
![image](https://user-images.githubusercontent.com/20438689/30650073-47ebdbc4-9e22-11e7-99aa-bb27c5056ce5.png)


![image](https://user-images.githubusercontent.com/20438689/30650108-5bdf843c-9e22-11e7-9230-5a8c37b80e24.png)


![image](https://user-images.githubusercontent.com/20438689/30650126-6ac2b8d4-9e22-11e7-981d-5ed56d1e8f6d.png)


![image](https://user-images.githubusercontent.com/20438689/30650150-7b3943cc-9e22-11e7-89c2-a22a199999ab.png)


Plugins are missing and "Current registrations" need some newlines, then it's finished :)

**Comment by NicholasRush** [comment]
@mimugmail Wow, this looks very very nice! I will test it soon.

**Comment by mimugmail** [comment]
@NicholasRush with the latest update you can install the plugin via CLI:

`pkg install siproxd os-siproxd-devel`

Would be cool if you find the time to test it, it wont go stable without your OK :)

**Comment by fichtner** [comment]
PS. siproxd installs automatically

**Comment by NicholasRush** [comment]
I will test the plugin completely at the weekend.

**Comment by NicholasRush** [comment]
@mimugmail There are currently too many bugs in it, to make the plugin public available. First there are small bugs like the interface settings, which are not set.

![image](https://user-images.githubusercontent.com/15971491/31048612-2c2c0466-a621-11e7-9c44-161435778a89.png)

The rport option sets a variable. 

![image](https://user-images.githubusercontent.com/15971491/31048620-5c8a8010-a621-11e7-912b-4cd1159f379b.png)

The RTP input and output dejitter cannot be set.

![image](https://user-images.githubusercontent.com/15971491/31048630-9de49b0e-a621-11e7-8225-183eaa5550da.png)

Thats what i have currently found out.

**Comment by fichtner** [comment]
“Option3” is a new core feature that is missing from your install (development version)

Siproxd is still in development mode... we can take as many iterations as necessary before it is shipped as 1.0 in an actual opnsense release. 😊

**Comment by NicholasRush** [comment]
The Bugs, that i have described, are all that i could find. If they are fixed to the end of next weekend, i will test it again.

**Comment by mimugmail** [comment]
Thanks for testing! I'll fix them the next days and give you a note :)

**Comment by mimugmail** [comment]
Hi @NicholasRush, patches are in but not as a pkg yet.

If you want to test:

```
rm -rf /usr/plugins/
opnsense-code -a opnsense plugins
cd /usr/plugins/net/siproxd
make package
pkg install work/pkg/o*
```

**Comment by fichtner** [comment]
This is enough... ;)

    # opnsense-code -f plugins
    # cd /usr/plugins/net/siproxd
    # make upgrade

**Comment by mimugmail** [comment]
again what learned :D

**Comment by NicholasRush** [comment]
The authentication and the inbound and outbound interface settings are working now. Whats not working, is the in- output dejitter. Because i cannot change the setting. The "Remote ports in VIA-Header"-Option is also not working currently.

And maybe, but that´s is an option that could be added when the bugs are fixed, is a reminder that is showing up when a user add, remove, activate or disable a user in the users-tab or change something in the outbound proxy tab. The reminder could be same that is showing up when you change in the firewall settings a rule. I think that is useful, because nobody knows that he has to save the config on the "general"-tab to activate the changed settings in these tabs.
![image](https://user-images.githubusercontent.com/15971491/31196187-18436f0a-a94d-11e7-99f9-fd77e3aabb75.png)

**Comment by mimugmail** [comment]
Which browser are you using? For me dejitter stuff is working fine. 
The Option setting will only work when you add some patches, these will be included soon, so not a real bug.

I can add an additional save button in the users tab, no problem :)

**Comment by mimugmail** [comment]
Oh, I thought this is 0 for disable and 1 for enable :) I'll fix this!

**Comment by fichtner** [comment]
motivational post: @mimugmail @NicholasRush thank you both for the work!

**Comment by mimugmail** [comment]
Show must go on :)

@NicholasRush 

If you want the option thing fixed:

```
opnsense-patch c7c1c55
opnsense-patch ecb0f41
opnsense-patch 60b0b26

```

And the other things just to again:

```
opnsense-code -f plugins
cd /usr/plugins/net/siproxd
make upgrade
```

**Comment by fichtner** [comment]
the "option thing" has been shipped in OPNsense 17.7.4 ;)

https://github.com/opnsense/changelog/blob/master/doc/17.7/17.7.4#L24

**Comment by mimugmail** [comment]
Whoopsie .. so forget about this one :)

**Comment by NicholasRush** [comment]
@mimugmail Now everything is working fine. Great work. 

I think it could be now released to the public.

**Comment by fichtner** [comment]
ok, if @mimugmail agrees I'll change it to 1.0 and remove the development lock so that it will show up in 17.7.6. :)

**Comment by mimugmail** [comment]
@eugenmayer have tested it yet? Would be cool to have a second beta tester before going stable :)

**Comment by EugenMayer** [comment]
@mimugmail i would love to, still waiting for the answer in the forum ( https://forum.opnsense.org/index.php?topic=5799.msg25578#msg25578 ) to be actually sure i am falling into that case.. before i test and the result is "still not working" .. but the reason is, its just not for my case.

Does not help here, if i add FUD to the issue :)

**Comment by fichtner** [comment]
@mimugmail release? :D

**Comment by mimugmail** [comment]
Release, but dont be mad when there is some trouble in the beginning ;)

**Comment by fichtner** [comment]
never! thanks to you all!

**Comment by NicholasRush** [comment]
The trouble in the beginning should not be a big problem. If anyone have trouble with it, he or she should write in this Forum topic: https://forum.opnsense.org/index.php?topic=6112.0
And if there is a problem with the help inside the Plugin, i will change the help text and that can be pulled as patch from my Github account then.
