### ISSUE TITLE
Wireguard DNS config updates Unbound configuration, localhost DNS fails

### ISSUE THREAD

**Issue by twodrops** [opnsense/plugins#2462]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

If DNS servers are specified in Wireguard configuration, they are overwritting unbound configuration (`/etc/resolv.conf`). This removes "127.0.0.1" resulting is name resolution not working for localhost anymore.

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**

Prerequsite: Make sure "Do not use the local DNS service as a nameserver for this system" is NOT selected.

1. Specify DNS Servers in Wireguard "Local" Settings
2. Restart OPNsense
3. Run any operation that needs name resolution on localhost (for example, check "Status" in System->Firmware->Status)
4. The operation fails and Status is not displayed
5. Check `/etc/resolv.conf`
6. `nameserver 127.0.0.1` is missing in `/etc/resolv.conf`
7. Click Save on "System->Settings->General" 
8. `nameserver 127.0.0.1` appears in `/etc/resolv.conf`
9. Repeat 3.
10. The operation succeeds and "Status" is displayed
11. Restart OPNsense
12. Repeat 3.
13. The operation fails and Status is not displayed

**Workaround**

Do not specify DNS Server in Wireguard

**Related Discussions**
https://www.reddit.com/r/OPNsenseFirewall/comments/mwgl7r/update_issue/

**Environment**

OPNsense 21.1.8_1-amd64
Hardware: PC Engines apu2, coreboot v4.14.0.2

**Comment by fichtner** [comment]
Disable DNS in WireGuard configuration…

**Comment by twodrops** [comment]
That's right. I specified this as workaround in the issue above. 
Is this an intended behaviour?

**Comment by fichtner** [comment]
Yes, it's how WireGuard developers designed it and it's relatively useless for a full firewall. We have since moved the setting to advanced hidden options.

**Comment by twodrops** [comment]
Thanks. Makes totally sense now. I was confused with the DNS Server specification in Wireguard in the context of OPNsense.
How about providing a small hint about this in https://docs.opnsense.org/manual/how-tos/wireguard-client.html
Shall I raise a PR?

**Comment by fichtner** [comment]
Yes please, that would be good indeed. 😊

**Comment by psychogun** [comment]
Does it not already say, or is this the PR in effect perhaps;

https://docs.opnsense.org/manual/how-tos/wireguard-client.html

> Leave the DNS Server field (which appears if advanced mode is selected) blank. Otherwise WireGuard will overwrite OPNsense’s DNS configuration

**Comment by twodrops** [comment]
@psychogun I didn't manage to create a PR yet (forgot about this completely 😢)
The text seems to be new and explains it correctly. This issue can therefore be closed.
