### ISSUE TITLE
Feature request: Backup to Nextcloud Public Shares

### ISSUE THREAD

**Issue by Michael-Hennemann** [opnsense/plugins#2465]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[-] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[-] I have searched the existing issues and I'm convinced that mine is new.

[-] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**

If you use the backup to nextcloud you have to store user credentials of a real nextcloud user in the opnsense configuration. 
If you have more than one opnsense instance to backup and change the password of that user you have to change it everywhere
I guess storing user credentials in configurations is never a good idea.

**Describe the solution you'd like**
IMHO it would be nice if you could backup the opnsense configuration to nextcloud public shares.  If you have several opnsense instances to backup you could create a seperate share for each one, with an (optional) unique password. You could even set the permissions to "file drop only" 
Those individual share passwords don't change if you change the password for your nexcloud user. 

Nextcloud public shares can be accessed quite simple via WebDAV. The URL is the same one for every share on your Nextcloud, The share ID functions as username, Password is optional

`https://example.com/nextcloud/public.php/webdav`

https://docs.nextcloud.com/server/20/user_manual/en/files/access_webdav.html#accessing-public-shares-over-webdav

**Describe alternatives you've considered**

**Additional context**

**Comment by putt1ck** [comment]
File drop only would be ideal

**Comment by putt1ck** [comment]
Shouldn't be closed.

**Comment by fichtner** [comment]
Missing a contributor. Volunteers step forward. 😊

**Comment by putt1ck** [comment]
lf the maker of the existing NC backup plugin can give some guidance I can probably volunteer someone to modify that to allow backup to public shares (file drops). Would seem the best solution where multiple firewalls are being supported.

**Comment by mimugmail** [comment]
https://github.com/opnsense/core/pull/2251/files

This was the Initial commit. If you know someone PHP experienced it should be doable.

**Comment by Michael-Hennemann** [comment]
Hi, 
well, I am no developer so I guess I won’t be much of a help, I just thought it might be a nice feature to have  ^^ 

But I think _IF_ someone is willing to work on that, it might be a good idea to move from a specific nextcloud backup to a generic  WebDAV backup where you can enter any webdav URL with or without username and password. 
That way it would work with nextcloud user auth, nextcloud public link and potentially many other similar tools… 

cheers
Michael
