### ISSUE TITLE
Zerotier initial bring-up rocky, down after reboot

### ISSUE THREAD

**Issue by obrienmd** [opnsense/plugins#247]
Per the issue on binding interfaces https://github.com/opnsense/plugins/issues/239, I was able to get OSPFv2 working as expected over a ZeroTier "switch" built in the OPNSense UI with static IPs :) Thanks @dharrigan !

During this testing, I found the following to report:

1. The initial bring-up is a little rocky:
   - I had to disable/enable, re-apply a few times on that page to get it to come up, even after waiting 15 minutes the first time I brought it up. 
   - Generally, I think the UI would benefit from information on current status (up/down, client id, error msg, and could use a UI to the ZT log.

1. After a reboot, the ZeroTier interface does not come up as expected:
   - No networks show in `zerotier-cli listnetworks` at the command line, but the network **does** show in the ZeroTier web UI list. 
   - OPNSense interface for ZT with 'Prevent interface removal' was re-assigned to igb0 (the first available NIC on my system).
   - After clicking 'Apply' again in the ZeroTier web UI, ZT interface remains down.
   - After disabling and enabling in the ZeroTier web UI, ZT interface comes up with **a different client id**, meaning it needs to be re-authorized in ZT Central. Once re-authorized, the OPNSense interface comes up and OSPF starts working without intervention, which was pretty cool to see.

**Comment by obrienmd** [comment]
I did some digging on 1.1 - when it's not working after initial setup, `zerotier-cli listnetworks` (or any subcommand for that matter) results in:
`zerotier-cli: missing port and zerotier-one.port not found in /var/db/zerotier-one`

**Comment by fichtner** [comment]
@obrienmd Sounds like an issue in the FreeBSD package. Will check tomorrow.

**Comment by dharrigan** [comment]
Hi,

Thanks for the feedback @obrienmd. @fichtner happy to work with you on this one (tbh, I think I noticed the same thing yesterday - the service didn't start cleanly after an install - but was investigating the other issue so didn't delve further).

-=david=-

**Comment by fichtner** [comment]
It looks like this is simply because of zerotier-one not being started unless a network is configured and applied.

Traditionally, off by default is sensible, but in other plugins we have a global "enabled" flag to allow a zero-config service run.

Does that make sense? I haven't reproduced yet, just looked at the code.

**Comment by dharrigan** [comment]
@fichtner thanks. now working on an implementation to allow global activation of zerotier service.

**Comment by dch** [comment]
I'm the freebsd zerotier port maintainer, let me know if I can help out here. Also, it might be time to move my firewall over to opnsense to take advantage of this new package.

**Comment by fichtner** [comment]
@dch Hi Dave, it might have just been a misconception, sorry for the trouble! zerotier-one isn't started yet so zerotier-cli complains (rightfully) about /var/db/zerotier-one not being ready.

Thanks,
Franco

**Comment by dharrigan** [comment]
Hi,

That's very kind of you thank you. I'm presently working on fixing this issue (making the code better), but I'll be happy to reach out @dch if (when!) I need some assistance! :-) So far, zerotier on FreeBSD works amazingly well - been using it for quite a while, on bare metal and within Jails without issue :-)

-=david=-

**Comment by dharrigan** [comment]
@fichtner Hi, yes, part of my code cleanup is to only do zerotier-cli stuff when the zerotier-one service is running. Still cleaning things up.

-=david=-

**Comment by dharrigan** [comment]
@obrienmd hi - would you like to help me test the updated plugin out-of-band? Ping me on IRC if interested :)

**Comment by obrienmd** [comment]
Sure! Pinging...

**Comment by dharrigan** [comment]
I think this can be closed now. @obrienmd reach out to me on irc to talk about this if you need to :)

**Comment by obrienmd** [comment]
Agreed, looking forward to the new version hitting repo!
