### ISSUE TITLE
security/acme-client Error re-issuing certificate DNS nsupdate method 

### ISSUE THREAD

**Issue by shdwshinobi** [opnsense/plugins#2479]
Using the letsencrypt web GUI, I am unable to re-issue a certicate. I am using the DNS nsupdate method to update a TXT record. The webgui instantly returns 'validation failed'. It appears that something is not set right for the challenge, as the acme.sh client will get the value it needs to add the TXT record, but the client does not even attempt to send any network traffic to the DNS server to update it. 

I have verified the nsupdate key is correct. The configuration I'm using was working for a year before April 2021 (as that's when my last certificate was issued).

I have manually run the acme.sh client via root on ssh, and setting the proper variables using setenv, it is able to properly issue a certificate.

**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[-] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[-] I have searched the existing issues and I'm convinced that mine is new.

[-] The title contains the plugin to which this issue belongs

**Describe the bug**
A clear and concise description of what the bug is, including last known working version (if any).

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Relevant log files**
If applicable, information from log files supporting your claim.

**Additional context**

**Environment**
Software version used and hardware type if relevant.
e.g.:

OPNsense 21.1.8_1-amd64

**Comment by fraenki** [comment]
Please go to `Services: Let's Encrypt: Settings` and set `Log Level` to `debug`, then click the `Apply` button.

Next time the renewal fails, go to `Services: Let's Encrypt: Log Files` and provide the full logs for both `System log` and `Acme log` (feel free to cloak sensitive information).

**Comment by shdwshinobi** [comment]
I'm unable to reproduce it anymore and it seems to work now.
