### ISSUE TITLE
Standardize Wireguard plugin labeling to match official WG nomenclature.

### ISSUE THREAD

**Issue by Bubbgump209** [opnsense/plugins#2483]
The labeling in the Wireguard plugin does not follow the standard WG nomenclature. For instance, within WG [Interface] and [Peer] are the basic parts of a configuration file. However, the WG plugin uses the terms Local and Endpoint respectively. I find this confusing and I have seen others in forums get confused as well. There are other similar minor issues in the help that could use some love too. This appears to be an easy fix I could contribute, but I didn't want to go down this road if the maintainers don't see value in such consistency or have other reasons to use the nomenclature that exists. Just looking for a +1 thumbs up before digging in.

**Comment by mimugmail** [comment]
Hm, sounds like a bigger change but it sounds reasonable. Would you also update all the docs (which is way more work than plugin code)?

**Comment by Bubbgump209** [comment]
I hadn’t considered it, but that makes perfect sense. For sure assuming docs are a simple pull request too.
