### ISSUE TITLE
net/haproxy: Maintenance page not loading in 21.7

### ISSUE THREAD

**Issue by mnaiman** [opnsense/plugins#2485]
Important notices
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

[X] The title contains the plugin to which this issue belongs

Describe the bug
Nothing is displayed in Maintenance - Servers

During debugging find out that  https://opnsense/api/haproxy/maintenance/searchServer is returning nothing (0 bytes)

And console log this error (empty json)
![image](https://user-images.githubusercontent.com/2264442/127699726-db6eb494-8c0b-459a-9162-a3b2e04dac71.png)

To Reproduce
Started 2 frontends and 4 backends.

Expected behavior
Correct data will be displayed

Screenshots
![image](https://user-images.githubusercontent.com/2264442/127699449-b7f41e7b-f148-4d74-ba57-89c373c295e6.png)

Relevant log files
NA

Additional context
NA

Environment
OPNsense 21.7

**Comment by fraenki** [comment]
Please and again and check `System: Log Files: Backend` as well as `System: Log Files: General` for error messages. If there are none, please also check if `/tmp/PHP_errors.log` exists.

**Comment by mnaiman** [comment]
There are no errors even file PHP_errors.log doesnt exists.
I found out in code, that API calls this python script, but cant figure out parameters to replicate on console.
/usr/local/opnsense/scripts/OPNsense/HAProxy/socketCommand.py show-servers

**Comment by walbroehl** [comment]
System=>Log Files => Backend:
`[fd4978da-13bb-4ff5-8876-c70b6cb611ee] Script action failed with Command '/usr/local/opnsense/scripts/OPNsense/HAProxy/socketCommand.py show-servers --output bootstrap --page-rows '10' --page '1' --search '' --sort-col '' --sort-dir ''' returned non-zero exit status 1. at Traceback (most recent call last): File "/usr/local/opnsense/service/modules/processhandler.py", line 478, in execute subprocess.check_call(script_command, env=self.config_environment, shell=True, File "/usr/local/lib/python3.8/subprocess.py", line 364, in check_call raise CalledProcessError(retcode, cmd) subprocess.CalledProcessError: Command '/usr/local/opnsense/scripts/OPNsense/HAProxy/socketCommand.py show-servers --output bootstrap --page-rows '10' --page '1' --search '' --sort-col '' --sort-dir ''' returned non-zero exit status 1.`

**Comment by walbroehl** [comment]
"/usr/local/opnsense/scripts/OPNsense/HAProxy/socketCommand.py show-servers" returns the results to shell

**Comment by walbroehl** [comment]
error persists in 21.7.1 ...

(╯°□°)╯︵ ┻━┻

**Comment by kulikov-a** [comment]
for "TypeError: 'Namespace' object is not subscriptable" it looks like typo in
https://github.com/opnsense/plugins/blob/c149e55aa691768206a08b49229d174051b9f858/net/haproxy/src/opnsense/scripts/OPNsense/HAProxy/socketCommand.py#L155-L159
imho it should be
`args.debug`

for `'dict' object has no attribute 'move_to_end'` (if its really need to move the id to the first place?)
imho need to `import collections` and convert `row = collections.OrderedDict(row)` at
https://github.com/opnsense/plugins/blob/c149e55aa691768206a08b49229d174051b9f858/net/haproxy/src/opnsense/scripts/OPNsense/HAProxy/lib/haproxy/cmds.py#L319-L321
?

**Comment by fraenki** [comment]
#2496 contains a first attempt to fix this, another PR will follow

**Comment by fraenki** [comment]
This will be fixed in the upcoming release 3.5 of os-haproxy.
