### ISSUE TITLE
FRR7 : add MULTIPATH option on the package.

### ISSUE THREAD

**Issue by xbeaudouin** [opnsense/plugins#2491]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[-] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[-] I have searched the existing issues and I'm convinced that mine is new.

[-] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
I have several WAN on my OPNsense. I use currently a cisco with OSPF(v3) and maxium-path X.
Which is ECMP.

On the FreeBSD port :  https://www.freshports.org/net/frr7/, option MULTIPATH is off per default.
Enabling it, enable the option inside the frr7.

**Describe the solution you'd like**

Set MULTIPATH=ON when compiling frr7.

**Describe alternatives you've considered**

No alternative except using another hardware.

**Additional context**

n/a

**Comment by mimugmail** [comment]
Beginning with 22.1

https://github.com/opnsense/tools/pull/185
