### ISSUE TITLE
DNScrypt-Proxy logs

### ISSUE THREAD

**Issue by likeahoss** [opnsense/plugins#2498]
Just updated to the following OPNsense version and Logs aren't being generated.

OPNsense 21.1.9_1-amd64

os-dnscrypt-proxy (installed) | 1.8_1

**Comment by fichtner** [comment]
It's fixed in 21.7.1, but if you need to stay on the end of life version 21.1.9 then:

    # pkg add -f https://pkg.opnsense.org/FreeBSD:12:amd64/21.7/MINT/21.7.1/OpenSSL/All/os-dnscrypt-proxy-1.9.txz


Cheers,
Franco
