### ISSUE TITLE
Telegraf plugin error using unbound input

### ISSUE THREAD

**Issue by andrema2** [opnsense/plugins#2499]
With the implementation of Telegraf 1.19.0 on 21.1 and 21.7 families of OPNSense the use of unbound as an input generates the following error:

E!  [inputs.unbound] Error in plugin: error gathering metrics: error  running unbound-control: exit status 1 (/usr/local/sbin/unbound-control  [-c /var/unbound/unbound.conf stats_noreset])

What I've tried so far:
- Use the patch provided by mimugmail that was included on 21.7.1 - same error. On a thread with him on the forum he mention also that the patch sometimes doesn't work with him too.
-  I've added the telegraf user to the groups, wheel, unbound and admins. It didn't change the result
- I've tried to change the path of the unbound.conf the message just change the location of it, but not the result
- Many versions behind I faced the same problem this is how I solved the same error back then : 

rm /usr/local/etc/unbound/unbound.conf
ln -s /var/unbound/unbound.conf /usr/local/etc/unbound/unbound.conf
/usr/sbin/pw groupmod unbound -m telegraf

As it is if I ssh to OPNSense and in the shell i run /usr/local/bin/telegraf --config /usr/local/etc/telegraf.conf --test --input-filter unbound .  It does work. Looks like when the process runs in the background it is not using the right user or not recognizing its permissions/groups

**Describe the solution you'd like**
The solution Mimugmail created, although not working now, it's more professional. It's a option at the input page and a option to run telegraf as part of wheel group, which I think is necessary.

I'm available if more details or tests are needed

Just as information the output is influxdb, but I don't think the issue is there. If I don't use the input unboud it does work.

**Comment by mimugmail** [comment]
After my vacation I will have a look

**Comment by psychogun** [comment]
Having the same issue. Are you still on vacation, @mimugmail? :)
```
E! [inputs.unbound] Error in plugin: error gathering metrics: error running unbound-control: command timed out (/usr/local/sbin/unbound-control [-c /var/unbound/unbound.conf stats_noreset])
```
I am running:
* OPNsense 21.7.7-amd64
* os-telegraf  1.12.3 (Telegraf 1.20.4)

This is the running paramameter;
```
telegraf 76777   0.0  1.2  5062176   95176  -  S    19:13       0:01.54 /usr/local/bin/telegraf --quiet --config=/usr/local/etc/telegraf.conf --config-directory=/usr/local/etc/telegraf.d
```

Checking 'Run as root' indeeds make `telegraf` run as root:

```
root    41679   1.6  1.1  5061428   89440  -  S    19:15       0:00.36 /usr/local/bin/telegraf --quiet --config=/usr/local/etc/telegraf.conf --config-directory=/usr/local/etc/telegraf.d
```
So I do not think it is a user permission thingie. 


Running the command manually:
```
root@opnsense:~ # /usr/local/sbin/unbound-control -c /var/unbound/unbound.conf stats_noreset
thread0.num.queries=134861
thread0.num.queries_ip_ratelimited=0
thread0.num.cachehits=54032
(...)
```

Running the command as given in the log file presents me with the same error message, "timeout":
```
root@opnsense:~ # /usr/local/sbin/unbound-control [-c /var/unbound/unbound.conf stats_noreset]
[1640716178] unbound-control[29703:0] warning: control-enable is 'no' in the config file.

[1640716183] unbound-control[29703:0] fatal error: timeout: could not connect to server
```

However, trying
```
service telegraf stop
```
... and editing
```
vi /usr/local/etc/telegraf.conf

#   config_file = "/var/unbound/unbound.conf"
```
Which makes `[[inputs.unbound]]` use the default configuration file `"/etc/unbound/unbound.conf"`, which I create a symbolic link to `/var/unbound/unbound.conf` (loosely based on https://forum.netgate.com/topic/152082/help-getting-unbound-grafana-dashboard-working/15)
```
mkdir /etc/unbound
ln -s /var/unbound/unbound.conf /etc/unbound/unbound.conf
```
yields basically the same error message - `E! [inputs.unbound] Error in plugin: error gathering metrics: error running unbound-control: command timed out (/usr/local/sbin/unbound-control [stats_noreset])`

Reading through https://github.com/influxdata/telegraf/tree/master/plugins/inputs/unbound, which defaults to `server = "127.0.0.1:8953"` and comparing with `/var/unbound/unbound.conf` - 

```
remote-control:
    control-enable: yes
    control-interface: 127.0.0.1
    control-port: 953
```

I added `server = "127.0.0.1:953` in `telegraf.conf` under `[[inputs.unbound]]`, and I got these error messages:

```
E! [inputs.unbound] Error in plugin: error gathering metrics: error running unbound-control: command timed out (/usr/local/sbin/unbound-control [-c /var/unbound/unbound.conf -s 127.0.0.1@953 stats_noreset])
```

This was with the `config_file` parameter **not** hashed out. 

So, `service telegraf stop`, `vi /usr/local/etc/telegraf.conf`
```
[[inputs.unbound]]
   server = "127.0.0.1:953"
   binary = "/usr/local/sbin/unbound-control"
  # config_file = "/var/unbound/unbound.conf"
   thread_as_tag = true
```

`service telegraf start`. This is with `Run as root` enabled. I have not received any error messages in the log, yet.

I will wait and see if anything populates in InfluxDBv2, but maybe this troubleshooting will help others come up with a better answer?

**Comment by psychogun** [comment]
Some more fiddling around:

```
service stop telegraf
```

With default configuration settings in `/usr/local/etc/telegraf.conf`:
```
[[inputs.unbound]]
   binary = "/usr/local/sbin/unbound-control"
   config_file = "/var/unbound/unbound.conf"
   thread_as_tag = true
```

```
root@opnsense:~ # telegraf --config=/usr/local/etc/telegraf.conf --test --input-filter unbound
2021-12-28T22:21:56Z I! Starting Telegraf 1.20.4
2021-12-28T22:21:56Z D! [agent] Initializing plugins
2021-12-28T22:21:56Z D! [agent] Starting service inputs
2021-12-28T22:21:57Z E! [inputs.unbound] Error in plugin: error gathering metrics: error running unbound-control: command timed out (/usr/local/sbin/unbound-control [-c /var/unbound/unbound.conf stats_noreset])
2021-12-28T22:21:57Z D! [agent] Stopping service inputs
2021-12-28T22:21:57Z D! [agent] Input channel closed
2021-12-28T22:21:57Z D! [agent] Stopped Successfully
2021-12-28T22:21:57Z E! [telegraf] Error running agent: input plugins recorded 1 errors
```

Removing the `config_file`, which makes `[[inputs.unbound]]` use the default configuration path `/etc/unbound/unbound.conf` (which I have symlinked; 
```ls -l /etc/unbound/unbound.conf 
lrwxr-xr-x  1 root  wheel  25 Dec 28 20:18 /etc/unbound/unbound.conf -> /var/unbound/unbound.conf
```
```
[[inputs.unbound]]
   binary = "/usr/local/sbin/unbound-control"
#   config_file = "/var/unbound/unbound.conf"
   thread_as_tag = true
```

```
root@opnsense~ # telegraf --config=/usr/local/etc/telegraf.conf --test --input-filter unbound
2021-12-28T22:28:31Z I! Starting Telegraf 1.20.4
2021-12-28T22:28:31Z D! [agent] Initializing plugins
2021-12-28T22:28:31Z D! [agent] Starting service inputs
2021-12-28T22:28:32Z E! [inputs.unbound] Error in plugin: error gathering metrics: error running unbound-control: command timed out (/usr/local/sbin/unbound-control [stats_noreset])
2021-12-28T22:28:32Z D! [agent] Stopping service inputs
2021-12-28T22:28:32Z D! [agent] Input channel closed
2021-12-28T22:28:32Z D! [agent] Stopped Successfully
2021-12-28T22:28:32Z E! [telegraf] Error running agent: input plugins recorded 1 errors
```


With the server defined **AND** the default `config_file`:
```
[[inputs.unbound]]
   server = "127.0.0.1:953"
   binary = "/usr/local/sbin/unbound-control"
   config_file = "/var/unbound/unbound.conf"
   thread_as_tag = true
```

```
root@hopnsense:~ # telegraf --config=/usr/local/etc/telegraf.conf --test --input-filter unbound
2021-12-28T22:22:49Z I! Starting Telegraf 1.20.4
2021-12-28T22:22:49Z D! [agent] Initializing plugins
2021-12-28T22:22:49Z D! [agent] Starting service inputs
2021-12-28T22:22:50Z E! [inputs.unbound] Error in plugin: error gathering metrics: error running unbound-control: command timed out (/usr/local/sbin/unbound-control [-c /var/unbound/unbound.conf -s 127.0.0.1@953 stats_noreset])
2021-12-28T22:22:50Z D! [agent] Stopping service inputs
2021-12-28T22:22:50Z D! [agent] Input channel closed
2021-12-28T22:22:50Z D! [agent] Stopped Successfully
2021-12-28T22:22:50Z E! [telegraf] Error running agent: input plugins recorded 1 errors
```

What seems to work is using the symlink, plus `server` parameter:

```
[[inputs.unbound]]
   server = "127.0.0.1:953"
   binary = "/usr/local/sbin/unbound-control"
#   config_file = "/var/unbound/unbound.conf"
   thread_as_tag = true
```

```
root@opnsense:~ # telegraf --config=/usr/local/etc/telegraf.conf --test --input-filter unbound
2021-12-28T22:31:22Z I! Starting Telegraf 1.20.4
2021-12-28T22:31:22Z D! [agent] Initializing plugins
2021-12-28T22:31:22Z D! [agent] Starting service inputs
2021-12-28T22:31:22Z D! [agent] Stopping service inputs
2021-12-28T22:31:22Z D! [agent] Input channel closed
2021-12-28T22:31:22Z D! [agent] Stopped Successfully
```

**Comment by psychogun** [comment]
HAH!

Forget all my ramblings. Just increase the default timeout value! 

`service telegraf stop`

Edit `/usr/local/etc/telegraf.conf` (on the very bottom):
```
[[inputs.unbound]]
   binary = "/usr/local/sbin/unbound-control"
   config_file = "/var/unbound/unbound.conf"
   thread_as_tag = true
   timeout = "5s"
```

This is what a correct test looks like:
```
root@opnsense:~ # telegraf --config=/usr/local/etc/telegraf.conf --test --input-filter unbound
2021-12-28T22:51:18Z I! Starting Telegraf 1.20.4
2021-12-28T22:51:18Z D! [agent] Initializing plugins
2021-12-28T22:51:18Z D! [agent] Starting service inputs
> unbound,host=opnsense.home.arpa time_elapsed=1113293.657265,time_now=1640731881.345097,time_up=1113293.657265,total_num_cachehits=218622,total_num_cachemiss=332283,total_num_expired=0,total_num_prefetch=0,total_num_queries=550905,total_num_queries_ip_ratelimited=0,total_num_recursivereplies=332283,total_recursion_time_avg=0.197237,total_recursion_time_median=0.0448509,total_requestlist_avg=0.443315,total_requestlist_current_all=0,total_requestlist_current_user=0,total_requestlist_exceeded=0,total_requestlist_max=32,total_requestlist_overwritten=0,total_tcpusage=0 1640731882000000000
> unbound_threads,host=opnsense.home.arpa,thread=2 num_cachehits=53787,num_cachemiss=83871,num_expired=0,num_prefetch=0,num_queries=137658,num_queries_ip_ratelimited=0,num_recursivereplies=83871,recursion_time_avg=0.187966,recursion_time_median=0.04534,requestlist_avg=0.439639,requestlist_current_all=0,requestlist_current_user=0,requestlist_exceeded=0,requestlist_max=32,requestlist_overwritten=0,tcpusage=0 1640731882000000000
2021-12-28T22:51:21Z D! [agent] Stopping service inputs
> unbound_threads,host=opnsense.home.arpa,thread=3 num_cachehits=55640,num_cachemiss=82107,num_expired=0,num_prefetch=0,num_queries=137747,num_queries_ip_ratelimited=0,num_recursivereplies=82107,recursion_time_avg=0.212176,recursion_time_median=0.0444528,requestlist_avg=0.451837,requestlist_current_all=0,requestlist_current_user=0,requestlist_exceeded=0,requestlist_max=29,requestlist_overwritten=0,tcpusage=0 1640731882000000000
2021-12-28T22:51:21Z D! [agent] Input channel closed
> unbound_threads,host=opnsense.home.arpa,thread=0 num_cachehits=55568,num_cachemiss=83182,num_expired=0,num_prefetch=0,num_queries=138750,num_queries_ip_ratelimited=0,num_recursivereplies=83182,recursion_time_avg=0.205558,recursion_time_median=0.0451246,requestlist_avg=0.44179,requestlist_current_all=0,requestlist_current_user=0,requestlist_exceeded=0,requestlist_max=21,requestlist_overwritten=0,tcpusage=0 1640731882000000000
2021-12-28T22:51:21Z D! [agent] Stopped Successfully
> unbound_threads,host=opnsense.home.arpa,thread=1 num_cachehits=53627,num_cachemiss=83123,num_expired=0,num_prefetch=0,num_queries=136750,num_queries_ip_ratelimited=0,num_recursivereplies=83123,recursion_time_avg=0.18351,recursion_time_median=0.0444862,requestlist_avg=0.440131,requestlist_current_all=0,requestlist_current_user=0,requestlist_exceeded=0,requestlist_max=24,requestlist_overwritten=0,tcpusage=0 1640731882000000000
```

Then start `telegraf`: `service telegraf start`.

Atleast in my case this provided me with metrics in InfluxDBv2. Did not bother with trying different timeout values, as `5s` worked on the first try.

**Comment by mimugmail** [comment]
Doesn't really makes sense since your command only tooks 3ms to start and stop. 
What happens when you use 2s?

**Comment by psychogun** [comment]
That might be. Anyways, it worked :)

Using `#`, `1s`, `2s` gives me `[inputs.unbound] Error in plugin: error gathering metrics: error running unbound-control: command timed out (/usr/local/sbin/unbound-control [-c /var/unbound/unbound.conf stats_noreset])`.

Only first at `3s` does the command `telegraf --config=/usr/local/etc/telegraf.conf --test --input-filter unbound` give me the output shown above.

**Comment by psychogun** [comment]
And now I think I have another request. But I would like to have some feedback from @andrema2 if setting the `timeout` also fixes the problem for him as well. 

Anyways, looking over at https://github.com/influxdata/telegraf/tree/master/plugins/inputs/unbound; 

> Histogram related statistics will never be collected, extended statistics can also be imported ("extended-statistics: yes" in unbound configuration).

I do not receive any metrics such as `num_query_type_PTR, num_query_type_TXT, num_query_type_AAAA (...)`. This is because `extended-statistics` is set to `no` in `unbound.conf` (??)

```
root@opnsense:~ # cat /var/unbound/unbound.conf | grep extended
extended-statistics: no
```

How can I change this value to `yes` to figure out if this is the case? Whenever I try to change it to `yes`, and restart Unbound with `/usr/local/sbin/pluginctl dns`, the value is reverted back to `no`.

**Comment by psychogun** [comment]
Looks like `timeout = "3s"` produces sometimes (?) connection timeouts in the Telegraf log. 

These errors are inconsistent in regards to timestamp (coming and going). 
`E! [inputs.unbound] Error in plugin: error gathering metrics: error running unbound-control: command timed out (/usr/local/sbin/unbound-control [-c /var/unbound/unbound.conf stats_noreset])`

I also saw these errors in the Unbound log:
`unbound[84543] | [84543:0] error: remote control failed ssl crypto error:00000000:lib(0):func(0):reason(0)`, but they do not correspond with errors in the Telegraf log. Do not know yet what produces these. 

Having it back to `5s` now and then I'll see.

And to answer my own question; setting `extended-statistics: yes` in `/var/unbound/unbound.conf` - and then reloading the new configuration which can be done with `/usr/local/sbin/unbound-control -c /var/unbound/unbound.conf reload`, gives a lot more metrics in InfluxDBv2.

So theres that. Please anyone else confirm :)

**Comment by agh1467** [comment]
> How can I change this value to yes to figure out if this is the case? Whenever I try to change it to yes, and restart Unbound with /usr/local/sbin/pluginctl dns, the value is reverted back to no.

@psychogun I believe the `extended-statistics` setting is controlled via Services -> Unbound DNS -> Advanced -> Extended statistics setting. Checking it there should set "yes" in the config when you restart via the UI.

**Comment by psychogun** [comment]
@agh1467 ah, of course, thank you!
