### ISSUE TITLE
HAproxy server does not respect SSL

### ISSUE THREAD

**Issue by jpawlowski** [opnsense/plugins#25]
Using the latest version 16.7, the HAproxy plugin does not respect SSL for servers.
Even though the SSL option was enabled, the resulting haproxy.conf file misses the addition "ssl" at the end of the server entry.

**Comment by fraenki** [comment]
@jpawlowski Thanks for your report(s)! I'll look into this.

**Comment by fraenki** [comment]
@jpawlowski: Thanks for all the time you've put into the reports, much appreciated! I've added fixes for this and most other issues. Please report back if there are still issues.
