### ISSUE TITLE
net/zerotier: how-to documentation

### ISSUE THREAD

**Issue by fichtner** [opnsense/plugins#250]
Continuation / conclusion of #239

**Comment by fabianfrz** [comment]
@fichtner this may require access to the `opnsense_docs` repository, where @dharrigan may not have access to.

**Comment by fabianfrz** [comment]
@fichtner Seems to be done: https://docs.opnsense.org/manual/how-tos/zerotier.html
close?

**Comment by dharrigan** [comment]
hi,

yes please 😁

-=david=-

**Comment by Tennyleaz** [comment]
The documentation for adding zerotier interface seems a bit outdated?
It says:

```
For IPv4 Configuration Type, choose Static IPv4 then in the appropriate input boxes, 
key in the IPv4 address that you have assigned to this node via the Zerotier portal. 
Keep the IPv4 Upstream Gateway set to None.
```

But there is no `None` option in `IPv4 Upstream Gateway` when creating zerotier interface.
