### ISSUE TITLE
support setting the tftpd serving directory for os-tftp

### ISSUE THREAD

**Issue by razamatan** [opnsense/plugins#2501]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

[x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
I would like to specify what path to set as my tftpd root.  Right now, it's defaulted to `/usr/local/tftp`

**Describe the solution you'd like**
https://github.com/opnsense/plugins/blob/ef88595e0cc60b89d24ac93a24462af44265a02b/ftp/tftp/src/opnsense/service/templates/OPNsense/Tftp/tftpd#L3

it'd be nice to be able to specify the directory to serve via a setting text box.  fine to default it to `/usr/local/tftp`.

**Describe alternatives you've considered**
`ln -sf /path/i/want/to/serve /usr/local/tftp`

**Additional context**
n/a

**Comment by razamatan** [comment]
:(

**Comment by zackdotgomez** [comment]
I would like to see this issue reopened. This functionality could have saved me time troubleshooting #5510 and I see it as generally useful/desirable. Thanks!
