### ISSUE TITLE
[WireGuard] Multiple peers not showing up in configuration/handshakes

### ISSUE THREAD

**Issue by dkrutsko** [opnsense/plugins#2503]
**Describe the bug**
I have two WireGuard servers I want to add, both are created with [Algo](https://github.com/trailofbits/algo) and hosted on their own cloud servers. They don't have anything in common, so unique addresses and keys. When I create Local and Endpoint entries for each and enable WireGuard, it only ever lists the first one in List configuration and Handshakes. I expect to see both of them connected with their own interface (i.e. wg0 and wg1).

**Screenshots**
![image](https://user-images.githubusercontent.com/3094700/129685359-33c37f20-1060-4069-af61-b361c9a52918.png)

**Environment**
os-wireguard 1.7
OPNsense 21.7.1-amd64
FreeBSD 12.1-RELEASE-p19-HBSD
OpenSSL 1.1.1k 25 Mar 2021
Intel(R) Xeon(R) D-2146NT CPU @ 2.30GHz (16 cores)

**Comment by chudsaviet** [comment]
Good bot.
I also have this bug. Will try to create using one of their templates.

**Comment by psychogun** [comment]
Have you checked the logs? Because I do not think your `vpn2` interface has even started; it should listen on a different port than `vpn1`.

* 51820
* 51821
