### ISSUE TITLE
net-mgmt/lldpd - IP/Port mismatch

### ISSUE THREAD

**Issue by Xeroxxx** [opnsense/plugins#2506]
**Describe the bug**

There is an issue with correct Management IP Address.

-I allows to ignore interfaces, however even ignored it grabs the first IP-Address it can find. In my case igb0, even if this is ignored. (-I igb*,!igb0).

However it displays correct PORT igb1 and correct MAC-ADDRESS but the IP-Address of igb0. This mismatches.

Currently I added this manually to my implementation with -m <IP of igb1>.

I'm not experienced enough to create a dropdown of all interfaces to choose from.

**To Reproduce**

1. Management of OPNSense and listening on igb1.
2. Have igb0 configured and link up.
2. Start lldpd
3. Management IP Address will be igb0.

**Expected behavior**

Allow to configure via dropdown of Mgmt-Interface and make resolution of ip-address. IP-Address should be added as -m parameter to lldpd.

**Screenshots**
CORRECT (port matches with ip-address via -m paramter): 
![image](https://user-images.githubusercontent.com/1109954/130057427-465a6629-a43f-46d1-bd6d-740e4ae6c389.png)

INCORRECT (port does not match with correct mgmt ip-address):
![image](https://user-images.githubusercontent.com/1109954/130057580-f03087a8-21b2-4a4b-b599-d0ca86b405f5.png)

**Comment by mimugmail** [comment]
I will test how to implement best in a few weeks

**Comment by Xeroxxx** [comment]
Thank you, if you need further information or documentation let me know or if anything is unclear.

**Comment by SeimusS** [comment]
Hello,

I know this was closed. But will this be maybe fixed in any future? I can see the same behavior.

Regards,
S.

**Comment by fichtner** [comment]
I'll happily review and merge patches, but seeing the last to this plugin update was in 2021 I don't think there is a lot of interest in continued development here.


Cheers,
Franco

**Comment by SeimusS** [comment]
Fair enough,

Thank you for the answer, I was curious if this is abandoned or just forgotten.

Regards,
S.
