### ISSUE TITLE
[os-wireguard] Only first WireGuard peer (endpoint) appears in the WireGuard config

### ISSUE THREAD

**Issue by chudsaviet** [opnsense/plugins#2507]
**Description**
If we have more that one peer (endpoint) configuration, only the first one appears in the WireGuard config file.
Therefore, other peers cannot connect.
Related to https://github.com/opnsense/plugins/issues/2503 .

**To Reproduce**
1. Go to VPN -> WireGuard.
2. Make sure there is `Local` configuration set.
3. Add two peers (endpoints) configurations.
4. Restart `wireguard-go` service.
5. Either:
    a. Go to VPN -> WireGuard -> `List Configuration` tab.
    b. In command line, see `/usr/local/etc/wireguard/wg0.conf` file.
6. You shall see that only the first peer configuration exists.

**Expected behavior**
All peers are listed in the WireGuard config.
All peers can connect.

**Screenshots**
<img width="955" alt="Screen Shot 2021-08-19 at 3 19 33 PM" src="https://user-images.githubusercontent.com/4819157/130152217-c12af79b-6357-4c9c-81fd-daf7c2fe3631.png">
<img width="1313" alt="Screen Shot 2021-08-19 at 3 20 28 PM" src="https://user-images.githubusercontent.com/4819157/130152218-ea165bb6-1e87-42af-b80a-9c018b931624.png">

**Relevant log files**
`/usr/local/etc/wireguard/wg0.conf` file:
```
[Interface]
PrivateKey = <>
Address = <>
ListenPort = <>

[Peer]
PublicKey = <>
AllowedIPs = <>
```

**Environment**
OPNSense version: 
```
OPNsense 21.7.1-amd64
FreeBSD 12.1-RELEASE-p19-HBSD
LibreSSL 3.3.3
```
First appeared at `os-wireguard` version `1.7`
GUI page: https://[opnsense]/ui/wireguard/general/index , tabs `Endpoints` and `List Configuration`.

**Comment by chudsaviet** [comment]
Possibly related to https://github.com/opnsense/plugins/blob/master/net/wireguard/src/opnsense/service/templates/OPNsense/Wireguard/wireguard-server.conf template.

**Comment by mimugmail** [comment]
I will have a look in a few weeks

**Comment by chudsaviet** [comment]
I'm closing this issue - I have found that I haven't associated new peers with instance on 'local' tab.
However, this association is unintuitive, and it would be great to make UI more intuitive.
Thank you anyway guys!
