### ISSUE TITLE
net/zerotier: issues under high load

### ISSUE THREAD

**Issue by obrienmd** [opnsense/plugins#251]
More ZT observations from testing, sorry for the deluge!

With ZT used as a VPN connection between 3 OPNSense routers (OSPF used between them to manage routes to LANs), when I push a large amount of data between two of the routers, connections of all types will start to fail between them or devices behind their LANs to devices on a 'far' LAN.

Wehn I try to ping between the 2 routers involved, I get `ping: sendto: No buffer space available`. 

Pings, and other data transfers, between either of the 'failing' routers or devices on their LANS, and the 1 that was not involved in the large transfer, or devices on its LAN, work great.

Everything is healthy again after about 30 seconds. I have tried to replicate this between non-OPNSense devices (a few linux boxes, my Windows laptop) on the same Zerotier issue, but haven't been able to cause the issue. I have not tried it between vanilla FreeBSD 11 boxes.

**Comment by fichtner** [comment]
Could be an issue with network buffer depletion. What is your MBUF Usage from the system info widget when you observe this?

> kern.ipc.nmbclusters - loader tunable and read/write sysctl, global limit for number of mbuf clusters in the system; packet drops happen when this value is reached.

from: https://wiki.freebsd.org/NetworkPerformanceTuning

**Comment by obrienmd** [comment]
MBUF usage is minimal - 1520/125446.

I don't know much about ZT interfaces, but the same traffic ran over an IPSec tunnel without problems, so perhaps it has something to do with how ZT interfaces handle buffers / queues?

**Comment by obrienmd** [comment]
For the last few hours, my go-to tool to trigger this has been iperf3 - I originally saw it when Hyper-V replication was kicking in (big traffic tunneled over HTTPS), but needed something more reproducible.

I can trigger this at will with an iperf3 run either between a firewall or host on one side, and a firewall or host on the other side of the tunnel, as long as I'm targeting a LAN IP as the iperf3 server. Traffic drops to 0 then I get a failure message (there have been a few different types).

Strangely, when I run iperf3 from one firewall, targeting the other firewall's ZT IP address (i.e. the iperf3 connection doesn't take any layer3 hops, if you see ZT as a "virtual switch"), I can't seem to simulate the failure.

Any pointers on debug logs or sysctl/other items to watch? If this were a buffer issue I'd just expect packet drops and TCP back-off (as I'm using iperf3 in TCP mode) - this looks different to me than any connection I've seen that just can't buffer enough, but I'm admittedly not a deep nets guru :)

**Comment by obrienmd** [comment]
@dharrigan @dch Thought you folks might be interested given the other thread(s).

I'm a bit lost as to where to start debugging - didn't have the issue over IPSec so I'd love to dig into the Zerotier interface, but I'm not sure how to get it to log verbose data / where to look for errors / counters / etc.

**Comment by dharrigan** [comment]
Hi,

Unfortunately zerotier doesn't come with any debug or logging, see here: https://github.com/zerotier/ZeroTierOne/issues/377. I suppose the standard networking toolchain would help here (except of course if you want to examine the payload, since that is encrypted). I would ssh into your OPNsense box, then use tools like ifconfig, tcpdump, netstat etc., to perhaps help? I would also reach out to the Zerotier people directly at their community website and ask for assistance.

The plugin is a simple wrapper that installs, enables and configures basic functionality. How Zerotier works directly on the OS is specific to that application directly. 

Sorry I can't be of more help, but I don't think there is much I can do here.

-=david=-

**Comment by obrienmd** [comment]
Gotcha, thanks @dharrigan !

**Comment by dch** [comment]
@dharrigan I actually have a tweak to the port that enables debugging https://github.com/skunkwerks/ports/commit/e9582cd4 you need to run ZT in the foreground though to see it. I'd be interested in chattiing on IRC sometime if you are there. I'm in EU timezones.

**Comment by obrienmd** [comment]
@dch @dharrigan I'd be super interested in trying this port revision with my high-load use case. I have never built a port from source, but if you're planning to release a 1.2.4_1, I'd love to pull it in, or if there's a binary build I could deploy without you doing a full release, I'd be happy to try that!

**Comment by obrienmd** [comment]
@dharrigan @dch I did quite a bit of debugging this weekend, and I think I have the culprit. See details here:

https://github.com/zerotier/ZeroTierOne/issues/579

I'm not sure how to best approach this. A few ideas that may be terrible (I'm pretty beat):
1. Add all interfaces without default gateways (i.e. LAN networks) in their subnet to the blacklist by default.
2. Provide a UI for local.conf parameters, specifically in this case to blacklist interfaces against ZeroTier traffic.

I'm sure I'm missing all sorts of edge cases that the first option might hit... But perhaps there's some calculus, or even a check/uncheck option for it, that would let something like this work. The second one is probably a logical progression of this plugin, even if the first step is just allowing a local.conf to be defined in a text box.

**Comment by obrienmd** [comment]
... and I'm not sure it's the culprit. Certain it helps to resolve that issue, but when I'm routing traffic through the OPNSense tunnel, packet loss is FAR higher than when running the same tests (using iperf3) from one route client to another than from one ZT IP to another on OPNSense.

I'm out of ideas, and trying to generate new ones, but I'd really like to know - **has anyone had success with getting 20 - 100mbps traffic loads from clients through FreeBSD routers connected via ZeroTier, without high packet loss and/or TCP resets?**

**Comment by dharrigan** [comment]
@obrienmd 32e478ff45ec3448fe960bdfb6ab6e4416eca535 teaches Zerotier to allow for the use of a local.conf. Let me know how you get along!

-=david=-

**Comment by obrienmd** [comment]
@dharrigan Brilliant - works great for masking the networks, so ZT doesn't try to use them.

... but unfortunately the high load issue persists. Ugh :)

I'm going to try to find time to set up 2x vanilla FreeBSD 11 boxes with ZeroTier, and test using these as gateways for some of the traffic types I'm using (e.g. Hyper-V replication)... But would love some other test cases with high traffic load from other folks to sanity-check me.

**Comment by dharrigan** [comment]
@obrienmd can you ping me on irc to talk about this please

**Comment by obrienmd** [comment]
Per my chat with dharrigan on Github, I'm looking for sanity checks on the following scenarios. I'll keep filling this out as time goes on - my next test is linux clients behind the firewalls so I can see if the Windows client stack is freaking out for some reason.

**OPNSense router A - Zerotier over WAN - OPNSense router B**
obrienmd results over 60ms gigabit link with 2CPU E5 or equivalent / 4GB on each OPNSense host:
```
[OPNSense A] iperf3 -s -B {{OPNSense A LAN IP}}
[OPNSense B] iperf3 -P 10 -c -t 180 -c {{OPNSense A LAN IP}} -B {{OPNSense B LAN IP}}
BW 250mbps, 10k retries (seems reasonable for # of packets)

[OPNSense A] iperf3 -s -B {{OPNSense A LAN IP}}
[OPNSense B] iperf3 -u -b 50M -c {{OPNSense A LAN IP}} -B {{OPNSense B LAN IP}}
Jitter 0.034ms, packet loss 0.25% (seems reasonable)
```

**Windows Client A - LAN A - OPNSense router A - Zerotier over WAN - OPNSense router B - LAN B - Windows Client B**
obrienmd results over 60ms gigabit link with 2CPU E5 or equivalent / 4GB on each OPNSense host:
```
[Win Client A] iperf3 -s
[Win Client B] iperf3 -P 10 -c -t 180 -c {{Win Client B LAN IP}}
BW 30mbps, not sure of retries as Win client doesn't report
Seems FAR too low based on firewall to firewall, and Win clients are 
not CPU/net constrained in the least.

[Win Client A] iperf3 -s -B {{OPNSense A LAN IP}}
[Win Client B] iperf3 -u -b 50M -c {{OPNSense A LAN IP}} -B {{OPNSense B LAN IP}}
Jitter 0.018ms, packet loss 35.50%
Again, seems horrible based on the firewall to firewall results.
```

**Linux Client A - LAN A - OPNSense router A - Zerotier over WAN - OPNSense router B - LAN B - Linux Client B**
TESTS IN PROGRESS

**Comment by dharrigan** [comment]
Doing my own testing

All using Zerotier 1.2.4.

Linux A (ZT node) -> OPNsense -> Linux B (ZT Node)
Boxes are real hardware, not virtualised.

```
Linux A : iperf3 -t 180 -u -b 50M -c {{ZeroTier LAN IP B}} -B {{ZeroTier LAN IP A}}
Linux B : iperf3 -s -B {{ZeroTier LAN IP B}}

Results
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[  4]   0.00-180.00 sec  1.05 GBytes  50.0 Mbits/sec  5.641 ms  122792/137185 (90%)  
[  4] Sent 137185 datagrams
```

**Comment by obrienmd** [comment]
Did a bit more testing, swapping out the OPNSense gateways for Linux (Ubuntu 16.04.3) ones:
https://github.com/opnsense/plugins/issues/251#issuecomment-331971089

The testing implies that something happens when OPNSense is forwarding packets through a ZeroTier tunnel that makes it fall over, given:

1. OPNSense to OPNSense iperf through a Zerotier tunnel looks great
2. Win client to Win client routed via OPNSense through a site-site Zerotier tunnel looks terrible
3. Win client to Win client routed via Linux through a site-site Zerotier tunnel looks good

When OPNSense is choking, CPU isn't running that hot on the router, mbufs look great, etc... I've played around with MTU, but I'm at a loss for how to move forward.

**Comment by obrienmd** [comment]
Added a bit more test data - putting OPNSense as just a WAN gateway on each side (beyond the Linux routers) kill throughput again. So, it not even OPNSense directly forwarding packets via a Zerotier tunnel, it's OPNSense anywhere in the path.

To verify - Suricata is off, as are all other "fancy" firewall things. iPerf between hosts behind OPNSense generally (with Zerotier not involved) is great.

**Comment by obrienmd** [comment]
I'm not really getting anywhere. Today:

I traced syscalls on the OPNSense zerotier-one process (though it seems to be network layer per last few posts) and saw:
1. Tons of `gettimeofday` syscalls, I think one for each packet
2. Quite a bit of `zerotier-one RET   recvfrom -1 errno 35 Resource temporarily unavailable`

I thought OPNSense wasn't holding states for the firewall correctly, in that return traffic (9993/UDP back to an ephemeral port) was being blocked at the non-9993 side even though a state should have been opened from the originating "connection" (UDP, but a state should be opened anyway). I still think that's true, but opening up all src port 9993 traffic didn't really help timeouts / retransmissions / packet loss much.

I feel like I'm going in circles on this, and given it's a work (though side) project, I might have to fall off for a bit and fail back to OpenVPN or GRE/IPSec.

**Comment by dch** [comment]
@obrienmd @dharrigan I've had a chance in the last week to do some perf testing through native FreeBSD, and I don't see significant issues at my end. However, all my boxes are big with fat pipes etc and I have no OPNSense in between nor OSPF nor other routing goop anywhere. I can probably stick some stuff together if there are things you'd like tested. Rumour has it there's a zerotier release "soon" so it might be time to whip up a package using upstream's dev branch and see what we get out of it. The build system apparently has changed so I would need to fix that up first.

I'll ask privately wrt timing and documentation, especially for the promised debugging enhancements.

**Comment by fichtner** [comment]
Timeout on issue.
