### ISSUE TITLE
OSPF not working as expected

### ISSUE THREAD

**Issue by obrienmd** [opnsense/plugins#252]
I've taken a few hacks at getting OSPF working - reviewed:
https://github.com/opnsense/plugins/issues/170 (another OSPF issue, original reporter never provided feedback)
https://github.com/opnsense/plugins/issues/172 (raw config, which I may find useful in future)

Typically in an OSPF deployment (Cisco, pfSense, etc.), I'd configure the following:
- An interface for OSPF to broadcast on
- Networks to redistribute via OSPF (manually)

Here are my attempts thus far at doing this in the OPNSense UI:
- Set up interface for OSPF, networks for distribution, with all non-OSPF-involved interfaces set as passive. OSPF does not broadcast packets on the desired interface at all. Resulting config in diagnostics is: https://gist.github.com/obrienmd/1ff4f5b09435a2f5c5b7c43f53cdd7d6
- Set up interface for OSPF, network of OSPF interface (weird), 'Route Redistribution' of all 'Connected routes', with all non-OSPF-involved interfaces set as passive. Strangely, this gets OSPF working (I can see broadcast packets on the wire and neighbors are found). However, I can't get prefix filtering working right, and this is redistributing WAN interfaces, which causes all sorts of problems. Result config in diagnostics is: https://gist.github.com/obrienmd/c2a6080b1cbb2700384b0d8a7ca6ed54

I'd really like the first one to work, as it's how I see OSPF set up in most small net cases like ours, but I can't figure out where I'm going wrong. Any ideas?

**Comment by mimugmail** [comment]
Which commands do you use to redistribute manually like stated above?

**Comment by obrienmd** [comment]
Ah - I think you made me figure it out :) I should add to "networks" both the OSPF-using network _and_ the networks I want routed. I'm going to test today to verify, but reviewing the OSPFd.conf that pfSense generated made me think this is probably the case. Thanks for pushing me in the right direction :)

**Comment by mimugmail** [comment]
Great! Please come back with the results :)

**Comment by obrienmd** [comment]
Verified - good to go with both routing and "stub" networks defined. Thanks!
