### ISSUE TITLE
No logs about c-icap in GUI but there are in system

### ISSUE THREAD

**Issue by JulienDlq** [opnsense/plugins#2521]
**Describe the bug**
There is no log visible in GUI for plugin c-icap in its log section.
But if I ssh on my opnsense: 
```
% sudo ls -l /var/log/c-icap/
total 4672
-rw-r--r--  1 c_icap  c_icap  2225286 Sep  3 21:27 access.log
-rw-r--r--  1 c_icap  c_icap     8124 Aug 25 00:00 access.log.0.gz
-rw-r--r--  1 c_icap  c_icap    55567 Aug 23 00:00 access.log.1.gz
-rw-r--r--  1 c_icap  c_icap    15260 Aug  5 00:00 access.log.2.gz
-rw-r--r--  1 c_icap  c_icap    32844 Sep  3 21:22 server.log
-rw-r--r--  1 c_icap  c_icap     1210 Aug 25 00:00 server.log.0.gz
-rw-r--r--  1 c_icap  c_icap     2807 Aug 23 00:00 server.log.1.gz
-rw-r--r--  1 c_icap  c_icap     1167 Aug  5 00:00 server.log.2.gz
```
There is something!

**To Reproduce**
1. Go to Services/C-ICAP/logs on WebGUI (or something like that, mine is in French)
2. Nothing in logs

**Expected behavior**
Something in logs, since they exists in the system!

**Screenshots**
![Screenshot_20210903_213906](https://user-images.githubusercontent.com/18351090/132057929-22be19f4-bafb-4d9e-814c-5518eb9c0250.png)
![Screenshot_20210903_214033](https://user-images.githubusercontent.com/18351090/132058028-b6847dd7-8831-41af-843c-caf2ea27b8a8.png)

**Environment**
Software version used and hardware type if relevant.
e.g.:

OPNsense 21.7.1-amd64
FreeBSD 12.1-RELEASE-p19-HBSD
OpenSSL 1.1.1k 25 Mar 2021
Intel Core Processor (Skylake, IBRS) (4 cores)

**Comment by fichtner** [comment]
@JulienDlq @mimugmail I assume same issue as dnscrypt-proxy
