### ISSUE TITLE
os-fetchmail - File /usr/local/etc/fetchmailrc must  have no more than -rwx------ (0700) permissions - 

### ISSUE THREAD

**Issue by mr44er** [opnsense/plugins#2532]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

[X] The title contains the plugin to which this issue belongs

`

2021-09-12T17:04:40 | configd.py[41345] | [882a4bc5-f7c7-4326-93a0-1ee3dbc07184]  Script action stderr returned "b'File /usr/local/etc/fetchmailrc must  have no more than -rwx------ (0700) permissions.\nFile  /usr/local/etc/fetchmailrc must have no more than -rwx------ (0700)  permissions.'"
-- | -- | --

`

...but permissions are right:

`
-rwx------   1 fetchmail        fetchmail            155 Sep 12 17:04 fetchmailrc
-rw-------   1 fetchmail        fetchmail            107 Sep  6 04:28 fetchmailrc.sample
`

`poll imap.gmail.com protocol imap username "xxx@gmail.com" password "xxxpw" is xxx@mylocalpostfixdomain smtphost localhost`

![gmailsettingforpop3](https://user-images.githubusercontent.com/46787531/132993282-b064327f-26b4-4263-9f17-c85e287dfbe2.png)

Trying to use the plugin for the first time. No idea right now, no mails. :D
Same result with pop3 and ssl on/off

The postfix-plugin itself just works right. No difference when I target my second, internal postfix.

OPNsense 21.7.2_1-amd64
FreeBSD 12.1-RELEASE-p20-HBSD
LibreSSL 3.3.4

**Comment by mimugmail** [comment]
Can you switch to Openssl?

**Comment by mr44er** [comment]
I could maybe, but not easy hop over just to try. Other way round: this gmail-acc isn't really worth to switch.
It might be gmail to blame with the obscure security stuff, but it feels that the plugin just doesn't connect anywhere.

How can I let fetchmail be verbose or log to /var/log/fetchmail? GUI overwrites my settings and backend-log only tells me about the 700 permissions. :)

**Comment by mr44er** [comment]
I tried OpenSSL + reboot, no change.

SSL on/off:

`root@router0:~ # cat /usr/local/etc/fetchmailrc

set daemon 600
set syslog

poll imap.gmail.com protocol imap username "xxx@gmail.com" password "xxx" is xxx@mylocaldomain smtphost localhost  sslproto ''
root@router0:~ # sockstat | grep fetchmail
fetchmail fetchmail 27447 3  dgram  -> /var/run/log
fetchmail fetchmail 27447 4  tcp4   x.x.x.x:2866     173.194.76.109:143

####################################################

root@router0:~ # cat /usr/local/etc/fetchmailrc

set daemon 600
set syslog

poll imap.gmail.com protocol imap username "xxx@gmail.com" password "xxx" is xxx@mylocaldomain smtphost localhost 
root@router0:~ # sockstat | grep fetchmail
fetchmail fetchmail 95555 3  dgram  -> /var/run/log
fetchmail fetchmail 95555 4  tcp4   x.x.x.x:5811     142.250.110.108:143`

POP3 + SSL on/off tries to connect to port 110.

Gmail only accepts pop.gmail.com:995 and imap.gmail.com:993 with SSL. Trying to add the port in GUI explicit gives me "please specify a valid address (IPv4/IPv6) or hostname".
Now I wonder if "Use SSL" in GUI is only meant for target-server...?

Additionally I noticed that there are double spaces in /usr/local/etc/fetchmailrc between localhost and sslproto.
smtphost localhost<**here**>sslproto ''

**Comment by mr44er** [comment]
I found the solution, 'ssl' needs to be at the end.

Deactivated in GUI, made a new configfile 'fetchtest' with content:
`set daemon 600
set syslog

poll imap.gmail.com protocol imap username "xxx@gmail.com" password "xxx" is xxx@mylocaldomain smtphost localhost ssl`

Then
fetchmail -f /usr/local/etc/fetchtest
and tada, mails are floating in. :)
