### ISSUE TITLE
security/acme-client: BIND API not working? Can't get txt entry

### ISSUE THREAD

**Issue by superwinni2** [opnsense/plugins#2535]
**Important notices**
[-] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
Yes
[-] I have searched the existing issues and I'm convinced that mine is new.
Yes
[-] The title contains the plugin to which this issue belongs
Yes
**Describe the bug**
I want to do the ACME Challenge with my local BIND Server running on OpnSense.
BIND is running and answering to external. ALIAS Settings are made on domain names.
I've already certified some requests with this method. But now it doesn't work anymore.

API with the user and curl is working.

Domain to verify; domain.de
Bind Server hears to: home.domain.de

If I read the log right the User can't access the BIND API.

Can anybody verify please if this is a real problem or if I'm just to stupid?

**To Reproduce**
Create LE Certificate with selfhosted BIND DNS Challenge.

**Expected behavior**
DNS Entry going to be written and everything else is working.

**Screenshots**

**Relevant log files**
Here is my acme.sh.log:
[Mon Sep 13 13:11:52 CEST 2021] ACME_DIRECTORY='https://acme-staging-v02.api.letsencrypt.org/directory'
[Mon Sep 13 13:11:52 CEST 2021] DOMAIN_PATH='/var/etc/acme-client/home/domain.de'
[Mon Sep 13 13:11:52 CEST 2021] Renew: 'domain.de'
[Mon Sep 13 13:11:52 CEST 2021] Le_API='https://acme-staging-v02.api.letsencrypt.org/directory'
[Mon Sep 13 13:11:52 CEST 2021] Using config home:/var/etc/acme-client/home
[Mon Sep 13 13:11:52 CEST 2021] ACME_DIRECTORY='https://acme-staging-v02.api.letsencrypt.org/directory'
[Mon Sep 13 13:11:52 CEST 2021] _init api for server: https://acme-staging-v02.api.letsencrypt.org/directory
[Mon Sep 13 13:11:52 CEST 2021] Retrying GET
[Mon Sep 13 13:11:52 CEST 2021] GET
[Mon Sep 13 13:11:52 CEST 2021] url='https://acme-staging-v02.api.letsencrypt.org/directory'
[Mon Sep 13 13:11:52 CEST 2021] timeout=
[Mon Sep 13 13:11:52 CEST 2021] displayError='1'
[Mon Sep 13 13:11:52 CEST 2021] _CURL='curl --silent --dump-header /var/etc/acme-client/home/http.header -L '
[Mon Sep 13 13:11:53 CEST 2021] ret='0'
[Mon Sep 13 13:11:53 CEST 2021] _hcode='0'
[Mon Sep 13 13:11:53 CEST 2021] ACME_KEY_CHANGE='https://acme-staging-v02.api.letsencrypt.org/acme/key-change'
[Mon Sep 13 13:11:53 CEST 2021] ACME_NEW_AUTHZ
[Mon Sep 13 13:11:53 CEST 2021] ACME_NEW_ORDER='https://acme-staging-v02.api.letsencrypt.org/acme/new-order'
[Mon Sep 13 13:11:53 CEST 2021] ACME_NEW_ACCOUNT='https://acme-staging-v02.api.letsencrypt.org/acme/new-acct'
[Mon Sep 13 13:11:53 CEST 2021] ACME_REVOKE_CERT='https://acme-staging-v02.api.letsencrypt.org/acme/revoke-cert'
[Mon Sep 13 13:11:53 CEST 2021] ACME_AGREEMENT='https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf'
[Mon Sep 13 13:11:53 CEST 2021] ACME_NEW_NONCE='https://acme-staging-v02.api.letsencrypt.org/acme/new-nonce'
[Mon Sep 13 13:11:53 CEST 2021] _main_domain='domain.de'
[Mon Sep 13 13:11:53 CEST 2021] _alt_domains='domain.de'
[Mon Sep 13 13:11:53 CEST 2021] Using ACME_DIRECTORY: https://acme-staging-v02.api.letsencrypt.org/directory
[Mon Sep 13 13:11:53 CEST 2021] _init api for server: https://acme-staging-v02.api.letsencrypt.org/directory
[Mon Sep 13 13:11:53 CEST 2021] Le_NextRenewTime
[Mon Sep 13 13:11:53 CEST 2021] Using CA: https://acme-staging-v02.api.letsencrypt.org/directory
[Mon Sep 13 13:11:53 CEST 2021] _on_before_issue
[Mon Sep 13 13:11:53 CEST 2021] _chk_main_domain='domain.de'
[Mon Sep 13 13:11:53 CEST 2021] _chk_alt_domains='domain.de'
[Mon Sep 13 13:11:53 CEST 2021] Le_LocalAddress
[Mon Sep 13 13:11:53 CEST 2021] d='domain.de'
[Mon Sep 13 13:11:53 CEST 2021] Check for domain='domain.de'
[Mon Sep 13 13:11:53 CEST 2021] _currentRoot='dns_opnsense'
[Mon Sep 13 13:11:53 CEST 2021] d='domain.de'
[Mon Sep 13 13:11:53 CEST 2021] Check for domain='domain.de'
[Mon Sep 13 13:11:53 CEST 2021] _currentRoot='dns_opnsense'
[Mon Sep 13 13:11:53 CEST 2021] d
[Mon Sep 13 13:11:53 CEST 2021] _saved_account_key_hash is not changed, skip register account.
[Mon Sep 13 13:11:53 CEST 2021] Read key length:4096
[Mon Sep 13 13:11:53 CEST 2021] _createcsr
[Mon Sep 13 13:11:53 CEST 2021] Multi domain='DNS:domain.de,DNS:domain.de'
[Mon Sep 13 13:11:53 CEST 2021] Getting domain auth token for each domain
[Mon Sep 13 13:11:53 CEST 2021] d='domain.de'
[Mon Sep 13 13:11:53 CEST 2021] d
[Mon Sep 13 13:11:53 CEST 2021] url='https://acme-staging-v02.api.letsencrypt.org/acme/new-order'
[Mon Sep 13 13:11:53 CEST 2021] payload='{"identifiers": [{"type":"dns","value":"domain.de"},{"type":"dns","value":"domain.de"}]}'
[Mon Sep 13 13:11:53 CEST 2021] RSA key
[Mon Sep 13 13:11:55 CEST 2021] Retrying post
[Mon Sep 13 13:11:55 CEST 2021] HEAD
[Mon Sep 13 13:11:55 CEST 2021] _post_url='https://acme-staging-v02.api.letsencrypt.org/acme/new-nonce'
[Mon Sep 13 13:11:55 CEST 2021] _CURL='curl --silent --dump-header /var/etc/acme-client/home/http.header -L -I '
[Mon Sep 13 13:11:56 CEST 2021] _ret='0'
[Mon Sep 13 13:11:56 CEST 2021] _hcode='0'
[Mon Sep 13 13:11:56 CEST 2021] Retrying post
[Mon Sep 13 13:11:56 CEST 2021] POST
[Mon Sep 13 13:11:56 CEST 2021] _post_url='https://acme-staging-v02.api.letsencrypt.org/acme/new-order'
[Mon Sep 13 13:11:56 CEST 2021] _CURL='curl --silent --dump-header /var/etc/acme-client/home/http.header -L '
[Mon Sep 13 13:11:56 CEST 2021] _ret='0'
[Mon Sep 13 13:11:56 CEST 2021] _hcode='0'
[Mon Sep 13 13:11:56 CEST 2021] code='201'
[Mon Sep 13 13:11:56 CEST 2021] Le_LinkOrder='https://acme-staging-v02.api.letsencrypt.org/acme/order/8541739/523858448'
[Mon Sep 13 13:11:56 CEST 2021] Le_OrderFinalize='https://acme-staging-v02.api.letsencrypt.org/acme/finalize/8541739/523858448'
[Mon Sep 13 13:11:56 CEST 2021] url='https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/483058388'
[Mon Sep 13 13:11:56 CEST 2021] payload
[Mon Sep 13 13:11:57 CEST 2021] Retrying post
[Mon Sep 13 13:11:57 CEST 2021] POST
[Mon Sep 13 13:11:57 CEST 2021] _post_url='https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/483058388'
[Mon Sep 13 13:11:57 CEST 2021] _CURL='curl --silent --dump-header /var/etc/acme-client/home/http.header -L '
[Mon Sep 13 13:11:57 CEST 2021] _ret='0'
[Mon Sep 13 13:11:57 CEST 2021] _hcode='0'
[Mon Sep 13 13:11:57 CEST 2021] code='200'
[Mon Sep 13 13:11:57 CEST 2021] d='domain.de'
[Mon Sep 13 13:11:57 CEST 2021] Getting webroot for domain='domain.de'
[Mon Sep 13 13:11:57 CEST 2021] _w='dns_opnsense'
[Mon Sep 13 13:11:57 CEST 2021] _currentRoot='dns_opnsense'
[Mon Sep 13 13:11:57 CEST 2021] entry='"type":"dns-01","status":"pending","url":"https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/483058388/aWTs-A","token":"8jxbpWA6h5xBmveMs7Uh6r_vUlHbcy2MVo07LzI8ioE"'
[Mon Sep 13 13:11:57 CEST 2021] token='8jxbpWA6h5xBmveMs7Uh6r_vUlHbcy2MVo07LzI8ioE'
[Mon Sep 13 13:11:57 CEST 2021] uri='https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/483058388/aWTs-A'
[Mon Sep 13 13:11:57 CEST 2021] keyauthorization='8jxbpWA6h5xBmveMs7Uh6r_vUlHbcy2MVo07LzI8ioE.AH8IvW3zEUkdY5c0LEC6FsDQGyUfpf6twWlG2xaoDMg'
[Mon Sep 13 13:11:57 CEST 2021] dvlist='domain.de#8jxbpWA6h5xBmveMs7Uh6r_vUlHbcy2MVo07LzI8ioE.AH8IvW3zEUkdY5c0LEC6FsDQGyUfpf6twWlG2xaoDMg#https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/483058388/aWTs-A#dns-01#dns_opnsense'
[Mon Sep 13 13:11:57 CEST 2021] d='domain.de'
[Mon Sep 13 13:11:57 CEST 2021] Getting webroot for domain='domain.de'
[Mon Sep 13 13:11:57 CEST 2021] _w='dns_opnsense'
[Mon Sep 13 13:11:57 CEST 2021] _currentRoot='dns_opnsense'
[Mon Sep 13 13:11:58 CEST 2021] entry='"type":"dns-01","status":"pending","url":"https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/483058388/aWTs-A","token":"8jxbpWA6h5xBmveMs7Uh6r_vUlHbcy2MVo07LzI8ioE"'
[Mon Sep 13 13:11:58 CEST 2021] token='8jxbpWA6h5xBmveMs7Uh6r_vUlHbcy2MVo07LzI8ioE'
[Mon Sep 13 13:11:58 CEST 2021] uri='https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/483058388/aWTs-A'
[Mon Sep 13 13:11:58 CEST 2021] keyauthorization='8jxbpWA6h5xBmveMs7Uh6r_vUlHbcy2MVo07LzI8ioE.AH8IvW3zEUkdY5c0LEC6FsDQGyUfpf6twWlG2xaoDMg'
[Mon Sep 13 13:11:58 CEST 2021] dvlist='domain.de#8jxbpWA6h5xBmveMs7Uh6r_vUlHbcy2MVo07LzI8ioE.AH8IvW3zEUkdY5c0LEC6FsDQGyUfpf6twWlG2xaoDMg#https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/483058388/aWTs-A#dns-01#dns_opnsense'
[Mon Sep 13 13:11:58 CEST 2021] d
[Mon Sep 13 13:11:58 CEST 2021] vlist='domain.de#8jxbpWA6h5xBmveMs7Uh6r_vUlHbcy2MVo07LzI8ioE.AH8IvW3zEUkdY5c0LEC6FsDQGyUfpf6twWlG2xaoDMg#https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/483058388/aWTs-A#dns-01#dns_opnsense,domain.de#8jxbpWA6h5xBmveMs7Uh6r_vUlHbcy2MVo07LzI8ioE.AH8IvW3zEUkdY5c0LEC6FsDQGyUfpf6twWlG2xaoDMg#https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/483058388/aWTs-A#dns-01#dns_opnsense,'
[Mon Sep 13 13:11:58 CEST 2021] d='domain.de'
[Mon Sep 13 13:11:58 CEST 2021] _d_alias='=home.domain.de'
[Mon Sep 13 13:11:58 CEST 2021] txtdomain='home.domain.de'
[Mon Sep 13 13:11:58 CEST 2021] txt='DL2BLudZh4LUAuQdGnQeG5t0L9PQN1LfyfqtxhshpQs'
[Mon Sep 13 13:11:58 CEST 2021] d_api='/usr/local/share/examples/acme.sh/dnsapi/dns_opnsense.sh'
[Mon Sep 13 13:11:58 CEST 2021] Found domain api file: /usr/local/share/examples/acme.sh/dnsapi/dns_opnsense.sh
[Mon Sep 13 13:11:58 CEST 2021] Adding txt value: DL2BLudZh4LUAuQdGnQeG5t0L9PQN1LfyfqtxhshpQs for domain: home.domain.de
[Mon Sep 13 13:11:58 CEST 2021] Retrying GET
[Mon Sep 13 13:11:58 CEST 2021] GET
[Mon Sep 13 13:11:58 CEST 2021] url='https://rV5jPL3dCT3E83%2fQeR%2bbMjSDLcEPkDoEAIKX6r5MLwiI5TFvLFoGUM2%2f5D4Uwmlf0MbKc6Vfh2Z2sUS9:aosAcQRuEsu0R6Utnk1cklzQYrgmqIPTpKihCtZaiqBvo8GqCeOZHIxgmslXCgzEAA6sgXvo%2b19QvaSN@127.0.0.1:443/api/bind/general/get'
[Mon Sep 13 13:11:58 CEST 2021] timeout=
[Mon Sep 13 13:11:58 CEST 2021] displayError='1'
[Mon Sep 13 13:11:58 CEST 2021] _CURL='curl --silent --dump-header /var/etc/acme-client/home/http.header -L --insecure '
[Mon Sep 13 13:11:58 CEST 2021] ret='0'
[Mon Sep 13 13:11:58 CEST 2021] _hcode='0'
[Mon Sep 13 13:11:58 CEST 2021] Adding record home.domain.de with challenge: DL2BLudZh4LUAuQdGnQeG5t0L9PQN1LfyfqtxhshpQs
[Mon Sep 13 13:11:58 CEST 2021] Detect root zone
[Mon Sep 13 13:11:58 CEST 2021] Retrying GET
[Mon Sep 13 13:11:58 CEST 2021] GET
[Mon Sep 13 13:11:58 CEST 2021] url='https://rV5jPL3dCT3E83%2fQeR%2bbMjSDLcEPkDoEAIKX6r5MLwiI5TFvLFoGUM2%2f5D4Uwmlf0MbKc6Vfh2Z2sUS9:aosAcQRuEsu0R6Utnk1cklzQYrgmqIPTpKihCtZaiqBvo8GqCeOZHIxgmslXCgzEAA6sgXvo%2b19QvaSN@127.0.0.1:443/api/bind/domain/get'
[Mon Sep 13 13:11:58 CEST 2021] timeout=
[Mon Sep 13 13:11:58 CEST 2021] displayError='1'
[Mon Sep 13 13:11:58 CEST 2021] _CURL='curl --silent --dump-header /var/etc/acme-client/home/http.header -L --insecure '
[Mon Sep 13 13:11:58 CEST 2021] ret='0'
[Mon Sep 13 13:11:58 CEST 2021] _hcode='0'
[Mon Sep 13 13:11:58 CEST 2021] h='domain.de'
[Mon Sep 13 13:11:58 CEST 2021] h='de'
[Mon Sep 13 13:11:58 CEST 2021] invalid domain
[Mon Sep 13 13:11:58 CEST 2021] Error add txt for domain:home.domain.de
[Mon Sep 13 13:11:58 CEST 2021] _on_issue_err
[Mon Sep 13 13:11:58 CEST 2021] Please check log file for more details: /var/log/acme.sh.log
[Mon Sep 13 13:11:58 CEST 2021] url='https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/483058388/aWTs-A'
[Mon Sep 13 13:11:58 CEST 2021] payload='{}'
[Mon Sep 13 13:11:58 CEST 2021] Retrying post
[Mon Sep 13 13:11:58 CEST 2021] POST
[Mon Sep 13 13:11:58 CEST 2021] _post_url='https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/483058388/aWTs-A'
[Mon Sep 13 13:11:58 CEST 2021] _CURL='curl --silent --dump-header /var/etc/acme-client/home/http.header -L '
[Mon Sep 13 13:11:59 CEST 2021] _ret='0'
[Mon Sep 13 13:11:59 CEST 2021] _hcode='0'
[Mon Sep 13 13:11:59 CEST 2021] code='200'
[Mon Sep 13 13:11:59 CEST 2021] url='https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/483058388/aWTs-A'
[Mon Sep 13 13:11:59 CEST 2021] payload='{}'
[Mon Sep 13 13:11:59 CEST 2021] Retrying post
[Mon Sep 13 13:11:59 CEST 2021] POST
[Mon Sep 13 13:11:59 CEST 2021] _post_url='https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/483058388/aWTs-A'
[Mon Sep 13 13:11:59 CEST 2021] _CURL='curl --silent --dump-header /var/etc/acme-client/home/http.header -L '
[Mon Sep 13 13:12:00 CEST 2021] _ret='0'
[Mon Sep 13 13:12:00 CEST 2021] _hcode='0'
[Mon Sep 13 13:12:00 CEST 2021] code='200'
[Mon Sep 13 13:12:00 CEST 2021] pid
[Mon Sep 13 13:12:00 CEST 2021] No need to restore nginx, skip.
[Mon Sep 13 13:12:00 CEST 2021] _clearupdns
[Mon Sep 13 13:12:00 CEST 2021] dns_entries
[Mon Sep 13 13:12:00 CEST 2021] skip dns.

**Additional context**

**Environment**
OPNsense 21.7.2_1-amd64
FreeBSD 12.1-RELEASE-p20-HBSD
OpenSSL 1.1.1l 24 Aug 2021

**Comment by superwinni2** [comment]
If I try to reset acme client i get the following message:
`/usr/local/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/BaseField.php:324: lastUpdate not an attribute of accounts.account.6591b98a-1e9e-489b-8a53-0d271a93de38`

Is something wrong with my account?!?

**Comment by superwinni2** [comment]
It's something that has to do with my upgrade to 21.7.2_1.
If I do `opnsense-revert -r 21.7 os-acme-client` it works again.

**Comment by superwinni2** [comment]
Also tried reinstalling my complete OPNsense.
Also not working.

Am I really the only one with this problem?

**Comment by mimugmail** [comment]
I dont use this feature and also didnt add it. To me it seems something break with acme 3.0. @fraenki any idea?

**Comment by wacki4** [comment]
+1 same problem here, 'invalid domain' error.

**Comment by fraenki** [comment]
Please check `System: Log Files: Backend` and `System: Log Files: General` when trying to issue/renew a certificate. And check if `/tmp/PHP_errors.log` exists, it may contain the real error (only if this is actually a code error).

Is there a BIND log available? This could also tell us why the TXT entry cannot be created.

**Comment by wacki4** [comment]
Fragment of acme log when trying to get certificate:

2021-10-04T00:00:46 | acme.sh[34179] | ] Please check log file for more details: /var/log/acme.sh.log
-- | -- | --
2021-10-04T00:00:46 | acme.sh[67531] | ] _on_issue_err
2021-10-04T00:00:46 | acme.sh[96515] | ] Error add txt for domain:_acme-challenge.aaa.test.pl
2021-10-04T00:00:46 | acme.sh[57501] | ] invalid domain
2021-10-04T00:00:46 | acme.sh[22615] | ] h='pl'
2021-10-04T00:00:46 | acme.sh[20618] | ] h='test.pl'
2021-10-04T00:00:46 | acme.sh[6209] | ] h='aaa.test.pl'
2021-10-04T00:00:46 | acme.sh[95843] | ] _hcode='0'
2021-10-04T00:00:46 | acme.sh[35607] | ] ret='0'
2021-10-04T00:00:46 | acme.sh[49601] | ] _CURL='curl --silent --dump-header /var/etc/acme-client/home/http.header  -L  --trace-ascii /tmp/tmp.TYdTJbKu  --insecure  '
2021-10-04T00:00:45 | acme.sh[44639] | ] displayError='1'
2021-10-04T00:00:45 | acme.sh[82114] | ] timeout=
2021-10-04T00:00:45 | acme.sh[85694] | ]   url='https://[CUT OFF FOR SECURITY]/api/bind/domain/get'

I also made a ticket before on offical client:

https://github.com/acmesh-official/acme.sh/issues/3735

Backend log has only this entry on same time:

2021-10-04T00:00:49 | configd.py[60037] | [36d2a6fa-6336-4ff2-bdee-edb69a371bbc] trigger config changed event |  
-- | -- | -- | --
2021-10-04T00:00:33 | configd.py[60037] | [a01bbf26-252c-4377-9e2a-beb4bb36dab1] Tested for presence of plugin bind |  
2021-10-04T00:00:33 | configd.py[60037] | [1be9b148-f918-4236-8705-5fbabd567c93] trigger config changed event |  
2021-10-04T00:00:32 | configd.py[60037] | message 7b91938a-ca99-4b0c-9866-59305954584a [filter.refresh_aliases] returned {"status": "ok"} |  
2021-10-04T00:00:32 | configd.py[60037] | [7b91938a-ca99-4b0c-9866-59305954584a] refresh url table aliases |  
2021-10-04T00:00:32 | configd.py[60037] | OPNsense/Filter generated //usr/local/etc/filter_geoip.conf |  
2021-10-04T00:00:32 | configd.py[60037] | OPNsense/Filter generated //usr/local/etc/filter_tables.conf |  
2021-10-04T00:00:32 | configd.py[60037] | generate template container OPNsense/Filter |  
2021-10-04T00:00:32 | configd.py[60037] | [da044b74-550a-4a61-a995-d8ca970e6567] generate template OPNsense/Filter |  
2021-10-04T00:00:31 | configd.py[60037] | [c5cbd42c-dff8-48d5-a9f5-2e4c55bb2ebd] Reloading filter |  
2021-10-04T00:00:00 | configd.py[60037] | [431c1bbe-4b6d-420a-bb07-aa84713e4e33] cronjob running to sign or renew certificates

PHP has also error on same time:
[04-Oct-2021 00:00:33 Europe/Warsaw] PHP Warning:  dns_get_record(): DNS Query failed in /usr/local/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/Base.php on line 240
[04-Oct-2021 00:00:33 Europe/Warsaw] PHP Warning:  dns_get_record(): DNS Query failed in /usr/local/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/Base.php on line 264

**Comment by wacki4** [comment]
As i looked error seems to be from file https://github.com/acmesh-official/acme.sh/blob/master/dnsapi/dns_opnsense.sh , on line 153 we have regex to find root for domain. Maybe something changed on bind api, and returns different output?

**Comment by superwinni2** [comment]
My Response for https://firewall/api/bind/domain/get:

`{"domain":{"domains":{"domain":{"320e19d1-4f9b-46da-9ea3-af35719833ce":{"enabled":"1","type":{"master":{"value":"master","selected":1},"slave":{"value":"slave","selected":0}},"masterip":{"":{"value":"","selected":1}},"allownotifyslave":{"":{"value":"","selected":1}},"domainname":"subdomain.domain.com","allowtransfer":{"":{"value":"none","selected":0},"3a407540-5710-4ead-84dd-d2ab0abb5fed":{"value":"Jeder","selected":1}},"allowquery":{"":{"value":"none","selected":0},"3a407540-5710-4ead-84dd-d2ab0abb5fed":{"value":"Jeder","selected":1}},"serial":"2107191618","ttl":"600","refresh":"21600","retry":"3600","expire":"3542400","negative":"60","mailadmin":"mailadmin.mailserver.com","dnsserver":"dns.dnsserver.com"}}}}}`

I tried to solve the egrep regex... but I'm not nearly as good as I wish to be to unterstand was it's doing

**Comment by fraenki** [comment]
So to summarize the reports, this looks like an upstream issue in acme.sh that should be fixed there:
https://github.com/acmesh-official/acme.sh/issues/3735
