### ISSUE TITLE
Wireguard - Dashboard widget to show Endpoint name instead of public key

### ISSUE THREAD

**Issue by Nikotine1** [opnsense/plugins#2537]
I was wondering if it would be possible to show the endpoint name instead of, or in addition to, the public key in the Wireguard dashboard widget.

![dashboard](https://user-images.githubusercontent.com/1538384/133253529-696d5703-8c42-4905-86be-1b86a71ef1bf.jpg)

**Comment by jkellerer** [comment]
There is a pending PR #1970

**Comment by Nikotine1** [comment]
Thanks. That would be great, if it could be integrated.

**Comment by dimmenhau** [comment]
Hello,
is there an approximate plan when the PR will be implemented ?
