### ISSUE TITLE
SNMP support for os-frr

### ISSUE THREAD

**Issue by ciroiriarte** [opnsense/plugins#2541]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

[X] The title contains the plugin to which this issue belongs

**Describe the bug**
SNMP support if offered in the GUI, but if setup up, frr complains  with "no such command". Also, no information regarding routing seems present in an snmpwalk

**To Reproduce**
1. Enable AgentX support in net-snmp
2. Enable SNMP support in os-frr
3. Restart service

**Expected behavior**
After setting up net-snmp & os-frr properly, routing information should be available through SNMP requests to net-snmp.

**Screenshots**
![image](https://user-images.githubusercontent.com/1750260/133939602-a3168a19-eec8-4584-9ba9-edcd6c74db85.png)

![image](https://user-images.githubusercontent.com/1750260/133939627-b8037ce7-fb75-4399-a012-87b8b473d28e.png)

**Relevant log files**
```
root@vfw01:~ # service frr start
Checking zebra.conf
2021/09/19 13:41:36 ZEBRA: [EC 4043309110] Disabling MPLS support (no kernel support)
2021/09/19 13:41:36 ZEBRA: [EC 100663304] ERROR: No such command on config line 12: agentx
OK
```

**Additional context**
Feature added in https://github.com/opnsense/plugins/pull/2321

**Environment**
OPNsense 21.7.2_1-amd64
Xeon(R) CPU E5-2680 v4
KVM vtnet

**Comment by joshland** [comment]
hmm. this used to work, I was using it - i can validate that routes cannot be exported through this mechanism, and the problem is on the FRR side.
