### ISSUE TITLE
FRR diagnostics add BFD diagnostics and show BFD peers status

### ISSUE THREAD

**Issue by nzkiwi68** [opnsense/plugins#2542]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:
[X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
[X] I have searched the existing issues and I'm convinced that mine is new.
[X] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
It's hard to see if the BFD peers are actually connecting and working because there is no simple diagnostic view

**Describe the solution you'd like**
Add to "Routing > Diagnostics" a new section "BFD" and show status as per;
[https://docs.frrouting.org/en/stable-7.5/bfd.html](url)
Ideally show all configured BFD peers information and current status
    and
Show more detailed status for each specific BFD peer.

**Describe alternatives you've considered**
There isn't a GUI easy way to do so today.

**Additional context**
See the FRR documentation;
[https://docs.frrouting.org/en/stable-7.5/bfd.html](url)

**Comment by mimugmail** [comment]
I will have a look this week as I also work on the BGP part the next days

**Comment by nzkiwi68** [comment]
I have a customer running three sites HA pfSense that we are migrating to new HA OPNsense. Because it's not yet in production installed side by side, I'd be more than happy to help with testing.
If you're able to get Wireguard to follow CARP, tell me how I can down the patch and I'll help test.

I'd much rather migrate direct to WG site to site tunnels than IPSEC.

Thanks!

**Comment by nzkiwi68** [comment]
Any chance of getting BFD status into 22.1?

**Comment by mimugmail** [comment]
No, but an early 22.1.x
