### ISSUE TITLE
Request for OpenVPN Client configuration Import

### ISSUE THREAD

**Issue by squadramunter** [opnsense/plugins#255]
When I created a OpenVPN client profile I want to Import that on my OpnSense router. But how can I Import that on my router so my connection is secure over a VPN. On Windows you have openvpn client and you can put there the configuration file in it. but on opnsense how can I do that? It should be fine if there is a method for that.

**Comment by AdSchellevis** [comment]
Unfortunately you have to import your settings manually, creating an automatic import which maps the ovpn format back to the fields we use will likely be very prune to errors.... (and most of the time the settings needed are quite basic).

**Comment by fabianfrz** [comment]
@AdSchellevis this is not possible in a reasonable way as OpenVPN is currently not MVC. This means there would be an incompatibility with core.

**Comment by ghstwhl** [comment]
If importing .ovpn file is so difficult, why am I able to import into tunnelblick and Viscoscity?
