### ISSUE TITLE
security/acme-client: Lets Encrypt certificates are provided by obsolete DST Root CA X3

### ISSUE THREAD

**Issue by cedvan** [opnsense/plugins#2550]
**Important notices**
[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
[x] I have searched the existing issues and I'm convinced that mine is new.
[x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
Lets Encrypt certificates are provided by DST Root CA X3 in acme plugin. But this root CA is deprecated and expire in september 2021 (https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/)

![cert-date](https://user-images.githubusercontent.com/4289595/135067202-8dc1a881-bad4-4a68-b194-a43d13fe48b4.png)
![root-cert](https://user-images.githubusercontent.com/4289595/135067201-40940038-bf8e-4081-89b7-5c1308a992f7.png)

**Describe the solution you'd like**
Use new root certificate ISRG Root X1 is a new way. How use it with acme plugin ?

**Comment by fraenki** [comment]
@cedvan Maybe I'm missing something here? As far as I'm aware, Let's Encrypt added a new [cross-signed CA](https://letsencrypt.org/2020/12/21/extending-android-compatibility.html) which should work beyond 30.09.2021:

`R3 ← ISRG Root X1 ← DST Root CA X3`

I've manually renewed one of my certificates and the two parts of the chain seem to confirm that it's using the new cross-signed CA:

```
# openssl x509 -noout -text -in /tmp/chain1.crt 
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            91:2b:08:4a:cf:0c:18:a7:53:f6:d6:2e:25:a7:5f:5a
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = US, O = Internet Security Research Group, CN = ISRG Root X1
        Validity
            Not Before: Sep  4 00:00:00 2020 GMT
            Not After : Sep 15 16:00:00 2025 GMT
        Subject: C = US, O = Let's Encrypt, CN = R3
...

# openssl x509 -noout -text -in /tmp/chain2.crt
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            40:01:77:21:37:d4:e9:42:b8:ee:76:aa:3c:64:0a:b7
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: O = Digital Signature Trust Co., CN = DST Root CA X3
        Validity
            Not Before: Jan 20 19:14:03 2021 GMT
            Not After : Sep 30 18:14:03 2024 GMT
        Subject: C = US, O = Internet Security Research Group, CN = ISRG Root X1
...
```

And viewing the resulting cert chain in Firefox 92 it seems that it already preferres the X1 route over the expiring X3. However, I can confirm that Chrome still shows the the same output that you've posted in the screenshot.

Yes, there is an [alternative chain available](https://community.letsencrypt.org/t/production-chain-changes/150739):
`R3 ← ISRG Root X1`
But it provides worse compatibility with older clients and should not provided any benefit.

Does this make sense to you? Is there something wrong with this explanation? D

**Comment by cedvan** [comment]
CONNECTED(00000005)
depth=1 C = US, O = Let's Encrypt, CN = R3
verify error:num=20:unable to get local issuer certificate
---
Certificate chain
 0 s:CN = YOUR_HAPROXY_FQDN
   i:C = US, O = Let's Encrypt, CN = R3
-----BEGIN CERTIFICATE-----
MIIGKDCCBRCgAwIBAgISBOlQk2YxK1k6zpgJ7op5EDtGMA0GCSqGSIb3DQEBCwUA
MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
EwJSMzAeFw0yMTA5MjgwODUwMThaFw0yMTEyMjcwODUwMTdaMBsxGTAXBgNVBAMT
EHRyYWNrLmtlZW5vdmEuaW8wggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoIC
AQDJ0BVEl+0GktavwqWDbP1DFY92bouOv7DHrn7XJDqh0qFypcxotq1YRRiEOjQ4
0rY8rruB4k4dYHps+8t3H3d2p2xdIGsiODJh80EYG7ndor3TiEmg7PDnqqwtW6mS
C57PSHNKZEvaCb8B2fIssy5258zZL4fwkh/dQBytdyHXKD55Vqvi4QU3e70oj3eP
1wT/U+MZBUMqcp4aQz22oyWkAGUFRHc9Oc00G7mx3yNQ5mCqYlTAlDnTv1CgKvhU
fhn63dfaFXkOACHrVcN3bMZn1Cj/rOyDFayGIZdTdUFQBxAvA3/vMlZSFAU56KI9
8Vkkw1wUh5ayIRx3OdTdtYymWYVbZlVAkuFMlsqZ06/9+Yrd5/4DWl97KmxJzXLc
DRVMnlj8DR7dxhSo1zLFH4u91a60j3m3CWhzAYyF7QCUz3b9CaN1LkxNw8NSRwX0
cJMFqDM5AhaKsi1zM6OfGawVOSLAaIF+8ivtzWd5jlmEWyDwvj8DKWa/AXwKxaVy
kPBkDPlarwX6ZvCUeqXARxAysdYLZBigEIEfwx3IbxkJK2ylEPYIpLeJBzmnu+lJ
l7dDwd2EH6whOeyd3WImkw9omwecb2TqooGyhEawmmASpean4FM1mm7A2McI0njS
uXxsO1WLT+Z5E0LX1Kx0DiVj3C4aLTITGlOG+BUSQWgErQIDAQABo4ICTTCCAkkw
DgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAM
BgNVHRMBAf8EAjAAMB0GA1UdDgQWBBQu+QQrfDppanzbSs3RCfnrUlnNZzAfBgNV
HSMEGDAWgBQULrMXt1hWy65QCUDmH6+dixTCxjBVBggrBgEFBQcBAQRJMEcwIQYI
KwYBBQUHMAGGFWh0dHA6Ly9yMy5vLmxlbmNyLm9yZzAiBggrBgEFBQcwAoYWaHR0
cDovL3IzLmkubGVuY3Iub3JnLzAbBgNVHREEFDASghB0cmFjay5rZWVub3ZhLmlv
MEwGA1UdIARFMEMwCAYGZ4EMAQIBMDcGCysGAQQBgt8TAQEBMCgwJgYIKwYBBQUH
AgEWGmh0dHA6Ly9jcHMubGV0c2VuY3J5cHQub3JnMIIBBgYKKwYBBAHWeQIEAgSB
9wSB9ADyAHcARJRlLrDuzq/EQAfYqP4owNrmgr7YyzG1P9MzlrW2gagAAAF8K8/p
PwAABAMASDBGAiEA6C/p7b8gziaEFnnquwYMC9MJMJuPVIo96Op4jwmNleoCIQD9
0xNS9zpn+ZlyjemieMepTpWFuQHb/wu4loFTsK1P6gB3APZclC/RdzAiFFQYCDCU
Vo7jTRMZM7/fDC8gC8xO8WTjAAABfCvP6R4AAAQDAEgwRgIhAJC/OSDmoSlzNBpp
PZ7eOTf7f3iVU3omFO9eoSsT1vCtAiEAzClJRKjDZPwM/lAF2CGcDfM62PSQboPC
/X4ByB17AV8wDQYJKoZIhvcNAQELBQADggEBAEV7FggBBVwuG/c17PKgw+D1OQEP
0e2Dpuvmw1f9vHUm9bmSwkXcG9bhVT4ld8luSvMPPUlSS/eXTigvzzoWvEeDVSBb
vH7k0JHVIXBw88dtMeccK1sD6iewmSHJlmZq/ibXvA7a1MORFiMIX8Gmw5gCioir
6GqXt3+Q0CzNyMP2e4vW4wJuy+Oj4CIXXp0xXPJ0G4E+ZiLBj4er1M+BSGW+yTX1
cyR2SDRNCYLOQRk6UKiaWkhZL1VqXSA9bOQMGEq7ualk6XuHj8kjJHkfEWwqSPnh
YqUkPmIH8vwnldd1kuOgndTvS9lHrt7q4MIsqwew9d2N5rZdospb66WqjPY=
-----END CERTIFICATE-----
 1 s:C = US, O = Let's Encrypt, CN = R3
   i:O = Digital Signature Trust Co., CN = DST Root CA X3
-----BEGIN CERTIFICATE-----
MIIEZTCCA02gAwIBAgIQQAF1BIMUpMghjISpDBbN3zANBgkqhkiG9w0BAQsFADA/
MSQwIgYDVQQKExtEaWdpdGFsIFNpZ25hdHVyZSBUcnVzdCBDby4xFzAVBgNVBAMT
DkRTVCBSb290IENBIFgzMB4XDTIwMTAwNzE5MjE0MFoXDTIxMDkyOTE5MjE0MFow
MjELMAkGA1UEBhMCVVMxFjAUBgNVBAoTDUxldCdzIEVuY3J5cHQxCzAJBgNVBAMT
AlIzMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuwIVKMz2oJTTDxLs
jVWSw/iC8ZmmekKIp10mqrUrucVMsa+Oa/l1yKPXD0eUFFU1V4yeqKI5GfWCPEKp
Tm71O8Mu243AsFzzWTjn7c9p8FoLG77AlCQlh/o3cbMT5xys4Zvv2+Q7RVJFlqnB
U840yFLuta7tj95gcOKlVKu2bQ6XpUA0ayvTvGbrZjR8+muLj1cpmfgwF126cm/7
gcWt0oZYPRfH5wm78Sv3htzB2nFd1EbjzK0lwYi8YGd1ZrPxGPeiXOZT/zqItkel
/xMY6pgJdz+dU/nPAeX1pnAXFK9jpP+Zs5Od3FOnBv5IhR2haa4ldbsTzFID9e1R
oYvbFQIDAQABo4IBaDCCAWQwEgYDVR0TAQH/BAgwBgEB/wIBADAOBgNVHQ8BAf8E
BAMCAYYwSwYIKwYBBQUHAQEEPzA9MDsGCCsGAQUFBzAChi9odHRwOi8vYXBwcy5p
ZGVudHJ1c3QuY29tL3Jvb3RzL2RzdHJvb3RjYXgzLnA3YzAfBgNVHSMEGDAWgBTE
p7Gkeyxx+tvhS5B1/8QVYIWJEDBUBgNVHSAETTBLMAgGBmeBDAECATA/BgsrBgEE
AYLfEwEBATAwMC4GCCsGAQUFBwIBFiJodHRwOi8vY3BzLnJvb3QteDEubGV0c2Vu
Y3J5cHQub3JnMDwGA1UdHwQ1MDMwMaAvoC2GK2h0dHA6Ly9jcmwuaWRlbnRydXN0
LmNvbS9EU1RST09UQ0FYM0NSTC5jcmwwHQYDVR0OBBYEFBQusxe3WFbLrlAJQOYf
r52LFMLGMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjANBgkqhkiG9w0B
AQsFAAOCAQEA2UzgyfWEiDcx27sT4rP8i2tiEmxYt0l+PAK3qB8oYevO4C5z70kH
ejWEHx2taPDY/laBL21/WKZuNTYQHHPD5b1tXgHXbnL7KqC401dk5VvCadTQsvd8
S8MXjohyc9z9/G2948kLjmE6Flh9dDYrVYA9x2O+hEPGOaEOa1eePynBgPayvUfL
qjBstzLhWVQLGAkXXmNs+5ZnPBxzDJOLxhF2JIbeQAcH5H0tZrUlo5ZYyOqA7s9p
O5b85o3AM/OJ+CktFBQtfvBhcJVd9wvlwPsk+uyOy2HI7mNxKKgsBTt375teA2Tw
UdHkhVNcsAKX1H7GNNLOEADksd86wuoXvg==
-----END CERTIFICATE-----
---
Server certificate
subject=CN = YOUR_HAPROXY_FQDN

issuer=C = US, O = Let's Encrypt, CN = R3

---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 3530 bytes and written 398 bytes
Verification error: unable to get local issuer certificate
---
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Server public key is 4096 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 20 (unable to get local issuer certificate)
---
---
Post-Handshake New Session Ticket arrived:
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : TLS_AES_256_GCM_SHA384
    Session-ID: EF399C96D212C47AB2E7F5D29D96A2C8F0DB987A0E92BC5EC4A5100DAF86F531
    Session-ID-ctx: 
    Resumption PSK: 3EB8086999FF6711495E6CA92FB4A81963224A9FA2BFF8E752A8D13C77FD9FE38F80583E7FD32B5D8E8F343360DDD032
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 7200 (seconds)
    TLS session ticket:
    0000 - 3e 0e 69 78 07 b9 e4 57-b4 16 66 41 bd 09 73 ad   >.ix...W..fA..s.
    0010 - c9 3e aa bf c0 c1 09 bd-ca 97 bf a8 e6 85 68 75   .>............hu

    Start Time: 1632837812
    Timeout   : 7200 (sec)
    Verify return code: 20 (unable to get local issuer certificate)
    Extended master secret: no
    Max Early Data: 0
---
read R BLOCK
---
Post-Handshake New Session Ticket arrived:
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : TLS_AES_256_GCM_SHA384
    Session-ID: BF92C190D8CE371F9BD2B177946C7E6FD23548E2A432052CEADA4037CB3BB7AC
    Session-ID-ctx: 
    Resumption PSK: 07582B9D51AB5E9FFDF81E544E47CB0F95E9CC42D1F3585DC8CCA4DDA7CC23280EBE01539DF4EE1600F052365703DD57
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 7200 (seconds)
    TLS session ticket:
    0000 - a1 17 1a 9d 9e 35 51 00-0a 9d 04 29 58 d8 c2 17   .....5Q....)X...
    0010 - e6 5c 65 60 74 68 78 f7-a5 b2 73 32 86 79 84 4a   .\e`thx...s2.y.J

    Start Time: 1632837812
    Timeout   : 7200 (sec)
    Verify return code: 20 (unable to get local issuer certificate)
    Extended master secret: no
    Max Early Data: 0
---
read R BLOCK

**Comment by cedvan** [comment]
I have latest version to opnsense and all plugins. My certificate regenerate today, but no presence to `ISRG_Root_X1`

**Comment by cedvan** [comment]
My account in Acme client use `Let's Encrypt[default]`

![account-to-acme](https://user-images.githubusercontent.com/4289595/135105377-c08b2531-0ae1-41ed-8494-b1c8a73da9f6.png)

**Comment by cedvan** [comment]
Maybe need recreate new account or recreate new certificate to get good CA hierarchy ?

**Comment by fraenki** [comment]
@cedvan Let's check one more thing:

- go to `System: Trust: Certificates`
- find your Let's Encrypt certificate
- What is the issuer? Please paste the full name here.

**Comment by cedvan** [comment]
issuer to all generated certificates with acme client is `R3 (Let's Encrypt) `

**Comment by fraenki** [comment]
OK, so the real problem is that os-acme-client failed to import the cross-signed R3 CA certificate and as a result applications such as the WebUI and HAProxy will only present the expiring R3 CA certificate to clients. I'll look into this.

**Comment by cedvan** [comment]
Ok, I look forward to your feedback and a solution :)

**Comment by kulikov-a** [comment]
@cedvan 

> My servers have ISRG_Root_X1.pem but no DST_Root_CA_X3.pem in CA certificates list.

sorry, what https://www.ssllabs.com/ssltest/index.html tells about cert path?
imho `DST_Root_CA_X3` still needed for `End-entity certificate ← R3 ← ISRG Root X1 ← DST Root CA X3` chain (default Android compatible chain)

**Comment by cedvan** [comment]
@kulikov-a Yes of course `DST_Root_CA_X3` is still needed for old Android systems. To do this Let's Encrypt added a new cross-signed CA. This allows generated certificates compatible with `ISRG_Root_X1` and `DST_Root_CA_X3`. 

But ACME client generate certificates with old `CA R3` instead of new `cross-signed R3 CA`. On recent systems, `DST_Root_CA_X3` is removed because obsolete. So certificates are invalid...

**Comment by cedvan** [comment]
This bug is quite urgent, because some applications will become unreachable after September 2021

**Comment by kulikov-a** [comment]
@cedvan

> But ACME client generate certificates with old CA R3 (no compatbile with ISRG_Root_X1) instead of new cross-signed R3 CA

not quite so (ACME client does not generate certificate)
so https://www.ssllabs.com/ssltest/index.html reports broken chain for your domain?

**Comment by fraenki** [comment]
I've found the bug, give me some minutes to test the fix :)

**Comment by kulikov-a** [comment]
@fraenki ok, thanks!)
i have production 20.7.7_1's and already working cross-signed LE certs. i just can't remember if i imported the new R3 cert manually or not )

**Comment by fraenki** [comment]
OK, here we go. The following patch for OPNsense 217.3 fixes the bug:

```
root@opnsense: # opnsense-patch -c plugins ae69739 9220a41 247408e
```

Besides fixing the underlying bug in the cert/CA import logic, it also adds a new "import" button to `Services: ACME Client: Certificates`. By using this button the certificate should be linked to the correct CA. Afterwards you need to restart the service that uses the certificate.

**I could only test it on my test server, so make a configuration backup before applying/testing this bugfix.**

In my case it fixes the bug, the example shows the ouput when using the certificate for the OPNsense WebUI:

```
# without bugfix
$ openssl s_client -showcerts -connect opnsense:443
CONNECTED(00000003)
depth=1 C = US, O = Let's Encrypt, CN = R3
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN = opnsense
verify return:1

# after applying the bugfix and re-importing the cert
$ openssl s_client -showcerts -connect opnsense:443
CONNECTED(00000003)
depth=2 C = US, O = Internet Security Research Group, CN = ISRG Root X1
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = R3
verify return:1
depth=0 CN = opnsense
verify return:1
```

**Comment by fraenki** [comment]
(The width of the "commands" column had to be changed after adding the new button, this is fixed in https://github.com/opnsense/plugins/pull/2551/commits/774374a49e261c43ff70ee6f02346177951f2b3d.)

**Comment by cedvan** [comment]
Ok super! Thank you :) 

So just I execute
`opnsense-patch -c plugins ae69739 9220a41 247408e 774374a4` ?

**Comment by fraenki** [comment]
You don't need to regenerate your certificates, just use the new "import" button:

> Besides fixing the underlying bug in the cert/CA import logic, it also adds a new "import" button to `Services: ACME Client: Certificates`. By using this button the certificate should be linked to the correct CA. Afterwards you need to restart the service that uses the certificate.

**Comment by fraenki** [comment]
> are you planning to add the option to select the preferred chain (https://github.com/acmesh-official/acme.sh/wiki/Preferred-Chain)?

I'm still undecided. Adding a text input field is really error prone: a minor typo and it breaks. But adding a dropdown list of possible values puts the maintenance burden on me. Not sure which route to choose.

**Comment by kulikov-a** [comment]
got it, thanks! (will be glad to any option. a text input with a link to the wiki is quite convenient imho)

**Comment by cedvan** [comment]
I test patch, but not working :/.

My step : 
- Go to OpnSense machine in CLI and select shell option
- Execute `opnsense-patch -c plugins ae69739 9220a41 247408e 774374a4` => `All patches have been applied successfully.  Have a nice day.`
- Go to `Services: ACME Client: Certificates` and click on new button `Re-import` on my FQDN row
- Restart HAProxy
- Try `curl` call, same result : `curl: (60) SSL certificate problem: unable to get local issuer certificate`
- Execute `openssl s_client -showcerts -connect FQDN:443` : Same result, missing X1
- Go check `System: Certificats: FQDN` issuer => `R3 (Let's Encrypt) `

**Comment by cedvan** [comment]
Ok, I regenerate my cert and works now !!!

**Comment by cedvan** [comment]
Thank you :pray:

**Comment by hny-gd** [comment]
Any plans to release an official OPNSense patch for this or is manual patching like described by @cedvan above the way to go?

**Comment by fichtner** [comment]
Can we wait for this to be merged to any sort of branch in the project before we talk release timelines?

**Comment by mimugmail** [comment]
@hny-gd Just delete the old CA in Authorities, reissue all LE certs and link them again in the Services (HAProxy, Postfix etc.). Last step is important!

**Comment by hny-gd** [comment]
Thanks a lot, @mimugmail, that indeed is the way to go.
