### ISSUE TITLE
security/acme-client: Automation SFTP-Upload: Fullchain incomplete, intermediate missing

### ISSUE THREAD

**Issue by mattjes04** [opnsense/plugins#2553]
**Describe the bug**
ACME-client Automation "Upload certificate via SFTP" is not sending a complete fullchain.pem. The intermediate certificate is missing.

**To Reproduce**
1. Renew certificate with Automation "Upload certificate via SFTP" in the end
2. Check fullchain.pem after succesfull upload

**Expected behavior**
Fullchain.pem with complete certificate chain

ACME-Client Version: 3.1
OPNsense 21.7.3_1-amd64
FreeBSD 12.1-RELEASE-p20-HBSD
OpenSSL 1.1.1l 24 Aug 2021

**Comment by ysguy** [comment]
THANK YOU. I am having the same issue with DNSDist, seem other things like HAProxy are ok with the chaining, they must generate the chain on their own. So i managed to go here: 

https://tools.keycdn.com/ssl

and paste the fullchain.pem in and it says there is a chaining / ordering issue. 

So i went here: https://whatsmychaincert.com/

and there is a "Generate correct chain" option, i took the output, pasted it into fullchain2.cer and everything works when i point to that file. So i compared the two and they are different in the last cert, but i don't know enough to understand why exactly this would be. 

Hope this helps with at least the workaround.

**Comment by fraenki** [comment]
> ACME-client Automation "Upload certificate via SFTP" is not sending a complete fullchain.pem. The intermediate certificate is missing.

I cannot reproduce this. In my case the fullchain.pem is complete, it contains my certificate and both intermediate certificates. Please provide more details (which ACME CA, the actual contents of your fullchain.pem, etc.).

**Comment by mattjes04** [comment]
I am using the "Let's Encrypt" CA. I think the problem is caused by the "upload_sftp.php" and the construction of the fullchain.pem certificate since the fullchain.pem the client downloads are ok and containing the complete chain.

This problem just came to my attention because the Let's Encrypt DST Root CA X3 expired today and caused my services to fail. After exchanging the fullchain.pem manually by just copying the Version downloaded by the ACME-Client to other servers it started working again as expected. The Problem only exists with the certs uploaded by the automation script.

Here you see the chain details of the fullchain.pem uploaded via sftp automation:
Certificate chain
 0 s:/CN=greensite.me
   i:/C=US/O=Let's Encrypt/CN=R3
 1 s:/C=US/O=Let's Encrypt/CN=R3
   i:/O=Digital Signature Trust Co./CN=DST Root CA X3

And here are the chain details of a fullchain.pem downloaded by ACME-Client:
Certificate chain
 0 s:/CN=greensite.me
   i:/C=US/O=Let's Encrypt/CN=R3
 1 s:/C=US/O=Let's Encrypt/CN=R3
   i:/C=US/O=Internet Security Research Group/CN=ISRG Root X1
 2 s:/C=US/O=Internet Security Research Group/CN=ISRG Root X1
   i:/O=Digital Signature Trust Co./CN=DST Root CA X3

**Comment by fraenki** [comment]
OK, so this has nothing to do with the SFTP functionality.
Please apply the hotfix as described in the other issue:
https://github.com/opnsense/plugins/issues/2550#issuecomment-929380587
