### ISSUE TITLE
dyndns: make latest update-status visible (Dashboard and/or services_dyndns.php)

### ISSUE THREAD

**Issue by oli-h** [opnsense/plugins#2556]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

[X] When the request is meant for an existing plugin, I've added its name to the title.

**Problem**
Due to a password-change which I made on my DynDNS-Provider, the appropriate IP-update (which I used for longer without problem on OpnSense) failed. But there were no clear indication that it failed. Though, then, when looking into the Logs (System: Log Files: General) and searched appropriate I found indications of the failed update.

**Proposed solution**
Make the status of the latest dyndns-update visible, together with the update-timestamp.
Although there is already a "Dynamic DNS"-Widget for the Dashboard there are no indications when one or more configured updated failed.. At least some "red/green"-bubble would be very helpful

**Comment by psychogun** [comment]
What kind of theme are you using on your pfsense? 

On my firewall, which use the default theme, the IP address of the cached IP is shown with the color black, on the widget. However, under services, if the cached IP corresponds, it is shown with the color green. Color red whenever something is wrong. 

I would like to have the colors represented in the widget as well :) That would be enough for my part.
