### ISSUE TITLE
NUT-OS: unable to choose Blazer_USB

### ISSUE THREAD

**Issue by JOduMonT** [opnsense/plugins#2558]
Hi;

I open this as a question, because when I [searched for blazer_usb](https://github.com/opnsense/plugins/issues?q=blazer_usb) it gave me the impression it has been resolved before but sadly, none of these resolved issue, leaded me to fix my situation by myself.

Basically; I have a basic UPS cleanline which use the driver blazer_usb, which works fine with OpenMediaVault and the blazer_usb. When I try to transfer this UPS to OPNsense I have potentially 2 errors.

### 1.1. I'm unable to enable blazer_usb;
when I select blazer_usb, enable and apply; it comes back to the NUT panel, the **USBHID-UPS** driver is enabled.
![image](https://user-images.githubusercontent.com/5204724/135749598-3f63bd60-b13d-4233-9ab9-5bf7ec5dcf6d.png)

*I tried several pirouettes, such as disabling and apply, selecting blazer_usb without enabling and apply, ... without success.*

### 1.2. Inerrant to the first one: via the command line, I'm unable to test my UPS because USBHID-UPS is enabled for my UPS.
![image](https://user-images.githubusercontent.com/5204724/135749501-352616d4-d062-498f-8a70-c079cfdb3b16.png)

So what I'm potentially doing wrong and how I could fix that ?

Thank you :)

**Comment by mimugmail** [comment]
To me it sounds you have usbhid ticked enabled and only one is allowed.
