### ISSUE TITLE
security/acme-client: certificate installing fails

### ISSUE THREAD

**Issue by smindorf** [opnsense/plugins#256]
HI,

Version:

OPNsense 17.7.1_2-amd64
FreeBSD 11.0-RELEASE-p12
OpenSSL 1.0.2l 25 May 2017

Acme Client now works, but the new certificate will not be installed.

```
15:32:37 CEST 2017] Installing full chain to:/var/etc/acme-client/certs/59a50a1d94e960.04057068/fullchain.pem
15:32:37 CEST 2017] Installing key to:/var/etc/acme-client/keys/59a50a1d94e960.04057068/private.key
15:32:37 CEST 2017] Installing CA to:/var/etc/acme-client/certs/59a50a1d94e960.04057068/chain.pem
15:32:37 CEST 2017] Installing cert to:/var/etc/acme-client/certs/59a50a1d94e960.04057068/cert.pem
15:32:36 CEST 2017] _on_issue_success
15:32:36 CEST 2017] And the full chain certs is there: /var/etc/acme-client/home/xxx/fullchain.cer
15:32:36 CEST 2017] The intermediate CA cert is in /var/etc/acme-client/home/xxx/ca.cer
...
15:32:36 CEST 2017] Le_LinkIssuer='https://acme-v01.api.letsencrypt.org/acme/issuer-cert'
15:32:36 CEST 2017] Your cert key is in /var/etc/acme-client/home/xxx/xxx.key
15:32:36 CEST 2017] Your cert is in /var/etc/acme-client/home/xxx/xxx.cer
15:32:36 CEST 2017] Cert success.
```

The webinterface shows me the old one.

I checked on the filesystem:

/var/etc/lighty-webConfigurator.conf
```
...
ssl.pemfile = "/var/etc/cert.pem"
...
```
So I checked the certifiate in `/var/etc/cert.pem`, but this is the **old** one, so not installed.

Also I checked `/var/etc/acme-client/certs/59a50a1d94e960.04057068/cert.pem`, this is the new one.

Kind Regards
Sören

**Comment by fraenki** [comment]
Hi @smindorf, thanks for your report!

Let me begin with an important clarification: the acme plugin will never directly install the certificate outside of /var/etc/acme-client. Instead it will import the certificate to OPNsense's **Certificate Manager**.
Can you confirm that the new certificate is visible in `System -> Trust -> Certificates`?

So to actually use the new certificate you have to select it for the desired use-case. Two things are important:
1. If you want to use the certificate for the WebUI, go to `System -> Settings -> Administration -> SSL Certificate` and choose the Let's Encrypt certificate from the list.
2. To ensure that the WebUI certificate is updated when the certificate is **renewed**, you need to define a `Restart Action` in `Services -> Let's Encrypt -> Restart Actions` and select "Restart OPNsense WebUI" for `Restart Command`. Afterwards just add this new `Restart Action` to your certificate in `Services -> Let's Encrypt -> Certificates`. Note that this will automatically restart the WebUI everytime the certificate is renewed.

HTH.

**Comment by smindorf** [comment]
Hi @fraenki, 

Thank you for your reply.

Yes it is there, two times. The old one and the new one. Both are Let's Encrypt certificates.
The actually one is my old one from OPNSense 17.1.8.
And actually the certificate is set to the old one.

Also I've set the cron to restart the webUI.

As I understand this complete acme client is that I configure the client and it will be automatically renew the certificate and install it fpr the WebUI. But this was not working. Don't know why I've now two LE Certificates in my Tuststore.

Now I've select the new certificate an it was installed correctly.

Kind Regards,
Sören

**Comment by fraenki** [comment]
> As I understand this complete acme client is that I configure the client and it will be automatically renew the certificate and install it fpr the WebUI.

Yes, the acme plugin is able to do this, given that the requirements are all met, as described in [my previous post](https://github.com/opnsense/plugins/issues/256#issuecomment-327745181).

> But this was not working.

I've just retested all of this on my OPNsense test box and it's still working as expected. So even after the changes in #236 it still looks good to me. No regression afaict :)

> Don't know why I've now two LE Certificates in my Tuststore.

Me neither. :( The logs are (hopefully) key to this issue. You can check `System -> Configuration -> History` to find out if the acme plugin _updated_ an **existing certificate** or if it _imported_ a **new certificate** to Certificate Manager. The acme plugin will use the following log messages:

* when importing a new certificate: "Imported Let's Encrypt SSL certificate..."
* when updating an existing certificate: "Updated Let's Encrypt SSL certificate..."

Besides that it might be useful to check `System -> Log File` for further acme log messages.

**Comment by smindorf** [comment]
Ok @fraenki, 

I've checked the History:

```
9/4/17 15:32:37	11.2	174 KB	(root): Updated Let's Encrypt SSL certificate: xxx
8/29/17 09:35:46	11.2	174 KB	(root): Updated Let's Encrypt SSL certificate: xxx
8/29/17 08:51:32	11.2	174 KB	(root): Updated Let's Encrypt SSL certificate: xxx
8/29/17 08:47:35	11.2	174 KB	(root): Imported Let's Encrypt SSL certificate: xxx
```

Now I understand the new Certificate but I don't know where this import comes from.

Maybe from finding the bug #236

Sorry...

Sören

**Comment by fraenki** [comment]
> 8/29/17 08:47:35	11.2	174 KB	(root): Imported Let's Encrypt SSL certificate: xxx

Have you at some point deleted the certificate from `Services -> Let's Encrypt -> Certificates` and recreated it? This would explain why the certificate was imported a second time.

(FYI, the acme plugin records the hidden `certRefId` from OPNsens's Certificate Manager. This information is lost if the certificate is deleted from `Services -> Let's Encrypt -> Certificates`. And the acme plugin will never delete a certificate from the Certificate Manager. That's why a duplicate entry in Certificate Manager is easily possible if the user deletes and recreates the same certificate.)

> Maybe from finding the bug #236

The issue in #236 would not trigger a re-import of the certificate, AFAICT.

**Comment by smindorf** [comment]
Hello @fraenki,

> Have you at some point deleted the certificate from Services -> Let's Encrypt -> Certificates and recreated it? This would explain why the certificate was imported a second time.

I didn't delete here anything. But I've deleted the acme-plugin and installed it again to test what is going wrong before I've reported the Bug #236 
I also switch from production to stable and back. 

> The issue in #236 would not trigger a re-import of the certificate, AFAICT.

Yes you are right. 

Regards
Sören

**Comment by fraenki** [comment]
> I didn't delete here anything. But I've deleted the acme-plugin and installed it again

A plugin reinstall does not trigger a re-import of the certificate.
I'm sorry, I have no explanation for the second certificate import :(

I'd suggest to delete the second certificate from the Certificate Manager, update to 17.7.2 (later this week) and watch if it happens again on next due/renewal date.

>  I also switch from production to stable and back.

Where did you change this setting? Do you mean the Let's Encrypt "Staging" vs. "Production" environment?

**Comment by fraenki** [comment]
I'm closing this now. Feel free to comment or reopen this issue if it happens again or if you can provide further information.
