### ISSUE TITLE
Toggleable WireGuard group interface?

### ISSUE THREAD

**Issue by FingerlessGlov3s** [opnsense/plugins#2577]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

[x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
Should we add the ability to disable/remove the default WireGuard group interface? What's everyone thoughts?

Currently now you can create your own group interfaces in recent versions of OPNsense, I personally think having this default WireGuard group confuses users. which the plugin creates. As they think the interface group is the WireGuard interface but of course its all the WireGuard interfaces, which causes confusion and then wonder why there's a rule page called WireGuard but their interface they assigned is called MyRoadWarrior.

Thoughts?

**Describe the solution you'd like**
Toggle box or removal of the WireGuard group interface in the plugin.

**Describe alternatives you've considered**
Ignoring it which is fine for me but I'm thinking about making things more easier for users to understand.

**Additional context**
![image](https://user-images.githubusercontent.com/3495647/137358823-8fa37635-aee5-4c4b-8a0a-533571619f27.png)
^ Group Interface

**Comment by FingerlessGlov3s** [comment]
https://github.com/opnsense/plugins/commit/891cb2a1d0928c9aeee9fe43cd24b4163af35475 - Commit where group interface got added from the looks of it.

**Comment by mimugmail** [comment]
I'm not sure what the problem is, it's the same behavior like with OpenVPN and IPsec. What should it be different here?

**Comment by FingerlessGlov3s** [comment]
It's not a problem problem, but having the group interfaces there by default for when people are setting up VPNs leads too confusion for new users of OPNsense. IPsec one may make sense, as it works differently to OpenVPN and WireGuard.People also get confused with OpenVPN group interface when creating VPN clients or servers. You don't hear much about IPsec one due to people usually sticking to OpenVPN and WireGuard it seems when they talk about setting up a VPN tunnel on IRC at least.

I'm not sure about you but I never use the group interface created by OpenVPN or WireGuard on any of my OPNsense installs, I always do it on a per interface level.

**Comment by mimugmail** [comment]
And I manage setups with nearly 100 branches connected via OpenVPN S2S, I see different setups about every 2 weeks and I never ever saw an assigned interface in business. And everytime I saw one it was the cause of strange errors why they need professional help. This assigning thing comes from these VPN providers which are mostly used for stuff which might not be legal. 
Dont get me wrong, but I think 90% of all use cases dont need assigning and 5% are due to wrong forum posts

**Comment by mimugmail** [comment]
Like this? https://github.com/opnsense/plugins/blob/master/net/wireguard/src/etc/inc/plugins.inc.d/wireguard.inc#L64
 
![image](https://user-images.githubusercontent.com/20438689/137383426-4bed3095-f086-4feb-9075-3f0dce53bfb3.png)

**Comment by FingerlessGlov3s** [comment]
Yeah that makes more sense, you can tell straight away it's a group interface.

Not sure if it should be like that or maybe a sub headings and under that the group interfaces. So you get all your normally interfaces then you have all your group interfaces, nicely in order.

But what you have there in that screenshot is on the right tracks for sure. 💪

**Comment by psychogun** [comment]
My WireGuard assignments are renamed as; 
* `WG_S2S`
* `WG_RW`

.. so I never touch the `WireGuard` interface. As I do not either with the `OpenVPN` interface, I just edit the `OpenVPN_RW` interface. 

When I started this venture with pfsense/OPNsense, this was not intuitive at first. But, through learning, trying to add more granular rules, remembering, and finally- reading the documentation ;) - I have now a good rule of thumb that I do not use those interfaces. But for new users? It would probably help adding (Group)- as it might trigger them to read the documentation more thoroughly. 

 https://docs.opnsense.org/manual/how-tos/wireguard-client.html 

> Finally, it allows separation of the firewall rules of each WireGuard instance (each wgX device). Otherwise they all need to be configured on the default WireGuard group that OPNsense creates. This is more an organisational aesthetic, rather than an issue of substance

And, maybe, if the documentation (for WireGuard - probably other pages too) could hint back to the Processing order - https://docs.opnsense.org/manual/firewall.html#processing-order it would be easier to comprehend for new users. 

I would not like it to have been ignored / removed, but having a (Group) added is fine by me.

**Comment by mimugmail** [comment]
@fichtner ok for you to label this line https://github.com/opnsense/plugins/blob/master/net/wireguard/src/etc/inc/plugins.inc.d/wireguard.inc#L64 like the one in https://github.com/opnsense/plugins/issues/2577#issuecomment-943663448

**Comment by fichtner** [comment]
@mimugmail sure, why not
