### ISSUE TITLE
NGINX: In most recent Master, reconfigureAction is missing from ServiceController

### ISSUE THREAD

**Issue by bimbar** [opnsense/plugins#2580]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

[X] The title contains the plugin to which this issue belongs

**Describe the bug**
NginX plugin is not calling setup.php on restart.

**To Reproduce**
change something, click apply

**Expected behavior**
Configuration (for example certificated) should be regenerated.

**Screenshots**

**Relevant log files**
If applicable, information from log files supporting your claim.

**Additional context**

**Environment**
Software version used and hardware type if relevant.
e.g.:

OPNsense 19.1.1 (amd64, OpenSSL).
Intel® Xeon™ E3-1225V5 3.3Ghz Quad Core
Network Intel® I210-AT

**fix**

Add the following back into the NginX ServiceController:

`    public function reconfigureAction()
    {
        if ($this->request->isPost()) {
            $this->sessionClose();
            $model = $this->getModel();
            $backend = new Backend();
            if ($this->reconfigureForceRestart()) {
                $backend->configdRun('nginx stop');
            }
            $backend->configdRun('template reload OPNsense/Nginx');
            $runStatus = $this->statusAction();
            if ($runStatus['status'] != 'running') {
                $backend->configdRun('nginx start');
            } else {
                $backend->configdRun('nginx reload');
            }
            return array('status' => 'ok');
        } else {
            return array('status' => 'failed');
        }
    }`

**Comment by fichtner** [comment]
@bimbar Did you mean to close this? reconfigureAction() was removed because it wasn't properly implementing a reload from the parent class which provides reconfigureAction() and does handle that correctly. The code hasn't been released yet due to lack of testing, but at least a missing function should not be the actual problem here.


Cheers,
Franco
