### ISSUE TITLE
GoDaddy DDNS AAAA record update fails

### ISSUE THREAD

**Issue by marjohn56** [opnsense/plugins#2582]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

[X] The title contains the plugin to which this issue belongs

**Describe the bug**
AAAA record updates fail due to what appears to be an issue with the curl_* php functions. Whilst IPv4 addresses update perfectly fine, sending an AAAA update results in  PAYLOAD error. I have temporarily modified the code to call curl directly and that works fine. I suspect this is not an issue with the plugin itself but with php.

**To Reproduce**

1.  Have a GoDaddy domain
2.  Set the AAAA record to something other than your AAAA address,
3.  Setup the DDNS plugin, then Save & Update

**Expected behavior**
It should update the GoDaddy AAAA record entry

OPNsense 21.7.3_3-amd64FreeBSD 12.1-RELEASE-p20-HBSDOpenSSL 1.1.1l 24 Aug 2021
Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz (4 cores)

**Comment by marjohn56** [comment]
PR #2686

**Comment by fichtner** [comment]
38a704a521a1
