### ISSUE TITLE
dyndns: IDN domain names on CloudFlare

### ISSUE THREAD

**Issue by abjugard** [opnsense/plugins#2583]
**Describe the bug**
The CloudFlare plugin does not work with IDN domain names.

CloudFlares API returns the UTF-8 version of internationalised domain names, and OPNsense does not allow inputting the UTF-8 version of an internationalised domain name.

**To Reproduce**
1. Go to 'Services > Dynamic DNS'
2. Add a configuration using an IDN domain name in punycode, using the CloudFlare API token service. Save and force update.
3. Go to System > Log Files > General and search for 'services_dyndns_edit.php'.
4. See error 'UNKNOWN ERROR'

**Expected behavior**
The Dynamic DNS entry updates.

**Screenshots**
N/A

**Relevant log files**
N/A

**Additional context**
Simply using the UTF-8 representation of an IDN domain name would not be a solution here, since the CloudFlare API in some instances expect the punycoded representation, but in other cases return the UTF-8 representation.

The following solves the problem:
Make available for the OS distribution, and add the `php74-intl` package as a dependency to dyndns
Replace:
https://github.com/opnsense/plugins/blob/7a82982f865fb842f7e8bbfa066decaaafec74db/dns/dyndns/src/etc/inc/plugins.inc.d/dyndns/phpDynDNS.inc#L825
With this:
```
if (preg_match("/^{$zoneObj->name}$|\.{$zoneObj->name}$/", idn_to_utf8($fqdn))) {
```

**Environment**
OPNsense 21.7.1-amd64
FreeBSD 12.1-RELEASE-p19-HBSD
OpenSSL 1.1.1k 25 Mar 2021

Netgate SG-2440

**Comment by abjugard** [comment]
@fichtner 

I think entering it as punycode is the correct way to do it. The translated domain name isn't actually codepoint-wise what is being used under the hood in network communication anyway, IDN domain names as they are used today is really a lie, what we are talking about is registered punycoded domains.

The problem in a single sentence is that; the plugin relies on the output from a certain endpoint in the CloudFlare API, and for non-IDN this works fine, but for punycoded domain names this endpoint translates to UTF-8 on the server side, so the check doesn't match on the opnSense side.

**Comment by abjugard** [comment]
Also this isn't really a "support request" as much as it is a bug report that the CloudFlare integration does not take certain CloudFlare behaviour into account when handling responses from it.

**Comment by abjugard** [comment]
@fichtner Any chance we could advance this?

**Comment by IzaacJ** [comment]
Any progress on this?
If not, I might look into it, but it could take me a while (school, family, etc), but I'm also extremely motivated to get this working 😅

**Comment by fraenki** [comment]
@IzaacJ The issue is unassigned, so I guess there's currently nobody working on it. I'd say give it a try and submit a PR :)
