### ISSUE TITLE
net/haproxy: Retries can't be set to 0

### ISSUE THREAD

**Issue by hostalp** [opnsense/plugins#2585]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

[X] The title contains the plugin to which this issue belongs

**Describe the bug**
Currently the minimum value allowed for **Retries** is 1, however HAProxy itself can take 0 as well.
This is useful in some cases with just 1 backend server etc. or generally wherever one wants to achieve a fast-fail behavior.

**To Reproduce**
1. Go to '**Settings: Default Parameters** or **Virtual Services: Backend Pools**'
2. Set '**Retries**' to '**0**'
3. Click on '**Apply**'
4. See error **Please specify a value between 1 and 100.**

**Expected behavior**
Zero value for Retries should be accepted and applied.

**Screenshots**
N/A

**Relevant log files**
N/A

**Additional context**
I've found it at these place, hopefully I didn't miss any:
**Settings: Default Parameters**
**Virtual Services: Backend Pools**

As a workaround, `retries 0` may be specified via _Custom options_ or _Option pass-through_ in advanced mode. This shouldn't be necessary though.

**Environment**
OPNsense 21.7.3_3-amd64
os-haproxy 3.5
haproxy22 2.2.17

**Comment by fraenki** [comment]
This will be available in the upcoming os-haproxy version 3.6.
