### ISSUE TITLE
net/haproxy: SSL being applied to port 80

### ISSUE THREAD

**Issue by atomicom** [opnsense/plugins#2589]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

[x] The title contains the plugin to which this issue belongs

**Describe the bug**
When creating a http/https frontend that listens on both port 80 and 443 with ssl offloading, the ssl certs are also being applied to port 80. Clients will then get an empty response to plain http requests on port 80.

**To Reproduce**
1. Create a frontend that listens on both port 80 and 443
2. enable ssl offloading
3. add rule to redirect http traffic to https

**Expected behavior**
Http traffic is redirected to https.

**Screenshots**

> frontend Test_Redirects
> bind 123.456.789.1:80 name 103.251.168.10:80 ssl crt-list /tmp/haproxy/ssl/616cc908d09101.77214123.certlist
> bind 123.456.789.1:443 name 103.251.168.10:443 ssl crt-list /tmp/haproxy/ssl/616cc908d09101.77214123.certlist
> mode http
> option http-keep-alive
> option forwardfor
> #tuning options
> timeout client 30s
> #logging options
> #ACL: HTTP Traffic
> acl acl_615d757fad27c6.77757010 ssl_fc
> #ACTION: Redirect HTTP to HTTPS
> http-request redirect scheme https code 301 if !acl_615d757fad27c6.77757010
> 

**Additional context**
I've currently worked around the issue by having splitting all my frontends in two, one listens on port 80 without SSL offloading and the other listens on port 443 with SSL offloading. So while I don't believe this to be high priority, it would be nice to have it working so that a single frontend with ssl offloading enabled can accept and process standard http requests.

**Environment**
OPNsense 21.7.3_3-amd64
HA Proxy version 2.2.17-dd94a25

**Comment by fraenki** [comment]
> When creating a http/https frontend that listens on both port 80 and 443 with ssl offloading

Yes, you have to create a frontend for every protocol (HTTP, HTTPS, TCP), you can't combine them into one frontend. This is how it is designed.
