### ISSUE TITLE
net/haproxy: Web UI doesn't notify if there are any pending (unapplied) configuration changes

### ISSUE THREAD

**Issue by hostalp** [opnsense/plugins#2590]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

[X] The title contains the plugin to which this issue belongs

**Describe the bug**
If there are any pending (unapplied) HAProxy configuration changes, this fact isn't highlighted in any way. It would be good to have some notification/warning banner shown in such cases, because it's easy to perform some changes somewhere and then forget to save (apply) them.

**To Reproduce**
1. Change any HAProxy configuration
2. The Web UI looks identical - as in the state before any changes were made. User is kind of blind as for whether any configuration changes were made that weren't applied yet.

**Expected behavior**
A good example of how it might work is **VPN: IPsec** config where any unapplied configuration changes result in a banner being displayed at the top of the page (screenshot provided for reference).

**Screenshots**
![Screenshot Tunnel Settings IPsec VPN](https://user-images.githubusercontent.com/47250981/137718482-184f2a8b-d84f-4f52-8d44-808afc73db94.png)

**Relevant log files**
N/A

**Additional context**
Quite similar problem affects other parts of the OPNsense configuration, for example Firewall. There at least a brief warning to save any configuration changes appears, but it's only for a few seconds and then it doesn't reappear.

**Environment**
OPNsense 21.7.3_3-amd64
os-haproxy 3.5

**Comment by fraenki** [comment]
Thanks, this is indeed a very good suggestion. I will add it in one of the next releases.

**Comment by AdSchellevis** [comment]
we moved away from persisting these, instead we offer the `editAlert` option in grids now which gently reminds people of needing to apply.  (e.g. https://github.com/opnsense/core/commit/ee17fa6c26215dfe2b7bf851ba25b9c6de4ead21)

**Comment by fraenki** [comment]
In https://github.com/opnsense/plugins/pull/2625/commits/a387c1ff86f48a081f8cda2367787c0c2ddecf85 I've implemented the default hint that was mentioned by @AdSchellevis on almost every page, it is only briefly visible. Besides that the plugin already knows if there are pending config changes, so in https://github.com/opnsense/plugins/pull/2625/commits/440e76aa8fd397cd7b1c1fae76cf19654c9f273b I've added a persistent warning based on this functionality.
