### ISSUE TITLE
Postfix - Allow TLS Only removed from config file?

### ISSUE THREAD

**Issue by ElXk6** [opnsense/plugins#2591]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.
https://github.com/opnsense/plugins/issues/2579
This can be closed, would be nice if someone can do it, Thx :)

[x] The title contains the plugin to which this issue belongs

**Describe the bug**
i used to monitor " Allow TLS Only " which was /opnsense/OPNsense/postfix/general/disable_ssl in the xml config in
After upgrading from 21.1.9_1 to 21.7.3_3 its not in the XML anymore .

When i save the xml change the " Allow TLS Only " and then do a diff to the config there seem to be no changes.

**To Reproduce**
grep -r "disable_ssl" /conf/config.xml

**Expected behavior**
Same variable name like befor "disable_ssl" or a new one.
Or does it got changed to "intermediate"?

**Screenshots**
-

**Relevant log files**
-

**Additional context**
-

**Environment**
Software version used and hardware type if relevant.
e.g.:

OPNsense 21.7-amd64
FreeBSD 12.1-RELEASE-p19-HBSD
OpenSSL 1.1.1k 25 Mar 2021

**Comment by mimugmail** [comment]
It was introduced/changed with plugin version 1.19:
https://github.com/opnsense/plugins/pull/2255/files
