### ISSUE TITLE
FRR bgp route-reflector-client, need option on peer context

### ISSUE THREAD

**Issue by sense-f** [opnsense/plugins#2594]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

[x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**

Didn't find route-reflector-client option in context of peer settings in bgp.
Found in FRR documentation that the option can be written in the config file.
https://docs.frrouting.org/en/latest/bgp.html#route-reflector
I set the setting for the peer in the config /usr/local/etc/frr/bgpd.conf, save the file. Then restart Quagga and draw the output in the console:

```
root@OPNsense:/ # /usr/local/bin/vtysh -c "show running-config"
Building configuration...

Current configuration:
!
frr version 7.4
frr defaults traditional
hostname OPNsense.localdomain
log syslog notifications
!
router bgp 65550
 bgp router-id 192.168.1.1
 no bgp ebgp-requires-policy
 neighbor 10.11.1.1 remote-as 65550
 neighbor 10.11.1.1 update-source gre0
 !
 address-family ipv4 unicast
   neighbor 10.11.1.1 route-reflector-client
 exit-address-family
!
line vty
!
end
```
As you can see, the option is accepted and displayed in the running config, but after the opnsense reboot, the setting disappears.

**Describe the solution you'd like**
Please add a checkbox option in the BGP peer context to enable route-reflector-client functionality.

**Describe alternatives you've considered**
No alternatives.

**Comment by sense-f** [comment]
Thanks for your work. I am amazed at your productivity, which even works on your weekends. Could you tell me how to get this plugin fix? In updates, I see only version 1.22_1, how can I get 1.23 from the web interface?

**Comment by sense-f** [comment]
Also I check install from console with grub latest master code, the frr version is only 1.22_1 or develop. What am I doing wrong?

**Comment by mimugmail** [comment]
pkg install git
opnsense-code plugins
cd /usr/plugins/ner/frr
make upgrade

**Comment by sense-f** [comment]
`pkg install git
opnsense-code plugins
cd /usr/plugins/net/frr
make upgrade`
This is exactly what I did. Version 1.22_1 only.
`root@OPNsense:~ # pkg install git
Updating OPNsense repository catalogue...
OPNsense repository is up to date.
All repositories are up to date.
Checking integrity... done (0 conflicting)
The most recent versions of packages are already installed
root@OPNsense:~ # opnsense-code plugins
Fetching origin
Already up to date.
Fetching origin
Already up to date.
root@OPNsense:~ # cd /usr/plugins/net/frr
root@OPNsense:/usr/plugins/net/frr # make upgrade
>>> Generating metadata for os-frr-1.22_1... done
>>> Staging files for os-frr-1.22_1... done
>>> Generated version info for os-frr-1.22_1:
{
    "product_abi": "21.7",
    "product_arch": "amd64",
    "product_email": "franz.fabian.94@gmail.com",
    "product_flavour": "OpenSSL",
    "product_hash": "2269a2a2f",
    "product_id": "os-frr",
    "product_name": "frr",
    "product_version": "1.22_1",
    "product_website": "https://opnsense.org/"
}
>>> Packaging files for os-frr-1.22_1:
file sizes/checksums    [87]: 100%
packing files           [87]: 100%
packing directories      [0]: 100%
Checking integrity... done (0 conflicting)
Deinstallation has been requested for the following 1 packages (of 0 packages in the universe):

Installed packages to be REMOVED:
        os-frr: 1.22_1

Number of packages to be removed: 1
[1/1] Deinstalling os-frr-1.22_1...
[1/1] Deleting files for os-frr-1.22_1: 100%
Reloading plugin configuration
Installing os-frr-1.22_1...
Extracting os-frr-1.22_1: 100%
Stopping configd...done
Starting configd.
*** OPNsense\Quagga\BGP Migration failed, check log for details
*** OPNsense\Quagga\OSPF6 Migration failed, check log for details
*** OPNsense\Quagga\RIP Migration failed, check log for details
Reloading plugin configuration
Configuring system logging...done.
Reloading template OPNsense/Quagga: OK
Reloading template OPNsense/Syslog: OK
`

**Comment by mimugmail** [comment]
Before make upgrade type git pull

**Comment by fichtner** [comment]
Too much false information. 😉

1. opnsense-code downloads git on its own
2. opnsense-code pulls on its own
3. opnsense-code selects the stable branch for the current release by default.

therefore:

    # cd /usr/plugins
    # git checkout master
    # opnsense-code
    # cd net/frr
    # make upgrade

**Comment by mimugmail** [comment]
Was it always using stable branch? Wasnt aware of it

**Comment by fichtner** [comment]
It's trying to check if tools.git has a stable branch for the current ABI configuration and checking that out... that is true for core, plugins and src. When the directory exists it won't change the branch anymore. :)

**Comment by sense-f** [comment]
Guys, I don't know what I would do without you) I think this needs to be added to the instructions for people like me). Thanks again.
