### ISSUE TITLE
mdns-repeater: VRRP Cluster will cause DoS

### ISSUE THREAD

**Issue by 53c70r** [opnsense/plugins#2595]
When using more than one Opnsense with VRRP/CARP with mdns-repeater plugin on all routers enabled (and the fix in #1466) it will cause a Denial of Service since for example two gateways will amplify the repeated mDNS package to each other.
The workaround for this problem is to disable the mDNS repeater on all but one Opnsense host.
Furthermore no mDNS repeater redundancy is given.

**Comment by reitermarkus** [comment]
I have the same problem when mDNS repeater is running on both my OPNsense instances. Weirdly I only experience the problem when connecting via WiFi.

**Comment by 53c70r** [comment]
Trying to use "Enabe CARP Failover" will fail and the service will not start.
Version: 22.1.4_1

```
<13>1 2022-03-29T23:06:55+02:00 opnsense-00 root 70747 - [meta sequenceId="27"] /usr/local/etc/rc.d/mdns-repeater: WARNING: /var/run/mdns-repeater.CARP_MASTER is not readable.
<13>1 2022-03-29T23:06:55+02:00 opnsense-00 root 70998 - [meta sequenceId="28"] /usr/local/etc/rc.d/mdns-repeater: WARNING: failed precmd routine for mdns_repeater
```

**Comment by fichtner** [comment]
@53c70r without further context I will say this is expected following the rule that backup needs the service not to start.

**Comment by 53c70r** [comment]
This was tested on the Master.
Immediate after setting "Enable CARP Failover" and pressing Save, the service goes into fail state, turning the upper right symbol red.

**Comment by 53c70r** [comment]
No file /var/run/mdns-repeater.CARP_MASTER exists when Master is in Master state.

**Comment by fichtner** [comment]
May be worth opening a ticket with steps to reproduce. Thanks.
