### ISSUE TITLE
ospf with openvpn

### ISSUE THREAD

**Issue by ra1nb0w** [opnsense/plugins#261]
Hello,
I am trying to use ospf gui with openvpn but without success. In essence, the gui set openvpn group as single interface (I have two vpn clients) and physical_interface() doesn't resolv to ovpncX. If I change "interface openvpn" in the configuration with "interface ovpnc1" and "interface ovpnc2", the daemon works correctly. Unfortuntaly, I can't add raw interface on the gui so I am not sure how to resolve this issue.
What do you thing?

Thanks for the hard work that you are doing on opnsense!

**Comment by fabianfrz** [comment]
The GUI framework does not have this option as far as I know. Maybe @AdSchellevis knows more.

@AdSchellevis: Does an Interface field support this?

**Comment by AdSchellevis** [comment]
As far as I know we don't keep track of the raw openvpn interfaces, in theory we should be able to rename them and force them to something predictable (like with vlan's). 
If an interface rename works, we need changes to openvpn (both client and server), registration of the interfaces, etc. 

Unfortunately I don't have a lot of time available at the moment, first real question is, can we force the openvpn interface to something predictable/preset.

**Comment by fabianfrz** [comment]
@AdSchellevis there is a `dev` option for a persistent tun or tap device.

**Comment by AdSchellevis** [comment]
ok, that could work, the challenge probably lies in the migration and possibly creating the device before openvpn starts (not sure what it does, can't test it at the moment).

**Comment by fabianfrz** [comment]
@AdSchellevis this is something that might be handled with care anyway as it may also split up the firewall section for OpenVPN so it might be a very breaking change.

**Comment by AdSchellevis** [comment]
@fabianfrz yes, handle with care :) but if we can force the use of the correct device name and we're making sure that the openvpn group is still assigned to all, it should be possible. 

But like I said, I don't have a lot of time at the moment, maybe it's better to park the issue in core with a different description (something like "assign interfaces to openvpn sessions")....  although it might take quite some time to materialise, there more use-cases where this could be practical.

**Comment by ra1nb0w** [comment]
Ok. I understood. I check out the code for other ideas but you are right, it's a breaking change and not quite easy. At least, not for me. I noticed that unbound see the right openvpn interfaces but the code is a mixture of php and html so probably is useless as ospf is a plugin and unbound a core (probably old) module.
Just one question for @fabianfrz : what/where is the dev option?

anyway, thank @fabianfrz and @AdSchellevis  for the support.
In the meantime, I use manual configuration of ospfd.conf.

**Comment by fabianfrz** [comment]
The dev option is an option in the config file of OpenVPN which makes OpenVPN use the given tun or tap device. In this case the Interface can be handled as all other interfaces of the system and therefore does not need to be grouped anymore.

**Comment by ra1nb0w** [comment]
a ok, an option of openvpn.
What we do with this ticket? create a new one as suggested by @AdSchellevis ?

**Comment by fabianfrz** [comment]
I'd close this one.

**Comment by ra1nb0w** [comment]
ok. I close
