### ISSUE TITLE
Quick fix:

### ISSUE THREAD

**Issue by schattencr** [opnsense/plugins#2624]
Quick fix:

```
opnsense-patch -c plugins 31b82cd 18cd9f6
```

Sorry for the trouble :-/

_Originally posted by @fraenki in https://github.com/opnsense/plugins/issues/2616#issuecomment-954136985_

Hi, good night

I did this and now I'm getting these errors

[NOTICE] 302/200618 (52483) : haproxy version is 2.2.17-dd94a25
[ALERT] 302/200618 (52483) : parsing [/usr/local/etc/haproxy.conf.staging:62] : errorfile : '/tmp/haproxy/errorfiles/617de220e2a3f2.90833152.txt': unabled to parse headers (error offset: 0)
[ALERT] 302/200618 (52483) : Error(s) found in configuration file : /usr/local/etc/haproxy.conf.staging
[ALERT] 302/200618 (52483) : Fatal errors found in configuration.

**Comment by schattencr** [comment]
Never mind, found the issue, it was on the line 62, I deleted it and now works...

**Comment by fraenki** [comment]
> errorfile : '/tmp/haproxy/errorfiles/617de220e2a3f2.90833152.txt': unabled to parse headers (error offset: 0)

You've created an invalid error file. You need to fix it or the issue will re-appear.

**Comment by schattencr** [comment]
how come? I had  the issue #2616, but also a miss configuration on the error message section, but now it is working good

**Comment by fraenki** [comment]
The HAProxy error message is clear on this. The issue #2616 prevented syntax checks, so your broken error file could not be identified earlier.

**Comment by fraenki** [comment]
> errorfile : '/tmp/haproxy/errorfiles/617de220e2a3f2.90833152.txt': unabled to parse headers (error offset: 0)

To elaborate further on this: the required HTTP headers are missing from the error file. This is a common mistake. People often add a custom error message like "501 error error", but the error file must also contain the full HTTP headers.

See the HAProxy documentation for more information:
http://cbonte.github.io/haproxy-dconv/2.2/configuration.html#errorfile%20(Alphabetically%20sorted%20keywords%20reference)
https://www.haproxy.com/de/blog/serve-dynamic-custom-error-pages-with-haproxy/

**Comment by schattencr** [comment]
Yes, I had The issue #2616, but I ran opnsense-patch -c plugins 31b82cd 18cd9f6, then I was getting the other error but I found it was also a miss configuration on the error message, fixed, now it is working good, sites up and running :)
