### ISSUE TITLE
security/acme-client: deploy certificates to Webhooks (Unifi Controller)

### ISSUE THREAD

**Issue by arnho72** [opnsense/plugins#2627]
[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

[x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
The plugin os-acme-client does not purpose deployement with official deployhooks of acme.sh script.

**Describe the solution you'd like**
Create a new automation which offers the deployment of certificates to Unifi Controler and remote server through SSH access using the already existing deployment hook script from acme.sh.
https://github.com/acmesh-official/acme.sh/wiki/deployhooks

**Additional context**
This request is at the same context that https://github.com/opnsense/plugins/issues/2236

Many thanks,
Arnaud Hercé

**Comment by fraenki** [comment]
Deploying certs using SSH is already possible using the "SFTP" automation, so there's not need to support the "ssh" deployhook. However, I'll consider adding support for the "unifi" deployhook in a future release.

**Comment by c0nsumer** [comment]
> Deploying certs using SSH is already possible using the "SFTP" automation, so there's no need to support the "ssh" deployhook.

The ssh deployhook mentions this:

> DEPLOY_SSH_REMOTE_CMD Command to execute on the remote server after copying any certificates. This could be any additional command required for example to stop and restart the service.

It would be really nice to have this, so remote services could be restarted post-deployment.

**Comment by adn77** [comment]
If I may jump on this... having a **[unifi](https://github.com/acmesh-official/acme.sh/wiki/deployhooks#23-deploy-the-cert-on-a-unifi-controller-or-cloud-key)** deployhook would also be desirable when the Unifi controller runs on OPNsense natively.

**Comment by fraenki** [comment]
> I'll consider adding support for the "unifi" deployhook in a future release

I took a look at the ["unifi" deploy hook](https://github.com/acmesh-official/acme.sh/blob/master/deploy/unifi.sh) and noticed that this does not work with the UniFi **API**. Instead it targets _local_ installations of UniFi, which are currently not supported on OPNsense – there's no plugin available.

It's a real bummer that the deploy hook does not use the UniFi API and this is a showstopper for _me_. I will not work on an unsupported feature.

**Comment by fraenki** [comment]
Thanks to a contribution from @adn77 this will be available in the upcoming os-acme-client 3.6. (It still covers an unsupported/unofficial modification, so I will not provide support for it.)
