### ISSUE TITLE
Plugin for telegraf

### ISSUE THREAD

**Issue by fenice2** [opnsense/plugins#263]
As grafana and its acolytes are becoming more popular as a monitoring solution - would it be possible to get the current version of telegraf added as a plugin. I'm quite happy to configure this manually without any UI for the moment.

**Comment by fabianfrz** [comment]
Should not that be possible with collectd?

**Comment by fichtner** [comment]
Hi @fenice2,

We have a ticket here, enough responses now and build power to make this happen:

https://github.com/opnsense/core/issues/1626

I'm closing this duplicate, as we are talking about the package, not the plugin as per your request.

The package will be available with 17.7.3.

Chances are good that someone will start a plugin in the mid-term. :)


Cheers,
Franco
