### ISSUE TITLE
FreeRADIUS server certificate expired if LetsEncrypt is used (WPA2-Enterprise authentication)

### ISSUE THREAD

**Issue by sraspe** [opnsense/plugins#2630]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x]  I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
Since some time (possibly since September 29 2021) my FreeRADIUS server stopped working. The log shows a "certificate expired" error.
When using a self signed certificate (Signed by a local CA installed on the client) for the server it does succeed authentication.
FreeRADIUS is set-up to authenticate WiFi clients (WPA2-Enterprise) using certificates.

**To Reproduce**
1. Create local CA
2. Create certificate for user (Phone) signed by local CA
3. Create certificate for OPNsense signed by local CA
4. Create/install LetsEncrypt certificate
5. Install FreeRADIUS
6. Configure Client (AccessPoint) including IP OPNsense and Secret) - depends on your accesspoint/client)
7. Configure FreeRADIUS Client (AccessPoint) including IP and Secret
8. Configure FreeRADIUS User on  (Phone)
9. Configure FreeRADIUS EAP. Set Type=TLS, Root Certificate=internal CA, Server Certificate=LetsEncrypt certificate
10. Configure User (Phone) to connect to wifi. Set method/type=EAP, CA certificate=internal system certificates, domain=OPNsense FQDN, identity=created user

This will result in the following **error**:
`Auth: (23) Login incorrect (eap_tls: (TLS) Alert read:fatal:certificate expired): [Phone/<via Auth-Type = eap>] (from client Accesspoint port 0 cli XX-XX-XX-XX-XX-XX)`
The connection on the user (phone) fails.

Change steps 9 and 10 to:
9. Configure FreeRADIUS EAP. Set Type=TLS, Root Certificate=internalCA, Server Certificate=**OPNsense certificate**
10. Configure User (Phone) to connect to wifi. Set method/type=EAP, CA certificate=**internal CA**, domain=OPNsense FQDN, identity=created user

This will result in **success**:
`Auth: (6) Login OK: [Phone/<via Auth-Type = eap>] (from client Accesspoint port 0 cli XX-XX-XX-XX-XX-XX)`
The connection on the user (Phone) succeeds.

**Environment**
Firmware: OPNsense 21.7.4
Plugin: os-freeradius 1.9.16
Access-point: Ubiquiti UAP-AC-Pro
Phone: Pixel 6 (verified with old Pixel 3) running Android 12 (November update)

**Possible Issue**
My suspicion is that this is caused by the Expired LetsEncrypt Intermediate CA still used by the FreeRADIUS plugin. But I could be mistaken.
Since this is not a web-server, but goes through the access-point  I cannot use the openssl client to validate the certificate chain, at least I don't know how.

**Comment by mimugmail** [comment]
This is rather an issue for core since Freeradius doesnt handle certificates. But you should really consider switching to a private CA when it comes to privacy.

**Comment by kulikov-a** [comment]
any chance that you have expired R3 intermediate CA cert in System: Trust: Certificates ?

**Comment by sraspe** [comment]
> This is rather an issue for core since Freeradius doesnt handle certificates. But you should really consider switching to a private CA when it comes to privacy.

I think having a global cert is just as safe, but better for maintenance: Client certificates are still created by a private CA with all security advantages. The only cert that is external id to identify the server. This is the same as any website and is I think sufficient to do certificate authentication. The main advantage is that you don't have to install a RootCA on the clients. I think this is both better for maintainability and safer from the phone perspective (to not have an extra RootCA in there that could be compromised (probably easier than a formal RootCA).




> any chance that you have expired R3 intermediate CA cert in System: Trust: Certificates ?

No, I have 4 rootCAs of which none are expired. I do have the Letsencrypt R3 CA in there, but it is valid until September 15 2025.

**Comment by kulikov-a** [comment]
@sraspe hm. may be a "long chain" issue?
are you importing intermediate certificates into the store? (System: Settings: General-> Store intermediate)?
how many certificates are visible in the Certificate data field when trying to edit the R3 CA cert?

**Comment by sraspe** [comment]
> @sraspe hm. may be a "long chain" issue? are you importing intermediate certificates into the store? (System: Settings: General-> Store intermediate)? 

No, store intermediate is disabled (Check-mark is off).

> how many certificates are visible in the Certificate data field when trying to edit the R3 CA cert?

There are two certificates in the R3 CA cert (Didn't expect that, thanks). I don't think it is the problem though:
- ISRG Root X1 valid until Sept 15 2025
- DST Root CA X3 valid until Sept 30 2024
(I copied both certs separately in a file and used Openssl to check the details)

**Comment by kulikov-a** [comment]
@sraspe 
got it, thanks. 
not using a FreeRADIUS (yet?), so only a guess: 
at the moment, the `auto_chain` option is enabled by default (they are going to get rid of it, judging by the commits in the master branch https://github.com/FreeRADIUS/freeradius-server/commit/72fd8198bdc427e238a590e5d845e5c4472bb0f1).
Thus, the expired `DST Root CA X3` root cert can be taken from the trusted store, where it is still present. and the `ISRG Root X1` certificate can point to it, since the acme plug-in receives a long chain.
if I'm right, then in theory, cutting out the `ISRG Root X1` certificate from the `R3 CA`  list on the System: Trust: Authorities  page should help.
https://github.com/opnsense/core/issues/5257#issuecomment-933668219

**Comment by sraspe** [comment]
@kulikov-a 
Thank worked like a charm! Thanks a lot!
