### ISSUE TITLE
Zerotier: Zerotier plugin does not use upnp to open ports

### ISSUE THREAD

**Issue by mgiammarco** [opnsense/plugins#2632]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

[X] The title contains the plugin to which this issue belongs

**Describe the bug**
I have an opnsense 21.7.4. I install zerotier. The opnsense is connected to internet using a router with upnp enabled.
I expect zerotier to open a port using upnp so I can have a DIRECT connection.

(the upnp router is correctly configured if I try with linux or windows opnsense I see the upnp rule immediately added)

**To Reproduce**

1) Install zerotier in an opnsense under a upnp firewall
2) Connect zerotier to a zerotier network.
3) check if a upnp rule is added by zerotier in the firewall

**Expected behavior**

A pnp rule is added to the firewall. Zerotier start to use direct connection and not relayed.

**Screenshots**
none

**Relevant log files**
none

**Additional context**
none

**Environment**

    Device: OpnSense 21.7.4
    OS/Distribution opnsense
    ZeroTier Version 1.6.6

**Comment by AdSchellevis** [comment]
I don't think zerotier generates any rules, and in most cases it's best to not assume policies from the plugins either.  In some rare cases auto generated rules are practical if they can never lead to unambiguous behaviour.

**Comment by mgiammarco** [comment]
Sorry I try to explain better. 
Zerotier official behaviour is to check if is installed on a device with a public ip. If it is not it sends an upnp request to the firewal directly connected to internet to open a specific port. In the case above opnsense is slave to another firewall that is direct connected to internet. That firewall does not receive the upnp request. I suppose is a bug of zerotier plugin or it is disabled by choice. Anyway it is wrong.

**Comment by sjansen1** [comment]
I would recommend looking at your opnsense box an check if any upnp traffic gets generated. Maybe multicast is blocked on your opnsense "wan" port etc..
