### ISSUE TITLE
HAProxy 3.6 doesn't log requests

### ISSUE THREAD

**Issue by walbroehl** [opnsense/plugins#2639]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

[x] The title contains the plugin to which this issue belongs

**Describe the bug**
after installation of 21.7.4 with haproxy 3.6 at first no config could be saved, the quick fix did work (opnsense-patch -c plugins 31b82cd 18cd9f6) and was also neccessary when updating from 21.7.3_3 and haproxy 3.5 to the newest versions.

However no connections are logged on new installations but on the updated ones.
Config files are identical.

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)
revert to 3.5 doesn't do the trick.

even after the quick-fix the following lines are logged each time the config is applied, with or wihtout changes to it:

**Relevant log files**
`configd.py[19380]: [3bddcfd1-5e70-46af-a302-136239527043] requesting haproxy status
configd.py[19380]: [abafd138-39bf-4627-9f86-9dfeb6f21296] generate template OPNsense/HAProxy
configd.py[19380]: generate template container OPNsense/HAProxy
configd.py[19380]: [abafd138-39bf-4627-9f86-9dfeb6f21296] Inline action failed with OPNsense/HAProxy OPNsense/HAProxy/haproxy.conf expected token ',', got 'integer' at Traceback (most recent call last):   File "/usr/local/opnsense/service/modules/template.py", line 247, in _generate     j2_page = self._j2_env.get_template(template_filename)   File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 997, in get_template     return self._load_template(name, globals)   File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 958, in _load_template     template = self.loader.load(self, name, self.make_globals(globals))   File "/usr/local/lib/python3.8/site-packages/jinja2/loaders.py", line 137, in load     code = environment.compile(source, name, filename)   File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 757, in compile     self.handle_exception(source=source_hint)   File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception     raise rewrite_traceback_stack(source=source)   File "/usr/local/opnsense/service/modules/../templates/OPNsense/HAProxy/haproxy.conf", line 136, in template     {%                 set acl_enabled = '0' %} jinja2.exceptions.TemplateSyntaxError: expected token ',', got 'integer'  During handling of the above exception, another exception occurred:  Traceback (most recent call last):   File "/usr/local/opnsense/service/modules/processhandler.py", line 506, in execute     return ph_inline_actions.execute(self, inline_act_parameters)   File "/usr/local/opnsense/service/modules/ph_inline_actions.py", line 51, in execute     filenames = tmpl.generate(parameters)   File "/usr/local/opnsense/service/modules/template.py", line 341, in generate     raise render_exception   File "/usr/local/opnsense/service/modules/template.py", line 332, in generate     for filename in self._generate(template_name, create_directory):   File "/usr/local/opnsense/service/modules/template.py", line 249, in _generate     raise Exception("%s %s %s" % (module_name, template_filename, templExc)) Exception: OPNsense/HAProxy OPNsense/HAProxy/haproxy.conf expected token ',', got 'integer'
configd.py[19380]: [773052d2-9d0f-4122-a646-68161c60aea0] setup haproxy service requirements
configd.py[19380]: [a22c6395-f6c1-4fb3-82ef-5902c3f28cad] request pf current overall table record count and table-entries limit
configd.py[19380]: [c12655b5-54ab-4f2a-8881-7b8373e57c18] request pf current overall table record count and table-entries limit
configd.py[19380]: [42c36f2d-64bb-417b-9ea2-74901a6cdc6c] request pf current overall table record count and table-entries limit
configd.py[19380]: [0b3423a2-49e7-4731-8d1e-9b526014f258] request pf current overall table record count and table-entries limit
configd.py[19380]: [1b7402c0-9fcc-4805-b748-d8f40d9e4495] testing haproxy configuration
configd.py[19380]: [2fb09a74-1bba-4fe3-85a8-e78ce30160c0] generate template OPNsense/HAProxy
configd.py[19380]: generate template container OPNsense/HAProxy
configd.py[19380]: [2fb09a74-1bba-4fe3-85a8-e78ce30160c0] Inline action failed with OPNsense/HAProxy OPNsense/HAProxy/haproxy.conf expected token ',', got 'integer' at Traceback (most recent call last):   File "/usr/local/opnsense/service/modules/template.py", line 247, in _generate     j2_page = self._j2_env.get_template(template_filename)   File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 997, in get_template     return self._load_template(name, globals)   File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 958, in _load_template     template = self.loader.load(self, name, self.make_globals(globals))   File "/usr/local/lib/python3.8/site-packages/jinja2/loaders.py", line 137, in load     code = environment.compile(source, name, filename)   File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 757, in compile     self.handle_exception(source=source_hint)   File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception     raise rewrite_traceback_stack(source=source)   File "/usr/local/opnsense/service/modules/../templates/OPNsense/HAProxy/haproxy.conf", line 136, in template     {%                 set acl_enabled = '0' %} jinja2.exceptions.TemplateSyntaxError: expected token ',', got 'integer'  During handling of the above exception, another exception occurred:  Traceback (most recent call last):   File "/usr/local/opnsense/service/modules/processhandler.py", line 506, in execute     return ph_inline_actions.execute(self, inline_act_parameters)   File "/usr/local/opnsense/service/modules/ph_inline_actions.py", line 51, in execute     filenames = tmpl.generate(parameters)   File "/usr/local/opnsense/service/modules/template.py", line 341, in generate     raise render_exception   File "/usr/local/opnsense/service/modules/template.py", line 332, in generate     for filename in self._generate(template_name, create_directory):   File "/usr/local/opnsense/service/modules/template.py", line 249, in _generate     raise Exception("%s %s %s" % (module_name, template_filename, templExc)) Exception: OPNsense/HAProxy OPNsense/HAProxy/haproxy.conf expected token ',', got 'integer'
configd.py[19380]: [8d3ab7e4-ad2c-4472-9865-5c1f199600cc] requesting haproxy status
configd.py[19380]: [9f144ce7-5bf4-49cb-81f4-6f6ae12c1ca8] reloading haproxy
configd.py[19380]: [acc04514-f23c-463d-af4b-6cb39c31283d] request pf current overall table record count and table-entries limit
configd.py[19380]: [201e59ad-4fd2-4c06-82c5-569ca69c7b0a] request pf current overall table record count and table-entries limit
configd.py[19380]: [37850e37-9d3b-4287-9eb0-c832fe4245bc] request pf current overall table record count and table-entries limit
configd.py[19380]: [9f1fec7e-e204-4576-8f51-d5dbe4c54d6c] request pf current overall table record count and table-entries limit`

**Comment by fraenki** [comment]
> the quick fix did work

Then the patch was probably not applied correctly. Either wait for the next release of provide the output of the opnsense-patch command.

**Comment by walbroehl** [comment]
> > the quick fix did work
> 
> Then the patch was probably not applied correctly. Either wait for the next release or provide the output of the opnsense-patch command. Maybe it's best to revert the updated OPNsense installations to the previous release.
> 
> In any case, this duplicates #2616.

NO it is not a duplicate!

Issue was that no **config could be written**. I'm stating that **no connections are logged** on a fresh installation.
Totally different issues!

Also if you would care to read the given log entries, you would notice that there are multiple files with multiple lines mentioned and the patch only addresses two files with one line each.

**Comment by walbroehl** [comment]
here is your patch output:
`Found local copy of 31b82cd, skipping fetch.
Found local copy of 18cd9f6, skipping fetch.
Hmm...  Looks like a unified diff to me...
The text leading up to this was:
--------------------------
|From 31b82cdd2e43724c3e1873821e961469b99433db Mon Sep 17 00:00:00 2001
|From: kulikov-a <36099472+kulikov-a@users.noreply.github.com>
|Date: Thu, 28 Oct 2021 20:32:48 +0300
|Subject: [PATCH] typo
|
|---
| .../opnsense/service/templates/OPNsense/HAProxy/haproxy.conf    | 2 +-
| 1 file changed, 1 insertion(+), 1 deletion(-)
|
|diff --git a/net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf b/net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf
|index 7d11f3df99..d6e0624ef3 100644
|--- a/net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf
|+++ b/net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf
--------------------------
Patching file opnsense/service/templates/OPNsense/HAProxy/haproxy.conf using Plan A...
Reversed (or previously applied) patch detected!  Assuming -R.Hunk #1 succeeded at 131.
done
Hmm...  Looks like a unified diff to me...
The text leading up to this was:
--------------------------
|From 18cd9f647799b061371e9c0eabbeefd5da12c78b Mon Sep 17 00:00:00 2001
|From: kulikov-a <36099472+kulikov-a@users.noreply.github.com>
|Date: Thu, 28 Oct 2021 20:34:26 +0300
|Subject: [PATCH] indentfirst->first
|
|https://jinja.palletsprojects.com/en/3.0.x/templates/#jinja-filters.indent
|---
| .../opnsense/service/templates/OPNsense/HAProxy/sslCerts.yaml   | 2 +-
| 1 file changed, 1 insertion(+), 1 deletion(-)
|
|diff --git a/net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/sslCerts.yaml b/net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/sslCerts.yaml
|index fd766e0025..2f7d7a4eec 100644
|--- a/net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/sslCerts.yaml
|+++ b/net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/sslCerts.yaml
--------------------------
Patching file opnsense/service/templates/OPNsense/HAProxy/sslCerts.yaml using Plan A...
Reversed (or previously applied) patch detected!  Assuming -R.Hunk #1 succeeded at 53.
done
All patches have been applied successfully.  Have a nice day.
`

Patches were applied and I was able to safe the configuration. But on a fresh installation no connections are logged, on an upgrade they still are. 
I manage more than a dozen OPNsense systems, none of them cloned, all manually configured with the same HAproxy config output, but only the ones who were configured after 3.6 was installed do not work.
So my guess is that although the patches were applied successfully the other lines mentioned in the first post interfere with logging.
But since you are so certain it is a duplicate, the patches only address the saving issue, not the one I mentioned.

**Comment by fichtner** [comment]
> But on a fresh installation no connections are logged, on an upgrade they still are.

What kind of expectation is that. Upgrade to latest, see if issue persists. We do not have a time machine to fix previous versions.

**Comment by walbroehl** [comment]
> > But on a fresh installation no connections are logged, on an upgrade they still are.
> 
> What kind of expectation is that. Upgrade to latest, see if issue persists. We do not have a time machine to fix previous versions.

are you sure you comprehend english?
If I update a system there is no issue with connection logging

If I install a blank system, apply all OS patches and install the plugins, then no connections will be logged although the config is identical to another system where the updates and patches were applied later and which are logging.

Don't be rude just because you didn't have any coffee yet ...

**Comment by fichtner** [comment]
Ok, bye.
