### ISSUE TITLE
net/haproxy: Add limit for maximum connections to the backend server

### ISSUE THREAD

**Issue by hostalp** [opnsense/plugins#2641]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

[X] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
It would be nice to be able to set the server and default-server option `maxconn` (Maximum connections to the backend server).
http://cbonte.github.io/haproxy-dconv/2.2/configuration.html#5.2-maxconn

**Describe the solution you'd like**
This setting should be available in:
1. **Default Parameters** section (where it should go to the `default-server` option just like `init-addr last,libc`).
2. **Real Servers** section (just like the _Check interval_).
3. And you can even add it into the **Backend Pools** for convenience and consistency just like the _Check interval_, but that isn't that necessary.

**Describe alternatives you've considered**
Currently I have to rely on the pass-through options in order to set that.

**Additional context**
None

**Comment by fraenki** [comment]
This will be available in the upcoming os-haproxy 3.8.
