### ISSUE TITLE
net/haproxy: Default timeouts duplicated in haproxy.cfg backend configs

### ISSUE THREAD

**Issue by hostalp** [opnsense/plugins#2642]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

[X] The title contains the plugin to which this issue belongs

**Describe the bug**
In **Settings: Default Parameters** when i configure:
- **Client Timeout**
- **Connection Timeout**
- **Server Timeout**

And then don't configure (= leave blank) the same parameters in **Virtual Services: Backend Pools**
Each backend in the generated haproxy config file will still contain `timeout connect`, `timeout check` and `timeout server` entries copied from the `defaults` section (where they exist as well of course) which is unnecessary as defaults are enough in this case.

**To Reproduce**
1. Go to 'Settings: Default Parameters'
2. Set either of 'Client Timeout', 'Connection Timeout', 'Server Timeout'
3. Make sure the same parameters aren't set in at least some 'Virtual Services: Backend Pools'
4. Save & Apply the configuration
5. Go to 'Config Export'
6. See that the same `timeout connect`, `timeout check` or `timeout server` values are set in both 'defaults' as well as 'backend' sections.

**Expected behavior**
If any of these timeouts aren't explicitly set in the backend configuration they shouldn't be generated into the haproxy config file.

**Screenshots**
N/A

**Relevant log files**
N/A

**Additional context**
None

**Environment**
OPNsense 21.7.5 (amd64, OpenSSL).
haproxy22 2.2.17
os-haproxy 3.7

**Comment by fraenki** [comment]
The duplication of global defaults will be fixed in os-haproxy 4.0 (scheduled for inclusion in OPNsense 23.1).
