### ISSUE TITLE
net/relayd: haproxy logging duplicated due to the current relayd syslog config

### ISSUE THREAD

**Issue by hostalp** [opnsense/plugins#2643]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

[X] The title contains the plugin to which this issue belongs

**Describe the bug**
Note: This is related to #2587, see especially https://github.com/opnsense/plugins/issues/2587#issuecomment-955969617.
Currently, the **/usr/local/etc/syslog-ng.conf.d/syslog-ng-local.conf** file contains the following:
```
filter f_local_relayd {
    program("haproxy") or
    program("relayd");
};
```
The `program("haproxy")` entry causes duplicated haproxy logging which is unnecessary as there's a separate handling of haproxy logging.

**To Reproduce**
1. View file '/usr/local/etc/syslog-ng.conf.d/syslog-ng-local.conf'
2. Find the 'relayd' configuration section
3. See `program("haproxy")` in the 'f_local_relayd' filter definition

**Expected behavior**
The `program("haproxy")` entry shouldn't be present in the relayd configuration section.

**Screenshots**
N/A

**Relevant log files**
N/A

**Additional context**
This comes from https://github.com/opnsense/core/blob/master/src/opnsense/service/templates/OPNsense/Syslog/local/relayd.conf#L5

**Environment**
OPNsense 21.7.5 (amd64, OpenSSL).
os-relayd 2.6
haproxy22 2.2.17
os-haproxy 3.7

**Comment by AdSchellevis** [comment]
This more or less is a remnant of previous migrations it seems, moved and changed the relayd target to the plugin where it belongs
