### ISSUE TITLE
telegraf - option to apply insecure_skip_verify = true for InfluxDB2

### ISSUE THREAD

**Issue by giterest** [opnsense/plugins#2648]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[-] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[-] I have searched the existing issues and I'm convinced that mine is new.

[-] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
After each opnsense-reboot, I have to manually edit telegraf.conf in order to add insecure_skip_verify = true to it.

**Describe the solution you'd like**
Could you please add an option in the GUI that sets insecure_skip_verify = true (also) for influxDB 2?

**Describe alternatives you've considered**
The only alternative is to either manually add that line to telegraf.conf or write a script that would do it after boot.

**Additional context**
none.

**Comment by fichtner** [comment]
Strange timing, was added in 21.7.5. 🤷‍♂️

**Comment by giterest** [comment]
Hi there, i **am** on OPNsense 21.7.5-amd64, tried every option available, but still:
`E! [agent] Error writing to outputs.influxdb_v2: Post "https://influxdb-host:port/api/v2/write?bucket=telegraf&org=default": x509: certificate signed by unknown authority`

- Disable SSL verification = true
- Enable Influx v2 Output = true

If I nano' into the .conf, the line is missing. I have to add it manually, restart the service - afterwards it's fine. After reboot, the line is gone and I have to do it again.

**Comment by fichtner** [comment]
Short of fixing your chain there might be a bug in the template configuration. Should be easy to spot but not near a computer today.

**Comment by kulikov-a** [comment]
@fichtner imho insecure_skip_verify is added for v1 only for now. [outputs.influxdb_v2] part of the template not contains this directive

**Comment by fichtner** [comment]
Ok, so that means we need a new setting since the plugin splits v1/v2 setup.

**Comment by fichtner** [comment]
@mimugmail ftw!

**Comment by giterest** [comment]
many thanks, guys - have a nice day :)
