### ISSUE TITLE
sysutils/monit: filesystem statistics error -- cannot parse device '/dev/gpt/rootfs'

### ISSUE THREAD

**Issue by Woi** [opnsense/plugins#265]
Hey,

my system log gets spammed by the following message since weeks or even month:
```
Sep 14 10:59:07 | monit[53265]: filesystem statistics error -- cannot parse device '/dev/gpt/rootfs'
Sep 14 10:57:07 | monit[53265]: filesystem statistics error -- cannot parse device '/dev/gpt/rootfs'
Sep 14 10:55:07 | monit[53265]: filesystem statistics error -- cannot parse device '/dev/gpt/rootfs'
Sep 14 10:53:07 | monit[53265]: filesystem statistics error -- cannot parse device '/dev/gpt/rootfs'
Sep 14 10:51:07 | monit[53265]: filesystem statistics error -- cannot parse device '/dev/gpt/rootfs'
Sep 14 10:49:07 | monit[53265]: filesystem statistics error -- cannot parse device '/dev/gpt/rootfs'
Sep 14 10:47:07 | monit[53265]: filesystem statistics error -- cannot parse device '/dev/gpt/rootfs'
```

On `ui/monit/status/` everything looks fine:

```
Monit 5.23.0 uptime: 8d 2h 58m

System 'opnsense.example.com'
  status                       OK
  monitoring status            Monitored
  monitoring mode              active
  on reboot                    start
  load average                 [0.42] [0.34] [0.27]
  cpu                          1.9%us 1.6%sy
  memory usage                 628.3 MB [15.5%]
  swap usage                   0 B [0.0%]
  uptime                       8d 3h 0m
  boot time                    Wed, 06 Sep 2017 11:47:53
  data collected               Thu, 14 Sep 2017 14:47:15

Filesystem 'RootFs'
  status                       OK
  monitoring status            Monitored
  monitoring mode              active
  on reboot                    start
  filesystem type              ufs
  filesystem flags             soft updates, noatime, local, rootfs
  permission                   755
  uid                          0
  gid                          0
  block size                   4 kB
  space total                  13.5 GB (of which 8.0% is reserved for root user)
  space free for non superuser 11.2 GB [82.8%]
  space free total             12.2 GB [90.8%]
  inodes total                 1845886
  inodes free                  1809716 [98.0%]
  data collected               Thu, 14 Sep 2017 14:47:15
```

The file however is there:
```
~ # ls -l /dev/gpt/rootfs 
crw-r-----  1 root  operator  0x56 Sep  6 11:47 /dev/gpt/rootfs
```

Could this be a configuration import/export problem as in https://github.com/opnsense/plugins/issues/243?

OPNsense version strings:
```
OPNsense 17.7.2-amd64
FreeBSD 11.0-RELEASE-p12
LibreSSL 2.5.5
```

**Comment by fichtner** [comment]
Hi woi,

We recently talked about this here, it seems to be a spurious log error in monit:

https://forum.opnsense.org/index.php?topic=5358.msg24789#msg24789

Reporting it upstream would probably be the best course of action.


Cheers,
Franco

**Comment by Woi** [comment]
What is upstream in this case: FreeBSD or Monit Project?

**Comment by fichtner** [comment]
monit, looks like it tries to dispatch a command that freebsd doesn't support or dispatches it in a way that freebsd doesn't like.

**Comment by Stephanowicz** [comment]
Hi,

I reported it on [freebsd ](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=222312) 
and on [tildeshlash](https://bitbucket.org/tildeslash/monit/issues/666/filesystem-statistics-error-cannot-parse)

Hopefully there'll be a (positive) reaction...
Maybe someone from here could support/enforce/confirm this? ;)

Cheers,

Stephan

**Comment by Woi** [comment]
Thanks a lot Stephan :)

I don't have a bitbucket account nor a FreeBSD bugzilla account. I'll wait a few days for an answer. If they don't show up, I'll get my self a login.
But may be you could already add links to the down- and upstream reports for FreeBSD? I guess this could be helpful.

**Comment by Stephanowicz** [comment]
hmm... ;)
well I also just created an account for this - sry I really have no experience regarding this :D 

Maybe Franco could lend a helping hand...? ;)

Cheers

**Comment by fichtner** [comment]
Let's give them a couple of days to react. The maintainer of the FreeBSD port is also a tildeslash dev so you will have the right person's attention in any case. Thanks guys.

Franco

**Comment by Woi** [comment]
Done: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=222312#c1 :-)

**Comment by Stephanowicz** [comment]
Here's our troublemaker:

```
// Parse the device path like /dev/da0p2 into name:instance -> da:0
static boolean_t _parseDevice(const char *path, Device_T device) {
        const char *base = File_basename(path);
        for (int i = 0; base[i]; i++) {
                if (isdigit(*(base + i))) {
                        strncpy(device->key, base, i < sizeof(device->key) ? i : sizeof(device->key) - 1);
                        device->instance = Str_parseInt(base + i);
                        return true;
                }
        }
        LogError("filesystem statistics error -- cannot parse device '%s'\n", path);
        return false;
}
```

**Comment by fichtner** [comment]
so it's expecting "ada0", but gets "rootfs" and fails because the digit is missing on the label because it's not a traditional device node ;)

**Comment by Stephanowicz** [comment]
Ok, dunno what else they need this instantiation - probably we could comment out the LogError part for peace in the log? ;)

**Comment by fichtner** [comment]
will be fixed in 5.24.0 according to Martin :)

**Comment by Stephanowicz** [comment]
Jep! :D

**Comment by fichtner** [comment]
Closing this, better to assume this is fixed than not. We can always reopen. Thanks again guys :)

**Comment by fichtner** [comment]
This will land in 17.7.4 on Wednesday.

**Comment by Stephanowicz** [comment]
Nice!
