### ISSUE TITLE
net/udpbroadcastrelay: VTI Interfaces and other Virtual Interfaces not Selectable

### ISSUE THREAD

**Issue by KYLE-HILL** [opnsense/plugins#2652]
**Important notices**
Our forum is located at https://forum.opnsense.org , please consider joining discussions there in stead of using GitHub for these matters.

Before you ask a new question, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

OPNsense 21.7.5-amd64
FreeBSD 12.1-RELEASE-p21-HBSD
OpenSSL 1.1.1l 24 Aug 2021

Hello Opnsense Community,

I am not sure if I have encountered a bug or perhaps a limitation of the Plugin? 

I am attempting to use the UDP Broadcast Relay Plugin to relay some UDP multicasts from a Physical Port on my Opnsense Firewall to another network that is connected over IPsec/VTI.  

When I configure the UDP Broadcast Relay Plugin I do not have the option to select any Virtual Tunnel Interfaces despite them being correctly configured/in-use. I know that Multicast is supported by the VTI Protocol and what I am wanting to do should be feasible using either VTI or GRE over IPSec.

The plugin appears to only support physical interfaces and not virtual interfaces. Is this a bug? If not, could support for virtual tunnel interfaces be easily added? If there is a particular issue with VTIs and the plugin - would GRE support be more feasible due to the wider variety of supported protocols? 

Thanks,
Kyle

**Comment by mimugmail** [comment]
There are no limitations in the plugin code, but I'd guess it only accepts assigned interfaces which is not the way how route-based interfaces work. GRE should work, or WireGuard/OpenVPN with assigned interfaces
