### ISSUE TITLE
net/udpbroadcastrelay: IPv6 support

### ISSUE THREAD

**Issue by chris-beedie** [opnsense/plugins#2655]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

[X] When the request is meant for an existing plugin, I've added its name to the title.

OPNsense 21.7.5-amd64
os-udpbroadcastrelay 1.0_2

**Is your feature request related to a problem? Please describe.**
Netflix on android is not able to discover newer chromecast generations (at least gen3 and gen4. gen1 is ok, gen2 untested) as they use IPv6 mDNS. Other apps (e.g. youtube) are ok on all chromecasts.

**Describe the solution you'd like**
udp broadcast relay to support ipv6 mDNS. 

**Describe alternatives you've considered**
I've tried blocking and rejecting ipv6 udp traffic to force netflix/chromecast to fallback to ipv4, but it didn't work.

**Additional context**

**Comment by marjohn56** [comment]
I'll not be adding v6 support as I don't have time, but the source is available for forking if anyone wants to do so.

**Comment by fichtner** [comment]
@marjohn56 is this about the port instead of plugin?

**Comment by mimugmail** [comment]
If it's only plugin I can take it.

**Comment by marjohn56** [comment]
It's likely to be both. Certainly the port needs to be checked too.

**Comment by chris-beedie** [comment]
I've done some digging. It looks like the port would need updated too. There is an issue on https://github.com/udp-redux/udp-broadcast-relay-redux/issues/18 which looks to be a fork from the same original code. It mentions the need for `AF_INET6` sockets which don't appear in the opnsense port either.  

I'm happy to help if I can, but I'm not familiar with FreeBSD development and my C and networking knowledge is rough at best.
