### ISSUE TITLE
security/acme-client: Add ALPN Challenge Type

### ISSUE THREAD

**Issue by revr3nd** [opnsense/plugins#2661]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

[X] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
Many businesses I am aware of have performed some odd choices in blocking TCP/80 HTTP traffic on their edge firewalls in order to discourage the use of any incoming unencrypted HTTP traffic internally. Residential ISPs are also starting to enforce this as well under the guise of security for end users.
This creates an issue where the built in ACME client for OPNSense is unable to issue certificates using the HTTP-01 challenge type, and not all users may have the ability to use the DNS-01 challenge type due to lack of access or the registrar not supporting dynamic functionality.
Because of this issue, I am unable to use the built in haproxy and acme-client on my OPNSense firewall, and instead rely on a separate container for this service.

**Describe the solution you'd like**
This issue is requesting to add TLS-ALPN-01 as an additional challenge type to the acme-client plugin. acme.sh provides an alternate challenge type for these use cases with tls-alpn-01. This acts similar to a standalone HTTP challenge, but will utilize TCP/443 as the transport as opposed to the more commonly blocked TCP/80.
Reference documentation: https://github.com/acmesh-official/acme.sh/wiki/How-to-issue-a-cert#3-standalone-tls-alpn-mode

I have this working on my haproxy container as well using the below command to initiate a certificate issue using the alpn challenge:
acme.sh --issue --alpn [ -d {{ web-domain }} ]

**Comment by fraenki** [comment]
I've implemented this in https://github.com/opnsense/plugins/pull/2688/commits/7f0ec9b47e495d51e76d45eade211672db5e421f. However, this is based on the implemention of the HTTP-01 challenge type, so it's prone to the same failures and instability (because it tries to guess the correct settings and needs to use a dynamic port forward).

Besides that I can't test it, but the generated acme.sh command looks good to me:

```
Dec  8 00:21:14 opnsense.example.com opnsense[38935]: AcmeClient: running acme.sh command: /usr/local/sbin/acme.sh --issue --syslog 7 --debug --server 'letsencrypt_test' --alpn [...] --tlsport '43581' [...]
```

And the acme.sh log seems to confirm that TLS-ALPN-01 is being used:

```
Dec  8 00:21:16 opnsense.example.com acme.sh[9535]: [Wed Dec  8 00:21:16 CET 2021] Standalone alpn mode.
Dec  8 00:21:16 opnsense.example.com acme.sh[10419]: [Wed Dec  8 00:21:16 CET 2021] _checkport='43581'
```

**Comment by revr3nd** [comment]
Confirmed this is working in 3.6 using the test server.

Thank you for the fast turnaround!
