### ISSUE TITLE
security/acme-client: SFTP upload fails due to invalid action type

### ISSUE THREAD

**Issue by 3ster** [opnsense/plugins#2671]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

[x] The title contains the plugin to which this issue belongs

**Describe the bug**
Uploading a certificate via SFTP automation to a remote server does not work due to the action type being "configd_upload_sftp" instead of "upload_sftp."

**To Reproduce**
1. Create a new automation via Services->ACME Client->Automations with the Run Command set to "Upload certificate via SFTP" and a valid configuration
2. Execute the automation
3. Log entry "/usr/local/opnsense/scripts/OPNsense/AcmeClient/upload_sftp.php: Ignoring disabled or invalid automation [uuid]" is created.

**Expected behavior**
Certificate is uploaded to the remote machine.

**Screenshots**
n/a

**Relevant log files**
See above.

**Additional context**
Changing line 411 in /usr/local/opnsense/scripts/OPNsense/AcmeClient/upload_sftp.php from
```php
if ($action->enabled && "upload_sftp" === (string)$action->type) {
```
to
```php
if ($action->enabled && "configd_upload_sftp" === (string)$action->type) {
```
results in the automation working as expected.

**Environment**

OPNsense 21.7.6-amd64
os-acme-client 3.5

**Comment by fraenki** [comment]
Thanks for the report! This will be fixed in os-acme-client 3.6

For those in need for a hotfix:

```
opnsense-patch -c plugins 57ada90e890832b67ad93f54bed2ee26bde4b669
```
