### ISSUE TITLE
security/acme-client: Uncaught Error: Call to undefined method OPNsense\AcmeClient\LeAutomation\AcmeSynologyDsm::getMethod()

### ISSUE THREAD

**Issue by cbrueffer** [opnsense/plugins#2674]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

[x] The title contains the plugin to which this issue belongs

**Describe the bug**

The new Synology automation results in an error when logging, see below. I assume the new FritzBox automation may have the same problem.

That said, thanks a lot for exposing this automation, it works beautifully otherwise.

**To Reproduce**
1. Add a Synology (tested) or FritzBox (presumably has the same problem) automation
2. Add a certificate with the automation above enabled
3. Run the automation
4. OPNsense crash reporter reports the problem

**Expected behavior**
No 

**Screenshots**

**Relevant log files**

```30-Nov-2021 17:10:05 Europe/Stockholm] PHP Fatal error:  Uncaught Error: Call to undefined method OPNsense\AcmeClient\LeAutomation\AcmeSynologyDsm::getMethod() in /usr/local/opnsense/mvc/app/library/OPNsense/AcmeClient/LeAutomation/Base.php:148
Stack trace:
#0 /usr/local/opnsense/mvc/app/library/OPNsense/AcmeClient/LeAutomation/Base.php(98): OPNsense\AcmeClient\LeAutomation\Base->runAcme()
#1 /usr/local/opnsense/mvc/app/library/OPNsense/AcmeClient/LeCertificate.php(611): OPNsense\AcmeClient\LeAutomation\Base->run()
#2 /usr/local/opnsense/scripts/OPNsense/AcmeClient/lecert.php(188): OPNsense\AcmeClient\LeCertificate->runAutomations()
#3 /usr/local/opnsense/scripts/OPNsense/AcmeClient/lecert.php(199): main()
#4 {main}
  thrown in /usr/local/opnsense/mvc/app/library/OPNsense/AcmeClient/LeAutomation/Base.php on line 148
```

![Screenshot_2021-11-30_19-25-40](https://user-images.githubusercontent.com/2705287/144105911-89fc9f7c-2b77-4476-98a5-ab80601fd553.png)
**Environment**

OPNsense 21.7.6 (amd64, OpenSSL).
security/acme-client version: 3.5

**Comment by fraenki** [comment]
Please try this patch:

```
opnsense-patch -c plugins 83813dcbb570d31103d6e1804988200137e6a72e
```

**Comment by cbrueffer** [comment]
Looks like that did the trick, thanks!
