### ISSUE TITLE
unbound aaaa-filter-iterator.patch

### ISSUE THREAD

**Issue by kadiremrah** [opnsense/plugins#2676]
Is it possible to implement aaaa-filter-iterator.patch to unbound

https://github.com/monero-project/unbound/blob/master/contrib/aaaa-filter-iterator.patch

Thanks for advance,

**Comment by AdSchellevis** [comment]
closing as also replied via email, leaving the email response here for reference:

> Probably best ask the people from Unbound (https://github.com/NLnetLabs/unbound/issues), one advice, make sure to open complete tickets explaining context, what the implication would be and why anyone should want a specific feature.
> Asking for a patch without context usually doesn't lead to anything (the mentioned repository looks rather unmaintained to be honestl).
>

**Comment by feld** [comment]
Actually I'd like to reopen this -- this patch is shipped by FreeBSD in base and it's not an uncommon feature request

https://cgit.freebsd.org/src/tree/contrib/aaaa-filter-iterator.patch?h=vendor/unbound

**Comment by fichtner** [comment]
Happy to take PRs for tools.git and core.git
