### ISSUE TITLE
security/acme-client: add support for "dynv6" (HTTP REST API) 

### ISSUE THREAD

**Issue by ulbi** [opnsense/plugins#2678]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

[x] The title contains the plugin to which this issue belongs

**Describe the bug**
A clear and concise description of what the bug is, including last known working version (if any).
Not sure, whether this ever worked.
I see, that under "Challenge Types" - DNS-01, the list of DNS Services does not contain dynv6 
The introduction claims " that your DNS provider is supported both by acme.sh and this plugin."
I verifed the acme.sh script supports dynv6 - obviously the plugin does not.

Not sure, whether this is intentional or not.

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**
1. Go to 'Challenge Types'
2. Click on 'add'
3. Scroll down to 'search dynv6 in the list of dns services'
4. See error ---> it is missing

**Expected behavior**
like other DNS Services dynv6 should be in the list for usage...

**Screenshots**

**Relevant log files**
If applicable, information from log files supporting your claim.

**Additional context**

**Environment**
Software version used and hardware type if relevant.
e.g.:

OPNsense 19.1.1 (amd64, OpenSSL).
Intel® Xeon™ E3-1225V5 3.3Ghz Quad Core
Network Intel® I210-AT

**Comment by fraenki** [comment]
https://github.com/acmesh-official/acme.sh/wiki/dnsapi#97-use-dynv6-api-to-automatically-issue-a-cert
I will probably add support for the HTTP API in one of the next releases.

> OPNsense 19.1.1 (amd64, OpenSSL).

If this is true, then you should upgrade ASAP :)

**Comment by ulbi** [comment]
Thanks for the quick reply - I'm looking forward to it.

For the version :-)
OPNsense 21.7.6-amd64
FreeBSD 12.1-RELEASE-p21-HBSD
OpenSSL 1.1.1l 24 Aug 2021

**Comment by fraenki** [comment]
This will be available in the upcoming os-acme-client 3.6.
