### ISSUE TITLE
os-freeradius 1.9.17 does not start and install errors on opnsense 21.10.1

### ISSUE THREAD

**Issue by spottaaja1** [opnsense/plugins#2681]
Radius does not start and install log seems to have some errors. See attached logs:

[freeradius install.log](https://github.com/opnsense/plugins/files/7656755/freeradius.install.log)
[freeradius onedebug.log](https://github.com/opnsense/plugins/files/7656756/freeradius.onedebug.log)

Steps to reproduce:

Installed normally and configured as seen in the attached config snippet:

[freeradius config.log](https://github.com/opnsense/plugins/files/7656766/freeradius.config.log)

**Comment by mimugmail** [comment]
Can you go to Services : Freeradius : EAP and hit apply? It should start work now ...

**Comment by spottaaja1** [comment]
Hello and thank you. That worked!

**Comment by fichtner** [comment]
@mimugmail thanks for the quick support! ❤️
