### ISSUE TITLE
Best way to install npm

### ISSUE THREAD

**Issue by 8191** [opnsense/plugins#2684]
**Important notices**
Our forum is located at https://forum.opnsense.org , please consider joining discussions there in stead of using GitHub for these matters.

Before you ask a new question, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

The www/nginx plugin requires nodejs (more specifically the npm) to compile the frontend JS. What's the preferred way to install npm on OPNsense?

I always temporarily enable the FreeBSD repos, install npm (e.g. using `pkg install npm-node14`), which leads to pkg being updated to the FreeBSD one and requires manual reinstallation to the OPNsense one. All in all quite bulky... Is there a better way?

**Comment by mimugmail** [comment]
The best way is to build it yourself. For me it only works on 22.1 / FBSD13, I can add it to the community repo but I dont see any chance for 21.7.

**Comment by 8191** [comment]
@mimugmail Did you build it from the ports collection?

**Comment by mimugmail** [comment]
https://www.reddit.com/r/opnsense/comments/q4epyo/guide_to_try_to_opnsense_221/

Add www/node-npm14 to 22.1/ports.conf and run `make SETTINGS="22.1" packages`

**Comment by fichtner** [comment]
# pkg lock pkg

is your friend, but pkg 1.17 made a mess of their repo and we cannot clean this up before 22.1 is released...too risky since major release depends on smooth transition.

**Comment by 8191** [comment]
Thanks!

@mimugmail As some plugins (at least www/nginx) depend on it, I'd appreciate if it could be added to the community repo.

**Comment by mimugmail** [comment]
When an official plugin has this dependency the pkg needs to go in the official one. Needs to be discussed with @fichtner

**Comment by 8191** [comment]
Well it's a dev dependency only. Running www/nginx works also without nodejs or any module installed via npm.

**Comment by mimugmail** [comment]
I updated the repo, if you are on 22.1 beta you can grab the pkg via CLI
https://www.routerperformance.net/opnsense-repo/

**Comment by 8191** [comment]
@mimugmail Thanks! Worked without any problems.

**Comment by fabianfrz** [comment]
@8191 I always ran the npm based build on my linux host machine and copied the files to the OPNsense machine via SSH. This works perfectly out of PHPStorm with a deploy button. However you may have a different toolchain for development.

**Comment by fichtner** [comment]
@8191 I don't consider npm an essential tool, least of all one that should be shipped in the binary packages if we can avoid it. We did so for a while since another vendor used nodejs, but we are happy this is no longer the case. E.g. for the documentation the compile also works better on Linux. Translation tools are also somewhat cluttered in that regard as well.

There's also the possibility of using off-device development with https://github.com/opnsense/ui_devtools anywhere where tools like scss compilers and minifiers and the like lives.


Cheers,
Franco

**Comment by fabianfrz** [comment]
@fichtner how essential it is depends on how complex the frontend is. It is the defacto standard of modern web development.
Most time when using it with frontend builds, it is used to transpile (TypeScript -> JavaScript, SCSS -> CSS, …), compress (x.js -> x,min.js and x.map) and bundle JavaScript files and resources. In a simple UI, this does not matter as you can write that in simple vanilla JS.

**Comment by fichtner** [comment]
Well, it's not essential if you just want to make it essential for complex frontend work. I don't think we opt anywhere for complex frontend work if it can't be avoided and we have never minified or generated code for core, probably won't do so either.

Don't get me wrong, as maintainer you can decide on what to do, but for core and tools and such we need to keep more focus on limiting complexity.

Cheers,
Franco
