### ISSUE TITLE
security/os-intrusion-detection-content-et-open - ET Open rules not updated via UI

### ISSUE THREAD

**Issue by pmhausen** [opnsense/plugins#2685]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

[x] The title contains the plugin to which this issue belongs

**Describe the bug**

The os-intrusion-detection-content-et-open plugin was as far as I understand created to specifically add missing rules from the "ET open" ruleset in case one uses the "ET Pro Telemetry" ruleset, where these rules are empty. I am referring to this issue:
https://github.com/opnsense/plugins/issues/2329

After activating the "ET Pro Telemetry" ruleset with a proper subscription token everything is working as expected, the rules are updated, alerts raised, etc.

When adding the os-intrusion-detection-content-et-open plugin later, one can enable the rules but they are never downloaded.

**To Reproduce**

1. Install/update to 21.7.6
2. Enable IDS
3. Install the os-etpro-telemetry plugin
4. Enter token, save, download & update rules
5. Now install os-intrusion-detection-content-et-open plugin
6. New rules show up in the UI, are enabled, but never downloaded
7. Explicitly selecting and clicking "enable selected", then again download & update doesn't change anything.

The state is as in the attached screenshot. abuse.ch rules, OPNsense rules, ET Pro Telemetry rules ... update just fine. The ET Open rules don't.

**Expected behavior**

All activated rules should be downloaded and updated.

**Screenshots**

![Screenshot #3](https://user-images.githubusercontent.com/27051716/144910095-6d006506-3b29-400b-9532-864f1bacc360.jpg)

Kind regards,
Patrick

**Comment by pmhausen** [comment]
[system.log](https://github.com/opnsense/plugins/files/7663206/system.log)

No error as far as I can see. My gut feeling is that this is a UI issue. The os-intrusion-detection-content-et-open plugin is supposed to fill some rule files that originally belong to the os-etpro-telemetry plugin, if I read the referenced issue correctly. Possibly the UI in its current state is simply confused about which ruleset belongs to which plugin?

I am really only concerned about the display (see screenshot) of e.g. "ET open/drop" as "not installed".

When I look at `/usr/local/etc/suricata/rules/drop.rules` there are 83 lines in there. The `/usr/local/etc/suricata/opnsense.rules/drop.rules` contains another 82 lines and a quick diff shows that apart from the copyright boilerplate the two files are mostly identical. The different number of lines being caused by a missing newline @ EOF.

**Comment by AdSchellevis** [comment]
the rule files for these should use different filenames https://github.com/opnsense/plugins/blob/master/security/intrusion-detection-content-et-open/src/opnsense/scripts/suricata/metadata/rules/et-open-extra.xml#L10 (et_open.drop.rules)

![image](https://user-images.githubusercontent.com/9783985/144916941-ad636c9b-6c92-41f3-b9b9-7b7c9f8283a2.png)

Only thing that stands out in your logs is that it seems to download a different file (suri-5).

```
<13>1 2021-12-06T21:23:08+01:00 OPNsense.localdomain /rule-updater.py 79896 - [meta sequenceId="5"] version response for https://rules.emergingthreats.net/open/suricata-4.0/version.txt : 9904
<13>1 2021-12-06T21:23:10+01:00 OPNsense.localdomain /rule-updater.py 79896 - [meta sequenceId="6"] download completed for https://rules.emergingthreats.net/open/suricata-4.0/emerging.rules.tar.gz
```

**Comment by pmhausen** [comment]
OK. So the why don't they download?
```
root@opnsense:/usr/local/etc/suricata # find . -name et_open.drop.rules
root@opnsense:/usr/local/etc/suricata #
```

I can provide any information from my system you ask for, now. This is my home firewall and although "productive", IDS is not in any way essential. Just starting to toy with it.

If you can reproduce the issue by following the steps I documented, there's one more thing I did yesterday, but did not want to add to the issue initially, not wanting to complicate things. So I started fresh to get a proper report.

Yesterday with all the "ET open" rules "not installed", I went and deinstalled the os-etpro-telemetry plugin. Then went to the IDS settings, clicked "download & update" - immediately downloaded and shown in the UI with a timestamp.
Then reinstalled the os-etpro-telemetry plugin. Now when I clicked "download & update" then, all rules (rulesets?) got updated timestamps. abuse.ch, telemetry, ... but the "ET open" ones did not! Their timestamps stayed frozen at the last successful update.

Kind regards,
Patrick

**Comment by AdSchellevis** [comment]
On my end it seems to work, but I didn't try to deinstall telemetry.  You could try to empty the rules dir (/usr/local/etc/suricata/rules) and see if that resets the state when forcing a download.

**Comment by pmhausen** [comment]
OK, so with both plugins installed you get a clean update for all rules showing in the UI? I'll try that, of course.

**Comment by pmhausen** [comment]
Stopped IDS/Suricata from the dashboard.
Deleted `/usr/local/etc/suricata/rules/*`

**Comment by AdSchellevis** [comment]
Hi Patrick, 

If you search for "drop" in the list, the above entry is the only shown?

Best regards,

Ad

**Comment by pmhausen** [comment]
![Bildschirmfoto 2021-12-07 um 09 15 00](https://user-images.githubusercontent.com/27051716/144991763-9c6dcfa1-d59c-4ea3-b38c-54426c2bd139.png)

**Comment by AdSchellevis** [comment]
ok, try disabling "drop" in telemetry and fetch again

**Comment by AdSchellevis** [comment]
hmm,  I thought it was overlapping somehow, but I don't see how or why to be honest, found an OPNsense 21.7.6 here at the office, when enabling both it seems to fetch them as expected:

![image](https://user-images.githubusercontent.com/9783985/145074286-6e08b199-0a06-43a2-9d17-055070b24e6b.png)

**Comment by pmhausen** [comment]
Possibly I created the problem by downloading and installing the standard OPNsense bundled "open" rulesets first, before activating the "telemetry" ones? Is it possible to empty the opnsense.rules directory just for a try?

**Comment by pmhausen** [comment]
Seems to be ok, but did not change anything.

**Comment by kulikov-a** [comment]
@pmhausen @AdSchellevis Hi!
for reference: https://forum.opnsense.org/index.php?topic=25765.0 another similar issue . and i also can not reproduce this behaviour for all this days.
@pmhausen any chance that this is just some sort of "time-out" issue? if Rules Update task takes more than 2 min, IDS page will not update rulsets statuses (actualy javascript breaks receiving 'null' response from api) and you need to wait for actual job finish (wait for suri reload event in suri log) and refresh the page to get rulsets statuses

**Comment by pmhausen** [comment]
No, refreshing the page does not change the status. Uninstalling the telemetry ruleset lets me download the "ET open" ones. But when I reinstall it aftewards they stay installed but don't get updated.

From that thread:
> imho there is no sense to use os-intrusion-detection-content-et-open  plugin any more

Is that true? I can uninstall the plugin and close this ...

**Comment by kulikov-a** [comment]
> Is that true? I can uninstall the plugin and close this ...

no, maybe I was in a hurry. I was talking specifically about using the os-intrusion-detection-content-et-open plugin along with a 'core' ET Open rulsets.  I have no way to compare the os-intrusion-detection-content-et-open rules with the rules from **telemetry** plugin (have no token)

**Comment by kulikov-a** [comment]
> No, refreshing the page does not change the status.

got it, thanks. will try to reproduce the issue from the forum again.

**Comment by AdSchellevis** [comment]
I can't reproduce it either, but I can leave some things to check.

in `/usr/local/etc/suricata/rule-updater.config` there should be a (one) section for the file in question, so when et_open drop is enabled I would expect a section like:
```
[et_open.drop.rules]
enabled=1
```

The rule downloader `/usr/local/opnsense/scripts/suricata/rule-updater.py` could be triggered manually, additional debug output is best added somewhere around here https://github.com/opnsense/core/blob/1221542a43642d35552f0e597e28d0715696a775/src/opnsense/scripts/suricata/rule-updater.py#L71  , each `rule` should refer to a file.

Best check the contents of the xml file (https://github.com/opnsense/plugins/blob/master/security/intrusion-detection-content-et-open/src/opnsense/scripts/suricata/metadata/rules/et-open-extra.xml) with the one on disk to exclude any differences in test setup by the way.

**Comment by pmhausen** [comment]
Well, that escalated quickly ;)
```
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='opnsense-staging.emergingthreats.net', port=443): Max retries exceeded with url: /api/v1/ruleset/version (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xbd3dc1c370>: Failed to establish a new connection: [Errno 61] Connection refused'))
```

Trying to get some more info:
```
root@opnsense:/usr/local/etc/suricata # ping opnsense-staging.emergingthreats.net
PING opnsense-staging.emergingthreats.net (72.12.200.24): 56 data bytes
64 bytes from 72.12.200.24: icmp_seq=0 ttl=242 time=241.924 ms
64 bytes from 72.12.200.24: icmp_seq=1 ttl=242 time=240.879 ms
^C
--- opnsense-staging.emergingthreats.net ping statistics ---
2 packets transmitted, 2 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 240.879/241.402/241.924/0.523 ms
root@opnsense:/usr/local/etc/suricata # ping6 opnsense-staging.emergingthreats.net
ping6: Name does not resolve
root@opnsense:/usr/local/etc/suricata # telnet opnsense-staging.emergingthreats.net 443
Trying 72.12.200.24...
telnet: connect to address 72.12.200.24: Connection refused
telnet: Unable to connect to remote host
root@opnsense:/usr/local/etc/suricata # 
```

**Comment by AdSchellevis** [comment]
@pmhausen big oops from my end.... missed a "staging" keyword https://github.com/opnsense/plugins/commit/e74210a4edf59204a1c490f1ec11d26a4df63861

We should improve the error handing as well for these cases by the way (but that's a core thing)

**Comment by AdSchellevis** [comment]
Hi Patrick, 

A hotfix for the issue should be online now, can you check for updates and see if this fixes yours?

Best regards,

Ad

**Comment by pmhausen** [comment]
Applies cleanly and looks good.
