### ISSUE TITLE
DynDns version 1.2_1 is broken with OPNSense 17.7.2 for NameCheap

### ISSUE THREAD

**Issue by liorokman** [opnsense/plugins#269]
The namecheap response calls a function called xml2array, which existed before updating OPNSense to version 17.7.2, but doesn't exist in OPNSense 17.7.2. 

I get the following crash:
```
Fatal error: Uncaught Error: Call to undefined function xml2array() in /usr/local/etc/inc/plugins.inc.d/dyndns/phpDynDNS.inc:942 Stack trace: 
#0 /usr/local/etc/inc/plugins.inc.d/dyndns/phpDynDNS.inc(735): updatedns->_checkStatus(Resource id #89, '_update() 
#2 /usr/local/etc/inc/plugins.inc.d/dyndns.inc(169): updatedns->__construct('namecheap', 'home.example.com', 'example.com', 'somepassword...', false, '', 'wan', NULL, NULL, NULL, '', true, '', '', '', 'wan', '1', false, false, false) 
#3 /usr/local/www/services_dyndns_edit.php(166): dyndns_configure_client(Array) 
#4 {main} thrown in /usr/local/etc/inc/plugins.inc.d/dyndns/phpDynDNS.inc on line 942
```

**Comment by AdSchellevis** [comment]
@fichtner this seemed to be buried in the upgrade_config.php we ditched. It's also in https://github.com/opnsense/core/blob/52bfec334b33f7f56d57355004a063c24c1e8965/src/www/getserviceproviders.php I'm trying to get rid of xml2array there at the moment.

**Comment by fichtner** [comment]
if you want please take this as well, thanks :)

**Comment by AdSchellevis** [comment]
will do

**Comment by AdSchellevis** [comment]
@liorokman this https://github.com/opnsense/plugins/commit/da5ae3c45205f04ead8f29e6b61addd482c14ff3 should do the trick, but I don't have a namecheap account to test at my end so I haven't tested all the bits together.

**Comment by fichtner** [comment]
apply via command line:

    # opnsense-patch -c plugins da5ae3c

**Comment by liorokman** [comment]
Works like a charm.

Thanks!!!

**Comment by fichtner** [comment]
Thanks for the confirmation. Will be in 17.7.3 next week. 😊
