### ISSUE TITLE
MTU of the Wireguard interface when WAN uses a PPPoE connection

### ISSUE THREAD

**Issue by KuddelSK** [opnsense/plugins#2690]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

* [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
* [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

I connect to my ISP using a PPPoE connection. When i configure wireguard and look at the wg0 interface using ifconfig i see a MTU of 1420 (1500 - 80 for the Wireguard header). This is wrong in case of a PPPoE connection as PPPoE adds 8 Byte on its own. Therefore the MTU should be 1412 in this case.

This is not critical as one can manually adjust the tunnel MTU.

I don't know if its relevant to the bug but i have to use a VLAN which provides the ethernet layer for the PPPoE connection.    

**To Reproduce**

1. Use a PPPoE Wan connection
2. Install the Wireguard service
3. Configure Wireguard (leave MTU empty for automatic calculation)
4. Execute "ifconfig wg0" in a router shell

**Expected behavior**

MTU of 1412 for wg0 in case of a PPPoE connection.

**Describe alternatives you considered**

One can set the tunnel MTU manually.

**Environment**

OpnSense 21.7.6
APU 4D4 (GX-412TC CPU; 4 Nics i211AT )

**Comment by nzkiwi68** [comment]
I'm not sure that statement of 80 bytes for the Wireguard header is correct. From what I am reading, the Wireguard header is only 60 bytes and thus 1420 automatic MTU is fine for PPPoE and non PPPoE connections for IPv4.

Only IPv6 over PPPoE would require an MTU of 1412.

**My reference is here:**
[https://lists.zx2c4.com/pipermail/wireguard/2017-December/002201.html](url)

**Comment by KuddelSK** [comment]
Sorry for missing this information in the description.

I configured WAN to use IPv4 *and* IPv6. I connect to Wireguard using the public IPv6. I guess this is quite common as a non RFC1918 IPv4 is rare these days for non-business users.
