### ISSUE TITLE
os-freeradius - edit client dialog does not accept a network with CIDR as configuration for IP address or network

### ISSUE THREAD

**Issue by martinroehder** [opnsense/plugins#2696]
**Important notices**

**Describe the bug**
The description in the dialog says to enter: IP address or network with CIDR.

The dialog does accept e.g. 192.168.10.1/32 but it does NOT accept 192.168.10.0/24. The error says "please specify a valid address (IPv4/IPv6) or hostname.

**To Reproduce**
ui/freeradius/client/index

Click on + to add a new client. Enter the above date and you will see the message from the picture.

**Expected behavior**
Specifying a network with CIDR 24 should be accepted.

**Screenshots**
![freeradius_editclient](https://user-images.githubusercontent.com/51159911/145411441-17e6bb0d-531f-42a1-973b-1cf21641ff72.png)

**Relevant log files**

**Additional context**

**Environment**
opnsense 
  | Version | 21.1.8_1 |  
  | Architecture | amd64 |  
  | Flavour | OpenSSL

os-freeradius (installed) | 1.9.14

**Comment by mimugmail** [comment]
There must be a space inside somewhere, it works for me here with latest version. Also please check the changelog, I guess it was added between yours and current version

**Comment by Wireheadbe** [comment]
Works here as well on 21.7.7

**Comment by martinroehder** [comment]
The problem occurs again in 22.7.4.
Could you please fix it again.
