### ISSUE TITLE
os-zabbix-agent / os-zabbix5-proxy - add support for custom config parameters

### ISSUE THREAD

**Issue by kdkelson** [opnsense/plugins#2697]
**Problem:**
Currently it is not possible to add custom config lines to Zabbix agent or proxy, which are not supported by the OPNsense webfrontend. There exists the config directive "Include=/usr/local/etc/zabbix_agentd.conf.d" in /usr/local/etc/zabbix_agentd.conf (Zabbix agent config file), which makes it possible to read further config files, but I don't know, if this is update-safe. The "Include" directive does not exist in /usr/local/etc/zabbix5/zabbix_proxy.conf, which is the config file for Zabbix proxy. So, it is currently impossible to add configuration there.

**Use case**
***Zabbix agent***
- Adding UserParameters (see https://www.zabbix.com/documentation/5.0/en/manual/config/items/userparameters) for implementing checks, which are not part of the Zabbix agent by default.

***Zabbix proxy***
- Making it possible to gather statistics. For allowing this, it is needed to add the directive "StatsAllowedIP=<ip/hostname>" to the config file, where the allowed host(s) should be entered (see https://www.zabbix.com/documentation/5.0/en/manual/appendix/items/remote_stats).

**Solution proposal**
- Add a field "Advanced Parameters" to Zabbix agent and proxy, where additional config lines can be added
- Add a field "Stats Allowed IP", where allowed hosts for getting statistics can be entered

**Comment by fraenki** [comment]
>  Zabbix agent

I'm the maintainer of the Zabbix agent plugin. Adding UserParameters is already possible:
`Services: Zabbix Agent: Settings -> Advanced -> User Parameters`

> Currently it is not possible to add custom config lines to Zabbix agent or proxy

...and that's for a reason. This would greatly increase the risk of breaking the configuration at any time. Contributors and plugin maintainers simply cannot test all combinations of arbitrary configuration includes, so any change may break things at any time. So I'm strongly opposed to this. Instead all features should be directly added to the GUI.

@mimugmail is the maintainer of the Zabbix proxy plugin, maybe he can comment on the other requests.

**Comment by crazycarl1011** [comment]
Hello  Fraenki, I met an issue. My inputs are checked by the ui before submit and are rejected. Even though my inputs are totally valid for the zabbix agent the ui's form validation won't accept the input.

Key = openvpn.user.status[*]
===> Error Message: Should be a string between 1 and 255 characters.

May need your assit to do some more works about this. 
Thank you!

**Comment by fraenki** [comment]
```Key = openvpn.user.status[*]```

Remove the `[*]` fromn the key and enable the option `Accept Parameters` instead.
