### ISSUE TITLE
HAproxy servers: Allow advanced SSL verification options

### ISSUE THREAD

**Issue by jpawlowski** [opnsense/plugins#27]
Refering to #26, one should be able to define advanced SSL verification options to have it enabled (similar to what pfSense offers). Otherwise the HAproxy plugin cannot be used appropriately within production environments.

**Comment by fraenki** [comment]
Same here: I've prepared a fix, but we'll have to fix a related bug in the framework before we can release an updated HAProxy plugin.

**Comment by fraenki** [comment]
@fichtner: This should be fixed, please close this issue.
