### ISSUE TITLE
Feature request: Bash

### ISSUE THREAD

**Issue by peppelinux** [opnsense/plugins#270]
I'm doing it with
pkg add http://pkg.freebsd.org/freebsd:11:x86:64/latest/All/bash-4.4.12_2.txz

**Comment by fichtner** [comment]
is there a particular dependency that misses it or just the problem of writing a bash script in your code that could be replaced with a POSIX shell script?

**Comment by peppelinux** [comment]
history and auto-complete are good features, just for this.

**Comment by fichtner** [comment]
so just for using it as a user shell?

**Comment by fabianfrz** [comment]
for a user shell `zsh` would be even better ;)

**Comment by peppelinux** [comment]
Yeah zsh is better, this means that is possible having it in the next OPNsense release? :)

**Comment by fichtner** [comment]
zsh is ok, I will check. Note that we won't accept shell scripts for anything but POSIX shell for portability, review and maintenance reasons. That's the reasons why we reluctantly offer other shells, and furthermore later people will ask for how to switch a users shell from the GUI etc... And then if people break shells or installs they end up with problems we never even should have supported. 😊

**Comment by fabianfrz** [comment]
@fichtner for anything that cannot be done in a shell script, many high level programming language are available ;)

**Comment by peppelinux** [comment]
you are wise men
