### ISSUE TITLE
net-mgmt/zabbix-proxy - Request for SNMPTrapper fields to GUI config

### ISSUE THREAD

**Issue by datazon** [opnsense/plugins#2708]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

[x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
Currently SNMP Trapper parameters are missing, so zabbix proxy can't get SNMP data. I added the parameter manually and it is working, but changes in gui will delete the manual parameters. My zabbix-proxy plugin version is 5.4

**Describe the solution you'd like**
Add the following fields to enable in webinterface in zabbix-proxy config.

StartSNMPTrapper=1
SNMPTrapperFile=/tmp/zabbix_traps.tmp
TrapperTimeout=300
StartTrappers=5

**Describe alternatives you've considered**
I can't see a good alternative.

**Additional context**
No additional context needed.

**Comment by barzog** [comment]
The same was almost a year ago. https://github.com/opnsense/plugins/issues/2141. Meanwhile you can use patch proposed with plugin lock not to overwrite

**Comment by fraenki** [comment]
@barzog Instead of pointing to a patch, why not [submit a pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests)? :)

**Comment by barzog** [comment]
It requires some skills, like forking repo, patching, pulling. Not in my daily routine:(

**Comment by fraenki** [comment]
@barzog The first PR may be a bit tough, be we'll get you there. :) If you have any questions, either ask here or on the [Development Forum](https://forum.opnsense.org/index.php?board=4.0) or on [IRC](https://docs.opnsense.org/support.html#community)... @mimugmail may also have some advice (he's the maintainer of os-zabbix-proxy) :smile:

**Comment by mimugmail** [comment]
If you want to do it in your own have a look at this one :)

https://github.com/opnsense/plugins/pull/2275/files

**Comment by datazon** [comment]
@barzog Let me know if I can help in something.

**Comment by clanto007** [comment]
I have created a PR to have SNMP Trap:
https://github.com/opnsense/plugins/pull/2966
