### ISSUE TITLE
security/acme-client: gcloud not working anymore

### ISSUE THREAD

**Issue by thomasglauser** [opnsense/plugins#2710]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

[X] The title contains the plugin to which this issue belongs

**Describe the bug**
The integration of the gcloud sdk with the current version of os-acme-client does not work anymore. The gcloud sdk had breaking changes.

Example:

On line 77 in the DnsGcloud.php file, os-acme-client executes a ```gcloud config``` command with dots in the config name. But gcloud does not allow dots:
```configuration names start with a lower case letter and contain only lower case letters a-z, digits 0-9, and hyphens '-'.```

**To Reproduce**
1. Setup the acme client with an Google Cloud DNS Challenge
2. Try to issue the certificate
3. You will get an error message:
```/usr/local/opnsense/scripts/OPNsense/AcmeClient/lecert.php: AcmeClient: The shell command '/usr/local/bin/gcloud config configurations create returned exit code '120'```

**Expected behavior**
The gcloud SDK should be able to log in with the service account and edit the DNS entries.

**Environment**
OPNsense 21.7.7 (amd64, OpenSSL).
os-acme-client 3.6
os-google-cloud-sdk 1.0_1

**Comment by fraenki** [comment]
> configuration names start with a lower case letter and contain only lower case letters a-z, digits 0-9, and hyphens '-'.

:facepalm: 

I'll try to find a workaround in one of the next releases.

**Comment by fraenki** [comment]
OK, let's test a simple fix. Please try the following patch:

```
opnsense-patch -c plugins 80f0c0b8
```

...and report back if it fixes the issue.

**Comment by thomasglauser** [comment]
Okay I just installed the patch. I proceeded in the same way as with the initial bugreport.

The same error message still appears in the ACME client log file:

```
2021-12-21T22:43:49 | opnsense[5562] | /usr/local/opnsense/scripts/OPNsense/AcmeClient/lecert.php: AcmeClient: The shell command '/usr/local/bin/gcloud --quiet config set project prod-XXXXX' returned exit code '120'
2021-12-21T22:43:48 | opnsense[5562] | /usr/local/opnsense/scripts/OPNsense/AcmeClient/lecert.php: AcmeClient: The shell command '/usr/local/bin/gcloud --quiet config set account opnsense@XXXXX.iam.gserviceaccount.com' returned exit code '120'
2021-12-21T22:43:47 | opnsense[5562] | /usr/local/opnsense/scripts/OPNsense/AcmeClient/lecert.php: AcmeClient: The shell command '/usr/local/bin/gcloud --quiet auth activate-service-account --key-file=/tmp/acme_dns_gcloud_61c24955db6458-61118180.json' returned exit code '120'
2021-12-21T22:43:46 | opnsense[5562] | /usr/local/opnsense/scripts/OPNsense/AcmeClient/lecert.php: AcmeClient: The shell command '/usr/local/bin/gcloud --quiet config configurations activate acme-61c24955db6458-61118180' returned exit code '120'
2021-12-21T22:43:45 | opnsense[5562] | /usr/local/opnsense/scripts/OPNsense/AcmeClient/lecert.php: AcmeClient: The shell command '/usr/local/bin/gcloud --quiet config configurations create acme-61c24955db6458-61118180' returned exit code '120'
```

But here's what's interesting:
When I execute the shell commands which fail in the upper logfile via SSH as root, I get no exit code 120.

Here is the Bash history:
```
root@router:~ # /usr/local/bin/gcloud --quiet config configurations create acme-61c24955db6458-61118180
ERROR: (gcloud.config.configurations.create) Cannot create configuration [acme-61c24955db6458-61118180], it already exists.
root@router:~ # /usr/local/bin/gcloud --quiet config configurations activate acme-61c24955db6458-61118180
Activated [acme-61c24955db6458-61118180].
root@router:~ # /usr/local/bin/gcloud --quiet auth activate-service-account --key-file=/tmp/acme_dns_gcloud_61c24955db6458-61118180.json
Activated service account credentials for: [opnsense@XXXXX.iam.gserviceaccount.com]
root@router:~ # /usr/local/bin/gcloud --quiet config set account opnsense@XXXXX.iam.gserviceaccount.com
Updated property [core/account].
root@router:~ # /usr/local/bin/gcloud --quiet config set project prod-335120
Updated property [core/project].
```

I hope this information helps you. Thank you!

**Comment by fraenki** [comment]
In my own testing I've also noticed the exit code 120, but the gcloud configuration was properly set up. It doesn't seem to be a problem. Afterwards acme.sh was started as usual and was able to use the specified gcloud configuration without issues.

@thomasglauser, can you check the `ACME Log` in `Services: ACME Client: Log Files` please? I'd assume that it was able to use the generated gcloud config without any issues. (I cannot test it properly, because I don't use gcloud.)

**Comment by thomasglauser** [comment]
You are right @fraenki. The exit code is not a problem. The commands are executed correctly.

The error in the ACME log is now the following:
```
2021-12-22T00:23:30 acme.sh[97449] _dns_gcloud_start_tr: failed to execute transaction
```

This error is in the acmesh-official codebase on Line 62:
https://github.com/acmesh-official/acme.sh/blob/master/dnsapi/dns_gcloud.sh


```
if ! gcloud dns record-sets transaction start \
    --transaction-file="$tr" \
    --zone="$managedZone"; then
    rm -r "$trd"
    _err "_dns_gcloud_start_tr: failed to execute transaction".
    return 1
  fi
}
```
As I understand it, there is something wrong with the transaction file `$tr` that the script creates. When I run this gcloud sdk command with a custom transaction file via SSH I get no error.

I think we can close this ticket since the transaction file is not generated by your code, right?

I hope your fix will be merged soon. Thank you very much.

**Comment by fraenki** [comment]
> I think we can close this ticket since the transaction file is not generated by your code, right?

Yes, indeed. :)

Maybe it's worth to report the "failed to execute transaction" error with the latest gcloud SDK to the acme.sh project.

**Comment by unquietwiki** [comment]
@fraenki & @thomasglauser I saw your post here, and wanted to give a follow-up. I ran into the same issue described here, and can report it's still not-fixed. I tried both the patch & running  **gcloud components update** to update the SDK from 331 to 368. DNS-TLS-01 challenge did work.

**Comment by fraenki** [comment]
@unquietwiki The issue is resolved, as confirmed by the author. You are likely facing a different problem. Please open a new issue and provide more data, i.e. your os-acme-client config and logs.
