### ISSUE TITLE
net/haproxy: websocket feature doesn't work

### ISSUE THREAD

**Issue by patan32** [opnsense/plugins#2717]
Hello,

I just tested the Haproxy with Websocket and it doesn't work. i have created the config as per your instruction.

From HAproxy page:
```
## routing based on websocket protocol header
acl hdr_connection_upgrade hdr(Connection) -i upgrade
acl hdr_upgrade_websocket hdr(Upgrade) -i websocket"
```

Here is my exported config:

```
Automatically generated configuration.
Do not edit this file manually.
global
uid 80
gid 80
chroot /var/haproxy
daemon
stats socket /var/run/haproxy.socket group proxy mode 775 level admin expose-fd listeners
nbproc 1
nbthread 1
hard-stop-after 60s
tune.ssl.default-dh-param 1024
spread-checks 0
tune.chksize 16384
tune.bufsize 16384
tune.lua.maxmem 0
log /var/run/log local0 info
lua-prepend-path /tmp/haproxy/lua/?.lua
cache opnsense-haproxy-cache
total-max-size 4
max-age 60

defaults
log global
option redispatch -1
timeout client 30s
timeout connect 30s
timeout server 30s
retries 3
default-server init-addr last,libc

autogenerated entries for ACLs
autogenerated entries for config in backends/frontends
autogenerated entries for stats
Frontend: HTTP (Front End HTTP)
frontend HTTP
bind 0.0.0.0:80 name 0.0.0.0:80
mode http
option http-keep-alive
option forwardfor
# tuning options
timeout client 30s

# logging options
# WARNING: pass through options below this line
Frontend: HTTPS (Front End HTTPS)
frontend HTTPS
http-response set-header Strict-Transport-Security "max-age=15768000; includeSubDomains; preload"
bind 0.0.0.0:443 name 0.0.0.0:443 ssl no-sslv3 no-tlsv10 no-tls-tickets ciphers ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256 ciphersuites TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256 alpn h2,http/1.1 crt-list /tmp/haproxy/ssl/5e7eb6cd3ccad8.52678052.certlist
mode http
option http-keep-alive
option forwardfor
# tuning options
timeout client 30s

# logging options
# ACL: Emby_Webserver
acl acl_5e811fc593d624.87923872 hdr(host) -i emby.noobstogeeks.com
# ACL: Unifi_Protect_Websocket_1
acl acl_61bfe65d4066b0.98106842 hdr(Connection) -i upgrade
# ACL: Unifi_Protect_Websocket_2
acl acl_61bfe67f211b51.96043088 hdr(Upgrade) -i websocket



# ACTION: Emby_Webserver
use_backend Emby_Webserver if acl_5e811fc593d624.87923872 !acl_61bfe65d4066b0.98106842 
Backend: Emby_Webserver (Emby Web Server)
backend Emby_Webserver
# health check: Health Check 443
option ssl-hello-chk
mode http
balance source
# stickiness
stick-table type ip size 50k expire 30m
stick on src
# tuning options
timeout connect 30s
timeout server 30s
http-reuse safe
server Emby_Webserver 10.10.40.18:8096 check inter 2s port 443
```

I still get websocket error on my emby server.
https://ibb.co/hy6WctM

Something is missing in Haproxy to support websocket connections. Please help.
Original feature request. 
https://github.com/opnsense/plugins/issues/1907

**Comment by fraenki** [comment]
@patan32 The options that you've requested in #1907 were implemented. I was under the impression that the config snippet that you've provided was a working config. If it still does not work for you, please figure out which option is missing or wrong.

**Comment by patan32** [comment]
Hello fraenki,

How would i know which option is missing? I just went through the Haproxy blog config that was provided. I am not sure what is not ported to the version of Haproxy on Opnsense. When looking at the haproxy documentation i can see they just provide the same two lines. The two lines in Opnsense Haproxy doesn't work clearly. 

What are we missing here. There is few people that have asked this question in forums and facebook page why websocket doesn't work in Opnsense.

**Comment by fraenki** [comment]
@patan32 OPNsense uses an unmodified version of HAProxy. Everything from the official HAProxy [documentation](http://cbonte.github.io/haproxy-dconv/2.2/configuration.html) will work, provided that it is being used in the correct way. However, this is not a HAProxy support forum, so I cannot tell you why Websockets aren't working for you.

**Comment by patan32** [comment]
When you say that haproxy is not modified version then why did you had to add the feature when i asked you last time? Haproxy comes with websocket feature from a long time. It's obvious that something is missing hence why this is not working.  I am not a coder and i don't understand code much but if you can help me figure this out i can give it a try. I am not sure where to start.

**Comment by fichtner** [comment]
@patan32 I get that things are probably lost in translation, but maybe you can try not to come off as someone who doesn't understand what's going on and be actually helpful since you started this in the first place. ;)

**Comment by kulikov-a** [comment]
@patan32 sorry, i dont see where you start to use acl_61bfe65d4066b0.98106842 and acl_61bfe67f211b51.96043088 acls?
I would rather expect to see something like (assuming that the websocket--backend is called Emby_WS):
  use_backend Emby_WS if acl_61bfe65d4066b0.98106842 acl_61bfe67f211b51.96043088
  default_backend Emby_Webserver

**Comment by patan32** [comment]
@kulikov-a  - It's right here:

`# logging options
# ACL: Emby_Webserver
acl acl_5e811fc593d624.87923872 hdr(host) -i emby.noobstogeeks.com
# ACL: Unifi_Protect_Websocket_1
acl acl_61bfe65d4066b0.98106842 hdr(Connection) -i upgrade
# ACL: Unifi_Protect_Websocket_2
acl acl_61bfe67f211b51.96043088 hdr(Upgrade) -i websocket



# ACTION: Emby_Webserver
use_backend Emby_Webserver if acl_5e811fc593d624.87923872 !acl_61bfe65d4066b0.98106842 
Backend: Emby_Webserver (Emby Web Server)
backend Emby_Webserver
# health check: Health Check 443
option ssl-hello-chk
mode http
balance source
# stickiness
stick-table type ip size 50k expire 30m
stick on src
# tuning options
timeout connect 30s
timeout server 30s
http-reuse safe
server Emby_Webserver 10.10.40.18:8096 check inter 2s port 443`

Please see the code on the top.

**Comment by patan32** [comment]
@fraenki @fichtner @kulikov-a I have got it working now. Thanks for everyone's help with this. I am sorry if i upset anyone, i was trying to understand what was going on and i spend couple of hours looking at the config and examples from haproxy. Finally figured out how this should be setup. 

Please close this ticket.

**Comment by fraenki** [comment]
@patan32 Glad that you've got it working. Do you mind to add the solution to this issue, maybe another config export with the working configuration? It might help others in the future :)

**Comment by patan32** [comment]
Here is the working config. 

```
# Frontend: HTTPS (Front End HTTPS)
frontend HTTPS
    http-response set-header Strict-Transport-Security "max-age=15768000; includeSubDomains; preload"
    bind 0.0.0.0:443 name 0.0.0.0:443 ssl no-sslv3 no-tlsv10 no-tls-tickets ciphers ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256 ciphersuites TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256 alpn h2,http/1.1 crt-list /tmp/haproxy/ssl/5e7eb6cd3ccad8.52678052.certlist 
    mode http
    option http-keep-alive
    option forwardfor
    # tuning options
    timeout client 30s

    # ACL: Websocket_Upgrade
    acl acl_61bfe65d4066b0.98106842 hdr(Connection) -i Upgrade
    # ACL: Websocket
    acl acl_61bfe67f211b51.96043088 hdr(Upgrade) -i WebSocket
    # ACL: Websocket_WS
    acl acl_61c0e62bc10459.22208791 hdr_beg(host) -i ws
    # ACL: Emby_Webserver
    acl acl_5e811fc593d624.87923872 hdr_sub(host) -i example.com

    # ACTION: Emby_Websocket
    use_backend Emby_Webserver if acl_61bfe65d4066b0.98106842 acl_61bfe67f211b51.96043088 acl_61c0e62bc10459.22208791
    # ACTION: Emby_WebServer
    use_backend Emby_Webserver if acl_5e811fc593d624.87923872


# Backend: Emby_Webserver (Emby Web Server)
backend Emby_Webserver
    # health check: Health Check 443
    option ssl-hello-chk
    mode http
    balance source
    # stickiness
    stick-table type ip size 50k expire 30m  
    stick on src
    # tuning options
    timeout connect 30s
    timeout server 30s
    http-reuse safe
    server Emby_Webserver 10.10.40.18:8096 check inter 2s port 443 
```

**Comment by jeremiah-k** [comment]
I apologize, I am new to OPNsense and HAProxy, but I have been trying to figure this out for days before I asked.  It seems pretty straightforward to be able to add the lines to the config if we're able to edit it manually, but how is it done with the HAProxy plugin? I've checked the OPNsense HAProxy documentation, but that seems to be for an earlier version with a different layout and the topic of websockets isn't covered.

Would you mind going through the steps needed to generate those lines in the config?  What options to select in Rules, Conditions, Public Services, and if anything special needs to be configured in the backend?

For example, I don't see a place to set `hdr(Connection) -i Upgrade`.  Do I use "http-request header replace value", or "Custom rule (option pass-through)" (with some values) as a rule and then reference that rule in the frontend?

**Comment by kulikov-a** [comment]
@jeremiah-k 

> , I don't see a place to set hdr(Connection) -i Upgrade

i beleive you need to create a condition(s) first, like
![image](https://user-images.githubusercontent.com/36099472/227736698-e1793f21-3e4c-4cc9-9d0e-bb2b7d10f7a5.png)

then make a rule(s) that uses that conditions,  like
![image](https://user-images.githubusercontent.com/36099472/227736819-ce71a3b7-fa4a-49cd-8ad6-8ee407d4ae96.png)

then you can include this rule(s) in frontend settings

**Comment by jeremiah-k** [comment]
This helps a lot. Thank you.

> @jeremiah-k
> 
> > , I don't see a place to set hdr(Connection) -i Upgrade
> 
> i beleive you need to create a condition(s) first, like ![image](https://user-images.githubusercontent.com/36099472/227736698-e1793f21-3e4c-4cc9-9d0e-bb2b7d10f7a5.png)
> 
> then make a rule(s) that uses that conditions, like ![image](https://user-images.githubusercontent.com/36099472/227736819-ce71a3b7-fa4a-49cd-8ad6-8ee407d4ae96.png)
> 
> then you can include this rule(s) in frontend settings
