### ISSUE TITLE
Feature request: iperf3 server and client

### ISSUE THREAD

**Issue by peppelinux** [opnsense/plugins#272]
It would be great to have a configurable istance of iperf3 in 
Interfaces/Diagnostics 

Two menu items in it: 
Server and Client

At the moment: 
from command line I installed iperf3 as well
pkg install iperf3

**Comment by fabianfrz** [comment]
@peppelinux you can get the server in a simple implementation

**Comment by peppelinux** [comment]
Hi Fabian, thank you for your attention.
Actually I'm very busy at the job and hopefully I'll try to push this feature soon as possible but not before January. I'd like also to see my arpscanner plugin in the stable release (not development) before start some other application in OPNsense.
