### ISSUE TITLE
Freeradius - Add option for adding "accept all users" to users config

### ISSUE THREAD

**Issue by chelming** [opnsense/plugins#2722]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

- [x] I have searched the existing issues and I'm convinced that mine is new.

- [x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
I'm trying to move to a single wireless SSID with MAC-based authentication. During this migration I'd like to register all known devices on the FreeRADIUS users table in OPNSense and have any unknown users allowed to connect but falling onto a default VLAN (and thus the guest network captive portal).

**Describe the solution you'd like**
I'd like a checkbox under Services/FreeRADIUS/General/Advanced Options for "Accept all users" that would add `DEFAULT Auth-Type := Accept` to the users config.

🚨 **Solutioning** 🚨
Add a checkbox to the MVC controller [form, general.xml](https://github.com/opnsense/plugins/blob/master/net/freeradius/src/opnsense/mvc/app/controllers/OPNsense/Freeradius/forms/general.xml)
```xml
    <field>
        <id>general.defaultaccept</id>
        <label>Accept all users</label>
        <type>checkbox</type>
        <advanced>true</advanced>
        <help>This allows all users to connect even if they do not exist in the users table.</help>
    </field>
```
As well as adding it as an item in the MVC [model, General.xml]()
```xml
        <defaultaccept type="BooleanField">
            <default>0</default>
            <Required>N</Required>
        </enabled>
```
And finally, adding an if-statement based on that check box inside the [user template after line 100](https://github.com/opnsense/plugins/blob/master/net/freeradius/src/opnsense/service/templates/OPNsense/Freeradius/users#L100) with the following:
```
{% if OPNsense.freeradius.general.defaultaccept == '1' %}
DEFAULT Auth-Type := Accept
{%   endif %}
```

**Describe alternatives you've considered**
- Creating a [target overwrite](https://docs.opnsense.org/development/backend/templates.html#target-overwrites). 
- Removing the plugin and using the freeradius3 package (this would prevent me from using the GUI for adding/removing users)

**Additional context**
None yet 😄

**Comment by mimugmail** [comment]
TBH I'm not a real fan of this solution. I a switch there is usually a the possibility to put a user in a separate VLAN if auth fails. Isn't this possible with your AP's / Wifi Controller? To me the risk is too high that unexperienced users just click this checkbox without knowing the meaning.

**Comment by chelming** [comment]
afaik without `DEFAULT Auth-Type := Accept` there's no way for it to continue? without this option my devices wouldn't connect to the SSID.

>To me the risk is too high that unexperienced users just click this checkbox without knowing the meaning.
That was my idea about putting it as an advanced option. Isn't the risk pretty high for most advanced options? Perhaps a more obvious warning?

>This allows all users to connect even if they do not exist in the users table. WARNING: This will allow un-authenticated users to continue as if they authenticated.

**Comment by Alanin** [comment]
Hi, there is already a pull request addressing that https://github.com/opnsense/plugins/pull/2566
