### ISSUE TITLE
[os-wireguard] Resolve hostname instead of requiring IP in "peer - endpoint address"

### ISSUE THREAD

**Issue by TheHellSite** [opnsense/plugins#2727]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[+] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
[+] I have searched the existing issues and I'm convinced that mine is new.
[+] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
Currently the WireGuard plugin for OPNsense is not able to resolve hostnames set in the endpoint address of a peer. It only accepts IPs otherwise the interface is not created.

This is a bit problematic for a few reasons:
1. Site-to-Site tunnels won't work reliable for (home) internet connections not having a static IP.
2. Using specific destination countries of VPN providers, f.e. `nl.vpnprovider.tld`.
3. It also breaks "load-balancing" / "choosing the best server before connection" for VPN providers.

**Describe the solution you'd like**
I would like the WireGuard plugin to be able to resolve public hostnames.

**Describe alternatives you've considered**
Resolving the hostname to IP everytime the IP changed.

**Additional context**
N/A

**Comment by AdSchellevis** [comment]
I would advise against allowing hostnames to prevent re-introducing past mistakes. If the service itself has valid means of resolving the address, it's no problem, but if it all relies on other components signaling changes, it's disaster waiting to happen.

**Comment by mimugmail** [comment]
On the server just leave endpoint empty for dynamic IPs, works great

**Comment by TheHellSite** [comment]
> I would advise against allowing hostnames to prevent re-introducing past mistakes. If the service itself has valid means of resolving the address, it's no problem, but if it all relies on other components signaling changes, it's disaster waiting to happen.

Any other wireguard client software (android, windows, ...) is able to resolve hostnames set as a peers endpoint address.
I was not talking about checking every few minutes for changes to the endpoints hostname. I was only talking about resolving the hostname once before the connection is initiated.

> On the server just leave endpoint empty for dynamic IPs, works great

This I know. I am already using WireGuard on my OPNsense with a road-warrior setup to connect to my home network.

I am also using OpenVPN on OPNsense with my VPN provider (AirVPN) to route specific clients through the tunnel, which is working great. Since my VPN know supports wireguard I would like to replace OpenVPN.

I mean the tunnel is working but only if I set the IP of a server as endpoint in the peer config.

**Comment by mimugmail** [comment]
> I was not talking about checking every few minutes for changes to the endpoints hostname. I was only talking about resolving the hostname once before the connection is initiated.

Is this a guess or do you really know that wireguard itself (not the plugin) tries to resolve before a "connection"? Wireguard is connection-less, there is no server handling open connections, an outgoing packet gets encrypted when it matched against the endpoint IP. And to fight against connection handlers in firewalls there is a keepalive. I'm not sure how many times the FQDN in wireguard tries to resolve against an IP. Do you have a doc where this is explained?

**Comment by TheHellSite** [comment]
I can't provide a doc, but the windows and android client software does it fine.

This is what my config files for ALL devices connecting to my OPNsense look like.
```
[Interface]
PrivateKey = privkey
Address = 10.15.87.21/32

[Peer]
PublicKey = pubkey
PresharedKey = pskey
AllowedIPs = 10.153.0.0/16
Endpoint = vpn.domain.tld:59501
PersistentKeepalive = 25
```

It resolves the hostname once when activating the profile.

**Comment by mimugmail** [comment]
Yes, but what happens when the server changes its IP? How often does the wireguard client tries to look up for a new IP?

**Comment by TheHellSite** [comment]
It obviously won't notice that and will not re-resolve the hostname and I am fine with that.

It would still be nice if if the OPNsense plugin would resolve the hostname just once during the initiation of the connection. Like all other wireguard clients do.

**Comment by agh1467** [comment]
I may be missunderstanding something here. If the field at the center of the discussion is this one:

https://github.com/opnsense/plugins/blob/master/net/wireguard/src/opnsense/mvc/app/models/OPNsense/Wireguard/Client.xml#L30-L32

Which is the field located at Wireguard - > Endpoints Tab -> Edit Endpoint -> Endpoint Address. It's configured as a `HostnameField`, and has no additional constraints beyond those set for the field type, which allow for entering a hostname in the format of `nl.vpnprovider.tld`.

`wg` supports hostname in the `Endpoint` field along with IP address.

https://git.zx2c4.com/wireguard-tools/about/src/man/wg.8
>This example may be used as a model for writing configuration files, following an INI-like syntax. Characters after and including a ’#’ are considered comments and are thus ignored.
>
>[Interface]
>PrivateKey = yAnz5TF+lXXJte14tji3zlMNq+hd2rYUIgJBgB3fBmk=
>ListenPort = 51820
>
>[Peer]
>PublicKey = xTIBA5rboUvnH4htodjb6e697QjLERt1NAB4mZqp8Dg=
>Endpoint = 192.95.5.67:1234
>AllowedIPs = 10.192.122.3/32, 10.192.124.1/24
>
>[Peer]
>PublicKey = TrMvSoP4jYQlY6RIzBgbssQqY3vxI2Pi+y71lOWWXX0=
>Endpoint = [2607:5300:60:6b0::c05f:543]:2468
>AllowedIPs = 10.192.122.4/32, 192.168.0.0/16
>
>[Peer]
>PublicKey = gN65BkIKy1eCE9pP1wdc8ROUtkHLF2PfAqYdyYBz6EA=
>Endpoint = test.wireguard.com:18981
>AllowedIPs = 10.10.10.230/32

It's described in the documentation as such:
>Endpoint — an endpoint IP or hostname, followed by a colon, and then a port number. This endpoint will be updated automatically to the most recent source IP address and port of correctly authenticated packets from the peer. Optional.

The documentation doesn't discuss specifics about frequency of DNS queries, or if the DNS name is re-requested with any kind of regularity. The source code has specific activities related to DNS lookup of the endpoint:
https://git.zx2c4.com/wireguard-tools/tree/src/config.c#n241

I'd guess that if the endpoint IP were to change, then the IP that that `wg` was connected with would stop working, and a connection re-establish would occur, and a DNS lookup would happen during that process.

Also, I tried this just now, and the DNS name is used in the `wg0.conf` configuration file, `wg` resolves the DNS name successfully, and shows the IP address in the List Connection tab. This demonstrates that it's able to take a DNS name, resolve it, and connect to the IP address all by itself, and the plugin allows this to happen already. Maybe I'm looking at the wrong field?

**Comment by mimugmail** [comment]
Indeed, its already a HostnameField

https://github.com/opnsense/plugins/blob/master/net/wireguard/src/opnsense/mvc/app/models/OPNsense/Wireguard/Client.xml#L30

**Comment by TheHellSite** [comment]
> I may be missunderstanding something here. If the field at the center of the discussion is this one:
> 
> https://github.com/opnsense/plugins/blob/master/net/wireguard/src/opnsense/mvc/app/models/OPNsense/Wireguard/Client.xml#L30-L32
> 
> Which is the field located at Wireguard - > Endpoints Tab -> Edit Endpoint -> Endpoint Address. It's configured as a `HostnameField`, and has no additional constraints beyond those set for the field type, which allow for entering a hostname in the format of `nl.vpnprovider.tld`.
> 
> `wg` supports hostname in the `Endpoint` field along with IP address.

Yes I am talking about exactly that field. I know that WireGuard supports hostnames in the endpoint address and this is working great for every client application (windows, macos, linux, android, ...) **except for the OPNsense plugin**.

It is not working on OPNsense, I tried it a dozen times. The same config however works great on any other system.
Maybe my ticket should be a bug then and not a feature request.

> Also, I tried this just now, and the DNS name is used in the `wg0.conf` configuration file, `wg` resolves the DNS name successfully, and shows the IP address in the List Connection tab. This demonstrates that it's able to take a DNS name, resolve it, and connect to the IP address all by itself, and the plugin allows this to happen already. Maybe I'm looking at the wrong field?

You are looking at the right field.  I am also well aware of the fact that WireGuard is not (yet?) re-resolving hostnames after not getting a handshake within a certain timeframe. But this is not the issue here.

---

My issue is related to the fact that the WireGuard plugin for OPNsense is NOT resolving hostnames defined in the endpoint address field. Please see my screenshot below.

![grafik](https://user-images.githubusercontent.com/34900685/147814541-05f26830-b640-4477-8352-11e22abc5bdc.png)

**Green field in the screenshot**
Setting up the peer using an IP in the endpoint address is working fine. I add the peer in the "Local" tab to the wg1_instance, hit save and then apply. I go to "List Configuration", I can see the wg1 instance is listed there with the peer below it and I also see traffic flow to the peer.

**Red field in the screenshot**
Setting up the peer using an FQDN in the endpoint address is NOT working. I add the peer in the "Local" tab to the wg1_instance, hit save and then apply. I go to "List Configuration" but this time the wg1 instance is NOT listed there and the peer is also obviously not there.

**Comment by mimugmail** [comment]
If its accepted when added its obviously your Firewall not able to resolve it.

**Comment by TheHellSite** [comment]
But the OpenVPN plugin is able to resolve these FQDNs and all other plugins are also able to resolve them.

**Comment by mimugmail** [comment]
Try 

/usr/local/etc/rc.d/wireguard restart

Via console and post the output

**Comment by fichtner** [comment]
Maybe wireguard dns override again?

**Comment by TheHellSite** [comment]
```
[#] ifconfig wg create name wg1
[!] Missing WireGuard kernel support (ifconfig: SIOCIFCREATE2: Invalid argument). Falling back to slow userspace implementation.
[#] wireguard-go wg1
┌──────────────────────────────────────────────────────┐
│                                                      │
│   Running wireguard-go is not required because this  │
│   kernel has first class support for WireGuard. For  │
│   information on installing the kernel module,       │
│   please visit:                                      │
│         https://www.wireguard.com/install/           │
│                                                      │
└──────────────────────────────────────────────────────┘
[#] wg setconf wg1 /dev/stdin
Name does not resolve: `nl.vpn.airdns.org:1637'
Configuration parsing error
[#] rm -f /var/run/wireguard/wg1.sock
```

It is indeed not resolving the DNS.

**Comment by fichtner** [comment]
No, it’s falling back to wireguard-go („slow implementation“) as intended.

**Comment by mimugmail** [comment]
Its definetly not a general problem as I wrote the guides for Mullvad and Azire and they both use DNS names too

**Comment by TheHellSite** [comment]
I found the issue. It was so stupid...

I recently changed the subnets of my network and one of my wireguard instances still had the old dns address left in it.
This caused the systems dns to stop working. So it every restart of the wireguard plugin crashed the system dns. The network client dns (unbound on opnsense) was still working so I didn't notice it.
