### ISSUE TITLE
Feature request: flush ARP cache

### ISSUE THREAD

**Issue by peppelinux** [opnsense/plugins#273]
It would be great to have in
Interfaces/Diagnostics/ARP Table

a button to flush ARP table for diagnostics.
This could be usefull in case of:
 - ARP poison
 - just-changed-ip as AP or others critical nodes
 - diagnosys on ARP loop and unwanted ARP proxy (after flush something will be more visible if happens)

**Comment by fichtner** [comment]
this belongs to the core repo, not plugins :)
