### ISSUE TITLE
OpenConnect username too long

### ISSUE THREAD

**Issue by jyourstone** [opnsense/plugins#2735]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

- [X] I have searched the existing issues and I'm convinced that mine is new.

- [X] The title contains the plugin to which this issue belongs

**Describe the bug**

I want to setup an OpenConnect VPN connection to my office. We use LDAP to connect and the username is in the format UserPrincipalName. The problem I have now is that my username is 34 characters, and the max username length when configuring OpenConnect in OPNSense is 32 characters. Is there a reason the max length is 32 characters for usernames?

**To Reproduce**
1. Download the OpenConnect plugin
2. Enter a username that is longer than 32 characters
3. Click "Save"

**Expected behavior**
It would be great if the max username length could be increased.

**Environment**
OPNsense 21.7.7-amd64

**Comment by fichtner** [comment]
32 chars is the UNIX limit, but since we're not using those we should be able to relax the validation.


Cheers,
Franco

**Comment by jyourstone** [comment]
That was fast, thank you very much!
