### ISSUE TITLE
www/nginx: default_server not applied to https servers

### ISSUE THREAD

**Issue by 8191** [opnsense/plugins#2741]
The `default_server` directive is only applied to the non-ssl listed part. I.e.:

```
server {

    listen 80 default_server;
    listen [::]:80 default_server;

    listen 443 http2 ssl;
    listen [::]:443 http2 ssl;
```

__Originally posted by @8191 in https://github.com/opnsense/plugins/pull/2578#issuecomment-1002718288__

**Comment by fichtner** [comment]
no need to open a ticket if you have a PR ready... you can always explain in the PR :)
