### ISSUE TITLE
DynDNS pushes temporary private IP address to dynamic DNS provider

### ISSUE THREAD

**Issue by maxkratz** [opnsense/plugins#2745]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

-> I'm not quite sure about the second checkbox. There are at least two "related" but somehow different issues. I will differentiate this issue to these two below:
* https://github.com/opnsense/core/issues/2368
* https://github.com/opnsense/core/issues/3422

**Describe the bug**

From time to time, OPNsense, i.e. the dynamic DNS plugin, publishes a private IP address. In my case, this IP address is always `192.168.1.1` which I do not use and which is outside of all local subnets configured on my OPNsenes box.

* In contrast to https://github.com/opnsense/core/issues/2368, I do not have any other router or NOT *before* the OPNsense system. In my case, the OPNsense box is directly connected to a VDSL "modem" and uses PPPoE to authenticate.
* In contrast to https://github.com/opnsense/core/issues/3422, the bug occurs even if the DSL connection did **not** break.

**To Reproduce**

1. Setup dynamic DNS (in my case with https://no-ip.com).
2. Configure OPNsense to push new IP addresses to https://no-ip.com
3. Wait a longer period of time.

(I'm sorry, but I'm unable to give further information on how to reproduce the bug :(.)

**Expected behavior**

Never push any other IP than the public IP to the dynamic DNS provider.

**Describe alternatives you considered**

I've configured another dynamic DNS provider (self-hosted, uses only curl). This one did not receive the wrong IP but I'm not quite sure if that's just a coincidence.

**Screenshots**

**Relevant log files**

![Bildschirmfoto_2022-01-06_09-06-01](https://user-images.githubusercontent.com/20956405/148426201-bea96300-19de-47d2-a0b6-6209ded7d9be.png)

**Additional context**

Dynamic DNS plugin configuration:
![Bildschirmfoto_2022-01-06_18-39-31](https://user-images.githubusercontent.com/20956405/148426452-7df84703-93ff-4174-813f-8e52818c1185.png)

**Environment**

Software version used and hardware type if relevant, e.g.:

* OPNsense 21.7.7-amd64
* I'm sure that this issue did also affect multiple earlier versions, but I'm unable to tell on which version it started.
* (Hardware should not be relevant for this issue.)

**If you need any other information, please let me know!**

----

CC @HackHerz (also affected IIRC)

**Comment by fichtner** [comment]
> Never push any other IP than the public IP to the dynamic DNS provider.

I think there is misunderstanding of what the "dummy" update is trying to achieve here.

But anyway the real issue seems to be the 15 seconds timeout on the update. Maybe you want to look into why that happens because I cannot.


Cheers,
Franco

**Comment by maxkratz** [comment]
@fichtner Thank you for your fast response!

> I think there is misunderstanding of what the "dummy" update is trying to achieve here.

I'm quite sure the misunderstanding is on my side. Can you please clarify it for me?

> But anyway the real issue seems to be the 15 seconds timeout on the update. Maybe you want to look into why that happens because I cannot.

Do I understand the timeline correctly?

* IP set to `192.168.1.1` temporarily.
* Propagate IP to https://no-ip.com
* Curl timeout (What is curl used for in this step? Get the public IP from an external site? Propagate the IP to https://no-ip.com ?)

**Comment by marjohn56** [comment]
Alternative is to just prevent DynDNS from ever using anything in the private IP range. As I've volenteered to take this under the TR umbrella I can do and issue a PR.

**Comment by maxkratz** [comment]
@marjohn56 Yes, but I do not use `192.168.1.0/24` as a private IP range on my OPNsense firewall. I'm glad you volunteered to issue a PR :).

**Comment by marjohn56** [comment]
I assume it's the WAN interface that you want to set the DDNS address for. It's likely that the WAN interface is picking up the 192.168.1.1 address from the modem. This sometimes happens if the ISP connection resets and the modem gives out that address before it gets the propper address from the ISP. You can also get around this issue by entering the address of the modem in the 'Reject Leases from' field in the DHCP client config settings on the WAN interface page. The only issue there is that you need to know the address the modem is using when it hands out the lease, and it won't be 192.168.1.1!
Whatever, I'll add a bit of putty that will force DynDNS to skip if the address is in the RFC 1918 range.

**Comment by maxkratz** [comment]
Thank you for the explanation, that makes sense to me.

And once again thank you for updating the DynDNS plugin to skip private addresses!

**Comment by marjohn56** [comment]
Rather odd that it happens, however I've pushed a routine in that checks the address being used for the update is not in the RFC1918 ranges.  You can try the patch in the PR above to see if that fixes it for you.

**Comment by fichtner** [comment]
Sorry for not following up earlier. Basically this is being set for the provider:

https://github.com/opnsense/plugins/blob/6a7babcf20398b1fa845deff35edcda498384925/dns/dyndns/src/etc/inc/plugins.inc.d/dyndns/phpDynDNS.inc#L371-L374

Either we disable dummy updates if the provider doesn't lock you out for not having your address changing or all of this is looking at it from the wrong end.

**Comment by maxkratz** [comment]
@fichtner Do I understand you correctly: The problem with the IP issued by the modem is not the problem in my case?

Maybe the dummy updates could be made "opt-out" in the DynDNS settings? With this change, normal behavior would be fine (at least for most people). People with the problem discussed here could then simply remove the flag.

Another idea that comes to my mind: If an IP update fails (like my second one, after the dummy one) the DynDNS mechanism could re-try several times. This should resolve my problem, too.

**Comment by marjohn56** [comment]
Yes, understood. Fortunaly I've never used a ddns provider that requires me to update once a month to keep it free; I can see thier logic though, OK, I'll bin that PR and re-think this. I'll create my own account at no-ip and see what gives. Might not be able to get back to this until next week though.

**Comment by maxkratz** [comment]
@marjohn56 AFAIK, the dummy update is not necessary for no-ip. I've other (consumer) routers that have the no-ip DynDNS functionality built-in and they do not necessarily update the IP every month.

**Comment by marjohn56** [comment]
I think perhaps the best way forward, so as not to break systems where it obviously does work, or we'd have heard about it, is to add a flag in the GUI to enable/disable dummy updates.

**Comment by maxkratz** [comment]
This would be a good solution, at least in my opinion.

Additionally, I would welcome a parameter in the advanced tab to configure:
* Number of curl retries (if, e.g., the connection is temporarily broken)
* Time delta for periodic re-tries if curl fails
* etc.

**Comment by marjohn56** [comment]
I've set up a free no-ip account and  I cannot make it fail, works every time. Logs show me updating using the dummy, then 10 seconds later it updates with the correct address. I'll keep trying to make it fail though.

**Comment by maxkratz** [comment]
> I've set up a free no-ip account and I cannot make it fail, works every time. Logs show me updating using the dummy, then 10 seconds later it updates with the correct address. I'll keep trying to make it fail though.

Maybe @fichtner is correct and the problem with my instance was that the second update (with the "real" IP) did not come through. If that is correct, the procedure can be the following:

1. Dummy IP update to no-ip succeeds.
2. curl (update with "real" IP) fails, e.g., because of a broken VDSL connection.
3. OPNsense/the DynDNS plugin logs an error and the dummy IP was the last IP submitted to no-ip.

Possible solutions:
1. Option to disable the dummy IP update completely.
2. Implement a re-try mechanism in case a curl IP update fails.
