### ISSUE TITLE
Support restart of FreeRadius from Acme Client

### ISSUE THREAD

**Issue by F13** [opnsense/plugins#2749]
Hi all,

It would be great if the system/plugin commands options in the Acme Client automations could include a restart of the FreeRadius plugin. Or, otherwise, if it were included as a specific command that could be run. I am using Acme Client issued certificates in my FreeRadius configuration, but without a service restart new certs don't get picked up on renew.

Based on what I'm reading here: https://forum.opnsense.org/index.php?topic=8679.0, I guess all that needs to happen is for FreeRadius restart actions to include a description that is captured by Acme Client's filter. As far as I can tell, the FreeRadius actions do not have descriptions at this time.

**Comment by fichtner** [comment]
#2718
