### ISSUE TITLE
security/acme-client: automations SFTP upload 'password' for login missing

### ISSUE THREAD

**Issue by rantwolf** [opnsense/plugins#2751]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[check] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[check] I have searched the existing issues and I'm convinced that mine is new.

[check] The title contains the plugin to which this issue belongs

**Describe the bug**
I requested a wildcard certificate for my internal devices.
It can be automatically uploaded to synology and some other devices.
But I have some devices which can't export the public key.

**Expected behavior**
Is it possible to add a password field for the SFTP upload automation?
So I can always use the updated certificate automatically on this devices too.
 
**Environment**
Software version used and hardware type if relevant.
e.g.:

OPNsense 21.7.7 (amd64, OpenSSL).
AMD® Ryzen™ V1605 Quad Core
Network: VirtIO

**Comment by fraenki** [comment]
> But I have some devices which can't export the public key.
> Is it possible to add a password field for the SFTP upload automation?

I'm sorry, I don't understand. How are these two things related to each other? Please explain in more detail why a password field is necessary and how exactly this should change the current behaviour.

**Comment by rantwolf** [comment]
Sorry for the delay. It was my fault. I missunderstand the directions.
