### ISSUE TITLE
net/wireguard: Local Configuration - Maximum number of instances reached

### ISSUE THREAD

**Issue by astuckey123** [opnsense/plugins#2759]
https://github.com/opnsense/plugins/blob/f8f3975e00560425bd1de3136320d181a83e4f84/net/wireguard/src/opnsense/mvc/app/models/OPNsense/Wireguard/Server.xml#L20

It looks like we are hard-coding the maximum number of WG local configurations to 20.
Can this be increased, or the limitation be removed altogether?
I haven't been able to find any evidence so far on an actual limitation within WG itself (could be lack of googling skill here too, so happy to stand corrected)

**Comment by mimugmail** [comment]
You know that you dont need acseparate instance for every s2s? Cant imagine you need more than 5 :)

I came from early days where WireGuard vittselfself was unstable

**Comment by astuckey123** [comment]
> You know that you dont need acseparate instance for every s2s? Cant imagine you need more than 5 :)
> 
> I came from early days where WireGuard itself was unstable

Lots of BGP and OSPF international overlay networking over multiple clouds and on-prem sites where they each need their own interfaces and policies, but you are right, can probably squeeze some things into single WG local's.

**Comment by mimugmail** [comment]
Cool :) next version wont come with any limits. Maybe you want to Share your setup in a blogpost. Always nice to see how others are using OPNsense :)
