### ISSUE TITLE
possible core issue in service start order: c-icap + clamav

### ISSUE THREAD

**Issue by kekek2** [opnsense/plugins#276]
When system boots, c-icap starts before clamd, and could not open tcp socket:

> Mon Sep 18 15:38:12 2017, main proc, clamd_connect: Can not connect to clamd server on 127.0.0.1:3310!
> Mon Sep 18 15:38:12 2017, main proc, clamd_init: Error while sending command to clamd server
> Mon Sep 18 15:38:12 2017, main proc, Registry 'virus_scan::engines' does not exist!

**Comment by fichtner** [comment]
This may be a glitch in the proverbial matrix... https://github.com/opnsense/core/blob/master/src/etc/rc.freebsd starts services in a more or less fixed random order

**Comment by mimugmail** [comment]
@kekek2 Where do you get this error? I can't reproduce it. I'm seeing c_icap starting before clamd but I dont see such errors.

**Comment by fichtner** [comment]
I think it can depend on how the file system returns the file names from the disk ;/

https://github.com/opnsense/core/blob/master/src/etc/rc.freebsd#L68

**Comment by kekek2** [comment]
/var/log/system.log:
> Sep 15 12:19:12 vibro kernel: <118>Starting c_icap.
> Sep 15 12:19:12 vibro kernel: <118>Starting clamav_clamd.

/var/log/c-icap/server.log:
> Fri Sep 15 12:20:26 2017, main proc, clamd_connect: Can not connect to clamd server on 127.0.0.1:3310!
> Fri Sep 15 12:20:26 2017, main proc, clamd_init: Error while sending command to clamd server

time configctl clamav start
> OK
> configctl clamav start  0,07s user 0,06s system 0% cpu 1:27,73 total

**Comment by mimugmail** [comment]
But it retries and finally works without manual interaction, correct?

**Comment by kekek2** [comment]
Only manual restart c_icap

> Tue Sep 19 07:33:52 2017, main proc, clamd_connect: Can not connect to clamd server on 127.0.0.1:3310!
> Tue Sep 19 07:33:52 2017, main proc, clamd_init: Error while sending command to clamd server
> Tue Sep 19 07:33:52 2017, main proc, Registry 'virus_scan::engines' does not exist!
> Tue Sep 19 12:05:49 2017, 39401/1742841344, Registry 'virus_scan::engines' does not exist!
> Tue Sep 19 12:05:49 2017, 39401/1742841344, Registry 'virus_scan::engines' does not exist!
> Tue Sep 19 12:05:49 2017, 39401/1742840064, Registry 'virus_scan::engines' does not exist!
> Tue Sep 19 12:05:49 2017, 39401/1742840064, Registry 'virus_scan::engines' does not exist!
> Tue Sep 19 12:05:49 2017, 39401/1742840064, Antivirus engine is not available, allow 204
>

**Comment by fichtner** [comment]
I dunno, maybe we need to delay a bit after c-icap start?

**Comment by mimugmail** [comment]
Why isn't there a numbering scheme like on linux with S03clamd where you can easily set a boot order? :/

**Comment by fichtner** [comment]
well there is but it requires the full rc system of freebsd or better emulation to allow ordering

**Comment by fabianfrz** [comment]
@mimugmail on current GNU/Linux this does not exist as well (1). What you can do is writing a dependency into the unit file which should also work with with rc. 

(1) look for "After" in systemd service files

**Comment by ffries** [comment]
Same issue here.

**Comment by Stephanowicz** [comment]
Is there a way to 're-register' the clamav module without restarting c-icap?
(Even better would be that c-icap would do it automatically...)

**Comment by fichtner** [comment]
you can also cycle c-icap the same way?

**Comment by kekek2** [comment]
My workaround

diff --git a/www/c-icap/src/opnsense/scripts/OPNsense/CICAP/setup.sh b/www/c-icap/src/opnsense/scripts/OPNsense/CICAP/setup.sh
index 9e1e741..e84a7d5 100755
--- a/www/c-icap/src/opnsense/scripts/OPNsense/CICAP/setup.sh
+++ b/www/c-icap/src/opnsense/scripts/OPNsense/CICAP/setup.sh
@@ -7,3 +7,52 @@ chmod 750 /var/run/c-icap
 mkdir -p /var/log/c-icap
 chown -R c_icap:c_icap /var/log/c-icap
 chmod 750 /var/log/c-icap
+
+# check which services to enable
+if [ -f /etc/rc.conf ]; then
+	. /etc/rc.conf
+fi
+if [ -f /etc/rc.conf.local ]; then
+	. /etc/rc.conf.local
+fi
+for RC_CONF in $(find /etc/rc.conf.d -type f); do
+	. ${RC_CONF}
+done
+
+rc_enabled()
+{
+	rc_filename=${1}
+	name=${2}
+
+	# check if service has a name
+	if [ -z "${name}" ]; then
+		echo "Error: no name set in ${rc_filename}"
+		return 1
+	fi
+
+	# check if service has a variable
+	eval "$(grep "^rcvar[[:blank:]]*=" ${rc_filename})"
+	if [ -z "${rcvar}" ]; then
+		# FreeBSD does this, leave here for debugging
+		#echo "Error: no rcvar set in $rc_filename"
+		return 1
+	fi
+
+	# check if service is enabled
+	eval "enabled=\$${rcvar}"
+	if [ "${enabled}" != "YES" ]; then
+		return 1
+	fi
+
+	return 0
+}
+
+rc_filename="/usr/local/etc/rc.d/clamav-clamd"
+eval "$(grep "^name[[:blank:]]*=" ${rc_filename})"
+
+if ! rc_enabled ${rc_filename} ${name}; then
+	return 0
+fi
+
+/usr/local/opnsense/scripts/OPNsense/ClamAV/setup.sh
+${rc_filename} start

**Comment by kekek2** [comment]
The formatting was off...

**Comment by Stephanowicz** [comment]
@fichtner 
>you can also cycle c-icap the same way?

...You mean me?^^
I now created a restart script for clamd which is called by monit when clamd crashes 

```
#!/bin/sh

/usr/local/etc/rc.d/clamav-clamd start
sleep 5
/usr/local/etc/rc.d/c-icap restart

```

**Comment by fichtner** [comment]
@Stephanowicz yes, does this work as expected?

**Comment by Stephanowicz** [comment]
yep, I tried it manually by stopping clamd....

Nevertheless I consider this jut as a workaround  - maybe the c-icap guys could implement something that tries to start the av-scanner when detecting that it can't be accessed and then reinits the Connection...

**Comment by fichtner** [comment]
Ok so we know what to do, now we need to figure out a robust way to integrate it.

Alex’s suggestion isn’t bad but it should ideally be more portable / avoid code duplication.

**Comment by Stephanowicz** [comment]
Ok, meanwhile I stumbled over the same problem as in OT...

Regarding monit and its possibility to also test file contents I made another workaround:

In monit add a new test with condition
`content = "Registry 'virus_scan::engines' does not exist" for 3 cycles`
(not tested enough, yet - could be that one needs to lower this to 2 cycles or to remove it completely)

then add a new service test with `file` as type and `/var/log/c-icap/server.log` as path
As start option I used the script mentioned above - it does not check if clamd is already running - but this does not matter as the clamd startscript itself takes care of this. (maybe it would be even better to use the `restart` option...?)

One 'annoying' thing is, that You have to add a start/stop/restart parameter, though it's not needed...

One also needs to enter a stop script, otherwise You'll get a syntax error - I used `/usr/local/etc/rc.d/c-icap stop` - probably a dummy script would be the better solution...

As test enter the test You created before.

I copied the error text manually to the log file for testing  and received a 

> Sep 30 16:45:05 lifesense monit[18659]: 'c-icap' content match: Sat Sep 30 16:44:46 2017, 36646/3592524288, Registry 'virus_scan::engines' does not exist!


hope this helps!

Cheers,

Stephan

**Comment by Stephanowicz** [comment]
After having tested it now thoroughly I changed the test condition to
`content = "(Registry 'virus_scan::engines' does not exist)|(clamd_connect: Can not connect to clamd server)" for 2 cycles`
when stopping clamd the first condition doesn't show up, but the second one.

It also has been shown that c-icap doesn't restart properly in this condition - but monit will try it again the next cycle and then succeeds...

So, this is working, but it feels somehow like a dirty hack... :D

**Comment by Stephanowicz** [comment]
Update:
After a scheduled reboot this morning we had the same issue that c-icap was started before clamd.
Monit resolved it properly:

```
Oct 1 04:05:22 monit[11037]: 'lifesense.life' Monit 5.24.0 started 

Oct 1 04:05:23 monit[11037]: 'c-icap' content match: Sun Oct 1 04:03:04 2017, main proc, clamd_connect: Can not connect to clamd server on 127.0.0.1:3310! Sun Oct 1 04:03:04 2017, main proc, Registry 'virus_scan::engines' does not exist! Sun Oct 1 04:03:42 2017, 97721/253863424, Registry 'virus_scan::engines' does not exist! Sun Oct 1 04:03:42 2017, 97721/253863424, Registry 'virus_scan::engines' does not exist! Sun Oct 1 04:03:54 2017, 97721/253854464, Registry 'virus_scan::engines' does not exist! Sun Oct 1 04:03:54 2017, 97721/253854464, Registry 'virus_scan::engines' does not exist! ... 

Oct 1 04:07:23 monit[11037]: 'c-icap' content match: Sun Oct 1 04:07:02 2017, 97721/253863424, Registry 'virus_scan::engines' does not exist! Sun Oct 1 04:07:02 2017, 97721/253854464, Registry 'virus_scan::engines' does not exist! Sun Oct 1 04:07:02 2017, 97721/253863424, Registry 'virus_scan::engines' does not exist! 

Oct 1 04:07:23 monit[11037]: 'c-icap' start: '/usr/local/etc/c-icap/restart start' 

Oct 1 04:09:39 monit[11037]: 'c-icap' content doesn't match 
```

Cheers, Stephan

**Comment by fabianfrz** [comment]
@mimugmail maybe patching this section may help:

![spectacle p15107](https://user-images.githubusercontent.com/3713914/31054012-71850f7a-a6a9-11e7-9f61-c87be5c24c82.png)

The file is `/usr/local/etc/rc.d/c-icap`

**Comment by fichtner** [comment]
No this won’t help as we don’t use the full RC system.

**Comment by fabianfrz** [comment]
@fichtner This is not even the full issue for your information. If the ICAP server is down, squid will make troubles too (it will say that it cannot reach the ICAP server and blocks the connection (it will mark the server as down).

The advantage here is that squid connects to the ICAP server as soon as it gets an HTTP request so this is a bit dangerous as a race condition too.

**Comment by fichtner** [comment]
Should be simple and effective: https://github.com/opnsense/plugins/blob/79d4a7c79f7652ffbe2cadec397c26acdc6f033d/www/c-icap/src/etc/rc.syshook.d/50-c-icap.start

Please share your test results. :)

**Comment by Stephanowicz** [comment]
Hi, thank You - well, anything else that needs to be done - or just copy the file to rc.syshook.d?

Cheers, Stephan

**Comment by fichtner** [comment]
Hi @Stephanowicz,

Yes, copy file, make sure to chmod to 755.


Cheers,
Franco
