### ISSUE TITLE
net/haproxy: Allow exporting prometheus metrics

### ISSUE THREAD

**Issue by onedr0p** [opnsense/plugins#2764]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

[x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**

I would like to gather metrics from haproxy with prometheus.

**Describe the solution you'd like**

Haproxy has native support for a prometheus endpoint, see this [blog post](https://www.haproxy.com/blog/haproxy-exposes-a-prometheus-metrics-endpoint/) for more detail.

It would be cool to have this configurable in the UI.

**Describe alternatives you've considered**

n/a

**Additional context**

n/a

**Comment by fraenki** [comment]
Instead of pointing to a rather lengthy blog post, would you please describe the options _you_ would like to see in OPNsense?

**Comment by onedr0p** [comment]
Sure, it would be nice to have an option to turn on the metrics endpoint, which looks like the option would configure this prometheus line in the config below.

```bash
frontend stats
   bind *:8404
   option http-use-htx
   # This line below turns on prometheus metrics
   http-request use-service prometheus-exporter if { path /metrics }
   stats enable
   stats uri /stats
   stats refresh 10s
```

**Comment by fichtner** [comment]
@fraenki did you want to take this maybe?

**Comment by fraenki** [comment]
Maybe. I'll reopen it.

**Comment by fraenki** [comment]
The next version of the HAProxy plugin will include two ways to enable a Prometheus exporer:
* `Settings -> Statistics` –  a simple one-click option
* `Virtual Services -> Public Services` – an advanced option (hidden by default) with all frontend customization options
