### ISSUE TITLE
[node_exporter] update to most recent version

### ISSUE THREAD

**Issue by onedr0p** [opnsense/plugins#2765]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

[x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**

As of writing node_exporter is on 1.3.1

**Describe the solution you'd like**

Update node_exporter to the latest version

**Describe alternatives you've considered**

n/a

**Additional context**

n/a

**Comment by onedr0p** [comment]
Looks like 1.3.1 is the latest there too,
https://www.freshports.org/sysutils/node_exporter/

Does anything need to be done on the opnsense side to bring it over?

**Comment by fichtner** [comment]
Is the latest here too ;)

https://github.com/opnsense/ports/commit/8d7024656a535e7b04029ab3335d26281f9c2c45#diff-fa5888535be143fda9d2c3e49662a2d15f23a1696a6f9c8c09dd5da12d886517

**Comment by onedr0p** [comment]
My mistake, looks like it is! I'll make sure to check more places next time, thanks!
