### ISSUE TITLE
security/maltrail flagging its own blacklist.txt requests (solved by maltrail update)

### ISSUE THREAD

**Issue by BernhardHH** [opnsense/plugins#2768]
**Important notices**
[Y] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
[Y] I have searched the existing issues and I'm convinced that mine is new.
[Y] The title contains the plugin to which this issue belongs

**Describe the bug**

See https://github.com/stamparm/maltrail/issues/19044

Maltrail flags its own request for blacklist.txt as medium threat.

According to maltrail maintainer, this has been solved in newer versions.

**To Reproduce**

Check for the IP 185.53.177.52 (ipnoise.now.im) in maltrail (daily request)

**Expected behavior**

No threat logged.

**Screenshots**
See https://github.com/stamparm/maltrail/issues/19044

**Environment**
OPNsense 21.7.7 (amd64, OpenSSL).
os-maltrail 1.8

**Comment by fichtner** [comment]
Fair enough, but I don't think we need a ticket as a reminder to release 21.7.8 which is only one version above 21.7.7 after all. ;)
