### ISSUE TITLE
dns/ddclient: Does not support @ or * in hostname field

### ISSUE THREAD

**Issue by revr3nd** [opnsense/plugins#2771]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

[X] The title contains the plugin to which this issue belongs

**Describe the bug**
The os-ddclient 1.0 plugin in 22.1 does not accept @ (root) nor * (wildcard) hostnames and instead displays an error: please specify a valid address (IPv4/IPv6) or hostname
This appears to be a frontend filter as these hostnames do work with ddclient regularly
Example hostnames:
&.example.com
*.example.com

**To Reproduce**
1. Go to Services -> Dynamic DNS -> Settings
2. Add a new account
3. Use @.example.com or *.example.com in the Hostname(s) field

**Expected behavior**
Hostnames with a leading @. or *. should be allowed as root or wildcard hostnames

**Workaround**
My current workaround is to use the older dyndns plugin until this issue is resolved.

**Environment**
OPNsense 22.1-amd64
FreeBSD 13.0-STABLE
OpenSSL 1.1.1m 14 Dec 2021
os-ddclient 1.0

**Comment by AdSchellevis** [comment]
We might need to add a separate field type in the model or extend the new `WildcardAllowed` in the `HostnameField` type (https://github.com/opnsense/core/blame/317b3601d0baefe41cbaa0e7257b57d3c59e9fdc/src/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/HostnameField.php#L82-L90)

The latter also depends on the current Unbound code as the toggle was introduced in the latest MVC refactor. cc @swhite2
