### ISSUE TITLE
dns/ddclient Cloudflare not available

### ISSUE THREAD

**Issue by dpieski** [opnsense/plugins#2772]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

[x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
(e.g. I would like an input field in the `/ui/firewall/alias` which would add .... to ....)
I would like to be able to use Cloudflare with the new Dynamic DNS plugin like I could with the old one.

**Describe alternatives you've considered**
As far as I can tell, there is no alternative except moving away from Cloudflare?

**Additional context**
![image](https://user-images.githubusercontent.com/3300522/151482264-38d8c940-2bdc-4050-9d81-78bd75cdbdc4.png)

The bottom of this page includes the settings the old DynDNS service used:
https://docs.opnsense.org/manual/dynamic_dns.html

**Comment by dpieski** [comment]
@AdSchellevis I think you work on this plugin?

**Comment by AdSchellevis** [comment]
I build it, yes, pull requests will be accepted.
