### ISSUE TITLE
dns/ddclient Username when selecting Google gives error

### ISSUE THREAD

**Issue by dpieski** [opnsense/plugins#2773]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

[x] The title contains the plugin to which this issue belongs

**Describe the bug**
A clear and concise description of what the bug is, including last known working version (if any).
When entering in my username from Google, I get a "The username contains invalid characters." Error.

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**
1. Go to Dynamic DNS > plus sign > Google
2. Copy username from Google and paste in Username field
3. Fill out rest of form
4. Click [Save]
5. Get Error

**Expected behavior**
Don't get a character error when entering in your username.

**Screenshots**
Attached at end. 

**Relevant log files**
If applicable, information from log files supporting your claim.
N/A

**Additional context**
N/A

**Environment**
Software version used and hardware type if relevant.
e.g.:
OPNsense 22.1 (OpenSSL).

![image](https://user-images.githubusercontent.com/3300522/151483118-3a946960-32d5-4c44-9049-54ac880040e3.png)

**Comment by dpieski** [comment]
I have reset my username and password before posting the username here. Just wanted to show that there are no invalid characters.

**Comment by dpieski** [comment]
@AdSchellevis I think you work on this plugin?

**Comment by AdSchellevis** [comment]
@dpieski oops, missed upper case there https://github.com/opnsense/plugins/commit/c970a82d15dcd1a3c68d03296bebd4e8e67da40b

**Comment by undervox** [comment]
Can you confirm there's a plan to incorporate the fix into the upcoming 22.7 general release?

**Comment by fichtner** [comment]
I think the odds are better than winning the lottery. ;)

**Comment by tkrusterholz** [comment]
Reverting to os-dyndns until this is corrected.

**Comment by clajiness** [comment]
@tkrusterholz - https://forum.opnsense.org/index.php?topic=26446.msg130668#msg130668

**Comment by curbcoding** [comment]
In case anyone else gets this, if you copy/paste from Google Domains dynamic DNS admin page, it adds a space in front of the username. So either be careful when you select the username.
