### ISSUE TITLE
dns/ddclient missing OVH dyndns update method

### ISSUE THREAD

**Issue by ptitboogy** [opnsense/plugins#2775]
Hello,

[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

[x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
OVH DynDNS update method is missing

**Describe the solution you'd like**
I would like this update method to be available as it was previously with the old dyndns plugin

**Describe alternatives you've considered**
The only alternative is to stay with the old and deprecated dyndns plugin

**Additional context**

Can you please add this OVH dyndns update method before the old dyndns plugin will be completely removed?

Many thanks,

**Comment by lpoujoulat** [comment]
This one is also missing for me.
Regards
