### ISSUE TITLE
vnstat database lost following ZFS conversion during 22.1 upgrade

### ISSUE THREAD

**Issue by shonjir** [opnsense/plugins#2778]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

[X] The title contains the plugin to which this issue belongs

**Describe the bug**
I upgraded my firewall from 21.7.8 to 22.1.  During the upgrade I converted from UFS to ZFS.  The vnstat database at /var/lib/vnstat containing all history was lost during this conversion.

I do not know whether the database was lost during the upgrade or was lost when os-vnstat was reinstalled following the upgrade.

**To Reproduce**
1. Begin with 21.7.8 firewall on UFS with os-vnstat installed.
2. Run the firewall long enough to have vnstat historical information.
3. Upgrade to 22.1 via bootable installer converting to ZFS in the process
4. Reinstall os-vnstat plugin
5. Observe loss of historical vnstat information

**Expected behavior**
vnstat database should be retained during upgrade process

**Screenshots**
Relevant logs following upgrade:

![image](https://user-images.githubusercontent.com/11600703/151612230-710fdcb6-7ebd-4fc1-99aa-9992cdb62a62.png)

![image](https://user-images.githubusercontent.com/11600703/151612062-17677335-3fd4-495d-9807-d154de1cf90d.png)

**Relevant log files**
If applicable, information from log files supporting your claim.

**Additional context**

**Environment**
Software version used and hardware type if relevant.
OPNsense 22.1-amd64
FreeBSD 13.0-STABLE
OpenSSL 1.1.1m 14 Dec 2021

**Comment by fichtner** [comment]
Config import only grabs /conf/ directory so this is intended.
