### ISSUE TITLE
dns/ddclient - Service not listed on dashboard

### ISSUE THREAD

**Issue by astrandb** [opnsense/plugins#2783]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

[x] The title contains the plugin to which this issue belongs

**Describe the bug**
The ddclient service is not listed on the dashboard nor on System->Diagnostics->Services

**Comment by jameskimmel** [comment]
I have read, that you need to uninstall os-dyndns first, and then it shows up in services with exactly the same name as os-dyndns.

But I am too scared to lose my settings to verify that. 

Maybe we could change the service name of either one of them to get around that issue?
Like os-dyndns could be "Dynamic DNS legacy"

**Comment by AdSchellevis** [comment]
uninstall doesn't remove settings and then there's always a history saved in `System: Configuration: History` as well. https://github.com/opnsense/plugins/commit/400110af010e8a2cd3ea0f01d4b3db87154bacb6 closes this issue (move the old one to a separate location)
