### ISSUE TITLE
dns/ddclient - Please add possibility to select interface for each account

### ISSUE THREAD

**Issue by astrandb** [opnsense/plugins#2784]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

[x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
I use two ethernet interfaces with dynamic ip addresses and thus need ddclient to specify which ip address to use when updating the dyn dns service. In my case Google Domains

**Describe the solution you'd like**
A select box, similar to the one in the deprecated dyndns plugin

**Additional context**

I have edited ddclient.conf manually and I got it to work as I wanted. Noted that the generated ddclient.conf does not follow the ddclient.conf.sample exactly. The result is unpredictable when adding a line with `use if=...` without trailing comma and back-slash in the second google record.
The example below works fine for me.

```
daemon=300
syslog=yes                  # log update msgs to syslog
pid=/var/run/ddclient.pid   # record PID in file.

#
# setup how we expect to retrieve an IP address
#
use=web, web=http://checkip.dyndns.org/, web-skip="Current IP Address:"

protocol=googledomains
ssl=yes
login=**redacted**
password=**redacted**
strp81.**redacted**.com

protocol=googledomains, \
use=if, if=igb2, \
ssl=yes, \
login=**redacted**, \
password=**redacted** \
strp81-4g.**redacted**.com
```

**Comment by astrandb** [comment]
Works fine in 22.1.1
Thank you!

**Comment by toxic0berliner** [comment]
I would argue this fix actually breaks the "Check ip method", but given ddclient limitations and the fact that at least someone is satisfied with this, I turned to opening a new issue #2860 ;)
