### ISSUE TITLE
security/acme-client: Addtional deployhook - Hashicorp Vault

### ISSUE THREAD

**Issue by jeffmccollum** [opnsense/plugins#2796]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[✔️] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
[✔️] I have searched the existing issues and I'm convinced that mine is new.
[✔️] When the request is meant for an existing plugin, I've added its name to the title.

**Describe the solution you'd like**
I would like to push certificates to HashiCorp Vault which I run in my home lab. The ACME deployhooks supports HashiCorp Vault already and just needs to be enabled, as far as I understand. 
https://github.com/acmesh-official/acme.sh/wiki/deployhooks#12-deploy-your-cert-to-hashicorp-vault

**Describe alternatives you've considered**
I will write a custom script worst case, but native integration would be nice.

**Comment by fraenki** [comment]
The "vault_cli" deploy hook requires that the Vault CLI is locally installed on OPNsense. This is not officially supported, neither by a plugin nor in core. I don't think we should support unsupported configurations, in my experience this just leads to confusion and more support requests.

However, the "vault" deploy hook seems to simply POST to the Vault's HTTP API, which may work. I'll try to add support for it.

**Comment by fraenki** [comment]
This will be available in the upcoming release 3.12 of os-acme-client.
