### ISSUE TITLE
dns/ddclient: Missing provider "DynV6"

### ISSUE THREAD

**Issue by coach1988** [opnsense/plugins#2798]
Hello,

[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

[x] When the request is meant for an existing plugin, I've added its name to the title.

Is your feature request related to a problem? Please describe.
The DynV6 DynDNS service (https://dynv6.com/) is missing as a provider.

Describe the solution you'd like
As this was available in the old plugin, I'd highly appreciate it if this method could be implemented again, too.

Describe alternatives you've considered
Using the deprecated plugin.

Additional context

Many thanks,

**Comment by Alphakilo** [comment]
DynV6 supports [DynDNS protocol](https://dynv6.com/docs/apis#dyndns) for updating

**Comment by coach1988** [comment]
And how can that be utilized? I have checked its repo (https://github.com/ddclient/ddclient), but couldn't find any hints on that protocol in the supported providers list, could you please elaborate how to configure it?

PS: Suggestion for improvement: Add a small hint that some/most providers support that and that this specific option should be used in that case;)

**Comment by Alphakilo** [comment]
Support for custom providers, like DynV6, was added in #2813 Once that version is rolled out as an update for OPNsense, it can be utilized like this 😉:

![grafik](https://user-images.githubusercontent.com/8202374/153716640-aee24daf-1870-4a81-b0a1-97e5a9a42ce9.png)

**Comment by coach1988** [comment]
Awesome, that explains why i couldn't find it ;)
PS: Thank you all for your great job, you're the reason why I've got an awesome home network during this work-from-home phase that really helps with remote connections

**Comment by richardtsai** [comment]
According to [dynv6's docs](https://dynv6.com/docs/apis) the DynDns API supports IPv4 only. The IPv6 address seems won't get updated with ddclient.

**Comment by e-cite** [comment]
Unfortunately dynv6 is not working as custom provider, not even with dyndns1 nor with dyndns2 protocol.

Seems to be an issue with setting the correct URLs.

**Comment by PaulSorenson** [comment]
I have dynv6 working as customer provider:
protocol: dyndns2
use token in password field.
I don't know if login is actually required but I had to add it else ddclient complained about the login field.

**Comment by DjSni** [comment]
lol now i finally got it to work, i couldn't get it to work when i used something other than freedns for check ip method, but also had to allow ipv6 in the settings.
My settings:

protocol: dyndns2
server: update6.dedyn.io
username: thedomain.com
password: thetoken
Hostname: all to update hostnames
Checkip: freedns
Force SSL: checked
interface: WAN

**Comment by e-cite** [comment]
But now I got a one final question:
Can I update dynv6 **IPv6 address** with the new ddclient?

**Comment by SnejPro** [comment]
> So now it's all good, but unfortunately no support for updating dynv6 **IPv6 address**.

I have the same issue. It is possible to update ipv6 but not ipv4 and ipv6 at the same time. Even if I create two entries.

With _Dynamic DNS (legacy)_ it is working.

**Comment by BrAiNeeBug** [comment]
01.09.2022 Still no DynV6 Support, it only updates v4 or v6 but not both, so its useless. Can someone add it please ? On DynDns Legacy its working fine.

Regards

**Comment by Dark-Sider** [comment]
I manged to upgrade the ipv4 address at dynv6 with the dyndns2 protocol. However I only need to update the ipv6 address. According to some this should be possible. However checking the "allow ipv6" under general does not change anything.

**Comment by DjSni** [comment]
> I manged to upgrade the ipv4 address at dynv6 with the dyndns2 protocol. However I only need to update the ipv6 address. According to some this should be possible. However checking the "allow ipv6" under general does not change anything.

it seems a similar error as to its like mine. #3069

**Comment by hahaher123** [comment]
Do this for update dynv6 ipv6 record.

Enabled: yes
Service: Custom
Protocol: DynDns2
Server: ipv6.dynv6.com
Username: none 
Password: secret
Wildcard: no
Hostname: You_hostname.dynv.net(or other dynv6 domain)
Check ip method: ip6only.me
Force SSL: yes 
Interface to monitor: none

**Comment by e-cite** [comment]
Lately I had issues using DynV6 with an ipv4-only record. Previously this was possible by creating an empty A-record with a new name (ipv4.zone.example.com) with no address given, and DynV6 automatically uses the zone IPv4. But newly they introduced a garbage collector probably deleting empty records, and so this "empty" IPv4 will be deleted after a few minutes.

Got it working now with a second entry in opnsense. The magic lies in the return value of the IP check method. Returning IPv4 only generates an IPv4 only record at DynV6, and so is IPv6 only or both.

So my current config looks like:
- zone.example.com resolves to IPv4 and IPv6:
  - Service: Custom
  - Proto: DynDns2
  - Server: dynv6.com
  - Username: none
  - Password: <provided by DynV6 instructions without the quotes>
  - Wildcard: not checked
  - Hostname: zone.example.com
  - **Check ip method: he**
  - Check ip timeout: 10
  - Force SSL: checked
  - Interface to monitor: WAN
- ipv4.zone.example.com resolves to IPv4 only:
  - Service: Custom
  - Proto: DynDns2
  - Server: dynv6.com
  - Username: none
  - Password: <provided by DynV6 instructions without the quotes>
  - Wildcard: not checked
  - Hostname: ipv4.zone.example.com
  - **Check ip method: ip4only.me**
  - Check ip timeout: 10
  - Force SSL: checked
  - Interface to monitor: WAN

**Comment by SnejPro** [comment]
> Lately I had issues using DynV6 with an ipv4-only record. Previously this was possible by creating an empty A-record with a new name (ipv4.zone.example.com) with no address given, and DynV6 automatically uses the zone IPv4. But newly they introduced a garbage collector probably deleting empty records, and so this "empty" IPv4 will be deleted after a few minutes.
> 
> Got it working now with a second entry in opnsense. The magic lies in the return value of the IP check method. Returning IPv4 only generates an IPv4 only record at DynV6, and so is IPv6 only or both.
> 
> So my current config looks like:
> 
>     * zone.example.com resolves to IPv4 and IPv6:
>       
>       * Service: Custom
>       * Proto: DynDns2
>       * Server: dynv6.com
>       * Username: none
>       * Password:
>       * Wildcard: not checked
>       * Hostname: zone.example.com
>       * **Check ip method: he**
>       * Check ip timeout: 10
>       * Force SSL: checked
>       * Interface to monitor: WAN
> 
>     * ipv4.zone.example.com resolves to IPv4 only:
>       
>       * Service: Custom
>       * Proto: DynDns2
>       * Server: dynv6.com
>       * Username: none
>       * Password:
>       * Wildcard: not checked
>       * Hostname: ipv4.zone.example.com
>       * **Check ip method: ip4only.me**
>       * Check ip timeout: 10
>       * Force SSL: checked
>       * Interface to monitor: WAN

Your first config did not updated my IPv4 address.

**Comment by e-cite** [comment]
> Your first config did not updated my IPv4 address.
- Is anything useful printed in your logs?
- Enable verbose logging?
- Does http://checkip.dns.he.net/ return your current IPv4 correctly?

**Comment by SnejPro** [comment]
> > Your first config did not updated my IPv4 address.
> 
>     * Is anything useful printed in your logs?
> 
>     * Enable verbose logging?
> 
>     * Does http://checkip.dns.he.net/ return your current IPv4 correctly?

No it returned my IPv6-address.

I wrote a script for updating ipv6, ipv4, ipv6prefix. I run this with cron.

```bash
#!/bin/sh

# WAN-interface with public ipv6 and ipv4 (in my case pppoe0)
interface='<WAN INTERFACE>'
# Enter an interface using an ip6 with the prefix you want to send to dynv6 (in my case em1)
interface_prefix='<INTERFACE>'

# Your dynv6 domain
domain='<DOMAIN>'
# Your dynv6 token
token='<TOKEN>'

ipv6=`ifconfig ${interface} | grep 'inet6 2' | awk '{print $2}'`
ipv6_prefix_base=`ifconfig ${interface_prefix} | grep 'inet6 2' | awk '{print $2}' | sed 's/[a-z0-9]\{2\}\(:[0-9a-z]*\)\{4\}$//g'`
ipv6_prefix="${ipv6_prefix_base}00::/56"
ipv4=`ifconfig ${interface} | grep 'inet ' | cut -d: -f2 | awk '{print $2}'`
old_ipv6=`cat /tmp/dyndns_cache_ipv6_${interface}`
old_ipv6_prefix=`cat /tmp/dyndns_cache_ipv6_prefix_${interface}`
old_ipv4=`cat /tmp/dyndns_cache_ipv4_${interface}`

if [ $1 ] || [ "$old_ipv6" = "" ] || [ $ipv6 != $old_ipv6 ] || [ $ipv6_prefix != $old_ipv6_prefix ];
then
    ipv6_response=`curl "https://dynv6.com/api/update?hostname=${domain}&token=${token}&ipv6=${ipv6}&ipv6prefix=${ipv6_prefix}"`
	if [ "$ipv6_response" = "addresses updated" ];
    then
	    echo $ipv6 > "/tmp/dyndns_cache_ipv6_${interface}"
        echo $ipv6_prefix > "/tmp/dyndns_cache_ipv6_prefix_${interface}"
        echo "IPv6 changed"
    fi
else
    echo "No IPv6 change necessary"
fi

if [ $1 ] || [ "$old_ipv4" = "" ] || [ $ipv4 != $old_ipv4 ];
then
    ipv4_response=`curl "https://dynv6.com/api/update?hostname=${domain}&token=${token}&ipv4=${ipv4}"`
	if [ "$ipv4_response" = "addresses updated" ];
    then
        echo $ipv4 > "/tmp/dyndns_cache_ipv4_${interface}"
        echo "IPv4 changed"
    fi
else
    echo "No IPv4 change necessary"
fi


```
