### ISSUE TITLE
HAproxy frontend: allow advanced options for Listen Addresses

### ISSUE THREAD

**Issue by jpawlowski** [opnsense/plugins#28]
One should be able to add additional configuration settings at the very end of each listen address for example:

    npn http/1.1
    npn spdy/2
    accept-proxy npn http/1.1
    accept-proxy npn ssh/2.0

As a workaround, one could currently add those settings at the very end of "Advanced SSL options". However, one needs to add some SSL settings first, e.g.:

    no-sslv3 no-tls-tickets no-tlsv10 no-tlsv11 ciphers EDH+CAMELLIA:EDH+aRSA:EECDH+aRSA+AESGCM:EECDH+aRSA+SHA384:EECDH+aRSA+SHA256:EECDH:+CAMELLIA256:+AES256:+CAMELLIA128:+AES128:+SSLv3:!aNULL:!eNULL:!LOW:!3DES:!MD5:!EXP:!PSK:!DSS:!RC4:!SEED:!ECDSA:CAMELLIA256-SHA:AES256-SHA:CAMELLIA128-SHA:AES128-SHA npn http/1.1

**Comment by fraenki** [comment]
@jpawlowski: I've added a new parameter: `Advanced Bind Options`. The only drawback (for now) is, that these options will be added to *every* `Listen Address`.
