### ISSUE TITLE
net/haproxy: Logs too untransparent?

### ISSUE THREAD

**Issue by EugenMayer** [opnsense/plugins#280]
While i was debugging #279 i was never able to find anything in the logs, telling me, that this connection was forced to disconnect by the timeout.

I am not sure this is haproxy issue or a logging issue in opnsense, but i can imagine, that very issue will be one of the most important ones to deal with. 

Since setting up an backend could work, tests are ok - but later people complain about issues "sometimes" (due to the timeouts) .. find this in that very cause is very hard without any logs

**Comment by fraenki** [comment]
There are several GUI options available to fine-tune HAProxy's logging:

- `HAProxy -> Settings`, First Tab: `Logging Configuration`
  - enable "advanced mode"
  - set "Filter Syslog Level" to "none"

- `HAProxy -> Settings`, Tab: `Frontends`
  - edit frontend
  - enable "advanced mode"
  - try the following settings:
    - `[ ] Don't log null`
    - `[ ] Don't log normal`
    - `[X] Raise Log Level`
    - `[X] Detailed Logging`

**Comment by fraenki** [comment]
After enabling full logging, check HAProxy's [excellent documentation](https://cbonte.github.io/haproxy-dconv/1.7/configuration.html#8.5) to get used to it's log format. :)

**Comment by EugenMayer** [comment]
I would say I tried all of those an that particular issue was not logged. To ensure I am not doing it entirely wrong, which log are you expecting to get all those information?

**Comment by fraenki** [comment]
> To ensure I am not doing it entirely wrong, which log are you expecting to get all those information?

It's all in /var/log/haproxy.log (except you have remote logging enabled).
You'll notice a 2 or 4 characters long field in every log line, according to the [documentation](https://cbonte.github.io/haproxy-dconv/1.7/configuration.html#8.5):

> TCP and HTTP logs provide a session termination indicator in the
> "termination_state" field, just before the number of active connections. It is
> 2-characters long in TCP mode, and is extended to 4 characters in HTTP mode.

Most of the time this field is empty (indicated by either -- or ----).
My log contains mostly entries where the client aborted the connection such as this one:

`[25/Sep/2017:13:58:57.864] db_frontend db_backend/dbnode001 1/-1/0 0 CC 383/150/150/150/0 0/0`

Note the `CC`, it has the following meaning according to the aforementioned documentation:

>   (first)      C : the TCP session was unexpectedly aborted by the client.
>   (second) C : the proxy was waiting for the CONNECTION to establish on the
>            server. The server might at most have noticed a connection attempt.

**Comment by fraenki** [comment]
I'm closing this issue now. You may reopen it at any time if you still think there's something that we should improve with regard to HAProxy logging.
