### ISSUE TITLE
dns/ddclient: missing Cloudflare

### ISSUE THREAD

**Issue by Alphakilo** [opnsense/plugins#2801]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X]  I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X]  I have searched the existing issues and I'm convinced that mine is new.
- [X]  When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
The UI for `ddclient` is missing the option to configure [Cloudflare ](https://github.com/ddclient/ddclient/blob/v3.9.1/sample-etc_ddclient.conf#L208) accounts.

**Describe the solution you'd like**
Add a `Cloudflare` option for account creation.

**Comment by AdSchellevis** [comment]
we could conclude that point 2 (is new) isn't the case https://github.com/opnsense/plugins/issues/2772

**Comment by Alphakilo** [comment]
Oops, sorry! Was checking for open issues only

**Comment by thetruetype** [comment]
Hey, so when is this updated in the live OPNsense? I just removed the DynDNS due to the warning it will be removed. So I thought to move over to DDclient right away, But since Cloudflare isn't in the services I can't.

**Comment by Alphakilo** [comment]
@thetruetype Probably in the next minor version. Meanwhile, your could use[ `opnsense-patch` to apply the patchset](https://docs.opnsense.org/manual/opnsense_tools.html#id2) for Cloudflare integration. See [this for commit SHA references](https://github.com/opnsense/plugins/commits/master/dns/ddclient/src/opnsense).

```sh
opnsense-patch -c plugins c970a82d15dcd1a3c68d03296bebd4e8e67da40b
opnsense-patch -c plugins af2ec65aa0aeabb0d222c0c3e20eab3fc59d43a6
opnsense-patch -c plugins 8ee15ced75b5c554c0b7f3ee70dc32f7a5f6b14a
```

If this goes south, revert using `opnsense-revert -r 22.1 ddclient`, or by reapplying patches (see above) in reverse order.

**Comment by Alphakilo** [comment]
I had issues applying 8c1759abbc1ac32a6288ab8a57dcdbd23937914d so I just went and copied the `ddclient` folder from masters head. That is pretty dirty, though, wouldn't recommend doing that in a prod environment.
