### ISSUE TITLE
dns/ddclient: add manual account settings

### ISSUE THREAD

**Issue by Alphakilo** [opnsense/plugins#2802]
**Is your feature request related to a problem? Please describe.**
There are lots and lots of DynDNS providers. Can't maintain them all as options.

**Describe the solution you'd like**

1. Implement a "Custom" option for [each protocol `ddclient` has implemented](https://ddclient.net/protocols.html):
    - [x] dnspark
    - [x] dslreports
    - [ ] dyndns1
    - [x] dyndns2

2. Add UI inputs for the following settings:
    - [ ] `server=`
    - [x] `login=`
    - [x] `password=`
    - [ ] `zone=`

**Describe alternatives you've considered**
Manually editing the config file. Works, but meh.

**Additional context**
That'd effectively solve #2798 #2793 #2775 and future friends. Slap some examples in the docs, voila!

**Comment by AdSchellevis** [comment]
sure, it's probably best to add a different tab for "custom" options using a different section in the model, PR's are certainly welcome. similar to the account array:

https://github.com/opnsense/plugins/blob/8ee15ced75b5c554c0b7f3ee70dc32f7a5f6b14a/dns/ddclient/src/opnsense/mvc/app/models/OPNsense/DynDNS/DynDNS.xml#L47

**Comment by Alphakilo** [comment]
@AdSchellevis I'm a little uncertain what to do, some guidance would be appreciated.

Both dyndns2 and dnspark are already implemented, but labeled in a way, that indicates it's locked to specific providers:

https://github.com/opnsense/plugins/blob/8ee15ced75b5c554c0b7f3ee70dc32f7a5f6b14a/dns/ddclient/src/opnsense/mvc/app/models/OPNsense/DynDNS/DynDNS.xml#L58

Should we

1. ditch the `.com` label and add a `Server` textbox as an advanced option or
2. duplicate the protocols as, say, `<custom_dyndns2>Custom DynDNS</custom_dyndns>`?

**Comment by AdSchellevis** [comment]
@Alphakilo well, for everything we can easily preconfigure, the current account section is a fine solution. When it comes to adding custom inputs (within verifiable fields), it might make sense to add an additional grid for these options so the standard options aren't tainted with custom fields. The number of available protocols is limited as far as I know, so it might popup a form presenting something like this:

- protocol (select one of https://sourceforge.net/p/ddclient/wiki/protocols/)
- server (text with validation)
- login
- password
- hostnames
- zone (optional / advanced)
- wildcard (optional / advanced)

The tabs in the plugin would then be `Accounts`,  `Custom`, `General Settings`.  The standard account list would just be used for all account we know how to configure (and which settings they should use).

**Comment by MrRoundRobin** [comment]
@AdSchellevis 
Do we really need an extra tab for this?

I tested it successfully with this interface:
![image](https://user-images.githubusercontent.com/948771/152513360-03c53251-fc27-4d76-a77d-a907273d61a9.png)

If you select custom, the relevant fields will be displayed, same technique as with the conditional zone field.

In that example I implemented DynDNS2 and DynDNS1.

If that interface is ok, I'll create an PR

**Comment by AdSchellevis** [comment]
@MrRoundRobin It would be the cleanest option in my opinion, but I can live with alternatives. I'm not using any of this myself, just want to try to keep it as clean as possible. So feel free to open a PR (preferably against https://github.com/opnsense/plugins/tree/dns_ddclient_interfaces, I'll try to handle the merge this weekend)

**Comment by Alphakilo** [comment]
@MrRoundRobin do you intend to implement the other protocols as well?
