### ISSUE TITLE
Nginx dont start after installation

### ISSUE THREAD

**Issue by mkueh** [opnsense/plugins#2810]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X] The title contains the plugin to which this issue belongs

**Describe the bug**
After I installed the Nginx Plugin, I tried to start the service and get an error (don't change any settings)

Here is the Stacktrace

  ```
[03-Feb-2022 21:14:11 Etc/UTC] PHP Warning:  Invalid argument supplied for foreach() in /usr/local/opnsense/mvc/app/models/OPNsense/Nginx/Migrations/M1_24_0.php on line 44
  [03-Feb-2022 21:14:11 Etc/UTC] PHP Warning:  Invalid argument supplied for foreach() in /usr/local/opnsense/mvc/app/models/OPNsense/Nginx/Migrations/M1_24_0.php on line 52
  [03-Feb-2022 21:23:53 Etc/UTC] TypeError: Argument 1 passed to Phalcon\Http\Response::setContent() must be of the type string, null given in /usr/local/opnsense/mvc/app/controllers/OPNsense/Nginx/Api/LogsController.php:287
  Stack trace:
  #0 /usr/local/opnsense/mvc/app/controllers/OPNsense/Nginx/Api/LogsController.php(287): Phalcon\Http\Response->setContent(NULL)
  #1 /usr/local/opnsense/mvc/app/controllers/OPNsense/Nginx/Api/LogsController.php(71): OPNsense\Nginx\Api\LogsController->sendConfigdToClient('nginx tls_hands...')
  #2 [internal function]: OPNsense\Nginx\Api\LogsController->tlsHandshakesAction()
  #3 [internal function]: Phalcon\Dispatcher\AbstractDispatcher->callActionMethod(Object(OPNsense\Nginx\Api\LogsController), 'tlsHandshakesAc...', Array)
  #4 [internal function]: Phalcon\Dispatcher\AbstractDispatcher->dispatch()
  #5 /usr/local/opnsense/www/api.php(26): Phalcon\Mvc\Application->handle('/api/nginx/logs...')
  #6 {main}
  [03-Feb-2022 21:34:30 Etc/UTC] TypeError: Argument 1 passed to Phalcon\Http\Response::setContent() must be of the type string, null given in /usr/local/opnsense/mvc/app/controllers/OPNsense/Nginx/Api/LogsController.php:287
  Stack trace:
  #0 /usr/local/opnsense/mvc/app/controllers/OPNsense/Nginx/Api/LogsController.php(287): Phalcon\Http\Response->setContent(NULL)
  #1 /usr/local/opnsense/mvc/app/controllers/OPNsense/Nginx/Api/LogsController.php(71): OPNsense\Nginx\Api\LogsController->sendConfigdToClient('nginx tls_hands...')
  #2 [internal function]: OPNsense\Nginx\Api\LogsController->tlsHandshakesAction()
  #3 [internal function]: Phalcon\Dispatcher\AbstractDispatcher->callActionMethod(Object(OPNsense\Nginx\Api\LogsController), 'tlsHandshakesAc...', Array)
  #4 [internal function]: Phalcon\Dispatcher\AbstractDispatcher->dispatch()
  #5 /usr/local/opnsense/www/api.php(26): Phalcon\Mvc\Application->handle('/api/nginx/logs...')
  #6 {main}
  [04-Feb-2022 18:00:34 Etc/UTC] TypeError: Argument 1 passed to Phalcon\Http\Response::setContent() must be of the type string, null given in /usr/local/opnsense/mvc/app/controllers/OPNsense/Nginx/Api/LogsController.php:287
  Stack trace:
  #0 /usr/local/opnsense/mvc/app/controllers/OPNsense/Nginx/Api/LogsController.php(287): Phalcon\Http\Response->setContent(NULL)
  #1 /usr/local/opnsense/mvc/app/controllers/OPNsense/Nginx/Api/LogsController.php(71): OPNsense\Nginx\Api\LogsController->sendConfigdToClient('nginx tls_hands...')
  #2 [internal function]: OPNsense\Nginx\Api\LogsController->tlsHandshakesAction()
  #3 [internal function]: Phalcon\Dispatcher\AbstractDispatcher->callActionMethod(Object(OPNsense\Nginx\Api\LogsController), 'tlsHandshakesAc...', Array)
  #4 [internal function]: Phalcon\Dispatcher\AbstractDispatcher->dispatch()
  #5 /usr/local/opnsense/www/api.php(26): Phalcon\Mvc\Application->handle('/api/nginx/logs...')
  #6 {main}
```

**To Reproduce**
1. install Plugin Nginx
2. try to start in Dashboard

OPNsense 22.1-amd64
FreeBSD 13.0-STABLE
OpenSSL 1.1.1m 14 Dec 2021
AMD EPYC 7313P 16-Core Processor (16 cores, 32 threads)

**Comment by kulikov-a** [comment]
empty nginx config (not http servers or streams. but plugin have been installed before?)
none of these warnings and errors by themselves can prevent nginx from starting imho.
may be Services: Nginx: Logs / Global Error is working ? (and contains complaints that the configuration does not contain servers)

**Comment by mkueh** [comment]
i tried to start the service via ssh and got the following error

  `Performing sanity check on nginx configuration:
  nginx: the configuration file /usr/local/etc/nginx/nginx.conf syntax is ok
  nginx: configuration file /usr/local/etc/nginx/nginx.conf test is successful
  Starting nginx.
  nginx: [emerg] bind() to unix:/var/run/nginx_status.sock failed (48: Address already in use)
  nginx: [emerg] bind() to unix:/var/run/nginx_status.sock failed (48: Address already in use)
  nginx: [emerg] bind() to unix:/var/run/nginx_status.sock failed (48: Address already in use)
  nginx: [emerg] bind() to unix:/var/run/nginx_status.sock failed (48: Address already in use)
  nginx: [emerg] bind() to unix:/var/run/nginx_status.sock failed (48: Address already in use)
  nginx: [emerg] still could not bind()
  /usr/local/etc/rc.d/nginx: WARNING: failed to start nginx`

after all ... i restart the server and now everything works correct.

Thx @kulikov-a for you help
