### ISSUE TITLE
plugins/dns/ddclient DuckDNS wrong field is saved for the token

### ISSUE THREAD

**Issue by spasecookee** [opnsense/plugins#2811]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x ] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x ] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x ] The title contains the plugin to which this issue belongs

**Describe the bug**
In the old deprecated DynamicDNS plugin for OPN Sense the DuckDNS token went into the login/username field in the Gui. This behavior has persisted into the ddclient version of the plugin, however, the ddclient requires putting DuckDNS token into the password field. The only way to get this to work correctly is via shell, since the GUI saves the wrong field to the config file.
https://github.com/ddclient/ddclient.github.io/blob/master/protocols.md

**To Reproduce**
1. Go to 'Services/Dynamic DNS'
2. Click on 'Add/+'
3. Enter the DuckDNS details, you can put the token into both the username and password for good measure. 
4. CLick save/apply
5. SSH into OPNSense and view /usr/local/etc/ddclient.conf, you will see that the token was saved to the login=token, but it needs to be in password=token instead.

**Expected behavior**
Itis expected that /usr/local/etc/ddclient.conf will have the DuckDNS token saved in the password=<token> as this is what ddclient needs for DuckDNS 

If applicable, information from log files supporting your claim.

```
2022-02-04T13:17:49-07:00 | Notice | ddclient[9761] | 88291 - [meta sequenceId="1"] WARNING: null password specified for host hostname.duckdns.org.
-- | -- | -- | --

```
OPNsense 22.1-amd64
FreeBSD 13.0-STABLE

**Comment by AdSchellevis** [comment]
leaving the login blank, seems to provide the correct type of input on my end:
```
protocol=duckdns
ssl=yes
password=xxx
xxx
```

**Comment by spasecookee** [comment]
Yes, you are correct, I guess the issue is filling in both fields. The other issue I am seeing is that even with leaving the login blank when saving, upon re-editing, the password field is not pre-filled with the previously saved value. Though I will note that when saving the form with a blank login and blank password, the previously entered password is retained in ddclient.conf. However, that is not clear without using SSH to verify the contents of ddclient.conf.

**Comment by AdSchellevis** [comment]
I don't think you're allowed to save a blank password, at least on my end it fails validations.

**Comment by spasecookee** [comment]
On my end it does save with a blank password, though like  i say, that blank password does not go over to ddclient.conf after saving/applying.
![DuckDNS](https://user-images.githubusercontent.com/58440408/152727137-d6056612-cf8b-44dc-b700-1e46cf4da1ec.gif)
d

**Comment by fichtner** [comment]
@spasecookee yes, that's what @AdSchellevis meant. Structurally there is not benefit to fetch the "secret" password to the GUI to display it in **** so the next best thing is not to update it if it is blank. Close this?

Cheers,
Franco

**Comment by spasecookee** [comment]
We can close, but I think the UX could be better here. Perhaps I'll have a look at the code to see if there's anything I can think of. 

I tried adding again to confirm it works when providing both login and password. I am not sure why it didn't work the first time, though.

**Comment by fichtner** [comment]
What I can think of is modifying the placeholder to show something when previous password set but funnelling through MVC and UX implications for that weirdness might not be better at all.
