### ISSUE TITLE
os-frr: bgp not working (v1.26)

### ISSUE THREAD

**Issue by elsbrock** [opnsense/plugins#2812]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**

I am unable to get FRR with `bgp` to work; no routes are received nor transmitted. Logs show the following:

```
2022-02-05T00:19:58	Error	zebra	zebra/zebra_ptm.c:1348 failed to find process pid registration	
2022-02-05T00:19:58	Warning	zebra	[EC 4043309122] Client 'bgp' encountered an error and is shutting down.	
2022-02-05T00:19:58	Warning	zebra	[EC 4043309122] Client 'vnc' encountered an error and is shutting down.
```

As far as I can see there is also no traffic being sent out on the target interface.

I tried out running BGP without any neighbor configured but even this is showing the error. Hence, steps to reproduce are fairly simple.

**To Reproduce**
1. Go to Routing > General > enable
2. Go to Routing > BGP and enter your AS number
3. Enable BGP

**Expected behavior**

No errors should be shown in the log.

**Screenshots**

![grafik](https://user-images.githubusercontent.com/77769/152616646-24640464-5cd1-47a3-9441-0a157b7e0cce.png)
![grafik](https://user-images.githubusercontent.com/77769/152616665-aebe96c1-30f4-4516-8cb8-fbac1713294a.png)
![grafik](https://user-images.githubusercontent.com/77769/152616813-88b46ce4-840c-4806-b7ed-97c2117ea21f.png)
![grafik](https://user-images.githubusercontent.com/77769/152616863-d40ac705-cdfe-407c-a691-5d8df2066c87.png)

**Additional context**

Seems to be somewhat related to https://github.com/opnsense/plugins/issues/1947 although I am not really sure about the resolution.

**Environment**

* OPNsense 22.1 (amd64, OpenSSL)
* OPNsense 21.7.7 (amd64, OpenSSL)
* os-frr@1.26

**Comment by mimugmail** [comment]
Rhode errors come from frr itself where FreeBSD doesnt have high priority. You have to live with those errors. But everything runs fine, trust me :)

**Comment by elsbrock** [comment]
The reason why I started suspecting it is not working is because with the following config:

```
Building configuration...

Current configuration:
!
frr version 7.5.1
frr defaults traditional
hostname router.home.iodev.org
log syslog informational
!
router bgp 211900
 no bgp ebgp-requires-policy
 neighbor 2a09:4c0:3e0:a7::1 remote-as 58057
 neighbor 2a09:4c0:3e0:a7::1 interface gif1
 !
 address-family ipv6 unicast
  network 2a0e:b107:9fc::/48
  neighbor 2a09:4c0:3e0:a7::1 activate
  neighbor 2a09:4c0:3e0:a7::1 prefix-list any-out out
 exit-address-family
!
ipv6 prefix-list any-out seq 10 permit 2a0e:b107:9fc::/48
!
line vty
!
end
```

I don't get to see any traffic on `gif1`:

```
[else@router ~]$ sudo tcpdump -nvvi gif1
tcpdump: listening on gif1, link-type NULL (BSD loopback), capture size 262144 bytes
^C
0 packets captured
0 packets received by filter
0 packets dropped by kernel
```

The neighbor can be reached though:

```
[else@router ~]$ ping6 2a09:4c0:3e0:a7::1
PING6(56=40+8+8 bytes) 2a09:4c0:3e0:a7::2 --> 2a09:4c0:3e0:a7::1
16 bytes from 2a09:4c0:3e0:a7::1, icmp_seq=0 hlim=64 time=13.643 ms
16 bytes from 2a09:4c0:3e0:a7::1, icmp_seq=1 hlim=64 time=12.995 ms
16 bytes from 2a09:4c0:3e0:a7::1, icmp_seq=2 hlim=64 time=13.262 ms
^C
--- 2a09:4c0:3e0:a7::1 ping6 statistics ---
3 packets transmitted, 3 packets received, 0.0% packet loss
round-trip min/avg/max/std-dev = 12.995/13.300/13.643/0.266 ms
[else@router ~]$ nc -zv 2a09:4c0:3e0:a7::1 179
Connection to 2a09:4c0:3e0:a7::1 179 port [tcp/bgp] succeeded!
```

But the following entries show up in the logs:

```
2022-02-05T09:30:07 | Notice | zebra | client 26 says hello and bids fair to announce only vnc routes vrf=0 |  
2022-02-05T09:30:07 | Notice | zebra | client 11 says hello and bids fair to announce only bgp routes vrf=0 |  
2022-02-05T09:30:07 | Warning | bgpd | [EC 33554499] sendmsg_nexthop: zclient_send_message() failed |  
2022-02-05T09:30:07 | Notice | frr_carp | FRR received carp configuration event.
```

**Comment by mimugmail** [comment]
I never used GIF interfaces, maybe there is a limitation?

**Comment by elsbrock** [comment]
I think it should be working with GIF too. I found this: https://github.com/FRRouting/frr/issues/6504

```
router.home.iodev.org# show ipv6 nht
2a09:4c0:3e0:a7::1(Connected)
 unresolved(Connected)
 Client list: bgp(fd 11)
```

Does it mean it can resolve it or not? Does it use a different mechanism to resolve the next hop than what is used when I `ping6`?

**Comment by elsbrock** [comment]
I think I got it solved. First, we can see that `bgpd` believes the route is not connected:

```
router.home.iodev.org# show bgp nexthop
Current BGP nexthop cache:
 2a09:4c0:3e0:a7::1 invalid, #paths 0, peer 2a09:4c0:3e0:a7::1
  Must be Connected
  Last update: Sat Feb  5 10:52:03 2022
```

Probably because the IP is set as a remote tunnel address.

Setting `bgp disable-ebgp-connected-route-check` seems to do the trick (see [docs](https://docs.frrouting.org/en/latest/bgp.html#clicmd-bgp-disable-ebgp-connected-route-check)):

```
router.home.iodev.org# show bgp nexthop
Current BGP nexthop cache:
 2a09:4c0:3e0:a7::1 valid [IGP metric 0], #paths 0, peer 2a09:4c0:3e0:a7::1
  gate fe80::86a9:c4ff:fed2:b305
  Last update: Sat Feb  5 14:02:34 2022
```

Does it make sense to offer that option on the BGP configuration screen?
