### ISSUE TITLE
os-ddclient doesn't allow Google DNS usernames

### ISSUE THREAD

**Issue by haukened** [opnsense/plugins#2815]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X ] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X ] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X ] The title contains the plugin to which this issue belongs

**Describe the bug**
When setting up Google Domains DDNS, you are given a username and password.  Inputting those to the os-ddclient screen results in an invalid character field error on username

**To Reproduce**
1. Go To Services -> Dynamic DNS -> Settings
2. Click on Add +
3. Select "Google" and enter Google supplied credentials

**Expected behavior**
Username is accepted

**Screenshots**
![image](https://user-images.githubusercontent.com/8960497/152655544-910ef2f8-745b-4441-b3a4-21d9c68c5684.png)

**Environment**
OPNsense 22.1-amd64
FreeBSD 13.0-STABLE
OpenSSL 1.1.1m 14 Dec 2021
Intel(R) Core(TM) i3-2120 CPU @ 3.30GHz (2 cores, 4 threads)

**Comment by fichtner** [comment]
Try to use the search please as you confirmed you did. #2814
