### ISSUE TITLE
os-git-backup not acception github ssh addresses

### ISSUE THREAD

**Issue by btv** [opnsense/plugins#2816]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [ x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [ x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [ x] The title contains the plugin to which this issue belongs

**Describe the bug**
When trying to setup os-git-backup to use a github ssh address, address is not accepted.

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**
1. install `os-git-backup`
2. go to System->Backups
3. For the git section, do the following things:
    * enable git
    * Add a github ssh url, like so git@github.com:user/project.git
    * Add ssh private key
    * add `git ` as username.
    * Hit the `Setup/Test` button
4. receive the failure
`A valid git location must be provided. e.g. ssh://server/project.git, https://server/project.git`

**Expected behavior**
Expected the ssh user to be accpted

**Screenshots**

**Relevant log files**
If applicable, information from log files supporting your claim.

**Additional context**
Tried add `ssh://` in-front of the github url. This saves the configuration, but rails the test. Once the configuration is save, one can go to `/conf/backup/git` and manually fix the url in `.git/config` to correct the issues.

**Environment**
OPNsense 22.1-amd64FreeBSD 13.0-STABLEOpenSSL 1.1.1m  14 Dec 2021

**Comment by AdSchellevis** [comment]
Username is git....  https://docs.opnsense.org/manual/git-backup.html#initial-setup

**Comment by btv** [comment]
Hi @AdSchellevis, thanks for responding.

My problem isn't with the `git` user (I mention that in my instructions above). My issue is with the url. It only accepts urls starting with `ssh://` or `https://`. And if I put `ssh://` as the start of the github url, it will insert the line below into `/conf/backup/git/.git/config`: 

```
url = ssh://git@github.com:github_username/repo.git
```

Which isn't correct. For using github addresses, it needs to be:

```
url = git@github.com:github_username/repo.git
```
does that help clear up the bug report?

**Comment by AdSchellevis** [comment]
no, it doesn't, the url for github (or gitlab) is `ssh://github.com:github_username/repo.git`, the username as mentioned in the docs is `git`

**Comment by btv** [comment]
Thank you for continuing to engage with me. I'm still struggling with getting this to work as documented. If I put the url above:
`ssh://github.com:user_name/repo.git`
and hit the button `Setup/Test Git`. The form gives me the errors:
```
The following input errors were detected:

    unknown error, check log for details
    Saved settings, but remote backup failed.
```

If I go into the git configuration file for this repo, `/conf/backup/git.git/config`
I see the url line as such:
`url = ssh://git@github.com:user_name/repo.git`

If I go into any other github repo (say one for work) and I view the file `$REPO/.git/config`, the url line will look like this:
`url = github.com:user_name/repo.git`

If I modify the work repo git config file to have `ssh://` infront of the github information, making the repo look how the plugin configures it. Git will no longer communicate with github.

Having the `ssh://` infront of the github url is what is causing git to not backup to my github repo.

**Comment by AdSchellevis** [comment]
what happens if you `git pull` the repository with the configuration saved by the ui? at a first glance I would expect you're not using private key authentication.

**Comment by btv** [comment]
```
root@OPNsense:/conf/backup/git # git pull origin main
ssh: Could not resolve hostname github.com:$user_name: Name does not resolve
fatal: Could not read from remote repository.
```

**Comment by AdSchellevis** [comment]
git is right,  `github.com:$user_name: ` isn't a valid hostname, `github.com` is,  which makes sense as it should have been `ssh://github.com/user_name/repo.git`.  My previous comment was a bit too quick, the doc is correct in that sense as it only contains valid hostnames.  

Ideally the validation should have prevented this input, if you like you can also open a pull-request on the docs adding a note about GitHub's format (https://github.com/opnsense/docs)
