### ISSUE TITLE
UDP Broadcast Relay not working after upgrade to OPNsense 22.1

### ISSUE THREAD

**Issue by jyourstone** [opnsense/plugins#2817]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X] The title contains the plugin to which this issue belongs

**Describe the bug**
After upgrading OPNsense to version 22.1, the plugin UDP Broadcast Relay is not working anymore. The service itself is running and it seems to do something, since I can see the Multicast traffic in a packet trace. But devices cannot be discovered acress VLAN's.

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**
1. Install UDP Broadcast Relay on an OPNsense system running version 22.1
2. Configure UDP Broadcast Relay.
3. Try to send multicast traffic through OPNsense, it won't find devices across VLAN's.

**Expected behavior**
Devices should be discovered through Multicast across VLAN's.

**Screenshots**

**Relevant log files**
If a packet trace log would be helpful, I can provide this.

**Additional context**
UDP Broadcast Relay was working fine for me until I upgraded to version 22.1. Before upgrading I was running version 21.7.

When testing this, I'm using an iPhone connected to a VLAN on subnet 192.168.47.0/24 and trying to use Sonos and Spotify to cast/control music on another VLAN on subnet 192.168.55.0/24.

This is how UDP Broadcast Relay is configured:
![image](https://user-images.githubusercontent.com/4037547/152789030-52b7ee68-9cc3-430f-9363-59f07ba60298.png)

**Environment**
Software version used and hardware type if relevant.
e.g.:

OPNsense 22.1-amd64
FreeBSD 13.0-STABLE
Network Intel I211-AT Gigabit NIC

**Comment by marjohn56** [comment]
Not likely to be the daemon, but I'll check it out on my systems this week and see what happens.

**Comment by mimugmail** [comment]
Maybe this is also related to assigning parent interface and/or maybe setting promisc mode in interface section

**Comment by marjohn56** [comment]
Just checked after updating my test unit and I can see the packets being pushed between the LANs. Nothing funky, just a straight install on my test unit. When I am able I'll put the test unit live and see what happens then, it'll sometime this week.

**Comment by maxfield-allison** [comment]
Any new info? I'm having the same problem.
