### ISSUE TITLE
dns/ddclient: add custom service type with curl

### ISSUE THREAD

**Issue by maxkratz** [opnsense/plugins#2826]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
I've upgraded my OPNsense router to v22.1 today and was greeted with a warning that the old DynDNS plugin will be removed from the repository in the near future. Therefore, I've installed the recommended plugin **ddclient**.

The "new" dynamic DNS plugin (**ddclient**) and/or the web UI of OPNsense does not allow the use of a custom provider (with curl). Currently, I'm using the "old" DynDNS plugin to propagate my dynamic IP to a custom webhook via curl. The settings look like this:

![Bildschirmfoto_2022-02-09_21-36-39](https://user-images.githubusercontent.com/20956405/153285880-dbc503b5-698f-4f3e-a5c6-dd5bea6c81d8.png)

However, I do not know how to configure such an update procedure with the new ddclient plugin. Is this even possible or does the new ddclient plugin simply not support it?

**Describe the solution you'd like**
I would like to have a "custom" option within the ddclient web UI/config to add custom curl actions like in the old DynDNS plugin.

**Describe alternatives you've considered**
Maybe it is possible to configure ddclient via a config file to trigger such actions? I'm not quite sure about this.

**Comment by AdSchellevis** [comment]
custom services will be supported with https://github.com/opnsense/plugins/pull/2813, but only within the options that ddclient offers. Custom free text input won't be supported for security reasons. Best check how ddclient is able to feed your provider or start a discussion on our forum (https://forum.opnsense.org)

**Comment by khm** [comment]
> Custom free text input won't be supported for security reasons. 

What security reasons?

**Comment by AdSchellevis** [comment]
https://docs.opnsense.org/development/guidelines/basics.html#safeguard-user-input

**Comment by emaba** [comment]
> support for Azure DNS?

We need Azure DNS support too. Thank you.

**Comment by hauserkristof** [comment]
> > support for Azure DNS?
> 
> We need Azure DNS support too. Thank you.

Yes we need it!

**Comment by maxkratz** [comment]
Any news on this one? AFAIK, OPNsense 22.7 was just released - which, unfortunately, breaks the "old" dynamic DNS plug-in. The new one does not support all providers from the "old" plug-in.

**Comment by maxkratz** [comment]
> AFAIK, OPNsense 22.7 was just released - which, unfortunately, breaks the "old" dynamic DNS plug-in.

I discovered the possibility to configure a *custom* endpoint within the new dynamic DNS plug-in. Using this setting, I was able to configure OPNsense to send IP updates of the following form: https://host/nic/update?hostname=dyn.example.com&myip=192.0.2.1 to a custom endpoint. (This form is also known as [DynDNSv2 protocol](https://stackoverflow.com/questions/54039095/dyndns2-protocol-specification).)

For everybody that needs some inspiration to configure an endpoint to accept DynDNSv2 requests, feel free to check my *CoreDNS-DynDNS* repository:
https://github.com/maxkratz/coredns-dyndns
