### ISSUE TITLE
net/freeradius: request fails | FreeRADIUS (TTLS - MSCHAPv2) with Ubiquiti Unify AP 

### ISSUE THREAD

**Issue by lucaschoeneberg** [opnsense/plugins#2834]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
Hi, we have 2x U6-LR and 2x UAP-nanoHD-EU in our facility and are currently trying to set up a WPA2/3 Enterprise network. However, for this we need a working Radius server that supports EAP MSCHAPv2 over TLS. So I configured the Radius server on our OPNsense in such a way that the Radius server confirms the authentication via LDAP.

Overview:
MS-AD <- (Network) <- ldap <- freeradius(OPNsense) <- (Network) <- AP

**To Reproduce**

1. Configure your Freeradius as (see info CONFIG).
2. Use a Unifi AP with WPA2/3 Enterprise with authentication via Radius
3. See Error on (OPNsense) Services: FreeRADIUS: log file

**Expected behavior**
Working EAP MSCHAPv2 authentication.

**Screenshots**
![Bildschirmfoto 2022-02-15 um 08 56 44](https://user-images.githubusercontent.com/37987646/154017758-df1324d1-1a15-4a8d-b727-15912976b04d.png)
![Bildschirmfoto 2022-02-15 um 08 58 06](https://user-images.githubusercontent.com/37987646/154017763-00ac7874-2d9a-4b1f-bec0-50f497240edc.png)

**Relevant log files**
If applicable, information from log files supporting your claim.

/ui/diagnostics/log/core/radius
```
2022-02-15T08:23:03 |   | Auth: (12) Login incorrect (eap: Failed continuing EAP TTLS (21) session. EAP sub-module failed): [l.schoeneberg] (from client ARTandTECH.space e.V. port 0) 

2022-02-15T08:23:03 |   | Auth: (12) Login incorrect (mschap: Program returned code (2) and output 'Failed to execute "/path/to/ntlm_auth": No such file or directory'): [l.schoeneberg] (from client ARTandTECH.space e.V. port 0 via TLS tunnel) 
  
2022-02-15T08:23:03 |   | ERROR: (12) mschap: ERROR: Program returned code (2) and output 'Failed to execute "/path/to/ntlm_auth": No such file or directory'

```
It seems like Freeradius ntml_auth files are missing

**Additional context**
Configuration:
FreeRADIUS LDAP:
/ui/freeradius/ldap/index
![Bildschirmfoto 2022-02-15 um 09 22 32](https://user-images.githubusercontent.com/37987646/154022228-aab6f1bf-a524-4183-af93-cfb3e6ec43de.png)

FreeRADIUS EAP:
/ui/freeradius/eap/index
![Bildschirmfoto 2022-02-15 um 09 20 55](https://user-images.githubusercontent.com/37987646/154022482-632bbe11-6afb-491e-a30f-a51e0b494e67.png)

Tried too:
/ui/freeradius/eap/index
![Bildschirmfoto 2022-02-15 um 09 28 00](https://user-images.githubusercontent.com/37987646/154022501-e470928c-7489-421a-b38e-4ac63b28a0d1.png)

**Environment**
Software version used and hardware type if relevant.
e.g.:

OPNsense 21.10.3 (amd64, OpenSSL, opnsense-business).
DEC3850 – OPNsense® Rack Security Appliance
AMD EPYC 3201 8-Core Processor (8 cores) (16GB DDR4)

**Comment by mimugmail** [comment]
LDAP via FreeRADIUS is not yet supported: https://github.com/opnsense/plugins/pull/2626

**Comment by lucaschoeneberg** [comment]
Okay well now it's merged, that's nice 🤙🏼. 
But will this remove the error with ntlm_auth?

**Comment by mimugmail** [comment]
Not sure, do you have a change to spin up an OPNsense VM and test it?

**Comment by mimugmail** [comment]
And which one is it? :)

**Comment by fichtner** [comment]
@lucaschoeneberg fair point :)

**Comment by lucaschoeneberg** [comment]
Thanks, but back to the actual problem. MSCHARPv2 needs the ntlm_auth file from samba or winbindd to compare the NT password against Active Directory. I just found this out with a little web search. Do any of you have more knowledge about this?

**Comment by mimugmail** [comment]
Samba is not part of OPNsense, I think this wont be possible

**Comment by lucaschoeneberg** [comment]
Okay, then I'll know.
