### ISSUE TITLE
Support for Zabbix 6.0 LTS

### ISSUE THREAD

**Issue by jokay** [opnsense/plugins#2839]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**

No.

**Describe the solution you'd like**

`os-zabbix6-proxy` and `os-zabbix-agent` plugins supporting Zabbix 6.0 LTS.

**Describe alternatives you've considered**

None.

**Additional context**

- [What's new in Zabbix 6.0 LTS](https://www.zabbix.com/whats_new_6_0)
- [net-mgmt/zabbix6-*: Add new family of zabbix6-* ports](https://cgit.freebsd.org/ports/commit/net-mgmt?id=daa62df12ab218d5669424a67453974bbab9eb0c)

**Comment by fraenki** [comment]
@jokay Early adopter, huh? ;) I'll handle the Zabbix Agent part, but it will take some time.

**Comment by fraenki** [comment]
@Pimmetje Version 3 is not supported on OPNsense ;)

**Comment by Pimmetje** [comment]
I was in the impression that os-zabbix-agent was a old agent. Thanks for clarifying.

**Comment by rmundel** [comment]
Hey @fraenki 
If you need any kind of testing I'm glad to help.

**Comment by micfogas** [comment]
i'm also willing to test it :) just got done getting a zabbix server back up and running tonight, of course i naturally went for v6 LTS. 🥲 i guess the biggest work is the UI integration. anyway, looking forward to a test package :)

**Comment by fraenki** [comment]
Pull requests:
https://github.com/opnsense/plugins/pull/2963
https://github.com/opnsense/plugins/pull/2964

Support for Zabbix 6 will be available real soon, thanks to @rmundel!

**Comment by rroethof** [comment]
> i'm also willing to test it :) just got done getting a zabbix server back up and running tonight, of course i naturally went for v6 LTS. 🥲 i guess the biggest work is the UI integration. anyway, looking forward to a test package :)

sign me up too for test package too, we just installed the new zabbix LTS and now the offsite platforms behind opnsense are blind :(
