### ISSUE TITLE
dns/ddclient: Allow the use of "@" character in the "safety check" for hostname

### ISSUE THREAD

**Issue by Stifler6996** [opnsense/plugins#2841]
**Describe the bug**
Allow the use of "@" character, in the new ddclient. Namecheap requires it, in order to update the TLD.

![image](https://user-images.githubusercontent.com/12870096/154402506-e21da385-551f-4fcb-923e-407a43ab3a17.png)

Currently, the web comes up with an error stating that it is not valid, and doesn't allow you to save it.

**To Reproduce**

![image](https://user-images.githubusercontent.com/12870096/154402739-c23308e2-3b39-4470-98c5-637b8d61b1ec.png)

For those looking for a workaround, I setup everything and called the host "www". then saved the system config.
I then edited the xml, and changed "www" to "@".
Then I restored the config back to the system.
I then confirmed that ddclient works correctly after that. So the problem only exists in the web "safety check"

OPNsense 22.1.1_1 (amd64, OpenSSL).

**Comment by t3nk3y** [comment]
I'm also affected by this issue, and have opened a ticket using a template. Please close this one, and optionally link it to my ticket: https://github.com/opnsense/plugins/issues/2849

**Comment by Stifler6996** [comment]
> I'm also affected by this issue, and have opened a ticket using a template. Please close this one, and optionally link it to my ticket: #2849

I will add the temporary workaround to yours, and close this.
