### ISSUE TITLE
os-ddclient Cloudflare API Key

### ISSUE THREAD

**Issue by sachinwadhwa** [opnsense/plugins#2842]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
With latest update 22.1.1_1, Cloudflare DNS update only works with Global API key but it fails to work with an API token with DNS edit for the zone. Older plugin (DynDNS) I can create API token with specific DNS zone edit access and it used to works fine. Current method of using Global API key is very unsafe and might lead to security issues as Global API key have full admin access to your Cloudflare account.

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**
As specified above

**Expected behavior**
DNS update should work with specific API token/key and not with Global API key

**Screenshots**
None

**Relevant log files**
None

**Additional context**
None

**Environment**
22.1.1_1

**Comment by thafer30** [comment]
Commenting to show interest. I also am still using the legacy os-dyndns plugin since I cannot use Cloudflare api tokens with this new plugin.

**Comment by Tetricz** [comment]
This appears to be an issue regarding ddclient more than OPNSense.
It seems like we don't know when the next release will be coming (https://github.com/ddclient/ddclient/issues/272)

Version bump request on ddclient (https://github.com/ddclient/ddclient/issues/361)

It is marked as fixed in the next release, so maybe we can get a new ddclient built from the current src?

**Comment by jrm523** [comment]
Just chiming in that I am experiencing the same issue. I will transition back to the legacy client for now.

**Comment by asche77** [comment]
bumping and subscribing. Though it really is a matter for ddclient to release its next release.

**Comment by JHarding86** [comment]
Seem to be running into this issue as well.

**Comment by bskinner** [comment]
Same issue here. I just uninstalled the `os-ddclient` plugin as it's completely useless to me without this feature.

**Comment by CodeAndWeb** [comment]
I also need a solution for this....

**Comment by JHarding86** [comment]
This is a shame. I decided to make the leap from pfsense and was stopped dead in my tracks due to this. I had to revert. I love the interface of opnsense, but it's nothing if it doesn't work with the packages that I need. 🙃

**Comment by chiwou** [comment]
you can still use the old plugin, even both at the same time, just wait until the new plugin has all the features of the old one

**Comment by Nolij** [comment]
This is very necessary for me, as I'm pretty sure even if I wanted to use username/password 2FA would get in the way of that.

**Comment by rupertbenbrook** [comment]
Looking at the code of ddclient, it seems like if you use `token` as the username and your Cloudflare API token as the password, it uses the `Authentication: Bearer` header as opposed to the `X-Auth-` headers to talk to the Cloudflare API. I've not tried it yet, but plan to.

https://github.com/ddclient/ddclient/blob/11a583b003920f8e15591813598b70061d1a4654/ddclient.in#L4764-L4766

**Comment by Nolij** [comment]
> Looking at the code of ddclient, it seems like if you use `token` as the username and your Cloudflare API token as the password, it uses the `Authentication: Bearer` header as opposed to the `X-Auth-` headers to talk to the Cloudflare API. I've not tried it yet, but plan to.
> 
> https://github.com/ddclient/ddclient/blob/11a583b003920f8e15591813598b70061d1a4654/ddclient.in#L4764-L4766

It should, its been in the code for 2+ years. Perhaps a checkbox which makes this more user friendly can still be implemented? This is a "solution" but 10 of the 11 participants of this issue didn't find it until you posted that, and if this issue is closed it will likely be harder to find this issue as a method of finding that.

**Comment by AdSchellevis** [comment]
https://github.com/ddclient/ddclient/issues/361

**Comment by rupertbenbrook** [comment]
Ah, I see. ddclient hasn't had a release since 3.9.1 and the Cloudflare API token support was added just after that release. So, that begs the question why opnsense are switching to ddclient as it's not been released for over 2 years, and regresses the existing functionality? How are other projects doing this? Are they pulling direct from the ddclient repo and not relying on releases?

**Comment by Nolij** [comment]
> Ah, I see. ddclient hasn't had a release since 3.9.1 and the Cloudflare API token support was added just after that release. So, that begs the question why opnsense are switching to ddclient as it's not been released for over 2 years, and regresses the existing functionality? How are other projects doing this? Are they pulling direct from the ddclient repo and not relying on releases?

Come again? Please tell me dyndns is even more out of date...

**Comment by rupertbenbrook** [comment]
Yep, dyndns is much, MUCH more out of date! 2014 I think it the last code change.

https://git.savannah.nongnu.org/cgit/perl-dyndns.git

**Comment by Nolij** [comment]
> Yep, dyndns is much, MUCH more out of date! 2014 I think it the last code change.
> 
> https://git.savannah.nongnu.org/cgit/perl-dyndns.git

Alright that's much better. Still though should probably be swapping to something that's still receiving updates instead of replacing a horse and buggy with a crank-start car

**Comment by AdSchellevis** [comment]
likely caused by people only complaining and not a lot of people working on these topics, in which case the lack of commercial interest doesn't help either.

**Comment by Nolij** [comment]
> likely caused by people only complaining and not a lot of people working on these topics, in which case the lack of commercial interest doesn't help either.

Fair enough.

**Comment by Nolij** [comment]
Well my previous point still remains: a change to the UI to add a checkbox which just puts username as `token` (and hides it), and labels the password box `API Token` shouldn't be difficult to implement and would avoid much confusion and future complaining.

**Comment by AdSchellevis** [comment]
> I think ddclient is still getting updates and is being maintained, just no-one seems to be releasing the updates in versioned releases, so this isn't being picked up downstream by FreeBSD and OPNsense.

Developed, not being released https://github.com/ddclient/ddclient/tags hence the tickets asking for a release. 3.9.1 is the version most distro's ship

**Comment by GitPullNow** [comment]
This is the only situation where I need to use my global API key and also would like to see this fixed. Looking at the project of ddclient there is already an issue and fix but still open and not in a release yet. Does have label fixed in next release. Hope this gets released some time soon so opnsense can implement this.

https://github.com/ddclient/ddclient/issues/361

**Comment by agreenbhm** [comment]
This obviously isn't a long-term fix, but i modified my local ddclient script to work with the changes until the official version is updated.

`
--- /usr/local/sbin/ddclient	2022-05-23 10:04:19.328298000 -0400
+++ ddclient	2022-05-08 22:13:54.000000000 -0400
@@ -4564,12 +4564,8 @@
 		my $ip    = $config{$key}{'wantip'};

 		my $headers = "X-Auth-Email: $config{$key}{'login'}\n";
-		if ($config{$key}{'login'} eq 'token') {
-			$headers .= "Authorization: Bearer $config{$key}{'password'}\n";
-		} else {
-			$headers .= "X-Auth-Key: $config{$key}{'password'}\n";
-		}
-			$headers .= "Content-Type: application/json";
+		$headers .= "X-Auth-Key: $config{$key}{'password'}\n";
+		$headers .= "Content-Type: application/json";

 		# FQDNs
 		for my $domain (@hosts) {
`

**Comment by janssenjones** [comment]
> This obviously isn't a long-term fix, but i modified my local ddclient script to work with the changes until the official version is updated. Starting at line 4566, my file now looks like this.
> 
> ```
>                 my $headers = "X-Auth-Email: $config{$key}{'login'}\n";
>                 if ($config{$key}{'login'} eq 'token') {
>                         $headers .= "Authorization: Bearer $config{$key}{'password'}\n";
>                 } else {
>                         $headers .= "X-Auth-Key: $config{$key}{'password'}\n";
>                 }
>                         $headers .= "Content-Type: application/json";
> ```

Thanks for this info!  I just tried setting this up today for the first time, and was banging my head trying to switch from global API key, and this worked perfectly. I know it's a temporary fix, but still glad to have it!

**Comment by ilium007** [comment]
Modifying `/usr/local/opnsense/version/ddclient` as above worked for me on OPNsense 22.1.10-amd64

**Comment by viliusz** [comment]
@ilium007 
I assume you have made changes in `/usr/local/sbin/ddclient` (and not in `/usr/local/opnsense/version/ddclient`), right?

**Comment by viliusz** [comment]
had to slightly modify the script (based on above suggestions) to make it work with API Token in opnsense

file: `/usr/local/sbin/ddclient`
lines: `4566-4573`
```
                my $headers = "";
                if ($config{$key}{'login'} eq 'token') {
                        $headers .= "Authorization: Bearer $config{$key}{'password'}\n";
                } else {
                        $headers .= "X-Auth-Email: $config{$key}{'login'}\n";
                        $headers .= "X-Auth-Key: $config{$key}{'password'}\n";
                }
                $headers .= "Content-Type: application/json";
```

**Comment by ilium007** [comment]
> @ilium007
> I assume you have made changes in `/usr/local/sbin/ddclient` (and not in `/usr/local/opnsense/version/ddclient`), right?

Yes, copy and paste error. I’ll edit above to avoid any confusion.

**Comment by ilium007** [comment]
My changes in `/usr/local/sbin/ddclient` reverted, why would this happen? I did restart opsense.

**Comment by budimanjojo** [comment]
The latest pre release of `ddclient` now include this feature, should we get the pre release version?

**Comment by fichtner** [comment]
It's supposed to work for Cloudflare, but it broke my DuckDNS for no apparent reason. Not taking any chances with the prerelease. Hoping for a release at some point.

Here is the ports patch I wrote for the prerelease...

https://github.com/opnsense/ports/commit/34c7fd00d8f1cac5

**Comment by budimanjojo** [comment]
> It's supposed to work for Cloudflare, but it broke my DuckDNS for no apparent reason. Not taking any chances with the prerelease. Hoping for a release at some point.
> 
> Here is the ports patch I wrote for the prerelease...
> 
> [opnsense/ports@34c7fd00d8f1cac5](https://github.com/opnsense/ports/commit/34c7fd00d8f1cac5)

Yeah it's a big update with 200 commits and it looks like they just merge all the PRs altogether and call it a day :smile:

**Comment by agreenbhm** [comment]
> This obviously isn't a long-term fix, but i modified my local ddclient script to work with the changes until the official version is updated. Starting at line 4566, my file now looks like this.
> 
> ```
>                 my $headers = "X-Auth-Email: $config{$key}{'login'}\n";
>                 if ($config{$key}{'login'} eq 'token') {
>                         $headers .= "Authorization: Bearer $config{$key}{'password'}\n";
>                 } else {
>                         $headers .= "X-Auth-Key: $config{$key}{'password'}\n";
>                 }
>                         $headers .= "Content-Type: application/json";
> ```

FYI if anyone is using my workaround: I updated the other day and my fix was gone so I had to reimplement it (not surprisingly).  However, it wasn't working with the same changes.  I eventually found the issue was my config file (/usr/local/etc/ddclient.conf); it looked pretty weird, with all of the config parameters after line 4 set to be on the same line (using "\" to continue the line).  The line with "password" had a space after the password/token and the word "Copy" before a slash, and then the next line had my domain name.  

To fix this: I just commented out the whole config section that looked weird and rewrote it without the line continuations.  The first line is "use=if, if=<interface>", but the rest of the lines are just in the format "parameter_name=parameter", without any commas or slashes.  The last line is just the domain name (no "parameter_name=").

Example picture attached.
![image](https://user-images.githubusercontent.com/622379/183420671-1bba0978-5ef8-4c8b-8b9a-b821c4b7bbe4.png)

**Comment by stavros-k** [comment]
Looks like `3.10.0_1` includes a fix for the API key.
It's a prerelease tho https://github.com/ddclient/ddclient/releases/tag/v3.10.0_1

**Comment by giggio** [comment]
It looks like `3.10.0` (stable) was released a few days ago: https://github.com/ddclient/ddclient/releases/tag/v3.10.0
Hopefully that can be integrated into the plugin. Maybe this issue should be reopened to follow that up.

**Comment by Dmitri233** [comment]
Works fine on latest opnsense 23 version, just need to leave username field empty

**Comment by skaldenhoven** [comment]
> Works fine on latest opnsense 23 version, just need to leave username field empty

Both methods work. With or without username token. What I did need to do was delete and install the plugin before it started working correctly with the same config as before.

**Comment by kitos9112** [comment]
In case someone ends up in this rabbit hole. Your DNS record must pre-exist beforehand on Cloudflare, otherwise, the current `ddclient` implementation won't create it on your behalf. Also, I can confirm that either leaving the username empty or putting `token`  works regardless as @skaldenhoven stated.

Watch out for weird log errors like:

```
No 'A' record at Cloudflare
```

**Comment by Qhilm** [comment]
Not working for me. Have added API token in password field, username is empty, and I get a log line saying:

```
nja ddclient 30659 - [meta sequenceId="31"] RECEIVE: {"success":false,"errors":[{"code":6003,"message":"Invalid request headers","error_chain":[{"code":6111,"message":"Invalid format for Authorization header"}]}],"messages":[],"result":null}
```

Any idea?

**Comment by viliusz** [comment]
> Not working for me. Have added API token in password field, username is empty, and I get a log line saying:
> 
> ```
> nja ddclient 30659 - [meta sequenceId="31"] RECEIVE: {"success":false,"errors":[{"code":6003,"message":"Invalid request headers","error_chain":[{"code":6111,"message":"Invalid format for Authorization header"}]}],"messages":[],"result":null}
> ```
> 
> Any idea?

@Qhilm 

1. In SERVICES > DYNAMIC DNS > SETTINGS > General settings, which backend you have selected? OPNSense -or- ddclient
2. According to [OPNSense docs](https://docs.opnsense.org/manual/dynamic_dns.html#provider-specific-configuration), if you are using Global API key - username should be the email of the admin user account on CF, and in case you're using custom API token, then the username should be `token`. Could you please review your config and update accordingly?

Hope this helps.

**Comment by Qhilm** [comment]
@viliusz many thanks for the help, but the issue was at layer8. Wrong "check ip method" (should be "interface") and the field hostname was missing the domain part... I don't understand how I got that log line but I get "SUCCESS" for both A and AAAA now, all good. Thanks!

**Comment by viliusz** [comment]
> @viliusz many thanks for the help, but the issue was at layer8. Wrong "check ip method" (should be "interface") and the field hostname was missing the domain part... I don't understand how I got that log line but I get "SUCCESS" for both A and AAAA now, all good. Thanks!

You're welcome. Happy to see you have sorted it out.

**Comment by biggt** [comment]
I was also having issues with ddclient not operating correctly. 
I have tried the above fixes with no luck. 

However, under General Settings for ddclient, I updated the backend to "native" instead of ddclient... 
Added my email address to the username field and the global API key to the password field. 

Once I updated those, I checked the debug logs for ddclient and see that it is now updating the IP's as necessary.

Question still remains why I need to be setting the backend to native rather than ddclient though.

**Comment by viliusz** [comment]
@biggt 

Since original ddclient is no longer maintained the OPNSense team developed their own implementation of ddclient (so called 'native' option). This way they can keep adding new features to it. Hope that makes sense.

**Comment by biggt** [comment]
> @biggt
> 
> Since original ddclient is no longer maintained the OPNSense team developed their own implementation of ddclient (so called 'native' option). This way they can keep adding new features to it. Hope that makes sense.

makes perfect sense and works perfectly as well.

**Comment by giggio** [comment]
It seems ddclient is again being maintained. The fork became ddclient/ddclient 3 months ago.
Maybe there won't be a need for an alternative implementation after all.
