### ISSUE TITLE
sysutils/nut: Diagnostics --> UPS Status is empty in service mode standalone

### ISSUE THREAD

**Issue by Starkstromkonsument** [opnsense/plugins#2846]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
I previously had the nut plugin running in service mode netclient and changed to standalone now because I connected my UPS directly via USB now. Under NUT --> UPS Type --> Netclient I only unchecked the enabled-checkbox but did not empty the other fields. This resulted in the UPS Status page being empty.

**To Reproduce**
1. Go to 'NUT --> Configuration --> General Settings'
2. Check 'Enable Nut'
3. Switch 'Service Mode' to 'standalone'
4. Set 'Name' to 'ups'
3. Click on 'Apply'
4. Go to 'NUT --> Configuration --> UPS Type --> Netclient'
5. Uncheck 'enable'
6. Enter some valid IP-Address in 'IP Address', e.g. '10.20.10.20'
7. Click on 'Apply'
8. Go to 'NUT --> Diagnostics --> UPS Status'
9. See empty page

**Expected behavior**
Show the correct UPS status for 'ups@127.0.0.1', although an IP-Address is configured under 'NUT --> Configuration --> UPS Type --> Netclient', when Netclient is 'disabled' and/or 'service mode' is 'standalone'.

**Relevant log files**
'System --> Log Files --> Backend', e.g.:
```
2022-02-19T17:20:05 | Error | configd.py | [57265914-fd05-4dca-863f-bb098703c008] Script action failed with  Command '/usr/local/bin/upsc 'ups@10.20.10.20'' returned non-zero exit  status 1. at Traceback (most recent call last):   File  "/usr/local/opnsense/service/modules/processhandler.py", line 478, in  execute     subprocess.check_call(script_command,  env=self.config_environment, shell=True,   File  "/usr/local/lib/python3.8/subprocess.py", line 364, in check_call      raise CalledProcessError(retcode, cmd) subprocess.CalledProcessError:  Command '/usr/local/bin/upsc 'ups@10.20.10.20'' returned non-zero exit  status 1.
-- | -- | -- | --
```

**Additional context**
https://github.com/opnsense/plugins/blob/c526550c15bf1ad8efbaef819ed1b98daf71d286/sysutils/nut/src/opnsense/mvc/app/controllers/OPNsense/Nut/Api/DiagnosticsController.php#L41-L44

**Environment**
OPNsense 22.1.1_3-amd64
FreeBSD 13.0-STABLE
OpenSSL 1.1.1m 14 Dec 2021

**Comment by mimugmail** [comment]
And what happens when you remove all configs? Usually its empty If it doesnt receive data.

**Comment by Starkstromkonsument** [comment]
Emptying 'IP Address' solves the problem. It took me some time to figure that out though. I recommend adding an additional check for `$mdl->netclient->enabled`

**Comment by mimugmail** [comment]
This code is only for DiagnosticsController, it won't prevent false user handling. Maybe some constraints in the model would help here.

**Comment by Starkstromkonsument** [comment]
IMHO unchecking the 'enabled' checkbox for netclient and expecting the rest of the settings on this page to be ignored is no false user handling.

![image](https://user-images.githubusercontent.com/53019449/154863026-37b0ceab-9a70-4615-a541-6ab5db004978.png)

The only other place these settings seem to be used is the template for upsmon.conf

https://github.com/opnsense/plugins/blob/c526550c15bf1ad8efbaef819ed1b98daf71d286/sysutils/nut/src/opnsense/service/templates/OPNsense/Nut/upsmon.conf#L9-L13

The value of ''OPNsense.Nut.netclient.enable' ' is checked there. Why not add a similar check to the DiagnosticsController too to fix this bug? I'll be happy to submit a PR if you agree.

**Comment by mimugmail** [comment]
Sure, thx :)

**Comment by ZPrimed** [comment]
I can confirm that this bug exists, and I was just fighting it for a while after going through the same process. I had been using `nut` in netclient mode and then switched to local USB connection, but didn't delete the old config out of the netclient "driver" section.

Thanks to [Starkstromkonsument](https://github.com/Starkstromkonsument) for figuring this out!

**Comment by mimugmail** [comment]
@Starkstromkonsument are you still working on a PR for it?

**Comment by Starkstromkonsument** [comment]
Hi, no sorry. I startend working on it, ran into a problem and lost track.
