### ISSUE TITLE
ddclient: plugin prevents use of @ as root hostname, required by some services like Namecheap

### ISSUE THREAD

**Issue by t3nk3y** [opnsense/plugins#2849]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
The gui for configuring ddclient accounts requires entry of a hostname.  Some services, such as Namecheap, require the hostname to be set to just "@" in order to update the root domain.  The GUI prevents this.  The legacy Dynamic DNS plugin does not have this issue.

**To Reproduce**
1. Go to 'Dynamic DNS -> Settings -> Accounts'
2. Click on 'Add Account button (a plus +)'
3. Select NameCheap as the Service 
4. Set username to example.com
5. Set password to 12345678980
6. Set hostname to @
7. Click Save
8. GUI will display an error stating "please specify a valid address (IPv4/IPv6) or hostname"

**Expected behavior**
When entering an @ as the hostname for services like NameCheap, no error should be recorded, and the dialog should accept the change.

**Screenshots**
![image](https://user-images.githubusercontent.com/26716328/154828303-692eb12c-61de-46ec-952a-45ff54250c78.png)

**Relevant log files**
No log files are produced with error

**Additional context**
Some DNS hosts use "@" to specify their root host(a host without any subdomain).  These services also don't include the domain name, itself, in the hostname field.  Related help docs/notes really should reflect that this field should contain only the subdomain portion, or an @ sign if there is no subdomain.

**Environment**
OPNsense 22.1.1_3 (amd64, OpenSSL).
Intel(R) Core(TM) i5-2310 CPU @ 2.90GHz (4 cores, 4 threads)
Network Intel and ASRock

**Comment by Stifler6996** [comment]
Temporary workaround:

For those looking for a workaround, I setup everything and called the host "www".
Then make a system config backup.
search the xml, and find the dyndns section and change "www" to "@".
Then I restored the config back to the system.

I then confirmed that ddclient works correctly after that.
The problem only exists in the web "safety check".

**Comment by t3nk3y** [comment]
I mean, I worked around this as well, by changing the dynamic domain to a subdomain, and changing my @ domain to a CNAME pointed at the subdomain.

But I'm pretty sure this is between a 1 line, and like, 4 character fix.  And I could checkout the source, and build, and fix it, and setup a PR... but it's a lot more trouble than it is for someone who is actively developing.

**Comment by shonjir** [comment]
Came here to report this exact issue.   Can't upgrade to os-ddclient until this is resolved.
