### ISSUE TITLE
Acme challenge settings not updating

### ISSUE THREAD

**Issue by lgwapnitsky** [opnsense/plugins#2850]
- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
Editing the url information for an Acme Challenge is not updating in WebUI. A reboot may or may not fix, but I had to go in and manually edit the URL at the CLI to get my challenge working properly.

**Expected behavior**
Editing the URL for PowerDNS Challenge should update, but the old URL remains even after saving properly.

**Comment by fraenki** [comment]
Please provide logs.

**Comment by lgwapnitsky** [comment]
There is no log. This was a manual edit procedure.  Unless there's a log of
config changes

**Comment by fraenki** [comment]
If saving a config change cannot be saved, then there is often an error in `System: Log Files: Backend` or `System: Log Files: General`.

Which file was edited manually?

**Comment by lgwapnitsky** [comment]
Closing out. Rebuilt and setting saving,but now acme isnt verifying.  Thats a whole other issue
