### ISSUE TITLE
os-ddclient should display the status

### ISSUE THREAD

**Issue by toxic0berliner** [opnsense/plugins#2861]
the former os-dyndns client was nice enough to check the ip of each interface using the appropriate webservice and display a status : 

- red : the current ip returned by a webservice does not match what can be read from DNS or dyndns server for the hostname associated
- green: the current ip is up to date ;)

Hope we can look into that feature request when #2860 is fixed since it already needs some outside script to fetch the public IP of an interface, it could be reused here.

**Comment by Starkstromkonsument** [comment]
@toxic0berliner please update your issue description to use one of the provided templates for this issue to be addressed. It will not be looked at, while it has the "incomplete" label. Thank you.

**Comment by toxic0berliner** [comment]
I updated the description it should be completed now. Sorry for that I just thought it would take more time to be looked at @Starkstromkonsument
