### ISSUE TITLE
os-ddclient : force-update (nice-to-have)

### ISSUE THREAD

**Issue by toxic0berliner** [opnsense/plugins#2862]
the former os-dyndns plugin allowed to force-update the IP for all hosts of a configuration entry.

It would be very nice if ddclient allowed this as well, I fear it could be a bit complicated as ddclient has a cache mechanism and will refuse to update too often...  So doing this might require to actually clear part of the ddclient cache (for all hostnames of an entry) and probably restart the service (the good part is that restarting the service won't affect other configurations if we don't touch their cache entries...)

That's a nice to have, but as I was here asking for help migrating from os-dyndns to os-ddclient, I thought I'd actually put that as well in the wish list ;)

**Comment by toxic0berliner** [comment]
Issue is now following the template I think we could reopen this one please

**Comment by fichtner** [comment]
this was added via https://github.com/opnsense/plugins/commit/8e7ec17828f351 for cron
