### ISSUE TITLE
os-ddclient: unable to use webservice to check IP of various interfaces

### ISSUE THREAD

**Issue by toxic0berliner** [opnsense/plugins#2863]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X] The title contains the plugin to which this issue belongs

**Describe the bug**
my dns record is being updated with the local ip of my interfaces instead of the public IP as I have 2 "public" interfaces that have 2 different public IPs but are both behind a routher that does NAT

**To Reproduce**
1. setup a VPN interface to some cheapo VPN providing you some shared IP
2. use the old os-dyndns plugin to monitor that VPN interface for yourhost.example.com
3. you'll see a public IP beeing assigned to yourhost.example.com
4. now setup os-ddclient to monitor that same interface
5. you'll see the crappy privateIP assigned to you by the VPN provider beeing assigned to yourhost.example.com
6. If you're so lucky to have a VPN provider that enable you to do port-forwarding you'll see that yourhost.example.com:1234 will work at step 3 using the dyndns plugin but not at step 5 using ddclient...

**Expected behavior**
monitoring an interface when the "Check ip method" setting in the "General settings" page is set to anything that is a public webservice should result in a config file using the workaround `use=cmd, cmd="<something intelligent>"` or something better but not fallback to using `use=if`

**Screenshots**
Not applicable

**Relevant log files**
Not applicable

**Additional context**
To understand the context, I have 1 public fibre connection and 2 VPNs, all of which are on dedicated interfaces on the opnsense box, but NAT is happening between my opnSense box and the real internet public network somewhere at my ISP or at my VPN providers.
All of these do provide me with a single IP address and all ports forwarded properly, but the real public IP of each of these interface is not visible by opnSense and suceptible to change.

The previous os-dyndns plugin allowed me to select the interface I wanted **and** use any online service like checkmyip or similar to find out what is the real public IP of the interface.

Now, it is a limitation of ddclient, if the configfile says `use=web, web=http://...` you cannot specify which interface is going to be used to send out the http request... If you want to specify the interface as is now possible thanks to nice people solving the issue #2784 if will always have `use=if` which will return the IP of the interface which in my case is not a public IP address and not useful at all :(

The only way around this I see is to have `use=cmd, cmd="<something intelligent>"` and craft something intelligent to be able to perform an http request over a specific interface and parse the result.

I am not good enough to actually create that cmd to send the http request over a specific interface and parse it, nor to actually update the plugin ui to allow setting it up, so thanks in advance for any help you would kindly provide !

**Environment**
OPNsense 22.1.1_3-amd64
os-ddclient (installed) | 1.1

**Comment by toxic0berliner** [comment]
I have actually been able to make it work by manually editing the config file like this : 
```
me@myopnsense:~ $sudo cat /usr/local/etc/ddclient.conf
daemon=300
syslog=yes                  # log update msgs to syslog
pid=/var/run/ddclient.pid   # record PID in file.
ssl=yes
verbose=yes

#
# setup how we expect to retrieve an IP address
#
use=web, web=http://ip1.dynupdate.no-ip.com/

use=cmd, cmd="curl --interface vtnet0 api.ipify.org", \
protocol=dyndns2, \
server=www.ovh.com, \
login=XXX, \
password=XXX\
first.example.com

use=cmd, cmd="curl --interface ovpnc1 api.ipify.org", \
protocol=dyndns2, \
server=www.ovh.com, \
login=YYY \
password=ZZZ \
second.otherexample.com
```

But that is because the folks at api.ipify.org simply return my IP and there is nothing to parse, other online providers might be less curl-friendly....

Anyway, if someone knows how to add this option (and check-ip-method ?) in the plugin and push it somewhere I'm all open to install it and test it ;) (will need directions if I need to install a plugin manually, I know only of the plus button to install from Firmware/Plugins page, sorry )

**Comment by AdSchellevis** [comment]
If the "checkip" service has rather static ip addresses, you may also add a static route to the desired location using the gateway in question.

**Comment by marjohn56** [comment]
There's another issue too. If you have the same hostname name for both IPv4 and Ipv6 you are stuffed. Check IP method needs to be per client and not global.

**Comment by toxic0berliner** [comment]
not sure about the IPv4/v6 stuff as I'm only using v4, but I agree that the ip check method needs to be per account.

**Comment by AdSchellevis** [comment]
I don't think ddclient supports that, but a manual configuration is always an option. Just  make sure to only install ddclient (without the plugin `os-ddclient`)

**Comment by marjohn56** [comment]
It can. It detects the IP version you are updating, and adjusts either the field type for the version to A or AAAA, I have a modified  ddclient where I have added godaddy. Now, if you use web to get the IP, I can use ipv6.nsupdate.info to get the IPv6 address or  ipv4.nsupdate.info to get the v4 address that works and updates correctly. I have also modded the ddclient plugin to allow me to select a different web update client for each entry, same hostname bit one is using v4 the other v6. My issue at present is having to mangle the  ddclient.conf, the one for the plugin not the daemon, to play nicely. Is there any reason we cannot use the real name of the web update site rather than the 'prettified' version that gets saved in the config? i.e. 

`use=web, web=http://ip1.dynupdate6.no-ip.com/
{%    elif checkip == 'web_nsupdate.info-ipv4' %}
use=web, web=https://ipv4.nsupdate.info/myip
{%    elif checkip == 'web_nsupdate.info-ipv6' %}
use=web, web=https://ipv6.nsupdate.info/myip`

if it could just use the real name of the checkip website in the dropdowns it's nice and easy. e,g.

`{%            elif account.service == 'godaddy' %}
use=web, web=https://{{account.checkip}}

**Comment by marjohn56** [comment]
It appears you are correct. It only updates the last entry in the config, you cannot spec the same client  twice using v4 and v6 so pants really.

**Comment by toxic0berliner** [comment]
I think your discussion merits another issue, mine here is mainly about the --interface to be used in the check ip mechanism that I would like some help in configuring to allow me to migrate from os-dyndns to os-ddclient.
I'm not willing to continue tweaking the config files manually if I can avoid it.
I have it working in the above example now please focus on questions or help in modifying the GUI to configure this method by account and not globally
