### ISSUE TITLE
os-git-backup unknown error, check log for details (sh: git: not found )

### ISSUE THREAD

**Issue by thorian93** [opnsense/plugins#2866]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
After installing os-git-backup for the first time and doing the initial configuration, the backup fails, and the general log says this:
```
git-backup unknown error, check log for details (sh: git: not found )
```
**To Reproduce**
1. Install os-git-backup
2. Configure the backup per the documentation
3. Click on 'Setup/Test Git'

**Expected behavior**
The backup should start and succeed.

**Relevant log files**
```
git-backup unknown error, check log for details (sh: git: not found )
```

**Environment**
OPNsense 22.1.1_3-amd64
FreeBSD 13.0-STABLE
OpenSSL 1.1.1m 14 Dec 2021
os-git-backup (installed) | 1.0_1 | 14.2KiB
-- | -- | --

**Comment by AdSchellevis** [comment]
`os-git-backup` depends on `git` which should automatically be installed when using the gui. You could try to install git manually using `pkg install git` from a console to try to fix the issue.

**Comment by AdSchellevis** [comment]
this sounds odd, can you share a (redacted) screenshot of your settings? maybe we're overlooking something in the validations. As far as I can find, all scripts use `/usr/local/bin/git` explicit, so not being able to find git is quite odd.

**Comment by thorian93** [comment]
Here's the configuration:
![image](https://user-images.githubusercontent.com/12239876/155882762-3a5c1662-8678-4f13-aeed-ced8384288e1.png)
The system is already some years old, and I never did a reinstallation, but I also cannot remember changing something in the system, as I really rarely use the command line. However, I am aware, that often the changes one made without realizing it, are the problematic ones.

**Comment by AdSchellevis** [comment]
wel, the url looks off to be honest. It should look like `ssh://my_server/path/repo.git` and the username field should contain the `git`  entry.

**Comment by thorian93** [comment]
Well this is embarrassing. Looks like you are right, and I misread the documentation. I sure read it, but I read what I expected to read, not what stood there. It is quite counterintuitive to be forced to change the default URL format provided by GitLab, but you sure have technical reasons to require the change.
Maybe a warning message above the table [here](https://docs.opnsense.org/manual/git-backup.html#initial-setup) might help others prevent my - admittedly avoidable - mistake.

Thanks a lot for the pointer @AdSchellevis and for the superfast support, I appreciate that!

**Comment by AdSchellevis** [comment]
there's already a "tip" note pending https://github.com/opnsense/docs/commit/0dc360ca76fbea362faced453f4f002165f1f092

The error message from git unfortunately is very confusing, better validation on our end would help, but not very high on my list at the moment to be honest.

**Comment by AdSchellevis** [comment]
close ticket?

**Comment by thorian93** [comment]
I submitted my own PR to clarify that this also affects GitLab: https://github.com/opnsense/docs/pull/382
The issue is resolved, so I am closing this.

Thanks again!
