### ISSUE TITLE
security/acme-client: Duck DNS API token get lost 

### ISSUE THREAD

**Issue by Tranquillius** [opnsense/plugins#287]
I setted up an validation method for Duck DNS. Also entered the API key and tried to issue the certificate. The issuing fails:

[Sun Sep 24 17:43:07 CEST 2017] d_api='/usr/local/share/examples/acme.sh/dnsapi/dns_duckdns.sh'
[Sun Sep 24 17:43:07 CEST 2017] Found domain api file: /usr/local/share/examples/acme.sh/dnsapi/dns_duckdns.sh
[Sun Sep 24 17:43:07 CEST 2017] You must export variable: DuckDNS_Token
[Sun Sep 24 17:43:07 CEST 2017] The token for your DuckDNS account is necessary.
[Sun Sep 24 17:43:07 CEST 2017] You can look it up in your DuckDNS account.
[Sun Sep 24 17:43:07 CEST 2017] Error add txt for domain:_acme-challenge.mydomain.duckdns.org

When I take a look in the validation method setting again, the API token field is empty.

**Comment by fraenki** [comment]
@Tranquillius Thanks for your report! This should fix your issue:

# opnsense-patch -c plugins 2c2303e
