### ISSUE TITLE
www/nginx: Feature Request: Automatic Timeout of Entries in the permaban list

### ISSUE THREAD

**Issue by waffshappen** [opnsense/plugins#2876]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
As of right now a IP, once banned by nginx rules, seems to be staged to be kept forever - even if after years its resold, under new management or now in use by a more respectful Individual.

**Describe the solution you'd like**
There should be a way to set automatic timeouts (ex: 1d, 1w etc) for banned ips which would provide instant lockdown from a bad actor but then allow the ip to grace themselves later on.

**Describe alternatives you've considered**
Not using the nginx banned alias for a firewall rule

**Comment by kulikov-a** [comment]
Hi!
IMHO, this is a very reasonable request. can we reopen it? I'll try to make a PR for this with the ability to specify the autoblock TTL in hours if @fabianfrz doesn't mind (the timestamp is already in the config/model so it shouldn't be that hard. quick tested with `ngx_autoblock.php` small changes)? (no exact timeline, sorry)
