### ISSUE TITLE
security/acme-client DNS-01 challenge with selfhost.de not working

### ISSUE THREAD

**Issue by Michael-Hennemann** [opnsense/plugins#2878]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x ] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x ] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x ] The title contains the plugin to which this issue belongs

**Describe the bug**
A clear and concise description of what the bug is, including last known working version (if any).

Let's Encrypt DNS-01 Challenge for DNS provider selfhost.de seems to be non functional. 

Error in acme log on OPNsense: 
2022-02-24T21:15:42   acme.sh   [Thu Feb 24 21:15:42 CET 2022] You need to add the txt record manually.
2022-02-24T21:15:42   acme.sh   [Thu Feb 24 21:15:42 CET 2022] Can not find dns api hook for: dns_selfhost

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**

Configure LE DNS-01 challenge with DNS provider selfhost.de

**Expected behavior**

acme-client should update the TXT (_acme-challenge.<YOUR_DOMAIN>) record automatically via api provided by selfhost.de

**Screenshots**

**Relevant log files**
If applicable, information from log files supporting your claim.

**Additional context**

For additional info see OPNSense forum (German)
https://forum.opnsense.org/index.php?topic=27109.0

**Environment**
Software version used and hardware type if relevant.
e.g.:

OPNsense 19.1.1 (amd64, OpenSSL).
Intel® Xeon™ E3-1225V5 3.3Ghz Quad Core
Network Intel® I210-AT

**Comment by fraenki** [comment]
As mentioned in https://github.com/opnsense/plugins/pull/2746 and in the release notes, selfhost DNS API support is not functional at this time:

https://github.com/opnsense/plugins/blob/698d8164342f207ea4e964bdb524526de40bb333/security/acme-client/pkg-descr#L13-L14

The PR for acme.sh https://github.com/acmesh-official/acme.sh/pull/3873 is not yet merged, so selfhost support is still lacking from acme.sh. I'll close this issue, because there's nothing else we could do. I figure it was too early to merge the GUI part in OPNsense, I should have known that this would lead to confusion... :-/

**Comment by Marvo2011** [comment]
I hope it will be merge soon. 
You could add the selfhost dns api manually.

Go to shell on you opnsense:
```
cd /usr/local/share/examples/acme.sh/dnsapi/
fetch -o dns_selfhost.sh https://raw.githubusercontent.com/Marvo2011/acme.sh/dev/dnsapi/dns_selfhost.sh
```

**Comment by bsafh** [comment]
What do I have to put in the input fiel in the OPNsense GUI? 

Whatever I try, I get this error:
`"SELFHOSTDNS_MAP must contain the fulldomain incl. prefix and at least one RID"`

I die create 2 TXT records in selfhost.de and I do have the RIDs

but
`_acme_challenge.mydomain.selfhost.eu:123456:54327`
or
```
_acme_challenge.mydomain.selfhost.eu:123456:54327
alias.mydomain.selfhost.eu:111445
```
does not work.

Is it in the wrong format?

**Comment by Marvo2011** [comment]
Hello @bsafh,

you have to put the
```_acme_challenge.mydomain.selfhost.eu:123456:54327``` 
in the field `RID Mapping` under ACME Challenge Types. Also put the Selfhost customer number in the `User` field and your password in `Password`.

It is possible that Selfhost restrict the api for free domain/account, I never have tried this.

**Comment by bsafh** [comment]
Hmm, well I did exactly that. Strange. Did not work.
The script error message comes before it even tries to connect to selfhost.de, it's an internal check.

**Comment by Marvo2011** [comment]
@bsafh I have request a free domain, wenn I have it I will try it. I think so because we have some one that have exactly the same issue with the free domain with usage of the cli script.

**Comment by bsafh** [comment]
Thanks!
