### ISSUE TITLE
os-git-backup 1.0_1 does not work with ssh key authentication

### ISSUE THREAD

**Issue by urmel1960** [opnsense/plugins#2882]
**Important notices**

- [X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X] The title contains the plugin to which this issue belongs

**Describe the bug**
Setting up os-git-backup with ssh key authetication does not work with remote self hosted gitlab ee server.

**To Reproduce**
1. Go to 'System\Configuration\Backup and enter neccessary data into the appropriate section including ssh private key data '
2. Click on 'Setup/Test Git Button'
3. Yor get an error message that it is saved but not working. 

Log file says:

`Error  - php-cgi - git-backup authentication failure (xxxx@git@git.domain.tld:  Permission denied (publickey,password).\x0d fatal: Could not read from  remote repository.  Please make sure you have the correct access rights  and the repository exists. )
`

6. I double checked that the proper public ssh key is set up in the remote gitlab sevrer and that the connection is working properly outside of opnsense using the same ssh-key pair

**Expected behavior**
ssh key authentication should work for backup config to remote git repo

**Screenshots**
n/a

**Relevant log files**
see above

**Additional context**
none

**Environment**

OPNsense 22.1.2_1-amd64FreeBSD 13.0-STABLEOpenSSL 1.1.1m  14 Dec 2021 
Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (6 cores, 12 threads)

**Comment by fraenki** [comment]
> git-backup authentication failure (xxxx@git@git.domain.tld: Permission denied

It looks like you've set `User Name` to "xxxx@git", while you should only use "xxxx" there.

**Comment by urmel1960** [comment]
That was not completely the solution but it pointed me into the right direction. 

In opnsense I entered the username of the user from the gitlab server where the ssh key is associated to. In fact it must be just "git" in my case - that means it is the username running  the gitlab server on the remote machine. 

That finally worked. 

Maybe a good idea to improve help for the varius filed in that section.

**Comment by AdSchellevis** [comment]
> Maybe a good idea to improve help for the varius filed in that section.

https://docs.opnsense.org/manual/git-backup.html#initial-setup

^^ "Username, when using gitlab and ssh, the default is git here (most of these providers use a single user and identify the user by it’s key)"  ;)

**Comment by GJKrupa** [comment]
git is the username that I filled in on the UI
