### ISSUE TITLE
Feature request: Static ARP entries and Unsolicitated ARP responses against IP collisions

### ISSUE THREAD

**Issue by peppelinux** [opnsense/plugins#289]
It would be great to have a tool to face ipv4 collisions.

For this feature we should have to extend the actual ARP OPN management, just develop a UI to store static ARP entries, following the example of

/system_routes.php

Coupled with this we could also create a tool to forge Unsolicitated ARP responses. Actually I'm doing this kind of task with the help of nemesis network tool, this way:

````
# to be unsolecitated, continous, arp response, it could run into a while :)
while [ 1 ] ;
    do sleep 1 && 
    nemesis arp -d eth0 -r -S 10.97.60.33 -h 98:90:96:A6:4F:DB -D 10.97.60.245 -m 00:16:b9:d4:9a:00;
done

# to send these unsolicitated responses to all the hosts, from 1 to 245 :)
while [ 1 ]; do
    for i in {1..254}; 
        do sleep 1 &&
        nemesis arp -d eth0 -r -S 10.97.60.33 -h 98:90:96:A6:4F:DB -D 10.97.60.$i; 
        done;
done
````
IT would be great to use this feature through the OPN UI.
What about nemesis package? Could it be ported, compiled or whatever, on hardenedBSD?

**Comment by fabianfrz** [comment]
I usually use [Bettercap](https://www.bettercap.org/) for MITM. It is a very good tool and easy to extend.
If you want to sniff in the network, `bettercap -I interface_name -X` should do the job.

**Comment by peppelinux** [comment]
Thank you Fabianfrz, bettercap is awesome.
I think that the main goal, on OPNsense, wouldn't be doing a MITM but prevent the MITM.
So I'm asking if would you like to deploy/develop, into OPNsense, a robust strategy to defence against MITM and I spoke about "unsolicitated arp responses" and, more over, static ARP entries.

Could they be good enough against MITM and, the question is, do we want to implement this feature in OPN?

I was thinking about how many problems could resolve, a network administrator, with the help of a network appliance like OPN, with this kind of funcionality.

Do you think that static ARP entries and unsolicitated ARP response could be helpfull in OPN against MITM?

**Comment by fabianfrz** [comment]
Another idea is using [ndpmon](http://ndpmon.sourceforge.net/) and `arpwatch` for monitoring. A static neighbor cache in OPNsense would be good but it would be still half duplex (the host is still vulnerable to ARP spoofing). It might be also very hard to teach the firewall all the MAC/IP combinations.

**Comment by peppelinux** [comment]
So, can we develop arpwatch plugin and, also, a tool to produce unsolicitated arp response with a scheduled interval?

it's just a proposal in a potentially extensive view of what we are considering the potentially best network solution ever, no stress :) if the idea could sounds fine we can think when start coding.

**Comment by fabianfrz** [comment]
@peppelinux `ndpmon` and `arpwatch` are tools to detect an anomaly. You don't need to inject packets as they act passively (they sniff traffic and start an action if something is detected).

**Comment by peppelinux** [comment]
@fabianfrz thank you, I really do not want to boring you on this topic. I was tryng to introduce an active defense together with a passive defense. Arpwatch listens but if the sysadmin have a ip collision on a critical peer and he do not have the time to take a look to find where is the collider, he could simply push in the LAN a fixed amount of gratuitous arp responses, letting  others nodes to refresh their cache in the right way

**Comment by fabianfrz** [comment]
@peppelinux the neighbor cache is only valid for seconds so there is no reson to restore it. The right action would be banning one of the hosts via the switch by setting the port down.

Maybe that can help you: https://supportforums.cisco.com/t5/lan-switching-and-routing/portsecurity-and-ip-conflicts/td-p/1250461

**Comment by peppelinux** [comment]
@fabianfrz thank you, I really appreciate your help, unfortunately in each office everyone can link a switch and share a port with other guys so, I'm talking about ARP because I know that I have to deal with it :)

**Comment by peppelinux** [comment]
I found a good solution with addrwatch coupled with stored procedures as proactive actions:
https://github.com/fln/addrwatch

**Comment by fichtner** [comment]
Contributor missing -> timeout.

**Comment by peppelinux** [comment]
Probably this issue could be helpfull in a open status as a reminder. A titolo like this could be awesome i think

**Comment by fichtner** [comment]
1,5 years and zero progress say no. Google and GitHub search still work fine despite the status.
