### ISSUE TITLE
os-freeradius: Error processing template "sites-enabled-inner-tunnel". Leads to empty file "inner-tunnel"

### ISSUE THREAD

**Issue by oli-h** [opnsense/plugins#2890]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X] The title contains the plugin to which this issue belongs

**Describe the bug**
EAP Radius-Authentication (for Wifi-Interface) fails with "TTLS and PAP". This worked for ~2 years with OpnSense before version 22.1.

**To Reproduce**
1. Install os-freeradius
2. Do all setup for TTLS for a WiFi-Interface (Client with Shared secrets, Certificates, User+Password etc.)
3. Start radius-Service
4. Look file `/usr/local/etc/raddb/sites-available/**inner-tunnel**` --> has **size=0**
5. Look into Backend-Logs (via Web-UI) and you see **Error while processing `OPNsense/Freeradius OPNsense/Freeradius/sites-enabled-inner-tunnel`**: 'collections.OrderedDict object' has no attribute 'ldap'

**Expected behavior**
A properly generated "inner-tunnel" file and a working EAP-Authentication with TTLS-PAP

**Relevant log files**
`2022-03-13T15:00:46 | Error | configd.py | [a0091e7c-6524-4d52-8c23-a96e4d244358] Inline action failed with OPNsense/Freeradius OPNsense/Freeradius/sites-enabled-inner-tunnel 'collections.OrderedDict object' has no attribute 'ldap' at Traceback (most recent call last): File "/usr/local/opnsense/service/modules/template.py", line 267, in _generate content = j2_page.render(cnf_data) File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 1304, in render self.environment.handle_exception() File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception raise rewrite_traceback_stack(source=source) File "/usr/local/opnsense/service/modules/../templates/OPNsense/Freeradius/sites-enabled-inner-tunnel", line 158, in top-level template code {% if helpers.exists('OPNsense.freeradius.ldap.innertunnel') and OPNsense.freeradius.general.ldap.innertunnel == '1' %} File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 474, in getattr return getattr(obj, attribute) jinja2.exceptions.UndefinedError: 'collections.OrderedDict object' has no attribute 'ldap' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/local/opnsense/service/modules/processhandler.py", line 506, in execute return ph_inline_actions.execute(self, inline_act_parameters) File "/usr/local/opnsense/service/modules/ph_inline_actions.py", line 51, in execute filenames = tmpl.generate(parameters) File "/usr/local/opnsense/service/modules/template.py", line 344, in generate raise render_exception File "/usr/local/opnsense/service/modules/template.py", line 335, in generate for filename in self._generate(template_name, create_directory): File "/usr/local/opnsense/service/modules/template.py", line 270, in _generate raise Exception("%s %s %s" % (module_name, template_filename, render_exception)) Exception: OPNsense/Freeradius OPNsense/Freeradius/sites-enabled-inner-tunnel 'collections.OrderedDict object' has no attribute 'ldap'`

**Additional context**
- imported a config.xml from OpnSense 21.7

**Environment**
OPNsense 22.1.2_1-amd64
FreeBSD 13.0-STABLE
OpenSSL 1.1.1m 14 Dec 2021
running on APU2

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/plugins/pull/2881 ?

**Comment by oli-h** [comment]
Yepp. Know idea why I didn't find it. Will close this here. Thx and Sorry

**Comment by oli-h** [comment]
Note: applied patch from #2881 with `opnsense-patch -c plugins 1354e23397812cd3d51054b715411d2c2e1f114b` - it now works like a charm. Thx guys :-)
