### ISSUE TITLE
dns/ddclient: add AWS Route53

### ISSUE THREAD

**Issue by AryasDad** [opnsense/plugins#2892]
Important notices
Before you add a new report, we ask you kindly to acknowledge the following:

[ x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
[ x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
[ x] When the request is meant for an existing plugin, I've added its name to the title.

Is your feature request related to a problem? Please describe.
Legacy plugin set to be deprecated has Route53 as a provider option, but replacement plugin does not.

Describe the solution you'd like
Add Route53 as a provider in the GUI.

Describe alternatives you've considered
Use the legacy plugin but would like to switch to non-deprecated plugin.

**Comment by xlrx** [comment]
Second the request. It's a 22.7 breaker for me.
