### ISSUE TITLE
dns/ddclient 1.3 breaks SSL updates

### ISSUE THREAD

**Issue by MrRoundRobin** [opnsense/plugins#2894]
- [x] I have read the contributing guidelines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
In commit d408dbb6487f6316ec38e868d59fea00320323a8 the global configuration option to force HTTPS for updates was moved to individual entries. But this only ensures that the ip detection is done over SSL not the actual update. By default, this version of ddclient the dnydns2 protocol uses only HTTP: https://github.com/ddclient/ddclient/blob/v3.9.1/ddclient#L2789

To force HTTPS there is the global `SSL=yes` option. https://github.com/ddclient/ddclient/blob/v3.9.1/ddclient#L2043

There are some DDNS providers which force Updates over HTTPS (like dynv2.com).

**To Reproduce**
1. Add an dynv6.com account
2. Configure SSL on the account
3. See the update logs:

```
ddclient[46082]	49992 - [meta sequenceId="19"] FAILED: updating [..]: Could not connect to dynv6.com.
[...]
ddclient[46082]	48049 - [meta sequenceId="6"] CONNECTED: using HTTP
ddclient[46082]	47650 - [meta sequenceId="5"] CONNECT: dynv6.com
```

**Comment by Aergan** [comment]
Having the same issue using 1.3 with namecheap

**Comment by MrRoundRobin** [comment]
@Aergan Namecheap works for me when you select it as Service. It uses HTTPS:
https://github.com/ddclient/ddclient/blob/v3.9.1/ddclient#L3726

**Comment by AdSchellevis** [comment]
@MrRoundRobin can you try https://github.com/opnsense/plugins/commit/09d2b21b09b42a5ab15fd39b1a783f8887f59785 ? seems like I missed a spot

**Comment by MrRoundRobin** [comment]
@AdSchellevis sadly it does not work on an account level 😞 That's why I added that option in the global settings page.

**Comment by AdSchellevis** [comment]
@MrRoundRobin sorry, my mistake. I'll reopen so we can discuss options. We may have to move the option back or decide to set the global setting based on the accounts (if set in any, choose ssl)

**Comment by MrRoundRobin** [comment]
I thought about 'if set in any, choose HTTPS'. But this is some magic decision which is not obvious and impacts other accounts, which might not work anymore if they don't support HTTPS. (This should not be the case, but you never know). That's why I chose the specific option in the first implementation. I think it's easier to predict. 

In addition, it's easier to implement: `set it if its marked` instead of `set it if it's set in any account which is enabled`. Which is also questionable, should disabling an account disable the global option? Imagine you have two accounts, both requiring HTTPS, but you set it only in the first account. Everything works but disabling one impacts the second which is, as said before, not obvious to see.

What do you think? @AdSchellevis

**Comment by AdSchellevis** [comment]
> I thought about 'if set in any, choose HTTPS'. But this is some magic decision which is not obvious and impacts other accounts, which might not work anymore if they don't support HTTPS. (This should not be the case, but you never know). That's why I chose the specific option in the first implementation. I think it's easier to predict.

I see your point, but it's less easy to revert to the old situation due to migrations. Whatever we do it will always be confusing, I totally missed this, otherwise I probably wouldn't have merged this. (functionally I would rather see that accounts are isolated, but ddclient is quite confusing about the options).

> In addition, it's easier to implement: set it if its marked instead of set it if it's set in any account which is enabled. Which is also questionable, should disabling an account disable the global option? Imagine you have two accounts, both requiring HTTPS, but you set it only in the first account. Everything works but disabling one impacts the second which is, as said before, not obvious to see.

If one has ssl enabled, it will be valid for the global scope, we will have to change the label explaining that.

**Comment by MrRoundRobin** [comment]
For me it's ok to use the individual ssl checkmark, just wanted to share why I decided to do it like that in the first version.

Can you fix that? I'm not too deep in that templating language.

**Comment by AdSchellevis** [comment]
will certainly do, I'm (partly) responsible for this mess.

**Comment by AdSchellevis** [comment]
@MrRoundRobin https://github.com/opnsense/plugins/commit/4fcedf7201800e45d1ab60a24ab2755c9ac3ac68 should to the trick

**Comment by MrRoundRobin** [comment]
Just a small typo? `[..] check check ip [..]`

https://github.com/opnsense/plugins/blob/4fcedf7201800e45d1ab60a24ab2755c9ac3ac68/dns/ddclient/src/opnsense/mvc/app/controllers/OPNsense/DynDNS/forms/dialogAccount.xml#L73

**Comment by AdSchellevis** [comment]
@MrRoundRobin yep, thanks!
