### ISSUE TITLE
HAproxy unknown keyword "inactive"

### ISSUE THREAD

**Issue by jpawlowski** [opnsense/plugins#29]
When using modes like "disabled" or "inactive" in server configuration, the following warning occurs:

    unknown keyword 'inactive'. Registered keywords :
    [ ALL] id <arg>
    [ SSL] ca-file <arg>
    [ SSL] check-ssl
    [ SSL] ciphers <arg>
    [ SSL] crl-file <arg>
    [ SSL] crt <arg>
    [ SSL] force-sslv3
    [ SSL] force-tlsv10
    [ SSL] force-tlsv11
    [ SSL] force-tlsv12
    [ SSL] no-ssl-reuse
    [ SSL] no-sslv3
    [ SSL] no-tlsv10
    [ SSL] no-tlsv11
    [ SSL] no-tlsv12
    [ SSL] no-tls-tickets
    [ SSL] send-proxy-v2-ssl
    [ SSL] send-proxy-v2-ssl-cn
    [ SSL] sni <arg>
    [ SSL] ssl
    [ SSL] verify <arg>
    [ SSL] verifyhost <arg>
    [ALERT] 211/195229 (47201) : Error(s) found in configuration file : /usr/local/etc/haproxy.conf
    [ALERT] 211/195229 (47201) : Fatal errors found in configuration.

However, HAproxy daemon boots up just as normal ignoring that warning.

**Comment by fraenki** [comment]
Actually the 'disabled' keyword is valid according to the [HAProxy documentation](http://cbonte.github.io/haproxy-dconv/1.6/configuration.html#5.2-disabled). But I've removed the obsolete 'inactive' mode. Thanks for reporting this issue!

**Comment by fraenki** [comment]
@fichtner: This should be fixed, please close this issue.
