### ISSUE TITLE
os-netdata: Connect agent to netdata cloud fails

### ISSUE THREAD

**Issue by cmonty14** [opnsense/plugins#2902]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
After installation of plugin os-netdata I want to connect this agent to [Netdata Cloud](https://learn.netdata.cloud/docs/agent/claim).
Based on this installation instruction I run this command:
`curl https://my-netdata.io/kickstart.sh > /tmp/netdata-kickstart.sh && sh /tmp/netdata-kickstart.sh --claim-token -<token> --claim-rooms <room> --claim-url https://app.netdata.cloud`

This fails with following error:
`ABORTED  Found an existing netdata install at /usr/local, but the install type is 'custom', which is not supported, refusing to proceed.`

**To Reproduce**
1. Go to System - Firmware - Plugins
2. Click on Install for os-netdata
3. Enter CLI shell
4. Run command to connect agent to cloud

**Expected behavior**
Connection of agent to netdata cloud completes w/o error.

**Environment**
OPNsense 22.1.3-amd64
FreeBSD 13.0-STABLE
OpenSSL 1.1.1m 14 Dec 2021

**Comment by mimugmail** [comment]
Cloud support is disabled during build time cause of unasked sending data to it

**Comment by cmonty14** [comment]
> Cloud support is disabled during build time cause of unasked sending data to it

This means it is considered as a security issue?

**Comment by mimugmail** [comment]
No, its more a privacy concern

**Comment by kalpik** [comment]
> Cloud support is disabled during build time cause of unasked sending data to it

Sorry to bump an old issue, but could this be made a toggle so people who want to use the cloud can use it?

**Comment by xitation** [comment]
You could include the --disable-telemetry flag as part of the build to disable the anonymous data collection aspects. 

See more info here - https://community.netdata.cloud/t/opnsense-with-netdata-cloud/2734/4

Would be great to have an official plugin that enable the cloud sync for those that would benefit from it.

**Comment by dimitrijp** [comment]
> You could include the --disable-telemetry flag as part of the build to disable the anonymous data collection aspects.
> 
> See more info here - https://community.netdata.cloud/t/opnsense-with-netdata-cloud/2734/4
> 
> Would be great to have an official plugin that enable the cloud sync for those that would benefit from it.

Im also waiting for this, i hope maintainer builds the plugin without telemetry, so that we can use the cloud feature, or at least make it optional.

**Comment by mimugmail** [comment]
I just the binary, it already has cloud support.
Is there any config option needed for templating?
I dont use the cloud feature

**Comment by xitation** [comment]
There are numerous ways to join the system to the cloud.
However the package needs to have cloud support included/compiled to allow the following to work.

https://learn.netdata.cloud/docs/getting-started/monitor-your-infrastructure/connect-agent-to-cloud#claiming-script

I usually use the CLI option due to the way I like to deploy it, however you could allow for the app to ask for the claim id and rooms to join and then have a script run the following after end user provides those variables.

/usr/sbin/netdata -D -W "claim -token=MYTOKEN1234567 -rooms=room1,room2"

Or to keep things simple require that people ssh into the host and run this command by hand instead.

**Comment by mimugmail** [comment]
The package already has cloud support, can anyone test the command above?

**Comment by dimitrijp** [comment]
Tested and working.

**Comment by xitation** [comment]
Can confirm, also working for me!

**Comment by mimugmail** [comment]
So you both ran such a command one time and thats enough?

/usr/sbin/netdata -D -W "claim -token=MYTOKEN1234567 -rooms=room1,room2"
netdata-claim.sh -token=MYTOKEN1234567 -rooms=room1,room2

**Comment by xitation** [comment]
I used the netdata-claim.sh -token=MYTOKEN1234567 command, as that's what I normally use on other builds so used what I know.

I didn't specific a room, it's optional.
