### ISSUE TITLE
net/haproxy: New cache parameters in HAProxy 2.4

### ISSUE THREAD

**Issue by svenschiller** [opnsense/plugins#2908]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [y] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [y] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [y] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
HAProxy 2.4 added two new parameters (process-vary, max-secondary-entries) to support caching responses using the Vary header, see http://cbonte.github.io/haproxy-dconv/2.4/configuration.html#6.2.1-process-vary

Could you please add support for these in the web GUI?

**Describe alternatives you've considered**
No alternatives

**Additional context**
None

**Comment by jan-win1993** [comment]
This feature will be available in the upcoming release 3.11 of os-haproxy.
