### ISSUE TITLE
net/freeradius: accounts management

### ISSUE THREAD

**Issue by peppelinux** [opnsense/plugins#291]
I do not have understand if in OPNsense is possible to managed freeradius accounts, if there is or there will be the possibility to view and modify it's users definitions

**Comment by mimugmail** [comment]
Hi, ATM only the attributes available when adding a user can be managed.

Do you need some additional attributes?

**Comment by peppelinux** [comment]
hi @mimugmail thank you very much for your attention, at the moment I do not need any additional attribute. If needed, we could develop it in OPN but I did not understand, sincerely, how to manage freeRadius users (or ldap users as well) in OPNsense, I mean in the way that it could let me view, search, create, modify and delete a user or a group of user... And watch who's actually logged (accounting log).

If I'm doing a mess tell me how to explore this funcionality, if some other feature are needed we could start to think how to develop them :) (first of all: "why" we are developing them!)

**Comment by mimugmail** [comment]
My intention to build this plugin was WPA2/Enterprise for home use, so no need fro group management.
If you have some practical examples please post, I dont think it's too hard to build groups.

Accouting on a firewall is not that good since most systems don't have much diskspace. Also most applications using radius have their own user mgmt where connect time is displayed.

**Comment by peppelinux** [comment]
For WPA2 home use, and also office use, I'm using openWRT/LEDE on AccessPoints and a standalone freeradius with mysql. Now I'm looking to introduce a good freeradius web interface for a general purpose user management. 

Someone of my collegues tolds me that in pfSense there was the possibility to manage Radius accounts and we are looking how to to that in a common way, if possibile, in OPNsense.

If there are no way to have this feature in OPNsense I will have to develop a freeRadius accounting manager using Django Framework.

Talking about embedded devices: Disk space doesn't worry me because my freeRadius configuration always have mysql and this, as you know, could be deployed on another server too (and logs with NFS). But, as I tolds you, now I'm looking for a general purpose common way to do that, without any hardcoding. Do I miss how to create freeradius user in OPNsense?

**Comment by mimugmail** [comment]
If you need a general purpose FR then OPN is the wrong place. The pfsense plugin is way more feature complete. We wont setup MySQL on OPN, so this not the right place.

What do you mean with createing freeradius users? You go to Services - FreeRADIUS - Users ... and create the users ...

**Comment by fichtner** [comment]
it would seem @peppelinux does now know a plugin exists yet? :)

**Comment by peppelinux** [comment]
@fichtner You got it man! Really thank you, I now have the answer: "Yes, we also have a freeRadius plugin to do this".

**Comment by fichtner** [comment]
There is an early plugin with essential features by @mimugmail, yes. So far, not a lot of requests additional functionality which does not mean it out of the question to extend the current scope. I don't think a database is off the table as well if somebody is doing the work. The packages already have mysql and postgresql as packages in addition to the "standard" sqlite.

**Comment by peppelinux** [comment]
@fichtner good news. I'm going to see if the pluging can do our needs, if everything is good and just something is needed I can give you an help.

brilliant
