### ISSUE TITLE
os-acme-client: Had to install it 3 times under 22.1.4 for it to work

### ISSUE THREAD

**Issue by meyergru** [opnsense/plugins#2912]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
Unser 22.1.4, I wanted to activate os-acme-client, but it did not get fully installed the first (and the second time).

**To Reproduce**
1. Install 22.1.4
2. Try to install os-acme-client.
3. No menu entries appear
4. Go back to plugins, os-acme-client does not show "(installed)".
5. Try a few more times until the installation window actually shows that show uid has been created.

**Expected behavior**
Plugins is installed on first run.

**Screenshots**
Now it works, so duh.

**Relevant log files**
Logs show the plugin only being installed after 3rd try. However, there were no errors or warnings in the window on 1st or 2nd try.

**Environment**
OPNsense 22.1.4 (amd64, OpenSSL)

**Comment by fichtner** [comment]
It might seem like hanging but from previous experience it can hang quite a bit during installation for no fault of its own. Menu hooks, package database... all this only gets updated when the process was finished. It might still have been running when you tried the second and third time?


Cheers,
Franco

**Comment by meyergru** [comment]
Probably, but I had the impression that the process took longer on the successful 3rd try. I did not see the uid creation in the log windows on 1st and 2nd tries. I just did this on another box and it worked right away, BTW.
