### ISSUE TITLE
os-ddclient plugin does not support linode dynamic dns update

### ISSUE THREAD

**Issue by rfc4711** [opnsense/plugins#2914]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [ X ] I have read the contributing guidelines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [ X ] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [ X ] The title contains the plugin to which this issue belongs

**Describe the bug**
Linode updates are not supported ddclient, but are supported with legacy dyndns client

With the forced update to ddclient in the future, there is a lack of provider options compared to the DynDNS-OS plugin. Can before the forced switchover parity to all providers as previously available with the os-dyndns plugin be achieved?
I use Linode to update my dynamic DNS domains, are there at least instructions on how to add Linode as a custom provider to ddclient?

**To Reproduce**
1. Install os-ddclient
2. Try to convert os-dyns configuration to os-ddlcient config

**Expected behavior**
Have feature parity with the to be depreciated plugin

**Environment**
OPNsense 22.1.4_1-amd64

**Comment by vaygr** [comment]
I second this, as I realized it after moving away from pfSense to OPNsense. Would be nice to have it supported.

**Comment by webxI23** [comment]
Same here, using Linode as my domain DNS hosting. Ok for now but I don't find a propet way to convert my configuration to os-ddclient. I think Linode is a pretty serious company and should be there.

**Comment by snuffop** [comment]
No Traction on this,  or at least instructions on using custom?  We're on the cusp of forced update

**Comment by vladgitdev** [comment]
Maybe not the best solution, but worked for me while a native ddclient (or other plugin) solution arrives:

I created a no-ip host that I update from opnsense (any ddclient supported service should work) and then I created a CNAME record on the Linode Domain (DNS) Manager pointing to the no-ip host.

A script that employs curl (as shown in https://www.linode.com/docs/api/domains/#domain-record-update) probably would be a better way to implement a more straightforward solution.
