### ISSUE TITLE
os-ddclient http Update

### ISSUE THREAD

**Issue by abplfab** [opnsense/plugins#2916]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
We are using our own dyndns. It uses https URL to update. With the legacy plugin it works fine on about 50 OPNsense installations.
![image](https://user-images.githubusercontent.com/28706980/160272807-09430830-0c6a-4a71-9785-ea0c20c4963c.png)

With os-ddclient this doesn't seem to work anymore. It would also be nice if there is an automatic migration of the legacy plugin to the os-ddclient plugin...

**Expected behavior**
Add https URL update

**Screenshots**
Legacy:
![image](https://user-images.githubusercontent.com/28706980/160272844-464798a4-e39b-4b52-9b20-dc609b98195d.png)

**Relevant log files**
none

**Additional context**
none

**Environment**
OPNsense 22.1.4_1 (amd64, OpenSSL).
APU Boards

**Comment by alexandergitter** [comment]
I have more or less the same issue.

One thing I'd like to add is that my DynDNS server uses a port different from 80/443. In the os-ddclient settings, I don't see a way to set a different port, the "Server" setting only accepts an ip address / hostname. The good thing about the legacy plugin is that I can just provide an arbitrary update URL.
