### ISSUE TITLE
mDNS Repeater CARP Failover file missing

### ISSUE THREAD

**Issue by 53c70r** [opnsense/plugins#2919]
Using the mDNS Plugin in CARP setup (simple Master/Backup with two hosts) the mDNS Service will not start because no initial file /var/run/mdns-repeater.CARP_MASTER gets created.
This was tested on the CARP Master all selected interface are in Master state when trying to active the CARP Failover setting.
The plugin works just fine without "Enable CARP Failover".

Settings on Master

Enable: yes
Enable CARP Failover: yes
Interface: 5 different interface all with CARP set up and running as Master.

```
<13>1 2022-03-30T16:57:51+02:00 opnsense-00 root 41210 - [meta sequenceId="5"] /usr/local/etc/rc.d/mdns-repeater: WARNING: /var/run/mdns-repeater.CARP_MASTER is not readable.
<13>1 2022-03-30T16:57:51+02:00 opnsense-00 root 42699 - [meta sequenceId="6"] /usr/local/etc/rc.d/mdns-repeater: WARNING: failed precmd routine for mdns_repeater
<13>1 2022-03-30T16:57:51+02:00 opnsense-00 configctl 94682 - [meta sequenceId="7"] event @ 1648652271.25 msg: Mar 30 16:57:51 opnsense-00 config[75228]: [2022-03-30T16:57:51+02:00][info] config-event: new_config /conf/backup/config-1648652271.1896.xml 
<13>1 2022-03-30T16:57:51+02:00 opnsense-00 configctl 94682 - [meta sequenceId="8"] event @ 1648652271.25 exec: system event config_changed
```

**Comment by fichtner** [comment]
@53c70r thanks, maybe the issue is it needs a backup/master transition (or a plain reboot) to trigger?

**Comment by 53c70r** [comment]
The actual problem is it won't start in the first place right after saving the config.
Immediate after saving the config with "Enable CARP Failover" the services goes into fail state.
Reboots did not solve the problem.
Should there be a High Availability setting for synchronizing the config to the secondary firewall too?

**Comment by lolkop-cmd** [comment]
Same Issue here

**Comment by hanzec** [comment]
create an empty file using `touch /var/run/mdns-repeater.CARP_MASTER` would solve the problem

**Comment by stelb** [comment]
just had that issue, i was sure mdns was running at least until last update.  How is this file maintained anyway?
No time right now..

**Comment by stelb** [comment]
/usr/local/etc/rc.syshook.d/carp/50-mdns should be doing this, one time it failed while switching to BACKUP and MASTER again.  But manually called it created the file as intendend.
The second  time it just works as expected.

Noting that, as known mishap, just in case I can't see my services next time.
