### ISSUE TITLE
net/freeradius: feature Improvements

### ISSUE THREAD

**Issue by peppelinux** [opnsense/plugins#292]
os-freeradius is a smart plugin, really. I'm going to love it.
I saw that at line 90, in file user.volt the password input field is in clear text.

Is it possible to have two separate input fields, password and verify_password, as a html password/hidden field?

I'm continuing to study this plugin, if somethingelse I will post here, and after all, It's probably that there will be some coding :)

**Comment by mimugmail** [comment]
You know that the passwords are stored in cleartext in users file?

**Comment by peppelinux** [comment]
We could opening the discussion on this, wouldn't be better to store hashed password?
I use NT-password for eap compatibility, instead of this we could use other format or, better then all, a customizable option in a settings template

**Comment by mimugmail** [comment]
Hm, my thought was that encrypted passwords can only be used by pap .. does this really work with all types of EAP?

**Comment by mimugmail** [comment]
@peppelinux do you know to export only the NT Hash from smbencrypt?

**Comment by peppelinux** [comment]
I coded it:
https://github.com/peppelinux/UniTools/blob/master/freeradius/nt_hash.py

yeah, sometime smbcrypt tired me :)

**Comment by mimugmail** [comment]
Did you test it on OPN? 

I get 
```
Traceback (most recent call last):
  File "nt_hash.py", line 2, in <module>
    from passlib.hash import nthash
ImportError: No module named passlib.hash
```

**Comment by mimugmail** [comment]
Oh, no passlib :(
Really ugly to extract from smbencrypt

**Comment by peppelinux** [comment]
You have just to install python2 passlib.
I do not tested it because I didn't start to code into this project yet. At this time I could not start coding on it but I'm keeping an eye on this feature request, you know :)

**Comment by mimugmail** [comment]
@fichtner What do think about adding passlib? 

With the `smbencrypt` program from freeradius I get:

```
root@OPNsense:~ # smbencrypt test
LM Hash                         NT Hash
--------------------------------        --------------------------------
01FC5A6BE7BC6929AAD3B435B51404EE        0CB6948805F797BF2A82807973B89537
```
and I only need:

`0CB6948805F797BF2A82807973B89537`

I wasn't really successful to extract it with grep/tail/cut bla .. perhaps your BSD skills are better then mine (hopefully) :D

**Comment by fichtner** [comment]
not today, @AdSchellevis should take a look, too

**Comment by mimugmail** [comment]
Easy .. :)

**Comment by peppelinux** [comment]
@mimugmail it seems trivial but it's not so! :)

I mean that smbcrypt works like something that uses stdout in a very special way. Look at this:

````
$ smbencrypt ciao > test 
LM Hash                         	NT Hash
--------------------------------	--------------------------------
````
Seems strange, doesn't it? Password hashes are stored into a file called "test" but command's stdout is still visible so...This means that output header is not on stdout fd!

But the password is on stdout and can get it as usual, this way:

````
smbencrypt yourpasswd | awk -F'\t' {'print $2'} > hashed_password_file
# or
smbencrypt yourpasswd | awk -F'\t' {'print $2'}
````
the only output that you'll fetch is the hased password, it works and it should be good enough :)

**Comment by AdSchellevis** [comment]
If passwords are stored in the model using nt hash, it’s probably better  to use a php function in the model to handle hashing, if I’m not mistaken the chap package has a similarly function https://pear.php.net/manual/en/package.encryption.crypt-chap.crypt-chap-mschapv1.ntpasswordhash.php

**Comment by peppelinux** [comment]
Sorry for all that commotion but, regarding to smbencrypt.c source file, [found in freeradius source](https://doc.freeradius.org/smbencrypt_8c_source.html), at line 70 we can read:

````
         fprintf(stderr, "LM Hash                         \tNT Hash\n");
         fprintf(stderr, "--------------------------------\t--------------------------------\n");
         fflush(stderr);
````
it was written on stderr ! :)

**Comment by mimugmail** [comment]
@peppelinux This only works in Linux

```
root@OPNsense:~ # smbencrypt yourpasswd | awk -F"\t" {'print $2'}
awk: syntax error at source line 1
 context is
         >>> print <<<  $2
awk: bailing out at source line 1
LM Hash                         NT Hash
--------------------------------        --------------------------------

```

**Comment by peppelinux** [comment]
@AdSchellevis I saw a lot of mess in the latest PHP upgrades, regarding crypt features.
Could it be good from configd command, installing passlib?

@mimugmail You're right, for getting it to work on BSD we should move the ` symbol this way

````
smbencrypt yourpasswd | awk -F"\t" '{print $2}'
````

In other works the ` should stay outside the {}. Nothingelse :)

**Comment by AdSchellevis** [comment]
I really wouldn’t know why we shouldn’t first try the standard functions.... it’s not really worth the call overhead if you can easily store the correct value at once.

**Comment by AdSchellevis** [comment]
For reference, the hash code in the chap lib:

    /**

     * Generates the NT-HASH from the given plaintext password.

     *

     * @access public

     * @return string 

     */

    function ntPasswordHash($password = null) 

    {

        if (isset($password)) {

            return pack('H*',hash('md4', $this->str2unicode($password)));

        } else {

            return pack('H*',hash('md4', $this->str2unicode($this->password)));

        }

    }


Doesn’t look like a lot of magic to me

**Comment by fichtner** [comment]
We used to carry this exact code ;) https://github.com/opnsense/core/blob/1812da68d4f8e8bbf0c125ff3de4dd9a5137685f/src/etc/inc/captiveportal.CHAP.inc#L182

**Comment by AdSchellevis** [comment]
I know 😊

**Comment by mimugmail** [comment]
I dont want to change the password type from plain to nt in the model since this would need a migration of existing ones. 

What I have done now it exclude the password tab in the view and changed the field type to password so you will only see *****

This should be fine for the beginning. When the users are familiar with the new design and don't worry about seeing passwords anymore we can change the type in model later on.

**Comment by peppelinux** [comment]
@mimugmail We could add an option to set the password type for each user. Passwords do not must be of the same type, different user could have different password storage. The option set labels could be the same used by freeradius:

- Cleartext-Password
- NT-Password
- LM-Password
- MD5-Password
- SMD5-Password
- SSHA-Password
- Crypt-Password

We could activate the only supported password type at the moment. LM, NT, MD5, Crypt and Cleartext, seems trivial to introduce

**Comment by mimugmail** [comment]
@peppelinux Good idea, so let me push my changes so far and then you are very welcome to add this functionality 👍

**Comment by peppelinux** [comment]
@mimugmail I also wrote an update comment on the previous post. 
We should only map a convertion function for every password type id (NT-Password, LM-Password...). This works only for Cleartext-password, if the original password was not created/stored as cleartext the password must be resetted.

Great!

**Comment by peppelinux** [comment]
![selezione_169](https://user-images.githubusercontent.com/1297620/33421701-3f993c64-d5b3-11e7-9be6-2022d1b1f9ff.png)

I developed this feature in a project based on Django. As you can see, for an adeguate level of security, we have a password length witha secure validation and, depending by the password-hash-format that the user choosed, the value will be auto hashed before being stored. It also permits to disable some password-hash-format like Cleartext-Password or other.

sorry for italian labels, that's gettext :)

**Comment by mimugmail** [comment]
As said here https://github.com/opnsense/plugins/issues/292#issuecomment-335101486 you are very welcomed to push your changes to master :)

**Comment by fichtner** [comment]
Overcome by events.
