### ISSUE TITLE
security/acme-client: TransIP DNS Provider, unable to configure key correctly

### ISSUE THREAD

**Issue by delgurth** [opnsense/plugins#2924]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X] The title contains the plugin to which this issue belongs

**Describe the bug**
When I try to use the TransIP DNS provider (building the plugin from source since it's only available in version 3.9 of the os-acme-client plugin and the develop version 3.8.1 is broken) the text field that contains the required key converts newlines into spaces which breaks the key. The key used is a PEM encoded private key.

**To Reproduce**
Steps to reproduce the behaviour:
1. clone git repository, build plugin and install it
2. Configure plugin, first create account, then challenge type then certificate
3. Click on issue or renew certificate
4. Go to logfiles
5. See errors "Unknown key file format" and "Can not get token"

**Relevant log files**
2022-04-03T13:49:15 | acme.sh | [Sun Apr 3 13:49:15 UTC 2022] Can not get token.
2022-04-03T13:49:15 | acme.sh | [Sun Apr 3 13:49:15 UTC 2022] _ret='0'
2022-04-03T13:49:15 | acme.sh | [Sun Apr 3 13:49:15 UTC 2022] _CURL='curl --silent --dump-header /var/etc/acme-client/home/http.header -L --trace-ascii /tmp/tmp.pmdipO6E '
2022-04-03T13:49:15 | acme.sh | [Sun Apr 3 13:49:15 UTC 2022] _post_url='https://api.transip.nl/v6/auth'
2022-04-03T13:49:15 | acme.sh | [Sun Apr 3 13:49:15 UTC 2022] POST
2022-04-03T13:49:15 | acme.sh | [Sun Apr 3 13:49:15 UTC 2022] Unknown key file format.

**Additional context**
For now I worked around this by providing the key via a separate file and configure that file in `/usr/local/share/examples/acme.sh/dnsapi/dns_transip.sh` (btw why is this file in the examples directory if we actually use it)

I was searching https://docs.opnsense.org/development/frontend/models_fieldtypes.html to see what field type would produce a textarea in stead of a input type=txt, but there seems to be none? Should I change it into base64 and then add instructions on how to change the key into a base64 encoded file? Any other suggestions on how to fix this? Also checked System -> Trust, but that requires you to have a certificate that goes with the private key. Is there a way to get the Textfield (or perhaps better UpdateOnlyTextField) to not touch the pasted newlines?

Tried to configure this using both safari and chrome.

**Environment**
OPNsense 22.1.4_1-amd64
FreeBSD 13.0-STABLE
OpenSSL 1.1.1n 15 Mar 2022

**Comment by MeganerdNL** [comment]
#2932 will solve this.

**Comment by MeganerdNL** [comment]
You can temporary workaround this (until the aformentioned pull request is merged and there is a new version released of the plugin) by manually editing the file (as root): **/usr/local/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml** and changing **text** in **textbox**.

**Change:**

```
    <field>
        <id>validation.dns_transip_key</id>
        <label>API Key</label>
        <type>text</type>
        <help>Requires the whole key file in a format that is compatible with TransIP.</help>
    </field>
```
**in**

```
    <field>
        <id>validation.dns_transip_key</id>
        <label>API Key</label>
        <type>textbox</type>
        <help>Requires the whole key file in a format that is compatible with TransIP.</help>
    </field>
```
