### ISSUE TITLE
security/acme-client: Uncaught Error: Call to a member function init() on null in .../OPNsense/AcmeClient/LeCertificate.php:634

### ISSUE THREAD

**Issue by taxilian** [opnsense/plugins#2930]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**

On three different routers running opnsense I'm getting this error frequently reported and often certificates don't seem to be re-issuing. I suspect it is probably related to some configuration issue we have rather than a full / overt bug in the excellent acme-client plugin, but I have been unable to effectively troubleshoot.

```
[30-Mar-2022 00:02:21 America/Denver] PHP Fatal error:  Uncaught Error: Call to a member function init() on null in /usr/local/opnsense/mvc/app/library/OPNsense/AcmeClient/LeCertificate.php:634
Stack trace:
#0 /usr/local/opnsense/mvc/app/library/OPNsense/AcmeClient/LeCertificate.php(404): OPNsense\AcmeClient\LeCertificate->runAutomations()
#1 /usr/local/opnsense/scripts/OPNsense/AcmeClient/lecert.php(165): OPNsense\AcmeClient\LeCertificate->issue()
#2 /usr/local/opnsense/scripts/OPNsense/AcmeClient/lecert.php(199): main()
#3 {main}
  thrown in /usr/local/opnsense/mvc/app/library/OPNsense/AcmeClient/LeCertificate.php on line 634
[01-Apr-2022 00:02:19 America/Denver] PHP Fatal error:  Uncaught Error: Call to a member function init() on null in /usr/local/opnsense/mvc/app/library/OPNsense/AcmeClient/LeCertificate.php:634
Stack trace:
#0 /usr/local/opnsense/mvc/app/library/OPNsense/AcmeClient/LeCertificate.php(404): OPNsense\AcmeClient\LeCertificate->runAutomations()
#1 /usr/local/opnsense/scripts/OPNsense/AcmeClient/lecert.php(165): OPNsense\AcmeClient\LeCertificate->issue()
#2 /usr/local/opnsense/scripts/OPNsense/AcmeClient/lecert.php(199): main()
#3 {main}
  thrown in /usr/local/opnsense/mvc/app/library/OPNsense/AcmeClient/LeCertificate.php on line 634
[01-Apr-2022 15:48:39 America/Denver] PHP Fatal error:  Uncaught Error: Call to a member function init() on null in /usr/local/opnsense/mvc/app/library/OPNsense/AcmeClient/LeCertificate.php:634
Stack trace:
#0 /usr/local/opnsense/mvc/app/library/OPNsense/AcmeClient/LeCertificate.php(404): OPNsense\AcmeClient\LeCertificate->runAutomations()
#1 /usr/local/opnsense/scripts/OPNsense/AcmeClient/lecert.php(170): OPNsense\AcmeClient\LeCertificate->issue()
#2 /usr/local/opnsense/scripts/OPNsense/AcmeClient/lecert.php(199): main()
#3 {main}
  thrown in /usr/local/opnsense/mvc/app/library/OPNsense/AcmeClient/LeCertificate.php on line 634
[06-Apr-2022 00:02:20 America/Denver] PHP Fatal error:  Uncaught Error: Call to a member function init() on null in /usr/local/opnsense/mvc/app/library/OPNsense/AcmeClient/LeCertificate.php:634
Stack trace:
#0 /usr/local/opnsense/mvc/app/library/OPNsense/AcmeClient/LeCertificate.php(404): OPNsense\AcmeClient\LeCertificate->runAutomations()
#1 /usr/local/opnsense/scripts/OPNsense/AcmeClient/lecert.php(165): OPNsense\AcmeClient\LeCertificate->issue()
#2 /usr/local/opnsense/scripts/OPNsense/AcmeClient/lecert.php(199): main()
#3 {main}
  thrown in /usr/local/opnsense/mvc/app/library/OPNsense/AcmeClient/LeCertificate.php on line 634
```

I did submit a crash report from the opnsense gui.

Any suggestions you may have would be appreciated, and hopefully this will help the next person who manages to hit the issue however we did =]

**To Reproduce**

Unfortunately I just don't know how to make it happen, only that it is happening frequently.

**Environment**

```
User-Agent Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36
FreeBSD 13.0-STABLE stable/22.1-n248063-ac40e064d3c SMP amd64
OPNsense 22.1.4_1 1aa77c16b
Plugins os-acme-client-3.8 os-api-backup-1.0_1 os-dmidecode-1.1_1 os-frr-1.27 os-google-cloud-sdk-1.0_1 os-haproxy-3.10 os-node_exporter-1.1 os-relayd-2.6 os-tftp-1.0 os-wireguard-1.10 
Time Wed, 06 Apr 2022 15:17:54 -0600
LibreSSL 3.3.6
PHP 7.4.28
```

**Comment by taxilian** [comment]
Possibly but not necessarily related: my certificates frequently still say "validation failed" for "last acme status" on the systems where this happens even when the certificate worked fine and is current

**Comment by justfly1111** [comment]
i have the same issue and also submitted the crash repports have you had any pprogress getting past this??

**Comment by justfly1111** [comment]
have same issue with failed certs also

**Comment by fraenki** [comment]
>   thrown in /usr/local/opnsense/mvc/app/library/OPNsense/AcmeClient/LeCertificate.php on line 634

The ACME plugin is trying to run an automation, but it fails to initialize it.
@taxilian maybe the automation was removed? Please try to edit the cert and just save again, this should clear possible traces of a removed automation. Besides that please provide more details about other automations that are currently configured and in-use.

**Comment by ikke-t** [comment]
I fixed this on mine by opening the cert for editing, and removed the haproxy restarting automation, and re-added it. It likely has been renamed a bit, and such old name wasn't found -> error. The functionality is available again there. I have no idea why someone has renamed the task, but good example how to break things :)

**Comment by rderensy** [comment]
It does seem like it's a problem with older automations. I needed to delete and re-add (and re-assign it to my certificate) my simple "Restart OPNsense Web UI" automation and it now works correctly.

**Comment by fraenki** [comment]
Maybe a data migration went wrong during a plugin upgrade sometime in the past, but that's just a wild guess. I cannot reproduce it and the information provided does not hint at any error in the code. I don't know what to do about it, so I'm closing this issue now.

Feel free to request someone to re-open this ticket if you think there is a bug that should be fixed.

**Comment by Sieboldianus** [comment]
I had the exact same issue, also coming from an old installation. I re-added the automations-restart for ACME. If you don't hear something, this must have also solved it for me! Thanks rderensy for reporting.
