### ISSUE TITLE
wireguard: unable to start when using Disable Routes options

### ISSUE THREAD

**Issue by dummys** [opnsense/plugins#2931]
- [X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X] The title contains the plugin to which this issue belongs

I'm using latest version of Opnsense on APUC2 hardware.

I want to use selective routing on different VPN provider therefore I need to check "Disable Routes Options". When looking inside the configuration of wg0.conf I get the following:

```
PostUp = route add 192.168.20.1 -iface %i
PostDown = route del 192.168.20.1 -iface %i
``` 

when wireguard-go is restarted, it said: `add host 192.168.20.1: gateway wg0 fib 0: route already in table`
If I delete the two entry, then wireguard start successfully.
when I restart the OPNsense, those entry are added again. Is it a bug or something is wrong in my configuration ?

**Comment by mimugmail** [comment]
Remove the gateway in instance config

**Comment by dummys** [comment]
yes but if I do this then the selective routing will stop working as stated in the opnsense guide: https://docs.opnsense.org/manual/how-tos/wireguard-selective-routing.html
Documentation is wrong ?

**Comment by dummys** [comment]
its ok I found my error. I was using 192.168.20
.1 as gateway in my local, which is wrong I had to use the ip-1 of the tunnel address. thanks
