### ISSUE TITLE
os-freeradius should allow colons in usernames and passwords

### ISSUE THREAD

**Issue by meyergru** [opnsense/plugins#2933]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
When using RADIUS-based authentication for Mikrotik and Cisco switches, the MAC format is XX:XX:XX.XX:XX:XX. Standard on Cisco would be to user both username and password from the original MAC, but it is not possible to use that in os-freeradius plugin.

**Describe the solution you'd like**
I would like to be able to use a colon in both username and password - Freeradius itself allows any UTF-8-character, so this should work right away.

**Describe alternatives you've considered**
Even better would be to support any characters that Freeradius allows for.

**Comment by antanasbruzas** [comment]
Would be nice to have this UI regex change included without wireguard stuff. Editing /usr/local/etc/raddb/users directly works with colons
