### ISSUE TITLE
os-frr ACL number for prefix-list 

### ISSUE THREAD

**Issue by LensHunnel** [opnsense/plugins#2939]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**

FRR supports using in prefix-list a **seq** number less than 4294967295 but the gui on opnsense limit us only to 10-99
Ex.: In FRR, we could write the line below:  
ip prefix-list BGP_INT seq 155 permit 10.0.0.0/10 
but in opnsense we got an error like following
![image](https://user-images.githubusercontent.com/6883486/163175755-609eb5d3-dd10-482a-a481-be3b5e90f27c.png)
 

**Describe the solution you'd like**

I would like to be authorized to add a number greater thant 99 in the input field in the `ui/quagga/bgp` which would add more than 90 prefix-lists usable. 

**Describe alternatives you've considered**

**Additional context**

The FRR's documentation related to this is available [here](https://docs.frrouting.org/en/latest/filter.html#ip-prefix-list)

**Comment by mimugmail** [comment]
But your example would also fit for a standard ACL?
What is the exact use case for this?

**Comment by LensHunnel** [comment]
Thanks for your answer. related to  FRR's documentation [here](https://docs.frrouting.org/en/latest/filter.html#ip-prefix-list) we can use  a seq number less than 4294967295 for a prefix-list not only a number between 10-99 which could be a problem if we want to use more than 90 prefix-lists. A best practice, we're using is to use a seq number by a unit of five in case we need to add a new prefix-list  between two existings which reduce the number of seq number of prefix-list usable.

**Comment by LensHunnel** [comment]
any news on that issue ?
