### ISSUE TITLE
security/acme-client: please add support for active24 DNS API

### ISSUE THREAD

**Issue by pcmediapear** [opnsense/plugins#2941]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
acme.sh already contains necessary provider so please just add it to GUI
https://github.com/acmesh-official/acme.sh/blob/master/dnsapi/dns_active24.sh

**Describe alternatives you've considered**
- we considered to change registrar but active24 is the only registrar with API support in our country
- we tested opnsense BIND API but it is not working (https://github.com/acmesh-official/acme.sh/issues/3735)

**Comment by fraenki** [comment]
This will be available in the upcoming release 3.12 of os-acme-client.
