### ISSUE TITLE
frr: Configure ipv6 next-hop on route-map

### ISSUE THREAD

**Issue by nsapa** [opnsense/plugins#2955]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X ] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X ] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X ] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
I cannot setup a route-map to set "ipv6 next-hop prefer-global".
I can put whatever I want in the "set" field, it will be ignored.

**Describe the solution you'd like**
On the form for new route-map on ui/quagga/bgp/index#routemaps, add a new drop-list called "IPv6 Next-hop preference" with two options:
- [peer-address](https://docs.frrouting.org/en/stable-7.5/routemap.html?highlight=prefer-global#clicmd-setipv6next-hoppeer-address): «Set the BGP nexthop address to the address of the peer. For an incoming route-map this means the ipv6 address of our peer is used. For an outgoing route-map this means the ip address of our self is used to establish the peering with our neighbor.»
- [prefer-global](https://docs.frrouting.org/en/stable-7.5/routemap.html?highlight=prefer-global#clicmd-setipv6next-hopprefer-global): « For Incoming and Import Route-maps if we receive a v6 global and v6 LL address for the route, then prefer to use the global address as the nexthop.»

**Describe alternatives you've considered**
Fix the free-form set field to accept "ipv6 next-hop .." command.

**Additional context**
This is a workaround for an issue with missing link-local ipv6 on wireguard interface.

**Comment by mimugmail** [comment]
How does your `/usr/local/etc/frr/bgpd.conf` looks like when you inser `ipv6 next-hop prefer-global` in set field?

**Comment by nsapa** [comment]
When I insert `ipv6 next-hop prefer-global` in the set field, bgpd.conf look like that:

```
!
!
route-map Force_Global_IPv6 permit 10
!
!
```

**Comment by davidheijkamp** [comment]
We see the exact same behavior on OPNsense 22.1.6 with FRR plugin 1.27. When we edit the config manually in `/usr/local/etc/frr/bgpd.conf` and restart FRR with `/usr/local/etc/rc.d/frr restart` the config is picked up by FRR and is functional (our setting is `set ip next-hop <ipv4>`). The set command we've configured in the webinterface is included in the XML config backup:

```xml
<routemap uuid="fd5e2f9d-fabe-4391-a964-fbf581bc8c0c">
            <enabled>1</enabled>
            <description/>
            <name>next-hop-carp-inside</name>
            <action>permit</action>
            <id>20</id>
            <match/>
            <match2/>
            <match3/>
            <set>ip next-hop ...</set>
</routemap>
```
