### ISSUE TITLE
net-mgmt: collectd: make prefix and postfix in collectd graphite plugin editable

### ISSUE THREAD

**Issue by knxuf** [opnsense/plugins#297]
please make the prefix and postfix in the graphite plugin editable or remove the defaults.

If you enter host.domain.com as hostname the prefix and postfix make the name 
`collectdhost.domain.comcollectd.`

alternative make just the prefix something like collectd_

**Comment by knxuf** [comment]
didn't saw related pull request https://github.com/opnsense/plugins/pull/296
but that still adds the postfix as mentioned above

**Comment by fichtner** [comment]
Fixed already.
