### ISSUE TITLE
ntopng: DNS-Mode

### ISSUE THREAD

**Issue by 150d** [opnsense/plugins#2985]
OPNsense 22.1.7_1-amd64
Plugin os-ntopng-enterprise 5.3.220514

In the GUI under Services/ntopng Enterprise/settings, "DNS-Mode" is always set to "none". I can choose another value from the dropdown, but it is not saved - after pressing the "Save" button, on subsequent visits to the dialog it has always returned to "none".

Is this a bug or am I doing something wrong?

Note:
In System/Firmware/Plugins, the plugin is listed as "os-ntopng-enterprise (misconfigured)". Other plugins are listed as "... (installed)". Can this have to do something with it?

**Comment by fichtner** [comment]
We do not maintain os-ntopng-enterprise and ntop isn’t a supporter of OPNsense so we don’t have any ground to talk about this.
