### ISSUE TITLE
dns/ddclient: Dashboard widget

### ISSUE THREAD

**Issue by plinss** [opnsense/plugins#2988]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] When the request is meant for an existing plugin, I've added its name to the title.

**Describe the solution you'd like**
The legacy DynDNS client has a dashboard widget that shows the status of the configured services and the cached IP address. 

This seems to be missing with ddclient. 

I found it useful for quick confirmation that IP addresses were up to date and a replacement would be appreciated.

**Comment by Nostradamus1973** [comment]
I wouldn't hold your  breath on this one, people have been asking for a widget since January 2022; supposedly the next community release should have it, however I'd be surprised if it did.

**Comment by fichtner** [comment]
Well, nobody stepped up to this yet. I'd be very much surprised as well. ;)
