### ISSUE TITLE
zabbix-agent2 support

### ISSUE THREAD

**Issue by colttt** [opnsense/plugins#2996]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
It would be really nice if we can add the zabbix-agent2, because it has a lot of benefits. eg native SMART-monitoring etc.

**Describe the solution you'd like**
a zabbix-agent2 in opnsense

**Additional context**
https://www.zabbix.com/documentation/current/de/manual/concepts/agent2
https://www.zabbix.com/documentation/current/de/manual/appendix/agent_comparison
https://www.zabbix.com/documentation/current/en/manual/config/items/itemtypes/zabbix_agent/zabbix_agent2#s.m.a.r.t.

**Comment by colttt** [comment]
so for me, it looks like I can copy/paste the os-zabbix-agent thing, I think the more difficult thing is to compile the zabbix-agent2.

Sorry for that noob question, but how is the zabbix-agent himself installed?! via pkg add? If so, what is, when it is not available?

**Comment by mimugmail** [comment]
If you want we can setup a Teams call and do it together with a recording to other can learn too.

**Comment by colttt** [comment]
Hello and sorry for the late response, I'm still interested in this. 
So what do I need for this? And hopefully, you're fine with my bad english ;-)

**Comment by colttt** [comment]
at the moment it's not possible to compile: https://support.zabbix.com/browse/ZBX-21633
