### ISSUE TITLE
security/acme-client:  Please add support for Mythic_Beasts DNS API (V2)

### ISSUE THREAD

**Issue by retep** [opnsense/plugins#2998]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [✔] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [✔] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [✔] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
Mythic Beasts DNS challenge is missing in the GUI of the ACME client, but is supported by the underlying code. It's quite simple with an API key and secret, similar to many others in the list.

See: https://github.com/acmesh-official/acme.sh/wiki/dnsapi#139-use-mythic-beastscom-dns-api
       https://www.mythic-beasts.com/support/api/dnsv2
       https://www.mythic-beasts.com/support/api/auth

**Describe the solution you'd like**
Please add Mythic Beasts in the DNS challenge section. Thanks!

**Describe alternatives you've considered**
Not Applicable

**Additional context**
Not Applicable

**Comment by jan-win1993** [comment]
This feature will be available in the upcoming release 3.13 of os-acme-client.

**Comment by retep** [comment]
> This feature will be available in the upcoming release 3.13 of os-acme-client.

Thank you @jan-win1993 & @fraenki and anyone else who contributed. It's very much appreciated.
