### ISSUE TITLE
`wireguard-go`: service shown as stopped even when running

### ISSUE THREAD

**Issue by marc0777** [opnsense/plugins#2999]
On the Dashboard with the services widget and on System->Diagnostics->Services the `wireguard-go` service is always shown as stopped, even when `wireguard` is running correctly:

![image](https://user-images.githubusercontent.com/7026812/172334512-53e3c8b3-346e-4038-8a8d-2c521be48f18.png)

Executing `service wireguard status` correctly outputs all the wireguard interfaces and peers:

```
root@OPNsense:~ # service wireguard status
interface: wg0
  [...]
interface: wg1
  [...]
interface: wg2
  [...]
```

I'm able to connect to wireguard and all locals/peers are working correctly. However, I'm not able to stop or restart the service from the GUI. 

I'm running OPNsense 22.1.8 on Proxmox 7.2.4, but I've been noticing this issue for a while. 

Even if I haven't been able to verify this yet, I think it stopped showing the correct status when I added a second local peer. I'm running also another OPNSense instance with the same environment (22.1.8 on Proxmox 7.2.4) but only one peer and the service is reporting it's status correctly on the GUI.

**Comment by fichtner** [comment]
are you using wireguard-kmod?

**Comment by marc0777** [comment]
Yes, those are the packages that I currently have installed:

![image](https://user-images.githubusercontent.com/7026812/172338452-b70ac8e8-af89-415f-9082-dc21d69963bc.png)

**Comment by fichtner** [comment]
Ok, the plugin only handles wireguard-go, which isn't used if you install wireguard-kmod. It's on the wish list to support wireguard-kmod via a separate plugin....

**Comment by marc0777** [comment]
Ok, so this is the expected behaviour until there is a dedicated plugin for `wireguard-kmod`. Thanks for the information!
