### ISSUE TITLE
vnstat

### ISSUE THREAD

**Issue by matheusber** [opnsense/plugins#3]
Hi,

when there will be the vnstat plugin on opnsense ? If there is anything I can help to make it work, please tell me. I am none from Forum !

thanks,

**Comment by fichtner** [comment]
What to you expect from vnstat on a plugin/GUI level? You probably know you can install vnstat from the console, yes? :)

**Comment by matheusber** [comment]
Hi,

I know that yes, I just can't figure out how to make it show me data using http. I can do that on regular FreeBSD, but as opnsense has its own organization, I miss the way to do it on a maintainable way. What I expect is pretty much what pfsense shows for it.

If there is any kind of template to this, I can try by mylself and send :)

thanks

**Comment by AdSchellevis** [comment]
@matheusber we have some documentation available about our architecture, you can find it here:
https://wiki.opnsense.org/index.php/Developers

Unfortunately we haven't had time to build a "hello world" application yet to show the full architecture, but something like that will be there in the future.

To get you started, there are a couple of basic rules to follow when developing OPNsense components.

*   command (shell) type actions, which very often require root access, should be registered into configd templates and started via configd commands. 
-  templates are registered in /usr/local/opnsense/service/conf/actions.d/ (don't forget to restart using "service configd restart" )

* When needing configuration templates for your daemon or tool, you should build a "Jinja" template for it, which should also be registered into configd at the following location.
 /usr/local/opnsense/service/templates/
(no restart needed)

The technology used for templates is "Jinja2" http://jinja.pocoo.org/docs/dev/ and automatically receives the config.xml data to do it's work on.
A sample can be found here: /usr/local/opnsense/service/templates/OPNsense/Sample/
 
*  The current development version of OPNsense supports pluggable ACL's and menu's, for an example of how to implement, look in the model of IDS (/usr/local/opnsense/mvc/app/models/OPNsense/IDS/)

* All new style components should always separate logic from presentation and all actions should be available from the API, which will be accessible from other tools as of version 16.1. 
The framework automatically handles routing, more information can be found here: https://wiki.opnsense.org/index.php/Develop:Frontend/Routing

* When building applications, you can prefix your "Vendor" name into most parts. Just replace OPNsense for your chosen name. The routing will automatically pick this up for the frontend components. The backend templates should be started using the full scope. 
 
As soon as we find the time to create the "hello world" application, it will be on the wiki as well.

**Comment by fichtner** [comment]
This is a bit rusty, superseded by the Insight/Netflow reporting. Closing this for now until somebody lets us know they want to work on it. :)

**Comment by fichtner** [comment]
I'm closing this now due to inactivity.
