### ISSUE TITLE
sysutils/nut (OS-NUT): add support for the BCMXCP Serial driver

### ISSUE THREAD

**Issue by MrMrRubic** [opnsense/plugins#3001]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
I want to connect my HP R3000XR USP to OPNSense/NUT using a Serial Bus, and only the BCMXCP driver is supported. I have tried with the existsing drivers.

**Describe the solution you'd like**
I'd like for the BCMXCP driver to be added to 'UPS Type' drop-down menu.

**Describe alternatives you've considered**
I don't think there is any alternatives to this.

**Additional context**
https://networkupstools.org/docs/man/bcmxcp.html
![image](https://user-images.githubusercontent.com/48393008/172469026-827aff20-8721-47e7-b858-f7dd85517a49.png)

**Comment by mimugmail** [comment]
I try to add it after Holidays in 2 weeks

**Comment by MrMrRubic** [comment]
@mimugmail Hello, how is this going? Would it also be possible to add suport for the netserver MODE?
