### ISSUE TITLE
security/acme-client: highest port number is limited to 49151 in SSH/SFTP automation

### ISSUE THREAD

**Issue by deahbe** [opnsense/plugins#3005]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [ ] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [ ] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [ ] The title contains the plugin to which this issue belongs

**Describe the bug**
I want to configure an automation that run a remote SSH command. The max. port I can configure for the remote host is 49151. But I need a higher one.

**Environment**
Software version used and hardware type if relevant.
e.g.:

OPNsense 22.1.8_1 (amd64, OpenSSL).
Intel(R) Xeon(R) CPU E5645 @ 2.40GHz (4 cores, 4 threads)

**Comment by fraenki** [comment]
@jkellerer Do you happen to know why the port number is limited to 49151? Is this an arbitrary limit or is there a valid reason? Thanks :)

**Comment by fraenki** [comment]
@jkellerer, thanks for the quick response! Much appreciated.

This restriction will be removed in the upcoming release 3.12 of os-acme-client.
