### ISSUE TITLE
sysutils/monit: how to add file content monitoring?

### ISSUE THREAD

**Issue by Stephanowicz** [opnsense/plugins#301]
Hi,

monit has an option to scan file contents:
[https://mmonit.com/monit/documentation/monit.html#FILE-CONTENT-TEST](https://mmonit.com/monit/documentation/monit.html#FILE-CONTENT-TEST)

Is there a way to achieve this with the current posibilities in 'service settings'?

Cheers, Stephan

**Comment by Stephanowicz** [comment]
Ok, I think I made it...

One needs to create a new service test with a fix condition like:
`content = "Registry 'virus_scan::engines' does not exist" for 3 cycles`

One thing I think would be worth to optimize:
to have a 'general' test for file contents, the condition itself should be inserted in the service settings

Cheers, Stephan

**Comment by fichtner** [comment]
Please either leave open and edit title or open new ticket so @fbrendel can pick it up 😊

**Comment by Stephanowicz** [comment]
:) 
Well, closed it as it is 'solved'

An 'howto' concerning this would be helpful 
the idea with the 'general test' is just an idea - meanwhile I think it's the basic concept I've problems with :D 
Nevertheless I'm thankful that it's working...

**Comment by fbrendel** [comment]
> An 'howto' concerning this would be helpful

Yes and we have one at the [OPNsense Forum](https://forum.opnsense.org/index.php?topic=5303.0).
And basically, what it says is that everything between IF and THEN is a condition. And the file content test condition contains the key word "CONTENT".
May I ask you to add this as an example to the howto, please :smiley:

**Comment by Stephanowicz** [comment]
Ok, done :D

**Comment by fbrendel** [comment]
Thanks! :+1:
