### ISSUE TITLE
dns/ddclient: no-ip broken

### ISSUE THREAD

**Issue by theepan007** [opnsense/plugins#3017]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
IP address changes to WAN interface are not detected and sent to No-IP service, and ddclient logs the following messages:

```
ddclient[43123]	60634 - [meta sequenceId="2"] WARNING: unable to determine IP address	
ddclient[43123]	59557 - [meta sequenceId="1"] WARNING: found neither ipv4 nor ipv6 address
```
Doesn't matter what combination of Check ip method and Interface to monitor I use:

Check ip method: Interface, Interface to monitor: WAN
Check ip method: noip-ipv4, Interface to monitor: WAN
Check ip method: noip-ipv4, Interface to monitor: none

I prefer the Interface/WAN method as this keeps detection local and only sends data to no-ip when there are changes.

The generated ddclient.conf is:

```
daemon=300
syslog=yes                  # log update msgs to syslog
pid=/var/run/ddclient.pid   # record PID in file.
verbose=yes
ssl=yes

use=if, if=vtnet1, \
protocol=noip, \
login=xxxx, \
password=yyyy \
my.no-ip-name.net
```

I started using ddclient late last year, and this has "always" been an issue for me. 

**To Reproduce**
1. Add a Noip service
2. Choose Check IP method = Interface
3. Choose Interface to monitor = WAN

As mentioned I have also tried using Check IP method = noip-ipv4, same result.

**Expected behavior**
The public IP is correctly detected, change sent to No-IP service if update is needed.

**Relevant log files**
```
ddclient[43123]	60634 - [meta sequenceId="2"] WARNING: unable to determine IP address	
ddclient[43123]	59557 - [meta sequenceId="1"] WARNING: found neither ipv4 nor ipv6 address
```

**Workaround**
Modifying the ddclient.conf as follows:

From:
```
use=if, if=vtnet1, \
```
To:
```
use=if, if=vtnet1
```
And restarting the service - but this only persists until next reboot or update.

**Environment**
OPNsense 22.1.9 (amd64, OpenSSL)
Proxmox VM
Host CPU pass-through: Intel(R) Core(TM) i3-8109U CPU @ 3.00GHz (2 cores, 2 threads)
Network: VirtIO

**Comment by ilikenwf** [comment]
See the workaround I'm using in the above - I just modified the command called to use curl and icanhazip.com - checkip is the script that is failing for some reason.

**Comment by maxkratz** [comment]
I was able to successfully update IPs for no-ip hostnames by configuring the service type 'custom'.
![Screenshot_2022-08-04_19-05-34](https://user-images.githubusercontent.com/20956405/182909629-5e6a1e6a-f37e-43ad-b8e9-4580e9e63723.png)

**Comment by ilikenwf** [comment]
Interesting. I may have to try it.

**Comment by theepan007** [comment]
@maxkratz, nicely done, thank you. 
Your workaround solved my issue as well - now my ddclient can detect the WAN IP address and update if needed.

**Comment by christian-schulze** [comment]
I had this same issue, the problem was the python script `/usr/local/opnsense/scripts/ddclient/checkip` always returning `None`. This script calls the various services via `curl`, which is hard coded to timeout after 10 seconds. Updating the script to timeout after 15 seconds fixed the issue for me...

**Comment by fichtner** [comment]
What does 10 to 15 seconds fundamentally change about this? This is something about your setup, maybe DNS timeout.

**Comment by christian-schulze** [comment]
@fichtner its absolutely a timeout:

**Comment by fichtner** [comment]
I don’t think this is a technical problem we can solve by fiddling with a timeout. 10 seconds is more than enough for a healthy connection.

**Comment by theepan007** [comment]
The timeout wasn't my issue either, since I was using interface detection method.

So far the only thing that worked for me is described in the workaround section of the initial post, as well as changing 'Service' to 'Custom' as described by @maxkratz. The latter being what I ended up doing, since it survives a reinstall/reboot.

**Comment by christian-schulze** [comment]
Fair enough. In my particular instance its a timeout issue, so adding to the collective knowledge in case it helps someone else.

**Comment by wholtii** [comment]
> I was able to successfully update IPs for no-ip hostnames by configuring the service type 'custom'. ![Screenshot_2022-08-04_19-05-34](https://user-images.githubusercontent.com/20956405/182909629-5e6a1e6a-f37e-43ad-b8e9-4580e9e63723.png)

Worked for me!! Thanks

**Comment by Keldandorin** [comment]
same here solved by using custom config and interface as source for Ip opnsense 22.1.8 installed

**Comment by maxkratz** [comment]
> I have tried many different configurations, and cannot get no-ip to work.

Have you tried [this way]? For my setup, it worked.

**Comment by francismiles1** [comment]
> > I have tried many different configurations, and cannot get no-ip to work.
> 
> Have you tried [this way](https://github.com/opnsense/plugins/issues/3017#issuecomment-1205534104)? For my setup, it worked.

Yup. Still not happy.. Its a shame really, as duckdns works well, but my organisation block it on my work laptop unfortunately, so need no-ip for  wireguard access.

**Comment by maxkratz** [comment]
> Yup. Still not happy..

What exactly is the problem? Could you elaborate a bit more? The configuration above works fine for me since I posted it here.

**Comment by francismiles1** [comment]
Hmm, you have me second-guessing myself now. am 'actually' now not sure the service is 'Not' working.. The logs however tell me nothing of any relevance, and for sure, the updated IP address etc. is not being populated etc., but I think this is a known issue.
Will fiddle further; The No-Ip web interface does not help much either as it gives no real indication of any firm IP updates

![3](https://github.com/opnsense/plugins/assets/28559506/1c519b21-5177-42f1-a89f-53d95ea911ea)
![2](https://github.com/opnsense/plugins/assets/28559506/41bb513b-959f-48d1-9071-859995615f99)
![1](https://github.com/opnsense/plugins/assets/28559506/bf9c9933-16cb-44f2-b9eb-da7dbafecb78)
