### ISSUE TITLE
net-mgmt/collectd: generic configuration

### ISSUE THREAD

**Issue by fprina** [opnsense/plugins#302]
Hi all

Related to my [Forum request](https://forum.opnsense.org/index.php?topic=6072.0)
I've cerate "a patch" to append a generic configuration to the collectd.conf 

But at the moment I'm not sure how to push this "patch" to you.... can you please suggest me the right way 

Thanks

**Comment by mimugmail** [comment]
Do you want to do it on your own or shall I add this feature? 
If you want to do it yourself fork the plugins, add your changes to your copy and create a pull request. 

You have to add a checkbox to enable/disable openvpn module in controller forms and model and add it to the template.

**Comment by fprina** [comment]
The collectd OpenVPN plugin have various options so at the momnet I've added a simple  textbox (marked as advanced, so normaly hidden) who append the value to the collectd.conf template 
... exaclty as the advanced textbox in the "VPN: OpenVPN: Servers"

so I've  touched:
/usr/local/opnsense/mvc/app/controllers/OPNsense/Collectd/forms/general.xml
/usr/local/opnsense/mvc/app/models/OPNsense/Collectd/General.xml
/usr/local/opnsense/service/templates/OPNsense/Collectd/collectd.conf

**Comment by mimugmail** [comment]
Great! Then just push the changes via a pull request 👍

**Comment by mimugmail** [comment]
Ah, sorry, a textbox or a checkbox? I'd prefer a checkbox for en-/disabling and for every value an input field (or only checkbox and load defaults in template)

**Comment by fprina** [comment]
As commented in the pull request I've added a checkbox to enabel/disable the plugin and other fields for pluging  specific paramiters
The generic textbox  was removed

**Comment by mimugmail** [comment]
You need of clause for every option, fix typos and pleased "OpenVPN" for
help and label

Am 02.10.2017 8:14 vorm. schrieb "fprina" <notifications@github.com>:

**Comment by fprina** [comment]
* Clause for every option
* Replaced OpenVPN in label and help
* Set options defaults according to man page
* A bit more descriptive help
* Removed typo (I hope)

**Comment by mimugmail** [comment]
Great! So, your decision to make a default for status file, but if you don't you should add a default path to the help so others don't have to check man page or whatever. 

Also I would add a help to the enable button with a small doc what have to be done to openvpn advanced field to get this done.

**Comment by fprina** [comment]
Status file do not have a real default but  manpage talk about  /var/run/openvpn-status so we can use this path as default

**Comment by mimugmail** [comment]
It should be the value you set in OpenVPN advanced settings. If its like in your forum post set it this way and include this path in the help of the checkbox (enable) that the user have to also set this in OpenVPN settings

**Comment by fprina** [comment]
Increased the verbosity of the help

**Comment by fichtner** [comment]
Timeout.
