### ISSUE TITLE
os-ddclient: (Dynamic DNS) - Check ip method: dyndns - No address found

### ISSUE THREAD

**Issue by MBfromOK** [opnsense/plugins#3021]
1. The current plugin version:
        -  os-ddclient: 1.7_1 patch: 946583e
        - os-dyndns: 1.27_3
   
   2. No issues found in:
       - OPNsense 22.1.7: Dynamic DNS (with dyndns)
       - OPNsense 22.1.9_1: Dynamic DNS (legacy) (with dyndns) - https://opnsense/services_dyndns.php

   3. The exact URL of the GUI page involved (if any)
       - Services: https://opnsense/ui/dyndns/
       - Logs: https://opnsense/ui/diagnostics/log/core/ddclient

   4. A list of steps to replicate the bug
       - Update from OPNsense 22.1.7 to 22.1.9_1
       - Update plugin versions to current

   5. The current OPNsense version:
       - OPNsense 22.1.9_1-amd64
       - FreeBSD 13.0-STABLE
       - OpenSSL 1.1.1o 3 May 2022

Dynamic DNS: Debug Log file shows more than 20 of these messages:
```
Date: 2022-06-29T10:38:38-05:00 
Severity: Notice
Process: ddclient[57371]
Line: 29855 - [meta sequenceId="1"] WARNING: found neither ipv4 nor ipv6 address
```

with check ip method: dyndns

_Originally posted by @MBfromOK in https://github.com/opnsense/plugins/issues/3019#issuecomment-1170142547_

**Comment by fichtner** [comment]
For me dyndns check doesn’t work with TLS. The connection seems to be accepted but not served on the other end.

**Comment by MBfromOK** [comment]
Sorry, I clicked the link to mention my comment in a new issue, the window
that came up didn't include boilerplate / template text.

Would it be acceptable to edit my original message and add the following
details (from the Contributing page)?

   1. The current plugin version where the bug first appeared
   2. Add the name of the plugin to the front of the subject
   3. The last plugin version where the bug did not exist
   4. The exact URL of the GUI page involved (if any)
   5. A list of steps to replicate the bug
   6. The current OPNsense version used

**Comment by MBfromOK** [comment]
I am (as far as I can tell) using dyndns check with the Dynamic DNS
(legacy) plugin without issue... Did something change?

**Comment by fichtner** [comment]
legacy plugin only does http to checkip.dyndns.org, in ddclient you can choose but apparently https is not an option for them to it comes up empty (timeout)

**Comment by fichtner** [comment]
so I switched to freedns check service and that works for https too. we maybe have to switch the default

you can fill out the missing info here in this ticket, it would be useful

**Comment by MBfromOK** [comment]
> so I switched to freedns check service and that works for https too. we maybe have to switch the default
> 
> you can fill out the missing info here in this ticket, it would be useful

Thanks for your reply, perhaps bring the force ssl to the above the "check ip method" and then populate the "check ip method" dropdown based on that setting (so that non-https options aren't offered when it is off)

**Comment by fichtner** [comment]
Force option is already convoluted for ddclient internal reasons as it looks per service when in fact it can only be global.

micromanaging the check urls is also tedious. Maybe even better would be to fail and fall back to http and log the incident as it can relate to security policies?

**Comment by MBfromOK** [comment]
Ugh, round and round we go, now seeing a bunch of messages in the log that seems to indicate IP has been attained but CloudFlare doesn't like the headers:
```
44803 - [meta sequenceId="40"] RECEIVE: {"success":false,"errors":[{"code":6003,"message":"Invalid request headers","error_chain":[{"code":6103,"message":"Invalid format for X-Auth-Key header"}]}],"messages":[],"result":null}
```
Which I am guessing is a separate issue to be posted related to CloudFlare support?

**Comment by MBfromOK** [comment]
> Maybe even better would be to fail and fall back to http and log the incident as it can relate to security policies?

That would work and would advise that a configuration change is likely needed.  Additionally, at the least it should be reported as a warning, so far everything seems to be relegated to notice level (even when it fails).

**Comment by awyork** [comment]
I had this problem when I choose "dyndns" for the "check ip method" instead of "interface".  I am using dynu for my ddns.
