### ISSUE TITLE
Add more secure algorithms to RFC2136 client

### ISSUE THREAD

**Issue by Ketanest** [opnsense/plugins#3028]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
You are not able to set another algorithm key than with MD5.

**Describe the solution you'd like**
Add the ability to use also other algorithms like hmac-sha1, hmac-sha224, hmac-sha256, hmac-sha384 and hmac-sha512.

**Describe alternatives you've considered**
There are no alternatives.

**Additional context**
There has been an issue #1664 for this but that has been closed due to inactivity/incompleteness. The actual open issue is #2203 and av-commits seems to have a solution but the merge into the main branch is stuck since august 2021. It it assigned to fichtner since oct 2021. It also says "This branch has conflicts that must be resolved".

**Comment by mcwanek** [comment]
I have ported the changes that av-commits made (mentioned above) up into the current master branch. Seems to be working ok with my limited local testing.

Changes can be seen here: https://github.com/opnsense/plugins/compare/master...mcwanek:opnsense-plugins:master

I can submit a pull request if there is any interest.
