### ISSUE TITLE
WireGuard - Instance variable is AutoNumberField

### ISSUE THREAD

**Issue by BCurrell** [opnsense/plugins#3031]
**Important notices**
Our forum is located at https://forum.opnsense.org , please consider joining discussions there in stead of using GitHub for these matters.

Before you ask a new question, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.

---

Asking this as a question so I can tag a potential pull request to this issue.

Is there a reason that the WireGuard Instance variable is an AutoNumberField, rather than an Integer field? It's not at all important, but I'd like the ability to manually set my instance ID without having to edit the config.xml. If there's no particular reason, I'll happily put the PR in to change that.

**Comment by mimugmail** [comment]
The reason is that it automatically counts the instance number up with integrated protection that unexperienced users assign the same number twice :)

**Comment by fichtner** [comment]
Although validation could be added for manual input it seems inconvenient and to little benefit for manual instance ID assignment.

**Comment by BCurrell** [comment]
Thought that may be the case. Thanks for the info
