### ISSUE TITLE
FreeRadius gives pap error when libressl 

### ISSUE THREAD

**Issue by MartenVijnNaturalis** [opnsense/plugins#3036]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

Freeradius won't start when enabled when on libressl flavour

1. update to 22.1.10
2. Set LibreSSL https:*/ui/core/firmware/settings in Flavors
3. Click on 'update' and openssl removed en libressl installed
4.  install FreeRadius, enable it and try to start it in the gui....

/usr/local/etc/rc.d/radiusd debug ends with:
/usr/local/etc/raddb/mods-enabled/pap[13]: Failed to link to module 'rlm_pap': Cannot open "/usr/local/lib/freeradius-3*/rlm_pap.so"

in /usr/local/etc/raddb/radiusd.conf I canged
Code: [[Select]](javascript:void(0);)

#libdir = /usr/local/lib/freeradius-3*
libdir = /usr/local/lib/freeradius-3.0.25

/usr/local/etc/rc.d/radiusd debug
/usr/local/etc/raddb/mods-enabled/pap[13]:  \
Failed to link to module 'rlm_pap': /usr/local/lib/freeradius-3.0.25/rlm_pap.so: Undefined symbol "EVP_sha3_224" 

change back to Open SSL, and now Radius starts...
also in post : https://forum.opnsense.org/index.php?topic=27557.msg141595#msg141595

Kind regards Marten

**Comment by fichtner** [comment]
@MartenVijnNaturalis LibreSSL is no longer actively supported and will be removed when 23.1 comes out.
