### ISSUE TITLE
os-ddclient: Add support again to Azure DNS

### ISSUE THREAD

**Issue by hauserkristof** [opnsense/plugins#3037]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
In version
OPNsense 22.1.10-amd64
with plugin version: 1.8

Also tested on:
|Key | Val |
|--|--|
| Type | opnsense-business |  
| Version | 22.4.2 |  
| Architecture | amd64 |  
| Flavour | OpenSSL |  
| Commit | f350d31bc

GUI link: /ui/dyndns/

We do not have to same functionality for ddclient as the ddclient legacy, to be exact, we can not set up Azure DNS in the new version.

Legacy version:
<img width="691" alt="Képernyőfotó 2022-07-13 - 20 39 38" src="https://user-images.githubusercontent.com/1770194/178807319-bb9bf34d-30f0-46fc-ae78-e2731e99b785.png">

New version:
<img width="991" alt="Képernyőfotó 2022-07-13 - 20 39 57" src="https://user-images.githubusercontent.com/1770194/178807349-33fddd96-21d3-45e9-b685-3556613c82c1.png">

**Describe the solution you'd like**
The same functionality as the legacy ddclient would be perfect.

**Describe alternatives you've considered**
I did not find any easy solution yet.

**Additional context**
There is another open [issue](https://github.com/opnsense/plugins/issues/2844) , but due to bad formatting the bot tagged this as low priority and absolutely no answer was given by the team since February 17. #2844 [](url)

**Comment by AdSchellevis** [comment]
It doesn't appear to be supported by ddclient (https://github.com/ddclient/ddclient/issues/107), so someone interested in this should probably open a pull-request there first.

**Comment by hauserkristof** [comment]
Why did opnsense change for this module if it is a step back from the legacy one?

In business use cases the legacy ddns was really useful!

**Comment by fichtner** [comment]
I would like to point out you are not a business user...

**Comment by fichtner** [comment]
@hauserkristof if you want to complain to me about you not giving more context than "OPNsense 22.1.10-amd64" in the original report feel free to do so.

**Comment by hauserkristof** [comment]
> @hauserkristof if you want to complain to me about you not giving more context than "OPNsense 22.1.10-amd64" in the original report feel free to do so.

true that, sorry, I've modified the description. Could you modify the label on the issue?

Also, can you please tell why the team decided to move from the previous extension?

**Comment by mimugmail** [comment]
Hetzner Support might also find it's way in the new relase. 
Enclosed a PR (also by an OPN user) to see how add support to upstream:
https://github.com/ddclient/ddclient/pull/406/files

**Comment by hauserkristof** [comment]
> Changed the labels accordingly. The old dyndns plugin was deprecated over code quality issues and near-impossible maintenance for no visible business case (this is not against you in particular, it just is what we have seen and it matches with the reality of dyndns software being overly bad as a whole because it is mostly for home users written by other home users).
> 
> We've had a lot of work done to the old plugin code base over the years but it keeps breaking for integrated services as the original project is already dead since 2005 and there is no stringent structure to embed new services as all gets to be glued into one single file...
> 
> https://github.com/opnsense/plugins/blob/abf01bff99e019b31792cf3489372f07e0c33653/dns/dyndns/src/etc/inc/plugins.inc.d/dyndns/phpDynDNS.inc#L67-L70
> 
> That being said we went looking for a maintained upstream project and to our knowledge only ddclient and inadyn exist. ddclient had the benefit of it being in our packages provided for a long time without a plugin so the decision was made to build a plugin for it seeing that they do have recent activity in their GitHub home nowadays and are almost ready for a new release (there are two prereleases available of the latest version but we want to hold off that to not deliver underperforming updates).
> 
> The new plugin supports MVC/API access and is easier to extend within the scope of provided functionality of ddclient of course. For possible support / how to's on ddclient integration the readme/docs of ddclient should at least be skimmed to see if it can work with any particular service now or in the future (new code added but not released). If not, a feature request on their end would be the most sensible way to see if support for a particular hoster can be added or not.
> 
> https://github.com/ddclient/ddclient#supported-services
> 
> Cheers, Franco

Thank you for the explanation @fichtner ! It makes complete sense, I wrote a comment to a preexisting issue on their side, I hope they are going to implement Azure dyndns.

I have also commented on another issue in opnsense ddclient plugin #2899

I hope when the final release comes out of this plugin and the legacy would be removed from 22.7 these features would be available. I really like working with opnsense, so keep the good work up please :)

**Comment by jortfal** [comment]
Bad News!!!

They will not implement Azure DNS support in `ddclient`.

👎🏼 https://github.com/ddclient/ddclient/issues/107#issuecomment-1189003343

**Comment by fichtner** [comment]
@jortfal can you please be more specific in that neither you nor anybody else will apparently work on this? Thanks.

**Comment by jortfal** [comment]
Yes, of course. What I wanted to share is that by ddclient developers are not going to implement Azure DNS support. So if someone else doesn't do it we are going to be left without this option in the new release of OPNSense.

**Comment by fichtner** [comment]
Not exactly. First of all the dyndns plugin will not be deleted and secondly the dyndns plugin will still available for a while on on 22.7 for multiple reasons.


Cheers,
Franco

**Comment by AdSchellevis** [comment]
I've wrote an alternative for ddclient and added it as an additional "backend" selection (general settings) in https://github.com/opnsense/plugins/commit/ef91a6b4f9feef7b412ab4a98f14f452d0c187ac. Although I'm not planning to build implementations for all different vendors it seemed like a good idea to add dyndns as a simple example and azure as a complexe one.

**Comment by hauserkristof** [comment]
Thank you @AdSchellevis !

Is there any method to test it? Can I somehow add the main repo as an alpha test to an OPN system?

I assume this change would not be included in the 23.1 version, because of too short notice. When can it be released to production?

**Comment by AdSchellevis** [comment]
@hauserkristof you're welcome

> Is there any method to test it? Can I somehow add the main repo as an alpha test to an OPN system?

The easiest option is to build a package, but I've just done that for you and published it to our pkg server. To forcefully install the package use the following command:

```
pkg add -f https://pkg.opnsense.org/distfiles/os-ddclient-devel-1.11.pkg
 ```

Then go to general settings and choose OPNsense as backend 
<img width="906" alt="image" src="https://user-images.githubusercontent.com/9783985/211017452-87ab3273-86d3-45fa-b3a8-20baab664c8d.png">


> I assume this change would not be included in the 23.1 version, because of too short notice. When can it be released to production?

No clue yet to be honest,  the way it's implemented now shouldn't influence `ddclient` based setups, but it certainly helps if people test what's in there now. Dynamic DNS as concept isn't very complicated, there's just little to no interest from enterprise users which likely explains the state of most software available. Last year I really hoped to get rid of this by using `ddclient` as everyone seems to be using it.....

**Comment by hauserkristof** [comment]
Super, thank you very much!

I successfully installed it, started to test.

**Comment by fichtner** [comment]
> I assume this change would not be included in the 23.1 version, because of too short notice. When can it be released to production?

Personally I don't mind pushing this latest release in 23.1 along with ddclient-devel package (3.10.0) otherwise we will have no movement whatsoever and some like to complain about it more that it would be helpful. Plus we'd have two separate branches we would have to maintain separately for a longer period of time.


Cheers,
Franco

**Comment by AdSchellevis** [comment]
@hauserkristof can you share some feedback? 23.1 is almost on its way.

**Comment by ei-ke** [comment]
@AdSchellevis Thank you for writing the alternative backend. Using the external check IP method sometimes failed. Using the interface method was not an option with the ddclient backend as I'm behind a CGNAT (issue #2872). So far this new backend seems to work for me because there is the check IP method that allows me to choose for IPv6 only.
Would be nice if there would be the "custom" option as with the ddclient backend where one can just enter the dyndns2 compatible DynDNS provider.
Alternatively the interface chek IP method with the v4/v6 option for the ddclient backend would also solve this as there is already the "custom provider" option.

**Comment by AdSchellevis** [comment]
@ei-ke maybe best open a ticket (using our template) to request the feature, it might not be an enormous amount of work to allow a custom `dyndns2` endpoint, but I can't promise when I can find time for it.
