### ISSUE TITLE
os-bind: Add support for additional RPZ files and/or new addition to the blocklist

### ISSUE THREAD

**Issue by ajkblue** [opnsense/plugins#3047]
- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
I cannot add custom RPZ files to the BIND DNSBL list.

**Describe the solution you'd like**
It would be convenient to add a custom RPZ file to the BIND plugin, such as the way that Unbound has an option to add custom blocklists at `https://x.x.x.x/ui/unbound/dnsbl/index` after ticking the "advanced mode" switch. For example, there is a DOH blocklist in RPZ format that would be very useful located at [jpgpi250/piholemanual/DOH.rpz](https://github.com/jpgpi250/piholemanual/blob/master/DOH.rpz).

**Describe alternatives you've considered**
If it is not as easy to add a custom URL box to the BIND plugin page due to different file formates (e.g., this file is ready as a .rpz file, not formatted as a regular domain list in .txt file like the others), then this is an additional blocklist that could be considered as part of the default BIND blocklists.

**Comment by boomer41** [comment]
Additionally, could we add an option to add a local DNS zone as a RPZ list?
Currently, I have a use case:
The RPZ zone gets synchronized to OPNsense as a secondary zone via DNS transfers.
In BIND, i just need to set this domain as a RPZ zone.
However, I can only use some of the preselected blocklists of the plugin.
