### ISSUE TITLE
[c-icap - virus_scan.conf] maxobjectsize is overridden by default

### ISSUE THREAD

**Issue by Stephanowicz** [opnsense/plugins#305]
Hi,
according to [http://c-icap.sourceforge.net/install.html](http://c-icap.sourceforge.net/install.html)
the **maxobjectsize** is ignored by the hardcoded line
 `ServiceAlias  avscan virus_scan?allow204=on&sizelimit=off&mode=simple`
in [www/c-icap/src/opnsense/service/templates/OPNsense/CICAP/virus_scan.conf ](www/c-icap/src/opnsense/service/templates/OPNsense/CICAP/virus_scan.conf ) in line 2

> sizelimit=off to ignore srv_clamav.MaxObjectSize directive in c-icap.conf file

**Comment by mimugmail** [comment]
Wow, what a stupid default from the pkg sample. Thanks for digging into this, you finally fixed this one! :) 👍

**Comment by Stephanowicz** [comment]
Thanx for fixing  :) 
just an idea: is this necessary to disable the size limit if not wanted?
Then maybe an selectable option needs to be added...?

Cheers, Stephan
