### ISSUE TITLE
os-ddclient checkip - randomly stopped working today using any given IP check service

### ISSUE THREAD

**Issue by ilikenwf** [opnsense/plugins#3051]
I am afraid I can't tell you what caused this issue as no settings have been altered - the latest changes were just installing the latest minorversion update to OPNsense 22.1.10 and I have yet to have a chance to restart and try again, but even in the shell, calling checkip manually as so:

```
/usr/local/opnsense/scripts/ddclient/checkip -i em0 -t 1 -s nsupdate.info-ipv4
```

Results in "None" with any of the available services.

If I replace the cmd called in the ddclient.conf with:

```
cmd="/usr/local/bin/curl -sB icanhazip.com",
```

It works properly.

Example log entries:
```
<29>1 2022-07-26T22:48:09-05:00 myinternalhost.lan ddclient[74369] 36005 - [meta sequenceId="1"] WARNING:  found neither ipv4 nor ipv6 address
<29>1 2022-07-26T22:48:09-05:00 myinternalhost.lan ddclient[74369] 37323 - [meta sequenceId="2"] WARNING:  unable to determine IP address
<29>1 2022-07-26T22:53:19-05:00 myinternalhost.lan ddclient[74369] 39992 - [meta sequenceId="1"] WARNING:  found neither ipv4 nor ipv6 address
<29>1 2022-07-26T22:53:19-05:00 myinternalhost.lan ddclient[74369] 40910 - [meta sequenceId="2"] WARNING:  unable to determine IP address
<29>1 2022-07-26T22:57:08-05:00 myinternalhost.lan ddclient[91010] 10792 - [meta sequenceId="1"] WARNING:  found neither ipv4 nor ipv6 address
<29>1 2022-07-26T22:57:09-05:00 myinternalhost.lan ddclient[91010] 11801 - [meta sequenceId="2"] WARNING:  unable to determine IP address
<29>1 2022-07-26T22:58:33-05:00 myinternalhost.lan ddclient[76594] 29266 - [meta sequenceId="1"] WARNING:  found neither ipv4 nor ipv6 address
<29>1 2022-07-26T22:58:33-05:00 myinternalhost.lan ddclient[76594] 30858 - [meta sequenceId="2"] WARNING:  unable to determine IP address
<29>1 2022-07-26T22:58:36-05:00 myinternalhost.lan ddclient[83519] 31880 - [meta sequenceId="3"] WARNING:  found neither ipv4 nor ipv6 address
<29>1 2022-07-26T22:58:36-05:00 myinternalhost.lan ddclient[83519] 33369 - [meta sequenceId="4"] WARNING:  unable to determine IP address
<29>1 2022-07-26T23:00:16-05:00 myinternalhost.lan ddclient[17553] 21205 - [meta sequenceId="1"] WARNING:  found neither ipv4 nor ipv6 address
<29>1 2022-07-26T23:00:16-05:00 myinternalhost.lan ddclient[17553] 21710 - [meta sequenceId="2"] WARNING:  unable to determine IP address
<29>1 2022-07-26T23:05:27-05:00 myinternalhost.lan ddclient[17553] 3268 - [meta sequenceId="1"] WARNING:  found neither ipv4 nor ipv6 address
```

**Comment by ilikenwf** [comment]
This seems possibly related to #3017

**Comment by AdSchellevis** [comment]
don't force an interface? your curl command uses the default route,  `checkip` is set to force `em0`

**Comment by ilikenwf** [comment]
I tried both with and without an interface forced with no luck - checkip, regardless of the settings and service chosen, always fails. Not sure if there's a routing issue or what - I can manually pull with curl the same URIs used by checkip with success, I should mention.

**Comment by AdSchellevis** [comment]
the script basically uses curl underneath

https://github.com/opnsense/plugins/blob/fc2c08b029e6625be9ba12229093a7c674308ab3/dns/ddclient/src/opnsense/scripts/ddclient/checkip

which with the chosen options would render into :
```
/usr/local/bin/curl -m 10 --interface le1 https://ipv4.nsupdate.info/myip
```

maybe `nsupdate` isn't reachable from your location, there are many other options to choose from in the list `icanhazip.com` just isn't one of them

**Comment by christian-schulze** [comment]
I had this same issue, the problem was the python script /usr/local/opnsense/scripts/ddclient/checkip always returning None. This script calls the various services via curl, which is hard coded to timeout after 10 seconds. Updating the script to timeout after 15 seconds fixed the issue for me...

**Comment by AdSchellevis** [comment]
just open a pull-request and we'll review it, it's not very difficult to add another provider to the list.
