### ISSUE TITLE
Add support for Zabbix 6.2 / EOL Zabbix 5.4

### ISSUE THREAD

**Issue by Pimmetje** [opnsense/plugins#3054]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
`os-zabbix62-proxy` and `os-zabbix62-agent` plugins supporting Zabbix 6.2

**Describe alternatives you've considered**
Zabbix proxy requires exact matching version. 

**Additional context**

* https://www.freshports.org/net-mgmt/zabbix62-agent/
* https://www.freshports.org/net-mgmt/zabbix62-proxy/

**Comment by fraenki** [comment]
I'll take care of this and add Zabbix 6.2 support. However, this will also mean that we're ending support for Zabbix 5.4, because it is EOL.

**Comment by fichtner** [comment]
FreeBSD ports still has it, but I’d favour removal as well.

**Comment by Gromigno** [comment]
Is there any plan to support proxy 6.5 ?

**Comment by mimugmail** [comment]
https://www.zabbix.com/life_cycle_and_release_policy

**Comment by fraenki** [comment]
Please don't post in arbitrary closed issues. If a new release of Zabbix is out, just open a new feature request.
