### ISSUE TITLE
/usr/local/opnsense/service/templates/OPNsense/Nginx 

### ISSUE THREAD

**Issue by JSuenram** [opnsense/plugins#3058]
Maybe it is possible to add

include http_post/*.conf;

in the templates to easier work around issues with Exchange Publishing and prevent this custom setting from being overwritten on updates?

See https://forum.opnsense.org/index.php?topic=21154.msg99523#msg99523

Thanks in advance...

**Comment by fichtner** [comment]
I think it was added for next version
