### ISSUE TITLE
[os-nginx]: basic auth credentials broken in 22.7

### ISSUE THREAD

**Issue by dabo-devconsole** [opnsense/plugins#3063]
**Important notices**
- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
After upgrade from 22.1.10 to 22.7 basic auth is broken.

PHP Fatal error:  Uncaught ArgumentCountError: crypt() expects exactly 2 arguments, 1 given in /usr/local/opnsense/scripts/nginx/setup.php:231
Stack trace:
#0 /usr/local/opnsense/scripts/nginx/setup.php(231): crypt('the_cleartext_password')
#1 {main}
  thrown in /usr/local/opnsense/scripts/nginx/setup.php on line 231

**To Reproduce**
1. Go to 'Services...Nginx...Configuration'
2. Click on 'HTTP(S) -> Credential'
3. Add user and password.
4. Use user in HTTP(S) -> User List
5. In the "System...Reporter" an issue is detected (see above)

**Expected behavior**
- Basic Auth working for nginx plugin

**Additional context**
- PHP crypt() function call needs 2 strings - password and salt(mandatory in PHP 8)
https://www.php.net/manual/de/function.crypt.php#refsect1-function.crypt-changelog

**Environment**
OPNsense 22.7_4-amd64

**Comment by dabo-devconsole** [comment]
Ok, just found this [commit](https://github.com/opnsense/plugins/commit/cc0605386cc). Will seem to fix it.

**Comment by fichtner** [comment]
SHA-512 might not be supported yet. Not sure what the highest supported hash is.

**Comment by dabo-devconsole** [comment]
Isn't this just related to openssl, which supports SHA-512? The Auth file with crypted password is now created for me, but without salt, correct me if I'm wrong.
Is there anything, I can assist with?

**Comment by fichtner** [comment]
Well does auth work for you now? I think SHA-512 is salted by default, but not 100% sure.

**Comment by dabo-devconsole** [comment]
yes works for me

**Comment by dabo-devconsole** [comment]
I think crypt() itself doesn't generates a salt, but instead password_hash() will do.

https://www.php.net/manual/en/function.password-hash.php

**Comment by fichtner** [comment]
@dabo-devconsole you are right, changed it accordingly. thanks!

**Comment by fichtner** [comment]
(was confirmed working on reddit as well)
