### ISSUE TITLE
os-git-backup should hide deploy keys in the UI

### ISSUE THREAD

**Issue by pmhausen** [opnsense/plugins#3070]
- [X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X] The title contains the plugin to which this issue belongs

**Describe the bug**
I just gave a presentation including an OPNsense walkthrough. The UI openly shows the SSH keys which it really should not.

**To Reproduce**
Configure os-git-backup with key authenticated deployment to the upstream git repo.
Save and apply.
Invoke configuration once more - clear text visible private key.

**Expected behavior**
The key field should be hidden by default with the option to expand for changes or a file upload instead of a text field.

**Environment**
22.1
22.7

No pull request this time, sorry folks.

**Comment by fichtner** [comment]
@pmhausen throwing around ideas... how about a UI-side solution that hides the key by default?

**Comment by pmhausen** [comment]
Yes, of course. I'm not asking for a vault or anything providing actual security. One should use a dedicated repo for the config upload, probably on a private server, anyway.

My only complaint is that the key is shown in the open by default so anyone looking over your shoulder or watching your presentation and carrying a smartphone ...

Some hide/unhide function that defaults to hidden would absolutely be enough. That's where my web UI knowledge ends or you would have gotten a pull-request ;)

Kind regards
Patrick

**Comment by pmhausen** [comment]
I prefer re-opening and working on that os-postfix bug. Please go ahead whenever you find the time. UI stuff that takes you five minutes is an hour for me.

**Comment by fichtner** [comment]
Sure, I'll take this then. Which postfix bug do you mean?
