### ISSUE TITLE
Cannot assign network interface

### ISSUE THREAD

**Issue by mscdex** [opnsense/plugins#3071]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

External/pre-made network interfaces are not available for assignment. Specifically, the network interface created by the [net/wifibox](https://github.com/pgj/freebsd-wifibox) FreeBSD port is not able to be assigned for the purposes of firewalling and routing (or configuring of the IP for the interface). The network interface _does_ show up in the overview, where it's listed as an "unassigned" interface. It also shows up when trying to add it as a wireless device, presumably because the PHP code sees that the interface name starts with "wi" and assumes it's a wireless device (when it's technically not).

For what it's worth, here are the two interfaces created (`wifibox0` is the one I want to be able to work with from OPNsense):

```
wifibox0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
	ether zz:zz:zz:zz:zz:zz
	inet 10.0.0.1 netmask 0xffffff00 broadcast 10.0.0.255
	id 00:00:00:00:00:00 priority 32768 hellotime 2 fwddelay 15
	maxage 20 holdcnt 6 proto rstp maxaddr 2000 timeout 1200
	root id 00:00:00:00:00:00 priority 32768 ifcost 0 port 0
	member: tap0 flags=143<LEARNING,DISCOVER,AUTOEDGE,AUTOPTP>
	        ifmaxaddr 0 port 12 priority 128 path cost 2000000
	groups: bridge
	nd6 options=9<PERFORMNUD,IFDISABLED>
tap0: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=80000<LINKSTATE>
	ether yy:yy:yy:yy:yy:yy
	inet6 xxxx::xxxx:xxxx:xxxx:xxxx%tap0 prefixlen 64 scopeid 0xc
	groups: tap
	media: Ethernet autoselect
	status: active
	nd6 options=23<PERFORMNUD,ACCEPT_RTADV,AUTO_LINKLOCAL>
	Opened by PID 96614
```

**To Reproduce**

1. Have a wireless card supported by Linux installed and not in use by FreeBSD.
2. Install the net/wifibox, net/wifibox-core, and net/wifibox-alpine ports (already in the OPNsense ports)
3. Configure wifibox appropriately.
4. Start the wifibox service
5. Navigate to the interface assignment page in OPNsense

**Expected behavior**

To have the `wifibox0` interface show up for the purposes of assigning, allowing me to set the IP address, firewall rules, routing, etc.

**Describe alternatives you considered**

Finding a way to manually configure routing and firewall rules in FreeBSD without causing issues with OPNsense. I _really_ don't want to have to resort to that.

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 22.1.x (amd64, OpenSSL)

**Comment by fichtner** [comment]
Typically you want to add a plugin specification for the network devices, esp. coming from a third party software that needs compiling and configuring anyway.


Cheers,
Franco

**Comment by mscdex** [comment]
At this point I'm only really interested in adding firewall rules and routing and the interface does not seem to be anything out of the ordinary, so I wasn't sure why OPNsense couldn't directly work with it?
