### ISSUE TITLE
DNS-01 - All-Inkl Domain API - OUTDATED

### ISSUE THREAD

**Issue by bashinator** [opnsense/plugins#3073]
Hi there.
Using acme.sh .. with OpenSense..

ACME.SH is for All-Inkl Domain API .. not up2date //

<html><body>

2022-08-07T20:08:42 | acme.sh | [Sun Aug  7 20:08:42 CEST 2022] timeout=
-- | -- | --
2022-08-07T20:08:42 | acme.sh | [Sun Aug  7 20:08:42 CEST 2022]  url='https://kasapi.kasserver.com/dokumentation/formular.php?kas_login=<username>&kas_auth_type=sha1&kas_auth_data=<password>&var1=record_name&wert1=&var2=record_type&wert2=TXT&var3=record_data&wert3=0wYze4VF-SjGHu66z8gg_jQIZ0Ko2WhFGLYZI17mMIU&var4=record_aux&wert4=0&kas_action=add_dns_settings&var5=zone_host&wert5=_acme-challenge.<domain>.'
2022-08-07T20:08:42 | acme.sh | [Sun Aug  7 20:08:42 CEST 2022] GET

</body>
</html>

The new URL is for ALL-Inkl. ::

https://test-account.com/formular.php

--
https://kasapi.kasserver.com/dokumentation/formular.php <-- is outdated!! Doesn't work anymore..

so someone need to fix it from 👍 

https://kasapi.kasserver.com/dokumentation/formular.php > https://test-account.com/formular.php

could someone fix it, that OpenSense got the right version ... included that Fix!

And :: SHA1 doesn't work from 12/2022, they use : plain instead of SHA1 .. 
So someone needs to fix // ALL-INKL. Domain for ACME..

Regards

**Comment by fraenki** [comment]
>  https://kasapi.kasserver.com/dokumentation/formular.php <-- is outdated!! Doesn't work anymore..

This cannot be fixed in OPNsense, it needs to be fixed in the upstream acme.sh project. There are already pending PRs (https://github.com/acmesh-official/acme.sh/pull/4222, https://github.com/acmesh-official/acme.sh/pull/4219). When a fix is merged and included in an official release of acme.sh, it will automatically be available in one of the next OPNsense releases.

> And :: SHA1 doesn't work from 12/2022, they use : plain instead of SHA1

This was addressed in https://github.com/opnsense/plugins/pull/3068.

**Comment by Marco4223** [comment]
Hi [bashinator](https://github.com/bashinator)
if you have shell access to your machine, you can try the dns_kas.sh script from the pull requests mentioned.
Cheers

**Comment by bashinator** [comment]
i can't need - to wait for opensense fix // still no url change .. :)

<html><body>


2022-08-19T20:51:57 | acme.sh | [Fri Aug 19 20:51:57 CEST 2022]  url='https://kasapi.kasserver.com/dokumentation/formular.php?kas_login=<user>&kas_auth_type=plain&kas_auth_data=<pass>&var1=record_name&wert1=&var2=record_type&wert2=TXT&var3=record_data&wert3=AaNQnwFtzPPN7jIisEuO0Qo47BkZ0D8iMBE0MTpqk_o&var4=record_aux&wert4=0&kas_action=add_dns_settings&var5=zone_host&wert5=_acme-challenge.opnsense.inetoff.de.'
-- | -- | --
2022-08-19T20:51:57 | acme.sh | [Fri Aug 19 20:51:57 CEST 2022] GET


</body>
</html>

-- still old url :: doesn't work for ALL-INKL

https://kasapi.kasserver.com/dokumentation/formular.php <-- is outdated!! Doesn't work anymore..

so someone need to fix it from 👍

https://kasapi.kasserver.com/dokumentation/formular.php > https://test-account.com/formular.php

dunno how hard that mess is :)

**Comment by Marco4223** [comment]
Hi [bashinator](https://github.com/bashinator),
Bug is still fixed. So you have to wait until opensense pull the latest version.
URL change doesn’t fix the issue!

**Comment by bashinator** [comment]
[Tue Sep 6 15:22:34 CEST 2022] url='https://kasapi.kasserver.com/dokumentation/formular.php?kas_login=<username>&kas_auth_type=plain&kas_auth_data=<passwd>&var1=record_name&wert1=&var2=record_type&wert2=TXT&var3=record_data&wert3=76xZqfXA4Ukv0wowAP5lqCeeJEBwWrfjQU2Ov-lSF1k&var4=record_aux&wert4=0&kas_action=add_dns_settings&var5=zone_host&wert5=_acme-challenge.<url>'

06.09.2022 - still no "PULL" from opnsense?
Works fine.. NOT!
-------------
OpnSense coming up with "" acme.sh | Version : 3.0.4
------------
os-acme-client |  Version : 3.13
------------

Since 18Days no upgrade? Yeah Marco, there is still not a fix outside ?? :)
OLD URL STILL INCOMING !!
BUT, PLAIN <Passwd> is up2date.. so there was a fix, but nobody fix the damn URL..

regards

**Comment by fraenki** [comment]
The statement I've made is still valid:

> This cannot be fixed in OPNsense, it needs to be fixed in the upstream acme.sh project. There are already pending PRs (https://github.com/acmesh-official/acme.sh/pull/4222, https://github.com/acmesh-official/acme.sh/pull/4219). When a fix is merged and included in an official release of acme.sh, it will automatically be available in one of the next OPNsense releases.

Simply put: there is still [no new release](https://github.com/acmesh-official/acme.sh/releases) of acme.sh available.
