### ISSUE TITLE
Add multiply Prefix lists to BGP route map Issue

### ISSUE THREAD

**Issue by skynets4** [opnsense/plugins#3074]
**Describe the bug**
Cannot add multiply prefix-list's to bgp route-map.

**To Reproduce**
1. Go to 'Routing-BGP-Prefix Lists'
2. Add some prefix-list
3. Go to - Routing - BGP - Route maps
4. Click to plus
5. Write name and click section "prefix-lists"
6. Add two or more prefix-list
7. See error "Related item not found"

**Expected behavior**
Add multiply prefix lists

**Screenshots**
![Снимок экрана от 2022-08-08 10-35-39](https://user-images.githubusercontent.com/10193107/183376026-da31a94e-3d4e-4e79-a205-821840a5586b.png)

**Relevant log files**
not applicable

**Additional context**
No additional

**Environment**

OPNsense 22.7.4  (amd64, OpenSSL)
Network Intel® I210-AT
Plugin Version os-frr 1.29

**Comment by patschi** [comment]
I can confirm experiencing the same issue with OPNsense 22.7.1-amd64:
![image](https://user-images.githubusercontent.com/2029878/184556699-f81aac4d-1a07-429b-a929-dd9c6127aee6.png)

The route-map is designed to handle multiple entries:
https://github.com/opnsense/plugins/blob/3d2144223206b8a5edfcf22b0aa50dd2bbdc991b/net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/dialogEditBGPRouteMaps.xml#L40-L47

Similar issue seen with other plugins apparently, maybe this is some generic issue and not specific to FRR/BGP?
https://github.com/opnsense/plugins/blob/7d682dd143fd413eb9b1a3f42cc2c2293cdfcd60/security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/Api/SettingsController.php#L370-L373

The validation part of Quagga/BGP seems to be here:
https://github.com/opnsense/plugins/blob/16f3522d08d30919b17e66bdec38352ef4c75208/net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/Api/GeneralController.php#L56-L63

I'm not too familiar with the code base with OPNsense. Changing above functions to e.g. disable validation or output more details don't reflect in the UI for some reason, also not after restarting webui.

This is quite limiting for my new setup now. Any help would be appreciated.

**Comment by FilipK-CZ** [comment]
Multiple PrefixLists can be added but Running Configuration is different from /usr/local/etc/frr/bgpd.conf and multiple PrefixLists are not working correctly. Router advertise just one of the lists (and it matches the Running Configuration)

Running Configuration (under GUI - Routing - Diagnostics - General)
```
Building configuration...

Current configuration:
!
frr version 7.5.1
frr defaults traditional
hostname gw1.lan
log syslog critical
!
router bgp 65000
 no bgp ebgp-requires-policy
 bgp graceful-restart
 neighbor 192.168.255.1 remote-as 65002
 neighbor 192.168.255.1 update-source vtnet9
 !
 address-family ipv4 unicast
  neighbor 192.168.255.1 route-map NewNetwork in
  neighbor 192.168.255.1 route-map NewNetwork out
 exit-address-family
!
ip prefix-list PrivateA seq 10 permit 10.0.0.0/8 le 32
ip prefix-list PrivateB seq 15 permit 172.16.0.0/12 le 32
ip prefix-list PrivateC seq 20 permit 192.168.0.0/16 le 32
!
route-map NewNetwork permit 11
 match ip address prefix-list PrivateC
!
line vty
!
end
```

File: /usr/local/etc/frr/bgpd.conf
```
!
! Zebra configuration saved from vty
!   2017/03/03 20:21:04
!
log syslog critical
frr defaults traditional
!
!
!
router bgp 65000
 no bgp ebgp-requires-policy
 bgp graceful-restart
 neighbor 192.168.255.1 remote-as 65002
 neighbor 192.168.255.1 update-source vtnet9

 address-family ipv4 unicast
  neighbor 192.168.255.1 activate
  neighbor 192.168.255.1 route-map NewNetwork in
  neighbor 192.168.255.1 route-map NewNetwork out
 exit-address-family
!
 address-family ipv6 unicast
 exit-address-family
!

ip prefix-list PrivateA seq 10 permit 10.0.0.0/8 le 32
!
ip prefix-list PrivateB seq 15 permit 172.16.0.0/12 le 32
!
ip prefix-list PrivateC seq 20 permit 192.168.0.0/16 le 32
!
!
!
!
route-map NewNetwork permit 11
 match ip address prefix-list PrivateA
 match ip address prefix-list PrivateB
 match ip address prefix-list PrivateC
!
!
!
line vty
!
```

**Comment by creagel** [comment]
I have the same experience as FilipK-CZ (tested on opnsense 22.7.11_1 / os-frr  1.31).

**Comment by straussmarkus** [comment]
I am afraid this is not fixed. I have the exact same behavior as @FilipK-CZ running OPNsense 23.7.6-amd64 with os-frr 1.36_1

While /usr/local/etc/frr/bgpd.conf has the expected route-map like this:
```
route-map MY_ROUTE_MAP permit 100
 match ipv6 address prefix-list MY_LIST1
 match ipv6 address prefix-list MY_LIST2
 ```

the output showing the running configuration displays

```
route-map MY_ROUTE_MAP permit 100
exit
!
```

I can reproduce that only the first prefix-list added to the route-map works and any others are ignored. I somewhere read a workaround to give all your prefix-lists the same name, but this does not work for me either.

**Comment by cjemorton** [comment]
I am having this exact same problem. Has there been any progress on solving it ?
