### ISSUE TITLE
os-ddclient Multi-WAN scenario, all get the same public IP

### ISSUE THREAD

**Issue by Deutschi** [opnsense/plugins#3076]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
I have multiple WAN interfaces, each one is connected to a modem - so every WAN interface in OPNsense gets a LAN IP. Until now, I used the legacy dyndns client to update multiple No-IP domains, one for each WAN interface. The new os-ddclient works as expected if there is only one entry made - the public IP of the interface is correctly determined. However, once I enable the second entry for the second WAN interface, os-ddclient finds one IP and sets this one for every entry.

**To Reproduce**
1. Go to Dynamic DNS settings of the new os-ddclient
2. Add an entry for a specific WAN interface, save and apply (works)
3. Add another entry for a different interface, same Provider, different domains/hostnames, save and apply
4. All entries get the same IP address

**Expected behavior**
Every entry should be considered independent and get a different public IP address.

**Screenshots**
Legacy Dyndns (working):
![legacy ddns](https://user-images.githubusercontent.com/2011264/183622219-8df83e4c-bbf4-4cd6-b3b1-1cded780d170.jpg)

"new" os-ddclient:
![os ddns](https://user-images.githubusercontent.com/2011264/183622240-3eec573f-d4bf-4033-98b8-692860646726.jpg)
![os ddns log](https://user-images.githubusercontent.com/2011264/183622256-877d82b5-c88c-4563-898c-6bd339fd7ba6.jpg)

**Additional context**
- I have no special settings in my outgoing NAT, just the automatic stuff.
- This is not a visual bug, the single IP gets submitted to No-IP for all domains.

**Environment**
OPNsense 22.1.10_4-amd64
FreeBSD 13.0-STABLE
OpenSSL 1.1.1q 5 Jul 2022

Plugin: os-ddclient 1.8

**Comment by Links2004** [comment]
Having a very similar problem but with IPv4 + IPv6 updates. 
os-ddclient does always use the IPv4 interface address, which is bad.

the legacy dyndns is working perfectly fine, for my use case.



### Versions 
OPNsense: 22.7.9-amd64
FreeBSD :13.1-RELEASE-p5
OpenSSL: 1.1.1s 1 Nov 2022
