### ISSUE TITLE
[os-haproxy-3.10]  stop working after few hours and parameter page crashing

### ISSUE THREAD

**Issue by Gis70** [opnsense/plugins#3078]
- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

User-Agent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
FreeBSD 13.1-RELEASE stable/22.7-n250212-a26d6065f1f SMP amd64
OPNsense 22.7_4 909dcabd5
Plugins os-acme-client-3.11 os-cache-1.0_1 os-crowdsec-1.0 os-haproxy-3.10 os-iperf-1.0_1 os-mdns-repeater-1.1 os-theme-vicuna-1.41 os-vmware-1.5_1 os-wireguard-1.11 
Time Tue, 09 Aug 2022 17:45:53 +0200
OpenSSL 1.1.1q  5 Jul 2022
Python 3.9.13
PHP 8.0.20

**Describe the bug**
Since i moved to OPNsense 22.7_4 909dcabd5 from 22.1 My HAProxy is crashing after some hours (cannot access from outside of my network) and the HAProxy PARAMETERS page is crashing with the following report :  

Everything was working as intendend on 22.1 version.

Thank you for your help

`PHP Errors:
[09-Aug-2022 17:45:53 Europe/Paris] ValueError: Missing format specifier at end of string in /usr/local/opnsense/mvc/app/cache/_usr_local_opnsense_mvc_app_views_opnsense_haproxy_index.volt.php:674
Stack trace:
#0 /usr/local/opnsense/mvc/app/cache/_usr_local_opnsense_mvc_app_views_opnsense_haproxy_index.volt.php(674): sprintf('Plus d'inf...[', '](https://192.168.0.254:4443/...',%20'%3C/a%3E',%20'%3Ca%20href=)[', '](https://192.168.0.254:4443/...',%20'%3C/a%3E')#1%20[internal%20function]:%20Phalcon\Mvc\View\Engine\Volt-%3Erender('/usr/local/opns...',%20Array,%20true)#2%20[internal%20function]:%20Phalcon\Mvc\View-%3EengineRender(Array,%20'OPNsense/HAProx...',%20true)#3%20[internal%20function]:%20Phalcon\Mvc\View-%3EprocessRender('index',%20'index',%20Array)#4%20[internal%20function]:%20Phalcon\Mvc\View-%3Erender('index',%20'index')#5%20/usr/local/opnsense/www/index.php(70):%20Phalcon\Mvc\Application-%3Ehandle('/ui/haproxy')#6%20{main}[09-Aug-2022%2017:52:16%20Europe/Paris]%20ValueError:%20Missing%20format%20specifier%20at%20end%20of%20string%20in%20/usr/local/opnsense/mvc/app/cache/_usr_local_opnsense_mvc_app_views_opnsense_haproxy_index.volt.php:674Stack%20trace:#0%20/usr/local/opnsense/mvc/app/cache/_usr_local_opnsense_mvc_app_views_opnsense_haproxy_index.volt.php(674):%20sprintf('Plus%20d'inf...',%20'%3Ca%20href=)', '')
#1 [internal function]: Phalcon\Mvc\View\Engine\Volt->render('/usr/local/opns...', Array, true)
#2 [internal function]: Phalcon\Mvc\View->engineRender(Array, 'OPNsense/HAProx...', true)
#3 [internal function]: Phalcon\Mvc\View->processRender('index', 'index', Array)
#4 [internal function]: Phalcon\Mvc\View->render('index', 'index')
#5 /usr/local/opnsense/www/index.php(70): Phalcon\Mvc\Application->handle('/ui/haproxy')
#6 {main}`

**Environment**
virtual machine on ESXI 6.7

**Comment by fraenki** [comment]
@Gis70 please upgrade to 22.7.1, which was released yesterday, and report back.

**Comment by Gis70** [comment]
Still the same even after updating :  

System Information:
User-Agent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
FreeBSD 13.1-RELEASE stable/22.7-n250212-a26d6065f1f SMP amd64
OPNsense 22.7.1 4b384de5c
Plugins os-acme-client-3.12 os-cache-1.0_1 os-crowdsec-1.0 os-haproxy-3.10_1 os-iperf-1.0_1 os-mdns-repeater-1.1 os-theme-vicuna-1.41 os-vmware-1.5_1 os-wireguard-1.11 
Time Thu, 11 Aug 2022 00:21:19 +0200
OpenSSL 1.1.1q  5 Jul 2022
Python 3.9.13
PHP 8.0.20
PHP Errors:
[11-Aug-2022 00:21:19 Europe/Paris] ValueError: Missing format specifier at end of string in /usr/local/opnsense/mvc/app/cache/_usr_local_opnsense_mvc_app_views_opnsense_haproxy_index.volt.php:674
Stack trace:
#0 /usr/local/opnsense/mvc/app/cache/_usr_local_opnsense_mvc_app_views_opnsense_haproxy_index.volt.php(674): sprintf('Plus d'inf...[', '](https://192.168.0.254:4443/...',%20'%3C/a%3E',%20'%3Ca%20href=)', '[ on acpi0](https://192.168.0.254:4443/...',%20'%3C/a%3E')
#1%20[internal%20function]:%20Phalcon\Mvc\View\Engine\Volt-%3Erender('/usr/local/opns...',%20Array,%20true)
#2%20[internal%20function]:%20Phalcon\Mvc\View-%3EengineRender(Array,%20'OPNsense/HAProx...',%20true)
#3%20[internal%20function]:%20Phalcon\Mvc\View-%3EprocessRender('index',%20'index',%20Array)
#4%20[internal%20function]:%20Phalcon\Mvc\View-%3Erender('index',%20'index')
#5%20/usr/local/opnsense/www/index.php(70):%20Phalcon\Mvc\Application-%3Ehandle('/ui/haproxy')

**Comment by fraenki** [comment]
TBH, I have no idea.

Try to reboot the firewall.

Maybe try to purge the MVC cache?
`rm -rf /usr/local/opnsense/mvc/app/cache/_usr*`

Also check `System: Log Files: General` and `System: Log Files: Backend` for other errors, maybe the HAProxy issue is just a symptom of another issue.

**Comment by kulikov-a** [comment]
Hi!

> Missing format specifier at end of string
sprintf('Plus d'inf..


not sure if the reported error is related to the underlying problem (crash after a few hours), but it looks like the format specifier is missing from the french translation file at the end of the line
`msgstr "Plus d'information disponible dans notre %sHAProxy plugin documentation%s et bien sûr dans %sofficial de HAProxy docummentation%s. Les incidents comme les demandes fonctionnelles sont à faire sur notre %sGitHub issue page%"`

**Comment by fichtner** [comment]
[9af7fcd](https://github.com/opnsense/lang/commit/9af7fcd83807025818dfb0e0c1f6d1035e148906) takes care of is at least.

**Comment by Gis70** [comment]
Thanks, first, i would like to apply the update of translation but how to do that ? then i will dig following your advices.

**Comment by kulikov-a** [comment]
https://forum.opnsense.org/index.php?topic=29543.msg142666#msg142666

but, if this is not a problem, I would suggest switching the interface to English for the time of haproxy debugging
