### ISSUE TITLE
FR: FRR BGP plugin - add support for neighbor options attribute-unchanged

### ISSUE THREAD

**Issue by ikiris** [opnsense/plugins#3084]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
Feature support is missing for required operational ability to leave certian attributes unchanged with eBGP peers such as private AS internal peerings

**Describe the solution you'd like**
Ideally implement the following neighbor options in the bgp neighbor config. Should be easy to add a subgrouping for attribute unchanged with checkboxes for the possible 3 (med, as-path, next-hop), maybe under a roll tab or something. I don't care how the UX looks as long as it works :)

**Describe alternatives you've considered**
If there were manual config sections I would just do so in the meantime, but there does not appear to be a way to do so.

**Additional context**
relevant FRR docs:
https://docs.frrouting.org/en/latest/bgp.html#clicmd-neighbor-PEER-attribute-unchanged-as-path-next-hop-med

I also apologize that this isn't a PR, but I'm not very strong on the UI side and brand new to the codebase.

**Comment by patschi** [comment]
I just created PR #3112 to add the setting as you requested. From a config standpoint, that should do the trick.
