### ISSUE TITLE
security/acme-client: does not sufficiently pass through vague curl error message

### ISSUE THREAD

**Issue by hboetes** [opnsense/plugins#3088]
I couldn't get the acme account registered, and the log message was not useful, so I increased logging to debugging and I got this message in the web-gui:

```
AcmeClient: running acme.sh command: /usr/local/sbin/acme.sh --registeraccount --syslog 7 --debug --server 'https://acme-server.domain.tld/acme/directory' --home '/var/etc/acme-client/home' --accountconf '/var/etc/acme-client/accounts/6306261d7e03d9.68619529_custom/account.
```

As you can see that's missing a bit. So I searched the logfiles.

```
root@fwpecs01:~ # grep -r /usr/local/sbin/acme.sh /var/log/
/var/log/system/latest.log:<13>1 2022-08-24T15:53:02+02:00 firewall.domain.tld opnsense 53999 - [meta sequenceId="4"] AcmeClient: running acme.sh command: /usr/local/sbin/acme.sh --registeraccount --syslog 7 --debug --server 'acme-server.domain.tld/acme/directory' --home '/var/etc/acme-client/home' --accountconf '/var/etc/acme-client/accounts/6306261d7e03d9.68619529_custom/account.conf'
```

So now I could finally run the command that was run by the plugin, and it has this output:

```
[Wed Aug 24 15:57:01 CEST 2022] Lets find script dir.
[Wed Aug 24 15:57:01 CEST 2022] _SCRIPT_='/usr/local/sbin/acme.sh'
[Wed Aug 24 15:57:01 CEST 2022] _script='/usr/local/sbin/acme.sh'
[Wed Aug 24 15:57:01 CEST 2022] _script_home='/usr/local/sbin'
[Wed Aug 24 15:57:01 CEST 2022] Using config home:/var/etc/acme-client/home
https://github.com/acmesh-official/acme.sh
v3.0.4
[Wed Aug 24 15:57:02 CEST 2022] Using server: https://acme-server.domain.tld/acme/directory
[Wed Aug 24 15:57:02 CEST 2022] Running cmd: registeraccount
[Wed Aug 24 15:57:02 CEST 2022] Using config home:/var/etc/acme-client/home
[Wed Aug 24 15:57:02 CEST 2022] ACME_DIRECTORY='https://acme-server.domain.tld/acme/directory'
[Wed Aug 24 15:57:02 CEST 2022] Using config home:/var/etc/acme-client/home
[Wed Aug 24 15:57:02 CEST 2022] ACME_DIRECTORY='https://acme-server.domain.tld/acme/directory'
[Wed Aug 24 15:57:02 CEST 2022] _init api for server: https://acme-server.domain.tld/acme/directory
[Wed Aug 24 15:57:02 CEST 2022] GET
[Wed Aug 24 15:57:02 CEST 2022] url='https://acme-server.domain.tld/acme/directory'
[Wed Aug 24 15:57:02 CEST 2022] timeout=
[Wed Aug 24 15:57:02 CEST 2022] _CURL='curl --silent --dump-header /var/etc/acme-client/home/http.header  -L '
[Wed Aug 24 15:57:02 CEST 2022] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 60
[Wed Aug 24 15:57:02 CEST 2022] ret='60'
[Wed Aug 24 15:57:02 CEST 2022] Can not init api for: https://acme-server.domain.tld/acme/directory.
[Wed Aug 24 15:57:02 CEST 2022] Sleep 10 and retry.
```

And then it struck me what was going wrong: I needed to install the company CA.

Since this kind of debugging might be out of scope for the average admin, I'd like to propose a more obvious message in the GUI, warning that no CA has been added for the ACME server and thus the registration process will fail. This is a catch-22 situation.

I don't know if my ACME server can also provide the CA, looking into that now. Can the ACME plugin download it from the acme server?

**Comment by fraenki** [comment]
> root@fwpecs01:~ # grep -r /usr/local/sbin/acme.sh /var/log/

No need to use the CLI, this log file is also available from the GUI:
`Services: ACME Client: Log Files -> Tab: ACME Log`

> I'd like to propose a more obvious message in the GUI, warning that no CA has been added for the ACME server

It's unlikely that this will ever be implemented, because of how much work one would need to put into this for a relatively rare use-case.
I think it's reasonable to assume that an admin would just read the logs to figure this out. Just like you successfully did. :)
