### ISSUE TITLE
security/openconnect reconnect feature (bug?)

### ISSUE THREAD

**Issue by syserr0r** [opnsense/plugins#3091]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
When the OpenConnect connection drops it does not reconnect automatically.

**Describe the solution you'd like**
Openconnect should reconnect if the connection is terminated

**Describe alternatives you've considered**
This can be accomplished using Monit with the following set-up:

Test:
  - Condition: `<some condition to check connection is alive>` (in our case checking the DNS server with: `failed host 100.65.2.10 port 53 type udp protocol dns`
  - Action: Restart
Service:
  - Type: Process
  - PID File: `/var/run/openconnect.pid`
  - Start: `/usr/local/etc/rc.d/opnsense-openconnect start`
  - Stop: `/usr/local/etc/rc.d/opnsense-openconnect stop`
  - Tests: Select name of test above

**Additional context**
N/A

**Comment by Dees7** [comment]
Hello.
I have the same trouble. Looks like it is a bug. Please review issue.
