### ISSUE TITLE
 os-ddclient: `Description` field validation function returns misleading validation criteria

### ISSUE THREAD

**Issue by kquinsland** [opnsense/plugins#3095]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X] The title contains the plugin to which this issue belongs

**Describe the bug**
The string validation for `Description` under the `Edit Account` modal dialogue has incorrect/incomplete validation.

I stumbled on this while trying to diagnose some issues with `ddclient` w/r/t IPv4 vs IPv6 address being updated similar to #3069 and #2943.

**To Reproduce**
1. Install `dclient` plugin
2. Set up any account/interface/service configuration
3. observe issues with IPv4 vs IPv6 being sent back to the dynamic DNS service
4. Attempt to leave a comment with punctuation in it, specifically the `(` and `.` and `)` characters
5. Click `Save`
6. Observe a "Description should be a string between 1 and 255 characters" message

**Expected behavior**
I would expect an accurate error describing which characters are prohibited

**Screenshots**

![pngout](https://user-images.githubusercontent.com/1808375/187054059-60ae007e-cb15-4087-82d4-8e06cbd118c4.png)

**Environment**

```
OPNsense 22.7.2-amd64FreeBSD 13.1-RELEASE-p1OpenSSL 1.1.1q  5 Jul 2022
```

**Comment by AdSchellevis** [comment]
@kquinsland https://github.com/opnsense/plugins/commit/af42c4ebf22681077c118f0815374b3b5e45f9d4 should loosen the validation to only the length constraint.
