### ISSUE TITLE
FRR: Increase ACL number range 

### ISSUE THREAD

**Issue by boomer41** [opnsense/plugins#3098]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
Issue #2939 requested to increase the available number range for prefix lists from 10-99 to 10-10000.
Although 10000 seems a bit low, it should still be enough.

FRR supports numbers between 0 and 4294967295. See docs section below.

It feels a bit awkward to introduce artificial limits.
This makes it hard to directly "import" any existing configuration and may introduce errors.
In my case, I moved from pfSense to OPNsense and I was very annoyed when those restrictions came into place, because I had to reorder my rule set manually.

The range for route maps and AS path lists are still restricted to 10-99.

**Describe the solution you'd like**
Remove any artificial restriction for sequential ids from:
- route maps
- AS path lists
- prefix lists.

Numbering shall be possible between between 0 to 4294967295 for any of the three given examples.

**Describe alternatives you've considered**
Renumbering existing rule sets I'd like to use 1:1.
This may introduce errors and effectively desynchronize the lists between other routers.

**Docs**
AS path lists:
> bgp as-path access-list WORD [seq (0-4294967295)] permit|deny LINE
https://docs.frrouting.org/en/latest/bgp.html?highlight=AS%20path%20list#as-path-access-lists

Prefix lists:
> seq number can be set either automatically or manually. In the case that sequential numbers are set manually, the user may pick any number less than 4294967295.
https://docs.frrouting.org/en/latest/filter.html?highlight=prefix%20lists#ip-prefix-list

Route Maps:
Not explicitly mentioned in the docs, but
> access-list TEST seq 4294967294 permit any
works on my machine

**Comment by patschi** [comment]
FYI, I just created PR #3110 which increases the limits as you suggested.
