### ISSUE TITLE
FRR: Route-Maps: Allow matching on Peer IP

### ISSUE THREAD

**Issue by boomer41** [opnsense/plugins#3099]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
In FRR, route maps allow matching on the BGP peer's IP address using the "match peer" family of commands.
This is not supported in OPNsense and makes matching on a very specific peer very hard.
See https://docs.frrouting.org/en/latest/routemap.html

**Describe the solution you'd like**
An option to match on the peer's IPv4/v6 address

**Describe alternatives you've considered**
In my use case, i can do a workaround.
But this is an ugly hack.

**Comment by mimugmail** [comment]
So when we add a HostnameField below Community where you can enter a v4/v6 Address (one) this should be fine?
![image](https://user-images.githubusercontent.com/20438689/187138486-bbe8eaa3-3e88-4189-b6af-1c6d1bb9dc67.png)

**Comment by boomer41** [comment]
In theory, yes.

But I have another idea:
As the Set-Command is a completely free text already, maybe we could add a free text for "match"-commands, too?
This way, we could use all match commands without having explicit support for the GUI.

See #3100 - I asked over there to allow multiple set commands per entry.
Maybe the same principle could be added here, too.
