### ISSUE TITLE
FRR: Allow multiple set commands in a Route Map entry

### ISSUE THREAD

**Issue by boomer41** [opnsense/plugins#3100]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
For some entries, i have to execute multiple set commands for a single match.
As the engine terminates processing after the first match (and I cant set "on-match next" or "continue"), I can only have exactly one set command.
Workarounds using "\n" did not work, either.

**Describe the solution you'd like**
An option to have a list of set commands instead of one.

**Comment by mimugmail** [comment]
Can you post a config snipped of your setup (which you need) please?

**Comment by boomer41** [comment]
For example, the following config (made up numbers to get the point):

> set weight 1000
> set community 123:123
