### ISSUE TITLE
BIND plugin API missing searchDomain action...

### ISSUE THREAD

**Issue by micah-quinn** [opnsense/plugins#3103]
When attempting to access the BIND plugin API action "searchDomain", I'm getting the following response:

{"message":"action searchDomain not found","status":400}

According to the [API documentation](https://docs.opnsense.org/development/api/plugins/bind.html), this action should exist.

I noticed it when I attempted to setup the ACME client to renew a Let's Encrypt certificate and the challenge type for the OPNsense BIND plugin kept failing. The ACME client is getting the same error.

To reproduce, just attempt to access your OPNsense install at /api/bind/domain/searchDomain.

OPNsense 22.7.2-amd64
FreeBSD 13.1-RELEASE-p1
OpenSSL 1.1.1q 5 Jul 2022

**Comment by mimugmail** [comment]
Its now splitted into Master and Slave Domain since the last update:

https://github.com/opnsense/plugins/blob/master/dns/bind/src/opnsense/mvc/app/controllers/OPNsense/Bind/Api/DomainController.php#L42

**Comment by koelle25** [comment]
I started work on a PR on the upstream acme.sh repository to fix the update script.
