### ISSUE TITLE
security/acme-client: fix implementation of setup.sh

### ISSUE THREAD

**Issue by fraenki** [opnsense/plugins#3113]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
The current usage and implementation of setup.sh diverts from other implementations and may break in the future.

**Describe the solution you'd like**
The setup.sh implementation should be changed:
* do not run setup.sh from controllers or other mvc components
* move to NAME_setup use 

**Describe alternatives you've considered**
Leave it as it is and risk breakage in the future. Not a real alternative though. :)

**Additional context**
This was discussed here:
https://github.com/opnsense/plugins/commit/27d89b85955cf1cc7cd3bd721ff3fbdff062fa0d

**Comment by fichtner** [comment]
If you need help with this let me know. I would have attempted it but I think nobody would appreciate the breakage since I don't have a proper test setup. :)
