### ISSUE TITLE
security/crowdsec: CrowdSec produces malformed PF logs

### ISSUE THREAD

**Issue by Byter09** [opnsense/plugins#3115]
- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
CrowdSec seems to produce malformed packet filter logs - see attached screenshot and log. I am not knowledgeable enough to determine if this includes not actually functioning correctly. From what I can tell it does still correctly block blacklisted IPs.

**To Reproduce**
1. Install `crowdsec` plugin
2. Activate it
3. enable logging
4. set a tag for diagnostic purposes (I can't tell if this is relevant, so I'm including it)
5. go to the Firewall Live View and wait for a line to appear that looks like what is attached at the screenshot.

**Expected behavior**
A correct entry in the live view (and probably correct plain log lines, I can't tell if they're malformed), that I can dissect and filter for.

**Screenshots**
![image](https://user-images.githubusercontent.com/16060697/188880728-0cb457e4-ada7-4ac7-bcb5-b8ded21b3a13.png)
(note, this screenshot is not associated to the below log line)

**Relevant log files**
`Plain View` gives me lines like these:
```
70,,,blocked by crowdsec,re0,match,block,in,4,0x0,,53,13133,0,none,17,udp,132,185.65.135.170,10.0.0.200,11910,51918,112
```

**Additional context**
I opened an issue here as well but wasn't sure it will be worked on there, given it was merged here. https://github.com/crowdsecurity/opnsense-plugin-crowdsec/issues/34

**Environment**
OPNsense 22.7.4-amd64
FreeBSD 13.1-RELEASE-p2
OpenSSL 1.1.1q 5 Jul 2022
Intel(R) Celeron(R) J4125 CPU @ 2.00GHz (4 cores, 4 threads)

Unsure if important but network interfaces look like this:
![image](https://user-images.githubusercontent.com/16060697/188881768-0518f881-24cc-41ce-a1ac-6ef488c39373.png)

**Comment by bradyrf** [comment]
Also seeing this issue when trying to view Crowdsec blocks in Live View.
My interface is EM5. Comes in Live View with no info, as interface "in" see Dark Blue line in first image.
Just let me know who to send the Pizza to :) Thanks in advance.

![Bug 1](https://user-images.githubusercontent.com/88627993/191028577-d15d1ca1-71c1-4332-b7c5-6d68a764bf4a.png)

![Bug 2](https://user-images.githubusercontent.com/88627993/191028835-30865852-9cf6-4e35-9fe5-c25426d8e53e.png)
![Bug3](https://user-images.githubusercontent.com/88627993/191028876-6b1c9aef-2686-4ff7-9661-2d4ad1a6fbc6.png)

**Comment by AdSchellevis** [comment]
let's poke @mmetc as maintainer of this plugin

**Comment by mmetc** [comment]
Thanks!
There was a mismatched key.

I prepared a PR: https://github.com/opnsense/plugins/pull/3130

**Comment by bradyrf** [comment]
![Working](https://user-images.githubusercontent.com/88627993/191086579-b3d89e59-bcbe-4f3f-886c-ca7792629624.png)
Looks like success! Thank you!
