### ISSUE TITLE
security/acme-client: missing control bar for System Log

### ISSUE THREAD

**Issue by Starkstromkonsument** [opnsense/plugins#3119]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
The control bar

![image](https://user-images.githubusercontent.com/53019449/189497644-0c3fce40-6459-46ea-804f-1f904ca7434c.png)

is missing at  'Services --> ACME Client --> Log Files --> System Log':

![image](https://user-images.githubusercontent.com/53019449/189497772-8e81eb6f-5492-4642-a609-3346657e8bea.png)

It is only shown at 'Services --> ACME Client --> Log Files --> ACME Log':

![image](https://user-images.githubusercontent.com/53019449/189497751-9e6a4e95-48df-4ee2-a838-a21b451f0f38.png)

**To Reproduce**
1. Go to 'Services --> ACME Client --> Log Files --> System Log'
2. See error (missing control bar)

**Expected behavior**
Seeing the control bar.

**Screenshots**
See above.

**Relevant log files**
System Log, ACME Log.

**Additional context**
None.

**Environment**
OPNsense 22.7.4-amd64

**Comment by fraenki** [comment]
Yes, it is hidden because it does not work when integrated into the plugin. If someone knows how to fix this... let me know :)
