### ISSUE TITLE
net/firewall: Gateway Groups not available

### ISSUE THREAD

**Issue by ansibleguy** [opnsense/plugins#3139]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
Plugin version used: 1.2
The os-firewall automation-rules do not allow gateway-groups to be selected (as gateway).

If one tries to set a gw-group via API there is no error response.
The gateway of the processed rule is set to 'none'.

**To Reproduce**
1. Add a gateway group in 'System - Gateways - Group'
2. Install the plugin os-firewall
3. Try selecting the before created gw-group as target gateway for a rule in 'Firewall - Automation - Filter'

**Expected behavior**
Being able to select gateway groups as target gateway for those rules as this is an important functionality.

**Screenshots**
Per example:
1. automation rules
![automation_rules](https://dl.ansibleguy.net/collection_opnsense/gw_automation_rules.png)
2. default rules
![default_rules](https://dl.ansibleguy.net/collection_opnsense/gw_webui_rules.png)

**Additional context**
This is a very commonly used functionality and therefore it would be nice for it to be available using the API.
Lack of this functionality makes the API management unusable in many practical use-cases and environments. (_WAN-/VPN-Failover and so on.._)

**Comment by sbobber** [comment]
Same issue on:
OPNsense 22.7.7_1-amd64
FreeBSD 13.1-RELEASE-p3
OpenSSL 1.1.1s 1 Nov 2022

**Comment by AdSchellevis** [comment]
@sbobber can't be an issue if it's a feature request, but feel free to open a PR

**Comment by sbobber** [comment]
@AdSchellevis understood, would be great, thanks
