### ISSUE TITLE
net/firewall: Aliases in use can be deleted

### ISSUE THREAD

**Issue by ansibleguy** [opnsense/plugins#3140]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
Plugin version in use: 1.2

Aliases that are referenced in os-firewall automation-rules can be deleted.

I would think that this behaviour could break the ruleset (?) or at least bring problems with it.

As this problem is directly linked to the os-firewall rules I guessed the issue belongs to the plugins-repository.

**To Reproduce**
1. Install the 'os-firewall' plugin
2. Create a host-alias in 'Firewall - Aliases'
3. Create a rule that uses the alias in 'Firewall - Automation - Filter'
4. Save the rules
5. Go back to 'Firewall - Aliases' and delete the alias
6. Now the rule exists and references a non-existent alias

**Expected behavior**
The deletion of the referenced alias should not be possible.

The user 'Fright' in the OPNSense forum mentioned the following:

> may be additional check (in Filter model) should be added at
https://github.com/opnsense/core/blob/7601e9cab3badfd78673bee3f486f8cb9f092266/src/opnsense/mvc/app/models/OPNsense/Firewall/Alias.php#L129

Reference: https://forum.opnsense.org/index.php?topic=30077.msg145270#msg145270

**Environment**
OPNsense 22.7.4-amd64
FreeBSD 13.1-RELEASE-p2
OpenSSL 1.1.1q 5 Jul 2022
Common KVM processor (4 cores, 4 threads)
Hypervisor: Promox PVE

**Comment by AdSchellevis** [comment]
We don't have a mechanism in place for handling constraints originating from plugins automatically in this case, but since this is only a single plugin managed by us, I don't mind adding the optional config path the list so it does check for our `os-firewall` plugin
