### ISSUE TITLE
Please extend acme.sh's webhook automatiuon "Upload certificate via SFTP" with DEPLOY_SSH_REMOTE_CMD

### ISSUE THREAD

**Issue by Lay3r3ight** [opnsense/plugins#3146]
- [*] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [*] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [*] When the request is meant for an existing plugin, I've added its name to the title.

_**Is your feature request related to a problem? Please describe.**_

When adding a "Upload certificate via SFT"-Automation, its only possible to upload certificates with this task, but its not possible to perform a command. 

In most cases, after uploading fresh certificates, its necessary to restart a service to use the fresh certs, so one must add a second automation process to restart the service.

_**Describe the solution you'd like**_

Would be nice to upload certs and perform commands in one task. 

Please add a (optional) form field so that we can enter one or more commands to the automation task.

Basic solution would be, that the cmd will be performed after the certificates are uploaded.

Premium solution would be, that you can perform commands before and after the upload. For example, to backup the old cert before uploading new ones or maybe i guess sometimes it could be necessary to stop services, before uploading new certs. But i am not sure if this is possible with current acme version.

_**Additional context**_

This is the current form

![grafik](https://user-images.githubusercontent.com/28432815/193475431-e2d8e4a4-8fbb-4c14-b049-787f1167ad25.png)

DEPLOY_SSH_REMOTE_CMD is described here:

https://github.com/acmesh-official/acme.sh/wiki/deployhooks

**Comment by fraenki** [comment]
> Basic solution would be, that the cmd will be performed after the certificates are uploaded. Premium solution would be, that you can perform commands before and after the upload.

Both is already possible with Automation `Remote command via SSH`. You may add as many Automations as you want, and run them in the desired order (by sorting them accordingly in the Certificate GUI). :)
