### ISSUE TITLE
dns/ddclient: add njal.la

### ISSUE THREAD

**Issue by dabruh** [opnsense/plugins#3151]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
I am unable to use Dynamic DNS with Njalla.

**Describe the solution you'd like**
ddclient recently merged code for njal.la support into the master branch. I suggest using it: https://github.com/ddclient/ddclient/pull/459

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by satrapes** [comment]
Hello,
A pull request is already opened and another issue.
https://github.com/opnsense/plugins/pull/3129
