### ISSUE TITLE
security/acme-client: auto-renew is failing after restoring config.xml

### ISSUE THREAD

**Issue by mnaiman** [opnsense/plugins#3154]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
auto-renew is failing with domain validation - http01

**To Reproduce**
1. create certificate and successfully issue via HTTP01 challenge
2. set debug3 level for letsencrypt to get max info
3. wait around 60-70 days to for getting to expire range (max 90 days)
4. Cron job will start renew
5. Error

**Working workaround**
1. Push force renew certificate
2. Enjoy renewed certificate

**Expected behavior**
Renewed certificate using cron job

**Screenshots**
N/A

**Relevant log files**
```
[Thu Oct  6 22:43:07 CEST 2022] _is_idn_d='mail.domain1.com'
[Thu Oct  6 22:43:07 CEST 2022] _idn_temp
[Thu Oct  6 22:43:07 CEST 2022] _is_idn_d='mail.domain2.com'
[Thu Oct  6 22:43:07 CEST 2022] _selectServer try snames='zerossl.com,zerossl'
[Thu Oct  6 22:43:07 CEST 2022] _selectServer try snames='letsencrypt.org,letsencrypt'
[Thu Oct  6 22:43:07 CEST 2022] _selectServer match letsencrypt
[Thu Oct  6 22:43:07 CEST 2022] Selected server: https://acme-v02.api.letsencrypt.org/directory
[Thu Oct  6 22:43:07 CEST 2022] readlink exists=0
[Thu Oct  6 22:43:07 CEST 2022] dirname exists=0
[Thu Oct  6 22:43:07 CEST 2022] Lets find script dir.
[Thu Oct  6 22:43:07 CEST 2022] _SCRIPT_='/usr/local/sbin/acme.sh'
[Thu Oct  6 22:43:07 CEST 2022] _script='/usr/local/sbin/acme.sh'
[Thu Oct  6 22:43:07 CEST 2022] _script_home='/usr/local/sbin'
[Thu Oct  6 22:43:07 CEST 2022] Using config home:/var/etc/acme-client/home
[Thu Oct  6 22:43:07 CEST 2022] ACCOUNT_CONF_PATH='/var/etc/acme-client/accounts/61030d6995be36.79313309_prod/account.conf'
[Thu Oct  6 22:43:07 CEST 2022] logger exists=0
touch: /var/etc/acme-client/accounts/61030d6995be36.79313309_prod/account.conf: No such file or directory
grep: /var/etc/acme-client/accounts/61030d6995be36.79313309_prod/account.conf: No such file or directory
grep: /var/etc/acme-client/accounts/61030d6995be36.79313309_prod/account.conf: No such file or directory
[Thu Oct  6 22:43:07 CEST 2022] APP
/usr/local/sbin/acme.sh: cannot create /var/etc/acme-client/accounts/61030d6995be36.79313309_prod/account.conf: No such file or directory
grep: /var/etc/acme-client/accounts/61030d6995be36.79313309_prod/account.conf: No such file or directory
[Thu Oct  6 22:43:07 CEST 2022] 
[Thu Oct  6 22:43:07 CEST 2022] LE_WORKING_DIR='/var/etc/acme-client/home'
https://github.com/acmesh-official/acme.sh
v3.0.4
[Thu Oct  6 22:43:07 CEST 2022] Using server: letsencrypt
[Thu Oct  6 22:43:07 CEST 2022] Running cmd: renew
[Thu Oct  6 22:43:07 CEST 2022] Using config home:/var/etc/acme-client/home
[Thu Oct  6 22:43:07 CEST 2022] ACCOUNT_CONF_PATH='/var/etc/acme-client/accounts/61030d6995be36.79313309_prod/account.conf'
[Thu Oct  6 22:43:07 CEST 2022] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Thu Oct  6 22:43:07 CEST 2022] _ACME_SERVER_HOST='acme-v02.api.letsencrypt.org'
[Thu Oct  6 22:43:07 CEST 2022] _ACME_SERVER_PATH='directory'
[Thu Oct  6 22:43:07 CEST 2022] CA_CONF='/var/etc/acme-client/home/ca/acme-v02.api.letsencrypt.org/directory/ca.conf'
[Thu Oct  6 22:43:07 CEST 2022] DOMAIN_PATH='/var/etc/acme-client/home/'mail.domain1.com_ecc'
[Thu Oct  6 22:43:07 CEST 2022] Renew: ''mail.domain1.com'
[Thu Oct  6 22:43:07 CEST 2022] ''mail.domain1.com' is not an issued domain, skip.
```

**Additional context**
In Log-General there is this row

`AcmeClient: running acme.sh command: /usr/local/sbin/acme.sh --renew --syslog 7 --debug 3 --server 'letsencrypt' --webroot /var/etc/acme-client/challenges --home '/var/etc/acme-client/home' --certpath '/var/etc/acme-client/certs/6117dcb3410bd3.19217795/cert.pem' --keypath '/var/etc/acme-client/keys/6117dcb3410bd3.19217795/private.key' --capath '/var/etc/acme-client/certs/6117dcb3410bd3.19217795/chain.pem' --fullchainpath '/var/etc/acme-client/certs/6117dcb3410bd3.19217795/fullchain.pem' --domain 'mail.domain1.com' --domain 'mail.domain2.com' --days '1' --ocsp --keylength 'ec-384' --ecc --accountconf '/var/etc/acme-client/accounts/61030d6995be36.79313309_prod/account.conf'`

Actual domains where replaced by mail.domain1.com and mail.domain2.com

Similar was reported and unresolved here https://github.com/opnsense/plugins/issues/2394 and here https://github.com/opnsense/plugins/issues/2007

**Environment**
OPNsense 22.07 - fully updated

**Comment by mnaiman** [comment]
Noticed in last two rows in log - 2 single quotes Renew: ''mail.domain1.com'
Could this be an issue?

**Comment by mnaiman** [comment]
> Noticed in last two rows in log - 2 single quotes Renew: ''mail.domain1.com' Could this be an issue?

No, wrong lead - it was duplicated during domain anonymization.

**Comment by mnaiman** [comment]
Similar problem was reported here https://github.com/opnsense/plugins/issues/2007

**Comment by mnaiman** [comment]
Even people with DNS challenge have same issue https://forum.opnsense.org/index.php?topic=30249.0

**Comment by mnaiman** [comment]
Same issue here https://forum.opnsense.org/index.php?topic=21085.0

All my certificates have selected ECC and Must staple

![image](https://user-images.githubusercontent.com/2264442/194604166-91646579-3bf7-4fb7-a7eb-e1da0357a6fc.png)

**Comment by zulasch** [comment]
I can confirm that also DNS verification is also affected and not working. Only manualy renew is working.

**Comment by fraenki** [comment]
> /usr/local/sbin/acme.sh: cannot create /var/etc/acme-client/accounts/61030d6995be36.79313309_prod/account.conf: No such file or directory

Files which are required for Acme Client are not available and cannot be created. There is something wrong with your OPNsense installation.

Did you restore a backup of OPNsense? Did you experience a filesystem corruption or system crashes? Did you manually remove any files from `/var/etc/acme-client`?

Your OPNsense system needs to be fixed/repaired in order to fix Acme Client.

**Comment by mnaiman** [comment]
No system crashes, or corruption(it is VPS in cloud), no manual removal of files from file system.
Yes system was haf year ago reinstalled because of ZFS support to new version and config.xml was restored.

Missing account.conf is probably not restored during restore process, because in GUI I have account OK.
![image](https://user-images.githubusercontent.com/2264442/195086444-cc73356d-d713-4629-bb83-8ddce088f454.png)

Now I used button "Register account"
![image](https://user-images.githubusercontent.com/2264442/195086979-b9af6bd3-059b-4894-b0a4-dde898d176bb.png)

And files are there
root@opnsense:~ # ls /var/etc/acme-client/accounts/61030d6995be36.79313309_prod/
account.conf    account.key

Now autorenew is not complaining about missing folders anymore, but issue is still there and renew is not working

```
[Tue Oct 11 14:20:52 CEST 2022] _is_idn_d='mail.domain1.com'
[Tue Oct 11 14:20:52 CEST 2022] _idn_temp
[Tue Oct 11 14:20:52 CEST 2022] _is_idn_d='mail.domain2.com'
[Tue Oct 11 14:20:52 CEST 2022] _idn_temp
[Tue Oct 11 14:20:52 CEST 2022] _selectServer try snames='zerossl.com,zerossl'
[Tue Oct 11 14:20:52 CEST 2022] _selectServer try snames='letsencrypt.org,letsencrypt'
[Tue Oct 11 14:20:52 CEST 2022] _selectServer match letsencrypt
[Tue Oct 11 14:20:52 CEST 2022] Selected server: https://acme-v02.api.letsencrypt.org/directory
[Tue Oct 11 14:20:52 CEST 2022] readlink exists=0
[Tue Oct 11 14:20:52 CEST 2022] dirname exists=0
[Tue Oct 11 14:20:52 CEST 2022] Lets find script dir.
[Tue Oct 11 14:20:52 CEST 2022] _SCRIPT_='/usr/local/sbin/acme.sh'
[Tue Oct 11 14:20:52 CEST 2022] _script='/usr/local/sbin/acme.sh'
[Tue Oct 11 14:20:52 CEST 2022] _script_home='/usr/local/sbin'
[Tue Oct 11 14:20:52 CEST 2022] Using config home:/var/etc/acme-client/home
[Tue Oct 11 14:20:52 CEST 2022] ACCOUNT_CONF_PATH='/var/etc/acme-client/accounts/61030d6995be36.79313309_prod/account.conf'
[Tue Oct 11 14:20:52 CEST 2022] logger exists=0
[Tue Oct 11 14:20:52 CEST 2022] OK
[Tue Oct 11 14:20:52 CEST 2022] 2:SYS_LOG='7'
[Tue Oct 11 14:20:52 CEST 2022] LE_WORKING_DIR='/var/etc/acme-client/home'
https://github.com/acmesh-official/acme.sh
v3.0.4
[Tue Oct 11 14:20:52 CEST 2022] Using server: letsencrypt
[Tue Oct 11 14:20:52 CEST 2022] Running cmd: renew
[Tue Oct 11 14:20:52 CEST 2022] Using config home:/var/etc/acme-client/home
[Tue Oct 11 14:20:52 CEST 2022] ACCOUNT_CONF_PATH='/var/etc/acme-client/accounts/61030d6995be36.79313309_prod/account.conf'
[Tue Oct 11 14:20:52 CEST 2022] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Tue Oct 11 14:20:52 CEST 2022] _ACME_SERVER_HOST='acme-v02.api.letsencrypt.org'
[Tue Oct 11 14:20:52 CEST 2022] _ACME_SERVER_PATH='directory'
[Tue Oct 11 14:20:52 CEST 2022] CA_CONF='/var/etc/acme-client/accounts/61030d6995be36.79313309_prod/ca.conf'
[Tue Oct 11 14:20:52 CEST 2022] DOMAIN_PATH='/var/etc/acme-client/home/mail.domain1.com_ecc'
[Tue Oct 11 14:20:52 CEST 2022] Renew: 'mail.domain1.com'
[Tue Oct 11 14:20:52 CEST 2022] 'mail.domain1.com' is not an issued domain, skip.
```

Further digging folder /var/etc/acme-client/home/mail.domain1.com_ecc is not present, thats why  it complains it is not issued domain.

**Comment by mnaiman** [comment]
Now I hit at one affected certificate forcefully issue or renew certificate button and it run above command
/usr/local/sbin/acme.sh --renew --syslog 7 --debug 3 --server 'letsencrypt' --webroot /var/etc/acme-client/challenges --home '/var/etc/acme-client/home' --certpath '/var/etc/acme-client/certs/6117dcb3410bd3.19217795/cert.pem' --keypath '/var/etc/acme-client/keys/6117dcb3410bd3.19217795/private.key' --capath '/var/etc/acme-client/certs/6117dcb3410bd3.19217795/chain.pem' --fullchainpath '/var/etc/acme-client/certs/6117dcb3410bd3.19217795/fullchain.pem' --domain 'mail.domain1.com' --domain 'mail.domain2.com' --days '1' --force --ocsp --keylength 'ec-384' --ecc --accountconf '/var/etc/acme-client/accounts/61030d6995be36.79313309_prod/account.conf'

This time with --force parameter. It went ok, No complain about not issued domain and folder mail.domain1.com_ecc in /var/etc/acme-client/home/ was created.

So after restore from backup config.xml it should reregister account and force reissue all certificates to put installation to correct state.

**Comment by mnaiman** [comment]
You are genius :)
After using "Reset ACME client" button (I was always wandering about its purpose :) ), all certificates were reissued ok.

It would be great for opnsense to run that command automatically after restore of xml, like PostRestoreAction.

**Comment by fraenki** [comment]
> It would be great for opnsense to run that command automatically after restore of xml, like PostRestoreAction.

I agree, but AFAICT there's nothing like this available.
