### ISSUE TITLE
[os-nginx] Enabling PROXY protocol does not act as expected and is broken

### ISSUE THREAD

**Issue by Zoarial94** [opnsense/plugins#3159]
- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
This issue is similar to #2809, but with another issue and more information. 
The option "PROXY Protocol" is not descriptive enough to understand what it really does, and it is likely not doing what the user wants or expects. For either an HTTP server or Data Stream, there are not enough options to properly configure the server to a user's needs.

Currently, this plugin also does not enable receiving the PROXY Protocol on the configured HTTPS port, but does enable it for the configured HTTP port. 

**To Reproduce**
### For HTTP Servers
1. Go to the Nginx configuration page
2. Click on the drop-down option on the 'HTTP(S)' tab
3. Select the 'HTTP Server' option
4. Edit an existing server, or create a new server
5. Check the 'advanced mode' toggle
6. Enable the 3th option from the top: 'PROXY Protocol'

### For Data Streams:
1. Go to the Nginx configuration page
3. Select the 'Data Streams'
4. Edit an existing stream, or create a new server
6. Enable the 5th option from the top: 'PROXY Protocol'

**Expected behavior**
For ~HTTP Servers, and~ Data Streams, the PROXY Protocol options should be split between a receiving option, and sending option.
> HTTP Servers only support receiving the PROXY Protocol

On a Data Stream, for example, I should be able to received data from a down stream source using the PROXY protocol, and then proxy the data to the upstream without the PROXY Protocol. The opposite should also be possible. 

The [Nginx documentation](https://docs.nginx.com/nginx/admin-guide/load-balancer/using-proxy-protocol/) has a some information about the PROXY Protocol, but I am concerned with 2 pieces of information in this issue.

- To receive the PROXY Protocol, the `proxy_protocol` parameter needs to be added to the `listen` directive.
  - Users should get a warning when this option is selected on a HTTP Server. It could cause unexpected issues if other virtual hosts share the same ports. 
- The send the PROXY Protocol, you need to have the line `proxy_protocol on;` in conjunction with a `proxy_pass example.com;` directive (Data Streams Only)

This amount of configuration is important because the PROXY Protocol is not a part of the HTTP protocol; the proxy data is inserted before the HTTP data on the TCP level. This means when the PROXY Protocol is used to send data, it is **not compatible** unless the receiver is configured to receive the PROXY Protocol. The reverse it also true. (These statements are true as far as I am aware with current implementations in various applications)

#### Important Note
It is not possible, at least with Nginx, to conditionality receive the PROXY Protocol on a single port. This may cause unexpected behavior when you have virtual hosts listening on 443, but only one listens for the PROXY Protocol 
Take the following example:
```
server {
  listen 443 ssl proxy_protocol;
  server_name sub1.example.com;
}
server {
  listen 443 ssl;
  server_name sub2.example.com;
}
```
In this example, connecting to sub1.example.com or sub2.example.com **REQUIRE a connection using the PROXY Protocol** because they share the same port. Using different ports would allow for one to use the PROXY Protocol and the to use a standard HTTP connection.

## Depending on how this would be implemented, end users will likely have broken configurations as soon as they upgrade. 
- ~For HTTP Servers, I would recommend migrating the currently 'PROXY Protocol' option to the 'Enable PROXY Protocol for upstream' keeping the user selection, and then have the new 'Enable PROXY Protocol for downstream' option default to false.~
- For HTTP Servers, I would recommend migrating the currently 'PROXY Protocol' option to 'Enable PROXY Protocol for downstream' and default it to false regardless of the current user choice.
- For Data Streams, I would recommend migrating the currently 'PROXY Protocol' option to both of the new options keeping the user's selection for both. 
This would most accurately reflect the current implementation and (hopefully) prevent the most amount of headaches. 

I am currently not familiar enough with the OPNSense frontend to provide a meaningful pull request. 

**Environment**

OPNsense 22.7.5-amd64
FreeBSD 13.1-RELEASE-p2
OpenSSL 1.1.1q 5 Jul 2022

**Comment by kulikov-a** [comment]
I thought that enabling the PROXY protocol for the upstream connection is possible only for streams
(and this is implemented in the plugin)

**Comment by Zoarial94** [comment]
Wow. Somehow I missed that. You are correct. 

The streams still need to have the options split into two (sending and receiving PROXY), and I also found another issue. The 'Trusted Proxies' in a Stream Server do not work. The set_real_ip_from directive does not seem to work in streams, despite the what the Nginx documentation says.

**Comment by kulikov-a** [comment]
> options split into two (sending and receiving PROXY)

there is separate "PROXY protocol" checkbox in Upstream settings. 
I will try to check if the directives are generated correctly, but at first glance everything looks fine.

> The 'Trusted Proxies' in a Stream Server do not work. The set_real_ip_from directive does not seem to work in streams, despite the what the Nginx documentation says.

oops! nginx does not build with `--with-stream_realip_module`
moreover, I don't see such an option in port
i can see it in nginx-devel port:
https://github.com/freebsd/freebsd-ports/blob/bb1004269594ee8e7c6ac2d63fd981a55c8e7000/www/nginx-devel/Makefile#L182
but not in nginx port (https://github.com/freebsd/freebsd-ports/blob/main/www/nginx/Makefile)

will be glad if more understanding guys correct me

**Comment by Zoarial94** [comment]
Thank you for taking the time to look at this. This has been a bit of a headache for me for a while, and I just needed to get an issue opened. I hope I am not coming across wrong in any of my wording. I really appreciate everything which is being provided by the OPNSense team. 

[This line](https://github.com/opnsense/plugins/blob/abf01bff99e019b31792cf3489372f07e0c33653/www/nginx/src/opnsense/service/templates/OPNsense/Nginx/streams.conf#L103) is where `proxy_protocol on` is generated. Should it use `upstream.proxy_protocol` in the condition instead?

**Comment by kulikov-a** [comment]
@Zoarial94 yes, the templates require a little tweaking (both in terms of the ssl listener for incoming PROXY proto and in terms of streams part for outgoing). Im preparing a pr for another question from forum ([link](https://forum.opnsense.org/index.php?topic=30547.0)) and will try to include this part there as well.
but I have no idea what to do with the lack of support for adding a STREAM_REALIP module in the port (if I correctly identify the problem).
@fichtner Hi! Could you please suggest the best way in this case? Ask @joneum about it? Open ticket on bugzilla (no experience)? Or are there other options? thanks!
