### ISSUE TITLE
os-nginx: Add option for upstream keepalive

### ISSUE THREAD

**Issue by sigurdvaa** [opnsense/plugins#3162]
**Important notices**  
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**  
For performance tuning I would like to be able to enable keepalive for upstream connections.

**Describe the solution you'd like**  
Two new options in Upstream:  
* Keepalive: how many connections to keep alive upstream (0 or empty for disabled)
* Keepalive Timeout: how long to wait for closing an idle upstream connection

**Describe alternatives you've considered**  
Not really any alternatives, as the keepalive directive must be set in the `upstream` context, which will be overwritten when pressing Apply in the WebUI.

**Additional context**
This will require two new directives in the `upstream` context and two in the `location` context when upstream keepalive is enabled:
`upstream`
* keepalive [int];
* keepalive_timeout [int];

`location`
* proxy_http_version 1.1;
* proxy_set_header Connection "";

**Comment by 1249993110** [comment]
I also need proxy_http_version.
