### ISSUE TITLE
WireGuard: "wg genpsk" command in GUI

### ISSUE THREAD

**Issue by Wr1gleys** [opnsense/plugins#3164]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
When adding a new Endpoint (peer) there is field called "Shared Secret" which will stay empty by default. To use this PSK, as another layer of security, CLI access is needed and the output of command "wg genpsk" needs to be copied over to the GUI. 

Is there an option to implement such kind of a button for that in the GUI?

Reference to my Opnsense Forum post:
https://forum.opnsense.org/index.php?topic=30629.0

**Describe alternatives you've considered**
@mimugmail mentioned in the Forum: https://forum.opnsense.org/index.php?topic=30629.msg147754#msg147754

> _"We could add a Tools tab and add some buttons with such commands :)"_

That would also be sufficient and highly appreciated.

**Additional context**
Many thanks for your hard work! I'm in love with OPNsense 🥇 👍

**Comment by oscarsmx** [comment]
Agreed. Pfsense has this button within the actual preshared field to auto generate from the gui. which it's actually helpful.
