### ISSUE TITLE
Add export/import of whitelists in dnscrypt-proxy

### ISSUE THREAD

**Issue by L1ghtn1ng** [opnsense/plugins#3170]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**

It's frustrating having to set your whitelist of domains you want to not be blocked by the DNSBL on a new install. 

**Describe the solution you'd like**
I would like the ability to be able to export/import the entries that have been white listed from an easy of setup and backup stand point. 

**Describe alternatives you've considered**

None

**Additional context**

**Comment by mimugmail** [comment]
Hm, usually when using a single field for multiple values after a couple of month someone needs this and that and everything needs to get migrated to a grid view. Now its vice versa :)
