### ISSUE TITLE
os-wireguard: wireguard-go uses /dev/tunX,  new openvpn-server config fails

### ISSUE THREAD

**Issue by chrstnth** [opnsense/plugins#3171]
[✓] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
[✓] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
[✓] The title contains the plugin to which this issue belongs

11 openvpn-server Instances and 2 wireguard instances are running on the Firewall. When i create a new openvpn-server instance, this instance is unreachable.

**To Reproduce:**
1.) Install OPNsense and install os-wireguard
2.) under VPN:OpenVPN:Servers 11 instances
3.) under VPN:WireGuard create and enable 2 local instances
4.) reboot OPNsense
5.) create a new VPN:OpenVPN:Servers instance
6.) In Webgui the new instance themes find, but openvpn-server ist unreachable

Logs while creating openvpn-instance 12:

> <11>1 2022-10-24T11:07:06+02:00 rtr.lan php 60786 - [meta sequenceId="1"] /vpn_openvpn_server.php: The command '/sbin/ifconfig 'tun12' name 'ovpns12'' returned exit code '1', the output was 'ifconfig: interface tun12 does not exist'                                                                                                                                    
<11>1 2022-10-24T11:07:06+02:00 rtr.lan php 60786 - [meta sequenceId="2"] /vpn_openvpn_server.php: The command '/sbin/ifconfig 'ovpns12' group openvpn' returned exit code '1', the output was 'ifconfig: interface ovpns12 does not exist'                                                                                                                                 
<11>1 2022-10-24T11:07:06+02:00 rtr.lan php 60786 - [meta sequenceId="3"] /vpn_openvpn_server.php: The command '/sbin/route -q delete 10.0.10.49' returned exit code '1', the output was 'route: route has not been found'                                                                                                                                                  
<13>1 2022-10-24T11:07:06+02:00 rtr.lan configctl 38867 - [meta sequenceId="4"] event @ 1666602426.04 msg: Oct 24 11:07:06 rtr.lan config[60786]: [2022-10-24T 11:07:06+02:00][INFO] config-event: new_config /conf/backup/config-1666602425.8506.xml                                                                                                        
<13>1 2022-10-24T11:07:06+02:00 rtr.lan configctl 38867 - [meta sequenceId="5"] event @ 1666602426.04 exec: system event config_changed                                       
<11>1 2022-10-24T11:07:16+02:00 rtr.lan php 60786 - [meta sequenceId="6"] /vpn_openvpn_server.php: OpenVPN server 12 instance start timed out.                                
<11>1 2022-10-24T11:07:17+02:00 rtr.lan opnsense 14122 - [meta sequenceId="7"] /usr/local/etc/rc.filter_configure: ROUTING: keeping current default gateway '192.168.101.1'   

**Expected behavior:**
A working openvpn-server instance

Problem seems to be a already used /dev/tun device. openvpn tries to allocate the next free /dev/tun12 device:

> root@rtr:~ # head /var/etc/openvpn/server12.conf
dev ovpns12
verb 1
dev-type tun
dev-node **/dev/tun12**
writepid /var/run/openvpn_server12.pid

This device is already in use by wireguard-go:

> root@rtr:~ # lsof /dev/tun12 
COMMAND     PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
wireguard 80096 root    3u  VCHR  0,137      0t0  137 /dev/tun12

just to verify:

> root@rtr:~ # ./lsof -p 80096
COMMAND     PID USER   FD     TYPE             DEVICE SIZE/OFF   NODE NAME
wireguard 80096 root  txt     VREG               0,99  2523136   5132 /usr/local/bin/wireguard-go (/dev/ufs/OPNsense_Nano)
wireguard 80096 root  cwd     VDIR               0,99      512      2 / (/dev/ufs/OPNsense_Nano)
wireguard 80096 root  rtd     VDIR               0,99      512      2 / (/dev/ufs/OPNsense_Nano)
wireguard 80096 root    0r    VCHR               0,27      0t0     27 /dev/null (devfs)
wireguard 80096 root    1r    VCHR               0,27      0t0     27 /dev/null (devfs)
wireguard 80096 root    2r    VCHR               0,27      0t0     27 /dev/null (devfs)
wireguard 80096 root    3u    VCHR              0,137      0t0    137 **/dev/tun12** (devfs)
wireguard 80096 root    5u  KQUEUE 0xfffff800587d7200                 count=0, state=0x2
wireguard 80096 root    6u    PIPE 0xfffff80058618000    16384        ->0xfffff80058618160
wireguard 80096 root    7u    PIPE 0xfffff80058618160     4096        ->0xfffff80058618000
wireguard 80096 root    8u     rte                         0t0        no protocol control block
wireguard 80096 root    9u    unix 0xfffff8001e2a1b10      0t0        /var/run/wireguard/wg2.sock
wireguard 80096 root   10u     rte                         0t0        no protocol control block
wireguard 80096 root   11u  KQUEUE 0xfffff800587d7300                 count=0, state=0x2
wireguard 80096 root   12r    VDIR               0,99      512 507483 /var/run/wireguard (/dev/ufs/OPNsense_Nano)
wireguard 80096 root   13u    IPv4 0xfffff8001e659d90      0t0    UDP *:47001
wireguard 80096 root   14u    IPv6 0xfffff8001e0c69b0      0t0    UDP *:47001

try to start on cli:
> root@rtr:~ # /usr/local/sbin/openvpn --config /var/etc/openvpn/server12.conf
2022-10-24 13:12:48 Cipher negotiation is disabled since neither P2MP client nor server mode is enabled
2022-10-24 13:12:48 OpenVPN 2.5.7 amd64-portbld-freebsd13.1 [SSL (OpenSSL)] [LZO] [LZ4] [MH/RECVDA] [AEAD] built on Jul 25 2022
2022-10-24 13:12:48 library versions: OpenSSL 1.1.1q  5 Jul 2022, LZO 2.10
2022-10-24 13:12:48 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
2022-10-24 13:12:48 Cannot open TUN/TAP dev /dev/tun12: Device busy (errno=16)
2022-10-24 13:12:48 Exiting due to fatal error

I'm new to OPNsense, so I don't know the boot process in detail. Just to guess what happens:
- openvpn 1-11 starts and use /dev/tun1 to /dev/tun11
- wireguard-go use first /dev/tun0
- the next wireguard-go instance use /dev/tun12
- openvpn don't know anything about the blocked /dev/tun12 device and tries to use it.

**Environment**
OPNsense 22.7.6 (amd64, OpenSSL).
AMD GX-412TC SOC
os-wireguard 1.12

**Comment by fichtner** [comment]
Due to both OpenVPN and WireGuard using "tun" interfaces the implementation limitation is that /dev/tunX nodes are static so more than one service using "tun" will eventually break. You can perhaps use `wireguard-kmod` and sidestep this. Otherwise there isn't anything we intend to do about it.


Cheers,
Franco

**Comment by chrstnth** [comment]
Did a test on two other OPNsense firewalls. wireguard-kmod works very well. No tun conflicts any more. Thank you!
