### ISSUE TITLE
bgp update-source option missing or overwritten in os-frr (gui)

### ISSUE THREAD

**Issue by zagi-tng** [opnsense/plugins#3178]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X ] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [ X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X] The title contains the plugin to which this issue belongs

**Describe the bug**
Can't set source IPv6 address for BGP neigbour from which to start BGP session.
Using CARP to make IPv6 failover on vlan01 interface. CIDR is /120

I can only set interface:

neighbor X:X:X:1 interface vlan01

but not :
neighbor X:X:X:1 update-source X:X:X:X 

And then the bgp peer session is started from WAN interface IPv6, not the VIP one.
This worked in pfsense version of frr.

**To Reproduce**
1. If i add this option via vtysh it works till next time i use FRR via GUI
2.  https://opnsense/ui/quagga/diagnostics/bgp

**Expected behavior**
Local host: 2X:X:1:1::21:2
Foreign host: 2X:X:1:1::21:1, Foreign port: 179

**Relevant log files**
  Connections established 0; dropped 0
  Last reset 03:13:16,   Notification received (Cease/Connection Rejected)

**Additional context**
VIP is ::21:2
OPN1 has ::21:20
OPN2 has ::21:21

**Environment**
OPNsense 22.7.6-amd64
FreeBSD 13.1-RELEASE-p2
OpenSSL 1.1.1q 5 Jul 2022
Intel(R) Atom(TM) CPU C3558 @ 2.20GHz (4 cores, 4 threads)

**Comment by ansibleguy** [comment]
Hello.

I might be wrong, but I think this is related to [issue 3179](https://github.com/opnsense/plugins/issues/3179).

\- AnsibleGuy

**Comment by zagi-tng** [comment]
> 

Hi

Using NAT on outbound BGP session is not possible on IPv6. :)
Now i run BGP w/ FRR, but w/o os-frr (gui) because 

- it ignores/deletes "update-source" in config if i added it via vtysh
- os-frr (bgp neighbour section) tself does not have update-source option


and all of this worked in pfsense/frr. :)

**Comment by NielsPiersma** [comment]
> Hello.
> 
> I might be wrong, but I think this is related to [issue 3179](https://github.com/opnsense/plugins/issues/3179).
> 
> - AnsibleGuy

@ansibleguy , you are correct, it is the same, but I didn't notice this as it was regarding IPv6.
Anyone, pls feel free to merge these tickets.
NIels

**Comment by mimugmail** [comment]
We could use the localip field which was introduced for MD5 passwords
