### ISSUE TITLE
net/freeradius: add daily session limit feature to FreeRADIUS and GUI

### ISSUE THREAD

**Issue by borisneubert** [opnsense/plugins#318]
[The howto on accounting with FreeRADIUS](https://docs.opnsense.org/manual/how-tos/accounting.html) shows how to setup accounting. The Max-Daily-Session attribute cannot be set, though, in the FreeRADIUS plugin on OPNsense (see section "Add test users" in the howto). This is probably a much sought for feature and I kindly ask to add it.

**Comment by mimugmail** [comment]
Sure, no problem. I'm waiting for a few changes to come, after this I'll add it.

**Comment by mimugmail** [comment]
Do you want to use the Max Daily attribute with CP? I will add this now but unsure if compatible with CP

**Comment by borisneubert** [comment]
Max-Daily-Session should be used with Captive Portal. To make this work as expected, Captive Portal needs to reauthenticate connected users every minute and the admin should set Idle Timeout in Zone to a reasonable value.

**Comment by mimugmail** [comment]
Yep, I already have the code, just needs some testing tomorrow :)

**Comment by mimugmail** [comment]
@borisneubert Were you able to setup the feature like in the howto described without the plugin? 
I get an error when setting a manual attribute via dictionary.

**Comment by borisneubert** [comment]
I did not try this before but I did now. I get
`Cannot find module "daily"`
which seems to come from the _daily_ entry in the _instantiate_ section of _radiusd.conf_.
Actually, _daily_ is not in _mods-available_.

**Comment by mimugmail** [comment]
Same to me, I think the howto is for a linux version, not the BSD package, but I already got this running.
If there would be a devel-package, would you install and test it, since I don't use CP?

**Comment by borisneubert** [comment]
Yes, I like to do so.

**Comment by mimugmail** [comment]
If you like to test update to 17.7.8, download a backup, and then via cli `pkg remove os-freeradius` and then `pkg install os-freeradius-devel`

**Comment by fichtner** [comment]
remove should be automatic if you install the conflicting package :)

**Comment by mimugmail** [comment]
Not via make package and pkg install ...

**Comment by borisneubert** [comment]
Did this. freeradius refuses to start, even after reboot and adding time limits in the user management of the captive portal.

radius.log

```
Thu Nov 23 18:51:47 2017 : Warning: No 'ipaddr' or 'ipv4addr' or 'ipv6addr' field found in client 192.168.31.0/24. Please fix your configuration   
Thu Nov 23 18:51:47 2017 : Warning: Support for old-style clients will be removed in a future release                                              
Thu Nov 23 18:51:47 2017 : Info: Debugger not attached                                                                                             
Thu Nov 23 18:51:47 2017 : Error: Cannot find module "daily" 
```

**Comment by fichtner** [comment]
Which version do you have installed?

    # pkg info os-freeradius-devel

**Comment by fichtner** [comment]
@mimugmail did you try "make upgrade" ?

**Comment by borisneubert** [comment]
```
root@opnsense:~ # pkg info os-freeradius-devel
os-freeradius-devel-1.3.0
Name           : os-freeradius-devel
Version        : 1.3.0
Installed on   : Thu Nov 23 18:40:25 2017 CET
Origin         : opnsense/os-freeradius-devel
Architecture   : FreeBSD:11:amd64
Prefix         : /usr/local
Categories     : net
```

**Comment by mimugmail** [comment]
Can you do a ls on mods-enabled please?

**Comment by mimugmail** [comment]
f*ck .. I forgot to add mods-enabled-counter to +TARGETS :(

**Comment by mimugmail** [comment]
`opnsense-patch -c plugins d9e4428`

Then it should start ...

**Comment by borisneubert** [comment]
This did the trick. It started.

Will test actual functionality tomorrow.

**Comment by borisneubert** [comment]
This did the trick. It started.

Will test actual functionality tomorrow.

**Comment by borisneubert** [comment]
Actual functionality does not work. Set the time limit to 120 (seconds) but have been online for hours now.

I think that is because the captive portal does not try to re-authenticate the user every minute against FreeRadius which is necessary for the portal to know that login is denied.

**Comment by mimugmail** [comment]
@AdSchellevis Any idea to this?
I add functionality to the package described like here: https://docs.opnsense.org/manual/how-tos/accounting.html

Were there some changed to the CP reauthenticating to Radius? Since I dont use it I have no idea :)

**Comment by AdSchellevis** [comment]
@mimugmail no time to read the whole thread, but accounting using radius normally works quite simple in CP.

When logged in it will check for restrictions and push them to the captive portal https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/controllers/OPNsense/CaptivePortal/Api/AccessController.php#L191-L201 then the accounting procedure will start sending accounting pages to radius back using https://github.com/opnsense/core/blob/master/src/opnsense/scripts/OPNsense/CaptivePortal/process_accounting_messages.php which is called from https://github.com/opnsense/core/blob/master/src/opnsense/scripts/OPNsense/CaptivePortal/cp-background-process.py

The main principe is that upfront you know how much time a user can spare, used to keep the session duration for the amount of time reported, then messages are send back to radius so it knows how much is actually spend.

First thing to check is if the session actually gets set with the right end time, if I'm not mistaken you will see this in the session overview, syslog should also have some details on the configd commands executed, including the set of restrictions.

**Comment by mimugmail** [comment]
@AdSchellevis thanks, seems I have to setup a test lab at work :)

**Comment by borisneubert** [comment]
This is system.log for a successful login to CP with a user with time limit:

```
Nov 25 13:31:29 opnsense configd.py: [4012472f-8a34-4d54-9bcf-9574f6c26cc6] list registered clients
Nov 25 13:31:48 opnsense configd.py: [1571ba86-771b-44b9-91f4-40f812eb33c5] list registered clients
Nov 25 13:31:48 opnsense configd.py: [4413cd22-97c1-4381-b732-d1018398fcd3] allow client access to captive portal
```

Session overview in UI shows only Username | MAC address | IP address | Connected since.

portalauth.log has

`Nov 25 13:31:48 opnsense captiveportal[82743]: AUTH neubert (192.168.35.102) zone 0`

Any place else where to look for session details?

**Comment by AdSchellevis** [comment]
I expect the radius session is missing a session timeout, which sets session_timeout in https://github.com/opnsense/core/blob/17.7.7/src/opnsense/mvc/app/library/OPNsense/Auth/Radius.php#L397 

A log line containing `set extra restrictions for session (%s) %s` is missing

**Comment by mimugmail** [comment]
@borisneubert please try `opnsense-patch -c plugins 18e4e8d`
It works in my test lab.

@AdSchellevis Max-Daily-Session has to be in the first line of the username, that's all :)

**Comment by borisneubert** [comment]
@mimugmail It works!

```
Wed Nov 29 13:34:13 2017 : Auth: (0) Login OK: [neubert/password] (from client Captive Portal port 0)
Wed Nov 29 13:38:04 2017 : Auth: (24) Invalid user (daily: Maximum daily usage time reached): [neubert/password] (from client Captive Portal port 0)
Wed Nov 29 13:38:04 2017 : Auth: (24) Login incorrect (daily: Maximum daily usage time reached): [neubert/password] (from client Captive Portal port 0)
```
The captive portal login shows "Authorization failed". Would it be possible to show the reason as well?

**Comment by mimugmail** [comment]
@borisneubert This is way over my skills, perhaps @AdSchellevis or @fichtner have an idea or a quick fix for this.

@fichtner So Freeradius 1.3.1 can go to next stable ..

**Comment by mimugmail** [comment]
This one can be closed :)
