### ISSUE TITLE
Feature Request - UPNP - Include fix for multiple consoles playing the same game

### ISSUE THREAD

**Issue by hyperenergy** [opnsense/plugins#3183]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [ X ] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [ X ] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [ X ] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**

This is a feature request to see if a fix can be added for UPNP to allow multiple gaming consoles online when playing the same game.   

**Describe the solution you'd like**

There was some discussion on the opnsense forums about a UPNP fix added to pfsense that allowed multiple gaming consoles to play the same game when utliziting UPNP:  

https://forum.opnsense.org/index.php?topic=27513.0

I couldn't find a feature request for this on GitHub so I thought I would submit one to see if the fix could be added to opnsense. 

Thanks!

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by fichtner** [comment]
I guess  this is about https://github.com/opnsense/plugins/pull/3165 and https://github.com/opnsense/ports/pull/163 ?

**Comment by hyperenergy** [comment]
Oh wow, how did I miss those?!  Yes, I think those are the same.

I guess I'll keep an eye on the the other pull requests for future updates.  Very exciting, big thank you to you and Tawmu!

**Comment by fichtner** [comment]
@hyperenergy I might have to shortcut this into a usable development version. I expect FreeBSD ports to move slowly on this front...

**Comment by fichtner** [comment]
(if this is silent please remind me again in a week)

**Comment by hyperenergy** [comment]
Hi @fichtner just checking-in as requested.  I checked the pull requests mentioned earlier and they are marked as merged/closed.  Looks exciting!

**Comment by fichtner** [comment]
Thanks, I did the necessary packaging work but https://github.com/opnsense/plugins/pull/3096 still needs to tie it all together. Latent ping for @Tawmu as well or we need to pick it up but I'd prefer the submitter to do it.
