### ISSUE TITLE
Upgrade to OPNsense 22.7.7_1-amd64 breaks Wireguard VPN

### ISSUE THREAD

**Issue by f45tb00t** [opnsense/plugins#3184]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**
After upgrading today OPNSense to OPNsense 22.7.7_1-amd64 it breaks the Wireguard VPN Plugin. I am not able anymore to start it.
Checked also the logs but did not find anything.

**To Reproduce**

1. Upgrade to recent version
2. reboot
3. Wireguard does not start anymore
4. Tunnel is not working

**Expected behavior**

WireGuard should work as usual.

**Describe alternatives you considered**

none

**Screenshots**

none

**Relevant log files**
none

**Additional context**

none

**Environment**

OPNsense 22.7.7_1-amd64

**Comment by f45tb00t** [comment]
# /usr/local/etc/rc.d/wireguard restart
wg-quick: `wg1' is not a WireGuard interface
[#] ifconfig wg create name wg1
[!] Missing WireGuard kernel support (ifconfig: SIOCIFCREATE2 (wg): Invalid argument). Falling back to slow userspace implementation.
[#] wireguard-go wg1
┌──────────────────────────────────────────────────────┐
│                                                      │
│   Running wireguard-go is not required because this  │
│   kernel has first class support for WireGuard. For  │
│   information on installing the kernel module,       │
│   please visit:                                      │
│         https://www.wireguard.com/install/           │
│                                                      │
└──────────────────────────────────────────────────────┘
[#] wg setconf wg1 /dev/stdin
Key is not the correct length or format: `fUCK0FF1'
Configuration parsing error
[#] rm -f /var/run/wireguard/wg1.sock

**Comment by mimugmail** [comment]
Are you joking??

**Comment by f45tb00t** [comment]
no, basically I am not joking. 

By a matter of fact the VPN worked flawlessly before the uprade. now it's not. The setup is basic and no tweaks no nothing.

**Comment by fichtner** [comment]
I’m sort of missing what the last working version was anyway?

**Comment by ThePowerOfDreams** [comment]
Where did `fUCK0FF1` come from?

**Comment by f45tb00t** [comment]
The "fUCK0FF1" is the preshared key. It was even working before as I upgraded OPNSense (22.7.3 => 22.7.4 => ....)

**Comment by f45tb00t** [comment]
I removed it now and it starts again. Very strange. Espacially since this setup ran now for month with the sharedkey...

**Comment by mimugmail** [comment]
There was an update related to PSK lately, but I can't imagine it has worked before with such a value. :)

**Comment by f45tb00t** [comment]
Can be closed, as removing the key worked.
