### ISSUE TITLE
net/frr: rip prefix lists

### ISSUE THREAD

**Issue by fabianfrz** [opnsense/plugins#319]
das hier hat sich zu mir per Mail verirrt:

> Good morning Fabian,
> i want to you place question regarding how to use prefix-list for blocking 
> distribution of specific routes over RIP from some interfaces.
> 
> I am using latest build of OPNsense and your quagga package os-quagga 1.4.2.
> 
> I am familiar with cisco inteface and quagga looks similiar. In GUI i cannot
> find how to block specific networks distribution, there is only passive-
> interface, but in quagga CLI is possible to create distribution list. 
> 
> If i create access-list for example "test" and include it to RIP procotol as
> distribution list for filtering this specific network out of interface em0 
> and after all i do WRITE (or copy running-config startup-config) to save 
> changes into files /usr/local/etc/quagga/zebra.conf and  ripd.conf, then 
> after reload of opnsense everything revert back to setting inside of to GUI.
> So access-list and distribution-list will disappear from the config.
> 
> 
> 
> 
> Thank you for help,
> 
> Dan from CZ
>

**Comment by fabianfrz** [comment]
sorry but I have only stable network Access for some hours

**Comment by mimugmail** [comment]
@fabianfrz Please send me the email address of this guy, I'll try to implement it.

**Comment by mimugmail** [comment]
Close? AFAIR the guy didn't respond to my mail and RIP is quite outdated.
