### ISSUE TITLE
Nginx Upstream won't update in os-nginx 1.31

### ISSUE THREAD

**Issue by jmcgrath207** [opnsense/plugins#3196]
I am seeing this error once I updated from opnsense 22.7.5 to 22.7.8. 

```bash
invalid number of arguments in "server" directive in /usr/local/etc/nginx/nginx.conf:90
```
I noticed there is no upstream servers in the config.

```
cat /usr/local/etc/nginx/nginx.conf
...
    upstream upstream9f11d4eeca03468db99efede4c20d966 {
        server ;
        server ;
    }
    
 ```

Based on this release doc os-nginx was bumped to `1.31` so as far as I know this was work in `1.30`

https://docs.opnsense.org/releases/CE_22.7.html#november-17-2022

**Comment by kulikov-a** [comment]
1.31 did not touch upstreams parts of the templates or the nginx model (https://github.com/opnsense/plugins/commit/f8fe9af7703a92dc056da80b669b38c39ef7a6c3)
any other errors in backend or system logs?
