### ISSUE TITLE
Firewall plugin API returns false-positive information no matter the uuid

### ISSUE THREAD

**Issue by wrobelda** [opnsense/plugins#3197]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X] The title contains the plugin to which this issue belongs

**Describe the bug**

calling the API with:
```
curl -k -u "key":"pass" "https://opnsense/api/firewall/filter/getRule?uuid=356ddf83-1e2d-4fde-80ac-d9efb725b6fa"
```
always returns the same JSON, no matter the actual uuid used. 

**Expected behavior**
The information returned should be appropriate for the rule requested.

**Environment**
Software version used and hardware type if relevant.
e.g.:

OPNsense 22.7.8-amd64

**Comment by wrobelda** [comment]
Tried that, too, but that returns:
`[]%`

for all of the uuids. 

Besides, if `/getRule?uuid=` is an incorrect syntax then returning a false positive is super misleading.

**Comment by kulikov-a** [comment]
the plugin comes with simple ui at ui/firewall/filter/#Firewall_Automation
I think it's convenient to start working with api via the browser dev console

**Comment by wrobelda** [comment]
OK, so the plugin works, but only with the rules previously created using the plugin itself. 

That having said, the plugin somehow returning a random? data when used with `/getRule?uuid=` query is misleading. This is, after all, a perfectly well formed GET query.

**Comment by AdSchellevis** [comment]
https://docs.opnsense.org/development/examples/using_grids.html#api-controller
>o getItemAction, fetches an existing record (or returns a blank one with all defaults)
