### ISSUE TITLE
relayd not adding pf anchors

### ISSUE THREAD

**Issue by jlbaker75** [opnsense/plugins#3204]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

relayd isn't creating the "relayd" anchors in the pf ruleset without rebooting the system; `configctl relayd restart/reload` do not cause them to be added

**To Reproduce**

1. Install os-relayd plugin
2. Configure plugin appropriately
3. Enable & start plugin
4. Observe that `configctl relayd status` and `configctl relayd summary` show the plugin ought to be working as expected
5. Observe that the "relayd/*" anchors do not exist in `pfctl -s all | grep anchor`
6. Reboot
7. Observe that the "relayd/*" anchors now exists in `pfctl -s all | grep anchor`

**Expected behavior**

relayd would create appropriate pf anchors, without a reboot

**Describe alternatives you considered**

1. Checking for errors in configuration
2. Reloading/restarting relayd plugin

**Relevant log files**

Before reboot:
Edit (replaced "-s rules" with "-s all"):
```
root@(redacted):/home/(me) # pfctl -s all | grep anchor
nat-anchor "acme-client/*" all
rdr-anchor "acme-client/*" all
anchor "acme-client/*" all
root@(redacted):/home/(me) #
```
After reboot:
Edit (replaced "-s rules" with "-s all"):
```
root@(redacted):/home/(me) # pfctl -s all | grep anchor
nat-anchor "acme-client/*" all
rdr-anchor "acme-client/*" all
rdr-anchor "relayd/*" all
anchor "acme-client/*" all
anchor "relayd/*" all
root@(redacted):/home/(me) #
```
```
root@(redacted):/home/(me) # configctl relayd status
osrelayd is running as pid 96097.
```
```
root@(redacted):/home/(me) # configctl relayd summary
Id      Type            Name                            Avlblty Status
1       redirect        172.28.130.2 port 80                    active
1       table           haproxy_servers:80                      active (2 hosts)
1       host            172.29.173.76                   100.00% up
2       host            172.29.173.77                   100.00% up
2       redirect        172.28.130.2 port 443                   active
2       table           haproxy_servers:443                     active (2 hosts)
3       host            172.29.173.76                   100.00% up
4       host            172.29.173.77                   100.00% up
```
```
root@(redacted):/home/(me) # cat /usr/local/etc/relayd.conf
# DO NOT EDIT THIS FILE -- OPNsense auto-generated file

interval 5
prefork 3
timeout 200

table <haproxy_servers> {
172.29.173.76
172.29.173.77
}

redirect "172.28.130.2 port 80" {
listen on 172.28.130.2 tcp port 80
forward to <haproxy_servers> mode least-states  check tcp
session timeout 600
}
redirect "172.28.130.2 port 443" {
listen on 172.28.130.2 tcp port 443
forward to <haproxy_servers> mode least-states  check tcp
session timeout 600
}
```

**Additional context**

The hardware I'm running is underpowered for ssl proxies with haproxy, so I'm moving the reverse-proxy functionality I currently use to other machines, and trying to forward connections to them using relayd.

**Environment**

PCEngines APU2, ROM v4.17.0.2
```
root@(redacted):/home/(me) # uname -a
FreeBSD (redacted).(domain) 13.1-RELEASE-p3 FreeBSD 13.1-RELEASE-p3 stable/22.7-n250262-83840459d88 SMP amd64
```

Edit:
- os-relayd v2.7
- OPNsense 22.7.9

**Comment by AdSchellevis** [comment]
I expect the registration is there, but needs a firewall restart after installation to be used. 
https://github.com/opnsense/plugins/blob/16f3522d08d30919b17e66bdec38352ef4c75208/net/relayd/src/etc/inc/plugins.inc.d/relayd.inc#L44-L45

Maybe we could hook this in after plugin restart, I expect a firewall restart (apply in the alias section or firewall) would fix the issue after installation.

**Comment by jlbaker75** [comment]
So it seems my familiarity with pf on the command line isn't as thorough as I'd thought: I'd incorrectly assumed that "pfctl -s all" would show, well, "all" the things, including rdr rules within relayd's anchors.  It does not.

relayd _is_ redirecting the packets, once the anchor is created - though that still requires a reboot.

I've updated the issue.  Mea culpa.

(On a related note: can someone please tell me what command would list the redirect rules within the relayd anchor and rdr-anchors?)

**Comment by AdSchellevis** [comment]
> So it seems my familiarity with pf on the command line isn't as thorough as I'd thought: I'd incorrectly assumed that "pfctl -s all" would show, well, "all" the things, including rdr rules within relayd's anchors. It does not.

The documentation (https://www.freebsd.org/cgi/man.cgi?query=relayd) suggests it does list in pf, but as far as I know it only registers a hook after which relayd injects its own rules not visible to pfctl (table names aren't the same ones either).

> (On a related note: can someone please tell me what command would list the redirect rules within the relayd anchor and rdr-anchors?)

`relayctl` ?

**Comment by jlbaker75** [comment]
`relayctl` is useful for showing redirect/relay/session info from relayd, but not the actual pf rules injected into the pf anchors - which I'm beginning to realize isn't really that important to know.
