### ISSUE TITLE
Wireguard interfaces are not grouped if the last one fails to start

### ISSUE THREAD

**Issue by xbb** [opnsense/plugins#3206]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
When there are multiple tunnels configured and the last one fails to start (for example, due to failed dns resolution, see #3186), all the wireguard interfaces are not grouped in the `wireguard` group.

Weirdly this isn't the case if, for example only the first tunnel of 3 fails.

**To Reproduce**
For a quick way to test this just create local interfaces in the plugin ui:

1. Create a local interface by giving it only a name
2. Create a second local interface and give it an invalid private key (some random char)
3. Apply / start / restart the service

**Expected behavior**

All the up wireguard interfaces are grouped in the `wireguard` group (from `ifconfig` output)

**Screenshots**

![image](https://user-images.githubusercontent.com/239074/205062854-eb65fa67-f107-4311-a769-62c7f36e4c5c.png)

**Additional context**

This happens because `start_postcmd` (`/etc/rc.conf.d/wireguard`) isn't ran if the service command returns non-zero.

`start_postcmd` can be forced to run if using `service wireguard forcestart|forcerestart`

**Environment**

OPNsense 22.7.8

**Comment by fichtner** [comment]
Did you see https://github.com/opnsense/plugins/commit/2cdaf717b269329424e1b5de1376a1fec818882b which was added in 22.7.9? Not claiming it’s perfect yet but it seemed to resolve at least the DNS issue.

**Comment by xbb** [comment]
> Did you see [2cdaf71](https://github.com/opnsense/plugins/commit/2cdaf717b269329424e1b5de1376a1fec818882b) which was added in 22.7.9? Not claiming it’s perfect yet but it seemed to resolve at least the DNS issue.

Yes, just after the report sadly, but that definitely helps.

Apart from misconfiguration or DNS resolution it doesn't seem to fail to bring up the interfaces even if a peer is unreachable.

**Comment by xbb** [comment]
Sorry, I think you can close, your fix should cover most cases.

Unless there is a simple way to re-implement what the [start_postcmd](https://github.com/opnsense/plugins/blob/22.7.9/net/wireguard/src/opnsense/service/templates/OPNsense/Wireguard/wireguard#L13-L19) does (group the new interfaces with `ifconfig`), I don't think it's worth fixing.

With the `start_postcmd`, all the wireguard interfaces will not be grouped only when the last interface configured doesn't come up because of an error (the service start command returns 1 in that specific case), definitely rare.

This doesn't affect me, as I'm not using rules in the wireguard group, I just noticed it accidentally while looking at #3186.

**Comment by fichtner** [comment]
Now I see the problem you mention is with our code although a partial success-is-failure paradigm doesn’t help much from the port rc script end… let me fix that on Monday within the constraints of our plugin.

**Comment by fichtner** [comment]
@xbb should be better with 3d4205c  -- thanks for the report!
