### ISSUE TITLE
Crowdsec upgrade to v1.4.2 or soon to be released v1.4.3

### ISSUE THREAD

**Issue by nzkiwi68** [opnsense/plugins#3210]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X ] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X ] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X ] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
Crowdsec v1.4.2 now auto-updates parsers & scenarios on a daily basis to stay on top of upcoming threats
[https://github.com/crowdsecurity/crowdsec/releases](url)

**Describe the solution you'd like**
Please upgrade the Crowdsec plugin

**Describe alternatives you've considered**
None

**Additional context**
Thanks

**Comment by fichtner** [comment]
Updates are done via FreeBSD ports sync, ticket still open it seems https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=267808
