### ISSUE TITLE
Make Wireguard widget customizable 

### ISSUE THREAD

**Issue by Eypsilon312** [opnsense/plugins#3212]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Make the Wireguard widget customizable. So you are able to show or hide columns, like the "Public Key" column, which I personally don't need to see on the dashboard.

**Describe alternatives you've considered**
None

**Additional context**

![image](https://user-images.githubusercontent.com/55278376/206029619-8fbf6156-a296-4d27-a9dc-7b90c920d600.png)

**Comment by patschi** [comment]
Bump. PR Review still pending in #3272
