### ISSUE TITLE
os-frr does not persist vtysh commands after reboot

### ISSUE THREAD

**Issue by jmcgrath207** [opnsense/plugins#3214]
When I reboot my firewall, any changes I apply  via the cli with `vtysh` won't persist after reboot. Once the firewall comes back up it will start with the old GUI configuration. How do I change this behavior?

```
OPNsense.localdomain# wr
Note: this version of vtysh never writes vtysh.conf
Building Configuration...
Configuration saved to /usr/local/etc/frr/zebra.conf
Configuration saved to /usr/local/etc/frr/bgpd.conf
Configuration saved to /usr/local/etc/frr/bfdd.conf
OPNsense.localdomain# exit
```

OPNsense 22.7.9_3-amd64
FreeBSD 13.1-RELEASE-p5
OpenSSL 1.1.1s 
1 Nov 2022

**Comment by mimugmail** [comment]
Only install frr without the plugin, then its cli only
