### ISSUE TITLE
dns/bind: Plugin Improvements

### ISSUE THREAD

**Issue by sestary** [opnsense/plugins#3225]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
There are a couple of missing features I'd like to use in the `dns/bind` plugin and I'm working on adding them, I'm opening this issue to gather feedback/suggestions.

**Describe the solution you'd like**
1. Better Key management, allowing you to re-use keys for multiple zones.
2. Slave Zone Master configuration, this would allow you to re-use masters/keys for multiple zones.
3. RFC 2136 support, dependent on 1. , but would allow for a master zone to be updated by something like K8s external DNS or similar type dynamic DNS

Better Key Management (I've already started work on this here https://github.com/sestary/opnsense-plugins/tree/keys):
- [x] Create a new Key management page, where you can add/remove keys (name, algo and secret fields)
- [x] Keys are added to `named.conf`
- [x] Add multiple key selector to `master` zone dialog
- [x] Update slave zone dialog to select key
- [x] Dedicated section to allow updates to the `RNDC Key` (default will use existing key) https://github.com/opnsense/plugins/issues/2196, completed in PR #3239.
- [x] Create migration from existing key setup

Slave Zone Master configuration:
- [ ] Create a new Masters page, where you can add/remove masters, this would allow you to specify the IP/Port and select the Key
- [ ] Update the `named.conf` logic to support new masters
- [ ] Add multiple key selector to the `slave` zone dialog

RFC 2136 Support:
- [ ] Add RFC 2136 `allow-update` support. This would simply reference existing ACLs like `Allow Query`
- [ ] Add RFC 2136 `update-policy` support. Three options here:
1. Only support one rule per zone
2. Support multiple rules, this would need to be a separate model (I haven't figured out a way to add multiple fields multiple times)
3. Add a simple text field for users to add their own rules to (rather not do this since it's error prone)

Other things I'd like to do at some point:
- [x] Update `master`/`slave` in official nomenclature as per https://github.com/opnsense/plugins/pull/3222#issuecomment-1357428183 done in https://github.com/opnsense/plugins/pull/3234
- [ ] Advanced field that allows any Bind `name.conf` option to be added through a text box in General settings and in the `zone` dialogs. Allowing for custom advanced config without direct support in the Plugin.
- [ ] Views? 

@mimugmail @fichtner Let me know what you think of this. Is there anything else that makes sense to be added?

**Comment by bugspencor** [comment]
I would like to update DNS records from DHCP. As far as I can see on the DHCP-side everything is here and your changes would add the required bind configuration. Please let me know if you have a testable version, I would be happy to give it a try.

**Comment by dweimer** [comment]
I would love support for Forward Only DNS zones, the zone configuration is quite simple.

zone "somedomain.com" {
        type forward;
        forward only;
        forwarders { 8.8.8.8; 8.8.4.4; };
};

I use quite a few of these for internal only domains on VPN tunnel setups, to point them to the correct internal DNS server on the other end. Some times its just you don't get permissions to copy a slave zone. And sometimes the server doesn't support it.

**Comment by sestary** [comment]
@bugspencor I will let you know once I have a testable version with the RFC 2136 Support.

@dweimer That should be relatively easy to add, definitely something I could use as well.

**Comment by lucaschoeneberg** [comment]
Is it possible to include DNS overrides? As I understand it, this is done via RPz entries or?

**Comment by sestary** [comment]
@lucaschoeneberg This is possible, but I'd have to look into it. This is not a feature I'd be using so it'd be low priority for me to implement it. Might be good to open a separate feature request for it.

**Comment by howudodat** [comment]
@lucaschoeneberg @sestary I have done a simple implementation of overrides.  It uses a master zone called rpzlocal and a one line change to the template see my comment here https://github.com/opnsense/plugins/issues/3276

I am very interested in views, because that's really the correct way to do split horizon config.

**Comment by pcmediapear** [comment]
@sestary any news about RFC 2136 support?

**Comment by sestary** [comment]
Right now I don't have any news I've ran into a couple of problems getting some of the functionality to work reliably. The main problem is with the migrations. This plugin is one of the only plugins that uses multiple models to represent the data and doing a migration from one model to another to add new features is proving to be more difficult than I thought.

The second issue I've identified while doing the initial RFC 2136 support is that essentially it would need to be setup like a secondary zone where you can't create/list/delete the records on the UI. This is because the records are stored in the config file and there doesn't seem to be a good way to sync the dynamic information in the zone file so that when you edit a manually added record it erases all of the dynamic entries. 

I've investigated adding a UI records manager which uses RFC 2136 in the background, but at that point I'm almost rewriting the entire plugin. Coupled with the migration issues above and I'm wondering if it's easier to just do a new plugin with an easier to maintain data model.

**Comment by fichtner** [comment]
For 1) we discussed this not too long ago and you can do https://github.com/opnsense/core/blob/84f0bcdbdb182c104c07b1170daf8a4927655253/src/opnsense/mvc/app/models/OPNsense/Core/Migrations/M1_0_0.php#L42-L44 to pin down the migration to a specific model. The other issue is that you need to bump all version numbers of models to the same target version the migration exists for in order to cleanly execute it.

**Comment by fichtner** [comment]
About 2) I'm not sure what you try to do. Usually we split configuration data and runtime data. Sometimes configuration data is expanded with runtime information, but runtime information is never used to be turned into configuration data.

**Comment by sestary** [comment]
> For 1) we discussed this not too long ago and you can do https://github.com/opnsense/core/blob/84f0bcdbdb182c104c07b1170daf8a4927655253/src/opnsense/mvc/app/models/OPNsense/Core/Migrations/M1_0_0.php#L42-L44 to pin down the migration to a specific model. The other issue is that you need to bump all version numbers of models to the same target version the migration exists for in order to cleanly execute it.

Setting the model that the migration is part of isn't the problem. The problem is migrating data from the General Model to a new model for example but keeping a link in General to the entries created under the new model. The code here: https://github.com/sestary/opnsense-plugins/blob/forwardzone/dns/bind/src/opnsense/mvc/app/models/OPNsense/Bind/Migrations/M1_2_0.php#L43 is how far I got with trying to get that to work. It's broken but I'm not sure of a good way to implement this.

> About 2) I'm not sure what you try to do. Usually we split configuration data and runtime data. Sometimes configuration data is expanded with runtime information, but runtime information is never used to be turned into configuration data.

The problem is that Bind will add dynamically added entries to the zone files (initially in a journal file but those are written to the main zone file very X min). Right now in the plugin those are templated so when you hit save because you added a new entry the file is overwritten and all dynamic entries are now gone. So there are two options that are viable:
1. Have dynamic only zones, this way you'd have to setup a keys that allow updates to the zone even for admins, so that automatic updates from tools and admin go through the same route. (definitely the easiest)
2. Treat all the zones as dynamic and rewrite the "save" function to do the updates through the `rndc` utility. The biggest issue with this approach would be having a dynamically updated entry override the static entry and that would still show the old value in the config.

**Comment by financelurker** [comment]
As @howudodat pointed out: being able to do a proper split horizon dns vía bind views would be awesome!
I am struggling to setup such a split horizon dns with the given UI tools right now...

**Comment by ApertureDevelopment** [comment]
I have a few suggestions for additions, I hope they are welcome:
- I think we should have the ability to define forwarders running on non standard ports. As of now you can only add forwarders running on port 53
- Adding support for DNS-over-TLS and DNS-over-HTTPS for bind9. This was introduced in bind 9.17
- Planning ahead for Bind 9.19 which added support for DNS-over-TLS for forwarders

**Comment by 0dragosh** [comment]
Is there any progress being planned for this? It'd be great if we could use rndc keys with custom zones with the bind plugin.

Maybe this could be split off into multiple smaller features that perhaps are more digestible and not as ambitious up front?

**Comment by los93sol** [comment]
Stumbled onto this issue after needing my bind to support RFC 2136 and manually updating the template file so it doesn't overwrite me constantly, but official support would be fantastic!  I agree with @0dragosh that the goals here were a bit overly optimistic and could have been broken down into smaller parts that would be more than sufficient for most users needs

**Comment by 0dragosh** [comment]
@los93sol I've since discovered you can leverage `/usr/local/opnsense/service/templates/OPNsense/Bind/named.conf` to at least partially hack your way around the config file overwrites. Have not played with it enough though.

If you do manage to get a proper template config working through service restarts for RFC2136 I'd love to see it!

**Comment by bugspencor** [comment]
I recently found out that my use case (being able to resolve dhcp clients in the LAN via unbound) is already working with current opnsense.

I'm using opnsense-unbound as resolver and unbound forwarding to bind for my primary LAN domain and reverse zones. IIRC I enabled "Register DHCP Leases" in unbound and also set the domain in System/Settings/General. Unbound seems to first resolve the known DHCP leases and forwards the rest to DNS.

Maybe that helps anybody else.

**Comment by Pleune** [comment]
It is unfortunate that this has not seen any progress recently. RFC 2136 Support would significantly help in some ipv6 hosting use-cases. Currently I have bind running in a separate container acting as the authoritative server for my local domain.  The lack of allow-update support prevents me from using the os-bind plugin instead. Easy configuration to let the DHCP services do local DDNS would be great.

**Comment by Nick2253** [comment]
Just to add another voice to this, I just opened a feature request specifically for the: 

"Advanced field that allows any Bind name.conf option to be added through a text box in General settings and in the zone dialogs. Allowing for custom advanced config without direct support in the Plugin."

https://github.com/opnsense/plugins/issues/4773
