### ISSUE TITLE
www/nginx: Add the respective nginx config parameters to all help messages

### ISSUE THREAD

**Issue by codiflow** [opnsense/plugins#3228]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
I often struggle while configuring the plugin because I don't know what parameter the respective GUI element is triggering in the backend.

**Describe the solution you'd like**
I would like to add the respective nginx parameter names (also possible in brackets) inside every help text. Find an example here:

![grafik](https://user-images.githubusercontent.com/43847817/208926692-0aa9aef3-c78f-4b8e-9c93-0fe8be6c81b4.png)

I would also like to add some guidelines for the format the GUI element is waiting for like it was already added here:
![grafik](https://user-images.githubusercontent.com/43847817/208925868-7c9aaeb6-f6ac-4448-b0f9-239279b91f7b.png)

This currently is not mentioned for every parameter, see:
![grafik](https://user-images.githubusercontent.com/43847817/208925464-2e60d26b-8996-47a5-b80f-611fc863dac7.png)

I would like to do that **for the whole nginx plugin** in OPNsense to have it realized in a consistent way. But I'm currently not aware of how this would break the current language translations because changing all the main strings would most likely break all translations. What do you think about that?

**Describe alternatives you've considered**
No real alternative considered. I think it makes sense to have helpful and clear descriptions which help (especially newbies) to better understand the system and what the GUI option triggers.

**Additional context**
-

**Comment by kulikov-a** [comment]
Hi!
I think that would be just great.
but I also don't know how to do it without breaking the whole translation.
what comes to mind is adding a field to a form (eg "title") and using it in partial layout to add a title/tooltip to a control label (or wherever).
![tooltip](https://user-images.githubusercontent.com/36099472/213397497-6ab676d6-0beb-4989-9b6d-a341d83fd60c.PNG)

but then it's already a core request?
