### ISSUE TITLE
os-ddclient works once with a domain, then fails afterwards

### ISSUE THREAD

**Issue by clamo** [opnsense/plugins#3232]
os-ddclient worked for the first try, then returns wrong response after a config change, and the same domain cannot be used after the deleting the config. Please refer to repro steps for more detailed error messages. Also reported in official forum by others starting months ago - https://forum.opnsense.org/index.php?topic=29553.15 - what's interesting is that the os-ddclient works for many users while failing for some users with same/similar reasons.

**To Reproduce**
In my case:
1. Installed os-ddclient
2. Created a config for sd1.mydomain.page with Google Domains, worked fine - https://192.168.1.1/ui/dyndns/
3. Decided to use CloudFlare instead, so deleted the config and created a new config with CloudFlare settings
4. os-ddclient log says that the IP is already pointing to the correct address - SUCCESS: sd1.mydomain.page: skipped: IP address was already set to xx.xx.xx.xx - but confirmed that CloudFlare's IP DNS record didn't update
5. Decided to use Google Domains again with sd1.mydomain.page, so I cleared the DNS record, re-created the record for sd1 in Google Domains, re-created the config in os-ddclient; same message about skipping due to IP is correct already (which isn't true)
6. So I created a sd2.mydomain.page in Google Domains, created a new config for sd2.mydomain.page, and it started working again
7. I re-created the config for sd1.mydomain.page in os-ddclient, it returned message about skipping due to IP is correct already (which isn't true)
8. I changed to sd2.mydomain.page in os-ddclient, it returned message about skipping due to IP is correct already (which isn't true)
9. Very puzzled that I could only use a subdomain ONCE and cannot change settings or re-create configs, I decided to reboot OPNsense
10. Same thing happening; cannot reuse the sd1 or sd2 subdomains. I also found the following message from backend log - Script action stderr returned "b"pgrep: Cannot open pidfile `/var/run/ddclient.pid': No such file or directory""

**Expected behavior**
1. os-ddclient should double check and make sure that the IP is correct in both OPNsense and DNS servers, instead of making a false claim and skipping to update the DNS record
2. Deleting a config in os-ddclient should completely clear the settings, so that users can use same subdomains multiple times as long as the configs are deleted and re-created in proper manner

**Additional context**
My guess is some kind of race condition, or local files not being cleared correctly when the configs are being created or deleted. 

**Environment**
OPNsense 22.7.10_2 (amd64, OpenSSL, bdce9463f) 
Intel Core i5-6500
Network Intel X520-DA2
os-ddclient 1.9_2
Unbound DNS

**Comment by clamo** [comment]
Pff time to try out pfsense

**Comment by fichtner** [comment]
Your patience for the holiday season seems to be rather thin. Good luck. 😉

**Comment by clamo** [comment]
I easily get annoyed by automated, derogatory messages that says "We won't even read it, even though more than enough information are provided, while many users have reported the issue." And instead of understanding the effort of community, or even trying to understand the situation, a member thinks low of a contributor(s). Good luck with the market share 😉

**Comment by fichtner** [comment]
Thanks!
