### ISSUE TITLE
Add support for Zabbix proxy 6.2.5

### ISSUE THREAD

**Issue by Gromigno** [opnsense/plugins#3242]
Zabbix proxy 6.2 is not compatible with latest zabbix version 6.2.5:
Server-proxy compatibility
This version has the following server-proxy compatibility issues:
Zabbix server 6.2.5 will not work with a Zabbix proxy below/above 6.2.5;
Zabbix proxy 6.2.5 will not work with a Zabbix server below/above 6.2.5.

**Comment by fraenki** [comment]
Zabbix Proxy 6.2.6 is already available in OPNsense 22.7.10.

**Comment by fraenki** [comment]
If you really need a specific _minor_ version (.5), things may get complicated. This is usually not supported, as each OPNsense release is shipped with a specific set of packages. I'd suggest to upgrade your Zabbix proxy/server to a version that is supported in OPNsense.
