### ISSUE TITLE
[nginx] Add option to disable HTTP compression

### ISSUE THREAD

**Issue by duburcqa** [opnsense/plugins#3245]
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**

gzip compression is enabled unconditionally [here](https://github.com/opnsense/plugins/blob/f8fe9af7703a92dc056da80b669b38c39ef7a6c3/www/nginx/src/opnsense/service/templates/OPNsense/Nginx/http.conf#L32) which incurs vulnerability to [BREACH attack](https://techblogs.42gears.com/mitigating-breach-attack-in-nginx-server/).

**Describe the solution you'd like**

It should be possible to disable gzip compression with a check box in `General Settings`.

**Describe alternatives you've considered**

I don't think any other alternative is worth considering.

**Additional context**

None

**Comment by kulikov-a** [comment]
given the specificity of the attack and the wide 'SameSite' support, might it be enough to add the 'disable gzip' at the server context? )

**Comment by duburcqa** [comment]
yes it would be fine for sure !

**Comment by ProgTiger** [comment]
Also searching for this option at Server-Context-Level. Would appreciate this feature!
