### ISSUE TITLE
[os-maltrail] Save button does not save

### ISSUE THREAD

**Issue by Xeroxxx** [opnsense/plugins#3250]
**Describe the bug**
Maltrail adds three configuration pages. Its clear that a restart is mandatory to reload the config. However the three pages added are general, sensor and server. Using the "Save" button in general does not result in save/rewrite of maltrail.conf. You're required to switch to sensor or server and save again.

**To Reproduce**
Change settings in general and save
Restart maltrail
no change

---

Change settings in general and save
check maltrail.conf
Save in sensor page
check maltrail.conf

**Expected behavior**
Save button in general should save

**Screenshots**

**Relevant log files**

**Additional context**

**Environment**
OPNsense 22.7.10_2-amd64
FreeBSD 13.1-RELEASE-p5
OpenSSL 1.1.1s 1 Nov 2022

**Comment by daygle** [comment]
I would like to contribute here.

The original reported issue helped me figure out the bazaar issues I had when I was pressing the 'Save' button within the Maltrail settings - basically it would never take on the changes. Just like how @Xeroxxx reported, I figured out from this issue to successfully save/update the Maltrail configuration it is performed with a two step process.

1. Make changes to the 'General' screen then press 'Save'.
2. Navigate to the 'Sensor' screen and simply press 'Save'.

Without performing step two the Maltrail configuration file would not update with the updated values. @OPNsense-bot mentions that @Xeroxxx is not using our templates? I have OPNsense installed and have simply installed the 'Maltrail' plugin - is this not an OPNsense template?

I personally do not know why there are three sections 'General', 'Sensor' and 'Server' - there should only be the two  'Sensor' and 'Server'. In fact official documentation from Maltrail includes all 'General' values within the 'Sensor' and 'Server' sections. Updating the OPNsense/Maltrail plugin would correct this issue.

**Comment by mimugmail** [comment]
At the time the plugin was written, most of the values in General needed to be in either server-only or sensor-only.

**Comment by daygle** [comment]
> At the time the plugin was written, most of the values in General needed to be in either server-only or sensor-only.

Correct, that's what I am saying the general items should fall under the sensor or server sections.

**Comment by daygle** [comment]
@mimugmail I have generated a pull request to attempt to move the config to the correct sections. Someone may need to review/test to ensure that the changes work correctly (and that I have not missed anything).
