### ISSUE TITLE
os-postfix 1.23_3 | Add ways to edit master.cf using web UI

### ISSUE THREAD

**Issue by lucas3F59** [opnsense/plugins#3251]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
The problem is that it isn't possible to change `/usr/local/etc/postfix/master.cf` in a persistent manner. I have experienced two issues so far:
1. postfix documentation recommends to comment out the `local` line in `master.cf`, when using postfix as a relay. After a reboot, this is gone.
2. When postfix tries to forward mails to an internal Exchange Server, I always get the error "cannot start tls handshake failure". This could be solved by uncommenting the `tlsproxy` line in `master.cf`.

**Describe the solution you'd like**
I would like to have a new tab in `https://opnsense/ui/postfix/general/index` where `master.cf` can be edited in a persistent manner. Alternatively default settings, which disable `local` and enable `tlsproxy`, after all, it's not a mail server, but only a gateway.

**Describe alternatives you've considered**
Manually editing `/usr/local/etc/postfix/master.cf`

**Additional context**
Thank you very much!

**Comment by HacCat** [comment]
Yes this is imperative.     The same is needed at the very least for **main.cf** please
I wish to enable the postscreen module of postfix. By the default configuration in opnsense, if the internal mail server is temporarily unavailable (eg rebooting) postfix deletes the incoming message instead of simply queuing it!
Even if not exposed in the GUI, support for persistent edit via SSH et al would suffice.
See also https://forum.opnsense.org/index.php?topic=18860.0  where the current implementation of opnsense is contributing to spam.

**Comment by fichtner** [comment]
You know you don’t have to use the plugin and just configure the package by hand. ;)

**Comment by mimugmail** [comment]
I will add two checkboxes for disabling the mentioned lines

**Comment by lucas3F59** [comment]
> I will add two checkboxes for disabling the mentioned lines

Is it as simple as doing the following:

In
`plugins/mail/postfix/src/opnsense/mvc/app/models/OPNsense/Postfix/General.xml`
add:
`        <service_enable_local type="BooleanField">`
`            <default>1</default>`
`            <Required>Y</Required>`
`        </service_enable_local>`
`        <service_enable_tlsproxy type="BooleanField">`
`            <default>0</default>`
`            <Required>Y</Required>`
`        </service_enable_tlsproxy>`

In
`plugins/mail/postfix/src/opnsense/service/templates/OPNsense/Postfix/master.cf`
replace
`#tlsproxy  unix  -       -       n       -       0       tlsproxy`
`local     unix  -       n       n       -       -       local`
with
`{% if helpers.exists('OPNsense.postfix.general.service_enable_tlsproxy') and OPNsense.postfix.general.service_enable_tlsproxy == '1' %}`
`tlsproxy  unix  -       -       n       -       0       tlsproxy`
`{% endif %}`

`{% if helpers.exists('OPNsense.postfix.general.service_enable_local') and OPNsense.postfix.general.service_enable_local == '1' %}`
`local     unix  -       n       n       -       -       local`
`{% endif %}`

If yes, I could try to commit this myself if I ever find out how to do it.
