### ISSUE TITLE
Telegraf: if influxv2 is disabled in output, its timeout fields still appends to influxv1 in config file 

### ISSUE THREAD

**Issue by JPBeltman** [opnsense/plugins#3265]
- [X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X] The title contains the plugin to which this issue belongs

**Describe the bug**
If a value exists in the timeout field for influx v2 output , it will be appended in the config (it looks like the options are all hardcoded to a particular line in the config file), even if influxv2 output is disabled.

**To Reproduce**
1. Enable Telegraf plus in- & output
2. Enable influxv1, disable influxv2 
3.  Enter value in influxv2 timeout field
4. Check config file
5. Remove value from influxv2 timeout field
6. Check config file
7. Repeat but with influxv2 enabled, influxv1 disabled etc
 

**Expected behavior**
A timeout value (or any value) should only exist in the config file if the corresponding service is enabled

**Relevant log files**
same log every Default data collection interval for all inputs in seconds:
`E! [telegraf] Error running agent: error loading config file /usr/local/etc/telegraf.conf: error parsing data: line 31: key "timeout" is in conflict with line 17d`

**Environment**
FreeBSD 13.1-RELEASE-p5 stable/22.7-n250270-9d1c26e8548 SMP amd64
OPNsense 22.7.10_2 bdce9463f
Plugins os-clamav-1.8 os-crowdsec-1.0.1 os-firewall-1.2 os-ntopng-1.2_2 os-realtek-re-1.0 os-redis-1.1_2 os-sensei-1.12.3 os-sensei-updater-1.12 os-smart-2.2 os-sunnyvalley-1.2_2 os-telegraf-1.12.7 os-wireguard-1.13_3 
OpenSSL 1.1.1s  1 Nov 2022
Python 3.9.16
PHP 8.0.26

**Screenshots**
influxv1 output enabled, influxv2 output disabled;
  - timeout field: no value
![NoTimeouts](https://user-images.githubusercontent.com/44642825/213240430-c62fc7b4-e4e6-4c68-8d15-1a3b23425d1c.png)
  - timeoutfield: 0
![timeoutv2](https://user-images.githubusercontent.com/44642825/213241148-be7208aa-1e6b-45a6-982b-4ef8ef1929e6.png)

both enabled, influxv2 timeout: 5;
![v2enabled](https://user-images.githubusercontent.com/44642825/213242379-fb992de3-a328-4eb6-bdc5-3f79c822b647.png)

config after disabling influxv2 output 
![v2dis](https://user-images.githubusercontent.com/44642825/213242775-97771b10-9ca8-48ef-ba88-582333a85e16.png)

**Comment by JPBeltman** [comment]
Just saw a commit from 2 months ago, where influxv2 timeout was added.

In [net-mgmt/telegraf/src/opnsense/service/templates/OPNsense/Telegraf/telegraf.conf](https://github.com/opnsense/plugins/commit/ebcdb5eef611d185cd0cf90952d5a3d149a7cedf#diff-e3501e5c04617b45da71f3f7a10aca5108f398144b954d771b0bc47f8d22c0d9) on line 179:
`{%   if helpers.exists('OPNsense.telegraf.output.influx_v2_timeout') and OPNsense.telegraf.output.influx_v2_timeout != '' %}
  timeout = "{{ OPNsense.telegraf.output.influx_v2_timeout }}s"
{%   endif %}`

Couldn't this be solved really easily (and not beautiful in any kind of way) by nesting it in influx_V2_enable statement:
```

{% if helpers.exists('OPNsense.telegraf.output.influx_v2_enable') and OPNsense.telegraf.output.influx_v2_enable == '1' %}
    {%   if helpers.exists('OPNsense.telegraf.output.influx_v2_timeout') and OPNsense.telegraf.output.influx_v2_timeout != ''   %}
        timeout = "{{ OPNsense.telegraf.output.influx_v2_timeout }}s"
    {% endif %}
{% endif}
```

**Comment by g-a-c** [comment]
I had the same issue; https://github.com/opnsense/plugins/pull/3313 should fix it
