### ISSUE TITLE
os-theme-cicada : Low color contrast on Unbound DNS reporting page

### ISSUE THREAD

**Issue by PacoTyson** [opnsense/plugins#3267]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X] The title contains the plugin to which this issue belongs

**Describe the bug**
On the newly introduced Unbound Reporting page (https://opnsense/ui/unbound/overview), the colors provided by Cicada theme prevent reading the values.

**To Reproduce**
1. Install and use Cicada theme
2. Go to https://opnsense/ui/unbound/overview
3. Try to read the Overview or Details tab
4. Contrast is so low you can't read text

**Expected behavior**
High enough contrast

**Screenshots**
![image](https://user-images.githubusercontent.com/10000103/213565426-dda58baf-188e-4285-9a49-ea88a49e383c.png)
![image](https://user-images.githubusercontent.com/10000103/213565574-9870749b-1744-46c8-ab6b-237224273c63.png)

**Additional context**
No problem when using default theme

**Environment**
OPNsense 23.1.r2-amd64
FreeBSD 13.1-RELEASE-p5
OpenSSL 1.1.1s 1 Nov 2022

**Comment by jkemp814** [comment]
Same here, under the details tab is unreadable:
![Screenshot from 2023-02-06 14-58-44](https://user-images.githubusercontent.com/12059343/217097294-7d2fde20-0ebb-4474-9228-bfc051e753d9.png)
