### ISSUE TITLE
WireGuard-Go in the dashboard shown as not running

### ISSUE THREAD

**Issue by stultitiophobia** [opnsense/plugins#3268]
When running OPNsense 23.1.r_20-amd64 (updated from 22.x) it shows me (on dashboard /services) that WireGuard-Go is not running.
WireGuard as a VPN-server is running and up and working.
Perhaps this might be a cosmetic error ?

![image](https://user-images.githubusercontent.com/809290/213671225-c38bf9fb-41e4-4c6c-b159-acadee747953.jpeg)

**Comment by fichtner** [comment]
The plugin does not support service status for kmod variant yet which is the new default on 23.1. And yes it is cosmetics only. PRs welcome.

**Comment by maurice-w** [comment]
It's not just in the services widget, but also in `status_services.php`. wireguard-go should only be displayed there if os-wireguard-go is actually installed, not when using os-wireguard.

**Comment by fichtner** [comment]
True, but nobody cared before so we start with this and go from here😊

**Comment by patschi** [comment]
I've just filed PR #3273 with my proposed changes. I think it would be a good idea to hide the service when applicable, to avoid any confusion or anger when e.g. the buttons are not working. Not sure if the solution fits.

I hope it's still manageable before 23.1 GA? (I've filed multiple PRs today)

**Comment by fichtner** [comment]
23.1 is too late not even factoring in code freeze. I’ve made a comment on the PR.

**Comment by f45tb00t** [comment]
ahhh... was just about to write the same. But yes... confirmed. Just in case I restarted the service manually without any issues. So it's definately just a cosmetical issue.

**Comment by AdSchellevis** [comment]
wireguard-go is going to be removed in 24.1
