### ISSUE TITLE
[Wireguard] Can't run more than 2 tunnels at a time. 

### ISSUE THREAD

**Issue by sataris** [opnsense/plugins#3280]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X] The title contains the plugin to which this issue belongs

**Describe the bug**

Prior to 23.1 this worked flawlessly, 

I have 4 WG tunnels configured
wg0 (RoadWarrior) 
wg2 (Mullvad)
wg3 (Mullvad)
wg4 (Mullvad) 

I can get all of these running individually, but I can only ever get 2 of these running at a time and not in all combinations 

I've been able to get the following combinations working correctly. 

wg0 - wg2
wg0 - wg3
wg0 - wg4

Combinations I can't get to work correctly
wg0-wg2-wg3-wg4 (Only wg0 and wg2
wg2-wg3 (Only wg2 runs) Enabling WG2 first and then WG3
wg2-wg4 (Only wg2 runs) Enabling WG2 first and then WG4
wg3-wg4 (Only wg3 runs) Enabling WG3 first and then WG4

If I reverse the order of the endpoints
wg4-wg3 (wg4 runs and then stops and wg3 starts running)
wg4-wg2 (wg4 runs and then stops and wg2 starts running)

Now this may be because I'm an idiot, but I haven't changed the configuration and this worked well before upgrading

**Expected behavior**
Should be able to run any number of wg tunnels at a time. 

**Relevant log files**
I don't think the wireguard modules log anything anywhere?

**Comment by fichtner** [comment]
Have you tried switching back to os-wireguard-go?

**Comment by mimugmail** [comment]
Sounds like a /24 and /32 config issue which worked on -go. Any screenshots for us?

**Comment by sataris** [comment]
> Have you tried switching back to os-wireguard-go?

Yeah, and it's also still not working. :( 

@mimugmail what screen do you need ss of?

**Comment by sataris** [comment]
Update on this (and let this be a lesson to manage your backup configurations). 

Turns out the backup config I was restoring actually includeed DNS servers for the wg tunnels, which caused them to fail. 

Removing the DNS solved all the issues.
