### ISSUE TITLE
emulators/qemu-guest-agent: upstream port was replaced with FLAVOR=guestagent

### ISSUE THREAD

**Issue by fraenki** [opnsense/plugins#3283]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X] The title contains the plugin to which this issue belongs

**Describe the bug**
The FreeBSD port of emulators/qemu-guest-agent was removed:
https://github.com/FreeBSD/freebsd-ports/commit/92dec795cd3fc00c5b9f62cd8be7b6540132f27e

It is now a FLAVOR of emulators/qemu:
https://github.com/FreeBSD/freebsd-ports/commit/564c4cb3d9bb0aa87d676103fa164ea9833b7897

However, the patches that made the original port work on FreeBSD were removed. I'll have to test whether or not the new qemu@guestagent port is working properly.

**To Reproduce**
n/a

**Expected behavior**
n/a

**Screenshots**
n/a

**Relevant log files**
n/a

**Additional context**
n/a

**Environment**
n/a

**Comment by fraenki** [comment]
It looks like qemu-guest-agent 7.2.0 is working just fine:

```
$ sudo virsh qemu-agent-command opnsense.example.com '{"execute":"guest-get-osinfo"}'
{"return":{"kernel-release":"13.1-RELEASE-p5","kernel-version":"FreeBSD 13.1-RELEASE-p5 stable/23.1-n250372-c4ad069e50a SMP","machine":"amd64"}}

$ sudo virsh qemu-agent-command opnsense.example.com '{"execute":"guest-get-host-name"}'
{"return":{"host-name":"opnsense.example.com"}}

$ sudo virsh qemu-agent-command opnsense.example.com '{"execute":"guest-network-get-interfaces"}'
{"return":[{"name":"vtnet0","ip-addresses":[{"ip-address-type":"ipv4","ip-address":"192.168.123.123","prefix":24}, ...
```

**Comment by Ramalama2** [comment]
Hey @fraenki & @fichtner 
Thank you very much for the 7.2 port!
But is it possible to update the package to 8.0.3?

See here:
https://www.freshports.org/emulators/qemu/
The flavour is still "guestagent: qemu-guest-agent"

That would fix fsfreeze as far i understand and is the first official freebsd guest agent.
Also contains this 8 months old changes:
https://patchew.org/QEMU/20221026175518.2636846-1-kkostiuk@redhat.com/

And as we have on proxmox 8, qemu 8.0, this would allow for version parity.

Thanks again!
