### ISSUE TITLE
theme cicada

### ISSUE THREAD

**Issue by bcosden** [opnsense/plugins#3284]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
The new REPORTING: UNBOUND DNS page color scheme needs to adjusted for the new page color scheme released by OpnSense. On the overview page, the white overview grids are white text on white background. On the Details page, the white text on the pastel background makes the text unreadable.

**To Reproduce**
1. Go to 'Reporting->Unbound DNS -> Overview and Reporting -> Unbound DNS -> Detail'
2. See error

**Expected behavior**
Change text color in stylesheet to #000

**Screenshots**

Overview page
![image](https://user-images.githubusercontent.com/27424423/215224349-48d3b4f6-3a65-440e-b17a-fc7496bc990a.png)

Details page
![image](https://user-images.githubusercontent.com/27424423/215224373-1f445d51-952c-411d-88c0-357615625d59.png)

**Environment**
Software version used and hardware type if relevant.
OPNsense 23.1-amd64

**Comment by AdSchellevis** [comment]
duplicate https://github.com/opnsense/plugins/issues/3267
