### ISSUE TITLE
collectd plugin

### ISSUE THREAD

**Issue by willjones** [opnsense/plugins#33]
As we now have collectd available from the default repo would someone like to make this pluggable.

We use it for remote monitoring of opnsense boxes that I do not have direct access to, imagine they are behind someone else network that permits outbound connections but not inbound, we use the graphite plugin to send stats back to a remote server without needing to worry about a VPN tunnel.

Collectd can do a whole lot more beyond this, maybe it could be a good replacement for some of the RRD backend stuff? - There are plugins that could monitor other processes such as unbound, ntp, openvpn and so on.

https://collectd.org/features.shtml

GUI Ideas:

Enable / disable various plugins.
Set targets for sending data to remote collectors via graphite etc.
Some basic options to configure plugin variables.

**Comment by mimugmail** [comment]
@willjones I moved away from collectd when they jumped from 4 to 5, but I like the way you did it with Graphite! If you're still interested I'd do a collectd-agent-plugin, as far as I remember the config it should be quite easy.

**Comment by fichtner** [comment]
First development version merged thanks to @mimugmail
