### ISSUE TITLE
dns/bind named start before nginx

### ISSUE THREAD

**Issue by tinus-github** [opnsense/plugins#3302]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
At boot, when nginx starts, it tries to resolve all the hostnames it's serving. If you use the default unbound, that service starts before nginx so resolving the hostnames works. But if you use bind/named, that service starts after nginx. So nginx tries to resolve the hostnames and waits for a timeout and then fails to start. Then named starts and if you restart nginx it works. I don't know if the order of services works using numbers or dependencies or something, but named should start at the same time as unbound.

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**
1. Install os-bind (1.25_2) and os-nginx (1.31).
2. Set up opnsense to use Bind named on port 53.
3. Setup nginx to be a reverse proxy for a hostname hosted on an internal machine (with the internal hostname hosted in named)
3. Reboot
4. See on the console that nginx takes very long to start and ultimately fails.

**Expected behavior**
Everything starts correctly

**Actual behavior**
nginx waits for a timeout and does not start, complaining that it can't resolve the domains it's hosting.

**Relevant log files**
I couldn't find a log file for what you see on the console. In nginx/error.log it says 'host not found in upstream "hostname" in /usr/local/etc/nginx/nginx.conf

**Additional context**
If you login to the web interface and manually start named, the boot continues correctly. Alternatively if you configure a secondary domain server and put that first in the list, the boot also continues correctly.

**Environment**
OPNsense 23.1_6 (amd64, OpenSSL).

**Comment by fichtner** [comment]
Bind in its current state is not a replacement for Unbound/Dnsmasq. That's one of the reasons it's a plugin.


Cheers,
Franco

**Comment by fichtner** [comment]
Maybe to clarify: resolving (especially external) hostnames on bootup are an issue in any type of setup that requires early DNS. The best setup still is to use a an external DNS server in the same setup that is more or less immune to restarts or connectivity drops (serving expired too) and just migrate whatever you try to do on OPNsense. You can even use a single-WAN OPNsense VM with os-bind installed and keep your config.
