### ISSUE TITLE
Zenarmor plugin can't discover interfaces when development deployment type is selected

### ISSUE THREAD

**Issue by szafranski** [opnsense/plugins#3305]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X] The title contains the plugin to which this issue belongs

**Describe the bug**
Zenarmor cannot discover interfaces when "Development" deployment type is selected.
The "wheel" keeps going. After changing to "Production" type - works as expected.

Screenshots attached.

**Environment**
Versions OPNsense 23.1_6-amd64
FreeBSD 13.1-RELEASE-p5
OpenSSL 1.1.1s 1 Nov 2022

Proxmox VM on HP T630

<img width="699" alt="1" src="https://user-images.githubusercontent.com/23621888/218601554-2ec69a48-b482-48b4-aac8-1a4829ac91dc.png">
<img width="1440" alt="2" src="https://user-images.githubusercontent.com/23621888/218601556-1af3fa0b-cf48-47a8-be94-d214e646c2ce.png">
<img width="661" alt="3" src="https://user-images.githubusercontent.com/23621888/218601560-52947a2c-c423-421d-967b-29247c921c28.png">
<img width="1440" alt="4" src="https://user-images.githubusercontent.com/23621888/218601563-147832bb-2989-460b-bb81-3a1db6f40103.png">

**Comment by fichtner** [comment]
PHP 8.1 has become pretty strict. Probably an warning being emitted in backend code breaking JSON format or so... CC @muratbalaban43

**Comment by muratbalaban43** [comment]
@fichtner @szafranski , looking at it.
