### ISSUE TITLE
net/quagga : allow manual file config

### ISSUE THREAD

**Issue by djgreg13** [opnsense/plugins#331]
Hello,

I currently prepare a migration of a pfSense box to opnSense

I need to put manual config for quagga because gui allow a little part of quagga conf

Do you plan to allow quagga manual conf files as pfSense today ?
I have modified manual by ssh but if someone use gui files are replaced.

Thanks.

**Comment by mimugmail** [comment]
Hi,

no, there wont be a field for manual config. You can paste the parts you want/need and we'll implement them if possible

**Comment by fabianfrz** [comment]
If you want to do manual configuration, you can also install quagga or frr without the plugin. As soon as you uninstall the plugin, your configuration will not be overwritten anymore (but your setup may break in some cases).

just use `pkg install quagga` on the shell.
The old how to page still exists: https://docs.opnsense.org/manual/how-tos/quagga.html

**Comment by fichtner** [comment]
for short-term I recommend the package approach, we've made sure that services autostart when you add them to rc.conf and don't interact with the rest of the system in a negative way.

long-term asking for features in quagga (or probably frr in the mid-term) is the best bet to get everything into the GUI, API and config.xml

**Comment by djgreg13** [comment]
Principally :
- zebra password
- ospf md5 auth

I currently check if other keys are mandatory because it's migration of a very old network(2006) so confs files has lot of died confs 

Thanks for quick reply



Envoyé de mon iPhone

**Comment by fabianfrz** [comment]
a password can be set per interface if needed - maybe thar works.

what is the zebra password needed for?

**Comment by djgreg13** [comment]
Perfect,
thanks
I not see this.

Another question
Is it simple to migrate from pfSense 2.3 ? Reimport certificates is not a problem, i need a way for migrate especially for thousands firewall rules. I can reconfigure ospf after migration
