### ISSUE TITLE
Throughput Drop Seemingly After Plugins Installed, Toggling Hardware Offload Solves It - But Won't Survive a Reboot

### ISSUE THREAD

**Issue by l10nard0** [opnsense/plugins#3310]
This happened to me on the last major release and this new one.  I have Xfinity 1.2 service, Opnsense connected to the modem at 2.5.  Opnsense to LAN at 10Gbps fiber.  LAN to testing host ist 10Ggbps plus testing directly on Opnsense terminal via speedtest cli.

If I install out of the box Opnsense the throughput it as expected - no problems, and it survives reboots.

If I browse and install the plugins I'd like, boom, the throughput will not exceed 1 Gbps.

Last major release I was forced to reload from scratch with no plugins to preserve throughput.

This new major release I tried again, but ended up with the same result.  Through troubleshooting and a bit of luck I decided to try enabling hardware offload just to see the results - as I have Intel chipsets in the mainlines.

https://x.x.x.x/system_advanced_network.php

To my surprise and joy - the throughput came back to normal.  I then disabled and re-enabled and the throughput stayed correct.  It does not matter if it is enabled or disabled, the act of toggling fixes it.  However, if I reboot Opnsense I am again restricted to a 1 Gbps ceiling - never exceeding this threshold.

But if I simply go toggle the hardware offload - either on or off, doesn't matter, the throughput again returns to normal... until reboot that is...

This is my first post, I didn't know about templates.  Happy to find them and edit re-post.

**Comment by l10nard0** [comment]
Here is the hardware info:

https://bsd-hardware.info/?probe=3e96602a8f

**Comment by L1ghtn1ng** [comment]
So 2 things I have noticed, 1 you are not running 23.1.1 is there any improvements using that? Second remove ad guard home and use either unbound DNSBL to block ad’s etc or dns crypt-proxy to do that as well and does that make a difference? As my hunch says it will.

On 17 Feb 2023, at 00:16, Mike Liotus ***@***.***> wrote:

﻿

Here is the hardware info:

https://bsd-hardware.info/?probe=3e96602a8f

**Comment by l10nard0** [comment]
I upgraded to 23.1.1 after submitting this - no difference.

I will test changing the ad filtering.

Thank you.

**Comment by l10nard0** [comment]
This issue continues to this day.

I am running the latest OS / Opnsense / Firmware.

No ad software loaded anymore.

Would you like to pick this back up?

Michael
