### ISSUE TITLE
Nextcloud Backup not working with NC located on LAN

### ISSUE THREAD

**Issue by geotekberlin** [opnsense/plugins#3311]
Nextcloud Configuration Backup does no work on Nextcloud servers that are located on the local LAN. Log message is:

`Error while fetching filelist from Nextcloud '/.' path`

But this is misleading, as the HTTPS request is not even showing up on the LAN interface and consequently does not reach the NC box.

NC backup works fine if the NC Server is located on the WAN side or if a local HAProxy is reflecting the request back into the LAN. It does not matter if an IP address is given or a hostname, as soon as the resolved IP is within the LAN net, no packages are showing up on the LAN interface. Verified with packet capture and NC access log. It looks like the developers assumed that NC servers are always located in the cloud :-)

**To Reproduce**
Put a NC box in the LAN and click on Setup/Text Nextcloud. The red error badge will show up immediately.

**Expected behavior**
It should be possible to put Nextcloud servers on any connected LAN, the router should send the backup request to the appropriate interface.

**Describe alternatives you considered**
Enabled a HAProxy with a URL that accesses the WAN address and reflects the backup request into the LAN interface. This works, but can be considered a workaround kludge at best. 

**Environment**
Observed at OPNsense 22.10.1-amd64 and verified at another box in a separate location running 23.1_6-amd64

**Comment by Lebernd** [comment]
Okay, and the error is not consistent.

- Changing the URL to a wrong one with a tailing /
- Changing it back and 
- changing the ip back to host.domain.name

WORKS.

(In the mean time I have configured the same timeservers on the second opnsense)

**Comment by wols** [comment]
I had the same error `Cannot get real username` and found a tip [here](https://blog.gradiian.io/backing-up-opnsense/).

My Apache log shows lines beginning with hostname (no domain) AND without username:
```
opnsense - - [25/Feb/2023:18:59:10 +0000] "GET /ocs/v1.php/cloud/user HTTP/1.1" 403 269
```
I added a line in `/etc/hosts`...
```
192.168.1.x    opnsense.my.domain
```
...and then the username appeared(!):
```
opensense.my.domain - username [25/Feb/2023:19:08:48 +0000] "GET /ocs/v1.php/cloud/user HTTP/1.1" 200 1593
```

**Comment by Taomyn** [comment]
Hopefully someone can eventually look into this, for me no matter which internal LAN IP I used, real IP, HAProxy on OPNsense IP, even overridden by Unbound, it would fail. Nothing was ever logged on the NC server, and no connections ever detected from OPNsense.

When I overrode the FQDN of the server in Unbound with my external IP on the Internet, it started working again.

**Comment by kulikov-a** [comment]
should be something with name resolution from OPN itself? just tested on OPN 23.7.11 -> NC 27.1.5 (on LAN). works well.
does it ping by 'lan fqdn' from OPN?

**Comment by Taomyn** [comment]
> should be something with name resolution from OPN itself? just tested on OPN 23.7.11 -> NC 27.1.5 (on LAN). works well. does it ping by 'lan fqdn' from OPN?

Yes, ping, nslookup and anything else from the terminal on OPNsense all responds, it's only the plug-in that doesn't. Even if I use an IP address so DNS shouldn't be invloved, it fails and I still see no connections on the NC server (which wouldn't work anyway as Apache would have no clue where to send the traffic without knowing which site was required, but the connection should still appear).

**Comment by kulikov-a** [comment]
> but the connection should still appear

not necessary. the server log may be empty if, for example, сurl did not like the cert
what error appears in General log when you try to "Setup/Test Nextcloud"?
may be `ssl_verify_result` is not 0 in info string?

**Comment by Taomyn** [comment]
@kulikov-a you got me thinking, as even though there was no evidence in the OPNsense logs of an SSL issue, I suddenly thought that one difference between using NC via the external IP and the internal IP was the certificate. Externally it's a Let's Encrypt cert, whereas internally it's my own CA issued one, which is trusted all my devices.............apart from OPNsense where there was no sign of my CA's certificate present under "Trust, Authorities". Once I added it there and tried again, the setup/test button worked.

I still cannot explain why I was getting no traffic logged, but hopefully my experience helps someone else.

Thank-you for your comments as they help my thought processes - it's so nice to have secure automated backups again.
