### ISSUE TITLE
ACME Client: Automations: restart openvpn?

### ISSUE THREAD

**Issue by hboetes** [opnsense/plugins#3326]
Hi there,

It appears there is no ACME-client automation for restarting the OpenVPN, after updating the certificate.

I can see all kinds of things I can trigger but no option to restart OpenVPN. Also not under the system command section. "Reload IPSEC" is there. Or am I missing something? If not, please add this feature.

Thanks!
Han

**Comment by hboetes** [comment]
Will be fixed by #3327

**Comment by fraenki** [comment]
AFAICT this is fixed.

**Comment by hboetes** [comment]
https://github.com/opnsense/plugins/pull/3327#issuecomment-1474097302

**Comment by fraenki** [comment]
Please report bugs by creating a new issue, don't hijack old issues.
