### ISSUE TITLE
Cannot add new Wireguare Local due to PHP 8.1 error

### ISSUE THREAD

**Issue by Bubbgump209** [opnsense/plugins#3328]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X ] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X ] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X ] The title contains the plugin to which this issue belongs

**Describe the bug**
In creating a new Wireguard Local an error is thrown 

strtolower(): Passing null to parameter #1 ($string) of type string is deprecated. See screen shot for complete error.

I restored back to a version of my firewall on 22.7.11 and this behavior does not exist. In upgrading to 23.1_6 and then 23.1.1_2 this appears every time. This appears to be new behavior in PHP 8.1 to throw a deprecation notice.

**To Reproduce**
VPN > Wireguard> Local Tab

Click +

Enter a tunnel name, IP address (eg. 10.25.0.1/25) and a port number (eg 51825) leaving Public Key and Private Key blank.

Click Ok

**Expected behavior**
Perform the above and the Local is created along with a visible Public Key when editing the local a second time. 

**Screenshots**
<img width="892" alt="Screen Shot 2023-02-28 at 1 00 42 PM" src="https://user-images.githubusercontent.com/59414539/221941044-01b02e6a-4239-4e40-a6e1-509930559eac.png">

**Relevant log files**

**Additional context**
This started after an upgrade to 23.x. As mentioned above, I restored several backups from 22.7.11 and all of those showed correct behavior.

**Environment**
Current 23.1.1_2

**Comment by AdSchellevis** [comment]
System->Settings->Administration/Deployment type set to development? changing to production should omit this.
 should be fixed with https://github.com/opnsense/core/commit/a9ecea3dcd4aa7abfc964d9c3ebb957a9a086762

**Comment by Bubbgump209** [comment]
Bah, that's exactly what it was. Thank you!

**Comment by AdSchellevis** [comment]
hehe, things happen. This setting helps us cleanse the code for php 8.x incompatibilities, most of them are gone already, but sometimes small glitches appear.

**Comment by Bubbgump209** [comment]
That makes total sense. Welp, there's an instance if you hadn't identified it earlier. :)
