### ISSUE TITLE
Crowdsec update?

### ISSUE THREAD

**Issue by a1ad** [opnsense/plugins#3332]
Can we update Crowdsec ourselves (with a [custom](https://docs.crowdsec.net/blog/crowdsec_firewall_freebsd/) repo) or do we need to wait for the plugin maintainers to update the plugin?

I have some problems with the bouncer: https://github.com/crowdsecurity/cs-firewall-bouncer/issues/233 and I want to test with the latest version available.

Thanks.

**Comment by L1ghtn1ng** [comment]
> Can we update Crowdsec ourselves (with a [custom](https://docs.crowdsec.net/blog/crowdsec_firewall_freebsd/) repo) or do we need to wait for the plugin maintainers to update the plugin?
> 
> 
> 
> I have some problems with the bouncer: https://github.com/crowdsecurity/cs-firewall-bouncer/issues/233 and I want to test with the latest version available.
> 
> 
> 
> Thanks.

You need to wait till the plugin maintainer updates it

**Comment by a1ad** [comment]
ok
