### ISSUE TITLE
security/acme-client: Feature Request - Support for DNS-01 challenge using domain.com as registrar

### ISSUE THREAD

**Issue by winzlocom** [opnsense/plugins#3338]
When setting up a challenge of type DNS-01, there is no option in the drop-down list for domain.com.  Request it be added ASAP so I can generate wildcard SSL certificates for my company’s hosted services.  An alternative workaround would be appreciated also and in the meantime.  Thanks for an awesome plug-in that I can’t wait to use.  ;)

**Comment by fraenki** [comment]
AFAICT, there is no support for domain.com in our upstream project acme.sh:
https://github.com/acmesh-official/acme.sh/wiki/dnsapi
acme.sh needs to support the DNS API, otherwise we can't integrate it into the acme-client plugin.

**Comment by winzlocom** [comment]
Acknowledged. Since domain.com supports an API, is this still a viable request?  It would simplify my hosting need by reducing the need to use clouddns.net since domain.com doesn’t allow for manual  TXT records that are needed for DNS-01 validation.

**Comment by fraenki** [comment]
Yes, still a viable request. But we can't start to work on this until someone adds the required functionality to [acme.sh](https://github.com/acmesh-official/acme.sh).

(FYI, this issue will timeout soon. But it may be re-opened when/if the feature is available in acme.sh.)
