### ISSUE TITLE
Dynamic DNS (ddclient): columns not showing ip address and ddns updated every 5 minutes

### ISSUE THREAD

**Issue by Christophe999s** [opnsense/plugins#3344]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**
The ip-address and updated columns in Services: Dynamic DNS: Settings aren't being populated.
Issue with duckdns and ddclient showing failed has been fixed upstream: https://github.com/ddclient/ddclient/issues/503
Cloudflare updates correctly, but ip isn't shown. Using interface for check ip.
Even though the dns is updated correctly, ddclient keeps updating it every 5 minutes

**Expected behavior**
Populate 'Current IP' an 'Updated' in GUI
Only request update when interface ip has changed

**Describe alternatives you considered**
Using legacy ddns plugin as a workaround for now

**Screenshots**
![account](https://user-images.githubusercontent.com/36367001/224303015-0c79e0b9-f0e0-4bfd-b187-fbd455c2e8ff.png)
![logs](https://user-images.githubusercontent.com/36367001/224304413-2c58ad08-3245-43e1-bc15-65a074438d8b.png)
![settings](https://user-images.githubusercontent.com/36367001/224303021-419a1107-516e-486d-abc0-98a52c6e9980.png)

**Environment**
OPNsense 23.1.1_2-amd64
FreeBSD 13.1-RELEASE-p6
OpenSSL 1.1.1t 7 Feb 2023
Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz (4 cores, 4 threads)
Running in Proxmox VM

**Comment by cektom** [comment]
I have the same problem and also created an issue #3341 (Maybe we can close mine?)
According to the post, it seems that ddclient is dead (or dying) [Future of the project or the lack of one #528](https://github.com/ddclient/ddclient/issues/528)
So I guess OPNsense needs an alternative in the future.

**Comment by cektom** [comment]
@AdSchellevis Yeah, I've seen this option and tried that. Unfortunately I couldn't find much documentation/explanation about it. I will definitely play around with the feature and try to implement Cloudflare support. But don't expect a pull request too soon. I temporarily fixed my problem with a custom script on my Linux machine. So to everyone else reading this, if you're faster than me or have more experience in OPNsense development, don't hesitate to implement Cloudflare support.

**Comment by sfdementor** [comment]
To get the "OPNsense" backend (Services: Dynamic DNS: Settings/General Settings/backend) working i also had to delete file "/var/tmp/ddclient.cache".

**Comment by AdSchellevis** [comment]
@cektom the documentation needs to be updated indeed, added a tracking ticket for that https://github.com/opnsense/docs/issues/466

**Comment by cektom** [comment]
[Cloudflare implementation for OPNsense backend ddclient](https://github.com/opnsense/plugins/pull/3357)

**Comment by fichtner** [comment]
Some fixes went in. I'm not seeing this problem regularly anymore.
