### ISSUE TITLE
Os-xen plugin crashed after update

### ISSUE THREAD

**Issue by cardosocristian** [opnsense/plugins#3346]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x ] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x ] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x ] The title contains the plugin to which this issue belongs

**Describe the bug**
After upgrading Opnsense from version 22 to version 23.1, the os-xen plugin is no longer starting and displays the following error on the startup screen:

```
ld-elf.so.1: Shared object "libxenstore.so.4" not found, required by "xenstore"
```

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)`
On other servers that are still in version 22 the plugin is still working.

**To Reproduce**
1. After updating the problem will be displayed on the system boot screen in the terminal

**Expected behavior**
Get the bug fixed

**Screenshots**
No

**Relevant log files**
If applicable, information from log files supporting your claim.

**Additional context**

**Environment**
OPNsense 23.1
VM on XCP-NG with 8 vCPU's and 8GiB Memory

**Comment by billgertz** [comment]
Up to the powers that be, could be combined with issue #3347 as that issue contains the fix. @cardosocristian would you consider closing this issue as issue #3347 documents the fix?
