### ISSUE TITLE
Wireguard plugin API call 

### ISSUE THREAD

**Issue by bobbylv75** [opnsense/plugins#3355]
I wanna automate user creation for OpnSense Wireguard plugin.

1. I can create new user by /wireguard/client/addclient api call (an example new peer have uuid "7cd840ca-d649-4df5-aa01-5c2f783980c7") .

3. Now I need to enable new user (Peer) in VPN>Wireguard>Local>Peers

I call /wireguard/server/set API with JSON 

{
  "server": {
    "enabled": "1",
    "peers": {
      "7cd840ca-d649-4df5-aa01-5c2f783980c7": {
        "selected": "1"
      }
    },
    "uuid": "9cdba781-2611-4168-97f2-1ff25c61a64f"
  }
}

where "9cdba781-2611-4168-97f2-1ff25c61a64f" is my Wireguard server uuid

and next call /wireguard/service/reconfigure API

But unfortunally new peer stay uncheked in VPN>Wireguard>Local>Peers :(((((

What I do wrong?

**Comment by ezra-buckingham** [comment]
Can you give an sample of the payload you are sending to create the client, I am still just trying to create the client :)

**Comment by bobbylv75** [comment]
This is part of Jenkins job (sh call):

header="Content-Type: application/json"
auth="${env:opnUser}:${env:opnPassword}"
url="http://10.99.10.1/api/wireguard/client/addClient"
data='{"client": {"enabled": "1","name": "${env:uName}_${env:ulName}","pubkey": "${env:pubkey}","tunneladdress": "${env:vpnAddr}","persistentkeepalive": "25"}}'
curl -X POST -H "\$header" -u "\$auth" -d "\$data1" "\$url"



Subscribe if you can solve my problem :))))))))

**Comment by pkoevesdi** [comment]
Here it is made with `wireguard/server/setServer`: https://github.com/FingerlessGlov3s/OPNsensePIAWireguard/blob/main/PIAWireguard.py
Still I couldn't get it to work. Do I need to repost all existing peers? I tried it, but the new one still is not "selected" in the GUI.

**Comment by pkoevesdi** [comment]
Ok, I found out how to set an single peer active:
send `{'server': {'peers': SinglePeerUUID}}` to `wireguard/server/setServer`, then `SinglePeerUUID` gets enabled.
But, my problem is, all others that were enabled before are disabled now. How can I either leave them alone, or set multiple peers enabled? I triewd to post a list of UUIDs instead of `SinglePeerUUID`, but this doesn't work. Any help appreciated.

**Comment by pkoevesdi** [comment]
Ok, I figured this out and posted here: https://forum.opnsense.org/index.php?topic=33177.msg163175#msg163175:
To set an single peer active send `{'server': {'peers': SinglePeerUUID}}` to `wireguard/server/setServer/ServerUUID`, then _`SinglePeerUUID`_ gets enabled. To set multiple active: `{'server': {'peers': 'SinglePeerUUID1,SinglePeerUUID2' }}`
Take care, not to send a json array `['SinglePeerUUID1','SinglePeerUUID2']`, but a string with comma separated values.

Still I consider this a bug - in the documentation. IMO this belongs on this page: https://docs.opnsense.org/development/api/plugins/wireguard.html

**Comment by pkoevesdi** [comment]
I made a little project which allows to make a new wireguard peer and push it to the opensense: https://github.com/pkoevesdi/wg-keygen-notrust. Can also be used as a demo for the wireguard API.
