### ISSUE TITLE
ddclient - won't accept two freedns accounts

### ISSUE THREAD

**Issue by Sopor** [opnsense/plugins#3356]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
I'm using two different freedns accounts (let use call them account `one` and `two`) and i only get
`FAILED: updating xxxxxx.xxxxxxx.org: Cannot set IPv4 to 123.123.123.123 No 'A' record at FreeDNS`
on account `one` when both accounts are enabled.

Account `two` has no problem to work
`SUCCESS: updating xxxxx.xxxxx.info: update not necessary, 'A' record already set to 111.222.11.22`

Account `one` is the account at the top in `OPNSense` and in `ddclient.conf`.

If i disable account `two` it make account `one` start to work.

**To Reproduce**
1. Add two different accounts at freedns
2. Enable both
3. Check log

**Expected behavior**
Both accounts should work of course 😊

**Screenshots**
![image](https://user-images.githubusercontent.com/5789283/227062037-3a821ad2-0681-4644-ae53-e70b0d48449d.png)

**Additional context**
I don't get any `Current IP` or `Updated` either as you can see in the above picture.

Login and password are correct because i have tried them both and i can login with them both.

I have tried to enable and disable SSL, but i get the same error.

The only thing that will get account `one` to work is to disable account `two` as i already have mentioned above.

**Environment**
OPNsense 23.1.4_1-amd64
ddclient 1.11_1

**Comment by AdSchellevis** [comment]
General settings -> Backend = OPNsense might work better, (ddclient's state : https://github.com/ddclient/ddclient/issues/528 )

**Comment by Sopor** [comment]
@AdSchellevis Thanks, but how do i know it works?

I can't see any IP addresses, nor any Updated and the log is empty 😕

**Comment by AdSchellevis** [comment]
new backend also feeds data to the gui, I would start to look at logs in any case

**Comment by Sopor** [comment]
I was going to update my UPS, so i shut down all my computers and after OPNsense was up and running again my ddns did not updated as they should when i was running `Backend = OPNsense`. So, it seems that this is not working at all 😒

To update my ddns i changed back to `Backend = ddclient` and enable and disable the freedns account one by one.

Not the best way to update, but it worked.

Btw, is it possible to add a custom cron job script that will update my ddns?

**Comment by Sopor** [comment]
Sad to see that ddclient is not working and it was nice when i could see the updates on the dashboard (Legacy ddns).

Now i run it as a cron job by using the curl script from FreeDNS. It seems to work, so far.

Should i leave this issue open or should i close it?

It is still a bug that it can't handle two accounts from FreeDNS, but i assume you can't do anything about it?

**Comment by AdSchellevis** [comment]
I don't think our backend has a notion of the same provider, it just updates the entries in `/usr/local/etc/ddclient.json`, could also be a limitation of freedns, but in both cases, logs matter.
