### ISSUE TITLE
os-ddclient: OPNsense backend - custom dyndns2 endpoint

### ISSUE THREAD

**Issue by ei-ke** [opnsense/plugins#3362]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
Current state: The OPNsense backend that has been added to os-ddclient allows to choose the interface and also to only use the interface's IPv6 address for the available dyndns providers. This, in theory, solves the issue with CGNAT that I described a while back (#2872) where the CGNAT IPv4 and the public IPv6 is pushed to the dyndns provider when using the ddclient backend.
A workaround was using external services that just reply the IPv6 address to ddclient. But sometimes I got timeouts and honestly prefer to do those things locally.

**Describe the solution you'd like**
As written [here](https://github.com/opnsense/plugins/issues/3037#issuecomment-1465017282) I'd like to suggest to offer a generic dyndns2 option like the "Custom" service option when using the ddclient backend where I can just enter the dyndns server I'm using - btw: it's desec.io .

**Describe alternatives you've considered**
The other option would be to port the interface chek IP method with the IPv4/IPv6 option for the ddclient backend which already has the "Custom" service option. Not sure which is easier to implement / maintain.

**Additional context**

**Comment by AdSchellevis** [comment]
@ei-ke for the dyndns2 protocol this (https://github.com/opnsense/plugins/commit/410cb9dbf812d2e02aa38adba13176501869a369) should be all that's needed.
