### ISSUE TITLE
Maltrail version issue: requires 23.1.5 but 23.1_6 installed

### ISSUE THREAD

**Issue by Extarys** [opnsense/plugins#3370]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
Trying to install os-maltrail result in a version error:
```
***GOT REQUEST TO INSTALL***
Currently running OPNsense 23.1_6 at Wed Mar 29 12:34:20 EDT 2023
Installation out of date. The update to opnsense-23.1.5 is required.
***DONE***
```

**To Reproduce**
1. Update to latest version 23.1.6
2. Try to install os-maltrail

**Expected behavior**
Maltrail should install and run fine

**Additional context**
I had issues where the maltrail daemon would simply stop without any error in the logs, so I uninstalled the plugin, upgraded to the latest version (was on 22.x) and tried to reinstal the plugin.

**Environment**
Software version used and hardware type if relevant.

OPNsense 23.1_6-amd64
FreeBSD 13.1-RELEASE-p5
OpenSSL 1.1.1s 1 Nov 2022
Intel(R) Celeron(R) N5105 @ 2.00GHz (4 cores, 4 threads)
2x8 GB of RAM

**Comment by fichtner** [comment]
23.1.6 is not a version we have as of today. You have 23.1_6 which is smaller than 23.1.5, which is the current version.

Simply updating your firewall will fix it...

**Comment by Extarys** [comment]
Oh, I thought upgrading to 23 was upgrading to the latest available version. I was confused by the version string :joy:  I understand now that after the upgrade to 23 I need to update to 23.x.

Thank you and sorry.
