### ISSUE TITLE
net/frr - BGP passwords not being added automatically (register_sas script not running)

### ISSUE THREAD

**Issue by as8net** [opnsense/plugins#3372]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X] The title contains the plugin to which this issue belongs

**Describe the bug**
When configuring a BGP peer with a password, the key is not automatically added to setkey. I manually have to run
/usr/local/opnsense/scripts/frr/register_sas
on each reboot

**To Reproduce**
1. Configure a BGP peer with a password and a local initiator IP
2. Check with `setkey -D` that no keys have been added to the system
3. Reboot the machine/restart FRR - still no keys present
4. Run `/usr/local/opnsense/scripts/frr/register_sas` manually - keys have now been added, but this needs to be done manually after each reboot

**Expected behavior**
register_sas should run when FRR is reloaded from the gui, and on reboots

**Environment**
OPNsense 23.1.5_2-amd64
FreeBSD 13.1-RELEASE-p7
OpenSSL 1.1.1t  
7 Feb 2023
Intel Xeon Processor (Cascadelake) (1 cores, 1 threads)

**Comment by AdSchellevis** [comment]
it should execute that at service start https://github.com/opnsense/plugins/blob/3e64ff9251fb9c1b332f2faf2f98385cad884192/net/frr/src/opnsense/scripts/quagga/setup.sh#L23

don't think a lot changed here recently.

**Comment by as8net** [comment]
I've only been trying this since february so i can't say if it worked in a previous release, but (unless i've misconfigured something) it isn't working as i'd expect atleast.

Are there any logs that would be helpful, to see if /usr/local/opnsense/scripts/frr/register_sas is being run in the setup script?

**Comment by AdSchellevis** [comment]
it doesn't really log, but the action that should trigger it is the usual rc script `/usr/local/etc/rc.d/frr start`  (or restart) as defined in the configd action (https://github.com/opnsense/plugins/blob/master/net/frr/src/opnsense/service/conf/actions.d/actions_quagga.conf).

Easiest option is to add some "echo" there and start. I don't think FRR needs to be active in order to add the key.

**Comment by olanystrom** [comment]
After looking at this for a while.
The quick and easy solution is to patch line 14 and 21 of https://github.com/opnsense/plugins/blob/master/net/frr/src/opnsense/service/conf/actions.d/actions_quagga.conf to just add a call to  /usr/local/opnsense/scripts/frr/register_sas 
Is that an acceptable solution?

The real rc.d-script comes from the ports-tree and it does not feel right to add a depentancy to  register_sas from this package to the rc-script in ports.

**Comment by sopex** [comment]
@olanystrom Open a PR. Should it only be on restart?

**Comment by olanystrom** [comment]
> [@olanystrom](https://github.com/olanystrom) Open a PR. Should it only be on restart?

I would think on restart and reload.
I will open a PR.
