### ISSUE TITLE
WireGuard API

### ISSUE THREAD

**Issue by neverlless** [opnsense/plugins#3373]
**Important notices**
Our forum is located at https://forum.opnsense.org , please consider joining discussions there in stead of using GitHub for these matters.

Before you ask a new question, we ask you kindly to acknowledge the following:

- [+] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [+] I have searched the existing issues, open and closed, and I'm convinced that mine is new.

I send a request via the opnsense api to edit the wireguard server to add a peer(/api//wireguard/server/setServer/uuid), but even if I send the same information that I received from the get method, I get an error {"result":"failed","validations":{"server.peers":"Choose an Peer."}

Please, tell me how to solve this error.

**Comment by abruening-iwt** [comment]
I just ran into the same issue, the format expected appears to be

```
{"server": {"peers":"uuid,uuid[,...]"}}
```

instead.

**Comment by pkoevesdi** [comment]
I had the same issue and resolved it this way: https://github.com/pkoevesdi/wg-keygen-notrust/blob/opnsensebridge/opnsensebridge.py#L84
