### ISSUE TITLE
Wireguard, show Timestamp in UI under "VPN/Wireguard/Handshakes"

### ISSUE THREAD

**Issue by NightDragon1** [opnsense/plugins#3378]
The Information about the handshakes of Wireguard Endpoints can be found under "VPN/Wirguard/Handshhakes". The information displayed there is pretty raw.

The Minimum to adjust is to at format the unix timestamp to a more common time format.
The best option would be that also Alias/Endpoint names are shown instead of keys (only)

**Comment by hvdort** [comment]
After recent update to 2.0, the handshake page is replaced by diagnostics. I like that change!
The only thing I'm missing is the "latest handshake" time. It 's very useful to see if the VPN is in use on that moment...

**Comment by AdSchellevis** [comment]
@hvdort I think this is what you’re looking for : https://github.com/opnsense/plugins/commit/7e42d0b5542c1b1b54cb304e740b8f865b300d23
