### ISSUE TITLE
ddclient doesn't work with Hetzner DNS

### ISSUE THREAD

**Issue by jusicgn** [opnsense/plugins#3389]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X] The title contains the plugin to which this issue belongs

**Describe the bug**
A clear and concise description of what the bug is, including last known working version (if any).

In the legacy "DynDNS Client" I have my DNS entry at Hetzner DNS updated without any problems.
Now wanted to switch to the "ddclient" but it doesn't work.
Of course I used the same credentials as in the legacy Client.

In the ddclient logs it says:
4338 - [meta sequenceId="100"] FAILED: updating test-opnsense: invalid json or result.
I can also see in the logs that the Hetzner API is sending the zone data.
Therefore I assume that there is some trouble with parsing the data.

Please let me know if you need further logs or stuff.

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**
1. In ddclient add an account with Hetzner DNS
2. See the logs and Hetzner DNS Console to verify it's not updated

**Expected behavior**

Update DNS entry at Hetzner DNS.

**Screenshots**

**Relevant log files**
If applicable, information from log files supporting your claim.

In the ddclient logs it says:
4338 - [meta sequenceId="100"] FAILED: updating test-opnsense: invalid json or result.

Can provide more logs but have to redact them as there are the API keys in and my DNS zones and stuff. Please let me know if it's necessary and I'l provide them.

**Additional context**

**Environment**
Software version used and hardware type if relevant.
e.g.:

OPNsense 23.1.5_4-amd64
FreeBSD 13.1-RELEASE-p7
OpenSSL 1.1.1t 7 Feb 2023
os-ddclient (installed) | 1.11_1
os-dyndns (installed) | 1.27_3

**Comment by ThomasTr** [comment]
They broke hetzner dns update in ddclient and fixed it in https://github.com/ddclient/ddclient/pull/491
Until there is a new ddclient / os-ddclient version, you can fix it with:

Replace in /usr/local/sbin/ddclient
```
$url = "https://$config{$key}{'server'}/records?$zone_id";
```
with:
```
$url = "https://$config{$key}{'server'}/records?zone_id=$zone_id";
```

**Comment by Hideloop** [comment]
Thank you!

Thomas Trautner ***@***.***> schrieb am Di., 23. Mai 2023,
15:18:
