### ISSUE TITLE
NSD support in the future?

### ISSUE THREAD

**Issue by dngray** [opnsense/plugins#3391]
- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

I'm wondering whether at some point [NSD](https://www.nlnetlabs.nl/projects/nsd/about/) support will be something that will be worked on. I did notice this issue https://github.com/opnsense/plugins/issues/405 but it's from some time ago.

Since then it certainly seems Unbound has been selected as the default choice, (since 17.7) and more features (such as DNS statistics) are [being developed](https://opnsense.org/opnsense-23-1-released/) :+1: .

It would then make logical sense that would be paired with something more lightweight in order to reduce complexity. NSD is [authoritative only](https://github.com/NLnetLabs/nsd/blob/master/doc/NSD-FOR-BIND-USERS#L27). From what I can see it could replace the portion of features BIND provides that Unbound does not.

Thoughts?

**Comment by dngray** [comment]
I didn't expect it to be a priority as BIND likely meets most usecases. I was only curious if there were any thoughts on it given Unbound was being adopted, and from what I see elsewhere NSD is often touted as a "more secure/modern" alternative. Likely a part of the latter sentiment is because of what ended up happening to BIND10.

As for how authoritative dns and the core system this is how I am thinking of using it:

I want to use BIND's authoritative features to manage `.home.arpa`. I also think that with the [BIND opnsense plugin](https://github.com/opnsense/plugins/blob/master/security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml#L489) I can do [DNS-01 challenge](https://smallstep.com/docs/step-ca/acme-basics/#the-dns-challenge-dns-01), with my [own CA](https://smallstep.com/blog/build-a-tiny-ca-with-raspberry-pi-yubikey/). I noticed that a lot of those options rely on a third party provider API. I couldn't find much about [nsupdate (RFC 2136)](https://github.com/opnsense/plugins/blob/master/security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml#L487) and whether this could be used to do what I want. The intention is to have the OPNsense device get a new web certificate regularly from the CA on my LAN. I [don't want to use a public CA](https://smallstep.com/blog/reasons-not-to-use-public-certificate-authorities/#3-certificate-transparency-logs-used-by-public-web-cas-expose-internal-networks-to-potential-security-risks) for that because I'm worried about ct logs of networks which are not ever going to be public facing anyway.

I tried this with a forward zone [same as this post](https://forum.opnsense.org/index.php?topic=33537) and had the same issues with Unbound being unable to get anything back from BIND but a SOA when using "Query Forwarding". That seems to create a "forward zone". After reading this post about [stub zones](https://calomel.org/unbound_dns.html), I think that's more what I want:

> #### Unbound DNS cluster with [BIND](https://calomel.org/dns_bind.html) or [NSD](https://calomel.org/nsd_dns.html) master server
>
>
>The idea is to have a few Unbound validating, recursive and caching DNS servers which LAN clients can query. Then use BIND (named) as an authoritative server which can resolve internal LAN names only. LAN clients will NEVER access the BIND DNS server and BIND will never go out to the Internet. BIND's only job is to serve internal names to the Unbound DNS server cluster. The Unbound cluster will serve all LAN clients. If Unbound needs to resolve a private ip it will ask the BIND server for ips and then cache the response. If the client needs an external ip, lets say from google.com or cnn.com, Unbound will recursively query the Internet root DNS servers and cache the response.

> Pay special attention to the stub-zone directive we are using. Stub-zone is only used to point queries to an authoritative server like a [NSD](https://calomel.org/nsd_dns.html) dns server. The forward-zone directive can only be used to point queries to a resolving dns server like OpenDNS.com or you local ISP's caching server. The two are not interchangeable.

One thing I did discover about the Unbound plugin, is there doesn't seem to be a way to make a stub zone I am using opnsense-business 22.10.2 which came with my DEC3840 (not sure if the community edition would be more appropriate or has more features here).

Would the correct approach be to use an [advanced config](https://docs.opnsense.org/manual/unbound.html#advanced-configurations) template?

On a side note I noticed there the BIND section refers to the [Custom Options](https://docs.opnsense.org/manual/how-tos/bind.html#advanced) section that should be updated as it no longer exists.

**Comment by melroy89** [comment]
I fully believe NSD is the future and not bind!

If you need a recursive resolver, run unbound. If you need an authoritative DNS server, use nsd. Please provide a NSD plugin.
