### ISSUE TITLE
FRR weight on BGP Neigbors with IPv6 not working

### ISSUE THREAD

**Issue by Yoshi-081** [opnsense/plugins#3392]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
[X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

if a BGP session is established with IPv6 the weight ist not added right to config. it is mistakenly added to the ipv4 block.

**To Reproduce**

Install os-frr 

Setup BGP on two Interfaces and two OPNsense Instances with IPv6 and IPv4

Set weight to 10 and 20 and Apply

Under Diagnostics -> General

weight is added incorrectly under the ipv4 block

......
 !
 address-family ipv4 unicast
  neighbor 192.168.10.30 activate
  neighbor 192.168.10.30 weight 10
  neighbor 192.168.10.30 route-map IPv4 in
  neighbor 192.168.10.34 activate
  neighbor 192.168.10.34 weight 20
  neighbor 192.168.10.34 route-map IPv4 in
  **_neighbor 2a01:xxx:90::2 weight 10
  neighbor 2a01:xxx:f90::2 weight 20_**
exit-address-family
 !
 address-family ipv6 unicast
  neighbor 2a01:xxx::2 activate
  neighbor 2a01:xxx::2 route-map IPv6 in
  neighbor 2a01:xxx:90::2 activate0
  neighbor 2a01:xxx:90::2 route-map IPv6 in
  neighbor 2a01:xxx:f90::2 activate
  neighbor 2a01:xxx:f90::2 route-map IPv6 in
 exit-address-family
 !
....

**Expected behavior**
Weight on IPv6 should be set correct

**Describe alternatives you considered**
Current Workaround:
set weight via CLI (vtysh)

**Environment**
OPNsense 23.1.5_4-amd64
FreeBSD 13.1-RELEASE-p7
OpenSSL 1.1.1t 7 Feb 2023

**Comment by mimugmail** [comment]
Are you sure? My test system is on 23.1.4 and look good:


```
log syslog notifications
frr defaults traditional
!
!
!
router bgp 65001
 no bgp default ipv4-unicast
 no bgp ebgp-requires-policy
 bgp network import-check
 neighbor 10.255.255.2 remote-as 65002
 neighbor 10.255.255.2 password test
 neighbor 10.255.255.2 weight 10
 neighbor 10.255.255.2 update-source vlan01
 neighbor 2001:dba::1 remote-as 65002
 neighbor 2001:dba::1 password test
 neighbor 2001:dba::1 weight 20

 address-family ipv4 unicast
  network 192.168.1.0/24
  neighbor 10.255.255.2 activate
 exit-address-family
!
 address-family ipv6 unicast
  neighbor 2001:dba::1 activate
 exit-address-family
!

```

**Comment by Yoshi-081** [comment]
> Are you sure? My test system is on 23.1.4 and look good:

Yes, i have rebootet my device. Same behavior.

See attached pictures

Neigbors

![image](https://user-images.githubusercontent.com/77161028/233747295-6d5cd7f8-3336-431e-8397-abcec3d9e49a.png)

![image](https://user-images.githubusercontent.com/77161028/233748129-e71b6e80-c4af-4db6-8126-c34980da926d.png)

Diagnostics -> General -> IPv6 Routes

Weight is 0

![image](https://user-images.githubusercontent.com/77161028/233747145-ab26ca4a-94bb-4e5a-a9ab-d2ef35c1cff1.png)

Running Configuration

> Building configuration...

>Current configuration:
!
frr version 7.5.1
frr defaults traditional
hostname OPNsense.vnet
log syslog notifications
!
router bgp 65552
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 bgp graceful-restart
 neighbor 192.168.10.30 remote-as 65000
 neighbor 192.168.10.30 bfd
 neighbor 192.168.10.30 update-source wg2
 neighbor 192.168.10.34 remote-as 65000
 neighbor 192.168.10.34 bfd
 neighbor 192.168.10.34 update-source wg3
 neighbor 2a01:xxxx:90::2 remote-as 65000
 neighbor 2a01:xxxx:90::2 bfd
 neighbor 2a01:xxxx:f90::2 remote-as 65000
 neighbor 2a01:xxxx:f90::2 bfd
 !
 address-family ipv4 unicast
  neighbor 192.168.10.30 activate
  neighbor 192.168.10.30 weight 10
  neighbor 192.168.10.30 route-map xxxIPv4 in
  neighbor 192.168.10.34 activate
  neighbor 192.168.10.34 weight 20
  neighbor 192.168.10.34 route-map xxxIPv4 in
  neighbor 2a01:xxxx:90::2 weight 10
  neighbor 2a01:xxxx:f90::2 weight 20
 exit-address-family
 !
 address-family ipv6 unicast
  neighbor 2a01:xxxx:90::2 activate
  neighbor 2a01:xxxx:90::2 route-map xxxIPv6 in
  neighbor 2a01:xxxx:f90::2 activate
  neighbor 2a01:xxxx:f90::2 route-map xxxIPv6 in
 exit-address-family
!
ip prefix-list xxxIPv4 seq 101 permit any
!
ipv6 prefix-list xxxIPv6 seq 101 permit 2a01:xxxx::/64 le 76
!
route-map xxxIPv4 permit 101
 match ip address prefix-list xxxIPv4
!
route-map xxxIPv6 permit 101
 match ipv6 address prefix-list xxxIPv6
!
line vty
!
bfd
 peer 192.168.10.6
 !
 peer 2a01:xxxx:10::2
 !
 peer 192.168.10.34
 !
 peer 192.168.10.30
 !
 peer 2a01:xxxx:f90::2
 !
 peer 2a01:xxxx:90::2
 !
!
end

Weight is generated to address-family ipv4 unicast

**Comment by mimugmail** [comment]
The sh run is done in runtime, so its frr itself putting there.
When you look at bgpd.conf via cli its correct.

**Comment by Yoshi-081** [comment]
you are right.

In the file /usr/local/etc/frr/bgpd.conf its correct.

**Comment by mimugmail** [comment]
So the main question, is it causing trouble at your site or do you just think its a but cause of wrong position?

**Comment by Yoshi-081** [comment]
As the weighting does not work with IPv6, there is a bug for me.

See here is 0 instead of 10 and 20

Unfortunately for IPv6 the backup link is now preferred.

```
BGP table version is 1, local router ID is 192.168.105.33, vrf id 0
Default local pref 100, local AS 65552
Status codes:  s suppressed, d damped, h history, * valid, > best, = multipath,
               i internal, r RIB-failure, S Stale, R Removed
Nexthop codes: @NNN nexthop's vrf id, < announce-nh-self
Origin codes:  i - IGP, e - EGP, ? - incomplete

   Network          Next Hop            Metric LocPrf Weight Path
*= 2a01:xxxx:40::/76
                    2a01:xxxx:f90::2
                                             0             0 65000 i
*>                  2a01:xxxx:90::2
                                             0             0 65000 i

Displayed  1 routes and 2 total paths
```
netstat

`2a01:xxxx:40::/76        2a01:xxxx:90::2      UG1         wg2`

route via 2a01:xxxx:f90::2 would be the goal.

Comparison with IPv4

```
BGP table version is 1, local router ID is 192.168.105.33, vrf id 0
Default local pref 100, local AS 65552
Status codes:  s suppressed, d damped, h history, * valid, > best, = multipath,
               i internal, r RIB-failure, S Stale, R Removed
Nexthop codes: @NNN nexthop's vrf id, < announce-nh-self
Origin codes:  i - IGP, e - EGP, ? - incomplete

   Network          Next Hop            Metric LocPrf Weight Path
*> 206.x.x.41/32    192.168.105.34           0            20 65000 i
*                   192.168.105.30           0            10 65000 i

Displayed  1 routes and 2 total paths
```
netstat

`206.x.x.41      192.168.105.34     UGH1        wg3`

route via 192.168.105.34  as expected

**Comment by mimugmail** [comment]
@fichtner maybe publish a frr8 pkg and test? To me it sounds as a bug in frr itself

**Comment by ruifung** [comment]
Just stumbled upon this when setting up my backup router. 
For anyone else who finds this in the future, assuming it's not fixed in an FRR update or anything.
You can use route-maps to achieve the same effect.

Just create route maps with the weight <weight> in it's set field, and apply it to your peers.

![image](https://github.com/user-attachments/assets/d788a4c3-3d88-4d6b-9b33-a2970b854e0d)
