### ISSUE TITLE
Tayga logging bugged "Wrote somethinh"

### ISSUE THREAD

**Issue by agowa338** [opnsense/plugins#3394]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Logging of tayga is bugged.

**To Reproduce**

Steps to reproduce the behavior: Unknown (I suspect it happens when something tries to access an RFC1918 that got mapped to the well-known prefix 64:ff9b::/96, but without working logs it is hard to tell). See screenshot.

**Expected behavior**

Correct error message

**Describe alternatives you considered**

SSH and looking for the log files

**Screenshots**

![image](https://user-images.githubusercontent.com/2544867/232667569-f0acd982-b35a-4fbf-b10c-738d6bad0f42.png)

**Environment**

Software version used and hardware type, if relevant, e.g.:

OPNsense 23.1.5_4-amd64
FreeBSD 13.1-RELEASE-p7
OpenSSL 1.1.1t 7 Feb 2023
AMD Ryzen 7 3800X 8-Core Processor

**Comment by mimugmail** [comment]
Seems to be a problem of Taiga itself,  I only maintain the plugin around. Did you try contacting the author of it?

**Comment by kulikov-a** [comment]
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=253605 ?

**Comment by fichtner** [comment]
https://github.com/opnsense/ports/commit/df4d23f1314bd
