### ISSUE TITLE
ddclient updates DNS entry without having an IP address

### ISSUE THREAD

**Issue by codiflow** [opnsense/plugins#3396]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
ddclient (the legacy one and not the new OPNsense backend) updates the DNS entry **without having an IP address at all**. Therefore I assume the A entry gets removed because it's emtpy. This should never happen.

**To Reproduce**
Not an easy thing as I don't know why OPNsense can't get its public IP address. Everything worked before the provider reconnect (and before the update to 23.1.5_4 but this has not been validated yet).

The configuration is as follows:

![grafik](https://user-images.githubusercontent.com/43847817/233036511-1ef7fcc0-13a0-406e-af3c-d1d48b11dc7e.png)

**Expected behavior**
If the IP address is **empty** the update procedure should be **canceled** and a request with an empty IP address should not be sent under any circumstances.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/43847817/233035542-2b240631-610b-4e4f-9b8b-4aac8f67f027.png)

![2023-04-19_11-21](https://user-images.githubusercontent.com/43847817/233035016-00d3ba3b-c99e-4624-bc94-55e3d7ce3dbc.png)

**Additional context**
Before updating to 23.1.5_4 I think everything worked as it should. But as the internet provider (it's a Telekom LTE backed DSL connection) only reconnects every few weeks I can't verify that.

I will try to switch to the new OPNsense backend as ddclient seems to be dead (https://github.com/opnsense/plugins/issues/3344). So this issue is for informational purposes only as I suppose ddclient will get removed in a future release because of being unmaintained.

**Environment**
OPNsense  23.1.5_4

**Comment by codiflow** [comment]
Seems like the used service for getting the IP address (freedns) was down yesterday:
![grafik](https://user-images.githubusercontent.com/43847817/233324393-fad5800d-d966-43d7-acb6-914bdca59a97.png)

But if a service like freedns is not able to return an IP address ddclient should skip the update procedure instead of updating the entry with an empty value.

**Comment by j-vaughn** [comment]
Was there any update or workaround on this? I was trying to test out a dual wan gateway the other day and realized my dynamic dns entry received an update of blank when I disabled one of the wan interfaces. 

23.7.4 with ddclient backend
