### ISSUE TITLE
[FR] devel/helloworld add example for a cron job

### ISSUE THREAD

**Issue by gitdevmod** [opnsense/plugins#34]
Could you add an example for a creating a cron job?

Thanks in advance

**Comment by AdSchellevis** [comment]
@gitdevmod you best take a look at the IDS controller  https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/controllers/OPNsense/IDS/Api/ServiceController.php#L121

**Comment by gitdevmod** [comment]
@AdSchellevis I tried this https://github.com/gitdevmod/plugins/blob/master/sysutils/SSOProxyAD/src/opnsense/mvc/app/controllers/OPNsense/SSOProxyAD/Api/ServiceController.php but I do not see the cron job with "crontab -l". I want to run joinDomain the first day of month.

**Comment by AdSchellevis** [comment]
@gitdevmod did you apply the new settings in Cron? it should generate your crontab to /var/cron/tabs/nobody

**Comment by gitdevmod** [comment]
How do I apply the new settings? I used "save" button

**Comment by AdSchellevis** [comment]
Apply at the bottom of the screen in /ui/cron/

**Comment by gitdevmod** [comment]
There is "no results found!" after apply

**Comment by AdSchellevis** [comment]
what does the cron overview look like?

**Comment by gitdevmod** [comment]
https://github.com/gitdevmod/plugins/blob/master/sysutils/SSOProxyAD/src/opnsense/mvc/app/models/OPNsense/SSOProxyAD/SSOProxyAD.xml

I've this error if I save on my plugin page 
```
An API exception occured
UpdateCron not an attribute of general
```

**Comment by AdSchellevis** [comment]
which is true  :) UpdateCron is not placed inside the general tag, which isn't a problem if you don't try to update general.UpdateCron

**Comment by gitdevmod** [comment]
Ok, I moved UpdateCron to genral tag no more error with save button in plugin page but still no cron for updateDomain in /ui/cron/ or /var/cron/tabs/nobody

**Comment by gitdevmod** [comment]
Hi @AdSchellevis, I still have not found a solution about this, any idea? Thanks

**Comment by fraenki** [comment]
@gitdevmod: FWIW, I've added cron functionality to our new `security/acme-client` plugin just recently. It worked flawlessly. You may take a look at https://github.com/fraenki/plugins/blob/le_fixes/security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/Api/SettingsController.php#L49-L115 for another example.
