### ISSUE TITLE
Can you fix it plugins stunnel ? It causes OPNSENSE to shut down the machine. 

### ISSUE THREAD

**Issue by newtoptan** [opnsense/plugins#3401]
System Information:
User-Agent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
FreeBSD 13.1-RELEASE-p7 stable/23.1-n250430-7eb6eb035df SMP amd64
OPNsense 23.1.6 982c0e24c
Plugins os-acme-client-3.16 os-bind-1.26_4 os-c-icap-1.7_3 os-clamav-1.8 os-crowdsec-1.0.4 os-ddclient-1.12 os-dnscrypt-proxy-1.13 os-etpro-telemetry-1.6_1 os-grid_example-1.0_1 os-haproxy-4.1 os-igmp-proxy-1.5_2 os-intrusion-detection-content-et-open-1.0.1 os-intrusion-detection-content-pt-open-1.0_1 os-intrusion-detection-content-snort-vrt-1.1_1 os-maltrail-1.10 os-net-snmp-1.5_2 os-netdata-1.2_1 os-ntopng-1.2_2 os-qemu-guest-agent-1.2 os-redis-1.1_2 os-rspamd-1.12_1 os-shadowsocks-1.0_2 os-sslh-1.0 os-theme-cicada-1.34 os-web-proxy-sso-2.2_2 os-zerotier-1.3.2_4
Time Sat, 22 Apr 2023 04:02:11 +0700
OpenSSL 1.1.1t  7 Feb 2023
Python 3.9.16
PHP 8.1.18

PHP Errors:
[22-Apr-2023 03:53:45 Asia/Bangkok] Error: Call to undefined function openssl_crl_new() in /usr/local/etc/inc/plugins.inc.d/stunnel.inc:97
Stack trace:
#0 /usr/local/etc/inc/plugins.inc(304): stunnel_refresh_crls(false)
#1 /usr/local/opnsense/scripts/stunnel/generate_certs.php(90): plugins_configure('crl')
#2 {main}
[22-Apr-2023 03:53:48 Asia/Bangkok] Error: Call to undefined function openssl_crl_new() in /usr/local/etc/inc/plugins.inc.d/stunnel.inc:97
Stack trace:
#0 /usr/local/etc/inc/plugins.inc(304): stunnel_refresh_crls(false)
#1 /usr/local/opnsense/scripts/stunnel/generate_certs.php(90): plugins_configure('crl')
#2 {main}

dmesg.boot:
Copyright (c) 1992-2021 The FreeBSD Project.
Copyright (c) 1979, 1980, 1983, 1986, 1988, 1989, 1991, 1992, 1993, 1994
	The Regents of the University of California. All rights reserved.
FreeBSD is a registered trademark of The FreeBSD Foundation.
FreeBSD 13.1-RELEASE-p7 stable/23.1-n250430-7eb6eb035df SMP amd64
FreeBSD clang version 13.0.0 (git@github.com:llvm/llvm-project.git llvmorg-13.0.0-0-gd7b669b3a303)
VT(efifb): resolution 1280x800
CPU: Common KVM processor (2494.27-MHz K8-class CPU)
  Origin="GenuineIntel"  Id=0xf61  Family=0xf  Model=0x6  Stepping=1
  Features=0x1783fbff
  Features2=0x80202001
  AMD Features=0x20100800
  AMD Features2=0x1
Hypervisor: Origin = "KVMKVMKVM"
real memory  = 8589934592 (8192 MB)
avail memory = 8203476992 (7823 MB)
Event timer "LAPIC" quality 100
ACPI APIC Table: 
FreeBSD/SMP: Multiprocessor System Detected: 4 CPUs
FreeBSD/SMP: 1 package(s) x 4 core(s)
random: unblocking device.
ioapic0  irqs 0-23
Launching APs: 1 2 3
random: entropy device external interface
wlan: mac acl policy registered
kbd1 at kbdmux0
WARNING: Device "spkr" is Giant locked and may be deleted before FreeBSD 14.0.
kvmclock0: 
Timecounter "kvmclock" frequency 1000000000 Hz quality 975
kvmclock0: registered as a time-of-day clock, resolution 0.000001s
efirtc0: 
efirtc0: registered as a time-of-day clock, resolution 1.000000s
smbios0:  at iomem 0x7e9d4000-0x7e9d401e
smbios0: Version: 2.8, BCD Revision: 2.8
aesni0: No AES or SHA support.
acpi0: 
acpi0: Power Button (fixed)
cpu0:  on acpi0
atrtc0:  port 0x70-0x77 irq 8 on acpi0
atrtc0: registered as a time-of-day clock, resolution 1.000000s
Event timer "RTC" frequency 32768 Hz quality 0
hpet0:  iomem 0xfed00000-0xfed003ff on acpi0
Timecounter "HPET" frequency 100000000 Hz quality 950
Timecounter "ACPI-fast" frequency 3579545 Hz quality 900
acpi_timer0: <24-bit timer at 3.579545MHz> port 0x608-0x60b on acpi0
pcib0:  port 0xcf8-0xcff on acpi0
pci0:  on pcib0
vgapci0:  mem 0xc0000000-0xc0ffffff,0xc224b000-0xc224bfff at device 1.0 on pci0
vgapci0: Boot video device
uhci0:  port 0xd300-0xd31f irq 16 at device 26.0 on pci0
usbus0 on uhci0
usbus0: 12Mbps Full Speed USB v1.0
uhci1:  port 0xd2e0-0xd2ff irq 17 at device 26.1 on pci0
usbus1 on uhci1
usbus1: 12Mbps Full Speed USB v1.0
uhci2:  port 0xd2c0-0xd2df irq 18 at device 26.2 on pci0
usbus2 on uhci2
usbus2: 12Mbps Full Speed USB v1.0
ehci0:  mem 0xc224a000-0xc224afff irq 19 at device 26.7 on pci0
usbus3: EHCI version 1.0
usbus3 on ehci0
usbus3: 480Mbps High Speed USB v2.0
hdac0:  mem 0xc2240000-0xc2243fff irq 16 at device 27.0 on pci0
pcib1:  mem 0xc2249000-0xc2249fff irq 16 at device 28.0 on pci0
pcib1: failed to allocate initial I/O port window: 0xd000-0xdfff
pci1:  on pcib1
pcib2:  mem 0xc2248000-0xc2248fff irq 16 at device 28.1 on pci0
pci2:  on pcib2
pcib3:  mem 0xc2247000-0xc2247fff irq 16 at device 28.2 on pci0
pci3:  on pcib3
pcib4:  mem 0xc2246000-0xc2246fff irq 16 at device 28.3 on pci0
pci4:  on pcib4
uhci3:  port 0xd2a0-0xd2bf irq 16 at device 29.0 on pci0
usbus4 on uhci3
usbus4: 12Mbps Full Speed USB v1.0
uhci4:  port 0xd280-0xd29f irq 17 at device 29.1 on pci0
usbus5 on uhci4
usbus5: 12Mbps Full Speed USB v1.0
uhci5:  port 0xd260-0xd27f irq 18 at device 29.2 on pci0
usbus6 on uhci5
usbus6: 12Mbps Full Speed USB v1.0
ehci1:  mem 0xc2245000-0xc2245fff irq 19 at device 29.7 on pci0
usbus7: EHCI version 1.0
usbus7 on ehci1
usbus7: 480Mbps High Speed USB v2.0
pcib5:  at device 30.0 on pci0
pci5:  on pcib5
pcib6:  mem 0xc1800000-0xc18000ff irq 21 at device 1.0 on pci5
pci6:  on pcib6
virtio_pci0:  port 0x90c0-0x90ff mem 0x80000c000-0x80000ffff irq 20 at device 3.0 on pci6
vtballoon0:  on virtio_pci0
virtio_pci1:  port 0x9080-0x90bf mem 0xc1602000-0xc1602fff,0x800008000-0x80000bfff irq 21 at device 8.0 on pci6
virtio_pci2:  port 0x9000-0x907f mem 0xc1601000-0xc1601fff,0x800004000-0x800007fff irq 23 at device 10.0 on pci6
vtblk0:  on virtio_pci2
vtblk0: 8192MB (16777216 512 byte sectors)
virtio_pci3:  port 0x9100-0x911f mem 0xc1600000-0xc1600fff,0x800000000-0x800003fff irq 23 at device 18.0 on pci6
vtnet0:  on virtio_pci3
vtnet0: Ethernet address: a6:b2:0a:c5:fb:03
vtnet0: netmap queues/slots: TX 1/256, RX 1/512
000.000152 [ 450] vtnet_netmap_attach       vtnet attached txq=1, txd=256 rxq=1, rxd=512
pcib7:  mem 0xc1801000-0xc18010ff irq 22 at device 2.0 on pci5
pci7:  on pcib7
pcib8:  mem 0xc1802000-0xc18020ff irq 23 at device 3.0 on pci5
pci8:  on pcib8
pcib9:  mem 0xc1803000-0xc18030ff irq 20 at device 4.0 on pci5
pci9:  on pcib9
isab0:  at device 31.0 on pci0
isa0:  on isab0
ahci0:  port 0xd240-0xd25f mem 0xc2244000-0xc2244fff irq 16 at device 31.2 on pci0
ahci0: AHCI v1.00 with 6 1.5Gbps ports, Port Multiplier not supported
ahcich0:  at channel 0 on ahci0
ahcich1:  at channel 1 on ahci0
ahcich2:  at channel 2 on ahci0
ahcich3:  at channel 3 on ahci0
ahcich4:  at channel 4 on ahci0
ahcich5:  at channel 5 on ahci0
acpi_syscontainer0:  on acpi0
vmgenc0:  on acpi0
acpi_syscontainer1:  port 0xb2-0xb3 on acpi0
acpi_syscontainer2:  port 0xcd8-0xce3 on acpi0
acpi_syscontainer3:  port 0x620-0x62f on acpi0
acpi_syscontainer4:  port 0xcc0-0xcd7 on acpi0
atkbdc0:  port 0x60,0x64 irq 1 on acpi0
atkbd0:  irq 1 on atkbdc0
kbd0 at atkbd0
atkbd0: [GIANT-LOCKED]
psm0:  irq 12 on atkbdc0
psm0: [GIANT-LOCKED]
WARNING: Device "psm" is Giant locked and may be deleted before FreeBSD 14.0.
psm0: model IntelliMouse Explorer, device ID 4
attimer0:  at port 0x40 on isa0
Timecounter "i8254" frequency 1193182 Hz quality 0
Event timer "i8254" frequency 1193182 Hz quality 100
Timecounters tick every 10.000 msec
ZFS filesystem version: 5
ZFS storage pool version: features support (5000)
ugen5.1:  at usbus5
ugen1.1:  at usbus1
ugen7.1:  at usbus7
ugen2.1:  at usbus2
uhub0 on usbus5
uhub0:  on usbus5
uhub1 on usbus7
uhub1:  on usbus7
uhub2 on usbus2
uhub2:  on usbus2
ugen6.1:  at usbus6
ugen0.1:  at usbus0
uhub3 on usbus1
uhub3:  on usbus1
uhub4 on usbus0
uhub4:  on usbus0
uhub5 on usbus6
uhub5:  on usbus6
ugen3.1:  at usbus3
ugen4.1:  at usbus4
uhub6 on usbus3
uhub6:  on usbus3
uhub7 on usbus4
uhub7:  on usbus4
Trying to mount root from zfs:ZFS/ROOT/default []...
uhub0: 2 ports with 2 removable, self powered
uhub2: 2 ports with 2 removable, self powered
uhub3: 2 ports with 2 removable, self powered
uhub4: 2 ports with 2 removable, self powered
uhub5: 2 ports with 2 removable, self powered
uhub7: 2 ports with 2 removable, self powered
Root mount waiting for: usbus3 usbus7
Root mount waiting for: usbus3 usbus7
uhub1: 6 ports with 6 removable, self powered
uhub6: 6 ports with 6 removable, self powered
ugen7.2:  at usbus7

**Comment by fichtner** [comment]
https://github.com/opnsense/plugins/blob/f920b48a94705cc6577221f293b7796f5f0feaf7/security/stunnel/src/etc/inc/plugins.inc.d/stunnel.inc#L97

**Comment by newtoptan** [comment]
hi

PHP Errors:
[22-Apr-2023 13:44:33 Asia/Bangkok] ParseError: syntax error, unexpected identifier "©" in /usr/local/etc/inc/plugins.inc.d/stunnel.inc:177
Stack trace:
#0 /usr/local/opnsense/scripts/syslog/list_applications.php(35): plugins_syslog()
#1 {main}
[22-Apr-2023 13:45:33 Asia/Bangkok] ParseError: syntax error, unexpected identifier "©" in /usr/local/etc/inc/plugins.inc.d/stunnel.inc:177
Stack trace:
#0 /usr/local/sbin/pluginctl(153): plugins_interfaces()
#1 {main}
[22-Apr-2023 13:45:34 Asia/Bangkok] ParseError: syntax error, unexpected identifier "©" in /usr/local/etc/inc/plugins.inc.d/stunnel.inc:177
Stack trace:
#0 /usr/local/etc/inc/console.inc(59): plugins_devices()
#1 /usr/local/etc/rc.bootup(74): is_interface_mismatch()
#2 {main}
[22-Apr-2023 13:45:35 Asia/Bangkok] ParseError: syntax error, unexpected identifier "©" in /usr/local/etc/inc/plugins.inc.d/stunnel.inc:177
Stack trace:
#0 /usr/local/opnsense/scripts/syslog/list_applications.php(35): plugins_syslog()
#1 {main}
[22-Apr-2023 13:45:55 Asia/Bangkok] ParseError: syntax error, unexpected identifier "©" in /usr/local/etc/inc/plugins.inc.d/stunnel.inc:177
Stack trace:
#0 /usr/local/opnsense/scripts/stunnel/generate_certs.php(90): plugins_configure('crl')
#1 {main}
[22-Apr-2023 13:45:55 Asia/Bangkok] ParseError: syntax error, unexpected identifier "©" in /usr/local/etc/inc/plugins.inc.d/stunnel.inc:177
Stack trace:
#0 /usr/local/etc/inc/system.inc(690): plugins_configure('monitor', true)
#1 /usr/local/etc/rc.routing_configure(46): system_routing_configure(true)
#2 {main}
[22-Apr-2023 13:45:57 Asia/Bangkok] ParseError: syntax error, unexpected identifier "©" in /usr/local/etc/inc/plugins.inc.d/stunnel.inc:177
Stack trace:
#0 /usr/local/opnsense/scripts/stunnel/generate_certs.php(90): plugins_configure('crl')
#1 {main}
[22-Apr-2023 13:46:54 Asia/Bangkok] ParseError: syntax error, unexpected identifier "©" in /usr/local/etc/inc/plugins.inc.d/stunnel.inc:177
Stack trace:
#0 /usr/local/etc/inc/util.inc(110): plugins_services()
#1 /usr/local/etc/inc/util.inc(192): service_by_name('syslog-ng', Array)
#2 /usr/local/etc/inc/util.inc(274): service_control_get('syslog-ng', Array)
#3 /usr/local/sbin/pluginctl(135): service_control_restart('syslog-ng', Array)
#4 {main}
[22-Apr-2023 13:46:55 Asia/Bangkok] ParseError: syntax error, unexpected identifier "©" in /usr/local/etc/inc/plugins.inc.d/stunnel.inc:177
Stack trace:
#0 /usr/local/opnsense/scripts/syslog/list_applications.php(35): plugins_syslog()
#1 {main}
[22-Apr-2023 13:46:57 Asia/Bangkok] ParseError: syntax error, unexpected identifier "©" in /usr/local/etc/inc/plugins.inc.d/stunnel.inc:177
Stack trace:
#0 /usr/local/etc/inc/util.inc(110): plugins_services()
#1 /usr/local/etc/inc/util.inc(192): service_by_name('cron', Array)
#2 /usr/local/etc/inc/util.inc(274): service_control_get('cron', Array)
#3 /usr/local/sbin/pluginctl(135): service_control_restart('cron', Array)
#4 {main}
[22-Apr-2023 13:46:58 Asia/Bangkok] ParseError: syntax error, unexpected identifier "©" in /usr/local/etc/inc/plugins.inc.d/stunnel.inc:177
Stack trace:
#0 /usr/local/etc/inc/util.inc(110): plugins_services()
#1 /usr/local/etc/inc/util.inc(192): service_by_name('sysctl', Array)
#2 /usr/local/etc/inc/util.inc(274): service_control_get('sysctl', Array)
#3 /usr/local/sbin/pluginctl(135): service_control_restart('sysctl', Array)
#4 {main}
[22-Apr-2023 13:47:59 Asia/Bangkok] ParseError: syntax error, unexpected identifier "©" in /usr/local/etc/inc/plugins.inc.d/stunnel.inc:177
Stack trace:
#0 /usr/local/etc/inc/legacy_bindings.inc(172): plugins_run('return_gateways...')
#1 /usr/local/opnsense/scripts/OPNsense/Monit/gateway_alert(52): return_gateways_status()
#2 {main}
dmesg.boot:
Copyright (c) 1992-2021 The FreeBSD Project.
Copyright (c) 1979, 1980, 1983, 1986, 1988, 1989, 1991, 1992, 1993, 1994
	The Regents of the University of California. All rights reserved.
FreeBSD is a registered trademark of The FreeBSD Foundation.
FreeBSD 13.1-RELEASE-p7 stable/23.1-n250430-7eb6eb035df SMP amd64
FreeBSD clang version 13.0.0 (git@github.com:llvm/llvm-project.git llvmorg-13.0.0-0-gd7b669b3a303)
VT(efifb): resolution 1280x800
CPU: Common KVM processor (2494.29-MHz K8-class CPU)
  Origin="GenuineIntel"  Id=0xf61  Family=0xf  Model=0x6  Stepping=1
  Features=0x1783fbff
  Features2=0x80202001
  AMD Features=0x20100800
  AMD Features2=0x1
Hypervisor: Origin = "KVMKVMKVM"
real memory  = 8589934592 (8192 MB)
avail memory = 8203476992 (7823 MB)
Event timer "LAPIC" quality 100
ACPI APIC Table: 
FreeBSD/SMP: Multiprocessor System Detected: 4 CPUs
FreeBSD/SMP: 1 package(s) x 4 core(s)
random: unblocking device.
ioapic0  irqs 0-23
Launching APs: 1 2 3
random: entropy device external interface
wlan: mac acl policy registered
kbd1 at kbdmux0
WARNING: Device "spkr" is Giant locked and may be deleted before FreeBSD 14.0.
kvmclock0: 
Timecounter "kvmclock" frequency 1000000000 Hz quality 975
kvmclock0: registered as a time-of-day clock, resolution 0.000001s
efirtc0: 
efirtc0: registered as a time-of-day clock, resolution 1.000000s
smbios0:  at iomem 0x7e9d4000-0x7e9d401e
smbios0: Version: 2.8, BCD Revision: 2.8
aesni0: No AES or SHA support.
acpi0: 
acpi0: Power Button (fixed)
cpu0:  on acpi0
atrtc0:  port 0x70-0x77 irq 8 on acpi0
atrtc0: registered as a time-of-day clock, resolution 1.000000s
Event timer "RTC" frequency 32768 Hz quality 0
hpet0:  iomem 0xfed00000-0xfed003ff on acpi0
Timecounter "HPET" frequency 100000000 Hz quality 950
Timecounter "ACPI-fast" frequency 3579545 Hz quality 900
acpi_timer0: <24-bit timer at 3.579545MHz> port 0x608-0x60b on acpi0
pcib0:  port 0xcf8-0xcff on acpi0
pci0:  on pcib0
vgapci0:  mem 0xc0000000-0xc0ffffff,0xc224b000-0xc224bfff at device 1.0 on pci0
vgapci0: Boot video device
uhci0:  port 0xd300-0xd31f irq 16 at device 26.0 on pci0
usbus0 on uhci0
usbus0: 12Mbps Full Speed USB v1.0
uhci1:  port 0xd2e0-0xd2ff irq 17 at device 26.1 on pci0
usbus1 on uhci1
usbus1: 12Mbps Full Speed USB v1.0
uhci2:  port 0xd2c0-0xd2df irq 18 at device 26.2 on pci0
usbus2 on uhci2
usbus2: 12Mbps Full Speed USB v1.0
ehci0:  mem 0xc224a000-0xc224afff irq 19 at device 26.7 on pci0
usbus3: EHCI version 1.0
usbus3 on ehci0
usbus3: 480Mbps High Speed USB v2.0
hdac0:  mem 0xc2240000-0xc2243fff irq 16 at device 27.0 on pci0
pcib1:  mem 0xc2249000-0xc2249fff irq 16 at device 28.0 on pci0
pcib1: failed to allocate initial I/O port window: 0xd000-0xdfff
pci1:  on pcib1
pcib2:  mem 0xc2248000-0xc2248fff irq 16 at device 28.1 on pci0
pci2:  on pcib2
pcib3:  mem 0xc2247000-0xc2247fff irq 16 at device 28.2 on pci0
pci3:  on pcib3
pcib4:  mem 0xc2246000-0xc2246fff irq 16 at device 28.3 on pci0
pci4:  on pcib4
uhci3:  port 0xd2a0-0xd2bf irq 16 at device 29.0 on pci0
usbus4 on uhci3
usbus4: 12Mbps Full Speed USB v1.0
uhci4:  port 0xd280-0xd29f irq 17 at device 29.1 on pci0
usbus5 on uhci4
usbus5: 12Mbps Full Speed USB v1.0
uhci5:  port 0xd260-0xd27f irq 18 at device 29.2 on pci0
usbus6 on uhci5
usbus6: 12Mbps Full Speed USB v1.0
ehci1:  mem 0xc2245000-0xc2245fff irq 19 at device 29.7 on pci0
usbus7: EHCI version 1.0
usbus7 on ehci1
usbus7: 480Mbps High Speed USB v2.0
pcib5:  at device 30.0 on pci0
pci5:  on pcib5
pcib6:  mem 0xc1800000-0xc18000ff irq 21 at device 1.0 on pci5
pci6:  on pcib6
virtio_pci0:  port 0x90c0-0x90ff mem 0x80000c000-0x80000ffff irq 20 at device 3.0 on pci6
vtballoon0:  on virtio_pci0
virtio_pci1:  port 0x9080-0x90bf mem 0xc1602000-0xc1602fff,0x800008000-0x80000bfff irq 21 at device 8.0 on pci6
virtio_pci2:  port 0x9000-0x907f mem 0xc1601000-0xc1601fff,0x800004000-0x800007fff irq 23 at device 10.0 on pci6
vtblk0:  on virtio_pci2
vtblk0: 8192MB (16777216 512 byte sectors)
virtio_pci3:  port 0x9100-0x911f mem 0xc1600000-0xc1600fff,0x800000000-0x800003fff irq 23 at device 18.0 on pci6
vtnet0:  on virtio_pci3
vtnet0: Ethernet address: a6:b2:0a:c5:fb:03
vtnet0: netmap queues/slots: TX 1/256, RX 1/512
000.000220 [ 450] vtnet_netmap_attach       vtnet attached txq=1, txd=256 rxq=1, rxd=512
pcib7:  mem 0xc1801000-0xc18010ff irq 22 at device 2.0 on pci5
pci7:  on pcib7
pcib8:  mem 0xc1802000-0xc18020ff irq 23 at device 3.0 on pci5
pci8:  on pcib8
pcib9:  mem 0xc1803000-0xc18030ff irq 20 at device 4.0 on pci5
pci9:  on pcib9
isab0:  at device 31.0 on pci0
isa0:  on isab0
ahci0:  port 0xd240-0xd25f mem 0xc2244000-0xc2244fff irq 16 at device 31.2 on pci0
ahci0: AHCI v1.00 with 6 1.5Gbps ports, Port Multiplier not supported
ahcich0:  at channel 0 on ahci0
ahcich1:  at channel 1 on ahci0
ahcich2:  at channel 2 on ahci0
ahcich3:  at channel 3 on ahci0
ahcich4:  at channel 4 on ahci0
ahcich5:  at channel 5 on ahci0
acpi_syscontainer0:  on acpi0
vmgenc0:  on acpi0
acpi_syscontainer1:  port 0xb2-0xb3 on acpi0
acpi_syscontainer2:  port 0xcd8-0xce3 on acpi0
acpi_syscontainer3:  port 0x620-0x62f on acpi0
acpi_syscontainer4:  port 0xcc0-0xcd7 on acpi0
atkbdc0:  port 0x60,0x64 irq 1 on acpi0
atkbd0:  irq 1 on atkbdc0
kbd0 at atkbd0
atkbd0: [GIANT-LOCKED]
psm0:  irq 12 on atkbdc0
psm0: [GIANT-LOCKED]
WARNING: Device "psm" is Giant locked and may be deleted before FreeBSD 14.0.
psm0: model IntelliMouse Explorer, device ID 4
attimer0:  at port 0x40 on isa0
Timecounter "i8254" frequency 1193182 Hz quality 0
Event timer "i8254" frequency 1193182 Hz quality 100
Timecounters tick every 10.000 msec
ZFS filesystem version: 5
ZFS storage pool version: features support (5000)
ugen2.1:  at usbus2
ugen3.1:  at usbus3
ugen7.1:  at usbus7
ugen6.1:  at usbus6
uhub0 on usbus2
uhub0:  on usbus2
ugen0.1:  at usbus0
uhub1 on usbus7
uhub1:  on usbus7
uhub2 on usbus6
uhub2:  on usbus6
ugen4.1:  at usbus4
ugen5.1:  at usbus5
uhub3 on usbus3
uhub3:  on usbus3
uhub4 on usbus0
uhub4:  on usbus0
ugen1.1:  at usbus1
uhub5 on usbus1
uhub5:  on usbus1
uhub6 on usbus4
uhub6:  on usbus4
uhub7 on usbus5
uhub7:  on usbus5
Trying to mount root from zfs:ZFS/ROOT/default []...
uhub0: 2 ports with 2 removable, self powered
uhub2: 2 ports with 2 removable, self powered
uhub4: 2 ports with 2 removable, self powered
uhub5: 2 ports with 2 removable, self powered
uhub6: 2 ports with 2 removable, self powered
uhub7: 2 ports with 2 removable, self powered
Root mount waiting for: usbus3 usbus7
Root mount waiting for: usbus3 usbus7
uhub1: 6 ports with 6 removable, self powered
uhub3: 6 ports with 6 removable, self powered
ugen7.2:  at usbus7
