### ISSUE TITLE
I fixed but still encountered problems. plugins stunnel

### ISSUE THREAD

**Issue by newtoptan** [opnsense/plugins#3404]
I have been fixed according to the URL specified.
But still encountered a problem
https://github.com/opnsense/plugins/issues/3401#issuecomment-1518516819

System Information:
User-Agent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
FreeBSD 13.1-RELEASE-p7 stable/23.1-n250430-7eb6eb035df SMP amd64
OPNsense 23.1.6 982c0e24c
Plugins os-acme-client-3.16 os-bind-1.26_4 os-c-icap-1.7_3 os-clamav-1.8 os-crowdsec-1.0.4 os-ddclient-1.12 os-dnscrypt-proxy-1.13 os-etpro-telemetry-1.6_1 os-grid_example-1.0_1 os-haproxy-4.1 os-igmp-proxy-1.5_2 os-intrusion-detection-content-et-open-1.0.1 os-intrusion-detection-content-pt-open-1.0_1 os-intrusion-detection-content-snort-vrt-1.1_1 os-maltrail-1.10 os-net-snmp-1.5_2 os-netdata-1.2_1 os-ntopng-1.2_2 os-qemu-guest-agent-1.2 os-redis-1.1_2 os-rspamd-1.12_1 os-shadowsocks-1.0_2 os-sslh-1.0 os-stunnel-1.0.5_1 os-theme-cicada-1.34 os-web-proxy-sso-2.2_2 os-zerotier-1.3.2_4
Time Sat, 22 Apr 2023 22:53:43 +0700
OpenSSL 1.1.1t  7 Feb 2023
Python 3.9.16
PHP 8.1.18
PHP Errors:
[22-Apr-2023 22:33:46 Asia/Bangkok] ParseError: syntax error, unexpected integer "2023" in /usr/local/etc/inc/plugins.inc.d/stunnel.inc:177
Stack trace:
#0 /usr/local/etc/inc/legacy_bindings.inc(172): plugins_run('return_gateways...')
#1 /usr/local/opnsense/scripts/routes/gateway_status.php(36): return_gateways_status()
#2 {main}

Stack trace:
#0 /usr/local/etc/inc/legacy_bindings.inc(172): plugins_run('return_gateways...')
#1 /usr/local/opnsense/scripts/routes/gateway_status.php(36): return_gateways_status()
#2 {main}
[22-Apr-2023 22:53:16 Asia/Bangkok] ParseError: syntax error, unexpected integer "2023" in /usr/local/etc/inc/plugins.inc.d/stunnel.inc:177
Stack trace:
#0 /usr/local/sbin/pluginctl(105): plugins_services()
#1 {main}
[22-Apr-2023 22:53:34 Asia/Bangkok] ParseError: syntax error, unexpected integer "2023" in /usr/local/etc/inc/plugins.inc.d/stunnel.inc:177
Stack trace:
#0 /usr/local/etc/inc/legacy_bindings.inc(172): plugins_run('return_gateways...')
#1 /usr/local/opnsense/scripts/OPNsense/Monit/gateway_alert(52): return_gateways_status()
#2 {main}
[22-Apr-2023 22:53:41 Asia/Bangkok] ParseError: syntax error, unexpected integer "2023" in /usr/local/etc/inc/plugins.inc.d/stunnel.inc:177
Stack trace:
#0 /usr/local/etc/inc/legacy_bindings.inc(172): plugins_run('return_gateways...')
#1 /usr/local/opnsense/scripts/routes/gateway_status.php(36): return_gateways_status()
#2 {main}
[22-Apr-2023 22:53:41 Asia/Bangkok] ParseError: syntax error, unexpected integer "2023" in /usr/local/etc/inc/plugins.inc.d/stunnel.inc:177
Stack trace:
#0 /usr/local/sbin/pluginctl(105): plugins_services()
#1 {main}
dmesg.boot:
Copyright (c) 1992-2021 The FreeBSD Project.
Copyright (c) 1979, 1980, 1983, 1986, 1988, 1989, 1991, 1992, 1993, 1994
	The Regents of the University of California. All rights reserved.
FreeBSD is a registered trademark of The FreeBSD Foundation.
FreeBSD 13.1-RELEASE-p7 stable/23.1-n250430-7eb6eb035df SMP amd64
FreeBSD clang version 13.0.0 (git@github.com:llvm/llvm-project.git llvmorg-13.0.0-0-gd7b669b3a303)
VT(efifb): resolution 1280x800
CPU: Intel(R) Core(TM) i3-4100M CPU @ 2.50GHz (2494.30-MHz K8-class CPU)
  Origin="GenuineIntel"  Id=0x306c3  Family=0x6  Model=0x3c  Stepping=3
  Features=0x1f83fbff
  Features2=0xfffab223
  AMD Features=0x2c100800
  AMD Features2=0x21
  Structured Extended Features=0x7ab
  Structured Extended Features2=0x4
  Structured Extended Features3=0x20000000
  XSAVE Features=0x1
  IA32_ARCH_CAPS=0x48
  VT-x: PAT,HLT,MTF,PAUSE,EPT,UG,VPID
Hypervisor: Origin = "KVMKVMKVM"
real memory  = 8589934592 (8192 MB)
avail memory = 8203464704 (7823 MB)
Event timer "LAPIC" quality 600
ACPI APIC Table: 
FreeBSD/SMP: Multiprocessor System Detected: 4 CPUs
FreeBSD/SMP: 1 package(s) x 4 core(s)
random: registering fast source Intel Secure Key RNG
random: fast provider: "Intel Secure Key RNG"
random: unblocking device.
ioapic0  irqs 0-23
Launching APs: 3 1 2
random: entropy device external interface
wlan: mac acl policy registered
kbd1 at kbdmux0
WARNING: Device "spkr" is Giant locked and may be deleted before FreeBSD 14.0.
kvmclock0: 
Timecounter "kvmclock" frequency 1000000000 Hz quality 975
kvmclock0: registered as a time-of-day clock, resolution 0.000001s
efirtc0: 
efirtc0: registered as a time-of-day clock, resolution 1.000000s
smbios0:  at iomem 0x7e7d4000-0x7e7d401e
smbios0: Version: 2.8, BCD Revision: 2.8
aesni0: 
acpi0: 
acpi0: Power Button (fixed)
cpu0:  numa-domain 0 on acpi0
atrtc0:  port 0x70-0x77 irq 8 on acpi0
atrtc0: registered as a time-of-day clock, resolution 1.000000s
Event timer "RTC" frequency 32768 Hz quality 0
hpet0:  iomem 0xfed00000-0xfed003ff on acpi0
Timecounter "HPET" frequency 100000000 Hz quality 950
Timecounter "ACPI-fast" frequency 3579545 Hz quality 900
acpi_timer0: <24-bit timer at 3.579545MHz> port 0x608-0x60b on acpi0
pcib0:  port 0xcf8-0xcff on acpi0
pci0:  on pcib0
vgapci0:  mem 0xc0000000-0xc0ffffff,0xc224b000-0xc224bfff at device 1.0 on pci0
vgapci0: Boot video device
uhci0:  port 0xd300-0xd31f irq 16 at device 26.0 on pci0
usbus0 on uhci0
usbus0: 12Mbps Full Speed USB v1.0
uhci1:  port 0xd2e0-0xd2ff irq 17 at device 26.1 on pci0
usbus1 on uhci1
usbus1: 12Mbps Full Speed USB v1.0
uhci2:  port 0xd2c0-0xd2df irq 18 at device 26.2 on pci0
usbus2 on uhci2
usbus2: 12Mbps Full Speed USB v1.0
ehci0:  mem 0xc224a000-0xc224afff irq 19 at device 26.7 on pci0
usbus3: EHCI version 1.0
usbus3 on ehci0
usbus3: 480Mbps High Speed USB v2.0
hdac0:  mem 0xc2240000-0xc2243fff irq 16 at device 27.0 on pci0
pcib1:  mem 0xc2249000-0xc2249fff irq 16 at device 28.0 on pci0
pcib1: failed to allocate initial I/O port window: 0xd000-0xdfff
pci1:  on pcib1
pcib2:  mem 0xc2248000-0xc2248fff irq 16 at device 28.1 on pci0
pci2:  on pcib2
pcib3:  mem 0xc2247000-0xc2247fff irq 16 at device 28.2 on pci0
pci3:  on pcib3
pcib4:  mem 0xc2246000-0xc2246fff irq 16 at device 28.3 on pci0
pci4:  on pcib4
uhci3:  port 0xd2a0-0xd2bf irq 16 at device 29.0 on pci0
usbus4 on uhci3
usbus4: 12Mbps Full Speed USB v1.0
uhci4:  port 0xd280-0xd29f irq 17 at device 29.1 on pci0
usbus5 on uhci4
usbus5: 12Mbps Full Speed USB v1.0
uhci5:  port 0xd260-0xd27f irq 18 at device 29.2 on pci0
usbus6 on uhci5
usbus6: 12Mbps Full Speed USB v1.0
ehci1:  mem 0xc2245000-0xc2245fff irq 19 at device 29.7 on pci0
usbus7: EHCI version 1.0
usbus7 on ehci1
usbus7: 480Mbps High Speed USB v2.0
pcib5:  at device 30.0 on pci0
pci5:  on pcib5
pcib6:  mem 0xc1800000-0xc18000ff irq 21 at device 1.0 on pci5
pci6:  on pcib6
virtio_pci0:  port 0x90c0-0x90ff mem 0x707000c000-0x707000ffff irq 20 at device 3.0 on pci6
vtballoon0:  on virtio_pci0
virtio_pci1:  port 0x9080-0x90bf mem 0xc1602000-0xc1602fff,0x7070008000-0x707000bfff irq 21 at device 8.0 on pci6
virtio_pci2:  port 0x9000-0x907f mem 0xc1601000-0xc1601fff,0x7070004000-0x7070007fff irq 23 at device 10.0 on pci6
vtblk0:  on virtio_pci2
vtblk0: 8192MB (16777216 512 byte sectors)
virtio_pci3:  port 0x9100-0x911f mem 0xc1600000-0xc1600fff,0x7070000000-0x7070003fff irq 23 at device 18.0 on pci6
vtnet0:  on virtio_pci3
vtnet0: Ethernet address: a6:b2:0a:c5:fb:03
vtnet0: netmap queues/slots: TX 1/256, RX 1/512
000.000407 [ 450] vtnet_netmap_attach       vtnet attached txq=1, txd=256 rxq=1, rxd=512
pcib7:  mem 0xc1801000-0xc18010ff irq 22 at device 2.0 on pci5
pci7:  on pcib7
pcib8:  mem 0xc1802000-0xc18020ff irq 23 at device 3.0 on pci5
pci8:  on pcib8
pcib9:  mem 0xc1803000-0xc18030ff irq 20 at device 4.0 on pci5
pci9:  on pcib9
isab0:  at device 31.0 on pci0
isa0:  on isab0
ahci0:  port 0xd240-0xd25f mem 0xc2244000-0xc2244fff irq 16 at device 31.2 on pci0
ahci0: AHCI v1.00 with 6 1.5Gbps ports, Port Multiplier not supported
ahcich0:  at channel 0 on ahci0
ahcich1:  at channel 1 on ahci0
ahcich2:  at channel 2 on ahci0
ahcich3:  at channel 3 on ahci0
ahcich4:  at channel 4 on ahci0
ahcich5:  at channel 5 on ahci0
acpi_syscontainer0:  on acpi0
vmgenc0:  on acpi0
acpi_syscontainer1:  port 0xb2-0xb3 on acpi0
acpi_syscontainer2:  port 0xcd8-0xce3 on acpi0
acpi_syscontainer3:  port 0x620-0x62f on acpi0
acpi_syscontainer4:  port 0xcc0-0xcd7 on acpi0
atkbdc0:  port 0x60,0x64 irq 1 on acpi0
atkbd0:  irq 1 on atkbdc0
kbd0 at atkbd0
atkbd0: [GIANT-LOCKED]
psm0:  irq 12 on atkbdc0
psm0: [GIANT-LOCKED]
WARNING: Device "psm" is Giant locked and may be deleted before FreeBSD 14.0.
psm0: model IntelliMouse Explorer, device ID 4
attimer0:  at port 0x40 on isa0
Timecounter "i8254" frequency 1193182 Hz quality 0
Event timer "i8254" frequency 1193182 Hz quality 100
Timecounters tick every 10.000 msec
ZFS filesystem version: 5
ZFS storage pool version: features support (5000)
ugen6.1:  at usbus6
ugen7.1:  at usbus7
ugen0.1:  at usbus0
ugen2.1:  at usbus2
uhub0 on usbus6
uhub0:  on usbus6
uhub1 on usbus0
uhub1:  on usbus0
uhub2 on usbus2
uhub2:  on usbus2
ugen3.1:  at usbus3
uhub3 on usbus7
uhub3:  on usbus7
ugen5.1:  at usbus5
uhub4 on usbus3
uhub5 on usbus5
uhub5:  on usbus5
ugen1.1:  at usbus1
ugen4.1:  at usbus4
uhub6 on usbus4
uhub6:  on usbus4
uhub7 on usbus1
uhub7:  on usbus1
Trying to mount root from zfs:ZFS/ROOT/default []...
uhub4:  on usbus3
cd0 at ahcich0 bus 0 scbus0 target 0 lun 0
cd0:  Removable CD-ROM SCSI device
cd0: Serial Number QM00001
cd0: 150.000MB/s transfers (SATA 1.x, UDMA5, ATAPI 12bytes, PIO 8192bytes)
cd0: 0MB (1 0 byte sectors)
uhub0: 2 ports with 2 removable, self powered
uhub2: 2 ports with 2 removable, self powered
uhub1: 2 ports with 2 removable, self powered
uhub5: 2 ports with 2 removable, self powered
uhub7: 2 ports with 2 removable, self powered
uhub6: 2 ports with 2 removable, self powered
Root mount waiting for: usbus3 usbus7
Root mount waiting for: usbus3 usbus7
uhub3: 6 ports with 6 removable, self powered
uhub4: 6 ports with 6 removable, self powered
ugen7.2:  at usbus7

**Comment by AdSchellevis** [comment]
can you please stop spamming our issue tracker?
