### ISSUE TITLE
security/acme-client: Add support for Google Domains DNS API

### ISSUE THREAD

**Issue by nmiller0113** [opnsense/plugins#3408]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [ ] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [ ] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [ ] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
(e.g. I would like an input field in the `/ui/firewall/alias` which would add .... to ....)

Please add the exisiting deployment option from acme.sh that supports the Google Domains using their API
https://github.com/acmesh-official/acme.sh/wiki/dnsapi2#157-use-google-domains-dns-api

To Reproduce

Go to 'Challenge Types'
Click on 'add'
Scroll down to 'search Google Domains in the list of dns services'
See error ---> it is missing

**Comment by fraenki** [comment]
Although the upstream PR https://github.com/acmesh-official/acme.sh/pull/4542 was merged, there is no official release of acme.sh available that provides support for this new DNS API. We'll have to wait until a new release of acme.sh is available.

**Comment by fraenki** [comment]
> I see dns_googledomains.sh in there, so that’s why I was curious.

It was merged to the code repository, yes. But there is [no official release](https://github.com/acmesh-official/acme.sh/releases) with support for Google Domains just yet. We only use official releases. Once there is a new release of acme.sh I will add support for Google Domains.

**Comment by nmiller0113** [comment]
Ahhh, I see what you mean @fraenki! My apologies for the misunderstanding!

**Comment by nmiller0113** [comment]
> Although the upstream PR [acmesh-official/acme.sh#4542](https://github.com/acmesh-official/acme.sh/pull/4542) was merged, there is no official release of acme.sh available that provides support for this new DNS API. We'll have to wait until a new release of acme.sh is available.

@fraenki I believe that the new official release contains the support. Thank you!

**Comment by fichtner** [comment]
Yep, required file was added... https://github.com/opnsense/ports/commit/f5632185f54d3

**Comment by nmiller0113** [comment]
> Yep, required file was added... [opnsense/ports@f5632185f54d3](https://github.com/opnsense/ports/commit/f5632185f54d3)

Thanks for sharing this @fichtner. Forgive my ignorance on this, but do you know the next steps on where this has to go before it is released as an opnsense update?

**Comment by fichtner** [comment]
While acme.sh itself will be 3.0.6 in 23.1.10 I’m unsure about the plugin state. If it’s not selectable now it still needs to be added to the plugin. I don’t see any pending changes in the development version, not sure about open PR here.

**Comment by nmiller0113** [comment]
> While acme.sh itself will be 3.0.6 in 23.1.10 I’m unsure about the plugin state. If it’s not selectable now it still needs to be added to the plugin. I don’t see any pending changes in the development version, not sure about open PR here.

Thanks @fichtner. Perhaps @fraenki knows? I'm on 23.1.9 currently and do not see an option for 23.1.10. I'm assuming it's still in beta then?

**Comment by fichtner** [comment]
There is no beta/development code in our repository. Mentioned it before.

**Comment by nmiller0113** [comment]
> There is no beta/development code in our repository. Mentioned it before.

@fichtner, I was referring to updating my opnsense version to 23.1.10, not to the plugin beta/development. I did follow what you were mentioning. Thanks!

**Comment by fichtner** [comment]
Let me clarify: unless something is actively added to the plugin for 23.1.10 you won't be able use the new dns_googledomains addition from acme.sh package itself.

**Comment by fichtner** [comment]
It looks like #3429 might do the trick?

If you are on 23.1.9 with the acme.sh hotfix installed (check for version 3.0.6) you can try and test:

    # opnsense-patch -c plugins e10a96037fa5

But there is a comment here that the PR is not complete: https://github.com/opnsense/plugins/pull/3429#issuecomment-1575655101


Cheers,
Franco

**Comment by nmiller0113** [comment]
> Let me clarify: unless something is actively added to the plugin for 23.1.10 you won't be able use the new dns_googledomains addition from acme.sh package itself.

I understood @fichtner, thank you very much!

**Comment by nmiller0113** [comment]
> It looks like #3429 might do the trick?
> 
> If you are on 23.1.9 with the acme.sh hotfix installed (check for version 3.0.6) you can try and test:
> 
> ```
> # opnsense-patch -c plugins e10a96037fa5
> ```
> 
> But there is a comment here that the PR is not complete: [#3429 (comment)](https://github.com/opnsense/plugins/pull/3429#issuecomment-1575655101)
> 
> Cheers, Franco

@fichtner, is the opnsense-patch command you shared the way to install the hotfix mentioned? Sorry, have not done a hotfix  in opnsense yet. Thanks again!

**Comment by fichtner** [comment]
@nmiller0113 yep, `opnsense-patch` is a builtin. Run it from a root console on the OPNsense. It fetches the patch from GitHub and tries to install it so you don't have to :)

**Comment by nmiller0113** [comment]
> PR #3499 was merged, so this should be available in one of the next OPNsense releases.

Thank you @fraenki, I'm very much looking forward to the next OPNsense release!

**Comment by slackadelic** [comment]
Well glad to see this being added.   Hopefully a full patch will go out at some point before the next release so we can fully utilize this!
