### ISSUE TITLE
Unable to get iperf package running after fresh 23.1(.6) install

### ISSUE THREAD

**Issue by dohlin** [opnsense/plugins#3409]
Had to unfortunately reload my firewall this past week (100% my fault!), but unfortunately after reinstalling and restoring my config backup I get the following error thrown in the 'backend' log file when trying to start iperf:

![image](https://user-images.githubusercontent.com/5067574/234437079-9745e98a-c7e6-4dad-a51f-4ddad63a9101.png)

`[f9554eee-440c-40dd-8c03-f8be60111476] Script action failed with Command '/usr/local/etc/rc.d/iperf status ' returned non-zero exit status 1. at Traceback (most recent call last): File "/usr/local/opnsense/service/modules/processhandler.py", line 482, in execute subprocess.check_call(script_command, env=self.config_environment, shell=True, File "/usr/local/lib/python3.9/subprocess.py", line 373, in check_call raise CalledProcessError(retcode, cmd) subprocess.CalledProcessError: Command '/usr/local/etc/rc.d/iperf status ' returned non-zero exit status 1.`

I've tried uninstalling/re-installing the plugin multiple times, but it seems like no matter what I do this same error always gets thrown.  I've seen this error on some other posts online, but haven't yet found anything to point me in the right direction towards a resolution.  Anyone else seen this before?

**Comment by iqt4** [comment]
Same issue here on 23.1.6 after upgrade.
Others seem to have the problem as well: [IPerf3 on OpnSense - stopped working for me, has it for you?](https://www.reddit.com/r/opnsense/comments/12u10qd/iperf3_on_opnsense_stopped_working_for_me_has_it/)

**Comment by dohlin** [comment]
> Same issue here on 23.1.6 after upgrade. Others seem to have the problem as well: [IPerf3 on OpnSense - stopped working for me, has it for you?](https://www.reddit.com/r/opnsense/comments/12u10qd/iperf3_on_opnsense_stopped_working_for_me_has_it/)

Don't know how I missed that Reddit thread - thank you!  Glad to hear it's at least not just me.  Thanks!!

**Comment by fichtner** [comment]
The two ruby-dependent plugins are iperf and tor. Since 2.7 ruby is EOL and vulnerable we had no other choice but to push 3.1. fixing the scripts here is maintainer territory and also we would encourage porting these scrips to Python 3 instead to free the hard dependency on ruby to avoid similar issues in the future.

**Comment by iqt4** [comment]
Thanks @fichtner for clarifying. Then a `pkg install rubygem-rexml` is only a workaround. Could we address this issue to the maintainer please?

**Comment by fichtner** [comment]
That would be the least favourable way to fix by adding more 😔

CC @fabianfrz

**Comment by fabianfrz** [comment]
@fichtner rexml is part of the standard rollout but not a core library and it looks like freebsd messes around with the package to make it installable as a separate package to keep the ruby package smaller and update it out of band.
https://nts.strzibny.name/ruby-stdlib-default-bundled-gems/

In my opinion, we can just add it back by adding `rubygem-rexml` as a dependency so we have the status of before the upgrade to the newer version of the ruby package.

**Comment by thexperiments** [comment]
Also ran into this, will go with the manual install of the package but it would be great if it can be fixed by adding the dependency.

However might that dependency break for older freebsd where it is still part of the standard rollout and not available as a package? Just a wild guess, don't know if it is a use-case to have latest plugin with older bsd

**Comment by damooooooooooh** [comment]
Same issue here.  Installed the package on fresh install and service won't start.

**Comment by strawberryfly** [comment]
> In my opinion, we can just add it back by adding `rubygem-rexml` as a dependency so we have the status of before the upgrade to the newer version of the ruby package.

Could someone adjust the dependency in the source code?

**Comment by Zerreth** [comment]
https://github.com/opnsense/plugins/pull/3544

**Comment by Hawxxer** [comment]
While the package rubygem-rexml is installed, I still can't create a new Instance. It shows a green playbutton in the top right corner but no instance.

**Comment by em-winterschon** [comment]
iperf is still broken on version 24.7.5_3-amd64. after install the plugin worked one time, and then it does the same thing that is described by previous comments. It shouldn't need ruby in the first place, both iperf and iperf3 are available in the FreeBSD repos with zero dependencies. Replace it, and reduce the attack footprint by removing the deps.
