### ISSUE TITLE
WireGuard Selective Routing to External VPN Endpoint not configurable for IPv6

### ISSUE THREAD

**Issue by hobbes444** [opnsense/plugins#3413]
[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
[x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

Similar (closed) issue found: https://github.com/opnsense/core/issues/5766

#### Bug description:

* Issue observed on: OPNsense 23.1.6
* last OPNsense version where the bug did not exist: unknown.
* When attempting to follow instructions to configure selective routing to external wireguard endpoint, when adding the IPv6 gateway, hitting error "Cannot add IPv6 Gateway Address because no IPv6 address could be found on the interface."

#### Steps to reproduce:
1. follow instructions here: https://docs.opnsense.org/manual/how-tos/wireguard-selective-routing.html
2. At step "[Configuring IPv6](https://docs.opnsense.org/manual/how-tos/wireguard-selective-routing.html#configuring-ipv6)", after step 11, when adding the IPv6 Gateway, it will throw error "Cannot add IPv6 Gateway Address because no IPv6 address could be found on the interface."

I am unclear if it's a bug in the code or a documentation defect and "IPv6 Configuration Type" on the Wireguard interface shouldn't be "None" (as described in [step 4](https://docs.opnsense.org/manual/how-tos/wireguard-selective-routing.html#step-4-assign-an-interface-to-wireguard-and-enable-it)).

#### Expected behavior:

Being able to add the IPV6 gateway for the Wireguard interface.

**Comment by hobbes444** [comment]
@AdSchellevis If it's a documentation issue I would agree it belongs into opnsense/plugin, but as it stands it's an opnsense/core issue: it fails when I try to configure the IPv6 Gateway, which is a core function in my understanding.

I assume that at the time the documentation I refer to above was written it was working as described and something broke since then, which would point to a core issue with IPv6 gateways rather.

**Comment by hobbes444** [comment]
@AdSchellevis I did follow these instructions, I assigned the gateway another IP within the /127 subnet, the issue is happening nonetheless.

**Comment by AdSchellevis** [comment]
My assumption would be that the wireguard interface does not have an address assigned when trying to add the gateway, which would be easy to check with `ifconfig`, unfortunately, for us this lies out of community support, I'll happily move the issue to core when `ifconfig` does show the correct address and the next hop being assigned as gateway can not be added, but that would require this ticket to contain te relevant information.

**Comment by hobbes444** [comment]
You can close this @AdSchellevis:
a/ I am not able to reproduce it anymore.
b/ There was an error in my Wireguard config, I had the wrong IPv6 configured on the intf.
