### ISSUE TITLE
os-bind not listening 53530

### ISSUE THREAD

**Issue by sawjai** [opnsense/plugins#3417]
os-bind version 1.26_4
opnsense version 23.1.7_3-amd64

This is first time installation os-bind. After initial installation, I add some secondary zone and leave other configuration to default. Start os-bind, I did not see bind listening to port 53530.
sockstat shows
bind     named      62190 3  dgram  -> /var/run/logpriv
bind     named      62190 29 tcp4   127.0.0.1:9530        *:*
bind     named      62190 30 tcp4   127.0.0.1:9530        *:*
bind     named      62190 31 tcp4   127.0.0.1:9530        *:*
bind     named      62190 34 tcp4   127.0.0.1:9530        *:*

named.conf has this port defined
        listen-on port 53530 { 0.0.0.0; };
        listen-on-v6 port 53530 { ::; };

The log shows named is up and running
06-May-2023 08:17:38.528 zoneload: info: managed-keys-zone: loaded serial 0
06-May-2023 08:17:38.529 zoneload: info: zone 127.in-addr.arpa/IN: loaded serial 42
06-May-2023 08:17:38.530 zoneload: info: zone 0.ip6.arpa/IN: loaded serial 42
06-May-2023 08:17:38.531 zoneload: info: zone localhost/IN: loaded serial 42
06-May-2023 08:17:38.532 zoneload: info: zone mydomain.org/IN: loaded serial 33708
06-May-2023 08:17:38.533 notify: info: zone mydomain.org/IN: sending notifies (serial 33708)
06-May-2023 08:17:38.533 zoneload: info: zone 168.192.in-addr.arpa/IN: loaded serial 4291
06-May-2023 08:17:38.533 notify: info: zone 168.192.in-addr.arpa/IN: sending notifies (serial 4291)
06-May-2023 08:17:38.533 general: notice: all zones loaded
06-May-2023 08:17:38.534 general: notice: running

Am I missing something?

**Comment by fichtner** [comment]
Thanks, looks like bind needs some help to deal with special cases:

`listen-on(-v6) { any; };` for any address types and `listen-on(-v6) { none; };` if any of the two address family lists is empty.


Cheers,
Franco

**Comment by sawjai** [comment]
If I change the listening ip to any, the bind now has port 53530 listened.

I think we can close this issue.

**Comment by fichtner** [comment]
No, not really. The plugin has two clear defects here.

**Comment by fichtner** [comment]
It looks like there was only one issue since empty listen address is not supported. You can try the patch via:

    # opnsense-patch -c plugins 51d6c76


Cheers,
Franco

**Comment by sawjai** [comment]
Franco,
Patch works.

Thanks
