### ISSUE TITLE
dns/bind + security/acme-client: "OPNSense Bind Plugin" fails with "invalid domain" after Master/Slave -> Primary/Secondary terminology change

### ISSUE THREAD

**Issue by DarkStarSword** [opnsense/plugins#3420]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
The dns_opnsense version of the acme script calls the old searchMasterDomainAction() API, however when this API was changed to searchPrimaryDomainAction the backwards compatibility searchMasterDomainAction() API was broken in multiple ways:

- It attempts to call searchPrimaryDomainAction(), however misspelt "sea**r**ch" as "seach", and forgot the `$this->`
- With the above corrected, the data returned from the API has "type":"Primary", but the script is expecting "type":"master" and as such fails to recognise the entries.

Probably the best fix will be to update the acme.sh to properly use the new API, though it's not great that the backwards compatibility API is broken.

**To Reproduce**
1. Install os-bind and os-acme-client plugins in OPNSense
2. Configure a zone in Bind and make sure it responds to external DNS queries, setting up any port forwarding / firewall rules / ACL / DNS records etc. as necessary
3. Set up ACME plugin account to use Let's Encrypt Test CA
4. Create a "DNS-01" challenge type with DNS Service set to OPNSense Bind Plugin and opnsense API key+token filled out, Disable TLS Verification if necessary
5. Create a certificate using the above account + challenge
6. Attempt to issue that certificate
7. Open ACME logs, see error

**Expected behavior**
Challenge should have been successfully set to _acme-challenge TXT record and certificate issued.

**Screenshots**
![image](https://user-images.githubusercontent.com/379749/236811973-dc04d347-977d-4a95-abc2-b0166e2dcdf0.png)

**Environment**
OPNsense 23.1.7_3-amd64
os-acme-client 3.16
os-bind 1.26_4
acme.sh 3.0.5_1

**Comment by fichtner** [comment]
055e303393 fixes the dns/bind end I hope

**Comment by fraenki** [comment]
> With the above corrected, the data returned from the API has "type":"Primary", but the script is expecting "type":"master" and as such fails to recognise the entries.

I see. This needs to be done in the upstream acme.sh repository:
https://github.com/acmesh-official/acme.sh/blob/master/dnsapi/dns_opnsense.sh

It would be greatly appreciated if someone wants to volunteer and submit a Pull-Request to acmesh-official :blush:

**Comment by fichtner** [comment]
I'll fix the port to cope with the change for now... but upstream PR is good for long-term support.

**Comment by fichtner** [comment]
@DarkStarSword https://github.com/opnsense/ports/commit/c16489db9b1d I can also provide a test package

**Comment by DarkStarSword** [comment]
@fichtner Looks like it's case sensitive - I still got an "invalid domain" error with "primary", changing it to "Primary" fixed it

**Comment by fichtner** [comment]
hmm, why is it reading the label then oO the value itself is defined as lowercase value in the config.xml -- I'm inclined to do this instead... 8f8b2f63db7

**Comment by DarkStarSword** [comment]
Yep, confirmed that changing the xml file works:

![image](https://user-images.githubusercontent.com/379749/236837147-996da804-c71e-4113-8449-6da2d2027ba3.png)

**Comment by fichtner** [comment]
@DarkStarSword thanks, so for 23.1.8 I think we have this settled but I'd like to keep this open until acme.sh has this of @fraenki is ok with it. I can take assignment too.

**Comment by fraenki** [comment]
@fichtner Sure, you can take assignment. Would you submit your patch to acmesh-official too, or should someone else do this?

**Comment by fichtner** [comment]
ok, I'll do it tomorrow

**Comment by DarkStarSword** [comment]
I've written a blog post on my experiences setting up Lets Encrypt on OPNSense today - briefly mentioned this bug (but not making a huge deal of it because you are all so fast at fixing this stuff :)

If you're interested in reading it you can find it here:
http://blog.darkstarsword.net/2023/05/lets-encrypt-on-opnsense-using-local.html

Thanks again :)

**Comment by fichtner** [comment]
Dropped this here https://github.com/acmesh-official/acme.sh/pull/4629 and closing.

@DarkStarSword thanks for the writeup. I understand that the subject is difficult and bugs are annoying. However, I'd like to point out that this was going to be a breaking change induced by BIND 9.16 -> 9.18 transition doing configuration syntax and  file name changes. Naturally this will cause more harm than not for downstream. ;)


Cheers,
Franco

**Comment by fraenki** [comment]
Thanks, @fichtner :+1:

**Comment by fichtner** [comment]
Just FYI: https://github.com/acmesh-official/acme.sh/pull/4629 was merged.
