### ISSUE TITLE
www/nginx Feature: allow enabling underscores_in_headers directive in server block

### ISSUE THREAD

**Issue by hursjohn** [opnsense/plugins#3423]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
I have been troubleshooting an issue with applications I run via this plugin.  The cause of my issue is that HTTP headers containing an underscore are being ignored and not passed upstream.  This is the default behavior of nginx.
I can correct the problem by manually editing the server block:
server {
...
underscores_in_headers on;
...
}

**Describe the solution you'd like**
I would like to see an Nginx > HTTP Server form checkbox that would allow users to enable this directive.  In addition, update the templating to add this server block directive.

**Describe alternatives you've considered**
After some reading, it is taboo to have underscores in your HTTP header.
-  I'm in communication with my app developer to end this practice.
- For now, I will manually configure the server in opnsense_stream_vhost_plugins
- maybe try os-haproxy

**Additional context**
[nginx docs: underscores in headers.
](http://nginx.org/en/docs/http/ngx_http_core_module.html#underscores_in_headers)

**Comment by hursjohn** [comment]
> Thank you for creating an issue. Since the ticket doesn't seem to be using one of our templates, we're marking this issue as low priority until further notice.
> 
> For more information about the policies for this repository, please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.
> 
> The easiest option to gain traction is to close this ticket and open a new one using one of our templates.

I updated using one of your templates.

**Comment by jesulo** [comment]
> > Thank you for creating an issue. Since the ticket doesn't seem to be using one of our templates, we're marking this issue as low priority until further notice.
> > For more information about the policies for this repository, please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.
> > The easiest option to gain traction is to close this ticket and open a new one using one of our templates.
> 
> I updated using one of your templates.

Hi, could you tell me the path of the file you modified and the commands to follow? Cheers.

**Comment by hursjohn** [comment]
I had to edit /usr/local/etc/nginx/nginx.conf
Then in the server bock for the http server you wish to enable this on you add the directive as described in the nginx documentation and my original post.  after making the change restart the nginx service "service nginx restart".  This manual change will be overwritten the next time opensense generates a config file.

**Comment by jesulo** [comment]
> I had to edit /usr/local/etc/nginx/nginx.conf Then in the server bock for the http server you wish to enable this on you add the directive as described in the nginx documentation and my original post. after making the change restart the nginx service "service nginx restart". This manual change will be overwritten the next time opensense generates a config file.

Thanks. Have you found another permanent solution or an option in the GUI? It seems like the developers don’t care about this solution, and it’s strange because many applications use underscores in their headers. Cheers.
