### ISSUE TITLE
www/nginx feature request enabling underscores_in_headers directive in server block

### ISSUE THREAD

**Issue by hursjohn** [opnsense/plugins#3424]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
I have been troubleshooting an issue with applications I run via this plugin.  The cause of my issue is that HTTP headers containing an underscore are being ignored and not passed upstream.  This is the default behavior of nginx.
I can correct the problem by manually editing the server block:
server {
...
underscores_in_headers on;
...
}

**Describe the solution you'd like**
I would like to see an Nginx > HTTP Server form checkbox allowing users to enable this directive.  In addition, update the templating to add this server block directive.

**Describe alternatives you've considered**
After some reading, it is taboo to have underscores in your HTTP header.
-  I'm in communication with my app developer to end this practice.
- For now, I will manually configure the server in opnsense_stream_vhost_plugins
- maybe try os-haproxy

**Additional context**
[nginx docs: underscores in headers.
](http://nginx.org/en/docs/http/ngx_http_core_module.html#underscores_in_headers)

**Comment by jesulo** [comment]
Now have check .. underscores_in_headers?
