### ISSUE TITLE
os-ddclient: opnsense backend and cloudflare sets all domain names as unproxied (DNS only)

### ISSUE THREAD

**Issue by juantxorena** [opnsense/plugins#3426]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X] The title contains the plugin to which this issue belongs

**Describe the bug**
Cloudflare can set DNS entries as "proxied" and "DNS only" (see here: https://developers.cloudflare.com/dns/troubleshooting/faq/#h_86206161161541019836180). I have both types of entries. When trying to update them with the opnsense backend of ddclient, it sets them as "DNS only", no matter the previous status.

There is a parameter in the update query for this (https://developers.cloudflare.com/api/operations/dns-records-for-a-zone-update-dns-record), but there is no way of setting it. I guess a checkbox should be needed in the frontend, and the query should respect it.

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**
1. Have DNS entries in cloudflare set as "proxied"
2. Update them with ddclient with opnsense backend
3. These entries are set to "DNS only"

**Expected behavior**
Their proxied status shouldn't change.

**Environment**
Software version used and hardware type if relevant.

OPNsense 23.1.7 (amd64, OpenSSL).

**Comment by AdSchellevis** [comment]
The original attributes should be left intact (as that is what was configured), which is what https://github.com/opnsense/plugins/commit/ec4d29100ccf3117fb68c341c8749cf1f1ba3b66 aims to offer.
