### ISSUE TITLE
Openconnect username: Allowed characters 2

### ISSUE THREAD

**Issue by markomdinic** [opnsense/plugins#3428]
Hello,

our ocserv serves multiple tenants ("domains"), so the username has format

  domain/username

or

  domain/email@address

It can also include optional modifiers:

   modifier:domain/username

or

  modifier:domain/email@address

for example, to select between split-tunneling and default route, like

 nosplit:office/john.smith

Unfortunately, OPNSense won't let us use this username format, because ':' and '/' are not allowed.

 Can this restriction be relaxed a bit ? Other characters could be required on other non-trivial VPN setups, as well.

**Comment by fichtner** [comment]
@markomdinic I thought @mimugmail would pick this up but I fixed it now. May be too late for you but in the hopes somebody else will find it useful. Thanks for the report!
