### ISSUE TITLE
www/web-proxy-sso: hostname is modified before AD computer creation

### ISSUE THREAD

**Issue by mmorev** [opnsense/plugins#343]
https://github.com/opnsense/plugins/blob/31dd6f6d5104fb7b6673193ec1bf09b2e6238311/www/web-proxy-sso/src/opnsense/mvc/app/controllers/OPNsense/ProxySSO/Api/ServiceController.php#L48
What is the need to modify hostname here? Computer account in AD should be named same as Opnsense hostname by default. Think this could be made in accordance to some internal standards of this file author's company.

**Comment by evbevz** [comment]
This account is registering for kerberos usage only, to avoid conflicts with other account of this computer, for other purposes.

**Comment by mmorev** [comment]
@evbevz Until other opnsense plugins and modules don't create ad accounts, this hostname should correspond to real hostname. Optional user should be noticed about potential conflicts.
Current behavior could be useful in case of plugin for os-independent installable software, which opnsense is not.

**Comment by evbevz** [comment]
Sometimes it is useful (in our environment). This option can be moved to web-interface.

**Comment by evbevz** [comment]
Close this due to #368 ?

**Comment by fichtner** [comment]
Sure. I think you should be able to close?

**Comment by mmorev** [comment]
Thanks a lot!
