### ISSUE TITLE
os-ddclient - does not accept a ClouDNS apikey

### ISSUE THREAD

**Issue by sja1440** [opnsense/plugins#3430]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
Since version 1.13.0, the 'Dynamic DNS' plugin (os-ddclient) has declared support for ClouDNS. 

Updating the ClouDNS api does not use Username and Password. Instead it uses an API key as follows:
https://ipv4.cloudns.net/api/dynamicURL/?q=MYAPIKEY

1. It is not clear from the GUI where to insert the ClouDNS API key

3. Making many attempts at inserting the APIkey and url (parts of the url) into various combinations of the GUI fields:
Username
Password
resourceid (using advanced mode)
Hostname= mydomain.eu
always fails with the same type of log entry (see below)

**To Reproduce**
Using the plugin's GUI I have tried

**Expected behavior**
The ClouDNS account should be accepted by the plugin and update successfully.

**Screenshots**
not applicable

**Relevant log files**
Here is a typical plugin log entry whenever I attempt to add a ClouDNS account (nb I have replaced my domain with the string MYDOMAIN):

2023-05-05T15:07:22 | Notice | ddclient[8125] | 9764 - [meta sequenceId="4"] WARNING:  skipping host: MYDOMAIN.eu: 'dynurl=' is an invalid string.
-- | -- | -- | --

**Additional context**

**Environment**
OPNsense 23.1.7_3-amd64

**Comment by AdSchellevis** [comment]
It was added in https://github.com/opnsense/plugins/pull/3190 , I don't see any special treatment in the configuration file, maybe best check what `ddclient` expects first.

**Comment by sja1440** [comment]
I have monitored the contents of /usr/local/etc/ddclient.conf whilst attempting to register a ClouDNS account using the plugin's GUI.

No matter how I complete the plugin's GUI I see no "dynurl" field within the ddclient.conf.

An example of how it should be filled in is given in the /usr/local/etc/ddclient.conf.sample. This is what it says:
##
## ClouDNS (https://www.cloudns.net)
##
# protocol=cloudns, \
# dynurl=https://ipv4.cloudns.net/api/dynamicURL/?q=Njc1OTE2OjY3Njk0NDM6YTk2, \
# myhost.example.com

I therefore suspect that there is a bug in the GUI rather than the external ddclient script.

**Comment by AdSchellevis** [comment]
Let's tag this help wanted, shouldn't be very difficult to add.
