### ISSUE TITLE
FRR adds Fw filter rules generaly for OSPF

### ISSUE THREAD

**Issue by rudiservo** [opnsense/plugins#3431]
*Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X] The title contains the plugin to which this issue belongs

**Describe the bug**
FRR adds FW rules in general instead of the interface it is supposed to broadcast in, I do not know the impact of general rule in the overall performance of the FW

This is on the net/frr/src/etc/inc/plugins.inc.d/frr.inc

The following code does not have an interface, 

```
    if ((string)$ospf->enabled == '1') {
        foreach ($ospf->networks->network->iterateItems() as $network) {
            if ((string)$network->enabled == '1') {
                $fw->registerFilterRule(
                    1, /* priority */
                    array(
                        'ipprotocol'     => 'inet',
                        'protocol'       => 'ospf',
                        'statetype'      => 'keep',
                        'label'          => 'Pass OSPF (autogenerated)',
                        'from'           => $network->ipaddr . '/' . $network->netmask,
                        'to'             => '224.0.0.0/24',
                        'direction'      => 'in',
                        'type'           => 'pass',
                        'disablereplyto' => 1,
                        'quick'          => true
                    ),
                    null
                );
```

My suggestion would be to add the interface by using a for loop for the interfaces

```
 foreach ($ospf->interfaces->interface->iterateItems() as $interface) {
  foreach ($ospf->networks->network->iterateItems() as $network) {
            if ((string)$network->enabled == '1') {
                $fw->registerFilterRule(
                    1, /* priority */
                    array(
                        'ipprotocol'     => 'inet',
                        'interface'      => $interface->interfacename,
```

**To Reproduce**
1. enable FRR with OSPF

**Expected behavior**
Only have rules for the Interface it is configured on

**Screenshots**
None

**Relevant log files**
None

**Additional context**

I could be wrong about this and it could be nonsense, can I get some feedback if this is working properly has expected or the change I suggested is viable? Maybe it's needs to check passive interfaces?

**Environment**

OPNsense 23.1.7_3-amd64

**Comment by AdSchellevis** [comment]
We decided to make the rules optional so people with more advanced setups can create their own manually. ref https://github.com/opnsense/plugins/pull/3531#issuecomment-1670053571

**Comment by rudiservo** [comment]
@AdSchellevis nice, thanks, anyway, I do have a PR request with said changes, it is still valid for auto added rules. #3432
Can we still use it, do you want me to change anything on it?

**Comment by fichtner** [comment]
But despite being optional they are opt-out, not opt-in. I just wanted to make this clear from the code point of view.

**Comment by rudiservo** [comment]
@fichtner I assumed it would be opt-out, opt-in would break a lot of setups, again check my PR please.

**Comment by fichtner** [comment]
I have. I wanted to clarify "We decided to make the rules optional".

**Comment by AdSchellevis** [comment]
let's close https://github.com/opnsense/plugins/pull/3432 as we do not plan to add more logic to the rules. Our strategy for new components if they do offer a way to auto register rules is to keep it simple only, for more security you have to define manual rules which offers all control in the world.

**Comment by rudiservo** [comment]
@AdSchellevis hope you don't mind me bumping into this, your solution of having the option to disable automatic rules is great, although I would not mind having my suggestion has a 3rd option of try and automatically create targeted and specific rules has "alpha" or "beta".

I do not mind creating it or maintaining it if it comes to that, if you would like that I can change my PR or create a new one.

**Comment by AdSchellevis** [comment]
@rudiservo we've discussed this internally some time ago, but prefer to only allow a limited set of automated rules which are easy to generate and maintain. The documentation might be a better place to explain to people how to tighten their security.

**Comment by rudiservo** [comment]
Fair enough, maybe in the future then. Thanks.
