### ISSUE TITLE
net/sslh: Transparent Proxy

### ISSUE THREAD

**Issue by thn80** [opnsense/plugins#3436]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
The commit [#2729](https://github.com/opnsense/plugins/pull/2729/commits/d882e31712c4edb99d2e5f3a08ee60f1918be76a) states "Remove transparent functionality: Documentation reports this as a 'Linux only' feature, remove since there is no provision for using this on FreeBSD.". I think this is not the case (anymore).

**Describe the solution you'd like**
The documentation of sslh states for the Transparent Proxy "On Linux **and FreeBSD** you can use the --transparent option to request transparent proxying." (Source: [https://github.com/yrutschle/sslh/blob/master/doc/tproxy.md](https://github.com/yrutschle/sslh/blob/master/doc/tproxy.md)). So, please add the option for Transparent Proxy again to the plugin.

**Describe alternatives you've considered**

**Additional context**

**Comment by AdSchellevis** [comment]
well, this https://github.com/yrutschle/sslh/issues/118 doesn't look hopeful and it seems only to support `ipfw`, which probably doesn't combine well with other features of the firewall.

**Comment by thn80** [comment]
> it seems only to support `ipfw`, which probably doesn't combine well with other features of the firewall.

I'm not sure if I get the point correctly. For me it looks like that in [yrutschle/ssl#118](https://github.com/yrutschle/sslh/issues/118) the onyl issue is the returning of the packets from the destination servers to sslh instead of directly passing them to the originator. Why is this not possible with OPNsense firewall rules?
(_I apologize for any stupid question._)
