### ISSUE TITLE
radsecproxy reported as not running by opnsense but really running

### ISSUE THREAD

**Issue by aureb** [opnsense/plugins#3437]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
I have configured radsec proxy, Everything is working as expected, except that opnsense report it as not running (and it is generating false alarm in my monitoring service)

**To Reproduce**
1.  Configure radsec proxy
2.  Start it
3.  Go to System >> services
4.  Find radsec (it is shown as not running)
5.  In terminal a ps -ax | grep radsec show is running

**Expected behavior**
Opnsense should report radsecproxy running, if it is really running

**Screenshots**
![svc](https://github.com/opnsense/plugins/assets/6369347/7f0aa13e-0419-4b90-8ca6-2438ebba5ff8)
![ps](https://github.com/opnsense/plugins/assets/6369347/688b146f-a3d9-47c2-a664-26bbed27d871)

**Relevant log files**

**Additional context**

**Environment**
OPNsense 23.1.7_2-amd64
FreeBSD 13.1-RELEASE-p7
OpenSSL 1.1.1t 7 Feb 2023
Kvm

Thanks in advanced

**Comment by fichtner** [comment]
# opnsense-patch -c plugins 08144ed

Thanks for the report!

**Comment by aureb** [comment]
Great!
Thank you very much!
