### ISSUE TITLE
Update zabbix-proxy and zabbix-agent plugins to version 6.4

### ISSUE THREAD

**Issue by ThomasBahn** [opnsense/plugins#3439]
As far as I remember I saw - after installing the zabbix-proxy-62 plugin - a message, announcing the end of service date of the port (I assume, this means the BSD port of the Zabbix proxy) is 2023-05-31 and the package would be removed after then. (I can't find the installation logs, thus I cannot verify this).

Nonetheless: An update of both plugins to version 6.4 would be nice.
Since the proxy must be on the same version as the server, I cannot update the latter, because there is no zabbix-proxy-64 plugin.

It seams, this update would only consist on some new lines in the file net-mgmt/zabbix-(proxy|agent)/pkg-descr
But I don't know, how to do this on Github and how to get this to my OPNsense server afterwards. I couldn't find an option to install plugins from local.

**Comment by arefinhasib23** [comment]
I would like to inform you that the current Opnsense Zabbix proxy plugin doesn't work with the latest Zabbix server version. 
Proxy version is outdated, only data collection and remote execution is available with server version 6.4.3. However current Zabbix proxy Opnsense version is 6.2.9

**Comment by ThomasBahn** [comment]
That's why I'd like to have a 6.4 Zabbix proxy running on my OPNsense. For now I'm stuck with 6.2 proxy and therefore server.

**Comment by ThomasBahn** [comment]
When I look at the delta in the repository from 6.0 to 6.2 it seems a very simple addition of a line or two in the configuration, but I don't understand how to bring the change into the Github repo and from there into my OPNsense installation. It looks like there is no way to install plugins not on a official list?!

**Comment by tuxmainy** [comment]
Hi,
I was in contact with @fraenki who told me that the update gets automatically rolled out in the next OpnSense release. So if I understood that correctly, Zabbix proxy 6.4 should be available in july (see [roadmap](https://opnsense.org/about/road-map/)).

@fraenki Could you confirm?

regards
Daniel

**Comment by ThomasBahn** [comment]
I assume, this is true, after somebody changed the plug-in here in the Github repository?

I don't know, how to do this (at the moment), but before commiting such a change: How could I test the modifications before the commit (and therefore before the a distritributed worldwide)?

**Comment by fichtner** [comment]
https://github.com/opnsense/plugins/pull/3461
https://github.com/opnsense/plugins/pull/3460

**Comment by fraenki** [comment]
released in OPNsense 23.1.11
