### ISSUE TITLE
os-crowdsec - Test command incorrect 

### ISSUE THREAD

**Issue by Kennochas** [opnsense/plugins#3440]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X ] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X ] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X ] The title contains the plugin to which this issue belongs

**Describe the bug**

The documentation says: "cscli decisions add -t ban -d 2m -i" to test to see if it is working.

root@opnsense:~ # cscli decisions add -t ban -d 2m -i
FATA[0000] flag needs an argument: 'i' in -i

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**
1. SSH Into OPNsense
2. Try to run 'cscli decisions add -t ban -d 2m -i'

**Expected behavior**
SSH Session dropped.

**Screenshots**

**Relevant log files**
If applicable, information from log files supporting your claim.

**Additional context**

**Environment**
Software version used and hardware type if relevant.
e.g.:

OPNsense 23.1.6-amd64
FreeBSD 13.1-RELEASE-p7
OpenSSL 1.1.1t 7 Feb 2023

**Comment by fichtner** [comment]
cc @mmetc
