### ISSUE TITLE
Wireguard, cannot have two peers with the same subnet

### ISSUE THREAD

**Issue by deajan** [opnsense/plugins#3443]
- [X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X] The title contains the plugin to which this issue belongs

**Describe the bug**
I've setup a wireguard server on OPNsense with two remote peers.
If I happen to use same Allowed IPs network in both remote peers, only one gets to be configured with the Allowed IPs content.
This prevents the other peer to use the VPN tunnel.

*Tip*: to validate your setup was working with the previous version, use opnsense-revert 
Cannot revert production system

**To Reproduce**
1. Configure a wireguard server
2. Create two endpoints using the same Allowed IPs network
3. Go to status page
4. See following error:

```
interface: wg1
  public key: <public key>
  private key: (hidden)
  listening port: 12345

peer: <public key>
  allowed ips: (none)

peer: <public key>
  allowed ips: 10.13.47.0/24
```

**Expected behavior**
Wireguard being a mesh VPN, your're supposed to be able to have multiple peers with the same Allowed IPs networks.

Expected behavior:
```
interface: wg1
  public key: <public key>
  private key: (hidden)
  listening port: 12345

peer: <public key>
  allowed ips: 10.13.47.0/24

peer: <public key>
  allowed ips: 10.13.47.0/24
```

**Screenshots**
![image](https://github.com/opnsense/plugins/assets/4681318/c8577561-6dcc-41b1-8b76-524394f13094)

![image](https://github.com/opnsense/plugins/assets/4681318/8a506069-57af-4fc0-991e-cca7c7e12529)

**Relevant log files**
N/A

**Additional context**
N/A

**Environment**

OPNsense 23.1.7_3 (amd64) on KVM Qemu 7.2.0 with virtio network cards
os-wireguard v1.13_5

**Comment by mimugmail** [comment]
What happens on /usr/local/etc/rc.d/wireguard restart?

**Comment by deajan** [comment]
```
root@opnsense:~ # /usr/local/etc/rc.d/wireguard restart
[#] ifconfig wg1 destroy
[#] ifconfig wg create name wg1
[#] wg setconf wg1 /dev/stdin
[#] ifconfig wg1 inet 10.13.47.1/24 alias
[#] ifconfig wg1 mtu 1420
[#] ifconfig wg1 up
[+] Backgrounding route monitor
```

If I happen to add a bit treachery (added second network as 10.13.47.16/28 so I could get both peers to connect on same subnet), I get the following:
```
[#] ifconfig wg1 destroy
[#] ifconfig wg create name wg1
[#] wg setconf wg1 /dev/stdin
Warning: AllowedIP has nonzero host part: 10.13.47.20/28
[#] ifconfig wg1 inet 10.13.47.1/24 alias
[#] ifconfig wg1 mtu 1420
[#] ifconfig wg1 up
[#] route -q -n add -inet 10.13.47.16/28 -interface wg1
[+] Backgrounding route monitor
```

**Comment by justinhorton** [comment]
> Wireguard being a mesh VPN, your're supposed to be able to have multiple peers with the same Allowed IPs networks.

I don't think that's correct. WireGuard uses the AllowedIPs to make routing decisions (and decide which peer's key to encrypt the traffic with). Typically, peers are configured server-side with unique /32 addresses.

https://lists.zx2c4.com/pipermail/wireguard/2019-April/004058.html

https://superuser.com/a/1670157

**Comment by deajan** [comment]
My bad. Sorry.

**Comment by tnzil** [comment]
Proton is using the address `10.2.0.2/32` for all clients, and I’m still curious how this works. I've generated four configurations, all with the same `10.2.0.2/32` address on the same server, and they’re all working simultaneously.
