### ISSUE TITLE
[os-ddclient] cloudns is not working

### ISSUE THREAD

**Issue by kcris** [opnsense/plugins#3447]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x ] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [ x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [ x] The title contains the plugin to which this issue belongs

**Describe the bug**

opnsense gui does not work with cloudns

* the `Cloudns` service does not work
* the `Custom` service does not support full URL e.g. `ipv4.cloudns.net/api/dynamicURL/?q=some-token-here`

whereas manually editing the `/usr/local/etc/ddclient.conf` does work. I have checked this.

```
use=cmd, cmd="/usr/local/opnsense/scripts/ddclient/checkip -t 1 -s ipify-ipv4 --timeout 10",
protocol=cloudns, \
dynurl=https://ipv4.cloudns.net/api/dynamicURL/?q=my-token-here, \
my-hostname.here
```

tested with opnsense 23.1.8, via `Services/Dynamic DNS`, backend=ddclient

Here is the official doc for cloudns.net showing the format of the custom url.
https://www.cloudns.net/wiki/article/36/

Thanks

This is reopening issue #2880. Similar issue: #3430.

Thanks

cc: @AdSchellevis 

**To Reproduce**
Try it

**Expected behavior**
Should work.

**Screenshots**
none

**Relevant log files**
none

**Additional context**
none

**Environment**
OPNsense 23.1.8

**Comment by fichtner** [comment]
will fix in https://github.com/opnsense/plugins/issues/3430

**Comment by kcris** [comment]
thank you!!
