### ISSUE TITLE
os-nginx: Unable to delete created elements

### ISSUE THREAD

**Issue by roens** [opnsense/plugins#3448]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
The trashcan icon at the far right of a list of elements is missing, preventing ability to delete a created element. 

**To Reproduce**
1. Go to a config section where an element can be created (Location, HTTP Server, Security Headers, Stream Servers, …)
2. Click on the plus button below the list, fill in any required fields, click Save at the bottom of the form
3. The element just created is now editable, yet permanent. There is no UI for deleting it.

**Expected behavior**
Presence of little trashcan icons on list items.

**Screenshots**
Using `opnsense-revert -r 23.1.5 os-nginx` I was able to switch back to the previous release, which brought back the trashcan icons, allowing me to delete an unwanted element (a Stream Server I was suspecting as causing trouble). Attached are screenshots from 23.1.6 (broken) and 23.1.5 (not broken).

<img width="1137" alt="Screen Shot 2023-05-26 at 11 09 54 AM" src="https://github.com/opnsense/plugins/assets/152455/dd9242f3-4126-4ffa-b433-8c219eaf5630">
<img width="1145" alt="Screen Shot 2023-05-26 at 11 10 25 AM" src="https://github.com/opnsense/plugins/assets/152455/c697c31d-a733-4c5f-a7b5-89573228b536">

**Relevant log files**
n/a

**Additional context**
Possibly related to this point on the 1.32 version of `os-nginx`, included in 23.1.6:
* $internalModelUseSafeDelete enabled in API Settings controller to check item references before delete

**Environment**
OPNsense 23.1.7_3-amd64
FreeBSD 13.1-RELEASE-p7
OpenSSL 1.1.1t 7 Feb 2023

Supermicro E302-9D
Intel(R) Xeon(R) D-2123IT CPU @ 2.20GHz (4 cores, 8 threads)

**Comment by roens** [comment]
> After looking for a way how to get rid of settings and almost rage-quitting in despair, I hovered just a little to the right of the "..." - just to find a tooltip saying "delete" and my cursor changing:

Interesting find! I too noticed that ellipsis and thought the control might be hidden there, but for me, nothing actionable lies there (hovering/clicking there does nothing). I'm using Safari in macOS Ventura (13.4).

It looks like @krbrs has added a commit that may fix this. Looking forward to that merge. 👍🏻

**Comment by krbrs** [comment]
@roens Thanks for the heads up 😄 

I went digging in the last commits that occurred between the faulty display and the working one and stumbled across the lines I changed in my PR.

I tested with chrome on macOS - in the past I experienced problems with the zoom factor on macOS with a few web applications, but testing around with the zoom didn't do anything as the column seemed to be too small. 
Only the change of the column width fixed it for me.

Until the merge, I changed all the lines from the commit locally to confirm it's fixed on my opnsense - and the button is now there:

<img width="179" alt="commands" src="https://github.com/opnsense/plugins/assets/57227244/da473714-322a-48f8-939f-e367a705bb1b">

For the deletion - when the text is displayed, does clicking there (even without the cursor changing) remove the entry?

If you don't want to mess with the files like I did, you can try editing the value faulty column using the developer tools (I think you need to enable them somewhere in safari settings first):

<img width="499" alt="devtools" src="https://github.com/opnsense/plugins/assets/57227244/17936e6e-66b1-4535-9131-337b6fc51bfc">
(the part at the end with width 10em)

It should immediately expand the column and make the delete button clickable.
Same for every configuration page you visit..

**Comment by roens** [comment]
Thanks for the quick update! However, I've updated to current release (nginx plugin v1.32.1_2), and still do not see the trashcan button, nor can I delete a config element I've created.

**Comment by krbrs** [comment]
This must be a scaling problem, which I encountered a lot of times with macOS for all kinds of web applications in the past -
try setting another scaling in your System settings -> Displays ("more space" or similar, to the right of "Default") and check if the button shows up.

**Comment by roens** [comment]
> This must be a scaling problem, which I encountered a lot of times with macOS for all kinds of web applications in the past -
> try setting another scaling in your System settings -> Displays ("more space" or similar, to the right of "Default") and check if the button shows up.

Thanks for the thought, and apologies for the late reply.

I've always used my Apple laptops set to use the most dense display resolution (aka: "more space"), having always preferred seeing more on screen than having things "look big".
