### ISSUE TITLE
HAProxy ACLs not being generated

### ISSUE THREAD

**Issue by brendans-bits** [opnsense/plugins#3449]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X ] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [ X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [ X] The title contains the plugin to which this issue belongs

**Describe the bug**

ACLs are not being generated in the haproxy config file.

I need to make the following changes by hand to /usr/local/etc/haproxy.conf

```
     bind 192.168.101.1:443 name 192.168.101.1:443 
     mode tcp
+    tcp-request inspect-delay 5s
+    tcp-request content accept if { req.ssl_hello_type 1 }
+    use_backend mastodon if { req.ssl_sni -i mastodon.brendans-bits.com }
+    use_backend mastodon if { req.ssl_sni -i www.mastodon.brendans-bits.com }
+
     # logging options
```

**To Reproduce**

Create a real server that is listening on port 443

![image](https://github.com/opnsense/plugins/assets/111632696/ab797abe-51fd-48fd-8d00-18119ede6806)

Add this server to a backend pool

![image](https://github.com/opnsense/plugins/assets/111632696/e1810a60-c513-4fc7-9f1e-463a098833ed)

Create a condition based on SNI (I am using TLS pass through) - NOTE: It doesn't matter what type of condition I write here. No ACLs are generated and no request is passed from the public service to the backend pool.

![image](https://github.com/opnsense/plugins/assets/111632696/21eaee14-d63f-4237-a059-73ec05c8ac8e)

Add this condition to a rule

![image](https://github.com/opnsense/plugins/assets/111632696/74af2eac-b7dd-4ae9-a930-1e32c8cdf333)

HAProxy does not pass the request onto the backend server.

```
#
# Automatically generated configuration.
# Do not edit this file manually.
#

global
    uid                         80
    gid                         80
    chroot                      /var/haproxy
    daemon
    stats                       socket /var/run/haproxy.socket group proxy mode 775 level admin
    nbthread                    2
    hard-stop-after             60s
    no strict-limits
    maxconn                     10000
    tune.ssl.default-dh-param   2048
    spread-checks               2
    tune.bufsize                16384
    tune.lua.maxmem             0
    log                         /var/run/log local0 info
    lua-prepend-path            /tmp/haproxy/lua/?.lua

defaults
    log     global
    option redispatch -1
    timeout client 30s
    timeout connect 30s
    timeout server 30s
    retries 3
    default-server init-addr last,libc

# autogenerated entries for ACLs

# autogenerated entries for config in backends/frontends

# autogenerated entries for stats

# Frontend: shared_https ()
frontend shared_https
    bind 192.168.101.1:443 name 192.168.101.1:443 
    mode tcp

    # logging options

# Backend: mastodon (mastodon)
backend mastodon
    # health checking is DISABLED
    mode tcp
    balance source
    server mastodon 192.168.101.10:443 send-proxy-v2

# Backend: nextcloud ()
backend nextcloud
    # health checking is DISABLED
    mode tcp
    balance source
    server nextcloud 192.168.101.2:443 

# statistics are DISABLED

```

However, if I set the default backend pool (in the public service) to the backend I want, HAproxy passes the request to the server.

![image](https://github.com/opnsense/plugins/assets/111632696/c552ca58-63cb-4cdf-bc52-bc45f4e0df86)

**Expected behavior**

An ACL should be generated for the condition and rule to pass the request from the public service to the backend pool. 

**Screenshots**

**Relevant log files**
If applicable, information from log files supporting your claim.

**Additional context**

I am not using TLS offloading on HAProxy, I am using TLS passthrough.

**Environment**
OPNSense 23.1.8
os-haproxy 4.1

**Comment by brendans-bits** [comment]
Added in manual edits to /usr/local/etc/haproxy.conf which work as intended.

**Comment by fraenki** [comment]
You need to add the rule to either a _Backend Pool_ or a _Virtual Service_.
