### ISSUE TITLE
[os-ddclient] os-ddclient generates invalid ddclient.conf when monitoring interface ip

### ISSUE THREAD

**Issue by rhyser9** [opnsense/plugins#3450]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X] The title contains the plugin to which this issue belongs

**Describe the bug**
GUI URL: https://opnsense/ui/dyndns/

When configuring os-ddclient to update DNS based on the IP of an interface, os-ddclient generates that into the following configuration in `/usr/local/etc/ddclient.conf`:

```
syslog=yes                  # log update msgs to syslog
pid=/var/run/ddclient.pid   # record PID in file.

usev4=ifv4, if=vtnet0_vlan500, \
protocol=namecheap, \
login=<snip>, \
password=<snip> \
<snip>.com
```

As found in ddclient/ddclient#540, this configuration should actually be `usev4=ifv4, ifv4=xxx`, otherwise ddclient falls back to attempting to retrieve the interface for the default route (which also fails, for unrelated reasons described in ddclient/ddclient#540).

**To Reproduce**
1. Create an interface with a device name longer than 8 characters (i.e. 'vtnet0_vlan1')
2. Install os-ddclient plugin
3. Go to Services > Dynamic DNS > Settings
4. General Settings > Enable: True
5. General Settings > Backend: ddclient
6. Accounts > Add:
    - Check ip method: interface
    - Interface to monitor: Interface defined in step 1 with device name >8 characters
    - Service/Username/Password: user choice / doesn't matter, doesn't make it this far anyways
7. Click "Save" then "Apply"
8. See error
    - "Current IP" column is blank
    - Services > Dynamic DNS > Log File shows "FAILED: Unable to obtain information for '<ifname>' -- missing ip or ifconfig command" (where ifname is only the first 8 characters of the interface name).
    - The `/usr/local/etc/ddclient.conf` file contains the configuration `usev4=ifv4, if=<ifname>, ...`
    - Executing `ddclient -daemon=0 -debug -verbose -noquiet` returns the following results:
```
config{<snip>.com}{if}  : vtnet0_vlan500
config{<snip>.com}{ifv4} : default
config{<snip>.com}{ifv6} : default
config{<snip>.com}{usev4} : ifv4
...
DEBUG:    Reply from 'netstat -rn -4' :
DEBUG:    ------
DEBUG:    Routing tables
DEBUG:
DEBUG:    Internet:
DEBUG:    Destination        Gateway            Flags     Netif Expire
DEBUG:    default            1.2.3.4            UGS    vtnet0_v
DEBUG:    1.2.3.0/24         link#8             U      vtnet0_v
DEBUG:    1.2.3.4            link#8             UHS         lo0
DEBUG:    127.0.0.1          link#3             UH          lo0
DEBUG:    192.168.0.0/24     link#6             U      vtnet0_v
DEBUG:    192.168.0.2        link#6             UHS         lo0
DEBUG:    192.168.2.0/24     link#7             U      vtnet0_v
DEBUG:    192.168.2.1        link#7             UHS         lo0
DEBUG:    ------
DEBUG:    Default routes found for IPv4 :
DEBUG:    default            1.2.3.4            UGS    vtnet0_v
FAILED:   Unable to obtain information for 'vtnet0_v' -- missing ip or ifconfig command
DEBUG:    Reply from 'missing ip or ifconfig command' :
DEBUG:    ------
DEBUG:    ------
DEBUG:    get_ipv4: using (ifv4, default) reports <undefined>
WARNING:  <snip>.com: unable to determine IPv4 address with strategy usev4=ifv4
```

**Expected behavior**
The `/usr/local/etc/ddclient.conf` file contains the configuration `usev4=ifv4, ifv4=<ifname>, ...`.

**Environment**
Software version used and hardware type if relevant.
- OPNsense 23.1.8
- os-ddclient 1.13_1

**Comment by fichtner** [comment]
Merged, thanks!
