### ISSUE TITLE
FRR encoding & in password

### ISSUE THREAD

**Issue by pantherale0** [opnsense/plugins#3456]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

When using a password on a BGP neighbour containing special chars (specifically "&") this gets html encoded and consequently the generated config uses a password that has "&amp;" rather than "&"

This could also just be a rendering issue perhaps on the diagnostics screen?

**To Reproduce**

Create BGP neighbour with "&" symbol in password, go to "Routing" > "Diagnostics" > "General" > "Running Configuration" and check config output. 

**Expected behavior**

Should generate a config with the correct password in.

**Comment by fichtner** [comment]
A but unlikely there are encoding issues from and to XML. Possibly only the page escaping for HTML here. Have you checked the actual configuration file on the disk?

**Comment by 11harveyj** [comment]
I haven't checked the config on the disk, no. Can you point me in the right direction to the file? I'll then take a look

**Comment by 11harveyj** [comment]
Ignore that, I've just had a look at the config.xml file on the disk and it's the same, unless there is another config file I need to check?

**Comment by fichtner** [comment]
The XML is what it is... can't store a plain special character but it's very likely correctly decoded and encoded when needed... Look at `/usr/local/etc/frr/bgpd.conf` instead.


Cheers,
Franco

**Comment by 11harveyj** [comment]
I've just checked - yes, PW is right in the config file itself, just the gui is showing whats in the XML file and not taking into account the encoding it seems.

Thanks anyway, now to figure out why BGP isn't working 👍

**Comment by fichtner** [comment]
Well, almost. I think the jQuery is escaping too much. Let me take a look next week.


Cheers,
Franco

**Comment by fichtner** [comment]
@AdSchellevis do you think this still applies after recent changes? would you mind picking it up as you know better?

**Comment by AdSchellevis** [comment]
<img width="379" alt="image" src="https://github.com/opnsense/plugins/assets/9783985/bf08c806-b339-4962-adc2-ba01bdb86d1f">
<img width="601" alt="image" src="https://github.com/opnsense/plugins/assets/9783985/aeb13c14-d54f-4eb7-b791-69f0d42aa5db">

looks sane from my end, closing

**Comment by fichtner** [comment]
Wasn't this about "Routing" > "Diagnostics" > "General" > "Running Configuration"?

**Comment by AdSchellevis** [comment]
<img width="290" alt="image" src="https://github.com/opnsense/plugins/assets/9783985/f73c782e-79ab-4c71-a0c3-c07a19746a37">

**Comment by fichtner** [comment]
Perfect, thanks!
