### ISSUE TITLE
[FEATURE REQUEST] RTSP handler is needed

### ISSUE THREAD

**Issue by JGeek00** [opnsense/plugins#3458]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
I am using OPNSense as my main router on my home. My ISP provides internet connection and IPTV, and some of the features of the IPTV service relies on a RSTP server. The connection between the TV box and the RTSP server works fine, but then the UDP traffic, which contains the video streaming itself doesn't reach the TV box because the router doesn't create the rules to route it. Creating a port forwarding rule to route this traffic it's not an option because the port that will be used to transmit the UDP packages containing the video streaming is negotiated between the RTSP server and the TV box each time you request a video streaming, and that means that the port isn't always the same one. This situation isn't particular of my ISP, many ISPs around the world uses RTSP for the IPTV service. Also many IP cameras and other devices which transmit streaming video requires this feature.

**Describe the solution you'd like**
I would like to have a RSTP handler plugin to handle this situation. It should capture the RTSP traffic between the TV box and the server to identify which port will be used to stream the UDP packages, and then create a rule to forward traffic comming from that specific port on the IPTV VLAN interface to that same port on the TV box. Other advanced routers already have this feature. As far I know Mikrotik's routerOS, OpenWRT, and I think also pfSense has this feature. OPNSense has a lot of features but I don't know why this one is missing when other alternatives already have it. Also other consumer brands like Asus, D-Link or TP-Link have this feature for the IPTV streaming. I have been doing a research and I found this PR https://github.com/opnsense/plugins/pull/1312. The feature seems to be already created, but it has to be adapted to the newer versions of OPNSense. Please consider adding that feature to OPNSense because it would be very useful for a lot of people.

**Comment by Fclem** [comment]
looking into it : https://github.com/opnsense/plugins/pull/5045
