### ISSUE TITLE
FRR OSPF area setup

### ISSUE THREAD

**Issue by rdeftery** [opnsense/plugins#3463]
Missing options in the config pages for FRR/OSPF for setting the ospf area type.
We need to be able to set 'area x.x.x.x stub no-summary' in frr.conf.
In pfsense there's an "Areas" tab to FRR/OSPF that allows you to define areas as normal/stub/stub no-summary/nssa/nssa no-summary. 
In opnsense "Areas" tab is missing.

**Comment by jazares18** [comment]
I hope this gets the attention as we also need this. For now we are currently doing this via config but it gets overwritten when we do a few changes and has to manually add this again
