### ISSUE TITLE
security/acme-client: acme.sh runs arbitrary commands from a remote server

### ISSUE THREAD

**Issue by jfqd** [opnsense/plugins#3465]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**

acme.sh runs arbitrary commands from a remote server related to this issue: https://github.com/acmesh-official/acme.sh/issues/4659

Version [3.0.6](https://github.com/acmesh-official/acme.sh/releases/tag/3.0.6) is fixing the security issue.

**Comment by AdSchellevis** [comment]
https://twitter.com/opnsense/status/1667277622370344960

**Comment by fichtner** [comment]
This is not a plugin issue.
