### ISSUE TITLE
Add error_log to remote syslog in Nginx plugin

### ISSUE THREAD

**Issue by timolow** [opnsense/plugins#3469]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X ] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X ] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [ X] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
I am trying to track down NAXSI issues with a remote syslog and nothing is being sent when SYSLOG targets is populated under 'HTTP server' in NGINX plugin.

**Describe the solution you'd like**
I would like either access_log and error_log to follow the SYSLOG targets field or have access and error_logs broken out to two different fields in 'HTTP Server'

**Describe alternatives you've considered**
I have currently hand jammed error_log in the running config and got the expected output I am looking for,

**Comment by wesystems** [comment]
Hi there, 

this Feature is really missing, the error_log and the Output of the NAXSI Rules is simply not readable, especially for creating false positive Rules this makes a big effort to Analyse them. 

Currently its only possible to send Access Logs to a Remote Syslog Server but not Error Logs of the Webserver. 

@timolow Could you give me a Hint how you modified the running Config to Achieve a Remote Syslog for error_logs.
