### ISSUE TITLE
os-nginx - Allow other types than just host and network in trust proxy firewall alias

### ISSUE THREAD

**Issue by Fma965** [opnsense/plugins#3471]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
Currently the Nginx option "Trusted Proxies (Firewall Alias)" only supports host and network
![image](https://github.com/opnsense/plugins/assets/1707290/db1029f3-ae23-495d-b032-a89c918e9dfe)
https://github.com/opnsense/plugins/blob/master/www/nginx/src/opnsense/mvc/app/models/OPNsense/Nginx/Nginx.xml#L742

**Describe the solution you'd like**
Can we add the following types? this will allow for a easy automatic cloudflare IP update, as far as i can see URL isn't much different from Network but just dynamic from a URL.
URL (IPs) | A table of IP addresses that are fetched once
URL Tables (IPs) | A table of IP addresses that are fetched on regular intervals.

**Describe alternatives you've considered**
Writing a custom script to add the firewall rule as type "network" and crontab it.

**Comment by kulikov-a** [comment]
@Fma965 I don’t think it will work this way: URL-types aliases do not store their contents in the config (thus the template will not be able to pull the addresses from there). in addition, if the previous one were possible, nginx will not respond to changes in the alias content - nginx needs to be reloaded.
Couldn't it work as a workaround: use an alias in the firewall to allow access to the nginx ports from cloudflare addresses and set the Trusted Proxies to `0.0.0.0/0`? (and iirc cloudflare uses special header for real ip passing?)
