### ISSUE TITLE
View BFD neighbors is Routing Diagnostics view

### ISSUE THREAD

**Issue by michmoor0725** [opnsense/plugins#3473]
In order to view BFD neighbors today, you would need to go into the shell , vtysh, and run the command 'show bfd peer'.
Is it possible to have an option to view BFD neighbors within the GUI?

**Comment by MarkStitson** [comment]
I have most of the code for this, but still need to test it.

**Comment by michmoor0725** [comment]
Thank you. Truly appreciate it.  Because the code is mostly there what is the turnaround time to making it into the next release?

**Comment by MarkStitson** [comment]
#3487 adds BFD diagnostics for: "show bfd peers brief", "show bfd peers" and "show bfd peers counters".
This has been merged into the master branch.
