### ISSUE TITLE
Proper FRR logging

### ISSUE THREAD

**Issue by michmoor0725** [opnsense/plugins#3474]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**
I dont fully know how the OPNsense team integrated the FRR package so unsure if its a bug or not.

A clear and concise description of what the problem is including your motivation for the request,

Within the logs for the FRR dameon when a dynamic router relationship is lost the expected output [at least in my experience] is something similar to the below

`<30>Jun 19 22:12:41 bgpd[73781]: %ADJCHANGE: neighbor 10.6.106.2(790-OPNsensePOC.xxyy) in vrf default Down Peer closed the session`

The log above is taken form a pfsense deployment. 

**Describe the solution you like**

If possible can this log type be made available as shown above? As of now parsing the routing logs for neighbor adjacency failures is difficult. What's expected from a Cisco appliance or pfSense appliance is not the same or even similar on an OPNsense appliance which makes me think its the way the FRR package is integrated. Perhaps there is an option that needs to be made available?

**Describe alternatives you considered**
I dont know of any for now.

**Additional context**

Add any other context or screenshots about the feature request here or links to relevant forum thread or similar

**Comment by AdSchellevis** [comment]
just out of curiosity, how is "Routing: General->Log Level" configured?

**Comment by michmoor0725** [comment]
Its set for Emergencies. Toying around with this option doesn't produce the log line thats expected when bouncing a BGP neighbor. 
Strangely there really isnt much in the way of any useable logs when it comes to any bgp routing disruption which is a worry.

**Comment by mimugmail** [comment]
![image](https://github.com/opnsense/plugins/assets/20438689/7854058c-a299-4a60-af91-cb0d8eb94e04)

You need to check notification level, not emergency

**Comment by michmoor0725** [comment]
Thats OSPF. What about BGP? Thats the area where the AdjChg logs arent generated.

**Comment by michmoor0725** [comment]
The differences in the frr.conf file are not much esepecially when related to syslog.

OPNsense
!
frr version 7.5.1
frr defaults traditional
hostname GAF1
log syslog notifications
!
router bgp 65001
 bgp router-id 69.69.69.69
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 bgp graceful-restart



pfSense
!
frr defaults traditional
hostname GAFW
password sfhsdfh
log syslog
service integrated-vtysh-config
!
router bgp 65001
 bgp log-neighbor-changes
 bgp router-id 192.168.50.254
 bgp default local-preference 400
 no bgp network import-check
 bgp bestpath as-path multipath-relax as-set
 bgp bestpath compare-routerid

**Comment by mimugmail** [comment]
![image](https://github.com/opnsense/plugins/assets/20438689/6913b183-950e-43ac-b75c-bf919d673d4a)

**Comment by michmoor0725** [comment]
I don't understand...
My logging is back at defaults. 
I apologize for this issue then. I truly don't understand how my outputs are different.

**Comment by michmoor0725** [comment]
Is there anything different with your frr conf file? Logging overall on the system?

**Comment by mimugmail** [comment]
In logging menu deselect multiselect and uncheck all option to display all

**Comment by michmoor0725** [comment]
Just to make sure im on the correct path here.

![image](https://github.com/opnsense/plugins/assets/47565104/51cf3940-55cc-4930-a8ee-ccf5574d9430)
![image](https://github.com/opnsense/plugins/assets/47565104/47c6af49-95e9-4e49-9b77-d7194db3e5fc)
![image](https://github.com/opnsense/plugins/assets/47565104/d027ca88-999a-42ad-bced-954942297b2c)

**Comment by michmoor0725** [comment]
When i do take down a neighbor by going into the vtysh config option in the shell these are the only logs i have. Noticed there is no message for the BGP going down.


GAFW#conf t
GAFWconfig)# router bgp 65001
GAFWconfig-router)# address-family ipv4 unicast
GAFWconfig-router-af)# no neighbor 10.6.106.2 activate



![image](https://github.com/opnsense/plugins/assets/47565104/ced49e0d-26a1-4451-8c4b-8a55820d2316)

**Comment by mimugmail** [comment]
In your screenshot upper right, you only selected to display warning and above. I think I already told you so ;)

**Comment by michmoor0725** [comment]
I showed warning but if i select warning or notice or error the results are the same. No BGP bounces seen in the logs. For example these are set to notice 

I just dropped a neighbor on purpose

![image](https://github.com/opnsense/plugins/assets/47565104/583d9540-f952-4927-acbf-b908d01d8204)

**Comment by michmoor0725** [comment]
Hmm..Taking a closer look at your output vs mine i see the issue but dont know how to resolve.
You have  some BGP log events as informational. 
All of mine bgpd events are logged as Error.....Why? This shouldnt be.

**Comment by mimugmail** [comment]
No idea, in my Tests I'm killing bgp at the other side, so this is real live, not the same as disabling something locally

**Comment by michmoor0725** [comment]
Appreciate you trying to help. I do. At this point its not clear whats the specific issue within the FRR dameon. 
The exact same config exists on a previous *sense. 
The following tasks i have done
1. Remove all BGP configurations. Started with a clean slate here
2. Reinstalled frr
3. As a test i used OSPFv2
4.  Because we got a maintenance window, i moved the connections back to previous sense and everything works as it should with proper logging messages.
5. 
No matter what is done all routing protocol messages are in an ERROR state with the following in the log 
[EC 100663299] buffer_flush_available: write error on fd 2: Bad file descriptor	

Whats strange is that all neighbor relationships form and i am able to route across. The issue is there are no usable logs as everything is from ERROR severity. Whatever is going on its specific only to opn.

**Comment by michmoor0725** [comment]
@mimugmail i think i figured out the issue.
On the pfsense side the frr configuration has the following under the BGP process
`(config-router)# bgp log-neighbor-changes
`
that of course logs neighbor flaps. Removed it from pfsense side and no more notifications.

I suspect you may have that in your running frr.conf.

Can you confirm if you have that configured?

I am running frr version 7.5.1

**Comment by michmoor0725** [comment]
Success. Notifications are now working.
I have mimicked the config from pfsense. 
Because these changes were done through vtysh/shell if i reload services the config is gone. Is there anyway to push some hotfix to the way OPNsense generates a configuration? PF does certain things by default.

Change 1..
`log syslog
`

Change 2
` bgp log-neighbor-changes
`

**Comment by mimugmail** [comment]
I think I can add a checkbox, but maybe it will stay until 23.7 when it goes live

**Comment by michmoor0725** [comment]
A checkbox would be awesome. Please !!
Also will 23.7 change how FRR will function?

**Comment by michmoor0725** [comment]
Should i open a new Feature Request linking to this one or keep this one open for tracking?
