### ISSUE TITLE
FRR Expose route-via-default

### ISSUE THREAD

**Issue by pantherale0** [opnsense/plugins#3478]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
This may already be a feature, but my BGP provider requires me to add "ip nht route-via-default" and "ipv6 nht route-via-default" to FRRs config.

Requesting here for that support, there appears to be next-hop self, however this doesn't work for me.

**Describe the solution you'd like**
Input field on FRR/BGP neighbor config

**Describe alternatives you've considered**

**Additional context**

**Comment by JSuenram** [comment]
Reopening this as having same issue. At least there is a change in the FRR-Template needed to add "ip nht resolve-via-default" when you enable "Multi-Hop" for a neighbor. Without BGP-Session do not come up, as they need to go through default route, which FRR does not do by default....
