### ISSUE TITLE
security/acme-client: Allow for short lived ACME certificates

### ISSUE THREAD

**Issue by matthew-salerno** [opnsense/plugins#3479]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
I run my own ACME server / CA for homelab purposes and would like to be able to issue short lived certificates, on the order of hours. I issue one day certs, and setting the renew interval to 1 day means my certificates can expire before they are ready. 

**Describe the solution you'd like**
Allowing 0 days and adding an hours field would solve my issue

**Describe alternatives you've considered**
Specify renewal intervals as a lerp between the valid from and valid until fields (e.g. 75% on a 4 day certificate would try to renew after 3 days)

For the time being, upping my certificate lifespan to 2 days has little effect for me, but that may not be true for all users.

**Additional context**
[needsRenewal function](https://github.com/opnsense/plugins/blob/682780e6f61ba8650e0928b768078ebab65e6d71/security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeCertificate.php#L416)

**Comment by fraenki** [comment]
I think that's a very special use-case and I fail to see the benefit of using certs with such a short lifetime. Additionally having _two_ fields in the GUI to specify the cert lifetime would just increase complexity. I would really like to avoid this.

**Comment by matthew-salerno** [comment]
I understand if it's not a priority. I'm not an expert, but in my scenario short lived certificates are part of a "if it hurts, do it more" mentality. If there's misconfiguration or issues in automation or connectivity, I ideally want to find it early rather than a month later when I'm working on something completely different. It also allows for passive revocation, which can reduce some of the complexity involved around certificate revocation lists.

**Comment by Gabgobie** [comment]
I am having a similar issue, although my situation is not quite as extreme. I am using Step-CA for my internal certificates. They also provide good reasons for using short lived certificates.
My certificates are valid for seven days and I set my renewal interval to be daily. My CA isn't rate limiting. The acme plugin will ignore the set renewal interval and determine that the certificate doesn't need to be renewed every night when the cron job is telling it to renew the cert. So far I don't mind it, however it will wait until the certificate has expired to try and renew the certificate. At that point it is too late to renew the certificate and it will fail, presenting me with the expired certificate when I try to access the WebUI. It will ONLY successfully renew the certificate when I force renew the certificate.

I set my log level to debug when I last force renewed so I should be able to post logs of the process if need be.

**Comment by abcd678** [comment]
> I think that's a very special use-case and I fail to see the benefit of using certs with such a short lifetime. Additionally having _two_ fields in the GUI to specify the cert lifetime would just increase complexity. I would really like to avoid this.

In what world is that a special use-case? Short lived certificates are incredibly common for setups with automation and are basically the norm with locally run CA's.
Not to mention that the world is moving towards shorter and shorter lifetime certificates all the time.

**Comment by Monviech** [comment]
I guess the logical conclusion of less and less lifetime would be one certificate per TCP connection lifetime. xD

**Comment by abcd678** [comment]
Great strawman!
P.S. this doesn't change the reality that 24 hour certificates are incredibly common, and for good reasons.

**Comment by fichtner** [comment]
The irony is that 24 hours is 1 day which you can input, no? The OP was asking for sub-day granularity.

**Comment by Gabgobie** [comment]
@fichtner I don‘t like @abcd678‘s tone either but unless something changed since 2023 (or my configuration was erroneous since I was moderately new to everything IT back then), there should still be the issue I raised about the renewal behaviour and I‘d generally also like the ability to issue certificates with sub-day lifetimes.

Best,
Gab

Edit: I really like the proposed alternative in OP of the adaptive renewal interval based on certificate lifetime. I think to remember certbot defaulting to 1/3 or 2/3 but don‘t quote me on that.

This would also entirely sidestep the complexity of setting a possibly invalid interval or having a second sub-day field.

Edit 2:

> The irony is that 24 hours is 1 day which you can input, no? The OP was asking for sub-day granularity.

I think the part about 24h certificates is not covered since the renewal interval cannot be set lower and the certificates would expire before renewal is triggered.
