### ISSUE TITLE
`unknown directive "vhost_traffic_status_zone"` after upgrading to os-nginx 1.32.1_1

### ISSUE THREAD

**Issue by mreiche** [opnsense/plugins#3481]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [✓] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [✓] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [✓] The title contains the plugin to which this issue belongs

**Describe the bug**
I've upgraded the Opnsense version of the secondary WAF from 21.1.9 to 23.1.10_1 for upgrade testing purposes. There weren't any errors during the update. When I synchronized the configuration from primary, I noticed that the Nginx service was not starting because of the errors below.

Working packages/plugins for OpnSense 21.1.9
- os-nginx 1.28
- Nginx 1.20.2_9,2

Not working packages/plugins for OpnSense 23.1.10_1
- os-nginx 1.32.1_1
- nginx 1.24.0_6,3

**Relevant log files**

```
nginx: configuration file /usr/local/etc/nginx/nginx.conf test failed	
nginx: [emerg] unknown directive "vhost_traffic_status_zone" in /usr/local/etc/nginx/opnsense_http_vhost_plugins/vts.conf:1	
```

**Environment**
OPNsense 23.1.10_1 (amd64, OpenSSL).

**Comment by mreiche** [comment]
Update: We've upgraded step-by-step and the last working version is:

* OpnSense: 23.1_6
* nginx 1.22.0_7,3
* os-nginx: 1.31

**Comment by fichtner** [comment]
This has already been hotfixed yesterday...

**Comment by mreiche** [comment]
Are you really sure? Because we've experienced that in yesterday `23.1.10` and also upgraded to `23.1.10_1` yesterday.

**Comment by fichtner** [comment]
You need to reapply the nginx configuration again. This was broken by 1.24 but should have been in the plugin a long time ago.. for some reason the module auto-loaded on nginx 1.22..

**Comment by mreiche** [comment]
More details:
```
***GOT REQUEST TO UPDATE***
Currently running OPNsense 23.1_6 at Fri Jun 23 11:25:39 CEST 2023
Updating OPNsense repository catalogue...
OPNsense repository is up to date.
All repositories are up to date.
Updating OPNsense repository catalogue...
OPNsense repository is up to date.
All repositories are up to date.
Checking for upgrades (79 candidates): .......... done
Processing candidates (79 candidates): .......... done
The following 87 package(s) will be affected (of 0 checked):
...
Message from opnsense-23.1.10_1:

--
I'm no chicken
Checking integrity... done (0 conflicting)
...
!!!!!!!!!!!! ATTENTION !!!!!!!!!!!!!!!
! A critical upgrade is in progress. !
! Please do not turn off the system. !
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Installing kernel-23.1.8-amd64.txz... done
Installing base-23.1.8-amd64.txz... done
Cleaning obsolete files... done
Please reboot.
***REBOOT***
```
![OpnSense Apply Nginx Config](https://github.com/opnsense/plugins/assets/572453/ad7a64f4-4c5f-449d-9d1f-bb3378068c89)
![OpnSense Apply Nginx Config2](https://github.com/opnsense/plugins/assets/572453/de6ca6ad-5d88-4e91-b372-1e03a59cc20e)

```
2023-06-23T11:31:19 | Emergency | nginx | nginx: configuration file /usr/local/etc/nginx/nginx.conf test failed |  
2023-06-23T11:31:19 | Emergency | nginx | nginx: [emerg] Naxsi-Config : Incorrect line MainRule id:1500 (/usr/obj/usr/ports/www/nginx/work/naxsi-29793dc/naxsi_src/naxsi_skeleton.c/973)... in /usr/local/etc/nginx/nginx.conf:33
```

**Comment by fichtner** [comment]
Well, the module error is gone... and now you have the error from #3480

**Comment by mreiche** [comment]
No. The other error comes up, when I uncomment `/usr/local/etc/nginx/nginx.conf:33`

**Comment by fichtner** [comment]
With all due respect this is a waste of time. I've been through this yesterday.

**Comment by fichtner** [comment]
If you don't have this line in https://github.com/opnsense/plugins/commit/7c83dbba152d nginx.conf you're not going to get rid of the error indeed.

**Comment by mreiche** [comment]
```
    MainRule id:1401 "str:%U" "msg:M$ encoding" "mz:BODY|ARGS|URL|$HEADERS_VAR:Cookie" "s:$policy990c18d143b747479aaa6c0754cac049:4";

#    MainRule id:1500 "rx:\.ph|\.asp|\.ht|\.jsp" "msg:asp/php/jsp file upload" "mz:FILE_EXT" "s:$policyd90f9550098d4eb0bacca9ebad947934:8";

    MainRule id:1106 "str:data://" "msg:data:// scheme" "mz:BODY|ARGS|$HEADERS_VAR:Cookie" "s:$policydd6604697d034955bf975f97134d0888:8";
```
```
/usr/local/etc/nginx/nginx.conf: 2894 lines, 118739 characters.
```

```
2023-06-23T11:37:11 | Emergency | nginx | nginx: configuration file /usr/local/etc/nginx/nginx.conf test failed |  
2023-06-23T11:37:11 | Emergency | nginx | nginx: [emerg] unknown directive "vhost_traffic_status_zone" in /usr/local/etc/nginx/opnsense_http_vhost_plugins/vts.conf:1
```

**Comment by mreiche** [comment]
> If you don't have this line [7c83dbba152d](https://github.com/opnsense/plugins/commit/7c83dbba152d) in nginx.conf you're not going to get rid of the error indeed.

I've added the line manually to `nginx.conf`. The error is gone but now the other error occurs:
```
2023-06-23T11:39:25 | Emergency | nginx | nginx: configuration file /usr/local/etc/nginx/nginx.conf test failed |  
2023-06-23T11:39:25 | Emergency | nginx | nginx: [emerg] Naxsi-Config : Incorrect line BasicRule id:2003 (/usr/obj/usr/ports/www/nginx/work/naxsi-29793dc/naxsi_src/naxsi_skeleton.c/555)... in /usr/local/etc/nginx/nginx.conf:33
```
How to force rewrite `nginx.conf` completely?

**Comment by fichtner** [comment]
# configctl template reload OPNsense/Nginx

**Comment by mreiche** [comment]
Ran as root:
```
# configctl template reload OPNsense/Nginx
Execute error
```

**Comment by fichtner** [comment]
Yep, all broken up it seems, but hotfix is working... You can check for errors under System: Log Files: Backend and I'm closing this.

**Comment by mreiche** [comment]
The reason for this bug was, that the config file could not be rewritten correctly (https://github.com/opnsense/plugins/issues/3482)
