### ISSUE TITLE
os-bind BIND+view

### ISSUE THREAD

**Issue by alexunderboots** [opnsense/plugins#3495]
opnsense 23.1.11

os-bind 1.26_5

Good afternoon. Help set up BIND for split-DNS using VIEW. There are no VIEW settings in the OPNSENSE interface, and when writing directly to named.conf - OPNSENSE resets the settings

**Comment by sifybug** [comment]
AFAIK bind views are not implemented in Opnsense interface. Instead of editing named.conf directly, you can edit the template file of named.conf. Template files are usually not overwritten, unless there is an upgrade in package.

Path to template files are here: /usr/local/opnsense/service/templates/

More information about using templates is documented here:  https://docs.opnsense.org/development/backend/templates.html

**Comment by Gabgobie** [comment]
As this is unfortunately a low effort issue report I'd generally prefer to open a new one but according to the CONTRIBUTING.md I think this is close enough to join in.

I would like to go towards turning this into a feature request, although not for adding view but instead for adding an "advanced mode" which would disable the user-friendly GUI for the administration of Bind and replaces it with a file-manager and text editor.

I assume that the Bind package is a standard bind server which works with configuration files that are generated through the UI and it therefore generally supports the full feature set.
While you can use SSH to work with your named.conf, it is unreliable as it will be overwritten by the UI.
I also don't think that changing the template is the best way to go as it can be overwritten by an upgrade as sifybug mentioned.

If there was a simple option that disabled the templating and friendly-UI and warned you about potentially overwriting your configuration if you try to disable it again, the full featureset of bind would be unleashed in a stable way and with relatively low effort on the plugin maintainers side.

While the text-editor from the web-UI I mentioned would be nice, it would be entirely sufficient to have the option to disable the templating and autocreation of the configuration in favor of managing it by hand.

**Comment by mimugmail** [comment]
You can install the bind pkg without the plugin and use the cli, nothing gets overwritten then

**Comment by Gabgobie** [comment]
Thanks for the suggestion. It never occurred to me that this was an option.

I still think it would be nice to have a way to interact with the necessary files from the WebUI and use the standard way of installation but I guess this is a good solution until that becomes a possibility.

**Comment by fichtner** [comment]
@mimugmail did such plugins and demand was not as you expect. I think GUI with managed set of features and no GUI with full manual feature set are two very good options. For everything in between adding support for a new feature in the plugin is the most robust way in the long term.
