### ISSUE TITLE
os-nrpe upcoming issue with nrpe3, switch to net-mgmt/nrpe?

### ISSUE THREAD

**Issue by Beleggrodion** [opnsense/plugins#3496]
It's not directly a bug report on the first hand, because the plugin works as expected at the moment, but their coul'd be an upcoming problem in the future. Because when i install the nrpe plugin i receive the following notice:

```
Currently running OPNsense 23.1.11 at Thu Jul  6 12:32:03 CEST 2023
...
===>   NOTICE:

The nrpe3 port currently does not have a maintainer. As a result, it is
more likely to have unresolved issues, not be up-to-date, or even be removed in
the future. To volunteer to maintain this port, please create an issue at:

https://bugs.freebsd.org/bugzilla

More information about port maintainership is available at:

https://docs.freebsd.org/en/articles/contributing/#ports-contributing
--
===>   NOTICE:

This port is deprecated; you may wish to reconsider installing it:

Fails to build with recent OpenSSL so use net-mgmt/nrpe.

It is scheduled to be removed on or after 2023-06-03.

```

As seen here: https://www.freshports.org/net-mgmt/nrpe/ this commit with that note was done this summer. So perhaps the remove coul'd happen soon? Perhaps this is already planned, because the README.md already has an entry for "net-mgmt/nrpe" ?

**Comment by fichtner** [comment]
@mimugmail and me fixed this for upcoming 24.1
