### ISSUE TITLE
os-tor: Add the FreeBSD nyx port to the OPNSense ports collection or provide a better tor management tool

### ISSUE THREAD

**Issue by noseshimself** [opnsense/plugins#3500]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
You added a tor plugin with out any useful information about the gateway's state. There is a terminal UI tool that would provide at least basic monitoring/troubleshooting abilities (nyx) and there are several GUI options you might consider

**Describe the solution you'd like**
Minimum: Just add nyx to the subset of FreeBSD ports provided in the OPNSense collection.
Better: Add one of the tor Web frontends.

**Describe alternatives you've considered**
Removing tor proxy functions from the OPNSense gateway and run a separat system just for tor.

**Comment by MikeBishop** [comment]
FWIW, nyx is easy to install:

```
python3 -m ensurepip --upgrade
pip3 install nyx
```

Then you just need to get the ControlPort password out of your OPNsense config file and store it in `.nyx/config`.

**Comment by noseshimself** [comment]
As soon as I'm *not* using "vendor included package sources" and have to use "third-party sources" (i. e. pip) I have to write an essay on the topic, prepare a ISO-level presentation and still fear that someone wants to discuss it for days.
