### ISSUE TITLE
www/nginx (v 1.32.1_2): "X-Forwarded-For": inconsistency?

### ISSUE THREAD

**Issue by labor4** [opnsense/plugins#3505]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
This may be a misunderstanding on my side, or it could be an unwanted ambiguity.

The template for nginx: `location.conf` produces:
````
...
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
...
````
In a setup where the client speaks directly to nginx (reverse proxy):

Is it true that "X-Real-IP" is exclusively the header to communicate the client's IP to the upstream server?
Is it true that these are not interchangeable?

I see the technical difference between a) nginx getting a request from client, and b) nginx getting a request from a reverse-proxy,
but is not the goal in both cases to gather the original client's IP?

I am asking because I was under the impression that these were conflicting definitions.
HAproxy, IIRC, does a XFF when activating forwardfor, which IS the client's IP.

If so, && in case no downstream proxy is allowed, should...
````
...
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $remote_addr;
...
````
?
(plus vice versa)

**Comment by kulikov-a** [comment]
https://stackoverflow.com/questions/72557636/difference-between-x-forwarded-for-and-x-real-ip-headers ?

**Comment by labor4** [comment]
thanks. cannot reconstruct.
