### ISSUE TITLE
dns/rfc-2136

### ISSUE THREAD

**Issue by mfld-pub** [opnsense/plugins#3510]
- [X ] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X ] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X ] The title contains the plugin to which this issue belongs

**Describe the bug**
RFC 2136 input validation in GUI rejects key names that end in a period.

**To Reproduce**

key names that end in a period can be valid keys. Plugin refuses to save a config where the key name ends in a period.

**Expected behavior**
It should save and apply a key name ending in a period.

Seen as recently as OPNsense 23.1.11-amd64

**Comment by fichtner** [comment]
@mfld-pub for future reports it would be best to give the exact error message or a screenshot, but you are likely looking for dd511ea

    # opnsenses-patch -c plugins dd511ea


Cheers,
Franco
