### ISSUE TITLE
www/web-proxy-useracl: Non-existent method called

### ISSUE THREAD

**Issue by mmorev** [opnsense/plugins#352]
https://github.com/opnsense/plugins/blob/3fba5e1ca1839f3814fa0b9e9343927c724fa6d0/www/web-proxy-useracl/src/opnsense/mvc/app/controllers/OPNsense/ProxyUserACL/Api/SettingsController.php#L96
https://github.com/opnsense/plugins/blob/3fba5e1ca1839f3814fa0b9e9343927c724fa6d0/www/web-proxy-useracl/src/opnsense/mvc/app/controllers/OPNsense/ProxyUserACL/Api/SettingsController.php#L160

No such method `OPNsense\Proxy\Api\SettingsController::encode`.
Therefore, group addition in plugin interface not working.

**Comment by kekek2** [comment]
It use https://github.com/opnsense/core/pull/1892

**Comment by fichtner** [comment]
we haven't even built the first dev version yet :D

this will take a while, also needs a tools git refresh for php70-intl

**Comment by mmorev** [comment]
Okay, thanks a lot!
@kekek2 very wonderful plugin! (offtop) Are you planning to implement filtration by categories, not only by URLs? I'm ready to help if you need.

**Comment by fichtner** [comment]
was merged to core just now, thanks! https://github.com/opnsense/core/commit/baab54de6

**Comment by kekek2** [comment]
@mmorev could you tell in detail about the categories ?

**Comment by mmorev** [comment]
@kekek2 I mean URL Filtering configured on page "Services->Web Proxy->Administration->Remote ACLs". Currently, if I block public mail services there, for example, they are blocked for all users. Can we combine squid acl entries created by URL filtering with ones created by your plugin into single http_access rule set?
For example: "http_access allow ext_group_ldap_0 remoteblacklist_publicmail".
squid http_access directive uses 'and' logic in case multiple acl names specified.
Minor changes to remoteACLs module may be needed.
