### ISSUE TITLE
FRR: Permissions not set properly when installing plugin

### ISSUE THREAD

**Issue by derbolle** [opnsense/plugins#3521]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [ x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [ x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x ] The title contains the plugin to which this issue belongs

**Describe the bug**
A clear and concise description of what the bug is, including last known working version (if any).

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**
1. Go to system --> firmware --> plugins
2. Click on os-frr
3. Scroll down to Routing
4. Enable and change some settings
5. click on Routing --> Diagnostics - General --> Running configuration

A changed Running configuration (e.g something like router bgp asnumber ) should be displayed
but instead the default configuration is displayed and settings are not in effect. 

After starting the console and using "reload all services" there are permission errors displayed for 
/usr/local/etc/frr/ospf6d.conf and other files 

I set the permissions for the directory /usr/local/etc/frr to 755 
and for the files in the directory to 644 like they are on opnsense version 23.1.11 (where FRR is working correctly and i didn't change anything manually)

after setting the permissions on opnsense 23.7 FRR is working as it should again. 

Reinstalling the plugin doesn't help and reinstalling opnsense(on fresh virtual hardware) leads to the same behaviour. 

I don't exactly know if this is a plugin or opnsense core issue but my guess is that it is more fitting here.
I hope I could provide sufficient information to help fix the issue

![grafik](https://github.com/opnsense/plugins/assets/53299502/687e26a0-23b6-4da8-889d-78ff5cf9bae2)

OPNsense 23.7
Virtual Machine on proxmox Host
Network virtio

**Comment by teknofyl** [comment]
Can confirm this behaviour and workaround.

**Comment by derbolle** [comment]
@AdSchellevis I think this should be labelled as bug instead of support. What do you think?

**Comment by fichtner** [comment]
As soon as it’s been investigated what/where the actual bug is.

**Comment by mimugmail** [comment]
I guess missing call of setup.sh and it changed cause of frr8 upgrade

**Comment by derbolle** [comment]
Thanks for the fast reply. If I can help narrow down the issue or you require further information I will gladly help on monday when I am back at work.

**Comment by AdSchellevis** [comment]
`/usr/local/opnsense/scripts/quagga/setup.sh`  doesn't appear to be executed indeed, marking this as a bug.

**Comment by AdSchellevis** [comment]
this https://github.com/opnsense/plugins/commit/d50fc1f4a737e3e86ee8c65fc8f0a2f26eca23d5 should do the trick, but @fichtner should probably take a look next week if he agrees.

**Comment by fichtner** [comment]
I don’t understand what broke the FreeBSD port here 🤨

**Comment by AdSchellevis** [comment]
no clue, it's a bit weird, but the fix seems to work for now.

**Comment by fichtner** [comment]
Looks like a feasible workaround but start_postcmd is broken as well since rc.d file overwrites this (and splits up "frr" service into daemons which goes agains even mediocre practices). I'm afraid this will eat more time than justified.

**Comment by fichtner** [comment]
@AdSchellevis would you mind testing this for me? https://github.com/opnsense/plugins/commit/2c943b4de4d5af
