### ISSUE TITLE
os-iperf 1.0_1 is not starting

### ISSUE THREAD

**Issue by hsiewert** [opnsense/plugins#3522]
**Important notices**
- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
I tried to start an iperf to measure the bandwith of an VPN.  I selected an interfache and clicked "Create instance" but nothing happens.
The processes ins the system shows this:
```
root@fw1:/var/etc/openvpn # ps aux | grep iperf
root    26386   0.0  0.1  12724   2116  -  Ss   21:43       0:00.00 daemon: /usr/local/opnsense/scripts/iperf/ruby_iperf.rb[27326] (daemon)
root    27326   0.0  0.4  84528  16156  -  R    21:43       0:00.39 /usr/local/bin/ruby /usr/local/opnsense/scripts/iperf/ruby_iperf.rb (ruby31)
root    28349   0.0  0.1  12720   2248  0  S+   21:43       0:00.01 grep iperf

```
Remove and reinstalling the plugin didn't solve it.

**To Reproduce**
1. Go to 'IInterfaces', 'Diagnostics', 'Iperf'
2. Drop down an Interface
3. Click on 'Create instance'
4. It will show the 'egg timer' butnoting happens

I tested it on my production firewall as well as on my soho installation. 

prod: 2x OPNsense 23.7 (amd64, OpenSSL) as HA
soho: OPNsense 23.7 (amd64, OpenSSL) on Apu2

iperf 1.0_1

**Comment by HannahKiekens** [comment]
After some digging:

the /usr/local/opnsense/scripts/iperf/ruby_iperf.rb script fails with:
```
<internal:/usr/local/lib/ruby/3.1/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- rexml/document (LoadError)
        from <internal:/usr/local/lib/ruby/3.1/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /usr/local/opnsense/scripts/iperf/ruby_iperf.rb:33:in `<main>'
```

pretty sure its just missing a dependency on:
```
rubygem-rexml-3.2.5            XML toolkit for Ruby
```
