### ISSUE TITLE
FRR: OSPFv3 Generate Multicast Rules

### ISSUE THREAD

**Issue by billgertz** [opnsense/plugins#3524]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
Noticed when I tried to enable OSPFv3 that no rules in the floating rulest are created to allow OSPFv3 Multicasts for Router (ff02::5) or Designated Router (ff02::6) are created as they are for the equivalent in OSPFv2. See: /net/frr/src/etc/inc/plugins.inc.d/frr.inc:

```
function frr_firewall($fw)
{
    $ospf = new \OPNsense\Quagga\OSPF();

    if ((string)$ospf->enabled == '1') {
        foreach ($ospf->networks->network->iterateItems() as $network) {
            if ((string)$network->enabled == '1') {
                $fw->registerFilterRule(
                    1, /* priority */
                    array(
                        'ipprotocol'     => 'inet',
                        'protocol'       => 'ospf',
                        'statetype'      => 'keep',
                        'label'          => 'Pass OSPF (autogenerated)',
                        'from'           => $network->ipaddr . '/' . $network->netmask,
                        'to'             => '224.0.0.0/24',
                        'direction'      => 'in',
                        'type'           => 'pass',
                        'disablereplyto' => 1,
                        'quick'          => true
                    ),
                    null
                );
                $fw->registerFilterRule(
                    1,
                    array(
                        'ipprotocol'     => 'inet',
                        'protocol'       => 'ospf',
                        'statetype'      => 'keep',
                        'label'          => 'Pass OSPF UNICAST (autogenerated)',
                        'from'           => $network->ipaddr . '/' . $network->netmask,
                        'to'             => '(self)',
                        'direction'      => 'in',
                        'type'           => 'pass',
                        'disablereplyto' => 1,
                        'quick'          => true
                    ),
                    null
                );
                $fw->registerFilterRule(
                    1,
                    array(
                        'ipprotocol'     => 'inet',
                        'protocol'       => 'ospf',
                        'statetype'      => 'keep',
                        'label'          => 'Pass OSPF (autogenerated)',
                        'from'           => '224.0.0.0/24',
                        'to'             => $network->ipaddr . '/' . $network->netmask,
                        'direction'      => 'out',
                        'type'           => 'pass',
                        'disablereplyto' => 1,
                        'quick'          => true
                    ),
                    null
                );
                $fw->registerFilterRule(
                    1,
                    array(
                        'ipprotocol'     => 'inet',
                        'protocol'       => 'ospf',
                        'statetype'      => 'keep',
                        'label'          => 'Pass OSPF UNICAST (autogenerated)',
                        'from'           => '(self)',
                        'to'             => $network->ipaddr . '/' . $network->netmask,
                        'direction'      => 'out',
                        'type'           => 'pass',
                        'disablereplyto' => 1,
                        'quick'          => true
                    ),
                    null
                );
            }
        }
    }
}
```
When enabled OSPFv3 on an interface, no new rules are created at all in the Firewall Floating section. Without these rules, the OSPFv3 instances on each router never communicate. 

Setting the interface Network Type to "Broadcat multi-access network" or "Point-to-point network" under the Interface tab for OSPFv3 does not generate any rules either:

<img width="1795" alt="Screenshot 2023-08-06 at 17 43 14" src="https://github.com/opnsense/plugins/assets/3613249/47562560-9a75-4649-9271-9aaa19102e85">

Without OSPFv3 broadcast rules in the Floating rule set the following blocks are seen in the firewall log:

```
2023-08-06T15:48:41 | Informational | filterlog | 20,,,02f4bab031b57d1e30553ce08e0ec131,xn1,match,block,in,6,0xc0,0x00000,1,ospf,89,40,fe80::da18:d301:90a2:3030,ff02::5,datalength=40 |  
2023-08-06T15:48:31 | Informational | filterlog | 20,,,02f4bab031b57d1e30553ce08e0ec131,xn1,match,block,in,6,0xc0,0x00000,1,ospf,89,40,fe80::da18:d301:90a2:3030,ff02::5,datalength=40 |  
2023-08-06T15:48:22 | Informational | filterlog | 20,,,02f4bab031b57d1e30553ce08e0ec131,xn1,match,block,in,6,0xc0,0x00000,1,ospf,89,40,fe80::da18:d301:90a2:3030,ff02::5,datalength=40 |  
2023-08-06T15:48:12 | Informational | filterlog | 20,,,02f4bab031b57d1e30553ce08e0ec131,xn1,match,block,in,6,0xc0,0x00000,1,ospf,89,40,fe80::da18:d301:90a2:3030,ff02::5,datalength=40 |  
2023-08-06T15:48:04 | Informational | filterlog | 20,,,02f4bab031b57d1e30553ce08e0ec131,xn1,match,block,in,6,0xc0,0x00000,1,ospf,89,40,fe80::da18:d301:90a2:3030,ff02::5,datalength=40 |  
2023-08-06T15:47:56 | Informational | filterlog | 20,,,02f4bab031b57d1e30553ce08e0ec131,xn1,match,block,in,6,0xc0,0x00000,1,ospf,89,40,fe80::da18:d301:90a2:3030,ff02::5,datalength=40
```

**Describe the solution you'd like**
Create a floating rule that allows these protocols to inbound on interfaces configured for OSPFv3. 

**Describe alternatives you've considered**
As a work around added an Alias:

    OSPFv3_Multicast: fe02::5, fe02::6

<img width="1192" alt="Screenshot 2023-08-06 at 17 44 28" src="https://github.com/opnsense/plugins/assets/3613249/5a969d33-5ee2-4843-9c8d-6afa63b252cf">

Also added a Floating firewall rule:
   Action: Pass
   Interface: <Same as OSPFv3 Configured interfaces>
   TCP/IP Version: IPv6
   Protocol: OSPF
   Destination: OSPFv3_Multicast

<img width="1791" alt="Screenshot 2023-08-06 at 17 47 39" src="https://github.com/opnsense/plugins/assets/3613249/deedf735-d3a9-4ae2-ae48-5cd284d909e6">

When the rule is added and enabled OSPFv3 neighbor comes up to Full state as a DR.

**Additional context**
OPNsense Versions:
   OPNsense 23.7-amd64
   FreeBSD 13.2-RELEASE-p1
   OpenSSL 1.1.1u 30 May 2023

Platform:
   xcp-ng: 8.2

**Comment by billgertz** [comment]
Have created a PR to add the rules for OSPFv3 in [this PR](https://github.com/opnsense/plugins/pull/3530). Please let me know what is screwed up.

**Comment by AdSchellevis** [comment]
closed with https://github.com/opnsense/plugins/commit/69499ffc80c2a8819000bb3feca826065925d388
