### ISSUE TITLE
security/acme-client: Automation Not Uploading Certificates to Hashicorp Vault

### ISSUE THREAD

**Issue by tstoco** [opnsense/plugins#3525]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
When trying to use the OPNsense ACME Client feature to upload Let's Encrypt certificates to Hashicorp Vault, it needed to be fixed.

The challenge started when the automation began to fail because it could not find the VAULT_TOKEN as an environment variable.
At first, it seemed easy to fix since, according to the sparse documentation on how to set environment variables in OPNsense, in System>Settings>Tunables, when a value is set without a parent, it would become an env variable. However, it did not work.
Another suggestion from a user in the [OPNsense forum](https://forum.opnsense.org/index.php?topic=21443.0&ref=blog.infoitech.co.uk) was to set the variable in /usr/local/opnsense/service/conf/configd.conf. It did not work either.

**To Reproduce**

1. Go to 'Services>ACME Client>Automations>Add'
2. Use the option 'Upload ACME certificates to Vault for Redistribution'
3. Save & add as automation in a certificate.
4. Renew the certificate and check the logs or Vault.

**Fix**
[I have fixed the issue and wrote a blog post describing the fix.](https://blog.infoitech.co.uk/opnsense-bugfix-acme-plugin-upload-to-vault/#1-opnsense-acme-plugin-form)

Not sure if my approach fixing the issue was correct, but I hope that a fix is achieved in future releases. :smile: 

Thanks for the great work developing this software. :+1: 

**Environment**

Type | opnsense |  
-- | -- | --
Version | 23.7 |  
Architecture | amd64 |  
Commit | b35678139

os-acme-client (installed) | 3.18 | 725KiB | 3 | OPNsense | ACME Client
-- | -- | -- | -- | -- | --

**Comment by fraenki** [comment]
Thanks for looking into this. If I understand you correctly, then the primary bug is the use of `sed -z` in [vault.sh](https://github.com/acmesh-official/acme.sh/blob/master/deploy/vault.sh). Please report it to the [upstream acme.sh project](https://github.com/acmesh-official/acme.sh/issues). Or if possible submit a pull request to them that fixes this issue, this usually speeds up the process. :)

Once acme.sh has accepted a fix and has released it in a new version, we can continue here.

**Comment by nurtext** [comment]
@tstoco Did you already reported the bug to the acme upstream project?

**Comment by tstoco** [comment]
> @tstoco Did you already report the bug to the acme upstream project?

No, but I will be reviewing if it got fixed soon.

Regards.

**Comment by themarek** [comment]
I created a pull request for https://github.com/acmesh-official/acme.sh/pull/5159 and hope it will get merged soon.
@tstoco I changed your solution a little; it doesn't preserve the backslash of the \n. Thank you for the great write-up of the problem and the solution!

**Comment by themarek** [comment]
The [changes](https://github.com/acmesh-official/acme.sh/pull/5159) in [acme.sh were merged](https://github.com/acmesh-official/acme.sh/releases/tag/3.0.8)and are now available in opnsense. I created a [pull request](https://github.com/opnsense/plugins/pull/4270) with the remaining changes to fix the issues as described in the blog of @tstoco.
