### ISSUE TITLE
Add Wireguard restart button instead of having to disable/enable to powercycle a wireguard interface.

### ISSUE THREAD

**Issue by satrapes** [opnsense/plugins#3532]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [*] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [*] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [*] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
When I change something to my Wireguard configuration that needs a restart I can only disable the Wireguard interface and then enable it. If I am connected from a remote location this means that after disabling the Wireguard interface I am locked out of the device I was remoting into thus making it impossible to make changes remotely, unless you have a separate way to connect to the same remote host.

**Describe the solution you'd like**
I would like an atomic restart button instead of having to do 2 separate actions (disable and re-enable) on the wireguard interface. This would ensure that unless I messed up the configuration that I would still be able to access the Wireguard tunnel.

**Describe alternatives you've considered**
A workaround would be to always have 2 wireguard connections enabled so that if you disable the one you can still access through the other one but this does not feel like a robust solution.

**Additional context**

**Comment by AdSchellevis** [comment]
The new plugin shows different endpoints in the "System: Diagnostics: Services" menu, similar to OpenVPN. Closing this for that reason.
