### ISSUE TITLE
ddclient OPNsense backend: Add new account class for single call URL Update for ipv4 and ipv6

### ISSUE THREAD

**Issue by bringha1** [opnsense/plugins#3535]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [ X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [ X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [ X] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
The new ddclient OPNsense backend allows already a lot of different providers with different protocols and mechanisms. However there is one white spot class of providers which require update of ipv4 and ipv6 in one single URL. Example for this is provider [Ionos](https://www.ionos.de/hilfe/domains/ip-adresse-konfigurieren/dynamisches-dns-ddns-einrichten-bei-company-name/).
The Update URL has the form:

https://ipv4.api.hosting.ionos.com/dns/v1/dyndns?q=NDFjZmM3YmVjYjQzNDRhMTkxMzliZDAwYzA2OGU3NzEuU2FvNlhuR2U4UmtxNGdiQzlMN19TLWpZanM4LWZBdGsxX2Ixa2FFUmRFWUp4Z1pmR3NWOVFpUjZYZGQ5TTZ5QjBIZkxSRFAyN2lzeHhCRWNuNVpSU0E&ipv4=&ipv6=

**Describe the solution you'd like**
While most of the URL elements can be already provided via the current ddclient config GUI version, the current checkip logic of the backend implementation allows only either ipv4 OR ipv6 per call.

To facilitate general support for single URL IP updates, the feature request suggests to extend the current account mechanism to

- Add variables for ipv4 and ipv6 addresses
- extend checkip to read both address variables in one call (at least optional, dependent of 'check IP method' value)
- add additional protocol in GUI for 'single URL update'-service provider
- add 'check IP method' with something like Interface[IPv4+IPv6]

**Describe alternatives you've considered**
Note that a similar feature request has been accepted for ddclient recently and saw a very first draft implementation from the new maintainer.

**Additional context**

**Comment by AdSchellevis** [comment]
It does sound a bit odd you are required to update both at the same time, these are separate records. Don't want to discourage anyone on working on this, but if you do use this service, I would certainly try if updating one by one doesn't just work. 

Another implementation for ionos (https://github.com/lazaroblanc/IONOS-DynDNS/blob/main/README.md) at least seems to suggest you can just update one or the other.

**Comment by bringha1** [comment]
Well - we can indeed discuss about the single URL concept Ionos has chosen for their dyndns service.  I personally also see some major disadvantages but it is what it is.

 I had lengthy discussion with their customer service what needs to be done to have a valid A AND AAAA record at the same time (which is the normal case for dual stack end users) . - It turned out that this is NOT possible to be achieved via separate calls for IPv4 and IPv6. If you update the A record and try then to get an AAAA record with a subsequent URL for ipv6, the formerly updated A record disappears again. You end up with either or. They could not offer a solution except the described one doing the update in ONE call (which is proven to work for Fritz!Box). Starting a discussion with their technical folks how to do different was not successful. It is an irony that Ionos is one of the biggest dual stack ISP provider in Germany though ...

There is an indication in the comments of the ddclient feature request  that there seem to be more providers doing the updates with one URL only so there might arise an interest beyond Ionos only. This was the reason that I suggested to provide the basic mechanisms generically. 

Doing the update with subsequent calls is also subject of some (for me minor) oddities: Eg. desec generates some hiccups by throttling the second call to the next update interval so that there is a delay of one interval between Ipv4 and IPv6 updates.

**Comment by AdSchellevis** [comment]
It might be worth checking if https://github.com/lazaroblanc/IONOS-DynDNS does function as one should expect as it seems to be using a different endpoint, but that's just a tip, I'm not planning to work on this anyway.

**Comment by twoellert** [comment]
As a quick info: ddclient has a code change in the pipe which works with IONOS (IPv4+IPv6). Just tested it today and commented on two necessary fixes they still need to do.

https://github.com/ddclient/ddclient/pull/556

Input variables are simply an API key as provided by IONOS as "password" in the ddclient config file.

I also checked the latest ddclient plugin v1.14 which comes with opnsense 23.7.1_3. A "Custom POST" type was added there but IONOS relies on a GET request. POST gives an error there.

When that merge on the ddclient GitHub is done I hope that the new version of the ddclient plugin will quickly find its way into the next opnsense release since right now I cannot update my office opnsense anymore since I need that IONOS dynamic DNS update for our office VPN.

**Comment by Starkstromkonsument** [comment]
I have the same problem with INWX. They require this URL-Format to be used:

`https://dyndns.inwx.com/nic/update?myip=<ipaddr>&myipv6=<ip6addr>`

If you try to update `https://dyndns.inwx.com/nic/update?myip=<ipaddr>` or `https://dyndns.inwx.com/nic/update?myipv6=<ip6addr>` the other one gets messed up (IPv4 gets set to 127.0.0.1 if you update IPv6 only and IPv6 is deleted if you update IPv4 only).

This is the same problem as discussed in https://github.com/opnsense/plugins/issues/1611 prior to the rewrite of the plugin.

**Comment by Starkstromkonsument** [comment]
I just noticed, this Issue is a duplicate of https://github.com/opnsense/plugins/issues/3233
