### ISSUE TITLE
www/nginx: Support proxy_timeout 0; for stream configurations

### ISSUE THREAD

**Issue by Stibila** [opnsense/plugins#3538]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
Default nginx proxy timeout value of 10 minutes can be a bit much for a lot of usecases. It would be great to have this value configurable.

https://nginx.org/en/docs/stream/ngx_stream_proxy_module.html#proxy_timeout

**Describe the solution you'd like**
An input field in the stream config that takes an integer for proxy_timeout and sets it in the config if not empty.

**Describe alternatives you've considered**
I was unable to find an alternative solution.

**Comment by kulikov-a** [comment]
Hi.
It seems easy to add, and i can even try adding it to https://github.com/opnsense/plugins/pull/3678 request before the maintainer starts reviewing, just a question: what is the purpose of setting this to `0`, because it will instantly close the connection?
