### ISSUE TITLE
ddclient custom post:  custom URL is getting mangled

### ISSUE THREAD

**Issue by joecoolio** [opnsense/plugins#3540]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
Porkbun has a custom API that is required to do DDNS against their hosts.  I built a script that's housed on an internal server that accepts a custom URL and then builds the appropriate API calls.  This was used in the legacy plugin and is running fine.  In the new plugin, when trying to use the Custom POST functionality, my URL is getting changed:
My "server" value:
http://10.1.104.12/porkbun_ddns.php?domain=__HOSTNAME__&hosts=ipv4&ip=__MYIP__

What is sent:
SENDING: GET //10.1.104.12/porkbun_ddns.php?domain=__hostname__&hosts=ipv4&ip=__myip__/nic/update?system=dyndns&hostname=myhostname.com&myip=1xx.xxx.xxx.xxx HTTP/1.1

Full config:
Service: Custom
Protocol: custom POST
Server: http://10.1.104.12/porkbun_ddns.php?domain=__HOSTNAME__&hosts=ipv4&ip=__MYIP__
Username: none <-- the actual word "none" because a value here appears to be required even though I don't use authentication
Password: none
Wildcard: unchecked
Hostname(s): myhostname.com
Check ip method: dyndns
Interface to monitor: WAN
Force SSL: unchecked

This is on OPNsense 23.7.1_3-amd64 and this is my first time trying to use the new POST options.

**To Reproduce**
1. Set it up like above
2. See error

**Expected behavior**
I believe the "server" value should go through untouched with the variables added in.

**Environment**
OPNsense 23.7.1_3-amd64
FreeBSD 13.2-RELEASE-p2
OpenSSL 1.1.1v 1 Aug 2023

**Comment by joecoolio** [comment]
One more thing after looking at the plugin code.  The log file is telling me this:
 WARNING: file /usr/local/etc/ddclient.conf, line 11: Invalid Value for keyword 'protocol' = 'post'

It looks like protocol should = 'postapi' in order for the URL to fall into the proper code block.  /usr/local/etc/ddclient.conf has:
use=cmd, cmd="/usr/local/opnsense/scripts/ddclient/checkip -i vtnet1 -t 0 -s dyndns -timeout 10"
protocol=**_post_**, \
server= ...

**Comment by fichtner** [comment]
> WARNING: file /usr/local/etc/ddclient.conf, line 11: Invalid Value for keyword 'protocol' = 'post'

ddclient.conf shouldn't be read, especially not by ddclient script when the OPNsense (native) backend is used.

**Comment by joecoolio** [comment]
I removed the legacy plugin, switched the backend from ddclient to opnsense, and upgraded to v23.7.3.  Somewhere in there this is resolved.  So this is now working just fine and this issue can be closed.
