### ISSUE TITLE
FRR - Routing Issue - Redistribute Static/Kernel Routes

### ISSUE THREAD

**Issue by ChristopherZender** [opnsense/plugins#3543]
OPNsense is running on Hetzner Cloud with Version 23.7.1_3
Hetzner cloud routing technology is based on layer 3 only.

The local routes to the private networks are installed as /xx static routes on a hetzner router in the same network x.x.x.1.

The IP address configuration of the network adapters in the opnsense are configured as /32, the gateways are configured as far gateway.

Static Routes correctly installed into Kernel / System, but there is no reditribute via OSPF to other neighbors any more.

FRR Version 8.5.2

Configuration FRR: 

![image](https://github.com/opnsense/plugins/assets/44568234/b6fb7d1a-c696-444f-a6d4-c0e95cd64b7e)

Routing Table:
![image](https://github.com/opnsense/plugins/assets/44568234/42f007ff-87c2-47cd-b0a5-cbd3d13d9c65)

OSPF Routing Table:
- only /32 interfaces ip "routes" are redistributed

![image](https://github.com/opnsense/plugins/assets/44568234/94cb4ba3-c1f1-4dbf-b090-f699f0bb289a)

Testings:

- delete configuration of (static, kernel, connected routes)
- delete services interfaces from frr config only neighbors interfaces + static routes
- set prefix list / route map

Logs:

- can't find any usefull log entrys for this problem

**Comment by joachimtingvold** [comment]
If it only affects redistribution of static routes (i.e. redistribution of connected routes works), it might be same underlying problem as in #3520 .

**Comment by bimbar** [comment]
You should open this using the template, or it is probably going to be ignored.
