### ISSUE TITLE
os-iperf TypeError on failed iPerf3 causes browser not to show anything

### ISSUE THREAD

**Issue by Zerreth** [opnsense/plugins#3545]
**Describe the bug**
If iperf fails to complete for some reason, some variables are undefined causing the browser not to show any running iperf instances.

**To Reproduce**
1. Install iPerf3 plugin & `pkg install rubygem-rexml` to get iPerf working.
2. Start an Instance. (the first one after a clean boot always shows properly)
3. Run iPerf3 on client and try to connect to OPNSense router but try to specify the MTU. e.g:
`iperf3 -c 10.0.0.1 --port 5201 -P 2 -O 1 --time 10 --window '4096k' --set-mss 8960`
4. Receive error in teminal:
`iperf3: error - unable to set TCP/SCTP MSS: Invalid argument`
5. iPerf3 plugin UI in browser is now empty and "Create Instance" doesn't **_seem_** to do anything.
6. Look in browser dev console and see TypeError:
`start.timestamp is undefined`
7. Using VNC/Terminal to connect to OPNSense, verify the iperf process is running:
`pgrep iperf`
8. See that processes are actually started when pressing the Create Instance button, but fail to ever be shown in the UI because of the above error fails whilst trying to render the results on the webpage.

**Expected behavior**
A result showing the reason why that instance failed. Also should still show new instances being fired up.

**Screenshots**
![terminal](https://github.com/opnsense/plugins/assets/20321245/57a8534f-ee54-4274-9b56-bdbd7ea13cf6)
![firefox console](https://github.com/opnsense/plugins/assets/20321245/1ada07f9-a20c-4014-96d3-1d8962c891a4)
![start is undefined](https://github.com/opnsense/plugins/assets/20321245/62e6447c-eb02-40dc-90c6-5fcb50684f1e)

**Environment**
VM running on UNRAID
OPNsense 23.7.1_3-amd64
FreeBSD 13.2-RELEASE-p2
OpenSSL 1.1.1v 1 Aug 2023
CPU AMD 5600G
Network Intel® Intel X710-T4L
Firefox / Chrome

**Comment by brandonk10** [comment]
Seeing the same when a test has not completed or has failed.  Below json shows both a failure, without the 'start' object, and the beginning of a fully completed test, where it is present.  May also be worth noting that the result is an array on a failure and an object on success.  It looks like this may have changed since the issue was opened, the failure now is in the initialization for 'start.connected'

```javascript
	{  
			"start_time": "2024-01-11 21:02:28 -0500",
			"interface": "ix0",
			"port": 46542,
			"result": [
				-1,
				{
					"error": "timeout"
				}
			]
		},
		{
			"start_time": "2024-01-11 21:07:08 -0500",
			"interface": "ix0",
			"port": 21665,
			"result": {
				"start": {
					"connected": [
						{
							"socket": 5,
							"local_host": "10.72.0.1",
							"local_port": 21665,
							"remote_host": "10.72.0.100",
							"remote_port": 38298
						},
	...
```
