### ISSUE TITLE
Add logging for os-wireguard

### ISSUE THREAD

**Issue by loudar** [opnsense/plugins#3547]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
When trying to debug Wireguard connections it is incredibly frustrating to do so.

**Describe the solution you'd like**
I would love a panel / tab for the Wireguard plugin that lets me see things like "Attempted connection" or whatever to be able to somehow trace where the issue could be.

**Describe alternatives you've considered**
None, because this is specific to Wireguard.

**Comment by mimugmail** [comment]
Wireguard itself doesnt log anything

**Comment by loudar** [comment]
Would it be possible to build custom logging/debugging for this (e.g. checking connections, displaying error states)? Is there a good alternative that is better debuggable?

**Comment by mimugmail** [comment]
OpenVPN works best

**Comment by loudar** [comment]
Thanks for the tip! Will try ;)

**Comment by loudar** [comment]
Closed accidentally.
