### ISSUE TITLE
Python dependencies for ddclient_opn.py

### ISSUE THREAD

**Issue by gglockner** [opnsense/plugins#3548]
I'm working to add AWS Route53 support for ddclient_opn.py. My test code is working, and I want to start on integrating with ddclient_opn.py. I have avoided the heavyweight AWS boto library, but I still need a function to compute the AWS signature version 4 Authentication hash. My test code currently works with either of these packages:

- [aws-requests-auth](https://github.com/DavidMuller/aws-requests-auth), which uses a nonstandard open source license that only appears to require that the copyright notice is included
- [requests-auth-aws-sigv4](https://github.com/andrewjroth/requests-auth-aws-sigv4), which uses the Apache 2.0 license

My questions:
1. Which library better fits the license requirements of OPNsense?
2. What is the best way to package this dependent library? The most Pythonic way is to install it into site-python, but I could include it in the dns/ddclient/src/opnsense/scripts/ddclient/lib/account subdirectory so that it doesn't need to be installed separately.

Note that I'm not looking for suggestions to build my own hashing library; there is no reason to 'reinvent the wheel' when these two libraries already do exactly what is required to call an AWS API via the [Python Requests](https://requests.readthedocs.io) package.

**Comment by fichtner** [comment]
@gglockner Thanks for working on this! Any library from FreeBSD ports is ok. Let me check tomorrow about the boto packages as I know these are built some time during the build process anyway, but not sure if they end up in the packages set currently (cloudinit maybe?) and how heavy they really are.


Cheers,
Franco

**Comment by gglockner** [comment]
@fichtner Thanks! It looks like both boto3 and aws-requests-auth are both available via FreeBSD ports. A quick search does show other OPNsense features use these libraries, so I'll reconsider rewriting with boto3. That's all the info I need for now; I will close this issue.

**Comment by fichtner** [comment]
It is pretty heavy but I'm ok with it, packages are online already indeed :)

# pkg install py39-boto3
Updating OPNsense repository catalogue...
OPNsense repository is up to date.
All repositories are up to date.
Updating database digests format: 100%
The following 4 package(s) will be affected (of 0 checked):

```
New packages to be INSTALLED:
	py39-boto3: 1.28.3
	py39-botocore: 1.31.3
	py39-jmespath: 1.0.1
	py39-s3transfer: 0.6.1

Number of packages to be installed: 4

The process will require 86 MiB more space.
6 MiB to be downloaded.
```


Cheers,
Franco
