### ISSUE TITLE
net/wireguard - remove wg-quick dependency and drop go support

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/plugins#3555]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**

With FreeBSD 13.2 including wieguard by default, the `wireguard-go` implementation is not really usable anymore and given the focus of wireguard is aimed at kernel support anyway, this might be a good moment to ditch `wireguard-go` support.

The advantage is when we do this, it would be relatively easy to lower wireguard's footprint making it easier to include it in `core` at some point in time.

Looking at what the current rc implementation is doing, it seems rather trivial to only use the `wg` command from base.  
A sample excerpt from some random input on my test box looks like this:

```
ifconfig wg create name wg0
wg setconf wg0 /usr/local/etc/wireguard/wg0.conf  <<<< remove Address and rc events
ifconfig wg0 10.213.0.0/24 alias
ifconfig wg0 mtu 1420
ifconfig wg0 up
route -q -n add -inet 10.213.0.2/32 -interface wg0
```

**Describe the solution you'd like**

Simplify the plugin, to ease future core inclusion. While there it should also be easily doable to only restart the changed tunnels in stead of a full reconfigure (similar to OpenVPN instances).

**Describe alternatives you've considered**

None, just opening a discussion.

**Comment by fichtner** [comment]
We can drop the go client in 24.1 which also avoids using the wireguard-kmod package then. I just removed if_wg from modules to retain the state of 23.1. I don’t think we have to rush this. The go client does have benefits in edge cases and proper removal deadline (roadmap).

**Comment by AdSchellevis** [comment]
As these edge cases die eventually anyway and 13.2 came with the module preinstalled, personally I found this a good opportunity to cleanup the plugin and get rid of the go variant. It's only stretching pain in my humble opinion.

**Comment by mimugmail** [comment]
I think getting rid of wg-quick would be biggest win for all :)

**Comment by AdSchellevis** [comment]
Doesn't look too complicated, I do need to test the outcome on my test environment, but I've made a start in https://github.com/opnsense/plugins/pull/3556. With a bit of extra effort we can make this more usable in a short time span, which likely outweighs the benefit of being able to support the edge-cases for a bit longer.... 

Each instance is presented as a separate entity in the services now,  only downside is that I currently can not tell it it's active or not (no pid attached to check).

**Comment by AdSchellevis** [comment]
check
