### ISSUE TITLE
dns/ddclient: supporting IPv6 prefixes in native backend

### ISSUE THREAD

**Issue by kevinchalet** [opnsense/plugins#3558]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**

Some providers - like dynv6.net - support assigning a static IPv6 suffix to a host (e.g `::aaaa:aaaa:aaaa:aaaa`) and make the IPv6 prefix dynamically configurable via the API. It's an extremely convenient feature that avoids having to install a DynDNS client on each machine (each having to update its own record).

**Describe the solution you'd like**

That would be awesome if OPNsense's native ddclient backend supported the `ipv6prefix` parameter (in this case, I'd assume the prefix would need to be resolved from the selected LAN interface, rather than from an external service).

Here's the docs for dynv6: https://dynv6.com/docs/apis.

**Describe alternatives you've considered**

N/A

**Additional context**

https://twitter.com/kevin_chalet/status/1692614974110142682
https://twitter.com/dennis_schroed/status/1692863779569049954

**Comment by b1ggi** [comment]
would be a great addition

**Comment by Tschak77** [comment]
good point I vote for this feature too

**Comment by fichtner** [comment]
I'm not entirely clear if this is a feature request for us (implemented in ddclient) or a feature request for a feature in ddclient (not implemented in ddclient) to be used from our side in which case I'd have to tag this "upstream".

**Comment by kevinchalet** [comment]
@fichtner I'm not an expert, but I thought the dynamic DNS plugin had a native backend that didn't depend on ddclient (from the docs: "With ddlient developments sunsetting [[*](https://github.com/ddclient/ddclient/issues/528)] we decided to offer an alternative written in Python"). If such feature was added to the native backend, it wouldn't need to be implemented upstream, right?

**Comment by fichtner** [comment]
Let me change the subject then. The +1's aren't really helping make this clear. Thanks!

**Comment by fichtner** [comment]
True, adding the backend option was a necessity after ddclient went EoL for a while and now it's a bit problematic ;)

**Comment by kevinchalet** [comment]
@fichtner looks like @OPNsense-bot was a bit overzealous on this one as the thread is still quite active. Any chance you could reopen it? 😃

**Comment by Commifreak** [comment]
+1

What about providers without a direct prefix support? Wouldnt it be a nice idea to support dynamic hosts for address updates? So the dyndns client could send the full, current IP from a dynamic host to cloudflare as an example?
