### ISSUE TITLE
web-proxy: about remote black lists

### ISSUE THREAD

**Issue by evbevz** [opnsense/plugins#356]
According to #352 : maybe it make sense to move out remote black lists from web-proxy to standalone proxy plugin and add ability to link lists to users and groups?
We can make it.

**Comment by fichtner** [comment]
Would rather merge web-proxy-useracl into core as it has no dependencies? User/group is really useful :)

**Comment by evbevz** [comment]
Not every user needs it. Proxy configuration is already monstrous for an ordinary user. Do you want to increase the complexity even more?
I think, the better way is to go in opposite direction: move out all filtering features from proxy general configuration module to proxy-plugins.

**Comment by mimugmail** [comment]
Hm, but for business it's really easy (right now) ... Sophos e.g. supports a profile mode for proxy. You can setup whole instances for users/groups/ipranges. I can't be complex enough 👍

**Comment by fabianfrz** [comment]
I would also prefer the solution of @fichtner. If the code does not add new dependencies, it could be in core as well. A plugin makes sense if it adds a new dependency or it does not logically fit into core which is not the case here as the proxy is already in core.
