### ISSUE TITLE
dns/ddclient: Timestamp of Updated Record Does Not Get Recorded Properly with Native Backend

### ISSUE THREAD

**Issue by drinn** [opnsense/plugins#3560]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X] The title contains the plugin to which this issue belongs

**Describe the bug**
Using the new ddclient native backend with duckdns, it appears that the IP is getting updated successfully (thank you for the new feature!) according to the logs, but the UI does not appear to update the last successful time that it was updated.

For my particular instance, the logs at /var/log/ddclient/latest.log shows that my IP was updated on:

2023-08-23T09:25:39

But the UI under Services -> Dynamic DNS -> Settings shows it was last "Updated" at:

1969-12-31T18:00:00

**Expected behavior**
The Updated timestamp to match when the last successful update was made.

**Environment**
OPNsense 23.7.2

**Comment by fichtner** [comment]
Looks ok on my end. Timestamp is read as "0" for you it seems.

    # cat /var/tmp/ddclient_opn.status

**Comment by drinn** [comment]
I checked /var/tmp/ddclient_opn.status and it has the proper mtime timestamp.

I checked again in a private browsing window and the timestamp does appear to be correct in the UI. I'm guessing it was some kind of cache/refresh issue on my part. Sorry for the false alarm! Closing this out.

**Comment by fichtner** [comment]
Ok no problem. :)
