### ISSUE TITLE
net/haproxy: Haproxy startup errors are silently ignored in the frontend

### ISSUE THREAD

**Issue by taxilian** [opnsense/plugins#3562]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
First, this should replace #3385 which is the same issue but due to not following the template was marked low priority; however, this should in my opinion be considered a fairly high priority issue.

The problem is that if there are errors during startup for haproxy they will be silently ignored from the web interface -- the service will not start but there will be no indication on the web interface of why it did not start. The error will show up in the logs and it will show up on the console if you start haproxy on the command line, but that is not always easy.

These errors will not show up during a config file check because the config file is actually valid, it's just not able to start for whatever reason -- the two most common that I've hit are when something else is listening on a port it wants or if it was using an IP address which has been removed from the system.

This issue has been around for a very long time -- I have hit it at least 5 or 6 times, it took me a long time to figure out what was actually going on to where I could troubleshoot it relatively quickly despite the issue with the frontend.

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**
1. Add a public service which uses either an IP address that doesn't belong to the system or else tries to bind to a port which is already in use. There are doubtless many other easy ways to reproduce the issue, but these are the easiest
2. Attempt to start haproxy with the web GUI -- it will not start, but the config file check will succeed.

**Expected behavior**

There should be an error message surfaced somewhere (preferably on the web interface in response to trying to start the service, but even if it just showed up as a crash log that would be better than nothing.

**Comment by FizykPSX** [comment]
I can confirm, when I set a virtual ip registered in interfaces as https_frontent listening interface HAProxy service immediately died.

**Comment by fraenki** [comment]
There's a small number of errors that the HAProxy config test cannot identify. An invalid Listen IP is probably the most famous example. I've misconfigured this too several times, so I feel your pain. ;-)

However, there is no way to capture the output of the "start" command and pass it to the GUI. And as a result there is no way to show/handle these errors in the GUI. At least I am not aware of any way to do this. :-/

**Comment by taxilian** [comment]
Okay, so we either need a command that can be run which will attempt to bind all ports, fully start up, and then immediately stop (to use instead of or in addition to the current config test) or else a way to check for and get errors back from the start script; that sound like a good definition of the problem?

I can spend some time looking into this, but I want to make sure I'm trying to figure out the right thing and that it would be used if I take the time to do it =]

**Comment by ivoruetsche** [comment]
Hi guys

I straggling with the same issue, we have an IP Range via a PPPoE connected provider, the modem is in bridge mode. I can't bring up the haproxy, witch binds to one of the public IP.

Because I never worked before with the HA Proxy on opnsense, i'm not sure, is this the problem or is there something else. I can't find any entries in a log file which points me to any problem. Just "/usr/local/etc/rc.d/haproxy: WARNING: failed to start haproxy" is not much. Where can I find more details about the "why"?

thanks a lot
Ivo

**Comment by fraenki** [comment]
> Okay, so we either need a command that can be run which will attempt to bind all ports, fully start up, and then immediately stop (to use instead of or in addition to the current config test) or else a way to check for and get errors back from the start script

In theory yes, that would be a hacky way to simulate the error. ;) However, this cannot be used in real world setups. Because you cannot successfully bind to the IP/port if it is currently in use, e.g. if HAProxy is currently running. So in order to successfully perform this IP/port validation, HAProxy need to be stopped. I don't think it is acceptable to stop the service just to perform a validation.

**Comment by fraenki** [comment]
> I straggling with the same issue, we have an IP Range via a PPPoE connected provider, the modem is in bridge mode. I can't bring up the haproxy, witch binds to one of the public IP.

I think this is unrelated to the topic we're discussing here. It would be better to discuss your issue in the [forum](https://forum.opnsense.org/) instead.

**Comment by ivoruetsche** [comment]
> > I straggling with the same issue, we have an IP Range via a PPPoE connected provider, the modem is in bridge mode. I can't bring up the haproxy, witch binds to one of the public IP.
> 
> I think this is unrelated to the topic we're discussing here. It would be better to discuss your issue in the [forum](https://forum.opnsense.org/) instead.

Well, we use also virtual IP's on the public range (sorry forgot to wrote about), so is the problem because the virt. IP's?

**Comment by taxilian** [comment]
> > Okay, so we either need a command that can be run which will attempt to bind all ports, fully start up, and then immediately stop (to use instead of or in addition to the current config test) or else a way to check for and get errors back from the start script
> 
> In theory yes, that would be a hacky way to simulate the error. ;) However, this cannot be used in real world setups. Because you cannot successfully bind to the IP/port if it is currently in use, e.g. if HAProxy is currently running. So in order to successfully perform this IP/port validation, HAProxy need to be stopped. I don't think it is acceptable to stop the service just to perform a validation.

That is a very good point; we're back to figuring out how to pull the information out of the logs somehow and/or figuring out why they aren't getting picked up.
