### ISSUE TITLE
Add AgentX support to LLDPD

### ISSUE THREAD

**Issue by sorano** [opnsense/plugins#3563]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
LLDPd is compiled with support for the SNMP subagent, but the option to activate it is not visible in webui.
From lldpd -h:
-x       Enable SNMP subagent.

By using the subagent LLDP neighbours will be visible via SNMP if you enable the AgentX support in NET-SNMP which can be benificial for NMS for example.

**Describe the solution you'd like**
A checkbox in webui to enable SNMP subagent option ( -x flag to lldpd binary ).

**Comment by sorano** [comment]
@mimugmail I'll ping you in this since you created the LLDP plugin. Hope you don't mind.

**Comment by choopm** [comment]
I added `-x` to lldpd_flags in `/usr/local/opnsense/service/templates/OPNsense/Lldpd/lldpd` on my machine until this is implemented. Keep in mind you have to enable `Add AgentX Support` for Services/Net-SNMP.

```
{% if helpers.exists('OPNsense.lldpd.general.enabled') and OPNsense.lldpd.general.enabled == '1' %}
lldpd_enable="YES"
lldpd_flags="{% if helpers.exists('OPNsense.lldpd.general.cdp') and OPNsense.lldpd.general.cdp == '1' %}-c{% endif %}{% if helpers.exists('OPNsense.lldpd.general.fdp') and OPNsense.lldpd.general.fdp == '1' %} -f{% endif %}{% if helpers.exists('OPNsense.lldpd.general.edp') and OPNsense.lldpd.general.edp == '1' %} -e{% endif %}{% if helpers.exists('OPNsense.lldpd.general.sonmp') and OPNsense.lldpd.general.sonmp == '1' %} -s{% endif %}{% if helpers.exists('OPNsense.lldpd.general.interface') and OPNsense.lldpd.general.interface != '' %} -I {{ OPNsense.lldpd.general.interface }}{% endif %} -M 4 -x"
{% else %}
lldpd_enable="NO"
{% endif %}
```

It works fine:

```bash
choopm ~ % snmpwalk -v2c -c public 192.168.0.250 .1.0.8802.1.1.2.1.3.4.0
iso.0.8802.1.1.2.1.3.4.0 = STRING: " FreeBSD 13.1-RELEASE-p8 FreeBSD 13.1-RELEASE-p8 stable/23.1-n250461-cf0d42d1ca7 SMP amd64"
```

**Comment by sorano** [comment]
Yeah I've been doing the same cheat 😉 but it would be nice to have it enabled via the official way.

**Comment by TotalGriffLock** [comment]
I would like to do this, if you can reopen the issue I can do a PR for it. It would be very useful for me in my job and is simple to implement!

**Comment by fichtner** [comment]
Sure, here you go.

**Comment by sorano** [comment]
Bad bot 🤖

**Comment by fichtner** [comment]
whoops :D
