### ISSUE TITLE
os-wireguard -- Version 2.0 does not properly configure IPv6 tunnel addresses and routes

### ISSUE THREAD

**Issue by rfrederick** [opnsense/plugins#3571]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
After updating os-wireguard to version 2.0 as part of updating to OPNsense 23.7.2, configuration of IPv6 tunnel addresses and IPv6 routes fails on wireguard service start with the following wireguard log entries:
`/usr/local/opnsense/scripts/Wireguard/wg-service-control.php: The command '/sbin/ifconfig 'wg1' '<tunnelIPv6Address>/64' alias' returned exit code '1', the output was 'ifconfig: <tunnelIPv6Address>/64: bad value (width too large)'`
`/usr/local/opnsense/scripts/Wireguard/wg-service-control.php: The command '/sbin/route -q -n add -'inet6 ' '<routeIPv6Address>' -interface 'wg1'' returned exit code '64', the output was 'route: bad keyword: inet6 route: usage: route [-46dnqtv] command [[modifiers] args]'`

**Environment**
OPNsense 23.7.2 (amd64, OpenSSL).
os-wireguard 2.0

**Comment by fichtner** [comment]
Likely https://github.com/opnsense/plugins/commit/a5131fe214ed30429cc829ecbf241495913b5443

**Comment by kevinchalet** [comment]
@fichtner I can confirm the patch fixes this issue 👍🏻

**Comment by fichtner** [comment]
Thanks, I’ll hotfix tonight.

**Comment by rfrederick** [comment]
I've found an additional regression and have created the following pull request to remedy it: https://github.com/opnsense/plugins/pull/3572

**Comment by AdSchellevis** [comment]
@rfrederick can you double check? `$ipproto` is either `inet` or `inet6` in which case it needs to prefix the `-` there.

**Comment by rfrederick** [comment]
@AdSchellevis I twas just able to test the command on a vanilla FreeBSD system, and it appears that the trailing space (`-'inet6 '` within `/sbin/route -q -n add -'inet6 ' '<routeIPv6Address>' -interface 'wg1'` ) is the issue.

**Comment by rfrederick** [comment]
I closed my previous pull request since the issue is not with the leading dash. My apologies for being hasty on that.

**Comment by kevinchalet** [comment]
@rfrederick could that be caused by these two lines?

https://github.com/opnsense/plugins/blob/20533c665138a3c97ee2aaf881f482d1bb4e7f8b/net/wireguard/src/opnsense/scripts/Wireguard/wg-service-control.php#L70

https://github.com/opnsense/plugins/blob/20533c665138a3c97ee2aaf881f482d1bb4e7f8b/net/wireguard/src/opnsense/scripts/Wireguard/wg-service-control.php#L90

**Comment by fichtner** [comment]
Yeah both trailing spaces in the double quotes are definitely not good.

**Comment by rfrederick** [comment]
@kevinchalet I believe what I'm experiencing is likely caused by line 70.

**Comment by fichtner** [comment]
@rfrederick you can open a PR and we will handle it in the morning. Already getting a bit late for work ;)

**Comment by rfrederick** [comment]
@fichtner Will do. I'll get one open to remove the trailing spaces on lines 70 and 90.

**Comment by rfrederick** [comment]
Pull request is now open at https://github.com/opnsense/plugins/pull/3573
