### ISSUE TITLE
Wazuh plugin issue

### ISSUE THREAD

**Issue by L1ghtn1ng** [opnsense/plugins#3577]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
Do not have the wazuh plugin be enabled by default on install. It has not been setup, so during the install it throws an error. 

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**
On a clean system that has not had the plugin installed before, install it and you will see the error in the output. 

**Expected behavior**
No error in the install

**Screenshots**

**Relevant log files**
If applicable, information from log files supporting your claim.

**Additional context**

**Environment**
Software version used and hardware type if relevant.
e.g.:

OPNsense 23.7.3

**Comment by fichtner** [comment]
> On a clean system that has not had the plugin installed before, install it and you will see the error in the output.

To avoid this being labeled support and glossed over: mind sharing the error?

**Comment by L1ghtn1ng** [comment]
While looking at the logs I found another issue which is also included in this output https://pastebin.com/7gUsuA84

**Comment by L1ghtn1ng** [comment]
But the error when installing is reloading template opnsense/wazuhagent: Exacute error
