### ISSUE TITLE
dns/ddclient: show IP and Sync-Time Issue

### ISSUE THREAD

**Issue by xpd1000** [opnsense/plugins#3578]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [ x ] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [ x ] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [ x ] The title contains the plugin to which this issue belongs

OPNsense 23.7.1_3-amd64
FreeBSD 13.2-RELEASE-p2
OpenSSL 1.1.1v 1 Aug 2023

Hallo keine Ahnung, ob ich das so richtig mache, aber mir ist ein Problem in der Anzeige im Dynamischen DNS: Einstellungen aufgefallen.
Dort wird in der aktuellen Version (OPNsense 23.7.1_3-amd64) bei neu hinzugefügten DDNS kein Wert mehr unter [Current IP] und [Aktualisiert] angezeigt.
Ein DDNS-Eintrag den ich so vor 3 Monaten angelegt habe steht weiter drin mit IP & Zeit vom letzten sync stimmt welche aktuelle ist.
Die Synchronisierung funktioniert auch bei dem neuen Eintrag der vor 3 Stunden angelegt wurde, nur die Info fehlt.
Analog habe ich es auch auf einer weiten FW getestet mit gleichem Ergebnis.

Hello, I have no idea if I'm doing this correctly, but I noticed a problem in the display in Dynamic DNS: Settings.
In the current version (OPNsense 23.7.1_3-amd64) no value is displayed under [Current IP] and [Updated] for newly added DDNS.
A DDNS entry that I created 3 months ago is still there with the IP & time from the last sync, which is the current one.
The synchronization also works for the new entry that was created 3 hours ago, only the information is missing.
I also tested it on a wide FW with the same result.

![2023-09-06 14_49_46-Clipboard](https://github.com/opnsense/plugins/assets/29287252/35ffccf8-d938-4266-9f1a-a296e280dc6a)

**Comment by xpd1000** [comment]
![2023-09-06 14_49_46-Clipboard](https://github.com/opnsense/plugins/assets/29287252/afa819db-1094-4417-98f5-bae5d31fe192)

**Comment by fichtner** [comment]
Hi @xpd1000,

Die aktuelle Version ist 23.7.3. Sollte der Fehler weiter bestehen bitte das Log File prüfen. Ich nehme einfach an der Dienst kann nicht aktualisiert werden.


Grüsse
Franco

**Comment by frikisama** [comment]
This bug is still present in 23.7.6.

The client updates the address and works fine in general, but the interface doesn't show neither the currently set IP ("Current IP") nor the last sync time ("Updated").
