### ISSUE TITLE
os-firewall plug in reporting values even if they are not yet applied

### ISSUE THREAD

**Issue by roblatour** [opnsense/plugins#3581]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
os-firewall plug in reporting rule enabled/disabled values even if they are not yet applied

As an example: 
If a firewall - automation - filter - rule exists and it is enabled
and the user has changed it to be disabled via the opnsense UI or via an api call but has not yet applied that change
the api os-firewall plug in is reporting that rule as disabled (even though it has not been applied).

**To Reproduce**
1. Go to firewall - automation - filter
2. create a rule and ensure it is disabled, click apply
3. using an api call, query the rule - it should (correctly) show as disabled
4. manually enable the rule (but do not apply the change)
5.  using an api call, query the rule - it will show as enabled (even though the change has not yet been applied).

**Expected behavior**
the api call should report the enabled/disabled status of the rule that is in effect (not just pending an apply)

**Screenshots**
n/a

**Relevant log files**
n/a

**Additional context**
n/a

**Environment**
OPNsense 23.7.3
amd64FreeBSD 13.2
RELEASE-p2
OpenSSL 1.1.1v 1 Aug 2023

**Comment by fichtner** [comment]
Hi Rob,

The API works on the configuration (config.xml) so a change is reflected by the next API fetch of the configuration. There are other APIs for monitoring/diagnostics which can show running configuration, but there is no model of "pending changes" or "masking" of non-applied settings. The firewall GUI works in the same way.


Cheers,
Franco

**Comment by roblatour** [comment]
Thanks for the explanation Franco.

However, respectfully, while that may be how it works, it is not perhaps how it should work.   

At least with the GUI for the Firewall Interface rules when a change is made but has not yet been applied it is evident that it will not take effect until after you click the apply button.   The same is not the case, for changes via the api (as described above) nor is it the case on the GUI for the Firewall Automation rules (i.e. for the GUI - Firewall - Automation rules; i.e. if a rule is changed, there is no reminder on GUI - Firewall - Automation screen that there is a pending change as is the case with the GUI - Firewall - Interface rules scrren.  While this last point in itself may not a bug, it is an inconsistency which may be worth looking at.

Also, as an aside, in the documentation https://docs.opnsense.org/development/api/plugins/firewall.html the API call 
Post - Firewall - Filter - Apply is not documented in the chart near the top of the page, but is used in the savepoint_example.py example near the bottom of the page, and does work fine.  Also, an api call to /api/firewall/filter/getRule/ with a uuid specified does work and is very handy but is also undocumented at the link above.

Regardless, back to the original post, if this is not considered a bug, you may want to consider it a feature request - i.e. if a rule is changed its state - pending or applied (i.e. in effect in production)- be retrievable via the api ( /api/firewall/filter/getRule/uuid ) as well.

In any case, thank you Franco for all your work on this project, it is a great tool and very much appreciated.

I hope to post a little github project that further shows the strength of the api shortly.

Rob

**Comment by AdSchellevis** [comment]
> Also, an api call to /api/firewall/filter/getRule/ with a uuid specified does work and is very handy but is also undocumented at the link above.

it’s generic functionality, works the same for all “grid” components as documented in https://docs.opnsense.org/development/examples/using_grids.html

It’s quite easy to contribute to the documentation, just start with a pull request… there’s always room for improvement.

Given most of this is generic, it doesn’t make sense to try to “detect” which rules are modified and which aren’t as this would be highly application specific and only drives further away from consistency. The inconsistency is mostly between legacy components and new mvc ones, only one way to fix that, get rid of the old code….. which is what we are working on…. 

We have written quite some pages about this journey and how the new architecture works, most can be found in our documentation.

**Comment by mimugmail** [comment]
Usually the api caller should track if they were also applied yet
