### ISSUE TITLE
dns/ddclient - adopt code to support domeneshop for ddns

### ISSUE THREAD

**Issue by byeskille** [opnsense/plugins#3585]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [ x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [ x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [ x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
It is hard to find a working setup for updating ddns with the provider Domeneshop/domene.shop with existing set of configuration profiles. Their API is described here: [https://api.domeneshop.no/docs/#tag/ddns/paths/~1dyndns~1update/get](https://api.domeneshop.no/docs/#tag/ddns/paths/~1dyndns~1update/get)

**Describe the solution you'd like**
There seems to be working code in the original ddclient codebase.
See PR [https://github.com/ddclient/ddclient/pull/478](https://github.com/ddclient/ddclient/pull/478)
Suggest the code be implemented also in the opnsense version of ddclient.

**Describe alternatives you've considered**
The new custom provider with GET support might be possible to use, but quick testing seem to interpret 204 repsonses from the Domeneshop API as errors and not sucess.

**Comment by propagandalf** [comment]
Support for Domeneshop service in ddclient/ddclient has been good for a year. Why has it been left out of the OPNsense ddclient?

Did you manage to get the Cusomt GET working?

**Comment by sudnam** [comment]
@propagandalf FYI In the latest version of OPNsense the custom GET for Domeneshop works as expected, I have been using it for a month or two now without issues.

**Comment by propagandalf** [comment]
@sudnam Can you provide an example? I tried a straight forward version but not getting it to update at Domeneshop, however it says in SERVICES: DYNAMIC DNS: SETTINGS that it was.  

I did wait more than 5 minutes between attempts. Log:
WARNING: Wait at least 5 minutes between update attempts.	
WARNING: last updated <never> but last attempt on Sun Dec 18 13:51:33 2023 failed.	
WARNING: skipping update of "myDomain" from <nothing> to "myip".

**Comment by fichtner** [comment]
This was addressed inm the native backend btw....
