### ISSUE TITLE
[Plugin: Wireguard] plugin should auto-restart on config change, or offer a button to do so

### ISSUE THREAD

**Issue by issmirnov** [opnsense/plugins#3592]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
I am setting up a road warrior wireguard setup on Opnsense. 

Despite making changes, my clients were not connecting.

After an accidental restart of the service, everything worked. I realized that my changes were not going live until the service restarted. This was confusing and unexpected behavior.

**To Reproduce**
1. Set up wireguard
2. Make some changes
3. Observe changes are not live until a manual "disable" + "enable" loop through the "General" tab.

**Expected behavior**
Wireguard should auto-restart on saved config changes, or offer a banner like Opensense does for the firewall rules indicating that the changes are not live until the service is restarted.

**Additional context**
This one ate up a decent chunk of my time, and I solved my issue by accident. I imagine many other users spend too much time mucking around with keys, when instead all they need to do is restart the plugin.

I am very thankful for Opnsense, and appreciate everything that the devs do. I hope that this is an easy tweak that can make this incredible offering even more user friendly!

**Environment**

OPNsense 23.1.11_2-amd64FreeBSD 13.1-RELEASE-p8OpenSSL 1.1.1u 30 May 2023

**Comment by issmirnov** [comment]
Small bucket of other feature requests: happy to make a separate issue for each

1. The tabs "General", "Local" (etc) should be URL encoded, otherwise when the page is refreshed the tab resets to the first one
2. When adding new endpoints, there should be an option to auto add it to the local server (otherwise this step is easy to miss)
3. Add a tab for wg logs output, to facilitate debugging complex connections and where the packets stop.

Again, thanks for a great system!

**Comment by AdSchellevis** [comment]
upgrade? (https://docs.opnsense.org/releases/CE_23.7.html)

**Comment by issmirnov** [comment]
Ah, yes! Read the patch notes and I think this should be a huge help. I'll schedule an upgrade.

Thank you - closing this one for now, will re-open with any 23.7+ specific issues.

Appreciate it!
