### ISSUE TITLE
security/acme-client: add DNS API support for DNSExit

### ISSUE THREAD

**Issue by myradon** [opnsense/plugins#3601]
Since 2 months official Acme.sh has support for method [DNS API support for DNSExit.](https://github.com/acmesh-official/acme.sh/blob/master/dnsapi/dns_dnsexit.sh) Is it possible to upgrade this Plugin with official Acme.sh so we have support for DNS Exit? Thanks in advance!

**Comment by fraenki** [comment]
Fixed in https://github.com/opnsense/plugins/pull/3732.
