### ISSUE TITLE
Add a plugin for (or at least a port of) security/tailscale

### ISSUE THREAD

**Issue by noseshimself** [opnsense/plugins#3604]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
OPNsense is including a number of VPN/mesh options but is ignoring the currently best available solution Tailscale.

Right now the only widely used mesh VPN/overlay network/soft SDN I have found in large environments was Tailscale. Installing and maintaining it (it is actively developed with a lot of attractive features like mulvad VPN integration) is a bit of a nightmare because it requires golang so compiling it yourself from ports is time and resource consuming.

Please consider adding a plugin for it or at least add the package to the OPNSense repository.

**Describe the solution you'd like**
Right now the only widely used mesh VPN/overlay network/soft SDN I have found in large environments was Tailscale. Installing and maintaining it (it is actively developed with a lot of attractive features like mulvad VPN integration) is a bit of a nightmare because it requires golang so compiling it yourself from ports is time and resource consuming.

Please consider adding a plugin for it or at least add the package to the OPNSense repository. Adding the Port "headscale" might be a good idea, too, although it is lacking all the additional services that make Tailscale interesting.

**Describe alternatives you've considered**
Right now I'm adding it from ports but upgrading is cumbersome.

**Comment by noseshimself** [comment]
Why did a search using the search field not find  that entry? Proves that adding the package name to the subject header is helpful.

**Comment by AdSchellevis** [comment]
likely because it was asked at their end 🙂
