### ISSUE TITLE
misc/theme-cicada: in 23.7.6 anything with drop down menu disappeared

### ISSUE THREAD

**Issue by R4toLoko** [opnsense/plugins#3616]
**Describe the bug**

Firewall Live log no longer displays the filters and the templates I had saved.
I have just updated it with the latest update so this is a bug introduced with the update:

OPNsense 23.7.6-amd64
FreeBSD 13.2-RELEASE-p3
OpenSSL 1.1.1w 11 Sep 2023

**To Reproduce**

1. Go to 'Firewall'
2. Click on 'Log Files'
3. Click on  'Live view'

**Expected behavior**

All the filters options and the templates I have created and was working just fine should be there but everything disappeared.
You can see the gif below, it is logging things just fine and the time is right too.

**Screenshots**

![Peek 2023-10-12 15-54](https://github.com/opnsense/core/assets/35049512/6c3ddcef-cf5b-45e7-b4d8-1b9ed52dec68)

**Relevant log files**

Gif above, data is being logged just fine, general and plain view looks correct.

**Additional context**

N/A other than it has been running fine for yearS with S and this is the first bug I am aware of.
I have been exploring the firewall and its logs a lot to block IoT, everything was perfectly fine prior to the update.

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.7.6-amd64
FreeBSD 13.2-RELEASE-p3
OpenSSL 1.1.1w 11 Sep 2023

Intel(R) Core(TM) i5-4210U CPU ( Proxmox)

**Comment by fichtner** [comment]
Something very odd here. I fixed the obvious visibility issue with the drop down and will hotfix now... c9f3c7b79205bb

**Comment by R4toLoko** [comment]
> Something very odd here. I fixed the obvious visibility issue with the drop down and will hotfix now... [c9f3c7b](https://github.com/opnsense/plugins/commit/c9f3c7b79205bb9f98fc92e49978ee53753cd27d)

Thank you for looking into it, will check the update within a few days.

**Comment by x3r00r** [comment]
im using vicuna theme and have the same problem after upgrade 23.7.5 to 23.7.6 - drop down menus are broken. how to fix ?

**Comment by R4toLoko** [comment]
Fixed with os-theme-cicada 1.34_2, everything is back to normal.
Thank you legends

**Comment by hashbanged** [comment]
Thank you @fichtner for the super fast work and all you do. The 1.34_2 patch has my dropdowns visible again. 

I don't know that the following qualifies the issue for reopening, but the patched removal of `position: absolute` on the `dropdown-menu` class forces the menu content container to push other elements down (Figure 1). Reverting this one change prevents this (Figure 2), which I believe matches the previous behavior. Please note that I haven't tested this from a build change, and I may be missing something important.

![before](https://github.com/opnsense/plugins/assets/53536018/549199ab-2797-4362-a43e-257245e7893f)
**Figure 1.** The 1.34_2 patch removal of `position: absolute` pushes elements down when the menu is expanded.

![after](https://github.com/opnsense/plugins/assets/53536018/6236075d-e28a-4d24-be46-078fbec99750)
**Figure 2.** Adding absolute positioning to `.dropdown-menu` preserves the menu container height.

**Comment by fichtner** [comment]
See https://github.com/opnsense/plugins/commit/b276276aeb94c1d4914208712d133fe311c5d123 😊

**Comment by hashbanged** [comment]
Like magic. Thanks again.
