### ISSUE TITLE
security/acme-client: PowerDNS acme plugin problem

### ISSUE THREAD

**Issue by rodolfo160** [opnsense/plugins#3617]
I am using the acme plugin with opnsense and i've always have this problem

here is my log from my powerdns server:
Oct 12 11:03:32 dns pdns_server[853]: [webserver] 60415426-8785-40ec-93ff-d93e68b6aa41 Handling request "//api/v1/servers/localhost/zones"
Oct 12 11:03:32 dns pdns_server[853]: [webserver] 60415426-8785-40ec-93ff-d93e68b6aa41 No route found for "//api/v1/servers/localhost/zones"
Oct 12 11:03:32 dns pdns_server[853]: [webserver] 60415426-8785-40ec-93ff-d93e68b6aa41 Error result for "//api/v1/servers/localhost/zones": 404
Oct 12 11:03:32 dns pdns_server[853]: [webserver] 60415426-8785-40ec-93ff-d93e68b6aa41 192.168.100.1:52182 "GET //api/v1/servers/localhost/zones HTTP/1.1" 404 114

As you can see there's a double slash at the beginning and no record is added.

I have no slash at the end of my url in the conf section
![immagine](https://github.com/opnsense/plugins/assets/147173664/9142a4ed-79b5-4027-a570-32f636224a65)

to make it works i usually edit the dns_pdns.sh file and remove the initial slash from this string: "/api/v1/servers"

Am i the only one having this problem?

Opnsense and powerdns are both at their latest version

**Comment by JSuenram** [comment]
Happens for me too, but not always... me be 5 to 10 of nearly 100 Certs have this issue...

**Comment by fraenki** [comment]
> to make it works i usually edit the dns_pdns.sh file and remove the initial slash from this string: "/api/v1/servers"

I think you should report this issue to the upstream acme.sh project:
https://github.com/acmesh-official/acme.sh/issues
