### ISSUE TITLE
mail/postfix: trusted networks may be a CSV list field

### ISSUE THREAD

**Issue by fabianfrz** [opnsense/plugins#362]
![screenshot_20171106_175941](https://user-images.githubusercontent.com/3713914/32453362-447ff0aa-c31c-11e7-9dba-42b1321a7a5f.png)

The frontend will become a `select_multiple` with tokenize style, which allows new entries and the backend will only split and rejoin the values.

**Comment by mimugmail** [comment]
Will be in the next PR, thanks.
