### ISSUE TITLE
net-mgmt/zabbix-agent: Service is not beeing restarted during upgrade procedure

### ISSUE THREAD

**Issue by Starkstromkonsument** [opnsense/plugins#3623]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X] The title contains the plugin to which this issue belongs

**Describe the bug**
I upgraded OPNsense from version 23.7.5 to 23.7.6. This upgrade did not require a reboot. During the upgrade zabbix5-agent was upgraded: 5.0.37 -> 5.0.38. The service has not been restarted during the upgrade procedure though and version 5.0.37 was still running. This was reproducible on three OPNsense instances. Restarting the service manually solved the issue.

**To Reproduce**
1. Install OPNsense 23.7.5 with the plugin zabbix5-agent 5.0.37
2. Upgrade OPNsense to 23.7.6
3. Check logs of zabbix-agent
4. See error: version 5.0.37 is still running, although version 5.0.38 has been installed

**Expected behavior**
Automatic service restart during upgrade procedure, if OPNsense will not reboot after upgrade.

**Screenshots**
None.

**Relevant log files**
Services --> Zabbix Agent --> Log File

**Additional context**
None.

**Environment**
OPNsense 23.7.6-amd64
FreeBSD 13.2-RELEASE-p3
OpenSSL 1.1.1w  11 Sep 2023

**Comment by fichtner** [comment]
This is the intended behaviour.

Cheers,
Franco

**Comment by Starkstromkonsument** [comment]
Thank you for the feedback, but may I ask for the reasons for this being considered as the intended behavior?

I noticed this issue, because Zabbix announced several critical security issues on versions prior to 5.0.38 lately. I checked the installed versions on my OPNsense instances and was happy with it. I didn't notice, that OPNsense was still running the old versions of the agents in the first place. So I thought my systems were safe, but they weren't.

**Comment by fichtner** [comment]
Restarting based on packages (and indirect dependencies) is a non-trivial task. Furthermore restarting (and reconfiguring) may not be side effect free. If you want the behaviour rebooting after a release as a best practice makes sense. Restarting services manually can be useful, but is also hard to define: restart software or just apply (possible) fixes in the configuration.

Restarting a service seems simple, but once you start defining what should be done when it’s going to be much more.

At least as it is intended now new versions don’t taint smooth operation. If you start restarting you will have negative impacts of varying sorts (VPN disconnecting, DNS cache flushing, etc.).


Cheers,
Franco

**Comment by Starkstromkonsument** [comment]
Thank you for the explanation. I will close this and open a new issue in [opnsense/core](https://github.com/opnsense/core), to request an "always reboot after update" option in System: Firmware: Settings or a new cronjob command "Automatic firmware update (always reboot)".
