### ISSUE TITLE
net-mgmt/zabbix-proxy: Service is not beeing restarted during upgrade procedure

### ISSUE THREAD

**Issue by Starkstromkonsument** [opnsense/plugins#3624]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X] The title contains the plugin to which this issue belongs

**Describe the bug**
I upgraded OPNsense from version 23.7.5 to 23.7.6. This upgrade did not require a reboot. During the upgrade zabbix5-proxy was upgraded: 5.0.37 -> 5.0.38. The service has not been restarted during the upgrade procedure though and version 5.0.37 was still running. This was reproducible on three OPNsense instances. Restarting the service manually solved the issue.

**To Reproduce**
1. Install OPNsense 23.7.5 with the plugin zabbix5-proxy 5.0.37
2. Upgrade OPNsense to 23.7.6
3. Check logs of zabbix-proxy
4. See error: version 5.0.37 is still running, although version 5.0.38 has been installed

**Expected behavior**
Automatic service restart during upgrade procedure, if OPNsense will not reboot after upgrade.

**Screenshots**
None.

**Relevant log files**
Services --> Zabbix Proxy --> Log File

**Additional context**
The plugin Zabbix Agent has the same bug. Please check #3623 too.

**Environment**
OPNsense 23.7.6-amd64
FreeBSD 13.2-RELEASE-p3
OpenSSL 1.1.1w  11 Sep 2023

**Comment by fichtner** [comment]
See https://github.com/opnsense/plugins/issues/3623
