### ISSUE TITLE
os-frr: Often it doesn't add/remove neighbors or the config otherwise doesn't sync in UI vs vtysh

### ISSUE THREAD

**Issue by samip5** [opnsense/plugins#3625]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**

When adding or removing peers or otherwise changing config, it doesn't appear to apply the changes to frr.

**To Reproduce**
1. Have FRR with multiple peers running
2. Go to add more peers or remove existing
3. See that it will not reflect the config when you go to vtysh shell

**Expected behavior**

I would have expected it to fully be in sync with each other.

**Additional context**

I went to the shell and ran `vtysh -c "show running-config"`

**Environment**

OPNsense 23.7.5 (amd64, OpenSSL).
Intel® Atom C3758 (8C/8T)
Network Intel® X533
os-frr: 1.36

**Comment by mimugmail** [comment]
Do you click the small reload Button near the + where you add neighbors?

**Comment by samip5** [comment]
> Do you click the small reload Button near the + where you add neighbors?

Oh, facepalm. No I had not noticed it as it's so small. user error. :)

**Comment by mimugmail** [comment]
UX error, maybe it needs an update :)
