### ISSUE TITLE
net/zerotier: used address changes all the time

### ISSUE THREAD

**Issue by StrikerTwo** [opnsense/plugins#363]
I have a virtual IP of type "IP alias" bound to my WAN interface.
Zerotier seems to jump between the interface IP and the virtual IP. `zerotier-cli listpeers` called in a loop on another device shows this:
```
200 listpeers 5e96a8e284 78.47.80.xxx/54437;2074;872;1.00 62 1.2.4 LEAF
200 listpeers 5e96a8e284 - 63 1.2.4 LEAF
200 listpeers 5e96a8e284 78.47.80.xxx/54437;92;92;0.98 86 1.2.4 LEAF
200 listpeers 5e96a8e284 144.76.20.yyy/54437;30;30;1.00 79 1.2.4 LEAF
200 listpeers 5e96a8e284 144.76.20.yyy/54437;30;0;1.00 79 1.2.4 LEAF
200 listpeers 5e96a8e284 78.47.80.xxx/9993;32;32;1.00 62 1.2.4 LEAF
```

Note also the changed ports. This leads to a very unstable ZeroTier connection to the network behind the OPNsense box. Is there any way to nail the ZeroTier plugin to the interface's primary address? In the ZT local.conf I can only add interface prefixes, not IP addresses.

**Comment by StrikerTwo** [comment]
I added the virtual IP's network as a blacklist in the ZT local.conf. That seems to have done the trick so far.

**Comment by StrikerTwo** [comment]
Nope, it has not. Damn.

**Comment by dharrigan** [comment]
Hi,

I'll keep an eye on this one and see if I can reproduce locally.

-=david=-

**Comment by dharrigan** [comment]
I believe I have observed the issue. It appears that the information in /var/db/zerotier-one is reset (possibly the /var/db directory is cleaned?) I saw this when I've upgraded to 18.1 and my zerotier one address was lost as well. Looking at the directory, it appears that it's been re-initialized. I will run some checks and ask some questions to see what I can do.

-=david=-

**Comment by dharrigan** [comment]
I think I have the answer.

For the short term,

Please ensure that the following setting is *false* or *disabled*:

`System...Settings...Miscellaneous`

`/var RAM disk` `Use memory file system for /var`

For the long term, I'll do a patch that 

Zerotier stores its database in /var/db which if the above setting is enabled, will be lost on reboot. If you disable the setting, then /var will stored to disk and not lost on reboot.

A longer term fix will be coming shortly.

-=david=-

**Comment by StrikerTwo** [comment]
I don't think that was my issue exactly. I'm talking about IP addresses, not ZT addresses. And the flapping occurs randomly several times a day when the box is running, not only on reboots.

Also that setting has never been enabled on my system:
![image](https://user-images.githubusercontent.com/6770084/35687987-7140a010-0770-11e8-81dc-9119724b7d38.png)

**Comment by dharrigan** [comment]
I've never seen this happen for me, but I'll keep observing to see if it occurs.

When I have zerotier enabled on my router, the IP address is solid and remains so for weeks (in fact, I've never seen it change). I have ensured that the "Do Not Auto-Assign IPs" is ticked for the router node (on the zerotier portal) and self-assigned a static IP on the router to the interface.

-=david=-

**Comment by StrikerTwo** [comment]
It's not the IP address on the ZT interface. That remains static.

It's the external IP ZeroTier uses to connect to its peers and that is shown on my.zerotier.com or `zerotier-cli listpeers`
