### ISSUE TITLE
FRR: Can no longer match a prefix-list in a route-map

### ISSUE THREAD

**Issue by Slair1** [opnsense/plugins#3630]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X] The title contains the plugin to which this issue belongs

**Describe the bug**
No longer able to do a match ip address prefix-list myprefixlist under route-map. Receive this error in the log, and the running config does not show the match line:

`[VAKV3-NMY7B][EC 100663337] error processing configuration change: error [internal inconsistency] event [apply] operation [modify] xpath [/frr-route-map:lib/route-map[name='Redistribution']/entry[sequence='10']/match-condition[condition='ipv4-prefix-list']/rmap-match-condition/list-name]
`
**To Reproduce**
Just create a ip prefix-list and try adding a match statement to a route-map

**Expected behavior**
Running Config:
```
ip prefix-list myprefixlist seq 10 permit 100.64.0.0/10 le 32
route-map Redistribution permit 10
 match ip address prefix-list myprefixlist
```

**Screenshots**
Actual Running Config because of bug:

```
ip prefix-list myprefixlist seq 10 permit 100.64.0.0/10 le 32
route-map Redistribution permit 10
```
_Missing match statement..._

**Relevant log files**
`[VAKV3-NMY7B][EC 100663337] error processing configuration change: error [internal inconsistency] event [apply] operation [modify] xpath [/frr-route-map:lib/route-map[name='Redistribution']/entry[sequence='10']/match-condition[condition='ipv4-prefix-list']/rmap-match-condition/list-name]`

**Additional context**
FRR issue also created: https://github.com/FRRouting/frr/issues/14626
Community post with others having issue:
https://forum.opnsense.org/index.php?topic=36507.0

**Environment**
OPNsense 23.7.6
OS Version: FreeBSD: 13.2-RELEASE-p3
FRR Version: 8.5.3

**Comment by fichtner** [comment]
Hi, config file is correct but daemon interpretation is not? Did I get this right?

Thanks,
Franco

**Comment by Slair1** [comment]
@fichtner yes, i would say that is correct.  using vtysh produces no error messages when entering the commands.  However a show run shows the match statement is missing, and an error (see my original post) shows up in the log.

**Comment by fichtner** [comment]
Thanks, marking this upstream for now and subscribed to other issue. May have to move this to ports repo where the fix would live under the current assumption.


Cheers,
Franco

**Comment by Trapulo** [comment]
I have same problem after today's upgrade: route map results empty in frr config :(

**Comment by 2Rukus** [comment]
Not quite sure how to downgrade this package

[https://github.com/FRRouting/frr/issues/14626#issuecomment-1773492428](url)

**Comment by fichtner** [comment]
Ok, it appears that the workaround is easier than expected:

# opnsense-revert -r 23.7.5 libyang2

**Comment by fichtner** [comment]
A newer version of libyang seems to be out, not entirely sure if it was fixed though https://github.com/CESNET/libyang/releases/tag/v2.1.128

**Comment by 2Rukus** [comment]
I installed the new version on a backup opnsense router for testing and it seems to be working

**Comment by fichtner** [comment]
@2Rukus thanks for the help :)

I've also made a copy and it can be tested like so:

# opnsense-update -z libyang2


Cheers,
Franco

**Comment by Trapulo** [comment]
> Ok, it appears that the workaround is easier than expected:
> 
> ```
> # opnsense-revert -r 23.7.5 libyang2
> ```

I did run this, and also restarted OSPF service, but still nothing. Do I need a full router reboot or something else to apply?

**Comment by 2Rukus** [comment]
@Trapulo 
Did you try "service frr restart" ?

**Comment by Trapulo** [comment]
> Did you try "service frr restart" ?

Restarted frr from the GUI, still have the problem
maybe I miss something? I've a workaround so I can wait for the fix if it will be available in a short time.

**Comment by fichtner** [comment]
Maybe still wrong package version...

# pkg info | grep libyang2

**Comment by Trapulo** [comment]
2.1.111
running again the " opnsense-revert -r 23.7.5 libyang2" command, this is the version it selects. What's wrong?

**Comment by fichtner** [comment]
2.1.111 IS the bad version

"-r 23.7.5" has 2.1.80 and "-z" has 2.1.128 so you need to pay attention to whether opnsense-revert actually reinstalls something or fails for whatever reason

**Comment by Trapulo** [comment]
![Screenshot 2023-10-24 092230](https://github.com/opnsense/plugins/assets/5655057/e17613ba-aed1-4ada-ad8a-b40b6c2ac369)

**Comment by fichtner** [comment]
Whatever this is it's not the mirror:

https://pkg.opnsense.org/FreeBSD:13:amd64/23.7/MINT/23.7.5/latest/All/libyang2-2.1.80.pkg
