### ISSUE TITLE
dns/ddclient updates nsupdate.info provider despite cache and cmd confirming no update needed

### ISSUE THREAD

**Issue by Contik** [opnsense/plugins#3631]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
On newest OPNsense 23.7.6 `os-ddclient` 1.16 and `ddclient-devel` 3.10.0_7 seem to trigger a `dyndns2` address update against `ipv4.nsupdate.info` every update interval even if its own cache is confirming that the address last transmitted is unchanged from the address just checked. This results in `ddclient` triggering `nochg` ("no change") reports from the dynamic DNS service and - depending on its abuse policy - potentially blocking itself from sending future updates.

I recently upgraded OPNsense from 21.1 to 23.7.6, I do not know anymore which versions of `os-ddclient` and `ddclient-devel` I was using on that version. They did not exhibit this current behavior but I can't comment on when exactly this was introduced.

*This issue template suggest to try `opnsense-revert`, for both `opnsense-revert -r 22.1 os-ddclient` and `opnsense-revert -r 22.1 ddclient-devel` I received `[...] *.sig: Not Found failed`.*

**To Reproduce**
This config (screenshots from [Edit account menu](https://i.imgur.com/ZqagFBP.png) and [General settings menu](https://i.imgur.com/uFF9tlO.png)) generates a `/usr/local/etc/ddclient.conf` file like so:
```
syslog=yes                  # log update msgs to syslog
pid=/var/run/ddclient.pid   # record PID in file.
ssl=yes

use=cmd, cmd="/usr/local/opnsense/scripts/ddclient/checkip -t 1 -s nsupdate.info-ipv4 --timeout 10", \
protocol=dyndns2, \
server=ipv4.nsupdate.info, \
login=fully.qualified.domain.name, \
password=12P4aSw0rD \
fully.qualified.domain.name
```
Where `password=` is a rather simple 10-character string with only characters `[a-zA-Z0-9]` generated by `nsupdate.info` themselves, so no fancy password characters. Manually executing `cmd=` returns the same IP address that's already set and known at `nsupdate.info`.

Per [OPNsense forum topic 35897](https://forum.opnsense.org/index.php?topic=35897.0) by a helpful poster from September (where OP's issue turned out to be a password with special characters that prevented `ddclient` from ever seeing the last line in its config file) I've gone ahead and followed their steps for debugging:

- Stop service at `"Services: Dynamic DNS: Settings"`
- Confirm that `/var/run/ddclient.pid` doesn't exist anymore
- Remove cache file `/var/tmp/ddclient.cache`
- Run `ddclient -daemon=0 -debug -verbose -noquiet`

This forces an update attempt since `ddclient` detects no cache file, see [full output at pastebin.com/raw/bJ66Yy8e](https://pastebin.com/raw/bJ66Yy8e). It receives a `nochg` reply and creates a cache file `/var/tmp/ddclient.cache` like so:
```
## ddclient-3.10.0
## last updated at Fri Oct 20 00:05:28 2023 (1697753128)
atime=1697753128,backupmx=0,custom=0,host=fully.qualified.domain.name,ipv4=11.22.33.44,mtime=1697753128,mx=,script=/nic/update,static=0,status=good,status-ipv4=good,status-ipv6=noconnect,warned-min-error-interval=0,warned-min-interval=0,wildcard=0,wtime=0 fully.qualified.domain.name
```

What seems a bit odd is that in OPNsense web GUI I'm never seeing any content in `Current IP` nor `Updated` columns; I'm moderately sure that these fields were always populated with correct info prior to me recently upgrading from 21.1 to 23.7.6:
![OPNsense web GUI DynDNS accounts menu](https://i.imgur.com/fBqP5GP.png)

On consecutive attempts `ddclient` sees and uses the cache file as seen by the fact that verbose debug output contains this additional section:
```
=== cache ====
cache{fully.qualified.domain.name}{atime}      : 1697750554
cache{fully.qualified.domain.name}{backupmx}   : 0
cache{fully.qualified.domain.name}{custom}     : 0
cache{fully.qualified.domain.name}{host}       : fully.qualified.domain.name
cache{fully.qualified.domain.name}{ipv4}       : 11.22.33.44
cache{fully.qualified.domain.name}{mtime}      : 1697750554
cache{fully.qualified.domain.name}{mx}         : 
cache{fully.qualified.domain.name}{script}     : /nic/update
cache{fully.qualified.domain.name}{static}     : 0
cache{fully.qualified.domain.name}{status}     : good
cache{fully.qualified.domain.name}{status-ipv4} : good
cache{fully.qualified.domain.name}{status-ipv6} : noconnect
cache{fully.qualified.domain.name}{warned-min-error-interval} : 0
cache{fully.qualified.domain.name}{warned-min-interval} : 0
cache{fully.qualified.domain.name}{wildcard}   : 0
cache{fully.qualified.domain.name}{wtime}      : 30
```

The rest remains unchanged: `ddclient` attempts an update despite its cache and its own `cmd=` confirming that no update is needed, it receives a correct `nochg` response and goes one step closer to getting itself blocked from `nsupdate.info` for spamming unnecessary updates.

**Expected behavior**
A `ddclient` DynDNS address update only when local cache file content and `cmd=` execution result differ.

**Screenshots**
- [Accounts menu](https://i.imgur.com/fBqP5GP.png)
- [Edit account menu](https://i.imgur.com/ZqagFBP.png)
- [General settings menu](https://i.imgur.com/uFF9tlO.png)

**Relevant log files**
- [Full ddclient debug output, no cache exists](https://pastebin.com/raw/bJ66Yy8e)
- [Full ddclient debug output when a local cache file exists](https://pastebin.com/raw/yYSiskCK)

**Additional context**
N/a

**Environment**
- OPNsense 23.7.6
- `os-ddclient` 1.16
- `ddclient-devel` 3.10.0_7
- [AMD GX-412TC 2nd gen G-series system-on-chip [PDF]](https://www.amd.com/en/system/files?file=2017-06/g-series-soc-product-brief.pdf)
- [Intel I211-AT 1 GbE ethernet controller](https://ark.intel.com/content/www/us/en/ark/products/64404/intel-ethernet-controller-i211at.html)

**Comment by fichtner** [comment]
Hi,

This being the "ddclient" backend with dyndns2... have you tried the "native" backend if that works as expected? ddclient will have new releases soon but it was already found that some oddities may take a long time to fix or are not fixable at all on their side -- at least that was the view of the former maintainer who briefly caused the project to be end of life.

We've added the native Python backend for this reason and people have contributed a few nice things that ddclient cannot possibly do being perl and a "lightweight" daemon.

I would recommend recreating the account after changing the backend because the settings for both backends might slightly differ causing issues when run with the other backend unmodified.


Cheers,
Franco

**Comment by fichtner** [comment]
@Contik yay :)
