### ISSUE TITLE
WireGuard missing tabs

### ISSUE THREAD

**Issue by Joriempie** [opnsense/plugins#3632]
I've freshly installed OPNSense 23.7.4 on my machine. I'm trying to install Wireguard (os-wireguard) with version 2.3.

After enabling under: VPN > Wireguard and then check the box called: 'Enable WireGuard'. I'm missing tabs. For example 'Local'.

I've followed a few articles on the internet for example this one: https://docs.opnsense.org/manual/how-tos/wireguard-client.html. But it's still missing.

My Wireguard view:
![Screenshot 2023-10-20 135902](https://github.com/opnsense/plugins/assets/88492366/7175ca3b-7c19-470f-98e1-c4a1f2b48387)

Output plugin install:

> ***GOT REQUEST TO INSTALL***
> Currently running OPNsense 23.7.6 at Fri Oct 20 13:54:09 CEST 2023
> Updating OPNsense repository catalogue...
> OPNsense repository is up to date.
> All repositories are up to date.
> Checking integrity... done (0 conflicting)
> The following 2 package(s) will be affected (of 0 checked):
> 
> New packages to be INSTALLED:
> 	os-wireguard: 2.3
> 	wireguard-kmod: 0.0.20220615_1
> 
> Number of packages to be installed: 2
> [1/2] Installing wireguard-kmod-0.0.20220615_1...
> [1/2] Extracting wireguard-kmod-0.0.20220615_1: .... done
> [2/2] Installing os-wireguard-2.3...
> [2/2] Extracting os-wireguard-2.3: .......... done
> Stopping configd...done
> Starting configd.
> Reloading plugin configuration
> Configuring system logging...done.
> Reloading template OPNsense/Syslog: OK
> Reloading template OPNsense/Wireguard: OK
> =====
> Message from wireguard-kmod-0.0.20220615_1:
> 
> --
> At this time this code is new, unvetted, possibly buggy, and should be
> considered "experimental". It might contain security issues. We gladly
> welcome your testing and bug reports, but do keep in mind that this code
> is new, so some caution should be exercised at the moment for using it
> in mission critical environments.
> --
> ===>   NOTICE:
> 
> This port is deprecated; you may wish to reconsider installing it:
> 
> Only useful for FreeBSD 12 which is EoL soon.
> 
> It is scheduled to be removed on or after 2023-12-31.
> Checking integrity... done (0 conflicting)
> Nothing to do.
> ***DONE***

**Comment by fichtner** [comment]
The terminology in the plugin has been renamed to more closely match WireGuard upstream terminology:

Local -> Instances
Endpoints -> Peers

The documentation will be fixed soon: https://github.com/opnsense/docs/issues/504
