### ISSUE TITLE
can I ask somethin about https://forum.opnsense.org/ << see me as spam

### ISSUE THREAD

**Issue by venuscazz** [opnsense/plugins#3636]
**Important notices**
Our forum is located at https://forum.opnsense.org , please consider joining discussions there in stead of using GitHub for these matters.

Before you ask a new question, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.

Hi Who may concern about it.
Try to read everything about 2 day and may by i'm going wrong direction may someone can help me to visit forum to educate more OPNsense (cause i'm noob with FreeBSD) 
>>> https://forum.opnsense.org/index.php?action=register #or#  https://forum.opnsense.org
just first time i visit the site is show error in short version is error 5522 
sometime I use another direction like VPN or TOR yes already use but Just click register or second page of the forum error 5522 came up

Ps. may i miss something (clear cache yes! ; Flush DNS Yes! already do clear cache at sever :yes already do) 

Thnak you in advance and sorry of my English.
Best regards
Sutthipong s,

**Comment by AdSchellevis** [comment]
responded via mail
