### ISSUE TITLE
sysutils/nut - I would like to be able to configure the NUT on a web interface.

### ISSUE THREAD

**Issue by Joci78** [opnsense/plugins#3646]
**Is your feature request related to a problem? Please describe.**
Unfortunately, it is not possible to set the NUT on the web interface. In pFsense, it is possible to specify a custom configuration, which is not possible here. I really miss this.

**Describe the solution you'd like**
I would be perfectly satisfied with a solution like the one in pfsense. The config files can be parameterized separately from the web interface.

**Describe alternatives you've considered**
It would be possible to parameterize the shutdown of the firewall on the web interface.

**Comment by fichtner** [comment]
Just submit a PR. I won’t allow trashing authors over volunteer work that others (like you too perhaps) are not willing to do anyway.
