### ISSUE TITLE
os-frr: BGP extended-nexthop

### ISSUE THREAD

**Issue by J0n4t4n** [opnsense/plugins#3649]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
I am trying to advertise BGP routes between VyOS and OPNsense via BGP, over an IPv6-only connection.
IPv6 routes work fine, but VyOS doesn't seem to send out the IPv4 routes with the IPv6 nexthop, as OPNsense doesn't advertise extended-nexthop.
I have another BGP connection to a Kubernetes cluster, which seems to just advertise these routes anyways, so I assume the solution would be as easy as adding a toggle for setting the extended-nexthop attribute.

**Describe the solution you'd like**
I would like to have an input checkbox for a neighbor, to enable the "extended-nexthop" attribute in frr, thus advertising extended-nexthop capabilities to the peer, which frr supports just fine.
This also seems to already be a feature with pfSense, so adding this would bring more feature-parity for users that might be switching over to OPNsense.

**Describe alternatives you've considered**
Alternatively a dual stack connection could be used to advertise the IPv4 and IPv6 routes via their respective IP families.
This would work, but I'd prefer to keep the setup in OPNsense the same as I have in other routers and only use IPv6 addresses between the routers.

**Additional context**
pfSense reference: https://docs.netgate.com/pfsense/en/latest/packages/frr/bgp/config-neighbor.html#advanced-options (Advertise Capability)

FRR reference: https://docs.frrouting.org/en/latest/bgp.html#clicmd-neighbor-PEER-capability-extended-nexthop

**Comment by mimugmail** [comment]
Would you be available for testing when I build a devel plugin? A simple checkbox is quite easy, if you're motivated I can also show you how to contribute on your own

**Comment by J0n4t4n** [comment]
Sure, I'd be absolutely be willing to try doing it myself with some guidance on what needs to be done!

**Comment by dfr** [comment]
I came across this missing feature today while trying to use the FRR plugin to peer with a few DN42 nodes (mostly to learn a bit more about BGP).  It would be nice if this feature was exposed in OPNsense but in the short term, I will probably move my DN42 experiment to a separate router probably running BSDRP.
