### ISSUE TITLE
mail/postfix: Add syslog support

### ISSUE THREAD

**Issue by mimugmail** [opnsense/plugins#366]
Postfix primarily support logging via syslog facility. Any chance to activate mail and log to a file like mail.log? 
Think this would be done with some .inc but not really plugin-approved.

ATM I put for testing `syslog_facility = security` so everything is in system.log

**Comment by mimugmail** [comment]
Yep, I already found this but wasn't sure to hardcode this in since postfix is just a plugin.

**Comment by fabianfrz** [comment]
@mimugmail Maybe create it for more software than just postfix (log rspamd, amavisd-new, spamassassin, opensmtpd etc. to this file).

**Comment by mimugmail** [comment]
Yeah, but I'm not feeling to make such a decision, that's why I opened an issue :)
@AdSchellevis @fichtner opinions?

**Comment by fichtner** [comment]
Not yet. Will rework all syslog handling end of November. Let’s wait a bit...

**Comment by mimugmail** [comment]
@fichtner Motivated to look on this again? :) I don't want to release this plugin without proper logging ..

**Comment by fabianfrz** [comment]
@mimugmail why not - in this case I would not consider it as so problematic as the information exists on multiple places:
* a remote syslog server (if configured)
* the destination mail server which is responsible for the mails.
* maybe the firewall log
* other related logs (rspamd, clamav,...)

**Comment by mimugmail** [comment]
In Germany you have to keep logs for 6 months, If you want to run this in production this is a must. 

I dont want to push noisy Mail Log to my Syslog :)

**Comment by fichtner** [comment]
@mimugmail the remote logging is prepared, but needs fixing in the core. that stuff is pretty complicated, so please remind me again in a quiet moment. :)

**Comment by mimugmail** [comment]
A quiet moment between RC1 and RC2? ;)

**Comment by fichtner** [comment]
you know what I mean :P

**Comment by fichtner** [comment]
Maybe 5e560ac6 will do the trick.
