### ISSUE TITLE
net/wireguard: API breaking change in opnsense 23.7.8 (wireguard 2.5) release

### ISSUE THREAD

**Issue by parnic** [opnsense/plugins#3663]
- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
On OPNsense 23.7.7, a request to `/wireguard/client/addClient` returned an object that contained both the result ("saved") and the uuid of the just-created client. On OPNsense 23.7.8, the uuid is no longer returned, only the "result".

Previously:
```
{
    "result": "saved",
    "uuid": "1c78ed78-141a-4ea3-a21e-12291af7d654"
}
```

Now:
```
{
    "result": "saved"
}
```

API clients can retrieve the uuid by requesting the list of clients and finding the name+pubkey of the just-added client, but it would reduce necessary requests if addClient could return the uuid like it used to.

**To Reproduce**
1. POST to /api/wireguard/client/addClient with an appropriate body, e.g.: `{"client":{"name":"parnic","pubkey":"my-obviously-valid-pubkey","tunneladdress":"10.10.11.1/32"}}`
2. See response missing uuid

**Expected behavior**
The uuid of the just-added client is returned in order to be used with other APIs that require the uuid as a parameter.

**Environment**
OPNsense 23.7.8-amd64
FreeBSD 13.2-RELEASE-p5
OpenSSL 1.1.1w 11 Sep 2023
Intel(R) Xeon(R) Platinum 8375C CPU @ 2.90GHz (1 cores, 2 threads)

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/plugins/commit/47ccdcc078f7a58432a7cf1350ec9700863416cb should fix this.
