### ISSUE TITLE
os-ddclient - Support Linode as ddns provider

### ISSUE THREAD

**Issue by rfc4711** [opnsense/plugins#3671]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [ X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [ X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X ] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
The legacy plugin of dyndns was removed on 23.7, and the ddns plugin does not have a solution for the Linode cloud provider. 

**Describe the solution you'd like**
Add Linode as a DDNS provider to the list. I found this project on GitHub: https://gist.github.com/amoe/06cf6ffe66eec9efd0135b775cff0363 which may be of help. 

**Describe alternatives you've considered**
No alternatives are available as all my domains are hosted by Linode. This prevents me from upgrading to Opnsense 23.7.

**Comment by rfc4711** [comment]
I still cannot understand why os-dyndns plugin was depreciated. The os-ddclient in either legacy or Opnsense version is seriously limited in functionality and support of DDNS providers. It does not work for FreeDNS either.

**Comment by rfc4711** [comment]
I found this patch with the help of @amoe: https://sourceforge.net/p/ddclient/tractickets/23/ - A patch was submitted for ddclient 3.8 on source forge to add Linode as ddns provider.

**Comment by doktornotor** [comment]
> I still cannot understand why os-dyndns plugin was depreciated. The os-ddclient in either legacy or Opnsense version is seriously limited in functionality and support of DDNS providers. It does not work for FreeDNS either.

I'd hazard to say that it's because noone wants to maintain these things. It's a complete nightmare. Things breaking all the time due to changes made by dyndns providers, loads of those services are paid for and/or with no way to test them, people bugging you to add obscure providers noone ever heard about and that's just the start.

**Comment by rfc4711** [comment]
I would not think Linode as an obscure provider. Since there is no support neither on ddns or here, I am pretty much stuck on last the opnsense version supporting os-dyndns plugin. And I believe I am not the only one. 

on 23.1.11_2 ddns does not even show what IP address it is tracking or updating. I honestly can't say if my address changes that ddns will update it. 

The ddns project also lost its maintainer and was being put on life-support until re-write. Also taking into consideration that os-dyndns had support for so many more providers, I still stand to that I cannot understand the rationale for depreciating the plugin. At least it could have stayed as a legacy plugin without support until a suitable replacement for all the providers was found.

**Comment by fichtner** [comment]
> The ddns project also lost its maintainer and was being put on life-support until re-write.

While that was true it's back on track and 23.7.9 will add the latest version 3.11.1.

To be frank we see two things here:

1. Lack of DynDNS providers adding support into all available tools themselves.
2. Lack of DynDNS users ability to code and debug themselves.

It tells us that DynDNS is a niche technology for home users with all of its good and bad implications. It only takes that one user contributing, but everyone seems to be complaining why that contribution wasn't made or why it was broken (by the provider most likely). This is a never-ending story. I also agree that paid-only access is making it way harder to implement these things and keeping them up-to-date.


Cheers,
Franco

**Comment by rfc4711** [comment]
I agree with your points. If I could write code at that level, I would certainly contribute. However, reading Reddit posts and other forums, many OPNsense users are stuck on the OPNsense release having the dyndns-plugin since they use providers not supported on the os-ddclient plugin. 

While I do not know how much work would have been involved in keeping the legacy dyndns plugin as an unsupported plugin, I still believe that this could have been a solution for users like myself to bridge the gap until os-ddclient was providing the necessary support for more DNS providers.
