### ISSUE TITLE
[os-ddclient] Native backend fails updating ovh dynhost, keeps an invalid cache thereafeter

### ISSUE THREAD

**Issue by interj** [opnsense/plugins#3679]
- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
There are seemingly two problems affecting native backend:
* ddclient always fails with a `badsys` status - there's no other information about it in the ddclient log, syslog or anywhere else
* after a failed attempt local cache gets written (even though the dns record was never updated) and ddclient gives up on updating the ip - it's a very dangerous assumption that local cache is always correct

**Expected behavior**
Ddclient reliably updates a dynamic domain with ovh as a provider. 

**Relevant log files**
```
2023-11-20T17:25:34	Notice	ddclient	Account fbc56979-2194-4574-9146-3cd82fbc3ca1 [ovh - test] not modified
2023-11-20T17:25:34	Notice	ddclient	Account fbc56979-2194-4574-9146-3cd82fbc3ca1 [ovh - test] executing	
2023-11-20T17:25:29	Notice	ddclient	Flush dyndns status to disk	
2023-11-20T17:25:29	Notice	ddclient	Account fbc56979-2194-4574-9146-3cd82fbc3ca1 [ovh - test] updated	
2023-11-20T17:25:29	Notice	ddclient	Account fbc56979-2194-4574-9146-3cd82fbc3ca1 [ovh - test] set new ip *.*.*.*[badsys]	
2023-11-20T17:25:28	Notice	ddclient	Account fbc56979-2194-4574-9146-3cd82fbc3ca1 [ovh - test] executing
2023-11-20T17:25:28	Notice	ddclient	Account fbc56979-2194-4574-9146-3cd82fbc3ca1 [ovh - test] uses DynDNS2 for service
```

**Additional context**
Legacy ddclient never seemed to work well with the ovh service (usually it updated some ips then crashed), legacy dyndns worked most of the time. Native backend doesn't work at all.

**Environment**
OPNsense 23.7.8
os-ddclient 1.16_2

**Comment by AdSchellevis** [comment]
I'm not sure this is our end to be honest if the endpoint returns a 2XX http_status code (https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#successful_responses):

https://github.com/opnsense/plugins/blob/85e4a256df0936fd4f15dcf23b781c8d078d4994/dns/ddclient/src/opnsense/scripts/ddclient/lib/account/dyndns2.py#L101-L109

**Comment by fichtner** [comment]
https://github.com/ovh/docs/issues/3529

**Comment by interj** [comment]
I found this https://techforum.ewon.biz/thread-163-post-537.html after learning that `badsys` is just some substandard status returned by ovh dynhost. Adding `'system': 'dynds'` to `params` in the `dyndns2.py` makes it work.

**Comment by AdSchellevis** [comment]
the standard is rather old and messy indeed, personally I don't mind adding the result strings documented in https://help.dyn.com/wp-content/uploads/2014/09/flow.pdf , log them separately and skip the action.

**Comment by AdSchellevis** [comment]
funny note, the `badsys` exists in the flow, but not in the return codes document at the same origin https://help.dyn.com/remote-access-api/return-codes/

**Comment by interj** [comment]
For what it's worth I made a small PR that fixes ddclient updates for ovh dynhost. Doesn't consider a potential `badsys` response however.
