### ISSUE TITLE
Consolidation of BSNMPD

### ISSUE THREAD

**Issue by stevefxp1** [opnsense/plugins#3680]
I am running OPNsense 23.7.9 and trying to configure SNMP monitoring to my Zabbix proxy server. I have read alot of posts that point to a CLI version of snmpd, rather than using the plugin version.

I would like to see a consolidation of these into one plugin, so we can get access to all the SNMP information. Right now it looks like the plugin does not support BEGEMOT or PF MIBs, that the CLI version does support. This makes it quite complicated to get the right information from SNMP.

Happy to help work this through, as I have a test firewall I can pull apart to get this done.

**Comment by fichtner** [comment]
I‘m unsure how many years ago we removed bsnmpd/os-snmp and how his ties into your request since it hasn’t been around since then?

**Comment by stevefxp1** [comment]
@fichtner thank you for your response Franco. I am somewhat confused. If there is no support then why is there a plugin? Shouldnt the plugin be removed if there is no support?

**Comment by fichtner** [comment]
Again, os-snmp was bsnmpd and is no longer available. os-net-snmp is net-snmp. Though Bsdnmpd is still in FreeBSD base system but we no longer operate it.

**Comment by stevefxp1** [comment]
Ahhhh...now I understand. Ok that makes alot of sense. So now the question becomes does net-snmp support MIBs from BEGEMOT or PF, like BSNMPD did? I am trying to monitor OPNsense with SNMP via Zabbix, as well as using the Zabbix agent.

**Comment by doktornotor** [comment]
> So now the question becomes does net-snmp support MIBs from BEGEMOT or PF, like BSNMPD did? 

Negative, no such thing implemented in net-snmp.

**Comment by stevefxp1** [comment]
> > So now the question becomes does net-snmp support MIBs from BEGEMOT or PF, like BSNMPD did?
> 
> Negative, no such thing implemented in net-snmp.

Is that a programming issue or is there no way of providing support for those MIBs?

**Comment by doktornotor** [comment]
Yes, it's a programming issue as in there is no support for the pf MIBS in net-snmp, the code does not exist (upstream).

**Comment by stevefxp1** [comment]
> Yes, it's a programming issue as in there is no support for the pf MIBs in net-snmp, the code does not exist (upstream).

That is a shame. I'd love to manage OPNsense as an application platform, not just get typical server stats.
