### ISSUE TITLE
net/freeradius: make libdir in radiusd.conf flexible

### ISSUE THREAD

**Issue by mimugmail** [opnsense/plugins#369]
In radiusd.conf the libdir is bound to the current version:

`libdir = /usr/local/lib/freeradius-3.0.15`

So when adding radiusd.conf to templating this make is impossible to use when there will be 3.0.16.
Is there a standard/easy way to make this dynamic?

I tested 

`libdir = /usr/local/lib/freeradius-3*`

and it works fine. But unsure if this is good code quality. :) Ideas?

@fichtner @fabianfrz @AdSchellevis

**Comment by fabianfrz** [comment]
@mimugmail for me, this is OK - there is no way to query the current package information.

**Comment by fichtner** [comment]
Sure, if this works why not. I can also ask FreeBSD port maintainer to stop doing this lock-in because there can only be one freeradius version at a time installed anyway.

**Comment by mimugmail** [comment]
I'll stick with 3* ... thank you guys :)
