### ISSUE TITLE
Suricata Snort VRT Rules Vastly Out of Date

### ISSUE THREAD

**Issue by ilikenwf** [opnsense/plugins#3692]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [ ] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [ ] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [ ] The title contains the plugin to which this issue belongs

**Describe the bug**
The Suricata rules file for Snort VRT hasn't been updated in 3 years. Surely https://github.com/opnsense/plugins/commit/0c67e9db298649fba190d2fddbf69e7dd5c1923e is way out of date at this point? We're up to suricata version 6.0.15 and VRT's latest v2 and v3 rules are:

snortrules-snapshot-31470.tar.gz
and
snortrules-snapshot-2983.tar.gz

**Comment by firestormo** [comment]
use snortrules-snapshot-29200.tar.gz thats the latest that works and ive been using it for awhile

**Comment by ilikenwf** [comment]
Are you certain the newer v2 rules won't work? Our suricata version has been bumped several times since.

**Comment by firestormo** [comment]
That is the latest v2 rules, v3 rules don’t work and won’t work

On Dec 7, 2023, at 7:37 PM, ilikenwf ***@***.***> wrote:

﻿

Are you certain the newer v2 rules won't work? Our suricata version has been bumped several times since.

**Comment by doktornotor** [comment]
Snort v3 rules definitely do NOT work. What's exactly the issue here? You want the default bumped to 29200, or? I mean, it's user configurable after all.
