### ISSUE TITLE
dns/ddclient: Update for improved dnsexit provider

### ISSUE THREAD

**Issue by jortkoopmans** [opnsense/plugins#3693]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**

Fairly recently, the upstream dnsexit provider has been successfully added to OPNsense (and I'm using it :smile:), see collaboration; https://github.com/opnsense/plugins/issues/2900
However, I have subsequently contributed an update upstream (https://github.com/ddclient/ddclient/issues/575), with the following main features:
1. [feature] Adopt ipv4 and ipv6 simultaneously, depending on the desired IP addresses (automatically). 
2. [bugfix] Specifically for the OPNsense plugin, while it uses the modern `usev4` (and `usev6`) configuration which works for updating the IP, but does not work for caching (while it checked the old `use` for caching purposes). This resulted in continuous updates through the API, which is not desirable. A manual workaround was to rewrite the `usev4` to `use` (i.e. using old format), but this cannot be done through the UI (and needs to be reapplied after each OPNsense update I believe). Adopting the updated upstream fixes this caching issue.

**Describe the solution you'd like**
In fact there are 2 problems with 2 possible solutions mixed together here. Updating to support the full feature-set has my preference and solves both points above.
The maintainers are now doing a great job creating tagged releases again, please consider adopting https://github.com/ddclient/ddclient/releases/tag/v3.11.2

**Describe alternatives you've considered**
Alternatively, the caching issue (point 2 above), is perhaps fixed upstream through this issue: https://github.com/ddclient/ddclient/issues/590
In short; there was a bug in the caching system to allow legacy dns provider implementations to work with modern `usev4` / `usev6` config. Not sure whether that is applicable to the current OPNsense implementation, as they state it's a recent bug, the problem seems identical. While I have not tested this, this could address point 2. Either way, fixing only the bug (somehow) is the only alternative I would consider.
Note: it is highly likely that other dns providers relying on the old `use` method, encounter the same caching bug (i.e. not limited to dnsexit implementation).
Note2: This resolution is packaged in the same tagged release (v3.11.2), if adopting this tagged release is acceptable, it's not an alternative :stuck_out_tongue: 

**Additional context**
There is no breaking change in the plugin configuration, it should work as-is. This is typically what I'm using:
```
protocol=dnsexit2, \
login=bogus, \
password=REDACTEDMyAPIKey \
myredactedhost.example.com
```

**Comment by fichtner** [comment]
23.7.10 should have 3.11.2. We barely missed it in 23.7.9 and I’ve already updated the original FreeBSD port to 3.11.2 as well. Does this conclude your ticket?

cheers,
Franco

**Comment by fichtner** [comment]
@jortkoopmans great, and thanks for contributing to ddclient 👍
