### ISSUE TITLE
XMLRPC sync for plugins?

### ISSUE THREAD

**Issue by mimugmail** [opnsense/plugins#370]
Hi,

XMLRPC sync to HA machine would be good for FreeRADIUS and Postfix. Sure not for all plugins this makes sense (like monitoring plugins) but for the two would be cool.

How to add this function? Never did this before :)

**Comment by fichtner** [comment]
https://github.com/opnsense/core/blob/master/src/etc/inc/plugins.inc.d/squid.inc#L60 😊

**Comment by mimugmail** [comment]
Really that easy? Thanks :)
