### ISSUE TITLE
[os-bind] Bind throws an error if you only add a primary zone and no records

### ISSUE THREAD

**Issue by kashalls** [opnsense/plugins#3703]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
When installing os-bind for the first time, and setting up a primary zone with the defaults, saving will result in the application crashing and opnsense having a backend error.

`configd.py`:
```
error generating template OPNsense/Bind : Traceback (most recent call last): File "/usr/local/opnsense/service/modules/template.py", line 262, in _generate content = j2_page.render(cnf_data) File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render self.environment.handle_exception() File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception raise rewrite_traceback_stack(source=source) File "/usr/local/opnsense/service/templates/OPNsense/Bind/domain.db", line 8, in top-level template code {% for record in helpers.sortDictList(OPNsense.bind.record.records.record, 'name', 'type' ) %} File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 485, in getattr return getattr(obj, attribute) jinja2.exceptions.UndefinedError: 'collections.OrderedDict object' has no attribute 'records' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/local/opnsense/service/modules/template.py", line 328, in generate for filename in self._generate(template_name, create_directory): File "/usr/local/opnsense/service/modules/template.py", line 265, in _generate raise Exception("%s %s %s" % (module_name, template_filename, render_exception)) Exception: OPNsense/Bind OPNsense/Bind/domain.db 'collections.OrderedDict object' has no attribute 'records'
```

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**
1. Install os-bind
2. Click on 'Bind> Configuration'
3. Add primary zone with default settings.
4. Save

**Expected behavior**

The configuration should save regardless of records not being added.

**Screenshots**
![RZ87NT](https://github.com/opnsense/plugins/assets/17620516/35427afd-cd32-4a7c-9b8c-69681eecc1ab)
![PRStsh](https://github.com/opnsense/plugins/assets/17620516/767ed3d1-c02e-4232-919a-8f0aed27fd01)
All other settings are default.

**Relevant log files**
If applicable, information from log files supporting your claim.

**Additional context**

**Environment**
OPNsense 23.7.9 (amd64).

Plugins enabled:
![EMsCcn](https://github.com/opnsense/plugins/assets/17620516/cab317d9-1a14-43ff-8c2b-c459b6ac175d)

**Comment by kulikov-a** [comment]
primary zone shoud have at least one NS record i think

**Comment by kashalls** [comment]
> primary zone shoud have at least one NS record i think

Is this required to allow rfc2136 to be used?

**Comment by kulikov-a** [comment]
i think its required by rfc1035 for zone functioning ))
regardless of rfc2136

**Comment by kulikov-a** [comment]
NS-records should be moved to the primary zone model\form first then

**Comment by kulikov-a** [comment]
or...add NS from SOA MNAME if there is no NS records in zone (not entirely correct but at least a description could be added to MNAME  help text)
