### ISSUE TITLE
dns/ddclient: fix needed for dnsexit provider's json for hostnames updates

### ISSUE THREAD

**Issue by DiSHTiX** [opnsense/plugins#3712]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X] The title contains the plugin to which this issue belongs

**Describe the bug**
ddclient is using incorrect json command for hostname update only (eg.hostname.domain.publicvm.com) ,  when using updating the subdomain (domain.publicvm.com) it works fine because the correct  'domain' is referenced.
**publicvm.com** is one of DNSExit's free domains.

**ddclient: log file snippet**
_modified using **hostname.domain.publicvm.com** and IP **1.1.1.100** which i'll continue to use for clarity_
```
Notice | ddclient | FAILED: Server response: System Error - Fail to find UserID for hostname.domain.publicvm.com
Notice | ddclient | FAILED: System Error. Our system problem. May not be your problem. Contact our support if you got such error.
Notice | ddclient | INFO: Server Message: System Error - Fail to find UserID for hostname.domain.publicvm.com -- Server Details: no details received
Notice | ddclient | INFO: Status: error -- Message: System Error. Our system problem. May not be your problem. Contact our support if you got such error. 
Notice | ddclient | RECEIVE: {"code":6,"message":"System Error - Fail to find UserID for hostname.domain.publicvm.com"}
Notice | ddclient | SENDING: data="{\"update\":[{\"content\":\1.1.1.100\",\"name\":\"hostname.domain.publicvm.com\",\"ttl\":5,\"type\":\"A\"}],\"apikey\":\"xxxxxx\",\"domain\":\"hostname.domain.publicvm.com\"}" 
```

**To Reproduce**
1. Create an additional hostname within your domain on DNSExit
2. Configure ddclient to update the hostname IP
3. Save and click on update
4. Check the ddclient log
5. See error

**Snippet of the JSON reference** modified based on above example
from [dnsexit's API document](https://dnsexit.com/dns/dns-api/) for posting an update. 1. domain(current) 2. hostname
```
{
   "domain":"domain.publicvm.com",
   "update":{
      "type":"A",
      "name":"",             //name can be "domain.publicvm.com" instead (not required)
      "content":"1.1.1.100"  //content is the new IPv4 address of the domain
      "ttl":5                //ttl value is in minutes 480 = 6 hours
   }
}

{
   "domain":"domain.publicvm.com",
   "update":{
      "type":"A",
      "name":"hostname",     //hostname without domain
      "content":"1.1.1.100"  //content is the new IPv4 address of the domain
      "ttl":5                //ttl value is in minutes 480 = 6 hours
   }
}
```

**DNS Exit Support issue confirmation:**
```
From: DNS Exit Support 
Sent: Friday, December 15, 2023 at 11:48 PM
Subject: API issue: System Error - Fail to find UserID ::Free User

"domain\":\"hostname.domain.publicvm.com\"

Sure there is no domain hostname.domain.publicvm.com
That is hostname under domain domain.publicvm.com

Jack
DNS Exit
```

**Environment**
OPNsense latest stable with ddclient

@fichtner

**Comment by DiSHTiX** [comment]
Fichtner, 
thanks again for helping with resolving previous issues related to DNSexit.

I had this issue since before legacy (non API) was pulled from ddclient but only recently realized the issue therefore only logging this now. Luckily my other opnsense boxes havent changed IP in ages else i'd lose my remote access.
I could get around this issue by creating additional free domains, but i'm not sure whats my limit per account on the providers side.

**Comment by jortkoopmans** [comment]
Thank you for this report @DiSHTiX . I have reviewed this and indeed this is broken. However, the problem is 2-fold:
1. The upstream ddclient breaks when provided with a zone and a non-identical hostname. I have filed a bug upstream, to get this resolved (and will propose a solution).
2. Currently, in opnsense ddclient interface, there is no UI option to define a `zone`. It would be nice to get this added, to support your use case.

**Comment by DiSHTiX** [comment]
Hello Jort, 
Thanks for your time looking into this and help raising a ticket.
I think you nailed it =)

As for the UI option, trimming it off the current input should work just as well. Which would keep the UI in line with other ddns provider.

**Comment by jortkoopmans** [comment]
Well, about the UI option, I don't think we can do without the `zone` field for the use case of implementing the 'sub' hosts on the root domain (note; you can override the config through ddclient.conf, but it will probably get overwritten during OPNSense updates).
With the DNSExit provider, it is possible to use more than 1 level of subdomains. Also it is possible to have a root domain at different levels (e.g. free shared tld domain versus private domain). Therefore I don't think we can reliably determine the root domain automatically. Additionally, the same kind of setup is being used by other providers, see example screenshot of Cloudflare provider pasted below with my annotations, we need that 'zone' field just like implemented there.

Note1: I have tested only to 2 levels deep from my root.
Note2: Wildcard does not seem supported through the provider API, while it is possible to set a wildcard record directly on the domain root, via the web interface.

![Screenshot from 2024-05-27 23-58-27](https://github.com/opnsense/plugins/assets/1008482/ec451c5b-9d42-4e5e-ad7b-73eef9e681bd)

**Comment by DiSHTiX** [comment]
Yes, fully agree on your points.
I was mainly trying to avoid raising UI changes for just a single case as it would likely get thrown aside. However with Cloudflare in the mix and likely others, its builds a solid requirement for this UI change.
Thanks for taking this forward

**Comment by jortkoopmans** [comment]
@fichtner ; Since you've been a great support previously, what is your take on this?

**Comment by fichtner** [comment]
I'm not sure about specific questions but adding the zone to a provider should be trivial since the GUI supports it for others.. the question is if that's all or more underlying problems related to its use?

**Comment by jortkoopmans** [comment]
Thanks for your response, yes a fix will be needed in the ddclient, which is still being worked on. It would be fine to wait for this to become available, but the UI option will be needed regardless (and the current ddclient will not break if it is added and set by users). I will update here when the fix is available.

**Comment by jortkoopmans** [comment]
Not sure why the bot automatically times out this issue. I think we were fairly actively discussing it :wink: .

**Comment by fichtner** [comment]
No assignee, but we can reopen when something code-wise is available (PR, fixed upstream release, etc.)
