### ISSUE TITLE
os-upnp 1.5_4 - miniupnpd fails to start if WAN interface isn't up

### ISSUE THREAD

**Issue by MorningLightMountain713** [opnsense/plugins#3716]
- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

I'm on 23.7.9 

My use case is pretty odd but I'm using UPNP with the WAN as an OpenVPN connection. (I'm on CGNat so use the other end of the VPN as a public IP)

Since the upnp "WAN" does not come up immediately - miniupnpd fails to start. So everytime OPNSense reboots (or power failure or whatever), I have to manually start miniupnpd.

**To Reproduce**

1/ Create VPN client to remote OpenVPN server
2/ setup upnp with the WAN as the vpn interface.
3/ Setup stun server connection or set ext_ip (if necessary)
4/ Confirm upnp working.
5/ Reboot
6/ Confirm upnp service has to be started manually

**Expected behavior**
Reboot and upnp eventually starts

**Comment by fichtner** [comment]
Did you try 23.7.10? https://github.com/opnsense/changelog/blob/0c074f642184433c335160ef62870f55372568b3/community/23.7/23.7.10#L33

**Comment by MorningLightMountain713** [comment]
Wow, missed that - I did not try it. I'll close this :)
