### ISSUE TITLE
add support for World4You in Acme

### ISSUE THREAD

**Issue by adriandanciu90** [opnsense/plugins#3722]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
I am working a lot with World4You and I had to use a lot of workarounds to use the ACME plugin from OpnSense.
I have domains registered at World4You and I had to use the nameservers from Desec because Desec is already supported by the ACME plugin in OpnSense.
I want to get rid of this as I want to use the full features from World4You and at the same time from OpnSense without any workaround.

**Describe the solution you'd like**
I have already found a solution which I have tested on my OpnSense instance. I have created a local branch, but I cannot push it, as I do not have permissions.

**Comment by fraenki** [comment]
Implemented in https://github.com/opnsense/plugins/pull/3735, will be available in os-acme-client 3.20.
