### ISSUE TITLE
os-frr 1.37 BGP Prefixes not received

### ISSUE THREAD

**Issue by dinoex** [opnsense/plugins#3728]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**

I have a setup with 2 BGP full feeds, 1 iBGP, 1 eBGP
I migrated a working configuration by hand from pfSense to OPNsense.

When testing the router the eBGP prefixes count was only between 50 and 500.
I diffed the filters in the generated config files.
I diffed  the filters in the running-config, no significant differences

The only differences I found was the running setup had
`soft-reconfiguration inbound` per neighbor.

A clear and concise description of what the bug is, including last known working version (if any).

**To Reproduce**
1. Setup an iBGP neighbor that send you a full table
2. Setup an iBGP neighbor that send you a full table
3. Check the number of prefixes received

**Expected behavior**
I  expect to receive a similar number of prefixes on each Feed.

**Screenshots**

```
soft-reconfiguration inbound
Neighbor         V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
2xxx:xxxx:1:1::1 4     2xxxxx     51043         6        0    0    0 00:01:03           79        0 N/A
2xxx:xxxx::250   4     2xxxxx     96135       305        0    0    0 00:01:03       185877       84 N/A

Total number of neighbors 2

```

For testing I forced `soft-reconfiguration inbound` into the config by patching the template:

```
--- /usr/local/opnsense/service/templates/OPNsense/Quagga/bgpd.conf.orig        2023-12-29 11:55:40.605243000 +0100
+++ /usr/local/opnsense/service/templates/OPNsense/Quagga/bgpd.conf     2023-12-29 12:03:56.844301000 +0100
@@ -115,6 +115,7 @@
   neighbor {{ neighbor.address }} next-hop-self {% if 'nexthopselfall' in neighbor and neighbor.nexthopselfall == '1' %}all{%  endif %}
 
 {%     endif %}
+  neighbor {{ neighbor.address }} soft-reconfiguration inbound
 {%     if 'rrclient' in neighbor and neighbor.rrclient == '1' %}
   neighbor {{ neighbor.address }} route-reflector-client
 {%     endif %}

```

This results in the expected behavior:

```
# echo "show bgp summary" | vtysh
[...]
Neighbor         V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
2xxx:xxxx:1:1::1 4     2xxxxx     51788         8        0    0    0 00:02:42       185001        0 N/A
2xxx:xxxx::250   4     2xxxxx     51233     51824        0    0    0 00:02:42       185870   185006 N/A

Total number of neighbors 2
```

**Relevant log files**
No related warning or errors in the logfiles

**Additional context**

**Environment**
Software version used and hardware type if relevant.

OPNsense 23.7.10_1 (amd64)

```
# uname -a
FreeBSD example.com 13.2-RELEASE-p7 FreeBSD 13.2-RELEASE-p7 stable/23.7-n254871-d5ec322cffc SMP amd64

```

```
# pkg info | grep frr
frr8-8.5.4                     IP routing protocol suite including BGP, IS-IS, OSPF and RIP
os-frr-1.37                    The FRRouting Protocol Suite

```

**Summary**

I do not understand why FRR8 behaves differently as the filters did not change

I would like the os-frr webinterface to extend so a user can add
 `soft-reconfiguration inbound`  to the neighbor configuration.

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/plugins/pull/3730 should do the trick if that's the option you're looking for.
