### ISSUE TITLE
os-bind allow specifying port in forwarders

### ISSUE THREAD

**Issue by aclerici38** [opnsense/plugins#3729]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [ ] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [ ] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [ ] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
Currently the GUI only allows forwarders on port 53, syntax like 127.0.0.1:5335 and 127.0.0.1 port 5335 are both not allowed. In named.conf I can specify port using 127.0.0.1 port 5335, however.
**Describe the solution you'd like**
(e.g. I would like an input field in the `/ui/firewall/alias` which would add .... to ....)
Either a mapping from 127.0.0.1:5335 to the proper bind syntax in the config or simply the option to enter the syntax manually in the GUI
**Describe alternatives you've considered**
Manually editing the config file

**Additional context**

**Comment by fichtner** [comment]
https://github.com/opnsense/plugins/issues/1715 already has a PR, but needs work.
