### ISSUE TITLE
IGMP Proxy is too old

### ISSUE THREAD

**Issue by timur-davletshin** [opnsense/plugins#373]
Current version of igmpproxy does not support v.3. Looks like sourceforge is abandoned and moved to https://github.com/pali/igmpproxy which provides support for v.3.

Report:

RECV V2 member report from 192.168.0.121 to 225.77.225.2
Updated route entry for 225.77.225.2 on VIF #2
RECV unk: 0x22/0x00 from 80.82.58.46 to 224.0.0.22
ignoring unknown IGMP message type 22 from 80.82.58.46 to 224.0.0.22
RECV Leave message from 192.168.0.121 to 224.0.0.2
leaveMcGroup: 225.77.225.2 on pppoe0

**Comment by fabianfrz** [comment]
this is a port issue which should be reported upstream to FreeBSD. I assign this to @fichtner as he knows how to handle this.

**Comment by timur-davletshin** [comment]
Or, just as an idea, pimd could be another option with same functionality. AFAIK it provides more robust IGMP routing...

**Comment by fichtner** [comment]
For sane inclusion we need a new release from them with release notes to see the list of changes and required changes for integration (if any)  https://github.com/pali/igmpproxy/issues/22

**Comment by fichtner** [comment]
See https://github.com/opnsense/ports/commit/ce69914ce21ecf250d415896e0eea5c75bb868cd and https://forum.opnsense.org/index.php?topic=6535.0 for testing instructions. Depending on user feedback and testing this may or may not make it into 18.1.
