### ISSUE TITLE
os-frr 1.37 Redistributing Kernel Routes into OSPF not working

### ISSUE THREAD

**Issue by magomez96** [opnsense/plugins#3731]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
Redistribution of kernel routes into OSPF is not working. This has not worked since I deployed OPNsense

See also this incomplete issue report describing the same issue: https://github.com/opnsense/plugins/issues/3543

**To Reproduce**
1. Add a static route under System -> Routes -> Configuration, make sure the route is enabled
2. In the OSPF Routing settings enable redistribution of Kernel routes
3. The previously created static route, which is present in the system routing table, will not be present in the OSPF routing table

**Expected behavior**
The static route created in OPNsense under System -> Routes -> Configuration is added to the OSPF routing table 

**Screenshots**
<img width="1428" alt="Screenshot 2023-12-29 at 9 51 09 AM" src="https://github.com/opnsense/plugins/assets/5390341/ce1fdfcf-9190-47a9-baeb-4ed813702a98">
<img width="1428" alt="Screenshot 2023-12-29 at 9 51 59 AM" src="https://github.com/opnsense/plugins/assets/5390341/2e8ab95e-904a-4ca9-bf3f-3701300394d3">
<img width="756" alt="Screenshot 2023-12-29 at 9 52 31 AM" src="https://github.com/opnsense/plugins/assets/5390341/2694e7b0-9d52-4bd4-ade9-365b256a990b">
<img width="1426" alt="Screenshot 2023-12-29 at 9 52 56 AM" src="https://github.com/opnsense/plugins/assets/5390341/1b6ac1fe-67eb-409b-ba86-9a66f963aee5">
<img width="1426" alt="Screenshot 2023-12-29 at 9 53 15 AM" src="https://github.com/opnsense/plugins/assets/5390341/f7ac94e3-f7fa-452f-bbc2-d8329cd59bd0">
<img width="1426" alt="Screenshot 2023-12-29 at 9 54 15 AM" src="https://github.com/opnsense/plugins/assets/5390341/142d0f9a-557f-4b14-b44f-9474caa48f86">

**Relevant log files**
frr configuration:
Building configuration...

Current configuration:
!
frr version 8.5.4
frr defaults traditional
hostname (removed)
log syslog warnings
!
interface enc0
 ip ospf passive
exit
!
interface igc0
 ip ospf passive
exit
!
interface ipsec1
 ip ospf area 0.0.0.0
 ip ospf dead-interval 3
 ip ospf hello-interval 1
exit
!
interface ix0
 ip ospf area 0.0.0.2
 ip ospf dead-interval 3
 ip ospf hello-interval 1
exit
!
interface lo0
 ip ospf passive
exit
!
interface openvpn
 ip ospf area 0.0.0.2
 ip ospf passive
exit
!
interface ovpnc2
 ip ospf passive
exit
!
interface ovpnc4
 ip ospf area 0.0.0.0
 ip ospf cost 100
exit
!
interface ovpns3
 ip ospf area 0.0.0.0
 ip ospf cost 110
 ip ospf dead-interval 3
 ip ospf hello-interval 1
exit
!
interface re0
 ip ospf passive
exit
!
interface vlan01
 ip ospf area 0.0.0.2
 ip ospf passive
exit
!
interface vlan02
 ip ospf area 0.0.0.2
 ip ospf passive
exit
!
interface vlan03
 ip ospf area 0.0.0.2
 ip ospf passive
exit
!
router ospf
 ospf router-id 10.2.1.1
 redistribute kernel route-map redist1918
 area 0.0.0.2 range 10.2.0.0/16
 default-information originate always
exit
!
ip prefix-list PL1 seq 10 permit 10.0.0.0/8 le 32
ip prefix-list PL1 seq 20 permit 172.16.0.0/12 le 32
ip prefix-list PL1 seq 30 permit 192.168.0.0/16 le 32
!
route-map redist1918 permit 10
 match ip address prefix-list PL1
exit
!
end

**Additional context**
The issue will occur with or without any route map/prefix list applied
Redistributing connected routes will work as expected

**Environment**
Software version used and hardware type if relevant.
e.g.:

OPNsense 23.7.10_1-amd64
Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 cores, 4 threads)

**Comment by mimugmail** [comment]
To me it sounds you dont have any adjacency and therefore the Status is empty. Is this already working without any redist?

**Comment by magomez96** [comment]
I have fully adjacent neighbors and routes are being exchanged, only the
redistribution is not working

**Comment by mimugmail** [comment]
I think with staticd this should work now
