### ISSUE TITLE
os-opnarp-maxit and os-homeassistant-maxit cannot coexist

### ISSUE THREAD

**Issue by Wampukas** [opnsense/plugins#3744]
**Describe the bug**

When enabling and starting os-opnarp-maxit service, interface_wan_inbytes_kilobytes_per_second and  interface_wan_outbytes_kilobytes_per_second (I am using these two sensors in home assistant) stops updating. If I disable opnarp service - it starts working as it should.

1. Install os-homeassistant-maxit
2. run it
3. Install os-opnarp-maxit
4. start it
5. os-homeassistant-maxit plugin counters stops updating

**Expected behavior**
Should work both plugins

**Environment**

OPNsense 23.7.10_1-amd64
FreeBSD 13.2-RELEASE-p7

**Comment by AdSchellevis** [comment]
both plugins are not shipped by us
