### ISSUE TITLE
net/haproxy: Script action stderr returned "b'WARNING: no nonce in response\nResponse verify OK\n / Certificate ID does not match any certificate or issuer

### ISSUE THREAD

**Issue by techsolo12** [opnsense/plugins#3755]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [?] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
   - A [similar issue](https://github.com/opnsense/plugins/issues/2323)was existing, but it was solved, since some parts of a old config was removed.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
Since i used haproxy i want to automatic update my ocsp data. Normally i only got this part of mesages in log. The data will be updated and works as expected:
```2024-01-09T01:37:01	Error	configd.py	[2cfe5601-5c93-4745-9d97-75ebf78e4682] Script action stderr returned "b'WARNING: no nonce in response\nResponse verify OK\nWARNING: no nonce in response\nResponse verify OK\nWARNING: no nonce in response\nResponse verify OK'"```

On some day i got this message addional to the first ones. If the message appears the seems the ocsp was updated, but the ocsp feature don't work. After a restart from haproxy everthing works, till the next time the messages will apears.
```2024-01-09T01:37:01	Informational	configd.py	message 2cfe5601-5c93-4745-9d97-75ebf78e4682 [] returned OCSP single response: Certificate ID does not match any certificate or issuer. OCSP single response```

Since the second message contains the hint with certificate id i have revoked and removed all certifcates. Additional i removed all files manually which are connected to this certificates. After this i issued the certificates new.

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**
1. Enable "Store OCSP responses" in HAProxy. (HAProxy --> Settings --> Service)
3. Configure the cron job to run every day.
4. Add ACME Certificate to HAProxy
5. Cron Job fails, see log below.

**Expected behavior**
A functional automatic update of the OCSP data for HAProxy.

**Relevant log files**
```
2024-01-09T01:37:01	Informational	configd.py	message 2cfe5601-5c93-4745-9d97-75ebf78e4682 [] returned OCSP single response: Certificate ID does not match any certificate or issuer. OCSP single response	
2024-01-09T01:37:01	Error	configd.py	[2cfe5601-5c93-4745-9d97-75ebf78e4682] Script action stderr returned "b'WARNING: no nonce in response\nResponse verify OK\nWARNING: no nonce in response\nResponse verify OK\nWARNING: no nonce in response\nResponse verify OK'"
```

**Environment**
Virtualized OPNsense 23.7.9 on proxmox VM with virtio nics

**Comment by fraenki** [comment]
Thanks for the report! This bug is most likely solved in the upcoming os-haproxy 4.0, which will be available in OPNsense 24.1 soon. The OCSP update was completely revamped, making the OSCP cron job approach unnecessary.

I consider this bug solved and will close this issue now. Please let me know if it's not solved in os-haproxy 4.0.
