### ISSUE TITLE
os-bind: please help me with setting up the DNS

### ISSUE THREAD

**Issue by habibullinrsh** [opnsense/plugins#3760]
**Important notices**
Our forum is located at https://forum.opnsense.org , please consider joining discussions there in stead of using GitHub for these matters.

Before you ask a new question, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.

- The current plugin version where the bug first appeared - 1.28_1
- Add the name of the plugin to the front of the subject - done
- The last plugin version where the bug did not exist - ...
- Список шагов для репликации ошибки:
 1. Install the opensense from the image OPNsense-23.7-dvd-amd64.iso
 2. Update the opensense version to version 23.7.11
 3. Install the os-bind plugin version 1.28_1
 4. Disable the Unbound DNS service
 5. Change the port of the Bind service to 53
 6. Enabling the Bing service with default settings
 7. I'm looking at the ports on the opensense virtual machine:
![image](https://github.com/opnsense/plugins/assets/61868780/fcef76a5-d469-49e3-a46d-b53d7c30a2bf)
 9. I run the nslookup command from the opensense console:
![image](https://github.com/opnsense/plugins/assets/61868780/84632041-a0ab-4a76-be87-fc581f3b3ba2)
![image](https://github.com/opnsense/plugins/assets/61868780/a03fef25-d696-4f32-8829-e4500198a0b0)
 10. I am running the nslookup command from a VM from the same subnet:
![image](https://github.com/opnsense/plugins/assets/61868780/4a9c6589-7372-4b27-ace0-af0462db3edd)
 11. I see it in the logs:
![image](https://github.com/opnsense/plugins/assets/61868780/94dfa2b6-6fb2-4ca1-bc87-dd81664851d6)
 - The current OPNsense version used - 23.7.11

I have tried using the Unbound DNS service with request forwarding or port forwarding. I tried to add the firewall rules "allow from any to any". I also changed the settings of DNS forwarders, recursion and ACL.
What am I doing wrong?

**Comment by L1ghtn1ng** [comment]
you need to make sure you have a forwarder setup in bind so it can query DNS that is not in its zones locally, here is the docs that should help you on your way https://docs.opnsense.org/manual/how-tos/bind.html#installation
