### ISSUE TITLE
os-frr 1.38: ebgp-multihop doesn't allow setting values

### ISSUE THREAD

**Issue by TechGeek01** [opnsense/plugins#3763]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
When using FRR, many options are able to be set using the GUI. In my particular case, setting up DN42, where the BGP peers are over a VPN tunnel, the routes are not considered valid because the default setting for `ebgp-multihop` is `1`. Because of the tunnel in place, the solution to this is to set `ebgp-multihop` for the peer in question to `255`.

There is no place in the GUI to set this. However, setting it manually fails.

**To Reproduce**
Via SSH, open a shell, and run the commands:
```
root@fw03:~ # vtysh
fw03.techgeek01.lan# conf
fw03.techgeek01.lan(config)# router bgp XXXXXXXXXX
fw03.techgeek01.lan(config-router)# neighbor A.A.A.A ebgp-multihop 255
fw03.techgeek01.lan(config-router)# exit
fw03.techgeek01.lan(config)# exit
fw03.techgeek01.lan# show run
Building configuration...

Current configuration:
!
frr version 8.5.4
!
router bgp XXXXXXXXXX
 ...
 neighbor A.A.A.A remote-as YYYYYYYYYY
 neighbor A.A.A.A ebgp-multihop
 exit-address-family
exit
!
```

**Expected behavior**
When setting `ebgp-multihop` to `255`, the expected output should result in `neighbor A.A.A.A ebgp-multihop 255`. Instead, the number is stripped off, and never set, thus defaulting to 1

**Environment**
Software version used and hardware type if relevant.
e.g.:

OPNsense 24.1.b_105-amd64
os-frr 1.38

I have seen the same results with 23.7.10 and 23.7.11, though I moved to `development` hoping updates might have changed behavior before 23.7.12 was released. Given that this pertains to the plugin version, I don't believe the OPNsense version matters.

**Comment by mimugmail** [comment]
We could just add 255 to the line as I don't see some kind of risk if it's more than 1 it won't break existing setups

**Comment by TechGeek01** [comment]
I mean, even if 1 was still the default, the main problem is that even if I manually edit the config to specify 255, it gets stripped off, rendering my edits useless. Changing default to 255 would fix that, but it's probably also preferred to let users be able to specify. Currently there's no option in the UI to do that, and like I mentioned, manual config changes are stripped off and ignored anyway, so in addition to defaulting to 255, there really should be *some* way for users to actually specify an arbitrary value and have it stick.

**Comment by Comstepr** [comment]
Hi any updates on this?

**Comment by Comstepr** [comment]
I've created a PR #3829 that might potentially fix this.

**Comment by JSuenram** [comment]
Sorry to reopen this, but for me it looks like this still does not work.
When enabling ebgp-multihop in WebGUI there is still no hop-count in the "Running-Config" visible.
I am using latest Business Edition of opnsense. (OPNsense 24.4.2-amd64)
