### ISSUE TITLE
os-wireguard - notifications for active unassigned endpoints

### ISSUE THREAD

**Issue by breca** [opnsense/plugins#3764]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**

I rarely interact with this module but when I do I'm usually doing it to add a new endpoint to an existing configuration. I find that I often do the exact same thing as the users in [482108](https://github.com/opnsense/plugins/issues/2926) and after log diving and wasted time, realise I've forgotten to associate the new endpoint to the interface.

**Describe the solution you'd like**

I would like a notification banner or reminder, something, to indicate that an enabled endpoint has not been assigned to an interface.

**Describe alternatives you've considered**

Existensial crisis management

**Additional context**

Nope

**Comment by fichtner** [comment]
Nowadays you can add the instance from the endpoint with a single edit in the same form. I don't think we should do more here as there are always downsides to requiring input here... like missing an instance to begin with... or requiring users to disable an endpoint which offers a bit of the same functionality (detach from all instances... now no instance selected is valid?) .. and considering migrating instances that's also a problem.


Cheers,
Franco

**Comment by breca** [comment]
> Nowadays you can add the instance from the endpoint with a single edit in the same form.

This sounds good, I'll have to make sure I'm properly updated!

For clarity I'm not suggesting implementing anything that blocks or interrupts the existing workflow, I just think a simple notification indicating a potential misconfiguration like what I described in my OP adds value and makes for a friendlier user experience.
