### ISSUE TITLE
NGINX Update changes UUID for location-section in nginx.conf

### ISSUE THREAD

**Issue by JSuenram** [opnsense/plugins#3765]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
After Update to latest NGINX-Plugin included in 23.10.x every UUID used in location-section gets changed.

**To Reproduce**
Update to latest version where new NGINX-Plugin-Version gets installed.

**Expected behavior**
UUID should not change after Update

**Additional context**
Using the so called autodiscover-trick from here https://forum.opnsense.org/index.php?topic=21154.msg99523#msg99523 to publish Exchange 2016/2019-Servers. Does have issues after upgrade which need to be fixed by manual creating the right folders and files again. After all, would be much easier if these settings where possible inside Plugin WebGUI.

OPNsense 23.10.1_2-amd64.
AMD EPYC 7343 16-Core Processor (2 cores, 2 threads)

**Comment by fichtner** [comment]
Cc @kulikov-a

**Comment by fichtner** [comment]
no rush, just wanted to keep you in the loop!

**Comment by JSuenram** [comment]
> Hi. Sorry for not answering on the forum - I need a couple of days more to clean some mess.. I didn't see anything in the updates that would cause this (there weren't even any migrations after 1.24.0). I also compared the uuids on the production 22.* with the test version 23.7.12 - they are same for the corresponding locations. Plus I think it would break not only user includes but the whole configuration (internal references in config)? so it must be something else IMHO

Hi,
we will update another opnsense this weekend, I will then compare what happens....

**Comment by JSuenram** [comment]
Will close this, not reproducable with other installations.
