### ISSUE TITLE
os-git-backup: Allow non default ssh port for git backups

### ISSUE THREAD

**Issue by ben-kenney** [opnsense/plugins#3766]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**

I would like to be able to specify a non default ssh port in the `os-git-backup` plugin. Currently it defaults to port 22 which works for services such as github but some self hosted options may be running on a non standard port for extra security.

**Describe the solution you'd like**

In the `os-git-backup` gui configuration it would be ideal if there was an option to specify ssh port. This option would default to port 22. 

After the gui setting has been implemented, the git ssh command could be: `git config core.sshCommand "ssh -p <port> -i <key>"`

Although I've never contributed to this project before, perhaps this could be implemented by modifying somewhere around [this line](https://github.com/opnsense/plugins/blob/d5ae01f361962c510172a5dec004fe0a13ac7309/sysutils/git-backup/src/opnsense/mvc/app/library/OPNsense/Backup/Git.php#L152)  to add `-p {$port}` such as:
```
ssh -p {$port} -i {$ident_file} -o StrictHostKeyChecking=accept-new -o PasswordAuthentication=no
```

Could also add an entry this entry to [getConfigurationFields()](https://github.com/opnsense/plugins/blob/d5ae01f361962c510172a5dec004fe0a13ac7309/sysutils/git-backup/src/opnsense/mvc/app/library/OPNsense/Backup/Git.php#L46)

```
 [
   "name" => "port",
   "type" => "text",
   "label" => gettext("SSH port"),
   "help" => gettext("Specify a non default port. (default=22)"),
   "value" => null
 ],
```

Might also need to add an entry similar [to this](https://github.com/opnsense/plugins/blob/d5ae01f361962c510172a5dec004fe0a13ac7309/sysutils/git-backup/src/opnsense/mvc/app/models/OPNsense/Backup/GitSettings.xml#L32-L35) (but for the port) to `GitSettings.xml`

**Describe alternatives you've considered**

The alternative is to use git via http/https, but there are some sacrifices to this method, like it doesn't work if the git service is behind an extra 2FA layer such as a cloudflare security policy as an example.

**Additional context**

Would like to be add an option for non default ssh port, potentially something like this:

![example_gui](https://github.com/opnsense/plugins/assets/2074287/b17274de-d928-4ad3-bc34-dff5c9f2b309)

**Comment by justinhorton** [comment]
This can be done today by specifying the port in the URL field. For example, `ssh://git.example.com:222/project.git` to target port 222 rather than the default 22.

**Comment by ben-kenney** [comment]
Oh, so it can! Thanks! I'll close this out.
