### ISSUE TITLE
os-telegraf - Please add OpenTelemetry output

### ISSUE THREAD

**Issue by bmnijhuis** [opnsense/plugins#3772]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Please add an OpenTelemetry output configuration section to the Telegraf UI.

**Describe alternatives you've considered**
The only alternative I know of is a manual installation and configuration of Telegraf

**Additional context**
The current output configuration in de UI supports InfluxDB, InfluxDB v2, Graphite, Graylog, Elasticsearch, Prometheus, Datadog and MQTT. Telegraf also supports OpenTelemetry (see the [docs](https://github.com/influxdata/telegraf/tree/master/plugins/outputs/opentelemetry))
It would be nice to be able to configure the OpenTelemetry output through the UI.

**Comment by mrpotato3** [comment]
+1!
