### ISSUE TITLE
Nginx Plugin: Add MJS to application/javascript mimetype

### ISSUE THREAD

**Issue by shadowcpy** [opnsense/plugins#3773]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X] The title contains the plugin to which this issue belongs

**Describe the bug**
When using Nextcloud 28.0.1 behind the NGINX OPNSense Reverse Proxy, [this bug](https://help.nextcloud.com/t/activity-and-logging-sections-in-admins-setting-shows-blank-pages/175958/6) appears, because `mjs` is not part of the [mime-types](https://github.com/opnsense/plugins/blob/e96c38421209307c2ca1d159eba260701e8f600f/www/nginx/src/opnsense/service/templates/OPNsense/Nginx/mime.types#L7)

This results in this error being thrown:
`Loading module from “https://cloud.domain.com/apps/logreader/js/logreader-main.mjs?v=ab2a8ef0-33” was blocked because of a disallowed MIME type (“application/octet-stream”).`

**Expected behavior**
The Plugin should treat `mjs` as javascript (or provide an override possibility)

**Environment**

OPNsense 23.7.10
OS-Nginx 1.32.2

**Comment by kulikov-a** [comment]
@your-sudden-death
are you sure you try to set mime-type (and its not application/javascript but text/javascript) on the right nginx? )
adding type to nginx config is necessary on NC instance, not reverse-proxy imo
ref.https://docs.nextcloud.com/server/latest/admin_manual/installation/nginx.html#nextcloud-in-the-webroot-of-nginx
