### ISSUE TITLE
net/haproxy: SNI not working when OCSP is enabled

### ISSUE THREAD

**Issue by martinjgrunwald** [opnsense/plugins#3779]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
SNI does not seem to be working in HAProxy 4.2. It did for me with HAProxy 4.1. Now it always uses the Default Certificate under Public Services -> "My HTTPS Frontend" -> SSL Offloading. When opening a website that does not match the CN of the default cert it is still used and i get a NET::ERR_CERT_COMMON_NAME_INVALID

**To Reproduce**
1. Have multiple Certificates in the ACME client
2. Select a Default Certificate under Public Services -> "My HTTPS Frontend" -> SSL Offloading
3. Access a website that does not match the CN of that default cert
4. NET::ERR_CERT_COMMON_NAME_INVALID error appears

**Expected behavior**
A different cert should be used

**Environment**
OPNsense 24.1 (amd64).
AMD EPYC 7282 16-Core Processor (4 cores, 4 threads) (VM under Proxmox)
HAProxy 4.2

**Comment by mnaiman** [comment]
I have same problem.

For those who wants back running HaProxy before fix will be issued:

1)locate in /tmp/haproxy/ssl file *.certlist
2)in that file remove all oscp suffix, leave just file on each row, save
3)SSH
killall haproxy
/usr/local/sbin/haproxy -q -f /usr/local/etc/haproxy.conf -p /var/run/haproxy.pid

HAProxy should be running fine.

This is not final solution, and any restart or save via GUI will overwrite that.
Just emergency solution to keep HAProxy running.

**Comment by mnaiman** [comment]
On each row, this was present "ocsp-update on" probably by this commit https://github.com/opnsense/plugins/commit/c4c0c2b4af21428941304f47e3926655fdaa5cb4

I dont want to mess with certificates - need running service.
Still thanks to devs for great plugin and hard work :)

**Comment by mnaiman** [comment]
After study of source code, even more elegant solution is Settings->Global parameters->Automatic OSCP updates -> OFF
APPLY
STILL TEMPORARY FIX - oscp certificates not working in firefox, but better than nothing :)

**Comment by fraenki** [comment]
Thanks for reporting this issue. The following patch should solve this:

```
opnsense-patch -c plugins 28fe2f1cc
```

os-haproxy 4.2 introduced a dumb syntax error. Be sure to hit the "Apply" button in os-haproxy in order to activate the changes.

**Comment by mnaiman** [comment]
Thanks, now it is working, but there is still one small glitch.

On frontend if there is Default certificate selected, and same certificate is added among certificates in field Certificates, HAProxy refuses to start with error like that
![image](https://github.com/opnsense/plugins/assets/2264442/0c9edb8e-1aad-4aca-9655-900497a2ee04)

cert file looks like that

/tmp/haproxy/ssl/61562d7491ed3.pem
/tmp/haproxy/ssl/639f7a739d5d6.pem [ocsp-update on]
/tmp/haproxy/ssl/639f6f26221f5.pem [ocsp-update on]
/tmp/haproxy/ssl/615626cd5eb6c.pem [ocsp-update on]
/tmp/haproxy/ssl/615629ace2d26.pem [ocsp-update on]
/tmp/haproxy/ssl/61562a04137d3.pem [ocsp-update on]
/tmp/haproxy/ssl/61562d473b790.pem [ocsp-update on]
/tmp/haproxy/ssl/64996cbd8cbf4.pem [ocsp-update on]
/tmp/haproxy/ssl/61562d7491ed3.pem [ocsp-update on]


when not selected in certificates, cert file looks like that
/tmp/haproxy/ssl/61562d7491ed3.pem [ocsp-update on]
/tmp/haproxy/ssl/639f7a739d5d6.pem [ocsp-update on]
/tmp/haproxy/ssl/639f6f26221f5.pem [ocsp-update on]
/tmp/haproxy/ssl/615626cd5eb6c.pem [ocsp-update on]
/tmp/haproxy/ssl/615629ace2d26.pem [ocsp-update on]
/tmp/haproxy/ssl/61562a04137d3.pem [ocsp-update on]
/tmp/haproxy/ssl/61562d473b790.pem [ocsp-update on]
/tmp/haproxy/ssl/64996cbd8cbf4.pem [ocsp-update on]


First line is where HAProxy is complaining. GUI should prevent to add to Certificates that which is default (first line), or allow to not confuse user, and backend should mark both as [ocsp-update on] (or add once and mark [ocsp-update on])

**Comment by fraenki** [comment]
@mnaiman I've revised the patch, please [try again](https://github.com/opnsense/plugins/issues/3779#issuecomment-1917956814).

**Comment by mnaiman** [comment]
Did I run it correctly? It fails.
opnsense-patch -c plugins 558d56479

Fetched 558d56479 via https://github.com/opnsense/plugins
1 out of 2 hunks failed while patching opnsense/scripts/OPNsense/HAProxy/exportCerts.php

**Comment by fraenki** [comment]
@mnaiman That's because the previous patch already modified this file. So be 100% sure, reinstall the plugin...

```
pkg install -f os-haproxy
```

...and apply the patch again.

**Comment by mnaiman** [comment]
It seems, firefox is right

https://www.ssllabs.com/ssltest/
![image](https://github.com/opnsense/plugins/assets/2264442/7915f050-7737-4f93-8792-4b106327c86b)

**Comment by fraenki** [comment]
@mnaiman Maybe third time's a charme? Please try the [3rd patch revision](https://github.com/opnsense/plugins/issues/3779#issuecomment-1917956814).

**Comment by Wireheadbe** [comment]
```opnsense-patch -c plugins 404c19f``` 
.. fixes firefox! Many thanks!

**Comment by mnaiman** [comment]
Yes, I confirm, that OSCP is working now. Firefox is fine.
Thanks for effort!

**Comment by TheHellSite** [comment]
@fraenki 
Thanks for the patches.

**The following issues are fixed for me:**
- OCSP with Firefox
- SNI with multiple certificates per Frontend

**The following issue is still present for me:**
Having a HTTPS frontend enabled with a default certificate set on it results in HAProxy beeing unable to start.
![haproxy](https://github.com/opnsense/plugins/assets/34900685/fc273123-359e-4a9c-818a-7715fafebd4e)

```
[NOTICE] (81393) : haproxy version is 2.8.5-aaba8d0
[NOTICE] (81393) : path to executable is /usr/local/sbin/haproxy
[ALERT] (81393) : config : parsing [/usr/local/etc/haproxy.conf.staging:77] : 'bind 127.4.4.3:443' in section 'frontend' : 'crt-list' : error processing line 1 in file '/tmp/haproxy/ssl/646e30990fd007.26614272.certlist' : '/tmp/haproxy/ssl/6106507cef0b9.pem' has an OCSP URI and OCSP auto-update is set to 'on' but an error occurred (maybe the issuer could not be found)'.
[ALERT] (81393) : config : Error(s) found in configuration file : /usr/local/etc/haproxy.conf.staging
[ALERT] (81393) : config : Fatal errors found in configuration.
```

**Workaround:** Once the default certificate is set to "none" HAProxy accepts the config and starts fine.

**Comment by fraenki** [comment]
@TheHellSite The error suggests that there is something odd with your certificate. Please provide the output of the following commands:

```
cat /tmp/haproxy/ssl/646e30990fd007.26614272.certlist

cat /tmp/haproxy/ssl/6106507cef0b9.pem
```

**Comment by TheHellSite** [comment]
```
# cat /tmp/haproxy/ssl/646e30990fd007.26614272.certlist

/tmp/haproxy/ssl/635341b3c1fe0.pem [ocsp-update on]
/tmp/haproxy/ssl/62546d24641f2.pem [ocsp-update on]
/tmp/haproxy/ssl/635bcc991a877.pem [ocsp-update on]


# cat /tmp/haproxy/ssl/6106507cef0b9.pem

cat: /tmp/haproxy/ssl/6106507cef0b9.pem: No such file or directory
```

The default "INVALID_SNI" certificate is self-signed and used to hide the real certificates if no valid SNI is provided by the accessing client.
See Part 8 of my tutorial: https://forum.opnsense.org/index.php?topic=23339.0

**Comment by mnaiman** [comment]
If you want privacy (read your tutorial), better user that feature on frontend

![image](https://github.com/opnsense/plugins/assets/2264442/b4991f62-b40a-4c79-b5c8-e9962869e8da)

**Comment by TheHellSite** [comment]
> If you want privacy (read your tutorial), better user that feature on frontend
> 
> ![image](https://private-user-images.githubusercontent.com/2264442/301326456-b4991f62-b40a-4c79-b5c8-e9962869e8da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NDAxNTUsIm5iZiI6MTcwNjczOTg1NSwicGF0aCI6Ii8yMjY0NDQyLzMwMTMyNjQ1Ni1iNDk5MWY2Mi1iNDBhLTRjNzktYjVjOC1lOTk2Mjg2OWU4ZGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMzFUMjIyNDE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWUxMWNjMzcyZWEwMjRlYjQ0ZGQ0ODYxYTMwOTYyOTgyNTg2NWM0YmZhZDIwOTVhYzE3NjNhMmQ0NGQ5MjMwZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.irADWwBQT--TihAmkRZZLxWJzDKbK9QeDdhuTB186Nk)

I very much like and appriciate your response! 
This is even easier and cleaner than my approach.

**Comment by fraenki** [comment]
> has an OCSP URI and OCSP auto-update is set to 'on' but an error occurred (maybe the issuer could not be found)

I was able to reproduce this error with an arbitrary self-signed certificate. There's not much I can do about it right now. The best workaround would probably be to avoid self-signed certificates if OCSP auto updates are enabled (use ACME certificates instead).

My gut feeling is that this may be a limitation or bug in HAProxy. I've reported this to the HAProxy project to get a confirmation.

**Please note that I consider the initially reported bug fixed. Everything else should be reported as NEW issues.** Every bug deserves it's own issue. :grin: Thanks!
