### ISSUE TITLE
Feature Request: IDS Alerts

### ISSUE THREAD

**Issue by tpcr** [opnsense/plugins#378]
I would like to see the IDS alerts page also show source and destination ports and which interface it was generated on in the main IDS alert listing. A choice of which categories to display would also be helpful.

**Comment by fabianfrz** [comment]
IDS is in `core`. Are you sure that this should be posted here?

**Comment by tpcr** [comment]
I am requesting an addition to the list of displayed alerts in IDS in the WebGUI. This dropdown list should show the ports and the interface. I know the ports are shown in the detail, but they should also be shown in the list. The Interface that triggered the alert is not shown anywhere which is useful when IDS is attached to multiple interfaces

**Comment by fabianfrz** [comment]
The issue tracker for `core` is here: https://github.com/opnsense/core/issues

Plugins is everything you can install via the plugins menu (system -> firmware).

**Comment by tpcr** [comment]
Thanks, I will post in core. Admin, please delete this thread.

**Comment by fabianfrz** [comment]
@tpcr We cannot delete it - but I can close it.
