### ISSUE TITLE
Captive Portal Customize Vouchers System

### ISSUE THREAD

**Issue by WaqarAliSofi** [opnsense/plugins#3780]
My clients are facing difficulties when trying to log in using the vouchers I provide. The current voucher format is somewhat complicated for them. Here's the current format as an example:

Voucher Format:
Username: Gj54b#
Password: v&Td4s

I'm interested in simplifying this format, perhaps by using just a voucher number or even by combining the username and password into a single numeric code. Is it feasible to use only numeric codes for authentication? Your input on this matter would be greatly appreciated.

Can someone create a plugin regarding this to enhance the experience?

**Comment by AdSchellevis** [comment]
please don't spam our Github on multiple repo's and use our templates in the correct one (core)
