### ISSUE TITLE
DNSCrypt Should Be Updated to 2.0.46 To Enable ODOH Support

### ISSUE THREAD

**Issue by ilikenwf** [opnsense/plugins#3783]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**

DNSCrypt should be updated to support odoh instead of just anonymous DNS. Additionally, it may be prudent to better document it or update the documentation sometime as it is out of date.

See https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Oblivious-DoH for information on the 2.0.46+ requirement for ODOH.

**Comment by fichtner** [comment]
It should, but it should also be said someone should do it, which is the initial problem. ;)
