### ISSUE TITLE
Hetzner dyndns console is missing after update to OPNsense 24.1_1-amd64 FreeBSD 13.2-RELEASE-p9 OpenSSL 3.0.12

### ISSUE THREAD

**Issue by dstr-wpd** [opnsense/plugins#3786]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [ x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [ x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x ] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
I just updated to OPNsense 24.1_1-amd64 FreeBSD 13.2-RELEASE-p9 OpenSSL 3.0.12 and the hetzner dyndns client is missing in ddclient configuration.
Anybody know how to get it back?
Thanks

**Describe the solution you'd like**
Using Hetzner dyndns console again. Can I revert to the point it is available again?

**Describe alternatives you've considered**
There is no

**Additional context**

**Comment by fichtner** [comment]
Switch to ddclient backend in plugin settings?

**Comment by dstr-wpd** [comment]
using ddclient already, not legacy.

new: ddclient | 3.11.2_1 | 340KiB | OPNsense | GPLv2+ | Update dynamic DNS entries

old: ddclient | 3.11.2_1 | 340KiB | OPNsense | GPLv2+ | Update dynamic DNS entries

same version number, just dropped configuration support

**Comment by dstr-wpd** [comment]
thats the solution, thanks
