### ISSUE TITLE
security/acme-client: deploy hook synology_dsm is not found

### ISSUE THREAD

**Issue by dwydler** [opnsense/plugins#3787]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [ ] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
I use the ACME client on the firewall to retrieve a certificate from LE for the firewall and my Synology NAS. Retrieving/renewing the certificates works without any problems after the update. However, the automation can no longer upload and set up the certificate on the Synology NAS.

**To Reproduce**
1. Install the plugin os-acme-client 4.0.
2. Go to Services: ACME Client: Automations
3. Services: ACME Client: Automations
4. Go to Services: ACME Client: Certificates
5. Add a new certificate which all required parameters and choose the previous automation.
6. Issue/renew the certifcate
7. See error

**Expected behavior**
Uploading the new certificate to the Synology NAS.

**Relevant log files**
```
/var/etc/acme-client/home # /usr/local/sbin/acme.sh --deploy --syslog 7 --debug 3 --server 'letsencrypt' --home '/var/etc/acme-client/home' --cert-home '/var/etc/acme-client/cert-home/65bab319d1d882.49786135' --certpath '/var/etc/acme-client/certs/65bab319d1d882.49786135/cert.pem' --keypath '/var/etc/acme-client/keys/65bab319d1d882.49786135/private.key' --capath '/var/etc/acme-client/certs/65bab319d1d882.49786135/chain.pem' --fullchainpath '/var/etc/acme-client/certs/65bab319d1d882.49786135/fullchain.pem' --domain 'dev.name.domain.de' --deploy-hook synology_dsm
[Wed Jan 31 22:24:15 CET 2024] _is_idn_d='dev.name.domain.de'
[Wed Jan 31 22:24:15 CET 2024] _idn_temp
[Wed Jan 31 22:24:15 CET 2024] _selectServer try snames='zerossl.com,zerossl'
[Wed Jan 31 22:24:15 CET 2024] _selectServer try snames='letsencrypt.org,letsencrypt'
[Wed Jan 31 22:24:15 CET 2024] _selectServer match letsencrypt
[Wed Jan 31 22:24:15 CET 2024] Selected server: https://acme-v02.api.letsencrypt.org/directory
[Wed Jan 31 22:24:15 CET 2024] readlink exists=0
[Wed Jan 31 22:24:15 CET 2024] dirname exists=0
[Wed Jan 31 22:24:15 CET 2024] Lets find script dir.
[Wed Jan 31 22:24:15 CET 2024] _SCRIPT_='/usr/local/sbin/acme.sh'
[Wed Jan 31 22:24:15 CET 2024] _script='/usr/local/sbin/acme.sh'
[Wed Jan 31 22:24:15 CET 2024] _script_home='/usr/local/sbin'
[Wed Jan 31 22:24:15 CET 2024] Using config home:/var/etc/acme-client/home
[Wed Jan 31 22:24:15 CET 2024] ACCOUNT_CONF_PATH='/var/etc/acme-client/home/account.conf'
[Wed Jan 31 22:24:15 CET 2024] logger exists=0
[Wed Jan 31 22:24:15 CET 2024] OK
[Wed Jan 31 22:24:15 CET 2024] 2:SYS_LOG='7'
[Wed Jan 31 22:24:15 CET 2024] LE_WORKING_DIR='/var/etc/acme-client/home'
https://github.com/acmesh-official/acme.sh
v3.0.7
[Wed Jan 31 22:24:15 CET 2024] Using server: https://acme-v02.api.letsencrypt.org/directory
[Wed Jan 31 22:24:15 CET 2024] Running cmd: deploy
[Wed Jan 31 22:24:15 CET 2024] Using config home:/var/etc/acme-client/home
[Wed Jan 31 22:24:15 CET 2024] ACCOUNT_CONF_PATH='/var/etc/acme-client/home/account.conf'
[Wed Jan 31 22:24:15 CET 2024] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Wed Jan 31 22:24:15 CET 2024] _ACME_SERVER_HOST='acme-v02.api.letsencrypt.org'
[Wed Jan 31 22:24:15 CET 2024] _ACME_SERVER_PATH='directory'
[Wed Jan 31 22:24:15 CET 2024] CA_CONF='/var/etc/acme-client/home/ca/acme-v02.api.letsencrypt.org/directory/ca.conf'
[Wed Jan 31 22:24:15 CET 2024] DOMAIN_PATH='/var/etc/acme-client/cert-home/65bab319d1d882.49786135/dev.name.domain.de'
[Wed Jan 31 22:24:15 CET 2024] DOMAIN_CONF='/var/etc/acme-client/cert-home/65bab319d1d882.49786135/dev.name.domain.de/dev.name.domain.de.conf'
[Wed Jan 31 22:24:15 CET 2024] OK
[Wed Jan 31 22:24:15 CET 2024] 22:Le_DeployHook='synology_dsm,'
[Wed Jan 31 22:24:15 CET 2024] The deploy hook synology_dsm is not found.
```

**Additional context**
The automation works last year on OPNsense 23.7.

**Environment**
OPNsense 24.1_1-amd64
os-acme-client 4.0.
Synology DSM 7.2-64570 Update 3

**Comment by fraenki** [comment]
Please switch `Log Level` to "debug 3" in Services->ACME Client->Settings and try again. (Note that debug logging causes the log to look somewhat scrambled in the GUI, this is expected.)

Afterwards the Acme Log should contain an entry for "_deployApi", this is what I'm looking for. :)

**Comment by dwydler** [comment]
> Please switch Log Level to "debug 3" in Services->ACME Client->Settings and try again.

I set the debug level over the UI to "debug 3" and reproduced the problem without restarting the acme client service.

> Afterwards the Acme Log should contain an entry for "_deployApi", this is what I'm looking for. :)

In the log file `/var/log/acmeclient/latest.log` are no entries from today. The log file `/var/log/acme.sh.log` is emtpy.
So which log file do you mean?

In the UI under ACME Client -> Log Files -> System Log i see only follow line:
```
AcmeClient: running acme.sh command: /usr/local/sbin/acme.sh --deploy --syslog 7 --debug 3 --server 'letsencrypt' --home '/var/etc/acme-client/home' --cert-home '/var/etc/acme-client/cert-home/65baaa65500538.29028643' --certpath '/var/etc/acme-client/certs/65baaa65500538.29028643/cert.pem' --keypath '/var/etc/acme-client/keys/65baaa65500538.29028643/private.key' --capath '/var/etc/acme-client/certs/65baaa65500538.29028643/chain.pem' --fullchainpath '/var/etc/acme-client/certs/65baaa65500538.29028643/fullchain.pem' --domain 'dev.name.domain.de' --deploy-hook synology_dsm
```

**Comment by fraenki** [comment]
> /var/etc/acme-client/home # /usr/local/sbin/acme.sh ...

I strongly advice against running acme.sh manually on OPNsense. This may easily cause arbitrary issues.

> without restarting the acme client service

What do you mean by that? How would you restart the acme client service?

> In the log file /var/log/acmeclient/latest.log are no entries from today.

The log is empty even after you rerun the automation? Then you're probably affected by another bug, try this patch:

```
opnsense-patch -c plugins 84644d4a
```

Then rerun the automation.

**Comment by dwydler** [comment]
With the patch is written back to the log file. Thanks.

But the restart of the web service on the synology nas was not possible:
```
2024-02-08T15:56:31	acme.sh	[Thu Feb 8 15:56:31 CET 2024] Success
2024-02-08T15:56:31	acme.sh	[Thu Feb 8 15:56:31 CET 2024] ret='0'
2024-02-08T15:56:30	acme.sh	[Thu Feb 8 15:56:30 CET 2024] _CURL='curl --silent --dump-header /var/etc/acme-client/home/http.header -L --trace-ascii /tmp/tmp.f2kXq4N2 -g '
2024-02-08T15:56:30	acme.sh	[Thu Feb 8 15:56:30 CET 2024] timeout=
2024-02-08T15:56:30	acme.sh	[Thu Feb 8 15:56:30 CET 2024] url='http://192.168.52.6:5000/webapi/entry.cgi?api=SYNO.API.Auth&version=7&method=logout'
2024-02-08T15:56:30	acme.sh	[Thu Feb 8 15:56:30 CET 2024] GET
2024-02-08T15:56:30	acme.sh	[Thu Feb 8 15:56:30 CET 2024] Restarting HTTP services failed
2024-02-08T15:56:30	acme.sh	[Thu Feb 8 15:56:30 CET 2024] _ret='0'
2024-02-08T15:56:21	acme.sh	[Thu Feb 8 15:56:21 CET 2024] _CURL='curl --silent --dump-header /var/etc/acme-client/home/http.header -L --trace-ascii /tmp/tmp.pB712unu -g '
```
The user being used is a member of the "Administrators" group on the NAS. The upload of the le certificate was successfully. After an manually restart of the http service it is also used. 

Do you have an idea, what can be the root cause?

**Comment by fraenki** [comment]
So this is actually a completely different error it seems? I can't help you with that, I don't know anything about Synology NAS.

**Comment by dwydler** [comment]
My understanding is that the error is caused by the ACME client, by the automation for Synology.
Who is in your opinion the correct maintainer?

**Comment by fraenki** [comment]
os-acme-client only integrate acme.sh, so you may search in their issue tracker to find out whether your issue was already reported (or resolved):

https://github.com/acmesh-official/acme.sh/issues?q=is%3Aissue+synology+is%3Aopen (open issues)
https://github.com/acmesh-official/acme.sh/issues?q=is%3Aissue+synology+is%3Aclosed (closed issues)

(The acme.sh project usually recommends bug reporters to manually upgrade acme.sh, but _don't do this on OPNsense_.  It may break os-acme-client now or at any point in the future.)

**Comment by kulikov-a** [comment]
@dwydler 

> _CURL='curl --silent --dump-header /var/etc/acme-client/home/http.header -L --trace-ascii /tmp/tmp.f2kXq4N2 -g '

i think /tmp/tmp.f2kXq4N2 should containt api call and syno response.
if response is success but not contains "restart_httpd":true, acme.sh throws "Restarting HTTP services failed"

**Comment by dwydler** [comment]
> i think /tmp/tmp.f2kXq4N2 should containt api call and syno response.
> if response is success but not contains "restart_httpd":true, acme.sh throws "Restarting HTTP services failed"

I think so too. The file is created when the automation for Synology starts, executed and then deleted.

So far I have not found a way in the ACME client on the OPNsense to explicitly configure the parameter. Neither in the general settings nor in the automation settings for the Synology NAS

**Comment by fraenki** [comment]
> So far I have not found a way in the ACME client on the OPNsense to explicitly configure the parameter.

It's not a configurable parameter. It's just a part of the Synology's response: `"restart_httpd":true` [only indicates whether or not the Synology was able to restart the webservice](https://github.com/acmesh-official/acme.sh/blob/de14d59bb38acc66972787e1f4b058b02619c933/deploy/synology_dsm.sh#L208-L222). [This post](https://github.com/acmesh-official/acme.sh/pull/4646#issuecomment-1673796844) discusses the restart issue and hints at a possible solution. That's all I could find.
