### ISSUE TITLE
os-squid: Add support for `tls_key_log`

### ISSUE THREAD

**Issue by 0xThiebaut** [opnsense/plugins#3788]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
Squid allows for transparent HTTPS proxying which, alongside interface diagnostics' ability to capture PCAPs, provides a sufficient setup to analyze TLS traffic (e.g., malware analysis lab). The current Squid options however do not include the activation of the [`tls_key_log`](http://www.squid-cache.org/Doc/config/tls_key_log/) feature, making it hard/impossible to decrypt captured TLS traffic.

**Describe the solution you'd like**
I would like a `Record TLS connection pre-master secret and encryption details` checkbox within the `Squid Web Proxy` service's `Administration` panel (under the `Forward Proxy`'s `General Forward Settings`[^1]). The checkbox would enable the [`tls_key_log`](http://www.squid-cache.org/Doc/config/tls_key_log/) feature and provide a UI similar to the current "cache", "access" and "store" logs to browse/download the TLS secrets for later analysis in Wireshark.

**Describe alternatives you've considered**
I have considered exporting the per-domain private-keys generated by Squid but these would [not allow the decryption of TLS 1.3](https://gitlab.com/wireshark/wireshark/-/wikis/TLS/#tls-decryption).

**Additional context**
N/A

[^1]: URL: `/ui/proxy#subtab_proxy-forward-general`

**Comment by AdSchellevis** [comment]
close with PR (https://github.com/opnsense/plugins/pull/3789#issuecomment-2081114580)
