### ISSUE TITLE
EuroDNS support for ACME Client Plugin

### ISSUE THREAD

**Issue by Kiritzai** [opnsense/plugins#3800]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
Would like to use DNS-01 for EuroDNS in combination with HAProxy, cause the HTTP-01 is really unreliable.

**Describe the solution you'd like**
EuroDNS support for the ACME Client plugin, so the DNS-01 can be used.

**Describe alternatives you've considered**
Tried HTTP-01 with ACME Client plugin, seem to be hit or miss so it's really unreliable at the moment.

**Comment by fraenki** [comment]
It looks like EuroDNS is not yet supported in the os-acme-client upstream project:
https://github.com/acmesh-official/acme.sh/issues/3443

I can only integrate DNS APIs in os-acme-client that are supported by acme.sh.
