### ISSUE TITLE
os-ddclient 1.20_2 - ddclient updates GoDaddy DNS entry every 300s even if dynamic IP has not changed

### ISSUE THREAD

**Issue by phaze75** [opnsense/plugins#3805]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**

I just changed my ddclient from using FreeDNS to using GoDaddy. The dynamic ip has been checked properly (via Interface/WAN) and the respective GoDaddy DNS entry has been updated correctly. However, ddclient now seems to "statically/periodically" update the GoDaddy DNS entry every 300 seconds (as configured in ddclient's general settings), **even if the dynamic ip has not changed.**

ddclient using GoDaddy now shows a different behavior compared to using FreeDNS. Using FreeDNS, the DNS entry was only updated if the dynamic IP had been changed by the provider.

**To Reproduce**
1. Within ddclient create a new account
2. Set "Service" to "GoDaddy"
3. Enter "Username", "Password", "Zone", "Hostname"
4. Set "IP check method" to "Interface"
5. Set "Interface to monitor" to "WAN"
6. Set "Check ip timeout" to "10"
7. Set "Force SSL" to "enabled"
8. Enable account.

**Expected behavior**
Initially, the dynamic IP should be checked, and the "Hostname" should be updated once. After the initial update of the "Hostname" ddclient should continuously check if the dynamic IP has been changed by the provider and only update "Hostname" in case it has been changed.

**Relevant log files**
Date
Severity
Process
Line
2024-02-07T10:30:24	Notice	ddclient	SUCCESS: dxxxxxxxxxxt -- Updated successfully to 8xxxxxxxxxx2 (status: 200).	
2024-02-07T10:25:23	Notice	ddclient	SUCCESS: dxxxxxxxxxxt -- Updated successfully to 8xxxxxxxxxx2 (status: 200).	
2024-02-07T10:20:21	Notice	ddclient	SUCCESS: dxxxxxxxxxxt -- Updated successfully to 8xxxxxxxxxx2 (status: 200).	
2024-02-07T10:15:19	Notice	ddclient	SUCCESS: dxxxxxxxxxxt -- Updated successfully to 8xxxxxxxxxx2 (status: 200).	
2024-02-07T10:10:17	Notice	ddclient	SUCCESS: dxxxxxxxxxxt -- Updated successfully to 8xxxxxxxxxx2 (status: 200).	
2024-02-07T10:05:15	Notice	ddclient	SUCCESS: dxxxxxxxxxxt -- Updated successfully to 8xxxxxxxxxx2 (status: 200).	
2024-02-07T10:00:13	Notice	ddclient	SUCCESS: dxxxxxxxxxxt -- Updated successfully to 8xxxxxxxxxx2 (status: 200).	
2024-02-07T09:55:12	Notice	ddclient	SUCCESS: dxxxxxxxxxxt -- Updated successfully to 8xxxxxxxxxx2 (status: 200).	
2024-02-07T09:50:10	Notice	ddclient	SUCCESS: dxxxxxxxxxxt -- Updated successfully to 8xxxxxxxxxx2 (status: 200).	
2024-02-07T09:45:08	Notice	ddclient	SUCCESS: dxxxxxxxxxxt -- Updated successfully to 8xxxxxxxxxx2 (status: 200).

**Environment**

OPNsense 24.1.1-amd64
FreeBSD 13.2-RELEASE-p9
OpenSSL 3.0.13
AMD GX-412TC SOC (4 cores, 4 threads)

**Comment by phaze75** [comment]
Any comments?

**Comment by fichtner** [comment]
Sure, have you looked for upstream bugs? https://github.com/ddclient/ddclient/issues

**Comment by phaze75** [comment]
To my understanding the "caching/spamming" issue has been fixed with the release of v3.11 in October 2023. The actual version is v3.11.2. 

[https://github.com/ddclient/ddclient/issues/552](url)

So, if the issue has been officially fixed on the ddclient side, maybe my issue is related to its implementation (plugin) into opnsense?

**Comment by fichtner** [comment]
If the bug is that we start the service script perhaps, but I doubt that we have influence on the internal renew timer or the way it handles these renews.

https://github.com/ddclient/ddclient/commit/f5a1a906d1cd53665490203252c116a7762d1121 was committed two weeks ago. 3.11.2 was released last year? ;)

**Comment by phaze75** [comment]
![image](https://github.com/opnsense/plugins/assets/2933023/bc2f4951-6d7a-4040-a787-b4f8bbf51761)

Well, I have no idea about how the plugin is implemented. But if I have an issue I start with the provider of the plugin. At least according to my logic.

**Comment by fichtner** [comment]
Again, the relevant commit is only 2 weeks old.

**Comment by phaze75** [comment]
![image](https://github.com/opnsense/plugins/assets/2933023/bd176bba-7ee8-4587-84a9-4d0156b24415)


Have you read the release notes of your own plugin os-ddclient? The release notes of your plugin tell me, that os-ddclient v1.17 has been updated to ddclient v.3.11.1. The actual version of your os-ddclient is v1.20_2. So?

**Comment by phaze75** [comment]
So, after spending most of your community time with me on trying to prove me wrong you could now finally agree to the fact that the officially fixed version v3.11.2+ (latest release + additional fix) of ddclient is part of your actual plugin os-ddclient v1.20_2. One step forward. Sorry for my sarcasm.

What next? Do you investigate the issue as the author of the plugin? Or do I need to go upstream and address the issue with ddclient?

**Comment by fichtner** [comment]
You could be productive and see that commit I posted is actually in the software you complain about which isn't us. If it isn't apply the patch and tell me if it works.

That would be an ideal way to stop wasting my time by acting like an entitled child. :)

**Comment by phaze75** [comment]
See it as a chance for self-reflection. Have you ever thought about the fact that not everybody trying to contribute here - like me - is a technical expert navigating the depths of Github with ease? So instead of accusing _me_ of wasting your time you deliberately chose to invest in proving me being an idiot - which backfired gloriously - _you_ could be productive by instructing me specifically and in detailed steps - like for the idiot that I seem to be - what to do next. Because I have no idea about what you are suggesting.

**Comment by fichtner** [comment]
> See it as a chance for self-reflection.

Yeah, I couldn't agree more.

To be frank I'm unsure what you expect of me and why you feel the need to be abusive towards me (and probably others). I've nothing but helped you and answer your questions.

I'm not here to test upstream changes that might be relevant to you. I'm not here to take a bit of abuse from a random reporter. In fact don't mistake my replies for anything else but honest help, but feel free to still tell me I'm the only problem.

I might be your problem right now, but that's only because you don't know how to solve it. But you are too tough to even ask for help. ;)

**Comment by phaze75** [comment]
> Yeah, I couldn't agree more.

Obviously not.

> To be frank I'm unsure what you expect of me and why you feel the need to be abusive towards me (and probably others). I've nothing but helped you and answer your questions.

Seriously? Ok, so I also add "abuser" to the list. If it suits you... ;-)

> I might be your problem right now, but that's only because you don't know how to solve it yourself. But you are too tough to even ask for help. ;)

If I could have solved the issue by myself, I wouldn't have opened this issue. And the opening of an issue imho implies asking for support or help. Sounds logical? However, supporting implies to _noticeably_ put yourself into the shoes of the one supported, rather than to simply deflect the issue. Otherwise, it is not supporting, it's gatekeeping. And that's how I experienced it.

**Comment by fichtner** [comment]
I think you are simply asking a lot in the worst way possible. We would have already solved this if you followed my hint to the commit which I still will not do for you for at least the reason that I don't have a GoDaddy account to test this. But it is what it is.

**Comment by phaze75** [comment]
> I think you are simply asking a lot in the worst way possible.

Then we share at least a comparable experience. As sad as it is.

> We would have already solved this if you followed my hint to the commit

I _still_ don't have a clue what to do with the two committed files [ddclient.conf.in](https://github.com/ddclient/ddclient/commit/f5a1a906d1cd53665490203252c116a7762d1121#diff-94694f8e9f7ecf132087e6de55d892dd579834e555b9be5883331b7609f214ae) and [ddclient.in](https://github.com/ddclient/ddclient/commit/f5a1a906d1cd53665490203252c116a7762d1121#diff-253dbf535718fb269f5bdb7ebcd6b98d65b198ca49cda8e4bdedbc0bc9a7a417).

**Comment by phaze75** [comment]
There is a likely fix for this issue: https://github.com/ddclient/ddclient/pull/670. Unfortunately, I could not test it, as GoDaddy recently updated their account requirements to access parts of their production Domains API and I have lost access.

**Comment by fichtner** [comment]
Since a lot of changes are piling up for 3.11.3 on their end I'd rather wait for an official release package.
