### ISSUE TITLE
[Solved Probably?] OpnSense 24.1.2 -> os-wireguard Missing

### ISSUE THREAD

**Issue by Ramalama2** [opnsense/plugins#3812]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

```
***GOT REQUEST TO INSTALL***
Currently running OPNsense 24.1.1 at Sat Feb 10 14:25:28 CET 2024
Updating OPNsense repository catalogue...
OPNsense repository is up to date.
All repositories are up to date.
pkg: No packages available to install matching 'os-wireguard' have been found in the repositories
Checking integrity... done (0 conflicting)
Nothing to do.
***DONE***
```

After the Update to 24.1.1 Wireguard was still there and working. (And after a reboot it was still there and working)
After the small update to 24.1.2 (Which is 24.1.1 with some updated Packages) wireguard was still working, but after a reboot, the package is missing and i cannot install it, because its missing entirely in the Package Repositories.

This is definitively reproducible on all my servers, since i lost the S2S Connection entirely to all Servers xD

Under the "Packages" Tab its still there, but not working anyway:
![image](https://github.com/opnsense/plugins/assets/6314556/9c94a6ca-eff2-4225-a9f7-faca868fad76)

EDIT:
After another reboot, its working! my S2S connection is back :-)
But there is no install Package anymore? Is it now entirely integrated into OpnSense?

Cheers

**Comment by Ramalama2** [comment]
Its Integrated into Core, glad god, false alarm!

Thanks guys for Providing all the updates and Hard work !
My Fault, sorry, cheers :-)

**Comment by TheChuckster** [comment]
Any way to remove the package from the list now that it's intentionally defunct?

**Comment by AdSchellevis** [comment]
`System: Firmware` :
<img width="670" alt="image" src="https://github.com/opnsense/plugins/assets/9783985/79aaf16d-b725-4fe9-9cd1-07045df24df2">

**Comment by gloriousjob** [comment]
I know this is closed but should this doc be updated? Until I found this issue, I thought I broke something because this page indicates that the plugin should be installed:
https://docs.opnsense.org/manual/how-tos/wireguard-client.html

**Comment by AdSchellevis** [comment]
@gloriousjob sure, https://github.com/opnsense/docs/commit/ac586586b2ebc9a81d40a352a7f7d4ad76c89587

**Comment by gloriousjob** [comment]
Thanks, appreciate the quick response!
