### ISSUE TITLE
ACME certificates command column too narrow, os-theme-cicada & os-theme-rebellion

### ISSUE THREAD

**Issue by Taomyn** [opnsense/plugins#3816]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
The two themes, cicada and rebellion, do not format the command column in ACME certificates, and it's too narrow to easily use the final commands. For the standard opnsense theme it's fine

I think it would be great if throughout the OPNsense GUI that columns could simply be adjustable and re-ordered as often even removing a column ends up with the wrong ones getting re-sized, which is the case for the one I'm reporting. Perhaps a future enhancement, but for now simply being able to quickly tap the delete icon would be great, as trying to move the mouse to just the right part of the "..." is tricky.

**To Reproduce**
1. Change theme to either cicada or rebellion
2. Go to ACME, Certificates
3. Final commands column is truncated

**Expected behavior**
Format the commands column like the opnsense theme

**Screenshots**
![image](https://github.com/opnsense/plugins/assets/4365929/f1ba7d37-5ae5-4859-8cb5-2c7ac2061be5)
![image](https://github.com/opnsense/plugins/assets/4365929/06ba5c72-91ab-4f0a-8c32-a6f55407c507)

**Relevant log files**
n/a

**Additional context**
I'm normally using Brave browser, but Edge does the same.

**Environment**
OPNsense 24.1.1-amd64
FreeBSD 13.2-RELEASE-p9
OpenSSL 3.0.13
![image](https://github.com/opnsense/plugins/assets/4365929/c0740325-4a5d-49ea-9bf6-4c93b8743874)

**Comment by opnsenseuser** [comment]
![grafik](https://github.com/opnsense/plugins/assets/34602360/fa21431e-d44b-4dcf-901a-84835a4bb041)
maybe we can change the width to auto? its hardcoded in the main opnsense html structure.
other way would be to make a seperate class for th#commands with "width:auto;"
don´t know whats the best way to fix this.

**Comment by opnsenseuser** [comment]
@marjohn56 

ok found the problem. I compared the working main.css from opnsense/vicuna theme with the main.css from cicada and found the problem.

problem:
![grafik](https://github.com/opnsense/plugins/assets/34602360/0322c909-5502-4218-9ea7-6654da3fa0f1)

fix:
![grafik](https://github.com/opnsense/plugins/assets/34602360/30cb7582-b90d-4305-b7ef-b796ca5498eb)

.btn-xs, .btn-group-xs > .btn {
  padding: 1px 4px; }

on every other theme i made there are no problems. (tukan, vicuna)

**Comment by opnsenseuser** [comment]
@marjohn56 if you want, i can fix it for theme rebellion too.

**Comment by opnsenseuser** [comment]
@marjohn56 i fixed it for theme rebellion too.

**Comment by marjohn56** [comment]
Hi,

Just about to do it this morning and then I read your email!

Thank you very much.😊

KR

Martin

**Comment by opnsenseuser** [comment]
https://github.com/opnsense/plugins/pull/3839
