### ISSUE TITLE
NRPE move from package to plugin on 24.1

### ISSUE THREAD

**Issue by michaelschefczyk** [opnsense/plugins#3817]
**Important notices**
Yes. I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
Yes, I have searched the existing issues, open and closed, and I'm convinced that mine is new.
The title contains the plugin to which this issue belongs

**Describe the bug**

Before upgrading to OPNSENSE 24.1, I did use NRPE via the manually installed package. I had/have a LAN firewall rule pointing port 5666/tcp from the LAN network or address to "This Firewall".

After upgrading - which did remove the manually installed package - and moving to the plugin, external calls to NRPE always generate: CHECK_NRPE STATE CRITICAL: Socket timeout after 10 seconds. I do not find relevant log entries on the firewall.

Posting in the forum does not yield results. Hence, there will either be a bug in the NRPE plugin or at least a lack of documentation.

**To Reproduce**
1. Install NRPE plugin and set it up
2. ssh to OPNSENSE and verify that check commands work, e. g, by typing /usr/local/libexec/nagios/check_users -w 5 -c 10
3. ssh to OPNSENSE and verify that /usr/local/etc/nrpe.cfg does contain a configuration matching GUI input
4. ssh to OPNSENSE and verify that /usr/local/etc/nrpe_commands.cfg does contain the commands matching GUI input
5. Try combinations of it listening to either localhost, 0.0.0.0 or the LAN interface with or without a firewall rule for 5666/tcp
6. Try adding /usr/local/bin/sudo before commands (i. e. /usr/local/libexec/nagios/check_users or the like) or not adding sudo.
7. Try adding nrpe user to sudoers like so: https://forum.opnsense.org/index.php?topic=30097.0
8. Execute NRPE from an allowed host and verify if there is valid feedback or not

**Expected behavior**
Allowed hosts get meaningful responses to nrpe commands.

Please inform me, if the NRPE plugin is working with OPNSENSE 24.1 in general and if so, what I might be missing. Documentation as to if the plugin should listen to localhost, 0.0.0.0 or LAN and if a (which) firewall rule is required would be a big plus to avoid such questions.

**Comment by mimugmail** [comment]
Can you post what happens after 2-8? Its just guessing without any input

**Comment by michaelschefczyk** [comment]
Thank you very much @mimugmail

My setup is Port 5666, Listen Address 0.0.0.0, Allowed Hosts: Those from which I am querrying plus 127.0.0.1 Allow Arguments plus a LAN Firewall rule forwarding 5666/tcp to “This Firewall” (same problem with or without this rule and with Listen Address LAN IP). Please let me know if I shoud try other variants. The LAN ip is 192.168.0.1

The output per step is:

2. Typing on the OPNSENSE console: /usr/local/libexec/nagios/check_users -w 5 -c 10

yields: USERS OK - 1 users currently logged in |users=1;5;10;0

3. /usr/local/etc/nrpe.cfg contains:

log_facility=daemon
log_file=/var/log/nrpe.log
debug=0
pid_file=/var/run/nrpe/nrpe.pid
nrpe_user=nagios
nrpe_group=nagios

server_port=5666
server_address=0.0.0.0
allowed_hosts=192.168.12.30,192.168.12.40,127.0.0.1
command_timeout=60
connection_timeout=300
dont_blame_nrpe=1
allow_bash_command_substitution=0
include=/usr/local/etc/nrpe_commands.cfg

4. /usr/local/etc/nrpe_commands.cfg contains:

command[check_users]=/usr/local/bin/sudo /usr/local/libexec/nagios/check_users -w 5 -c 10
command[check_load]=/usr/local/bin/sudo /usr/local/libexec/nagios/check_load -w 6,4,2 -c 12,10,8

(variant without /usr/local/bin/sudo does not work either).

5.+6. Just describe variants tried

7. Typed (with no feedback): echo "nagios ALL=(ALL) NOPASSWD: /usr/local/libexec/nagios" > /usr/local/etc/sudoers.d/nrpe

8. From 192.168.12.30 (command did work before OPNSENSE 24.1 with the NRPE system package):
/usr/lib/nagios/plugins/check_nrpe -H 192.168.0.1 -c check_users

Output:
CHECK_NRPE: Error - Could not connect to 192.168.0.1. Check system logs on 192.168.0.1

nrpe.log contains: [1708418745] Host 192.168.0.3 is not allowed to talk to us!

Added 192.168.0.3 to allowed hosts (without understanding the background of the error) so that . /usr/local/etc/nrpe.cfg contains:

log_facility=daemon
log_file=/var/log/nrpe.log
debug=0
pid_file=/var/run/nrpe/nrpe.pid
nrpe_user=nagios
nrpe_group=nagios

server_port=5666
server_address=0.0.0.0
allowed_hosts=192.168.12.30,192.168.12.40,127.0.0.1,192.168.0.1,192.168.0.2,192.168.0.3
command_timeout=60
connection_timeout=300
dont_blame_nrpe=1
allow_bash_command_substitution=0
include=/usr/local/etc/nrpe_commands.cfg

Then the feedback to /usr/lib/nagios/plugins/check_nrpe -H 192.168.0.1 -c check_users 
from 192.168.12.30 changes to:

NRPE: Unable to read output
with no entries in nrpe.log

I have no clue as to what to try next.

**Comment by mimugmail** [comment]
Can you set debug=1 to /usr/local/etc/nrpe.cfg and service nrpe restart via CLI then check again from remote and check for logs? (a save in gui will overwrite the config so stick to CLI)
