### ISSUE TITLE
Every ACME Automation results in Crash Report

### ISSUE THREAD

**Issue by JoTec2002** [opnsense/plugins#3820]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
Everytime I run an Certificate Deployment it results in an Crash Report. I tried with deployment to Synology NAS and Proxmox.
I have a "fresh" installation of OPNsense it never worked.

**To Reproduce**
1. Go to Services > ACME Client > Certificates
2. Click on 'Run Automations'
3. See error

**Expected behavior**
Deploy the SSL Certificate to Proxmox / Synology NAS.

**Screenshots**

**Relevant log files**
Crash Report:
`[16-Feb-2024 09:09:50 Europe/Berlin] PHP Fatal error:  Uncaught TypeError: proc_open(): Argument #2 ($descriptor_spec) must be of type array, null given in /usr/local/opnsense/mvc/app/library/OPNsense/AcmeClient/LeAutomation/Base.php:133
Stack trace:
#0 /usr/local/opnsense/mvc/app/library/OPNsense/AcmeClient/LeAutomation/Base.php(133): proc_open('/usr/local/sbin...', NULL, NULL, NULL, Array)
#1 /usr/local/opnsense/mvc/app/library/OPNsense/AcmeClient/LeAutomation/Base.php(106): OPNsense\AcmeClient\LeAutomation\Base->runAcme()
#2 /usr/local/opnsense/mvc/app/library/OPNsense/AcmeClient/LeCertificate.php(606): OPNsense\AcmeClient\LeAutomation\Base->run()
#3 /usr/local/opnsense/scripts/OPNsense/AcmeClient/lecert.php(188): OPNsense\AcmeClient\LeCertificate->runAutomations()
#4 /usr/local/opnsense/scripts/OPNsense/AcmeClient/lecert.php(199): main()
#5 {main}
  thrown in /usr/local/opnsense/mvc/app/library/OPNsense/AcmeClient/LeAutomation/Base.php on line 133`

No error logs under:
Services > ACME Clients > Logs (Debug 3 enabled)

**Additional context**

**Environment**
Software version used and hardware type if relevant.

User-Agent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
FreeBSD 13.2-RELEASE-p9 stable/24.1-n254969-8659880248c SMP amd64
OPNsense 24.1.1 516bda3fc
Plugins os-acme-client-4.0
Time Fri, 16 Feb 2024 09:12:14 +0100
OpenSSL 3.0.13
Python 3.9.18
PHP 8.2.15

**Comment by kulikov-a** [comment]
i think it discussed at https://github.com/opnsense/plugins/issues/3790 and the fix is planned for 4.1 release https://github.com/opnsense/plugins/pull/3806/files
