### ISSUE TITLE
Indefinitely duplicated ip/port in os-upnp

### ISSUE THREAD

**Issue by roylaprattep** [opnsense/plugins#3831]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ Y ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ Y ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

My last bug report was deleted. Can you please solve, give me a workaround or a direction I can go before closing... Instead of manual port forward.

There is a serious bug with os-upnp since latest version fresh install. The status list is deduplicating same entries again and again which means that the status log is growing indefinitely.

Everything was working perfectly fine on 23.7 and associated version.

Thank you very much guys.

**To Reproduce**

Go to "Services"
Click on "Universal Plug and Play"
Then click "Status"
See bug

**Expected behavior**

One entry per port/IP.

**Screenshots**

![image](https://github.com/opnsense/core/assets/20898294/0b365839-be96-40ed-b910-1533d1192c4d)
![image](https://github.com/opnsense/core/assets/20898294/37e33b24-f703-4c02-b96a-c475591c9101)
![image](https://github.com/opnsense/core/assets/20898294/93fab363-507f-4c0a-8ec4-25b6ddae6b6c)

**Environment**

-OPNsense 24.1.1-amd64
-FreeBSD 13.2-RELEASE-p9
-OpenSSL 3.0.13
-os-upnp 1.5_6
-Intel(R) Core(TM) i5-3450 CPU @ 3.10GHz (4 cores, 4 threads)
-Intel X520-DA2 E10G42BTDA PCI-E Dual Port 10G SFP+ NIC Server Adapter (Configured with LAG/LACP)

**Comment by fichtner** [comment]
@roylaprattep does this bring it back?

    # pkg add -f https://pkg.opnsense.org/FreeBSD:13:amd64/23.7/MINT/23.7.10/latest/All/miniupnpd-2.3.3_1,1.pkg


Cheers,
Franco

**Comment by CrazyCoder** [comment]
Looks exactly as my issue described at https://forum.opnsense.org/index.php?topic=38732.0.

UPnP clients get corrupted mappings from OPNsense miniupnpd server :(

**Comment by roylaprattep** [comment]
@fichtner 

Unfortunately not. :/

**Comment by roylaprattep** [comment]
This issue has been resolved upstream: https://github.com/miniupnp/miniupnp/issues/719

Please update this FreeBSD port to the latest version in order to resolve this issue.

**Comment by fichtner** [comment]
That leaves the complication that FreeBSD ports has custom patch glue that no longer applies to 2.3.6.

Still, the whole timing issue here is off so I wouldn't bet on this horse just yet.


Cheers,
Franco

**Comment by roylaprattep** [comment]
Just to know it's gonna be taken care of sooner or later, is nice. As for the "when", I don't think there is a hurry here... If, and when it is done, just let us know brother.

Thanks Franco.

**Comment by MorningLightMountain713** [comment]
> Just to know it's gonna be taken care of sooner or later, is nice. As for the "when", I don't think there is a hurry here... If, and when it is done, just let us know brother.
> 
> Thanks Franco.

If you're desperate (like I was :P) You can go to the miniupnpd website, and download the source, and compile. I can confirm this issue is resolved on the new version. (2.3.6)

**Comment by denverpilot** [comment]
Tempted to do that too @MorningLightMountain713 but leery because of @roylaprattep 's comment that ports has glue... wonder what the glue is for... if your compiled version is behaving fine... hahaha...yuck...

**Comment by fichtner** [comment]
A snapshot with the update has been published:

    # opnsense-revert -z miniupnpd

Feedback welcome.


Cheers,
Franco

**Comment by CrazyCoder** [comment]
Hmm, I just updated to 24.1.8 and the command above doesn't seem to install the right version?

```
root@gw:~ # opnsense-revert -z miniupnpd
Fetching miniupnpd.pkg: ... done
Verifying signature with trusted certificate pkg.opnsense.org.20240105... done
miniupnpd-2.3.3_3,1: already unlocked
Installing miniupnpd-2.3.3_3,1...
package miniupnpd is already installed, forced install
Extracting miniupnpd-2.3.3_3,1: 100%
=====
Message from miniupnpd-2.3.3_3,1:

--
*** !!WARNING!! !!WARNING!! !!WARNING!! ***
This port allows machines within your network to create holes in your
firewall.  Please ensure this is really what you want!
*** !!WARNING!! !!WARNING!! !!WARNING!! ***

For this daemon to work, you must modify your pf rules to add an anchor
in both the NAT and rules section.  Both must be called 'miniupnpd'.
Example:

# NAT section
# UPnPd rdr anchor
rdr-anchor "miniupnpd"

# Rules section
# uPnPd rule anchor
anchor "miniupnpd"
```

**Comment by fichtner** [comment]
@CrazyCoder not the main mirror then. still syncing on this one you have set up

**Comment by CrazyCoder** [comment]
@fichtner Thanks, indeed, switched to the default mirror (https://pkg.opnsense.org/FreeBSD:13:amd64/24.1) and it worked:

```
Installing miniupnpd-2.3.6,1...
package miniupnpd is already installed, forced install
Extracting miniupnpd-2.3.6,1: 100%
```

**Comment by fichtner** [comment]
@CrazyCoder update worked or the fix too? ;)

**Comment by CrazyCoder** [comment]
@fichtner The update and the fix. I did a quick test with https://github.com/kaklakariada/portmapper. Adding/removing mappings works, and there are no more duplicates or corrupted records.

**Comment by denverpilot** [comment]
@fichtner working properly now here also, when testing the updated miniupnpd.  No duplicate ports.  Thank you for your work.

**Comment by fichtner** [comment]
Ok I'll close then! Thanks all :)
