### ISSUE TITLE
os-git-backup does not work with http:// Gitea server

### ISSUE THREAD

**Issue by truppelito** [opnsense/plugins#3834]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
I'm setting up a git backup of my OPNsense router to a self-hosted Gitea server on my local network. The Gitea server does not have https set up. Ideally I would just configure os-git-backup with the following data:

URL = http://local-ip-address:port/username/router-config.git
Branch = main
SSH private key = NOTHING
User Name = username
Password = my-pass

Unfortunately, it seems that os-git-backup requires https, so this doesn't work. I also tried SSH but I'm having trouble getting the authentication to work, so that's why I'd like for http to be possible.

**Comment by craniac-pr** [comment]
workaround: 
you can edit the GitSettings.xml file to allow http and https

using nano
`nano /usr/local/opnsense/mvc/app/models/OPNsense/Backup/GitSettings.xml`

change the value of the url mask (should be line 20) to read
`/^((https?)|(ssh))?:\/\/.*[^\/]$/`
(add a question mark after the https, that will make the s optional)
