### ISSUE TITLE
Log Level "debug 3" in Services->ACME Client->Settings Does Not Output Logs to File

### ISSUE THREAD

**Issue by theoisadoor** [opnsense/plugins#3836]
Please switch `Log Level` to "debug 3" in Services->ACME Client->Settings and try again. The ACME Log really should not be empty. (Note that debug logging causes the log to look somewhat scrambled in the GUI, this is expected.)

_Originally posted by @fraenki in https://github.com/opnsense/plugins/issues/3790#issuecomment-1931641606_

/var/logs/acme.sh.log is empty despite setting debug to debug 3 in settings, therefore debugging of failures is almost impossible.
/var/logs/system/latest.log is the only way to view any output for acme.sh, even when argument is explicitly referenced:
`AcmeClient: running acme.sh command: /usr/local/sbin/acme.sh --deploy --syslog 7 --debug 3 --server 'letsencrypt' --home '/var/etc/acme-client/home' --cert-home '/var/etc/acme-client/cert-home/65bad1e249ba12.99143819' --certpath '/var/etc/acme-client/certs/65bad1e249ba12.99143819/cert.pem' --keypath '/var/etc/acme-client/keys/65bad1e249ba12.99143819/private.key' --capath '/var/etc/acme-client/certs/65bad1e249ba12.99143819/chain.pem' --fullchainpath '/var/etc/acme-client/certs/65bad1e249ba12.99143819/fullchain.pem' --domain 'HL1-MGT-PVRT1X.xxx.xxx' --deploy-hook proxmoxve`

**Comment by theoisadoor** [comment]
/var/logs/acme.sh.log is empty, however ACME log in the GUI is populated.

**Comment by fraenki** [comment]
The acme.sh log is available at `/var/log/acmeclient/latest.log`, plugin log message are available in `/var/log/system/latest.log`.
