### ISSUE TITLE
security/tor: allow for setting custom torrc options

### ISSUE THREAD

**Issue by paride** [opnsense/plugins#385]
I'd like to be able to manually set `MaxMemInQueues`, as tor set its too high for the machine where I'm running it. Instead of adding this specific option, it may be more useful to be able to manually specify options to be appended to the generated torrc file.

**Comment by fichtner** [comment]
We usually don't do custom block support, adding the feature is just as easy and less fragile and easily documentable :)

**Comment by fichtner** [comment]
@fabianfrz feel free to take this if you have time

**Comment by fabianfrz** [comment]
see #386 for how to add an option to the tor plugin. Pull requests are usually always welcome.

**Comment by paride** [comment]
@fabianfrz One thing I forgot to mention. When setting up a relay, the Tor documentation strongly suggest to set the `ContactInfo` variable to an (obfuscated) email address to contact in case of problems with the relay. When the variable is not set, Tor complains in the log file. It would be nice to be able to set it using the web interface. I would not consider it an "Advanced" option.

Thank a lot for the quick fixes. Expect some PRs in the future :)

**Comment by fabianfrz** [comment]
@paride you can try to add it by yourself if you like. You need to change 3 files: the form (generates the HTML form), the model (add the new field) and the template (for the configuration file).

In your case, you will need a `TextField`.

**Comment by fabianfrz** [comment]
@fichtner it looks like the ticket author got lost so I have implemented this.
