### ISSUE TITLE
nut - lack of customisation - i.e. POWERDOWNFLAG shutting down UPS - cannot remove this flag

### ISSUE THREAD

**Issue by homonto** [opnsense/plugins#3855]
nut configuration is recreated from the scratch when the system restarts - it takes from the template
i.e. upsmon.conf ALWAYS adds:

`POWERDOWNFLAG /etc/killpower`

that causes UPS to shutdown that in some cases is NOT NEEDED or even shall NOT happen (imagine Opnsense is not the only host connected to UPS) and while Opnsense should shutdown others should not 

modyfing template is not persistent - next upgrade will overwrite the files as per:
```
cat /usr/local/etc/nut/upsmon.conf
# Please don't modify this file as your changes might be overwritten with
# the next update.
```

ideally nut should have customization that is persistant and survives turning off/on service or restart or upgrades
POWERDOWNFLAG is only one of the examples - actually we are limitted to the template values that are not configurable

I would gladly help with code but I am no coder by any means

**Comment by mimugmail** [comment]
Can you post some examples how it should look like? The  I can add some stuff to the gui

**Comment by homonto** [comment]
> Can you post some examples how it should look like? The I can add some stuff to the gui

thank you @mimugmail for your interest
let me first describe the issue: there are many scenarios how one can use UPS i.e. in the home lab:
1- ups connected directly to opnsense machine (usb) and there is no other machine in the lab
2- like above (ups connected over usb to opnsense machine), but there are other machines that are powered up by the same ups 
3- ups connected to any other machine (over usb) while opnsense is powered up by the same ups

In short: nut can work as:
1- standalone service (scenario 1) - one host, one ups - simple
2- network server on opnsense host and network clients on other machines  (scenario 2) 
3- network server on other machine and network clients on opnsense and other machines  (scenario 3) 

Any of the scenario will require separate configuration. Usually nut installs config in /etc/nut but on opnsense I found it is in /usr/local/etc/nut that is also very ok

Now, today on GUI there is only very minimalistic setup i.e. when we use scenario 2, you just set IP of ups server, username, password and port.
That would be ok if someone did not want to set up anything else. But, there are many scenarios that can be nicely customised by the files in /usr/local/etc/nut

What I realised today is: if you enable/disable the config in GUI, the config files are rewritten by templates that are in another folder. That means: **_all customisation is lost_**. Actually, the same happens during restart.

What I did on my opnsense is:
1- create folder, i.e. /home/ups/configs that shall survive restart 
2- put there customised files, that shall be later in /usr/local/etc/nut
3- created a script: /home/ups/configure_nut.sh and put there:

```
#!/bin/sh
service nut_upsmon stop
rm /usr/local/etc/nut/*
cp /home/ups/configs/* /usr/local/etc/nut/
service nut_upsmon restart
```

4- added a line that calls this script on reboot in /usr/local/etc/rc
```
# ZH added:
# reconfigure ups monitor:
/home/ups/configure_nut.sh
```

just before these 3 lines:
```
/usr/local/sbin/opnsense-shell banner
/usr/local/etc/rc.subr.d/livemode
exit 0
```


the customised scripts are such as (but not limited to):
ups.conf
upsmon.conf
upsd.conf
upsd.users
upssched-cmd
upssched.conf

I would see 2 options for this plugin in GUI:
1- simple window in which one can enter the commands that shall be in every config file  (but that would require as many windows as many possible config files can be there) or
2- don't recreate the files in /usr/local/etc/nut on host restart or on enable/disable the plugin (however in the second case maybe the option "should I keep the old config files or do you want to recreate them?" would be helpfull 

I hope this helps.
I know my workaround is very dirty but... it works

What caused me to go for custom config file is: I use scenario 2, so other host is connected to UPS, I want that host to be powered off as the last so it means: config on opnsense has to be different.
Also, today, in the default config on opnsense there is a flag: 

`POWERDOWNFLAG /etc/killpower`

this flag turns off the ups - not good if you have other hosts connected to it and you just want opnsense to be shutdown first.

**Comment by homonto** [comment]
just to add example from TrueNAS where the configuration of nut is like this (some parameters are exposed, some are to be added on the bottom) and this configuration is persistant: 

<img width="797" alt="Screenshot 2024-03-13 at 08 02 48" src="https://github.com/opnsense/plugins/assets/46562447/e7cc73cd-5b44-4170-9560-15f63be60dd1">
<img width="805" alt="Screenshot 2024-03-13 at 08 02 56" src="https://github.com/opnsense/plugins/assets/46562447/9d0b7ee2-801c-4ebe-9219-a38157cdcadc">
