### ISSUE TITLE
security/acme-client: HAProxy plugin is NOT installed, skipping integration

### ISSUE THREAD

**Issue by ruslan-mogilevskiy** [opnsense/plugins#3860]
My setup: 
* OPNsense 24.1.3_1-amd64
* **os-acme-client** 4.1 is installed
* HAProxy pluging isn't installed in OPNsense nor activated in the ACME client settings (the 'HAProxy Integration' checkbox is unchecked).

The problem is that in OPNsense logs I frequently see the following error even though the HAProxy Integration is disabled:
`Error | api | AcmeClient: HAProxy plugin is NOT installed, skipping integration`
It doesn't break the acme client integration but more reasonable to log it as a notice instead of error.

**Comment by fraenki** [comment]
Thanks for reporting this issue. I've made adjustments to log severity, which will be available in the upcoming os-acme-client 4.5.
