### ISSUE TITLE
security/tor: Disable Diagnostics sub-page when ControlPort is disabled

### ISSUE THREAD

**Issue by lattera** [opnsense/plugins#387]
If the ControlPort is set to 0 (disabled), then the Diagnostics sub-page for the Tor service (Services -> Tor -> Diagnostics) causes the web GUI to lock up (infinite loop?).

**Comment by fabianfrz** [comment]
@lattera this was not an issue of the GUI, the service script was not aware of the port to use for the control socket (always used 9051). I added a pull request to fix this issue. If you like, you can give it a try.
