### ISSUE TITLE
os-bind does not start if 'Allow RDNC key update' is set on any primary domain when secondary zones exist

### ISSUE THREAD

**Issue by capsali** [opnsense/plugins#3870]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
When setting 'Allow RDNC key update' on any primary domain and secondary domains exist, Bind fails to start.
When trying to start the service manually via SSH, the service errors out with:
```
/usr/local/etc/namedb/named.conf:63: option 'update-policy' is not allowed in 'secondary' zone 'secondary.domain.name'
/usr/local/etc/rc.d/named: ERROR: named-checkconf for /usr/local/etc/namedb/named.conf failed
```

The issue seems to be that update-policy is only allowed on primary domains, but the option is written on secondary zones too.

The issue seems to be in the template **/usr/local/opnsense/service/templates/OPNsense/Bind/named.conf**:
```
{%      if domain.allowrndcupdate is defined and domain.allowrndcupdate == "1" %}
184         update-policy {
185                 grant rndc-key zonesub ANY;
186         };
187 {%      endif %}
```

The simple fix is to add **domain.type == 'primary'**:
```
{%      if domain.allowrndcupdate is defined and domain.allowrndcupdate == "1" and domain.type == 'primary' %}
184         update-policy {
185                 grant rndc-key zonesub ANY;
186         };
187 {%      endif %}
```

**To Reproduce**
1. Go to Services -> BIND -> Configuration
2. Under General tab (Advanced view) have **RNDC Key** section setup with an **Algorithm** and **Secret**
3. Go to **Primary Zones** tab, selection edit on any zone and tick the **Allow RDNC key update** option
4. If already set: untick -> Save -> Save -> edit zone -> tick -> Save -> Save
5. Bind service will fail to start
6. SSH into Opnsense server
7. service named start
8. Observe error

**Expected behavior**
Bind starts after setting **Allow RDNC key update** on any primary domain

**Screenshots**

**Relevant log files**
When trying to start the service manually via SSH, the service errors out with:
```
/usr/local/etc/namedb/named.conf:63: option 'update-policy' is not allowed in 'secondary' zone 'secondary.domain.name'
/usr/local/etc/rc.d/named: ERROR: named-checkconf for /usr/local/etc/namedb/named.conf failed
```

**Additional context**

**Environment**
Software version used and hardware type if relevant.
e.g.:

OPNsense 24.1.4 (amd64).
os-bind 1.30_1

**Comment by fraenki** [comment]
AFAICT, this was already fixed in https://github.com/opnsense/plugins/pull/3873.
