### ISSUE TITLE
BIND invalid configuration - loglevel 'warn' unexpected

### ISSUE THREAD

**Issue by Sverto** [opnsense/plugins#3876]
OPNsense 24.1.2_1 & 24.1.4
**Plugin**: os-bind 1.29 & 1.30_1

**To Reproduce**
1. In the OPNsense UI, go to Services -> BIND -> Configuration
2. Set the loglevel to "Warning"
3. Click Save

At this point BIND isn't starting anymore.
When looking at the logs:
`2024-03-27T19:59:37	Notice	root	/usr/local/etc/rc.d/named: ERROR: named-checkconf for /usr/local/etc/namedb/named.conf failed`

When verifying over ssh:
`# named-checkconf
/usr/local/etc/namedb/named.conf:264: 'warn' unexpected`

**Additional context**
It would seems that the "warn" loglevel set by OPNsense UI is not a valid value for the BIND configuration.

**Environment**
OPNsense VM

**Comment by kulikov-a** [comment]
oops. my bad, sorry. should be "warning", yes. 
I'll make a pr
