### ISSUE TITLE
www/caddy: Not satisfying ACL returns 200

### ISSUE THREAD

**Issue by jeliasson** [opnsense/plugins#3883]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X] The title contains the plugin to which this issue belongs

**Describe the bug**
When ACL is enabled and a request is made from a non-allowed IP, the proxy is responding with a `200` rather than e.g. `401`.

**To Reproduce**
1. Create a ACL with a internal subnet, e.g. `192.168.0.0/24`.
2. Create a domain that uses that ACL.
3. Request from a IP address that is satisfied by ACL _(in below example, I expect a 401 from upstream)_.
```
> curl -I https://example.com
HTTP/2 401 
alt-svc: h3=":443"; ma=2592000
server: Caddy
server: Kestrel
```
4. Request from an IP address not satisfied by ACL.
```
> curl -I https://example.com
HTTP/2 200 
alt-svc: h3=":443"; ma=2592000
server: Caddy
```

**Expected behavior**
Response code of `401` (Unauthorized) or similar when a request is made that does not satisfy ACL.

**Screenshots**
N/A

**Relevant log files**
The access log did not include any relevant information to the issue.

**Additional context**
This might be a strange edge-case in my setup and this being a faulty report. Kindly help me rule that out.

**Environment**
OPNsense `24.1.4-amd64` with `os-caddy` version `1.5.2`.

**Comment by Monviech** [comment]
Have you enabled the "Abort Connections" in the general settings?

**Comment by jeliasson** [comment]
Pretty sure I had that enabled at the time of the reporting. However, I did a quick test just now (disabling it, test, and re-enable it) but got that strange behavior as per #3887. I'll do some more troubleshooting later today and get back with my findings.

**Comment by Monviech** [comment]
I won't fix this issue since the plugin uses the standard approach with ```abort```, as referenced above.

**Comment by jeliasson** [comment]
While it makes sense to follow a recommended path, I just find it odd that a fail authorization would return a empty `200`.

This is what I have in my current setup (simplified for brevity) which I'm migrating away from.
```conf
(custom_acl_example) {
  @custom_acl_example {
    not remote_ip 192.168.0.0/24
  }
  respond @custom_acl_example "Disallowed by @custom_acl_example" 401
}
```
```conf
example.com {
  import custom_acl_example

  reverse_proxy example.internal:1234
}
```
By returning a `401`, it also satisfies monitoring services where a check would expect to fail with e.g. `401`.

**Comment by Monviech** [comment]
If it's just a ```respond 401``` that has to be sneaked in front of all ```abort``` then this would be easy to add.

There could be an advanced option field in general settings that allows to set a numerical response code, and when set the template generates a ```respond <number>``` one line before each abort.

**Comment by jeliasson** [comment]
> If it's just a `respond 401` that has to be sneaked in front of all `abort` then this would be easy to add.

Yes, but before `reverse_proxy` as we want to respond before hitting the proxy directive, i.e.

1. `<access list>` with a `respond 401` if not satisfied.
2. `reverse_proxy` directive.
3. `abort` directive.

> There could be an advanced option field in general settings that allows to set a numerical response code, and when set the template generates a `respond <number>` one line before each abort.

I suggest having the advanced option field under the respective Access List configuration, with defaults to `401`. Ideally, together with a response body `respond "<body>" <code>` with defaults to null/empty string. That would allow different use-cases, and ease of debugging. I defer this one to you.

**Comment by Monviech** [comment]
I can't do that since the logic of the Caddyfile template is totally different.

It doesn't deny access before hitting a handler and reverse proxy directive... it /allows/ access based on the access list.

So the only way to do it without the whole logic of the template deteriorating, is to replace all the ```abort``` with ```respond 403``` for example.

Everything else is totally unfeasible right now with the current template design.

**Comment by jeliasson** [comment]
I think your example addresses my expected behavior. We just have a different approach to overall logic/order, but your way is probably the preferred of the two. Alternatively to replace `abort` with `respond ...` would be to, as you said, optionally allow a respond before the abort.

**Comment by Monviech** [comment]
This here is the most I'm willing to do. It allows to set this globally.

https://github.com/opnsense/plugins/commit/c41319247ad11134ce381e9f04339404f4228ef1

**Comment by jeliasson** [comment]
I'll take it! 😊

**Comment by Monviech** [comment]
Does it work for you?

**Comment by jeliasson** [comment]
Indeed, it works well.

Unfortunately, for a specific edge-case involving a Password Manager and it's client, I have to set my default to e.g. 503 (_Service Unavailable_) as otherwise said client will be logged out when it sees a `4xx`. Never the less, this is a great improvement.

Thank you!

**Comment by Monviech** [comment]
If you can, please test this alternative implementation. It allows these codes to be set per access list. This one needs some careful testing if you can.

https://github.com/opnsense/plugins/commit/1021219b055608097369706a93d6e6bfb8b16105
https://github.com/opnsense/plugins/commit/a72b2d3bdb3c073b235bd28fb45027937804474d

**Comment by jeliasson** [comment]
Absolutely. Will try to have it thoroughly tested by Monday.

**Comment by jeliasson** [comment]
I think you nailed it. Below are some test cases. Let me know if there is another test that you can think of.

### ✅ Test 1: No Access List - expecting a `200` from application

```conf
test-200.example.com:443 {
        log 52b2c583-a89f-415c-a387-7488ae251202

        handle {
                reverse_proxy server1.corp.example.com:1234 {
                }
        }

        abort
}
```

```bash
hunter2@example.com:~$ curl -I https://test-200.example.com
HTTP/2 200
alt-svc: h3=":443"; ma=2592000
content-type: text/html; charset=UTF-8
server: Caddy
server: nginx
[...]
```

### ✅ Test 2: No Access List - expecting a `301` from application 

```conf
test-301.example.com:443 {
        log ae5b7946-0add-45c7-bee0-ab00c585dac1

        handle {
                reverse_proxy server2.corp.example.com:2345 {
                }
        }

        abort
}
```

```bash
hunter2@example.com:~$ curl -I https://test-301.example.com
HTTP/2 301
alt-svc: h3=":443"; ma=2592000
content-type: text/html; charset=UTF-8
location: https://test-301.example.com/subdomain/
server: Caddy
server: nginx
[...]
```

### ✅ Test 3: Access List - expecting a `403` from Caddy

```conf
test-403.example.com:443 {
        @7938c7ca-6496-4bc5-a70f-6e65e61d6b9c {
                client_ip 192.168.0.0/24
        }

        handle @7938c7ca-6496-4bc5-a70f-6e65e61d6b9c {
                handle {
                        reverse_proxy server3.corp.example.com:3456 {
                        }
                }
        }

        respond "Forbidden" 403
}
```

```bash
hunter2@example.com:~$ curl -I https://test-403.example.com
HTTP/2 403
alt-svc: h3=":443"; ma=2592000
content-type: text/plain; charset=utf-8
server: Caddy
[...]
```

### ✅ Test 4: Access List - expecting a `503` from Caddy

This one is to address my edge-/use-case where I can't pass `4xx`.

```conf
test-503.example.com:443 {
        @959003fb-75bb-4dfa-bc57-c4a8b95e5cd1 {
                client_ip 192.168.0.0/24     
        }

        handle @959003fb-75bb-4dfa-bc57-c4a8b95e5cd1 {
                handle {
                        reverse_proxy server4.corp.example.com:4567 {
                        }
                }
        }

        respond "Service Unavailable" 503
}
```

```bash
hunter2@example.com:~$ curl -I https://test-503.example.com
HTTP/2 503
alt-svc: h3=":443"; ma=2592000
content-type: text/plain; charset=utf-8
server: Caddy
[...]
```

### ✅ Test 5: Access List - expecting an abort Caddy

This one is without HTTP Response Code and Response Message defined.

```conf
test-abort.example.com:443 {
        @96f617b9-0f45-4cd3-8266-b42abaaaf5d6 {
                client_ip 192.168.0.0/24     
        }

        handle @96f617b9-0f45-4cd3-8266-b42abaaaf5d6 {
                handle {
                        reverse_proxy server5.corp.example.com:5678 {
                        }
                }
        }

        abort
}
```

```bash
hunter2@example.com:~$ curl -I https://test-abort.example.com
curl: (92) HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)
[...]
```

**Comment by Monviech** [comment]
Thanks for the feedback, this looks like what I expected. Now there is maximum flexibility with this setup without it being too difficult to configure. So this is the version that stays in the new os-caddy version.
