### ISSUE TITLE
www/caddy: Domain presentation under Handlers

### ISSUE THREAD

**Issue by jeliasson** [opnsense/plugins#3884]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X] The title contains the plugin to which this issue belongs

**Describe the bug**
Domain under "Handlers" is referencing the Domain description rather than the actual domain name. 

**To Reproduce**
1. Create a Domain with e.g. `example.com` as domain, and `Example` as description.
2. Create a Handler and select Reverse Proxy Domain `Example`.
3. In the Handler Overview, the Domain column will have `Example` rather than `example.com`.

**Expected behavior**
Under Reverse Domain Proxy and the Domain column, I would expect to see the Domain rather than the description. 

**Screenshots**
![image](https://github.com/opnsense/plugins/assets/865493/64f844fb-f844-4d24-8ac5-d730fe3b8a5f)

![image](https://github.com/opnsense/plugins/assets/865493/7cdd81b8-baef-409b-91cf-1c3832ca3aff)

**Relevant log files**
N/A

**Additional context**
This might just be by design. If so, feel free to close and I will just re-think about how I go about "Description". 😊

**Environment**
OPNsense `24.1.4-amd64` with `os-caddy` version `1.5.2`.

**Comment by Monviech** [comment]
This is by design, since you could create:
foo.example.com.443
foo.example.com.8443
foo.example.com.10000

And then there would be just "foo.example.com" 3 times in the handlers.

I tried to show a mix of domain name and port with the model relation field, but I didn't get it to work, so I defaulted for a required description.
