### ISSUE TITLE
www/caddy: Basic Auth dropdown selection

### ISSUE THREAD

**Issue by jeliasson** [opnsense/plugins#3885]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X] The title contains the plugin to which this issue belongs

**Describe the bug**
If you have many Basic Auths with the same username, it can be hard to know which one is which. 

**To Reproduce**
1. Create two Basic Auths with the same username but different passwords and description.
2. Try to figure out which one is which when applying the Basic Auth to a Domain.

**Expected behavior**
Dropdown showing either the `<description>` or `<username> - <description>`.

**Screenshots**
![image](https://github.com/opnsense/plugins/assets/865493/a25e92f5-6589-4304-8c7b-d906ce4cca83)
![image](https://github.com/opnsense/plugins/assets/865493/832a0c9f-3a0a-43c0-8e95-4f7f285b20ba)

**Relevant log files**
N/A

**Additional context**
Not necessarily a bug, but does not fit in a Feature Request or Question.

**Environment**
OPNsense `24.1.4-amd64` with `os-caddy` version `1.5.2`.

**Comment by Monviech** [comment]
I didn't expect people to use the same username for multiple users. Using the description in the model relation field makes sense.

Though, this could also be solved by constraining the username to be unique.

**Comment by jeliasson** [comment]
@Monviech I would prefer to continue allow having multiple users with the same username, as the users are for different upstreams/services. That being said, it would not be a big deal for me - personally - to change those to uniques. Your call.

**Comment by Monviech** [comment]
I won't constrain it since the additional validation of the Caddyfile will catch if anybody sets the same username twice to the same domain.
