### ISSUE TITLE
www/caddy: Handle HttpTlsInsecureSkipVerify missing frontend configuration

### ISSUE THREAD

**Issue by jeliasson** [opnsense/plugins#3886]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X] The title contains the plugin to which this issue belongs

**Describe the bug**
It looks like the frontend configuration option for `HttpTlsInsecureSkipVerify` on Handlers is missing.

**To Reproduce**
N/A

**Expected behavior**
Allow configuration of `HttpTlsInsecureSkipVerify` in the frontend.

**Screenshots**
N/A

**Relevant log files**
N/A

**Additional context**
According to the [package description](https://github.com/opnsense/plugins/blob/57ae4626a2c02ec251c92ef0909e453febc25ce4/www/caddy/pkg-descr#L32) and the [Caddyfile templating](https://github.com/opnsense/plugins/blob/57ae4626a2c02ec251c92ef0909e453febc25ce4/www/caddy/src/opnsense/service/templates/OPNsense/Caddy/Caddyfile#L386), it looks like we should be able to configure this option. I might be straight up blind, and if so, I apologize. 😊

**Environment**
OPNsense `24.1.4-amd64` with `os-caddy` version `1.5.2`.

**Comment by Monviech** [comment]
This comes in the patch today.

**Comment by jeliasson** [comment]
Works great. Thanks @Monviech!
