### ISSUE TITLE
www/caddy: Multiple running processes

### ISSUE THREAD

**Issue by jeliasson** [opnsense/plugins#3887]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X] The title contains the plugin to which this issue belongs

**Describe the bug**
TL;DR -- Multiple running processes of caddy caused a strange behavior. Killing them all and start again solved it. 

After migrating about +30 sites/directives to the plugin (previously running Caddy outside of OPNsense) I started seeing some strange behavior. At first, the server stopped serving requests all together. After some initial troubleshooting, by randomly disable different handlers, I jumped onto a shell and observed a lot of processes trying to stop Caddy. 

After allowing some time for it to catch up, the 'stopping' processes cleared up and Caddy started serving requests again. However, just some sites where responding. _dafaq.gif_. Soon thereafter I discovered that there were multiple processes of caddy running, and the one process responding to requests was probably one of the many configuration states on which I did the initial troubleshooting.

Firing a kill-canon at the caddy processes, followed by a manual start in the frontend, everything went back to normal and is now serving requests nicely.

**To Reproduce**
N/A: unknown what triggered the underlying behavior.

**Expected behavior**
Any running Caddy process are gracefully killed before a new one is spawned., by e.g. a start/restart event.

**Screenshots**
N/A

**Relevant log files**

_List of stopping processes_
```
hunter2@example.com:/var/log # ps aux | grep caddy
root     80005   2.1  0.4  765592  63276  -  S    21:29        0:00.07 /usr/local/bin/caddy stop --config /usr/local/etc/caddy/Caddyfile 
root     77073   0.2  0.0   13488   3204  -  S    21:29        0:00.01 /bin/sh /usr/local/etc/rc.d/caddy onerestart
root     79178   0.2  0.0   13488   3212  -  S    21:29        0:00.00 /bin/sh /usr/local/etc/rc.d/caddy onerestart
root     79710   0.2  0.0   13444   3012  -  S    21:29        0:00.00 /usr/bin/su -m root -c /usr/local/bin/caddy stop --config /usr/loc...
root     79809   0.2  0.0   13784   3320  -  S    21:29        0:00.01 /bin/csh -c /usr/local/bin/caddy stop --config /usr/local/etc/cadd...
root      8045   0.0  0.0   13488   3200  -  I    21:27        0:00.01 /bin/sh /usr/local/etc/rc.d/caddy onerestart
root      9878   0.0  0.0   13488   3208  -  I    21:27        0:00.00 /bin/sh /usr/local/etc/rc.d/caddy onerestart
root     10321   0.0  0.0   13444   3004  -  I    21:27        0:00.00 /usr/bin/su -m root -c /usr/local/bin/caddy stop --config /usr/loc...
root     10344   0.0  0.0   13784   3316  -  I    21:27        0:00.01 /bin/csh -c /usr/local/bin/caddy stop --config /usr/local/etc/cadd...
root     10497   0.0  0.4  765592  63052  -  I    21:27        0:00.07 /usr/local/bin/caddy stop --config /usr/local/etc/caddy/Caddyfile 
root     22965   0.0  0.0   13488   2924  -  I    21:05        0:00.01 /bin/sh /usr/local/etc/rc.d/caddy onestop
root     23675   0.0  0.0   13488   2924  -  I    21:04        0:00.01 /bin/sh /usr/local/etc/rc.d/caddy onestop
root     23869   0.0  0.0   13444   2992  -  I    21:05        0:00.00 /usr/bin/su -m root -c /usr/local/bin/caddy stop --config /usr/loc...
root     24003   0.0  0.0   13784   3032  -  I    21:05        0:00.01 /bin/csh -c /usr/local/bin/caddy stop --config /usr/local/etc/cadd...
[...~x3 repeating condensed for brevity]
root     80804   0.0  0.0   12720   2240  0  S+   21:29        0:00.00 grep caddy
```

_List of multiple running processes of caddy_
```bash
hunter2@example.com:/var/log # ps aux | grep caddy
root     12948   0.0  0.4  766104  70076  -  S    21:29        0:01.11 /usr/local/bin/caddy run --pingback 127.0.0.1:9269 --config /usr/lo...
root     12988   0.0  0.4  765592  65996  -  I    21:29        0:00.16 /usr/local/bin/caddy run --pingback 127.0.0.1:47715 --config /usr/l...
root     13081   0.0  0.4  765592  65744  -  I    21:29        0:00.20 /usr/local/bin/caddy run --pingback 127.0.0.1:6676 --config /usr/lo...
root     13170   0.0  0.4  765848  66000  -  I    21:29        0:00.16 /usr/local/bin/caddy run --pingback 127.0.0.1:3477 --config /usr/lo...
root     84735   0.0  0.0   12720   2248  0  S+   21:40        0:00.00 grep caddy
```

_List after killing all caddy processes and started it manually, we're back to one process._
```bash
hunter2@example.com:/var/log # ps aux | grep caddy
root     66575   0.0  0.4  766104  70488  -  S    21:42        0:01.81 /usr/local/bin/caddy run --pingback 127.0.0.1:44625 --config /usr/l...
root     35905   0.0  0.0   12720   2248  0  S+   22:08
```

**Additional context**
I cannot determine what lead to the issue, but hope this reporting can serve as a help for anyone that may see similar behavior - and that we maybe can ensure that there is only one process of caddy running. 

**Environment**
OPNsense `24.1.4-amd64` with `os-caddy` version `1.5.2`.

Finally; a huge thanks @Monviech for this plugin! This will be my last issue reporting for now. 😊

**Comment by Monviech** [comment]
@jeliasson Can you check if the ```cat /var/run/caddy/caddy.pid``` output has the same process ID as you can see with ```ps aux```?

**Comment by dmarcoux** [comment]
I have the same issue as you can see in this screenshot from the OPNsense web UI *System > Diagnostics > Activity*:

![caddy](https://github.com/opnsense/plugins/assets/1102934/4cceb63f-0b2e-4b43-8960-d8b39334cb95)

The number of processes (10 in my case) is the number of handlers I have. So it seems like one handler equals one process.

**Comment by Monviech** [comment]
Checking the rc.d file further, I see that a reload action is supported. The rc.d script injects the new Caddyfile right into ```/var/run/caddy/caddy.sock```, so Caddy can be soft reloaded without restarting the whole service.

This behavior needs some more testing, but it looks promising for faster applies of a new config without new processes being spawned when things go wrong.

**Comment by jeliasson** [comment]
> @jeliasson Can you check if the `cat /var/run/caddy/caddy.pid` output has the same process ID as you can see with `ps aux`?

It's the same pid.

Worth mentioning is that doing a graceful kill (`kill <pid>` on the `/usr/local/bin/caddy run ...` process) won't cut it. Have to do a `kill -9 <pid>`. That tells me that there is something preventing a proper shutdown, and probably the cause to what we're seeing. The logs don't tell me anything, yet.

> If anybody wants to test reload, here's the files that need to change [...]

I'll give it a shot.

**Comment by Monviech** [comment]
It was a typo I meant ```configctl```. But since the apply works with these changes, I'm more certain its the right way forward.

I use the plugin myself, but I never have more than 5 handlers, so maybe having a lot of them needs reloads instead of restarts?

**Comment by Monviech** [comment]
As reference, this is what happens with the following changes:
https://github.com/Monviech/opnsense-plugins/commit/e217c4dfaaa509d083e5c137196b4c6e08f7d56b
https://github.com/Monviech/opnsense-plugins/commit/9b0df87e6897bf1c2eee17853785fbda288678e8
https://github.com/Monviech/opnsense-plugins/commit/29675a0413fd865a450dea2b064eb04074becab6

Log entries:
2024-04-04T20:35:47	Informational	caddy	"info","ts":"2024-04-04T18:35:47Z","logger":"admin.api","msg":"load complete"}	
2024-04-04T20:35:47	Informational	caddy	"info","ts":"2024-04-04T18:35:47Z","msg":"config is unchanged"}	
2024-04-04T20:35:47	Informational	caddy	"info","ts":"2024-04-04T18:35:47Z","logger":"admin.api","msg":"received request","method":"POST","host":"127.0.0.1","uri":"/load","remote_ip":"","remote_port":"","headers":{"Accept-Encoding":["gzip"],"Content-Length":["5079"],"Content-Type":["application/json"],"User-Agent":["Go-http-client/1.1"]}}

The admin api of caddy is used to reload the service, and it also notices if the config is unchanged.
This means, in the future, the caddy service won't have any interruption when applying configs.
