### ISSUE TITLE
www/caddy: "Applying changes" stops Caddy, but doesn't restart it

### ISSUE THREAD

**Issue by dmarcoux** [opnsense/plugins#3890]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
After changing something in the *Domains* or *Handlers*, then applying changes, Caddy is stopped, but it never restarts. This is especially inconvenient since I put the OPNsense GUI behind Caddy as explained in the [docs](https://docs.opnsense.org/manual/how-tos/caddy.html#reverse-proxy-the-opnsense-webui).

This was working previously with *OPNsense 24.1.4-amd64* and *os-caddy 1.5.2*. I didn't find anything useful in the logs. One way to restart Caddy is to log into OPNSense via its IP address and execute `pluginctl -s caddy restart`. Then everything is fine again.

**To Reproduce**
1. Go to *Services > Caddy Web Server > Reverse Proxy*
2. Click on tab *Domains* or *Handlers*
3. Change something, then apply changes. The *Apply* button keeps on spinning, nothing happens.
4. Try to access a service behind the reverse proxy, it's not possible anymore.

**Additional context**
Right after clicking on the *Apply* button, I can see that Caddy is being stopped with:
```bash
$ sudo ps aux | grep caddy
root     26857   7.0  0.6 1280080 50472  -  S    19:35     0:00.13 /usr/local/bin/caddy stop --config /usr/local/etc/caddy/Caddyfile --adapter caddyfile
root     26783   0.9  0.0   13784  3308  -  S    19:35     0:00.01 /bin/csh -c /usr/local/bin/caddy stop --config /usr/local/etc/caddy/Caddyfile --adapter caddyfile
root     26319   0.8  0.0   13488  3384  -  S    19:35     0:00.02 /bin/sh /usr/local/etc/rc.d/caddy onestop
root     26693   0.8  0.0   13444  3044  -  S    19:35     0:00.01 /usr/bin/su -m root -c /usr/local/bin/caddy stop --config /usr/local/etc/caddy/Caddyfile --adapter caddyfile
root     26244   0.7  0.1   22428 10824  -  S    19:35     0:00.13 /usr/local/bin/python3 /usr/local/opnsense/scripts/OPNsense/Caddy/caddy_control.py stop (python3.9)
root      7718   0.0  0.6 1280080 52760  -  S    19:33     0:00.26 /usr/local/bin/caddy run --pingback 127.0.0.1:26504 --config /usr/local/etc/caddy/Caddyfile --adapter caddyfile --pidfile /var/run/caddy/caddy.pi
```

After some time, the same command returns nothing. The changes were still applied to the Caddyfile at `/usr/local/etc/caddy/Caddyfile`, so this is fine.

**Expected behavior**
After applying changes, I expect Caddy to keep on working.

**Environment**
*OPNsense 24.1.5_1-amd64*
*os-caddy 1.5.3*

**Comment by jeliasson** [comment]
Duplicate/related to #3887.

**Comment by dmarcoux** [comment]
@jeliasson I saw the issue and at first, I thought it would be the same. However, I don't have multiple processes of Caddy running before applying changes.

**Comment by Monviech** [comment]
I also experienced this issue before. On one of my firewalls, stopping caddy takes ages and times out eventually.

I think with the reload action referenced in the other thread this issue can be also solved.

But I haven't found out yet what makes Caddy unable to stop sometimes.

**Comment by dmarcoux** [comment]
> @dmarcoux That's fair. I think it boils down to the restart-handling - what we're both seeing. Could you by any chance try the changes suggested by @Monviech in that issue? Would help to confirm the potential fix.

Sure, but where are those files located exactly?

**Comment by jeliasson** [comment]
* `/usr/local/opnsense/scripts/OPNsense/Caddy/caddy_control.py`
* `/usr/local/opnsense/service/conf/actions.d/actions_caddy.conf`
* `/usr/local/opnsense/mvc/app/controllers/OPNsense/Caddy/Api/ServiceController.php`

**Comment by dmarcoux** [comment]
So I tried the changes mentioned in the previous comments, now I get: `Unable to parse the validation result.` after applying changes.

**Comment by Monviech** [comment]
Thanks for testing this. I was scared for a second. xD
