### ISSUE TITLE
security/acme-client: PHP deprecation messages

### ISSUE THREAD

**Issue by bubobih** [opnsense/plugins#3892]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
A clear and concise description of what the bug is, including last known working version (if any).

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Relevant log files**
If applicable, information from log files supporting your claim.

**Additional context**

**Environment**
Software version used and hardware type if relevant.
e.g.:

OPNsense 23.7.8 (amd64).
Intel® Xeon™ E3-1225V5 3.3Ghz Quad Core
Network Intel® I210-AT

hi there is a web gui error for a longer time like 6-12 months on latest versions of stable opnsense. here is a log

PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /usr/local/opnsense/mvc/app/controllers/OPNsense/AcmeClient/Api/SettingsController.php on line 350

PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /usr/local/opnsense/mvc/app/controllers/OPNsense/AcmeClient/Api/SettingsController.php on line 357

**Comment by bubobih** [comment]
After today update bugfix some new lines show. just to add to this bug.   


System Information:
User-Agent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
FreeBSD 13.2-RELEASE-p11 stable/24.1-n255007-1d6e165fb40 SMP amd64
OPNsense 24.1.5_3 0d4f3e17b
Plugins os-acme-client-4.1 os-ddclient-1.21_2 os-vmware-1.5_1
Time Fri, 05 Apr 2024 22:39:14 +0200
OpenSSL 3.0.13
Python 3.9.18
PHP 8.2.17



PHP Errors:
PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /usr/local/opnsense/mvc/app/controllers/OPNsense/AcmeClient/Api/SettingsController.php on line 350

PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /usr/local/opnsense/mvc/app/controllers/OPNsense/AcmeClient/Api/SettingsController.php on line 357

PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /usr/local/opnsense/mvc/app/models/OPNsense/AcmeClient/Migrations/M1_6_0.php on line 47

PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /usr/local/opnsense/mvc/app/models/OPNsense/AcmeClient/Migrations/M1_6_0.php on line 53

PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /usr/local/opnsense/mvc/app/models/OPNsense/AcmeClient/Migrations/M1_6_0.php on line 60

PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /usr/local/opnsense/mvc/app/models/OPNsense/AcmeClient/Migrations/M1_6_0.php on line 63

PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /usr/local/opnsense/mvc/app/models/OPNsense/AcmeClient/Migrations/M1_6_0.php on line 66

PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /usr/local/opnsense/mvc/app/models/OPNsense/AcmeClient/Migrations/M1_6_0.php on line 74

PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /usr/local/opnsense/mvc/app/models/OPNsense/AcmeClient/Migrations/M4_0_0.php on line 57

**Comment by fraenki** [comment]
Thanks for the report! Fixed in https://github.com/opnsense/plugins/pull/3899.

**Comment by bubobih** [comment]
Tnx for fixing it. I have more if u are interested :)
In interfaces tab i get this


PHP Warning:  Undefined array key 2 in /usr/local/www/interfaces.php on line 479

PHP Warning:  Trying to access array offset on value of type null in /usr/local/www/interfaces.php on line 479

PHP Deprecated:  base64_decode(): Passing null to parameter #1 ($string) of type string is deprecated in /usr/local/www/interfaces.php on line 479

PHP Warning:  Undefined array key 2 in /usr/local/www/interfaces.php on line 489

PHP Warning:  Trying to access array offset on value of type null in /usr/local/www/interfaces.php on line 489

PHP Warning:  Undefined array key 2 in /usr/local/www/interfaces.php on line 490

PHP Warning:  Trying to access array offset on value of type null in /usr/local/www/interfaces.php on line 490

PHP Warning:  Undefined array key 2 in /usr/local/www/interfaces.php on line 491

PHP Warning:  Trying to access array offset on value of type null in /usr/local/www/interfaces.php on line 491

PHP Deprecated:  str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /usr/local/www/interfaces.php on line 1869

PHP Warning:  Undefined array key "ipaddrv6" in /usr/local/www/interfaces.php on line 2939

 PHP Warning:  Undefined array key 2 in /usr/local/www/interfaces.php on line 3585

 PHP Warning:  Trying to access array offset on value of type null in /usr/local/www/interfaces.php on line 3585
dmesg.boot:

**Comment by bubobih** [comment]
Services acme client tab

 PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /usr/local/opnsense/mvc/app/controllers/OPNsense/AcmeClient/Api/SettingsController.php on line 350

PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /usr/local/opnsense/mvc/app/controllers/OPNsense/AcmeClient/Api/SettingsController.php on line 357

**Comment by bubobih** [comment]
System settings administration tab

PHP Warning:  Undefined array key "sudo_allow_wheel" in /usr/local/www/system_advanced_admin.php on line 57

**Comment by bubobih** [comment]
System settings general tab

 PHP Warning:  Undefined array key "gateway" in /usr/local/www/system_general.php on line 439

**Comment by bubobih** [comment]
System trust authorities tab

PHP Warning:  Undefined array key "id" in /usr/local/www/system_camanager.php on line 84

PHP Deprecated:  htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in /usr/local/www/system_camanager.php on line 375

PHP Warning:  Undefined array key "prv" in /usr/local/www/system_camanager.php on line 481

PHP Warning:  Undefined array key "prv" in /usr/local/www/system_camanager.php on line 872

**Comment by bubobih** [comment]
And in certificates wnd revocation tab too

 Errors:
 PHP Warning:  Undefined variable $tmpcrl in /usr/local/www/system_crlmanager.php on line 849

PHP Warning:  Trying to access array offset on value of type null in /usr/local/www/system_crlmanager.php on line 849

 PHP Deprecated:  htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in /usr/local/www/system_crlmanager.php on line 849

PHP Warning:  Undefined array key "userid" in /usr/local/www/system_certmanager.php on line 257

PHP Warning:  Undefined array key "id" in /usr/local/www/system_certmanager.php on line 261

PHP Deprecated:  htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in /usr/local/www/system_certmanager.php on line 818

PHP Warning:  Undefined array key "prv" in /usr/local/www/system_certmanager.php on line 1202

PHP Notice:  Only variable references should be returned by reference in /usr/local/etc/inc/certs.inc on line 69

**Comment by fichtner** [comment]
Let’s keep the scope for acme-client. We are aware of deprecation notes and fix them as we work on the old static pages, but eventually these will be replaced and the deprecation warnings are irrelevant for production mode away from MVC/API anyway.

**Comment by bubobih** [comment]
aham ok no problem i just wanted to help. there is more ofc errors, for example in System: Wizard: General Setup
wizard will probably not be replaced as its usual to be on systems like this. anyway sorry for spamming :)

**Comment by fichtner** [comment]
Pages ending in .php don’t have issues with these PHP notices and they can appear after PHP version upgrades too. For MVC pages the API end forces stricter coding styles so fixing there matters most.
