### ISSUE TITLE
ClamAV: Stuck downloading signatures (first time)

### ISSUE THREAD

**Issue by Hoosier-IT** [opnsense/plugins#3893]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x ] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

os-clamav (installed) | 1.8 | 47.7KiB | 3 | OPNsense

First time install, enabled as per docs. Clicked Download Signatures, waiting +2 hours with no sign of completion.
 
![image](https://github.com/opnsense/plugins/assets/8570961/1893eb0b-520d-4718-9fe3-ef04d1b968c3)

No log

Versions OPNsense 24.1.5_2-amd64
FreeBSD 13.2-RELEASE-p11
OpenSSL 3.0.13
Up to date
CPU type Intel(R) Celeron(R) N5100 @ 1.10GHz (4 cores, 4 threads)

**Comment by theomccall** [comment]
I'd just like to add I have a similar problem. Its late here at the moment so I dont have much else to add other than im also running OPNsense 24.1.4

I also see no change to traffic, no downloads are happening. I havnt had the time yet to check for any logs that might give insight. I'll be looking for solutions to over the next few days so will reply If i find anything.

**Comment by peter-lamantia** [comment]
I do want to add, it appears that the signatures update but don't show up in the 'Signatures' tab. I can see the database update from the logs section. If someone with more familiarity with this could take a look that would be helpful.

![image](https://github.com/user-attachments/assets/81db1472-c885-4fcc-8070-f50a92dc6e63)

**Comment by theomccall** [comment]
I get the same situation too, no signatures in the tab. No error banner any more saying none found and the service is running it would seem. Also have the logs reporting database ok and up to date.

**Comment by Mach-1977** [comment]
I get the same problem. just running a clean install of OPNsense 24.7.5 together with clamAV 1.8. 
Banner for downloading signatures is shown but when clicking it, nothing happens.
When having a look at the system-logs I can see a recurring error in the "configd.py".
- Script action stderr returned "b'/bin/sh: /usr/local/etc/rc.d/clamav-clamd: not found
- returned exit status 127
Also on the dashborad the service can not be started.

**Comment by rosti1226** [comment]
Had the same issue and could fix it in CLI.

1. Download initial signatures
#  freshclam

2. Enable and start clamAV-daemon
#  /usr/local/etc/rc.d/clamav_clamd enabled
#  /usr/local/etc/rc.d/clamav_clamd start

3. Enable and start freshclam-daemon
#  /usr/local/etc/rc.d/clamav_freshclam enabled
#  /usr/local/etc/rc.d/clamav_freshclam start

Hope this helps.

**Comment by Aquilo77** [comment]
Thank you @rosti1226!!

**Comment by teeesss** [comment]
@rosti1226 Thanks, this is still broke. Fresh install, enabled ClamAV and Freshclam, but it just hangs. 
Very bad UI experience with not showing what is going on.
Used the CLI via SSH to connect Shell. 8) Shell from the UI and followed @rosti1226.
Not sure why this issue isn't fixed, addressed and then auto closed out, as it's trivial and something in the plugins is broken.

**Comment by teeesss** [comment]
Thanks @mimugmail and @fichtner!! 👍 💯
