### ISSUE TITLE
security/acme-client: add support for Oracle Cloud Infrastructure DNS API

### ISSUE THREAD

**Issue by darkorb** [opnsense/plugins#3898]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
It appears on a freshly updated installation that the support for Oracle Cloud Infrastructure DNS isn't enabled in `os-acme-client`.

**Describe the solution you'd like**
Enable the option to use OCI DNS if at all possible :) 

There already exists `/usr/local/share/examples/acme.sh/dnsapi/dns_oci.sh` inside the Plugin so this appears to be UI related only?

Upstream docs on this are https://github.com/acmesh-official/acme.sh/wiki/How-to-use-Oracle-Cloud-Infrastructure-DNS - I guess this would be via the `Manual configuration` version using `OCI_CLI_USER`, `OCI_CLI_TENANCY`, `OCI_CLI_REGION` and `OCI_CLI_KEY`.

**Describe alternatives you've considered**
Aside from moving DNS provider, there's not a lot of other options currently (or doing it manually I guess).

**Additional context**
None.

**Comment by fraenki** [comment]
@darkorb Would you consider submitting a Pull Request? :) It's actually not too complicated, please have a look at the two most recent examples: https://github.com/opnsense/plugins/pull/3866, https://github.com/opnsense/plugins/pull/3882.

**Comment by fraenki** [comment]
Fixed in https://github.com/opnsense/plugins/pull/3901. Thanks!
