### ISSUE TITLE
ACME Client- Automation, add automation for postfix

### ISSUE THREAD

**Issue by Helmut1965** [opnsense/plugins#3902]
There are some automation rules after as Cert Change happend, like restarting WebService.
It would be good if there will also be a rule for restarting postfix after the cert for postfix is renewed.

Thx

**Comment by fraenki** [comment]
This is already possible today:
Automations -> Add -> Run Command: System of Plugin Command
Choose: Restart Postfix service

**Comment by fraenki** [comment]
Initially you need to select the ACME cert in the Postfix configuration GUI, of course. But for certificate renewals, that's all that is needed, AFAICT.

**Comment by Helmut1965** [comment]
Thanks, for sure
