### ISSUE TITLE
os-nginx - possibility to forward also the error_log

### ISSUE THREAD

**Issue by TimmiORG** [opnsense/plugins#3905]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] When the request is meant for an existing plugin, I've added its name to the title.

**Describe the solution you'd like**
the os-nginx plugin is allowing to forward the access_log via syslog to a remote target.
It would make sense to forward also the error_log. I guess a selection of which log you want to forward would make sense.
Current configuration looks like this in the conf file
```
nginx.conf:    access_log syslog:server=logs.domain.com:514,facility=local7,tag=nginx,severity=warn main;
```

**Describe alternatives you've considered**
Not sure how to make changes which are persistent to changes via the gui.

**Additional context**
I guess this is not needed.
If yes please let me know.

I guess this is the same request but it has been closed. -> https://github.com/opnsense/plugins/issues/3469

**Comment by wesystems** [comment]
+1 for a Option for Error Logging persistent Configuration in the GUI

**Comment by kulikov-a** [comment]
sound reasonable imho. I'll try to find time for this if @fabianfrz  is not against the idea

**Comment by fabianfrz** [comment]
@kulikov-a feel free to implement it. When I implemented it for the access log, it was not possible with the error log as the syslog option was missing. If it is there, you can add the functionality.

**Comment by kulikov-a** [comment]
@fabianfrz thanks!
