### ISSUE TITLE
[os-node_exporter ] Add SMART option to node exporter or option to use textfile collector

### ISSUE THREAD

**Issue by evanrich** [opnsense/plugins#3906]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X ] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X ] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
Feature Request

**Describe the solution you'd like**
The Node Exporter plugin offers a number of options, such as ZFS, NTP, DEV, interrupts, etc.  One thing missing though, is SMART status.   If one has the os-smart plugin installed, you can get metrics on the drive installed (such as SSD life remaining, a key thing to watch).   The Prometheus node exporter supports the use of a textfile collector that COULD grab output from a smartctl script, there is also PySMART which can grab smart ctl data as well.  It would be nice to have an option for either specifing a "textfile collector directory" so that we could run a script to do this, or have the plugin have a "SMART" option to expose smart metrics from the drive(s) in OpnSense

**Describe alternatives you've considered**
I could probably hand edit the node exporter config to do this but it might get erased upon updates. Also using some other tool, such as PySMART may work as well but have not tried it adn would require me running scripts on the box.  There is also https://github.com/Naudit/pySMART-exporter which is an exporter specifically for PySMART that I could run locally

**Comment by jwidess** [comment]
@evanrich to address this, I made a little script and configd action to automatically collect and send Smartctl data to Prometheus via a text file collector. More info on my repo here: https://github.com/jwidess/OPNsense-node-exporter-smartctl-collect
**Note**: The script currently only collects NVMe drive data, so if you're using a SATA SSD, it won't work yet. I plan to add this functionality eventually. I'm also working on a Grafana dashboard for this data as well.
