### ISSUE TITLE
www/caddy: DynDNS IP Version cannot be reverted to 'None'

### ISSUE THREAD

**Issue by jasonpstokes** [opnsense/plugins#3912]
- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

Great plugin, so easy - thanks!

**Describe the bug**
In General Settings > Dynamic DNS, the '**DynDNS IP Version**' only allows `IPv4 only` OR `IPv6 only` once a selection has been made; i.e. you cannot set it to (back to) 'None' to get both again (A and AAAA-Records), as described in the UI help text and [docs](https://docs.opnsense.org/manual/how-tos/caddy.html#general-settings-dynamic-dns).

![image](https://github.com/opnsense/plugins/assets/29766924/9abf3faa-6607-404e-be6f-72b6e2f86c6e)

![image](https://github.com/opnsense/plugins/assets/29766924/5c070364-f0ef-41d7-abf6-0f5f37fe0dee)

**Expected behaviour**
An option to select 'None', or (perhaps clearer) 'Both' - or this would be a multi-select box instead, to select (tick) one or both IP versions?

**Environment**
OPNsense 24.1.5_1-amd64
os-caddy 1.5.3

**Comment by Monviech** [comment]
Thank you. I already noticed that a while ago and it's fixed in the next version. The fix is already merged to main.
