### ISSUE TITLE
Request: Pomerium Plugin

### ISSUE THREAD

**Issue by eplusresearch** [opnsense/plugins#3913]
[Pomerium](https://www.pomerium.com/) is an identity and context-aware access proxy.

Pomerium builds secure, clientless connections to internal web apps and services without a corporate VPN.

Pomerium is:
- Easier because you don’t have to maintain a client or software.
- Faster because it’s deployed directly where your apps and services are. No more expensive data backhauling.
- Safer because every single action is verified for trusted identity, device, and context.
- It’s not a VPN alternative – it’s the trusted, foolproof way to protect your business.

Posting rules:

[✅ ] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
[✅ ] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
[ N/A] When the request is meant for an existing plugin, I've added its name to the title.

**Comment by mimugmail** [comment]
Looks nice, but freebsd port is way outdated and they dont offer freebsd go builds

**Comment by Monviech** [comment]
Is it the same as Authelia ( https://www.freshports.org/www/authelia/ ) or something totally different?

These kind of solutions imply that the service they proxy support Single Sign On.
