### ISSUE TITLE
www/caddy: handler sorting by domain not alphabetical

### ISSUE THREAD

**Issue by ryanwinter** [opnsense/plugins#3914]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
Sorting the `Domain` in the Handler tab of the reverse proxy settings does not sort the Domains alphabetically as expected.

**To Reproduce**
1. Go to `Services | Caddy Web Server | Reverse Proxy | Handlers`
2. Press the `Domain` header of the Handler table.
3. Observe the Domains are not sorted alphabetically

**Expected behavior**
Sorting the Domains should be alphabetical.

**Screenshots**
<img width="246" alt="image" src="https://github.com/opnsense/plugins/assets/10238039/dd4c7dae-181a-410b-8783-4d67182fa029">

OPNsense 24.1.5 (amd64).
Intel® N100 (4 cores, 4 threads)
Intel(R) Ethernet Controller I226-V

**Comment by Monviech** [comment]
I don't know how the sorting is determined. @AdShellevis could you help me here?

**Comment by ryanwinter** [comment]
Looking at the server request, it appear to be sorting by description, and these are all empty in my case:
<img width="409" alt="image" src="https://github.com/opnsense/plugins/assets/10238039/b4e5299c-8649-476a-b5cb-6e4c38647074">

**Comment by ryanwinter** [comment]
I believe the column is incorrectly names `reverse` as shown here:
https://github.com/opnsense/plugins/blob/8f2490aa8a1a1d057d1de2a30521d0037cc3c519/www/caddy/src/opnsense/mvc/app/views/OPNsense/Caddy/reverse_proxy.volt#L206C28-L206C88

**Comment by ryanwinter** [comment]
Oh maybe not, it appears to be defined as that in the xml too.

**Comment by Monviech** [comment]
It's a model relation field. It just displays as domain, but in the background its an UUID. Maybe it gets sorted by the UUID? (theyre the UUIDs of the domain page in this case, since the field in handlers refers to domains.)

**Comment by Monviech** [comment]
@AdSchellevis Is there a way to sort a model relation field in the bootgrid by their display name, and not by the UUID of the field they are referencing?

**Comment by AdSchellevis** [comment]
@Monviech I looked briefly at you code, when all you're doing is `return $this->searchBase("reverseproxy.handle", null, 'description');` on a standard model using `ModelRelationField`, best open a core ticket for this.  I suppose the grid search is either missing an "unpack" or the `ModelRelationField` doesn't return it properly yet. Both issues are mine to fix.

**Comment by Monviech** [comment]
@AdSchellevis The main version is not live for the users yet, they are still using the last stable code: https://github.com/opnsense/plugins/blob/4d63eeca500174b9faccbdf98bb129b19d4415a9/www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/Api/ReverseProxyController.php#L112

Thank you for looking into this. I'll open up a core ticket if needed. :)

**Comment by Monviech** [comment]
@ryanwinter Thanks for noticing this, it will be fixed in a future opnsense version. You can check the connected issue and PR. Please close this if you can. Thanks :)

**Comment by ryanwinter** [comment]
Thanks @Monviech!
