### ISSUE TITLE
os-relayd won't start if virtual server name is too long

### ISSUE THREAD

**Issue by knan-md** [opnsense/plugins#3916]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [ x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [ x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [ x] The title contains the plugin to which this issue belongs

**Describe the bug**
If you add a virtual server to relayd that has a name longer than 31 characters, and click apply, relayd will stop and not restart until you remove or shorten the virtual server name.

**To Reproduce**
1. Go to services => relayd => settings
2. Add a host on the Backend Hosts tab
3. Add a table on the Tables tab, including the host you added
4. Go to the virtual servers tab, click add
5. For server type, pick redirection
6. Pick the table you just created in tables
7. Fill out an arbitrary listen address and listen port
8. Type a name of >31 characters in the Name field
9. Save, Apply
10. Relayd won't run.

**Expected behavior**
Relayd running, or error message in the UI.

**Relevant log files**
relayd.conf:

interval 1
log state changes
log host checks
prefork 3
timeout 200

table <localhost-4446> {
127.0.0.1
}

redirect "localhost-4446 blarg blarg blatt" {
listen on 192.168.2.1 tcp port 10001
forward to <localhost-4446> port 4446 mode roundrobin  check https "/rules.limits" host acs-areq code 200
session timeout 600
}

root@OPNsense:/usr/local/etc # relayd -n
configuration OK

root@OPNsense:/usr/local/etc # relayd -d
startup
pfe: init_tables: name too long: Invalid argument
hce exiting, pid 27854
ca exiting, pid 28639
relay exiting, pid 28317
relay exiting, pid 28311
relay exiting, pid 28285
lost child: pid 27407 exited abnormally
ca exiting, pid 28730
ca exiting, pid 28836
parent terminating, pid 27011

**Environment**
OPNsense 24.1.5_3

**Comment by AdSchellevis** [comment]
@knan-md https://github.com/opnsense/plugins/commit/e7602ec2ad5a0af568526aa9ada142afb19a6ef2 should do the trick here

**Comment by knan-md** [comment]
Looks good to me! :)
