### ISSUE TITLE
Caddy DNS Provider secret field missing

### ISSUE THREAD

**Issue by jpieren** [opnsense/plugins#3922]
Hi,
Thank you for the good work with caddy! really appreciated.

Version Installed:
OPNsense 24.1.6-amd64
os-caddy (installed) | 1.5.4
os-crowdsec (installed) | 1.0.7

Steps:
I currently use GoDaddy DNS.
In the Service--> Caddy Web Server --> General Settings DNS Provider Tab:
selected GoDaddy DNS, I can enter the API key but nowhere the secret.
--see screenshot attached
![General Settings Caddy Web Server Services OPNsense xyz 2024-04-19 at 10 37 18 AM](https://github.com/opnsense/plugins/assets/5875107/9c82d445-d401-4d0a-9b72-ddffa0ab343f)

I tried to use the additional field 1 but that didn't help.

Error in Log File:

"error","ts":"2024-04-18T22:02:44Z","logger":"dynamic_dns","msg":"unable to lookup current IPs from DNS records","error":"could not get records: Domain: ; Status: 401; Body: {"code":"MALFORMED_CREDENTIALS","message":"Unauthorized : API Key-Secret is malformed"}"}

I have overlooked something where to enter the API secret?

regards
Jay

**Comment by jpieren** [comment]
add new with template

**Comment by Monviech** [comment]
Hey, so do you have a problem here? The Caddy DNS provider for Godaddy doesnt specify an additional api secret key, online one api token.

https://github.com/caddy-dns/godaddy

**Comment by jpieren** [comment]
Thank you  very much for the feedback, yes key:secret works.

**Comment by Monviech** [comment]
@jpieren If your problem is solved please close your duplicate issue too. https://github.com/opnsense/plugins/issues/3923
