### ISSUE TITLE
FRR BGP Prefix-List RouteMap Bug

### ISSUE THREAD

**Issue by touqeeranjum** [opnsense/plugins#3926]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x ] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [ x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [ x] The title contains the plugin to which this issue belongs

**Describe the bug**
There is an issue in FRR BGP Prefix-List and RouteMap where when a prefix-List with multiple networks (whether permitted or Denied)are added to RouteMap, only 1 network is advertised to the other peer. I have tested this over and over again between a Fortigate and an OPNSense v24.1.5.

https://forum.opnsense.org/index.php?topic=40066.0

**To Reproduce**
1. Create a new Prefix-List
2. Add any 2 or more different networks
3. Add the newly created prefix-List to a RouteMap
4. Add the RouteMap to the neighbour
5. Save the BGP settings

**Screenshots**
![image](https://github.com/opnsense/plugins/assets/47591211/023a332e-5407-41d5-b014-691e2e07c3a7)

![image](https://github.com/opnsense/plugins/assets/47591211/0621ef4c-daf5-42bf-8e5a-6bd89f5fe52b)

**Expected behavior**
The Fortigate will only receive 1 network from the Prefix-List

1) No Prefix-List added to neighbours
```
Routing table for VRF=0
B       10.10.11.0/24 [20/1] via 192.168.3.151 (recursive is directly connected, port1), 00:00:00, [1/0]
B       10.10.12.0/24 [20/1] via 192.168.3.151 (recursive is directly connected, port1), 00:00:00, [1/0]
B       10.10.13.0/24 [20/1] via 192.168.3.151 (recursive is directly connected, port1), 00:00:00, [1/0]
C       192.168.3.0/24 is directly connected, port1
B       192.168.30.0/24 [20/1] via 192.168.3.151 (recursive is directly connected, port1), 00:00:00, [1/0]
B       192.168.35.0/24 [20/1] via 192.168.3.151 (recursive is directly connected, port1), 00:00:00, [1/0]
C       192.168.40.0/24 is directly connected, port2
C       192.168.50.0/24 is directly connected, port3
```

2) 1 Prefix-List which has only 1 network (10.10.11.0/24) in it, advertises fine.
```
Routing table for VRF=0
B       10.10.11.0/24 [20/1] via 192.168.3.151 (recursive is directly connected, port1), 00:00:15, [1/0]
C       192.168.3.0/24 is directly connected, port1
C       192.168.40.0/24 is directly connected, port2
C       192.168.50.0/24 is directly connected, port3
```

3) With 1 Prefix-List with 2 networks in it (10.10.11.0/24, 192.168.35.0/24), only 1 network is advertised.
```
Routing table for VRF=0
C       192.168.3.0/24 is directly connected, port1
B       192.168.35.0/24 [20/1] via 192.168.3.151 (recursive is directly connected, port1), 00:00:20, [1/0]
C       192.168.40.0/24 is directly connected, port2
C       192.168.50.0/24 is directly connected, port3
```

**Relevant log files**
If applicable, information from log files supporting your claim.

**Additional context**
If a multiple Prefix-Lists are created with same name and different networks are created and then added to either RouteMap, or added as a prefix-List Outbound to the neighbours, it works as expected.

![image](https://github.com/opnsense/plugins/assets/47591211/6441710a-eab4-419d-b9d5-d598f00452dd)

![image](https://github.com/opnsense/plugins/assets/47591211/467d9d8a-b2f8-4cfe-a629-3d35eb0c3e2d)

```
Routing table for VRF=0
B       10.10.11.0/24 [20/1] via 192.168.3.151 (recursive is directly connected, port1), 00:01:52, [1/0]
C       192.168.3.0/24 is directly connected, port1
B       192.168.30.0/24 [20/1] via 192.168.3.151 (recursive is directly connected, port1), 00:01:52, [1/0]
C       192.168.40.0/24 is directly connected, port2
C       192.168.50.0/24 is directly connected, port3
```

**Environment**
Tested in ESXi, and VMware Workstation
Tested in OPNsense 24.1.5, and OPNSense v 23.1.11

**Comment by joni1993** [comment]
For me the prefix-list options for neighbors do nothing at all - no filter is applied.

**Comment by joni1993** [comment]
So the problem seems to be related to the fact that you need multiple entries in the "Prefix-List" tab with the same same name but different sequences.

In [/usr/local/opnsense/service/templates/OPNsense/Quagga/bgpd.conf:Line192`](https://github.com/opnsense/plugins/blob/70ecb2abd5a26d45978f901ae3dcec95144f81c5/net/frr/src/opnsense/service/templates/OPNsense/Quagga/bgpd.conf#L192) there is a check for enabled.

If you have multiple entries and the first one is disabled you don't apply the prefix-list at all.

**Comment by joni1993** [comment]
@touqeeranjum Regarding your specific issue i think your prefix-list entry is just invalid. This is not a comma separated list (see https://docs.frrouting.org/en/latest/filter.html#clicmd-ip-prefix-list-NAME-permit-deny-PREFIX-le-LEN-ge-LEN).
Instead you want to have two entries with the same prefix-list name but a different sequence number.
