### ISSUE TITLE
www/caddy: v1.5.5

### ISSUE THREAD

**Issue by Monviech** [opnsense/plugins#3935]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] When the request is meant for an existing plugin, I've added its name to the title.

Tracker for next version:
- [x] https://github.com/opnsense/plugins/pull/3938
- [x] https://github.com/opnsense/plugins/pull/3934
- [x] https://github.com/opnsense/plugins/pull/3937
- [x] https://github.com/opnsense/plugins/pull/3941
- [x] https://github.com/opnsense/plugins/pull/3944
- [x] https://github.com/opnsense/plugins/pull/3960
- [x] https://github.com/opnsense/plugins/pull/3957
- [x] https://github.com/opnsense/plugins/pull/3956
- [x] https://github.com/opnsense/plugins/pull/3948
- [x] https://github.com/opnsense/plugins/pull/3967
- [x] https://github.com/opnsense/plugins/pull/3977
- [x] https://github.com/opnsense/plugins/pull/3974
- [x] https://github.com/opnsense/plugins/pull/3967
- [x] https://github.com/opnsense/plugins/pull/3978

Docs:
- [x] https://github.com/opnsense/docs/pull/556

**Comment by Monviech** [comment]
@Fichtner This version is done, there won't be any more changes or additions.

**Comment by fichtner** [comment]
@Monviech if this is all feel free to close (even if small updates are still coming in later)

**Comment by Monviech** [comment]
@fichtner Sure, thank you for the review and the merge. :)

**Comment by Monviech** [comment]
Everything done here.
