### ISSUE TITLE
Acme-Client Support Caddy Reverseproxy + (Maybe Exchange Support?)

### ISSUE THREAD

**Issue by phillipunzen** [opnsense/plugins#3943]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [ X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [ X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [ X] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
My request is to solve the problem of replacing the SSL certificate at the Caddy reverse proxy. Currently, when I create a new SSL certificate, I have to stop the Caddy web server, then restart the firewall, and then restart the service. 

**Describe the solution you'd like**
It would be great if a new SSL certificate is generated, the caddy web server automatically uses the new certificate. Unfortunately, this didn't work for me. The actual solution can you see above. You can add a checkbox or something to enable the function. 

Maybe there is also a way to automatically exchange the certificate on an Exchange server in the automations? Currently, I have a combination of Bitvise SSH Server and Powershell Script, which is not 100% stable. The same certificate must be used in both places, otherwise Outlook has a problem

**Comment by Monviech** [comment]
- Where do you create a new SSL certificate? A reload of caddy automatically reads all certificates from the OPNsense trust store.
https://github.com/opnsense/plugins/blob/master/www/caddy/src/opnsense/scripts/OPNsense/Caddy/caddy_certs.php
https://github.com/opnsense/plugins/blob/ee0f83169a519c35780b0ae13cd2d911c31aeccb/www/caddy/src/opnsense/scripts/OPNsense/Caddy/setup.sh#L26
https://github.com/opnsense/plugins/blob/ee0f83169a519c35780b0ae13cd2d911c31aeccb/www/caddy/src/opnsense/service/templates/OPNsense/Caddy/rc.conf.d/caddy#L7

- If you want to use the ACME Client plugin, you can create an automation in it that reloads the caddy service. 

Services: ACME Client: Automations
Run Command: System or Plugin Command
System Command: Reload Caddy service

- Automations won't be added, this is not in the scope of this plugin. There is the ACME Client Plugin for these kind of solutions.

- Maybe the plugin doesn't fit your advanced usecase? Caddy works best if you use the automatic Let's Encrypt and ZeroSSL certificates it manages itself - without needing any additional configuration.

**Comment by Monviech** [comment]
Actually there might be a specific issue with reload vs. restart the caddy service when it comes to loading the certificates from an external source. I'm looking into it.
