### ISSUE TITLE
www/caddy: Migrate from root:wheel to unprivileged user?

### ISSUE THREAD

**Issue by Monviech** [opnsense/plugins#3946]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
https://github.com/opnsense/ports/blob/31b0d3f1d237014192beccdb6e66a1089335ad6d/www/caddy-custom/files/caddy.in#L13-L14

It would increase security (probably). I don't know how to measure the improvement, but since the rc.d file strongly recommends it, and OPNsense is a security appliance, it might be worth to harden it.

**Describe the solution**
Change caddy to an unprivileged user:group, like ```www:www``` as the rc.d file suggests.

```mac_portacl(4)```
would become an indirect dependency since it would be needed to bind to ports lower than 1023 on the system.

A regression would be that users couldn't freely use other ports below 1024 anymore without explicitely allowing it with portacl. So it would be restricted to ```80```, ```443``` and ```>=1024``` most likely.

-------------

Hardening the security would need adjustements to the OPNsense core, especially the loader.conf. These have to be carefully planned, since a wrong configuration here could potentially deny all applications from binding their ports.

* ```mac_portacl_load="YES"``` - This would enable the load of ```mac_portacl```
* ```security.mac.portacl.enabled``` - This enables the mac_portacl policy.
* ``` security.mac.portacl.port_high``` - This will enforce mac_portacl for all ports under 1024. (So 1023 and below.)
* ```security.mac.portacl.suser_exempt``` - This exempts ```root``` from the rules that mac_portacl imposes. This setting gives backwards compatibility to all "legacy" applications that use a superuser to bind their ports.
* ```security.mac.portacl.autoport_exempt``` allows all applications to bind to port 0.
* ```security.mac.portacl.rules``` sets the rule for the user:group ID that is allowed to bind to a specific port. It would be easier to maintain, if a user:group like www:www is used, to allow other www/ ports to reuse these easily. The rc.d file of caddy also states, that www:www is recommended.

For more information: ```man mac_portacl```

A change like this would be in line with the planned future of the OPNsense, detaching processes from root: https://docs.opnsense.org/development/guidelines/basics.html

**Describe alternatives you've considered**
Leaving everything as it is on ```root:wheel``` (don't fix what ain't broken).
The scope of this change can potentially affect all other applications, if the loader.conf settings aren't very precise!

**Comment by Monviech** [comment]
To run caddy (or any other webserver that will use ```www:www``` and ```priviledged ports```) as unpriviledged user and group, using ```www:www``` the following adjustements have to be made:

1. These tunables have to be set, (can be set via OPNsense GUI, tunables):
Reference: https://docs.freebsd.org/en/books/handbook/mac/#mac-portacl
```
mac_portacl_load="YES"
security.mac.portacl.enabled="1"
security.mac.portacl.suser_exempt="1"
security.mac.portacl.autoport_exempt="1"
sysctl security.mac.portacl.port_high="1023"
net.inet.ip.portrange.reservedlow="0"
net.inet.ip.portrange.reservedhigh="0"
security.mac.portacl.rules="uid:80:tcp:80,uid:80:tcp:443,uid:80:udp:80,uid:80:udp:443,gid:80:tcp:80,gid:80:tcp:443,gid:80:udp:80,gid:80:udp:443"
```

Small note: the security.mac.portacl.rules seem to be only set when using ```sysctl security.mac.portacl.rules="uid:80:tcp:80,uid:80:tcp:443,uid:80:udp:80,uid:80:udp:443,gid:80:tcp:80,gid:80:tcp:443,gid:80:udp:80,gid:80:udp:443"```

2. ```/etc/sysctl.conf``` has to be appended with:

```options MAC```

3. The caddy process has to be changed to ```www:www```
Reference: https://github.com/opnsense/ports/blob/31b0d3f1d237014192beccdb6e66a1089335ad6d/www/caddy-custom/files/caddy.in#L27

```sysrc caddy_user=www caddy_group=www```

4. The ownership of the following paths have to be recursively adjusted to be owned by ```www:www``` instead of ```root:wheel```

```
/var/run/caddy
/usr/local/etc/caddy
/var/db/caddy
/var/log/caddy
```

**Comment by fichtner** [comment]
Worst case this requires core changes to integrate neatly, which are not overly appealing as they add complications and bind different subsystems together that should remain independent for easy maintenance.

**Comment by Monviech** [comment]
@Fichtner It's not a must have. Its something to keep in mind for the future to harden the security. The one sore thumb still sticking out is that almost everything that needs priviledged ports is forced to run as root superuser.

**Comment by fichtner** [comment]
I understand. The easiest solution is a root option but since HTTP/S is 80/443 you’ll end up people opting in in 99% of the cases so these hoops seem necessary to make it work without root access.

BTW, a chroot is not an option?

**Comment by Monviech** [comment]
I don't have any experience with chroot jail stuff, so I don't know...

I thought, setting this up as a "framework" for the already existing user ```www:www``` would be the best maintainable usecase, since any webserver app could profit from it.

Additionally, with:
```
security.mac.portacl.suser_exempt="1"
security.mac.portacl.autoport_exempt="1"
```

none of the already existing applications that run on root or bind to port 0 would be affected. So it's a transparent change judging from the man pages and the freebsd handbook. It's also the default values.

In the future, a security framework like that could be expanded to more users, to migrate more applications away from root easily, by setting the needed ACLs to these users.

**Comment by Monviech** [comment]
This port would be needed: https://github.com/opnsense/ports/tree/master/security/portacl-rc

It allows to set ```security.mac.portacl.rules``` via ```sysrc```.

Otherwise, things like ```sysctl security.mac.portacl.rules=uid:80:tcp:80``` can only be invoked directly with the ```sysctl``` command. Setting it in ```sysctl.conf``` and ```loader.conf``` are ignored during boot.

```
Runtime Configuration
     The following sysctl(8) MIBs are available for fine-tuning the enforce-
     ment of this MAC policy.  All sysctl(8)] variables, except
     security.mac.portacl.rules, can also be set as loader(8) tunables in
     loader.conf).
```

@fichtner 

I can write a ticket in core with whats exactly needed to prepare for ```security.mac.portacl```. It's an addition, which multiple ports and plugins could benefit from, and it enhances security without imposing a too high maintainability overhead (like using jails would).

Though, I'm also open to drop this, if the potential side effects are too unpredictable and there are other more important goals right now.

**Comment by Monviech** [comment]
Probably not a good idea for now. Would need an additional plugin for portacl_rc.
