### ISSUE TITLE
Caddy rewrite directive

### ISSUE THREAD

**Issue by Damix48** [opnsense/plugins#3947]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
Currently, the Caddy plugin only enables the `reverse_proxy` directive through the web UI. Is it possible to modify the `autosave.json` file to add a `rewrite` directive for a subdomain?

**Describe the solution you'd like**
Add other configuration like `rewrite`

**Describe alternatives you've considered**
Using caddy without the plugin(?)

**Additional context**
I would like to replicate this configuration:

```
subdomain.{$DOMAIN} {
  rewrite /path /test/path
  @rewrite {
    path_regexp user ^/users/(.+)/path
    not path_regexp ^/users/(.+)/path/
  }
  rewrite @rewrite /test/users/{re.user.1}/path
  reverse_proxy {$IP}:8096
}
```

**Comment by Monviech** [comment]
https://docs.opnsense.org/manual/how-tos/caddy.html#using-custom-configuration-files

**Comment by Damix48** [comment]
Thank you
