### ISSUE TITLE
www/OPNProxy: Applying config changes throws errors

### ISSUE THREAD

**Issue by 0x646f6d** [opnsense/plugins#3962]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
Yestereday I upgraded from to opnsense community to business 24.4. I tried setting up some ACLs. After hitting Apply the first time it took quite long until I received an error 504 - see screenshots. Any other change raises other errors, like the second screenshot. 

I wasn't able to narrow it down any further. Maybe it could be related to that [bug](https://github.com/opnsense/plugins/issues/3827) which I also observe?

I tried if the ACLs are applied anyways and they seem to be applied properly after a squid restart!

**To Reproduce**
1. Go to 'Services -> Squid Web Proxy -> Access Control'
2. Click on '+'
3. Create any arbirary ACL

**Expected behavior**
It should save the ACL successfully.

**Screenshots**
![grafik](https://github.com/opnsense/plugins/assets/36824122/f2c9fe04-79e3-4cc0-bfa5-4e0dc1e2e8ad)
![grafik](https://github.com/opnsense/plugins/assets/36824122/765b9676-6d87-487d-bf78-68f9716c304c)

**Relevant log files**
![grafik](https://github.com/opnsense/plugins/assets/36824122/b0c1748f-024a-4c1d-80fc-27d49954a6b2)
![grafik](https://github.com/opnsense/plugins/assets/36824122/b62ee49f-1d30-4d95-adbf-ebfd940b1d94)

**Additional context**
Some releases earlier we used the old squid proxy authentication mechanisms which have been orphaned around a year or so. Possibly there is an old config which produces side effects? 

**Environment**
OPNsense Business Edition 24.4-amd64
Intel(R) Xeon(R) CPU D-1518 @ 2.20GHz (4 cores, 8 threads)
Network Intel® I210-AT

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/plugins/issues/3827 is indeed the same upstream issue. OPNproxy tries to reconfigure squid after applying policies. You could try to remove the reconfigure action from the config action (including the && on the previous line), the real fix unfortunately needs an upstream fix (squid).

https://github.com/opnsense/plugins/blob/da53031f7fe8f4fe26511164780819d9d0b52d69/www/OPNProxy/src/opnsense/service/conf/actions.d/actions_opnproxy.conf#L4

**Comment by 0x646f6d** [comment]
Thank you for your answer. Alright, understood. So it seems that this issue could be closed, if you aggree?

**Comment by AdSchellevis** [comment]
let's close indeed. if the issues in squid remain, at some point we might decide to remove the `reconfigure` actions, but as this has downsides of its own, I would leave it as is for now.
