### ISSUE TITLE
NET-SNMP: Add advanced configurations dialog to config screen

### ISSUE THREAD

**Issue by camsaway** [opnsense/plugins#3964]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
There is additional data that I would like to expose via SNMP (specifically CPU and SSD temps exposed from sysctl and smartctl). To do so I need to add extend commands to the snmpd.conf file that will not be overwritten on saving new settings.

**Describe the solution you'd like**
I would like a textbox "advanced configurations" added to the Settings screen for Net-SNMP

**Describe alternatives you've considered**
* Trying to deploy a subagent / secondary SNMP agent that is not controlled by OPNSense UI and us AgentX configuration - I would prefer not to run two SNMP installations (one from CLI only)
* A more complicated settings configuration screen change, specifically allow for the configuration of multiple extend parameters and scripts (limits use of advanced SNMP options and would take more time/effort)
* Specifically adding hardware metrics to the standard set of SNMP metrics that are deployed on with the OPNSense Net-SNMP Plug-in (but would likely create a host of different challenges for the different hardware configurations and what people want to monitor)

**Additional context**
I'm relatively new to OPNSense, so if there is an easier way to achieve what I want, please let me know. I have spent literally days googling for answers and options on this one.
I'm not a coder, but I'm even prepared to try to create a PR to do this if someone can assist me. Adding the AgentX support didn't look like a big change and I believe there are other text box config options I could look to as an example on how to do it.

**Comment by fichtner** [comment]
This is against our established security guideline. If you need custom configuration either use the template override, provide feature request or PR for individual options, or use the package manually without the plugin.


Cheers,
Franco

**Comment by camsaway** [comment]
Thank you @fichtner both for the VERY prompt response and guidance. I'll give template overrides a go.
