### ISSUE TITLE
security/acme-client: Failing to add txt record – Cloudflare

### ISSUE THREAD

**Issue by mullcom** [opnsense/plugins#3969]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [ ] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
(YES)

- [ ] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
(YES)

- [ ] The title contains the plugin to which this issue belongs
(Don't understand question)

**Describe the bug**
A clear and concise description of what the bug is, including last known working version (if any).

1. I have try making different changes in the config in UI in opnsens. To find out the behavior us different and get more knowledge.
2. I have ssh and delit old files and temp files.
3. Try to find if something old still there. Lack of knowledge make it difficult to 100% verify. 
4. Reinstall.
5. Remove plugin an install it.
6. Every thing I do I get later the same wring error in the Log. 

Error add txt for domain:_acme-challenge.domain.se
Add txt record error.

**To Reproduce**
1. Add let's encryp account.
2. Setup challenge type that is for CF
3. Follow the steps and fill the information 
4. Selecting DNS-01 as type , DNS service cloudflare.com , fill in email and global key.
5.create a cert for my root domain and subbs domains. 
6. Chuse the service and account.
Then run.

**Expected behavior**
it should be able to add txt record because it have the right to do so. It seams in the logs that it able to use API for connecting.

**Relevant log files**
OpenSSL 1.1.1t-freebsd 7 Feb 2023
openssl:openssl
[Tue May 7 14:35:21 CEST 2024] Diagnosis versions:
[Tue May 7 14:35:21 CEST 2024] code='200'
[Tue May 7 14:35:21 CEST 2024] _ret='0'
[Tue May 7 14:35:21 CEST 2024] _CURL='curl --silent --dump-header /var/etc/acme-client/home/http.header -L --trace-ascii /tmp/tmp.uvle2lrU -g '
[Tue May 7 14:35:21 CEST 2024] _post_url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/347794050257/Jalcag'
[Tue May 7 14:35:21 CEST 2024] POST
[Tue May 7 14:35:20 CEST 2024] payload='{}'
[Tue May 7 14:35:20 CEST 2024] url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/347794050257/Jalcag'
[Tue May 7 14:35:20 CEST 2024] =======Begin Send Signed Request=======
[Tue May 7 14:35:20 CEST 2024] code='200'
[Tue May 7 14:35:20 CEST 2024] _ret='0'
[Tue May 7 14:35:20 CEST 2024] _CURL='curl --silent --dump-header /var/etc/acme-client/home/http.header -L --trace-ascii /tmp/tmp.uvle2lrU -g '
[Tue May 7 14:35:20 CEST 2024] _post_url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/347794050287/QOSbHg'
[Tue May 7 14:35:20 CEST 2024] POST
[Tue May 7 14:35:20 CEST 2024] payload='{}'
[Tue May 7 14:35:20 CEST 2024] url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/347794050287/QOSbHg'
[Tue May 7 14:35:19 CEST 2024] =======Begin Send Signed Request=======
[Tue May 7 14:35:19 CEST 2024] code='200'
[Tue May 7 14:35:19 CEST 2024] _ret='0'
[Tue May 7 14:35:19 CEST 2024] _CURL='curl --silent --dump-header /var/etc/acme-client/home/http.header -L --trace-ascii /tmp/tmp.uvle2lrU -g '
[Tue May 7 14:35:19 CEST 2024] _post_url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/347794050267/y6YC9w'
[Tue May 7 14:35:19 CEST 2024] POST
[Tue May 7 14:35:19 CEST 2024] payload='{}'
[Tue May 7 14:35:19 CEST 2024] url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/347794050267/y6YC9w'
[Tue May 7 14:35:19 CEST 2024] =======Begin Send Signed Request=======
[Tue May 7 14:35:19 CEST 2024] code='400'
[Tue May 7 14:35:19 CEST 2024] _ret='0'
[Tue May 7 14:35:18 CEST 2024] _CURL='curl --silent --dump-header /var/etc/acme-client/home/http.header -L --trace-ascii /tmp/tmp.uvle2lrU -g '
[Tue May 7 14:35:18 CEST 2024] _post_url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/347794050277/ob7B9A'
[Tue May 7 14:35:18 CEST 2024] POST
Tue May 7 14:35:18 CEST 2024] POST
[Tue May 7 14:35:18 CEST 2024] payload='{}'
[Tue May 7 14:35:18 CEST 2024] url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/347794050277/ob7B9A'
[Tue May 7 14:35:18 CEST 2024] =======Begin Send Signed Request=======
[Tue May 7 14:35:18 CEST 2024] code='200'
[Tue May 7 14:35:18 CEST 2024] _ret='0'
[Tue May 7 14:35:17 CEST 2024] _CURL='curl --silent --dump-header /var/etc/acme-client/home/http.header -L --trace-ascii /tmp/tmp.uvle2lrU -g '
[Tue May 7 14:35:17 CEST 2024] _post_url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/347794050277/ob7B9A'
[Tue May 7 14:35:17 CEST 2024] POST
[Tue May 7 14:35:17 CEST 2024] payload='{}'
[Tue May 7 14:35:17 CEST 2024] url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/347794050277/ob7B9A'
[Tue May 7 14:35:17 CEST 2024] =======Begin Send Signed Request=======
[Tue May 7 14:35:17 CEST 2024] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[Tue May 7 14:35:17 CEST 2024] Please add '--debug' or '--log' to check more details.
[Tue May 7 14:35:17 CEST 2024] _on_issue_err
[Tue May 7 14:35:17 CEST 2024] Error add txt for domain:_acme-challenge.routeme.se
[Tue May 7 14:35:17 CEST 2024] Add txt record error.
[Tue May 7 14:35:17 CEST 2024] _ret='0'
[Tue May 7 14:35:16 CEST 2024] _CURL='curl --silent --dump-header /var/etc/acme-client/home/http.header -L --trace-ascii /tmp/tmp.uvle2lrU -g '
[Tue May 7 14:35:16 CEST 2024] _post_url='https://api.cloudflare.com/client/v4/zones/e88df047b6ac5922186155fab4f09810/dns_records'
[Tue May 7 14:35:16 CEST 2024] POST
[Tue May 7 14:35:16 CEST 2024] data='{"type":"TXT","name":"_acme-challenge.routeme.se","content":"T9hKnpN4KjS2qQU3vmxovkAMRydulyDRzisH_qRk5Yc","ttl":120}'
[Tue May 7 14:35:16 CEST 2024] zones/e88df047b6ac5922186155fab4f09810/dns_records
[Tue May 7 14:35:16 CEST 2024] Adding record
[Tue May 7 14:35:16 CEST 2024] ret='0'
[Tue May 7 14:35:15 CEST 2024] _CURL='curl --silent --dump-header /var/etc/acme-client/home/http.header -L --trace-ascii /tmp/tmp.uvle2lrU -g '
[Tue May 7 14:35:15 CEST 2024] timeout=
[Tue May 7 14:35:15 CEST 2024] url='https://api.cloudflare.com/client/v4/zones/e88df047b6ac5922186155fab4f09810/dns_records?type=TXT&name=_acme-challenge.routeme.se'
[Tue May 7 14:35:15 CEST 2024] GET
[Tue May 7 14:35:15 CEST 2024] zones/e88df047b6ac5922186155fab4f09810/dns_records?type=TXT&name=_acme-challenge.routeme.se
[Tue May 7 14:35:15 CEST 2024] Getting txt records
[Tue May 7 14:35:15 CEST 2024] _domain='routeme.se'
[Tue May 7 14:35:15 CEST 2024] _sub_domain='_acme-challenge'
[Tue May 7 14:35:15 CEST 2024] _domain_id='e88df047b6ac5922186155fab4f09810'
[Tue May 7 14:35:15 CEST 2024] ret='0'
[Tue May 7 14:35:14 CEST 2024] _CURL='curl --silent --dump-header /var/etc/acme-client/home/http.header -L --trace-ascii /tmp/tmp.uvle2lrU -g '
[Tue May 7 14:35:14 CEST 2024] timeout=
7 14:35:14 CEST 2024] url='https://api.cloudflare.com/client/v4/zones?name=routeme.se'
[Tue May 7 14:35:14 CEST 2024] GET
[Tue May 7 14:35:14 CEST 2024] zones?name=routeme.se
[Tue May 7 14:35:14 CEST 2024] h='routeme.se'
[Tue May 7 14:35:14 CEST 2024] ret='0'
[Tue May 7 14:35:13 CEST 2024] _CURL='curl --silent --dump-header /var/etc/acme-client/home/http.header -L --trace-ascii /tmp/tmp.uvle2lrU -g '
[Tue May 7 14:35:13 CEST 2024] timeout=
[Tue May 7 14:35:13 CEST 2024] url='https://api.cloudflare.com/client/v4/zones?name=_acme-challenge.routeme.se'
[Tue May 7 14:35:13 CEST 2024] GET
[Tue May 7 14:35:13 CEST 2024] zones?name=_acme-challenge.routeme.se
[Tue May 7 14:35:13 CEST 2024] h='_acme-challenge.routeme.se'
[Tue May 7 14:35:13 CEST 2024] First detect the root zone
[Tue May 7 14:35:13 CEST 2024] config file is empty, can not read SAVED_CF_Zone_ID
[Tue May 7 14:35:13 CEST 2024] config file is empty, can not read SAVED_CF_Account_ID
[Tue May 7 14:35:13 CEST 2024] config file is empty, can not read SAVED_CF_Token
[Tue May 7 14:35:13 CEST 2024] Adding txt value: T9hKnpN4KjS2qQU3vmxovkAMRydulyDRzisH_qRk5Yc for domain: _acme-challenge.routeme.se
[Tue May 7 14:35:13 CEST 2024] Found domain api file: /usr/local/share/examples/acme.sh/dnsapi/dns_cf.sh
[Tue May 7 14:35:13 CEST 2024] d_api='/usr/local/share/examples/acme.sh/dnsapi/dns_cf.sh'
[Tue May 7 14:35:13 CEST 2024] txt='T9hKnpN4KjS2qQU3vmxovkAMRydulyDRzisH_qRk5Yc'
[Tue May 7 14:35:12 CEST 2024] txtdomain='_acme-challenge.routeme.se'
[Tue May 7 14:35:12 CEST 2024] _d_alias
[Tue May 7 14:35:12 CEST 2024] d='routeme.se'
[Tue May 7 14:35:12 CEST 2024] The txt record is added: Success.
[Tue May 7 14:35:12 CEST 2024] Added, OK
[Tue May 7 14:35:12 CEST 2024] _ret='0'
[Tue May 7 14:35:12 CEST 2024] _CURL='curl --silent --dump-header /var/etc/acme-client/home/http.header -L --trace-ascii /tmp/tmp.uvle2lrU -g '
[Tue May 7 14:35:12 CEST 2024] _post_url='https://api.cloudflare.com/client/v4/zones/e88df047b6ac5922186155fab4f09810/dns_records'
[Tue May 7 14:35:12 CEST 2024] POST 

**Additional context**
The steps is one easiest way to reproduce the failing. But I try different setup to.

**Environment**

OPNsense 23.7.8 (amd64).
Intel® Xeon™ E3-1225V5 3.3Ghz Quad Core
Network Intel® I210-AT

**Comment by fraenki** [comment]
Probably related to #3871 and similar reports.

**Comment by fraenki** [comment]
> This didn't script like. So I be glad if someone can change script to ignore the same name in CN if it is in ALT name. This simplefy some mistakes from idiots like me.

I assume you're referring to acme.sh (or dns_cf.sh). You should report this issue to the acme.sh project:
https://github.com/acmesh-official/acme.sh/issues/new
