### ISSUE TITLE
Proxy/Squid: wpad.dat not generated correctly because of changes in getIPNetwork

### ISSUE THREAD

**Issue by tuxmainy** [opnsense/plugins#3988]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [ ] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
The commit https://github.com/opnsense/core/commit/67f6aeed2b40e1336c5c883b76486b2b41d4a17b changed the returned object class of `getIPNetwork` thus at least the `wpad.dat` template is not parsed correctly anymore as the call on `getIPNetwork().network` should now be replaced by `getIPNetwork().network_address`. This may impact other templates, too.

This issue occurred on 3 different 24.1.7 installations (one of it clean fresh install).

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**
1. Go to 'Services -> Squid Web Proxy -> Administration -> Proxy Auto-Config'
2. Setup a valid Auto-Config by adding a Rule, Proxy and Match. The match must be a "IP Is In Network"-type of value `10.0.0.0/24`
3. generate wpad.dat (should be done automatically)
4. request wpad.dat (e.g. `wget -O - http://<your opnsense>/wpad.dat`)

**Expected behavior**
the match should had been translated to:
`if (((isInNet(dstip, "10.0.0.0", "255.255.255.0")))) {` but is translated to `if (((isInNet(dstip, "", "255.255.255.0")))) {`

**Additional context**
I changed `tmp_net.network.__str__()` to `tmp_net.network_address.__str__()` in `/usr/local/opnsense/service/templates/OPNsense/Proxy/wpad.dat` which then produced the correct output.

**Environment**
Software version used and hardware type if relevant.
e.g.:

OPNsense 24.1.7 (amd64) fresh install

**Comment by fichtner** [comment]
Thanks, we will hotfix this today!
