### ISSUE TITLE
Haproxy, Using ${var} in strings is deprecated, use {$var} instead

### ISSUE THREAD

**Issue by zaidranger** [opnsense/plugins#3991]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [/] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [/] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [/] The title contains the plugin to which this issue belongs

**Describe the bug**
Cannot configure haproxy even after closing the danger popout warnings.

**To Reproduce**
1. Go to 'haproxy'
2. Click on 'anything from the sidemenu'
3. See error

**Expected behavior**
no dangers popout or can configure haproxy settings after closing said popouts

**Additional context**
I am aware that these will be replaced but as of now there is no way of configuring haproxy as long as the error is there, manually changing to {$var} fixes the issue but it's there again after an update.

**Comment by zaidranger** [comment]
Manually replaced the $(var) with ($var) and it worked again....hope it survives an update.

**Comment by fichtner** [comment]
It will not. Happy if you could provide a PR.

**Comment by zaidranger** [comment]
#4005

This fix is also applicable for acmeclient

**Comment by fichtner** [comment]
Thanks a lot! I forgot to mention that you probably have development mode enabled which is the only way this could break the API here?

**Comment by zaidranger** [comment]
Yeah i'm in development, i think that might be the case.
