### ISSUE TITLE
os-OPNWAF apache timeouts

### ISSUE THREAD

**Issue by 0x646f6d** [opnsense/plugins#3993]
- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
One of our backend websites requires to extend the default timeout of 60 seconds (MS Exchange Active Sync actually *facepalm*). 

**Describe the solution you'd like**
It would be great to have an option to make a persistant change to this config entry either via GUI or via a configuration file:
```
ProxyPass "balancer://<GUID>/" connectiontimeout=900
```

**Describe alternatives you've considered**
-

**Additional context**
Example apache config for MS Exchange - see Line 70: https://www.frankysweb.de/apache-als-reverse-proxy-fuer-exchange-server-teil-1/

**Comment by 0x646f6d** [comment]
Do you mind asking, if and when this feature would be implemented? I'd like to know, if I can wait for it or if I have to consider a different solution.

**Comment by AdSchellevis** [comment]
I’m likely going to implement it, but we’re currently busy preparing 24.7, if it can’t wait, I think we better scrap it off the list. A couple of months from idea to production is reasonable I’m afraid.

**Comment by 0x646f6d** [comment]
Alright, understood. Please don't scrap it from the list ;-) I think thats a valuable feature!

**Comment by AdSchellevis** [comment]
@0x646f6d if you drop us an email, I can offer you a test version.

**Comment by WAG-Adm** [comment]
Dear OPNsense-Team,
It could be a great idea to have the global "timeout" parameter for the BalancerMember. 
Our Backend needs something like that. https://httpd.apache.org/docs/2.4/mod/mod_proxy.html#proxyset
The "ConntectionTimeout" Parameter isn't working for us with an application server Wildfly.
It's quite useful when we're using Business Plugins for our Business App. By the way is it possible to restart only one proxy and not all at once? (typical business case too)
Regards,
Joel.

**Comment by AdSchellevis** [comment]
@WAG-Adm 

Hi Joel,

> It could be a great idea to have the global "timeout" parameter for the BalancerMember.
Our Backend needs something like that. https://httpd.apache.org/docs/2.4/mod/mod_proxy.html#proxyset
The "ConntectionTimeout" Parameter isn't working for us with an application server Wildfly.

Best open a ticket, not sure when we can find the time, but it might be possible to implement.

>By the way is it possible to restart only one proxy and not all at once? (typical business case too)

No, that's not possible, but shouldn't be needed either as applying settings uses a reload on apache.

Best regards,

Ad
