### ISSUE TITLE
Shadowsocks uses deprecated  pcre-8.45_4.

### ISSUE THREAD

**Issue by Zerophase** [opnsense/plugins#4001]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
When installing the Shadowsocks plugin I get notified about using the wrong version of pcre. pcre-8.45-4 gets installed instead of the recommended  devel/pcre2.

**To Reproduce**
1. Install Shadowsocks plugin through the gui. 

**Expected behavior**
I do not receive a warning about using the deprecated version of pcre. 

**Environment**
OPNsense 24.1.7_4 (amd64).

**Comment by mimugmail** [comment]
The upstream port of FreeBSD needs to be updated, maybe you can open an issue over there to get in touch with the maintainer?

**Comment by fichtner** [comment]
Not going to touch this. We could pivot to another dependency but not without maintainer ok and testing. All library related changes are FreeBSD ports territory.
