### ISSUE TITLE
net/upnp: upgrade miniupnpd to 2.3.6

### ISSUE THREAD

**Issue by Sjors** [opnsense/plugins#4003]
I think I'm running into the IPv6 renewal bug fixed in https://github.com/miniupnp/miniupnp/commit/7bd0877b8fd9a1c1c59cdf426b4640b3cee2bf61

When renewing an IPv6 pinhole I get `NO_RESOURCES`. Once the pinhole expires, it can be opened again, but this causes gaps in connectivity. Renewing IPv4 port mappings works fine.

According to the plugin documentation it's currently at miniupnpd 2.3.1. Hopefully simply bumping the miniupnpd version fixes this.

**Comment by Sjors** [comment]
Upon further reading, this particular bug fix is already in 2.3.3 and earlier versions.

Doesn't hurt to update to 2.3.5 so I'll just leave this open.

**Comment by fichtner** [comment]
BTW #3831 and #3747 are both open waiting for 3.2.6.

**Comment by fichtner** [comment]
For reference here is the test version of 2.3.6 after working through all the hoops...

    # opnsense-revert -r miniupnpd


Cheers,
Franco
