### ISSUE TITLE
ACMEClient does not populate ACME CA's in Accounts page

### ISSUE THREAD

**Issue by johnavich** [opnsense/plugins#4008]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [ x ] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [ x ] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [ x ] The title contains the plugin to which this issue belongs

**Describe the bug**
A new install of AcmeClient does not allow for creation of accounts on first view.
When attempting to setup a new account, I hit Add with default values, but no response is received from the backend api.
After fixing the PHP in /usr/local/opnsense/mvc/app/controllers/OPNsense/AcmeClient/Api/AccountsController.php, line 95, i was able to see all of the attempts i made to make a new account.

This is a brand new install of OPNSense, and no revert was possible.

**To Reproduce**
1. Go to Services -> ACME Client -> Accounts
2. Click on Add
3. View ACME CA's as blank
4. Fill out Name, Email and Description
5. Click Add.

**Expected behavior**
Expected behavior is for pop-in window to disappear, and new Account to populate the list.

**Actual Behavior**
The pop-in never disappears. A log entry in Firmware Reporter shows the following log entry:
`
[27-May-2024 18:26:56 America/Chicago] PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /usr/local/opnsense/mvc/app/controllers/OPNsense/AcmeClient/Api/AccountsController.php on line 95
`

**Relevant log files**
Please see above

**Additional context**
Changing ${uuid} to {$uuid} at the console resolved my issue with this bug.

**Environment**
OPNSense 24.1.7_4
acme.sh 3.0.7_1
os-acme-client 4.3

**Comment by fraenki** [comment]
> The pop-in never disappears.

I was unable to reproduce this, at least not on OPNsense 24.7.

However, I've prepared a fix for all PHP deprecation warnings, which will be available in the upcoming os-acme-client 4.5.

**Comment by Skammi** [comment]
Is this issue solved??
As I have the same Problem:
In the "Edit Account" popup, the Field named "ACME CA" shows: "Nothing selected" with a down arrow. Selecting the field does not populate the options, like "Lets Encrypt (default).
Typing in the short name from the arme.sh documentation displays "No result matched "letsencrypt".
The account can not be saved so I'm stucked.
