### ISSUE TITLE
os-zerotier: Add capability to edit <network-id>.local.conf

### ISSUE THREAD

**Issue by bl8rnr** [opnsense/plugins#4011]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
The current implementation of the os-zerotier plugin lacks important functionality in the client configuration namely, unable to manage the below options:

allowManaged=1 - Allow Managed. Default Yes. Allow ZeroTier to set IP Addresses and Routes (local/private ranges only)
allowGlobal=0 - Allow Global. Default No. Allow ZeroTier to set Global/Public/Not-Private range IPs and Routes.
allowDefault=0 - Allow Default. Default No. Allow ZeroTier to set the Default Route on the system.
allowDNS=0 - Allow DNS. Default No. Allow ZeroTier to set DNS servers.

**Describe the solution you'd like**
Option1 - Allow these options to be set in the gui when adding or editing a network.
Option2 - Allow the editing of the <network-id>.local.conf in the gui, the same way as the local.conf

**Describe alternatives you've considered**
Editing the file in cli works but changes are not persistent after a reboot.
Manually adding a gateway and routes in OPNsense works but that takes away from the automation build into Zerotier.

**Additional context**
I understand that adding a default gateway or DNS servers might have other complications but if the allowGlobal option could be added as a start it would be very helpful.

**Comment by divinehawk** [comment]
Please take a look at my pull request. Thank you
