### ISSUE TITLE
SSLH GUI Update

### ISSUE THREAD

**Issue by efaden** [opnsense/plugins#4013]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
Freshports is pulling the latest version of SSLH (2.1.2) in and it should be available soon.  That version adds some more configuration options, including UDP.  The interface doesn't currently support those.  

https://www.freshports.org/net/sslh/

**Describe the solution you'd like**
Upgrade the GUI to expose the new options and/or the ability to have a custom condition or edit the cfg directly.  The new version allows UDP, custom regex based filters, etc...  See the example config at
https://github.com/yrutschle/sslh/blob/master/test.cfg 
And 
https://github.com/yrutschle/sslh/blob/master/udp.cfg

For just UDP.

**Describe alternatives you've considered**
manually editing the config file in the terminal, but it's possible to accidentally override it.

**Additional context**

**Comment by fichtner** [comment]
Haven't seen the maintainer in a long time. You will have more luck contributing the changes yourself.

**Comment by efaden** [comment]
👍.
