### ISSUE TITLE
rebellion-theme: missing delete button

### ISSUE THREAD

**Issue by Gishan86** [opnsense/plugins#4014]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
When using the rebellion theme the delete button in various places is not shown.
i.e. reservations list in ui/kea/dhcp/v4

**To Reproduce**
1. Switch to rebellion theme (System -> General -> Theme)
2. Open something that shows a list with editable entries (example above)
3. Only button for Edit and Clone are shown
4. "..." has no function
5. on the right of "..." there is an invisible button (no icon) with only a tooltip "Delete"
6. Switch to standard theme opnsense and repeat -> the button/icon is visible

**Expected behavior**
Button should be visible

**Screenshots**
https://imgur.com/a/189vgfe

**Relevant log files**
-

**Additional context**
Tried tinkering with the html - editing the span's class from "fa fa-fw fa-trash-o" to "fa fa-trash-o" helped.
Don't know if that helps finding a solution.

**Environment**
OPNSense: 24.1.8
Rebellion: 1.8.10
Browser: Edge latest build as of today 125.0.2535.67 (64-Bit)

**Comment by nautilus7** [comment]
I have the same issue with opnsense 24.7.2 and rebellion 1.9.1.

![image](https://github.com/user-attachments/assets/4209d3f7-d996-46bf-8b05-fe6938747d19)
