### ISSUE TITLE
net/frr: enabling staticd doesn't enable staticd

### ISSUE THREAD

**Issue by fmeppo** [opnsense/plugins#4018]
Upgraded to OPNsense 24.1.8 this weekend; I was pleased to see support for STATIC has been merged!  Thanks.  The config options work fine and produce a `staticd.conf`, but enabling STATIC doesn't actually result in the daemon (`staticd`) getting started.  Turns out this is a typo in the template for `/etc/rc.conf.d/frr`; it looks for `staticd.enabled` rather than `static.enabled`.

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/plugins/pull/4019
