### ISSUE TITLE
NGINX - Non default behaviour - files within "root" directory and subfolders are served if no location is defined

### ISSUE THREAD

**Issue by belotv** [opnsense/plugins#4023]
**Describe the bug**
When defining an "HTTP Server" with no location, all files within the File System Root are made available

**To Reproduce**
1. Create a new "HTTP Server" and set "File System Root" to an existing folder containing a folder "img" with a picture called "test.jpg"
2. Enable NGINX
3. Connect to http://server:port/img/test.jpg

**Expected behavior**
Error page shall be displayed as access to this location was not explicitly authorized.

**Actual behavior**
The "test.jpg" is loaded.

**Additional context**
Nginx normally requires the try_files directive or autoindex of subdirectories to be enabled to serve static content in subfolders.

**Environment**
OPNsense 24.1.8 (amd64).

**Comment by fabianfrz** [comment]
Incorrect, that is exactly the desired behaviour. the root says that this should be used to lookup resources in that directory.

try_files is to say if it is not there, try something else so it is to provide an alternative to the default behaviour to just serve static files. this is usually used to speed up static file loading.

autoindex creates an index with a file listing if you try to open a directory without an index.html or simmilar file.

**Comment by fabianfrz** [comment]
since I cannot do that by myself, please close.
