### ISSUE TITLE
Support for Zabbix 7.0 LTS

### ISSUE THREAD

**Issue by dritier** [opnsense/plugins#4025]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X] The title contains the plugin to which this issue belongs

**Describe the bug**
_not a bug exactly_

**Expected behavior**
_Inclusion of a newer proxy and agent version 7.0, otherwise proxy config update is not possible if main server is already on 7.0_ 

**Additional context**
_Compatbility matrix -> https://www.zabbix.com/documentation/current/en/manual/appendix/compatibility_

**Comment by Park0** [comment]
https://www.freshports.org/net-mgmt/zabbix7-proxy
https://www.freshports.org/net-mgmt/zabbix7-agent

**Comment by burghy86** [comment]
Greetings. is there any news for the plugin for zabbix 7?

**Comment by fichtner** [comment]
Let's say it's progressing... https://github.com/opnsense/tools/pull/416

**Comment by pfender** [comment]
Hi,
Are there any updates on when the implementation for Zabbix 7.0 LTS can be expected?
Thank you!

**Comment by fichtner** [comment]
24.1.x for sure.

**Comment by burghy86** [comment]
> 24.1.x di sicuro.

i have OPNsense 24.1.9_4 but not see a plugin for zabbix 7. am I wrong?

**Comment by fichtner** [comment]
Don’t have a Time Machine. Maybe 24.1.10, but definitely before 24.7 because all the code has now been committed.

**Comment by burghy86** [comment]
i have update 24.1.10 and i have unistall zabbix proxy 6.4 and install zabbix proxy 7 plugin. services not starter: i have this log.

[Z3001] connection to database '/var/db/zabbix/zabbix7_proxy.db' failed: [2002] Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)

please help me.

**Comment by fichtner** [comment]
please reinstall the zabbix7-proxy package. It was not correctly built the first time.

**Comment by burghy86** [comment]
I just tried uninstalling 7 and reinstalling it but the problem remains. how did you build the first time?

**Comment by fichtner** [comment]
it depends on your mirror... just be a bit more patient...

**Comment by burghy86** [comment]
top. works perfectly. thank you

**Comment by fichtner** [comment]
Will be in 24.4.2 this month. Maybe next week, but it hasn't been agreed upon yet and 24.7 was binding a lot of time and resources so far.

**Comment by burghy86** [comment]
hello. i update opnsense to 24.7.1 and zabbix proxy to: 1.11
after reboot the proxy server start and stop with error:
![immagine](https://github.com/user-attachments/assets/738f74f1-1b7f-4607-802d-8a2a93686236)
I tried uninstalling and reinstalling the plugin without success
