### ISSUE TITLE
acme.sh: "[: !-f: unexpected operator" during upgrade from 3.0.6 to 3.0.6_1

### ISSUE THREAD

**Issue by cluck** [opnsense/plugins#4029]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**

The following message is shown during upgrade from 3.0.6 to 3.0.6_1
`[: !-f: unexpected operator`

**To Reproduce**
Upgrade acme.sh

**Expected behavior**

No scripting errors shown on console.

**Screenshots**

![2024-06-04_23h17_44](https://github.com/opnsense/plugins/assets/870386/f5049203-1c54-479a-85e0-23d0072e4239)

**Comment by fraenki** [comment]
Already fixed upstream:
https://github.com/FreeBSD/freebsd-ports/commit/678db807ed62622394f5ce17b7e492a300d10043
The broken script already takes care for the default log file, so this should not affect the functionality of os-acme-client.
