### ISSUE TITLE
Caddy: Allow Dynamic DNS to use a TTL shorter than `3600` (`1h`) for Caddy-managed DNS records

### ISSUE THREAD

**Issue by no-usernames-left** [opnsense/plugins#4037]
**Important notices**
- [X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
With a TTL of 3600, outages of almost an hour could occur between when the IP changes and the network reconverges when the TTL of the stale record times out.

Many DNS providers support TTLs as low as 300 seconds (and indeed this is the value I'd rather use); perhaps this should be the minimum value acceptable here.

**Describe the solution you'd like**
In `Caddy Web Server - General Settings`, change `DynDns TTL` to take a number of seconds instead of a number of hours (and label the input field with `seconds` for safety).

Also, add a migration from existing installs which multiplies that value by 3600 and re-saves the settings.

**Comment by Monviech** [comment]
I'll evaluate this. Sounds like a good idea to change it to seconds.

**Comment by Monviech** [comment]
You can test it by changing `h` to `s` here:

https://github.com/opnsense/plugins/blob/508864dd891a8f618fa3e8ec0a8db6627fdec08f/www/caddy/src/opnsense/service/templates/OPNsense/Caddy/Caddyfile#L339

File is here on the opnsense:

`/usr/local/opnsense/service/templates/OPNsense/Caddy/Caddyfile`

Please only change that one thing, don't copy the whole file in there.
