### ISSUE TITLE
security/acme-client: Update synology deploy hook to support SYNO_OTP_CODE for easier 2FA implementation

### ISSUE THREAD

**Issue by Podden** [opnsense/plugins#4045]
Newest "Upload certificate to Synology DSM" Script supports using the OTP Code directly instead of laboriously extracting Device ID and Name from cookies. Would be a nice addition.
https://github.com/acmesh-official/acme.sh/wiki/deployhooks

**Comment by fraenki** [comment]
Currently these changes are only available in acme.sh git repository. We'll need a new _release_ of acme.sh that includes these changes. Afterwards we'll continue here and may make the required changes to Acme Client.

**Comment by jacobgraf** [comment]
Has any progress been made on this? The Synology Deploy Hook is still broken and every time my certificate renews, I have to manually export from opnsense and import into Synology. I would love for the automation to work again! 😁

**Comment by jacobgraf** [comment]
@fraenki I did try as soon as 27.4.5 was released and still no luck. I only say it's broken because it worked fine using the old method of providing a device ID for a saved 2-factor device. Now it just won't work at all. I've tried everything I can think of. So for the last 4-6 months, I've been manually exporting my cert from OPNsense and importing it into Synology. I REALLY want to get the deploy hook fixed tho. Any ideas what I need to do in order to get it working again? I've tried setting the log level up to Debug 3, and don't see anything that stands out as the issue.

![errors](https://github.com/user-attachments/assets/a734bc7a-3f79-4739-b1c6-b3973d34fe40)

**Comment by fraenki** [comment]
>  Any ideas what I need to do in order to get it working again?

I don't know. You may want to [post your question on the forum](https://forum.opnsense.org/) or [report a bug](https://github.com/acmesh-official/acme.sh) to acme.sh.

**Comment by fraenki** [comment]
> @Podden I've read the [documentation for the Synology deploy hook](https://github.com/acmesh-official/acme.sh/wiki/deployhooks#20-deploy-the-certificate-to-synology-dsm)... could you please elaborate what should be changed in the Acme Client?

FWIW, a new "OTP Code" input field will be available for the Synology automation in version 4.7 of Acme Client.

**Comment by jacobgraf** [comment]
> > [@Podden](https://github.com/Podden) I've read the [documentation for the Synology deploy hook](https://github.com/acmesh-official/acme.sh/wiki/deployhooks#20-deploy-the-certificate-to-synology-dsm)... could you please elaborate what should be changed in the Acme Client?
> 
> FWIW, a new "OTP Code" input field will be available for the Synology automation in version 4.7 of Acme Client.

Looks like it just came out so thanks! One point of clarification, how does this work? It says enter "OTP Code", but I'm assuming this doesn't mean a current OTP Code, but instead the OTP passphrase used to generate the code? If the former, assuming as soon as I "save", it goes out and authenticates and automatically updates the Device ID?

In any case, it would be awesome to add a little more information in the help text as to what it's asking for and how it works.

**Comment by fraenki** [comment]
@jacobgraf I don't know, because I don't use Synology. You may want to check the documentation for the synology hook:
https://github.com/acmesh-official/acme.sh/wiki/deployhooks#20-deploy-the-certificate-to-synology-dsm
