### ISSUE TITLE
os-git-backup tries to delete master branch

### ISSUE THREAD

**Issue by marrobHD** [opnsense/plugins#4051]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new. (Previous Report is archived: https://forum.opnsense.org/index.php?topic=28163.msg136756#msg136756)
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
OPNsense Git Backups stopped working a month ago.
git-backup tries to remove the master branch, which is the default thus cannot be deleted.

**To Reproduce**
1. Go to 'System -> Configuration -> Backups'
2. Click on 'Setup/Test Git'
3. See error

**Expected behavior**
The plugin should not try to delete the branch.

**Relevant log files**
```
git-backup unknown error, check log for details (remote: remote: Gitea: branch master is the default branch and cannot be deleted To https://domain/TechHome/Opnsense-Backups.git ! [remote rejected] master (pre-receive hook declined) error: failed to push some refs to 'https://domain/TechHome/Opnsense-Backups.git' )
```

**Environment**
OPNsense 24.1.9_3 (amd64).

**Comment by bkeifer** [comment]
Also seeing this here, though the branch is 'main' for me.  Environment is `OPNsense 24.1.9_4-amd64`

`<171>1 2024-06-28T13:25:19-04:00 git.example.net config 37942 - [meta sequenceId="1"] git-backup unknown error, check log for details (error: unable to delete 'main': remote ref does not exist error: failed to push some refs to 'ssh://githost.lan:222/opnsense/config.git' )`

**Comment by marrobHD** [comment]
See: https://docs.opnsense.org/manual/git-backup.html#conflict-resolution

Quick fix: Rename the git branch with issues, Remove /conf/backup/git, Run Setup/Test Git again
