### ISSUE TITLE
 Enable automatic microcode updates

### ISSUE THREAD

**Issue by Zerophase** [opnsense/plugins#4075]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x ] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x ] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x ] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
We can manually update the cpu microcode our filewall uses based on this [guide](https://forum.opnsense.org/index.php?topic=36139.0). Updating that microcode might provide performance improvements and offer greater security. Currently, we have to take manual invention to enable this feature. Would be nice to have a plugin that just does this for the end user.

**Describe the solution you'd like**
I would like to be able to update microcode for AMD or Intel cpus without having to  manually intervene.

**Describe alternatives you've considered**
The alternative is just following the guide. I don't know if there's an advantage to having this feature natively supported by OPNSense vs doing it myself manually.

**Comment by fraenki** [comment]
I plan to create a tiny plugin for this.
