### ISSUE TITLE
net/relayd: SMTP monitor syntax error

### ISSUE THREAD

**Issue by shezzski** [opnsense/plugins#410]
## Background
I have a 3 day old installation of OPNsense 17.7.8-amd64. This installation was build ontop of a FreeBSD 11.0 VM via opnsense-bootstrap on Microsoft Azure.

## Problem
I have installed the relayd plugin "os-relayd version 1.1_1" and have noticed that when configuring a SMTP monitor on a Virtual Server relayd will not start.  

## Cause
This is due to a missing statement "Check"

###  OPNsense generated /var/etc/relayd.conf
```
log updates
timeout 1000
table <SMTP> {
        192.168.192.1
}
protocol "tcp" {
        tcp { nodelay, socket buffer 65536 }
}

relay "SMTP" {
  listen on 10.0.0.4 port 25
  protocol "tcp"
  forward to <SMTP> port 25  send  "" expect "220 *"
}
```

The error in /var/log/system.log is `/var/etc/relayd.conf:13: syntax error`

This is due to line 13, which is missing the statement "check", so the line should read

`forward to <SMTP> port 25  check send  "" expect "220 *"`

I am able to manually edit /var/etc/relayd.conf with vi, add the missing statement and start relayd with the command `relayd -f /var/etc/relayd.conf`

**Comment by fichtner** [comment]
Hi @shezzski,

Thanks, indeed, can you try:

    # opnsense-patch -c plugins cfda7cd


Cheers,
Franco

**Comment by shezzski** [comment]
Just tested and it works great.  Thanks @fichtner

**Comment by fichtner** [comment]
Thanks, I'll add this to 17.7.9 then :)
