### ISSUE TITLE
os-git-backup does not work with new repositories

### ISSUE THREAD

**Issue by meyergru** [opnsense/plugins#4105]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**

When you import a configuration from another machine that contains a Git Backup, the backup will not work.
In itself, this seems clear to me since /conf/backup/git does not contain an up-to-date version of the remote repo.

However, when you clear out the whole directory and set up another fresh repo on both OpnSense and Github, that will not work, either.
I have working backups that have been created a while ago, so this behaviour is new.

**To Reproduce**

1. Create a new repository on Github, like depicted in https://docs.opnsense.org/manual/git-backup.html
2. Click on Test/Setup
3. Error message:
```
The following input errors were detected:

    unknown error, check log for details
    Saved settings, but remote backup failed.
```

5. Log message:
```
2024-07-21T10:12:43 | Error | config | git-backup unknown error, check log for details (error: src refspec  master does not match any error: failed to push some refs to  'ssh://github.com/xxxx/yyyy' )
```

**Expected behavior**
Success message about pushed backup.

**Additional context**

I tried with and without an initialized repo (i.e. with a README.md and without) and also with default master branch set to "main" and "master". In case this matters (and I think it does): Github changed the behaviour to set the default branch name to "main" instead of "master" a while ago. This could probably cause problems. For example, I used "main" in my configuration, but the log message still refers to "master". I also used the full URL with ".git" and the abbreviated without it. All to no avail.

I have seen other problem reports (e.g. https://github.com/opnsense/plugins/issues/4051) where the behaviour was modified to first delete the master branch in case the repo is reinitialized, so maybe the main/master change on Github is the root cause?

**Environment**
Software version used and hardware type if relevant.
e.g.:

OPNsense 24.1.10_3 (amd64).

**Comment by fichtner** [comment]
Recent git bootstraps a ‚main‘ branch rather than ‚master‘ branch so I guess that’s why.

**Comment by meyergru** [comment]
I know. I tried every combination. I switched back to "master" on Github - no dice. And I used "main" in OpnSense config.
I think it has to do with hardcoded "master" deletion in OpnSense as that does not work either if the repo has not been initialized in the first place (although that did not work either). It is hard to track when you do not know the code / order of actions...

**Comment by AdSchellevis** [comment]
anything constructed via the gui in GitHub is likely not really "bare", if I'm not mistaken you can also just offer an non-existing branch and it will create a new one for you to circumvent these types of (upstream) issues.

**Comment by meyergru** [comment]
OK, let's get this straight: 

1. I create a **new** private repo on Github with no content and no init (i.e. no REAME.md) with organiation setting "main" as default branch - although there will be no branch without init.
2. I add a deploy key to the repo with write access.
3. I enter the ssh url (including ".git"), making sure that /conf/backup/git is empty, plus user git without password and the openssh key, set branch to "test" (which is neither main nor master), enable that and push "Setup/Test git".

And it does not work with the exact messages I gave above, including a reference to "master" where the was nothing of that sort in my configuration.

**Comment by AdSchellevis** [comment]
exactly why I asked to use a guaranteed non-existing branch in the backup config on OPNsense..... several tickets have been opened in the past about similar issues which all had the same cause (you can not push to a branch that needs to be pulled first), I think we even explained conflict resolution in the docs (https://docs.opnsense.org/manual/git-backup.html#conflict-resolution).

**Comment by meyergru** [comment]
Ad, sorry, are you actually reading what I write? Please try yourself to follow the steps I depicted above. The **new** Github repo is bare to the extent that Github allows for:

![grafik](https://github.com/user-attachments/assets/e8d71eef-fa57-41db-b039-77304973eb93)

Resulting in this:

![grafik](https://github.com/user-attachments/assets/fd3eadb6-8e4a-4f0d-9a2e-807e198ee038)

Then only added a deploy key:

![grafik](https://github.com/user-attachments/assets/f7a82170-eb3b-4dad-b699-8238e44ffdd8)

By using "test" as the branch name, it is guaranteed that it is a non-existing branch, even if main or master existed (which it does not):

![grafik](https://github.com/user-attachments/assets/cf531878-d477-4c37-bfba-b48c9a1c3f3e)

And I made sure that there were no conflicts by "rm -rf /conf/backup/git" altogether.

So what do you mean when you say "non-exiting branch"? I had my fair share of those and know what you mean, even if you restore a ZFS snapshot with "bectl", it will give you problems. However, this is a completely different situation:

1. Clean new Github repo
2. Clean local /conf/backup/git

While I concede that this problem most probably has been caused upstream by some Github changes, it still exists and the instructions to setup a Git backup given on the documentation pages do not work - unless I miss something completely obvious.

**Comment by meyergru** [comment]
On a side note: If the initial push needs to be pulled first, then maybe Github now really has a "bare" repository after creation. Matter-of-fact, when I look at the python scripts and try to call what the script would call after creating the local .git directory, I get this:

```
#git push origin master:test
error: src refspec master does not match any
error: failed to push some refs to 'ssh://github.com/meyergru/opnsense-kingnovy.git'
```

At that time, there are no local commits yet:

```
# git status
On branch master

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        identity
```

**Comment by meyergru** [comment]
Oh, well.... This: https://github.com/opnsense/plugins/issues/3050 brought me to delete /conf/event_config_changed.json and then retry. Guess what? That did the trick.

Also the same reports are here: https://github.com/opnsense/plugins/issues/2994, both of these seem to have been auto-closed after some time.

FWIW: There can obviously be situations where the timestamps in /conf/event_config_changed.json keep the initial backup from occuring. The "git status" on the local instance then shows "No commits yet", which maybe result from the config.xml never be copied over.

**Comment by AdSchellevis** [comment]
I'll try not to be offended (yes, I do read), but local time sync issues are also explained in the documentation https://docs.opnsense.org/manual/git-backup.html#cleanup

**Comment by meyergru** [comment]
Maybe you know too much about how this works and assume too much knowledge ;-)

I usually have quite a good understanding of what is going on, but that tip about the JSON deletion should be even more prominent. Until this time, it always sufficed to delete the git folder. IDK why/how the timestamps got bad (the machine usually has correct time as I also use 2FA).

Since these problematic situations can often arise with ZFS rollbacks, hardware migrations and now even with corrupt timestamps: Would it not be easier for casual users if there was a "reset" button for these?

Its function would be rather simple: remove both /conf/event_config_changed.json in order to make sure that config.xml gets re-created in the local repository and then issuing "git push origin .... --force", which effectively forces the local version to overwrite the remote repo.

After all, from a user perspective, this is just a config backup. As long as no problems arise, the side effect of a version history is nice, but if need be, most users will probably create a new repository get the backup working again, which is quite tedious.

The "reset" button could prominently carry a warning that the git history will be lost.

**Comment by AdSchellevis** [comment]
I don't mind adding a "trash all history" in `System: Configuration: History`, which also removes `event_config_changed.json`, but I doubt it would prevent the same discussion from happening to be honest. 

When this happens after a config import, there might be a more logical spot to remove this.

**Comment by AdSchellevis** [comment]
ok, let's flush by default on import https://github.com/opnsense/core/commit/8291ca38b5a60937d5550ea826d35b5527486a71

**Comment by Vertux** [comment]
@meyergru 
> Oh, well.... This: [#3050](https://github.com/opnsense/plugins/issues/3050) brought me to delete /conf/event_config_changed.json and then retry. Guess what? That did the trick.

I had the same issue with a fresh OPNSense installation, and my own Gitea service. The only difference was that I have used "https:" rather than "ssh:". After deleting the file `/conf/event_config_changed.json` everything worked. It's an annoying issue, especially because you don't get a helpful error message or log entry.

**Comment by AdSchellevis** [comment]
When this happens, the contents of `/conf/event_config_changed.json` and the timestamps (filenames) of the files in `/conf/backup/config-*.xml` are the relevant items to open a ticket in core... 

events are handled by https://github.com/opnsense/core/blob/master/src/opnsense/scripts/system/trigger_config_changed_events.py

**Comment by nbari** [comment]
Just in case I got this error:

    git-backup unknown error, check log for details (error: src refspec master does not match any error: failed to push some refs to 'ssh://github.com/<user>/<repo>.git' )

The fix for me was to remove the .git repo and just try again:

`rm -rf /conf/backup/git`

Then via gui try to the `Setup/Test Git` and worked out

**Comment by bernieke** [comment]
I spent an hour fighting this. In the end I just gave up and renamed my main branch to master, after which it all started working...
