### ISSUE TITLE
net-mgmt:snmp - process crashes with MibII enabled

### ISSUE THREAD

**Issue by shezzski** [opnsense/plugins#411]
I am running OPNsense 17.7.8-amd64 in a VM on VMware ESXi 6.0 and recently I have started having issues with bsnmpd crashing.  I have had some issues with this in the past where a reboot of OPNsense has resolved the issue, but this is not the case this time.

I have found that bsnmpd stops crashing when I disable MibII, but MibII is what I would like to use.

I am unsure where the logs are kept, but nothing appears to be written to `/var/log/system.log`

Any assistance to fault find this problem would be great and thanks in advance.

**Comment by mimugmail** [comment]
@fichtner this can be closed as old os-snmp is EoL
