### ISSUE TITLE
old wireguard plugin

### ISSUE THREAD

**Issue by burghy86** [opnsense/plugins#4111]
hello. i have upgrade opnsense without a problem but wireguard now is integrate in a core system.
in plugin i have a old version of os wireguard plugin.
how can remove this?
![immagine](https://github.com/user-attachments/assets/a7b859a7-9218-47a7-8101-2e9807fd250d)

**Comment by asychev** [comment]
https://github.com/opnsense/plugins/issues/3812#issuecomment-1940617594

**Comment by burghy86** [comment]
ok. thank you!
