### ISSUE TITLE
os-wol widget does not appear in 24.7

### ISSUE THREAD

**Issue by m3e-g** [opnsense/plugins#4114]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x ] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x ] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x ] The title contains the plugin to which this issue belongs

**Describe the bug**
After upgrade to the 24.7 WakeOnLan widget is not available anymore.

**To Reproduce**
1. Go to Dashboard
2. Click on "Add Widget"
3. Open available list
4. See that Wake On Lan is no longer available

**Expected behavior**
Widget is available for selection and operates in similar manner as in pre 24.7 versions.

I'm aware that MVC changed with the 24.7 release and widget requires a rewrite, but as I'm unfamiliar with the code I'm unable to contribute a fix. Hopefully someone else can help.

**Comment by phgarman** [comment]
+1 Also have this issue.

**Comment by potras18** [comment]
Same issue here

**Comment by Monviech** [comment]
@fichtner Should I look into this?

**Comment by fichtner** [comment]
Not yet. I don’t agree with the tickets conclusion of the expected outcome. WOL is practically an unmaintained community effort. With a dashboard replaced there are no immediate requirements of a widget replacement. The plugin is functional as is. Better than removed anyway.

**Comment by fichtner** [comment]
For the person with the thumb down: make sure to thank @m3e-g when you have the time
