### ISSUE TITLE
os-theme-rebellion - graphical glitch with "add widget"

### ISSUE THREAD

**Issue by ethanroy14** [opnsense/plugins#4122]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
with rebellion on, dropdown from "add widget" button in new dashboard shows up behind popup and cannot be navigated with mouse. problem does not happen on normal theme

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**
1. select "add widget" on dashboard
2. attempt to navigate the dropdown

**Expected behavior**
menu navigable with mouse, options visible

**Screenshots**
rebellion on:
![image_2024-07-27_140746466](https://github.com/user-attachments/assets/aa1ac0f3-fa72-4c4d-b7a0-1a4c944d3dcf)

rebellion off:
![image_2024-07-27_140850018](https://github.com/user-attachments/assets/04f59bf2-5695-4a66-988b-d4d4f98e2fb9)

**Relevant log files**
n/a

**Additional context**
menu is still navigable with tab/enter when in rebellion. 
all other functions in new update went off without a hitch and rebellion appears to be working well besides with this and with the widgets themselves.

**Environment**
OPNsense 24.7-amd64
Intel® Core i5-6500 @3.2 GHz

**Comment by xconverge** [comment]
This theme and these issues may be already fixed by the following commits? https://github.com/opnsense/plugins/commit/733cb0649d02966f6079a4f98c32dd966999118e and https://github.com/opnsense/plugins/commit/0269de844b79750738534a9a3b77c4e41a66e892

**Comment by fichtner** [comment]
Yes, landing in 24.7.1
