### ISSUE TITLE
Caddy will not start on new install 24.7_5

### ISSUE THREAD

**Issue by cnewman402** [opnsense/plugins#4124]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [ x] I have read the contributing guidelines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [ x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [ x] The title contains the plugin to which this issue belongs

**Describe the bug**
I have a new install on OPNsense 24.7 with a few other services installed. Caddy installs from the plugins page. When I go to configure the service in Services > Caddy Web Server > General Settings I get an error

"Error: setting up default log: opening log writer using &logging.NetWriter{Address:"unixgram//var/run/caddy/log.sock", DialTimeout:0, SoftStart:false, addr:caddy.NetworkAddress{Network:"unixgram", Host:"/var/run/caddy/log.sock", StartPort:0x0, EndPort:0x0}}: dial unixgram /var/run/caddy/log.sock: connect: no such file or directory"

No logs are created that I saw within Caddy. This is a new install. I have never used OPNsense before, so I am not sure of another working version. 

**Expected behavior**
Expected behavior was to start a reverse proxy service I can utilize. 

**Environment**
OPNsense 24.7_5-amd64
Dedicated HP Server R710 or something.
Smart Array Disk SAS RAID1

**Comment by Monviech** [comment]
Hmm that means it could not create or write to the file:
```
/var/run/caddy/log.sock
```

I see if I can reproduce it on a clean install.

**Comment by Monviech** [comment]
I did a totally clean 24.7 install, updated to 24.7_5, installed os-caddy.

I `Enabled` it, put my `ACME Email` in, pressed `Apply` and it started.

The unix socket for the logging was set up automatically with the right permissions.

```
srw-rw-rw-  1 root www 0 Jul 28 15:00 /var/run/caddy/log.sock
```

Maybe you had bad luck or something. Try a reboot?

If it still does not work, post the output of this command:
```
ls -la /var/run/caddy/
```

**Comment by cnewman402** [comment]
I thought it might be the drives, so I replaced them with SSD's. After a backup restore, I still had the same issue. I removed a list of plugins and that seemed to fix it. I had the following installed: 

- lldpd
- clamAV
- collectd
- iperf
- ntopng 
- redis

I think I will step into the plugins and and report back if I find anything.
