### ISSUE TITLE
www/caddy: configure dyndns to add/update IPv4 only for one subdomain?

### ISSUE THREAD

**Issue by jasonpstokes** [opnsense/plugins#4132]
**Important notices**
- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
Is there a way please to have Caddy only set an IPv4 dyn address for one subdomain, whilst setting IPv4+IPv6 for others? (As configured in the General Settings.)

I'm using a VPN client behind OPNsense that only supports IPv4, so my laptop only connects once I delete the AAAA record in Cloudflare... until it's automatically re-created.

**Describe the solution you'd like**
The option to select which IP version(s) to set records for, per subdomain. :)
(Or to know if this is possible through the config file -  as I realise this is likely a unique problem!)

**Describe alternatives you've considered**
Getting IKEv2 to work within OPNsense for native VPN, per the instructions! (But have failed so far)

Thanks for the plugin, works great.

**Comment by Monviech** [comment]
I'm sorry but that would add too much logic overhead.

Also, you will not be able to do that directly in the configuration file since the import statement in the global block of the Caddyfile is outside the scope of the dynamic DNS feature.

For more intricate configurations you should rather use a different plugin that handles dyndns.

**Comment by Monviech** [comment]
Thank you ^^
