### ISSUE TITLE
ftp proxy unexpected error since 24.7

### ISSUE THREAD

**Issue by Uglymotha** [opnsense/plugins#4153]
After upgrade to 24.7 ftp proxy displays an unexpected error after configuration (no error when proxy is not configured).
This is a PHP issue as seen in the PHP error log:
[05-Aug-2024 09:39:46 Europe/Amsterdam] Error: Typed property OPNsense\Mvc\Controller::$request must not be accessed before initialization in /usr/local/opnsense/mvc/app/controllers/OPNsense/FtpProxy/Api/ServiceController.php:44
Stack trace:
#0 /usr/local/opnsense/mvc/app/controllers/OPNsense/FtpProxy/Api/SettingsController.php(265): OPNsense\FtpProxy\Api\ServiceController->statusAction('4c80c81d-7bb7-4...')
#1 /usr/local/opnsense/mvc/app/library/OPNsense/Mvc/Dispatcher.php(165): OPNsense\FtpProxy\Api\SettingsController->searchProxyAction()
#2 /usr/local/opnsense/mvc/app/library/OPNsense/Mvc/Router.php(156): OPNsense\Mvc\Dispatcher->dispatch(Object(OPNsense\Mvc\Request), Object(OPNsense\Mvc\Response), Object(OPNsense\Mvc\Session))
#3 /usr/local/opnsense/mvc/app/library/OPNsense/Mvc/Router.php(139): OPNsense\Mvc\Router->performRequest(Object(OPNsense\Mvc\Dispatcher))
#4 /usr/local/opnsense/www/api.php(36): OPNsense\Mvc\Router->routeRequest('/api/ftpproxy/s...', Array)
#5 {main}

**Comment by Uglymotha** [comment]
This only affects configuration. FTP Proxy is running if it's configured correctly.

**Comment by fichtner** [comment]
Was https://github.com/opnsense/plugins/pull/4131 and is being shipped in 24.7.1.
