### ISSUE TITLE
Feature Request: Show protocol on IDS/IPS Alerts

### ISSUE THREAD

**Issue by tpcr** [opnsense/plugins#416]
The protocol is not shown in the Intrusion Detection Alerts tab list nor in the details.
This leads to some confusion when multiple triggers from the same IP occur.
Please add. Thanks

**Comment by AdSchellevis** [comment]
some changes in the alert log are already queued for delivery in the core package. 
![image](https://user-images.githubusercontent.com/9783985/33677370-ce7358de-dab8-11e7-82b6-d841d8e6b66b.png)

**Comment by tpcr** [comment]
The protocol is still not in the info you show
