### ISSUE TITLE
www/caddy: Add support for the propagation_timeout and propagation_delay tls options

### ISSUE THREAD

**Issue by Stitch10925** [opnsense/plugins#4161]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [v] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [v] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [v] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
Receiving a wildcard certificate only worked once. When the time came for a renewal I would always get propagation check errors. Research brought me to these parameters which fixed the problem.

**Describe the solution you'd like**
Adding those two parameters to my Caddyfile fixed a problem I was having retrieving wildcard certificates for my domain.

**Describe alternatives you've considered**
There are none

**Additional context**
The Caddy team added the parameters because many people had issues with retrieving wildcard certificates.

Caddy forum post: [caddytls: Add propagation_delay, support propagation_timeout -1](https://github.com/caddyserver/caddy/pull/4723)

Documentation around the tls module and propagation parameters are here: [tls docu](https://caddyserver.com/docs/caddyfile/directives/tls#issuers)

_**NOTE:**_ 

The current Caddyfile generated by the plugin creates levels: tls > dns
This will need to be changed to: tls > issuer acme > dns

The "issuer acme" level will need to be added for the propagation properties to be available. Structure is as follows:

`*.example.com {
    tls {
        issuer acme {
            dns provider {
                api_key xxxxxxx
                ...
            }
            propagation_delay 30s
            propagation_timeout -1
        }
    }
    ...
}
`

**Comment by Monviech** [comment]
Hey, do you want to try adding that? If not, I can do it, but it might take a while since Im busier now.

**Comment by Stitch10925** [comment]
Sadly enough I'm not capable to do this myself, otherwise I would have gladly helped. 

To me it's not that urgent. As long as I don't change my config now, the parameters will keep working.

**Comment by Monviech** [comment]
@Stitch10925 

Please test this patch with:

```
opnsense-patch -c plugins 64a3884
```

**Comment by Stitch10925** [comment]
@Monviech 
I found the flag and set it, then saved and applied. The properties are added correctly, the Caddyfile is valid, so I assume everything is ok. I cannot validate completely at the moment but I will be able to check the wildcard certificate retrieval soon.

Thanks for adding a patch for this issue so quickly, that was quite remarkable!
