### ISSUE TITLE
bug: multiple IDS blocks on the same packets

### ISSUE THREAD

**Issue by tpcr** [opnsense/plugins#417]
Using IDS and IPS, whenever a User defined GeoIP block triggers and another rule matches, they are both displayed in alerts. Shouldn't the first trigger end the rule search? Seems to happen only with the GeoIP rule and any other match. looks like a GeoIP rule match does not conclude the search
See 2 examples in these pics
![ips1](https://user-images.githubusercontent.com/22845650/33689581-48e5154c-da9d-11e7-91e0-b1d2684cdd53.jpg)
![ips2](https://user-images.githubusercontent.com/22845650/33689583-4950c062-da9d-11e7-9ffc-8235c8d9fca9.jpg)

**Comment by AdSchellevis** [comment]
Please open core issues in core next time (ids/ips is part of the core system), I'm not fully sure if a geo detect should be the end of the road, but the support status for geoip within suricata is Community (https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Support_Status).

You can always switch to geoip in firewall rules as an alternative.

**Comment by tpcr** [comment]
I am closing this and opening in core issue.
