### ISSUE TITLE
Caddy Access Lists does not support Opnsense Aliasses

### ISSUE THREAD

**Issue by robsiera** [opnsense/plugins#4174]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [ X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X ] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [ X] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
As a year long Pfsense user, I thought to try-out Opnsense once more. To my big surprise I noticed the Caddy plugin. Great, a UI on top of Caddy to facilitate Reverse Proxy entries!
But alas Alliases can't be used yet as shortcuts to IPaddresses in the Access Lists. That makes it impossible to add dynamic IPs to an access list.

**Describe the solution you'd like**
Allow to specify alliasses in the "Client IP Addresses" field.

**Comment by Monviech** [comment]
The default client_ip matcher can only use static IP addresses.

https://caddyserver.com/docs/modules/http.matchers.client_ip

The Aliases are used for features in the scope of the firewall, but not for plugins.

**Comment by robsiera** [comment]
Thanks for the swift reply.
Yes, I figured that would be the case, otherwise your would have problably used that possibility.
Still it seems to be valuable FR imho. But then again, I might be wrong.

**Comment by Monviech** [comment]
If you want to use dynamic IPs in these access lists, you can propose a working example in a Caddyfile and I can see if it can be implemented if it does not create too much overhead.

In the end, I want Caddy to handle all of these things inside its own binary with no external scripting involved.

**Comment by EarMaster** [comment]
As a suggestion: Wouldn't it be possible to recreate Caddy's configuration on an alias change?

**Comment by Monviech** [comment]
@EarMaster 

There are tools that can exist in the caddy binary itself but none of them are a core feature of caddy.

https://github.com/opnsense/plugins/issues/4533
