### ISSUE TITLE
security/acme-client: acme.sh version 2.7.5

### ISSUE THREAD

**Issue by fichtner** [opnsense/plugins#418]
According to the FreeBSD port strongswan.sh and fritzbox.sh are new as well.

Unfortunately, I have found no appropriate release notes: https://github.com/Neilpang/acme.sh/releases/tag/2.7.5

**Comment by fraenki** [comment]
Looks good to me, I didn't spot anything major, only fixes:
https://github.com/Neilpang/acme.sh/compare/2.7.4...2.7.5

@fichtner Please merge/import version 2.7.5. Thx!

**Comment by fichtner** [comment]
Will do, thanks!
