### ISSUE TITLE
NGINX - No Access & Error Logs in UI

### ISSUE THREAD

**Issue by BeNeDeLuX** [opnsense/plugins#4182]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
There is no entry for a Logfile in the UI. I'm not able to see the needed logs by day for access and error logs of nginx.

**To Reproduce**
1. Go to 'NGINX' under Services
2. Click on 'Logs/HTTP Access' or 'Logs/HTTP Error'
3. There is no entry for a vHOst to select a log file

**Expected behavior**
A list of logfiles per day to view in the UI as in 24.1.x versions

**Screenshots**
![scrnli_8_7_2024_9-02-49 PM (1)](https://github.com/user-attachments/assets/c3a9dcc1-ca40-43b9-9f7d-cba0ca6696ad)

**Additional context**
Forum discusion -> https://forum.opnsense.org/index.php?topic=42041.0

**Environment**
Software version used and hardware type if relevant.
e.g.:
- nginx 1.34

OPNsense 24.7.1 (amd64)
FreeBSD 14.1 p3

**Comment by kulikov-a** [comment]
Hi
https://github.com/opnsense/plugins/issues/4113

**Comment by BeNeDeLuX** [comment]
Duplicate https://github.com/opnsense/plugins/issues/4113
Thanks  @kulikov-a
