### ISSUE TITLE
NGINX 1.34 - Web Config incorrectly assumes client certificate authentication requires a CA certificate.

### ISSUE THREAD

**Issue by tunloop** [opnsense/plugins#4185]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**

The NGINX Web Configuration dialogs incorrectly assume that NGINX requires a Certificate Authority to use client certificate authentication/verification.

This is incorrect, NGINX does not care whether the client certificate is a self signed, only that it matches what cert is given in the config and to which depth the config says to verify to.

For example, on an NGINX config on a regular Debian server, I use a self signed certificate to identify myself for administrative access. The self signed certificate pem is on the web server and the config in the NGINX HTTP block is:
```
        ssl_client_certificate /etc/nginx/client_certs/admin.crt;
        ssl_verify_client on;
        ssl_verify_depth 1;
```
This allows NGINX to verify my self signed certificate without any CA's present. 

The configuration for OPNsense NGINX requires a CA certificate in the OPNsense System->Trust->Authorities but does not allow to choose a certificate from System->Trust->Certificates.
As I said above, NGINX is capable of using a self signed/leaf certificate instead of a CA for client authentication.

**Expected behavior**
OPNsense NGINX web configuration for the HTTP server should allow choosing a certificate from System->Trust->Certificates and specify to which depth NGINX should verify client transmitted certs as the raw NGINX configuration is already set up for.

**Environment**
OPNsense 24.7.1 (amd64).
os-nginx 1.34

**Comment by kulikov-a** [comment]
https://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_client_certificate
Specifies a file with trusted CA certificates in the PEM format..
so plugin correctly assumes that CA cert(s) is needed imo

>  but does not allow to choose a certificate from System->Trust->Certificates

because it's not a CA cert? ;)

**Comment by tunloop** [comment]
> https://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_client_certificate `Specifies a file with trusted CA certificates in the PEM format..` so plugin correctly assumes that CA cert(s) is needed imo
> 
> > but does not allow to choose a certificate from System->Trust->Certificates
> 
> because it's not a CA cert? ;)

Well yes, but actually no.

Technically a self signed certificate is a CA. For itself. The root of trust for a self signed certificate is itself.

I realize that NGINX may say that in its documentation, but functionally, it doesn't matter which cert in a chain you give it, because you can tell it what level to verify to.

But the issue here is that there is no way to have the NGINX plugin in OPNsense use a self signed certificate as the client authentication. Opnsense requires any CAs on the system to include the private key. I cannot create a CA cert in the OPNsense GUI without also including its private key, which is a security issue when using trying to authenticate a users self signed certificate because you should never give your private key to the server.

I could just ssh in and change the NGINX config manually, but at that point why would I even use this plugin. I seek to expand this plugins functionality.

But rather than attempting to get OPNsense to change the default required fields when importing a CA certificate in the base system, I figured it would make more sense to get the NGINX Plugin to also accept System->Trust->Certificates in the Client Certificate Authentication option.

**Comment by tunloop** [comment]
> > Technically a self signed certificate is a CA. For itself.
> 
> i don't agree. how about cA BasicConstraint then.

Thats a fair point. The designated use does take it into a different category. 
Every CA is a self signed cert, but not every self signed cert is a CA.

But that doesn't change the fact that NGINX doesn't care what the cert is supposed to be used for. It doesn't care what Basic Constraints or Key Usages extension you put on it. 

> 
> > Opnsense requires any CAs on the system to include the private key. I cannot create/import a CA cert in the OPNsense GUI without also including its private key, which is a security issue when using trying to authenticate a users self signed certificate because you should never give your private key to the server.
> 
> i dont agree again ;) Having a private key is not a requirement to add trust to the CA e.g.
> 
>     * create CA in OPNsense GUI
> 
>     * Issue your client cert
> 
>     * export CA and users certs keys
> 
>     * delete CA from first step (or try to remove priv key in gui)
> 
>     * import CA pub key in Trusted CA (if priv key removing does not worked somehow)
> 
>     * select this trusted CA in nginx config


OPNsense GUI *requires* the CA private key to import a CA.
I am not sure if you have actually tried to use the OPNsense GUI in System->Trust->Authorities and attempted importing a CA certificate. The process will NOT complete if you attempt to import a CA without a private key.
And even if I create the CA initially, then attempt to remove the Private Key, it will just pop back up if you edit the CA again.

I do realize that I could use a CA and sign my admin cert then use the CA to verify. That is certainly the more common scenario.
I have intentionally not done that. I have no use for a chain of trust for a single administrator in a small network. Its more steps and management overhead compared to generating a single leaf cert. Hence I use a self signed cert as my TLS client authentication.

Any scenario which would involve upload my private key for my self signed cert is absolutely unacceptable and not good security. 
NGINX by itself accepts just the certificate as the object to verify received client certs against. NGINX has no need for the private key.

NGINX on its own will take any PEM cert you give it for ssl_client_certificate. So it seems pretty reasonable to eliminate whatever blocker is in place for the plugin to allow any certificate in the OPNsense trust store to be used.

**Comment by kulikov-a** [comment]
> OPNsense GUI requires the CA private key to import a CA.

![image](https://github.com/user-attachments/assets/825740ba-94f2-403d-8036-0577166be759)
i really don't have USERTrust ECC CA priv key (check github site cert chain) ;)

**Comment by tunloop** [comment]
> > OPNsense GUI requires the CA private key to import a CA.
> 
>  i really don't have USERTrust ECC CA priv key (check github site cert chain) ;)

Not sure how you got it imported, I only get errors when attempting to import the cert only. Are you doing this all through the GUI?
![caimport](https://github.com/user-attachments/assets/c248f4f1-dc11-408b-8f9f-b58248f95914)

The "Please see log file" doesn't help when the entry is this vague:
```
2024-08-24T23:51:49-07:00	Error	config	[OPNsense\Trust\Cert:cert.a18b1484-afa6-4859-bad9-f01e5c24035e.caref] Please select a valid certificate from the list{66cad485a744e}
```

**Comment by kulikov-a** [comment]
> how you got it imported

just 'Import an existing certificate authority'. no magic
![image](https://github.com/user-attachments/assets/6db38a46-17f3-4e1f-9924-071f02fc9c7d)

i dont know if something fixed recently in Trusts. testing on 24.7.2

**Comment by tunloop** [comment]
> 
> my personal opinion (i am not the plugin maintainer, so feel free to ignore it) about the feature you requested: I have not tried it, but I believe that the scenario you described works, but it will be using an undocumented feature of nginx/OpenSSL. and in my opinion this should not be a declared feature of the plugin, because when and if it stops working without notice it will be fully consistent with the product documentation. if this use of the `ssl_client_certificate` directive seems to you the only correct one, then I think you can try not to unset the ssl_client_certificate directive in the GUI and use a hook to add the necessary directives (
> 
> https://github.com/opnsense/plugins/blob/ffe1badd2ced2bdf459cc6fabbae8a21cce7bbc0/www/nginx/src/opnsense/service/templates/OPNsense/Nginx/http.conf#L394
> )

I don't think its a hack or something that would ever disappear in the future from NGINX. Although the documentation you referenced did only specify CA certs, I believe that was just to show the most common use case. 

As evident by their own code comments, NGINX explicitly supports using self signed certs in client certificate authentication. 
```
# with verify depth 0, only self-signed certificates should
# be allowed
```
https://github.com/nginx/nginx-tests/blob/7a9e95fdd30729540ee9650be7f991c330367d5b/ssl_verify_depth.t#L145

I do realize that the depth 0 feature doesn't work fully (hence why I use depth 1), but my point here is that the maintainers clearly did not intend this feature to only work with Certificate Authorities. 

Also a few lines down in that same link:
```
# with verify depth 1 (the default), one signature is
# expected to be checked, so certificates directly signed
# by the root cert are allowed, but nothing more
```

So the only way me using depth 1 and a self signed cert could break EVER, is if CA certs in general suddenly weren't self signed which won't happen.

**Comment by kulikov-a** [comment]
checked with the priv key deleting. worked. seems like you have some issues on the Trusts side

**Comment by tunloop** [comment]
> > how you got it imported
> 
> just 'Import an existing certificate authority'. no magic ![image](https://private-user-images.githubusercontent.com/36099472/361191443-6db38a46-17f3-4e1f-9924-071f02fc9c7d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1Njk1NjEsIm5iZiI6MTcyNDU2OTI2MSwicGF0aCI6Ii8zNjA5OTQ3Mi8zNjExOTE0NDMtNmRiMzhhNDYtMTdmMy00ZTFmLTk5MjQtMDcxZjAyZmM5YzdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI1VDA3MDEwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjM2E1NDgxNTM3NWI0ZGU4Nzk1ZWUyMjcwZWFmMWQ3NDk1MWNhMjM3YzVhNTEwYThlNjc1OTAyNGNlZDY1MTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IkhC1PvP-rRvr9z7zU_ZfAiwT9YOT5EpySdLdjaPK0k)
> 
> i dont know if something fixed recently in Trusts. testing on 24.7.2

I have no idea whats wrong then, I would certainly like to have my client auth fixed.
I was on 24.7.1, and just upgraed to 24.7.2. I am getting the exact same error as I posted above.

**Comment by kulikov-a** [comment]
'Please select a valid certificate from the list' is coming not from priv key field but from caref field
https://github.com/opnsense/core/blob/0adece8d3e165acc0ba3bb2e1d8f0e6593dd8c41/src/opnsense/mvc/app/models/OPNsense/Trust/Cert.xml#L13
like you have some subordinate CA cert and the link to the root CA is broken or something like that..

nginx link point to some internal tests and there is root and subordinate CA creation in the pipeline. then there is a check that only first (root CA) cert should be OK with depth 0 verify. so i still dont think that adding self-signed client support in that manner is the right choice, sorry

**Comment by tunloop** [comment]
> 'Please select a valid certificate from the list' is coming not from priv key field but from caref field https://github.com/opnsense/core/blob/0adece8d3e165acc0ba3bb2e1d8f0e6593dd8c41/src/opnsense/mvc/app/models/OPNsense/Trust/Cert.xml#L13 like you have some subordinate CA cert and the link to the root CA is broken or something like that..
> 

The PEM I am putting in the cert field for import is a valid certificate. I just verified it with openssl.
```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            5e:b6:df:9c:db:76:bd:9b:e1:af:ff:53:33:1d:16:2b:6a:1e:2c:f3
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = US, ST =, O =, OU =, CN = admin
        Validity
            Not Before: Oct 10 15:31:35 2022 GMT
            Not After : Dec 27 15:31:35 2031 GMT
        Subject: C = US, ST =, O =, OU =, CN = admin
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (4096 bit)
                Modulus:
                    00:a7:65:8f:0c:58:49:5a:27:1e:14:80:8b:8c:26:
                    5c:14:fd:25:34:61:a0:ba:99:ac:e3:4c:21:69:99:
                    c5:8b:31:48:b2:59:3c:54:15:16:d6:db:a9:58:d8:
                    63:a3:07:97:0a:03:3b:ce:97:3b:1b:e7:fc:69:fa:
                    0c:a9:eb:2e:1a:f0:30:13:89:df:af:9b:0f:b7:44:
                    25:78:68:ef:6c:89:21:2e:17:32:2e:36:97:36:54:
                    ea:c5:fd:3f:0b:d1:9a:77:af:bf:21:fe:4c:13:30:
                    a4:55:6b:d8:71:a1:a5:40:75:65:b9:05:78:9b:73:
                    ba:66:64:26:25:94:51:89:b0:4c:20:46:0a:bc:37:
                    15:9e:f0:a0:b1:8f:7d:d6:5b:a6:a5:a8:75:3b:a3:
                    62:f7:08:48:ac:78:45:2c:f9:db:2f:11:88:ba:af:
                    f7:df:57:c1:49:c0:d7:69:dc:a2:0b:13:df:8e:b6:
                    de:07:20:ff:2e:67:1d:6c:f6:f0:7f:e3:2d:fd:95:
                    d3:01:b9:86:80:af:69:5f:22:1a:f5:90:de:31:99:
                    b2:6c:06:c0:c3:fa:c7:ae:74:3e:5b:8b:6c:77:88:
                    88:08:c4:3b:d6:68:d5:6a:49:d7:c7:01:c6:be:ff:
                    02:dc:f7:09:53:fc:76:a7:ff:90:e1:a9:e4:e5:75:
                    c4:83:a1:ca:0b:a7:0b:66:63:54:c0:d2:77:3c:fa:
                    63:87:86:f6:a3:97:22:cd:84:0a:5e:be:ef:79:ac:
                    42:21:3b:2f:6c:e8:94:73:ee:34:2f:68:c7:1d:1c:
                    4d:58:37:8c:d0:73:a5:3d:85:35:56:52:17:06:7d:
                    3e:02:f5:65:fc:3c:4b:a7:c7:4d:e4:f2:42:c4:f3:
                    84:60:fa:9f:4e:67:bd:db:4d:ca:ca:38:a4:b6:5a:
                    6b:71:ff:3a:1f:2d:d7:bf:7d:b8:c7:7a:71:73:c9:
                    74:54:77:f9:09:43:9c:7d:50:20:59:8b:02:64:0c:
                    96:7f:51:01:d9:22:c1:60:18:84:83:e7:ae:37:1b:
                    15:6e:14:77:67:47:45:26:fc:55:8d:b0:bd:d4:95:
                    9c:92:44:db:ef:48:40:c6:24:9d:9b:c1:a1:72:2d:
                    11:9e:a0:38:2f:d1:59:9a:7d:a8:3e:05:f7:ab:3c:
                    30:df:ce:55:9e:fe:55:12:8e:cc:d0:e1:37:7e:8d:
                    1f:ef:21:c8:3a:d1:fd:4f:e8:d7:e4:5d:5a:af:f3:
                    02:dc:b8:f2:79:2f:bf:9b:94:a4:c7:07:6c:2d:16:
                    05:c6:4a:d3:f5:69:a9:d7:6d:83:be:5a:66:ee:1b:
                    7d:78:01:5e:7a:18:62:33:0a:5e:12:e3:41:a2:b3:
                    b5:d7:4b
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Subject Key Identifier: 
                75:3E:A8:FE:8C:C2:62:A0:3E:46:D7:1C:4D:68:0E:AF:CD:DE:7E:28
            X509v3 Authority Key Identifier: 
                75:3E:A8:FE:8C:C2:62:A0:3E:46:D7:1C:4D:68:0E:AF:CD:DE:7E:28
            X509v3 Basic Constraints: critical
                CA:TRUE
    Signature Algorithm: sha256WithRSAEncryption
    Signature Value:
        71:db:81:fb:5a:f7:8e:61:3c:1f:c9:0e:1f:6d:85:c7:3d:0b:
        42:30:60:26:03:f3:30:63:72:3e:0c:4a:49:7f:54:d4:0c:7d:
        92:b8:c7:30:7f:bd:b4:0b:42:72:b2:1e:3b:c9:cb:e7:30:10:
        2d:bd:8c:8e:9f:08:76:ed:11:69:89:63:73:d1:f1:e6:62:da:
        16:e7:29:85:97:d9:52:da:71:cd:a5:08:7a:e7:30:ee:7f:b2:
        4d:69:9e:7e:f5:09:9e:af:cb:78:13:ac:bb:dd:e8:92:8c:bd:
        c9:1a:8c:5d:c8:01:9b:b1:fa:a7:27:04:4d:e2:15:1a:e2:b3:
        0a:12:20:07:91:83:f5:a9:3e:5f:37:f2:91:7d:ab:5f:ae:ec:
        8c:3e:9a:94:3d:ab:9f:78:43:1f:20:1a:03:61:3d:f5:89:72:
        09:41:1e:7d:10:f2:7a:0a:0b:73:b0:13:d1:b8:6b:34:98:59:
        42:48:34:41:69:2c:33:40:54:12:78:40:25:79:aa:2d:8c:e1:
        bd:f5:8f:5d:88:31:af:a2:41:42:5f:77:14:56:96:32:7e:2e:
        0b:55:73:42:47:d3:30:4e:8a:ec:bd:ce:7e:92:8f:02:b1:ec:
        75:55:64:57:26:b3:f5:f0:fa:2f:82:ae:96:f2:5f:90:94:41:
        a6:13:4a:21:bb:78:a7:6f:3b:a0:ca:10:79:05:9a:f4:30:e2:
        50:11:3d:c5:c7:cf:4f:72:ac:97:45:93:db:48:bd:3e:04:04:
        2e:84:32:c6:f1:f3:a7:a2:7a:d7:ea:96:b6:85:78:74:6e:8c:
        9e:54:e9:47:e0:93:52:d6:9d:18:66:1d:3b:f1:0f:48:10:d4:
        17:2d:0b:c3:33:98:c6:8b:e3:b4:c6:29:2b:66:d1:32:3e:5d:
        aa:7e:cf:4a:9f:a6:f7:1f:a2:16:2f:ca:38:57:b9:9f:41:f8:
        be:68:2d:66:21:c6:a4:cf:d0:d8:08:e0:ae:4a:35:20:81:9a:
        75:a3:44:c8:05:31:4e:c1:db:4f:d3:e3:68:b1:8f:21:d4:2f:
        c9:b1:a6:ec:41:fd:57:c9:cb:cc:c7:4c:67:ac:e8:7b:bb:71:
        77:1c:80:a1:00:fc:db:67:0e:50:26:44:cd:6a:9a:cc:b6:32:
        a6:43:02:78:29:f2:db:3d:0e:aa:bf:1b:ac:7c:cc:28:b3:e2:
        50:5b:a4:f7:a3:79:5f:23:d2:0e:bc:ea:bc:b4:21:9c:98:3e:
        dd:53:cf:e3:3a:2c:0e:85:ac:0f:7d:e7:b9:43:68:8a:53:d3:
        55:04:9d:51:96:3f:60:29:8d:b9:9f:1b:70:f0:5e:ae:e0:1c:
        5e:e2:b4:3c:53:4c:38:2b
```
Thats funny actually, I just noticed that my self signed admin cert is labeled as a CA. Ha.

I'll have to double check with some other certs, maybe my cert is unsupported by OPNsense in some way. I'll have to check tomorrow.

> nginx link point to some internal tests and there is root and subordinate CA creation in the pipeline. then there is a check that only first (root CA) cert should be OK with depth 0 verify. so i still dont think that adding self-signed client support in that manner is the right choice, sorry

All I am saying is that NGINX clearly intended self signed certs to be used with this client auth. 
And the functionality for verifying just a CA is identical to a regular self signed cert. 
So therefore, the use of client auth with a self signed cert is just as 'supported' as with a full CA cert. This is not opinion.

**Comment by kulikov-a** [comment]
>  I just noticed that my self signed admin cert is labeled as a CA

in this case you can definitely import this certificate as a trusted CA and use it in nginx (need to fix the broken Trusts part if you can't import certs in Trusts w/o priv keys)
![image](https://github.com/user-attachments/assets/1557fc7d-b4bc-4aa1-ae28-b69758139589)

**Comment by tunloop** [comment]
Found the issue. I am on KDE using Konsole and was using cat to get the PEM of my cert. 
Opening my cert in an actual GUI text editor (Kate) and copying from there allowed it to work. 
Probably some hidden characters messing up the import.
