### ISSUE TITLE
Caddy - Add the ability to create redirects

### ISSUE THREAD

**Issue by The-Istar** [opnsense/plugins#4221]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [ X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [ X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [ X] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
this feature request is requested here: [](https://www.reddit.com/r/opnsense/comments/1f6pa5b/caddy_plugin/)
There is currently no way to create redirects in the GUI, though it is a useful feature.

**Describe the solution you'd like**
(e.g. I would like an input field in the `/ui/firewall/alias` which would add .... to ....)
I would like to be able to create redirects in the GUI

**Describe alternatives you've considered**

**Additional context**
See here: [](https://www.reddit.com/r/opnsense/comments/1f6pa5b/caddy_plugin/)

**Comment by The-Istar** [comment]
Well, this comment seems to be unrelated to the issue. Also way to fast and sends a link to a suspicious file.

**Comment by Monviech** [comment]
Hey there,

could you fill out the template a little more?

What should be the scope of that feature? Free form like e.g., the HTTP Headers menu?

Or is the scope just these nextcloud redirections as of this reddit thread: https://www.reddit.com/r/opnsense/s/sIjv5Plx2p

Give an example of the redirects you need and the results you expect.

**Comment by The-Istar** [comment]
HTTP Headers menu seems fine. Basically it would be to integrate the redir directive, which is a simple enough command.
[](https://caddyserver.com/docs/caddyfile/directives/redir)

redir original_path new_path redirect_code

I suggest Original_path and New_path to be freeform and redirect_code to be a drop down?
That way it would work for all other situations that require a redirect as well.

Here is the example from the Nextcloud docs:

[](https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/reverse_proxy_configuration.html#caddy)
