### ISSUE TITLE
net/freeradius: newline missing in users file

### ISSUE THREAD

**Issue by mimugmail** [opnsense/plugins#423]
@fichtner @AdSchellevis I could need your help here:

https://github.com/mimugmail/plugins/blob/frlog/net/freeradius/src/opnsense/service/templates/OPNsense/Freeradius/users#L5-L8

If I add a user with Max-Daily-Session it looks like this (ok):

```
peter  Cleartext-Password := "chech", Max-Daily-Session := 1800
       Framed-Protocol = PPP

```

If I don't add a value for Max-Daily-Session it's missing the newline:

`test  Cleartext-Password := "test"       Framed-Protocol = PPP
`

I really have no idea why this is so and then FR doesn't like to start . :/

**Comment by fabianfrz** [comment]
jinja2 strips newlines if the line ends with a "endif", "endfor" etc.
You can fix this by adding an additional newline like I did in the proxy config for the ICAP stuff.

**Comment by mimugmail** [comment]
Args .. fool. 
Thanks Fabian 👍

**Comment by fabianfrz** [comment]
Glad I could help 👍
