### ISSUE TITLE
WOL ACL wont work

### ISSUE THREAD

**Issue by IDH-oliver** [opnsense/plugins#4230]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [ x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [ x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [ x] The title contains the plugin to which this issue belongs

**Describe the bug**
i tried to create a user with permissions ONLY to WOL Plugin and Widget. I added the user and added following privileges:
GUI | Dashboard (all)
GUI | Diagnostics: ARP Table
GUI | Services: Wake on LAN

Plugin Page works but Widget not. Which ACL need to be set, so the Widget can be used?

**Expected behavior**
working WoL widget

**Comment by fichtner** [comment]
For now you also need: Diagnostics: ARP Table


Cheers,
Franco

**Comment by IDH-oliver** [comment]
i added Diagnostics: ARP Table but it wont show the widget.

**Comment by fichtner** [comment]
It may have matching issues, I fixed the ACL definitions just today but haven't had the time to test it https://github.com/opnsense/plugins/commit/bae6b2bb9e6

**Comment by IDH-oliver** [comment]
sorry, didnt see you fixed it

**Comment by fichtner** [comment]
Did you try the fix? looking at it I think it's the missing "/api" prefix in the "/diagnostics/interface/getArp" entry.

**Comment by IDH-oliver** [comment]
yes, tried it. Works!

**Comment by fichtner** [comment]
perfect thanks. lucky timing :)
