### ISSUE TITLE
smart plugin for 24.7

### ISSUE THREAD

**Issue by pinysuse** [opnsense/plugins#4241]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**

`smart` [widget](https://forum.opnsense.org/index.php?PHPSESSID=qcthmf3s1edoasn0urh0mea1ea&topic=41581.msg204096#msg204096) needs to be rewritten

**Describe the solution you'd like**

...to be able to place the `smart` widget on the dashboard again...

**Describe alternatives you've considered**

`/usr/local/sbin/smartctl -a /dev/ada0` on the command line works.

**Additional context**

`smart` plugin was automatically (re-)installed during upgrade to 24.7

Feature request [hopefully welcome](https://forum.opnsense.org/index.php?PHPSESSID=qcthmf3s1edoasn0urh0mea1ea&topic=41581.msg204103#msg204103)

**Comment by fichtner** [comment]
It’s in the development version already but needs a bit more work.


Cheers,
Franco
