### ISSUE TITLE
enable underscores_in_headers

### ISSUE THREAD

**Issue by jesulo** [opnsense/plugins#4254]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [ ] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [ ] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [ ] The title contains the plugin to which this issue belongs

**Describe the bug**
How is it possible to enable underscores_in_headers? regards

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Relevant log files**
If applicable, information from log files supporting your claim.

**Additional context**

**Environment**
Software version used and hardware type if relevant.
e.g.:

OPNsense 23.7.8 (amd64).
Intel® Xeon™ E3-1225V5 3.3Ghz Quad Core
Network Intel® I210-AT

**Comment by AdSchellevis** [comment]
spam

**Comment by jesulo** [comment]
I don't understand what you mean by spam, in the end this thread helped me..
https://github.com/opnsense/plugins/issues/3423#issuecomment-2377945070
