### ISSUE TITLE
emulators/qemu-guest-agent: not working at 24.1 -> 24.7 upgrade

### ISSUE THREAD

**Issue by deimosian** [opnsense/plugins#4255]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

QEMU Guest Agent does not work after 24.1 -> 24.7 upgrade.

**To Reproduce**

1. Run OPNsense 24.1 in QEMU environment, eg Proxmox, with QEMU Agent installed.
2. Update from 24.1.x to 24.7.x.
3. Check hypervisor for QEMU Agent connection.

**Expected behavior**

QEMU Agent should remain installed and communicate with the host.

**Describe alternatives you considered**

N/A. There are no practical alternatives to having the proper agent.

**Comment by fraenki** [comment]
The plugin needs to move to the qemu port and activate the "guestagent" flavor:
https://github.com/freebsd/freebsd-ports/blob/main/emulators/qemu/Makefile
https://www.freshports.org/emulators/qemu-guest-agent/

I'll take care of this.

**Comment by jkellerer** [comment]
@fraenki , not sure if there is an additional problem, but I got it running again on 24.7 after adjusting the following CLI option:

https://github.com/opnsense/plugins/blob/f25a1fa6d54ef53339ab02685ecaf53a8fa5fcbb/emulators/qemu-guest-agent/src/opnsense/service/templates/OPNsense/QemuGuestAgent/rc.conf.d#L9

Changed to:

```rc.conf.d
{%     do optional_flags.append('--block-rpcs=' ~ OPNsense.QemuGuestAgent.general.DisabledRPCs) %}
```

Looks like `--blacklist` was renamed to `--block-rpcs`. See also: https://bugzilla.redhat.com/show_bug.cgi?id=2156515
