### ISSUE TITLE
net/haproxy warning "a 'http-request' rule placed after a 'use_backend' rule will still be processed before."

### ISSUE THREAD

**Issue by kumy** [opnsense/plugins#4274]
**Important notices**
- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**

Combined use of Rules `redirect_acme_challenges` (Added by ACME Client plugin) with a `http-request` rule trigger a validation warning
```
[WARNING] (64606) : config : parsing [/usr/local/etc/haproxy.conf.staging:67] : a 'http-request' rule placed after a 'use_backend' rule will still be processed before.
```

**To Reproduce**
1. Enable ACME plugin + haproxy integration
2. Create a `redirect_to_https` rule in haproxy (see screenshot below)
3. Create/update a public service and select both rules

**Expected behavior**
The validation should not trigger a warning

**Screenshots**
![image](https://github.com/user-attachments/assets/75566e1c-4ba1-4a6b-ab96-bf9ee679dbfb)
![image](https://github.com/user-attachments/assets/5aa72c14-c4ce-465e-871d-b61e811c153f)
![image](https://github.com/user-attachments/assets/7807fbf2-c194-4ce7-b8fd-be2921c04530)
![image](https://github.com/user-attachments/assets/422b8f79-4f10-4575-81cc-217076fdb923)

**Relevant log files**
That generates such config:
```
# Frontend: foo_HTTP (Public traffic HTTP)
frontend foo_HTTP
    bind 192.168.x.x:80 name 192.168.x.x:80 
    mode http
    option http-keep-alive

    # logging options
    # ACL: find_acme_challenge
    acl acl_66fc510bdc1e27.68520323 path_beg -i /.well-known/acme-challenge/

    # ACTION: redirect_acme_challenges
    use_backend acme_challenge_backend if acl_66fc510bdc1e27.68520323
    # ACTION: redirect_to_https
    http-request redirect scheme https unless acl_66fc510bdc1e27.68520323
    # ERROR FILE: general - Backend unavailable
    errorfile 503 /tmp/haproxy/errorfiles/66fc454820c0d4.66982534.txt
```

**Additional context**
Reversing the lines in the config prevent such warning

```diff
[/usr/local/etc]$ sudo haproxy -c -f /usr/local/etc/haproxy.conf
[NOTICE]   (92770) : haproxy version is 2.8.10-f28885f
[NOTICE]   (92770) : path to executable is /usr/local/sbin/haproxy
[WARNING]  (92770) : config : parsing [/usr/local/etc/haproxy.conf:67] : a 'http-request' rule placed after a 'use_backend' rule will still be processed before.
Warnings were found.
Configuration file is valid


[/usr/local/etc]$ sudo haproxy -c -f /usr/local/etc/haproxy-test.conf 
Configuration file is valid


[/usr/local/etc]$ diff -Nru /usr/local/etc/haproxy.conf /usr/local/etc/haproxy-test.conf
--- /usr/local/etc/haproxy.conf	2024-10-02 19:47:47.019719000 +0200
+++ /usr/local/etc/haproxy-test.conf	2024-10-02 19:46:11.604576000 +0200
@@ -61,10 +61,10 @@
     # ACL: find_acme_challenge
     acl acl_66fc510bdc1e27.68520323 path_beg -i /.well-known/acme-challenge/
 
-    # ACTION: redirect_acme_challenges
-    use_backend acme_challenge_backend if acl_66fc510bdc1e27.68520323
     # ACTION: redirect_to_https
     http-request redirect scheme https unless acl_66fc510bdc1e27.68520323
+    # ACTION: redirect_acme_challenges
+    use_backend acme_challenge_backend if acl_66fc510bdc1e27.68520323
     # ERROR FILE: general - Backend unavailable
     errorfile 503 /tmp/haproxy/errorfiles/66fc454820c0d4.66982534.txt
 
```

**Environment**

OPNsense 24.7.5_3-amd64
FreeBSD 14.1-RELEASE-p5
OpenSSL 3.0.15

**Comment by fraenki** [comment]
You may use drag'n'drop in the `Select Rules` input box to move and re-arrange the rules.

**Comment by kumy** [comment]
Before
![image](https://github.com/user-attachments/assets/3259f3ee-20e4-4085-a424-12aa7697c390)

After
![image](https://github.com/user-attachments/assets/698e0db5-7c88-4900-b7c9-c304d16fbefb)

Working
![image](https://github.com/user-attachments/assets/f1dbc4aa-cb90-4e49-823e-1d1b4afb2c68)

@fraenki Thanks! :bow:
