### ISSUE TITLE
[os-frr] Add multihop support to BFD web interface

### ISSUE THREAD

**Issue by KellenRenshaw** [opnsense/plugins#4282]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X ] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X ] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X ] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
I am running BGP on loopback addresses and would like to use BFD between the loopback addresses. This requires the "multihop" option on the peer directive in BFD. This was mentioned in #2050 but I don't think it made it into the merge.

**Describe the solution you'd like**
I would like a checkbox in the "Edit Neighbor" modal of the Neighbors tab at  /ui/quagga/bfd/index that says "Enable Multihop" or something to that effect.

This checkbox should cause the configuration for the peer to be written as:
peer X.X.X.X multihop
instead of:
peer X.X.X.X

**Describe alternatives you've considered**
I could manually edit the configuration to make it work, but exposing the option in the UI is cleaner and prevents accidental overwrites on save or reboot.

**Comment by AdSchellevis** [comment]
@KellenRenshaw https://github.com/opnsense/plugins/commit/4e7515edf28bc3b539b605feee24e6c0a2f97e26 should do the trick, but only for IPv4.

**Comment by KellenRenshaw** [comment]
Awesome! Thanks for taking a look!
