### ISSUE TITLE
net/haproxy: Better error reporting

### ISSUE THREAD

**Issue by StrikerTwo** [opnsense/plugins#429]
My HAProxy service on one OPNsense VM would not start after installing the latest upgrade.

The *only* way to see the cause for that was watching the console while booting and hoping I could read the messages scrolling by fast enough.
The problem was that an internal DNS server was not reachable and HAProxy could not resolve the hostname of a webserver. No error in the log files (that I could see with the OPNsense GUI), nothing. 

Clearly HAProxy logs the error somewhere if I can see it on the console, but they need to be visible in the GUI in order to be useful.

**Comment by fraenki** [comment]
@StrikerTwo These error messages are only available during service startup or when running a configtest. HAProxy does not log these errors, there's nothing I can do about it.

The GUI gives you the ability to run a configtest at any time to discover these errors quickly:

![testsyntax](https://user-images.githubusercontent.com/909706/33965857-baf2d5be-e05d-11e7-868a-e26a24622426.png)

In my test an unresolveable hostname was immediately spottet and a critical error was reported:

![haproxy_error](https://user-images.githubusercontent.com/909706/33965862-beabb64e-e05d-11e7-8c22-56d13be420a8.png)

Hope this helps.
