### ISSUE TITLE
web-proxy-sso: TODO list for public release

### ISSUE THREAD

**Issue by fichtner** [opnsense/plugins#43]
- ~~fix POST issue: {"errorMessage":"Error at /usr/local/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/BaseField.php:520 - array_key_exists() expects parameter 2 to be array, string given (errno=2)"}~~
- ~~copyright header style updates~~
- ~~change menu location~~
- ~~adjust squid.conf and rc.conf.d/squid~~
- ~~alt-auth hook to prevent local user authentication~~
- unwind auth server vs. squid authenticator
- protect exec() calls with exec_safe()
- GUI updates for actions
- testing during 16.7.x series
- Use a drop-down list for Domain Version
- ~~/etc/rc.conf.d/ssoproxyad is not sourced because the service is "squid" <-- need an /etc/rc.conf.d/squid DIRECTORY instead~~

Currently required patching for 16.7.7:

```
# opnsense-patch -c plugins 57cfcddf 916d315
```

**Comment by fichtner** [comment]
<img width="1093" alt="screen shot 2016-10-22 at 11 37 26 am" src="https://cloud.githubusercontent.com/assets/1915288/19618494/fb7825a4-984b-11e6-8ca7-9982595abae6.png">

**Comment by fichtner** [comment]
@gitdevmod problem with API POST turned out to be a typo: UpdateOnly -> UpdateOnlyTextField

**Comment by gitdevmod** [comment]
- adjust squid.conf and rc.conf.d/squid [example](https://github.com/gitdevmod/core/commit/c4c9c42f0d3ba969f42ab5cee30183af3dcdf9d9)

**Comment by fichtner** [comment]
@AdSchellevis the SSO plugin is quite light in terms of dependencies, and it requires a squid.conf base hook... it looks better to bring it into core.git itself. what do you think?

@gitdevmod At the moment, I don't know where the menu item should live (except in a native proxy server tab) and how it is going to be modelled: do we need a SSO configuration per user or is the "general" form the only form we need to use?

**Comment by gitdevmod** [comment]
@fichtner it's a general configuration, add a new server authentication, configure the plugin (AD information) and the server authentication in proxy configuration page.

**Comment by AdSchellevis** [comment]
@fichtner oops, was working may way through my email from top to bottom, so posted my comments here https://github.com/opnsense/core/pull/1235 

I'm not overly enthusiastic for integrating it into core, mainly because of timing and current workload. If it's in core it automatically means we have to support the feature. I do see the logic of having it integrated, but when pluggable its easier to manage.

**Comment by fichtner** [comment]
@gitdevmod squid.conf and rc.conf.d changes in via plugin.. almost done :)

**Comment by gitdevmod** [comment]
👍

**Comment by gitdevmod** [comment]
Thanks!

**Comment by gitdevmod** [comment]
Code for kerberos is added correctly but Local User Authentication helper config should not be added at the same time

`# Authentication Settings`
`# Configure Local User Authentication helper`
`auth_param basic program /usr/local/etc/inc/squid.auth-user.php`
`auth_param basic realm OPNsense proxy authentication`
`auth_param basic credentialsttl 2 hours`
`auth_param basic children 5`
`# ACL - Local Authorized Users - local_auth`
`acl local_auth proxy_auth REQUIRED`

`auth_param negotiate program "/usr/local/libexec/squid/negotiate_kerberos_auth"`
`auth_param negotiate children 10`
`auth_param negotiate keep_alive on`

**Comment by fichtner** [comment]
@gitdevmod ok, this is tricky to plug in, we may need an "alt-auth" file for this then

**Comment by fichtner** [comment]
@gitdevmod should be in there, I think we are ready for a first try :)

**Comment by fichtner** [comment]
@gitdevmod fix tested in core and plugins for /etc/rc.conf.d/squid subdir -- cannot commit ATM, but will be there soon

**Comment by gitdevmod** [comment]
Use a drop-down list for Domain Version. Last time I tried it did not work.

**Comment by fichtner** [comment]
@gitdevmod the authentication work on core.git moves to 16.7.8. I don't think we'll be ready for the first release of SSO just then, but 16.7.9 could be the one. :)

**Comment by fichtner** [comment]
I tried the option drop-down, but I didn't render properly as you said. Just keeping this for reference.

**Comment by adrianobragas** [comment]
Hi guys, how install this plugin web-proxy-sso in my opnsense 17.1.4-amd64?

**Comment by fabianfrz** [comment]
@adrianobragas You should be able to install it via `pkg install os-web-proxy-sso-devel` (afaik there is no stable release).

**Comment by fichtner** [comment]
Hi Adriano,

Update to 17.1.4 from the firmware pages, then log into the console or ssh and type:

    # pkg install os-web-proxy-sso-devel

The package is then available from the menu, but keep in mind it has not been finished for release.


Cheers,
Franco

**Comment by fichtner** [comment]
We are going to replace the old SSO plugin with https://github.com/opnsense/plugins/pull/266 soon
