### ISSUE TITLE
net/quagga: phase out string

### ISSUE THREAD

**Issue by fabianfrz** [opnsense/plugins#430]
As the quagga plugin is currently phased out, we should make this visible to users.

@fichtner suggested to write this into the comment.

Maybe: "Plugin EOL - please switch to frr"

The string can be discussed here.

**Comment by fichtner** [comment]
@fabianfrz @mimugmail how about https://github.com/opnsense/plugins/commit/e5451f62cd ?

**Comment by fabianfrz** [comment]
@fichtner looks ok.
