### ISSUE TITLE
Feature request: lldpd

### ISSUE THREAD

**Issue by djzort** [opnsense/plugins#431]
lldpd is a daemon which speaks lldp, cdp and a handful of other layer 2 protocols for neighbor discovery.

the port already exists in freebsd https://www.freshports.org/net-mgmt/lldpd/

There isnt all that much to configure as per http://vincentbernat.github.io/lldpd/usage.html

pretty much just protocol(s) selection, local system details ad interface(s) selection

the daemon is then interrogated via the socket or wrapping the lldpctl command

**Comment by fichtner** [comment]
The package has been available for a while:

# pkg install lldpd

We only need someone to start the plugin work :)

**Comment by mimugmail** [comment]
LLDP is fairly easy and a perfect candidate for a howto write own plugins by example. Let me finish Nut this week, then Freeradius LDAP and then I'll start.

**Comment by mimugmail** [comment]
@djzort with the next release there will be a devel pkg to test. Code is now in master.

**Comment by fabianfrz** [comment]
@mimugmail if you want us to close that, tell us.

**Comment by fabianfrz** [comment]
plugin exists
