### ISSUE TITLE
security/acme-client: dns validation using ispconfig3.1 api does not work

### ISSUE THREAD

**Issue by pcmediapear** [opnsense/plugins#434]
hello dear support

dns validation using ispconfig3.1 api does not work
tested on multiple ispconfig versions inlcuding latest 3.1.9 and also multiple opnsense versions including 17.7.9_9-amd64
it is really strange because txt record is created but validation ends with error

output from log:
----------------------------------------------------------------------------------------------------
[Sat Dec 16 17:43:46 CET 2017] Result of _ISPC_addTxt: '{"code":"ok","message":"","response":"161"}'
[Sat Dec 16 17:43:46 CET 2017] Record ID: '161'
[Sat Dec 16 17:43:46 CET 2017] Added ACME Challenge TXT record to zone.
[Sat Dec 16 17:43:46 CET 2017] Error add txt for domain:_acme-challenge.FQDN
[Sat Dec 16 17:43:46 CET 2017] pid
[Sat Dec 16 17:43:46 CET 2017] No need to restore nginx, skip.
[Sat Dec 16 17:43:46 CET 2017] _clearupdns
[Sat Dec 16 17:43:46 CET 2017] skip dns.
[Sat Dec 16 17:43:46 CET 2017] _on_issue_err
----------------------------------------------------------------------------------------------------

**Comment by fraenki** [comment]
Hi @pcmediapear, thanks for your report! The log looks a bit weird:

> [Sat Dec 16 17:43:46 CET 2017] Added ACME Challenge TXT record to zone.
> [Sat Dec 16 17:43:46 CET 2017] Error add txt for domain:_acme-challenge.FQDN

The TXT record is added, but acme.sh thinks there is an error. I have no idea why this happens.

We'll update acme.sh to 2.7.5 soon (#418), let's see if this fixes the issue for you. Please watch the OPNsense release announcements and report back here once acme.se 2.7.5 is available in OPNsense.

**Comment by fraenki** [comment]
One more suggestion: change the log level to "debug".

- Services -> Let's Encrypt -> Settings
- enable "advanced mode" to see hidden settings
- change "Log Level" to "debug"

Retry dns validation, maybe this time there's some useful information in acme.sh's log file.

**Comment by pcmediapear** [comment]
hi @fraenki

thanks for looking on this issue...

after changing log level to debug i am getting this error:

[Fri Jan 12 22:43:04 CET 2018] 	Diagnosis versions:
[Fri Jan 12 22:43:04 CET 2018] 	socat doesn't exists.
[Fri Jan 12 22:43:04 CET 2018] 	code='202'

but by playing around i found something what looks interesting:

by creating txt record in ispconfig manually there are 3 actions
Create DNS record: 1
Update DNS record: 1
Update DNS zone: 1

but if txt record is added from opnsense acme client there is only one action and other two are missing
Create DNS record: 1

i hope this will help you in some way

**Comment by pcmediapear** [comment]
hi @fraenki

after updating to latest opnsense which includes acme-client plugin v1.13 is behavior same

regards

**Comment by pcmediapear** [comment]
hi @fraenki

FYI: with opnsense 18.1.2_2 and ispconfig 3.1.11 still does not work

**Comment by fraenki** [comment]
@pcmediapear Thanks for keeping us updated! I've checked again both acme.sh as well as our plugin code, but I couldn't find any obvious issue. _Maybe_ your issue is related to [this bug report](https://github.com/Neilpang/acme.sh/issues/1198).

Two more ideas:
- Is the option "Disable SSL Verification" checked?
- Did you check the ISPconfig logs when acme.sh adds the TXT records?

**Comment by fraenki** [comment]
TBH there's nothing else I can do about this right now, so I'm closing this ticket. If someone else is able to provide further information, please comment and I'll gladly reopen this ticket.

**Comment by pcmediapear** [comment]
should be fixed in ispconfig...
https://git.ispconfig.org/ispconfig/ispconfig3/issues/5031#note_63976
