### ISSUE TITLE
os-telegraf ping broken 

### ISSUE THREAD

**Issue by Galaxy102** [opnsense/plugins#4349]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

This issue is a follow-up on #4317.

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
After Upgrading OPNSense to 24.7.7 I am no longer able to perform ping monitoring with telegraf.

**To Reproduce**
1. Configure os-telegraf to ping some IP adresses
2. See Telegraf log

**Expected behavior**

Telegraf pings the IP addresses and sends the monitoring results to a metric server.

**Screenshots**
![image](https://github.com/user-attachments/assets/93a30f6a-3d18-4413-9401-e639506b8ad6)

**Relevant log files**

See screenshots

**Additional context**

I am quite sure this bug was introduced via https://github.com/opnsense/plugins/pull/4316.
I added my problem (among other individuals) to the corresponding issue #4317 that seems to stay closed.

After reading some documentation, you would normally add the required capability, but in this security sensitive context it seems a bit odd. I'd consider switching back to "exec" ping mode.

**Environment**
Software version used and hardware type if relevant.

OPNsense 24.7.7-amd64
Hetzner Cloud VM (AMD)

**Comment by myadoran** [comment]
Thanks for the bug report Galaxy. I'm encountering the same behavior here.

For now I've mitigated the issue by manually changing the config in `/usr/local/etc/telegraf.conf` from 'native' to 'exec'. That's not ideal behavior though, as there's configuration drift to keep in mind on top of the XML config file.

I do understand based on the issue you linked why this was necessary but it seems there are two use cases that clash. Would it be possible to add a selector between native and exec in the web UI?

Of course, it seems like there's something below this problem, as native should be able to work as well through some permission magic. In that case this would be solved as well. If there's anything further to test, just let me know.

**Comment by fichtner** [comment]
Let's revert the change then since no consensus or alternative PR was offered. CC @alexwbaule


Cheers,
Franco

**Comment by fichtner** [comment]
The revert will be in 24.7.9. For everyone else it's trivial to reinstall an older version:

    # opnsense-revert -r 24.7.7 os-telegraf


Cheers,
Franco

**Comment by Galaxy102** [comment]
Thank you very much. Can this issue be closed?

**Comment by fichtner** [comment]
If you want yes.

**Comment by alexwbaule** [comment]
Yeap, thats it.

![Captura de tela de 2024-11-15 16-24-22](https://github.com/user-attachments/assets/3e2f8007-ec4d-4ac2-8652-12518a3201b0)

**Comment by fichtner** [comment]
If that's the case that could be a workaround to make the selection hinge on the root parameter, but it also means this code obscures what's happening and it may break again later. I have no idea what telegraf_pfifgw.php wants to do :)

**Comment by alexwbaule** [comment]
i will do a PR using the "/sbin/ping" but with the correct parameters, in the #4317 there is a explanation about the "count" parameter, that belongs to the native ping...

**Comment by alexwbaule** [comment]
> If that's the case that could be a workaround to make the selection hinge on the root parameter, but it also means this code obscures what's happening and it may break again later. I have no idea what telegraf_pfifgw.php wants to do :)

this PHP is another config that i do, don´t  related to this error, you can safely ignore it.

**Comment by alexwbaule** [comment]
@fichtner , PR done.

https://github.com/opnsense/plugins/pull/4359

**Comment by alexwbaule** [comment]
@Galaxy102  and @myadoran 

Please, can you help to test the #4359  PR ?

**Comment by myadoran** [comment]
@alexwbaule I tested the logic over here, no errors! I don't have consistent IPv6 connectivity though, so I can't test the split response (some ipv4, some ipv6 pings). I really don't see how that could still happen with them explicitly defined now though, awesome stuff.

**Comment by alexwbaule** [comment]
hi @myadoran , to test ipv6 i ping google.com and digitalocean.com (on my tests).
