### ISSUE TITLE
net/freeradius: feature request LDAP authentication

### ISSUE THREAD

**Issue by pcmediapear** [opnsense/plugins#435]
would be possible to think about to integrate to gui of freeradius ldap authentication?
for example in same way as it is for openvpn...

regards

**Comment by mimugmail** [comment]
Yeah, planned for January :)

**Comment by pcmediapear** [comment]
perfect... ;-)

**Comment by mimugmail** [comment]
@pcmediapear today I merged the last part with search filters. Tested against AD and Open LDAP, looks good. Will be im 18.1

**Comment by mimugmail** [comment]
@fichtner this one can be closed, I tested it some weeks ago with EAP-RADIUS for IKEv2 via local FreeRadius via LDAP to Windows AD :)

**Comment by fichtner** [comment]
splendid, thanks!
