### ISSUE TITLE
www/caddy [Feature request]: Ability to bind to selected ip addresses

### ISSUE THREAD

**Issue by QBANIN** [opnsense/plugins#4355]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [V] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [V] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [V] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
I have multi-wan/multi-IP setup but I need caddy to listen only on one or two selected IP address.

**Describe the solution you'd like**
Could be something similar to haproxy implementation.

**Describe alternatives you've considered**
Moving back to HAproxy :)

**Additional context**
![obraz](https://github.com/user-attachments/assets/45932f1e-438c-45d2-a2fe-ffe2a07f1cc5)

**Comment by Monviech** [comment]
The current GUI implementation of the os-caddy plugin does not fit your specific use case.

It can be configured as custom configuration file but I do not actively support it. When it breaks it will not be a priority to fix it.

https://docs.opnsense.org/manual/how-tos/caddy.html#bind-caddy-to-interfaces
