### ISSUE TITLE
os-nginx 1.34_2 cannot edit any config - unexpected error

### ISSUE THREAD

**Issue by AlmightyJojo** [opnsense/plugins#4358]
**Describe the bug**
Trying to edit any object in os-nginx 1.34_2 plugin results in unexpected error.
Example:  Edit http server, change no setting, and attempt save - unexpected  error.
My hunch is it is a permission issue as nothing can be written to but existing config running fine.
Nothing in logs however about reason for error or any permission denied.

**To Reproduce**
1. Go to 'http server'
2. Click on 'edit http server'
3. Scroll down to 'save button'
4. Unexpected error, no change can be made.

**Expected behavior**
os-nginx configuration to be editable and allow changes.

**Environment**
Poweredge R730xd , VMware7u3
OPNsense 24.7.8-amd64  VM, HA / CARP enabled
os-nginx 1.34_2

**Comment by AlmightyJojo** [comment]
Its using the template.  WTF...
Per usual incompetent AI bots wasting time.

**Comment by fichtner** [comment]
Maybe next time try not to waste _your_ time and go straight for the fix? #4342

**Comment by AlmightyJojo** [comment]
> Maybe next time try not to waste _your_ time and go straight for the fix? #4342

Yes forgot to mention - A member on opnsense forum shared this patch with me yesterday.
Unfortunately did not resolve.  So I reverted it.

Tried it again just now, re-applied config + nginx service restart.  Still cannot edit any config.

Results of patch install

`root@fw:/ # opnsense-patch -c plugins 1e23572
Found local copy of 1e23572, skipping fetch.
Hmm...  Looks like a unified diff to me...
The text leading up to this was:
--------------------------
|From 1e2357205385d63f0ec2ac286836aa914a771aa9 Mon Sep 17 00:00:00 2001
|From: Franco Fichtner <franco@opnsense.org>
|Date: Sat, 9 Nov 2024 12:44:44 +0100
|Subject: [PATCH] www/nginx: fix isEmpty() use #4342
|
|---
| www/nginx/Makefile                                       | 2 +-
| .../Base/Constraints/NgxBusyBufferConstraint.php         | 9 +++++----
| .../Constraints/NgxUniqueDefaultServerConstraint.php     | 4 ++--
| 3 files changed, 8 insertions(+), 7 deletions(-)
|
|diff --git a/www/nginx/src/opnsense/mvc/app/models/OPNsense/Base/Constraints/NgxBusyBufferConstraint.php b/www/nginx/src/opnsense/mvc/app/models/OPNsense/Base/Constraints/NgxBusyBufferConstraint.php
|index 409dfa6f22..83491dbff2 100644
|--- a/www/nginx/src/opnsense/mvc/app/models/OPNsense/Base/Constraints/NgxBusyBufferConstraint.php
|+++ b/www/nginx/src/opnsense/mvc/app/models/OPNsense/Base/Constraints/NgxBusyBufferConstraint.php
--------------------------
Patching file opnsense/mvc/app/models/OPNsense/Base/Constraints/NgxBusyBufferConstraint.php using Plan A...
Hunk #1 succeeded at 43.
Hmm...  The next patch looks like a unified diff to me...
The text leading up to this was:
--------------------------
|diff --git a/www/nginx/src/opnsense/mvc/app/models/OPNsense/Base/Constraints/NgxUniqueDefaultServerConstraint.php b/www/nginx/src/opnsense/mvc/app/models/OPNsense/Base/Constraints/NgxUniqueDefaultServerConstraint.php
|index 433d2b1015..4393425f4f 100644
|--- a/www/nginx/src/opnsense/mvc/app/models/OPNsense/Base/Constraints/NgxUniqueDefaultServerConstraint.php
|+++ b/www/nginx/src/opnsense/mvc/app/models/OPNsense/Base/Constraints/NgxUniqueDefaultServerConstraint.php
--------------------------
Patching file opnsense/mvc/app/models/OPNsense/Base/Constraints/NgxUniqueDefaultServerConstraint.php using Plan A...
Hunk #1 succeeded at 45.
Hunk #2 succeeded at 58.
done
All patches have been applied successfully.  Have a nice day.`
