### ISSUE TITLE
[packet capture] Unable to download capture, error: Unexpected error ...

### ISSUE THREAD

**Issue by doreks** [opnsense/plugins#4361]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [ x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [ x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [ x] The title contains the plugin to which this issue belongs

**Describe the bug**

after doing interface capture via packet capture option in --> interfaces --> diagnostic --> packet capture, I try to do web download in gui and I get this error: 
`{‘errorMessage’: ‘Unexpected error, check log for details’} 
`in the system logs, backend section I only see this in debug mode:

`severity: Notice: configd.py [4d171655-ad6d-430f-9b0f-5eb8cea6c5ca] Create archive for capture jobid df0cacc8-09e6-407d-9b80-029da6a53d1b ()
`
I have searched all the other logs and have not seen any other messages related to this error.

**To Reproduce**
from the gui after finish capture try to download it locally.

**Expected behavior**
capture is saved/downloaded without any errors.

**Screenshots**

**Relevant log files**
NA

**Additional context**
NA

Environment

OPNsense 24.7.8-amd64
FreeBSD 14.1-RELEASE-p2
OpenSSL 3.0.14

Proxmox G30W N100

**Comment by AdSchellevis** [comment]
If you change deployment type to development in `System: Settings: Administration` you should be able to get more data in these cases.

**Comment by doreks** [comment]
now if it is ‘more’ clear the error but no idea, I paste it here:

`{"errorMessage":"Too few arguments to function OPNsense\\Mvc\\Response::setContentType(), 1 passed in /usr/local/opnsense/mvc/app/controllers/OPNsense/Diagnostics/Api/PacketCaptureController.php on line 157 and exactly 2 expected","errorTrace":"#0 /usr/local/opnsense/mvc/app/controllers/OPNsense/Diagnostics/Api/PacketCaptureController.php(157): OPNsense\\Mvc\\Response->setContentType('application/oct...')\n#1 /usr/local/opnsense/mvc/app/library/OPNsense/Mvc/Dispatcher.php(165): OPNsense\\Diagnostics\\Api\\PacketCaptureController->downloadAction('df0cacc8-09e6-4...')\n#2 /usr/local/opnsense/mvc/app/library/OPNsense/Mvc/Router.php(156): OPNsense\\Mvc\\Dispatcher->dispatch(Object(OPNsense\\Mvc\\Request), Object(OPNsense\\Mvc\\Response), Object(OPNsense\\Mvc\\Session))\n#3 /usr/local/opnsense/mvc/app/library/OPNsense/Mvc/Router.php(139): OPNsense\\Mvc\\Router->performRequest(Object(OPNsense\\Mvc\\Dispatcher))\n#4 /usr/local/opnsense/www/api.php(36): OPNsense\\Mvc\\Router->routeRequest('/api/diagnostic...', Array)\n#5 {main}"}`

thanks for your support!

**Comment by AdSchellevis** [comment]
No clue, it works on my end, code looks normal as well:

https://github.com/opnsense/core/blob/9a689f2381e89af797729307d89df4511097b047/src/opnsense/mvc/app/controllers/OPNsense/Diagnostics/Api/PacketCaptureController.php#L157


Maybe try a firmware health audit to find broken files.

**Comment by doreks** [comment]
I have already solved it, it seems that the computer was not completely updated to version 24.7.8, I have forced it and after restarting and installing the verison correctly, it works now

thanks for your support  @AdSchellevis
