### ISSUE TITLE
os-dnscrypt-proxy: Missing ODoH aliases because of old base version

### ISSUE THREAD

**Issue by vpx23** [opnsense/plugins#4367]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] When the request is meant for an existing plugin, I've added its name to the title.

I would like to use the dnscrypt server alias "odoh-cloudflare" in "Services: DNSCrypt-Proxy: Configuration: Server List" but this is not possible because the base version seems to be 2.1.0 while ODoH servers were introduced in 2.1.2, to quote the dnscrypt-proxy changelog:

> # Version 2.1.2
>  - `dnscrypt-proxy -list` now includes ODoH (Oblivious DoH) servers.

Is it possible that you update the dnscrypt-proxy to the latest version 2.1.5?

os-dnscrypt-proxy version: 1.15_1

**Comment by vpx23** [comment]
Oh, I just looked at the plugin changelog which only mentioned "2.1". So it was probably not working because I didn't enter a ODoH relay server.

I just wanted to suggest to add "Base Version" in "System: Firmware: Plugins". But then I noticed it already is mentioned in "Packages".

It would be nice if there was some sort of link to the underlying package in "Plugins" that would be more convenient for non-developers. ☺

**Comment by fichtner** [comment]
Basically all versioning of packages is the same. The most convenient think would be to add a note to the upstream version in the plugin changelog. If you want to propose a change to there feel free (changing 2.1 to 2.1.5 which seems correct).

**Comment by vpx23** [comment]
I think I found the culprit and posted it here yesterday with my private account: https://github.com/opnsense/plugins/pull/3810

But I noticed another cosmetic bug in "DNSCrypt-Proxy: Log", the texts are not aligned to the column headings.

![dnscrypt_proxy_log](https://github.com/user-attachments/assets/4a03c747-5300-4284-8b3c-e180b123ace9)

That's probably because it's directly parsed from dnscrypt-proxy and not translated to the OPNsense format.
