### ISSUE TITLE
Caddy: support h2c protocol for reverse_proxy

### ISSUE THREAD

**Issue by oliverpool** [opnsense/plugins#4368]
**Important notices**

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**

I would like to have a gRPC streaming handler, with the TLS managed by Caddy. For this the upstream connection must use h2c (gRPC streams require http/2, but I don't want to have a certificate, hence "unencrypted http/2" a.k.a. h2c).

According to the [Caddy docs](https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#upstream-addresses), the resulting config should look like:
```caddy
reverse_proxy {
    to h2c://127.0.0.201:7777
}
```

**Describe the solution you'd like**
I would like to be able to select `h2c://` as upstream protocol (currently only `http://` and `https://` are available).

**Describe alternatives you've considered**
Using a Layer4 config should work, but I am not sure how to enable the TLS termination.

**Additional context**

The template should be adapted around the following lines:

https://github.com/opnsense/plugins/blob/8cd1be1adbf33c4d04d4b77406c0b84f1de0a42e/www/caddy/src/opnsense/service/templates/OPNsense/Caddy/Caddyfile#L447

The model should be expanded as well:

https://github.com/opnsense/plugins/blob/8cd1be1adbf33c4d04d4b77406c0b84f1de0a42e/www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.xml#L358

cc @Monviech who originally created the Caddy plugin, I believe (thanks for the great work BTW!)

**Comment by Monviech** [comment]
That seems easy to add, I will put it on my list.

Btw TLS termination will come here:
https://github.com/opnsense/plugins/pull/4364

**Comment by Monviech** [comment]
@oliverpool

You can test the change, execute this in the ssh shell:

```
opnsense-patch -c plugins ec4b328027e6e87ebab618834073fcd8f9b7bf06
```

Please give me feedback if it works as expected for you. :)

**Comment by oliverpool** [comment]
@Monviech thank you so much, it seems to be working fine!!
