### ISSUE TITLE
www/caddy - please give us a drop down for load balancing strategy selection.

### ISSUE THREAD

**Issue by tomtom13** [opnsense/plugins#4378]
- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
I would like to be able to change the load balancing strategy for given backend OR for whole caddy service (thou I think most people would prefer it to me per "handler")

**Describe the solution you'd like**
I would love to be able to set load balancing to "first" because most of my services require local auth in a service and sending packets to all the backend servers will make it NOT work. Strategy "first" will allow a simple failover.

**Describe alternatives you've considered**
Maybe rather than using "random" maybe set "first" as default, since I don't think most people run unauth / stateless services behind their opensense.

**Additional context**
No additional context here, I think feature request is sufficient.

**Comment by Monviech** [comment]
@tomtom13 You get an almost full load balancing implementation with all passive health checks and most load balancing options.

**Comment by tomtom13** [comment]
Errrrrrrrr .... don't know what to say, "Thanks" ? Usually there is a lot of pushback of simple changes on GH, yet here is a full menu implemented just by asking. So maybe: "Thank you very much" ?

**Comment by Monviech** [comment]
Its going to be in the next version this week.

There can be pushback, I also pushback if options are too convoluted or too specific. But this is generalized and adds value that was missing.

Thanks for testing this after release, if you find an issue Ill fix it.
