### ISSUE TITLE
Caddy Widget Wildcards Result in 'Caddy does not manage any automatic certificates'

### ISSUE THREAD

**Issue by dcrdev** [opnsense/plugins#4400]
- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
Currently the /api/caddy/reverse_proxy/get endpoint displays wildcard domains as '*.domain.com', however the  /api/caddy/diagnostics/certificate endpoint displays wildcard 'wildcard_.domain.com'. The net effect of this is the widget shows: 'Caddy does not manage any automatic certificates'.

The function responsible for this is https://github.com/opnsense/plugins/blob/06a28c3496eabdffc1216a8630b573a4f6c2df2b/www/caddy/src/opnsense/www/js/widgets/CaddyCertificate.js#L50

**Expected behavior**
I would expect wildcard certificates to show in the widget

**Screenshots**
<img width="249" alt="image" src="https://github.com/user-attachments/assets/3a0cbab8-e444-445e-9d45-1618abe350ee" />

OPNsense 24.7.10_2-amd64

Linked PR: https://github.com/opnsense/plugins/pull/4399

**Comment by dcrdev** [comment]
PR https://github.com/opnsense/plugins/pull/4399

**Comment by Monviech** [comment]
Fixed by: https://github.com/opnsense/plugins/pull/4385
