### ISSUE TITLE
FreeRADIUS: "EAP Check TLS Common-Name" Option does not work

### ISSUE THREAD

**Issue by fnufu** [opnsense/plugins#4408]
Version 	24.7.10_2
Plugin os-freeradius 1.9.26
(I am new user to this specific plugin, I don't know if this error existed in other versions)

**Reproduce**

1. Prerequisite: existing and working freeradius EAP TLS config using ca/server/user certs generated via system/trust
2. Go to /ui/freeradius/eap/index
3. Enable "Check TLS Common-Name" Option
4. Click Save
5. Optional: Test with Radius User configured as EAP TLS, Connection is always accepted no matter if cn matches username
6. ssh into opnsense shell
7. vi into /usr/local/etc/raddb/mods-enabled/eap
8. find line 329 commented out `       #        check_cert_cn = %{User-Name}`
9. Toggle/Save "Check TLS Common-Name" Option
10. Reload /usr/local/etc/raddb/mods-enabled/eap, no effect, line 329 stays commented out

**Expected behavior**
Option works as expected, GUI toggle reflects in Config File

**Comment by mimugmail** [comment]
https://github.com/opnsense/plugins/blob/master/net/freeradius/src/opnsense/service/templates/OPNsense/Freeradius/mods-enabled-eap#L724-L728

Which loads a new site with:

```
        # Check the client certificate common name against the supplied User-Name
        #
        if (&User-Name == &TLS-Client-Cert-Common-Name || &User-Name == "host/%{TLS-Client-Cert-Common-Name}") {
                update config {
                        &Auth-Type := Accept
                }
        }
        else {
                update config {
                        &Auth-Type := Reject
                }
        }
```

**Comment by fnufu** [comment]
Thank you for pointing out how this actually works, the commented out line in config was a red herring to a configuration problem on my side. Solved.
