### ISSUE TITLE
[os-nextcloud-backup] Support Custom CA Roots with Nextcloud Backup

### ISSUE THREAD

**Issue by tuaris** [opnsense/plugins#4422]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
The Nextcloud backup plugin currently does not work when the target server is using a certificate signed by a non public CA or a CA that's not commonly included in system defaults.  Even though that CA has been added to OPNsense's System: Trust: Authorities.

Attempting to use such a server will result in an error similar to the following, where the error message from cURL reporting `"ssl_verify_result":19`, indicates it failed to validate the TLS certificate.

```
{"url":"https:\/\/cloud.myserver.tld\/remote.php\/dav\/files\/OPNSense\/Backups","content_type":null,"http_code":0,"header_size":0,"request_size":0,"filetime":-1,"ssl_verify_result":19,"redirect_count":0,"total_time":0.219143,"namelookup_time":0.001327,"connect_time":0.025105,"pretransfer_time":0,"size_upload":0,"size_download":0,"speed_download":0,"speed_upload":0,"download_content_length":-1,"upload_content_length":-1,"starttransfer_time":0,"redirect_time":0,"redirect_url":"","primary_ip":"x.x.x.x","certinfo":[],"primary_port":443,"local_ip":"x.x.x.x","local_port":26534,"http_version":0,"protocol":2,"ssl_verifyresult":0,"scheme":"https","appconnect_time_us":0,"connect_time_us":25105,"namelookup_time_us":1327,"pretransfer_time_us":0,"redirect_time_us":0,"starttransfer_time_us":0,"total_time_us":219143,"effective_method":"PROPFIND"}
```

**Describe the solution you'd like**
The plugin, more specifically the cURL options used by the plugin in https://github.com/opnsense/plugins/blob/2b31d941f6dac7f064d423524632f1190c89895d/sysutils/nextcloud-backup/src/opnsense/mvc/app/library/OPNsense/Backup/Nextcloud.php#L326 should be modified to include a `CURLOPT_CAINFO` (or better `CURLOPT_CAPATH`) so that it may recognize the root CA's present in OPNsense's System: Trust: Authorities.

```
curl_setopt($ch, CURLOPT_CAINFO, '/path/to/custom/ca_certificate.pem');
```

Additionally, as an alternative (less optimal fallback) option, provide an option checkbox in the UI to bypass certificate validation, which will add `CURLOPT_SSL_VERIFYPEER` to the `curl_setopt_array`.

```
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
```

**Describe alternatives you've considered**
There are no alternatives to resolving this other than hacking the source code myself.

**Additional context**
N/a

**Comment by fichtner** [comment]
It's a bit unlikely the trust store doesn't work. 19 is indeed `X509_V_ERR_SELF_SIGNED_CERT_IN_CHAIN` which means that the cert is not offered to the trust store for one reason or another. I would suggest trying a `fetch` to the server domain from the box itself to see if the same error occurs and then looking into why the correct cert is not offered in the trust store.

**Comment by tuaris** [comment]
Oh you are 100% correct.  It was a silly mistake on my end.  I must have uploaded a combined version of the CA (which had both the Root and Intermediate PEM text) to the trust store and only the Intermediate got captured.  That's at least my suspicion since the error is present on multiple boxes.

**Comment by fichtner** [comment]
😊
