### ISSUE TITLE
net/arp-scan: error in template

### ISSUE THREAD

**Issue by fichtner** [opnsense/plugins#445]
Hey @peppelinux ,

I found this slight error during first arp-scan setup:

```
configd.py: [edb7b42a-a83a-489d-b1f6-826a89bfd733] Inline action failed with OPNsense/ARPscanner OPNsense/ARPscanner/ARPscanner.conf 'collections.OrderedDict object' has no attribute 'arpscanner' at Traceback (most recent call last): File "/usr/local/opnsense/service/modules/processhandler.py", line 507, in execute return ph_inline_actions.execute(self, inline_act_parameters) File "/usr/local/opnsense/service/modules/ph_inline_actions.py", line 50, in execute filenames = tmpl.generate(parameters) File "/usr/local/opnsense/service/modules/template.py", line 321, in generate raise render_exception Exception: OPNsense/ARPscanner OPNsense/ARPscanner/ARPscanner.conf 'collections.OrderedDict object' has no attribute 'arpscanner'
```

Cheers,
Franco

**Comment by fabianfrz** [comment]
@fichtner This is probably because the configuration for the template does not exist. This is why our (Franks, Michaels and mine) plugins contain a check in one of the first lines prevent full rendering such cases.

**Comment by peppelinux** [comment]
Hi guys, I can tell you that I never seen this exception, otherwise I would have solved it before release, sorry for this.

@fabianfrz it seems that you have an idea about how this should be fixed in a common way but I did not understand what about this "full rendering", sorry for this too :)

**Comment by fabianfrz** [comment]
@peppelinux this will prevent rendering the configuration file if the service is not configured:
https://github.com/opnsense/plugins/blob/master/net/frr/src/opnsense/service/templates/OPNsense/Quagga/ospfd.conf#L5
In this case you would get an empty file.

**Comment by peppelinux** [comment]
I fixed this: https://github.com/opnsense/plugins/issues/506 but I do not have the time to fix .conf as well.
I read the proposed syntax in ospf.conf (thank you @fabianfrz), this will take more time :(
