### ISSUE TITLE
HAPRoxy: Gui Forms autocomplete // Cannot configure Listen Address

### ISSUE THREAD

**Issue by Constey** [opnsense/plugins#448]
Using latest version: 17.7.11 (installed)
os-haproxy 2.2 (installed)

When configuring items like the Listen Adress in a Virtualhost it is required to press TAB after entering the adress, otherwise the item is not added correctly to the form field and a save is not possible because of the input field checker. So there is a adress entered but it does not count due it is not serialized? as object before.

May the entered stuff could be serialized? when pressing the save button, so there is no issue anymore?

**Comment by fichtner** [comment]
Duplicate, tracked via https://github.com/opnsense/core/issues/1689 :)

**Comment by Constey** [comment]
Sorry, didn't looked into core

**Comment by fichtner** [comment]
No worries. All feedback helps, especially with "tricky default behaviour".
