### ISSUE TITLE
[Request] Bro

### ISSUE THREAD

**Issue by lattera** [opnsense/plugins#453]
Having Bro as a plugin would be an awesome feature for OPNsense, especially when used in conjunction with Suricata.

**Comment by fichtner** [comment]
We should start with the addition of the package for 18.1 and go from there. I think it will be quite improbable that someone will come forward and write a plugin. We should also not just copy Suricata integration... ideally the code should be refactored where we could for rule management. It will be quite a lot of work.

**Comment by lattera** [comment]
Completely agreed.

**Comment by thutex** [comment]
@fichtner i see bro is in the ports, is there still an intent to introduce it into the firewall as an actual plugin? (asking because it might have its merits to have this integrated)

**Comment by fichtner** [comment]
@thutex it was never added as a package... back then we talked about how old the port was but I remember seeing it updated more frequently/recently now?

The biggest issue with a plugin is the complexity. So far nobody volunteered and from a core perspective we would prefer to keep the maintained IDS range to 1 solution which is Suricata.


Cheers,
Franco

**Comment by lrosenman** [comment]
I know bro is having a rename going on right now (I'm mentoring it's FreeBSD maintainer).

**Comment by thutex** [comment]
@fichtner ah ok...
i am happy with suricata (and even more so with OPNsense and the devs) but was wondering,
since i found this https://github.com/opnsense/ports/tree/master/security/bro  as well as this request being open making me think it was/will be on the planning.

**Comment by AdSchellevis** [comment]
We have an intern over here looking into Zeek (bro), but building a useful plugin which is suitable for the general audience might be too challenging at the moment. The package itself is quite easy to build and install by the way, it just has a quite some different use-cases and often needs additional packages to be really useful.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.

**Comment by Ondjultomte** [comment]
I'd like to see a simple integration of bro , only for the tap/span parts alone. You'd need a CLI for investigation etc. and I think thats the moste difficult part to solve on a dedicated firewall.

perhaps spawn a dedicated jail for the bro logs ? So one could ssh and just do analysis?
