### ISSUE TITLE
audit use of [reconfigure]

### ISSUE THREAD

**Issue by fichtner** [opnsense/plugins#454]
In a number of plugins reconfigure equals restart, which is effectivelly useless. reconfigure was a concept by the core web proxy, which did a rc.d "reload" after generating the temples. The service controllers, however, have a reconfigure that simply stop + start (or restart) unless a "reconfigure" is defined, which makes the use of [reconfigure] silly if we use a stock reconfigure call, especially with the introduction of the mutable service controller.

```
$ git grep '\[reconfigure\]'
mail/postfix/src/opnsense/service/conf/actions.d/actions_postfix.conf:[reconfigure]
net-mgmt/collectd/src/opnsense/service/conf/actions.d/actions_collectd.conf:[reconfigure]
net-mgmt/telegraf/src/opnsense/service/conf/actions.d/actions_telegraf.conf:[reconfigure]
net-mgmt/zabbix-agent/src/opnsense/service/conf/actions.d/actions_zabbixagent.conf:[reconfigure]
net-mgmt/zabbix-proxy/src/opnsense/service/conf/actions.d/actions_zabbixproxy.conf:[reconfigure]
net/freeradius/src/opnsense/service/conf/actions.d/actions_freeradius.conf:[reconfigure]
net/frr/src/opnsense/service/conf/actions.d/actions_quagga.conf:[reconfigure]
net/haproxy/src/opnsense/service/conf/actions.d/actions_haproxy.conf:[reconfigure]
net/quagga/src/opnsense/service/conf/actions.d/actions_quagga.conf:[reconfigure]
net/siproxd/src/opnsense/service/conf/actions.d/actions_siproxd.conf:[reconfigure]
security/clamav/src/opnsense/service/conf/actions.d/actions_clamav.conf:[reconfigure]
www/c-icap/src/opnsense/service/conf/actions.d/actions_cicap.conf:[reconfigure]
www/web-proxy-useracl/src/opnsense/service/conf/actions.d/actions_proxyuseracl.conf:[reconfigure]
```

**Comment by fichtner** [comment]
While here, change the backend of web proxy to „reload“ to avoid implying the reconfigure does what it should.

**Comment by fabianfrz** [comment]
can tell you from my plugins (frr/quagga) that they restart the service (the service command cannot reconfigure the service).

**Comment by fichtner** [comment]
Im those cases the backend call can be removed, and reconfigure usage replaced with restart. :)

**Comment by fichtner** [comment]
@fabianfrz it was unused in frr and quagga so I removed it. adding a "reload" is reasonable, but that requires testing by the maintainers as reload may or may not work with a particular service and I don't want to confuse users with "reload" commands that do not reload.

**Comment by fabianfrz** [comment]
@fichtner no problem.
