### ISSUE TITLE
net/haproxy: service reconfigure consolidation

### ISSUE THREAD

**Issue by fichtner** [opnsense/plugins#455]
Due to https://github.com/opnsense/plugins/commit/c458c3c7 it seems the reload is a bit strange / error-prone. Rework this for clarity. Ticket for feedback and discussion by @fraenki

**Comment by fraenki** [comment]
@fichtner Just noticed this too while working on other HAProxy stuff yesterday. I think it's solved by switching to the new mutable service controller (see #483, especially https://github.com/opnsense/plugins/pull/483/commits/7381101d5fafff59c4ffe20e342f63f6d2258775).

**Comment by fichtner** [comment]
Thanks! This means [reload] is now unused and could be removed from the configd actions.

Or you implement a reload logic hook like web proxy:

https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/controllers/OPNsense/Proxy/Api/ServiceController.php#L46-L57

Returning "0" in this function will execute a reload. Returning "1" is the default for the mutable controller.
