### ISSUE TITLE
security/acme-client: Provided agreement URL does not match current agreement URL

### ISSUE THREAD

**Issue by rschueler** [opnsense/plugins#470]
When issuing a new certifcate the process fails with following log messages:

Update account error. code='400'
response='{"type":"urn:acme:error:malformed","detail":"Provided agreement URL [https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf] does not match current agreement URL [https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf]","status": 400}'
responseHeaders='HTTP/1.1 100 Continue "detail": "Provided agreement URL [https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf] 	does not match current agreement URL [https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf]",
original='{_ret='0'
_CURL='curl -L --silent --dump-header /var/etc/acme-client/home/http.header '

**Comment by dharrigan** [comment]
I believe this is fixed already in acme.sh 2.7.5

https://github.com/opnsense/plugins/issues/418

-=david=-

**Comment by fichtner** [comment]
We could pull it in, it's in FreeBSD, but I need an ack from @fraenki as we have agreed a while ago.

**Comment by fichtner** [comment]
For reference, 2.7.5 could be installed on the OPNsense like this:

```
# opnsense-code tools ports
# cd /usr/ports/security/acme.sh
# make
# make deinstall
# make install
```

**Comment by fraenki** [comment]
Thanks for reporting this issue! :heart: 
I've greenlit acme.sh 2.7.5, it will be included in the next release :)

**Comment by fichtner** [comment]
There was a forum post that said the next version does not fix this (automatically). I don’t have the link at the moment.

**Comment by fraenki** [comment]
It [turned out](https://forum.opnsense.org/index.php?topic=7139.0) that acme.sh 2.7.5 did not contain a fix, but instead acme.sh 2.7.6 will finally include a fix:
https://github.com/Neilpang/acme.sh/commit/f87890cb4b534feecd23dd2e7042e8601f15a3c3

**Comment by fichtner** [comment]
Any idea when this will be released?

**Comment by fraenki** [comment]
> Any idea when this will be released?

Nope. :( The number of changes in acme.sh 2.7.6 already scares me, so he should take his time to make it a stable release.

**Comment by fraenki** [comment]
acme.sh 2.7.6 is available in the current release of OPNsense.
