### ISSUE TITLE
new plugin releases for 18.1

### ISSUE THREAD

**Issue by fichtner** [opnsense/plugins#474]
None of these are non-devel releases in 18.1-RC1, but we could switch them on in 18.1-RC2 or 18.1.

CC @dharrigan @fabianfrz @mimugmail 

* ~~benchmarks/iperf~~ (released)
* ~~databases/redis~~ (released)
* ~~mail/postfix~~ (released)
* ~~mail/rspamd~~ (released)
* ~~net-mgmt/lldpd~~ (released)
* net/shadowsocks (missing test via @Laven7)
* security/openconnect (audit via @fichtner)
* ~~sysutils/node_exporter~~ (released)
* sysutils/nut (missing test via @djzort)

**Comment by fabianfrz** [comment]
@fichtner this is the dependency tree:

Please note that `scp-backup` is missing in your list

* core -> postfix -> rspamd -> redis
* core -> scp-backup (some of my changes)
* lldpd
* iperf
* shadowsocks
* openconnect
* node_exporter
* nut

My plugins (redis, rspamd, iperf) can be published, however the first two will not be very useful without postfix which depends on a core change. iperf was on devel long enough without bug reports so it is probably stable. For nut I think the same.
In contrast lldpd, shadowsocks, openconnect and node_exporter should have some grace period before being merged to stable (1-2 weeks) so they can be tested by some users before.

**Comment by fabianfrz** [comment]
@fichtner just an idea: since RC is a `-devel`, all of them can be enabled except scp-backup, which should wait for my PR.

**Comment by fichtner** [comment]
No that’s not how RC works. It’s essentially a stable prerelease if 18.1 leading up to 18.1.x so we can’t undo a plugin release. ;)

Scp-backup is missing on purpose. Since we want to release in core, it should never be released as a plugin. Plugins.git is merely used as a convenient staging environment to test this. Also because committing to core was locked until stable/18.1 could be branched. That’s why scp/ssh is a sensitive topic.

**Comment by mimugmail** [comment]
OpenConnect and LLDPd can go stable with 18.1, they are really easy and when RC1 will add a devel pkg I can let some colleagues test as real business case. 
ShadowSocks needs a devel pkg so Laven7 can test, no hurry to go stable with 18.1. 
Nut needs testing of djzort, it seems he's on vacation, I can't release this until it's not really tested, so also no hurry. 
Postfix is stable to release with 18.1, I'm routing my mailing list accounts for 4-6 weeks over a virtual instance, it's fine. But the topic regarding logging is still unclear. Either you ( @fichtner ) add a mail class to syslog (I think this is core?) or we stick to system.log for a while (or this is a showstopper for 18.1).

**Comment by fichtner** [comment]
I'll add the syslog glue to postfix for 18.1-RC2 and switch all the mail plugins to release then.

lldpd will be released for 18.1-RC2, openconnect maybe 18.1, but I want to poke the interface rename thing to see how stable it is or if we should patch openconnect.

**Comment by fichtner** [comment]
iperf is also released in 18.1-RC2 👍

**Comment by fabianfrz** [comment]
if you want, you can release redis as well (it may be used for other stuff for now)

**Comment by fichtner** [comment]
Ok done.

In the future, I want to remind maintainers to send these "first pubic release" changes as PRs, it makes it easier to handle and implies an "ok" :)

**Comment by fichtner** [comment]
after an ok from @mimugmail for the latest changes we could switch on postfix (and rspamd previously ack'ed by @fabianfrz) for 18.1-RC2

**Comment by fichtner** [comment]
shadowsocks, openconnect and nut will wait for 18.1.x, everything else is out. thank you guys!

**Comment by dharrigan** [comment]
w00t!
