### ISSUE TITLE
Postfix GUI: Domain redirect: change port for redirect host

### ISSUE THREAD

**Issue by eigener-server** [opnsense/plugins#478]
Feature request: Is it possible to add the destination port of the new host in the GUI / Postfix / Domain section so that it is possible to relay to a server not running on port 25.

relayhost = [server.example.com]:50025

**Comment by mimugmail** [comment]
You mean a general relayhost without specific transports or within the transports?

**Comment by eigener-server** [comment]
I'm not that familiar with postfix. I've a opnsense firewall on a small vserver in the Internet where the postfix relay domain plugin is running. The postfix server with the domain is then running on my server at home. 
I do not like to open port 25 on the Internet router at home. Instead I like more to open a different port like port 50025.

**Comment by mimugmail** [comment]
Yes, I understand, so you use the Domain menu, set your domain and the destination, correct?

**Comment by eigener-server** [comment]
yes. And I like to set additional a destination port.

**Comment by mimugmail** [comment]
I'll try to change the field type so you can enter the complete string on your own
[server.example.com]:50025
server.example.com:50025
IP:50024

etc.

**Comment by eigener-server** [comment]
perfect :-) So I can close the other request with the FQDN.
