### ISSUE TITLE
postfix GUI: Domain section: Add FQDN name as destination

### ISSUE THREAD

**Issue by eigener-server** [opnsense/plugins#479]
Feature request: Allow to add FQDN as destination host.
![postfix gui domain fqdn](https://user-images.githubusercontent.com/28820248/34818024-e85492dc-f6b9-11e7-9569-bcca1010f351.JPG)

**Comment by mimugmail** [comment]
It this related to your first one? If yes you can close this one :)

**Comment by eigener-server** [comment]
yes and no. It's the same gui. Maybe the other request is not possible / or to difficult.
I think this request is only related to the filter on the FORM. Allow FQDN.
The other ticket might also involve an additional field or a change in the script.

**Comment by eigener-server** [comment]
Field type is planned to change in #478 So This request can be closed.
