### ISSUE TITLE
net-mgmt/Zabbix-Agent: Error on install

### ISSUE THREAD

**Issue by mimugmail** [opnsense/plugins#491]
```
Jan 17 16:00:11 OPNsense config[80154]: [OPNsense\ZabbixAgent\ZabbixAgent:local.hostname] Should be a string between 1 and 255 characters.
Jan 17 16:00:11 OPNsense config[80154]: [OPNsense\ZabbixAgent\ZabbixAgent:settings.main.serverList] Please provide valid Zabbix server addresses, i.e. 10.0.0.1 or zabbix.example.com.
Jan 17 16:00:11 OPNsense config[80154]: [OPNsense\ZabbixAgent\ZabbixAgent:settings.main.listenIP] Please provide valid IP addresses, i.e. 10.0.0.1.
Jan 17 16:00:11 OPNsense config[80154]: Model OPNsense\ZabbixAgent\ZabbixAgent can't be saved, skip ( Phalcon\Validation\Exception: [OPNsense\ZabbixAgent\ZabbixAgent:local.hostname] Should be a string between 1 and 255 characters. [OPNsense\ZabbixAgent\ZabbixAgent:settings.main.serverList] Please provide valid Zabbix server addresses, i.e. 10.0.0.1 or zabbix.example.com. [OPNsense\ZabbixAgent\ZabbixAgent:settings.main.listenIP] Please provide valid IP addresses, i.e. 10.0.0.1.  in /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php:511 Stack trace: #0 /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php(615): OPNsense\Base\BaseModel->serializeToConfig() #1 /usr/local/opnsense/mvc/script/run_migrations.php(56): OPNsense\Base\BaseModel->runMigrations() #2 {main} )

```

**Comment by fraenki** [comment]
This is expected. The plugin can't automatically generate a real-world Zabbix Ageng config.

I don't want to provide default values that would validate in the MVC, but would otherwise never work in a Zabbix environment. That's why the plugin does not provide any default config at all.

I'm open for suggestions.

**Comment by fichtner** [comment]
This is interesting. We want to validate, but only for the purpose of a running (enabled) config, yet we don't have anything yet (and possibly don't care). Sounds like an impossible choice. Let's agree that the errors sucks without agreeing on how to solve it?

**Comment by fraenki** [comment]
Maybe I should add the most obvious placeholders as default values. Something like zabbix.example.com and 127.0.0.1. This will satisfy the validation and should be obvious enough for most users.

**Comment by fraenki** [comment]
@mimugmail @fichtner Do you agree with my proposal?

**Comment by fichtner** [comment]
I'm not sure yet, let's keep this "under observation" for now?

**Comment by mimugmail** [comment]
Agreed .. this is nothing to fix between RC and stable :) 

For agent.conf.sample the defaults should be:
Hostname= "Zabbix agent"
Server IP= "127.0.0.1"
Listen = 0.0.0.0

**Comment by fraenki** [comment]
> For agent.conf.sample the defaults should be:
> Hostname= "Zabbix agent"
> Server IP= "127.0.0.1"
> Listen = 0.0.0.0

That's actually a good point. Following FreeBSD's configuration samples and Zabbix' own default values sounds like a rather good choice.

**Comment by fichtner** [comment]
fine by me 👍
