### ISSUE TITLE
frr interface missing ability to specify interfaces and vtysh password

### ISSUE THREAD

**Issue by rootwyrm** [opnsense/plugins#493]
FRR (formerly Quagga) in 18.1r2 does not provide a way to configure which interfaces it is bound to. Interface binding can only be set in `zebra.conf` using the following syntax:

`interface lo` (should always be present)
`interface $IFNAME` (e.g. vmx0)

Password is set as `password plaintext_password` (I know it's bad, but it's better than nothing.) This can be set in both zebra.conf (vtysh) and each specific instance. Without a password being set in the configuration, any IP address can access vtysh via telnet with no authentication.

If no interfaces are set, it will allow passwordless access to the vtysh interface (which the UI does not provide any mechanism to set) on **ALL** interfaces, creating multiple vulnerabilities. The vtysh interface can then be accessed remotely over WAN, LAN, and VPN with no authentication check permitting an attacker to inject malicious routes. This also can cause risks to networks through unwanted or malicious advertisements. The default of 'deny any' on WAN should be considered wholly insufficient protection on it's own.

**Comment by mimugmail** [comment]
If no passwords are set it doesn't allow you to enter when connecting to the service:
`Vty password is not set.`

If we enable this we should only allow binding to localhost. @fichtner @fabianfrz ?

**Comment by fabianfrz** [comment]
@mimugmail I do not want a password. Using vtysh from external computers may bypass OPNsense ACLs and the Ports are not exposed by default (PF will block them). Not setting any password is documented to disallow logins from external hosts so I think this is OK.

**Comment by rootwyrm** [comment]
@fabianfrz if it can bypass ACL, that's a very different problem that needs looked at. It should not be possible to bypass ACL, only to inject or delete. Additionally, a firewall is not an excuse for having no password or an insecure password. (Ask BCBS or Aetna for example.) However, you're right, I did miss that vtysh won't permit external without a password set, so that definitely can get chucked in the 'feature' pile. 
Optimally users should be able to enable access to vtysh if that is their choice. Maybe a tick box to enable remote vtysh? I'm not familiar with the php innards here.

But that still leaves the issue of binding to the interfaces. Which is killing me because my ISP is stupid enough to spam bad announces that collide. Plus it unnecessarily exposes all route data, which may be undesirable for a variety of reasons.

**Comment by fabianfrz** [comment]
@rootwyrm In the case users want to use `vtysh`, they should **NOT** use the plugin because it would bring the config out of sync and vtysh can change interface settings (which might not be what is intended). If you want to configure it by hand, you can - the GUI is optional.

For the last paragraph: That has nothing to do with `vtysh` but with your configuration. If you don't want your ISP routes -> passive interface. If you want them (filtered), use Route maps etc.

**Comment by rootwyrm** [comment]
I feel like you didn't actually read what was written. I CANNOT filter because they COLLIDE. And blindly binding to all interfaces is inadvisable regardless of that.

**Comment by mimugmail** [comment]
Ok, can we split the topics a bit. 
- Without passwords you cant connect to vtysh from outside, it's recommended by documentation. For debugging it's allowed without passwords via local SSH session
- configuring a lo0 in zebra.conf is only needed when you want password access for vty access from outside? We had a talk when introducing Quagga plugin regarding interfaces and we agreed to completely take this out to no interfere with interface configuration via UI
- Can you explain your ISP issue a bit more with IP addresses? For you it's all clear but for an external reader it's hard to follow

**Comment by rootwyrm** [comment]
Yeah; I'm in agreement that vtysh is a secondary concern and belongs as feature rather than bug.

The problem with my ISP, well, fitting that into less than five thousand words would be a miracle. Suffice to say, their exterior AS regularly gets filtered because of bogon announcements and a steadfast refusal to consolidate announcements. On the *inside* of their network; that is, behind border routers? It's infinitely worse. They announce basically the entire 10net space, in /24 chunks, and are making use of at least three dozen reserved ASNs to do so. Which results in both flood and collision. 

Those 10net announcements are also going out the edge routable IP interfaces - meaning the immediate next hop for WAN. (Also bear in mind that devices behind CPEs are able to gain full access to their 10net space simply by setting a static 10net address as well.) End result, the same ASNs I use are announcing either conflicting routes or bogus routes I don't want.
It's not realistic or even possible to filter prefixes or ASNs because they're using so many. And I can't prefix filter, because I use among others, IPv6 feeds, bgp-spamd, and other feeds that may announce literally any possible prefix. Plus that would require filtering my own prefixes, obviously suboptimal.
And you would be correct in assuming they should be constructing their neighbor statements to prevent this. However, they very much do not. All routable IPs they control are permitted neighbors. Response to date has been "meh, it's fine, none of our customers run BGP!" 
Also I have found that several popular VPN providers also apparently treat clients as BGP neighbors potentially. I'm still investigating that part. Even without it, BGP is an EXTREMELY chatty protocol and can cause severe problems even when you implement strict filtering.

**Comment by mimugmail** [comment]
Thanks for this belows 5000 words :) Ok this is extremely unusal .. I'd say with an infilter on the neighbor this should work, but I was never in a situation like this, you'll know better. On this problem I think I can't help you. But my main question is why do you need interface config to mitigate this false behavior?

**Comment by rootwyrm** [comment]
Simply put, all of the BGP I want? Should be isolated to lo0 and internal interfaces. If the WAN interface isn't specified, then bgpd doesn't listen on it, and won't eat the routes from it. (Remember, they're bypassing bogon filters because routable IPs announce.) So in my scenario, simply killing it off from the WAN and VPN interfaces, solves it completely. No additional filters or anything required.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
