### ISSUE TITLE
vmware: loader.conf and automatic kldload on install

### ISSUE THREAD

**Issue by fichtner** [opnsense/plugins#5]

**Comment by fichtner** [comment]
New proposal available.

**Comment by m4rcu5** [comment]
Let me know when its packaged, I should be able to test coming days :smile:

**Comment by fichtner** [comment]
It'll need some code glue in core.git and I'm not entirely sure about it, but doing a RFC right now amongst the devs to see if this has a future or to wiggle a little to see what else can be done without doing the proposal. I'll let you know soon! :)

**Comment by fichtner** [comment]
Works. Will ship this directly with 15.7.18 :)
