### ISSUE TITLE
rebellion theme: some found issues

### ISSUE THREAD

**Issue by fabianfrz** [opnsense/plugins#501]
some feedback for @marjohn56

![screenshot_20180120_184907](https://user-images.githubusercontent.com/3713914/35186393-cbe34da8-fe13-11e7-8db2-9bf8e1b5e5e6.png)
Maybe this colour combindation does not fit well together (green / blue)
![screenshot_20180120_185021](https://user-images.githubusercontent.com/3713914/35186395-d04e8628-fe13-11e7-8075-585852cb6335.png)
The "tokenize" fields do not have the theme colours
![screenshot_20180120_185514](https://user-images.githubusercontent.com/3713914/35186398-d4ad4416-fe13-11e7-89b1-91689485bb68.png)
Modals: The close button (top right -> "X") is not visible anymore.

**Comment by fabianfrz** [comment]
The headings are not readable unless hovered with the mouse:
![screenshot_20180120_190722](https://user-images.githubusercontent.com/3713914/35186471-25c8736a-fe15-11e7-919e-976fd05bdf6d.png)

**Comment by marjohn56** [comment]
It;'s not a bug in the theme itself, some of the things you have mentioned are contained in css files that are outside of the themes folder. Franco is aware that there is some work to do outside of the themes, :)


![image](https://user-images.githubusercontent.com/17962918/35186543-c56b0af2-fe0d-11e7-8583-4a8e28a76b67.png)

Here's mine where I have modified the files. See the comments on the original PR for this theme or have a look at the thread on the forum.

**Comment by fabianfrz** [comment]
may be hard to fix but here is the traffic graph page:
![screenshot_20180120_191750](https://user-images.githubusercontent.com/3713914/35186581-9b93fe74-fe16-11e7-9b5f-fc73de17a496.png)
-> Interface names are hard to read and the hover view might be problematic as well

same in the firewall summary view:
![screenshot_20180120_192059](https://user-images.githubusercontent.com/3713914/35186613-0d449268-fe17-11e7-87a6-6d1219e5bdb9.png)

**Comment by fabianfrz** [comment]
That is all I can find for now.

**Comment by marjohn56** [comment]
That's another that lives outside the themes folder... :)
![image](https://user-images.githubusercontent.com/17962918/35186675-f7e6ec42-fe0f-11e7-8820-9b191e053c1a.png)

**Comment by fabianfrz** [comment]
@marjohn56 👍 for that view.
Maybe the theme can be included into the SVG because CSS works there as well as far as I know.

**Comment by marjohn56** [comment]
Koala - a gui application for LESS, Sass, Compass and CoffeeScript compilation.
koala-app.com

Taken straight from Google search.😀

**Comment by fabianfrz** [comment]
ok, I am using the command line tool without GUI.

**Comment by marjohn56** [comment]
I'm very new to CSS and  scss, so how do you compile from the command line, it's probably a lot easier and quicker than using koala.

**Comment by fabianfrz** [comment]
sass is a ruby gem. it can be installed via `gem install sass`. You can use it via `sass input.scss output.css`.

**Comment by marjohn56** [comment]
Ta... I'll check that out tomorrow and see how I get on.

**Comment by fichtner** [comment]
Close?

**Comment by marjohn56** [comment]
close

**Comment by darkain** [comment]
The "tokenize" fields lost their theme colors again in the 18.7.r2. This is seen in both RIP and BGPv4 under the FRR plugin. Would be nice to get a quick little fix in place before 18.7 is finalized in a couple days.
