### ISSUE TITLE
[os-arp-scan] not select all interface

### ISSUE THREAD

**Issue by sjorge** [opnsense/plugins#506]
It looks like arp-scan is very picky about what interfaces it shows.

![screenshot](https://i.imgur.com/wDtdDdY.png)

Physical interface:
- em0 (normal interface with an IP, nothing fancy)
- igb0 (member of lagg0)
- igb1 (member of lagg0)
- igb2 (member of lagg0)
- igb3 (member of lagg0)

Logical Interface:
- lagg0 (LACP trunk)
- lagg0_vlan10 (over lagg0, network 1)
- lagg0_vlan20 (over lagg0, network 2)
- lagg0_vlan30 (over lagg0, network 3)
- lagg0_vlan40 (over lagg0, network 4)

Currently it is not possible to scan any of the other networks. arp-scan does support these type of setups!

```
root@hydrogen:~ # arp-scan --interface=lagg0_vlan10 xx.yy.zz.0/24
Interface: lagg0_vlan10, datalink type: EN10MB (Ethernet)
Starting arp-scan 1.9 with 256 hosts (http://www.nta-monitor.com/tools/arp-scan/)
xx.yy.zz.154	00:22:06:xx:xx:01	Cyberdyne Inc.
xx.yy.zz.155	00:22:06:xx:xx:02	Cyberdyne Inc.
xx.yy.zz.210	00:22:06:xx:xx:03	Cyberdyne Inc.
xx.yy.zz.216	00:22:06:xx:xx:04	Cyberdyne Inc.
xx.yy.zz.200	00:22:06:xx:xx:05	Cyberdyne Inc.
xx.yy.zz.201	00:22:06:xx:xx:06	Cyberdyne Inc.
xx.yy.zz.225	00:22:06:xx:xx:07	Cyberdyne Inc.
xx.yy.zz.231	00:22:06:xx:xx:08	Cyberdyne Inc.
xx.yy.zz.100	00:22:06:xx:xx:09	Cyberdyne Inc.
xx.yy.zz.135	00:22:06:xx:xx:10	Cyberdyne Inc.
xx.yy.zz.137	00:22:06:xx:xx:11	Cyberdyne Inc.
xx.yy.zz.150	00:22:06:xx:xx:12	Cyberdyne Inc.

2866 packets received by filter, 0 packets dropped by kernel
Ending arp-scan 1.9: 256 hosts scanned in 2.560 seconds (100.00 hosts/sec). 12 responded
```

Alternatively --interface=lagg0 and --vlan=XX can but then also a IP needs to be configured as it not auto detected. Allowing vlan interface for arp-scan in the interface should probably 'just work'TM

**Comment by fabianfrz** [comment]
The issue comes probably from this script:
https://github.com/opnsense/plugins/blob/master/net/arp-scan/src/opnsense/scripts/OPNsense/ARPscanner/IPtools.py#L156

**Comment by fabianfrz** [comment]
@peppelinux it is your plugin - cannot assign the ticket to you.

**Comment by peppelinux** [comment]
Hi there, really strange 'cause I've already scanned through VLAN.
@fabianfrz yes that script get the interfaces names, you got it!

@sjorge please copy and paste your ifconfig output here, I'll test regexps over it to get a working patch.

thank you all guys

**Comment by sjorge** [comment]
This is my output (with a few IPs xxx out)

```
em0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 
1500
	options=4019b<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,VLAN_HWCSUM,TSO4,VLAN_HWTSO>
	ether 00:22:06:xx:xx:xx
	inet xxx.xxx.xxx.10 netmask 0xffffff00 broadcast xxx.xxx.xxx.255
	inet6 fe80::222:6ff:feff:501%em0 prefixlen 64 scopeid 0x1
	nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
	media: Ethernet autoselect (1000baseT <full-duplex>)
	status: active
igb0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 
9000
	options=6507bb<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,TSO4,TSO6,LRO,VLAN_HWFILTER,VLAN_HWTSO,RXCSUM_IPV6,TXCSUM_IPV6>
	ether 0c:c4:7a:xx:xx:xx
	nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
	media: Ethernet autoselect (1000baseT <full-duplex>)
	status: active
igb1: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 
9000
	options=6507bb<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,TSO4,TSO6,LRO,VLAN_HWFILTER,VLAN_HWTSO,RXCSUM_IPV6,TXCSUM_IPV6>
	ether 0c:c4:7a:xx:xx:xx
	nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
	media: Ethernet autoselect (1000baseT <full-duplex>)
	status: active
igb2: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 
9000
	options=6507bb<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,TSO4,TSO6,LRO,VLAN_HWFILTER,VLAN_HWTSO,RXCSUM_IPV6,TXCSUM_IPV6>
	ether 0c:c4:7a:xx:xx:xx
	nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
	media: Ethernet autoselect (1000baseT <full-duplex>)
	status: active
igb3: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 
9000
	options=6507bb<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,TSO4,TSO6,LRO,VLAN_HWFILTER,VLAN_HWTSO,RXCSUM_IPV6,TXCSUM_IPV6>
	ether 0c:c4:7a:xx:xx:xx
	nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
	media: Ethernet autoselect (1000baseT <full-duplex>)
	status: active
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
	options=600003<RXCSUM,TXCSUM,RXCSUM_IPV6,TXCSUM_IPV6>
	inet6 ::1 prefixlen 128
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x6
	inet 127.0.0.1 netmask 0xff000000
	nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
	groups: lo
enc0: flags=0<> metric 0 mtu 1536
	nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
	groups: enc
pflog0: flags=100<PROMISC> metric 0 mtu 33160
	groups: pflog
pfsync0: flags=0<> metric 0 mtu 1500
	groups: pfsync
	syncpeer: 0.0.0.0 maxupd: 128 defer: off
lagg0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 
9000
	options=6507bb<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,TSO4,TSO6,LRO,VLAN_HWFILTER,VLAN_HWTSO,RXCSUM_IPV6,TXCSUM_IPV6>
	ether 0c:c4:7a:xx:xx:xx
	inet6 fe80::ec4:7aff:fe32:2784%lagg0 prefixlen 64 scopeid 0xe
	nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
	media: Ethernet autoselect
	status: active
	groups: lagg
	laggproto lacp lagghash l2,l3,l4
	laggport: igb0 flags=1c<ACTIVE,COLLECTING,DISTRIBUTING>
	laggport: igb1 flags=1c<ACTIVE,COLLECTING,DISTRIBUTING>
	laggport: igb2 flags=1c<ACTIVE,COLLECTING,DISTRIBUTING>
	laggport: igb3 flags=1c<ACTIVE,COLLECTING,DISTRIBUTING>
lagg0_vlan10: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 
0 mtu 1500
	options=303<RXCSUM,TXCSUM,TSO4,TSO6>
	ether 0c:c4:7a:xx:xx:xx
	inet6 fe80::ec4:7aff:fe32:2784%lagg0_vlan10 prefixlen 64 scopeid 0xf
	inet6 2001:xxx:xxx:xxx::1 prefixlen 64
	inet xxx.xxx.xxx.1 netmask 0xffffff00 broadcast xxx.xxx.xxx.255
	nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
	media: Ethernet autoselect
	status: active
	vlan: 10 vlanpcp: 0 parent interface: lagg0
	groups: vlan
lagg0_vlan20: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 
0 mtu 9000
	options=303<RXCSUM,TXCSUM,TSO4,TSO6>
	ether 0c:c4:7a:xx:xx:xx
	inet6 fe80::ec4:7aff:fe32:2784%lagg0_vlan20 prefixlen 64 scopeid 0x10
	inet6 2001:xxx:xxx:xxx::1 prefixlen 64
	inet xxx.xxx.xxx.1 netmask 0xffffff00 broadcast xxx.xxx.xxx.255
	nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
	media: Ethernet autoselect
	status: active
	vlan: 20 vlanpcp: 2 parent interface: lagg0
	groups: vlan
lagg0_vlan30: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 
0 mtu 1500
	options=303<RXCSUM,TXCSUM,TSO4,TSO6>
	ether 0c:c4:7a:xx:xx:xx
	inet6 fe80::ec4:7aff:fe32:2784%lagg0_vlan30 prefixlen 64 scopeid 0x11
	inet6 2001:xxx:xxx:xxx::1 prefixlen 64
	inet xxx.xxx.xxx.1 netmask 0xffffff00 broadcast xxx.xxx.xxx.255
	nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
	media: Ethernet autoselect
	status: active
	vlan: 30 vlanpcp: 0 parent interface: lagg0
	groups: vlan
lagg0_vlan40: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 
0 mtu 1500
	options=303<RXCSUM,TXCSUM,TSO4,TSO6>
	ether 0c:c4:7a:xx:xx:xx
	inet6 fe80::ec4:7aff:fe32:2784%lagg0_vlan40 prefixlen 64 scopeid 0x12
	inet6 2001:xxx:xxx:xxx::1 prefixlen 64
	inet xxx.xxx.xxx.1 netmask 0xffffff00 broadcast xxx.xxx.xxx.255
	nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
	media: Ethernet autoselect
	status: active
	vlan: 40 vlanpcp: 7 parent interface: lagg0
	groups: vlan
gif0: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> metric 0 mtu 1480
	options=80000<LINKSTATE>
	tunnel inet xxx.xxx.xxx.10 --> xxx.xxx.xxx.46
	inet6 2001:xxx:xxx:xxx::2 --> 2001:xxx:xxx:xxx::1  prefixlen 128
	inet6 fe80::222:6ff:feff:501%gif0 prefixlen 64 scopeid 0x13
	nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
	groups: gif
```
---
~ sjorge

**Comment by peppelinux** [comment]
Hi, I've tested on fresh installation of OPNsense, I also created vlans. 

![selezione_201](https://user-images.githubusercontent.com/1297620/35225955-112a790a-ff8a-11e7-8118-78c6e953c0c2.png)

This is my ifconfig output
````
vtnet0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=6d00b8<VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,VLAN_HWFILTER,VLAN_HWTSO,LINKSTATE,RXCSUM_IPV6,TXCSUM_IPV6>
	ether 08:00:27:71:b1:a2
	inet6 fe80::a00:27ff:fe71:b1a2%vtnet0 prefixlen 64 scopeid 0x1 
	inet 192.168.27.162 netmask 0xffffff00 broadcast 192.168.27.255 
	nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
	media: Ethernet 10Gbase-T <full-duplex>
	status: active
em0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=98<VLAN_MTU,VLAN_HWTAGGING,VLAN_HWCSUM>
	ether 08:00:27:83:65:91
	inet6 fe80::a00:27ff:fe83:6591%em0 prefixlen 64 scopeid 0x2 
	inet 10.0.3.254 netmask 0xffffff00 broadcast 10.0.3.255 
	nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
	media: Ethernet autoselect (1000baseT <full-duplex>)
	status: active
em1: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=98<VLAN_MTU,VLAN_HWTAGGING,VLAN_HWCSUM>
	ether 08:00:27:22:01:34
	inet6 fe80::a00:27ff:fe22:134%em1 prefixlen 64 scopeid 0x3 
	inet 192.168.7.254 netmask 0xffffff00 broadcast 192.168.7.255 
	nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
	media: Ethernet autoselect (1000baseT <full-duplex>)
	status: active
enc0: flags=0<> metric 0 mtu 1536
	nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
	groups: enc 
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
	options=600003<RXCSUM,TXCSUM,RXCSUM_IPV6,TXCSUM_IPV6>
	inet6 ::1 prefixlen 128 
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x5 
	inet 127.0.0.1 netmask 0xff000000 
	nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
	groups: lo 
pflog0: flags=100<PROMISC> metric 0 mtu 33160
	groups: pflog 
pfsync0: flags=0<> metric 0 mtu 1500
	groups: pfsync 
	syncpeer: 0.0.0.0 maxupd: 128 defer: off
ovpns1: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> metric 0 mtu 1500
	options=80000<LINKSTATE>
	inet6 fe80::a00:27ff:fe71:b1a2%ovpns1 prefixlen 64 scopeid 0x8 
	inet 10.17.0.1 --> 10.17.0.2  netmask 0xffffff00 
	nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
	groups: tun openvpn 
	Opened by PID 43604
em0_vlan3: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
	ether 08:00:27:83:65:91
	inet6 fe80::a00:27ff:fe83:6591%em0_vlan3 prefixlen 64 scopeid 0x9 
	nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
	media: Ethernet autoselect (1000baseT <full-duplex>)
	status: active
	vlan: 3 vlanpcp: 0 parent interface: em0
	groups: vlan 
vtnet0_vlan71: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
	ether 08:00:27:71:b1:a2
	inet6 fe80::a00:27ff:fe71:b1a2%vtnet0_vlan71 prefixlen 64 scopeid 0xa 
	nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
	media: Ethernet 10Gbase-T <full-duplex>
	status: active
	vlan: 71 vlanpcp: 0 parent interface: vtnet0
	groups: vlan 
em0_vlan11: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
	ether 08:00:27:83:65:91
	inet6 fe80::a00:27ff:fe83:6591%em0_vlan11 prefixlen 64 scopeid 0xb 
	nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
	media: Ethernet autoselect (1000baseT <full-duplex>)
	status: active
	vlan: 11 vlanpcp: 0 parent interface: em0
	groups: vlan 
em1_vlan12: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
	ether 08:00:27:22:01:34
	inet6 fe80::a00:27ff:fe22:134%em1_vlan12 prefixlen 64 scopeid 0xc 
	inet 10.1.2.251 netmask 0xffffff00 broadcast 10.1.2.255 
	nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
	media: Ethernet autoselect (1000baseT <full-duplex>)
	status: active
	vlan: 12 vlanpcp: 0 parent interface: em1
	groups: vlan 
````

this is script's output:
````
python2.7 test.py
[["vtnet0", "08:00:27:71:b1:a2", "192.168.27.162"], 
 ["em0", "08:00:27:83:65:91", "10.0.3.254"], 
 ["em1", "08:00:27:22:01:34", "192.168.7.254"], 
 ["em1_vlan12", "08:00:27:22:01:34", "10.1.2.251"]]

Excuse me if I ask the ifconfig output to you again, I need a precise formatting of the output (newlines and tabs must be respected) to test it.

Can you share this on a pastebin service or whatever?

````

**Comment by sjorge** [comment]
I'll try and pastbin it tonight when I am not on my phone,if I just run
IPtools.py I does give the wrong output for me. 

It seems to be chocking on the inet6 stuff, but fiddling on my phone is
not so easy.

---
~ sjorge 

On 2018-01-22 15:39, Giuseppe De Marco wrote:

> Hi, I've tested on fresh installation of OPNsense, I also created vlans. 
> 
> [1] 
> 
> This is my ifconfig output
> 
> vtnet0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
> options=6d00b8<VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,VLAN_HWFILTER,VLAN_HWTSO,LINKSTATE,RXCSUM_IPV6,TXCSUM_IPV6>
> ether 08:00:27:71:b1:a2
> inet6 fe80::a00:27ff:fe71:b1a2%vtnet0 prefixlen 64 scopeid 0x1 
> inet 192.168.27.162 netmask 0xffffff00 broadcast 192.168.27.255 
> nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
> media: Ethernet 10Gbase-T <full-duplex>
> status: active
> em0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
> options=98<VLAN_MTU,VLAN_HWTAGGING,VLAN_HWCSUM>
> ether 08:00:27:83:65:91
> inet6 fe80::a00:27ff:fe83:6591%em0 prefixlen 64 scopeid 0x2 
> inet 10.0.3.254 netmask 0xffffff00 broadcast 10.0.3.255 
> nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
> media: Ethernet autoselect (1000baseT <full-duplex>)
> status: active
> em1: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
> options=98<VLAN_MTU,VLAN_HWTAGGING,VLAN_HWCSUM>
> ether 08:00:27:22:01:34
> inet6 fe80::a00:27ff:fe22:134%em1 prefixlen 64 scopeid 0x3 
> inet 192.168.7.254 netmask 0xffffff00 broadcast 192.168.7.255 
> nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
> media: Ethernet autoselect (1000baseT <full-duplex>)
> status: active
> enc0: flags=0<> metric 0 mtu 1536
> nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
> groups: enc 
> lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
> options=600003<RXCSUM,TXCSUM,RXCSUM_IPV6,TXCSUM_IPV6>
> inet6 ::1 prefixlen 128 
> inet6 fe80::1%lo0 prefixlen 64 scopeid 0x5 
> inet 127.0.0.1 netmask 0xff000000 
> nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
> groups: lo 
> pflog0: flags=100<PROMISC> metric 0 mtu 33160
> groups: pflog 
> pfsync0: flags=0<> metric 0 mtu 1500
> groups: pfsync 
> syncpeer: 0.0.0.0 maxupd: 128 defer: off
> ovpns1: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> metric 0 mtu 1500
> options=80000<LINKSTATE>
> inet6 fe80::a00:27ff:fe71:b1a2%ovpns1 prefixlen 64 scopeid 0x8 
> inet 10.17.0.1 --> 10.17.0.2  netmask 0xffffff00 
> nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
> groups: tun openvpn 
> Opened by PID 43604
> em0_vlan3: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
> ether 08:00:27:83:65:91
> inet6 fe80::a00:27ff:fe83:6591%em0_vlan3 prefixlen 64 scopeid 0x9 
> nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
> media: Ethernet autoselect (1000baseT <full-duplex>)
> status: active
> vlan: 3 vlanpcp: 0 parent interface: em0
> groups: vlan 
> vtnet0_vlan71: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
> ether 08:00:27:71:b1:a2
> inet6 fe80::a00:27ff:fe71:b1a2%vtnet0_vlan71 prefixlen 64 scopeid 0xa 
> nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
> media: Ethernet 10Gbase-T <full-duplex>
> status: active
> vlan: 71 vlanpcp: 0 parent interface: vtnet0
> groups: vlan 
> em0_vlan11: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
> ether 08:00:27:83:65:91
> inet6 fe80::a00:27ff:fe83:6591%em0_vlan11 prefixlen 64 scopeid 0xb 
> nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
> media: Ethernet autoselect (1000baseT <full-duplex>)
> status: active
> vlan: 11 vlanpcp: 0 parent interface: em0
> groups: vlan 
> em1_vlan12: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
> ether 08:00:27:22:01:34
> inet6 fe80::a00:27ff:fe22:134%em1_vlan12 prefixlen 64 scopeid 0xc 
> inet 10.1.2.251 netmask 0xffffff00 broadcast 10.1.2.255 
> nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
> media: Ethernet autoselect (1000baseT <full-duplex>)
> status: active
> vlan: 12 vlanpcp: 0 parent interface: em1
> groups: vlan 
> 
> this is script's output:
> 
> python2.7 test.py
> [["vtnet0", "08:00:27:71:b1:a2", "192.168.27.162"], 
> ["em0", "08:00:27:83:65:91", "10.0.3.254"], 
> ["em1", "08:00:27:22:01:34", "192.168.7.254"], 
> ["em1_vlan12", "08:00:27:22:01:34", "10.1.2.251"]]
> 
> Excuse me if I ask the ifconfig output to you again, I need a precise formatting of the output (newlines and tabs must be respected) to test it.
> 
> Can you share this on a pastebin service or whatever?
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].
 

Links:
------
[1]
https://user-images.githubusercontent.com/1297620/35225955-112a790a-ff8a-11e7-8118-78c6e953c0c2.png
[2]
https://github.com/opnsense/plugins/issues/506#issuecomment-359442074
[3]

**Comment by peppelinux** [comment]
IPv6 doesn't use ARP. The equivalent is neighbour discovery, which is implemented with ICMPv6.

In OPNsense I used arp-scan for ipv4 arp scans BUT it won't work for ipv6.
For ipv6 we should develop another plugin.

@fabianfrz Please give us a revision on this assertion, thank you

**Comment by sjorge** [comment]
I was referring to the regex, it does not handle output with multiple
inet6 lines for the interface. Which seems to be why they are not
showing up.

---
~ sjorge 

On 2018-01-22 16:17, Giuseppe De Marco wrote:

> IPv6 doesn't use ARP. The equivalent is neighbour discovery, which is implemented with ICMPv6. 
> 
> In OPNsense I used arp-scan for ipv4 arp scans BUT it won't work for ipv6.
> For ipv6 we should develop another plugin. 
> 
> @fabianfrz [1] Please give us a revision on this assertion, thank you 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].
 

Links:
------
[1] https://github.com/fabianfrz
[2]
https://github.com/opnsense/plugins/issues/506#issuecomment-359454339
[3]

**Comment by sjorge** [comment]
https://gist.github.com/sjorge/e49edf7aa865c943e46e3b3e06d9c90f
This is just one of the interfaces enough to see the regex fail, the regex breaks down on line 5, if I remove ether one of the two lines beginning with inet6 the regex works.

**Comment by sjorge** [comment]
This works, but with a tiny change:
```
ifconfig_raw = subprocess.check_output(["ifconfig", "-u"]).decode()
ifconfig = '\n'.join([ i for i in ifconfig_raw.splitlines() if 'inet6' not in i])
```

ifconfig_raw.splitlines() instead of ifconfig.splitlines()

**Comment by peppelinux** [comment]
Ops, I should not made patch after the 5pm :)
Ok, I'm going to patch it this way, thank you very much

@fabianfrz leave this issue open for some days more, I'll reference this in the commit.

**Comment by peppelinux** [comment]
Fixed in PR: https://github.com/opnsense/plugins/pull/512
