### ISSUE TITLE
Feature Request: SNMP: integrate OSPF MIB into snmpd

### ISSUE THREAD

**Issue by cultcom** [opnsense/plugins#513]
To be able to check neighbour adjacencies the OSPF MIB should be integrated into SNMP.

OID tables like "1.3.6.1.2.1.14.10.1.6" are currently missing.

Maybe bsnmpd should be dropped over net-snmp which directly supports the "agentx" protocol defined in rfc 2741.

**Comment by mimugmail** [comment]
@cultcom have you tried new os-net-snmp plugin?

**Comment by mimugmail** [comment]
@cultcom are you able to test this?

**Comment by cultcom** [comment]
@mimugmail Yes, I am able to test it. But currently it is not running out of the box.

Quote from here: https://www.nongnu.org/quagga/docs/docs-multi/AgentX-configuration.html#AgentX-configuration
```
To enable AgentX protocol support, Quagga must have been build with the --enable-snmp or --enable-snmp=agentx option.
```

Is that given? I am not sure where to look for the activates flags.

**Comment by cultcom** [comment]
are you sure:
```
2018/11/13 14:20:20 OSPF: *** Error reading config: There is no such command.
2018/11/13 14:20:20 OSPF: *** Error occurred processing line 9, below:
agentx
```

**Comment by cultcom** [comment]
Where do I add " -M snmp" to ospfd ?

**Comment by mimugmail** [comment]
Can you post all the required steps as I have never used snmp with frr?
Or some full guide (not the official docs)?

I'm sadly a bit out of time digging into this topic ...

Thanks! :)

**Comment by cultcom** [comment]
All I have so far is this guide: https://github.com/FRRouting/frr/blob/master/doc/user/snmp.rst

frr needs 'loadable-module-support' and in this issue (https://github.com/FRRouting/frr/issues/970) I found a hint that the daemon should be started with "-M snmp".

Everything else is just a "master agentx" line in snmpd.conf. And a "agentx" lines in each frr daemon config file.

**Comment by ArmandoGalea** [comment]
help me https://github.com/imunes/imunes/issues/78

**Comment by fichtner** [comment]
SNMP was switched to net-snmp a while back...
