### ISSUE TITLE
Free radius Feature Request

### ISSUE THREAD

**Issue by rout3rx** [opnsense/plugins#520]
Hi, i was spoke with mimugmail in forum. 
as he says, there is some complexity for add this feature, i want to add Free-radius  functionality for all the VPN connections, can you guide me for researching and help you?
thanks

**Comment by rout3rx** [comment]
is there any plan to add this functionality? or is there any radius appliance for use for radius server?

**Comment by mimugmail** [comment]
@rout3rx with 18.7 you can use radius for openvpn and also assign IPs or set routes ..

**Comment by fichtner** [comment]
Close?

**Comment by mimugmail** [comment]
Yes, @rout3rx can reopen if missing something
