### ISSUE TITLE
intrusion- detection (Plugin)

### ISSUE THREAD

**Issue by b2410** [opnsense/plugins#524]
Hey,

OPNsense 17.7.12-amd64
FreeBSD 11.0-RELEASE-p17

Under "Services" I can activate intrusion detection and download rules. I have not installed any of the 3 plugins available.

Is the service still functional? Respectively, how do I activate all the rules which I already downloaded?

**Comment by fabianfrz** [comment]
IDS is not a plugin - it is a core component.

**Comment by b2410** [comment]
Thank you. I then confused that. Is there a button to activate all rules? Single clicking takes too long.

**Comment by fichtner** [comment]
@b2410 We can add the buttons, but we need a separate ticket in core. :)

Closing this as "plugin" question is answered.
