### ISSUE TITLE
HAPROXY stops working at 17.7.12

### ISSUE THREAD

**Issue by Julien-nl** [opnsense/plugins#525]
Hi Franky,
last year you've helped me to configure the haproxy for multiple http/https. however after we update the box to 17.7.12 we have noticed the https web servers are not working over the internet.
i have checked the value and everything is still there but the interface is a bit different as before.
somehow we can't get the haproxy started.
when i try to start it using the command line 
```
root@firewall:~ # service haproxy restart
haproxy not running? (check /var/run/haproxy.pid).
[ALERT] 026/234026 (48491) : parsing [/usr/local/etc/haproxy.conf:59] : 'tcp-request content accept' : error detected in frontend '443' while parsing 'if' condition : no such ACL : '{req_ssl_hello_type'
[ALERT] 026/234026 (48491) : parsing [/usr/local/etc/haproxy.conf:62] : unknown keyword 'tcp_request' in 'frontend' section
[ALERT] 026/234026 (48491) : Error(s) found in configuration file : /usr/local/etc/haproxy.conf
[ALERT] 026/234026 (48491) : Fatal errors found in configuration.
/usr/local/etc/rc.d/haproxy: WARNING: failed precmd routine for haproxy
root@firewall:~ #

**Comment by Julien-nl** [comment]
> Hi Franky,
> last year you've helped me to

 al

**Comment by fraenki** [comment]
https://github.com/opnsense/plugins/issues/526
