### ISSUE TITLE
os-arp-scan (Reloading template OPNsense/ARPscanner: Execute error)

### ISSUE THREAD

**Issue by itys** [opnsense/plugins#529]
18.1-amd64-OpenSSL

os-arp-scan Reports as "Action done"
even though.. 
Reloading template OPNsense/ARPscanner: Execute error

Full output below. 

> ***GOT REQUEST TO INSTALL: os-arp-scan***
> Updating OPNsense repository catalogue...
> OPNsense repository is up to date.
> All repositories are up to date.
> The following 2 package(s) will be affected (of 0 checked):
> 
> New packages to be INSTALLED:
> 	os-arp-scan: 1.0
> 	arp-scan: 1.9
> 
> Number of packages to be installed: 2
> 
> 307 KiB to be downloaded.
> [1/2] Fetching os-arp-scan-1.0.txz: .. done
> [2/2] Fetching arp-scan-1.9.txz: .......... done
> Checking integrity... done (0 conflicting)
> [1/2] Installing arp-scan-1.9...
> [1/2] Extracting arp-scan-1.9: .......... done
> [2/2] Installing os-arp-scan-1.0...
> Extracting os-arp-scan-1.0: .......... done
> Stopping configd...done
> Starting configd.
> Migrated OPNsense\ARPscanner\ARPscanner from 0.0.0 to 1.0.0
> Configuring system logging...done.
> Reloading template OPNsense/ARPscanner: Execute error
> Checking integrity... done (0 conflicting)
> Nothing to do.
> ***DONE***

**Comment by fichtner** [comment]
I think this was fixed via https://github.com/opnsense/plugins/issues/445 -- shipped in os-arp-scan 1.1 in OPNsense 18.1.1 :)
