### ISSUE TITLE
Regression: rules aren't loaded after upgrading from 17.7 to 18.1

### ISSUE THREAD

**Issue by whotwagner** [opnsense/plugins#530]
I upgraded OpnSense from 17.7.12 to 18.1. After the upgrade neither firewall rules nor nat was loaded properly. I found out that I had an invalid rule: Protocol: IPV4+IPV6 + ICMP
OpnSense 17.7 tolerated this rule, but 18.1 not. As soon as I deleted this rule, everything worked fine again.

**Comment by fichtner** [comment]
Try to set your ICMP rules to IPv4 only. It is something that seems to have changed in FreeBSD 11.0 -> 11.1 much to our surprise.

**Comment by whotwagner** [comment]
It works now after creating this rule with IPv4-only. I am afraid that other people might have this issue too.

**Comment by fichtner** [comment]
Likely. We need to identify (a) why this was not reported since testing FreeBSD 11.1 last two months and (b) identify the FreeBSD commit to see what it was supped to fix. I'll let others know about this. Thanks for confirming.
