### ISSUE TITLE
os-upnp: creates rdr rules beyond intended scope

### ISSUE THREAD

**Issue by gizahNL** [opnsense/plugins#534]
When setting up miniupnp to do nat-pmp on the wan interface it creates rules bound to that interface with any ip as destination.

```
pfctl -a miniupnpd -s nat
rdr pass log quick on pppoe0 inet proto tcp from any to any port = 62876 keep state label "Transmission at 62876" rtable 0 -> 10.0.1.10 port 62876
rdr pass log quick on pppoe0 inet proto udp from any to any port = 62876 keep state label "Transmission at 62876" rtable 0 -> 10.0.1.10 port 62876
```

This is unwanted, rdr rules should be limited in scope to the WAN IP adress, not /all/ public adresses routed over WAN interface!

To reproduce:
-set up os-upnp to allow nat-pmp
-set up client in network to request pmp (for example transmission)
-log into firewall via ssh and run command pfctl -a miniupnpd -s nat 

This is also true when override WAN Adress is set in configuration.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
