### ISSUE TITLE
Firewall: Settings: Advanced - 'Aliases Resolve Interval' not working

### ISSUE THREAD

**Issue by petererdos** [opnsense/plugins#542]
At least for host(s), the GUI feature is not triggering the resolver for any given values (for example, 60). A cron job is needed for FQDNs to be resolved (as a workaround).

OPNsense 18.1.1-amd64
FreeBSD 11.1-RELEASE-p6
LibreSSL 2.6.4

#

**Comment by fichtner** [comment]
@petererdos core issue, can you push to correct repo? :)

**Comment by petererdos** [comment]
Don't have git available right now, so I'll migrate this manually :)
Sorry, missed the repo when I added this.

**Comment by fichtner** [comment]
Thanks!
