### ISSUE TITLE
Request - SoftEther VPN Services

### ISSUE THREAD

**Issue by sempervictus** [opnsense/plugins#545]
SoftEther VPN is a multi-protocol session muxer which effectively creates overlay networks from multiple VPN connections over different protocols, with some advanced egress busting functionality, and support for all major platforms.
The suite consists of server, bridge, and client, providing L2 and L3 encapsulations for protocols like SSTP which are not available otherwise. I can't imagine this is trivial to implement, but it should provide significant coverage for client and mesh protocols, so may well be worth while.

**Comment by fichtner** [comment]
# pkg install softether

or

# pkg install softether-devel

**Comment by sempervictus** [comment]
@fichtner: I was thinking as an integrated component of the UI/API which handles all the VPN tasking instead if maintaining wholly separate server implementations for the protocols it supports.
