### ISSUE TITLE
Zabbix agent cannot be stopped, started, reloaded from web interface

### ISSUE THREAD

**Issue by thunfischbrot** [opnsense/plugins#551]
After installing and configuring the zabbix plugin connection attempts are rejected:
`root@zabbix:~# zabbix_get -s 10.0.0.1 -k agent.ping
zabbix_get [2925]: Check access restrictions in Zabbix agent configuration`
This is due to zabbix not reloading the configuration after saving and applying in the web interface. Also on the Dashboard it is not possible to actually stop and start the service despite the buttons being shown.

It is possible however to restart it from the shell, which immediately applies the configured changes:
![2018-02-08 19_21_03-clipboard-](https://user-images.githubusercontent.com/583358/35990761-72c92cf0-0d05-11e8-9277-82e6c35cbe8b.png)

**Comment by fraenki** [comment]
@thunfischbrot Thanks for your report! Which version of OPNsense and of os-zabbix-agent are you running?

**Comment by thunfischbrot** [comment]
I apologize for this omission, should have mentioned that they are all up-to-date:
`FreeBSD 11.1-RELEASE-p6  6621d681e(stable/18.1)
OPNsense 18.1.2-efa2c4f74 [18.1.1-a5575d7bd] LibreSSL 2.6.4 (amd64)
Plugins os-arp-scan-1.1 os-iperf-1.0 os-wol-1.0_1 os-zabbix-agent-1.2`

**Comment by fichtner** [comment]
FWIW, try to update. 18.1.2 had a buggy service handling and you want to double check on 18.1.2_2.

**Comment by thunfischbrot** [comment]
Just upgraded, still the same behaviour.

`User-Agent Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0
FreeBSD 11.1-RELEASE-p6  6621d681e(stable/18.1)
OPNsense 18.1.2_2-43d2878aa [18.1.2-efa2c4f74] LibreSSL 2.6.4 (amd64)
Plugins os-arp-scan-1.1 os-iperf-1.0 os-wol-1.0_1 os-zabbix-agent-1.2 `

![2018-02-09_10-37-48](https://user-images.githubusercontent.com/583358/36021199-530e54f0-0d85-11e8-84d3-a05e98fccd96.gif)

**Comment by nantoine555** [comment]
Hello, it's same with OPNsense 18.1.5-amd64 FreeBSD 11.1-RELEASE-p8 LibreSSL 2.6.4
I have to disable and re-enable the agent to restart it from the web interface

**Comment by fichtner** [comment]
Found and fixed, thanks for the video!
