### ISSUE TITLE
acme-client update

### ISSUE THREAD

**Issue by L1ghtn1ng** [opnsense/plugins#556]
Update acme-client to the new release to support the following new provider https://github.com/Neilpang/acme.sh/blob/master/dnsapi/dns_cloudns.sh and take care of #495 which is already supported

**Comment by fichtner** [comment]
https://github.com/Neilpang/acme.sh/releases/tag/2.7.6 was added a day ago. Not yet in FreeBSD.

**Comment by fichtner** [comment]
Will be in 18.1.3.

**Comment by fraenki** [comment]
@L1ghtn1ng Please note that this update will not automatically add support for dns_cloudns. I'v created #574 for this task.

@fichtner thx for taking care of this!

**Comment by EugenMayer** [comment]
@fichtner just tried wildcard certs with 18.1.4 with Cloudflare ( DNS challenge ) - did not work at all
