### ISSUE TITLE
freshclam log - day in wrong row!

### ISSUE THREAD

**Issue by opnsenseuser12123** [opnsense/plugins#559]
freshclam log - day in wrong row!

see attachement
![freshclam](https://user-images.githubusercontent.com/35663978/36074853-5c60511c-0f46-11e8-9eb1-6fcfef89ade8.JPG)

**Comment by fichtner** [comment]
Added a bit more tweaking to the log viewer while here... os-clamav 1.5 will be in OPNsense 18.1.3. Thanks!

**Comment by opnsenseuser12123** [comment]
Great...Thx for the fast response. Have a nice day!

Montag, 12. Februar 2018, 07:48 +0100 von notifications@github.com  <notifications@github.com>:
