### ISSUE TITLE
www/web-proxy-sso - No Bump Sites

### ISSUE THREAD

**Issue by AndyX90** [opnsense/plugins#560]
The configured No-Bump-Sites in Squid are getting ignored when Single-Sign-On is enabled.
After the plugin reconfigures the proxy, all sites get bumped, no matter what you have configured in ssl-no-bump-sites.

Would be great if this could be fixed, thanks.

**Comment by fichtner** [comment]
@AndyX90 thanks! :)

**Comment by evbevz** [comment]
@AndyX90 how do you conclude that no-bump sites ignored? I can not reproduce this on my installation. If I delete my proxy CA from client, and add some domains to no-bump-sites, then I can connect to no-bump-sites without security warnings. Is says that no-bump-sites option works right. SSO is enabled.

**Comment by AndyX90** [comment]
@evbevz Since i enabled sso, i can enter what i want in no-bump sites. Everything is replaced by my proxy-ca.

**Comment by evbevz** [comment]
![screen shot 2018-02-26 at 10 03 02](https://user-images.githubusercontent.com/8384497/36657117-675b61b4-1adc-11e8-9156-95fa2ef22621.png)
![screen shot 2018-02-26 at 10 03 15](https://user-images.githubusercontent.com/8384497/36657123-6eb01356-1adc-11e8-8364-90a5fe35ad36.png)

**Comment by AndyX90** [comment]
Sorry for the late reply. 
On my installation it doesn't work. If i configure for example "microsoft.com" in SSL no bump sites and i visit microsoft.com, the certificate is still being replaced by my proxy ca.
I have no clue..
The steps in squid.conf are:

# setup ssl bump acl's
acl bump_step1 at_step SslBump1
acl bump_step2 at_step SslBump2
acl bump_step3 at_step SslBump3
acl bump_nobumpsites ssl::server_name "/usr/local/etc/squid/nobumpsites.acl"

# configure bump
ssl_bump peek bump_step1 all
ssl_bump peek bump_step1 all
ssl_bump peek bump_step2 bump_nobumpsites
ssl_bump splice bump_step3 bump_nobumpsites
ssl_bump stare bump_step2
ssl_bump bump bump_step3

sslproxy_cert_error deny all

If i look in the nobumpsites.acl "microsoft.com" is included.

I have also reinstalled squid-package and deleted/recreated the proxy-ca.

**Comment by evbevz** [comment]
@AndyX90 , try to enter '.microsoft.com' (with dot at domain name start) to include all subdomains of microsoft.com to your no-bump-sites list.

**Comment by AndyX90** [comment]
@evbevz I have tested microsoft including subdomains and single websites. nothing seems to work :-(

**Comment by marcellinus77** [comment]
Hi
I just had a very similar issue: Configuring the SSL no bump sites to bypass Apple ITunes and Appstore Traffic, it was not correctly evaluating the traffic. However, adding a line to the conf:

squid.conf
>> ssl_bump splice bump_nobumpsites

```
# configure bump
ssl_bump peek bump_step1 all
**ssl_bump splice bump_nobumpsites**
ssl_bump peek bump_step2 bump_nobumpsites
ssl_bump splice bump_step3 bump_nobumpsites
ssl_bump stare bump_step2
ssl_bump bump bump_step3

sslproxy_cert_error deny all
```

made it work. Can someone kindly look into this issue and let me know of this is a bug and can be added to the configuration default instead of changing the config manually. Thanks.

Kr, Marcellinus

**Comment by peastone** [comment]
I had a similar situation with adding the URLs for Windows Updates to **SSL no bump** sites. Traffic interception and later analysis with Wireshark showed it still used my **CA to use**. Windows quitted with error 0x80240437.

Your hint acutally worked for me:
> 
> 
> Hi
> I just had a very similar issue: Configuring the SSL no bump sites to bypass Apple ITunes and Appstore Traffic, it was not correctly evaluating the traffic. However, adding a line to the conf:
> 
> squid.conf
> **ssl_bump splice bump_nobumpsites**
> 
> ```
> # configure bump
> ssl_bump splice bump_nobumpsites
> ssl_bump peek bump_step1 all
> ssl_bump peek bump_step2 bump_nobumpsites
> ssl_bump splice bump_step3 bump_nobumpsites
> ssl_bump stare bump_step2
> ssl_bump bump bump_step3
> 
> sslproxy_cert_error deny all
> ```
> 
> made it work. Can someone kindly look into this issue and let me know of this is a bug and can be added to the configuration default instead of changing the config manually. Thanks.
> 
> Kr, Marcellinus

Intutiveley, it makes sense for me to exclude **SSL no bump** sites as early as possible.
This said, I am not an expert using squid.

With http://www.squid-cache.org/Doc/config/ssl_bump/ I try to understand the original variant:

     ssl_bump peek bump_step1 all -> receive client certificate (preseverving possibility to splice)
     ssl_bump peek bump_step2 bump_nobumpsites -> receive server certificate (preseverving possibility to splice)
     ssl_bump splice bump_step3 bump_nobumpsites -> become TCP tunnel without decrypting traffice for bump_nobumpsites
     ssl_bump stare bump_step2 -> receive server certificate (preseverving possibility to bump)
     ssl_bump bump bump_step3 -> establishes a secure connection with the server and, using a mimicked server certificate, with the client

Does somebody understand, why splicing in the original variant did not work as expected?

Kind regards
peastone
