### ISSUE TITLE
REQUEST/QUESTION

### ISSUE THREAD

**Issue by jodumont** [opnsense/plugins#568]
as years ago
pfSense was offering a plain web daemon; if I remember well it was lighttpd.

I wondering if it is in the target of opnsense to offer this kind of daemon
or I should just focus on redirecting to an another machine with haproxy

I means lighttpd could be use for error page, maintenance page, static generator website, ...

and/or another subquestion
it is plan for opnsense to support PBIs or something similar ?
or it might worth it to consider running docker in a userspace non ?

**Comment by fabianfrz** [comment]
@jodumont docker is not an option - it is not stable on FreeBSD (at least the wiki said that when I have checked last time). lighttpd is already on board and nginx is in the repositories.

**Comment by jodumont** [comment]
I know I was silly with my docker request ;)
thanks for you kind answer
