### ISSUE TITLE
ClamAV - No signature database found

### ISSUE THREAD

**Issue by b2410** [opnsense/plugins#569]
hi,

OPNsense 18.1.2_2-amd64
FreeBSD 11.1-RELEASE-p6

The signatures are not downloaded. The system log says: "Check or install signatures".
I tried for hours.

**Comment by fichtner** [comment]
Can you check the database directory?

    # ls -lah /var/db/clamav

**Comment by b2410** [comment]
`# ls -lah /var/db/clamav`
`lrwxr-xr-x  1 root  wheel    19B Feb 27 10:06 /var/db/clamav -> /root/var/db/clamav`

**Comment by b2410** [comment]
@fichtner 
# ls -lah /var/db/clamav
lrwxr-xr-x 1 root wheel 19B Feb 27 10:06 /var/db/clamav -> /root/var/db/clamav

**Comment by b2410** [comment]
@fichtner 
`# ls -lah /var/db/clamav`
`lrwxr-xr-x 1 root wheel 19B Feb 27 10:06 /var/db/clamav -> /root/var/db/clamav`

**Comment by fichtner** [comment]
Ok, now these

    # ls -lah /var/db/clamav/
    # df -h

**Comment by b2410** [comment]
df -h
total 2
drwxr-x---  2 root  wheel   512B Jan  2 23:44 .
drwxr-xr-x  5 root  wheel   512B Jan 30 16:45 ..

df -h
Filesystem                Size    Used   Avail Capacity  Mounted on
/dev/ufs/OPNsense_Nano    7.5G    1.1G    5.8G    16%    /
devfs                     1.0K    1.0K      0B   100%    /dev
tmpfs                     2.3G    138M    2.2G     6%    /var
tmpfs                     2.2G    2.6M    2.2G     0%    /tmp
devfs                     1.0K    1.0K      0B   100%    /var/dhcpd/dev

**Comment by fichtner** [comment]
Ok, free space available. Does it tell you it’s fetching from the GUI?

**Comment by b2410** [comment]
It will be displayed. However, nothing happened.

**Comment by fichtner** [comment]
Would you mind sending a screenshot? Flying blind here.

**Comment by b2410** [comment]
After clicking on the download button, nothing happens anymore.

![unbenannt](https://user-images.githubusercontent.com/8990939/36902453-cbd23392-1e2a-11e8-959d-3a9a66fa0240.png)

**Comment by kekek2** [comment]
What show "Version" tab ?

**Comment by b2410** [comment]
![2](https://user-images.githubusercontent.com/8990939/36902920-6cb5cb38-1e2c-11e8-8008-8efcb9893535.png)

**Comment by kekek2** [comment]
Click "Enable Freshclam service" end "Enable ClamAV service" and then click "Aplay". After this check again signature bases.

**Comment by b2410** [comment]
Then nothing changes.

**Comment by mimugmail** [comment]
Your DNS resolution works?

Am 02.03.2018 15:18 schrieb "deleted" <notifications@github.com>:

Then nothing changes.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/opnsense/plugins/issues/569#issuecomment-369932405>,
or mute
the thread

**Comment by b2410** [comment]
I have not changed anything. I also get core updates.

**Comment by mimugmail** [comment]
@b2410 do you still have this issue?

**Comment by b2410** [comment]
Yes. I have just updated. The problem still exists.

**Comment by ezraholm50** [comment]
Same here, version 0.100.0

**Comment by ezraholm50** [comment]
```
root@opnsense:~ # freshclam
WARNING: Ignoring deprecated option AllowSupplementaryGroups at line 10
Thu Jul 12 13:46:14 2018 -> ClamAV update process started at Thu Jul 12 13:46:14 2018
Thu Jul 12 13:46:15 2018 -> ^Your ClamAV installation is OUTDATED!
Thu Jul 12 13:46:15 2018 -> ^Local version: 0.100.0 Recommended version: 0.100.1
Thu Jul 12 13:46:15 2018 -> DON'T PANIC! Read https://www.clamav.net/documents/upgrading-clamav
Thu Jul 12 13:46:22 2018 -> Downloading main.cvd [100%]

```

**Comment by macmenco** [comment]
The problem is in the rights on /root/var/db/clamav when /var is in ram. Changing ownership and rights on the link aren't set on the destination (/root/var/db/clamav). Changing these fixes the freshclam.

**Comment by fichtner** [comment]
@macmenco many thanks for the analysis... 1f96ba0 should fix it finally.

@mimugmail can you double check that I haven't broken anything?

**Comment by fichtner** [comment]
PS: ❤️

**Comment by mimugmail** [comment]
Unsure about the removing of exit 0 from stop, but removing db's and reinstallation worked, also reload via  UI, so it should be good to go.

**Comment by fichtner** [comment]
stop should not mask exit value, likely caused by a bug (stopping when not started). in this case it's ok to error (to log)

**Comment by simplove** [comment]
> ```
> root@opnsense:~ # chown -R clamav /var/db/clamav/
> root@opnsense:~ # freshclam
> WARNING: Ignoring deprecated option AllowSupplementaryGroups at line 10
> Thu Jul 12 13:46:14 2018 -> ClamAV update process started at Thu Jul 12 13:46:14 2018
> Thu Jul 12 13:46:15 2018 -> ^Your ClamAV installation is OUTDATED!
> Thu Jul 12 13:46:15 2018 -> ^Local version: 0.100.0 Recommended version: 0.100.1
> Thu Jul 12 13:46:15 2018 -> DON'T PANIC! Read https://www.clamav.net/documents/upgrading-clamav
> Thu Jul 12 13:46:22 2018 -> Downloading main.cvd [100%]
> ```
> 
> So it seems to be a permission issue, I'd like to see an official patch for this if the dev is up for it.


 chown -R clamav /var/db/clamav/
root@OPNsense:/var/db/clamav # freshclam
ClamAV update process started at Fri Jul 12 09:46:02 2024
daily database available for download (remote version: 27333)
Time:    8.6s, ETA:    0.0s [========================>]   60.91MB
Testing database: '/var/db/clamav/tmp.958be58da5/clamav-74a03610a5b02d4b2d28c69074ed5063.tmp-daily.cvd' ...
Database test passed.
daily.cvd updated (version: 27333, sigs: 2064131, f-level: 90, builder: raynman)
main database available for download (remote version: 62)
Time:   15.7s, ETA:    0.0s [========================>]  162.58MB
Testing database: '/var/db/clamav/tmp.958be58da5/clamav-6fe9c157205500cbccfa54f0d6780346.tmp-main.cvd' ...
Database test passed.
main.cvd updated (version: 62, sigs: 6647427, f-level: 90, builder: sigmgr)
bytecode database available for download (remote version: 335)
Time:    1.6s, ETA:    0.0s [========================>]  282.94KB
Testing database: '/var/db/clamav/tmp.958be58da5/clamav-3c1360f32f596fa51c7ca05647fd4698.tmp-bytecode.cvd' ...
Database test passed.
bytecode.cvd updated (version: 335, sigs: 86, f-level: 90, builder: raynman)

it's working 
thanks
