### ISSUE TITLE
IDS/Log file ERROR

### ISSUE THREAD

**Issue by itn3rd77** [opnsense/plugins#577]
Hi,

since the new "Log File" feature is available in the "Intrutions Detection" menu I recognized the following errors occur every night. 

```
3/3/2018 -- 03:42:40 | - <Error> - [ERRCODE: SC_ERR_UNDEFINED_VAR(101)] - Variable "DC_SERVERS" is not defined in configuration file
-- | --
3/3/2018 -- 03:42:40 | - <Error> - [ERRCODE: SC_ERR_INVALID_SIGNATURE(39)] - error  parsing signature "drop tcp !$DC_SERVERS any -> $DC_SERVERS [1024:]  (msg: "[PT OPEN] DCShadow Replication Attempt - DRSUAPI_REPLICA_ADD from  non-DC"; flow: established, to_server, no_stream; content: "\|05 00 00  03\|"; depth: 4; content: "\|05 00\|"; distance: 18; within: 2; flowbits:  isset, RPC.Bind.DRSUAPI; reference: url,  blog.alsid.eu/dcshadow-explained-4510f52fc19d; classtype:  attempted-admin; sid: 10002558; rev: 1; ) " from file  /usr/local/etc/suricata/opnsense.rules/pt.research.rules at line 199
```

Is this my fault or an error from the plugin?

Regards
Ingo

**Comment by AdSchellevis** [comment]
Hi Ingo,

It's not really your fault and not the plugins either it seems, you enabled the pt-research rules and they seem to have added a variable which doesn't exist by default.

https://github.com/ptresearch/AttackDetection/blob/cd2cd9273080414ac829932153e1885d4214829c/dcshadow/dcshadow.rules

https://github.com/ptresearch/AttackDetection/blob/34de3799832bbcc60e8bdb82b885851d9eb08702/wannamine/wannamine.rules

Easiest fix is to disable those rules, I'm not sure what content they expect in that variable (couldn't find it anywhere).

Best regards,

Ad

**Comment by itn3rd77** [comment]
Hi Ad,

found this ticket [handling missing variables](https://redmine.openinfosecfoundation.org/issues/2449). Any glue what has to be added to suricata.yaml?

```
At least one rule is using the DC_SERVERS address-group variable
which is not defined in your configuration. Please consider adding
it to your suricata.yaml.
```

Regards
Ingo

**Comment by AdSchellevis** [comment]
Hi Ingo,

I found the same ticket online, but I have no clue what DC_SERVERS should contain.
Disabling those rules is probably the easiest thing todo for now.

Regards,

Ad

**Comment by mimugmail** [comment]
https://twitter.com/AttackDetection/status/971057663709794306?s=19
