### ISSUE TITLE
Feature Request: BGP IPv6

### ISSUE THREAD

**Issue by galphanet** [opnsense/plugins#578]
The routing plugin with BGP IPv4 support is great (I'm using it, it is stable and working as expected), thanks for adding the routing plugin.

I would need IPv6 BGP support to announce my IPv6 range, it that possible ?

If not, can you point me to a solution to manually edit the quagga files without being overwritten by the GUI ?

**Comment by fabianfrz** [comment]
ping @mimugmail

**Comment by mimugmail** [comment]
It's on my list for ages, sorry :(
I'll try to add it next week.

**Comment by galphanet** [comment]
Thanks ! Let me know if I can be a beta-tester or of any help.

**Comment by mimugmail** [comment]
I'm just thinking what would be better, add a v6 address field to every neighbor or allow only v4 or v6 for every entry.

**Comment by galphanet** [comment]
I think the IPv6 and IPv4 neighbours shouldn't be mixed: in some case we have only IPv6 or only IPv4 neighbor.
What I was expecting while trying to configure IPv6 BGP was:
1. Add the IPv6 prefix to the network list
2. Add a prefix-list 
3. Add an IPv6 neighbor
4. Apply the configuration and in Diagnostic-> General -> Running configuration find under "address-family ipv6" the IPv6 configuration.

Side note: I was confused about "BGPv4" term instead of simply "BGP". I know it is the protocol version but there is no other version in use today and I was asking myself (is it only for IPv4 OR is the BGP protocol version ?)

**Comment by fabianfrz** [comment]
@mimugmail 
{%if ':' in variable %} should work for IPv6 detection.

**Comment by mimugmail** [comment]
Nice, thanks! I'll give it a try

**Comment by galphanet** [comment]
The config example seems OK for me!

**Comment by mimugmail** [comment]
Can you try on a test system:

opnsense-patch -c plugins 83eb2bf

Perhaps you get an error regarding makefile but it should work. If it works for you this can go to 18.1.5 or 18.1.6

**Comment by galphanet** [comment]
I've tested it, thanks!
The UI is working as expected but there is no configuration file generated (empty).

How can I debug it?

**Comment by mimugmail** [comment]
Do you still have this issue? Does a reboot solve it? You can check the files and permissions of /usr/local/etc/frr and do a vtysh via console to check the running config.

Oh .. do you use EoL'd Quagga plugin or FRR? Changes were only made to FRR

**Comment by galphanet** [comment]
Reboot doesn't change, removing IPv6 configuration neither, I use FRR.
So my version is `OPNsense 18.1.2_2-amd64`, `quagga 1.2.2_1` 
`root@gw:~ # ls -la /usr/local/etc/fr
ls: /usr/local/etc/fr: No such file or directory`

`root@gw:~ # vtysh

Hello, this is Quagga (version 1.2.2).
Copyright 1996-2005 Kunihiro Ishiguro, et al.

gw.test.local# sh run
Building configuration...

Current configuration:
!
log file /var/log/quagga.log warnings
!
interface enc0
!
interface lo0
!
interface ovpns1
!
interface ovpns2
!
interface ovpns3
!
interface pflog0
!
interface pfsync0
!
interface vtnet0
!
interface vtnet1
!
interface vtnet2
!
ip forwarding
ipv6 forwarding
!
line vty
!
end`

I'm trying to update to 18.1.3 right now.

**Comment by galphanet** [comment]
You know what ? You're right I was still using quagga. I've upgraded to frr and to 18.1.4, the BGP config file is ok with your patch.
My IPv6 sessions aren't coming up right now (stays in Active/Idle) but this is not related to this patch.
Therefore I think it is ready, many thanks !

**Comment by mimugmail** [comment]
Hm, isn't it possible for you to test with a real neighbor? Since the template was completely rewritten for address-families this is more than a small changeset.

**Comment by galphanet** [comment]
Sure, I'll try with a Cisco ASR and a Juniper MX.

**Comment by mimugmail** [comment]
This would be perfect. I'll wait for your feedback

**Comment by galphanet** [comment]
I have no success to establish the IPv6 BGP session with neither Cisco or Juniper.
`# sh ip bgp sum` shows ipv6 and ipv4 sessions but only ipv4 are up.
`# sh bgp ipv6 sum` doesn't report any neighbors.
Can I suggest to add `no neighbor 2a04:xxxx:yyyy:zzzz:916::1 activate` under the IPv4 address-family ?

For your reference, here is the configuration generated:
`router bgp xxxxxx
 neighbor 185.xxx.xxx.49 remote-as yyyy
 neighbor 185.xxx.xxx.49 update-source vtnet1
 neighbor 185.xxx.xxx.50 remote-as yyyy
 neighbor 185.xxx.xxx.50 update-source vtnet1
 neighbor 185.xxx.xxx.65 remote-as zzzz
 neighbor 185.xxx.xxx.65 update-source vtnet2
 neighbor 2a03:xxx.xxx::2d remote-as zzzz
 neighbor 2a03:xxx.xxx::2d update-source vtnet2
 neighbor 2a04:xxx.xxx:916::1 remote-as yyyy
 neighbor 2a04:xxx.xxx:916::1 update-source vtnet1
 neighbor 2a04:xxx.xxx:916::2 remote-as yyyy
 neighbor 2a04:xxx.xxx:916::2 update-source vtnet1
 !
 address-family ipv4 unicast
  network 185.xxx.xxx.0/24
  redistribute static
  neighbor 185.xxx.xxx.49 next-hop-self
  neighbor 185.xxx.xxx.49 prefix-list announce-v4-out out
  neighbor 185.xxx.xxx.50 next-hop-self
  neighbor 185.xxx.xxx.50 prefix-list announce-v4-out out
  neighbor 185.xxx.xxx.65 next-hop-self
  neighbor 185.xxx.xxx.65 prefix-list announce-v4-out out
 exit-address-family
 !
 address-family ipv6 unicast
  network 2001:xxx.xxx::/48
  redistribute static
  neighbor 2a03:xxx.xxx:6:1::2d next-hop-self
  neighbor 2a03:xxx.xxx:6:1::2d prefix-list announce-v6-out out
  neighbor 2a04:xxx.xxx:916::1 next-hop-self
  neighbor 2a04:xxx.xxx:916::1 prefix-list announce-v6-out out
  neighbor 2a04:xxx.xxx:916::2 next-hop-self
  neighbor 2a04:xxx.xxx:916::2 prefix-list announce-v6-out out
 exit-address-family
 vnc defaults
  response-lifetime 3600
  exit-vnc
!
ip prefix-list announce-v4-out seq 10 permit 185.xxx.xxx.0/24
ip prefix-list announce-v4-out seq 15 deny 0.0.0.0/0
!
ipv6 prefix-list announce-v6-out seq 10 permit 2001:xxx.xxx::/48
ipv6 prefix-list announce-v6-out seq 15 deny ::/0
`

**Comment by mimugmail** [comment]
Or better add activate to both address-families?

**Comment by galphanet** [comment]
Sorry, I don't understand. Can you give me a config example of what you mean ?

**Comment by mimugmail** [comment]
My Quagga live config has for every neighbor, no matter if v4 or v6 the line:

 `neighbor 2001:XX::c81 activate`

I would not use "no" since when the neighbor is disabled it wont appear in the config et all

**Comment by galphanet** [comment]
OK now I understand. However, I think you should add `no neighbor 2a04:xxxx:yyyy:zzzz:916::1 activate` for the IPv6 neigbors under the ` address-family ipv4 unicast` because my understanding is it will try to establish the session from the IPv4, which is useless.
From what I remember, IPv6 neighors can announce IPv4 prefix but not on the other way.

**Comment by galphanet** [comment]
Ok so I modified manually the configuration and it works like that (BGP session came up with the Juniper router):

> router bgp xxxxxx
> neighbor 185.xxx.xxx.49 remote-as yyyy
> neighbor 185.xxx.xxx.49 update-source vtnet1
> neighbor 185.xxx.xxx.50 remote-as yyyy
> neighbor 185.xxx.xxx.50 update-source vtnet1
> neighbor 185.xxx.xxx.65 remote-as zzzz
> neighbor 185.xxx.xxx.65 update-source vtnet2
> neighbor 2a03:xxx.xxx::2d remote-as zzzz
> neighbor 2a03:xxx.xxx::2d update-source vtnet2
> neighbor 2a04:xxx.xxx:916::1 remote-as yyyy
> neighbor 2a04:xxx.xxx:916::1 update-source vtnet1
> neighbor 2a04:xxx.xxx:916::2 remote-as yyyy
> neighbor 2a04:xxx.xxx:916::2 update-source vtnet1
 !
> address-family ipv4 unicast
>  network 185.xxx.xxx.0/24
>  redistribute static
>  neighbor 185.xxx.xxx.49 next-hop-self
>  neighbor 185.xxx.xxx.49 prefix-list announce-v4-out out
>  neighbor 185.xxx.xxx.50 next-hop-self
>  neighbor 185.xxx.xxx.50 prefix-list announce-v4-out out
>  neighbor 185.xxx.xxx.65 next-hop-self
>  neighbor 185.xxx.xxx.65 prefix-list announce-v4-out out
>  no neighbor 2a03:xxx.xxx:6:1::2d activate
>  no neighbor 2a04:xxx.xxx:916::1 activate
>  no neighbor 2a04:xxx.xxx:916::2 activate
> exit-address-family
> !
> address-family ipv6 unicast
>  network 2001:xxx.xxx::/48
>  redistribute static
>  neighbor 2a03:xxx.xxx:6:1::2d activate
>  neighbor 2a03:xxx.xxx:6:1::2d next-hop-self
>  neighbor 2a03:xxx.xxx:6:1::2d prefix-list announce-v6-out out
>  neighbor 2a04:xxx.xxx:916::1 activate
>  neighbor 2a04:xxx.xxx:916::1 next-hop-self
>  neighbor 2a04:xxx.xxx:916::1 prefix-list announce-v6-out out
>  neighbor 2a04:xxx.xxx:916::2 activate
>  neighbor 2a04:xxx.xxx:916::2 next-hop-self
>  neighbor 2a04:xxx.xxx:916::2 prefix-list announce-v6-out out
> exit-address-family
> vnc defaults
>  response-lifetime 3600
>  exit-vnc
>!
> ip prefix-list announce-v4-out seq 10 permit 185.xxx.xxx.0/24
> ip prefix-list announce-v4-out seq 15 deny 0.0.0.0/0
>!
> ipv6 prefix-list announce-v6-out seq 10 permit 2001:xxx.xxx::/48
> ipv6 prefix-list announce-v6-out seq 15 deny ::/0

**Comment by mimugmail** [comment]
Great, can you also please verify if it works when you don't use the no and only the activate lines in v6?

**Comment by galphanet** [comment]
Yes it works also BUT when I run `sh ip bgp sum` I see the IPv6 neighors in "Open/Connect" state and that's not very beautiful... :)

**Comment by mimugmail** [comment]
Hmpf, OK tomorrow some new for loops in the template. Thanks for testing

**Comment by mimugmail** [comment]
@galphanet 

opnsense-patch -c plugins 699f1f2

Should do the trick ..

**Comment by galphanet** [comment]
Yes it works !
Thanks again for your time, greatly appreciated.

**Comment by fichtner** [comment]
glad to hear, thanks guys 👍

**Comment by mimugmail** [comment]
@fichtner This can now also go to 18.1.6

**Comment by mimugmail** [comment]
Long overdue addition :/

**Comment by fichtner** [comment]
Converted service control while at it, please give it a brief test: 01734be02c43e3ff1b884f2a3277db22963b98e9 1126957fb83e057456c4690a898b8a4cef44e2bb

**Comment by mimugmail** [comment]
Worked for me ...
