### ISSUE TITLE
Monit does not update

### ISSUE THREAD

**Issue by tpcr** [opnsense/plugins#583]
Since update today to Monit 1.5 new or changed settings do not work as expected.
Also email notifications are not consistent. The 'Test Configuration' button does not work consistently.
Clicking the 'Reload Configuration' button does not reinitialize the status.

Monit also shows control issues on one of the boxes. Shows
'/usr/local/etc/monitrc:17: syntax error 'failed'' when testing the configuration. Tried to reinstall Monit with no success. 

Non of these issues existed yesterday.

**Comment by fichtner** [comment]
This should help for now:

    # opnsense-revert -r 18.1.2 os-monit

**Comment by tpcr** [comment]
Definitely an issue with 1.5. All works with 1.4.
One thing I noticed is the Apply button in the General Settings does not do anything with 1.5
With 1.4 the circle spins and changes are made to /etc/monitrc

**Comment by fbrendel** [comment]
> /usr/local/etc/monitrc:17: syntax error 'failed'

@tpcr you have an error in your 'Service Test Settings' that probably wasn't detected before 1.5
Could you post the lines 15 to 19 from your monitrc?

> One thing I noticed is the Apply button in the General Settings does not do anything in version 1.5

The behavior has changed slightly.
The Apply button does exactly what it's name say: "Apply the changes to the config" and not more.
In 1.4 it also reloads the service. This took some time and that's why you saw the spinner.

@fichtner I think we need a better feedback here. Maybe a status line "Your config has changed. Please click Apply and reload the service" which disappears after clicking Apply/Reload?

**Comment by fichtner** [comment]
I'll import monit plugin to base and take a look this week. All pages apply + reload/restart, maybe if restart takes to long we can get away with a reload?

**Comment by fbrendel** [comment]
No, it already reloads. :smirk: 
The problem was that the tables apply the config via dialog boxes. And the 'General Settings' via Apply button.
This was inconsistent since after editing tables you had to click on Reload.
Editing 'General Settings' only Apply was needed.

**Comment by tpcr** [comment]
Here is the monitrc file
`# DO NOT EDIT THIS FILE -- OPNsense auto-generated file
set httpd unixsocket /var/run/monit.sock
    allow localhost
set daemon 60 with start delay 30

set logfile syslog facility log_daemon

set mailserver 192.168.10.24 port 2525 username me@here.com password "xxxxxxxx" 

set alert me@here.com  { action,resource,status } mail-format { from: me@here.com } reminder on 10 cycles

check system $HOST
   if failed link then alert   # This is line 17 #
   if memory usage is greater than 25% then alert 
   if cpu usage is greater than 25% then alert 

check filesystem RootFs with path /
   if space usage is greater than 50% then alert 

check program CPUtemp with path /usr/local/bin/CheckCPUTemp.sh
   if status notequal 0 then alert 
`

**Comment by tpcr** [comment]
Monit has been uninstalled from the box with the issue, but the /etc/monitrc file is still there.
Monit 1.5 has been downgraded on the other boxes to version 1.4. With 1.5 installed it did not send notifications.
It acts as though it is getting the wrong monitrc file in version 1.5.
Also, one other thing I noticed in Monit. When email 'Secure Connection' is enabled, it forces SSL and not STARTTLS, so when you import the configuration from notifications and STARTTLS was used, it does not use the same Secure Connection in Monit. Which is why I think I get no notifications in version 1.5. Once I Imported the config from notifications, it stored the info in the 'ghost' monitrc and uses that instead of the actual one. Making changes in Monit has no affect on /etc/monitrc in the box with the issue.

**Comment by tpcr** [comment]
For more in depth info. When I first used monit 1.5, I made a change to the 'Service Tests Settings' condition on one of the entries to test. I changed the memory usage to invoke a trigger. I may have entered a wrong value which initially caused the error. But I was never able to correct it. The monitrc file made the change back, but monit would never start after that with the error I caused in the initial test.

So maybe a good test is to create a condition error on purpose and see if you can get rid of it.

**Comment by fbrendel** [comment]
> check system $HOST
if failed link then alert # This is line 17 #
if memory usage is greater than 25% then alert
if cpu usage is greater than 25% then alert

'failed link' is a network interface test and you have it linked to the system test.
see [Monit Network Interface Tests](https://mmonit.com/monit/documentation/monit.html#NETWORK-INTERFACE-TESTS)



> Monit has been uninstalled from the box with the issue, but the /etc/monitrc file is still there.

Really **/etc/monitrc** ?
This could cause your trouble. Because:
> Monit is configured and controlled via a control file called monitrc. The default location for this file is ~/.monitrc. If this file does not exist, Monit will try /etc/monitrc, then @sysconfdir@/monitrc and finally ./monitrc. ...

The plugin uses only /usr/local/etc/monitrc.


> Also, one other thing I noticed in Monit. When email 'Secure Connection' is enabled, it forces SSL and not STARTTLS, so when you import the configuration from notifications and STARTTLS was used, it does not use the same Secure Connection in Monit. Which is why I think I get no notifications in version 1.5

As far as I know Monit doesn't support STARTTLS for alerts. The notification import enables the SSL instead because most mail servers which support STARTTLS support SSL too.

> I believe that the service is pulling the data from somewhere other than /usr/local/etc/monitrc

I guess from /etc/monitrc. :smirk:

**Comment by tpcr** [comment]
Thanks, the Network link was the issue. Error went away as soon as I removed it and reloaded it.
The lack of documentation for this plug-in is so sparse I had no way to know where the Network link should have gone.

Also the way that the Apply button works is different and is misleading as to what it really does now.

The Monit install does not create monitrc at ~/ on my systems. The only place it exists is in /usr/local/etc.

The only reason I bring up the STARTTLS issue is because when importing from notifications, SSL does not exist so if the email server is setup to receive only STARTTLS, for whatever reason, it will not work in Monit. The GUI should have a warning when importing the secure connection since notifications and Monit use different methods. Don't assume every email server accepts both.

Thanks for clearing this up. I will close this issue.

**Comment by fbrendel** [comment]
>The lack of documentation for this plug-in is so sparse ...

A good starting point is the [Monit Mini Howto](https://forum.opnsense.org/index.php?topic=5303.0)
And then the [Monit Documentation](https://mmonit.com/monit/documentation/monit.html) itself.

**Comment by tpcr** [comment]
Read those, no explanation on what all the services tests are and how to use them. Which is what got me in trouble in the first place. Also no docs on setting up custom tests. What is the syntax for using conditions with a custom script? Docs are sparse and expect many issues if users like me dive into Monit.

For example, what conditions do I use for Network Saturation or Network link and do these only work with Type ' Network'? Do I need a specific name for a service or can I use anything?

**Comment by fbrendel** [comment]
Services are all things you can monitor: system, programs, filesystems or network interfaces just to name a few.
Possible service tests are listed in the SERVICE TESTS section of the Monit documentation.

But you have to define conditions at which you want to have an alert or other actions like restart, unmonitor etc.
These conditions are service specific. The system cannot have a failed link. It can have an overloaded CPU for example.
But a network interface test can check the link.
The NETWORK SERVICE TEST section describes all tests you can do on a network interface.

Example step by step:
What to monitor? Network Link.
Which condition? Link is down, i.e. failed.
What to do? Try to bring it up again.

First create a test:
**Name**: _NetworkLinkRestart_   <- choose a name of your choice
**Condition**: _failed link_ <- see Monit Documentation
**Action**: _Restart_

Now you can reuse this test on any network service check.

Then a service:
**Name**: _Iface_OPT1_ <- freely selectable, I add the interface name to see which one failed (see Interfaces->Assignments)
**Type**: _Network_
**Address**: <- leave it empty, we are not interested in addresses
**Interface**: _OPT1_ <- the interface to monitor
**Start**: _/etc/rc.d/netif start vtnet1_ <- vtnet1 is OPT1 see assignments
**Stop**: _/etc/rc.d/netif stop vtnet1_
**Test**: _NetworkLinkRestart_ <- the test created above

Create a service for all your interfaces with the same test.

Same with saturation (your networkcard must support it):
Test:
**Name**: _Saturation90_
**Condition**: _saturation greater 90%_
**Action**: _Alert_

Service:
**Name**: _Iface_OPT1_90_
**Type**: _Network_
**Interface**: _OPT1_
**Test**: _Saturation90_
Start/Stop is not needed since the test creates only alerts.

**Comment by tpcr** [comment]
That was a GREAT help. Thank you.
Now what about a custom test. I have created a script to check CPU temps.
How can I add a condition that has the temp value to check
ie. Condition -  "CPU temp greater than 60 degrees"
here is my script
`#!/bin/csh

set MaxCPUTemp = 60
set status = 0
set NumCPUs = `sysctl -n kern.smp.cpus`
set CurrentCPU = 0

while ( $CurrentCPU < $NumCPUs )
   set CPUTemp = `sysctl dev.cpu.$CurrentCPU.temperature | awk '{print $2}' | awk -F. '{print $1}'`
   echo "CPU $CurrentCPU temp: $CPUTemp"
   if ( $CPUTemp >= $MaxCPUTemp ) then
   exit 1
   endif
   @ CurrentCPU = $CurrentCPU + 1
end
exit 0`

**Comment by fbrendel** [comment]
> What can I add to a script that passes a variable/value to the script?

Usually as parameter.
But now I see the plugin doesn't allow that. It's a bug. :worried: 

Anyway the [PROGRAM STATUS TEST](https://mmonit.com/monit/documentation/monit.html#PROGRAM-STATUS-TEST) section says that you can test the exit code only.
Therefore let the script exit with the CPU temperature and create a test with condition 'status greater 60'.
Then create a custom service for each CPU and a script for each CPU as workaround for the bug.
After the fix you can use a single script and provide the CPU number as parameter.

```shell
#!/bin/csh

#set CPU = $1
set CPU = 0
set CPUTemp = sysctl dev.cpu.$CPU.temperature | awk '{print $2}' | awk -F. '{print $1}'
echo "CPU$CPU temp: $CPUTemp"
exit $CPUTemp
```

**Comment by fbrendel** [comment]
> Setting the Network Link action to restart, will that run the start/stop commands, or restart OPNsense?

it runs the Start/Stop commands

**Comment by tpcr** [comment]
I simplified the script because I got an error. Getting the same error.
Here is the script I used
```
#!/bin/csh

set CPUTemp = sysctl dev.cpu.0.temperature | awk '{print $2}' | awk -F. '{print $1}'
echo "CPU0 temp: $CPUTemp"
exit $CPUTemp

```

**Comment by fbrendel** [comment]
Yes, was a quick hack, not tested.
But I see you got the idea :smiley: 

And with the fix of #585 you need only one script with the CPU number as parameter.

**Comment by tpcr** [comment]
Excellent. Let me know when fix is ready and I will test it.

**Comment by fbrendel** [comment]
@tpcr the bug was fixed in #587

**Comment by tpcr** [comment]
I did make the changes and used the following script, which seems to work using a condition - "status greater 1. I could not use $CPUTemp as the exit code.
```
#!/bin/csh

set MaxCPUTemp = 60
set NumCPUs = `sysctl -n kern.smp.cpus`
set CurrentCPU = 0

while ( $CurrentCPU < $NumCPUs )
   set CPUTemp = `sysctl dev.cpu.$CurrentCPU.temperature | awk '{print $2}' | awk -F. '{print $1}'`
   echo "CPU $CurrentCPU temp: $CPUTemp"
   if ( $CPUTemp >= $MaxCPUTemp ) then
   exit 1
   endif
   @ CurrentCPU = $CurrentCPU + 1
end
exit 0
```

**Comment by fbrendel** [comment]
Why not?

**Comment by tpcr** [comment]
I get a unrecognized variable as the Last Exit Value

**Comment by fbrendel** [comment]
And why do you changed the script? :confused: 
You do not need more than these 6 lines.

**Comment by tpcr** [comment]
I was just pointing out that I did not get a value returned when using
exit $CPUTemp as I did with the previous script that only checked CPU 0.

I am happy with the new script as it sends a notification with the temp of the failing CPU from the echo command. But I would prefer a script that was controlled by the condition statement instead of having to hard code the max temp value in the script as in - status greater than 60. I am sure it can be done, I am just a novice coder.

**Comment by fbrendel** [comment]
Sorry now you've lost me.
Is your problem solved now or not?

**Comment by fbrendel** [comment]
You still need a custom service for each CPU.
Add the CPU number as parameter to the Path and use the script above.

**Comment by tpcr** [comment]
The script works if I hard code the MaxCPUTemp value in the script. Which I can live with for now.
The better approach would be to test all the CPU temps and pass the highest one to the exit code. Then have that temp checked by the condition - status greater 60. Or better yet - CPUtemp greater 60.
That way a default service test for CPU temps can be included with OPNsense.

**Comment by tpcr** [comment]
The script above checks all the CPU temps and then exits with an exit code 1 on the first CPU that exceed MAXTemp. If all CPU's are good, then an exit code of zero is passed. One script for all CPU tests, except then I have to hard code the MAX Temp value. It's a trade off.

**Comment by fbrendel** [comment]
Ah ok. now i got you.
And the problem :smiley: 
You should declare CPUTemp in a global context and provide MaxCPUTemp as parameter.
Try this script and add your max to the Path **Path**: _/usr/script/path 60_):
```shell
#!/bin/csh

set MaxCPUTemp = $1
set NumCPUs = `sysctl -n kern.smp.cpus`
set CurrentCPU = 0
set CPUTemp = 1000

while ( $CurrentCPU < $NumCPUs )
   set CPUTemp = `sysctl dev.cpu.$CurrentCPU.temperature | awk '{print $2}' | awk -F. '{print $1}'`
   echo "CPU $CurrentCPU temp: $CPUTemp"
   if ( $CPUTemp >= $MaxCPUTemp ) then
      exit $CPUTemp
   endif
   @ CurrentCPU = $CurrentCPU + 1
end
exit $CPUTemp
```

**Comment by tpcr** [comment]
Bingo! Works like a champ.
Thanks!!

**Comment by fbrendel** [comment]
:sunglasses:

**Comment by fbrendel** [comment]
@tpcr would be fantastic if you could add this as an example to the [Monit Mini Howto](https://forum.opnsense.org/index.php?topic=5303.0).
Please :smile:

**Comment by tpcr** [comment]
I have it ready, but need the patch first to Monit 1.6. Commit e94878b
When I do # opnsense-patch e94878b cannot find in the repository

**Comment by fichtner** [comment]
# opnsense-patch -c plugins e94878b

**Comment by tpcr** [comment]
returns
fetch: transfer timed out
I just updated to OPNsense 18.1.4 then tried again with same response

**Comment by fichtner** [comment]
sounds like dns or connectivity doesn't work (IPS?), it's a simple fetch

**Comment by tpcr** [comment]
Yes was an issue with IDS.
I have added to the thread. Should be a sticky in the forum.
