### ISSUE TITLE
sysutils/monit: path in custom tests doesn't allow parameters

### ISSUE THREAD

**Issue by fbrendel** [opnsense/plugins#585]
According to [PROGRAM STATUS TEST](https://mmonit.com/monit/documentation/monit.html#PROGRAM-STATUS-TEST) the 'PATH' option should accept parameters.
But the validation fails due to the space between program and parameter.

**Comment by fbrendel** [comment]
@fichtner do you migrate the plugin already?

**Comment by fichtner** [comment]
no, if you want to work on a bug just let me know when it's safe to merge :)
