### ISSUE TITLE
Dynamic DNS: Allow * in hostname for Namecheap

### ISSUE THREAD

**Issue by jkent** [opnsense/plugins#586]
https://www.namecheap.com/support/knowledgebase/article.aspx/295/11/can-i-use-your-dynamic-dns-client-for-a-wildcard-record

Namecheap allows for a wildcard in the hostname but the input validation does not allow for it.  Use wildcard does nothing with namecheap.

**Comment by itsbentheboy** [comment]
I would also like to see this as an option.

I'm making use of Wildcard subdomains, and also Wildcard certs from LetsEncrypt. The ability to update my *.exampledomain.com record with Opnsense would be much appreciated.

**Comment by itsbentheboy** [comment]
It looks like this issue can be resolved with a slight modification to
`plugins/dns/dyndns/src/www/services_dyndns_edit.php'

[Line 106](https://github.com/opnsense/plugins/blob/be5528b3a3036eb4a0cda976fc6f489ec5a3b471/dns/dyndns/src/www/services_dyndns_edit.php#L106) contains: 

105        `/* Namecheap can have a @. in hostname */`
106       `if ($pconfig['type'] == "namecheap" && substr($pconfig['host'], 0, 2) == '@.') {`

i'm not sure exactly what would be needed... I'm not skilled at this level of code. just a small time sysadmin. Thought i'd look into it to try and be helpful in getting this issue resolved though.

**Comment by fichtner** [comment]
Sorry for the silence. Good idea @itsbentheboy ... I've added the check and you can patch it without waiting for the release:

    # opnsense-patch -c plugins 39a926a84

Feedback welcome, even if working. :)

**Comment by itsbentheboy** [comment]
Update for you: 

Was out of town, updated to the latest version today. Tested and working, `*` is an allowed char for namecheap, and DDNS updated immediately. 

Thanks!

**Comment by fichtner** [comment]
@itsbentheboy superb, thanks for the feedback! It was shortcut directly to 18.7.4 since it made sense and impact was low :)

**Comment by h-town** [comment]
@fichtner can we get this enabled for cloudflare as well?

sorry to bump a closed issue but this is seemingly the same set of circumstances.

**Comment by fichtner** [comment]
@h-town sure, here you go:

    # opnsense-patch -c plugins b8a910253


Cheers,
Franco

**Comment by h-town** [comment]
@fichtner incredible commitment to support & development. thank you!!

**Comment by fichtner** [comment]
Nah, it's all in a day's work for bicycle repair man ;)

**Comment by gillenc** [comment]
As this has already worked once: 
@fichtner can we get this enabled for EuroDNS as well 😊 ? 
I already tried the modification locally, works like a charm.

**Comment by fichtner** [comment]
Sure, done via https://github.com/opnsense/plugins/commit/7e494c0cf :)

**Comment by vincesmits** [comment]
@fichtner would it be possible to enable it for Amazon Route 53? Thanks in advance!
