### ISSUE TITLE
[os-igmp-proxy] igmproxy not working since 18.1.3 - There must be at least 1 Vif as upstream

### ISSUE THREAD

**Issue by rx-tx** [opnsense/plugins#590]
Hello,
i am running OPNsense 18.1.3 with igmpproxy plugin 1.3 together with german telekom IPTV service.
The solution already worked with OPNsense 18.x just fine. After upgrading to 18.1.3 i recognized that the igmpproxy service does not come up.
The error in the log file is:

igmpproxy[20043]: There must be at least 1 Vif as upstream.

The igmpproxy service configuration is not changed, so there is one upstream interface (outside_pppoe) and one downstream interface (inside_untagged).

Maybe there is an issue with VLAN tagging, because the PPPoE interface is a tagged interface within an APU board. I tested to choose an untagged interface for the igmp upstream interface and the service started successfully. As soon as i switch back to my tagged PPPoE interface the service cannot start with the above error message.

Also tried to re-create the igmp configuration, but no change.

Any ideas or things i can check?

**Comment by fichtner** [comment]
igmpproxy was revived after many years of no updates. Unfortunately, several "forks" existed that did things slightly different. For now you can bring it back with:

    # opnsense-revert -r 18.1.2 igmpproxy

The better question: what is your upstream interface setup like? We would like to report this upstream.

**Comment by rx-tx** [comment]
Just verified - same issue with 18.1.4.

Installed igmpproxy from 18.1.2 and it works again.
Did not see anything related to igmpproxy in the release notes for 18.1.3.

The configuration is as follows:

a) physical interface - tagged (IEEE 802.1Q) ethernet interface w/ VLAN ID 7

igb2_vlan7: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=400000<TXCSUM_IPV6>
        ether 00:0d:b9:xx:xx:xx
        inet6 fe80::20d:b9ff:fe49:6352%igb2_vlan7 prefixlen 64 scopeid 0x9
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
        media: Ethernet autoselect (1000baseT <full-duplex>)
        status: active
        vlan: 7 vlanpcp: 0 parent interface: igb2
        groups: vlan

b) PPPoE on top of igb2_vlan7 (OUTSIDE_PPPOE)
see attached screenshot

c) igmpproxy configuration (upstream interface):

OUTSIDE_PPPOE 	upstream 	224.0.0.0/4, 193.158.0.0/15

![opns_pppoe_if](https://user-images.githubusercontent.com/37192230/37230004-40f354b0-23e6-11e8-918d-caa692231ff7.jpg)

**Comment by rx-tx** [comment]
Just verified with 18.1.5 and included igmpproxy 0.2.1 from https://github.com/pali/igmpproxy/tree/0.2.1 - same issue.
Workaround with "opnsense-revert -r 18.1.2 igmpproxy" helps.

**Comment by micressor** [comment]
Same problem with 18.1.8. I haven't tested the workaround yet.

**Comment by thomasnilsen** [comment]
Any update on this? Not beeing able to use igmpproxy is a huge disadvantage.

I run 18.7 and when I try to perform "opnsense-revert -r 18.1.2 igmpproxy" I get, "Fetching igmpproxy.txz: .. failed".

**Comment by fichtner** [comment]
Yep, somebody is working on it: https://github.com/pali/igmpproxy/pull/38

    # pkg add -f https://pkg.opnsense.org/FreeBSD:11:amd64/18.1/MINT/18.1.2/OpenSSL/All/igmpproxy-0.1_2,1.txz

**Comment by rx-tx** [comment]
Just for information: currently working combination for german IPTV service (Telekom Entertain):
OPNsense 18.1.13-amd64 +
os-igmp-proxy 1.3_1

**Comment by rx-tx** [comment]
Just for information: Working configuration at the moment:
OPNsense 18.1.13_1-amd64 + os-igmp-proxy 1.3_1 (with opnsense-revert -r 18.1.2 igmpproxy)

**Comment by ljpaff** [comment]
@thomasnilsen  Did the patch worked in you machine? Could you give me feedback please?

@fichtner There is a rollback in config.c, Please take care about it.

**Comment by thomasnilsen** [comment]
@ljpaff I found that `pkg add -f https://pkg.opnsense.org/FreeBSD:11:amd64/18.1/MINT/18.1.2/OpenSSL/All/igmpproxy-0.1_2,1.txz` worked for me. I had one issue with the VLAN I get multicast on did not have a IP set on the interface. Therefore igmpproxy did not want to start. I fixed that with a dummy ip address.

Things seemed fine to me when I fixed this, but I was unable due to lack of time to fully test this..

**Comment by nivek1612** [comment]
Note I have the same issue but I'm not using a pppoe interface. I'm a VLAN Tagged interface to Orange France for their IPTV service, the connection is established over VLAN 838 PCP 4 using DHCP. So I believe this isn't just PPPOE related. Regressing to v1.2 of IGMProxy and all is well

**Comment by fichtner** [comment]
@nivek1612 would you mind trying this version? https://pkg.opnsense.org/FreeBSD:11:amd64/snapshots/igmpproxy-0.2.1_1,1.txz

**Comment by nivek1612** [comment]
I'm not back in France at the minute and dont want to try over VPN just in case I break something :-) so let me ask one of the other guys to try

**Comment by nivek1612** [comment]
For what its worth I have just set up this version of IGMPproxy on my UK system which uses PPPOE and i can now start the IGMP proxy service where as before I could not. I cant fully test it as I dont have access to the Orange IPTV service here in the UK

**Comment by fichtner** [comment]
@nivek1612 ok... so far so good. Due to a mistake on my side this update won't make the 18.7.3 cut, but that also gives time for others to comment. I also published the CFT in the relevant forum thread. :)

**Comment by fichtner** [comment]
Due to a build mixup the proposed fix did not make it into 18.7.3 but will be included in 18.7.4.
