### ISSUE TITLE
SNMP does not autostart on secondary firewall in HA pair.

### ISSUE THREAD

**Issue by dragon2611** [opnsense/plugins#594]
SNMP is configured and works fine if I manually Login to the secondary and start the service but if the firewall is rebooted the service does not auto run on start-up.

This happened on 17.x and still happens on 18.1.4.

Since SNMP is often used by network monitoring software it's desirable to have it running on all members of the HA cluster.

**Comment by dragon2611** [comment]
I disabled MibII and SNMP has been a lot more stable since, that said I don't reboot very often.

**Comment by fichtner** [comment]
@dragon2611 Ok, shall we close this then? os-snmp is about to be superseded by os-net-snmp and the old code will likely be dropped within the next 6-12 months.

**Comment by dragon2611** [comment]
I think that's the best Idea, if it re-occurs I'll re-open and hopefully be able to post some logs
