### ISSUE TITLE
rspamd 1.7.2

### ISSUE THREAD

**Issue by mimugmail** [opnsense/plugins#602]
Just had a look at the changelog:

https://fossies.org/linux/misc/rspamd-1.7.0.tar.gz/rspamd-1.7.0/ChangeLog

We should better deeply test before just releasing a pkg update with the next update. :)

**Comment by fichtner** [comment]
I'll hold off on the update, provide a test package as soon as it hits FreeBSD. :)

**Comment by fabianfrz** [comment]
@fichtner upgraded rspamd on my linux server. Seems to work perfectly (did not have to modify config files).

The config files, which are created by OPNsense are a bit more complex than mine so we have to test anyway.

**Comment by fichtner** [comment]
hit FreeBSD, branched commit here... https://github.com/opnsense/ports/commit/e66177a36c3

Can't build at the moment, but we can try on Monday.

**Comment by fabianfrz** [comment]
@fichtner sounds good. Haven't much time for testing but will give it a try.
Didn't you tell us that your company wants to contribute a cryptographic extension to the OPNsense mail components?

**Comment by fichtner** [comment]
@fabianfrz it's a possibility in the future, but nothing concrete at the moment.

I've pulled rspamd into the ports, uploaded a test build (LibreSSL):

    # pkg add -f https://pkg.opnsense.org/FreeBSD:11:amd64/snapshots/libressl/All/rspamd-1.7.0.txz

**Comment by fabianfrz** [comment]
@fichtner did a quick test and it seems like it still works.

**Comment by fichtner** [comment]
thanks... one more gem for you: https://github.com/opnsense/plugins/commit/562bb2cd :)

**Comment by mimugmail** [comment]
1.7.0 and patch are also working for me, didn't look at the new features if we have to add some more config fields to the gui, but most defaults are fine too 👍

**Comment by fichtner** [comment]
@fabianfrz So move the rspamd plugin 1.2 to stable/18.1 then and ship both updates with 18.1.6? :)

**Comment by fabianfrz** [comment]
sure - especially because of the better performance ;)

**Comment by fabianfrz** [comment]
@fichtner when we are already here - maybe we can release wol 2.0 too - no bug reports in the forum and on github so far.

**Comment by fichtner** [comment]
will do a final check on wol, that was still on my list. sorry

**Comment by fichtner** [comment]
FWIW, I don't think anybody tested :/

**Comment by fichtner** [comment]
Closing this via https://github.com/opnsense/plugins/commit/6bca7f71f

**Comment by fichtner** [comment]
1.7.2 was released. Will be able to give out a test version tomorrow.

**Comment by fichtner** [comment]
Here is the latest one for LibreSSL:

    # pkg add -f https://pkg.opnsense.org/FreeBSD:11:amd64/snapshots/libressl/All/rspamd-1.7.2.txz

**Comment by mimugmail** [comment]
I'm running fine 1.7.2 for the last 9 days, no worries from my side to release it with 18.1.6 or 18.1.7 ...

**Comment by fichtner** [comment]
Okay, goes into 18.1.6. 😊
