### ISSUE TITLE
Suricata logging issue

### ISSUE THREAD

**Issue by tpcr** [opnsense/plugins#606]
The Suricata log no longer shows events such as updates as of OPNsense 18.1.4
Here is what I get in the log. When I manually look at the log, there is no data in it. Use to show rules updates. Happens on two different systems.
![opn1](https://user-images.githubusercontent.com/22845650/37354663-66399084-269f-11e8-9e24-3f2c85922961.jpg)

Here is the Suricata stats.log
------------------------------------------------------------------------------------
Date: 3/13/2018 -- 09:22:44 (uptime: 7d, 15h 27m 12s)
------------------------------------------------------------------------------------
Counter                                    | TM Name                   | Value
------------------------------------------------------------------------------------
capture.kernel_packets                     | Total                     | 281268445
decoder.pkts                               | Total                     | 281268445
decoder.bytes                              | Total                     | 257056721469
decoder.invalid                            | Total                     | 7
decoder.ipv4                               | Total                     | 288787228
decoder.ipv6                               | Total                     | 159789
decoder.ethernet                           | Total                     | 281268445
decoder.tcp                                | Total                     | 165552616
decoder.udp                                | Total                     | 94872715
decoder.icmpv4                             | Total                     | 3287
decoder.icmpv6                             | Total                     | 159654
decoder.teredo                             | Total                     | 135
decoder.avg_pkt_size                       | Total                     | 913
decoder.max_pkt_size                       | Total                     | 1514
flow.tcp                                   | Total                     | 168378
flow.udp                                   | Total                     | 310338
flow.icmpv6                                | Total                     | 5325
defrag.ipv4.fragments                      | Total                     | 28358610
defrag.ipv4.reassembled                    | Total                     | 14176308
decoder.tcp.hlen_too_small                 | Total                     | 6
decoder.tcp.opt_invalid_len                | Total                     | 1
tcp.sessions                               | Total                     | 166034
tcp.pseudo                                 | Total                     | 4982
tcp.invalid_checksum                       | Total                     | 139
tcp.syn                                    | Total                     | 175251
tcp.synack                                 | Total                     | 142743
tcp.rst                                    | Total                     | 66160
tcp.stream_depth_reached                   | Total                     | 2350
tcp.reassembly_gap                         | Total                     | 5
tcp.overlap                                | Total                     | 25251
tcp.overlap_diff_data                      | Total                     | 17
detect.alert                               | Total                     | 46372
app_layer.flow.http                        | Total                     | 45641
app_layer.tx.http                          | Total                     | 116364
app_layer.flow.smtp                        | Total                     | 9821
app_layer.tx.smtp                          | Total                     | 11385
app_layer.flow.tls                         | Total                     | 72303
app_layer.flow.ssh                         | Total                     | 22
app_layer.flow.smb                         | Total                     | 1
app_layer.flow.dns_tcp                     | Total                     | 1
app_layer.tx.dns_tcp                       | Total                     | 1
app_layer.flow.enip                        | Total                     | 3
app_layer.flow.failed_tcp                  | Total                     | 3574
app_layer.flow.dcerpc_udp                  | Total                     | 4
app_layer.flow.dns_udp                     | Total                     | 297698
app_layer.tx.dns_udp                       | Total                     | 298588
app_layer.tx.enip                          | Total                     | 3
app_layer.flow.failed_udp                  | Total                     | 12633
flow_mgr.closed_pruned                     | Total                     | 133202
flow_mgr.new_pruned                        | Total                     | 51465
flow_mgr.est_pruned                        | Total                     | 298582
flow.spare                                 | Total                     | 10000
flow.tcp_reuse                             | Total                     | 28
flow_mgr.flows_checked                     | Total                     | 1
flow_mgr.flows_notimeout                   | Total                     | 1
flow_mgr.rows_checked                      | Total                     | 65536
flow_mgr.rows_skipped                      | Total                     | 65535
flow_mgr.rows_maxlen                       | Total                     | 1
tcp.memuse                                 | Total                     | 2867200
tcp.reassembly_memuse                      | Total                     | 1304576
dns.memuse                                 | Total                     | 245508
http.memuse                                | Total                     | 560
flow.memuse                                | Total                     | 6957056

**Comment by AdSchellevis** [comment]
@tpcr I guess you mean the suricata.log file, visible from Services->Intrusion Detection->Log file, which seems to be wrongly configured in core.

can you try https://github.com/opnsense/core/commit/dc1cd4da918880a7a9b6036b02911b65128e2d7c?

`opnsense-patch dc1cd4
`

**Comment by tpcr** [comment]
Installed patch and rebooted. /var/log/suricata.log still empty after a rules update.
Use to show Suricata Rule update event.
But the Suricata WebGUI log now displays correctly for a blank file.
I noticed that the logging section of the suricata.yaml has the -file outputs removed.

**Comment by tpcr** [comment]
Need to put
  - file:
      enabled: yes
      filename: /var/log/suricata.log
Back in /usr/local/opnsense/service/templates/OPNsense/IDS/suricata.yaml line 752
Now it works. Also needed the patch.

**Comment by AdSchellevis** [comment]
oops, my mistake, @fichtner switched it to syslog in https://github.com/opnsense/core/commit/00b6bcefc48cccaeae6665ce4f37998b2fc806dc and removed the old reference. to get it working again, if I'm reading it correctly, you should enable syslog in the IDS settings and restart suricata and syslog (if you can reboot, that's probably the easiest option).

**Comment by tpcr** [comment]
Must have got the patch before the switch. Probably don't need the suricata.yaml change if syslog is enabled in the settings. I had it disabled.
All is working now

**Comment by tpcr** [comment]
Question
opnsense-patch 00b6bce
is not the same as
opnsense-patch dc1cd4

Do I still need the latter patch?

**Comment by fichtner** [comment]
No patches needed on 18.1.4. Enable IDS syslog, reset old suricata log. That’s it. :)

**Comment by tpcr** [comment]
Thanks
