### ISSUE TITLE
security/tinc: Features request for Tinc GUI

### ISSUE THREAD

**Issue by doublej74** [opnsense/plugins#61]
- Add a field to set custom port number (Tinc option)
- Add field for Mode option: router | switch | hub (Tinc option)
- Add field for setting the Ping Time-Out (Tinc option, for slow connections) 

- Allow FQDN host names in ext. Address field, so that it can work with Dynamic DNS (Tinc supports this according to tinc documentation). Currently field only allows IP address. I think this needs to be changed in 2 places in the GUI:

1. In the This Host of the Network section: Possible solutions (but I'm not sure!): Allow FQDN host name or allow to use keyword 'dynamic' (consistent with Gateway IP Address field under gateways), or replace with interface binding dropdown box (since this is the listen to IP address)?
2. Under Hosts (when creating a new host): Allowing FQDN host names in the ext. Address field. 

If you need a tester for this, let me know.

**Comment by fichtner** [comment]
thanks, assigning to @AdSchellevis for eval

**Comment by AdSchellevis** [comment]
@doublej74 I've added the port, ping and ext.address options, but I didn't have time to test (other then looking at the generated config). Do you have time to do this?

About the mode option, are you sure changing the mode to "switch" is all it needs? it's not a lot of work passing it through, but given the limited time I have, I want to ask you to test this first.

**Comment by fichtner** [comment]
This can be patched with the tinc plugin installed using:

    # opnsense-patch -c plugins 9b54074

**Comment by doublej74** [comment]
Just to let you know I'm working on it. However I'm running into some other
issues, making it hard to test. I'll get back to you on that with more info.

**Comment by doublej74** [comment]
Not yet finished, but 1 issue found: Under Networks I now have two fields with the same name and help description: Subnet and Subnet

**Comment by AdSchellevis** [comment]
oops, fixed in https://github.com/opnsense/plugins/commit/c5c5d6f310ae143adc45ac3343d4b1addb277e4c

**Comment by philippdieter** [comment]
I want to add that tinc allows the use of multiple subnets. This is especially useful to reach the net behind the firewall. This applies to the remote hosts as well to the own host.

**Comment by BiasF** [comment]
Hi,

the possibility to change the mode to switch would be very nice.

The tinc config is similar, except that the  subnet value in each host config are IP addresses in the same network.
(example: 10.4.0.1/32 for Host A, 10.4.0.2/32 for Host B and 10.4.0.3/32 for Host C)

**Comment by AdSchellevis** [comment]
@BiasF can you try?https://github.com/opnsense/plugins/commit/9af4e92996f7e475b0629bec87e12f1a94ad7400 

Don't forget to edit/save your configuration before restarting the service, a normal upgrade would fix the config.xml first.

**Comment by BiasF** [comment]
Hi,

thanks 👍  It seems to work. 
Maybe tomorrow I will try it in a larger testing environment, but with two OPNSense Hosts on my VMware Workstation it is working :) 

Thanks for your awesome work !

**Comment by AdSchellevis** [comment]
@BiasF your welcome! thanks for testing!

**Comment by fichtner** [comment]
Looks like this is closed.
