### ISSUE TITLE
Q: How to handle a service if it doesn't support pid file

### ISSUE THREAD

**Issue by mimugmail** [opnsense/plugins#610]
For the NUT plugin running in client mode there is a rc script nut_upsmon. The script calls /usr/local/sbin/upsmon which doesn't support pid files. How can I handle this with plugins.inc.d?
pfSense generates a dynamic init script for this case and just does a killall.

**Comment by fichtner** [comment]
https://github.com/opnsense/plugins/blob/master/security/clamav/src/opnsense/scripts/OPNsense/ClamAV/freshclam.sh#L40

**Comment by mimugmail** [comment]
Ja, I mixed pid file in plugins.inc.d with service handling, but it's just for the green service indicator ..
