### ISSUE TITLE
os-tor v3 onion services

### ISSUE THREAD

**Issue by alphazo** [opnsense/plugins#612]
Tor as of version 0.3.2.1-alpha supports the next-gen onion services protocol for clients and services that features many improvements over the legacy system, including:

- Better crypto (replaced SHA1/DH/RSA1024 with SHA3/ed25519/curve25519)
- Improved directory protocol, leaking much less information to directory servers.
- Improved directory protocol, with smaller surface for targeted attacks.
- Better onion address security against impersonation.
- More extensible introduction/rendezvous protocol.
- A cleaner and more modular codebase. 

There should be a check box to select between the type of hidden service to use v2 or v3. Both services can exist at the same time and will seen as following in torrc
   
```
HiddenServiceDir /home/user/tmp/hsv2
HiddenServicePort 6667 127.0.0.1:6667

HiddenServiceDir /home/user/tmp/hsv3
HiddenServiceVersion 3
HiddenServicePort 6668 127.0.0.1:6667

```

More information can be found here.
https://trac.torproject.org/projects/tor/wiki/doc/NextGenOnions#Howtoconnecttothetesthubfornextgenonionservices

https://blog.torproject.org/we-want-you-test-next-gen-onion-services

While v3 hidden services can apparently not be detected compared to v2 hidden services, it should be noted that HidServAuth is not yet supported on v3 hidden services. It will probably not be available before Tor 3.3.0.

**Comment by fabianfrz** [comment]
@alphazo pelease recheck the current version

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
