### ISSUE TITLE
Feature request for os-arp-scan

### ISSUE THREAD

**Issue by petererdos** [opnsense/plugins#614]
Hello,

The plugin is awesome and works great, but It's missing an important feature, which would make it even more awesome: the ability to add static leases from the results. 

It would be brilliant to click on a + sign next to a result, which opens the 'Edit lease' page on that specific interface with some prefilled stuff (like IP, MAC and hostname if possible). 
If the entry already has a static lease, a pencil to edit it, or a - minus sign to delete it.

Thank you!

**Comment by petererdos** [comment]
Or, instead the plugin, the same features for the ARP table page.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
