### ISSUE TITLE
Accounting Feature Request

### ISSUE THREAD

**Issue by rout3rx** [opnsense/plugins#616]
is there any plan to add accounting functionality ? 
or is there any radius appliance for use for radius server?
some radius servers needs some flags in accounting packet like mac-address and pap and mschap that don't relay with opnsense.

**Comment by mimugmail** [comment]
The problem is that every VPN service handles this on it's own. We can't edit a functionality in FreeRadius to let all daemons account to it. 

Can you give a concrete example what you want to achieve and what you have tried so far please.

**Comment by rout3rx** [comment]
aha, thanks dear mimugmail
i want to add some limitation such as Bandwidth, traffic, time and set these on a group or users for L2tp or pptp. 
i want already this.

**Comment by mimugmail** [comment]
Bandwidth can be set via the Traffic Shaper and the IP pool of VPN, same for time as you can set PF firewall rules with a schedule. Traffic is hard to achieve, I can't imagine L2TP/IPSec has such a feature. No idea of PPTP as nobody should use this protocol nowadays ..

**Comment by rout3rx** [comment]
but i think WISPr functionlity can do it in freeradius, you and your team built some of these for captive portal, if can do this for one of the vpn protocols it was so good

**Comment by mimugmail** [comment]
WISPr is only supported by Radius, not the Captive Portal. You need a device supporting/respecting these attributes. Captive Portal only supports Max-Daily-Session and this can be done via Radius plugin.

**Comment by rout3rx** [comment]
nice, i want use this attributes of radius for one of the vpn protocols
