### ISSUE TITLE
Application Filtering Feature Request

### ISSUE THREAD

**Issue by rout3rx** [opnsense/plugins#617]
hello
is there any idea to add App filtering ( for example block telegram or adobe Flash player or any other things in opnsense) 
i think deep packet inspection needs for this module

**Comment by mimugmail** [comment]
Yep ... I'm planning to integrate a sort of this via Suricata rules but it needs some time. Pipeline is full of projects.

**Comment by rout3rx** [comment]
also i think it can be done with nDPI package

**Comment by mimugmail** [comment]
This is in beta stage .. it's more or less complete but need some tweaks.
I can post you a patch to apply it if you like ...

**Comment by rout3rx** [comment]
thanks mimugmail

**Comment by fabianfrz** [comment]
@fichtner was not that in the latest release?

**Comment by fichtner** [comment]
It was.
