### ISSUE TITLE
net/wol: 2.0 release

### ISSUE THREAD

**Issue by fichtner** [opnsense/plugins#622]
Things to discuss:
* [ ] wakeHostByNode only works for static IPv4 (WAN DHCP errors out during broadcast probe)
* [x] Feedback for single WOL-Sending (error not on screen)
* [x] IPsec included in interface selection (not in old code, maybe only non-virtual?)
* [x] Dialogs have no literal close button, the x is hard to click
* [x] wake clock on entry does not wake -- calls API set ?
* [x] deleting an entry did not work

**Comment by fabianfrz** [comment]
@fichtner 23bb90918c27ef3b7ed877a1e7366e9dbd1be025 fixes the GUI stuff - I am not sure if it fixes IPsec (it does and did not show up on my machine) but at least it removes OpenVPN. For the first point I need more information (should I hide it too?)

**Comment by fabianfrz** [comment]
@fichtner Does the patch hide the ipsec interface on your side?

**Comment by fichtner** [comment]
interface hiding works good enough for release, but I've added 3 other points for your consideration

**Comment by fabianfrz** [comment]
everything except the first point is in #636

**Comment by fabianfrz** [comment]
@fichtner what is the todo in point 1 here?

**Comment by fichtner** [comment]
I'm releasing "2.0"now although the version has already been shipped with 18.7 anyway. We'll deal with bug reports as they come in. Thanks for your work!
