### ISSUE TITLE
Feature Request: OSPF or BGP

### ISSUE THREAD

**Issue by willjones** [opnsense/plugins#63]
Feature request for someone to write an OSPF or BGP plugin to allow for dynamic routing on internal networks and VPNs.

This would probably use Quagga or Bird in either instance.

**Comment by fabianfrz** [comment]
see #88 for OSPF. I did never use BGP but the code contains the base to support BGPv4 as well. It is using Quagga as routing daemon.

**Comment by fabianfrz** [comment]
note, that I have only implemented a minimal setup

**Comment by fabianfrz** [comment]
@willjones the code for OSPF should be generating a valid configuration now.
You may test it with an upcoming release.
