### ISSUE TITLE
C-ICAP 1.5 with ClamAV breaks after turning off

### ISSUE THREAD

**Issue by borisneubert** [opnsense/plugins#633]
OPNSense 1.8.5 with C_ICAP and ClamAV versions 1.5

I wanted to temporarily disable the virus scanner by turning Services | C-ICAP | Configuration | Enable c-icap service off. This breaks web access. Turning it on again reenables the green arrow run symbol but squid proxy on same server tells met that C-ICAP is not reachable.

In particular, what workaround does this turn off until the issue is solved?

Error message:

![grafik](https://user-images.githubusercontent.com/8795819/37966459-d52b949a-31c8-11e8-8d99-439525b577da.png)

Configuration: 

![grafik](https://user-images.githubusercontent.com/8795819/37966471-e29704fc-31c8-11e8-98d9-4c3092bc38f6.png)

![grafik](https://user-images.githubusercontent.com/8795819/37966483-f05b7da2-31c8-11e8-8f6e-ddcd783f927c.png)

**Comment by fichtner** [comment]
You need to turn off ICAP in web proxy first?

**Comment by borisneubert** [comment]
Oops, that's not obvious.

Forgot to mention that even after turning C-ICAP on again, it does not work any more. Even not after a reboot. I needed to restore the previous configuration from backup. Tried this loop several times.

**Comment by borisneubert** [comment]
This is a related PHP error

```
[27-Mar-2018 14:09:14 Europe/Berlin] PHP Fatal error:  Uncaught Error: Class 'OPNsense\CICAP\Api\General' not found in /usr/local/opnsense/mvc/app/controllers/OPNsense/CICAP/Api/ServiceController.php:52
Stack trace:
#0 [internal function]: OPNsense\CICAP\Api\ServiceController->checkclamavAction()
#1 [internal function]: Phalcon\Dispatcher->callActionMethod(Object(OPNsense\CICAP\Api\ServiceController), 'checkclamavActi...', Array)
#2 [internal function]: Phalcon\Dispatcher->dispatch()
#3 /usr/local/opnsense/www/api.php(26): Phalcon\Mvc\Application->handle()
#4 {main}
  thrown in /usr/local/opnsense/mvc/app/controllers/OPNsense/CICAP/Api/ServiceController.php on line 52
```

**Comment by fabianfrz** [comment]
There is a class missing. Can you try to reinstall the plugin?

**Comment by borisneubert** [comment]
I uninstalled and reinstalled the plugin. When I disable or re-enable ClamAV in the C-ICAP Antivirus configuration, the PHP error is thrown. At least the process is now reversible without the need to reboot. With ClamAV unchecked in C-ICAP Antivirus configuration, web access is still not possible (C-ICAP not running although the green arrow is shown). Maybe this is expected, though.

I suggest to disallow unchecking the C-ICAP enable and ClamAV enable checkboxes in the C-ICAP configuration when the web proxy is configured to use C-ICAP. Or at least add a warning or so in the help for the checkboxes and a hint that the virus checking can be turned off by turning off C-ICAP support in the web proxy.

**Comment by fabianfrz** [comment]
Probably found the bug - will try to fix it

**Comment by fabianfrz** [comment]
can you try `opnsense-patch -c plugins b1a8ea4` to install #634

**Comment by borisneubert** [comment]
Applied the patch. Turned ClamAV in the C-ICAP configuration off and on. No PHP error any more.

Still, with ClamAV turned off no web surfing at all. Is this expected?

**Comment by fabianfrz** [comment]
I can run the following command and see that the ICAP connection is successful:
```bash
c-icap-client -i ::1 -p 1344
```

![screenshot_20180327_200108](https://user-images.githubusercontent.com/3713914/37985632-97d74180-31f9-11e8-91ac-0dbc5aae06e1.png)

What shows the output on your shell?

**Comment by borisneubert** [comment]
No matter if ClamAV is turned on or off in the C-ICAP Antivirus config, I get:
```
root@opnsense:~ # c-icap-client -i ::1 -p 1344
ICAP server:::1, ip:::1, port:1344

OPTIONS:
        Allow 204: Yes
        Preview: 1024
        Keep alive: Yes

ICAP HEADERS:
        ICAP/1.0 200 OK
        Methods: RESPMOD, REQMOD
        Service: C-ICAP/0.4.4 server - Echo demo service
        ISTag: CI0001-XXXXXXXXX
        Transfer-Preview: *
        Options-TTL: 3600
        Date: Tue, 27 Mar 2018 18:04:12 GMT
        Preview: 1024
        Allow: 204
        X-Include: X-Authenticated-User, X-Authenticated-Groups
        Encapsulated: null-body=0
```

But with ClamAV disabled, I still get a message from squid in the browser like the one shown in the opening message when surfing the web.

**Comment by fabianfrz** [comment]
@borisneubert that tests if the "echo" service is reachable - it means that your ICAP server is running. You can now try to access the AV service by appending `-s avscan` to the command.

**Comment by borisneubert** [comment]
With ClamAV turned on, I get:
root@opnsense:~ # c-icap-client -i ::1 -p 1344 -s avscan
```
ICAP server:::1, ip:::1, port:1344

OPTIONS:
        Allow 204: Yes
        Preview: 1024
        Keep alive: Yes

ICAP HEADERS:
        ICAP/1.0 200 OK
        Methods: RESPMOD, REQMOD
        Service: C-ICAP/0.4.4 server - Antivirus service
        ISTag: CI0001-Wso6MpFwGMFMokJT+kaL1wAA
        Transfer-Preview: *
        Options-TTL: 3600
        Date: Tue, 27 Mar 2018 18:13:15 GMT
        Preview: 1024
        Allow: 204
        Encapsulated: null-body=0
```

With ClamAV turned off, I get:

```
root@opnsense:~ # c-icap-client -i ::1 -p 1344 -s avscan
ICAP server:::1, ip:::1, port:1344

OPTIONS:
        Allow 204: No
        Preview: -1
        Keep alive: No

ICAP HEADERS:
        ICAP/1.0 404 Service not found
        Server: C-ICAP/0.4.4
        Connection: close


```

**Comment by fabianfrz** [comment]
@borisneubert that means that the service is very likely working as expected and this is very likely no c-icap bug but a squid bug. The only thing you can try is appending `-f file.txt` to your command while clamav is enabled to be sure.

**Comment by borisneubert** [comment]
```
root@opnsense:~ # c-icap-client -i ::1 -p 1344 -s avscan -f /tmp/foo.bar 
ICAP server:::1, ip:::1, port:1344

No modification needed (Allow 204 response)
```
Well, if C-ICAP with ClamAV turned off produces a 404 error, then it is likely no bug at all, just a somewhat misleading message from squid. My expectation was that C-ICAP is transparent if the antivirus software is turned off (bypass instead of roadblock).

**Comment by fabianfrz** [comment]
I did set the config of squid to block if something in ICAP is broken because it is usually used to add a malware scanner so it cannot be bypassed by crashing the scanner or a misconfiguration.

Close the ticket?

**Comment by borisneubert** [comment]
For posterity:
- If you want to disable virus checking on webpages for a while, turn off C-ICAP in the squid web proxy settings.
- Do not disable C-ICAP service itself nor turn off ClamAV in the C-ICAP configuration.
