### ISSUE TITLE
security/tinc: Problems with the field-descriptions in tinc

### ISSUE THREAD

**Issue by EugenMayer** [opnsense/plugins#64]
@AdSchellevis punch me if its just me, or my poor knowledge about tinc. I tried to read the docs and map what i seen there against what the forms ask for

Network:

1. Network: his machines internal address to use and network mask for the whole network 
What does that mean - do you expect a address or a network? What does this field mean in general

2. Subnet: This machines part of the network
What part - i am not able to get 

Host:
1. hostname: The hostname for the selected machine in the network
What does "selected machine" means?

2. ext address/port: "this machine"
Any reason why i would re-enter this information since they are already part of the network?

3. subnet: This machines part of the network
Same as in network, what does "This machine" and "of the network" means.

4. public key: 
since the Network is selected above, why do i need to reenter this here?

----------------

Do not get me wrong on this, its for sure that i do not get the terminolgy right and you are so deep into this topic that its crystal clear for you.

But maybe we can get this done for the general purpose user and use more descriptive words? 

Thank you!

**Comment by AdSchellevis** [comment]
I don't have a lot of time at the moment, but the basics are quite simple.
Tinc delivers a mess network (the network) where all connected hosts should fit in (larger subnet vs hosts serving a part of it).

According to the documentation of Tinc all connected hosts should know the other connected hosts, hence the duplicate input of the other hosts in the same net. It will probably function too without the additional host records... This is just how it's supposed to be.

If someone has the time and spirit to write some documentation, we can add it to our online docs.
This example https://www.tinc-vpn.org/documentation/Example-configuration.html explains most of it, although the terminology isn't very straightforward there either.

**Comment by EugenMayer** [comment]
Well i would love to add the labels / descriptions, but yet, i am not gettin tinc, so i cannot get it running, so i cant help you :) its a hen/egg problem.

The problem is not the documetation online, but rather mapping your form on what they describe there. Using a tinc online doc + howto is easier then using the plugin right now, since it is 100% undocumentated and probably only clear for somebody being into tinc very much.

I would love to change that, also with contributing docs, but well, i need to have at least the tinc knowhow

**Comment by AdSchellevis** [comment]
I'm not sure where your issue is..... maybe hosts should have been called "other hosts" to make things more clear.... other then that, the form just contains all information needed.

Maybe with a simple example, let say we have a network 10.0.0.0/16, containing two hosts (firewalls in that network) using the following networks internally:
A 10.0.1.0/24
B 10.0.2.0/24

Network tab for A: 
Network 10.0.1.1/16 (assume it's using the first adres locally)
Subnet 10.0.1.0/24 

For B, well almost the same, but using 10.0.2.x.
And both need to configure the other host, including who should triggger a connection, simple as that. 

When configurated, you can very easily inspect the config files on the file system if you still have doubts... they are standard, very similar to the example earlier mentioned.

Just install 16.7 and test, I will look at 17.1 asap.

**Comment by EugenMayer** [comment]
well we got this to the core:

Network: thats the network of the tinc servers right, not the ones you really want to connect ( using routing ). that said, Network MUST be the same for alle "networks" defined. So lets say we build a tinc-connection of 3 servers, we need to have Network to be like

server1:
Network:172.1.1/24

server2:
Network:172.1.2/24

server3:
Network:172.1.3/24

The subnets the servers will route to can be whatever right ,could be 
server1 has:
Subnet: 10.1.1.0/24

server2:
server1 has:
Subnet: 192.1.1.0/24

And so on, right?

Where do i inspect the configuration files, i could not find them, used `find /usr/local -name '*tinc*'` and `find /var/etc -name '*tinc*'`

-----------------

The next point with the "host" is, why you again enter a subnet for the "host". Is it to ensure you have the configuration for all nets available on all tinc-servers due to the "mesh" structure ( if one goes down? ) it seems like duplication. Les put it this way: how does subnet from Network relate to the subnet in "host" or even, the host connecting and its "Network" subnet?

-----------------

The public key in Host, what public key is that, the one from the incoming server?
So lets say we have opnsense1(Server1) with and opnsense2(Server2).
Do i define a "Host" in opnsense1 for opensene2 (with the public key of opnsesne 2?)

--------

I bet you smell my confusion know. Thank you for the help! :)
