### ISSUE TITLE
net/haproxy: Setting for X-Forwarded-For disappeared in 2.0

### ISSUE THREAD

**Issue by StrikerTwo** [opnsense/plugins#647]
As per https://forum.opnsense.org/index.php?topic=7857.0
The option to set the X-Forwarded-For header seems to have disappeared with the HAProxy update. 
In the pre-redesign version there was an extra checkbox:
![image](https://user-images.githubusercontent.com/6770084/38625671-4958f824-3dab-11e8-9179-15fbee449c1d.png)

Can we have that back, please?

**Comment by fraenki** [comment]
@StrikerTwo Thanks for your report! The fix is simple:

```
# opnsense-patch -c plugins 84d815f
```

If you don't want to apply a patch, just change "Type" to something "TCP" and than back to "HTTP/HTTPS". The X-Forward-For option will reappear. :)

**Comment by StrikerTwo** [comment]
@fraenki Thanks!
