### ISSUE TITLE
security/tinc: Cannot submit Host-Form in tinc

### ISSUE THREAD

**Issue by EugenMayer** [opnsense/plugins#65]
The best description might be this screenshot: https://goo.gl/k1ffYu

I get a 200, response is empty, but the dialog stays open, no host is created in the end and now validation error is shown

**Comment by AdSchellevis** [comment]
What version of OPNsense are you using? And is there a response message in the post (I missed that one in the screenshot)

**Comment by EugenMayer** [comment]
No response ( empty ) , i am using 17.1, freebsd11

**Comment by EugenMayer** [comment]
@AdSchellevis i am in the IRC channel or in gitter, if you like, just drop by, i take my time to analyze this with you

**Comment by AdSchellevis** [comment]
@EugenMayer I'm not behind a desk, so can't reproduce this at the moment. Have you tried the same on 16.7? It might be a glitch in the volt template (although I wouldn't expect a successful post then).
Last question is there a crash report generated?

**Comment by EugenMayer** [comment]
@AdSchellevis Firmware->Reports does tell me, know programming bug - thats what you expect as a crash report right? Since the response type is 200, it might be something else, e.g. a broken route / wrong controller whatsover.

I cannot currently test it under 16.7, i only have 17.1 instances. If you like, you can easily build a 17.1 instance for virtualbox using packer https://github.com/EugenMayer/opnsense-packer

**Comment by AdSchellevis** [comment]
As soon as I have the time (next week), I will test it on my end, no image needed, thanks for the offer.

**Comment by EugenMayer** [comment]
I debugged this with xdebug. In the case it does not work, the csrf token cannot be validated  OPNsense\Base\ApiControllerBase\beforeExecuteRoute .. if that happens, an empty 200 is returned https://goo.gl/bxTNBX 

doing some non F5 reloads on the sight, it started to work . 

It might be related to something like https://forum.phalconphp.com/discussion/310/csrf-protection#C8665 since we have several forms and tokens ( search ). The pitty is, i could not debug
```
$csrf_valid = $this->security->checkToken($csrf_tokenkey, $csrf_token, false);
```

Since it is a call in into the C extension and i was not planning to gdb/debug symbols today :)

Probably that helps!

**Comment by AdSchellevis** [comment]
A crash indeed invalidates your csrf token, maybe another call on the same page crashed earlier and your looking at the wrong culprit now.... I had the same issue a long time ago (other piece of software).

We should return a 403 to make the issue explicit, probably not very complicated to fix.
