### ISSUE TITLE
Postfix: Smart host data validation & relayhost value generation improvement

### ISSUE THREAD

**Issue by jpawlowski** [opnsense/plugins#650]
Hi,

referring to [this merge](https://github.com/opnsense/plugins/pull/604#issuecomment-381395414), I would like to suggest to adjust the data input validator for the smart host.

It should also accept an optional port and square brackets for the hostname, so all of the following should be possible to enter:
```
# DNS records: MX, CNAME, A, AAAA
example.com
example.com:25
example.com:587

# DNS records: CNAME, A, AAAA
[smtprelay.example.com]
[smtprelay.example.com]:25
[smtprelay.example.com]:587

# DNS records: none
192.0.2.1 # --> implicitly transformed to [192.0.2.1]
[192.0.2.1]
[192.0.2.1]:25
[192.0.2.1]:587
2001:db8::1 # --> implicitly transformed to [2001:db8::1]
[2001:db8::1]
[2001:db8::1]:25
[2001:db8::1]:587
```
Ports are just examples, every port shall be possible to use.
Basically the address schema for Postfix parameter [relayhost](http://www.postfix.org/postconf.5.html#relayhost) shall be respected.
For IP4 and IP6 addresses, square brackets shall only be optionally provided and implicitly added for the config file, which is currently not the case.

It is quite common that you don't want Postfix to resolve MX record but purely rely on the CNAME/A/AAAA records instead. Also, it is not unusual that a smart host requires SMTP auth and only offers this on port 587 instead of 25.

Having control for the way Postfix resolves hosts can very often be important for many scenarios so it would be good to have those options.

**Comment by mimugmail** [comment]
@fichtner relay_host is currently a HostnameField, to manage this I have to change to TextField and add a mask. 

Is model bump ok for current installations or is there a migration script needed?
