### ISSUE TITLE
net/frr: frr kills default route / making it possible to add static routes to frr

### ISSUE THREAD

**Issue by vutral** [opnsense/plugins#651]
sometimes it seems even with configured routing filters frr kills the default route, it should be possible to add static routes to frr confguration to circumvent the problem

**Comment by mimugmail** [comment]
@fabianfrz @fichtner Do we really want a second place to add static routes?

Franco Fichtner <notifications@github.com> schrieb am Mo., 16. Apr. 2018,
15:45:

**Comment by fichtner** [comment]
we at least need some sort of fix for the undesired behaviour. I'm not sure about the scope of the problem, maybe @vutral can explain in more detail why/when this happens? maybe it's also a configuration issue solved easily

**Comment by fabianfrz** [comment]
@mimugmail I rewrote the static routes to MVC a long time ago. We can also render them into the zebra template if that helps.

**Comment by mimugmail** [comment]
While it's possible to add such a feature, it's very hard to track all events which would require a restart of FRR since a reconfigure of interface would kill the route set by FRR but not bring it back.

Close?
