### ISSUE TITLE
openconnect changes default route

### ISSUE THREAD

**Issue by klada** [opnsense/plugins#661]
Right now openconnect automatically changes the default route, which may break internet connectivity in many setups.

It would be nice if there could be an option to ignore the routes announced by the remote server, so that routes or NAT can be set up manually.

**Comment by klada** [comment]
@mimugmail The thing is that you might not always have control over the default route which is pushed to you.

For example I am getting a default route from my workplace's VPN. This way I am usually forced to route all of my private traffic through the company network, which I don't want. That's why I only want the traffic, which also goes to my company's network, to pass through the openconnect interface.

I also found the "config file" for this, which is `/usr/local/sbin/vpnc-script` (set_default_route/reset_default_route). Maybe calling that code can be controlled through a GUI config option.

**Comment by staeglis** [comment]
Is there any update to this issue? It would be very nice if could define my own routes. In this state this plugin is useless for me.

**Comment by fichtner** [comment]
@staeglis pardon the question, if it's useless to you why do you think telling others will motivate them to help? ;)

**Comment by mimugmail** [comment]
What so you want to achieve, or where is the problem? You receive default gateway and want only single routes?

**Comment by staeglis** [comment]
@mimugmail I would be very happy if you could also solve this issue. Also important for are the DNS settings. Maybe this option should be evaluated:
"Allow DNS server list to be overridden by DHCP/PPP on WAN"

By the way, what's the official way to disable OpenConnect? I've changed the specific option again (I haven't stop the OpenConnect service manually before) and after this the VPN connection was disabled again but the routes and the DNS settings wasn't reverted back.

**Comment by staeglis** [comment]
By the way, the "normal" IPSec implementation of OPNSense doesn't allow to act as client, do it?

**Comment by fabianfrz** [comment]
@staeglis fom a technical view. IPsec has no client - it is a feature of IPv6 and required in a compliant implementation.

**Comment by staeglis** [comment]
@fabianfrz Yes I know it theoretically ;)

Better said: Can I configure a host-to-site VPN, so make it acting like vpnc?

**Comment by fabianfrz** [comment]
In a road warrior setup like this you will very likely get problems with the routing.

**Comment by staeglis** [comment]
The main problem is that I can't setup the xauth credentials.

**Comment by cybercoder** [comment]
@staeglis Did you find any solution which a tunnel client only send traffics with specific determined destinations through tunnel ? In theory we can delete default gateway after connecting to tunnel then create static routes manually in client side, But isn't supported automatically?

**Comment by hosler** [comment]
I would also appreciate the option to not replace the default route. I would like to send none work related traffic over my ISP instead of my work VPN

**Comment by cybercoder** [comment]
> I would also appreciate the option to not replace the default route. I would like to send none work related traffic over my ISP instead of my work VPN

I tried this solution and it worked: https://gist.github.com/stefancocora/686bbce938f27ef72649a181e7bd0158

**Comment by mimugmail** [comment]
Pip is not an option, but I found a link with a vpnc script which might work

**Comment by hosler** [comment]
I've been using this vpn script for my routes. It works good

`#!/usr/bin/env sh

# Set up split tunneling
CISCO_SPLIT_INC=1
CISCO_SPLIT_INC_0_ADDR=10.0.0.0
CISCO_SPLIT_INC_0_MASK=255.0.0.0
CISCO_SPLIT_INC_0_MASKLEN=8
CISCO_SPLIT_INC_0_PROTOCOL=0
CISCO_SPLIT_INC_0_SPORT=0
CISCO_SPLIT_INC_0_DPORT=0

# Call regular vpnc-script
. /usr/local/sbin/vpnc-script
`

**Comment by ufgrat** [comment]
Would like to follow up on this-- It's one thing for the default route for my linux workstation, or my Windows pc, to be changed to route through my office network.  But I don't think they want me to route my **entire home network** through their system, which is what happens when opnsense connects to their VPN.

Can we get an "override default route" button, and create our own routes for VPN networks?  I've got the interface, it's easy enough to add the two routes I need, but I'd rather not have to script a workaround to delete the default network from the VPN.

**Comment by ufgrat** [comment]
Workaround:

Create /usr/local/etc/vpnc/connect.d

create a file in there with any name, containing (from above comment):

---- cut here ---
# Set up split tunneling
CISCO_SPLIT_INC=1
CISCO_SPLIT_INC_0_ADDR=10.0.0.0  # Route you want to route through VPN
CISCO_SPLIT_INC_0_MASK=255.0.0.0  # netmask for said route
CISCO_SPLIT_INC_0_MASKLEN=8   # netmask for said route
CISCO_SPLIT_INC_0_PROTOCOL=0
CISCO_SPLIT_INC_0_SPORT=0
CISCO_SPLIT_INC_0_DPORT=0
---- cut here ---

Still need to get routing working outside the opnSense box, but this is a start.

--John

**Comment by spa086** [comment]
Workaround to add dynamic routes:

Create /usr/local/etc/vpnc/connect.d

create a file in there with any name, containing (from above comment):
---
 #!/usr/bin/env sh

# URL of the route list
LIST_URL="http://192.168.1.13:8000/list.lst"

# Flag indicating that routes have already been added
ROUTES_ADDED_FLAG="/tmp/routes_added_flag"

# Check if the script has already been run
if [ -n "$ROUTES_SCRIPT_RUN" ]; then
    echo "The script has already been run."
    exit 0
fi

# Set the flag that the script has been run
export ROUTES_SCRIPT_RUN=1

# Function to get routes from the list
get_routes_from_list() {
    # Check if the routes have already been added
    if [ -f "$ROUTES_ADDED_FLAG" ]; then
        echo "Routes have already been added."
        return
    fi

    # Download the list
    routes=$(curl -s "$LIST_URL")

    # Check if the list was downloaded successfully
    if [ -z "$routes" ]; then
        echo "Error: failed to download the list of routes."
        exit 1
    fi

    # Parse the list and set the routes
    index=0
    while IFS= read -r route; do
        # Check if the line is not empty
        if [ -n "$route" ]; then
            export CISCO_SPLIT_INC_${index}_ADDR=$(echo $route | cut -d'/' -f1)
            export CISCO_SPLIT_INC_${index}_MASKLEN=$(echo $route | cut -d'/' -f2)
            export CISCO_SPLIT_INC_${index}_PROTOCOL=0
            export CISCO_SPLIT_INC_${index}_SPORT=0
            export CISCO_SPLIT_INC_${index}_DPORT=0
            echo "Route added: $route"
            index=$((index + 1))
        fi
    done <<EOF
$routes
EOF

    # Set the total number of routes
    export CISCO_SPLIT_INC=$index
    echo "Total routes added: $index"

    # Set the flag that the routes have been added
    touch "$ROUTES_ADDED_FLAG"
}

# Call the function to get routes
get_routes_from_list

# Call regular vpnc-script
/usr/local/sbin/vpnc-script
___
