### ISSUE TITLE
freeradius plugin feature request: group attributes

### ISSUE THREAD

**Issue by csszep** [opnsense/plugins#664]
Hi!

It would be useful if the plugin would handle user groups and reply group attributes too if an user belongs to a group.

The easiest way to solve this i think is the usage of rlm_passwd module to store  groups. (or use sqlite for the entire configuration?)

thx
csszep

**Comment by mimugmail** [comment]
rlm_passwd doesn't make fun, sqlite would be best for this. I already asked for sqlite support which is in there for some time, but I didn't find the time yet to redesign for sqlite and I also cannot garantee before 19.1 :/

**Comment by csszep** [comment]
Hi!

There is any news in this topic?

Thx

**Comment by mimugmail** [comment]
No, sqlite is broken since 3.0.19, have to fix this first

**Comment by csszep** [comment]
Hi!

There is any roadmap for support group attributes?

Thx

**Comment by mimugmail** [comment]
You can achieve this via AV-Pairs if your device supports it.
