### ISSUE TITLE
Custom attributes for freereadius

### ISSUE THREAD

**Issue by rantwolf** [opnsense/plugins#672]
I want to setup a radius based wifi ap with mikrotik hap ac2.
When I use the tags for the VLAN ID to seperate the clients, it won't work.
Mikrotik wiki means that I should use the following attributes:
MIKROTIK_WIRELESS_VLANID = 26, /* integer */
MIKROTIK_WIRELESS_VLANIDTYPE = 27, /* integer */ (0 - 802.1q tag)

Will these attributes combined with the existing VLAN attributes?

**Comment by mimugmail** [comment]
Do you have a link for the docs? If they have a VSA it should be easy

**Comment by rantwolf** [comment]
The things I have are these here:
https://forum.mikrotik.com/viewtopic.php?t=81881#p441736
https://wiki.mikrotik.com/wiki/MANUAL:RADIUS_Client

I hope it would be usefull.

**Comment by mimugmail** [comment]
Please note that the users werent fully able to use it with FreeRadius like in the link at the bottom.
I can add this features and let you test ... give me 1 or 2 days ..
