### ISSUE TITLE
net/zerotier: Update to new Zerotier version

### ISSUE THREAD

**Issue by StrikerTwo** [opnsense/plugins#675]
Zerotier version 1.2.8 has been out for a couple of weeks now, any chance of a plugin update?
Paging @dharrigan ;)

**Comment by fichtner** [comment]
@StrikerTwo the plugin is not really related to the package version, nobody seems to update FreeBSD port

**Comment by StrikerTwo** [comment]
Ah, thanks. I emailed the package maintainer and the updated FreeBSD port is ready:
https://github.com/skunkwerks/ports/commit/3aec72f27367c90db052df1f8fc94954ce6d5d61
https://reviews.freebsd.org/D15133

Now what? ;)

**Comment by fichtner** [comment]
@StrikerTwo wait for 18.1.9 hopefully. would you mind testing the new package version up front? I can provide a build in 1-2 days. Are you running amd64/OpenSSL or another combo?

PS: thanks to @dch for the update!

**Comment by StrikerTwo** [comment]
Sure, I can test it. amd64/OpenSSL is fine.

**Comment by fichtner** [comment]
First part of the puzzle: https://github.com/opnsense/ports/commit/ff99edfa44

**Comment by StrikerTwo** [comment]
@fichtner Looking good! Install went without problems and connections work just fine.

**Comment by fichtner** [comment]
@StrikerTwo super, let's ship this in 18.1.9 then. no further action needed. :)
