### ISSUE TITLE
security/tinc: 17.1 interface gets lost

### ISSUE THREAD

**Issue by EugenMayer** [opnsense/plugins#68]
When you install the tinc plugin you see a interface TINC in the interface section / rules section.
You can see the entry in <interfaces> section in the config.xml

You can configure a network/host like it is supposed, you then do a tinc daemon restart. You can see an tinc0 interface on the cli.

**Issue 1**
If you know reboot, the interface gets lost in opnsense, will though stay on the cli, so it gets created. You cannot really use the assign mode in the interfaces section, since this does not create a tinc like entry with all this dynamic...virtual and all this inside.

**Issues 2 if you re-assign the interface in the GUI:**
If you though do so and then reboot, you will cause a supernova, since the WAN/LAN interfaces are shifted, so WAN will be lan and you cannot connect to your box.

**Comment by EugenMayer** [comment]
On the 3rd box i could actually crack it down more precise. It is not the reboot removing the interface, actually, it is by design that the interface is not "assigned" as a WAN/LAN nic would do - it just shows up the firewall rules tab.

Now, i tried a lot on the first boxen and back then created rules on this virtual interface - and that is actually the cause. If you create a single rule in the TINCVPN tab in rules, the tab disapears completely

**Comment by AdSchellevis** [comment]
It materialises on legacy config save, which isn't triggered at the  moment. Just change a single item in the firewall should always enforce a sync.
We should probably add a simple service call in core for this, which can then be executed from the api of the plugin.

**Comment by EugenMayer** [comment]
@AdSchellevis u missed me here,  the point is, creating a rule will actually **remove** the tinc interface and cause a havok on the server.

I cannot see on how to "readd it" right now by editing rules?

**Comment by AdSchellevis** [comment]
can't reproduce on my end, the interface registration is the same as used by other services (ipsec, openvpn, etc) as far as I can see.

**Comment by AdSchellevis** [comment]
It seems I've found a box with a similar issue, let me get back on this one...

**Comment by EugenMayer** [comment]
@AdSchellevis i can reproduce it every single time. 

 1. Install tinc plugin
 2. configure one network + one host, press apply
 3. tinc service start and under rules you sie the tinc tab. Also you see an entry in config.xml
 4. add a rule to the tinc interface, after saving, the tab is gone, also the one in config.xml

**Comment by AdSchellevis** [comment]
The one I found was only related to ipsec only  (https://github.com/opnsense/core/commit/3a96c1dd5dc5d01249fcb41c2d072c68956969b7)

Are you sure the network and underlaying hosts are enabled? I can't reproduce this on my end, and am too busy at the moment.

**Comment by EugenMayer** [comment]
They are 100% enabled, i also checked it on the CLI, the configuration is generated.

Are you testing on 17.1? I have
 - 1 WAN
 - 1 LAN ( 10.1.5.0/24)

Tinc server is on 10.1.5.254
Subnet is 10.1.5.0/24

The other servers are the same and just differ in the subnet:
- Server B: Network: 10.1.6.254 / Subnet 10.1.6.0/24
- Server C: Network: 10.1.4.254 / Subnet 10.1.4.0/24

I can reproduce this issue on every single server - every time. Its not even about just reproducing - its a blocker, i cannot do anything

**Comment by EugenMayer** [comment]
I have not IPSEC, no OPENVPN activated / enable, but i have those plugins installed ( nothing created ). In general those boxes are pretty vanially. Beside the WAN/LAN and 3 rules, they are basically 17.1 vanilla

**Comment by EugenMayer** [comment]
@AdSchellevis is there any way i can support you getting this fixed?

**Comment by mimugmail** [comment]
@EugenMayer I tried to reproduce with the current code but my TINCVPN isn't gone after adding rules.

@AdSchellevis When OpenVPN is enabled I only see the OPENVPN tab in the rules, not TINCVPN. Only after disabling OpenVPN server it's there. Is this a known limitation?

**Comment by AdSchellevis** [comment]
@mimugmail it needs a save from a legacy component to plugin. if you change anything in the firewall it should popup immediately afterwards. We should fix that some time, maybe we should add a plugin probe after one of the configd commands is triggered.

**Comment by mimugmail** [comment]
@AdSchellevis Great, reproduceable, now every Interface is there. Thanks

**Comment by mimugmail** [comment]
@AdSchellevis What is best practice for OPNsense and Tinc? Starting the service creates a tinc0 interface without a IP address in OS itself ... but I can additonally assign it via UI. Is this required? 

For a simple S2S VPN there's no need to assign a new interface, do you know of any bigger use cases where this is required? 

Oh, and then I'd suggest to make the subnet field a CSV List to add multiple subnets to announce to other peers, like in this one:

http://ostolc.org/site-to-site-vpn-with-tinc.html

If this is fine for you I'd try to push a PR and send a write-up to Jos for the docs (what's possible and what's not with the plugin version)

**Comment by AdSchellevis** [comment]
@mimugmail it has been some time ago since I configured a tinc mesh. 

If I do remember correctly, you simply define a net which is large enough to fit all your locations, make sure every location has an ip address within the net (which should be managed by tinc) and define your part of the whole mesh within the network part. a bit like:

![image](https://cloud.githubusercontent.com/assets/9783985/26596065/cb31bcdc-456d-11e7-9a91-e653eae41331.png)

Full network is 192.168.0.0/16, my address should be 192.168.100.1/16, and I'm serving from this end 192.168.100.0/24.

![image](https://cloud.githubusercontent.com/assets/9783985/26596150/0c92a59c-456e-11e7-9793-fc18e12856fc.png)

Next you define all the other nodes in the network and the nets they're serving.

The screenshots are from my local vm, without a working setup.

**Comment by mimugmail** [comment]
@AdSchellevis Your tinc0 has an IP address, so you assigned this interface via UI? I also read this guide with /16 and multiple /24 in there for each branch. 

But what I you connect e.g. 2 DC's with multiple subnets .. what do you think about changing the model to allow multiple subnets?

**Comment by AdSchellevis** [comment]
@mimugmail I assigned it using the networks tab in tic, yes. I'm not sure why you would want totally different nets with tinc, but maybe I'm missing something. Normally you define one big net to host all your branches. if you just want s2s networks, openvpn might be a better option for your use case.

**Comment by mimugmail** [comment]
@AdSchellevis The big net design comes form the official doc, but I was thinking about an existing network design with different subnets. 
Example:

BranchA:
LAN: 10.0.1.0
DMZ: 192.168.1.0
DEVOps: 172.16.1.0

BranchB:
LAN: 10.0.2.0
DMZ: 192.168.2.0
DEVOps: 172.16.2.0

BranchC:
LAN: 10.0.3.0
DMZ: 192.168.3.0
DEVOps: 172.16.3.0

I know this is bad design, but if this is what you got (e.g. as an external consultant) and want to connect them via mesh, or better without a SPoF, tinc would be a nice solution. 

My perspective is just the integrator ones ... 

Just checked the model, there's a fieldseparator allowing multiple subnets, I'll check if this generates a useable config.

**Comment by AdSchellevis** [comment]
@mimugmail I my opinion you should be able to define 3 networks already, as long as the subnets of the separate nets are smaller then the total net.

so you define the nets 10.0.0.0/16, 192.168.0.0/16 and 172.16.0.0/16 which spawnes 3 tinc daemons connecting all together.
