### ISSUE TITLE
HAProxy / statistics table style off

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/plugins#681]
The overview tab seems to have a small style issue 
![image](https://user-images.githubusercontent.com/9783985/40269833-be2bd25c-5b83-11e8-8034-23d9c98269f6.png)

@fraenki I will push a fix later, but for reference I'm opening an issue.

**Comment by AdSchellevis** [comment]
@fraenki this https://github.com/opnsense/plugins/commit/e38d58ae88d79ddb80548ebd57fdd5e03409a992 ok ? 

![image](https://user-images.githubusercontent.com/9783985/40269981-e585aefc-5b85-11e8-93cc-bab2fe217c7a.png)

**Comment by fraenki** [comment]
@AdSchellevis Much better, thanks!

**Comment by fichtner** [comment]
Will be bundled in 2.7, thanks!
