### ISSUE TITLE
net/frr: Feature Request: IP Prefix List filtering add le ge options

### ISSUE THREAD

**Issue by ruffy91** [opnsense/plugins#683]
When filtering prefixes with the ACL option it is not possible to add the options le/ge to the acl entry.
This is needed if you want to allow/deny unspecific prefixes:
For example:
ip prefix-list NAME seq 10 permit 10.0.0.0/8 ge 16 le 24
This allows all prefixes included in 10.0.0.0/8 with a netmask between and including 16 to 24
10.128.0.0/9 denied
10.3.0.0/16 permitted
10.1.2.0/24 permitted
10.2.3.0/25 denied

The ordering of the options does not matter and they can be used alone or together.
This has to be added for all routing protocols.

**Comment by mimugmail** [comment]
This is from the helptext in BGP:

`The network pattern you want to match. You can also add "ge" or "le" additions after the network statement. It's not validated so please be careful!
`

Are you sure you're using the correct syntax? Cisco and FRR are sometimes bit different ...

**Comment by ruffy91** [comment]
I had a look at the frr documentation here: http://frrouting.readthedocs.io/en/latest/filter.html#ip-prefix-list

> Less than or equal to prefix numbers and greater than or equal to prefix numbers can be used together. The order of the le and ge commands does not matter.

Unfortunately the documentation is only available for 4.1-dev and 5.0

**Comment by mimugmail** [comment]
Go to CLI in OPNsense, do a vtysh and try to add it yourself to test the correct syntax.

**Comment by ruffy91** [comment]
It is working from the command line but the syntax in my first command is wrong.
I have edited the first post to reflect that.

**Comment by ruffy91** [comment]
Weird.
It is working now from CLI and UI.
I am now testing on a 18.1.7_1.
The other system which was not working was on 18.1.8.
I will test it again tomorrow on the other system and give Feedback, Most probably I did a mistake when entering the string.

I am closing this issue as the feature already exists.
