### ISSUE TITLE
security/acme-client: logfile is scrambled in the GUI

### ISSUE THREAD

**Issue by fraenki** [opnsense/plugins#69]
@fichtner: The logfile looks distorted in the GUI right now. Do you have some advise how I might fix this? :)

![lelog](https://cloud.githubusercontent.com/assets/909706/22426740/b0ec9d04-e700-11e6-9696-d04141d97b44.png)

**Comment by fichtner** [comment]
squid has a similar issue. the regex is fixed for BSD, not per daemon.

**Comment by fabianfrz** [comment]
@fraenki It may be the hardcore solution for your log but you can look at the log viewer of the `net/quagga` plugin. It gets the log from a `configd` call as a JSON structure and and passes it through.

**Comment by fichtner** [comment]
@fraenki you need core commit 11f359c and plugins commit 24ff623. Core commit won't be in the 17.7.1 release, so you can try this. I added the plugin fix to 17.7.1 anyway, it is harmless. "6" was guessed from your screenshot. May be off by one. ;)

**Comment by Woi** [comment]
I can test https://github.com/opnsense/core/commit/11f359c on top of 17.7.1 if you like me to...

**Comment by fichtner** [comment]
@Woi all help is welcome:

# opnsense-patch 11f359c

... but I think you know this :)


Cheers,
Franco

**Comment by Woi** [comment]
Looks nice now :+1:

**Comment by fichtner** [comment]
Thank you, Marco. We'll land this in 17.7.2 then :)

**Comment by Woi** [comment]
Reporting #243, I stumbled about this bad looking line breaks in the date column, if a long log message exists:

![os-acme-client_log_longlines](https://user-images.githubusercontent.com/5870628/30037007-3abd05ca-91b8-11e7-81ee-7561a39ca861.png)

**Comment by fichtner** [comment]
This can't be fixed. It writes a proper entry per line. It's the header dump that makes this awkward. 😊

**Comment by fraenki** [comment]
> This can't be fixed. It writes a proper entry per line. It's the header dump that makes this awkward.

We'll change acme.sh's default log level in the next release (https://github.com/opnsense/plugins/pull/254). This will finally fix this issue :)

**Comment by fichtner** [comment]
@fraenki nice, thanks!

**Comment by StrikerTwo** [comment]
Still broken on 17.7.2...
![image](https://user-images.githubusercontent.com/6770084/30476515-8726b7b2-9a0a-11e7-8f6e-ce989ebd3021.png)

**Comment by fichtner** [comment]
it's not broken, literal newlines in log messages from the particular service are, er, silly...

**Comment by StrikerTwo** [comment]
Whatever, it looks broken ;)

**Comment by fichtner** [comment]
ps: did you reboot? the services don't auto-restart

**Comment by StrikerTwo** [comment]
Ah, no, I haven't. Will try that tonight.

**Comment by fraenki** [comment]
@StrikerTwo The fix changes the log setting of acme.sh, that's why it will only fix _new_ log entries. Maybe clear the log and try again.

**Comment by StrikerTwo** [comment]
Ah, I see. I have rebooted the box and generated some new entries in the LE log and it looks better now. Thanks!
