### ISSUE TITLE
net/zerotier Notice: Undefined index: linkQuality

### ISSUE THREAD

**Issue by darkain** [opnsense/plugins#698]
When trying to view the status of a network, this warning appears in the middle of one of the tables.

`
Notice: Undefined index: linkQuality in /usr/local/opnsense/mvc/app/cache/_usr_local_opnsense_mvc_app_views_opnsense_zerotier_overview.volt.php on line 226
`

**Comment by fichtner** [comment]
Thanks, looks like the return value is missing so let's better skip the reading. :)
