### ISSUE TITLE
design error pages for nginx plugin

### ISSUE THREAD

**Issue by fabianfrz** [opnsense/plugins#699]
@marjohn56 @opnsenseuser This plugin needs some well designed error pages if you like to contribute and no SASS files are needed - simple HTML with embedded JS/CSS would be the best variant.  ;)

Please wait for #696 being on master.

* [x] A 404 error page
* [x] A server error page (server issue, upstream not reachable etc.)
* [x] A firewall denied the request error page done

Are you interested in adding them?

**Comment by opnsenseuser** [comment]
Hi,

I like doing it. But I have a lot to do at the moment (at work) and would not have time until next week. would that be okay?

Br rene

Am 03.06.18 um 18:20 schrieb Martin Wasley

**Comment by fichtner** [comment]
Take your time, remember this is all free voluntary stuff we do for fun :)

**Comment by fabianfrz** [comment]
@opnsenseuser no problem - the plugin is far from being released. The error pages are not required but a very nice to have (useful information for the user, OPNsense branded design to see a difference to a standard nginx error page, etc.)

**Comment by opnsenseuser** [comment]
I'd like to finish the new sidebar first. I have some ideas now. if i have finished the sidebar project and franco is satisfied, then i would crash on the next project.

Ok?

Rene

Am 04.06.18 um 18:01 schrieb Fabian Franz BSc

**Comment by fabianfrz** [comment]
sure, I can serve simple versions or default error pages in mean time

**Comment by opnsenseuser** [comment]
ok, because now the sidebar project is finished for now, i would like to dedicate myself to this topic. I would just ask someone to tell me which file has to be edited. are there own php error pages etc? ask for support so that I can read the matter a bit easier. Thank you

**Comment by fabianfrz** [comment]
The fipes are there: https://github.com/opnsense/plugins/tree/nginx/www/nginx/src/etc/nginx/views

The WAF denied page is simply designed, the others still need it but you can improve the denied page as well if needed.

The only thing that is important is that this files do not need external resources (images, js, css) because that may mess with application URLs.

**Comment by fabianfrz** [comment]
@opnsenseuser what's the status here?

**Comment by fabianfrz** [comment]
I made variant for the release so it will at least not be missing. You may add a better one in the future.

**Comment by opnsenseuser** [comment]
Sorry, i was on Holiday!

Regards,
Rene

Samstag, 21. Juli 2018, 10:16 +0200 von notifications@github.com  <notifications@github.com>:
