### ISSUE TITLE
acme-client: DNS-01/nsupdate: doesn't allow FQDN in the name

### ISSUE THREAD

**Issue by lrosenman** [opnsense/plugins#70]
when you put a FQDN in a certificate name request, you get: Should be a string between 1 and 255 characters.

if you remove all the special characters (INCLUDING PERIODS(!!)), it sends the unqualified name as the CN= to LE, and gets a 400 error:

[Sun Feb 5	00:00:07 CST 2017] new-authz error: {"type":"urn:acme:error:malformed","detail":"DNS name does not have enough labels","status": 400}
[Sun Feb 5	00:00:07 CST 2017] The new-authz request is ok.

This makes it IMPOSSIBLE to generate a certiificate. 
<img width="1440" alt="screen shot 2017-02-05 at 7 47 41 am" src="https://cloud.githubusercontent.com/assets/2868525/22626634/bbb2ce40-eb77-11e6-87ea-753148dd55ae.png">

Also, it is unclear what is supposed to go in the secret field of the validation request.  The whole key file, or just the secret or what. 

<img width="1440" alt="screen shot 2017-02-05 at 7 51 24 am" src="https://cloud.githubusercontent.com/assets/2868525/22626645/fb7e46da-eb77-11e6-9ef8-264b88a288ba.png">

**Comment by Aejoh** [comment]
Same problem, it is not possible to use a name like srv-1.example.com

**Comment by nemesix29** [comment]
Same issue when my FQDN contain a hyphen.

**Comment by fraenki** [comment]
Thanks for the report, I'm preparing a fix.

**Comment by fraenki** [comment]
A fix is included in PR #71.

**Comment by lrosenman** [comment]
Can you clarify the nsupdate secret key field?

**Comment by fraenki** [comment]
@lrosenman: You need to put in the whole key file, see the example in my initial PR #66. I'll fix the help text, though.

**Comment by lrosenman** [comment]
@fraenki Thanks!

**Comment by nemesix29** [comment]
Thanks !

**Comment by fraenki** [comment]
FYI, the fix will be available on thursday with OPNsense 17.1.1  :)
