### ISSUE TITLE
security/acme-client: add support for INWX

### ISSUE THREAD

**Issue by QDaniel** [opnsense/plugins#703]
https://github.com/Neilpang/acme.sh/tree/master/dnsapi dns_inwx.sh

**Comment by DonMcCoy** [comment]
The support to missing APIs has been added on PR #712 

You can manually change the affected files and test, if it's working properly we can then safely merge, 

the files are:
/usr/local/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
/usr/local/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
/usr/local/opnsense/scripts/OPNsense/AcmeClient/certhelper.php

**Comment by fraenki** [comment]
> You can manually change the affected files and test, if it's working properly we can then safely merge

Or use OPNsense fantastic tools to apply the PR locally on your installation:

```
# opnsense-patch -c plugins 252a319d166c20edd4993e5497832c75f6a60a39
# opnsense-patch -c plugins ac2899806972540d5b9ab5d1823ec4ffacfc3aac
```

I'll close this issue in favour of #712 (which is about to be merged, once I've finished a review).
