### ISSUE TITLE
telegraf ping option uses incorrect parameter -w

### ISSUE THREAD

**Issue by ikke-t** [opnsense/plugins#705]
I just tried enabling the telegraf service, and while at it, I enabled ping to some local hosts. This comes to log with each host:

```
2018-06-10T17:00:58Z E! Error in plugin [inputs.ping]: host xxx.yyy ping: illegal option -- w
usage: ping [-AaDdfnoQqRrv] [-c count] [-G sweepmaxsize] [-g sweepminsize]
            [-h sweepincrsize] [-i wait] [-l preload] [-M mask | time] [-m ttl]
            [-P policy] [-p pattern] [-S src_addr] [-s packetsize] [-t timeout]
            [-W waittime] [-z tos] host
       ping [-AaDdfLnoQqRrv] [-c count] [-I iface] [-i wait] [-l preload]
            [-M mask | time] [-m ttl] [-P policy] [-p pattern] [-S src_addr]
            [-s packetsize] [-T ttl] [-t timeout] [-W waittime]
            [-z tos] mcast-group, exit status 64
```

I don't know what it wants to have as an option. In linux that would be -w timeout, which in freebsd would be -t. Perhaps change that?

**Comment by mimugmail** [comment]
Can you try with IP instead of hostname?

**Comment by xmj** [comment]
This was fixed upstream in 
https://github.com/influxdata/telegraf/pull/4241
4 days ago.

**Comment by mimugmail** [comment]
Can we close this one @ikke-t ?

**Comment by ikke-t** [comment]
Looks valid to me. Thanks.

**Comment by Nornode** [comment]
This seem to have come back in Telegraf 1.7.2?
I just updated to opnsense 18.7.9 and I stopped getting ping data to influxDB.

To troubleshoot I removed all hosts from the input field and added only 8.8.8.8 
On top of other (old?) input errors I'm getting:

`2019-01-02T12:16:39Z E! [inputs.ping]: Error in plugin: host 8.8.8.8: ping: illegal option -- w
usage: ping [-AaDdfnoQqRrv] [-c count] [-G sweepmaxsize] [-g sweepminsize]
            [-h sweepincrsize] [-i wait] [-l preload] [-M mask | time] [-m ttl]
            [-P policy] [-p pattern] [-S src_addr] [-s packetsize] [-t timeout]
            [-W waittime] [-z tos] host
       ping [-AaDdfLnoQqRrv] [-c count] [-I iface] [-i wait] [-l preload]
            [-M mask | time] [-m ttl] [-P policy] [-p pattern] [-S src_addr]
            [-s packetsize] [-T ttl] [-t timeout] [-W waittime]
            [-z tos] mcast-group, exit status 64`

**Comment by mimugmail** [comment]
An upstream fix will come soon ..

https://github.com/influxdata/telegraf/pull/5112
