### ISSUE TITLE
please add haproxy monitoring to telegraf plugin

### ISSUE THREAD

**Issue by ikke-t** [opnsense/plugins#706]
Hi,

I'd like to use the telegraf, once I get it configured. I also run HAProxy on my OPNSense. It would be really nice to get the graffic stats exported from that one too into influxdb, and show it in my grafana instance.

So if possible, here would be the config for that to include into OPNSense Telegraf plugin:

https://github.com/influxdata/telegraf/tree/master/plugins/inputs/haproxy

I am glad to test it to get it developed.

**Comment by ikke-t** [comment]
FYI, I added it manually to telegraf.conf, and it works perfectly. This is all it takes:

```
[[inputs.haproxy]]
  servers = ["socket:/var/run/haproxy.socket"]
```

Having enable selection box in telegraf input conf for adding those lines would be great.

**Comment by mimugmail** [comment]
@fraenki will there only be one socket or are there some circumstances where multiple sockets exists?

**Comment by fraenki** [comment]
@mimugmail Yes, only _one_ socket and the plugin does not allow changing it's path, so you're safe assuming it is available from `socket:/var/run/haproxy.socket`. :)

**Comment by mimugmail** [comment]
Can we close this? It's already included

**Comment by ikke-t** [comment]
Thanks for adding this! Looking forward to try it, once it becomes available in released version.
