### ISSUE TITLE
Additional patch required for miniupnpd genconfig.sh

### ISSUE THREAD

**Issue by rootwyrm** [opnsense/plugins#709]
https://gist.github.com/rootwyrm/f9ccfd9e97c3a606093751e7256b1e4f

Preliminary patch here. This addresses the issue of genconfig.sh throwing errors attempting to detect firewall type, and should fix multicast problems by adding `HAVE_IP_MREQN` which sets the multicast struct to be post-FreeBSD 7.0 compatible. `HAVE_IP_MREQN` requires additional testing. This patch is also predicated on ${OS_NAME} being `opnsense`.

If there is desire, I can throw something together to enable MULTIPLE_EXTERNAL_IP as well (this is very beta, so probably should be a separate port - `miniupnpd-beta`?)

**Comment by rootwyrm** [comment]
Pull req for ports here: https://github.com/opnsense/ports/pull/61

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
