### ISSUE TITLE
OpenAppId in suricata

### ISSUE THREAD

**Issue by teliz** [opnsense/plugins#718]
hello,
It is possible to activate openappid in suricata to make blockages in the application layer ?

thanks :)

**Comment by mimugmail** [comment]
https://github.com/opnsense/rules

Will be released with one of the next versions.

OpenAppId only works with Snort

**Comment by fichtner** [comment]
Yep, let's close this. @mimugmail will continue to work on the rules and they should hit 18.1.11.

**Comment by teliz** [comment]
thanks :)
