### ISSUE TITLE
HAproxy floating IP (Need Help)

### ISSUE THREAD

**Issue by micruzz82** [opnsense/plugins#719]
Hi All

Can someone advise me on how I can use the HAproxy plugin to setup a floating IP between 2 instances to HAproxy loadbalancers.

I didn't want to get into the shell etc and configure things that way.

Can Opnsense natively handle floating IP's between 2 peering devices.

Would appreciate some help on setting this up.

Thanks in advance.

**Comment by fraenki** [comment]
To configure floating IPs in OPNsense, please see the [CARP documentation](https://docs.opnsense.org/manual/how-tos/carp.html).
