### ISSUE TITLE
net/zerotier: Performance under Hyper-V

### ISSUE THREAD

**Issue by StrikerTwo** [opnsense/plugins#721]
I have several dedicated Hyper-V servers across Hetzners datacenters. Each server has a gigabit uplink and an OPNsense virtual machine to do routing and VPN.
Hetzner now have a feature to connect the servers with a dedicated VLAN. So I added a VLAN interface to each OPNsense VM. I can copy files over this connection (Hyper-V host 1 -> OPNsense 1 -> VLAN -> OPNsense 2 -> Hyper-V host 2) with near wirespeed (100 MByte/s +).

So far so good, but unencrypted traffic on semi-public interfaces is bad. So I added the zerotier plugin to each OPNsense VM and connected them to a ZT network.
Over this connection (Hyper-V host 1 -> OPNsense 1 -> Zerotier -> OPNsense 2 -> Hyper-V host 2) I get around 2-3 MByte/s. Which is bad.
If I install Zerotier on the hosts directly (Hyper-V host 1 -> Zerotier -> Hyper-V host 2) I get 100 MByte/s again. But eventually I will need firewall rules and the Windows firewall is laughingly bad to configure.

Ideas? 
Network, drivers, OPNsense and Hyper-V all should not be the issue because it works perfectly over the VLAN connection (which has a MTU of 1400 to boot).
Zerotier shows direct paths to all peers (as far as I can tell), so relaying should not be the problem. Port 9993 is allowed in all firewall rules.

**Comment by mimugmail** [comment]
Try to set the MSS on LAN/WAN interfaces to 1300 for testing ...

**Comment by StrikerTwo** [comment]
Thanks for the idea, unfortunately that did not improve things...

**Comment by laduke** [comment]
is something funky with 1.2.10? 

Someone in #zerotier irc with a Celeron(R) CPU J3060 @ 1.60GHz (2 cores) says zerotier is at idling 100% CPU. 

Sorry to hijack a Hyper-V thread if it is a Hyper-V related thing.

**Comment by fichtner** [comment]
Timeout.
