### ISSUE TITLE
net/haproxy: Bind frontend to interface

### ISSUE THREAD

**Issue by jpawlowski** [opnsense/plugins#722]
I would like the frontend to be listening independent from an IP address but to all IP addresses of a specific interface. Main use case would be to listen to an interface with dynamic IP address, like with PPP dial-up connections (xDSL).

From the HAproxy documentation, I think one should be able to enter 0.0.0.0:<port> and :::<port> as listen address first, and then add something like "interface pppoe0". I tried to add this through the Advanced SSL settings under Bind options but it seems dynamic content is not excepted there, see screenshot:

![image](https://user-images.githubusercontent.com/75446/42323684-44d32eac-8061-11e8-876c-9a2f121bafec.png)

If such settings would work, it might even be nicer to just select one (or more) interfaces from a dropdown menu as an alternative to the "Bind address" text field so it does not get mixed with the SSL Advanced Settings (even though in the generated config file it will belong together).

**Comment by jpawlowski** [comment]
Realized that "advanced mode" would allow me to add something to the bind options at the right place.
However, interface support was not build in to this version on OPNsense it seems :-(

> 'interface' option is not implemented in this version (check build options).

**Comment by fichtner** [comment]
FreeBSD port doesn't seem to be aware of this option, at quick glance nothing that seems to match the description here https://github.com/opnsense/ports/blob/master/net/haproxy-devel/Makefile#L26

**Comment by fraenki** [comment]
From the [HAProxy documentation](http://cbonte.github.io/haproxy-dconv/1.8/configuration.html#interface):

> This is currently only supported on Linux.

Unless HAProxy adds support for this feature on FreeBSD, there's nothing we can do. :(

**Comment by Passaita** [comment]
You can achieve this by using a virtual IP.
Interfaces -> Virtual IPs -> Setting -> ADD
Mode: IP Alias
Interface: Loopback
Network/Address: 127.1.2.3/32
Deny service binding: Uncheck
VHID Group: leave empty

Firewall -> Aliases -> ADD
Name: HAProxy
Type: Port(s)
Content: 80 443

Firewall -> NAT -> Port Forward -> ADD
Interface: WAN
Protocol: TCP
Destination: WAN address
Destination port range FROM: HAProxy TO: HAProxy
Redirect target IP: Single Host or Network: 127.1.2.3
Redirect target port: HAProxy

Services -> HAProxy -> Settings -> Vitrual Server -> Public servers -> edit your public server
Listen Addresses: 127.1.2.3:443
