### ISSUE TITLE
net/haproxy: just stops

### ISSUE THREAD

**Issue by StrikerTwo** [opnsense/plugins#735]
About every 3-4 days I get complaints about our web server being offline.
Every single time the HAProxy service is just stopped (stop symbol on the dashboard). No entries in the log file, at least nothing I can see in the GUI.
If I just start the service, it works again until the next time.

Where can I start debugging?

**Comment by fraenki** [comment]
Please upgrade to the current release (OPNsense 18.1.11 and HAProxy 1.8.12), it contains multiple fixes for crashes in HAProxy.

**Comment by StrikerTwo** [comment]
Ooops, I thought I already did - but apparently I forgot that box, it's still on 18.1.9.
Will do, thanks!
