### ISSUE TITLE
www/nginx: add HTTPS upstream support

### ISSUE THREAD

**Issue by fabianfrz** [opnsense/plugins#749]
report by @mimugmail: add HTTPS upstream support

via: https://forum.opnsense.org/index.php?topic=9210.msg41515#msg41515

**Comment by fabianfrz** [comment]
see #762

**Comment by fabianfrz** [comment]
@mimugmail done - It is in the pull request - you may test it.

**Comment by mimugmail** [comment]
I'll try it this weekend, thx :)
