### ISSUE TITLE
net/zerotier: Restarting ZeroTier is not working and creating new tap interfaces / PORT_ERROR

### ISSUE THREAD

**Issue by virusmoere** [opnsense/plugins#751]
If restarting the zerotier service new tap interfaces are being created and zerotier-cli listnetworks outputs PORT_ERROR. It is working again after a reboot.

![port_error](https://user-images.githubusercontent.com/6796393/43128374-25894470-8f32-11e8-8904-86891ca8c39a.PNG)

OPNsense 18.1.12-amd64
FreeBSD 11.1-RELEASE-p11
OpenSSL 1.0.2o 27 Mar 2018

Manually starting the zerotier-one daemon results in:
![rename_failed](https://user-images.githubusercontent.com/6796393/43128333-0b60960c-8f32-11e8-9c6b-beea45e3f272.PNG)

New tap interfaces:
![tap](https://user-images.githubusercontent.com/6796393/43128348-162c7af6-8f32-11e8-8f93-9fe35b36b784.PNG)

**Comment by virusmoere** [comment]
If I kill the zerotier-one process, destroy the tap interface with "ifconfig zt8gk1jge8246sm destroy" and start the service again it is working fine...

**Comment by fichtner** [comment]
Timeout.
