### ISSUE TITLE
security/tinc [FR] Tinc Options and Subnets

### ISSUE THREAD

**Issue by QDaniel** [opnsense/plugins#752]
- [x] Allow Multiple Subnets in Config (Komma Separation in GUI allowed, but in Config ignored)
- [x] Automatic Add Tinc Interface IP as Subnet
- [ ] Display Status Infos z.B. Tinc Config "GraphDumpFile" and USR2 Signal
- [ ] Remove Required Attribut from Host Config Fields ( Address and Subnets )
- [ ]  Use Signals for reload Configs

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
