### ISSUE TITLE
IDS - Custom rules

### ISSUE THREAD

**Issue by b4b857f6ee** [opnsense/plugins#758]
Hi,

It's can be interesting to add a custom section to add rules from specific feed with a format choice, like .txt, .tgz (like we already have on SELKS)
from a STIX, MISP, etc...
Are you planning to do this kind of features?

Thank you

**Comment by fichtner** [comment]
You can already write your own definition XML files:

https://github.com/opnsense/plugins/blob/master/security/intrusion-detection-content-snort-vrt/src/opnsense/scripts/suricata/metadata/rules/snort-vrt.xml

**Comment by b4b857f6ee** [comment]
Ok i will try.

Thank you

**Comment by mimugmail** [comment]
@b4b857f6ee do you need help with this or not needed anymore?

**Comment by b4b857f6ee** [comment]
Sorry, i cannot test for now, i am going to try right now.

**Comment by b4b857f6ee** [comment]
It is possible with the  Key in the uri?
For exemple : <location url="https://misp.toto/download/......"/>

How can i add the header "Authorization: xxxxxxxxxxXXXXxxxxxxXXXXXx" ?

**Comment by b4b857f6ee** [comment]
It is possible with the  Key in the uri?
For exemple : <location url="https://misp.toto/download/......"/>

How can i add the header "Authorization: xxxxxxxxxxXXXXxxxxxxXXXXXx" ?

**Comment by fichtner** [comment]
It's possible, I think, let me check...

**Comment by b4b857f6ee** [comment]
Ok, or i think you can build a crontab with a wget local and the url on the xml on local web server, maybe? :)

**Comment by fichtner** [comment]
Yes, but the whole framework for what you want to do is there so why reengineer it? :)
