### ISSUE TITLE
theme/rebellion: missing some elements in 18.7

### ISSUE THREAD

**Issue by darkain** [opnsense/plugins#761]
Continuation from: https://github.com/opnsense/plugins/issues/501

With the UI changes in 18.7, some elements are no longer properly themed with Rebellion.

![reb-01](https://user-images.githubusercontent.com/2524251/43283494-ec8ea5e6-90cd-11e8-9fff-c40d298d74bd.png)
![reb-03](https://user-images.githubusercontent.com/2524251/43283495-ecab67bc-90cd-11e8-9048-250ca7de84ef.png)
![reb-02](https://user-images.githubusercontent.com/2524251/43283496-ecc501cc-90cd-11e8-9587-7d5f13fc2ef3.png)

**Comment by darkain** [comment]
`<ul class="tokens-container form-control" tabindex="0" style="width: 334px;"><li class="token" data-value="192.168.10.0/24"><a class="dismiss"></a><span>192.168.10.0/24 </span></li><li class="token-search" style="width: 17px;"><input autocomplete="off"></li></ul>`

Tokenized boxes have been updated in 18.7. I'm not sure what the HTML/CSS was before, since all of my boxes have already been pushed to the RC2 build. This is most evident from the last screen shot where it is a white box with a light gray element inside with a slightly less light gray text that is difficult to read (impossible to read on lower quality LCD screens if not seen from the correct viewing angle)

**Comment by marjohn56** [comment]
Issued PR #764
