### ISSUE TITLE
security/acme-client: new release in 18.7.1, including acme.sh 2.7.9?

### ISSUE THREAD

**Issue by fichtner** [opnsense/plugins#768]
Yes/No/Maybe :)

**Comment by fraenki** [comment]
Go! :)

**Comment by fichtner** [comment]
@fraenki ok, just to be sure you are ok with / aware of shipping changes that were included by @DonMcCoy  ?

**Comment by DonMcCoy** [comment]
It will be good if you upgrade it to 2.7.9 as there's support for new DNS API, I can write it later on.

**Comment by fraenki** [comment]
> ok, just to be sure you are ok with / aware of shipping changes that were included by @DonMcCoy

Positive :)

**Comment by fichtner** [comment]
thanks guys!
