### ISSUE TITLE
security/acme-client missing intermediate certificate from installed certificate

### ISSUE THREAD

**Issue by QuentinC** [opnsense/plugins#77]
Hello,

I've successfully installed a LE certificate using the opnsense plugin.
It seems to work, but some clients cannot validate it.

From different SSL checking sites, it seems that the certificate chain is incomplete:
https://www.ssllabs.com/ssltest/analyze.html?d=home.o2r.fr
(same here: https://cryptoreport.websecurity.symantec.com/checker/ and here: https://www.digicert.com/help/ ).

Can you add all the required certs to the full chain ?

Thanks,

Quentin

**Comment by fraenki** [comment]
Hi @QuentinC, please provide the steps to reproduce this issue. I've run the same tests for our LE certificates without any issues.

Please note that the LE plugin imports the certificate as well as the whole chain to `System -> Trust -> Certificates`. If you choose `export user cert` on the same page you'll notice that the file contains your LE certificate as well as the CA certificate for the LE Authority.

Depending on which application uses this certificate you may need to split these two certs into separate files. Which application are you using? Do you use it for the OPNsense WebGUI or for another application?

**Comment by smindorf** [comment]
Hi,
I've the same issue. I've created a LE Certificate for the web UI of opnsense but the Intermediate certificate is missing.

`openssl s_client -connect host.example.com:1234`

```
CONNECTED(00000003)
depth=0 CN = host.example.com
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN = host.example.com
verify error:num=27:certificate not trusted
verify return:1
depth=0 CN = host.example.com
verify error:num=21:unable to verify the first certificate
verify return:1
---
Certificate chain
 0 s:/CN= host.example.com
   i:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
.....
   Start Time: 1489744208
    Timeout   : 300 (sec)
    Verify return code: 21 (unable to verify the first certificate)
---
closed
```

Regards,
Sören

**Comment by fraenki** [comment]
Hi Sören,

thanks for the report! I can't reproduce this, I've tested the certificates with both HAProxy and OPNsense WebGUI (lighttpd) and it works without any issue. How do you use the certificate? Did you export the certificate and use it somewhere else, or do you use it on your OPNsense firewall? Which application or (OPNsense) plugin does not work with the generated certificates?

Thanks
- Frank

**Comment by smindorf** [comment]
Hi Frank,

you are welcome.
I've created the certificate on the OPNSense firewall with this plugin and I use this certificate exclusive on the OPNSense firewall for the Web UI.
It is the only certificate from LE on this firewall.

For example the firefox is not working, because the intermediate is missing.

Regards,
Sören

**Comment by fraenki** [comment]
Hi Sören,

I still think it's strange that it's not working for you (and few others), but I think this will be fixed once #84 is implemented. I'm working on this :)

Regards
Frank

**Comment by fraenki** [comment]
OK, after completing #84 I was finally able to reproduce and fix this.

> Without the fix:
> 
> Certificate chain
>  0 s:/CN=test.example.com
>    i:/CN=Fake LE Intermediate X1
> 
> NEW result:
> 
> Certificate chain
>  0 s:/CN=test.example.com
>    i:/CN=Fake LE Intermediate X1
>  1 s:/CN=Fake LE Intermediate X1
>    i:/CN=Fake LE Root X1

**Comment by smindorf** [comment]
I'll wait till next release to check if it is working.

Thanks a lot,
Sören

**Comment by smindorf** [comment]
@fraenki 
After upgrade to opnsense 17.1.4 and forcecing the LE Certificate renewal, Firefox will now trust the certificate.

Thanks
Sören

**Comment by QuentinC** [comment]
Hello,

Problem solved for me too ! 
Thanks :)

**Comment by fraenki** [comment]
Great, thanks for your feedback. :+1:
