### ISSUE TITLE
net-mgmt/Telegraf: Support output to Elasticsearch

### ISSUE THREAD

**Issue by alesnav** [opnsense/plugins#780]
Hello,

Telegraf plugin does already support output to Influx, Graphite and Graylog. Can you please add support to use the [native output to Elasticsearch](https://github.com/influxdata/telegraf/tree/master/plugins/outputs/elasticsearch)?

Thanks,
Best regards

**Comment by mimugmail** [comment]
@alesnav With 18.7.1 you can try to install:

pkg install os-telegraf-devel

via Console and check if it works for you.
If yes we can release to stable.

**Comment by alesnav** [comment]
Hello,

I have just tested it with a real elasticsearch cluster and does work fine.

I think that it can be merged then :)

Thanks!

**Comment by mimugmail** [comment]
@fichtner OK then plz for 18.7.2 :)

**Comment by fichtner** [comment]
ok, moved to stable/18.7
