### ISSUE TITLE
net-mgmt/telegraf - input/Disk Ignore FS does not handle multiple FS types

### ISSUE THREAD

**Issue by Daryes** [opnsense/plugins#784]
OPNsense version : 18.7
os-telegraf plugin : 1.4.0 (package telegraf 1.6.3)

In the telegraf service panel => input, the "Disk Ignore FS" option only handle a single FS type.
Specifying multiple entry, like : `tmpfs, devfs` will result in the following configuration : `ignore_fs = [ "tmpfs, devfs" ] `  
Telegraf is expecting the following instead : `ignore_fs = [ "tmpfs", "devfs" ] `  

Still, there's a way to bypass this limitation by using this value in the GUI panel : `tmpfs", "devfs`
Works perfectly, but not natural.

**Comment by mimugmail** [comment]
@fichtner ATM this is type TextField, would make more sense to make it Tokenize and do a for loop in templating. Does this require any migration script or is model bump also fine?

**Comment by fichtner** [comment]
No bump necessary. It's required N, isn't it?

**Comment by mimugmail** [comment]
It's N but the FieldType changes ..

**Comment by fichtner** [comment]
the field type is for input, model is for saving. in both the value does not change when you change the field type, and validation is still ok :)

**Comment by mimugmail** [comment]
@Daryes can you check if this syntax also works?

ignore_fs = ['tmpfs','proc']

I use it for ping so it could be compatible too ...

**Comment by Daryes** [comment]
It works.  
yaml came from python, so using ' ' or " " is accepted when declaring a string, even if it's an array : [ "a", 'b' ] or [ 'a', "b" ] are the same.

For the record, you can check it yourself with the default opnsense install, using :
`/usr/local/bin/telegraf --test --config /usr/local/etc/telegraf.conf`

Telegraf willl output the data only to stdout and exit.  
You can also use a short conf file, restricted to the `[agent]` block and only the `[[input.XXX]]` you want to check, it is enough for the `--test` arg

**Comment by mimugmail** [comment]
@Daryes have you checked latest version if it fits your needs? Then we can close this one ...

**Comment by Daryes** [comment]
I wasn't aware is was available in the new version.
Just checked, it's working fine, thx

**Comment by mimugmail** [comment]
Cool, would you close this one please? :)
