### ISSUE TITLE
net-mgmt/telegraf - global tag support

### ISSUE THREAD

**Issue by Daryes** [opnsense/plugins#785]
OPNsense version : 18.7
os-telegraf plugin : 1.4.0 (package telegraf 1.6.3)

The current OPNsense telegraf service panels don't allow to specify Telegraf global tags.  
It would be helpful to have an entry in the Telegraf General panel, allowing this sort of example in the final telegraf.conf file :
```
[global_tags]
  dc = "UK-LON"
  country = "UK"
  city = "LON"
  virtual_type = "vmware"
  virtual_role = "guest"
  os_family = "freebsd"
  os_distrib = "opnsense"
```
All the tags will be attached to each measurements returned by telegraf, allowing a more precise and generic filtering.

Tags use the following syntax under the `[global_tags]` section :   tag_name = "tag_value"
Order is irrelevant.  
Afaik, both are always handled as string.  
Spaces are also supported, but not recommended (escaping might be required).

**Comment by mimugmail** [comment]
@Daryes the keys, or tag names are also individual? So I could add
freebsd_version = "11.1"

**Comment by Daryes** [comment]
@mimugmail : yup, each tag is independent from the other. You can add any number of tag, with the name and value you want : all the tags in [global_tags] will be added to all returned metrics.  
Up to the user to make use of the available tags when filtering the data in the SQL query : a single one can be used if it's enough even if there are 10 different tag available.

**Comment by mimugmail** [comment]
Nice, wasn't aware of. I'll implement it the next two weeks when I find some time.

**Comment by mimugmail** [comment]
I'll start on Monday, sorry, totally forgot about you :/

**Comment by Daryes** [comment]
Just tested, working fine.
There's a point that would require an update, still :  currently the UI allow to enter duplicate tag names, while telegraf doesn't allow them : 
````
toml: line 8: key 'virtual_role' is in conflict with line 7
````
This error is only visible in `/var/log/telegraf/telegraf.log`, so it's not noticeable immediately. 


Also, some UI enhancements that would be welcomed : 
- having the list ordered by tag name
- allowing names and values with spaces around at the creation, and trimming them (copy/paste) instead of throwing a `text validation error`
- any possibility to reuse internal values as variables ? For example, returning OPNSense version with $opn_version (or similar name)

**Comment by mimugmail** [comment]
I'll have a look @Daryes .. when space on tag name is allowed, do we also need to put the name in quotes?

**Comment by Daryes** [comment]
The UI improvement I was talking about would be to trim the leading and trailing spaces from the name and value, to be easier on copy/paste data, nothing more. Sorry if it wasn't clear.  

On the whole spaces subject, Influxdb states :  spaces and commas must always be escaped by a backslash (\  )  
So this is not allowed : `tag_test = "this is a test"`, while this will work `tag_test = "this\ is\ a\ test"`  
Personally, I'm more along not allowing spaces on a tag name, due to the escaping nightmare while building a SQL query. But to not be closed on this, I would take the name and values, trim the leading and trailing spaces only, keep the rest as is, and let the user handle the escaping, with an additional line on this subject in the help tooltip.

**Comment by fichtner** [comment]
Let’s simply reject spaces and commas and backslashes, the unescaped use is forbidden anyway and escaping is difficult to get 100% right. I don’t believe automatic trimming is good: in password fields it’s unwelcome for example and will may lead to bugs in general compared to easily fixed user-side validation errors.
