### ISSUE TITLE
sysutils/monit: Allow source address to be specified for Ping check

### ISSUE THREAD

**Issue by ruffy91** [opnsense/plugins#787]
I want to ping the remote firewall on a IPsec tunnel.
I need to specify a source address as it is not possible to ping directly from one firewall to another over IPsec (https://github.com/opnsense/core/issues/1624)

**Comment by fichtner** [comment]
monit is now part of core :D

**Comment by ruffy91** [comment]
Moved to https://github.com/opnsense/core/issues/2632
