### ISSUE TITLE
security/tinc: Adding tinc interface as Gateway

### ISSUE THREAD

**Issue by BiasF** [opnsense/plugins#79]
Hi,

If you want to reach networks behind OPNSense, which are not part of the TINC-Subnet, you have to create routing rules.
But it's not possible, because you cant't choose the tinc0 as GW Interface. The tinc0 interface is not shown in the GUI (except on the firewall site)

Greetings
Tobias

**Comment by mimugmail** [comment]
The tinc-up script would need some tweaks like in http://ostolc.org/site-to-site-vpn-with-tinc.html

Then you also would not have the constraint to have a supernet with subnets in it.

**Comment by mimugmail** [comment]
@fichtner @BiasF with the prevent removal feature in interface configuration you can do this with tinc interfaces, I think this one can be closed.

**Comment by fichtner** [comment]
Hmm, but is tinc listed for assignments?

**Comment by mimugmail** [comment]
It's listed here:

https://github.com/opnsense/core/commit/865c3d6a377c43a53bdc792c467a926a71f28b2a#commitcomment-30516005

**Comment by fichtner** [comment]
Yes, but tinc has been listed there for ages. But that part is only so that boot doesn’t break. I guess tinc still isn’t listed in untefaces assignments?

**Comment by fichtner** [comment]
Ok, then there’s nothing left to be done here. Thanks!
