### ISSUE TITLE
security/acme-client: OCSP stapling is ALWAYS enabled?

### ISSUE THREAD

**Issue by fraenki** [opnsense/plugins#794]
split from #753:

> Is it possible that the plugin currently behaves as if OCSP stapling is ALWAYS enabled?
> 
> I have the checkbox definitely NOT set but the cert retrieved DOES contain the 1.3.6.1.5.5.7.1.24 TLS extension, causing my Firefox to reject connection with MOZILLA_PKIX_ERROR_REQUIRED_TLS_FEATURE_MISSING because OPNSense's lighttpd doesn't support OCSP stapling.

**Comment by pief** [comment]
Incredibly fast! Thank you very, very much!

**Comment by fraenki** [comment]
@pief I forgot to ask to you try the fix. You may do so by running the following command on the CLI:

```# opnsense-patch -c plugins  b817a41```

**Comment by DonMcCoy** [comment]
That's sad @fraenki after I found the bug now to come back here to see that it's already fixed, that was fast yeah. xD

**Comment by pief** [comment]
Yes, the fix seems to work for me, thank you!

**Comment by afontenot** [comment]
I'm having this problem on an up to date OPNSense installation. I don't have the OCSP checkbox checked, but after the most recent cert renewal (Sep 17), I get the `MOZILLA_PKIX_ERROR_REQUIRED_TLS_FEATURE_MISSING` error in Firefox with `security.ssl.enable_ocsp_must_staple` set to true. 

Anyone else have this problem show up for them again, or should I file a new bug?
