### ISSUE TITLE
REQUEST:  NUT Widget for Dashboard

### ISSUE THREAD

**Issue by waydavis** [opnsense/plugins#803]
Would be nice to have a nut widget for the dashboard like PF has.

**Comment by mimugmail** [comment]
https://github.com/networkupstools/nut/issues/7

**Comment by Overlawd** [comment]
Any update on this.  I just moved over from pfsense where a widget works well.

**Comment by phaze75** [comment]
I would like to back this feature request. Maybe, the new GUI technology introduced with 24.7 for the dashboard could mitigate the risk/issue @mimugmail pointed out initially? I'm no expert though.

**Comment by cloudynetwork** [comment]
Yes please. I would like this also.

**Comment by phaze75** [comment]
It has already been implemented in the last version of 2024 and is available. Just install the latest release and activate it in the dashboard settings.
