### ISSUE TITLE
MULTIPLE UPS on ONE OPNsense box

### ISSUE THREAD

**Issue by waydavis** [opnsense/plugins#804]
I have TWO UPS's THAT ARE NOT CONNECTED TO COMPUTERS that I would like controlled by one instance of OPNsense via the USB ports.   If there is a way to do that, I've not found it. :-(

**Comment by mimugmail** [comment]
Is this with the plain NUT tools possible?

**Comment by mimugmail** [comment]
Any news @waydavis ?

**Comment by waydavis** [comment]
none.

**Comment by mimugmail** [comment]
Do you want to investigate some time or close for now?

**Comment by waydavis** [comment]
You're asking ME because?  I asked the original question.  I'm a end-user.  If I knew what, where, or how, I would have posted a solution instead of the question.

**Comment by mimugmail** [comment]
You could Plug in both cables and Post the last 50 lines of system.log. When both are the same driver we perhaps can configure  both ports. Cant reproduce since I dont have 2 UPS

**Comment by mimugmail** [comment]
Close? I don't have 2 UPS and won't have 2 in future. Not able to test ...

**Comment by Nox-404** [comment]
Hello, can this be reopened ?

**Comment by mimugmail** [comment]
If you can implement this via cli and conf I can try to add it to gui

**Comment by Nox-404** [comment]
I won't be able to work on that this month but I can give it a try in July.
I've never worked on opnsense plugins before and my PHP skills are close to nonexistent but why not.

As for the issue, via shell I used `nut-scanner -U` and piped it to the `ups.conf` file, I also added one `MONITOR` line for each UPS and restarted `nut` using the `rc.d` file.
Doing so made the UPS metrics for both UPS via `upsc nutdevX@opnsense-ip:3493` (X -> device number).

**Comment by Nox-404** [comment]
Also it would be great to be able to specify the behavior and thresholds when the UPS battery goes down

**Comment by Jaharmi** [comment]
I am also interested in this. I could supply information for two of the UPS connected by both USB and via network.

**Comment by jwest1024** [comment]
This is a long-standing issue with opnsense. NUT is a very capable application, but opnsense only exposed 5% of it through the opnsense UI. No support for multiple ups's. No support for users file, no notify commands, the service modes are not all implemented, and the service modes that *are* implemented are merged in an odd way. If opnsense just implemented a couple "additional command options" and/or .conf file addition windows, they could have moved from 5% exposed features to 6% exposed features, but at least it would have served most use-cases. There are a lot of apps in the library that probably shouldn't be run on your router, but NUT is one that makes a lot of sense to do that way. Sad that the UI layer gets rid of much of the usefulness. The really sad part is, this is 100% a UI modification. No "coding". Just add fields and windows in the UI so they are preserved  on update. I'm not a UI guy or I'd have done it already. If interested in the above, I highly recommend people take a look at superiorone/nut-webgui as it not only provides an awesome gui, but exposes an api to accomplish much of what opnsense "hides". Adding nut-webgui (separately, along WITH opnsense/nut) solves most of these issues with the exception of multiple ups's being connected to once instance. That is a opnsense limitation, not a nut limitation.
