### ISSUE TITLE
MultiWAN and monitoring

### ISSUE THREAD

**Issue by A888R** [opnsense/plugins#810]
Hello!
MultiWAN uses monitoring IP over ICMP.
Please, add monitoring over HTTP requests (maybe code 200) оr another mechanism.
Thanks!
Sorry for my English.

**Comment by A888R** [comment]
@fabianfrz I no need monitor server health, I need monitoring gateways for MultiWAN

**Comment by fabianfrz** [comment]
@A888R yes but that's what ICMP is for - send a short packet (ICMP echo request also known as ping) and get an answer (ICMP echo response). What's wrong with it?
It also does not involve applications. If it involves L7, it will probably calculate incorrect RTTs etc.

**Comment by A888R** [comment]
@fabianfrz I know what ICMP.  My network have more LANs (isolated) over internet provider and ICMP blocked. I need an alternative to ICMP (http requests?) for monitoring gateways.

**Comment by fabianfrz** [comment]
If you block ICMP it is your fault - remove the stupid rule and it should work.

**Comment by fichtner** [comment]
Easy guys, arguing is not very useful.

FWIW, I don't fully understand the plugin request. Monit integration allows you to ping targets of your liking and get notifications when they disappear. The old system notifications will tell you when a gateway is down or up or has packet loss?

**Comment by A888R** [comment]
@fichtner ICMP/ping blocked in external WAN/LAN. I need monitoring gateways for working MultiWAN. How Monit solve my problem?

**Comment by fichtner** [comment]
I still don't understand. How do you want to monitor without ICMP?

**Comment by fichtner** [comment]
If you want to do TCP/HTTP health checks, monit can probably do it as well...

**Comment by A888R** [comment]
Yep. In System / Gateways / Single config: **Alternative monitor IP**
```
Enter an alternative address here to be used to monitor the link.
This is used for the quality RRD graphs as well as the load balancer entries.
Use this if the gateway does not respond to ICMP echo requests (pings).
```
I'm interested monitoring TCP/HTTP health checks for working MultiWAN.

**Comment by mimugmail** [comment]
AFAIK gateway monitoring works via apinger/dpinger and this is only capable to do icmp. 
You can to basic monitoring for http codes but it wont hook into gateway balancing code.
