### ISSUE TITLE
mail/postfix: add support for different smtp listening port

### ISSUE THREAD

**Issue by metzgerd** [opnsense/plugins#812]
Hello,

is it possible to add a field for postfix in the gui for a new listening port? Actually I need to change the port in the shell each time the configuration in the gui is changed.

root@OPNsense:/usr/local/etc/postfix # cat master.cf | grep smtpd
#smtp      inet  n       -       n       -       -       smtpd
2525      inet  n       -       n       -       -       smtpd

Many thanks
Dirk

**Comment by metzgerd** [comment]
My main postfix server is running at home behind the DSL providers dynamic IP range which is on the blacklist.
I've a small virtual server with a fixed IP in the cloud.

I use haproxy on the virtual server to catch all incoming mails, imap, outgoing client mails, ... and proxy to my home postfix.
I use postfix on the virtual server to proxy all outgoing mails from my home postfix via the virtual server.

The main issue I've with the outgoing client mails. I could also change all clients to use another port ...

**Comment by mimugmail** [comment]
Why don't you use portforward 2525 to 25?

**Comment by metzgerd** [comment]
haproxy is listening on port 25 on the virtual server. postfix can not listen on 25 too.

It's ok. I can stay with the option changing the config in the shell. It's not that often that I'll do config changes / software updates.
