### ISSUE TITLE
How to best create a PR for a second plugin without involving the first?

### ISSUE THREAD

**Issue by ndejong** [opnsense/plugins#817]
I currently have a PR for plugin "Configuration Sync" that syncs the OPNsense configuration to S3 compatible storage via this PR - https://github.com/opnsense/plugins/pull/777 - I now have a second plugin called "Autossh" for creating and automatically persisting SSH based tunnels and would like to submit.

In other situations I would have submitted each on their own branch which would keep the PRs separate from one another.

Looking at the branches in this repo I can only see release based branch names so it does not seem appropriate to submit under a branch - I tried making a second clone of the repo to establish separation however this seems to not be allowed through Github - I'm not entirely sure how to handle this situation.

For the OPNsense team benefit so the plugin submissions remain separate - how would you like me to go about creating a PR for you with this second plugin without involving the first?

**Comment by mimugmail** [comment]
Normally you fork from master, create local new branch and then PR to OPN master.

**Comment by ndejong** [comment]
Ahh - and thus keeping the separation within my repo-clone - this makes sense - thanks for the rapid response
