### ISSUE TITLE
security/acme-client: Add support for more DNS providers from latest acme.sh

### ISSUE THREAD

**Issue by fkling** [opnsense/plugins#82]
`acme.sh` [added more DNS validators](https://github.com/Neilpang/acme.sh/tree/e538a13e2854cc34b91a26838128e6b6859a5e83/dnsapi) recently, including linode which I'd love to use.

I'd be happy to provide a PR myself if someone could point me to instructions for how to test my changes. Or does it suffice if I just add the new files from/in the `dnsapi/` folder and make the corresponding changes in the UI and PHP files?

Thank you!

**Comment by fraenki** [comment]
It's probably a good idea to update [our copy of acme.sh](https://github.com/opnsense/plugins/blob/master/security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/acme.sh) and all DNS hooks when adding a new DNS provider.

To add support for new DNS providers you need to add them to the UI/MVC files, but you also need to add [a few lines of PHP code](https://github.com/opnsense/plugins/blob/master/security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/certhelper.php#L572-L573) to make it work.

> I'd be happy to provide a PR myself if someone could point me to instructions for how to test my changes. 

Just fork the repo and apply your changes within a feature branch. You may want to use `opnsense-patch` to apply and test your changes on OPNsense.

If you can come up with a PR I'd love to do the review.

**Comment by fkling** [comment]
So, I made some changes (see https://github.com/fkling/plugins/commit/95c8712bd98f64b8d64a21c30d710429ed5abab5), but I'm not able to use `opnsense-patch` to apply the changes. I'm getting the following:

```
root@OPNsense:/ # opnsense-patch -a fkling -r plugins 95c8712bd98f64b8d64a21c30d710429ed5abab5
Hmm...  Looks like a unified diff to me...
The text leading up to this was:
--------------------------
|From 95c8712bd98f64b8d64a21c30d710429ed5abab5 Mon Sep 17 00:00:00 2001
|From: Felix Kling <felix.kling@gmx.net>
|Date: Sun, 5 Mar 2017 19:09:34 -0800
|Subject: [PATCH] Update acme
|
|---
| .../OPNsense/AcmeClient/forms/dialogValidation.xml |   78 +
| .../app/models/OPNsense/AcmeClient/AcmeClient.xml  |   29 +
| .../opnsense/scripts/OPNsense/AcmeClient/acme.sh   | 1514 +++++++++++++++-----
| .../scripts/OPNsense/AcmeClient/certhelper.php     |   20 +
| .../scripts/OPNsense/AcmeClient/dnsapi/dns_ali.sh  |    2 +-
| .../scripts/OPNsense/AcmeClient/dnsapi/dns_aws.sh  |    8 +-
| .../scripts/OPNsense/AcmeClient/dnsapi/dns_cx.sh   |    4 +-
| .../scripts/OPNsense/AcmeClient/dnsapi/dns_cyon.sh |  328 +++++
| .../scripts/OPNsense/AcmeClient/dnsapi/dns_do.sh   |  148 ++
| .../OPNsense/AcmeClient/dnsapi/dns_freedns.sh      |  375 +++++
| .../AcmeClient/dnsapi/dns_gandi_livedns.sh         |  123 ++
| .../scripts/OPNsense/AcmeClient/dnsapi/dns_gd.sh   |    2 +-
| .../OPNsense/AcmeClient/dnsapi/dns_lexicon.sh      |    8 +-
| .../OPNsense/AcmeClient/dnsapi/dns_linode.sh       |  183 +++
| .../scripts/OPNsense/AcmeClient/dnsapi/dns_lua.sh  |   43 +-
| .../scripts/OPNsense/AcmeClient/dnsapi/dns_me.sh   |   35 +-
| .../scripts/OPNsense/AcmeClient/dnsapi/dns_ovh.sh  |    6 +-
| 17 files changed, 2538 insertions(+), 368 deletions(-)
| create mode 100644 security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/dnsapi/dns_cyon.sh
| create mode 100755 security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/dnsapi/dns_do.sh
| create mode 100755 security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/dnsapi/dns_freedns.sh
| create mode 100755 security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/dnsapi/dns_gandi_livedns.sh
| create mode 100755 security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/dnsapi/dns_linode.sh
|
|diff --git a/security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml b/security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
|index 4109e2c..f9dd582 100644
|--- a/security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
|+++ b/security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
--------------------------
No file to patch.  Skipping...
Hunk #1 ignored at 190.
Hunk #2 ignored at 243.
Hunk #3 ignored at 342.
3 out of 3 hunks ignored--saving rejects to acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml.rej
Can't create acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml.rej, output is in /tmp/patchrnlKeBewlnE: No such file or directory
Hmm...  The next patch looks like a unified diff to me...
[...]
```

It seems the folder structure of the plugin repository is different from how it is actually deployed. Is there anything special I have to do to make it work for plugins?

Should I still create a PR for the changes I have so far?

**Comment by fichtner** [comment]
permissions need a fix here:

create mode 100644 security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/dnsapi/dns_cyon.sh

Doesn't really matter if opnsense-patch works or not: it may just have issues with conflicting files or the plugin wasn't previously installed... some form of merge conflict one way or another. as long as you have changes and provide a PR we can add it to our repository in a clean step. :)

**Comment by fichtner** [comment]
Already merged.
