### ISSUE TITLE
sysutils/smart: periodic update of drivedb.h

### ISSUE THREAD

**Issue by beren12** [opnsense/plugins#821]
/usr/local/share/smartmontools/drivedb.h can be updated with sudo update-smart-drivedb --no-verify or wget https://www.smartmontools.org/browser/trunk/smartmontools/drivedb.h?format=txt

I guess the correct thing to do is check the gpg sig of the file…

**Comment by beren12** [comment]
No, I do not. drivedb.h is a runtime file that is used to determine what the smart attributes are for devices. There is even an updater tool included with the package. The problem is updates revert it and there is no way to update it from the gui.

**Comment by fichtner** [comment]
Hmm, @fabianfrz was a little trigger-happy. we discussed this on IRC, there's a script to update this file, it is not a header file for C...

**Comment by beren12** [comment]
Fixed the title, damn autocorrect…

**Comment by beren12** [comment]
It is a runtime configuration file for smartctl for device attributes

**Comment by fichtner** [comment]
The solution for the package issue seems to be "pkg check -r smartmontools" to recompute the file. Updates will undo the update, but there's not a lot we can do in these cases.
