### ISSUE TITLE
security/acme-client: add manual method validation

### ISSUE THREAD

**Issue by oasisck** [opnsense/plugins#823]
Hi,
I have issue with validation methods with OVH. With pfSense I could issue a certificate by a GUI manual method validation, by adding register TXT in zone with secret text inside, but I don't find this in your let's encrypt plugin validation method.
Can you add with please ?
Thanks

**Comment by fraenki** [comment]
I have no plan to implement this, we already support almost 50 ways to validate a Let's Encrypt certificate.

I'm closing this issue now, but if someone wants to work on this, please let me know and I'll gladly reopen this issue (or simply submit a pull-request).
