### ISSUE TITLE
os-telegraf enable prometheus output

### ISSUE THREAD

**Issue by sachaz** [opnsense/plugins#825]
All Telegraf metrics can be exported to Prometheus, we just have to enable this parameter on the telegraf's output interface (/ui/telegraf/output/index) and add a combo box for the port number

**Comment by fichtner** [comment]
silly question maybe: why not use node_exporter in the first place?

**Comment by sachaz** [comment]
this is a good question, I'll try to do a good answer
we are using the Prometheus FreeBSD node exporter for all our OPNSense Firewalls that's work fine !
 But Telegraf have a much more plugins (https://github.com/influxdata/telegraf#input-plugins). For exemple: ZFS Prometheus node exporter work only with linux (wtf !), there no pf metrics, there is no cpu temperature for FreeBSD, etc...
 So until (if it occurs) the Prometheus classical node export doesn't allow us to have such metrics on FreeBSD we use it combined with Telegraf which is much more complete.

**Comment by fichtner** [comment]
ok, thanks for the details :)

**Comment by mimugmail** [comment]
I'll add the output next week

**Comment by sachaz** [comment]
what is os-telegraf-devel ?
is it telegraf-nightly_freebsd_amd64.tar.gz ?

**Comment by fichtner** [comment]
os-telegraf-devel is the development plugin for OPNsense Telegraf plugin. The actual telegraf package is the same as the production plugin for OPNsense....

**Comment by mimugmail** [comment]
pkg install os-telegraf-devel

sachaz <notifications@github.com> schrieb am Fr., 21. Sep. 2018, 17:59:

**Comment by mimugmail** [comment]
Can we close this? I think it's fine ...

**Comment by sachaz** [comment]
not tested yet :/
