### ISSUE TITLE
security/acme-client: properly handle issuer certs

### ISSUE THREAD

**Issue by fraenki** [opnsense/plugins#84]
Currently our LE plugin does **not** import LE **CA** certificates, but instead _bundles_ them directly with the LE certificate (see https://github.com/opnsense/plugins/blob/3f1428dee4e5c4f3da5548574370996b5ee04647/security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/certhelper.php#L816-L817). Note that this is not really supported, as the OPNsense GUI shows the bundled cert as plain text when clicking on the `show certificate info` button in `System -> Trust -> Certificates`.

Maybe a better approach would be to import the LE Authority (from the LE certificate fullchain) as a new CA (if it does not exist yet) and link the LE certificate to this CA after the import. I'd use the `import_ca()` function in this case (found here https://github.com/opnsense/core/blob/4169afd16e614a418aa08d017f21258121aae32a/src/www/system_camanager.php#L33-L72).

The benefit is obviously no hackish bundled CA and likely better application support (HAProxy is able to handle the bundled CA cert properly, but other applications may not – lighttpd?).

I assume that #77 might be related to this.

**Comment by fraenki** [comment]
@fichtner Any thoughts on this?

**Comment by fichtner** [comment]
Makes sense to import it properly. It could help with VPN operation as well?

**Comment by fichtner** [comment]
But it may need a new type like "internal but handled by plugin" in cause anyone wants to issue new certificates from that CA.

**Comment by fraenki** [comment]
@fichtner you would introduce a new type to prevent people from generating new certificates from that CA, right?

**Comment by fichtner** [comment]
if we don't have a private key, we are good?!

**Comment by fichtner** [comment]
(scratch my previous ramblings)
