### ISSUE TITLE
[PLUGINS] Zabbix proxy needs 3 different packages

### ISSUE THREAD

**Issue by deZillium** [opnsense/plugins#859]
Hello,
Zabbix proxy as installed by the available plugin doesn't allow configuration updates from newer zabbix servers. The solution to this is to have 3 different os-zabbix-proxy packages (each tagged with the corresponding version) to support the three LTS releases of zabbix: 2.2, 3.0, 3.4. By extension, this means 3 different os-zabbix-agent packages as well (just to keep things nice and tidy).

This limitation is due to the proxy not syncing configuration with a zabbix server that doesn't match its version: [more info](https://www.zabbix.com/documentation/3.4/manual/appendix/compatibility)
```
It is known to be possible to start an upgraded server and have older, yet unupgraded proxies report data to a newer server (the proxies can't refresh their configuration though). This approach, however, is not recommended and not supported by Zabbix and choosing it is entirely at your own risk. For more information, see the upgrade procedure.
```
(which means that the packages will need to closely track the upstream project)

Adding insult to injury:
```
Zabbix 3.4.10 server can only work with Zabbix 3.4.10 proxies. Compatibility with proxies from other 3.4.x versions has been lost. This issue is fixed for Zabbix server 3.4.11.
```

**Comment by fraenki** [comment]
> The solution to this is to have 3 different os-zabbix-proxy packages

I don't think this is a acceptable solution – it requires to keep the plugin code between all 3 versions in sync. Not sure if it's worth the effort.

But that's just _my_ opinion. In the end the plugin maintainer @mimugmail must decide if he wants to invest the extra effort.

> this means 3 different os-zabbix-agent packages as well (just to keep things nice and tidy).

I disagree. Older/newer version os zabbix-agent work perfectly with any supported version of Zabbix server. As the current maintainer of os-zabbix-agent I'm not going to maintain 3 different versions.

**Comment by mimugmail** [comment]
Agent is compatible, Proxy only to the same version. We all agreed only to support LTS with Proxy, so 3.0 and 4.0 (when released).

**Comment by deZillium** [comment]
LTS is actually 2.2 and 3.0 (so already two versions if you are supporting LTS)

I'll forgive the 3.4 (current), since it's (supposed) to be EOL'd next month. Since 4.0 isn't yet out, I'm betting that it will be extended to LTS soon(ish).

Anyway, just reporting on what needs to be improved, no hard feelings.

**Comment by mimugmail** [comment]
When the plugin was built 3.0 was out so it was the only current version. Then there was 3.2 and 3.4 and we had a discussion how to handle this. We all agreed (from 3.0) to only support LTS. I know this is not the thing of bleeding edge guys. If you insist on 3.4 you can still install only the pkg via CLI and add the config .. this would work without any issues :)

**Comment by mimugmail** [comment]
Hm, true. I'm still for adding 4.0 and keeping 3.0 for a year or so .. it doesn't take too long now and if I remember correctly there were only 2 guys asking for proxy 3.4. Hope that's ok for you @deZillium ?

**Comment by deZillium** [comment]
Sure, if zabbix is moving to 4.0 next month(ish), I'll be upgrading a day or so after that anyway (I live on the bleeding edge, it's why my body is covered in cuts :-) ).

**Comment by deZillium** [comment]
Just FYI: Zabbix 4.0 LTS is out

**Comment by fichtner** [comment]
Yup, already mentioned here https://github.com/opnsense/tools/issues/98

**Comment by fichtner** [comment]
we are targeting 19.1 for this

**Comment by Alwaysin** [comment]
Is there a plan to add encryption settings for Zabbix with the new version? Would be nice!

**Comment by mimugmail** [comment]
There should be one already ... ?

**Comment by Alwaysin** [comment]
@mimugmail Would appreciate if I could have some guidance on this, as I didn't see any parameters related to TLS settings on the GUI. Do I maybe have to go with the CLI to configure it, as we do with our servers?

**Comment by x-jokay** [comment]
@fichtner what is the (current) status for the zabbix-proxy v4?

**Comment by fichtner** [comment]
https://github.com/opnsense/plugins/commit/3704c3b174da8788f635f1c189a70e8cbe9159f8

**Comment by fichtner** [comment]
19.1.2 or 19.1.3, but you can install it manually now...

# opnsense-code plugins
# cd /usr/plugins/net-mgmt/zabbix4-proxy
# make upgrade

**Comment by x-jokay** [comment]
Great, thank you for your work :)

**Comment by fichtner** [comment]
all credit goes to @mimugmail of course

**Comment by x-jokay** [comment]
Cleanup of the currently installed zabbix db file seems not to work but after manual intervention, the plugin works 👍
