### ISSUE TITLE
www/nginx: Export full chain as pem (if present)

### ISSUE THREAD

**Issue by fzoske** [opnsense/plugins#863]
Hi!

The nginx plugin should export the whole certificate chain (if present) and not only the certificate itself.
https://github.com/opnsense/plugins/blob/master/www/nginx/src/opnsense/scripts/nginx/setup.php#L85

Most browsers will not complain about the missing chain (especially when using Let's Encrypt as the intermediate certificate is already cached), but CLI tools will.

Best regards,
Fabian

**Comment by fabianfrz** [comment]
patch is on top of #828

**Comment by fzoske** [comment]
Great to hear, thank you!
