### ISSUE TITLE
www/nginx: add button for loading default core rules

### ISSUE THREAD

**Issue by mimugmail** [opnsense/plugins#864]
Started looking at the waf rules. It's a bit hard to setup when there are no preconfigured rules and also no import function.

How about a checkbox with loading the core rules in?

**Comment by mimugmail** [comment]
@fabianfrz what's your opinion on this?

**Comment by fabianfrz** [comment]
Good idea but needs some time. But in this case it makes more sense as a download button which shows a note about the GPL and then downloads the file if the user accepts.

**Comment by mimugmail** [comment]
Why do someone has to accept GPL first? Looking at the packages installed there's a ton of license mixes :)

**Comment by fabianfrz** [comment]
because the file is licensed under it. Just to handle it correctly.

**Comment by mimugmail** [comment]
The whole project is licensed under GPL3, but included in Nginx which is listed as BSD 2 Clause. 

If OK for you I can also take over the download part when you're limited in time .. only an offer.

**Comment by fabianfrz** [comment]
the download is only a small part and can be copied from nextcloud backup. It is nothing new. The most heavy part is parsing the rules and make policies from them.

**Comment by mimugmail** [comment]
Oh, policy relys on a value in config.xml ... hm, I'll have a look first.

**Comment by fabianfrz** [comment]
@mimugmail data structure parsing (almost complete) and download is here as a work in progress: #891. Now we need to put the data into the model.

**Comment by fabianfrz** [comment]
done - see the pull request
