### ISSUE TITLE
Plugin Request: icap

### ISSUE THREAD

**Issue by jeffg2k** [opnsense/plugins#87]
Would be nice to see an easy way to enable a free ICAP.  Maybe http://c-icap.sourceforge.net/ if it's any good.

**Comment by fabianfrz** [comment]
I made a tutorial about that some month ago: https://fabian-franz.eu/icaprb/opnsense/2016/11/23/install-icaprb-on-opnsense.html

You can also install `c-icap ` from the FreeBSD ports at own risk.
Note that good analysis requires a lot of CPU / Memory usage and content processing is always a risk I would not like to have on a firewall device. There is a reason why it should be external.

**Comment by fabianfrz** [comment]
@jeffg2k I am closing this as #226 is being merged soon. So it may be in the next release.
