### ISSUE TITLE
os-bind advanced config

### ISSUE THREAD

**Issue by andreas-p** [opnsense/plugins#877]
The current os-bind configuration is very minimalistic. At least a "advanced configuration" textbox should be provided, so that arbritrary configurations are possible, which will probably remain necessary even if the config gui is vastly extended.

**Comment by mimugmail** [comment]
Which configurations in named conf are you missing? We try to avoid custom options and better extend to your concrete wishes

**Comment by andreas-p** [comment]
I'm running named as secondary and would like to paste my current config.

**Comment by mimugmail** [comment]
Primary and secondary is planned for 2.0, January. In the meantime you could use just the pkg without GUI

**Comment by mimugmail** [comment]
Where is ne benefit of putting all text in a UI which put it into text? Unbound and Dnsmasq are legacy code where it's sometime easier to do, or it was just so forever. It's not a technical problem implementing zone management, only a lack of time.

Are there any else features missing? 

These are the planned features:

https://github.com/opnsense/plugins/issues/405#issuecomment-402542774

If you need more, feel free to add them ...

**Comment by andreas-p** [comment]
a) I didn't suggest a textbox that replaces named.conf, but instead adds arbitrary lines.
b) even a textbox-replaces-named.conf is valuable since the process is under OpnSense control.

**Comment by andreas-p** [comment]
a) I didn't suggest a textbox that replaces named.conf, but instead adds arbitrary lines.
b) even a textbox-replaces-named.conf is valuable since the process is under OpnSense control.

**Comment by andreas-p** [comment]
Most prominently, include is missing for me.
I'm including zone definitions and keys.

**Comment by stilez** [comment]
See also #974 ([direct link to comment](https://github.com/opnsense/plugins/issues/974#issuecomment-448340055)) - posted on main Bind feature requests tracker before seeing this

**Comment by andreas-p** [comment]
> Primary and secondary is planned for 2.0, January. In the meantime you could use just the pkg without GUI

Which January did you mean....

Other mature plugins I use (unbound, dhcp) DO have manual option fields, and I actually need them. Hoping to support any fancy named feature with the UI simply isn't feasable. 

I just was hit by an upgrade (19.1.6->19.1.7) removing my bind912 package without installing its successor bind914. That's why I'd like to use the os-bind package, with just a textfield to paste my running config into it. And I'm probably not the only guy who has a config he just doesn't want to touch but simply use.

**Comment by mimugmail** [comment]
Unbound and DHCP are core features and legacy code, thats why. And if you would follow the development you'd have seen that its already in Bind devel package. Now you have the chance to give something back and test the new code.

**Comment by andreas-p** [comment]
I don't see a freeform field in os-bind-devel 1.5.d

**Comment by fichtner** [comment]
Correct, there is none.

**Comment by andreas-p** [comment]
so, nothing to test for me...

**Comment by fichtner** [comment]
Fair enough. I vote for closing this ticket now. @mimugmail ok?

**Comment by andreas-p** [comment]
Why close this ticket, it's subject isn't resolved.

**Comment by fichtner** [comment]
Because you're being unfriendly and counter-productive.

**Comment by mimugmail** [comment]
master/slave zone management is now available .. no freeform field.

**Comment by andreas-p** [comment]
Methinks supporting a freeform field just as other plugins do as a catch-all for exotic options that take a long time to implement and test for just a few users isn't counter-productive, just pragmatic. 

master/slave zone management isn't what I'm looking for, since I'm copying those zones as include files  from a central source when installing. There might be more options (e.g. notification), haven't looked at those files for quite a while (they're working) and would like to keep it that way without translating their contents and testing them.
Currently, duplication to other instances is performed by copying the directory (and I'm ok with this), but os-bind should probably get a selective System/Configuration/Backups restore option here for standard purposes.

**Comment by fichtner** [comment]
> Methinks supporting a freeform field just as other plugins do as a catch-all for exotic options that take a long time to implement and test for just a few users isn't counter-productive, just pragmatic.

I wholeheartedly disagree. It stifles innovation, debate and increases the chances of problems and risks for its users. And judging from the past years it was a good practice to try and avoid it as much as possible that got the project further than it would have gotten with early and abundant DIY hacks in place.

Because you see, if technical users have to ask for features, the non-technical users will be using them very happy and keep improving them by asking for more features on top. And there are not many technical users (who will say this config file and this argument and you're good) vs. a lot of non-technical users who would like to see a GUI for a particular service integrated.

We need more technical users contributing solutions instead of asking for DIY hacks.

**Comment by andreas-p** [comment]
That means a very long road to go until os-bind is usable to me. Short glance at my config: keys needed as well. Another case for file import.

**Comment by fichtner** [comment]
Ok, I tried. I'm out of here. I don't want to hear any more "is it done yet" or complex "once sentence requirements" for your personal gain. If you know it's work you're even more overbearing than I thought.

**Comment by andreas-p** [comment]
Those are options I need partially, but I don't necessarily anticipate their full extend and effort required to implement them fully and correctly. Bind isn't my passion, I just hack on it until it works. I don't think I could be of much help here for a general implementation. My specific request, from an earlier post, was to enable file include. If the answer is "won't be implemented" this issue may well be closed.

**Comment by mimugmail** [comment]
@andreas-p would you mind closing it as you are the op? You can always open FR's about missing features, and with feature I don't mean a custom field. In the early days I also asked this these fields, they won't come with newer code. You can see the reason when you look at the forum posts asking for help because this and that doesn't work with Unbound. It's always something in the custom field, produces to many work for all other volunteers.

**Comment by andreas-p** [comment]
If unbound missed the custom field I probably didn't have it running, because I needed some try-and-error to find out which options I needed. Posting an FR "I need some options but I don't know which" doesn't appear too promising... NOW I can specify them. I didn't because I'm lazy and found my requirements exotic.
I'd at least need file includes; so far I'm using bind9 package directly which gets corrupted from time to time when freebsd people change package names and dependencies requiring manual fixing. This happens much less frequently with opnsense than back those days with pfsense, when each update removed any custom work and required extensive fixing.
