### ISSUE TITLE
Disabling of an attribute in Freeradius doesn't remove it from users file

### ISSUE THREAD

**Issue by reza-ebrahimi** [opnsense/plugins#878]
By enabling `Enable Daily Session Limit` and assigning a value in Users tab it will add `Max-Daily-Session := 600` attribute to user in Freeradius `users` file, the problem is by disabling it (unchecked) and applying, it still remains there in `users` file, the desired case is  `Max-Daily-Session := 600` should be deleted from corresponding user. By applying any config it should rebuild all configuration files again.

![1](https://user-images.githubusercontent.com/11276982/46236216-9820f500-c38a-11e8-9707-f097cbce1da3.png)

**Comment by reza-ebrahimi** [comment]
@mimugmail 
> Enabling Daily Limit in `General` adds some options to Freeradius and displays the field in `Users` via some JavaScript to not let the `Users` UI dialog grow too big, but it wont delete the config from the model. Theoretically I could add a check in templating that this option doesn't get into users file, but the value would still stay in the UI.

This is the part that hides each row if its enabled state in `general` is `0`. I think this is correct behaviour that it still remain in model and doesn't get removed,

```js
$.each(data.general, function(setting_key, setting_value){
  var search_item = 'row_user.' + setting_key +'_';
  if (this_item_name.startsWith(search_item) && setting_value == '0') {
	  // since our form tr rows are visible by default, we only have to hide what isn't needed
	  this_item.hide();
  }
});
```

My concern is configuration files, in this case `users` file, if we disabling an attribute like `session_limmit` it should not present in `users` file,

```
{{ user_list.username }}  Cleartext-Password := "{{ user_list.password }}"{% if user_list.sessionlimit_max_session_limit is defined %}, Max-Daily-Session := {{ user_list.sessionlimit_max_session_limit }}{% endif %}
```

The `if` part should be checked with general enabled state first I think:

```markdown
{% if freeradius.general.enabled is defined %}
  {% if user_list.sessionlimit_max_session_limit is defined %}
, Max-Daily-Session := {{ user_list.sessionlimit_max_session_limit }}
  {% endif %}
{% endif %}
```

**Comment by mimugmail** [comment]
Yes, as I said we can add a check in templating, but it will still stay in model. 
I'm not against this, since it's not worse than now :) 

@fichtner opinions?

**Comment by reza-ebrahimi** [comment]
@mimugmail The main concern is Freeradius correct behavior, model itself doesn't affect the behavior until it get applied into configuration, thanks for your quick responses, may quick bug fixes :)

**Comment by mimugmail** [comment]
Just create a PR and test, I'll gladly review

**Comment by fichtner** [comment]
I agree with @reza-ebrahimi about the config file concern and would welcome a PR

**Comment by reza-ebrahimi** [comment]
@mimugmail @fichtner I'll create a PR by today
