### ISSUE TITLE
net/haproxy: Rule "Execute function http-request header-delete" fails

### ISSUE THREAD

**Issue by sbuckmann** [opnsense/plugins#882]
The use of the function "http-request header-delete" in HAProxy Rules creates a corrupt haproxy.conf file.
The error seems to be on line 429 of file 
plugins/net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf:
Is: do action_options.append('http-response del-header' ~  ....
Should:  do action_options.append('http-response del-header ' ~ ....
(missing SPACE after del-header)

**Comment by fraenki** [comment]
@sbuckmann Thanks! A fix will be available in os-haproxy release 2.10, which will be included in the upcoming OPNsense 18.7.8.

If you want to test the fix:

```
$ opnsense-patch -c plugins 105adb81
``
