### ISSUE TITLE
[question] Add item to dropdown dynamically

### ISSUE THREAD

**Issue by reza-ebrahimi** [opnsense/plugins#883]
I need to add items to a dropdown element defined in Forms, I have tried it with JQuery append method inside script tag (.volt files) but it won't work, is there any way to do this?

```
<field>
      <id>general.test</id>
      <label>Test Dropdown</label>
      <type>dropdown</type>
</field>
```

**Comment by reza-ebrahimi** [comment]
@mimugmail Please have a look here

**Comment by mimugmail** [comment]
I'm note a core dev, for me it seems you have to choose the correct FieldType in Model. Which objects do you need to be dynamically loaded? Interfaces? Otherwise you have to add dialog tab and let the use add them (like Prefix-Lists in FRR->BGP)

**Comment by reza-ebrahimi** [comment]
I think there is two ways to append dynamically to dropdown, Controller and View, I've tested view already and not working:

```js
$this_item.append($("<option value=''>text</option>"))
```

But I don't know how to append a item inside controller. may appending to model updates view which I don't know how to do that.

**Comment by reza-ebrahimi** [comment]
The items I want to load is Users in freeradius. actually I need a dropdown to select freeradius defined users.

**Comment by mimugmail** [comment]
Go to FRR Plugin source, BGP controller, look at ModelRelationField. That's exactly what you want ...

**Comment by reza-ebrahimi** [comment]
I cannot got it to work, the line:

https://github.com/opnsense/plugins/blob/c1bacde5485f35cdc733dc358f53fbcaa77bfbcb/net/frr/src/opnsense/mvc/app/models/OPNsense/Quagga/BGP.xml#L67

in my case is in another model, when I put it in source, it will not works.

**Comment by reza-ebrahimi** [comment]
I cannot got it to work, the line:

https://github.com/opnsense/plugins/blob/c1bacde5485f35cdc733dc358f53fbcaa77bfbcb/net/frr/src/opnsense/mvc/app/models/OPNsense/Quagga/BGP.xml#L67

in my case is in another model, when I put it in source, it will not works.

**Comment by reza-ebrahimi** [comment]
I cannot got it to work, the line:

https://github.com/opnsense/plugins/blob/c1bacde5485f35cdc733dc358f53fbcaa77bfbcb/net/frr/src/opnsense/mvc/app/models/OPNsense/Quagga/BGP.xml#L67

in my case source is in another model, it will not works.

**Comment by mimugmail** [comment]
You said you need FreeRadius Users as source, so where is the problem?

If you exactly tell us what you want to achieve we can help you for sure :)

**Comment by reza-ebrahimi** [comment]
@mimugmail Thanks you!

I need to load users defined in Freeradius users section, so I have defined a dropdown in view and a model and controller respectively, 

Controller:
```xml
    <field>
        <id>test.user</id>
        <label>User Name</label>
        <type>dropdown</type>
    </field>  
```

Model:
```xml
<model>
    <mount>//OPNsense/freeradius/test</mount>
    <items>
        <tests>
            <test type="ArrayField">
                <enabled type="BooleanField">
                    <default>1</default>
                    <Required>Y</Required>
                </enabled>
                <user type="ModelRelationField">
					<Model>
						<template>
                                                        <source>OPNsense.freeradius.user</source>
							<items>users.user</items>
							<display>username</display>
							<group>username</group>
						</template>
					</Model>
                    <Required>Y</Required>
                </user>
            </test>
        </tests>
    </items>
</model>
```

**Comment by reza-ebrahimi** [comment]
@mimugmail Thank you!

I need to load users defined in Freeradius users section, so I have defined a dropdown in view and a model and controller respectively, 

Controller:
```xml
    <field>
        <id>test.user</id>
        <label>User Name</label>
        <type>dropdown</type>
    </field>  
```

Model:
```xml
<model>
    <mount>//OPNsense/freeradius/test</mount>
    <items>
        <tests>
            <test type="ArrayField">
                <enabled type="BooleanField">
                    <default>1</default>
                    <Required>Y</Required>
                </enabled>
                <user type="ModelRelationField">
					<Model>
						<template>
                                                        <source>OPNsense.freeradius.user</source>
							<items>users.user</items>
							<display>username</display>
							<group>username</group>
						</template>
					</Model>
                    <Required>Y</Required>
                </user>
            </test>
        </tests>
    </items>
</model>
```

**Comment by mimugmail** [comment]
Please check for correct usage of upper/lower-case.
This one took me a complete day:

https://github.com/opnsense/plugins/blob/master/net/wireguard/src/opnsense/mvc/app/models/OPNsense/Wireguard/Server.xml#L52

**Comment by reza-ebrahimi** [comment]
Actually that's the problem, `<source>OPNsense.freeradius.user</source>` is case sensitive, and after the case correction dropdown shows the users, its resolved, thanks for your cooperation.

**Comment by mimugmail** [comment]
Welcome to the Team. :)

**Comment by fichtner** [comment]
nice, thanks guys! ❤️

**Comment by reza-ebrahimi** [comment]
@mimugmail @fichtner Question: build times for `make plugins` command are too long when working on just a plugin, how to make a plugin itself without involve in making all plugins?

**Comment by mimugmail** [comment]
opnsense-code plugins
cd /usr/plugins

Then your directory If plugin, do your changes and make upgrade at plugin level like www/c-icap

**Comment by reza-ebrahimi** [comment]
@mimugmail Like this?
```bash
$ cd /usr/plugins/net/freeradius
$ # make changes
$ make upgrade
```

**Comment by mimugmail** [comment]
Yep

**Comment by reza-ebrahimi** [comment]
@mimugmail Hello, Another question please, I want to place html element horizontal, the default with base_dialogue or other forms is vertical.

```
<field>
	<id>example.element1</id>
	<label>Element 1</label>
	<type>text</type>
</field>
<field>
	<id>example.element2</id>
	<label>Element 2</label>
	<type>dropdown</type>
</field>
<field>
	<id>example.element3</id>
	<label>Element 3</label>
	<type>dropdown</type>
</field>
```

**Comment by reza-ebrahimi** [comment]
@mimugmail Hello, Another question please, I want to place html elements horizontal, the default value with base_dialogue or other forms is vertical.

The following snippet is place elements in vertical, I want that to be horizontal.
```
<field>
	<id>example.element1</id>
	<label>Element 1</label>
	<type>text</type>
</field>
<field>
	<id>example.element2</id>
	<label>Element 2</label>
	<type>dropdown</type>
</field>
<field>
	<id>example.element3</id>
	<label>Element 3</label>
	<type>dropdown</type>
</field>
```

**Comment by mimugmail** [comment]
I'm not the html guy, sorry. @AdSchellevis any ideas?

**Comment by fichtner** [comment]
it's better to keep it simple than ask for other people's time. we don't support different layouts of forms.

**Comment by reza-ebrahimi** [comment]
@fichtner I'm sorry for other people's time, but I think this is major requirement, sometimes needs to layout elements horizontals due to user experiences.

**Comment by reza-ebrahimi** [comment]
I have opened an issue.
