### ISSUE TITLE
net-mgmt/net-snmp: Override sysDescr for OPNsense

### ISSUE THREAD

**Issue by ashceryth** [opnsense/plugins#892]
Hey guys,

I am using LibreNMS for monitoring my OPNsense firewalls. After switching to the new net-snmp plugin the firewalls are discovered as generic FreeBSD systems (`iso.3.6.1.2.1.1.1.0 = STRING: "FreeBSD firewall.example.com 11.1-RELEASE-p14 FreeBSD 11.1-RELEASE-p14  93e30e927e5(stable/18.7) amd64"`). OS discovery depends on the sysDescr value which is set to something like `OPNsense 18.7.4 firewall.example.com FreeBSD 11.1-RELEASE-p14 amd64` for the old SNMP plugin. Including a line
```
sysDescr OPNsense 18.7.4 firewall.example.com FreeBSD 11.1-RELEASE-p14 amd64
```
in `/usr/local/share/snmp/snmpd.conf` does the trick for the new net-snmp plugin. Would it be possible to add this line automatically?

Thanks!

**Comment by ashceryth** [comment]
Issue has already been mentioned here: https://forum.opnsense.org/index.php?topic=9365.0

**Comment by mimugmail** [comment]
@fichtner How can this be templated with jinja? Or does this need an extra action?

https://github.com/opnsense/plugins/blob/master/net-mgmt/snmp/src/etc/inc/plugins.inc.d/bsnmpd.inc#L99-L106

**Comment by fichtner** [comment]
I need to talk to @adschellevis about this.

**Comment by fabianfrz** [comment]
It does not work. A helper for the values must be implemented in this file:
https://github.com/opnsense/core/blob/master/src/opnsense/service/modules/addons/template_helpers.py

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.

**Comment by mimugmail** [comment]
The `help wanted` tag can be removed as I'm working on this in #1602
