### ISSUE TITLE
FR oc-openconnect Add additional fields to WebGUI

### ISSUE THREAD

**Issue by mrPsycho** [opnsense/plugins#898]
Hello,
in continue to https://forum.opnsense.org/index.php?topic=9873.msg45036#msg45036

Add, please, additional fields to WebGUI, so it will be possible to use openconnect as Cisco AnyConnect client (in some cases). 

it needs this:
* --authgroup
* --certificate - will be gtreat to get it from "Trust" section
* --key - same as certificate

**Comment by mimugmail** [comment]
authgroup should be no problem. certificate is for certificate based authentication? with key you mean sslkey, correct? I try to add this next week.

**Comment by mimugmail** [comment]
@mrPsycho were you able to test the features?

**Comment by mrPsycho** [comment]
@mimugmail i did it!
but, with no luck:

```
root@OPNsense:~ # /usr/local/etc/rc.d/opnsense-openconnect start
starting openconnect
Enter PEM pass phrase:
fgets (stdin): Inappropriate ioctl for device
ifconfig: interface tun30000 does not exist
ifconfig: interface ocvpn0 does not exist
```

**Comment by mrPsycho** [comment]
everything is fine! 
thank you! 


sorry for late answer, forgot about it :(
