### ISSUE TITLE
network card tweak plugin

### ISSUE THREAD

**Issue by fichtner** [opnsense/plugins#9]
Some cards have best practices for sysctl tweaks.... a plugin should collect and enforce them automatically.

**Comment by fbrendel** [comment]
Yes would be nice to have optimized values with a simple click.

The plugin should detect the drivers and apply these sysctls.

But we need different values for different workloads on different hardware.
And the plugin will need a reboot since some settings can only be made in /boot/loader.conf.

And what do you think about a GUI to change this settings and let the admin easily publish it on github?

**Comment by fichtner** [comment]
Ideally yes, practically no. The sysctls do this mostly. We can't easily template the boot.loader settings, at least not in the traditional way as we need to ensure removal of rc.loader.d files (see https://github.com/opnsense/plugins/commit/7ccea3e5a2ae5b57560d3ff6992339328dab3a19 )

Anything settings + GUI also means a config.xml model, maybe even start with core support for loader.conf modifications? It sounds like an easy task on paper, but it's a lot of work if done right. :/

**Comment by fbrendel** [comment]
To understand it right: change a value in the gui, trigger a template reload for a new rc.loader file and then create a new /boot/loader.conf is a problem? Even with a big warning that the system will reboot?
And the files created by the template will not removed when I remove the plugin? Ok this is a problem then.
But wait, what if the plugin provides an empty rc.loader file? This would be removed on plugin removal, right?

**Comment by fichtner** [comment]
Yes, the plugin would register its own (empty or only comment-based) rc.loader.d file and rewrite it as needed. It wouldn't reboot, but tell the user that they need to reboot and that that reboot may be fatal ;)

**Comment by fbrendel** [comment]
Please don't say 'fatal'. It's so negative.
I think the worst case is that the system comes up without network.
Is it too naive to say "remove the plugin via console and reboot"?
Anything we can do at the loader prompt?

**Comment by fichtner** [comment]
It's hard to recover from loader.conf modifications, not even the boot loader console can help with overriding its values sometimes. Booting up without a network for a firewall appliance is tricky then, for most people an obvious mistake of the software.

**Comment by fbrendel** [comment]
Ok, then we have two options.
Static and unflexible or flexible and possibly unstable.
For the first case we can choose values for all-pupose workloads/hardware. What the default values already are.
For the second we could minimize failures with a plausibility test.

**Comment by fichtner** [comment]
I'm closing this, can always reopen. :)
