### ISSUE TITLE
quagga: setup.sh for directory creation under /var MFS

### ISSUE THREAD

**Issue by fichtner** [opnsense/plugins#90]
Hi Fabian,

The directories needed are these two, whereas:

user: quagga
group: quagga
mode: 750
localstate: /var/run/quagga
sysconf: /usr/local/etc/quagga (probably)

https://github.com/opnsense/ports/blob/master/net/quagga/pkg-plist#L108-L109

Cheers,
Franco

**Comment by fabianfrz** [comment]
@fichtner please close ticket when done - I don't have the permission to

**Comment by fichtner** [comment]
Closed via #93
