### ISSUE TITLE
www/nginx Problem with TLS Certificate enable in HTTP Server

### ISSUE THREAD

**Issue by juliocbc** [opnsense/plugins#902]
version: os-nginx-devel-1.1

If it is set TLS Certificate option in HTTP Server the following error occurs:

`PHP Warning:  Invalid argument supplied for foreach() in /usr/local/opnsense/scripts/nginx/setup.php on line 88`

@fabianfrz

**Comment by fabianfrz** [comment]
@juliocbc fix is provided in the PR above. You can try if it works for you using the `opnsense-patch -c plugins 667c381 ` command. The
