### ISSUE TITLE
[bug] NtopNG interface selection

### ISSUE THREAD

**Issue by thutex** [opnsense/plugins#906]
on the ntopng page we can choose an interface for ntopng to listen to.
however, you can only select a SINGLE interface.

i have several vlans dispersed over 10.0.x.0/24 where X marks the vlan, and ntop can currently only monitor one vlan... thereby considering all the other traffic it sees from internal hosts as being remote networks....

It is currently impossible, using the gui, to configure ntopng to listen to all my interfaces,
meaning i have to go into the shell and manually edit /usr/local/etc/ntopng.conf (not persistent) or the template file for ntopng.conf (not desired)

the interface selection should either allow for multiple selected interfaces (preferred) or at the very least offer an 'all' option.

**Comment by mimugmail** [comment]
If you dont set an interface you can choose it the normal way via ntopng own UI. Does this work for you?

**Comment by thutex** [comment]
this does seem to pretty much match what i want, though it then also adds interfaces like the vpn and pppoe which are 2 that i dont personally care for in ntop statistics.
but i'm not one to complain for minor issues, so for me this works.

maybe change the 'none' text to 'default' or add an info text that 'selecting none will show all interfaces in ntopng' to the gui for clarity.

**Comment by mimugmail** [comment]
Will do :)

**Comment by BentHaase** [comment]
Sorry for reopening this issue but the problem with only being able to select a single interface persists with current `OPNsense 21.7.7`:

![image](https://user-images.githubusercontent.com/5788982/151322599-8b1a9463-e901-4163-a12c-234c21b0e230.png)

This is not an issue as long as you only have <= 8 interfaces on your router, but the moment you have more interfaces and want to select a few specific interfaces for ntopng to monitor, (ntopng community only allows to monitor <= 8 interfaces) you simply can't.

**Can we get a multiselect dropdown window for this plugin?**

**Comment by mimugmail** [comment]
You mean there is no scroll bar when there are more than eight? Do you see cthem when you search for name?

**Comment by BentHaase** [comment]
> You mean there is no scroll bar when there are more than eight? Do you see cthem when you search for name?

I mean you **can't select multiple interfaces**. You can either select one or none (aka all) which results in random interface monitoring within ntopng.
