### ISSUE TITLE
DynDNS - No-IP Provide - API

### ISSUE THREAD

**Issue by vityank** [opnsense/plugins#909]
Hi, I've made an update to the client to use the current API recommended by No-IP as described in their documentation, here:
https://www.noip.com/integrate/request

The new API supports less status codes than the old one, but works correctly with groups(Current old API bundled with OpenSense does not(Error 99) and requires to create dedicated entry for each domain).

My patch for review attached in a zip file(Path: /dns/dyndns/src/etc/inc/plugins.inc.d/dyndns/).
I don't make Pull Request because it's a relatively small change.

[phpDynDNS.zip](https://github.com/opnsense/plugins/files/2471068/phpDynDNS.zip)

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
