### ISSUE TITLE
net/wireguard: rc.d script clashes with upcoming FreeBSD script

### ISSUE THREAD

**Issue by fichtner** [opnsense/plugins#910]
https://github.com/opnsense/plugins/blob/843643e340c5b00aeca29d1d019abb5fa610ab10/net/wireguard/src/etc/rc.d/opnsense-wireguard#L12

vs.

https://github.com/freebsd/freebsd-ports/commit/a934d9aa8d7

**Comment by mimugmail** [comment]
It looks familiar ;)
