### ISSUE TITLE
Redis start problem

### ISSUE THREAD

**Issue by rong00gle-007** [opnsense/plugins#918]
Redis couldn't get Started, when i check system logs i found this:
```
Oct 17 12:14:46 | redis[75526]: Creating Server TCP listening socket xx.xx.xx.106.106:6379: bind: Address already in use
-- | --
Oct 17 12:14:46 | redis-server: Configuration loaded
Oct 17 12:14:46 | redis-server: Redis version=4.0.11, bits=64, commit=00000000, modified=0, pid=75295, just started
Oct 17 12:14:46 | redis-server: oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
```

Then i tried different port, same error logs:

```
Oct 17 12:14:31 | redis[55447]: Creating Server TCP listening socket xx.xx.xx.106:6389: bind: Address already in use
-- | --
Oct 17 12:14:31 | redis-server: Configuration loaded
Oct 17 12:14:31 | redis-server: Redis version=4.0.11, bits=64, commit=00000000, modified=0, pid=55376, just started
Oct 17 12:14:31 | redis-server: oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
```

**Comment by rong00gle-007** [comment]
When I clear `Listen Interfaces`, then redis start working properly.
What is the role of `Listen Interfaces` in redis and why redis gave me `port already in use` error?

Can anybody elaborate Redis: Listen Interface?
Thanx in Advance

**Comment by fabianfrz** [comment]
this means another service is using the port of redis or redis was already running

**Comment by mimugmail** [comment]
@rong00gle-007 was this a one-time issue? Can this be closed?

**Comment by mimugmail** [comment]
Timeout?

**Comment by lshantz** [comment]
No, this is an an ongoing issue. It needs to be addressed. It doesn't matter what port you change it to, you still have the same error. I did get rid of the The TCP backlog setting of 511 cannot be enforced because kern.ipc.somaxconn is set to the lower value of 128 error, by adding it in tunables and increasing the value. Still at a loss on the port issue.

**Comment by mimugmail** [comment]
You dont need to warm up all old threads you can find ;)

https://forum.opnsense.org/index.php?topic=38845.0
