### ISSUE TITLE
[requirement] Need to layout HTML elements horizontally

### ISSUE THREAD

**Issue by reza-ebrahimi** [opnsense/plugins#919]
The following snippet is place elements in vertical, I want that to be horizontal. Sometimes needs to layout elements horizontally due to user experiences

```
<field>
	<id>example.element1</id>
	<label>Element 1</label>
	<type>text</type>
</field>
<field>
	<id>example.element2</id>
	<label>Element 2</label>
	<type>dropdown</type>
</field>
<field>
	<id>example.element3</id>
	<label>Element 3</label>
	<type>dropdown</type>
</field>
```
Example:

![photo_2018-10-17_16-46-19](https://user-images.githubusercontent.com/11276982/47088863-53230c80-d22c-11e8-98f9-0db5f5a449ad.jpg)

**Comment by fichtner** [comment]
It's possible to do this in the volt template via HTML and JS.

**Comment by reza-ebrahimi** [comment]
Is there any way to set an orientation flag on controller xml file side, and the layout operates based on the orientation flag?

**Comment by fichtner** [comment]
No, there is not.

**Comment by reza-ebrahimi** [comment]
and cannot be implemented as a new feature?

**Comment by fichtner** [comment]
No, it can. I'm simply trying to level the expectation for when, who and especially why. It all starts with a valid use case in the project that makes a solution that you suggest relevant. Which dialog that exists today needs improvement?

**Comment by reza-ebrahimi** [comment]
I don't know which dialogue needs any use case like this, but I have attached my use case image, this is a UX issue, you can layout example image above vertically but it's not a desired case for user experience design, may such horizontal use cases in `opnsense` has been implemented in vertical mode due to lack of this feature.

**Comment by fichtner** [comment]
I understand your position. Now please understand ours: requesting an open source solution should require an open source problem. :)
