### ISSUE TITLE
interface/routes: let plugin reconfigure routes after startup

### ISSUE THREAD

**Issue by mimugmail** [opnsense/plugins#921]
Hi,

tried to setup loadbalancing via multiple Wireguard gateways. Works fine so for, but when the system reboots, the routes are added before the interface has an ip address. After startup of Wireguard I can call 

configctl interface routes configure 

And everyting works.

Now I'm wondering where I could place this since it has to be set with every Save cause the interface goes down, but also somewhere within rc script since at startup the reconfigure action of the plugin is not called. 

setup.sh does not work since it's called before startup, initscript is not clean, perhaps there's a rc.conf variable to use for templating?

**Comment by fichtner** [comment]
yes [start] action, after service start via rc.d

**Comment by mimugmail** [comment]
Thx, forgot about start action :)

**Comment by mimugmail** [comment]
Sorry, in start action it does not fix it when the system comes up (= start in rc script, not actions)

**Comment by fichtner** [comment]
https://github.com/opnsense/plugins/commit/bbd15177f7ecb1f3e
