### ISSUE TITLE
NUT - add possibility to edit config files in GUI

### ISSUE THREAD

**Issue by cilresu** [opnsense/plugins#924]
Coming from pfSense, I am glad NUT made it into OPNsense too.

Id like to change some of the default options like ondelay or offdelay in ups.conf to minimize the risk of NUT shutting down the UPS before the connected systems are properly shut down. Doing so manually via CLI leads to the changes not being persistent through a reboot. 

Therefore I would propose to add the possibility to edit the main configuration files 

nut.conf
upsd.conf
upsd.users

directly in the GUI so that they survive a reboot and arent overwritten.

Moreover, (maybe it was because I was using standalone mode) I couldnt modify any settings like user names or upsmon mode, but that too could be addressed  by allowing persistent configuration file changes in the GUI (just like in the pfSense NUT Plugin). 

Any thoughts on that? I am willing to dedicate my time to testing. :) Or contributing otherwise, but Id need to get familiar with the plugin stuff.

Regards

**Comment by fabianfrz** [comment]
We won't do that except in some edge cases where it is not possible to do it differently.
The problem is that unchecked user input may break the daemon config which usually leads to an error preventing it from starting. If you need an option, you can usually ask for adding it.

For example, you can create a ticket requesting the ondelay or offdelay option in the nut plugin.
I'll assign the maintainer of the plugin, feel free to discuss the feature request with him.

**Comment by mimugmail** [comment]
Just tell my in which file you add the exact values and I'll add them. 
I can also tell you how if you want to do it on your own?

**Comment by cilresu** [comment]
Okay, I will check the files and variables and return with a list. 

And yes, please tell me how to modify it myself, too, that might be a good way for me to get used to it.

Thanks

**Comment by mimugmail** [comment]
I had a look at the config, what exactly do you need for MONITOR setting? There is already:

`MONITOR {{ OPNsense.Nut.general.name }} 1 monuser {{ OPNsense.Nut.account.mon_password }} master`

For upsd.users I dont know what exactly you need .. do you mean `netclient mode`?
Perhaps you just post the contents of your upsd.users. 

The other things should be easy ...
