### ISSUE TITLE
Cloudflare DDNS not retrieving Zone ID

### ISSUE THREAD

**Issue by jslay88** [opnsense/plugins#926]
I have looked at the dyndns plugin code, and validated the logic and sequence using postman to hit the api manually, and can clearly see valid responses from the CloudFlare API as the first result returned (I only have one domain on this CloudFlare account, and its the root record I am trying to update here). 

For some reason though, the DDNS service refuses to be able to parse it out and fails to update the record.

Here are the logs (reverse order) with the domain name and IP address redacted. But both domain and IP that appear in logs are correct.

```
Oct 19 22:54:01 | opnsense: /usr/local/etc/rc.dyndns: Dynamic DNS (example.net): ERROR - Zone ID was not found.
-- | --
Oct 19 22:54:01 | opnsense: /usr/local/etc/rc.dyndns: Dynamic DNS (example.net): Current Service: cloudflare
Oct 19 22:54:01 | opnsense: /usr/local/etc/rc.dyndns: Dynamic DNS (example.net): _checkStatus() starting.
Oct 19 22:54:00 | opnsense: /usr/local/etc/rc.dyndns: Dynamic DNS (example.net via CloudFlare): _update() starting.
Oct 19 22:54:00 | opnsense: /usr/local/etc/rc.dyndns: Dynamic DNS (example.net): running get_failover_interface for opt1. found pppoe0
Oct 19 22:54:00 | opnsense: /usr/local/etc/rc.dyndns: Dynamic DNS (example.net): xxx.xxx.xxx.xxx extracted
Oct 19 22:53:59 | opnsense: /usr/local/etc/rc.dyndns: Dynamic DNS: updatedns() starting
```

What am I missing? Is there any way to get an even more verbose output to the log outside of enabling `Verbose Output` on the DDNS config?

**Comment by fichtner** [comment]
https://github.com/opnsense/plugins/pull/861

**Comment by finish06** [comment]
I am experiencing this issue.  Let me know how I can assist with testing if needed.
