### ISSUE TITLE
Monit - an extra column for how often the service has already been called?

### ISSUE THREAD

**Issue by opnsenseuser** [opnsense/plugins#927]
@fbrendel in the monit tool widget it would be very interesting if you had an extra column for each service where you would see how often the service was already triggered. 

I hope you understand what I mean!
would it be possible?

reagards rené

**Comment by opnsenseuser** [comment]
@fichtner i don´t know if user @fbrendel is the developer of this.

**Comment by fbrendel** [comment]
@opnsenseuser I guess you mean how many times the service was checked.
I'm afraid that Monit doesn't provide such information.
So I can't add that to the widget. :unamused:

**Comment by fbrendel** [comment]
Yes, agree. But unfortunately that information is also not provided.
You could count your alert mails... :smirk: 
Or write a custom check that counts errors.

**Comment by opnsenseuser** [comment]
@fbrendel should i close this?

**Comment by fbrendel** [comment]
Hmm, perhaps the [Monit](https://bitbucket.org/tildeslash/monit/issues) guys would add such statistics to the daemon.
I could add them to the widget then.
