### ISSUE TITLE
Monit - use standard css classes for status view colors?

### ISSUE THREAD

**Issue by opnsenseuser** [opnsense/plugins#928]
@fbrendel would it be possible to customize the colors or even better and simpler just to use the standard css classes ?

regards rené

the problem is that it is not always very appropriate!
![grafik](https://user-images.githubusercontent.com/34602360/47252004-50e3cc80-d43d-11e8-976f-c9fd1dd8f6e6.png)

**Comment by opnsenseuser** [comment]
@fichtner i don´t know if user @fbrendel is the developer of this.

**Comment by fbrendel** [comment]
Good idea. It's more 'GUI integrated'.
@fichtner what do you think?

**Comment by fichtner** [comment]
yes please, see e.g. https://github.com/opnsense/core/commit/fe21186e05f5e

**Comment by opnsenseuser** [comment]
@fbrendel works great :-) thx very much!
regards rené
