### ISSUE TITLE
Firewall: Aliases not working

### ISSUE THREAD

**Issue by xarados** [opnsense/plugins#932]
Since update from 18.1.13 => 18.7.5 my Aliases for Hosts and Ports where not showed in the Drop-Down Menu.

In the rules.debug file each line is commented like this:
`#debug:Invalid target`
`# rdr on eth0 inet proto tcp from {any} to {xxx.xxx.xxx.xxx} port {29419} -> scm port 22`
or
`#debug:Unable to convert address, see to for details`
`# rdr on eth0 inet proto tcp from {any} to {{"address":"upload_example_de","port":"8443"}} port {8443} -> xxx.xxx.xxx.xxx port 8443`

When i try to update the Aliases manual it looks to be ok.
`/usr/local/sbin/configctl filter refresh_aliases`
`OK`

Please help, thx

**Comment by xarados** [comment]
Subsequent events:
I was able to install and test the system's config on a test system. The aliases can be easily selected when editing firewall rules.

The only alias that is visible comes from Nginx and has the name nginx_autoblock
![spectacle a17522](https://user-images.githubusercontent.com/1060030/47351618-a37ced00-d6b8-11e8-8fef-cb161a1efb06.png)

all other aliases are only displayed as name.
![spectacle f17522](https://user-images.githubusercontent.com/1060030/47351571-89dba580-d6b8-11e8-930d-4e4b0cc881a2.png)

**Comment by AdSchellevis** [comment]
You really need to supply more context, which type of aliases are missing, where can't you select them etc, etc,

**Comment by xarados** [comment]
All Aliases where i have set one or more IPs or Hostnames. The same is with Aliases which used for Ports with single or multiple Ports.
I can't select them in Firewall Rule editing same on NAT (Port Forward) in the Source or Destination Fields (and by Source/Destination Port)

Here my Aliases that i have in use:
![spectacle l18030](https://user-images.githubusercontent.com/1060030/47353006-70882880-d6bb-11e8-9c91-1d936e444591.png)

Do you need more information/Logs?

**Comment by AdSchellevis** [comment]
maybe some issue with the nginx plugin, already using the new style aliases

cc @fabianfrz

**Comment by xarados** [comment]
I had suspected synonymous and have the Nginx plugin uninstalled, but the result is the same, aliases are no longer displayed.

On the test system which has set up the same plugins and rules works the selection of aliases.

Is there a way to migrate the aliases (to new style)?

**Comment by xarados** [comment]
So i have revert Nginx and restart but still the same problem. Switch to dev is no option for me (productive environment).
```
Fetching os-nginx.txz: ... done
Verifying signature with trusted certificate pkg.opnsense.org.20180614... done
os-nginx-1.2: already unlocked
Updating OPNsense repository catalogue...
OPNsense repository is up to date.
All repositories are up to date.
Checking integrity... done (0 conflicting)
The following 1 package(s) will be affected (of 0 checked):

New packages to be INSTALLED:
        os-nginx: 1.0

Number of packages to be installed: 1
[1/1] Installing os-nginx-1.0...
Extracting os-nginx-1.0: 100%
Stopping configd...done
Starting configd.
Keep version OPNsense\Nginx\Nginx (1.1.2)
Reloading plugin configuration
Configuring system logging...done.
Reloading template OPNsense/Nginx: OK
```

**Comment by AdSchellevis** [comment]
you probably have to edit the config.xml manually, the nginx alias is likely still there. search for `<Alias` and remove the whole section. make sure you keep a backup of the original one.

**Comment by xarados** [comment]
that helps temporarily. I can now use the rules once with the aliases. Approx. 1min later, the <Alias> section is automatically added to the config.xml again. I have tested it against both Versions of Nginx. Now i'am back on 1.0 Version.

**Comment by fabianfrz** [comment]
@AdSchellevis the alias is created automatically via cron every minute and it is like the virusprot table. It contains a list of bot IPs which should be blocked. However it does not delete or hide anything.

The code which manages it is here:
https://github.com/opnsense/plugins/blob/master/www/nginx/src/opnsense/scripts/nginx/ngx_autoblock.php#L92-L110

As you can see, it will look for its own alias and uses that one or creates it if it is missing.

**Comment by fabianfrz** [comment]
@xarados The nginx plugin is currently the only plugin, which manages its own aliases and this feature is really new in core. It may be a core bug too because the plugin handles alias like any other standard OPNsense model class.

**Comment by fabianfrz** [comment]
@xarados for a temporary workaround, you can add an `exit(0)` after the `<?php` line. It should not create the alias then.

**Comment by fabianfrz** [comment]
ok, should we disable the script then?

**Comment by fichtner** [comment]
Well, 18.7.6 will ship the API so if it works on -devel now it's ok?!

**Comment by fabianfrz** [comment]
on OPNsense 19.1.a_288-amd64 it looks good.

**Comment by fichtner** [comment]
Er, current -devel is 19.1.b_54 which is 19.1.a-386 so please test something recent :D

**Comment by xarados** [comment]
> @xarados for a temporary workaround, you can add an `exit(0);` after the `<?php` line. It should not create the alias then.

That was it. In 18.7.6 is then fixed?

**Comment by fichtner** [comment]
According to @fabianfrz yes. Please close if you can confirm (18.7.6 will be released in an hour)

**Comment by xarados** [comment]
Over the Weekend i have upgrade to 18.7.6 and all is working as expected.

Thanks to all for the fast support.
