### ISSUE TITLE
IDS-IPS issues not parsing signature rules for User Defined Rule

### ISSUE THREAD

**Issue by jslay88** [opnsense/plugins#935]
I am having yet another issue with a different plugin in OPNsense. Starting to question the stability of this project, as every step I take (literally) I continue to hit bugs. (Yes, I have made sure I am up-to-date).

Adding a IDS User Defined Rule for blocking Non-USA traffic. When I try to apply the rule, I am met with this error in the log.

```
suricata: [100171] <Error> -- [ERRCODE: SC_ERR_INVALID_SIGNATURE(39)] - error parsing signature "alert ip any any -> any any (msg:"NOTUSA"; geoip:!US ; sid:4294967294; rev:1;)" from file /usr/local/etc/suricata/opnsense.rules/OPNsense.rules at line 8
```

There is nothing special about this rule, and was setup using the wiki from OPNsense (https://wiki.opnsense.org/manual/how-tos/ips-geoip.html)

**Comment by mimugmail** [comment]
Please use the GeoIP alias via Firewall to block this .. the way via Suricata is legacy and it think documentation also state this.

**Comment by AdSchellevis** [comment]
Maybe we should remove the feature in 19.1, on my end it still works, but some combinations won't and aliases provide a more fine grained solution indeed.

**Comment by fichtner** [comment]
yes please

**Comment by fichtner** [comment]
hrm, plugin ticket -.-

**Comment by AdSchellevis** [comment]
hmm, missed that too, close and reopen in core?

**Comment by fichtner** [comment]
yep

**Comment by AdSchellevis** [comment]
@fichtner thanks!
