### ISSUE TITLE
tinc configuration forces to specify an external address

### ISSUE THREAD

**Issue by tuxillo** [opnsense/plugins#936]
Hi,

According to the tinc.conf manpage: https://www.tinc-vpn.org/documentation/tinc.conf.5

    Address = address [port] [recommended]
      The IP address or hostname of this tinc daemon on the real network. 
      This will only be used when trying to make an outgoing connection to this tinc
      daemon.  Optionally, a port can be specified to use for this address.  Multiple
      Address variables can be specified, in which case each address will be tried until
      a working connection has been established.

In the OPNSense tinc plugin configuration, in the "Hosts" tab when you add a new host you are forced to enter an external address. In my opinion that should only be so when the "Connect To" checkbox is checked. For "clients" that are behind a firewall and there is no way exposing the tinc port to the world, it should be allowed to leave the "External address" field empty. That's perfectly fine.

Pointed out by @mimugmail (https://github.com/opnsense/plugins/blob/master/security/tinc/src/opnsense/mvc/app/models/OPNsense/Tinc/Tinc.xml#L122https://github.com/opnsense/plugins/blob/master/security/tinc/src/opnsense/mvc/app/models/OPNsense/Tinc/Tinc.xml#L122)

Regards,
Antonio Huete

**Comment by tuxillo** [comment]
Has anyone had the chance to look at this?

**Comment by AdSchellevis** [comment]
@tuxillo not yet, too busy, if you prepare a pull request with something we can test it might gain a higher priority then it has at the moment.

**Comment by AdSchellevis** [comment]
on https://docs.opnsense.org is our development documentation, I think this model definition has a similar issue in it https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/models/OPNsense/Backup/NextcloudSettings.xml 

The `DependConstraint` should fix your dependency issue, I'm not sure if it will generate the correct config instantly, but it's worth a try.

**Comment by mimugmail** [comment]
https://docs.opnsense.org/develop.html

https://www.routerperformance.net/opnsense/

I can try to help next week in IRC

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
