### ISSUE TITLE
jquery.bootgrid.css uses /ui/css instead of local theme storage?

### ISSUE THREAD

**Issue by opnsenseuser** [opnsense/plugins#937]
When revising my templates I noticed that the jquery.bootgrid.css always accesses the / ui / css / folder and not the directory of the respective template even though the jquery.bootgrid.css is stored in the template directory. did i miss something?

wrong path?
![grafik](https://user-images.githubusercontent.com/34602360/47600758-80a74d00-d9c6-11e8-9b33-a6e19e954476.png)

template css folder:
![grafik](https://user-images.githubusercontent.com/34602360/47600766-961c7700-d9c6-11e8-8788-36133051f7dd.png)

regards rené

**Comment by fabianfrz** [comment]
looks like there are two different places where they are included:
```
src/opnsense/mvc/app/views/layouts/default.volt:        <link rel="stylesheet" type="text/css" href="{{ cache_safe(theme_file_or_default('/css/jquery.bootgrid.css', theme_name)) }}" />
src/www/widgets/widgets/monit.widget.php:<link rel="stylesheet" type="text/css" href="<?= cache_safe('/ui/css/jquery.bootgrid.css') ?>">
```

are you using the monit widget which looks like lit causes the issue?

**Comment by fabianfrz** [comment]
sure

**Comment by opnsenseuser** [comment]
👍

**Comment by fabianfrz** [comment]
@opnsenseuser path for this link is made.

**Comment by opnsenseuser** [comment]
@fabianfrz big big thx 🥇
