### ISSUE TITLE
rspamd: version 1.8.1 approval

### ISSUE THREAD

**Issue by fichtner** [opnsense/plugins#940]
via https://github.com/opnsense/ports/commit/1b117d2b485

(package later today)

**Comment by fichtner** [comment]
OpenSSL: https://pkg.opnsense.org/FreeBSD:11:amd64/snapshots/latest/All/rspamd-1.8.1_1.txz
LibreSSL: https://pkg.opnsense.org/FreeBSD:11:amd64/snapshots/latest/All/rspamd-1.8.1_1.txz

**Comment by mimugmail** [comment]
Looks good, but we should change templating for clamav.
This comes when restarting rspamd via rc:

CLAM_VIRUS [clamav]: Using attachments_only is deprecated. Please use scan_mime_parts = true instead

**Comment by fabianfrz** [comment]
looks like everything keeps running :+1:

**Comment by fichtner** [comment]
thanks to you both ❤️ 

@mimugmail will you post a PR?
