### ISSUE TITLE
FRR OSPF config does not allow setting key id for MD5 auth

### ISSUE THREAD

**Issue by brilthor** [opnsense/plugins#941]
```
OPNsense 18.7.1_3-amd64
FreeBSD 11.1-RELEASE-p12
OpenSSL 1.0.2o 27 Mar 2018
```

URL: /ui/quagga/ospf/index (adding or editing interface config)

expected behavior: when selecting MD5 as an authentication method, there should be a field for the key itself and one for the key ID

Current generated config assumes key id of "1":
```
interface ovpns4
  ip ospf network point-to-point
  ip ospf authentication message-digest
  ip ospf message-digest-key 1 md5 <redacted>
!

```

**Comment by fabianfrz** [comment]
@mimugmail do you want to solve it or should i do?

**Comment by mimugmail** [comment]
I think you'll fix it faster than me :)
