### ISSUE TITLE
NUT serial port and blaser_ser driver support

### ISSUE THREAD

**Issue by woooow1** [opnsense/plugins#947]
Hello, is possible to add driver to nut plugin? System is opnsense 18.7.6
I make connection to my ups, after edit nut config files.
Here is status from diagnostic menu:

battery.charge: 100
battery.voltage: 14.00
battery.voltage.high: 13.00
battery.voltage.low: 10.40
battery.voltage.nominal: 12.0
device.mfr: 
device.model: 
device.type: ups
driver.name: blazer_ser
driver.parameter.pollinterval: 2
driver.parameter.port: /dev/ttyu1
driver.parameter.synchronous: no
driver.version: 2.7.4
driver.version.internal: 1.57
input.current.nominal: 0.0
input.frequency: 50.0
input.frequency.nominal: 50
input.voltage: 227.0
input.voltage.fault: 140.0
input.voltage.nominal: 220
output.voltage: 226.5
ups.beeper.status: enabled
ups.delay.shutdown: 30
ups.delay.start: 180
ups.firmware: TR00071G
ups.load: 7
ups.mfr: 
ups.model: 
ups.status: OL
ups.temperature: 30.0
ups.type: offline / line interactive

After reboot, connection is lost! I use os-nut plugin, installed from system->firmware->plugins!
How to make blaser_ser driver work after reboot? From gui i see only usbhid-driver.
I think, that os-nut plugin rewrite config files...

here is my working config files:

nut.conf
MODE=standalone

ups.conf
user=root ->> without this line driver not start, maybe permissions issue???
[ups]
driver=blazer_ser
port=/dev/ttyu1 

upsd.conf
LISTEN 127.0.0.1
LISTEN ::1

upsd.users
[admin]
password=Password
actions=set
instcmds=all
[monuser]
password=Password
upsmon master

upsmon.conf
MONITOR ups 1 monuser Password master
SHUTDOWNCMD "/usr/local/etc/rc.halt"
POWERDOWNFLAG /etc/killpower

**Comment by mimugmail** [comment]
os-nut-devel already includes blazer_usb, I'll add _ser with next release

**Comment by woooow1** [comment]
Thanks  for reply!
Today i have litle time to play with setting, and succsessfuly add options for blaser_ser in menu. Now config files are writing right values for me.
![1](https://user-images.githubusercontent.com/43699588/47853699-38ce5e80-dde8-11e8-8515-00b92ef30f7b.jpg)

But now i have issues with permissions. Is hardcoded somewhere, but im not able to find it.

nut not running? (check /var/db/nut/upsd.pid).
Network UPS Tools - UPS driver controller 2.7.4
Network UPS Tools - Megatec/Q1 protocol serial driver 1.57 (2.7.4)
kill: No such process
writepid: fopen /var/db/nut/blazer_ser-ups.pid: Permission denied

Unable to open /dev/ttyu1: Permission denied

  Current user id: uucp (66)
Serial port owner: root (0)
Serial port group: wheel (0)
     Mode of port: 0600

When change permissions driver start to work, but after reboot, again same log.
