### ISSUE TITLE
add pkg-descr for all plugins

### ISSUE THREAD

**Issue by fichtner** [opnsense/plugins#95]
- [x] devel/debug
- [x] devel/helloworld
- [x] net/ftp-proxy
- [x] net/haproxy
- [x] net/igmp-proxy
- [x] net/l2tp
- [x] net/pppoe
- [x] net/pptp
- [X] net/quagga
- [x] net/relayd
- [x] net/upnp
- [x] net/wol
- [X] net-mgmt/snmp
- [x] sysutils/boot-delay
- [x] sysutils/monit
- [x] sysutils/smart
- [x] sysutils/vmware
- [x] sysutils/xen
- [x] security/acme-client
- [x] security/intrusion-detection-content-pt-open
- [x] security/tinc
- [x] www/web-proxy-sso

Edit (Fabian): Typo, Add checkboxes

**Comment by fabianfrz** [comment]
@fichtner I created one for net-mgmt/snmp in #98 but I don't know most of those plugins as I have never used them.

**Comment by fichtner** [comment]
We should reuse FreBSD's pkg-descr files where we can as a base: https://github.com/opnsense/ports/blob/master/net/quagga/pkg-descr

**Comment by fabianfrz** [comment]
@fichtner the one for quagga looks good. Can it be copied?

**Comment by fichtner** [comment]
@fabianfrz it was copied from here http://www.nongnu.org/quagga/ so I would say yes....

**Comment by fichtner** [comment]
thanks for the todo list :)
