### ISSUE TITLE
NTOPNG plugin needs way to set https

### ISSUE THREAD

**Issue by shawngiese** [opnsense/plugins#952]
You currently cannot use the ntopng plugin unless you 
1. enable ssh access to opnsense
2. enable https in the console config (/usr/local/etc/ntopng.conf)
3. remove the non-http config option
4. supply a certificate for https (/usr/local/share/ntopng/httpdocs/ssl)
5. restart ntopng

Would be nice if we could do it from the plugin interface.

**Comment by mimugmail** [comment]
I'll have a look next week ...

**Comment by mimugmail** [comment]
Ok, was able to reproduce the setup .. will try to add it the next days ...

**Comment by shawngiese** [comment]
yay, thanks!

//Shawn
