### ISSUE TITLE
smart-widget (use standard theme colors) ?

### ISSUE THREAD

**Issue by opnsenseuser** [opnsense/plugins#955]
would be of advantage again to use the standard template colors. like red and green!

![grafik](https://user-images.githubusercontent.com/34602360/47961872-677c4d00-e013-11e8-8477-99e2807ee511.png)

regards rené

**Comment by fabianfrz** [comment]
@opnsenseuser #957

**Comment by opnsenseuser** [comment]
can´t see any difference on OPNsense 19.1.b_154-amd64 or did i miss something?

![grafik](https://user-images.githubusercontent.com/34602360/48017427-8c191780-e12e-11e8-99d9-1e073b9b0f0b.png)

**Comment by fabianfrz** [comment]
probably you don't have the patch. It must be manually installed

**Comment by opnsenseuser** [comment]
sorry franco. no difference!

**Comment by fabianfrz** [comment]
`make install`

**Comment by opnsenseuser** [comment]
now i did all again!

1. opnsense-code core
2. opnsense-code plugins
3. cd /usr/core
4. make upgrade
5. make install
6. reboot

no changes at all. 

![grafik](https://user-images.githubusercontent.com/34602360/48020676-c7b7df80-e136-11e8-8dcd-2ef5b25b21e1.png)

**Comment by opnsenseuser** [comment]
i also remove the plugin and reinstalled it.
same -> no changes!

**Comment by fichtner** [comment]
René, you need to update the plugin ;)

    # cd /usr/plugins/sysutils/smart && make upgrade

**Comment by opnsenseuser** [comment]
👍 thx @fichtner 
👍 thx @fabianfrz
