### ISSUE TITLE
security/tor: Add support for configuring bridges (via ui/torrc custom entries)

### ISSUE THREAD

**Issue by vogelfreiheit** [opnsense/plugins#961]
I don't see any spot in the UI to add bridges. I'm running stable. This would be nice to have since bridges serve a rather important purpose and help increase the safety of a Tor circuit somewhat (besides the censorship "bypass").

**Comment by fabianfrz** [comment]
If you want to make your instance a bridge, there is already a checkbox in the relay area. Or are you talking about the client side config?

**Comment by fabianfrz** [comment]
depends on python 2.7 so no (https://www.freshports.org/security/py-obfsproxy-tor/) and I will also not add custom config blocks because they may break the config.

Another pluggable transport (if you know one) may be a better idea. I do not want to add any deprecated software to my plugins.

**Comment by vogelfreiheit** [comment]
I agree re py27.

Yes, you can use this:
https://github.com/Yawning/obfs4

It's actually the favored transport, as it uses djb's elligator, and is backwards compatible. elligator makes the entire curve indistinguishable from random data, both the exchange and ciphertext.

It depends on Go, and there seems to be an existent port:
https://www.freshports.org/security/obfs4proxy-tor/

**Comment by fabianfrz** [comment]
sounds good, @fichtner there is a FreeBSD port needed.

**Comment by mrPsycho** [comment]
hello, 
as far as i understand there are some changes... and ports updated.  
also i left message on forum: https://forum.opnsense.org/index.php?topic=26029.msg125548#msg125548

**Comment by mrPsycho** [comment]
atm using /usr/local/opnsense/service/templates/OPNsense/Tor/torrc to make stable config (till new upgrade)
