### ISSUE TITLE
net-mgmt/net-snmp: support SNMP Proxy

### ISSUE THREAD

**Issue by sbaerlocher** [opnsense/plugins#962]
Implementation of a SNMP proxy, so that different devices in the network can be monitored via SNMP from the outside via the OPNsense.

Alternatively it can also be a field where you can directly enter your own snmp config.

**Comment by mimugmail** [comment]
How does this work with net-snmp?

**Comment by mimugmail** [comment]
Do you mean something like this? 
https://blog.sys4.de/snmp-proxy-en.html

**Comment by sbaerlocher** [comment]
Yes that SNMP proxy. This should be possible with the net-snmp packages.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
