### ISSUE TITLE
www/nginx: Avoid duplicated HTTP response headers

### ISSUE THREAD

**Issue by jpawlowski** [opnsense/plugins#971]
HTTP response headers from upstream servers should be replaced by any other headers that NGINX adds by its own. It shall be avoided that duplicate headers would appear to the client browser.

For example, if I had enabled HSTS headers in the web ui and in NGINX as well, there are currently 2 headers which might not even have the same setting. The NGINX header shall take precedence in that case.

This can also be discovered by SSLlab.com security reports.

**Comment by fabianfrz** [comment]
There are probably some additional headers to suppress like X-Powered-By. It can be probably done using `proxy_hide_header` but I don't want to add it into 1.4, or at least not in the current pull request because it is already very large.

**Comment by jpawlowski** [comment]
Not critical for immediate remediation, but v1.5 would be nice. I believe sprints are anyway rather short so we're not talking about summer next year ;-)

**Comment by fabianfrz** [comment]
I had time to implement it - so it will probably be in 1.4

**Comment by fabianfrz** [comment]
pull request is ready: #983
