### ISSUE TITLE
www/nginx: Add support for IP address listening

### ISSUE THREAD

**Issue by jpawlowski** [opnsense/plugins#973]
Currently the NGINX HTTP servers listen on every IP address which makes it kind of problematic to properly distinguish between internal and external access.

It would be great to be able to explicitly define one or more listening addresses. Without it, the public and private DNS records are the only way to avoid easy access to something internal that should not be accessible from the outer world. Of course, if you'd know the FQDN, you can just easily add it to your local host file and boom, you will have access to that internal HTTP server also using the external IP address. Explicit listening would help to circumvent this.

It would be even greater if one could also select an interface so it will also work with dynamic IPs. Obviously that's not supported by NGINX itself but I think the logic to trigger a config update based on IP address changes on an interface is already part of the OPNsense core part so it should be possible to do that.

**Comment by jpawlowski** [comment]
ACLs are not the same than not listening on a specific IP/interface at all, are they?
There is a reason NGINX does not secure servers by just using ACLs alone.
In my opinion, ACLs are good to have for more granular control but should not be used to separate internal from external access in general.

**Comment by fabianfrz** [comment]
@jpawlowski the difference is that the server is not used for virtual host decision but the rest should make no difference. The problem is that you will also get the requests logged in the wrong virtual host when doing separation with the binding setting.

**Comment by jpawlowski** [comment]
What if you would like HAproxy to listen on 443 for external traffic and NGINX for internal traffic?
That's currently not possible to do.

**Comment by fabianfrz** [comment]
Why should that be done anyway? Both are reverse proxies which handle incoming connections for upstreams. Both target different users but can never run on the same IP:port. If you need that, you can proxy locally from one to the other but I don't see a reason to do this (and for running two load balancers at the same time on the same machine for the same traffic).

**Comment by fabianfrz** [comment]
one of the main reasons is that the plugin gets unstable because if it binds an IP that is not available anymore, the listen socket breaks and that also can be done using configured static IPs. In IPv6 the whole network may change for private users so the appliance has to assign a new /64 to the interface using SLAAC. Enterprises do get static prefixes but the plugin must run everywhere. The same is true for port options: Some are setting some values at OS level (https://linux.die.net/man/3/setsockopt) which in case of duplication or inconsistency prevent the daemon from starting (violates security goal nr. 1: availability).
The plugin can serve the OPNsense web interface as well if you kill the lighttpd and change a line in the config. It must be fun for users to undo the port settings in some servers in vim to get the web interface back because the webserver does not start due to a misconfiguration.

**Comment by jpawlowski** [comment]
We have the same situation with a lot of other services, e.g. Unbound. Can be circumvented programmatically.

**Comment by ibanezbass** [comment]
@fabianfrz This shouldn't be extremely difficult to implement. I probably could have this written up within a few hours. 

Why not just allow a variable that's tied to an interface? For example, listen on $WAN. That way, if the IP of that interface changes, it would change in the config as well. Even without the variable, users with DHCP addresses could simply use '::' or '0.0.0.0' to allow it to listen on any address that is available to them.

There are a lot of reasons why this needs to be available. I'm using this plugin in an enterprise scenario and by not allowing the user to select a listen interface, you are introducing unnecessary complications in security. It also prevents the ability to use HAProxy and Nginx simultaneously for the same port number. For example, I need Nginx to listen on 443 on IP A, but I need HAProxy to listen on 443 on IP B.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.

**Comment by jpawlowski** [comment]
Too bad ...
