### ISSUE TITLE
www/nginx: Allow custom listen parameters

### ISSUE THREAD

**Issue by jpawlowski** [opnsense/plugins#976]
Currently I can add custom listen parameters after the port.
That's totally fine but seems undocumented and therefore might even be unintended.

I would like to ensure that this functionality is being kept or otherwise better implemented in the UI.
In particular, this feature is very useful to define a single HTTP server instance for "default_server".

**Comment by fabianfrz** [comment]
How do you get this into the config? The Port settings should not support this.

**Comment by fabianfrz** [comment]
BTW: they may prevent the proxy from starting because some settings can only defined once (for example running IPv6 with IPv4 in the same listen directive)

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.

**Comment by jpawlowski** [comment]
This still sounds useful to me
