### ISSUE TITLE
mail/postfix: Fix label for Recipient Address

### ISSUE THREAD

**Issue by jpawlowski** [opnsense/plugins#977]
I believe it is a copy&paste error and the field in the screenshot should be labeled "Recipient Address" instead of "Sender Address".
![image](https://user-images.githubusercontent.com/75446/48358786-c9842480-e69b-11e8-81e5-35faeb4639ae.png)

**Comment by mimugmail** [comment]
Indeed, copy&paste 👍 

I fixed it in https://github.com/opnsense/plugins/pull/978

**Comment by fabianfrz** [comment]
@mimugmail I closed it because the pull request is already ready to merge.
