### ISSUE TITLE
mail/postfix: Add address rewriting

### ISSUE THREAD

**Issue by jpawlowski** [opnsense/plugins#979]
Besides forwarding emails to backend servers, it would be neat to allow several options for recipient address rewriting also.

**Comment by mimugmail** [comment]
@jpawlowski how about a new submenu called "Address Rewriting" and doing the usual magic in /usr/local/etc/postfix/virtual?

**Comment by jpawlowski** [comment]
That would be a good starting point :-)

However, there are quite some [options](http://www.postfix.org/ADDRESS_REWRITING_README.html):

1. Address rewriting when mail is received
   - Rewrite addresses to standard form
   - Canonical address mapping
   - Address masquerading
   - Automatic BCC recipients
   - Virtual aliasing **(this is what you are referring to)**
2. Address rewriting when mail is delivered
  - Resolve address to destination
  - Mail transport switch
  - Relocated users table

/usr/local/etc/postfix/virtual is only a small portion (but yes, probably most common use case).

**Comment by mimugmail** [comment]
This sounds like a complete mail solution :) 
Let me think about it .. it's some time ago I worked daily with Postfix.

Can you give me examples for 
- Canonical address mapping
- Address masquerading
- Resolve address to destination

**Comment by jpawlowski** [comment]
Well not a complete solution, but yes, Postfix is extremely powerful and is quite popular to run as edge server.

You got me on the same food as you are, my Postfix book on the shelf is like 10 years old and so is my last extensive setup of it. Just wanted to make sure we have a common understanding about the generic term of "Address Rewriting", it is not just the virtual aliasing. The UI and config structure should just be flexible enough to be extended by those other configuration items.

**Comment by mimugmail** [comment]
Submenu Address Rewriting, on the site multiple Tabs with Rewriting, Canonicals etc. :)
