### ISSUE TITLE
www/nginx: Missing option "None" for Basic Credentials List

### ISSUE THREAD

**Issue by jpawlowski** [opnsense/plugins#981]
I believe it is by mistake the selection list does not have a default value of "None" but would always show the first existing user list, even though I don't want to select one:

<img width="371" alt="image" src="https://user-images.githubusercontent.com/75446/48429061-aaa19300-e76c-11e8-94f3-f1c5c6568cb0.png">

**Comment by jpawlowski** [comment]
>  but you have to set up two settings to enable it anyway:

That's another abnormality I was about to open an issue ticket :-)
It's really not obvious which settings have a relationship. I actually had to look it up in the source code to find out how to use the option "(PHP) Router Script".
Should I put it into a dedicated issue?

**Comment by jpawlowski** [comment]
> From the model view, you should not have to set it

That might be true, but it is not obvious to the user and cannot be assumed just from the UI.

**Comment by fabianfrz** [comment]
The router script needs the value itself and enable PHP

**Comment by fichtner** [comment]
Hmm, Multiple is set, which avoids a spurious "None" value that you can select, because you can deselect all and since it's not required that should work fine?

**Comment by fichtner** [comment]
54fc763061a5 should take care of it:

    # opnsense-patch -c plugins 54fc763061a5

**Comment by fabianfrz** [comment]
@fichtner this should not be a multiple field, I'll fix it.

**Comment by fichtner** [comment]
okay, I'm pretty bad at split decisions lately :D

**Comment by fichtner** [comment]
ok, approved it.. 18.7.8 is about a week away.

**Comment by fabianfrz** [comment]
@fichtner please don't forget the core changes, without them, the plugin will not work. Especially the constraint is now moved over to core. If the JS things were missing, the view is not initialized which does not really harm anyone (only used in new features).
