### ISSUE TITLE
Feature Request: Route-Map match Prefix-List

### ISSUE THREAD

**Issue by elizandropacheco** [opnsense/plugins#985]
A function that I consider important and is non-existent in the interface, is the "match" in prefix-list as well. Not only in aspath-list.

This facilitates a lot and I consider it a fundamental resource to use when the complexity of the filters is very great.

The command in quagga or frr would be:

match ip address prefix-list PREFIXLIST-NAME

Or, that it was possible to set a custom match command (just as there is a pro set).

Tkz.

Elizandro Pacheco

**Comment by mimugmail** [comment]
Do you talk about BGP or OSPF?

**Comment by elizandropacheco** [comment]
BGP
