### ISSUE TITLE
Add plugin package for V2ray

### ISSUE THREAD

**Issue by mervynsword** [opnsense/plugins#988]
Hi,can you add package for V2ray on opnsense ?

V2ray is a set of tools to help people build an own privacy network over internet.It is safer than VPN in China.The project has earned 11147 stars on Github.

The homepage is [https://www.v2ray.com/en/](https://www.v2ray.com/en/)
And github [https://github.com/v2ray/v2ray-core](https://github.com/v2ray/v2ray-core)

I dont have a freebsd server now,and I am not good at using freebsd,so I havent test it on freebsd,sorry about that.

Thank you very much.

**Comment by junkboypaul** [comment]
https://github.com/v2ray/v2ray-core/releases seems to have freebsd32 & freebsd64 listed now

**Comment by fichtner** [comment]
It was added to FreeBSD now... It's go with all of its ups and down. If there are interested parties we can try to pull it into our binary packages as a start. Please let us know...

**Comment by sheiy** [comment]
Please pull it into the binary packages thanks

**Comment by RevNelson** [comment]
Yes, please pull this!

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.

**Comment by iWangJiaxiang** [comment]
Seems f720f8a commit has added v2ray package but I couldn't find it.

**Comment by mimugmail** [comment]
root@OPNsense:~ # pkg search v2ray
v2ray-4.33.0                   Platform for building proxies to bypass network restrictions

**Comment by ER-EPR** [comment]
how to use v2ray now？Is there a guide？

**Comment by fichtner** [comment]
https://forums.freebsd.org/threads/how-do-i-setup-v2ray.88534/
