### ISSUE TITLE
Ability to change OSPF default route metric

### ISSUE THREAD

**Issue by Jelloeater** [opnsense/plugins#989]
In PFsense we can edit the config file for OSPF Quagga by VTY or in the GUI.
It would be nice in OpnSense if we could change the OSPF default route metric in the GUI, for injecting a second fail-over router.

Ex:
```
router ospf
 ospf router-id 1.1.1.1
 default-information originate metric 8
```

**Comment by Jelloeater** [comment]
Thank you so much!
I never expected such a quick response, let alone merge request!

**Comment by Yamakasi** [comment]
Does this actually work at the moment ? I don't see any change in my traffic when I change them in an order it should.

**Comment by Yamakasi** [comment]
> 
> 
> Does this actually work at the moment ? I don't see any change in my traffic when I change them in an order it should.

Yes it does :)

**Comment by Yamakasi** [comment]
It seems it doesn't add anything at all in usage... bug ?

**Comment by mimugmail** [comment]
How does ospfd.conf look when you set it?

**Comment by Yamakasi** [comment]
> 
> 
> How does ospfd.conf look when you set it?

Hi sorry for the delay, I should check but already created a more flexible design.

As discussed you were going to add something for CARP situations ? I still don't agree with the way you think OSPF works with CARP. With CARP you better advertise the CARP IP as default gateway rather then the OSPF IP as you wanted to do so.

**Comment by mimugmail** [comment]
When you tell me how to advertise a carp ip with FRR I'll add it. Until now nobody was able to find this out.

**Comment by Yamakasi** [comment]
> 
> 
> When you tell me how to advertise a carp ip with FRR I'll add it. Until now nobody was able to find this out.

I already told you, I don't have a backlog but can check maybe how I did it. It's pretty simple at the end but I need to dive into it again! I will do asap and let you know.

**Comment by wizard-010** [comment]
> > When you tell me how to advertise a carp ip with FRR I'll add it. Until now nobody was able to find this out.
> 
> I already told you, I don't have a backlog but can check maybe how I did it. It's pretty simple at the end but I need to dive into it again! I will do asap and let you know.

so what is the update? been 5 years

**Comment by fichtner** [comment]
> so what is the update? been 5 years

Nobody bothered to answer https://github.com/opnsense/plugins/issues/989#issuecomment-492271536 is what it is.
