### ISSUE TITLE
security/letsencrypt: Change key length after initial generation

### ISSUE THREAD

**Issue by jpawlowski** [opnsense/plugins#990]
For certificates that were already requested/issued, the private key is generated once based on key length set in the configuration. It does not make sense to be able to change that setting afterwards unless the key is replaced by a new one. That's actually quite difficult because that existing certificate might be in use already and will break things until the new CSR was signed successfully.

I suggest that once a key was generated, the key length cannot be changed anymore and therefore the field should be set to read-only in the configuration window. In case somebody would like to change the key length or type (e.g. RSA->EC), users shall create a new key pair in parallel. Although it would be more convenient for users to handle such change in the background (e.g. it would avoid to re-configure services using that particular cert already), I think it is still better to have a clear separation. Would also be the easier CR to handle ;-)

**Comment by fraenki** [comment]
> In case somebody would like to change the key length or type (e.g. RSA->EC), users shall create a new key pair in parallel.

I don't like this part of the proposal. The whole point of the GUI should be to avoid such things.

However, your report is valid, because things might break. Maybe we should add a new button to allow a user to recreate a key, and try to prevent key changes in all other cases.

**Comment by jpawlowski** [comment]
> I don't like this part of the proposal. The whole point of the GUI should be to avoid such things.

I agree, that'd be ideal. Wanted to describe a minimum fix which might be less complex to implement.

**Comment by DonMcCoy** [comment]
I already had some problems in those cases, I think something, as you mentioned, is really useful.
1. After the certificate is successfully created the key field is greyed out with a description of "a key for this certificate is already created"
2. a checkbox with "Generate new key" will appear.
3. Once the checkbox is selected the key length box will be available again.

@jpawlowski @fraenki if you think such a solution will address this problem, I can work on it the next days.

**Comment by jpawlowski** [comment]
I'd be happy so see such improvement.
The changes you described @DonMcCoy might be incomplete though. The existing private key and its public certificate need to be kept until the new certificate was successfully signed. That the slightly tricky part (not impossible, but will require some work).

**Comment by fraenki** [comment]
The next release will have a new button to remove the private key. This will in fact reset the whole certificate, because the certificate is pretty useless without the matching private key. But of course the certificate and key can still be found in `System: Trust: Certificates`.
