### ISSUE TITLE
www/nginx: Error parsing header X-XSS-Protection

### ISSUE THREAD

**Issue by jpawlowski** [opnsense/plugins#991]
The security header being added has an invalid format, leading to misbehaviours of the browser:
![image](https://user-images.githubusercontent.com/75446/48645070-d29b2b80-e9e4-11e8-80c0-b5c93539f467.png)

In that particular case, it is not possible to press the button "Issue/Renew Certificate Now" to re-issue Let'sEncrypt certificates.

**Comment by fabianfrz** [comment]
This is what the nginx plugin produces on my end:

```
HTTP/1.1 200 OK
Server: nginx
Date: Sat, 17 Nov 2018 07:29:56 GMT
Content-Type: text/html; charset=utf-8
Connection: keep-alive
Referrer-Policy: no-referrer
X-XSS-Protection: 1; mode=block
Strict-Transport-Security: 1234; includeSubDomains
Content-Security-Policy-Report-Only: …
```

As you can see, the header is set correctly by the plugin. It may be an upstream issue.

**Comment by fabianfrz** [comment]
I misread the screenshot, it has the header content twice. >= 1.4 will not pass upstream headers so this should not happen anymore.

**Comment by jpawlowski** [comment]
Did not check on it, apologies.
