### ISSUE TITLE
www/nginx: Integrate with core/system/trust

### ISSUE THREAD

**Issue by jpawlowski** [opnsense/plugins#992]
Not sure it belongs here or into core but system/trust shall show up use of a particular certificate in NGINX and block to delete it until it was de-configured from NGINX.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
